// ══════════════════════════════════════════════════════════════════════
// bb/script/lines/bond.js — friendships, couples and feuds (Phase 6)
// ══════════════════════════════════════════════════════════════════════
//
// The words for bb-events/bonds.js.
//
//   bond.kiss       a and b, a showmance, kiss for the first time (bedroom)   scene
//   bond.quiet      a and b, a showmance, talk late (bedroom)                 scene
//   bond.friends    a and b, close friends; c may be watching                 scene
//   bond.bad-day    a is having a bad day; b, a friend, notices (bedroom)     scene
//   bond.cold-war   a and b are not speaking                                  scene
//   bond.petty      a needles b in the kitchen                                scene
//   bond.apology    a apologises to b                                         accepted | refused

export default {
  'bond.kiss.scene': [
    { id: 'bk.1', turns: [{ beat: '{a} and {b} lie in the dark, talking. Then {a} kisses {b}.' }, { by: 'b', say: "Finally." }, { by: 'a', say: "Shut up." }] },
    { id: 'bk.2', turns: [{ by: 'b', say: "What?" }, { by: 'a', say: "Nothing. Come here." }, { beat: '{a} kisses {b}.' }] },
    { id: 'bk.3', turns: [{ by: 'a', dr: "I kissed {b}. It wasn't strategy. I just really wanted to." }] },
    { id: 'bk.4', turns: [{ beat: '{a} kisses {b}.' }, { by: 'b', say: "Did that just happen?" }, { by: 'a', say: "I think so." }, { by: 'b', say: "Good." }] },
    { id: 'bk.5', turns: [{ beat: '{a} kisses {b} in the middle of a sentence.' }, { by: 'b', say: "I was talking!" }, { by: 'a', say: "I know." }] },
    { id: 'bk.6', turns: [{ by: 'b', dr: "Everyone in here is playing a game. That kiss wasn't part of it." }] },
    { id: 'bk.7', turns: [{ beat: '{a} kisses {b}.' }, { by: 'a', say: "The cameras saw that." }, { by: 'b', say: "Let them." }] },
  ],
  // a and b were together before the show (kinship: married, engaged, partners, dating)
  'bond.kiss.couple': [
    { id: 'bkc.1', turns: [{ beat: 'The lights are off. {a} checks the door, then kisses {b}.' }, { by: 'b', say: "Somebody's going to see." }, { by: 'a', say: "I don't care. I've missed you." }] },
    { id: 'bkc.2', turns: [{ by: 'a', dr: "{b} and I came in here together. Keeping my hands off {b.obj} all day is the hardest competition in this house." }] },
    { id: 'bkc.3', turns: [{ by: 'b', say: "We said we'd keep it quiet in here." }, { by: 'a', say: "We are. It's just us." }, { beat: '{a} kisses {b}.' }] },
    { id: 'bkc.4', turns: [{ beat: '{a} kisses {b} in the middle of a sentence.' }, { by: 'b', say: "I was talking!" }, { by: 'a', say: "You can talk later. I've had to pretend I barely know you all day." }] },
    { id: 'bkc.5', turns: [{ by: 'b', dr: "Everyone thinks {a} and I just met. Pretending I'm not in love with {a.obj} is the hardest part of this game." }] },
    { id: 'bkc.6', turns: [{ beat: "Everyone else is asleep. {b} slides over to {a}'s bed." }, { by: 'a', say: "We agreed." }, { by: 'b', say: "Five minutes." }, { beat: '{a} kisses {b}.' }] },
  ],
  'bond.quiet.scene': [
    { id: 'bq2.1', turns: [{ by: 'b', say: "What's the first thing you'll do when this is over?" }, { by: 'a', say: "Sleep in a bed without a camera over it." }, { by: 'b', say: "And then?" }, { by: 'a', say: "Then I'll call you." }] },
    { id: 'bq2.2', turns: [{ by: 'a', say: "Are you asleep?" }, { by: 'b', say: "Nearly." }, { by: 'a', say: "Okay. Night." }, { by: 'b', say: "Night." }, { beat: 'Neither of them falls asleep for another hour.' }] },
    { id: 'bq2.3', turns: [{ by: 'a', say: "Tell me about home." }, { by: 'b', say: "What about it?" }, { by: 'a', say: "Anything. I just like hearing you talk." }] },
    { id: 'bq2.4', turns: [{ by: 'b', dr: "For an hour last night, it wasn't a game. It was just me and {a}, talking." }] },
    { id: 'bq2.5', turns: [{ by: 'a', say: "I haven't thought about the game once tonight." }, { by: 'b', say: "Me neither. Don't start now." }] },
    { id: 'bq2.6', turns: [{ by: 'a', say: "Can I ask you something real?" }, { by: 'b', say: "Always." }, { by: 'a', say: "Do you think we'd have met, out there?" }, { by: 'b', say: "I'd like to think so." }] },
    { id: 'bq2.7', turns: [{ by: 'a', dr: "{b} and I talked about everything except the game. It was the best night I've had in here." }] },
    { id: 'bq2.8', turns: [{ by: 'a', say: "I'm glad it was you I met in here." }, { by: 'b', say: "Me too." }] },
    { id: 'bq2.9', turns: [{ by: 'b', say: "Do you ever worry this won't last outside?" }, { by: 'a', say: "Sometimes." }, { by: 'b', say: "Me too." }, { by: 'a', say: "Let's worry about it outside, then." }] },
    { id: 'bq2.10', turns: [{ by: 'a', say: "What are you thinking about?" }, { by: 'b', say: "Nothing. That's the nice part." }] },
    { id: 'bq2.11', turns: [{ beat: '{a} and {b} share a blanket and whisper so they don\'t wake anyone.' }, { by: 'b', say: "Shh. You'll wake everyone." }, { by: 'a', say: "You shh." }] },
    { id: 'bq2.12', turns: [{ by: 'b', dr: "I came in here to play a game. I didn't expect to meet {a}." }] },
    { id: 'bq2.13', turns: [{ by: 'a', say: "If one of us goes home..." }, { by: 'b', say: "Don't. Not tonight." }] },
    { id: 'bq2.14', turns: [{ by: 'a', dr: "This house is a lot less lonely with {b} in it." }] },
  ],
  'bond.friends.scene': [
    { id: 'bf.1', turns: [{ by: 'a', say: "Pineapple." }, { beat: '{b} bursts out laughing. Nobody else gets the joke.' }] },
    { id: 'bf.2', turns: [{ by: 'a', say: "Plate for you." }, { by: 'b', say: "I didn't ask." }, { by: 'a', say: "I know." }] },
    { id: 'bf.3', turns: [{ by: 'b', dr: "{a} and I aren't in an alliance. {a} is just my person in here." }] },
    { id: 'bf.4', turns: [{ by: 'a', dr: "{b} and I don't have a deal. We've never needed one." }] },
    { id: 'bf.5', when: { third: true }, turns: [{ by: 'c', dr: "{a} and {b} say they're not working together. Ask one of them to vote the other out and see what happens." }] },
    { id: 'bf.6', when: { third: true }, turns: [{ by: 'a', say: "Plate for you." }, { by: 'b', say: "You're the best." }, { by: 'c', dr: "{a} made {b} a plate without even being asked. I'm keeping an eye on those two." }] },
    { id: 'bf.7', turns: [{ by: 'b', say: "Bad day?" }, { by: 'a', say: "How did you know?" }, { by: 'b', say: "You're pulling at your sleeve again." }] },
    { id: 'bf.8', turns: [{ by: 'a', say: "If I win HOH, you know you're safe, right?" }, { by: 'b', say: "We said no game talk." }, { by: 'a', say: "That's not game talk. It's just true." }] },
    { id: 'bf.9', turns: [{ by: 'a', say: "Have you eaten?" }, { by: 'b', say: "No." }, { by: 'a', say: "Sit down. I'll make you something." }] },
    { id: 'bf.10', turns: [{ by: 'b', dr: "If {a} went home, I'd be lost in here. Simple as that." }] },
    { id: 'bf.11', turns: [{ by: 'a', say: "You look tired." }, { by: 'b', say: "I am tired." }, { by: 'a', say: "Go and have a nap. I'll wake you for dinner." }] },
    { id: 'bf.12', turns: [{ by: 'a', say: "Remember the first night?" }, { by: 'b', say: "When you couldn't work the shower?" }, { by: 'a', say: "We don't talk about that." }] },
    { id: 'bf.13', turns: [{ by: 'b', say: "You always save me a seat." }, { by: 'a', say: "Somebody has to." }] },
    { id: 'bf.14', when: { third: true }, turns: [{ by: 'c', dr: "{a} and {b} are always together. If I go after one of them, I have to deal with both." }] },
  ],
  'bond.bad-day.scene': [
    { id: 'bd.1', turns: [{ by: 'b', say: "Are you okay?" }, { by: 'a', say: "Not really." }, { by: 'b', say: "Want to talk about it?" }, { by: 'a', say: "Not really." }, { by: 'b', say: "Okay. I'll just sit here, then." }] },
    { id: 'bd.2', turns: [{ by: 'b', say: "This isn't about the game, is it?" }, { by: 'a', say: "No. I just miss home." }, { by: 'b', say: "Yeah. Me too." }] },
    { id: 'bd.3', turns: [{ beat: '{b} finds {a} sitting alone and sits down without a word.' }, { by: 'a', dr: "{b} didn't ask what was wrong. {b} just sat with me. It helped." }] },
    { id: 'bd.4', turns: [{ by: 'a', say: "Sorry. I'm terrible company today." }, { by: 'b', say: "You're fine. Everyone has bad days in here." }] },
    { id: 'bd.5', turns: [{ by: 'a', dr: "You're not allowed to be sad out loud in here. {b} let me be sad anyway." }] },
    { id: 'bd.6', turns: [{ by: 'b', say: "You skipped lunch." }, { by: 'a', say: "I wasn't hungry." }, { by: 'b', say: "I made you a sandwich anyway." }] },
    { id: 'bd.7', turns: [{ by: 'b', dr: "{a} has been quiet all day. I waited until we were on our own to ask." }] },
    { id: 'bd.8', turns: [{ by: 'b', say: "Do you want a hug?" }, { by: 'a', say: "...Yeah." }] },
    { id: 'bd.9', turns: [{ by: 'a', say: "I just want to go home today." }, { by: 'b', say: "I know. It'll pass. It always does." }] },
    { id: 'bd.10', turns: [{ by: 'b', say: "Come for a walk with me." }, { by: 'a', say: "I don't feel like it." }, { by: 'b', say: "That's why we're going." }] },
    { id: 'bd.11', turns: [{ by: 'a', dr: "I cried in the bathroom today. {b} was the only one who noticed." }] },
    { id: 'bd.12', turns: [{ by: 'b', say: "Is it the game, or is it home?" }, { by: 'a', say: "Both." }, { by: 'b', say: "Okay. Start with whichever one's worse." }] },
    { id: 'bd.13', turns: [{ by: 'a', say: "I don't want to talk." }, { by: 'b', say: "Then we won't talk. I'll sit here anyway." }] },
    { id: 'bd.14', turns: [{ by: 'b', dr: "{a} isn't okay today. Nobody else noticed. I did." }] },
  ],
  'bond.cold-war.scene': [
    { id: 'bw.1', turns: [{ beat: '{b} walks into the room. {a} gets up and walks out.' }, { by: 'a', dr: "I'm not being rude. I'm just not talking to {b}." }] },
    { id: 'bw.2', turns: [{ by: 'b', dr: "{a} and I haven't spoken all day. That takes effort in a house this small." }] },
    { id: 'bw.3', turns: [{ by: 'a', say: "Can someone pass the plates?" }, { beat: '{b} passes them without looking up.' }] },
    { id: 'bw.4', turns: [{ by: 'a', dr: "I've started timing my showers so I don't run into {b}." }] },
    { id: 'bw.5', turns: [{ by: 'b', say: "Morning." }, { beat: '{a} says nothing.' }, { by: 'b', dr: "So we're still doing this." }] },
    { id: 'bw.6', turns: [{ by: 'a', dr: "{b} and I don't argue any more. We just don't speak. It's easier." }] },
    { id: 'bw.7', turns: [{ beat: '{a} and {b} sit at opposite ends of the room all evening.' }, { by: 'b', dr: "Everyone keeps looking at us. Let them." }] },
    { id: 'bw.8', turns: [{ by: 'a', say: "Has anyone seen the remote?" }, { beat: '{b} is holding it. Neither of them says a word.' }] },
    { id: 'bw.9', turns: [{ by: 'b', dr: "I'll talk to {a} when {a} apologises. So probably never." }] },
    { id: 'bw.10', turns: [{ beat: '{a} and {b} reach for the same mug. Both let go at once.' }, { by: 'a', dr: "I'll drink out of a bowl before I touch anything {b} has touched." }] },
    { id: 'bw.11', turns: [{ by: 'a', dr: "Other people have to pass messages between me and {b}. It's ridiculous. I'm not stopping." }] },
    { id: 'bw.12', turns: [{ by: 'a', dr: "{b} said good morning to everyone except me. Fine. Two can play that game." }] },
    { id: 'bw.13', turns: [{ by: 'b', dr: "I don't hate {a}. I just have nothing to say to {a}." }] },
    { id: 'bw.14', turns: [{ by: 'a', say: "Excuse me." }, { beat: '{b} moves out of the way without looking up.' }, { by: 'a', dr: "That's the most we've said to each other all week." }] },
  ],
  'bond.petty.scene': [
    { id: 'bp.1', turns: [{ by: 'a', say: "Who left this pan here?" }, { by: 'b', say: "Does it matter?" }, { by: 'a', say: "It matters to whoever has to wash it." }] },
    { id: 'bp.2', turns: [{ by: 'a', say: "Did you finish the cereal?" }, { by: 'b', say: "There was barely any left." }, { by: 'a', say: "There was enough for me." }] },
    { id: 'bp.3', turns: [{ by: 'b', dr: "{a} has been doing impressions of me behind my back. I heard about it within the hour." }] },
    { id: 'bp.4', turns: [{ by: 'a', say: "Oh, sorry. Was that yours?" }, { by: 'b', say: "You know it was." }] },
    { id: 'bp.5', turns: [{ by: 'a', say: "Is this supposed to be funny?" }, { by: 'b', say: "Is what?" }, { by: 'a', say: "The dirty pan. Next to my plate." }, { by: 'b', say: "I didn't even see it." }] },
    { id: 'bp.6', turns: [{ by: 'a', dr: "It's not about the pan. It's never about the pan. It's about {b}." }] },
    { id: 'bp.7', turns: [{ by: 'b', say: "Can you not slam things?" }, { by: 'a', say: "I'm not slamming anything." }, { beat: '{a} puts a cup down very hard.' }] },
    { id: 'bp.8', turns: [{ by: 'a', say: "Someone used my towel." }, { by: 'b', say: "It was on the floor." }, { by: 'a', say: "It was drying!" }] },
    { id: 'bp.9', turns: [{ by: 'b', dr: "{a} has been on at me all week. Today it's the washing-up." }] },
    { id: 'bp.10', turns: [{ by: 'a', say: "Nice of you to finally wash a cup." }, { by: 'b', say: "Nice of you to notice." }] },
    { id: 'bp.11', turns: [{ by: 'a', say: "That's my seat." }, { by: 'b', say: "It's a chair." }, { by: 'a', say: "It's my chair." }] },
    { id: 'bp.12', turns: [{ by: 'a', say: "You left the lid off the peanut butter. Again." }, { by: 'b', say: "It's peanut butter, not a crime." }] },
    { id: 'bp.13', turns: [{ by: 'b', say: "Are we really fighting about spoons?" }, { by: 'a', say: "We're not fighting. I'm just saying." }, { by: 'b', say: "About spoons." }] },
    { id: 'bp.14', turns: [{ by: 'a', dr: "Everything {b} does annoys me. The way {b} chews. The way {b} breathes. All of it." }] },
  ],
  'bond.apology.accepted': [
    { id: 'ba.a1', turns: [{ by: 'a', say: "I'm sorry. No excuses. I was wrong." }, { by: 'b', say: "...Okay. Thank you." }] },
    { id: 'ba.a2', turns: [{ by: 'a', say: "I want to say sorry. Properly." }, { by: 'b', say: "I didn't expect that." }, { by: 'a', say: "I mean it." }, { by: 'b', say: "Okay. Let's start again." }] },
    { id: 'ba.a3', turns: [{ by: 'b', dr: "{a} actually apologised. No 'but'. That's why I accepted it." }] },
    { id: 'ba.a4', turns: [{ by: 'a', say: "I'm sorry. I know it doesn't fix everything." }, { by: 'b', say: "No. But it helps." }] },
    { id: 'ba.a5', turns: [{ by: 'a', say: "You had every right to be upset." }, { by: 'b', say: "I did." }, { by: 'a', say: "I'm sorry." }, { by: 'b', say: "Thank you. Truce?" }, { by: 'a', say: "Truce." }] },
    { id: 'ba.a6', turns: [{ by: 'a', dr: "I said sorry to {b}. It was easier than staying angry." }] },
    { id: 'ba.a7', turns: [{ by: 'a', say: "I'm sorry for how I acted." }, { by: 'b', say: "Okay. I accept it." }, { by: 'a', say: "Really?" }, { by: 'b', say: "Don't make me change my mind." }] },
    { id: 'ba.a8', turns: [{ by: 'a', say: "I'm sorry. I mean it." }, { by: 'b', say: "I can tell. Thank you." }] },
    { id: 'ba.a9', turns: [{ by: 'b', dr: "I didn't want to forgive {a}. But {a} meant it. You can tell when someone means it." }] },
  ],
  'bond.apology.refused': [
    { id: 'ba.r1', turns: [{ by: 'a', say: "I'm sorry." }, { by: 'b', say: "Okay." }, { by: 'a', dr: "{b} said okay. {b} didn't mean it." }] },
    { id: 'ba.r2', turns: [{ by: 'a', say: "Can we talk?" }, { by: 'b', say: "I'd rather we didn't." }, { by: 'a', say: "I just want to apologise." }, { by: 'b', say: "I'd still rather we didn't." }] },
    { id: 'ba.r3', turns: [{ by: 'a', say: "Can we put the fight behind us?" }, { by: 'b', say: "You still think the problem was the fight." }] },
    { id: 'ba.r4', turns: [{ by: 'a', say: "I'm sorry about the argument." }, { by: 'b', say: "Just the argument?" }, { by: 'a', say: "...What else?" }, { by: 'b', say: "That's what I thought." }] },
    { id: 'ba.r5', turns: [{ by: 'b', dr: "{a} apologised. For the wrong thing. That made it worse." }] },
    { id: 'ba.r6', turns: [{ by: 'a', dr: "I tried to say sorry to {b}. It didn't work. Now it's worse than before." }] },
    { id: 'ba.r7', turns: [{ by: 'a', say: "I'm sorry." }, { by: 'b', say: "You're only sorry because people saw." }, { by: 'a', say: "That's not true." }, { by: 'b', say: "Then why now?" }] },
    { id: 'ba.r8', turns: [{ by: 'a', say: "Can I say something?" }, { by: 'b', say: "If it's sorry, save it." }] },
    { id: 'ba.r9', turns: [{ by: 'a', say: "I'm trying here." }, { by: 'b', say: "I know. It's not enough yet." }] },
    { id: 'ba.r10', turns: [{ by: 'b', dr: "{a} wants things to go back to normal. I don't want normal with {a}." }] },
    { id: 'ba.r11', turns: [{ by: 'a', say: "I'm sorry. I didn't mean it like that." }, { by: 'b', say: "Then you shouldn't have said it like that." }] },
    { id: 'ba.r12', turns: [{ by: 'a', dr: "I swallowed my pride and said sorry. {b} looked straight through me." }] },
  ],
};
