// ══════════════════════════════════════════════════════════════════════
// bb/script/lines/campaign.js — a nominee works a voter (Phase 6)
// ══════════════════════════════════════════════════════════════════════
//
// The campaign days, one conversation per voter. A scene is two picks put
// together: the CASE the nominee makes (keyed on the argument the engine
// chose, _read.js campaignCase) and the voter's REPLY (keyed on what the
// pitch did to the count). a is the nominee, b the voter.
//
//   campaign.case.<kind>   deal | hunted | pair | alliance | comps | beatable | clean | friend | count
//       {target} the other nominee; {partner} the other half of their pair (pair);
//       {alliance} the other nominee's group (alliance); {theirComps} {myComps} as words (comps)
//   campaign.reply.<end>   receptive | unmoved | worn (the second visit that finally lands)

export default {
  // ── the case ──────────────────────────────────────────────────────
  'campaign.case.deal': [
    { id: 'cc.d1', turns: [{ by: 'a', say: "We shook on something. I haven't forgotten it, and I don't think you have either." }, { by: 'a', say: "Keep me, and it's still a plan. Send me home, and you're doing the rest of this on your own." }] },
    { id: 'cc.d2', turns: [{ by: 'a', say: "You and me had a deal. That deal doesn't work with me in the jury house." }] },
    { id: 'cc.d3', turns: [{ by: 'a', say: "I'm not going to remind you what we promised each other. I'm just going to ask if it still counts." }] },
    { id: 'cc.d4', turns: [{ by: 'a', say: "If I go, our deal goes with me. Is that what you want?" }] },
    { id: 'cc.d5', turns: [{ by: 'a', say: "I kept my side every single week. This is the week I need you to keep yours." }] },
    { id: 'cc.d6', turns: [{ by: 'a', say: "We said the end, together. Please don't make this the end." }] },
  ],
  'campaign.case.hunted': [
    { id: 'cc.h1', turns: [{ by: 'a', say: "Every time you leave the room, {target} brings up your name. I'm not the one you need to worry about." }] },
    { id: 'cc.h2', turns: [{ by: 'a', say: "You know {target} wants you out, right? Next week, if {target} wins HOH, it's you." }] },
    { id: 'cc.h3', turns: [{ by: 'a', say: "Keep {target} and you're keeping the person who's coming for you. I'm not coming for you. Simple." }] },
    { id: 'cc.h4', turns: [{ by: 'a', say: "Ask yourself who {target} has been talking to about you. Then ask yourself why." }] },
    { id: 'cc.h5', turns: [{ by: 'a', say: "{target} has your name ready. I've heard it. I'm not saying it to scare you. I'm saying it because it's true." }] },
    { id: 'cc.h6', turns: [{ by: 'a', say: "I'm the safer vote for you. {target} isn't, and you know it." }] },
    { id: 'cc.h7', turns: [{ by: 'a', say: "Want to know who {target} wants out next? It's you. I'd rather you heard it from me." }] },
    { id: 'cc.h8', turns: [{ by: 'a', say: "{target} isn't your friend. {target} is your next HOH problem." }] },
    { id: 'cc.h9', turns: [{ by: 'a', say: "Vote me out and you're handing {target} a free shot at you next week." }] },
  ],
  'campaign.case.pair': [
    { id: 'cc.p1', turns: [{ by: 'a', say: "{target} and {partner} are a pair. Keep {target}, and you're the third person in a two-person plan." }] },
    { id: 'cc.p2', turns: [{ by: 'a', say: "Have you watched {target} and {partner} lately? They're a final two. You're not in it." }] },
    { id: 'cc.p3', turns: [{ by: 'a', say: "If {target} stays, {target} and {partner} have the numbers to run this house. I'm the only vote that breaks them up." }] },
    { id: 'cc.p4', turns: [{ by: 'a', say: "Count it. {target}, {partner}, and then you. You're the spare." }] },
    { id: 'cc.p5', turns: [{ by: 'a', say: "Split {target} and {partner} now, while you can. Next week it'll be too late." }] },
    { id: 'cc.p6', turns: [{ by: 'a', say: "{target} and {partner} never vote against each other. Not once. Think about what that means for you." }] },
    { id: 'cc.p7', turns: [{ by: 'a', say: "You'll be the one {target} and {partner} send home together. Unless you stop it now." }] },
    { id: 'cc.p8', turns: [{ by: 'a', say: "I'm the only thing standing between {target}, {partner} and an easy run to the end." }] },
    { id: 'cc.p9', turns: [{ by: 'a', say: "Keep {target}, and {partner} gets a free partner all the way to the end. Is that what you want?" }] },
  ],
  'campaign.case.alliance': [
    { id: 'cc.a1', turns: [{ by: 'a', say: "{target} is in {alliance}, and you're not. Keep {target}, and you're voting for a group with no seat for you." }] },
    { id: 'cc.a2', turns: [{ by: 'a', say: "Every vote you give {target} is a vote for {alliance}. Are you in {alliance}? No. So why help them?" }] },
    { id: 'cc.a3', turns: [{ by: 'a', say: "{alliance} needs {target} to stay. That should tell you everything about who to vote for." }] },
    { id: 'cc.a4', turns: [{ by: 'a', say: "If {alliance} keeps its numbers, you're picked off one week at a time. Starting soon." }] },
    { id: 'cc.a5', turns: [{ by: 'a', say: "Keep me and {alliance} is down a vote. Keep {target} and they're not. Your choice." }] },
    { id: 'cc.a6', turns: [{ by: 'a', say: "{alliance} is about to get one person bigger, or one person smaller. Your vote decides which." }] },
    { id: 'cc.a7', turns: [{ by: 'a', say: "Ask {alliance} where you'd finish if they won. Then ask me." }] },
  ],
  'campaign.case.comps': [
    { id: 'cc.c1', turns: [{ by: 'a', say: "{target} has won {theirComps} competitions. I've won {myComps}. One of us becomes your problem later, and it isn't me." }] },
    { id: 'cc.c2', turns: [{ by: 'a', say: "Do you want to beat {target} in a comp at the end? Because I don't think anyone can." }] },
    { id: 'cc.c3', turns: [{ by: 'a', say: "{target} keeps winning. Every week {target} stays, that gets harder to stop." }] },
    { id: 'cc.c4', turns: [{ by: 'a', say: "This is your chance to get the competition beast out without winning anything yourself. Take it." }] },
    { id: 'cc.c5', turns: [{ by: 'a', say: "{target} wins things. I don't. Which one would you rather be sitting next to in a month?" }] },
    { id: 'cc.c6', turns: [{ by: 'a', say: "Every time {target} wins, you lose a week of safety. I've never taken a week from you." }] },
    { id: 'cc.c7', turns: [{ by: 'a', say: "You can't beat {target} in a competition. Nobody can. So don't let it get to a competition." }] },
  ],
  'campaign.case.beatable': [
    { id: 'cc.b1', turns: [{ by: 'a', say: "Look at who's left. {target} beats you at the end. I don't, and I think we both know it." }] },
    { id: 'cc.b2', turns: [{ by: 'a', say: "Take the one you can beat. That's me. I'm being honest with you." }] },
    { id: 'cc.b3', turns: [{ by: 'a', say: "If it's you and {target} at the end, {target} wins. If it's you and me, you might." }] },
    { id: 'cc.b4', turns: [{ by: 'a', say: "Everyone likes {target}. That's exactly why {target} is dangerous at the end." }] },
    { id: 'cc.b5', turns: [{ by: 'a', say: "Keep the threat and you'll regret it. Keep me and you've still got a shot." }] },
    { id: 'cc.b6', turns: [{ by: 'a', say: "Juries love {target}. Juries won't love me. Which one do you want next to you?" }] },
  ],
  'campaign.case.clean': [
    { id: 'cc.n1', turns: [{ by: 'a', say: "I've never written your name down. Not once. {target} can't say the same, and I can." }] },
    { id: 'cc.n2', turns: [{ by: 'a', say: "Check the votes. My name has never been next to yours. {target}'s has." }] },
    { id: 'cc.n3', turns: [{ by: 'a', say: "{target} has voted against you before. I never have. That should count for something." }] },
    { id: 'cc.n4', turns: [{ by: 'a', say: "I'm the only one up here who's never come after you. Not once, not in any vote." }] },
    { id: 'cc.n5', turns: [{ by: 'a', say: "You know who's written your name down before. It wasn't me. Remember that on Thursday." }] },
    { id: 'cc.n6', turns: [{ by: 'a', say: "Look at the voting history. I've never come after you. That's not luck, that's a choice I made." }] },
  ],
  'campaign.case.friend': [
    { id: 'cc.f1', when: { known: true }, turns: [{ by: 'a', say: "You don't owe me anything. But you'll need a number next week, and I'll be one for you. {target} won't." }] },
    { id: 'cc.f2', turns: [{ by: 'a', say: "We've always been good, you and me. I just need that to be true on Thursday." }] },
    { id: 'cc.f3', turns: [{ by: 'a', say: "I'm not going to give you a big speech. You know me. That's my speech." }] },
    { id: 'cc.f4', turns: [{ by: 'a', say: "If I stay, you've got a friend in here who actually means it. That's rarer than you think." }] },
    { id: 'cc.f5', turns: [{ by: 'a', say: "I've had your back since the first day. I'm asking you to have mine, once." }] },
    { id: 'cc.f6', turns: [{ by: 'a', say: "Keep me and you've got somebody who'll tell you the truth. Every week. That's all I've got to offer." }] },
    { id: 'cc.f7', turns: [{ by: 'a', say: "I trust you. That's why I'm asking you first." }] },
    { id: 'cc.f8', when: { register: 'sweet' }, turns: [{ by: 'a', say: "I'd hate to leave without saying it, so I'm saying it now. You've been the best part of this house for me." }] },
    { id: 'cc.f9', turns: [{ by: 'a', say: "I'm not going to make a pitch. I'm just asking my friend for a favour." }] },
    { id: 'cc.f10', turns: [{ by: 'a', say: "You've been there for me all game. Be there one more time." }] },
  ],
  'campaign.case.count': [
    { id: 'cc.k1', turns: [{ by: 'a', say: "I'm not asking you to like me. I'm asking you to count. Without me, you're one short of everything you want to do." }] },
    { id: 'cc.k2', turns: [{ by: 'a', say: "Next week you'll need one more vote. I'll be that vote, if I'm still here." }] },
    { id: 'cc.k3', turns: [{ by: 'a', say: "Keep me, and you've got a vote nobody else has bought yet." }] },
    { id: 'cc.k4', turns: [{ by: 'a', say: "Think about what you want to do next week. Now count how many people will help you do it. I'm one." }] },
    { id: 'cc.k5', turns: [{ by: 'a', say: "Nobody owns my vote. Keep me, and you're the first person who gets a say in it." }] },
    { id: 'cc.k6', turns: [{ by: 'a', say: "I'm not part of anybody's plan. That means I'm free to be part of yours." }] },
    { id: 'cc.k7', turns: [{ by: 'a', say: "I'll be straight with you. I need your vote, and you'll need mine. Let's not pretend otherwise." }] },
    { id: 'cc.k8', when: { register: 'schemer' }, turns: [{ by: 'a', say: "Let's skip the speech. Keep me, and I'll owe you. I always pay what I owe." }] },
    { id: 'cc.k9', when: { register: 'shy' }, turns: [{ by: 'a', say: "I'm not good at this. But I'd really like to stay, and I'd vote with you if I did." }] },
    { id: 'cc.k10', when: { register: 'fiery' }, turns: [{ by: 'a', say: "I'm a fighter. Keep me and I fight for you. Send me home and you've wasted a fighter." }] },
    { id: 'cc.k11', turns: [{ by: 'a', say: "Every week from here is about numbers. I'm a number. Use me." }] },
    { id: 'cc.k12', turns: [{ by: 'a', say: "I'm not going to pretend we're best friends. I'm going to tell you I'm useful." }] },
    { id: 'cc.k13', turns: [{ by: 'a', say: "Whoever stays this week owes the people who kept them. I'd owe you. Think about that." }] },
    { id: 'cc.k14', turns: [{ by: 'a', say: "I'll keep it simple. Keep me, and next week I vote where you vote." }] },
  ],

  // ── the voter's reply ────────────────────────────────────────────
  'campaign.reply.receptive': [
    { id: 'cr.r1', turns: [{ by: 'b', say: "...Okay. Say that again." }, { by: 'b', dr: "I went in sure. I came out doing maths." }] },
    { id: 'cr.r2', turns: [{ by: 'b', say: "I hadn't thought about it like that." }, { by: 'a', say: "Think about it tonight." }] },
    { id: 'cr.r3', turns: [{ by: 'b', say: "You might be right. I'm not promising anything." }, { by: 'a', say: "You don't have to. Just think." }] },
    { id: 'cr.r4', turns: [{ by: 'b', say: "That's... actually a good point." }, { by: 'b', dr: "I hate it when the person I'm meant to vote out makes sense." }] },
    { id: 'cr.r5', turns: [{ by: 'b', say: "Leave it with me." }, { by: 'a', dr: "\"Leave it with me\" from {b} is the best thing I've heard all week." }] },
    { id: 'cr.r6', turns: [{ by: 'b', say: "Okay. I'm listening. Properly now." }] },
    { id: 'cr.r7', turns: [{ by: 'b', say: "I'll be honest. You've just changed something." }, { by: 'a', say: "That's all I wanted." }] },
    { id: 'cr.r8', turns: [{ by: 'b', say: "Who else have you said this to?" }, { by: 'a', say: "Only you. You're the one who matters this week." }, { by: 'b', dr: "Flattery. It works, apparently." }] },
    { id: 'cr.r9', turns: [{ by: 'b', dr: "I walked in knowing my vote. I walked out with a question. That's how it starts." }] },
    { id: 'cr.r10', turns: [{ by: 'b', say: "...Fine. You've got my attention." }, { by: 'a', say: "Better than nothing." }] },
    { id: 'cr.r11', turns: [{ by: 'b', say: "Don't tell anyone we talked." }, { by: 'a', say: "Who would I tell?" }] },
    { id: 'cr.r12', turns: [{ by: 'b', say: "Give me a day. I need to check something." }, { by: 'a', dr: "Checking something means I've got a chance. Finally." }] },
    { id: 'cr.r13', turns: [{ by: 'b', say: "Why didn't anybody else say this to me?" }, { by: 'a', say: "Because it doesn't help them." }] },
    { id: 'cr.r14', turns: [{ by: 'b', say: "If I did this, nobody can know it was me." }, { by: 'a', say: "Nobody will." }] },
    { id: 'cr.r15', turns: [{ beat: '{b} goes quiet, then asks {a} to go through it one more time.' }, { by: 'a', dr: "When somebody asks you to say it again, you're winning." }] },
    { id: 'cr.r16', turns: [{ by: 'b', say: "That's the first thing anyone's said this week that actually makes sense." }, { by: 'a', say: "Then trust it." }] },
    { id: 'cr.r17', turns: [{ by: 'b', say: "Who else knows you're asking?" }, { by: 'a', say: "Just you." }, { by: 'b', say: "Keep it that way." }] },
    { id: 'cr.r18', turns: [{ by: 'b', say: "I came in here to say no." }, { by: 'a', say: "And now?" }, { by: 'b', say: "And now I need to think." }] },
    { id: 'cr.r19', turns: [{ by: 'b', dr: "I've heard ten pitches this week. That's the only one I'm still thinking about." }] },
    { id: 'cr.r20', when: { registerB: 'cool' }, turns: [{ by: 'b', say: "Walk me through the numbers again." }, { beat: '{a} does. {b} counts along on one hand, slowly.' }, { by: 'b', say: "...Huh. Okay." }] },
  ],
  'campaign.reply.unmoved': [
    { id: 'cr.u1', turns: [{ by: 'b', say: "I hear you." }, { by: 'a', dr: "\"I hear you\" means no. Everybody in this house knows it means no." }] },
    { id: 'cr.u2', turns: [{ by: 'b', say: "I'm sorry. I made my mind up days ago." }] },
    { id: 'cr.u3', turns: [{ by: 'b', say: "That's a good speech." }, { by: 'a', say: "But?" }, { by: 'b', say: "But it's a speech." }] },
    { id: 'cr.u4', turns: [{ by: 'b', say: "I'll think about it." }, { by: 'b', dr: "I won't think about it. My vote isn't moving." }] },
    { id: 'cr.u5', turns: [{ by: 'b', say: "Thanks for coming to me. Honestly." }, { by: 'a', say: "That sounded like goodbye." }, { by: 'b', say: "..." }] },
    { id: 'cr.u6', turns: [{ beat: '{b} nods all the way through it and says nothing at all.' }, { by: 'a', dr: "Nodding is not a vote. I know that. I'm still choosing to hope." }] },
    { id: 'cr.u7', turns: [{ by: 'b', say: "I've already promised someone else." }, { by: 'a', say: "Promises change." }, { by: 'b', say: "Not mine." }] },
    { id: 'cr.u8', turns: [{ by: 'b', say: "You made a good point. It doesn't change anything." }] },
    { id: 'cr.u9', turns: [{ by: 'b', say: "I can't, {a}. I'm sorry." }, { by: 'a', say: "Okay. Thank you for telling me straight." }] },
    { id: 'cr.u10', turns: [{ by: 'b', dr: "{a} makes a good case. {a} always makes a good case. That's half the reason I want {a.obj} out." }] },
    { id: 'cr.u11', turns: [{ by: 'b', say: "Who told you I was the one to talk to?" }, { by: 'a', say: "Nobody. Why?" }, { by: 'b', say: "Because they were wrong." }] },
    { id: 'cr.u12', turns: [{ by: 'b', say: "I'm going with the house on this one." }, { by: 'a', dr: "\"With the house\". As if the house wasn't just a few people deciding I'm the easy option." }] },
    { id: 'cr.u13', turns: [{ by: 'b', say: "I know what you're doing, and you're good at it. It's still no." }] },
    { id: 'cr.u14', turns: [{ by: 'b', say: "If it helps, it's not personal." }, { by: 'a', say: "It doesn't help." }] },
    { id: 'cr.u15', turns: [{ by: 'b', say: "You've said all this to three people today, haven't you?" }, { by: 'a', say: "...Two." }, { by: 'b', say: "Then you know how it went with them." }] },
    { id: 'cr.u16', turns: [{ beat: '{b} glances at the door twice while {a} is still talking.' }, { by: 'a', dr: "Twice. {b} looked at the door twice. I'm not getting that vote." }] },
    { id: 'cr.u17', turns: [{ by: 'b', say: "I wish I could. I really do." }, { by: 'a', say: "You could. You just won't." }, { by: 'b', say: "...Yeah." }] },
    { id: 'cr.u18', turns: [{ by: 'b', say: "Can I be honest? It's already decided." }, { by: 'a', say: "By who?" }, { by: 'b', say: "By more people than me." }] },
    { id: 'cr.u19', turns: [{ by: 'b', say: "Good luck on Thursday." }, { by: 'a', dr: "\"Good luck\" is what you say to someone you're not voting for." }] },
    { id: 'cr.u20', turns: [{ by: 'b', say: "I need to do what's best for my game. I'm sorry." }, { by: 'a', say: "I'm what's best for your game." }, { by: 'b', say: "Not this week." }] },
    { id: 'cr.u21', turns: [{ by: 'b', say: "You've never once asked me anything until this week." }, { by: 'a', say: "I know. I'm asking now." }, { by: 'b', say: "Now's too late." }] },
    { id: 'cr.u22', turns: [{ by: 'b', dr: "Every nominee in history has given that exact speech. It didn't work on me then either." }] },
    { id: 'cr.u23', turns: [{ by: 'b', say: "Okay." }, { by: 'a', say: "Okay, you'll think about it, or okay, you're done talking?" }, { by: 'b', say: "Okay." }] },
    { id: 'cr.u24', when: { registerB: 'fiery' }, turns: [{ by: 'b', say: "Don't try and play me. I can see exactly what you're doing." }, { by: 'a', say: "I'm not playing you. I'm asking." }, { by: 'b', say: "Same thing, in here." }] },
  ],
  'campaign.reply.worn': [
    { id: 'cr.w1', turns: [{ by: 'a', say: "Me again. Same argument. New day." }, { by: 'b', say: "...Okay. This time I'm listening." }] },
    { id: 'cr.w2', turns: [{ by: 'b', say: "You again." }, { by: 'a', say: "Me again. Has anything changed?" }, { by: 'b', say: "Actually? Yes." }] },
    { id: 'cr.w3', turns: [{ by: 'a', say: "I know you said no yesterday." }, { by: 'b', say: "I said no yesterday. Today I'm less sure." }] },
    { id: 'cr.w4', turns: [{ by: 'b', dr: "{a} came back. Same words. But I've had a day to think about them, and they sound different today." }] },
    { id: 'cr.w5', turns: [{ by: 'a', say: "One more try, and then I'll leave you alone." }, { by: 'b', say: "Go on. I think you might have got me." }] },
    { id: 'cr.w6', turns: [{ by: 'b', say: "You're persistent, I'll give you that." }, { by: 'a', say: "Is persistent working?" }, { by: 'b', say: "...Maybe." }] },
    { id: 'cr.w7', turns: [{ by: 'b', say: "I've been thinking about what you said." }, { by: 'a', say: "And?" }, { by: 'b', say: "And I think you were right." }] },
    { id: 'cr.w8', turns: [{ by: 'a', say: "Last chance. I promise." }, { by: 'b', say: "You promised that yesterday." }, { by: 'a', say: "And yet you're still listening." }, { by: 'b', say: "...I am." }] },
    { id: 'cr.w9', turns: [{ by: 'b', dr: "{a} wore me down. I'm not proud of it. But the argument got better every time I heard it." }] },
    { id: 'cr.w10', turns: [{ by: 'b', say: "Stop. You've convinced me. Just stop talking before you un-convince me." }] },
  ],
};
