// Every Big Brother line pool, by key '<kind>.<ending>'. A converted event's
// pools are added here; tests/bb-script.test.js checks every one of them.
import FRICTION from './friction.js';
import CEREMONY from './ceremony.js';
import TALK from './talk.js';
import SOCIAL from './social.js';
import DEALS from './deals.js';
import ALLIANCE from './alliance.js';
import CAMPAIGN from './campaign.js';
import POWER from './power.js';
import LIFE from './life.js';
import PHASE from './phase.js';
import BLOC from './bloc.js';
import VENUE from './venue.js';
import FALLOUT from './fallout.js';
import BOND from './bond.js';
import REIGN from './reign.js';
import SCHEME from './scheme.js';
import FOLLOWUP from './followup.js';
import TEXTURE from './texture.js';
import EDITORIAL from './editorial.js';
import ARC from './arc.js';
import COUPLE from './couple.js';
import JURY from './jury.js';
import PLAN from './plan.js';
import KNOWN from './known.js';
import CER from './cer.js';
import ROMANCE from './romance.js';
import UPKEEP from './upkeep.js';
import ENGINE from './engine.js';
import DRINKS from './drinks.js';
import MEETING from './meeting.js';
import SLOP from './slop.js';
import WHACK from './whack.js';
import TWIST1 from './twist1.js';
import TWIST2 from './twist2.js';
import TWIST3 from './twist3.js';
import TWIST4 from './twist4.js';
import TWIST5 from './twist5.js';
import TWIST6 from './twist6.js';
import TWIST7 from './twist7.js';
import TWIST8 from './twist8.js';
import TWIST9 from './twist9.js';
import TWIST10 from './twist10.js';
import TWIST11 from './twist11.js';
import TWIST12 from './twist12.js';
import VFALL from './vfall.js';
import ENGINE2 from './engine2.js';

export const POOLS = { ...FRICTION, ...CEREMONY, ...TALK, ...SOCIAL, ...DEALS, ...ALLIANCE, ...CAMPAIGN, ...POWER, ...LIFE, ...PHASE, ...BLOC, ...VENUE, ...FALLOUT, ...BOND, ...REIGN, ...SCHEME, ...FOLLOWUP, ...TEXTURE, ...EDITORIAL, ...ARC, ...COUPLE, ...JURY, ...PLAN, ...KNOWN, ...CER, ...ROMANCE, ...UPKEEP, ...ENGINE, ...DRINKS, ...MEETING, ...SLOP, ...WHACK, ...TWIST1, ...TWIST2, ...TWIST3, ...TWIST4, ...TWIST5, ...TWIST6, ...TWIST7, ...TWIST8, ...TWIST9, ...TWIST10, ...TWIST11, ...TWIST12, ...VFALL, ...ENGINE2 };
export const POOL_KEYS = Object.keys(POOLS);
