// ══════════════════════════════════════════════════════════════════════
// td/story/phrases/core1.js — agreeing, refusing, pushing back, defending, blaming
// ══════════════════════════════════════════════════════════════════════
//
// Each move in every voice (td/story/voice.js tags) and age band (teen / adult / grown). A line
// here carries attitude, not facts: it has to fit any scene that asks for the move. {to} is the
// person spoken to. td/story/phrase.js picks the speaker's own voice first.

export default {
  // a plain yes
  agree: {
    any: ["Okay. Yeah.", "Sure.", "Fine by me.", "Yeah, okay.", "Works for me.", "Okay. Let's do it.", "Sounds good.", "I'm in."],
    dry: ["Sure. Why not.", "Great. Love that for us.", "Fine. Thrilling.", "Yes. Obviously."],
    loud: ["YES. Let's go!", "Heck yeah!", "Done! I'm in!", "Oh, absolutely!"],
    warm: ["Of course! Anything you need.", "Yeah, I'm with you.", "Totally. We've got this.", "Aw, yes. Count me in."],
    blunt: ["Yes.", "Fine. Done.", "Yeah. Good call.", "Okay. No arguments."],
    theatrical: ["Oh, a thousand times yes!", "Yes! Finally, a plan worthy of me!", "Darling, I'm in."],
    anxious: ["Okay. Okay, yes. I think yes.", "Yes? Yes. Sorry. Yes.", "If you think it's okay, then... yeah."],
    calm: ["Sure. Sounds fine.", "Yeah, that works.", "No problem."],
    competitive: ["Good. Let's win this.", "Fine. As long as we win.", "Yes. Let's not waste time."],
    schemer: ["Of course. Whatever you think is best.", "Sounds perfect.", "Absolutely. I trust you."],
    cruel: ["Fine. Try not to mess it up.", "Whatever. Yes.", "Sure. It's not like you'd come up with better."],
    chaotic: ["YES! Wait, what are we agreeing to? Doesn't matter, yes!", "Oh, I am SO in."],
    food: ["Yes. Is there a snack involved?", "Okay, but then we eat."],
    ditzy: ["Yes! Wait, what was the question? Yes anyway!", "Totally! Love it!"],
    nerdy: ["Logically, yes.", "Yes. The numbers check out.", "Agreed. Statistically it's our best option."],
    earnest: ["Yes. I'm with you all the way.", "I'll do it. You can count on me."],
    flirty: ["For you? Sure.", "Anything you want."],
    tough: ["Fine.", "Yeah. Let's go.", "Okay. I've got it."],
    bossy: ["Good. That's what I was going to say.", "Fine, but we do it properly."],
    emotional: ["Yes! Oh my gosh, yes.", "Okay. I'm in. I'm really in."],
    goofy: ["Yes, captain!", "Aye aye!", "Consider it done. Probably."],
    proud: ["Naturally.", "Of course. I'd have said the same."],
    quiet: ["Okay.", "Yeah.", "Mm-hm.", "Sure."],
    teen: ["Bet.", "Yeah, for sure.", "Okay, cool, yeah.", "Say less."],
    adult: ["Yeah, that works for me.", "Okay. Let's do it."],
    grown: ["All right. Let's do it.", "Fine by me.", "That's sensible."],
    'loud+teen': ["LET'S GOOO!", "Yes! Bet! Let's go!"],
    'dry+grown': ["Fine. I've agreed to worse.", "Yes. Let's get on with it."],
  },
  // yes, but not happily
  'agree.reluctant': {
    any: ["...Fine.", "Okay. I don't love it, but okay.", "Fine. But I'm not happy about it.", "I guess.", "...Yeah. Okay.", "If we have to.", "Fine. You win."],
    dry: ["Fine. I'll pretend this was my idea.", "Wonderful. Can't wait.", "Sure. What could go wrong."],
    loud: ["FINE. But I'm not happy!", "Ugh! Okay! Fine!"],
    warm: ["Okay, I'll do it, I just really hope it's the right thing.", "Fine. For you, okay."],
    blunt: ["Fine. It's a bad idea, but fine.", "I don't like it. I'll do it."],
    theatrical: ["Fine! But history will remember that I objected!", "Ugh. The things I do for you people."],
    anxious: ["Okay... I just really hope this doesn't backfire.", "I mean, okay. If everyone else is."],
    calm: ["Not my first choice. But okay.", "Sure. We'll see how it goes."],
    competitive: ["Fine. But if we lose, I'm saying I told you so.", "Okay. It better work."],
    schemer: ["Fine. For now.", "Okay, we'll do it your way. This time."],
    cruel: ["Fine. When it blows up, it's on you.", "Sure. Go ahead and fail."],
    nerdy: ["Fine, but I want it noted that the odds are bad.", "Okay. Against my better judgement."],
    tough: ["Fine. Whatever.", "...Yeah. Okay."],
    bossy: ["Fine. But we're doing it my way next time.", "Okay, but I'm in charge of the next one."],
    emotional: ["Okay, I hate this, but okay.", "Fine. I'm going to cry about it later."],
    goofy: ["Fine. But I'm going to complain the whole time.", "Okay, but I'm sulking."],
    proud: ["Fine. I'll lower myself to it.", "Very well. Don't make me regret it."],
    quiet: ["...Fine.", "Okay.", "If I have to."],
    teen: ["Ugh, fine.", "Okay, whatever.", "Fine, I guess."],
    grown: ["All right. Against my better judgement.", "Fine. But I want it on record."],
    'anxious+teen': ["Okay but if this goes bad I'm blaming you.", "Fine but I'm scared."],
  },
  // no
  refuse: {
    any: ["No.", "I don't think so.", "Nope.", "Not happening.", "No way.", "I'm not doing that.", "Absolutely not.", "Pass."],
    dry: ["Hard pass.", "No. But thank you for thinking of me.", "Tempting. No."],
    loud: ["NO. Are you crazy?", "No way! No way!", "Not in a million years!"],
    warm: ["I'm sorry. I can't do that.", "I wish I could. I can't.", "Please don't be mad. It's a no."],
    blunt: ["No.", "That's a no.", "Not a chance."],
    theatrical: ["Never! I would rather perish!", "Absolutely, positively not."],
    anxious: ["I... no. Sorry. I can't.", "Um. No? Is that okay? No."],
    calm: ["Nah. I'm good.", "No thanks."],
    competitive: ["No. That loses us the game.", "Not if I want to win."],
    schemer: ["I'd love to. I really can't.", "Let me think about it. ...No."],
    cruel: ["No. Ask someone who cares.", "Why would I do that for you?"],
    chaotic: ["No! Ha! Ask me tomorrow!", "Nope! Next question!"],
    nerdy: ["No. The risk is too high.", "Negative."],
    earnest: ["I can't. It wouldn't be right.", "No. I gave my word to somebody else."],
    tough: ["No.", "Not doing it.", "Forget it."],
    bossy: ["No. And don't ask again.", "No. We're not doing that."],
    emotional: ["No! I can't! Don't make me!", "I can't. I just can't."],
    goofy: ["Nope! Nope nope nope.", "No, my answer is no, and that's my final answer."],
    proud: ["That's beneath me.", "I don't do that."],
    quiet: ["No.", "...No.", "Nah."],
    teen: ["No, that's so weird.", "Nah. Hard no.", "Literally no."],
    grown: ["No. I'm too old for that.", "Not a chance."],
  },
  // challenging what somebody said
  pushback: {
    any: ["Says who?", "Wait. Why?", "I don't buy that.", "Hold on. That's not fair.", "Really? That's your plan?", "Are you serious?", "That doesn't make any sense."],
    dry: ["Bold of you to assume I'd agree.", "That's a choice.", "Interesting. Wrong, but interesting."],
    loud: ["Are you KIDDING me?!", "Excuse me?!", "Oh, no. No, no, no."],
    warm: ["I hear you, but I don't think that's right.", "Can we maybe think about that a little more?"],
    blunt: ["That's dumb.", "No. That's wrong.", "You're not making sense."],
    theatrical: ["I'm sorry, did you just say that out loud?", "The audacity!"],
    anxious: ["Are we sure about that? Like, really sure?", "Um. I don't know if that's a good idea."],
    calm: ["I don't think so.", "Hm. Not sure about that."],
    competitive: ["That loses. Pick something that wins.", "You're thinking too small."],
    schemer: ["Interesting. And who does that help?", "Funny. That's not what you said yesterday."],
    cruel: ["That's the stupidest thing I've heard all day.", "Did you think about that before you said it?"],
    chaotic: ["Counterpoint: no.", "Okay, but what if we did the exact opposite?"],
    nerdy: ["Your logic has a hole in it.", "That's not actually how that works."],
    earnest: ["That doesn't seem fair to everybody.", "I don't think that's right."],
    tough: ["You don't get to decide that.", "Says who?"],
    bossy: ["No. Here's what we're actually doing.", "That's not how this works."],
    emotional: ["How could you even say that?", "That's not fair and you know it!"],
    goofy: ["Objection! Overruled! By me!", "Wow. No."],
    proud: ["I'll pretend you didn't say that.", "Please. I know better."],
    quiet: ["No.", "...Why?", "Don't."],
    teen: ["That's literally so dumb.", "Okay, no. That's not it.", "Who even says that?"],
    adult: ["Come on. Really?", "That's not how it went."],
    grown: ["I've been around long enough to know that's nonsense.", "Let's not get carried away."],
    'loud+teen': ["Are you being FOR REAL right now?", "Bro. NO."],
    'dry+grown': ["I've heard better ideas from a vending machine.", "That's not a plan. That's a wish."],
    'warm+grown': ["Sweetheart, I don't think that's right.", "Let's slow down a minute."],
  },
  // pushing back on somebody taking charge
  'pushback.lead': {
    any: ["Who made you the boss?", "Who died and made you leader?", "Since when are you in charge?", "Nobody voted for you.", "Why do you get to decide?"],
    dry: ["Oh good, a dictator. We were missing one.", "I must have missed the election."],
    loud: ["Who put YOU in charge?!", "Whoa, whoa, whoa. Who's the boss now?"],
    warm: ["Maybe we could all decide together?", "Can we talk about it as a team first?"],
    blunt: ["You're not in charge.", "Stop bossing everybody around."],
    tough: ["You don't tell me what to do.", "Try that again and see what happens."],
    cruel: ["Nobody asked you to lead. Nobody asked you anything.", "Cute. You think you're in charge."],
    competitive: ["You're not the leader. You're just the loudest.", "I could run this better than you."],
    teen: ["Okay, who made you mom?", "You're not my dad."],
    grown: ["I've been doing this kind of thing since before you were born.", "Easy there. You're not my manager."],
    quiet: ["...Why you?", "No."],
  },
  // standing up for someone
  defend: {
    any: ["Hey. Back off.", "Leave {to} alone.", "That's not fair.", "Okay, that's enough.", "Lay off.", "Leave it."],
    dry: ["Wow, picking on people, that's really brave of you.", "Sure, blame the one who isn't yelling."],
    loud: ["HEY! Back off!", "Leave {to} alone! I'm serious!"],
    warm: ["Hey. That's not okay.", "Come on. Nobody deserves that."],
    blunt: ["Stop it. Now.", "You're being a jerk. Stop."],
    theatrical: ["How dare you!", "Unacceptable! Utterly unacceptable!"],
    anxious: ["Um, maybe we don't yell at {to}? Maybe?", "Guys, please, can we not?"],
    calm: ["All right. Take it easy.", "Let's cool it."],
    competitive: ["We lost as a team. Drop it.", "Yelling at {to} isn't going to win the next one."],
    schemer: ["Let's not turn on each other. That's what they want.", "Easy. We need everybody."],
    cruel: ["Pick on somebody who can actually fight back. Like me.", "Wow. Big talk from you."],
    nerdy: ["Statistically, that wasn't {to}'s fault.", "That's not even accurate."],
    earnest: ["{to} tried. That counts.", "That's not right and you know it."],
    tough: ["Back off.", "You want to say that to me instead?"],
    bossy: ["Enough. We're not doing this.", "Stop. Right now."],
    emotional: ["Stop it! Can't you see you're hurting {to}?", "That's so mean!"],
    goofy: ["Hey, hey, leave my friend alone, or I'll fight you. Badly, but I will."],
    quiet: ["Stop.", "Leave {to} alone."],
    teen: ["Bro, chill.", "Okay, that's actually so mean.", "Leave {to} alone, seriously."],
    grown: ["That's enough. Everybody calm down.", "Hey. We don't talk to each other like that."],
  },
  // it was your fault
  blame: {
    any: ["That was on you.", "We lost because of you.", "You messed that up.", "Nice going.", "Thanks a lot.", "That's on you and you know it."],
    dry: ["Great work out there, really, so inspiring.", "Well, that went exactly how I thought it would."],
    loud: ["What was THAT?!", "You had ONE job!"],
    warm: ["I'm not mad, I'm just... that was really hard to watch.", "It's okay. But that was kind of on you."],
    blunt: ["You lost us that.", "That was you. Own it."],
    theatrical: ["A disaster! A complete disaster! And we all know who's responsible."],
    anxious: ["I don't want to say it was you, but... it kind of was?"],
    competitive: ["We don't lose like that. You lose like that.", "If you'd just kept up, we'd have won."],
    schemer: ["People are going to remember who cost us that.", "I'm not blaming you. Everyone else is."],
    cruel: ["Pathetic. Honestly pathetic.", "Do us all a favour and sit the next one out."],
    nerdy: ["The data is clear. That was your section.", "Ninety percent of that loss was you."],
    tough: ["You choked.", "You froze. We lost."],
    bossy: ["I told you how to do it. You didn't listen.", "If you'd done it my way, we'd have won."],
    emotional: ["How could you let that happen?!", "We were so close!"],
    goofy: ["So, uh, that was all you, buddy."],
    proud: ["I was perfect out there. I can't say the same for you."],
    quiet: ["...That was you.", "Nice."],
    teen: ["Bro, you literally threw it.", "That was so bad. Like, so bad."],
    grown: ["I'm not going to sugarcoat it. That was you.", "You had a bad day. It cost us."],
  },
  // it wasn't me
  deflect: {
    any: ["That wasn't my fault.", "Don't put that on me.", "Everybody messed up.", "Why is it always me?", "I did my part.", "Whatever. We all lost."],
    dry: ["Sure. Blame the one person who showed up.", "Yes, it's all me. Obviously."],
    loud: ["Don't you DARE put that on me!", "Me?! What about you?!"],
    warm: ["I tried my best. I really did.", "I'm sorry. I didn't mean to let anybody down."],
    blunt: ["Wasn't me.", "You weren't great either."],
    theatrical: ["I am being framed!", "Unbelievable. Scapegoated, on day one."],
    anxious: ["I know, I know, I'm sorry, I'm so sorry.", "Was it really that bad? It was that bad."],
    calm: ["It happens. We'll get the next one.", "Okay, it's done, let's move on."],
    competitive: ["I was doing fine until somebody slowed me down.", "Check the scores. I wasn't last."],
    schemer: ["Funny how everyone remembers my mistake and not yours.", "Sure. Let's all agree it was me."],
    cruel: ["Please. I carried half of you.", "Look in a mirror."],
    nerdy: ["Technically, the error started before my part.", "That's not what happened."],
    tough: ["I don't care what you think.", "Say that again."],
    emotional: ["Why does everyone hate me?!", "I tried! I tried so hard!"],
    goofy: ["In my defence, I have no defence."],
    proud: ["I don't make mistakes. I make choices.", "I was fine. The rest of you weren't."],
    quiet: ["...Not me.", "Whatever."],
    teen: ["That's so not fair.", "Literally everyone messed up.", "Why are you looking at me?"],
    grown: ["I'm not taking that from you.", "Let's not start pointing fingers."],
  },
};
