// ══════════════════════════════════════════════════════════════════════
// td/story/phrases/core3.js — warning, doubting, confiding, greeting, thanking, sorry, sad, angry
// ══════════════════════════════════════════════════════════════════════

export default {
  // a warning
  threat: {
    any: ["Watch yourself.", "You're going to regret that.", "Don't push me.", "This isn't over.", "Be careful.", "Remember this."],
    dry: ["I'd sleep with one eye open, if I were you.", "That's going to be a problem for you. Later."],
    loud: ["Say that again! I dare you!", "You do NOT want to mess with me!"],
    warm: ["Please don't make me be the bad guy.", "I'm nice. I'm not a pushover."],
    blunt: ["Do that again and you're done.", "Cross me and you're out."],
    theatrical: ["You have made an enemy today!", "Mark my words!"],
    calm: ["I'd think about that, if I were you.", "Okay. I'll remember that."],
    competitive: ["I'm going to beat you. Every time.", "You just made this personal."],
    schemer: ["Interesting choice. We'll see how it works out for you.", "Enjoy it. It won't last."],
    cruel: ["You're done. You just don't know it yet.", "I'm going to enjoy watching you go home."],
    tough: ["Try me.", "Step up, then."],
    bossy: ["Last warning.", "Don't make me say it twice."],
    emotional: ["You'll be sorry! You'll be so sorry!"],
    proud: ["Nobody talks to me like that.", "You'll learn."],
    quiet: ["Don't.", "...Remember that."],
    teen: ["Okay, you're actually done.", "Say less. You're finished."],
    grown: ["I've dealt with people like you my whole life.", "Think very carefully about your next move."],
  },
  // I don't trust this
  suspicious: {
    any: ["Why are you being so nice?", "What do you want?", "Something's off with you.", "Where were you just now?", "Who've you been talking to?", "That's weird."],
    dry: ["Mm-hm. Sure.", "And I'm supposed to believe that?"],
    loud: ["Okay, what's going on?! Somebody tell me!", "Don't lie to me!"],
    warm: ["Are you okay? You've been weird all day.", "Is something going on? You can tell me."],
    blunt: ["You're lying.", "I don't trust you."],
    theatrical: ["The plot thickens!", "I smell a scheme!"],
    anxious: ["Are you mad at me? You seem mad at me.", "Is something happening that I don't know about?"],
    calm: ["Hm. Interesting.", "Okay. If you say so."],
    competitive: ["You're up to something.", "What's your angle?"],
    schemer: ["Funny. You said something different this morning.", "Who told you to say that?"],
    nerdy: ["That doesn't add up.", "Your story has changed twice."],
    tough: ["What's your deal?", "Out with it."],
    emotional: ["You promised! You promised me!"],
    quiet: ["...Why?", "Hm."],
    teen: ["That's so sus.", "Okay, that's weird. Why?", "You're being so weird."],
    grown: ["I've heard that one before.", "I wasn't born yesterday."],
  },
  // can I tell you something
  confide: {
    any: ["Can I tell you something?", "Between us?", "Don't tell anyone, okay?", "Can I be honest with you?", "I haven't said this to anybody."],
    dry: ["I'm going to say something, and you're going to pretend you didn't hear it.", "Don't make it weird."],
    loud: ["Okay, okay, come here. Secret time.", "You can't tell ANYONE."],
    warm: ["You're the only one I trust with this.", "I feel like I can tell you things."],
    blunt: ["I'm only telling you this once.", "Here's the truth."],
    anxious: ["Okay, this might be dumb, but...", "Promise you won't laugh?"],
    schemer: ["I'm only telling you this because I trust you.", "This stays between us. I mean it."],
    nerdy: ["I've been thinking about something, and I need a second opinion."],
    tough: ["Keep this to yourself.", "Listen."],
    emotional: ["I need to tell somebody or I'll burst."],
    quiet: ["Hey.", "Can I say something?"],
    teen: ["Okay, don't tell anyone, but...", "Can I tell you something kind of embarrassing?"],
    grown: ["I'm going to tell you something I haven't told anyone here.", "Sit down a second."],
  },
  // hello
  greet: {
    any: ["Hey!", "Hi.", "Hey there.", "Morning.", "Oh, hey.", "Hi, I'm {by}."],
    dry: ["Hello. I'm thrilled. Can't you tell?", "Oh. It's you. Hi."],
    loud: ["HEY! What's up?!", "There they are!"],
    warm: ["Hi! It's so nice to meet you!", "Hey you! How are you doing?"],
    blunt: ["Hey.", "Hi. {by}."],
    theatrical: ["Hello, darling!", "Behold! I'm here!"],
    anxious: ["Oh! Hi. Hi. Sorry. Hi.", "Hey... um, hi."],
    calm: ["Hey. What's up.", "Hi there."],
    flirty: ["Well, hello.", "Hey there, you."],
    goofy: ["Greetings, fellow human!", "Yo yo yo!"],
    tough: ["Yo.", "Hey."],
    quiet: ["Hi.", "...Hey."],
    teen: ["Heyyy.", "Yo! What's up?", "Oh hey!"],
    grown: ["Good to meet you.", "Hello there."],
  },
  thanks: {
    any: ["Thanks.", "Thank you. Really.", "I owe you one.", "Thanks for that.", "You didn't have to do that."],
    dry: ["Thank you. I'm touched. Visibly.", "Wow. A nice thing. Thanks."],
    loud: ["THANK YOU! You're the best!", "You legend!"],
    warm: ["Thank you so much. You have no idea.", "That means everything to me."],
    blunt: ["Thanks.", "Appreciate it."],
    theatrical: ["My hero!", "I'll never forget this!"],
    anxious: ["Oh! Thank you. Sorry. Thank you.", "You didn't have to. Thanks."],
    competitive: ["Thanks. I'll pay you back.", "Good. I needed that."],
    schemer: ["I won't forget this.", "Thank you. Really. I mean it."],
    tough: ["Thanks.", "...Thanks."],
    emotional: ["You're going to make me cry! Thank you!"],
    proud: ["I suppose I appreciate it.", "Thank you. That was the right thing to do."],
    quiet: ["Thanks.", "...Thank you."],
    teen: ["Thanks, seriously.", "You're a real one.", "Okay, thank you, that's so nice."],
    grown: ["Thank you. That was kind of you.", "I appreciate that more than you know."],
  },
  // sorry
  apologize: {
    any: ["I'm sorry.", "My bad.", "I shouldn't have said that.", "I messed up.", "That was out of line.", "I didn't mean it like that."],
    dry: ["I'm sorry. Write it down, it won't happen often.", "Fine. I was wrong. Once."],
    loud: ["I'm SORRY, okay? I'm sorry!", "Okay! I'm sorry! I get it!"],
    warm: ["I'm so sorry. I feel terrible.", "I never wanted to hurt you."],
    blunt: ["I was wrong. Sorry.", "That was on me."],
    theatrical: ["I am wretched! Forgive me!", "I apologise from the bottom of my heart."],
    anxious: ["I'm sorry, I'm so sorry, I didn't mean it.", "Are you mad? You're mad. I'm sorry."],
    calm: ["Sorry. That wasn't fair.", "My mistake."],
    schemer: ["I'm sorry. I'd hate for this to come between us.", "Let's put it behind us."],
    tough: ["...Sorry.", "My bad. Okay?"],
    proud: ["I may have been slightly out of line.", "I suppose I owe you an apology."],
    emotional: ["I'm sorry! I didn't mean any of it!"],
    quiet: ["Sorry.", "...My bad."],
    teen: ["Okay, I'm sorry, that was so bad.", "My bad, seriously."],
    grown: ["I owe you an apology.", "That was beneath me. I'm sorry."],
  },
  // that hurts
  sad: {
    any: ["I really thought we had it.", "That sucks.", "I don't even know what to say.", "This is the worst.", "I need a minute."],
    dry: ["Well. That's the day ruined.", "Fantastic. Truly."],
    loud: ["NO! No no no!", "This is SO unfair!"],
    warm: ["I'm going to miss them so much.", "It's just hard. That's all."],
    blunt: ["It's bad. I'm not going to pretend.", "That hurt."],
    theatrical: ["My heart! It's breaking!", "This is a tragedy!"],
    anxious: ["I knew it. I knew something bad would happen."],
    calm: ["Tough day.", "Rough one."],
    tough: ["Whatever. Next.", "It's fine. I'm fine."],
    emotional: ["I can't stop crying.", "Why does it hurt this much?"],
    goofy: ["I'm going to go be sad behind a tree. Don't follow me."],
    quiet: ["...", "Yeah."],
    teen: ["That's so sad, actually.", "I'm not okay."],
    grown: ["Some days are just hard.", "Give me a minute."],
  },
  // snapping
  angry: {
    any: ["I'm done.", "Unbelievable.", "Are you serious right now?", "Don't talk to me.", "I can't believe this."],
    dry: ["Wonderful. Just wonderful.", "I'm calm. I'm extremely calm. Can't you tell?"],
    loud: ["I am SO sick of this!", "UGH!", "That's IT!"],
    warm: ["I'm usually patient. I'm not feeling patient.", "That really hurt my feelings."],
    blunt: ["You're making me angry.", "Stop. Now."],
    theatrical: ["I have never been so insulted in my life!", "This is an outrage!"],
    anxious: ["I'm not mad. I'm a little mad. I'm mad."],
    calm: ["I'm going to walk away now.", "I'm not doing this."],
    cruel: ["You're pathetic.", "Get out of my face."],
    tough: ["Back off before I make you.", "Don't."],
    emotional: ["Why does this keep happening to me?!", "I can't take this anymore!"],
    proud: ["How dare you.", "You don't speak to me like that."],
    quiet: ["...Leave.", "Stop."],
    teen: ["Oh my god, I'm so done.", "This is literally so annoying."],
    grown: ["I'm too old for this nonsense.", "That's enough. I mean it."],
  },
  // I'll think about it
  stall: {
    any: ["Let me think about it.", "I'll think about it.", "Maybe.", "I don't know yet.", "Can I get back to you?", "We'll see."],
    dry: ["I'll add it to my list of things to think about.", "Maybe. Don't hold your breath."],
    loud: ["Ugh, I don't know! Ask me later!"],
    warm: ["I need a little time. Is that okay?"],
    blunt: ["Not now.", "Ask me tonight."],
    anxious: ["I don't know. I really don't know. Can I think?"],
    calm: ["Let me sleep on it.", "Give me a bit."],
    schemer: ["Let me see what else is out there.", "Interesting. Let me think."],
    nerdy: ["I need more information first.", "Let me run the numbers."],
    tough: ["Maybe.", "We'll see."],
    quiet: ["...Maybe.", "We'll see."],
    teen: ["Uh, maybe? Idk.", "Let me think, okay?"],
    grown: ["I don't make decisions in a hurry.", "Let me think it over."],
  },
};
