// ══════════════════════════════════════════════════════════════════════
// td/story/phrases/core2.js — reassuring, worrying, joking, teasing, complaining, reacting
// ══════════════════════════════════════════════════════════════════════

export default {
  // it's going to be okay
  reassure: {
    any: ["Hey. It's going to be okay.", "Don't worry about it.", "We'll be fine.", "You're okay. Breathe.", "It's not as bad as it looks.", "We've got this."],
    dry: ["Relax. If it was you, you'd know by now.", "Statistically, you'll probably survive. Probably."],
    loud: ["Hey! Chin up! We're fine!", "Stop worrying! We've totally got this!"],
    warm: ["Come here. It's going to be okay, I promise.", "You're doing so much better than you think.", "I've got you. Okay?"],
    blunt: ["Stop panicking. It doesn't help.", "You're fine. Move on."],
    theatrical: ["Darling, nothing bad will happen to you while I'm here.", "Fear not!"],
    anxious: ["It's okay. I think. I think it's okay.", "We're both scared. That's normal. Right?"],
    calm: ["Take a breath. It's fine.", "One thing at a time."],
    competitive: ["Shake it off. We win the next one.", "Forget it. Focus on what's next."],
    schemer: ["You're safe. Trust me on this.", "Nobody's coming after you. I'd know."],
    nerdy: ["Realistically, the odds are in your favour.", "Worrying doesn't change the outcome. Just so you know."],
    earnest: ["Whatever happens, I've got your back.", "You're not alone in this."],
    tough: ["You're fine. Toughen up.", "Get up. You're okay."],
    bossy: ["Nobody's panicking. We have a plan.", "Stop. We're handling it."],
    emotional: ["Oh, come here. It's okay. It's okay.", "Don't cry, or I'll cry."],
    goofy: ["Hey, worst case, we all go home and get pizza.", "Look at it this way. It can't get worse. Okay, it can."],
    flirty: ["Hey. I'm right here. Nothing's happening to you."],
    quiet: ["You're okay.", "Hey. It's fine."],
    teen: ["Bro, you're fine.", "It's okay, seriously. Don't freak out.", "You're good. You're good."],
    grown: ["Listen to me. You're going to be all right.", "I've seen worse. This isn't the end of anything."],
    'warm+grown': ["Come here, kiddo. It's going to be fine.", "You remind me of my niece. She worries too. It always works out."],
  },
  // I'm scared
  worry: {
    any: ["I've got a bad feeling about this.", "What if it's me?", "I don't like this.", "Something's off.", "I can't stop thinking about it.", "This is bad. This is really bad."],
    dry: ["Great. Love this feeling.", "Oh good. Dread. My favourite."],
    loud: ["I'm FREAKING out right now!", "This is a disaster!"],
    warm: ["I'm worried about you. And me. Mostly you.", "I just don't want anyone to get hurt."],
    blunt: ["I'm worried. That's all.", "I don't trust this."],
    theatrical: ["I can feel it. Doom. Approaching doom.", "My nerves cannot take this!"],
    anxious: ["Okay, I'm freaking out. I'm freaking out a little.", "What if they're all lying? What if everyone's lying?", "I'm going to throw up."],
    calm: ["I'm a little worried. Not a lot.", "Something feels off. Can't place it."],
    competitive: ["If we lose again, we're done.", "I hate not knowing where I stand."],
    schemer: ["Somebody's talking. I can feel it.", "It's too quiet. Quiet means plans."],
    nerdy: ["The odds are not great. I ran them.", "There's too many variables."],
    tough: ["Something's up.", "I don't like it."],
    emotional: ["I can't do this. I can't lose now.", "I'm so scared. Is that stupid?"],
    goofy: ["I'm nervous. When I'm nervous I eat. And there's no food. Big problem."],
    quiet: ["...I don't like this.", "Something's wrong."],
    teen: ["Okay this is actually scary.", "I'm lowkey freaking out.", "What if it's me? Like, actually?"],
    grown: ["I've been around long enough to know when something's off.", "I don't like the feel of today."],
  },
  // lightening the mood
  joke: {
    any: ["Well, at least the view is nice.", "Could be worse. Could be raining.", "Look on the bright side. There isn't one.", "This is fine. Everything is fine.", "I'd like to speak to the manager of this place."],
    dry: ["Another beautiful day in paradise.", "Love what they've done with the place. Nothing."],
    loud: ["Okay, who wants to hear my impression of the host?", "Party at my bunk! Bring nothing, because we have nothing!"],
    warm: ["Hey, at least we're miserable together.", "Group hug? No? Okay. Later."],
    theatrical: ["And the award for most miserable day goes to... all of us!", "This will make a wonderful chapter in my memoir."],
    anxious: ["Ha. Ha ha. Sorry. I laugh when I'm nervous.", "Is it bad if I'm laughing? I'm laughing."],
    calm: ["Eh. Tomorrow will be worse. That's something to look forward to."],
    nerdy: ["Fun fact: none of this is fun.", "On the bright side, we're building character. Lots of it."],
    goofy: ["I was going to tell a joke about the food, but it's too sad.", "What do you call a person on this show? Tired."],
    chaotic: ["What if we just set something on fire? For morale.", "I have an idea. It's terrible. Let's do it."],
    food: ["You know what would fix this? Literally any food.", "I'd trade my vote for a sandwich. I'm joking. Mostly."],
    flirty: ["Hey, at least you've got me to look at."],
    cruel: ["At least I'm not the one going home.", "Smile. You'll be gone soon anyway."],
    quiet: ["...Could be worse.", "Ha."],
    teen: ["This is so cursed.", "Okay this is lowkey funny.", "Not me laughing at this."],
    grown: ["When I was your age, we didn't do this for fun. We had jobs.", "My knees and I would like to file a complaint."],
  },
  // a friendly dig
  tease: {
    any: ["Nice one, genius.", "Smooth. Really smooth.", "Wow. Graceful.", "Are you always like this?", "You okay there?"],
    dry: ["Truly a great moment for you.", "I'm going to remember that forever."],
    loud: ["HA! Did everybody see that?!", "Oh, that's going on the highlight reel!"],
    warm: ["You're such a dork. I love it.", "Aw, you tried."],
    blunt: ["That was embarrassing.", "You look ridiculous."],
    theatrical: ["Bravo! Encore! Do it again, worse!"],
    cruel: ["Wow. Somehow you made it worse.", "That's the most useful you've been all week."],
    goofy: ["Ten out of ten. Would watch again.", "You fell with such style, though."],
    flirty: ["You're cute when you're embarrassed.", "Keep doing that. I'm enjoying it."],
    competitive: ["And that's why I'm winning.", "Keep up, slowpoke."],
    nerdy: ["Gravity: one. You: zero."],
    anxious: ["Are you okay? That looked bad. Also kind of funny. Sorry."],
    calm: ["Smooth.", "Nice landing."],
    schemer: ["Don't worry. Nobody saw that. Except everybody."],
    quiet: ["...Nice.", "Wow."],
    teen: ["Bro. BRO.", "That was so embarrassing for you.", "I'm screaming."],
    grown: ["Oh, to be young and that clumsy.", "I'd help, but this is funnier."],
  },
  // this place is terrible
  complain: {
    any: ["I'm so tired.", "My back is killing me.", "I haven't slept in days.", "Everything here is wet.", "I'm starving.", "Why is it always cold?"],
    dry: ["Five stars. Would not recommend.", "Wonderful. Another day of this."],
    loud: ["I am SO done with this place!", "Is there ANYTHING here that doesn't bite?"],
    warm: ["It's hard. But we'll get through it.", "I miss my family so much today."],
    blunt: ["This place is garbage.", "I hate it here."],
    theatrical: ["I was not built for this! I was built for room service!", "The suffering! The endless suffering!"],
    anxious: ["I keep hearing things at night.", "I think something crawled on me. Again."],
    calm: ["Bit rough today.", "Could be worse. Not much worse."],
    food: ["I'd do anything for a real meal. Anything.", "If I see that slop again, I'm going to cry."],
    nerdy: ["I'm pretty sure this is a health code violation.", "We're definitely not getting enough protein."],
    tough: ["Whatever. I've had worse.", "It's fine. I'm fine."],
    bossy: ["Somebody needs to fix the roof. And it won't be me."],
    emotional: ["I can't do another night like that. I can't.", "I just want to go home for one hour."],
    goofy: ["I've decided I live here now. I've given up."],
    proud: ["I deserve better than this. Frankly, everyone does, but mostly me."],
    quiet: ["...Cold.", "Tired."],
    teen: ["I literally can't with this place.", "I'd kill for my phone right now.", "This is so mid."],
    grown: ["I'm too old to sleep on the ground.", "My knees are not built for this."],
  },
  // this is amazing
  excited: {
    any: ["Yes! Yes!", "Let's go!", "This is amazing!", "No way! No way!", "Oh my gosh!", "Finally!"],
    dry: ["Wow. I'm actually happy. Weird.", "I'll allow it."],
    loud: ["LET'S GOOOO!", "WOOOO!", "Are you seeing this?!"],
    warm: ["I'm so happy for us!", "Oh, this is the best!"],
    theatrical: ["Glorious! Simply glorious!", "This is my moment!"],
    anxious: ["Wait, really? Really? Oh my gosh.", "I can't believe it worked!"],
    calm: ["Nice.", "That's pretty great."],
    competitive: ["That's what I'm talking about!", "Winning feels so good."],
    nerdy: ["That's statistically incredible!", "We did it! Against all odds!"],
    tough: ["Yeah! Good.", "About time."],
    emotional: ["I'm going to cry! Happy crying!", "This is the best day of my life!"],
    goofy: ["Victory dance! Everybody!", "I'm so happy I could eat a whole... anything."],
    proud: ["As expected.", "I knew I'd win."],
    quiet: ["...Nice.", "Huh. Good."],
    teen: ["No WAY!", "That's so sick!", "Let's goooo!"],
    grown: ["Well, how about that!", "Now that's more like it."],
  },
  // you were good
  impressed: {
    any: ["That was amazing.", "Okay, I'm impressed.", "Nice work.", "Where did that come from?", "You were great out there."],
    dry: ["Huh. You're not useless after all.", "Fine. That was good. Don't let it go to your head."],
    loud: ["You were INCREDIBLE!", "Did you SEE that?!"],
    warm: ["I'm so proud of you!", "You were so good! Seriously!"],
    blunt: ["Good job.", "You did well."],
    theatrical: ["A star is born!", "Magnificent!"],
    competitive: ["Not bad. Not as good as me, but not bad.", "Okay, you can stay."],
    schemer: ["You're a lot better than people think.", "Keep that up and people will notice. Careful."],
    cruel: ["Huh. I thought you'd be dead weight.", "You surprised me. Don't get used to it."],
    nerdy: ["That was efficient. Really efficient.", "Your technique was actually perfect."],
    tough: ["Good.", "Respect."],
    emotional: ["You were amazing! I'm actually tearing up!"],
    goofy: ["Teach me your ways!", "Who are you and what did you do with my teammate?"],
    quiet: ["Good job.", "...Nice."],
    teen: ["Okay that was actually so good.", "You're kind of cracked at this.", "That was sick."],
    grown: ["Well done. Really well done.", "You've got a real talent, you know that?"],
  },
  // whatever
  dismiss: {
    any: ["Whatever.", "Don't care.", "Okay. And?", "Sure. Moving on.", "That's nice.", "Noted."],
    dry: ["Fascinating. Truly.", "Thank you for sharing."],
    loud: ["Who CARES?!", "Ugh, whatever!"],
    warm: ["Okay, sweetie. Let's not worry about it."],
    blunt: ["Don't care.", "Doesn't matter."],
    theatrical: ["Boring! Next!", "I simply cannot be bothered."],
    calm: ["Eh. Doesn't matter.", "Okay."],
    schemer: ["Sure. If you say so.", "Of course. You're right."],
    cruel: ["Nobody asked.", "Wow, I really don't care."],
    tough: ["So?", "Whatever."],
    proud: ["I'm above this.", "That's beneath me."],
    anxious: ["Okay. Sure. I'm not going to think about it. I'm going to think about it."],
    competitive: ["Doesn't matter. Focus on the next one."],
    nerdy: ["Irrelevant.", "That has nothing to do with anything."],
    goofy: ["Cool cool cool. Anyway."],
    quiet: ["...Okay.", "Mm."],
    teen: ["Okay, and?", "Cool story.", "Literally nobody asked."],
    grown: ["I don't have the energy for this.", "Let it go."],
  },
};
