// ══════════════════════════════════════════════════════════════════════
// td/story/phrases/core5.js — the vote's end: shock, goodbyes, parting shots, last words
// ══════════════════════════════════════════════════════════════════════
// The user: last words in their own voice too. Same rules as core1-4: attitude, no facts, {to}
// is the person spoken to.

export default {
  // the name is read and it's me
  shocked: {
    any: ["Wait. What?", "No. No, that's not right.", "Me? Seriously?", "You're kidding.", "...Oh.", "Are you serious right now?"],
    dry: ["Huh. Well, that's not how I saw tonight going.", "Oh, great, good for you all."],
    loud: ["WHAT?! No way! No WAY!", "Are you kidding me?!"],
    warm: ["Oh. Oh, okay. I didn't think...", "I really thought we were okay."],
    blunt: ["Wow, okay, that's it, then.", "Fine. You got me."],
    theatrical: ["Betrayed! Utterly betrayed!", "This cannot be happening!"],
    anxious: ["Me? No. No no no. Me?", "I knew it. I knew it was going to be me."],
    calm: ["Huh. Okay.", "Well. That's that."],
    competitive: ["You're making a huge mistake.", "Wow. You'd rather lose challenges than keep me?"],
    schemer: ["Well played. Whoever it was.", "I didn't see that. I should have."],
    cruel: ["Cowards. Every one of you.", "You'll regret this. All of you."],
    chaotic: ["Ha! Okay! Didn't see that coming! Cool cool cool."],
    food: ["Do I at least get dinner first?"],
    ditzy: ["Wait, is that me? That's me? Oh."],
    nerdy: ["That defies every calculation I made.", "Statistically, that shouldn't have happened."],
    earnest: ["I hope you know what you're doing.", "Okay, I respect it, I just don't like it."],
    tough: ["Whatever.", "Fine. Your loss."],
    emotional: ["No! I'm not ready! I'm not ready to go!", "I can't believe this. I really can't."],
    goofy: ["Aw, man. I was just getting good at this."],
    proud: ["You've just voted out the best player here.", "Unbelievable. Truly."],
    flirty: ["Really? You're going to miss me."],
    bossy: ["Who organised this? I want names."],
    quiet: ["...Okay.", "Oh."],
    teen: ["Wait, are you being for real?", "Oh my god. Me? Seriously?", "This is so unfair."],
    adult: ["Wow, okay, I really didn't see that coming.", "Huh. Not how I pictured tonight."],
    grown: ["Well, I've had worse days. Not many, but I have.", "I suppose I'm too old for this game anyway."],
  },
  // to their person, on the way out
  goodbye: {
    any: ["Win this for me, okay?", "Don't let them get to you.", "I'm going to miss you.", "Go all the way. Promise me.", "Take care of yourself.", "You've got this."],
    dry: ["Try not to lose without me. It'll be hard.", "Don't get sentimental. Okay, a little."],
    loud: ["You'd BETTER win this! I'm serious!", "Win it! Win the whole thing!"],
    warm: ["Come here. I'm going to miss you so much.", "You're the best part of this whole thing. Win it."],
    blunt: ["Win. That's all.", "Don't trust them. Win."],
    theatrical: ["Go forth and conquer in my name!", "Avenge me!"],
    anxious: ["Be careful, okay? Please be careful.", "Don't let them do this to you too."],
    calm: ["You'll be fine. Go get it.", "See you at the end."],
    competitive: ["Win every challenge. Make them sorry.", "Beat all of them. For both of us."],
    schemer: ["Trust nobody. Not even the nice ones.", "Watch your back. I'll be watching too."],
    cruel: ["Don't embarrass me out there.", "Win. Then rub it in their faces."],
    nerdy: ["Run the numbers before every vote. Every single one.", "You're smarter than all of them. Use it."],
    earnest: ["I'm proud of you. Keep being you.", "Play it the right way. Like we said."],
    tough: ["Stay tough.", "Don't let them break you."],
    emotional: ["I love you, okay? I'll be watching every second.", "I can't believe I have to go without you."],
    goofy: ["Bring me back a souvenir. Like, the money."],
    flirty: ["Don't forget about me. I mean it."],
    bossy: ["Stick to the plan. Don't improvise.", "You know what to do. Do it."],
    proud: ["You're the only one here worth anything. Win."],
    quiet: ["...Win it.", "Bye."],
    teen: ["Okay, you have to win now. Like, actually.", "I'm gonna miss you so much.", "Win it for me, okay?"],
    grown: ["You're going to be just fine. I know it.", "Take care of yourself, kiddo. Win this."],
  },
  // a dig at the one they blame
  shot: {
    any: ["Enjoy it while it lasts.", "You're next.", "Hope it was worth it.", "Everybody knows what you did.", "Good luck sleeping tonight."],
    dry: ["Congratulations. You're the villain now.", "Enjoy being the next easy vote."],
    loud: ["You're NEXT! You hear me?!", "I hope they vote you out NEXT!"],
    warm: ["I hope you can live with that.", "I really thought you were better than that."],
    blunt: ["You're a snake. Everybody knows it.", "I'll be voting for you from home."],
    theatrical: ["History will remember your betrayal!", "Mark my words. Your time is coming."],
    anxious: ["I hope you feel bad. I hope you feel really bad."],
    calm: ["Watch your back.", "That's going to cost you."],
    competitive: ["Have fun losing challenges without me.", "You just lost your best shot at winning."],
    schemer: ["Tell them what you did. I'll wait.", "They'll find out who you are. Soon."],
    cruel: ["Nobody likes you. Just so you know.", "You'll be gone in a week."],
    chaotic: ["I'm going to haunt you! Spiritually!"],
    tough: ["This isn't over.", "See you on the other side."],
    emotional: ["How could you do this to me?!"],
    proud: ["You'll never be as good as me.", "Remember who you beat. It won't happen again."],
    quiet: ["...You.", "Enjoy it."],
    teen: ["You're literally so fake.", "Everyone knows you're a snake."],
    grown: ["I've met people like you before. It never ends well for them.", "You'll understand someday what you just did."],
  },
  // the last thing they say on the way out, to the camera
  parting: {
    any: ["I gave it everything I had.", "No regrets. Well, a few.", "I'll be watching.", "It was fun while it lasted.", "I'm proud of how I played.", "Next time, I'm winning."],
    dry: ["Well. That was a lot of work for a trip home.", "I'll miss the food. That's a lie."],
    loud: ["I'm going out loud and proud!", "You haven't heard the last of me!"],
    warm: ["I made real friends here. That's what I'm taking home.", "I'm sad. But I'm so glad I did this."],
    blunt: ["I lost. That's it.", "They got me. Good for them."],
    theatrical: ["Remember me! Remember my name!", "And so ends a legend."],
    anxious: ["I lasted longer than I thought I would. That's something, right?"],
    calm: ["It's okay, it's a game, and I played it.", "Not my week. That's fine."],
    competitive: ["I'll be back. And I'll win.", "I hate losing. I really hate losing."],
    schemer: ["I'm not sorry about a single move I made.", "I played them and they played me back, so that's fair."],
    cruel: ["They'll miss me when they're losing.", "Good riddance to all of them."],
    chaotic: ["Well, that was a ride! Ten out of ten!"],
    food: ["The first thing I'm doing is eating a real meal."],
    nerdy: ["My models were off by one vote. One."],
    earnest: ["I played it my way. I'm proud of that.", "I wouldn't change how I played. Not one thing."],
    tough: ["I'm not crying. Don't film me crying.", "Whatever. I'll survive."],
    emotional: ["I'm going to miss everybody so much.", "I can't believe it's over."],
    goofy: ["Well, at least I'll finally get a shower."],
    proud: ["They voted out the best player. Their problem.", "I was the best thing about this season."],
    quiet: ["...It was good.", "That's all."],
    teen: ["Honestly? Best summer ever.", "I'm so sad, but this was so cool.", "I can't wait to tell everybody back home."],
    grown: ["Not bad for someone my age.", "I'll take the experience home. And a sore back."],
  },
  // the friend left behind, after
  mourn: {
    any: ["I can't believe they're gone.", "It's not the same without them.", "I didn't even get to say goodbye properly.", "That one hurt.", "Camp is going to feel so empty now."],
    dry: ["Well. Now I have to talk to the rest of these people.", "Great. My one ally is gone."],
    loud: ["Whoever did that is going to PAY!", "I'm so mad I could scream!"],
    warm: ["I miss them already.", "They were the best person here."],
    blunt: ["That was a mistake. Theirs.", "I'm on my own now."],
    theatrical: ["My partner! Taken from me!", "I will avenge you!"],
    anxious: ["What do I do now? I don't know what to do now."],
    calm: ["It is what happened. I'll keep going.", "Okay. New plan."],
    competitive: ["Now it's personal.", "Fine. I'll win it for both of us."],
    schemer: ["I know who did it. I'll be patient.", "They just showed me who they are."],
    cruel: ["They'll regret it. Every one of them."],
    tough: ["I'll be fine.", "Doesn't change anything."],
    emotional: ["I can't stop crying. I can't.", "Why does it hurt this much?"],
    earnest: ["I'm going to keep playing the way they'd want."],
    nerdy: ["I lost my only reliable vote. Recalculating."],
    quiet: ["...", "Miss them."],
    teen: ["This is literally the worst.", "I'm not okay."],
    grown: ["I've lost people before. It doesn't get easier.", "Hard night. Tomorrow I get back to work."],
  },
  // the one who did it, after
  gloat: {
    any: ["That went exactly how I wanted.", "One down.", "Nobody saw that coming.", "That's how you do it.", "Tonight was a good night."],
    dry: ["Well. That was satisfying.", "I'd say I feel bad. I'd be lying."],
    loud: ["YES! Did you see their face?!", "That's how it's DONE!"],
    warm: ["I feel bad, I really do, but I'm still here."],
    blunt: ["Had to happen.", "Done. Next."],
    theatrical: ["A masterpiece! A blindside for the ages!"],
    anxious: ["It worked. Oh my gosh, it actually worked."],
    calm: ["Clean vote.", "Exactly as planned."],
    competitive: ["One less person to beat.", "Biggest threat, gone."],
    schemer: ["They never saw me coming.", "That was my move. Nobody knows it yet."],
    cruel: ["Bye. Won't miss you.", "Best night here so far."],
    nerdy: ["Exactly as projected.", "The plan held."],
    tough: ["Good riddance.", "Next."],
    proud: ["I run this game.", "Another one, thanks to me."],
    quiet: ["...Good.", "Done."],
    teen: ["Okay, that was kind of iconic.", "Bye bye!"],
    grown: ["I've been playing people since before most of them were born.", "I just waited for the right time, that's all I did."],
  },
};
