// ══════════════════════════════════════════════════════════════════════
// td/story/phrases/core4.js — more voices for the moves that had fewest
// ══════════════════════════════════════════════════════════════════════
// Merged into the same moves as core1-3 (phrases/index.js adds lists together).

export default {
  'pushback.lead': {
    theatrical: ["Oh, so now you're the director? Please.", "I don't recall auditioning you for leader."],
    anxious: ["Um, should we maybe vote on who's in charge?", "I'm not saying you can't lead, I'm just asking... who decided?"],
    calm: ["Easy. Nobody picked a leader yet.", "Let's not crown anybody on day one."],
    schemer: ["Taking charge this early? That's a bold move.", "Lead all you want. People remember who bossed them around."],
    nerdy: ["There's no evidence you're the most qualified.", "Leadership should be decided by competence. So, not you."],
    earnest: ["I think we should all get a say.", "It's not fair if one person decides everything."],
    bossy: ["No, I'm running this, so sit down.", "Cute. I was already in charge."],
    emotional: ["Why do you always get to decide?!", "Nobody ever asks what I think!"],
    goofy: ["Oh, all hail the new boss, I guess. No."],
    proud: ["You, leading us? Sorry, I laughed.", "I've led bigger teams than this. You haven't."],
  },
  joke: {
    blunt: ["Well, that was a disaster. Funny, though."],
    competitive: ["At least somebody here is having a worse day than me. Probably."],
    schemer: ["Don't worry. If this goes badly, I'll blame someone else."],
    ditzy: ["Wait, is this the part where we laugh? Ha!"],
    earnest: ["Okay, I'm going to try a joke. Why did the camper cross the road? To get away from this conversation. ...I tried."],
    tough: ["You call this rough? My little brother's tougher."],
    bossy: ["New rule, no more sad faces, and that's an order. Ha."],
    emotional: ["I'm laughing so I don't cry, and it's mostly working."],
    proud: ["I'd make a joke, but it would be too clever for this crowd."],
  },
  excited: {
    blunt: ["Good. That's how it should be.", "Yes. Finally."],
    schemer: ["Perfect. This is going exactly how I wanted.", "Oh, that's very good news."],
    cruel: ["Ha! Take that!", "Did you see their faces?"],
    chaotic: ["WOOOO! Something exploded! Not literally! Maybe literally!"],
    food: ["This calls for a celebration snack!", "We should celebrate with food! Is there food?"],
    ditzy: ["Yay! Wait, what happened? Yay anyway!"],
    earnest: ["We did it! All of us! I'm so proud of us!"],
    flirty: ["Okay, that was hot. Winning is hot."],
    bossy: ["See? That's what happens when you listen to me!"],
  },
  impressed: {
    anxious: ["Wow, how did you even do that? I'd have panicked."],
    calm: ["Nice. Really nice.", "That was clean."],
    chaotic: ["That was insane! Do it again! Do it worse!"],
    food: ["You deserve a whole cake for that. I'd eat half of it."],
    ditzy: ["Wow, you're like a superhero! A sweaty one, but still!"],
    earnest: ["You really earned that. I mean it."],
    flirty: ["Okay, that was really impressive. And kind of attractive."],
    bossy: ["Good. That's exactly how I'd have done it."],
    proud: ["I suppose that was almost as good as I would have done."],
  },
  suspicious: {
    cruel: ["What are you hiding? You're terrible at hiding things.", "You think I'm stupid?"],
    chaotic: ["Ooh, you're up to something! Tell me! I love schemes!"],
    food: ["You're being way too nice. Did you steal my food?"],
    ditzy: ["Wait, are you lying? You have a lying face. Or is that your normal face?"],
    earnest: ["Please just tell me the truth. I can handle it."],
    flirty: ["You're being all mysterious, and I like it, but I don't trust it."],
    bossy: ["Explain. Now.", "I want to know exactly where you were."],
    goofy: ["I'm watching you, just so you know."],
    proud: ["I can see right through you.", "Don't insult me with that story."],
  },
  confide: {
    theatrical: ["Come closer. What I'm about to tell you is classified.", "Swear on your life you won't repeat this."],
    calm: ["Got a second?", "I want to run something by you."],
    competitive: ["I'm going to tell you something that could change the game.", "Listen. This matters."],
    cruel: ["I'm telling you this because you're the least annoying person here.", "Don't make me regret this."],
    chaotic: ["Okay, I have a secret, and it's burning a hole in my brain."],
    food: ["I'll tell you a secret if you give me your dessert. Kidding. Mostly."],
    ditzy: ["Okay, so I have a secret, and I'm really bad at secrets, so listen fast."],
    earnest: ["I want to be honest with you about something.", "I don't want to keep anything from you."],
    flirty: ["Can I tell you something only you get to know?"],
    bossy: ["You need to hear this. Sit."],
    goofy: ["Psst, secret meeting, just you and me."],
    proud: ["I don't tell many people this. Consider yourself chosen."],
  },
  greet: {
    competitive: ["Hey. You any good?", "So you're the competition."],
    schemer: ["Hi! I've heard so much about you, all good things.", "There you are. I was hoping we'd meet."],
    cruel: ["Oh. You.", "Hi. Don't get comfortable."],
    chaotic: ["HELLO, new friend! Do you like explosions?"],
    food: ["Hi! Do you have any snacks? No? Well, hi anyway."],
    ditzy: ["Hiii! Wait, have we met? We should meet!"],
    nerdy: ["Hello. Statistically we were bound to meet."],
    earnest: ["Hi, I'm {by}. It's really nice to meet you."],
    bossy: ["Hi. You'll want to stick close to me."],
    emotional: ["Hi! Sorry, I'm a hugger. Can I? Thank you!"],
    proud: ["You may have heard of me.", "Hello, I'm {by}, and trust me, you'll remember that."],
  },
  thanks: {
    calm: ["Thanks. Appreciate it.", "Cool. Thank you."],
    cruel: ["Fine, thanks, just don't make it a thing."],
    chaotic: ["THANK YOU! I owe you one weird favour!"],
    food: ["Thank you! I'm going to repay you in snacks."],
    ditzy: ["Thank you! You're like the nicest person ever!"],
    nerdy: ["Thank you. That was statistically very kind."],
    earnest: ["Thank you. I won't forget it, I promise."],
    flirty: ["Thanks. I'll find a way to pay you back."],
    bossy: ["Good, thanks, keep it up."],
    goofy: ["You're a hero! A weird hero! Thank you!"],
  },
  apologize: {
    competitive: ["Sorry, I get intense, it's not about you."],
    cruel: ["Fine, I'm sorry. Happy now?"],
    chaotic: ["I'm sorry! I don't know what came over me! It was me. Me came over me."],
    food: ["I'm sorry. I'm cranky when I'm hungry, and I'm always hungry here."],
    ditzy: ["I'm so sorry! I didn't even know I did it!"],
    nerdy: ["I was wrong. That's rare, so enjoy it."],
    earnest: ["I'm really sorry. You didn't deserve that."],
    flirty: ["Sorry. Let me make it up to you."],
    bossy: ["Fine, I was harsh, but I'm still right."],
    goofy: ["Sorry! Forgive me? Pretty please?"],
  },
  sad: {
    competitive: ["I hate losing. I really hate it.", "That one's going to bug me for days."],
    schemer: ["That changes things. I don't like it."],
    cruel: ["Ugh, whatever, it doesn't matter."],
    chaotic: ["Well, that's a bummer. A big one."],
    food: ["I need comfort food, and there is no comfort food, which makes it so much worse."],
    ditzy: ["Wait, so that's it? Like, it's over? Aw."],
    nerdy: ["I calculated this outcome. I hoped I was wrong."],
    earnest: ["I really believed we could do it.", "I'm just disappointed. In me, mostly."],
    flirty: ["I could use a hug right now. Just saying."],
    bossy: ["That's not how that was supposed to go.", "We have to be better than that."],
    proud: ["I don't lose. This was an exception."],
  },
  angry: {
    competitive: ["I'm so sick of losing!", "We had that! We HAD that!"],
    schemer: ["Fine. Now I'm paying attention.", "That was a mistake. Theirs."],
    chaotic: ["I'm going to scream into a bucket. Who has a bucket?"],
    food: ["I'm angry AND hungry. Nobody talk to me."],
    ditzy: ["I'm mad! I think. Yes. I'm mad!"],
    nerdy: ["That was illogical, unfair, and frankly insulting."],
    earnest: ["That's not right, and I'm not going to pretend it is."],
    flirty: ["Wow. That was not cute."],
    bossy: ["Unacceptable. Completely unacceptable.", "Everybody stop. Now."],
    goofy: ["I'm so angry I could... eat something. Angrily."],
  },
  stall: {
    theatrical: ["A decision this big deserves time!", "Let me sleep on it. Dramatically."],
    competitive: ["I'll decide when I know it helps me win."],
    cruel: ["Maybe. If I feel like it."],
    chaotic: ["Ask me again in five minutes! I'll have a totally different answer!"],
    food: ["Let me think about it over lunch. If there's lunch."],
    ditzy: ["Ooh, a decision. Can I decide later? I'm bad at now."],
    earnest: ["I want to make the right choice. Give me a little time."],
    flirty: ["Maybe. Convince me."],
    bossy: ["I'll tell you when I've decided."],
    emotional: ["I can't decide right now! It's too much!"],
    goofy: ["Hmm, let me think about it. My brain's asleep, though."],
    proud: ["I'll let you know if you're worth it."],
  },
};
