// pm/lines/challenges.js — the villa's named challenges (Plan 4.5 phase 4).
// Data only. Every scene's cast, from pm/challenges.js, and what it decided:
//
//   challenge-text [a]          a reads out the text that starts the game (`of`: which).
//   receipt        [a, b, c, (d)] a reads a card about c and kisses b as the
//                                  guess (`guessed`: b is c). `of` is what the
//                                  card says: secret / pull / head-turned / ick /
//                                  row (with d) / love (said it to d).
//                                  d is c's partner (`cast` 4).
//   look-who       [a, b, c]     a reads out {quote}, which b said in the beach
//                                  hut about c. `guessed`; `of` two-faced / warm
//                                  (b likes c) / cold (b doesn't) / plain.
//   snogger-kiss   [a, b]        blindfolded b gives a's kiss the day's best
//                                  score (`of` ten / nine / high: eight or less).
//   snogger-win    [a, b]        a wins the Sauciest Snogger; b came second.
//   snogger-row    [a, b, c]     a's partner b scored c's kiss higher (`of` big: three points or more / small: two).
//   couple-goals   [a, b, c, d]  couple a and b wrote couple c and d on the
//                                  board (`of` marry / fake / break); `guessed`:
//                                  most of the boards said the same.
//   couple-goals-row [a, b, c]   a (with partner c) confronts b, a friend who
//                                  wrote them down (`of` fake / break).
//   knowing-me     [a, b]        a couple's score (`of` high / mid / low).
//   knowing-row    [a, b]        a wrote b as the one more likely to stray
//                                  (`of` guilty: b is hiding something / hurt).
//   talent-act     [a] / [a, b]  `of` flop: a's act goes wrong; duet: a and b.
//   talent-win     [a, (b)]      a wins; b is a's partner (`coupled`).
//   talent-snub    [a, b, c]     a's partner b voted for c's act, not a's.
//   baby-doll      [a, b]        `of` team / left-it (a did it all, b didn't) / lost.
//   sorts-podium   [a, b]        the public's order (`of` top / wrong / least);
//                                  `guessed`: they stood on the right podium.
//   grafties-award [a, (b)]      the public's awards (`of` couple / grafter /
//                                  least); b is a's partner (`coupled`).
//
// Nobody hosts a challenge: a text sets it up and the islanders run it.
import { LIE_LINES } from './lie-detector.js';
import { MORE_CHALLENGE_LINES } from './challenges-more.js';
export const CHALLENGE_LINES = {
  'challenge-text': [
    { id: 'challenge-text.receipts.1', when: { of: 'receipts' },
      stage: 'A text arrives, and {a} reads it out.',
      turns: [['a', "Islanders, the cameras have been keeping receipts. Today you'll find out who they belong to. #GotTheReceipts"], ['a', "Oh no. What have we all done?"]] },
    { id: 'challenge-text.receipts.2', when: { of: 'receipts' },
      stage: 'A text arrives, and {a} reads it out.',
      turns: [['a', "Islanders, the cameras have been keeping receipts. Today you'll find out who they belong to. #GotTheReceipts"], ['a', "Right. Everybody stay calm."]] },
    { id: 'challenge-text.look-who.1', when: { of: 'look-who' },
      stage: 'A text arrives, and {a} reads it out.',
      turns: [['a', "Islanders, it's time to find out who's been saying what about who. #LookWhosTalking"], ['a', "I've said so much in that beach hut."]] },
    { id: 'challenge-text.look-who.2', when: { of: 'look-who' },
      stage: 'A text arrives, and {a} reads it out.',
      turns: [['a', "Islanders, it's time to find out who's been saying what about who. #LookWhosTalking"], ['a', "Why is everyone looking at me?"]] },
    { id: 'challenge-text.snogger.1', when: { of: 'snogger' },
      stage: 'A text arrives, and {a} reads it out.',
      turns: [['a', "Girls, the boys will be blindfolded, and you'll be kissing every one of them. The boys will score each kiss out of ten. #SauciestSnogger"], ['a', "Okay. I'm ready. I was born ready."]] },
    { id: 'challenge-text.snogger.2', when: { of: 'snogger' },
      stage: 'A text arrives, and {a} reads it out.',
      turns: [['a', "Girls, the boys will be blindfolded, and you'll be kissing every one of them. The boys will score each kiss out of ten. #SauciestSnogger"], ['a', "Out of ten? Out loud? Oh my God."]] },
    { id: 'challenge-text.couple-goals.1', when: { of: 'couple-goals' },
      stage: 'A text arrives, and {a} reads it out.',
      turns: [['a', "Islanders, today you'll find out what the other couples really think of you. #CoupleGoals"], ['a', "This is going to cause so many arguments."]] },
    { id: 'challenge-text.couple-goals.2', when: { of: 'couple-goals' },
      stage: 'A text arrives, and {a} reads it out.',
      turns: [['a', "Islanders, today you'll find out what the other couples really think of you. #CoupleGoals"], ['a', "Be nice, everyone. Please be nice."]] },
    { id: 'challenge-text.knowing-me.1', when: { of: 'knowing-me' },
      stage: 'A text arrives, and {a} reads it out.',
      turns: [['a', "Islanders, it's time to find out how well you really know your partner. #KnowingMeKnowingYou"], ['a', "We've got this. We've definitely got this."]] },
    { id: 'challenge-text.knowing-me.2', when: { of: 'knowing-me' },
      stage: 'A text arrives, and {a} reads it out.',
      turns: [['a', "Islanders, it's time to find out how well you really know your partner. #KnowingMeKnowingYou"], ['a', "What if I don't know their middle name?"]] },
    { id: 'challenge-text.talent.1', when: { of: 'talent' },
      stage: 'A text arrives, and {a} reads it out.',
      turns: [['a', "Islanders, tonight the villa is putting on a talent show, and you'll be voting for the winner. #VillaGotTalent"], ['a', "I don't have a talent. What's my talent?"]] },
    { id: 'challenge-text.talent.2', when: { of: 'talent' },
      stage: 'A text arrives, and {a} reads it out.',
      turns: [['a', "Islanders, tonight the villa is putting on a talent show, and you'll be voting for the winner. #VillaGotTalent"], ['a', "Finally. I've been waiting for this."]] },
    { id: 'challenge-text.baby.1', when: { of: 'baby' },
      stage: 'A text arrives, and {a} reads it out.',
      turns: [['a', "Islanders, you're about to become parents. Look after your baby day and night. #VillaBabies"], ['a', "A baby? A whole baby?"]] },
    { id: 'challenge-text.baby.2', when: { of: 'baby' },
      stage: 'A text arrives, and {a} reads it out.',
      turns: [['a', "Islanders, you're about to become parents. Look after your baby day and night. #VillaBabies"], ['a', "I'm going to be such a good parent."]] },
    { id: 'challenge-text.couple-of-sorts.1', when: { of: 'couple-of-sorts' },
      stage: 'A text arrives, and {a} reads it out.',
      turns: [['a', "Islanders, the public have ranked your couples. Now stand where you think you came. #CoupleOfSorts"], ['a', "The public? This is terrifying."]] },
    { id: 'challenge-text.couple-of-sorts.2', when: { of: 'couple-of-sorts' },
      stage: 'A text arrives, and {a} reads it out.',
      turns: [['a', "Islanders, the public have ranked your couples. Now stand where you think you came. #CoupleOfSorts"], ['a', "Please don't let us be last."]] },
    { id: 'challenge-text.grafties.1', when: { of: 'grafties' },
      stage: 'A text arrives, and {a} reads it out.',
      turns: [['a', "Islanders, tonight is the Grafties, and the public have voted for every award. #TheGrafties"], ['a', "An awards night! Everyone get dressed up."]] },
    { id: 'challenge-text.grafties.2', when: { of: 'grafties' },
      stage: 'A text arrives, and {a} reads it out.',
      turns: [['a', "Islanders, tonight is the Grafties, and the public have voted for every award. #TheGrafties"], ['a', "I've already written my speech."]] },
  ],
  receipt: [
    { id: 'receipt.01', when: { of: 'secret', guessed: true },
      stage: '{a} reads the card out loud: "This islander has kissed someone behind their partner\'s back." {a} walks straight over to {c}, and kisses {c.obj}.',
      turns: [['a', "I'm sorry. I've just got a feeling about you."], ['c', "…Yeah. It's me."]],
      beat: '{d} gets up and walks off to the kitchen.' },
    { id: 'receipt.02', when: { of: 'secret', guessed: true, knows: true },
      stage: 'The card says: "This islander has kissed someone behind their partner\'s back." {a} doesn\'t even look at anyone else. {a} goes to {c}.',
      turns: [['c', "Why me? Why would you pick me?"], ['a', "Because I saw it."]],
      beat: 'The card is turned over, and it says {c}. {d} stares at {c}.' },
    { id: 'receipt.03', when: { of: 'secret', guessed: false },
      stage: 'The card says: "This islander has kissed someone behind their partner\'s back." {a} thinks for a long time, then kisses {b}.',
      turns: [['b', "Me? I haven't done anything!"], ['a', "Then who was it?"]],
      beat: 'The card is turned over. It says {c}. {d} looks at {c}, and {c} can\'t look back.' },
    { id: 'receipt.04', when: { of: 'secret', guessed: false },
      stage: '"This islander has kissed someone behind their partner\'s back." {a} picks {b}, and gives {b.obj} a kiss.',
      turns: [['b', "It wasn't me. I promise you it wasn't me."]],
      beat: 'It was {c}. The whole villa goes quiet, and {d} asks {c} to go for a chat.' },
    { id: 'receipt.05', when: { of: 'pull', guessed: true, cast: 4 },
      stage: 'The card: "This islander has pulled someone for a chat while they were coupled up." {a} goes straight to {c}.',
      turns: [['c', "It was just a chat!"], ['a', "That's what the card says, isn't it."]],
      beat: '{d} raises an eyebrow at {c}.' },
    { id: 'receipt.06', when: { of: 'pull', guessed: false, cast: 4 },
      stage: 'The card: "This islander has pulled someone for a chat while they were coupled up." {a} guesses {b}, and kisses {b.obj}.',
      turns: [['b', "I've been with my partner all week!"], ['a', "Sorry! Worth a try."]],
      beat: 'The answer is {c}. {d} turns to {c}: "Who did you pull?"' },
    { id: 'receipt.07', when: { of: 'pull', guessed: true },
      stage: '"This islander has pulled someone for a chat while they were coupled up." {a} kisses {c} without a second thought.',
      turns: [['c', "Okay, fine. I had a chat. Everyone has chats."]] },
    { id: 'receipt.08', when: { of: 'pull', guessed: false },
      stage: '"This islander has pulled someone for a chat while they were coupled up." {a} goes for {b}.',
      turns: [['b', "Not me! Honestly, not me."]],
      beat: 'The card is turned over, and it says {c}.' },
    { id: 'receipt.09', when: { of: 'head-turned', guessed: true },
      stage: '{a} reads: "This islander has said their head has been turned." {a} walks over to {c}.',
      turns: [['c', "I said I was confused. That's not the same thing."], ['a', "It kind of is."]] },
    { id: 'receipt.10', when: { of: 'head-turned', guessed: true, cast: 4 },
      stage: '"This islander has said their head has been turned." {a} kisses {c}, and the card says {c}.',
      turns: [['c', "I was going to talk to you about it."]],
      beat: '{d} goes very quiet for the rest of the game.' },
    { id: 'receipt.11', when: { of: 'head-turned', guessed: false },
      stage: '"This islander has said their head has been turned." {a} guesses {b}, and kisses {b.obj}.',
      turns: [['b', "My head is exactly where it should be, thank you."]],
      beat: 'The answer is {c}, who stares at the floor.' },
    { id: 'receipt.12', when: { of: 'ick', guessed: true },
      stage: '{a} reads: "This islander has had the ick about someone in the villa." {a} kisses {c}.',
      turns: [['c', "Okay, yes. It's one little thing. I'm not saying who."], ['a', "Everyone is going to ask you who."]] },
    { id: 'receipt.13', when: { of: 'ick', guessed: false },
      stage: '"This islander has had the ick about someone in the villa." {a} goes for {b}.',
      turns: [['b', "I never get the ick. I'm very easy to please."]],
      beat: 'The card says {c}. Everyone starts guessing who it was about.' },
    { id: 'receipt.15', when: { of: 'secret', guessed: true },
      stage: 'The next card: "This islander has kissed someone behind their partner\'s back." {a} takes a breath, and kisses {c}.',
      turns: [['c', "Can we not do this here?"]],
      beat: 'The card is turned over. It says {c}. {d} gets up without a word.' },
    { id: 'receipt.16', when: { of: 'pull', guessed: true },
      stage: 'The next card: "This islander has pulled someone for a chat while they were coupled up." {a} points at {c} before anyone else can.',
      turns: [['a', "It's you. It's got to be you."], ['c', "We were just talking!"]] },
    { id: 'receipt.17', when: { of: 'pull', guessed: false },
      stage: 'The next card: "This islander has pulled someone for a chat while they were coupled up." {a} goes for {b}, and gets it wrong.',
      turns: [['b', "I don't even pull my own partner for chats."]],
      beat: 'It was {c}.' },
    { id: 'receipt.18', when: { of: 'pull', guessed: true, cast: 4 },
      stage: '"This islander has pulled someone for a chat while they were coupled up." {a} kisses {c}, and {c} doesn\'t argue.',
      turns: [['c', "I'm not going to lie about it. I had a chat."]],
      beat: '{d} wants to know who with.' },
    { id: 'receipt.19', when: { of: 'head-turned', guessed: false },
      stage: '{a} reads: "This islander has said their head has been turned." {a} picks {b}.',
      turns: [['b', "Not me. I'm very happy, thank you."]],
      beat: 'The card says {c}, and {c} tries to laugh.' },
    { id: 'receipt.20', when: { of: 'ick', guessed: true },
      stage: 'The next card: "This islander has had the ick about someone in the villa." {a} goes for {c}.',
      turns: [['c', "How did you know?"], ['a', "Lucky guess. You've gone very quiet about someone."]] },
    { id: 'receipt.21', when: { of: 'row', guessed: true },
      stage: '{a} reads: "This islander has had a row with their partner this week." {a} kisses {c}.',
      turns: [['c', "We've sorted it! We're fine now."], ['a', "That's not what the card asked."]],
      beat: '{d} and {c} share a look.' },
    { id: 'receipt.26', when: { of: 'row', guessed: true },
      stage: 'The next card: "This islander has had a row with their partner this week." {a} kisses {c} straight away.',
      turns: [['c', "Everyone heard that one, didn't they?"], ['a', "The whole villa heard it."]] },
    { id: 'receipt.27', when: { of: 'row', guessed: true },
      stage: '"This islander has had a row with their partner this week." {a} picks {c}, and the card agrees.',
      turns: [['c', "It was a disagreement. It wasn't a row."]],
      beat: '{d} laughs, and doesn\'t correct {c.obj}.' },
    { id: 'receipt.22', when: { of: 'row', guessed: false },
      stage: '"This islander has had a row with their partner this week." {a} guesses {b}.',
      turns: [['b', "We never argue. We're boring like that."]],
      beat: 'The card says {c}. {c} and {d} both start explaining at once.' },
    { id: 'receipt.23', when: { of: 'love', guessed: true },
      stage: '{a} reads: "This islander has told their partner they\'re falling for them." {a} goes straight to {c}.',
      turns: [['c', "Okay, yes. I said it. I meant it, too."]],
      beat: '{d} goes bright red. The whole villa goes "aww".' },
    { id: 'receipt.24', when: { of: 'love', guessed: false },
      stage: '"This islander has told their partner they\'re falling for them." {a} kisses {b}.',
      turns: [['b', "I wish! Not yet."]],
      beat: 'It was {c}. {d} grins, and pulls {c} in for a kiss.' },
    { id: 'receipt.25', when: { of: 'love', guessed: true },
      stage: 'The last card is a nice one: "This islander has told their partner they\'re falling for them." {a} kisses {c}.',
      turns: [['c', "Guilty. And I'd say it again."]],
      beat: '{d} can\'t stop smiling.' },
    { id: 'receipt.14', when: { guessed: false, taken: true },
      stage: '{a} has no idea who the card is about, so {a} takes a guess and kisses {b}.',
      turns: [['a', "I didn't know! I had to kiss someone."], ['b', "I'm not complaining."]],
      beat: "{pa} isn't laughing. The card says {c}." },
  ],
  'look-who': [
    { id: 'look-who.01', when: { guessed: true, of: 'two-faced' },
      stage: '{a} picks a card and reads it out: "{quote}"',
      turns: [['a', "That's {b}. That's so obviously {b}."], ['b', "…Okay. Yes. That was me."]],
      beat: '{c} turns round slowly to look at {b}.' },
    { id: 'look-who.02', when: { guessed: false, of: 'two-faced' },
      stage: '{a} reads the next card: "{quote}"',
      turns: [['a', "I genuinely have no idea who said that."]],
      beat: 'The answer is {b}. {c} looks at {b} for a long moment, and {b} tries to laugh it off.' },
    { id: 'look-who.03', when: { of: 'two-faced' },
      stage: 'The next quote is read out: "{quote}" Everyone looks around.',
      turns: [['c', "Hang on. That's about me."], ['b', "It sounds worse than it was."]],
      beat: "{c} doesn't look convinced." },
    { id: 'look-who.04', when: { guessed: true, of: 'warm' },
      stage: '{a} reads the card: "{quote}"',
      turns: [['a', "That's {b}. Has to be."], ['b', "Guilty."]],
      beat: '{c} smiles, and {b} goes a bit red.' },
    { id: 'look-who.05', when: { guessed: false, of: 'warm' },
      stage: '{a} reads the card: "{quote}"',
      turns: [['a', "I don't know. Someone sweet?"]],
      beat: 'It was {b}, about {c}. {c} gives {b} a hug.' },
    { id: 'look-who.07', when: { guessed: true, of: 'cold' },
      stage: '{a} reads the card: "{quote}"',
      turns: [['a', "That's {b}. You can tell from how it sounds."], ['b', "I'm not going to deny it. I said it."]],
      beat: '{c} goes quiet.' },
    { id: 'look-who.08', when: { guessed: false, of: 'cold' },
      stage: '{a} picks a card: "{quote}"',
      turns: [['a', "Ouch. Who said that?"]],
      beat: 'It was {b}. {c} looks over at {b}, and {b} shrugs.' },
    { id: 'look-who.09', when: { of: 'cold' },
      stage: 'The next card is read out: "{quote}"',
      turns: [['c', "Well, at least I know now."], ['b', "It's nothing I wouldn't say to you."]] },
    { id: 'look-who.06',
      stage: 'The quote on the card is: "{quote}"',
      turns: [['c', "Wait, is that about me?"], ['b', "Yeah. It is."]] },
    { id: 'look-who.10', when: { of: 'plain', guessed: true },
      stage: '{a} reads the card: "{quote}"',
      turns: [['a', "That sounds like {b}."], ['b', "Yep. I stand by it."]],
      beat: '{c} nods slowly.' },
    { id: 'look-who.11', when: { of: 'plain', guessed: false },
      stage: '{a} reads out: "{quote}"',
      turns: [['a', "No idea. Genuinely no idea."]],
      beat: 'It was {b}. {c} looks over, and {b} gives a little wave.' },
    { id: 'look-who.12', when: { of: 'plain' },
      stage: 'Next card: "{quote}"',
      turns: [['c', "Who said that about me?"], ['b', "Me. It's true, isn't it?"]] },
  ],
  'snogger-kiss': [
    { id: 'snogger-kiss.01', when: { of: 'ten' },
      stage: 'The Sauciest Snogger. The boys sit blindfolded in a row, and the girls take it in turns to kiss each one. {a} kisses {b}.',
      turns: [['b', "Ten. That's a ten. I don't even need to think about it."]],
      beat: '{a} takes a little bow.' },
    { id: 'snogger-kiss.02', when: { of: 'ten', taken: true },
      stage: 'Blindfolded, {b} gives {a}\'s kiss a ten.',
      turns: [['a', "It's a game! It's a game."]],
      beat: "{pa} isn't clapping." },
    { id: 'snogger-kiss.03', when: { of: 'high' },
      stage: 'The boys are blindfolded, and the girls kiss each one in turn. When {a} kisses {b}, {b} goes very quiet.',
      turns: [['b', "Whoever that was… wow. That's an eight at least."]] },
    { id: 'snogger-kiss.06', when: { of: 'nine' },
      stage: 'The girls take turns kissing the boys, who are blindfolded. After {a}, {b} takes a second before scoring.',
      turns: [['b', "Nine. I'm keeping one back, but that was a nine."]] },
    { id: 'snogger-kiss.07', when: { of: 'nine', taken: true },
      stage: '{b} gives {a} a nine without seeing who it was.',
      turns: [['a', "I was just trying to win!"]],
      beat: '{pa} is staring at the floor.' },
    { id: 'snogger-kiss.04', when: { of: 'high', bTaken: true },
      stage: 'Blindfolded, {b} scores {a}\'s kiss higher than anyone else\'s.',
      turns: [['b', "I don't know who that was. I really don't."]],
      beat: '{pb} is watching from the side, arms folded.' },
    { id: 'snogger-kiss.05',
      stage: 'The girls take turns kissing the blindfolded boys. {a} saves {a.posAdj} best effort for {b}.',
      turns: [['b', "Okay. I'll be honest. That was the best one so far."]] },
  ],
  'snogger-win': [
    { id: 'snogger-win.01',
      stage: 'The scores are added up. {a} wins the Sauciest Snogger, and {b} comes second.',
      turns: [['a', "Oh my God! I actually won!"], ['b', "It was so close, though."]] },
    { id: 'snogger-win.02',
      stage: '{a} has the highest score of the day.',
      turns: [['a', "I'm not going to lie, I thought I might win this one."], ['b', "Next time, I'm coming for you."]] },
    { id: 'snogger-win.03', when: { persona: 'wallflower' },
      stage: 'Nobody expected it: the top score goes to {a}.',
      turns: [['a', "Me? Are you sure you added it up right?"], ['b', "They're sure. Well done."]] },
  ],
  'snogger-row': [
    { id: 'snogger-row.01', when: { of: 'big' },
      stage: 'The scores are read out. {b} gave {a} a much lower score than {c}.',
      turns: [['a', "You gave {c} a higher score than me?"], ['b', "I was blindfolded! I didn't know who anyone was!"],
        ['a', "You should know what I kiss like by now."]],
      beat: '{a} doesn\'t speak to {b} for the rest of the afternoon.' },
    { id: 'snogger-row.02', when: { of: 'big' },
      stage: 'Once the scores come out, {a} pulls {b} to one side.',
      turns: [['a', "Honestly, I'm embarrassed. Everyone heard that."], ['b', "It's a game. It doesn't mean anything."],
        ['a', "It means something to me."]] },
    { id: 'snogger-row.03', when: { of: 'small' },
      stage: 'The scores come out. {b} gave {c} two more points than {a}.',
      turns: [['a', "So {c} is a better kisser than me, is that it?"], ['b', "It's two points!"]],
      beat: '{a} is smiling, but only just.' },
    { id: 'snogger-row.04', when: { of: 'small' },
      stage: 'On the daybed after the challenge, {a} brings up the scores.',
      turns: [['a', "I'm not annoyed. I just want to know why."], ['b', "I didn't know it was you. If I'd known, you'd have got a ten."]] },
  ],
  'couple-goals': [
    { id: 'couple-goals.01', when: { of: 'marry' },
      stage: 'Couple Goals. The question: "Which couple is most likely to get married?" {a} and {b} turn their board round. It says {c} and {d}.',
      turns: [['c', "Stop it! That's so nice."]] },
    { id: 'couple-goals.02', when: { of: 'marry', guessed: true },
      stage: '"Which couple is most likely to get married?" Most of the boards say {c} and {d}.',
      turns: [['c', "I think I'm going to cry."], ['a', "It's obvious. Everyone can see it."]] },
    { id: 'couple-goals.03', when: { of: 'fake' },
      stage: 'Next question: "Which couple is the fakest?" {a} and {b} have written {c} and {d}.',
      turns: [['c', "Us? Are you joking?"], ['a', "It's just how it looks from where we're sitting."]],
      beat: '{c} and {d} look at each other.' },
    { id: 'couple-goals.04', when: { of: 'fake', guessed: true },
      stage: '"Which couple is the fakest?" The boards go round one by one. Most of them say {c} and {d}.',
      turns: [['c', "Wow. Okay. So that's what you all think."], ['b', "Don't take it personally."]],
      beat: 'Nobody says anything for a while.' },
    { id: 'couple-goals.05', when: { of: 'break' },
      stage: '"Which couple will be the first to break up on the outside?" {a} and {b} have put {c} and {d}.',
      turns: [['c', "Thanks, guys. Really."], ['b', "It's a game! Don't take it to heart."]] },
    { id: 'couple-goals.06', when: { of: 'break', guessed: true },
      stage: '"Which couple will be the first to break up on the outside?" Most of the boards say {c} and {d}.',
      turns: [['c', "That's most of you. That's not a joke any more."], ['a', "We're only saying what we see."]] },
    { id: 'couple-goals.07', when: { of: 'marry' },
      stage: '"Which couple is most likely to get married?" {a} and {b} hold up a board that says {c} and {d}.',
      turns: [['b', "Look at them. They're already like an old married couple."], ['c', "That's the nicest thing anyone's said to us."]] },
    { id: 'couple-goals.08', when: { of: 'fake' },
      stage: '"Which couple is the fakest?" {a} and {b} look at each other, then write down {c} and {d}.',
      turns: [['c', "Seriously? After everything?"], ['b', "You asked for honesty."]] },
    { id: 'couple-goals.09', when: { of: 'break' },
      stage: '"Which couple will be the first to break up on the outside?" {a} and {b} have written {c} and {d}, and they look a bit sorry about it.',
      turns: [['a', "I hope we're wrong. I really do."], ['c', "So do I."]] },
  ],
  'couple-goals-row': [
    { id: 'couple-goals-row.01',
      stage: 'After the challenge, {a} catches {b} by the pool.',
      turns: [['a', "I thought we were friends. Why would you write us down?"], ['b', "It wasn't personal. We had to put someone."],
        ['a', "You could have put anyone else."]],
      beat: '{b} tries to hug {a}. {a} steps back.' },
    { id: 'couple-goals-row.02',
      stage: '{a} finds {b} in the kitchen.',
      turns: [['a', "Of everyone, I didn't think it would be you."], ['b', "I'm sorry. I didn't think you'd take it like this."]],
      beat: '{c} comes over and takes {a} away.' },
    { id: 'couple-goals-row.03', when: { of: 'fake' },
      stage: 'After the game, {a} is still thinking about the board.',
      turns: [['a', "You really think we're fake? You've seen us every day."], ['b', "I just don't see it the way you do."],
        ['a', "Then you haven't been looking."]] },
  ],
  'knowing-me': [
    { id: 'knowing-me.01', when: { of: 'high' },
      stage: 'Knowing Me, Knowing You. {a} and {b} sit back to back with their boards, and match on almost every question.',
      turns: [['a', "We know each other so well. It's actually scary."], ['b', "I told you. We're the real thing."]] },
    { id: 'knowing-me.02', when: { of: 'high' },
      stage: '{a} and {b} top the board.',
      turns: [['b', "Who's the better cook? Both of us wrote you!"], ['a', "Because it's true!"]],
      beat: 'The other couples boo them, laughing.' },
    { id: 'knowing-me.07', when: { of: 'high' },
      stage: '{a} and {b} get every question but one.',
      turns: [['a', "The one we got wrong was your fault."], ['b', "It was not! You don't know what my star sign is."]] },
    { id: 'knowing-me.08', when: { of: 'low' },
      stage: 'Knowing Me, Knowing You. {a} and {b} get almost nothing right.',
      turns: [['a', "You thought my favourite film was a cartoon?"], ['b', "You watch cartoons!"]] },
    { id: 'knowing-me.03', when: { of: 'mid' },
      stage: '{a} and {b} get about half the questions right.',
      turns: [['b', "You didn't know my favourite food?"], ['a', "I know you like pasta! I just panicked."]] },
    { id: 'knowing-me.04', when: { of: 'mid' },
      stage: 'Halfway through, {a} and {b} are level with everyone else.',
      turns: [['a', "Who's the messiest? You wrote me?"], ['b', "Have you seen your side of the bed?"]] },
    { id: 'knowing-me.05', when: { of: 'low' },
      stage: '{a} and {b} barely match once.',
      turns: [['a', "How do you not know my middle name?"], ['b', "You've never told me your middle name!"]],
      beat: 'The other couples try very hard not to laugh.' },
    { id: 'knowing-me.06', when: { of: 'low' },
      stage: '{a} and {b} finish last, by a long way.',
      turns: [['b', "We need to talk more. Like, actually talk."], ['a', "Yeah. We do."]] },
  ],
  'knowing-row': [
    { id: 'knowing-row.01', when: { of: 'hurt' },
      stage: 'The last question: "Which of you is more likely to stray?" {a} has written {b}.',
      turns: [['b', "Me? Why me?"], ['a', "I don't know. It's just a feeling."], ['b', "I haven't done anything to give you that feeling."]] },
    { id: 'knowing-row.02', when: { of: 'hurt' },
      stage: '"Which of you is more likely to stray?" {a} turns round a board with {b}\'s name on it.',
      turns: [['b', "Wow. Okay. That hurts, actually."], ['a', "It's not a big deal. It's just a game."]],
      beat: '{b} is quiet for the rest of the afternoon.' },
    { id: 'knowing-row.03', when: { of: 'guilty' },
      stage: 'The last question: "Which of you is more likely to stray?" {a} has written {b}.',
      turns: [['b', "…Why have you put me?"], ['a', "You tell me."]],
      beat: '{b} laughs, a little too quickly.' },
    { id: 'knowing-row.04', when: { of: 'guilty' },
      stage: '"Which of you is more likely to stray?" {a} doesn\'t hesitate, and writes {b}.',
      turns: [['b', "That's a bit harsh."], ['a', "Is it?"]],
      beat: '{b} changes the subject.' },
  ],
  'talent-act': [
    { id: 'talent-act.01', when: { of: 'flop' },
      stage: 'The talent show. {a} goes up with a magic trick, and it goes wrong almost straight away.',
      turns: [['a', "Okay, that wasn't supposed to happen. Can I start again?"]],
      beat: 'The villa cheers anyway.' },
    { id: 'talent-act.02', when: { of: 'flop' },
      stage: '{a} sings, and forgets the words halfway through the first verse.',
      turns: [['a', "I knew this song this morning. I promise I knew it."]],
      beat: 'Everyone sings the rest for {a.obj}.' },
    { id: 'talent-act.03', when: { of: 'flop' },
      stage: '{a} tries a dance routine by the pool and slips on the wet tiles.',
      turns: [['a', "I'm fine! I'm fine. That was part of it."]] },
    { id: 'talent-act.04', when: { of: 'duet' },
      stage: '{a} and {b} do a dance together that they spent all morning practising.',
      turns: [['b', "We nailed that. We actually nailed that."], ['a', "I can't believe we didn't fall over."]] },
    { id: 'talent-act.05', when: { of: 'duet' },
      stage: '{a} and {b} sing a love song to each other, badly, in front of everyone.',
      turns: [['a', "That was for you. The bad notes too."]],
      beat: '{b} can\'t stop smiling.' },
  ],
  'talent-win': [
    { id: 'talent-win.01',
      stage: 'The villa votes with a show of hands, and {a} wins the talent show.',
      turns: [['a', "No way! I didn't think anyone would vote for me."]] },
    { id: 'talent-win.02',
      stage: 'Most of the hands go up for {a}.',
      turns: [['a', "Thank you! I've been practising that since I was about twelve."]] },
    { id: 'talent-win.03', when: { coupled: true },
      stage: '{a} wins the talent show.',
      turns: [['b', "That's my partner! That's my partner!"]],
      beat: '{b} lifts {a} right off the ground.' },
  ],
  'talent-snub': [
    { id: 'talent-snub.01',
      stage: 'When the hands go up, {b} votes for {c}, not {a}.',
      turns: [['a', "You didn't vote for me."], ['b', "{c} was better! I'm just being honest."], ['a', "I voted for you."]],
      beat: '{b} doesn\'t have an answer to that.' },
    { id: 'talent-snub.02',
      stage: 'Later, on the daybeds, {a} is still thinking about the vote.',
      turns: [['a', "Everyone saw you put your hand up for {c}."], ['b', "It's a talent show. It's not about us."]],
      beat: '{a} goes inside without saying anything else.' },
  ],
  'baby-doll': [
    { id: 'baby-doll.01', when: { of: 'team' },
      stage: 'Every couple is given a baby doll to look after, day and night. {a} and {b} take turns without being asked.',
      turns: [['b', "I did the night feed, so you do the morning one."], ['a', "Deal. Look at us."]] },
    { id: 'baby-doll.02', when: { of: 'team' },
      stage: '{a} and {b} have made their baby doll a little bed out of towels.',
      turns: [['a', "We're actually good at this."], ['b', "I always knew you'd be good at this."]],
      beat: '{a} goes quiet, and smiles.' },
    { id: 'baby-doll.03', when: { of: 'left-it' },
      stage: '{a} has done every feed and every nappy. {b} has spent the day on a sunbed.',
      turns: [['a', "Where were you? I've been doing this on my own all day."], ['b', "It's a doll!"],
        ['a', "That's not the point, though, is it?"]] },
    { id: 'baby-doll.04', when: { of: 'left-it' },
      stage: 'At three in the morning the baby doll starts crying. {b} rolls over. {a} gets up.',
      turns: [['a', "I'm not doing the next one."], ['b', "Mm. Okay."]],
      beat: '{a} does the next one as well.' },
    { id: 'baby-doll.05', when: { of: 'lost' },
      stage: '{a} and {b} leave their baby doll on a sunbed and forget about it for three hours.',
      turns: [['a', "Where's the baby?"], ['b', "…I thought you had the baby."]],
      beat: 'Everyone else thinks this is the funniest thing that has happened all week.' },
    { id: 'baby-doll.06', when: { of: 'lost' },
      stage: '{a} and {b} find their baby doll face down in the hideaway.',
      turns: [['b', "Okay, we are not ready for this."], ['a', "Nobody tell anyone."]],
      beat: 'Somebody has already told everyone.' },
  ],
  'sorts-podium': [
    { id: 'sorts-podium.01', when: { of: 'top', guessed: true },
      stage: 'Couple of Sorts. The public have ranked the couples, and each couple stands on the podium where they think they came. First category: the public\'s favourite couple. {a} and {b} stood on first, and they were right.',
      turns: [['a', "We knew it! We stood on first and everything."], ['b', "Thank you! Thank you, everyone at home!"]] },
    { id: 'sorts-podium.02', when: { of: 'top', guessed: false },
      stage: 'Couple of Sorts. The public have ranked the couples, and the couples have to guess the order. The public\'s favourite couple is {a} and {b}, who were standing somewhere else entirely.',
      turns: [['a', "Us? Really?"], ['b', "They like us! The public actually like us!"]] },
    { id: 'sorts-podium.03', when: { of: 'wrong' },
      stage: '{a} and {b} stood on the first-place podium. The public put them last.',
      turns: [['a', "Oh. Okay. That's embarrassing."], ['b', "Can we just get down now?"]] },
    { id: 'sorts-podium.04', when: { of: 'wrong' },
      stage: 'The order is read out. {a} and {b}, on first place, are at the very bottom.',
      turns: [['b', "I really thought we'd be higher than that."], ['a', "Me too."]],
      beat: 'They step down, and nobody quite knows where to look.' },
    { id: 'sorts-podium.05', when: { of: 'least' },
      stage: 'The last category: the couple least likely to last on the outside. The public have picked {a} and {b}.',
      turns: [['a', "That's harsh."], ['b', "They don't know us. Not really."]] },
    { id: 'sorts-podium.06', when: { of: 'least' },
      stage: '"Least likely to last on the outside": {a} and {b}.',
      turns: [['b', "Do you think they're right?"], ['a', "I don't know. Do you?"]],
      beat: 'Neither of them answers.' },
  ],
  'grafties-award': [
    { id: 'grafties-award.01', when: { of: 'couple' },
      stage: 'The Grafties: an awards night, and the public have voted. The award for favourite couple goes to {a} and {b}.',
      turns: [['a', "Thank you so much! We love you all!"], ['b', "Honestly, thank you. This means a lot."]] },
    { id: 'grafties-award.02', when: { of: 'couple' },
      stage: 'The first award of the night, the public\'s favourite couple, goes to {a} and {b}.',
      turns: [['b', "I want to thank my partner, obviously. And everyone who voted."]] },
    { id: 'grafties-award.03', when: { of: 'grafter' },
      stage: 'The award for grafter of the year goes to {a}.',
      turns: [['a', "I'll take it. I've worked hard for this."]] },
    { id: 'grafties-award.04', when: { of: 'grafter', coupled: true },
      stage: 'The public have named {a} grafter of the year.',
      turns: [['a', "It's a compliment! It's a compliment, isn't it?"], ['b', "Is it?"]],
      beat: '{b} doesn\'t laugh as hard as everyone else.' },
    { id: 'grafties-award.05', when: { of: 'least' },
      stage: 'The last award goes to the islander the public like least. It goes to {a}.',
      turns: [['a', "Wow. I didn't expect that at all."]] },
    { id: 'grafties-award.06', when: { of: 'least', coupled: true },
      stage: 'The public\'s least favourite islander: {a}.',
      turns: [['a', "Okay. I'll take that on board."], ['b', "They don't know you like I do."]],
      beat: '{b} puts an arm round {a}.' },
  ],
};
// The Lie Detector (pm/lie-detector.js), merged in; its challenge-text joins the others.
for (const [k, v] of Object.entries(LIE_LINES)) CHALLENGE_LINES[k] = [...(CHALLENGE_LINES[k] || []), ...v];
// The eight more (pm/challenges-more.js), merged the same way.
for (const [k, v] of Object.entries(MORE_CHALLENGE_LINES)) CHALLENGE_LINES[k] = [...(CHALLENGE_LINES[k] || []), ...v];
