// pm/lines/hut.js — beach-hut cutaways (Plan 3, Task 5). Data only.
//
// One speaker, straight to camera, right after the scene it cuts away from.
// {a} is the speaker; {b} is the other person in that scene, and a line that
// names {b} must say `withB: true` (a comedy bit has nobody else in it).
//
// Facts a hut line can test, on top of the usual: `kind` (the scene it
// follows), `family` (flirting, couple, jealousy, friendship, gossip,
// dumping, casa), `role` (0 started it, 1 was on the receiving end, 2 was
// the one talked about) and `stance`, which picks the pool:
//   honest     — says what the speaker feels
//   two-faced  — the speaker is hiding something (a secret, or a mask)
// The honest hut of somebody who is FAKING is the giveaway the spec promised
// (§6.5): the audience hears what the villa does not.
const B = { withB: true };
export const HUT = {
  honest: [
    // anything
    { id: 'hut.h01', turns: [['a', "I know what I want. I just want to be sure it wants me back."]] },
    { id: 'hut.h02', turns: [['a', "I'm actually really happy. I didn't think I'd say that in here."]] },
    { id: 'hut.h03', turns: [['a', "It's so hot today I've forgotten what I was going to say. Something about love. Probably."]] },
    { id: 'hut.h04', turns: [['a', "Everyone says the villa's a bubble. They're right. I just don't want to pop it yet."]] },
    { id: 'hut.h05', turns: [['a', "I'm taking every day as it comes. That's a lie. I'm taking every day and panicking about the next one."]] },
    { id: 'hut.h06', when: { early: true }, turns: [['a', "I've been here two minutes and I already can't remember what normal life is like."]] },
    { id: 'hut.h07', when: { late: true }, turns: [['a', "I've been in here so long I'm scared of how quiet it'll be at home."]] },
    { id: 'hut.h08', when: { mood: 'secure' }, turns: [['a', "For the first time in here, I'm not worried about anything. It's weird. I keep checking."]] },
    { id: 'hut.h09', when: { mood: 'lonely' }, turns: [['a', "Everyone's got someone to talk to at night. I've got the ceiling."]] },
    { id: 'hut.h10', when: { mood: 'stressed' }, turns: [['a', "I'm fine. I'm tired, and I'm hot, and I'm fine."]] },
    { id: 'hut.h11', when: { mood: 'heartbroken' }, turns: [['a', "I keep saying I'm over it. I'll let you know when that's true."]] },
    { id: 'hut.h12', when: { mood: 'guilty' }, turns: [['a', "I haven't slept properly for two nights. I think you know why."]] },
    // flirting
    { id: 'hut.h13', when: { ...B, family: 'flirting', role: 0 },
      turns: [['a', "I went for it. I'm not going to sit here in six weeks wondering what if."]] },
    { id: 'hut.h14', when: { ...B, family: 'flirting', role: 0 },
      turns: [['a', "{b} makes me nervous. Good nervous. The kind you don't get very often."]] },
    { id: 'hut.h15', when: { ...B, family: 'flirting', role: 1 },
      turns: [['a', "I didn't see that coming from {b}. I don't hate it, either."]] },
    { id: 'hut.h16', when: { ...B, family: 'flirting', role: 1, taken: true },
      turns: [['a', "I'm with someone. I know I'm with someone. It's still nice to be asked."]] },
    { id: 'hut.h17', when: { ...B, family: 'flirting', role: 1, taken: true, loyal: true },
      turns: [['a', "Nothing's going to happen with {b}. I'm telling you, and I'll be telling my partner too."]] },
    { id: 'hut.h18', when: { ...B, kind: 'kiss' }, turns: [['a', "Every time {b} kisses me I forget there are cameras. Hi, by the way."]] },
    { id: 'hut.h19', when: { ...B, kind: 'kiss', early: true }, turns: [['a', "That was our first real kiss. I'm trying to act normal about it and I'm not managing."]] },
    { id: 'hut.h20', when: { ...B, kind: 'challenge-kiss', role: 0, taken: true },
      turns: [['a', "It was a game. My partner knows it was a game. I just hope my partner's face knows."]] },
    { id: 'hut.h21', when: { ...B, kind: 'challenge-kiss', role: 1 },
      turns: [['a', "Out of everyone in that line, {b} picked me. I'm going to be thinking about that all night."]] },
    { id: 'hut.h22', when: { ...B, bombshell: true, family: 'flirting' },
      turns: [['a', "I didn't come in here to sit on the sidelines. {b} is the one I want to get to know."]] },
    // couple
    { id: 'hut.h23', when: { ...B, family: 'couple' },
      turns: [['a', "I didn't expect to like {b} this much. It's annoying, actually. I had a whole plan."]] },
    { id: 'hut.h24', when: { ...B, family: 'couple' },
      turns: [['a', "{b} does this thing where {b} listens properly. Like there's nobody else in the villa. That's rare."]] },
    { id: 'hut.h25', when: { ...B, family: 'couple', rung: ['exclusive', 'official'] },
      turns: [['a', "I don't look at the door any more when someone new walks in. That's how I know."]] },
    { id: 'hut.h26', when: { ...B, family: 'couple', rung: 'official' },
      turns: [['a', "I'm official. On {~telly}. There's no taking that back now, and I don't want to."]] },
    { id: 'hut.h27', when: { ...B, family: 'couple', gap: true },
      turns: [['a', "I think I'm further ahead than {b} is. I'm trying not to let it show. I don't think it's working."]] },
    { id: 'hut.h28', when: { ...B, family: 'couple', attachment: 'anxious' },
      turns: [['a', "When it's good with {b}, it's so good. And then I spend the next hour waiting for it to go wrong."]] },
    { id: 'hut.h29', when: { ...B, family: 'couple', attachment: 'avoidant' },
      turns: [['a', "I like {b}. I do. I just need a bit of air sometimes, and in here there isn't any."]] },
    { id: 'hut.h30', when: { ...B, kind: 'deep-chat' },
      turns: [['a', "I've never told anyone that. Not even at home. I don't know why I told {b}. Actually, I do."]] },
    { id: 'hut.h31', when: { ...B, kind: 'challenge-win' },
      turns: [['a', "We won, and the first thing I wanted to do was look at {b}. That's new for me."]] },
    { id: 'hut.h32', when: { ...B, family: 'couple', persona: 'checklist' },
      turns: [['a', "On paper, {b} ticks about half my boxes. But I've stopped caring about the boxes."]] },
    { id: 'hut.h33', when: { ...B, family: 'couple', persona: 'hopeless-romantic' },
      turns: [['a', "I know, I know. Everyone says I fall too fast. I'm falling. There, I said it."]] },
    // jealousy
    { id: 'hut.h34', when: { family: 'jealousy', role: 0 },
      turns: [['a', "I lost my temper. I'm not proud of it. I'm not sorry about all of it, either."]] },
    { id: 'hut.h35', when: { ...B, family: 'jealousy', role: 1 },
      turns: [['a', "I didn't even know I'd done anything until {b} was standing in front of me."]] },
    { id: 'hut.h36', when: { ...B, kind: 'argument', coupled: true },
      turns: [['a', "Couples argue. That's what I keep telling myself. It's just a lot louder when there's a microphone on your chest."]] },
    { id: 'hut.h37', when: { ...B, kind: 'argument', coupled: false },
      turns: [['a', "{b} and I were never going to be friends. I just didn't think it'd all kick off today."]] },
    { id: 'hut.h38', when: { family: 'jealousy', mood: 'jealous' },
      turns: [['a', "I don't want to be the jealous one. I've been the jealous one before. It's horrible."]] },
    { id: 'hut.h39', when: { ...B, kind: 'ick', role: 0 },
      turns: [['a', "I can't explain it. I just can't un-see it now. Poor {b}."]] },
    { id: 'hut.h40', when: { ...B, kind: 'ick', role: 1 },
      turns: [['a', "{b}'s gone a bit quiet on me. I don't know what I've done."]] },
    { id: 'hut.h41', when: { family: 'jealousy', archetype: 'hothead' },
      turns: [['a', "People say I overreact. Maybe I do. At least I say what I'm thinking."]] },
    // friendship
    { id: 'hut.h42', when: { ...B, family: 'friendship' },
      turns: [['a', "{b} is the one I'd call first when we get out. I think {b} knows that."]] },
    { id: 'hut.h43', when: { ...B, kind: 'friendship' },
      turns: [['a', "Forget the couples. {b} is the best thing I've found in here."]] },
    { id: 'hut.h44', when: { kind: 'comedy' }, turns: [['a', "Somebody has to keep this place going. It might as well be me."]] },
    { id: 'hut.h45', when: { kind: 'comedy' }, turns: [['a', "I'm not the funny one. I'm the one who says what everyone's thinking, which is apparently the same thing."]] },
    { id: 'hut.h46', when: { ...B, kind: 'friendship', gender: 'f', bGender: 'f' },
      turns: [['a', "The girls in here are the reason I've lasted this long. {b} most of all."]] },
    { id: 'hut.h47', when: { ...B, kind: 'friendship', gender: 'm', bGender: 'm' },
      turns: [['a', "{b}'s a real {~a-mate}. Tells me when I'm being an idiot, which is a lot."]] },
    // gossip
    { id: 'hut.h48', when: { ...B, kind: 'gossip', role: 0 },
      turns: [['a', "I didn't want to be the one to tell {b}. But I'd want to know, so I told."]] },
    { id: 'hut.h49', when: { ...B, kind: 'gossip', role: 0, persona: 'girls-girl', gender: 'f' },
      turns: [['a', "Girl code is girl code. I don't care who it upsets."]] },
    { id: 'hut.h50', when: { ...B, kind: 'gossip', role: 1 },
      turns: [['a', "I trusted them. That's the bit I can't get over. I trusted them."]] },
    { id: 'hut.h51', when: { ...B, kind: 'gossip', role: 1, attachment: 'avoidant' },
      turns: [['a', "I'm not going to cry about it on camera. I'll do that later, when nobody's looking."]] },
    { id: 'hut.h52', when: { kind: 'gossip', role: 2 },
      turns: [['a', "Everyone's looking at me like I've run someone over. I had a chat. A chat went too far."]] },
    { id: 'hut.h53', when: { ...B, kind: 'loyalty', role: 0 },
      turns: [['a', "{b} tried it. Fair play to {b} for trying. But I'm not interested."]] },
    { id: 'hut.h54', when: { ...B, kind: 'loyalty', role: 1 },
      turns: [['a', "I got turned down by {b}. I'll live. I'll just be very dramatic about it for about an hour."]] },
    // dumping and the recoupling
    { id: 'hut.h55', when: { family: 'dumping' }, turns: [['a', "The firepit is the worst place in the world. It's also the only place anything's ever decided."]] },
    { id: 'hut.h56', when: { family: 'dumping' }, turns: [['a', "My hands are still shaking. Look at them."]] },
    { id: 'hut.h57', when: { family: 'dumping', mood: 'heartbroken' }, turns: [['a', "I didn't think it would hurt this much. It's only been a few weeks. It's hurt the whole time."]] },
    { id: 'hut.h58', when: { family: 'dumping', coupled: true },
      turns: [['a', "When they read our names out, {b} squeezed my hand. That's all I remember."]] },
    { id: 'hut.h59', when: { kind: 'recouple-pick', role: 0 }, turns: [['a', "I stood up there and said it out loud. Whatever happens now, I said it."]] },
    { id: 'hut.h60', when: { kind: 'recouple-pick', role: 1 }, turns: [['a', "I didn't know until my name came out. I was holding my breath the whole speech."]] },
    // casa
    { id: 'hut.h61', when: { family: 'casa' }, turns: [['a', "Casa Amor is where couples go to die. I just didn't think it would be mine."]] },
    { id: 'hut.h62', when: { kind: 'casa-return', role: 0 },
      turns: [['a', "I walked back in on my own. Whatever's waiting for me, I can look it in the eye."]] },
    { id: 'hut.h63', when: { kind: 'photos', role: 0 },
      turns: [['a', "You can say you trust someone all you want. Then there's a photo, and it's in your hand."]] },
    // the faker's giveaway — the honest hut of somebody wearing a mask
    { id: 'hut.h64', when: { ...B, faking: true },
      turns: [['a', "Do I {~fancy} {b}? Not really. But everyone out there likes {b}, and I'm not going home in week two."]] },
    { id: 'hut.h65', when: { ...B, faking: true },
      turns: [['a', "{b} thinks this is going somewhere. I'll let {b} think that until the next recoupling."]] },
    { id: 'hut.h66', when: { ...B, faking: true, family: 'couple' },
      turns: [['a', "I said all the right things. I'm good at the right things. It doesn't mean I felt any of them."]] },
    { id: 'hut.h67', when: { ...B, faking: true, kind: 'kiss' },
      turns: [['a', "It's a kiss. It's television. {b} is lovely, and I'm doing what I need to do."]] },
  ],
  'two-faced': [
    { id: 'hut.t01', turns: [['a', "I'm keeping my options open. That's not a crime."]] },
    { id: 'hut.t02', turns: [['a', "What they don't know can't hurt them. Right?"]] },
    { id: 'hut.t03', turns: [['a', "I'm happy. Mostly. There's a bit of me that isn't, and that bit is doing the thinking."]] },
    { id: 'hut.t04', turns: [['a', "I'm not a bad person. I'm a person who's in a villa with a lot of options."]] },
    { id: 'hut.t05', when: { mood: 'guilty' }, turns: [['a', "I know I should say something. I just keep not saying it."]] },
    { id: 'hut.t06', when: { mood: 'guilty' }, turns: [['a', "Every time someone looks at me for more than two seconds, I think they know."]] },
    { id: 'hut.t07', when: { ...B, family: 'couple' },
      turns: [['a', "Everyone keeps saying we're solid. And {~yeah}, on paper. But paper's not a person, is it. I'll see how this week goes and then I'll decide."]] },
    { id: 'hut.t08', when: { ...B, family: 'couple' },
      turns: [['a', "{b} is lovely. {b} is really, really lovely. That's the problem."]] },
    { id: 'hut.t09', when: { ...B, family: 'couple', rung: ['closed-off', 'exclusive'] },
      turns: [['a', "I told {b} I'd closed myself off. I have. Mostly. There's a {~little} window I haven't shut."]] },
    { id: 'hut.t10', when: { ...B, kind: 'kiss' },
      turns: [['a', "Kissing {b} is nice. Kissing {b} is safe. I'm just not sure I came in here for safe."]] },
    { id: 'hut.t11', when: { ...B, family: 'flirting', role: 0 },
      turns: [['a', "I'm coupled up, but I'm not blind. And {b} is very hard to not see."]] },
    { id: 'hut.t12', when: { ...B, family: 'flirting', role: 1 },
      turns: [['a', "Nothing happened with {b}. And if something did, it was very small, and nobody saw."]] },
    { id: 'hut.t13', when: { family: 'jealousy' },
      turns: [['a', "I'm going to act like I'm upset about this. And I am. Just not for the reason they think."]] },
    { id: 'hut.t14', when: { ...B, kind: 'argument' },
      turns: [['a', "An argument's handy, actually. Nobody asks you where you were last night if you're busy shouting."]] },
    { id: 'hut.t15', when: { kind: 'gossip', role: 2 },
      turns: [['a', "It wasn't what it looked like. It was a bit what it looked like."]] },
    { id: 'hut.t16', when: { kind: 'gossip', role: 2 },
      turns: [['a', "Whoever {~grassed} on me needs to have a long look at themselves. I'm not saying I didn't do it."]] },
    { id: 'hut.t17', when: { kind: 'gossip', role: 0 },
      turns: [['a', "I told them because they deserved to know. And because it doesn't hurt me if that couple goes."]] },
    { id: 'hut.t18', when: { ...B, kind: 'friendship' },
      turns: [['a', "{b} tells me everything. That's useful. That's also why I'm not telling {b} everything."]] },
    { id: 'hut.t19', when: { kind: 'comedy' },
      turns: [['a', "If everyone's laughing, nobody's asking questions. Works every time."]] },
    { id: 'hut.t20', when: { family: 'dumping' },
      turns: [['a', "I stood there looking sad. I was a bit sad. I was mostly relieved it wasn't me."]] },
    { id: 'hut.t21', when: { kind: 'recouple-pick', role: 0 },
      turns: [['a', "Did I pick with my heart or my head? I picked with the bit that wants to stay in the villa."]] },
    { id: 'hut.t22', when: { family: 'casa' },
      turns: [['a', "What happens at Casa stays at Casa. That's what everyone says, isn't it?"]] },
    { id: 'hut.t23', when: { ...B, faking: true },
      turns: [['a', "{b} really likes me. I really like being liked. That'll do for now."]] },
    { id: 'hut.t24', when: { ...B, faking: true, family: 'couple' },
      turns: [['a', "Everyone thinks I'm head over heels. Let them. Head over heels gets votes."]] },
    { id: 'hut.t25', when: { late: true }, turns: [['a', "We're nearly at the end. I've kept it together this long. I can keep it together a bit longer."]] },
    { id: 'hut.t27', turns: [['a', "Honestly? I'm fine. I'm doing fine. Next question."]] },
    { id: 'hut.t28', turns: [['a', "I'd rather not get into that in here. You'll see why."]] },
    { id: 'hut.t29', turns: [['a', "Some things are between me and the daybed. Moving on."]] },
    { id: 'hut.t30', turns: [['a', "Nobody in there knows the full story. I'd like to keep it like that for a bit."]] },
    { id: 'hut.t31', turns: [['a', "I've done nothing wrong. I've done a few things that might look wrong."]] },
    { id: 'hut.t32', turns: [['a', "If you ask me whether I'm happy, I'll say yes. Ask me again in a week."]] },
    { id: 'hut.t33', when: { mood: 'guilty' }, turns: [['a', "I keep smiling at everyone. I don't think I've stopped smiling all day. That's not a good sign."]] },
    { id: 'hut.t34', when: { taken: true }, turns: [['a', "My partner's lovely. My partner's also not in the room right now."]] },
    { id: 'hut.t35', when: { ...B, family: 'couple' }, turns: [['a', "{b} asked me if everything's okay. I said yes. It's mostly yes."]] },
    { id: 'hut.t36', when: { ...B, family: 'flirting' }, turns: [['a', "It was a chat. It was a long chat. It was a very, very long chat."]] },
    { id: 'hut.t37', when: { family: 'jealousy' }, turns: [['a', "I'm upset. I'm also aware I'm not really in a position to be upset. Both things are true."]] },
    { id: 'hut.t38', when: { family: 'friendship' }, turns: [['a', "I love everyone in there. I just don't tell everyone in there everything."]] },
    { id: 'hut.t39', when: { family: 'dumping' }, turns: [['a', "That could have been me. After this week, it probably should have been."]] },
    { id: 'hut.t40', when: { family: 'casa' }, turns: [['a', "Whatever happened at Casa is staying at Casa. I've told myself that about fifty times today."]] },
    { id: 'hut.t26', when: { early: true }, turns: [['a', "It's early. Everyone's still working each other out. I've already worked out who's useful."]] },
  ],
};
