// pm/lines/kiss-games.js — night one's kissing games (pm/kiss-games.js). Data only.
//
//   icebreaker      [a, b]      a smashed the ice, read the card, kissed b.
//                               choice: 'spark' | 'flat' — whether it landed.
//   kiss-pick       [a, b]      after Icebreakers, a couples up with b.
//                               choice: 'spark' | 'flat' (how their kiss went tonight) | 'other' (no kiss).
//   lady-luck-kiss  [a, b]      a's first or second kiss (nth: 'first' | 'next').
//                               choice: 'spark' | 'flat'.
//   lady-luck-pick  [a, b, c]   a couples with b, not c, the other one kissed.
//                               choice: 'spark' (b's kiss landed) | 'flat' (neither did) |
//                               'passed-up' (c's kiss was the better one) | 'only-one' (no c: b was all that was left).

// The questions frozen in the ice, read out in the stage line as "{card}".
export const ICEBREAKER_CARDS = [
  "Kiss the islander you'd most like to wake up next to.",
  "Kiss the islander who caught your eye first.",
  "Kiss the islander you'd take home to meet your parents.",
  "Kiss the islander you think is the biggest flirt.",
  "Kiss the islander you think is the best kisser.",
  "Kiss the islander you'd most like to go on a date with.",
  "Kiss the islander with the best smile.",
  "Kiss the islander you'd want next to you on a night out.",
];

export const KISS_LINES = {
  icebreaker: [
    { id: 'icebreaker.01', when: { choice: 'spark' },
      stage: '{a} smashes the ice cube and fishes out the card. "{card}"',
      turns: [['a', "Oh, that's easy."], ['a', "{b}, come here."]],
      beat: 'They kiss, and when they pull apart {b} is grinning.' },
    { id: 'icebreaker.02', when: { choice: 'spark' },
      stage: 'The ice takes {a} three goes to break. The card inside says: "{card}"',
      turns: [['a', "Okay. {b}."], ['b', "Me? Go on, then."]],
      beat: 'The kiss lasts longer than anyone expected, and the fire pit starts cheering.' },
    { id: 'icebreaker.03', when: { choice: 'spark' },
      stage: '{a} reads the card out loud: "{card}"',
      turns: [['a', "I've known since I walked in. {b}."]],
      beat: '{b} kisses {a.obj} back, and looks a bit dazed afterwards.' },
    { id: 'icebreaker.04', when: { choice: 'spark' },
      stage: '{a} holds up the card so everyone can see it. "{card}"',
      turns: [['a', "Sorry, everyone. {b}."], ['b', "Don't be sorry."]],
      beat: 'Somebody on the bench whistles.' },
    { id: 'icebreaker.05', when: { choice: 'spark' },
      stage: '{a} breaks the ice with one hit. The card says: "{card}"',
      turns: [['a', "I was hoping I'd get that one."]],
      beat: '{a} walks straight over to {b}, and neither of them is in a hurry to stop.' },
    { id: 'icebreaker.06', when: { choice: 'spark' },
      stage: '{a} reads the card, laughs, and reads it again. "{card}"',
      turns: [['a', "{b}. Stand up."], ['b', "Yes, boss."]],
      beat: 'When the kiss ends, {b} sits down and says nothing for a while.' },
    { id: 'icebreaker.07', when: { choice: 'spark' },
      stage: 'The card says: "{card}" {a} does not even look round.',
      turns: [['a', "{b}."], ['b', "I was hoping you'd say that."]],
      beat: 'The kiss gets a round of applause.' },
    { id: 'icebreaker.08', when: { choice: 'flat' },
      stage: '{a} cracks the ice and reads the card: "{card}"',
      turns: [['a', "Er. {b}, I suppose?"]],
      beat: 'The kiss is quick. {b} laughs, a bit awkwardly, and sits back down.' },
    { id: 'icebreaker.09', when: { choice: 'flat' },
      stage: '{a} gets the card out and reads it twice. "{card}"',
      turns: [['a', "{b}. Don't make it weird."], ['b', "You're the one making it weird."]],
      beat: 'It is a peck, and both of them know it.' },
    { id: 'icebreaker.10', when: { choice: 'flat' },
      stage: 'The card says: "{card}" {a} walks over to {b}.',
      turns: [['b', "That was… nice."], ['a', "Nice. Great. Thanks."]] },
    { id: 'icebreaker.11', when: { choice: 'flat' },
      stage: '{a} reads the card: "{card}"',
      turns: [['a', "{b}. Just go with it."]],
      beat: 'The kiss is over almost before it starts, and nobody cheers.' },
    { id: 'icebreaker.12', when: { choice: 'flat' },
      stage: 'It takes {a} a while to get the card out of the ice. "{card}"',
      turns: [['a', "All that for this. Fine. {b}."]],
      beat: '{b} gets a quick kiss, and that is that.' },
    { id: 'icebreaker.13', when: { choice: 'flat' },
      stage: '{a} reads the card out: "{card}"',
      turns: [['a', "{b}? Is that allowed?"], ['b', "I think so."]],
      beat: 'They kiss, and then both look at the fire pit as if it might tell them how it went.' },
    { id: 'icebreaker.14', when: { choice: 'flat' },
      stage: 'The card in the ice says: "{card}" {a} chooses {b}.',
      turns: [['b', "Well. That happened."]],
      beat: '{a} is back on the bench before anyone has finished clapping.' },
  ],
  'kiss-pick': [
    { id: 'kiss-pick.01', when: { choice: 'spark' },
      stage: '{a} stands up at the fire pit.',
      turns: [['a', "I only needed one kiss to know. I'd like to couple up with {b}."]],
      beat: '{b} is on {b.posAdj} feet before {a} has finished.' },
    { id: 'kiss-pick.02', when: { choice: 'spark' },
      turns: [['a', "After that kiss, there wasn't really a choice. {b}."], ['b', "Good answer."]] },
    { id: 'kiss-pick.03', when: { choice: 'spark' },
      stage: '{a} looks along the line, and back at {b}.',
      turns: [['a', "The kiss said it all. {b}, will you couple up with me?"], ['b', "Obviously."]] },
    { id: 'kiss-pick.04', when: { choice: 'spark' },
      turns: [['a', "I'm still thinking about that kiss, if I'm honest. {b}."]],
      beat: '{b} walks over, trying not to look too pleased.' },
    { id: 'kiss-pick.05', when: { choice: 'spark' },
      stage: 'There are a few knowing looks before {a} even says it.',
      turns: [['a', "You all know who I'm going to pick. {b}."]] },
    { id: 'kiss-pick.06', when: { choice: 'flat' },
      turns: [['a', "Our kiss wasn't the best. But I want to get to know {b}."], ['b', "We'll practise."]] },
    { id: 'kiss-pick.07', when: { choice: 'flat' },
      stage: 'There is a pause before {a} says the name.',
      turns: [['a', "It was a bit awkward earlier. I still want to couple up with {b}."]],
      beat: '{b} laughs and comes over.' },
    { id: 'kiss-pick.08', when: { choice: 'flat' },
      turns: [['a', "One kiss isn't everything. {b}, I'd like to couple up with you."]] },
    { id: 'kiss-pick.09', when: { choice: 'flat' },
      stage: '{a} gets up, and {b} is already half out of {b.posAdj} seat.',
      turns: [['a', "We'll get it right next time. {b}."]] },
    { id: 'kiss-pick.10', when: { choice: 'other' },
      turns: [['a', "I kissed someone else tonight, but the person I want to get to know is {b}."]],
      beat: '{b} looks surprised, and very pleased.' },
    { id: 'kiss-pick.11', when: { choice: 'other' },
      stage: 'There is a murmur when {a} says the name.',
      turns: [['a', "{b}. We didn't kiss, but I think we should have."], ['b', "There's time."]] },
    { id: 'kiss-pick.12', when: { choice: 'other' },
      turns: [['a', "The kissing was fun. But I want to couple up with {b}."]],
      beat: '{b} walks over, grinning.' },
    { id: 'kiss-pick.13', when: { choice: 'other' },
      stage: "Heads turn when {a} says the name. It isn't anyone {a} kissed tonight.",
      turns: [['a', "I didn't get the chance with {b}. I'm taking it now."]] },
    { id: 'kiss-pick.14', when: { choice: 'other' },
      turns: [['a', "{b}, I didn't pick you out of the ice, but I'm picking you now."], ['b', "I'll take it."]] },
  ],
  'lady-luck-kiss': [
    { id: 'lady-luck-kiss.01', when: { nth: 'first', choice: 'spark' },
      stage: '{a} walks along the line and stops in front of {b}.',
      turns: [['a', "You're my first."]],
      beat: 'The kiss lands, and {b} is still smiling after {a} has moved on.' },
    { id: 'lady-luck-kiss.02', when: { nth: 'first', choice: 'spark' },
      stage: '{a} goes straight to {b}.',
      turns: [['b', "No hesitation. I like that."]],
      beat: 'The kiss goes on long enough that the host has to clear her throat.' },
    { id: 'lady-luck-kiss.03', when: { nth: 'first', choice: 'spark' },
      stage: 'For the first kiss, {a} chooses {b}.',
      turns: [['a', "Okay. That was good."], ['b', "Just good?"]] },
    { id: 'lady-luck-kiss.04', when: { nth: 'first', choice: 'flat' },
      stage: '{a} goes to {b} first.',
      turns: [['b', "Straight to me? I'm flattered."]],
      beat: 'The kiss is over quickly, and {a} gives the others a little shrug.' },
    { id: 'lady-luck-kiss.05', when: { nth: 'first', choice: 'flat' },
      stage: '{a} picks {b} for the first kiss.',
      turns: [['a', "Don't be nervous."], ['b', "I'm not. You are."]],
      beat: 'It is a nervous kiss, and it shows.' },
    { id: 'lady-luck-kiss.06', when: { nth: 'first', choice: 'flat' },
      stage: '{a} kisses {b} first, and pulls a face at the others afterwards.',
      turns: [['a', "Nothing wrong with it. It was just a kiss."]] },
    { id: 'lady-luck-kiss.07', when: { nth: 'next', choice: 'spark' },
      stage: 'For the second kiss, {a} chooses {b}.',
      turns: [['b', "Saved the best for last."]],
      beat: 'It is a real kiss, and the bench groans.' },
    { id: 'lady-luck-kiss.08', when: { nth: 'next', choice: 'spark' },
      stage: '{a} walks back along the line to {b}.',
      turns: [['a', "Right. Let's see."]],
      beat: 'When they pull apart, {a} is laughing, and {b} looks very sure of {b.ref}.' },
    { id: 'lady-luck-kiss.09', when: { nth: 'next', choice: 'spark' },
      stage: '{a} kisses {b}, and the whole fire pit goes "oooh".',
      turns: [['a', "Okay. That's made it harder."]] },
    { id: 'lady-luck-kiss.10', when: { nth: 'next', choice: 'flat' },
      stage: '{a} walks over to {b} for the second kiss.',
      turns: [['a', "Last one. Make it count."]],
      beat: "It doesn't really count. {a} walks back, thinking." },
    { id: 'lady-luck-kiss.11', when: { nth: 'next', choice: 'flat' },
      stage: '{a} kisses {b}, and then steps back to think.',
      turns: [['a', "Okay. That's both of them."]] },
    { id: 'lady-luck-kiss.12', when: { nth: 'next', choice: 'flat' },
      stage: 'The second kiss is {b}.',
      turns: [['b', "Was that all right?"], ['a', "It was fine!"]],
      beat: '{b} does not look convinced.' },
  ],
  'lady-luck-pick': [
    { id: 'lady-luck-pick.01', when: { choice: 'spark' },
      turns: [['a', "I kissed {b} and I kissed {c}. The one I can't stop thinking about is {b}."]],
      beat: '{c} claps for them, a bit too hard.' },
    { id: 'lady-luck-pick.02', when: { choice: 'spark' },
      stage: '{a} looks from {b} to {c}, but not for long.',
      turns: [['a', "Sorry, {c}. I'm going to couple up with {b}."], ['c', "No, fair enough. I saw that kiss."]] },
    { id: 'lady-luck-pick.03', when: { choice: 'spark' },
      turns: [['a', "Both of those were nice. One was better. {b}."]],
      beat: '{b} steps forward, and {c} sits back down.' },
    { id: 'lady-luck-pick.04', when: { choice: 'spark' },
      stage: '{a} does not need long.',
      turns: [['a', "{b}. Obviously."], ['c', "Yeah, I thought so."]] },
    { id: 'lady-luck-pick.05', when: { choice: 'flat' },
      stage: '{a} looks from {b} to {c} for a long time.',
      turns: [['a', "Neither of those set the world on fire, if I'm honest. {b}."], ['b', "I'll take it."]] },
    { id: 'lady-luck-pick.06', when: { choice: 'flat' },
      turns: [['a', "It wasn't really about the kisses. I get a good feeling about {b}."]],
      beat: '{c} nods, and looks a bit relieved.' },
    { id: 'lady-luck-pick.07', when: { choice: 'flat' },
      stage: '{a} takes a deep breath.',
      turns: [['a', "Sorry, {c}. {b}, let's give it a go."]] },
    { id: 'lady-luck-pick.08', when: { choice: 'passed-up' },
      turns: [['a', "Honestly, the better kiss was {c}. But I want {b}."], ['c', "Are you serious?"]],
      beat: '{b} walks over, looking slightly confused but not complaining.' },
    { id: 'lady-luck-pick.09', when: { choice: 'passed-up' },
      stage: 'Everyone expects {a} to say {c}.',
      turns: [['a', "{b}."], ['c', "After that?"], ['a', "A kiss isn't everything."]] },
    { id: 'lady-luck-pick.10', when: { choice: 'passed-up' },
      turns: [['a', "My head says {b}. The kiss said {c}. I'm going with my head."]],
      beat: '{c} laughs and shakes {c.posAdj} head, and {b} comes to stand next to {a}.' },
    { id: 'lady-luck-pick.11', when: { choice: 'only-one' },
      stage: 'There is only {b} left when {a} gets up.',
      turns: [['a', "Well, Lady Luck has decided for me. {b}."], ['b', "Lucky me."]] },
    { id: 'lady-luck-pick.12', when: { choice: 'only-one' },
      turns: [['a', "One kiss, one choice. {b}, it's you."]],
      beat: '{b} takes {a.posAdj} hand.' },
    { id: 'lady-luck-pick.13', when: { choice: 'only-one' },
      stage: '{a} is the last to choose, and {b} is the last one standing.',
      turns: [['b', "Looks like it's us."], ['a', "Looks like it is."]] },
  ],
};
