// pm/lines/moments.js — the nights the villa remembers (Plan 3, Task 4).
// Data only. Every moment's cast, from pm/moments.js, arrivals.js, casa.js
// and villa-day.js — and what each one already decided:
//
//   entrance       [a]          a walks in (a bombshell; with `split`, Casa's).
//   stand-up       [a, b, (c)]  a stands up for new arrival b; c is a's partner
//                                (only when a is `taken`).
//   nobody-stands  [a]          new arrival a asks, and nobody stands.
//   stand-up-pick  [a, b, (c)]  new arrival a chooses b from those who stood;
//                                `stoleFrom`: c was b's partner.
//   save-setup     [a, b]       a and b are single and at risk: a new arrival decides.
//   bombshell-save [a, b, c]    new arrival a keeps b; c is not chosen.
//   public-match   [a, b, (c)]  the public couple new arrival a with b;
//                                `stoleFrom`: c was b's partner.
//   profile-pick   [a, b]       night one: a picks b from a dating profile.
//   public-couple  [a, b]       night one: the public put a with b.
//   ranking-couple [a, b]       night one: a and b sit in the same place in the
//                                ranking (`rank` top / lower).
//   group-entrance [a, b…]      the rest of a big Casa Amor walk in together;
//                                {a} and {b} are the first two of them.
//   date           [a, b]       new arrival a on a date with b.
//   steal          [a, b, c]    a takes b; c is left single.
//   recouple-pick  [a, b, (c)]  a picks b for the `reason` that carried it
//                                (connection / attraction / safety / loyalty).
//                                `stoleFrom`: b was c's, and b chose a.
//   dump-buildup   [a, b]       a couple at risk. `channel` public / villa.
//   dump-verdict   [a]          a is dumped. `channel` public / villa /
//                                recoupling (left single) / casa.
//   ballot-reveal  [a, b]       a stands and votes to dump b.
//   dump-at-risk   [a]          a alone is at risk (save-one: the public's bottom).
//   dump-verdict-couple [a, b]  a and b, a couple, are dumped together.
//   dump-verdict-singles [a, b…] everyone left single is dumped at once; {a}
//                                and {b} are the first two of them.
//   save-vote      [a, b]       a stands and votes to SAVE b.
//   top-couple-pick [a, b, c, d] a and b, the public's favourite couple, send
//                                c and d home.
//   couples-vote   [a, b, c, d] a and b name c and d as the least compatible.
//   ex-return      [a]          the dumped islanders walk back in to vote,
//                                led by a (the most recent to leave).
//   ex-ballot      [a, b]       ex-islander a votes against b's couple.
//                                `grudge` voted (b voted a out) / moved-on (b
//                                was a's partner and has coupled up since).
//
//   The dumping's `channel` says who decided: public / villa / recoupling /
//   casa, and Plan 4.5's top-couple / save / couples / exes.
//   dump-reaction  [a, b]       a's partner b has just been dumped.
//   solidarity     [a, b]       a leaves with b.
//   dump-goodbye   [a, b] / [a] b hugs a goodbye / a says goodbye to everyone.
//   dump-fallout   [a]          a is suddenly single.
//   casa-return    [a, b]       `choice` stick: b is a's partner. twist: b is
//                                who a brings back, and {pa} is left waiting.
//   photos         [a, b]       a is shown a photo of b at Casa.
//   heart-rate     [a, b]       b set a's heart going most. `coupled` or not.
//   snog-marry-pie [a, b, c, d] a snogs b, marries c, pies d (`full`).
//   movie-night    [a, b…]      a clip of a (and b) plays; {quote} is its line.
//   notes          [a, b]       a wrote an anonymous note about b; `guessed`.
//   families       [a, b]       a's family on b (`verdict` good / bad / unsure).
//   declaration    [a, b]       the final: a speaks to b.
//   walk           [a] / [a, b] a walks (`cause`); with solidarity, a leaves with b.
//   reveal         [a, b…]      the reunion airs what nobody saw; {quote}.
//
// Dior hosts the dumpings, the final and the reunion — warm, dry, and never a
// word ahead of the result she is reading out. Everything else happens by text.
const ch = channel => ({ channel });
export const MOMENTS = {
  entrance: [
    { id: 'entrance.01', when: { split: false },
      stage: 'A text arrives: "Islanders, get ready. A new arrival is on the way." Then {a} walks down the steps.',
      turns: [['a', "Hi, everyone. I'm {a}. Don't all get up at once."]],
      beat: 'Everyone gets up to say hello.' },
    { id: 'entrance.02', when: { split: false },
      stage: '{a} walks into the garden, and every conversation stops.',
      turns: [['a', "Hello! I'm {a}. I've been watching, so I already know who I want to talk to."]],
      beat: 'Two couples shuffle a little closer together.' },
    { id: 'entrance.03', when: { split: false, persona: 'wallflower' },
      stage: '{a} comes down the steps slowly, holding on to the rail.',
      turns: [['a', "Hi. I'm {a}. I'm really nervous, sorry."]],
      beat: 'The girls rush over to give {a.obj} a hug.' },
    { id: 'entrance.04', when: { split: false, persona: 'game-player' },
      stage: '{a} stops at the top of the steps and takes a long look at the villa before coming down.',
      turns: [['a', "I'm {a}. I'm not here to make friends. Well, a few."]] },
    { id: 'entrance.05', when: { split: true },
      stage: 'At Casa Amor, the door opens, and {a} walks in with a suitcase and a big smile.',
      turns: [['a', "Hi! I'm {a}. So which of you are the ones with partners back at the other villa?"]],
      beat: 'Every hand goes up, slowly.' },
    { id: 'entrance.06', when: { split: true },
      stage: 'A new face arrives at Casa Amor, and the whole room goes quiet: {a}.',
      turns: [['a', "Don't worry, I don't bite. Unless you want me to."]],
      beat: 'Somebody laughs too loudly, and then stops.' },
    { id: 'entrance.07', when: { split: true, persona: 'fuckboy' },
      stage: 'At Casa Amor, {a} walks straight to the daybeds and sits in the middle of them.',
      turns: [['a', "I'm {a}. Nobody here is single, right? That's fine. I like a challenge."]] },
    { id: 'entrance.09', when: { split: true },
      stage: 'At Casa Amor, {a} walks out onto the terrace and does a little twirl.',
      turns: [['a', "Right. Who's first?"]] },
    { id: 'entrance.10', when: { split: true },
      stage: '{a} arrives at Casa Amor and heads straight for the drinks.',
      turns: [['a', "I've been told you're all taken. We'll see about that."]] },
    { id: 'entrance.11', when: { split: true },
      stage: 'The Casa Amor door opens, and in walks {a}.',
      turns: [['a', "Hello! Sorry, I'm really nervous. I always talk too much when I'm nervous."]] },
    { id: 'entrance.08', when: { split: true, persona: 'hopeless-romantic' },
      stage: 'At Casa Amor, {a} arrives with a bunch of flowers.',
      turns: [['a', "I'm {a}. I brought flowers. Is that too much? It's too much."]] },
  ],
  'stand-up': [
    { id: 'stand-up.01', when: { taken: false },
      stage: 'The new arrival asks who would like to get to know them. {a} is on {a.posAdj} feet first.',
      turns: [['a', "I'm single. Why not?"]] },
    { id: 'stand-up.02', when: { taken: false },
      stage: '{a} stands up without really thinking about it.',
      turns: [['a', "I've got nothing to lose, have I?"]] },
    { id: 'stand-up.03', when: { taken: true },
      stage: 'Slowly, {a} stands up. {c} is still sitting on the bench.',
      turns: [['c', "Seriously?"], ['a', "I just want to see. That's all."]],
      beat: "{c} doesn't look at {a.obj} again all night." },
    { id: 'stand-up.04', when: { taken: true },
      stage: '{a} stands up, and the whole fire pit turns to look at {c}.',
      turns: [['c', "Wow. Okay."]],
      beat: '{a} keeps {a.posAdj} eyes on the floor.' },
    { id: 'stand-up.05', when: { taken: true, persona: 'game-player' },
      stage: '{a} stands up straight away.',
      turns: [['a', "Sorry, {c}. I'd regret it if I didn't."], ['c', "You'd regret it? Right."]] },
  ],
  'nobody-stands': [
    { id: 'nobody-stands.01',
      stage: 'The new arrival waits. Nobody stands up.',
      turns: [['a', "Oh. Okay. That's a first."]],
      beat: 'The silence goes on for far too long.' },
    { id: 'nobody-stands.02',
      stage: 'Not a single islander gets to their feet for {a}.',
      turns: [['a', "Honestly, I'm not even upset. I'll just have to try harder."]] },
    { id: 'nobody-stands.03',
      turns: [['dior', "{a}, nobody has stood up. That means you are single, and vulnerable."]],
      beat: '{a} laughs, but it is a small laugh.' },
  ],
  'stand-up-pick': [
    { id: 'stand-up-pick.01', when: { stoleFrom: true },
      turns: [['a', "I know it's a lot to ask. But you stood up, and that told me something. {b}, I'm choosing you."]],
      beat: "{b} walks across the fire pit. {c} doesn't move." },
    { id: 'stand-up-pick.02', when: { stoleFrom: true },
      turns: [['a', "{b}. You stood up for me, so I hope you meant it."], ['c', "I hope you did too."]] },
    { id: 'stand-up-pick.03', when: { stoleFrom: false },
      turns: [['a', "There's one person I want to get to know, and that's {b}."]],
      beat: '{b} grins and goes to sit next to {a.obj}.' },
    { id: 'stand-up-pick.04', when: { stoleFrom: false },
      turns: [['a', "Thank you to everyone who stood up. I'm choosing {b}."]] },
  ],
  'save-setup': [
    { id: 'save-setup.01',
      turns: [['dior', "{a}. {b}. You're both single, so you're vulnerable. And the person who decides what happens to you hasn't even met you yet."]],
      beat: '{a} and {b} look at each other.' },
    { id: 'save-setup.02',
      stage: 'A text arrives for the single islanders.',
      turns: [['a', "A new arrival is going to take us on dates, and then choose one of us to save."], ['b', "And the rest of us go home?"]] },
    { id: 'save-setup.03',
      stage: 'The singles sit together on the terrace.',
      turns: [['b', "Well. May the best one win."], ['a', "Don't. I feel sick."]] },
  ],
  'bombshell-save': [
    { id: 'bombshell-save.01',
      turns: [['a', "I had a really nice time with both of you. But the person I want to get to know is {b}."]],
      beat: '{b} hugs {c} before anyone else can.' },
    { id: 'bombshell-save.02',
      turns: [['a', "This is so hard, because it means someone goes home. {b}, I'm saving you."], ['c', "It's fine. I get it."]] },
    { id: 'bombshell-save.03',
      turns: [['a', "{c}, you're lovely, and I'm sorry. But I felt something with {b} straight away."]],
      beat: '{c} nods, and starts saying goodbye.' },
  ],
  'public-match': [
    { id: 'public-match.01', when: { stoleFrom: true },
      turns: [['dior', "The public have been voting for who our new arrival should couple up with. {a}, you are now coupled up with {b}."]],
      beat: '{c} is left sitting on the bench on {c.posAdj} own.' },
    { id: 'public-match.02', when: { stoleFrom: true },
      stage: 'A text arrives: the public have chosen who {a} will couple up with.',
      turns: [['b', "Me? Oh my god."], ['c', "Of course it's you."]] },
    { id: 'public-match.03', when: { stoleFrom: false },
      turns: [['dior', "The public have decided. {a}, the islander you will couple up with is {b}."]],
      beat: '{b} jumps up and gives {a} a hug.' },
    { id: 'public-match.04', when: { stoleFrom: false },
      stage: 'The text arrives, and {b} reads it out.',
      turns: [['b', "The public have coupled me up with {a}!"], ['a', "Well, the public have good taste."]] },
  ],
  'profile-pick': [
    { id: 'profile-pick.01',
      stage: "The girls walk along the row of dating profiles. {a} stops at {b}'s.",
      turns: [['a', "Six foot, loves {b.posAdj} family, can cook. I'm sold."]],
      beat: '{b} walks out, and {a} tries very hard not to scream.' },
    { id: 'profile-pick.02',
      stage: "{a} reads every profile twice before standing by {b}'s.",
      turns: [['a', "The quote made me laugh. That's all I'm going on."]] },
    { id: 'profile-pick.03',
      stage: "{a} picks {b}'s profile, and then {b} walks down the steps.",
      turns: [['a', "Oh, thank god."], ['b', "Is that a good 'thank god'?"]] },
    { id: 'profile-pick.05',
      stage: "{a} hovers between two profiles, then picks {b}'s.",
      turns: [['a', "He says he's a hopeless romantic. We'll see."]],
      beat: '{b} walks out waving, and {a} waves back.' },
    { id: 'profile-pick.06',
      stage: "{a} goes straight to {b}'s profile without reading the others.",
      turns: [['a', "I just liked the name."], ['b', "That's the first time that's ever worked."]] },
    { id: 'profile-pick.07',
      stage: "{a} is the last to choose, and {b}'s is the only profile left.",
      turns: [['a', "Fate, then."]],
      beat: '{b} comes out, and {a} looks very pleased with fate.' },
    { id: 'profile-pick.04',
      stage: "{a} stands next to {b}'s profile.",
      turns: [['a', "I'm going with my gut. I've got a good feeling about this one."]],
      beat: '{b} comes out, and {a} gives a thumbs up to the other girls.' },
  ],
  'public-couple': [
    { id: 'public-couple.04',
      stage: "{b} walks in, and the public's choice for {a} is revealed.",
      turns: [['a', "Oh, the country knows me."]],
      beat: '{b} laughs and gives {a.obj} a hug.' },
    { id: 'public-couple.05',
      stage: '{a} and {b} sit down together on the daybed.',
      turns: [['b', "Do you think we'd have picked each other?"], ['a', "Maybe. We'll never know now."]] },
    { id: 'public-couple.06',
      stage: 'The public put {a} with {b}, and they shake hands like a job interview.',
      turns: [['a', "Nice to meet you. I'm your girlfriend, apparently."]],
      beat: '{b} laughs so hard {b} has to sit down.' },
    { id: 'public-couple.07',
      stage: '{b} is the last one down the steps, and walks straight over to {a}.',
      turns: [['b', "I've been told you're mine."], ['a', "That's one way to say hello."]] },
    { id: 'public-couple.01',
      turns: [['dior', "The public have been voting for the first couples. {a}, the public have chosen {b} for you."]],
      beat: '{b} walks into the villa, and {a} breaks into a smile.' },
    { id: 'public-couple.02',
      stage: '{b} walks down the steps to meet {a} for the first time.',
      turns: [['b', "So the country thinks we're a match."], ['a', "Let's prove them right, then."]] },
    { id: 'public-couple.03',
      stage: '{a} and {b} meet at the fire pit.',
      turns: [['a', "Hi! Apparently we're a couple now."], ['b', "I've had worse first dates."]] },
  ],
  'ranking-couple': [
    { id: 'ranking-couple.05', when: { rank: 'lower' },
      stage: "{a} and {b} are coupled by the ranking, and neither of them minds.",
      turns: [['b', "Honestly, I'd have picked you anyway."]],
      beat: '{a} goes a bit red.' },
    { id: 'ranking-couple.06', when: { rank: 'lower' },
      stage: 'The ranking pairs {a} with {b}.',
      turns: [['a', "Right. Let's show them they got the order wrong."]] },
    { id: 'ranking-couple.07', when: { rank: 'lower' },
      stage: "{a} and {b} walk over to each other when their positions are read out.",
      turns: [['a', "Hello, partner."], ['b', "Hello. This is so strange."]] },
    { id: 'ranking-couple.01', when: { rank: 'top' },
      turns: [['dior', "At the top of both rankings: {a} and {b}. You are our first couple."]],
      beat: '{a} and {b} walk to the middle of the fire pit together, grinning.' },
    { id: 'ranking-couple.02', when: { rank: 'lower' },
      stage: 'The rankings are read out, and {a} and {b} are in the same place.',
      turns: [['a', "So we're matched on being equally fanciable."], ['b', "I'll take it."]] },
    { id: 'ranking-couple.03', when: { rank: 'lower' },
      stage: '{a} and {b} stand side by side after the ranking.',
      turns: [['b', "I'm not going to ask where I came."], ['a', "Probably best."]] },
    { id: 'ranking-couple.04',
      stage: 'The ranking puts {a} and {b} together.',
      turns: [['a', "Hi. I've been wanting to talk to you all day."]],
      beat: '{b} laughs, and takes the seat beside {a.obj}.' },
  ],
  'group-entrance': [
    { id: 'group-entrance.01',
      stage: 'The door opens again, and the rest of the new arrivals walk in together, {a} and {b} at the front.',
      turns: [['a', "Hi, everyone! We're the fun ones."], ['b', "Speak for yourself."]],
      beat: 'Nobody knows who to look at first.' },
    { id: 'group-entrance.02',
      stage: 'A whole group of new faces comes down the steps at once, led by {a}.',
      turns: [['a', "Don't mind us. We're just going to get to know everyone."]],
      beat: '{b} is already waving at somebody across the garden.' },
    { id: 'group-entrance.03',
      stage: '{a}, {b} and the others arrive together, laughing about something from the car.',
      turns: [['b', "We've only known each other an hour and we're already best friends."]] },
  ],
  date: [
    { id: 'date.01',
      stage: 'On the date, at a little table by the sea.',
      turns: [
        ['a', "So. Tell me the truth. Are you happy in there?"],
        { by: 'b', vary: [
          { turns: [['b', "That depends on why you're asking."], ['a', "You know why I'm asking."]] },
          { when: { taken: true, loyal: true },
            turns: [['b', 'Yes. Very. I just wanted to be polite about coming on this date.']], beat: '{a} laughs anyway.' },
          { when: { mood: 'lonely' },
            turns: [['b', "…Not really, if I'm honest."], ['a', "Then let's see what happens."]] },
        ] },
      ] },
    { id: 'date.02',
      turns: [
        ['a', "I picked you because I liked you straight away. On {~telly} and in real life."],
        ['b', "What were you watching me doing?"],
        ['a', 'Being nice to everyone. And being a terrible dancer.'],
      ] },
    { id: 'date.03', when: { bTaken: true },
      turns: [
        ['a', "I know you're coupled up. I'm not going to pretend I don't know."],
        ['b', "Then why pick me?"],
        ['a', "Because I don't think it's working. And I think you know that too."],
      ] },
    { id: 'date.04',
      stage: 'The date is on a boat, and neither of them has ever been on one.',
      turns: [
        ['b', "I think I'm going to be sick."],
        ['a', "Great first date, then."],
      ],
      beat: 'They laugh the whole way back to shore.' },
    { id: 'date.05',
      turns: [
        ['a', "What's your type? Honestly."],
        ['b', 'Kind. Funny. Someone who asks questions and listens to the answer.'],
        ['a', "I'm asking questions."],
        ['b', "You're doing alright so far."],
      ] },
    { id: 'date.06', when: { persona: 'game-player' },
      turns: [
        ['a', "Everyone at home loves you, you know. You're the one people talk about."],
        ['b', 'Is that why you picked me?'],
        ['a', "It's one reason."],
      ],
      beat: '{b} laughs, and doesn\'t ask what the others are.' },
  ],
  steal: [
    { id: 'steal.01',
      stage: 'At the fire pit, {a} has to choose who to couple up with.',
      turns: [
        ['a', "I'm really sorry to do this. But I came in here for {b}, and I'd be lying if I picked anyone else."],
      ],
      beat: "{c} stares at the ground. {b} doesn't look at {c}." },
    { id: 'steal.02',
      stage: 'At the fire pit.',
      turns: [
        ['a', "I've only been here a day. But from the moment I walked in, it's been {b}."],
      ],
      beat: '{b} gets up and walks over. {c} is left sitting alone on the bench.' },
    { id: 'steal.03', when: { persona: 'game-player' },
      stage: 'At the fire pit.',
      turns: [
        ['a', "I know this is going to cause drama. I've made my peace with that. {b}."],
      ],
      beat: '{c} laughs once, with no humour in it, and looks away.' },
    { id: 'steal.04',
      stage: 'At the fire pit.',
      turns: [
        ['a', "I don't want to ruin anyone's couple. But I have to follow my gut, and my gut says {b}."],
        ['c', "…Right."],
      ],
      beat: '{b} squeezes {c.posAdj} arm on the way past.' },
  ],
  'recouple-pick': [
    // connection
    { id: 'recouple-pick.01', when: { reason: 'connection' },
      turns: [
        ['a', "The person I want to couple up with makes me feel like myself. We can talk about anything, and I've never had to pretend."],
        ['a', "That person is {b}."],
      ],
      beat: '{b} gets up and walks straight into {a.posAdj} arms.' },
    { id: 'recouple-pick.02', when: { reason: 'connection' },
      turns: [
        ['a', "This person has been there for me on my best days and my worst ones in here. I don't need to think about it. {b}."],
      ] },
    { id: 'recouple-pick.03', when: { reason: 'connection', rung: ['exclusive', 'official'] },
      turns: [
        ['a', "I don't need to say much, because everyone knows. {b}, it's always been you."],
      ],
      beat: 'The villa cheers before {a} has finished the sentence.' },
    // attraction
    { id: 'recouple-pick.04', when: { reason: 'attraction' },
      turns: [
        ['a', "I'll be honest. The person I'm picking caught my eye the moment I saw them. I want to see where it goes."],
        ['a', "It's {b}."],
      ],
      beat: '{b} laughs, and goes a bit red.' },
    { id: 'recouple-pick.05', when: { reason: 'attraction' },
      turns: [
        ['a', "We haven't had loads of deep chats yet. But there's something there, and I'd be stupid to ignore it. {b}."],
      ] },
    { id: 'recouple-pick.06', when: { reason: 'attraction', early: true },
      turns: [
        ['a', "It's early, and I'm going on a feeling. The feeling is {b}."],
      ] },
    // safety — never a claimed spark
    { id: 'recouple-pick.07', when: { reason: 'safety' },
      turns: [
        ['a', "I'll be honest, we haven't had the spark yet. But you've been nothing but decent to me, and I'd rather build on that than chase something that isn't there."],
        ['a', "{b}."],
      ],
      beat: '{b} nods, and sits down next to {a.obj}.' },
    { id: 'recouple-pick.08', when: { reason: 'safety' },
      turns: [
        ['a', "I trust this person. In here, that counts for a lot. I'm picking {b}."],
      ] },
    { id: 'recouple-pick.09', when: { reason: 'safety', persona: 'game-player' },
      turns: [
        ['a', "This person and I understand each other. We both know what we want out of this. {b}."],
      ],
      beat: '{b} gives {a.obj} a small nod, and nobody else in the villa can read it.' },
    // loyalty — staying put
    { id: 'recouple-pick.10', when: { reason: 'loyalty' },
      turns: [
        ['a', "I don't need to think about this one. I'm staying exactly where I am. {b}."],
      ],
      beat: "{b} is already on {b.posAdj} feet." },
    { id: 'recouple-pick.11', when: { reason: 'loyalty' },
      turns: [
        ['a', "People have tried to turn my head. It hasn't worked. I'm picking {b}, again, and I'll keep picking {b}."],
      ] },
    // a steal: {b} was {c}'s, and chose {a}
    { id: 'recouple-pick.12', when: { stoleFrom: true },
      turns: [
        ['a', "I know this is going to hurt someone. I'm sorry. But I have to be honest about how I feel. {b}."],
      ],
      beat: "{b} looks at {c} first, and then walks over to {a}. {c} doesn't move." },
    { id: 'recouple-pick.13', when: { stoleFrom: true },
      turns: [
        ['a', "The person I'm choosing is already coupled up. I'm choosing them anyway. {b}."],
        ['c', 'Wow.'],
      ],
      beat: 'The fire pit goes completely silent.' },
  ],
  'dump-buildup': [
    { id: 'dump-buildup.01', when: ch('public'),
      turns: [
        ['dior', "Islanders. The public have been voting for their favourite couple."],
        ['dior', "{a}. {b}. You have received the fewest votes."],
      ],
      beat: '{b} takes {a.posAdj} hand, and neither of them looks at anyone else.' },
    { id: 'dump-buildup.02', when: ch('public'),
      turns: [
        ['dior', "The couples with the fewest public votes are at risk of being dumped from the island. The first of those couples…"],
        ['dior', "…is {a} and {b}."],
      ] },
    { id: 'dump-buildup.03', when: ch('villa'),
      turns: [
        ['dior', "{a} and {b}. The public have put you at risk. Now the islanders will decide who stays."],
      ],
      beat: '{a} looks along the bench at the people who are about to vote.' },
    { id: 'dump-buildup.04', when: ch('villa'),
      turns: [
        ['dior', "Good evening, islanders. Tonight, your fate is in each other's hands. {a}, {b}, please stand."],
      ] },
    { id: 'dump-buildup.05', when: ch('top-couple'),
      turns: [
        ['dior', "The public have been voting for their favourite couple. {a} and {b}, you're one of the couples with the fewest votes."],
      ],
      beat: '{a} squeezes {b.posAdj} hand.' },
    { id: 'dump-buildup.06', when: ch('top-couple'),
      turns: [['dior', "{a}. {b}. You're at risk tonight. And it won't be me or the public who decides what happens next."]] },
    { id: 'dump-buildup.07', when: ch('couples'),
      turns: [['dior', "{a} and {b}. Your fellow islanders have voted you one of the least compatible couples in the villa."]],
      beat: "{b} can't look at anyone." },
    { id: 'dump-buildup.08', when: ch('couples'),
      stage: 'The names are read out, and {a} and {b} stand up together.',
      turns: [['a', "I honestly didn't see that coming."], ['b', 'Me neither.']] },
    { id: 'dump-buildup.09', when: ch('exes'),
      turns: [['dior', "{a} and {b}. The islanders have voted you one of the least compatible couples, so you're at risk of being dumped."]] },
    { id: 'dump-buildup.10', when: ch('exes'),
      stage: '{a} and {b} stand together at the front of the fire pit.',
      turns: [['a', "Whatever happens, I'm glad I came in here and met you."], ['b', "Don't say it like that. We're not going anywhere."]] },
  ],
  // Plan 4.5: who decides tonight is the first thing Dior says.
  'dump-at-risk': [
    { id: 'dump-at-risk.01', when: { channel: 'save', gender: 'm' },
      turns: [['dior', "The public have been voting for their favourite boy. {a}, you're one of the boys with the fewest votes."]],
      beat: '{a} stands up and goes to the front.' },
    { id: 'dump-at-risk.02', when: { channel: 'save', gender: 'f' },
      turns: [['dior', "The public have been voting for their favourite girl. {a}, you're one of the girls with the fewest votes."]],
      beat: '{a} stands up and goes to the front.' },
    { id: 'dump-at-risk.03', when: { channel: 'save' },
      turns: [['dior', "{a}, please come and stand next to me."]],
      beat: '{a} walks up, trying to smile.' },
    { id: 'dump-at-risk.05', when: { channel: 'public' },
      turns: [['dior', "The public have been voting for their favourite single islander. {a}, you're one of the islanders at risk."]],
      beat: '{a} stands up slowly.' },
    { id: 'dump-at-risk.06', when: { channel: 'public' },
      turns: [['dior', "Everyone who is single tonight is vulnerable. {a}, please stand."]],
      beat: '{a} looks round at the couples on the benches.' },
    { id: 'dump-at-risk.07', when: { channel: 'public' },
      stage: '{a} stands with the other single islanders.',
      turns: [['a', "Being single in here is the worst place to be."]] },
    { id: 'dump-at-risk.04', when: { channel: 'save' },
      stage: '{a} is called to the front.',
      turns: [['a', "I knew it. I just knew it."]] },
  ],
  'dump-verdict-singles': [
    { id: 'dump-verdict-singles.01',
      stage: 'The text arrives: every islander who is still single has been dumped from the island.',
      turns: [['a', "All of us? At once?"], ['b', "That's it, then."]],
      beat: 'The singles look at each other, and then at their suitcases.' },
    { id: 'dump-verdict-singles.02',
      stage: 'The couples are on the benches. {a}, {b} and the other singles are left standing.',
      turns: [['dior', "I'm sorry. If you're not in a couple tonight, you have been dumped from the island."]],
      beat: '{a} hugs {b} first.' },
    { id: 'dump-verdict-singles.03',
      stage: 'Nobody else is picked, and the singles know what that means.',
      turns: [['b', "I think I knew this morning."], ['a', "Yeah. Me too."]] },
  ],
  'dump-verdict-couple': [
    { id: 'dump-verdict-couple.01', when: ch('public'),
      turns: [['dior', "{a} and {b}. The public have voted, and I'm sorry, but you have been dumped from the island."]],
      beat: '{a} takes {b.posAdj} hand, and they stand up together.' },
    { id: 'dump-verdict-couple.02', when: ch('public'),
      turns: [['dior', "The couple leaving the villa tonight is…"], ['dior', "…{a} and {b}."]],
      beat: 'There is a long silence before anyone moves.' },
    { id: 'dump-verdict-couple.03', when: ch('villa'),
      turns: [['dior', "The islanders have decided. {a} and {b}, you have been dumped from the island."]],
      beat: '{b} puts an arm round {a}.' },
    { id: 'dump-verdict-couple.04', when: ch('villa'),
      stage: 'The last vote is read out.',
      turns: [['a', "That's us, then."], ['b', "At least we're going together."]] },
    { id: 'dump-verdict-couple.05', when: ch('top-couple'),
      turns: [['dior', "{a} and {b}, the couple the public love most have made their decision. You have been dumped from the island."]],
      beat: '{a} and {b} stand up together.' },
    { id: 'dump-verdict-couple.06', when: ch('top-couple'),
      stage: '{a} and {b} are already on their feet.',
      turns: [['a', "It's okay. Honestly. We'd have found it hard to pick too."]] },
    { id: 'dump-verdict-couple.07', when: ch('couples'),
      turns: [['dior', "The islanders have made their choice. {a} and {b}, I'm sorry, you have been dumped from the island."]] },
    { id: 'dump-verdict-couple.08', when: ch('couples'),
      stage: 'The votes are in, and they all point the same way.',
      turns: [['b', "I knew it was us the minute our names were read out."], ['a', "Me too."]] },
    { id: 'dump-verdict-couple.09', when: ch('exes'),
      turns: [['dior', "The people who know this villa best have decided. {a} and {b}, you have been dumped from the island."]],
      beat: 'The villa goes quiet.' },
    { id: 'dump-verdict-couple.10', when: ch('exes'),
      stage: 'The last ex-islander sits down, and the count is clear.',
      turns: [['a', "So close. We were so close."], ['b', "We still got this far."]] },
  ],
  'dump-verdict': [
    { id: 'dump-verdict.14', when: ch('bombshell'),
      turns: [['dior', "{a}, you weren't chosen. I'm sorry, but you have been dumped from the island."]],
      beat: '{a} takes it quietly, and goes to pack.' },
    { id: 'dump-verdict.15', when: ch('bombshell'),
      stage: 'The new arrival has made a choice, and it was not {a}.',
      turns: [['a', "I only went on one date. That's the worst part."]] },
    { id: 'dump-verdict.08', when: ch('top-couple'),
      turns: [['dior', "{a}, the couple the public love most have made their decision. You have been dumped from the island."]],
      beat: '{a} nods slowly.' },
    { id: 'dump-verdict.09', when: ch('save'),
      turns: [['dior', "{a}, you weren't saved. I'm sorry. You have been dumped from the island."]],
      beat: '{a} takes a deep breath and starts hugging people.' },
    { id: 'dump-verdict.10', when: ch('save'),
      stage: 'The last vote is counted, and {a} is not the one they chose to save.',
      turns: [['a', "It's okay. Honestly, it's okay."]] },
    { id: 'dump-verdict.11', when: ch('couples'),
      turns: [['dior', "The islanders have made their choice. {a}, you have been dumped from the island."]] },
    { id: 'dump-verdict.12', when: ch('exes'),
      turns: [['dior', "The people who know this villa best have decided. {a}, you have been dumped from the island."]],
      beat: 'The villa goes quiet.' },
    { id: 'dump-verdict.13', when: ch('exes'),
      stage: 'The last ex-islander sits down, and the count is clear.',
      turns: [['a', "So close. I was so close."]] },
    { id: 'dump-verdict.01', when: ch('public'),
      turns: [['dior', "{a}. I'm sorry. The public have voted, and you have been dumped from the island."]],
      beat: '{a} nods, and doesn\'t cry until the hugs start.' },
    { id: 'dump-verdict.02', when: ch('public'),
      turns: [['dior', "The islander leaving the villa tonight is…"], ['dior', "…{a}."]],
      beat: 'There is a long silence before anyone moves.' },
    { id: 'dump-verdict.03', when: ch('villa'),
      turns: [['dior', "The islanders have decided. {a}, you have been dumped from the island."]],
      beat: '{a} looks along the bench at the people who voted.' },
    { id: 'dump-verdict.04', when: ch('villa'),
      turns: [['dior', "With the most votes from the islanders… {a}. I'm sorry. Please say your goodbyes."]] },
    { id: 'dump-verdict.05', when: ch('recoupling'),
      stage: 'The last text of the night: whoever was not chosen is dumped from the island.',
      turns: [['a', 'That\'s me, then.']],
      beat: 'Nobody knows what to say, so everyone hugs {a.obj} at once.' },
    { id: 'dump-verdict.06', when: ch('recoupling'),
      stage: 'Everyone else is coupled up. {a} is the only one still standing.',
      turns: [['a', "It's fine. It's fine. I knew it might be me."]] },
    { id: 'dump-verdict.07', when: ch('casa'),
      stage: 'After the Casa Amor recoupling, the text arrives: the single islanders are dumped.',
      turns: [['a', "I came back for someone who didn't come back for me."]],
      beat: '{a} picks up the suitcase that was never unpacked.' },
  ],
  'ballot-reveal': [
    { id: 'ballot-reveal.01',
      turns: [['a', "This is so hard. But I'm voting to dump {b}, because I just haven't seen {b.posAdj} couple grow."]],
      beat: "{b} doesn't look at {a.obj}." },
    { id: 'ballot-reveal.02',
      turns: [['a', "I love everyone here. But I'm voting to save the couple I believe in, which means voting against {b}."]] },
    { id: 'ballot-reveal.03', when: { persona: 'game-player' },
      turns: [['a', "I've thought about who's genuine in here. I'm voting to dump {b}."]],
      beat: '{b} laughs once, and shakes {b.posAdj} head.' },
    { id: 'ballot-reveal.04',
      turns: [['a', "I'm sorry, {b}. It's not personal. I just don't think you're here for the right reasons."]],
      beat: "{b} mouths 'it's fine'." },
    { id: 'ballot-reveal.05', when: { loyal: true },
      turns: [['a', "I've got nothing against {b}. I just have to go with the couple that's been there for me. So it's {b}."]] },
    { id: 'ballot-reveal.06',
      turns: [['a', "I didn't want to do this. My vote is for {b} to leave."]],
      beat: 'The rest of the bench goes very still.' },
    { id: 'ballot-reveal.07',
      turns: [['a', "My vote goes to {b}. I just think the other couple has more going for it."]] },
    { id: 'ballot-reveal.08',
      turns: [['a', "This is the worst part of being in here. I'm voting for {b} to go."]],
      beat: '{b} nods. {b} saw it coming.' },
    { id: 'ballot-reveal.09', when: { feels: 'little' },
      turns: [['a', "I haven't spent much time with {b}, and that's why I'm voting this way. It's {b}."]] },
    { id: 'ballot-reveal.10',
      turns: [['a', "It's nothing {b} has done. I'm just backing the couple I've seen grow. So it's {b}."]] },
    { id: 'ballot-reveal.11',
      stage: '{a} stands up and takes a moment.',
      turns: [['a', "The person I'm voting for is {b}. I'm sorry."]] },
  ],
  'save-vote': [
    { id: 'save-vote.01',
      turns: [['a', "I'm saving {b}, because {b} has been a real friend to me since day one."]],
      beat: '{b} mouths "thank you".' },
    { id: 'save-vote.02',
      turns: [['a', "This is so hard, because I don't want anyone to go. But I'm saving {b}."]] },
    { id: 'save-vote.03', when: { feels: 'strong' },
      turns: [['a', "I think everyone knows what I'm going to say. I'm saving {b}."]],
      beat: '{b} laughs, and wipes {b.posAdj} eyes.' },
    { id: 'save-vote.04', when: { persona: 'game-player' },
      turns: [['a', "I've thought about who I trust in here. I'm saving {b}."]] },
    { id: 'save-vote.05',
      turns: [['a', "I haven't seen {b} get a real chance yet. So I want to save {b}."]] },
  ],
  'top-couple-pick': [
    { id: 'top-couple-pick.01',
      stage: '{a} and {b} stand up, holding hands.',
      turns: [
        ['a', "This is the hardest thing we've had to do in here."],
        ['b', "We've talked about it a lot, and it's not about who we like more."],
        ['a', "The couple we're sending home is {c} and {d}."],
      ],
      beat: '{c} puts an arm round {d}.' },
    { id: 'top-couple-pick.02',
      turns: [
        ['b', "We just went with the couple we think is least likely to work on the outside."],
        ['a', "And we're so sorry. It's {c} and {d}."],
      ],
      beat: "{d} nods, and doesn't say anything." },
    { id: 'top-couple-pick.03',
      stage: '{a} looks at {b}, and {b} nods.',
      turns: [
        ['a', "We love you all, and this isn't personal. We're dumping {c} and {d}."],
        ['c', "It's fine. You had to pick someone."],
      ] },
    { id: 'top-couple-pick.04',
      turns: [
        ['a', "Me and {b} agreed straight away, and we still hated doing it."],
        ['b', "It's {c} and {d}. We're sorry."],
      ] },
  ],
  'couples-vote': [
    { id: 'couples-vote.01',
      stage: '{a} and {b} stand up together.',
      turns: [
        ['a', "The couple we think is least compatible is {c} and {d}."],
        ['b', "We just haven't seen it grow."],
      ],
      beat: "{c} and {d} look at each other." },
    { id: 'couples-vote.02',
      turns: [
        ['b', "It's not easy, but we've gone for {c} and {d}."],
        ['a', "We don't think they're on the same page."],
      ] },
    { id: 'couples-vote.03',
      turns: [
        ['a', "{c} and {d}. Sorry, guys."],
        ['c', "No, it's fine. It's a game."],
      ],
      beat: "{d} doesn't say anything." },
    { id: 'couples-vote.04', when: { persona: 'game-player' },
      turns: [
        ['a', "We've watched every couple in here, and the one that doesn't add up for us is {c} and {d}."],
      ],
      beat: '{d} raises an eyebrow at {a}.' },
    { id: 'couples-vote.05',
      turns: [
        ['b', "Our vote goes to {c} and {d}. We love you both, we just don't see it."],
      ] },
    { id: 'couples-vote.06',
      turns: [
        ['a', "We've gone for {c} and {d}, because we've never really seen them together."],
        ['b', "It feels like they're just coupled up because they have to be."],
      ],
      beat: '{c} folds {c.posAdj} arms.' },
    { id: 'couples-vote.07',
      stage: '{a} and {b} look at each other before they speak.',
      turns: [
        ['b', "This is horrible. It's {c} and {d}."],
      ] },
    { id: 'couples-vote.08',
      turns: [
        ['a', "We love {c}, and we love {d}. We just don't love them together. So it's them."],
      ],
      beat: '{d} laughs, but only a little.' },
    { id: 'couples-vote.09',
      turns: [
        ['a', "We had a long chat about this."],
        ['b', "And we both said the same couple straight away. {c} and {d}."],
      ] },
    { id: 'couples-vote.10',
      turns: [
        ['b', "We don't think {c} and {d} are on the same page. Sorry, both of you."],
        ['c', "It's okay. We knew someone would say it."],
      ] },
  ],
  'ex-return': [
    { id: 'ex-return.01',
      stage: 'The villa door opens, and the dumped islanders walk back down the steps, {a} at the front.',
      turns: [['a', "Hello, everyone. Did you miss us?"]],
      beat: 'Half the fire pit screams.' },
    { id: 'ex-return.02',
      stage: 'The dumped islanders file in and sit on the bench at the side of the fire pit.',
      turns: [['dior', "Islanders, some familiar faces have come back for one night only. They've been watching everything."]],
      beat: 'Nobody at the fire pit knows where to look.' },
    { id: 'ex-return.03',
      stage: '{a} leads the dumped islanders in.',
      turns: [['a', "It's so weird being back. It looks exactly the same."]],
      beat: 'The couples at the fire pit go very quiet.' },
    { id: 'ex-return.04',
      turns: [['dior', "Tonight, the islanders you said goodbye to will decide who goes. Please welcome them back."]],
      beat: '{a} walks in first, and gives the fire pit a little wave.' },
  ],
  'ex-ballot': [
    { id: 'ex-ballot.01', when: { grudge: 'voted' },
      turns: [['a', "{b} voted to send me home. I haven't forgotten. So my vote goes against {b}."]],
      beat: '{b} holds {a.posAdj} gaze.' },
    { id: 'ex-ballot.02', when: { grudge: 'voted' },
      turns: [['a', "When I was at risk, {b} didn't back me. Tonight I'm not backing {b}."]] },
    { id: 'ex-ballot.03', when: { grudge: 'moved-on' },
      turns: [['a', "{b} told me I was the one, and then coupled up with someone else the minute I left. I'm voting against {b}."]],
      beat: 'The whole fire pit turns to look at {b}.' },
    { id: 'ex-ballot.04', when: { grudge: 'moved-on' },
      turns: [['a', "I'm not voting out of revenge. But I've seen how {b} acts from the outside, and I don't believe it."]] },
    { id: 'ex-ballot.05',
      turns: [['a', "I've watched it all back. The couple I don't believe in is {b}'s."]] },
    { id: 'ex-ballot.06',
      turns: [['a', "Watching from home, you see everything. And I don't think {b} is here for the right reasons."]],
      beat: "{b} shakes {b.posAdj} head." },
    { id: 'ex-ballot.07',
      turns: [['a', "I barely got to know {b} in here. From the outside, it doesn't look real."]] },
    { id: 'ex-ballot.08',
      turns: [['a', "Everyone at home has been talking about {b}'s couple. And not in a good way. That's who I'm voting for."]] },
    { id: 'ex-ballot.09',
      turns: [['a', "This isn't easy, because I like everyone here. But I'm voting against {b}."]],
      beat: '{b} nods, and looks at the floor.' },
    { id: 'ex-ballot.10', when: { persona: 'game-player' },
      turns: [['a', "I know how the game works now. And {b} has been playing it. My vote goes against {b}."]] },
    { id: 'ex-ballot.11',
      turns: [['a', "When you watch it back, you see who's genuine. I don't think {b} is. Sorry."]] },
    { id: 'ex-ballot.12',
      turns: [['a', "I'm going with my gut. It's {b}'s couple."]],
      beat: "{b} doesn't react." },
  ],
  'dump-reaction': [
    { id: 'dump-reaction.01',
      turns: [['a', "No. No, that's not fair."], ['b', "It's okay. It's okay. You stay and win this."]],
      beat: '{a} holds on to {b} and won\'t let go.' },
    { id: 'dump-reaction.02', when: { feels: 'strong' },
      turns: [['a', "I don't want to be in here without you."], ['b', 'You have to. Promise me you will.']] },
    { id: 'dump-reaction.03', when: { feels: 'little' },
      turns: [['a', "I'm really sorry. I'm going to miss you."], ['b', "You'll be fine."]],
      beat: 'The hug is short.' },
    { id: 'dump-reaction.04', when: { attachment: 'avoidant' },
      turns: [['a', "…Go on. Go and pack. I'll help you."]],
      beat: "{a} doesn't cry until {b} has gone." },
    { id: 'dump-reaction.05', when: { rung: ['exclusive', 'official'] },
      turns: [['a', "Wait for me. I'll see you on the outside."], ['b', "I'll be waiting."]],
      beat: 'They kiss, and the whole villa goes quiet.' },
    { id: 'dump-reaction.06',
      turns: [['a', "I can't believe it's you."], ['b', "Neither can I."]] },
  ],
  solidarity: [
    { id: 'solidarity.01',
      turns: [['a', "If you're going, I'm going."], ['b', "Don't. Don't give this up for me."], ['a', "I'm not giving anything up. You're what I came here for."]],
      beat: '{a} goes to pack, and the villa watches in silence.' },
    { id: 'solidarity.02',
      stage: '{a} stands up before the verdict is even finished.',
      turns: [['a', "I'm sorry, everyone. I'm leaving with {b}."], ['dior', "{a}, are you sure?"], ['a', "I've never been more sure."]] },
    { id: 'solidarity.03', when: { rung: 'official' },
      turns: [['a', "We came in as two people. We're leaving as a couple."]],
      beat: '{b} starts crying. Then everyone does.' },
    { id: 'solidarity.04',
      turns: [['a', "I don't want to be here without you. I'm coming with you."]],
      beat: '{b} tries to argue, and gives up halfway through.' },
  ],
  'dump-goodbye': [
    { id: 'dump-goodbye.01', when: { withB: true },
      turns: [['b', "I'm going to miss you so much."], ['a', 'Stay in touch. I mean it.']],
      beat: 'They hug for a long time.' },
    { id: 'dump-goodbye.02', when: { withB: true },
      turns: [['b', 'Win this for me.'], ['a', "It's you that has to win it now."]] },
    { id: 'dump-goodbye.03', when: { withB: true },
      turns: [['b', "This place won't be the same."], ['a', "Look after everyone for me."]] },
    { id: 'dump-goodbye.04', when: { withB: true, gender: 'f', bGender: 'f' },
      turns: [['b', "{~Girl}, I'm going to call you the second you're out."], ['a', "You'd better."]] },
    { id: 'dump-goodbye.05', when: { withB: false },
      stage: 'At the top of the steps, {a} turns round one last time.',
      turns: [['a', "Love you all. Don't do anything I wouldn't do."]],
      beat: 'The villa waves until {a} is out of sight.' },
    { id: 'dump-goodbye.06', when: { withB: false },
      stage: '{a} picks up the suitcase.',
      turns: [['a', "Thank you for everything. Honestly. It's been the best few weeks of my life."]] },
    { id: 'dump-goodbye.07', when: { withB: false, early: true },
      stage: '{a} picks up the suitcase.',
      turns: [['a', "I didn't even get to unpack properly."]],
      beat: 'Everyone laughs, and it helps a little.' },
  ],
  'dump-fallout': [
    { id: 'dump-fallout.01',
      stage: "Back at the villa, {a} is sitting on the empty side of the bed.",
      turns: [['a', "What do I do now?"]] },
    { id: 'dump-fallout.02',
      stage: 'In the kitchen, the next morning.',
      turns: [['a', "I'm single in the villa. Great. That's great."]] },
    { id: 'dump-fallout.03', when: { mood: 'heartbroken' },
      stage: '{a} is lying on the daybed with a pillow over {a.posAdj} face.',
      turns: [['a', "Don't. I know. I just need a minute."]] },
    { id: 'dump-fallout.04', when: { persona: 'game-player' },
      stage: '{a} is already looking around the garden.',
      turns: [['a', "Right. I'm single. So everyone's back on the table."]] },
  ],
  'casa-return': [
    { id: 'casa-return.01', when: { choice: 'stick', withB: true },
      stage: 'The Casa Amor recoupling. {b} is waiting at the fire pit.',
      turns: [['a', 'I came back on my own.'], ['b', '…You came back on your own.']],
      beat: '{b} runs to {a.obj}, and they nearly knock each other over.' },
    { id: 'casa-return.02', when: { choice: 'stick', withB: true },
      turns: [['b', "I didn't know if you'd come back for me."], ['a', "There was never any doubt. Not once."]] },
    { id: 'casa-return.03', when: { choice: 'stick', withB: true, mood: 'guilty' },
      turns: [['a', "I came back on my own."], ['b', "I know. Thank you."]],
      beat: "{a} holds {b} tight, and doesn't meet anyone else's eye." },
    { id: 'casa-return.04', when: { choice: 'twist', taken: true },
      stage: '{a} walks in holding hands with {b}. {pa} is waiting at the fire pit.',
      turns: [['a', "I'm sorry. I had to follow my heart."]],
      beat: '{pa} gets up and walks straight into the villa without a word.' },
    { id: 'casa-return.05', when: { choice: 'twist', taken: true },
      stage: '{a} walks in with {b}.',
      turns: [['a', "I didn't go in there looking for this. It just happened."]],
      beat: '{pa} laughs, and then starts crying.' },
    { id: 'casa-return.06', when: { choice: 'twist', taken: true, persona: 'fuckboy' },
      stage: '{a} walks in with {b}, and doesn\'t let go of {b.posAdj} hand.',
      turns: [['a', "Look, I'm not going to lie. I had a great time at Casa."]],
      beat: 'Nobody at the fire pit says anything.' },
    { id: 'casa-return.08', when: { choice: 'stick', withB: false },
      stage: '{a} walks back into the villa on {a.posAdj} own.',
      turns: [['a', "Nobody at Casa was for me. I'd rather come back single than pretend."]] },
    { id: 'casa-return.09', when: { choice: 'stick', withB: false },
      stage: 'The last of the Casa islanders comes back through the door. {a} is alone.',
      turns: [['a', "I'm back. On my own. I'm fine with that."]] },
    { id: 'casa-return.07', when: { choice: 'twist', taken: false },
      stage: '{a} walks back in with {b}.',
      turns: [['a', "I was single when I left, and I'm not single now."]],
      beat: 'The villa cheers for them.' },
  ],
  photos: [
    { id: 'photos.01',
      stage: 'At the fire pit, the photos from Casa Amor are handed round. {a} is holding one of {b}.',
      turns: [['a', "I'm going to be sick."], ['b', "It's not what it looks like."], ['a', "It's exactly what it looks like."]] },
    { id: 'photos.02',
      stage: 'A photo of {b}, on a daybed at Casa, much too close to somebody.',
      turns: [['a', 'You told me nothing happened.'], ['b', 'Nothing did happen. Not really.'], ['a', '"Not really."']],
      beat: '{a} puts the photo face down on the bench.' },
    { id: 'photos.03', when: { archetype: 'hothead' },
      stage: '{a} stares at the photo of {b}.',
      turns: [['a', "Are you serious? Are you actually serious?"]],
      beat: 'Two people have to get between them.' },
    { id: 'photos.04', when: { attachment: 'anxious' },
      stage: '{a} looks at the photo of {b} for a long time.',
      turns: [['a', "I trusted you. I sat here every night and trusted you."]],
      beat: "{a} can't finish the sentence." },
    { id: 'photos.05', when: { attachment: 'avoidant' },
      stage: '{a} glances at the photo of {b}, and hands it straight back.',
      turns: [['a', "Right. Okay. Good to know."]],
      beat: '{b} tries to talk to {a.obj} later. {a} is already asleep, or pretending to be.' },
  ],
  'heart-rate': [
    { id: 'heart-rate.01', when: { coupled: true },
      stage: "The heart-rate challenge. {a}'s monitor goes wild for one person: {b}.",
      turns: [['b', 'Obviously.'], ['a', "Don't look so smug about it."]] },
    { id: 'heart-rate.02', when: { coupled: true },
      stage: "{a}'s heart rate jumps the moment {b} starts dancing.",
      turns: [['a', "I can't help it. I'm not even embarrassed."]] },
    { id: 'heart-rate.03', when: { coupled: false, taken: true },
      stage: "{a}'s heart rate spikes for {b}, not for {pa}.",
      turns: [['a', "That doesn't mean anything. It's a machine."]],
      beat: '{pa} looks at the screen, and then at {a}.' },
    { id: 'heart-rate.04', when: { coupled: false, taken: true },
      stage: "The biggest spike of {a}'s whole afternoon is for {b}. {pa} is sitting right there.",
      turns: [['a', "…It was the dancing. It was very good dancing."]],
      beat: "{pa} doesn't laugh." },
    { id: 'heart-rate.05', when: { coupled: false, taken: false },
      stage: "{a}'s heart goes for {b}, and the whole villa turns to look.",
      turns: [['a', "Oh no. Well. Now everyone knows."]] },
    { id: 'heart-rate.06', when: { coupled: false, taken: false, persona: 'wallflower' },
      stage: "{a}'s monitor jumps for {b}, and {a} goes bright red.",
      turns: [['a', "Can we move on? Please?"]] },
  ],
  'snog-marry-pie': [
    { id: 'snog-marry-pie.01', when: { full: true },
      stage: '{a} stands up with the three cards.',
      turns: [['a', "Snog, {b}. Marry, {c}, obviously. Pie…"], ['a', 'Sorry, {d}.']],
      beat: '{d} takes a face full of cream, and takes it well.' },
    { id: 'snog-marry-pie.02', when: { full: true },
      turns: [['a', "I'd marry {c}. I'd snog {b}, just once, to see. And the pie is for {d}, who knows why."]],
      beat: '{d} asks why, through a face full of cream.' },
    { id: 'snog-marry-pie.03', when: { full: true, taken: true },
      turns: [['a', "Marry, {c}. Snog… {b}."], ['a', "And {d}, I'm really sorry."]],
      beat: '{pa} goes very quiet when the snog is called.' },
    { id: 'snog-marry-pie.04', when: { full: true, persona: 'messy' },
      turns: [['a', "Snog, {b}. Marry, {c}. And pie, {d}, because {d} knows exactly what {d} did."]],
      beat: 'The whole villa goes "ooooh".' },
    { id: 'snog-marry-pie.05',
      turns: [['a', "I'm not playing this properly. I'm just going to pie someone."]],
      beat: 'The cream goes everywhere.' },
  ],
  'movie-night': [
    { id: 'movie-night.01', when: { hasQuote: true },
      stage: 'Movie Night. The screen shows {quoteWho}, earlier in the week, saying: "{quote}"',
      turns: [['a', "Oh no. Oh, no."]],
      beat: 'The whole villa turns to look.' },
    { id: 'movie-night.02', when: { taken: true, hasQuote: true },
      stage: 'Movie Night. A clip of {a} plays. {quoteWho}: "{quote}" {pa} is sitting right next to {a.obj}.',
      turns: [['a', "I can explain."]],
      beat: '{pa} moves to the other end of the sofa.' },
    { id: 'movie-night.03', when: { taken: true },
      stage: 'Movie Night. A clip of {a} from earlier in the week plays, and {pa} is watching every second of it.',
      turns: [['a', "That was out of context. That was so out of context."]],
      beat: '{pa} gets up and goes to get a drink, and doesn\'t come back.' },
    { id: 'movie-night.04', when: { hasQuote: true },
      stage: 'Movie Night. The next clip is from a chat nobody else saw. {quoteWho}: "{quote}"',
      turns: [['a', "…Can we pause it? Can someone pause it?"]],
      beat: 'Nobody pauses it.' },
    { id: 'movie-night.05', when: { taken: true, attachment: 'avoidant' },
      stage: 'Movie Night. A clip of {a} plays, from a moment {a} thought nobody would see.',
      turns: [['a', "Yep. I said that."]],
      beat: '{pa} stares at {a}, and {a} keeps looking at the screen.' },
  ],
  notes: [
    { id: 'notes.01', when: { guessed: true },
      stage: 'An anonymous note is read out about {b}: someone in the villa thinks {b} is two-faced.',
      turns: [['b', "I know who wrote that."]],
      beat: '{b} is looking straight at {a}.' },
    { id: 'notes.02', when: { guessed: false },
      stage: 'An anonymous note about {b} is read out to the whole villa.',
      turns: [['b', "Whoever wrote that, you could have just said it to my face."]],
      beat: '{a} keeps a straight face, and says nothing.' },
    { id: 'notes.03', when: { guessed: false },
      stage: "The note says {b} is only here for the followers.",
      turns: [['b', "Wow. Okay. That's nice."]],
      beat: '{b} guesses the wrong person. {a} says nothing.' },
    { id: 'notes.04', when: { guessed: true, archetype: 'hothead' },
      stage: 'A note about {b} is read out.',
      turns: [['b', "{a}. That was you. I know it was you."], ['a', "I don't know what you're talking about."]],
      beat: "{a} doesn't meet {b.posAdj} eye." },
  ],
  families: [
    { id: 'families.01', when: { verdict: 'good' },
      stage: "A video from {a}'s family plays on the screen.",
      turns: [['a', "They love you. They actually love you."], ['b', 'Stop. They said that?']],
      beat: '{b} cries harder than {a} does.' },
    { id: 'families.02', when: { verdict: 'good' },
      stage: "{a}'s family have come to the villa. After an hour with {b}, they're all laughing together.",
      turns: [['a', "I've never brought anyone home before. I think this counts."]] },
    { id: 'families.03', when: { verdict: 'bad' },
      stage: "{a}'s family are polite to {b}. Very polite.",
      turns: [['a', "They're just protective. They'll come round."], ['b', "Will they?"]] },
    { id: 'families.04', when: { verdict: 'bad' },
      stage: "{a}'s family take {a} aside on the terrace, away from {b}.",
      turns: [['a', "They're not sure about you. They've watched everything."]],
      beat: '{b} nods, and looks down at the floor.' },
    { id: 'families.05', when: { verdict: 'unsure' },
      stage: "{a}'s family meet {b} for the first time.",
      turns: [['a', "They're still making their minds up. That's normal. Right?"], ['b', "I hope so."]] },
    { id: 'families.06', when: { verdict: 'unsure' },
      stage: "After the visit, {a} and {b} sit on the daybed together.",
      turns: [['b', "How did I do?"], ['a', "Honestly? I can't tell. They were really hard to read."]] },
  ],
  declaration: [
    { id: 'declaration.01',
      stage: 'The final. {a} stands at the fire pit and turns to {b}.',
      turns: [['a', "When I came in here, I didn't think I'd find anything real. Then I met you, and everything changed."]],
      beat: '{b} is already crying.' },
    { id: 'declaration.02',
      stage: 'The final. {a} unfolds a piece of paper, and then puts it away.',
      turns: [['a', "I wrote a speech. I'm not going to read it. I'm just going to say that I love you."]] },
    { id: 'declaration.03', when: { rung: 'official' },
      stage: 'The final.',
      turns: [['a', "You're my {b.gf}. You're my best friend. Whatever the public says tonight, I've already won."]],
      beat: 'The villa, watching from the benches, loses it.' },
    { id: 'declaration.04', when: { persona: 'villa-clown' },
      stage: 'The final.',
      turns: [['a', "I promised myself I wouldn't cry. I'm crying. {b}, you did this to me."]],
      beat: '{b} laughs, through tears.' },
    { id: 'declaration.05', when: { attachment: 'avoidant' },
      stage: 'The final.',
      turns: [['a', "I'm not good at this. I don't say things. So I'll say this once. I love you."]],
      beat: '{b} gets up and kisses {a.obj} before the speech is even finished.' },
    { id: 'declaration.06', when: { feels: 'little' },
      stage: 'The final.',
      turns: [['a', "We've been through so much in here. You've been an amazing partner, and I'll always be grateful."]],
      beat: '{b} smiles, and squeezes {a.posAdj} hand.' },
  ],
  walk: [
    { id: 'walk.01', when: { cause: 'heartbreak' },
      stage: '{a} asks to speak to everyone at the fire pit.',
      turns: [['a', "I can't stay here and watch it every day. I'm going home."]],
      beat: 'Nobody tries to talk {a.obj} out of it.' },
    { id: 'walk.02', when: { cause: 'homesick' },
      stage: '{a} gathers everyone in the kitchen.',
      turns: [['a', "I miss home. I miss my family. I've given it everything, and I've got nothing left."]] },
    { id: 'walk.03', when: { cause: 'homesick' },
      stage: '{a} has packed in the night.',
      turns: [['a', "I love you all. But I'm not happy, and I don't want to pretend for the cameras."]] },
    { id: 'walk.04', when: { cause: 'solidarity', withB: true },
      stage: '{b} is leaving, and {a} stands up.',
      turns: [['a', "I'm going with {b}. There's nothing for me here without {b.obj}."]],
      beat: 'The villa watches the two of them walk up the steps together.' },
    { id: 'walk.05', when: { cause: 'solidarity', withB: false },
      stage: '{a} has decided to leave with {a.posAdj} partner.',
      turns: [['a', "I came in for love. I'm leaving with it."]] },
    { id: 'walk.06', when: { cause: 'heartbreak', mood: 'heartbroken' },
      stage: 'The next morning, {a} is sitting on a packed suitcase by the door.',
      turns: [['a', "I'm not being dramatic. I just can't do it any more."]] },
  ],
  reveal: [
    { id: 'reveal.01', when: { hasQuote: true },
      stage: 'The reunion. The host introduces a clip the viewers never saw.',
      turns: [['dior', "Let's take a look at a moment that didn't make it to air."], ['dior', "Here's {quoteWho}: \"{quote}\""]],
      beat: 'The studio gasps.' },
    { id: 'reveal.02',
      turns: [['dior', "{a}, we have to talk about this one."], ['a', "I knew you were going to show that."]],
      beat: 'The audience gasps anyway.' },
    { id: 'reveal.03', when: { hasQuote: true },
      stage: 'The reunion. The clip plays. {quoteWho}: "{quote}"',
      turns: [['dior', "{a}. Would you like to explain?"], ['a', "Honestly? No."]],
      beat: 'The studio laughs, and {a} does too, eventually.' },
    { id: 'reveal.04', when: { withB: true },
      stage: 'The reunion. A clip nobody saw plays, and {b} is in it too.',
      turns: [['dior', "{b}, you look very surprised."], ['b', "I'm surprised they filmed it."]] },
  ],
};
