// pm/lines/moments.js — the nights the villa remembers (Plan 3, Task 4).
// Data only. Every moment's cast, from pm/moments.js, arrivals.js, casa.js
// and villa-day.js — and what each one already decided:
//
//   entrance       [a]          a walks in (a bombshell; with `split`, Casa's).
//   date           [a, b]       new arrival a on a date with b.
//   steal          [a, b, c]    a takes b; c is left single.
//   recouple-pick  [a, b, (c)]  a picks b for the `reason` that carried it
//                                (connection / attraction / safety / loyalty).
//                                `stoleFrom`: b was c's, and b chose a.
//   dump-buildup   [a, b]       a couple at risk. `channel` public / villa.
//   dump-verdict   [a]          a is dumped. `channel` public / villa /
//                                recoupling (left single) / casa.
//   ballot-reveal  [a, b]       a stands and votes to dump b.
//   dump-reaction  [a, b]       a's partner b has just been dumped.
//   solidarity     [a, b]       a leaves with b.
//   dump-goodbye   [a, b] / [a] b hugs a goodbye / a says goodbye to everyone.
//   dump-fallout   [a]          a is suddenly single.
//   casa-return    [a, b]       `choice` stick: b is a's partner. twist: b is
//                                who a brings back, and {pa} is left waiting.
//   photos         [a, b]       a is shown a photo of b at Casa.
//   heart-rate     [a, b]       b set a's heart going most. `coupled` or not.
//   snog-marry-pie [a, b, c, d] a snogs b, marries c, pies d (`full`).
//   movie-night    [a, b…]      a clip of a (and b) plays; {quote} is its line.
//   notes          [a, b]       a wrote an anonymous note about b; `guessed`.
//   families       [a, b]       a's family on b (`verdict` good / bad / unsure).
//   declaration    [a, b]       the final: a speaks to b.
//   walk           [a] / [a, b] a walks (`cause`); with solidarity, a leaves with b.
//   reveal         [a, b…]      the reunion airs what nobody saw; {quote}.
//
// Dior hosts the dumpings, the final and the reunion — warm, dry, and never a
// word ahead of the result she is reading out. Everything else happens by text.
const ch = channel => ({ channel });
export const MOMENTS = {
  entrance: [
    { id: 'entrance.01', when: { split: false },
      stage: 'A text arrives: "Islanders, get ready. A new arrival is on the way." Then {a} walks down the steps.',
      turns: [['a', "Hi, everyone. I'm {a}. Don't all get up at once."]],
      beat: 'Everyone gets up to say hello.' },
    { id: 'entrance.02', when: { split: false },
      stage: '{a} walks into the garden, and every conversation stops.',
      turns: [['a', "Hello! I'm {a}. I've been watching, so I already know who I want to talk to."]],
      beat: 'Two couples shuffle a little closer together.' },
    { id: 'entrance.03', when: { split: false, persona: 'wallflower' },
      stage: '{a} comes down the steps slowly, holding on to the rail.',
      turns: [['a', "Hi. I'm {a}. I'm really nervous, sorry."]],
      beat: 'The girls rush over to give {a.obj} a hug.' },
    { id: 'entrance.04', when: { split: false, persona: 'game-player' },
      stage: '{a} stops at the top of the steps and takes a long look at the villa before coming down.',
      turns: [['a', "I'm {a}. I'm not here to make friends. Well, a few."]] },
    { id: 'entrance.05', when: { split: true },
      stage: 'At Casa Amor, the door opens, and {a} walks in with a suitcase and a big smile.',
      turns: [['a', "Hi! I'm {a}. So which of you are the ones with partners back at the other villa?"]],
      beat: 'Every hand goes up, slowly.' },
    { id: 'entrance.06', when: { split: true },
      stage: 'A new face arrives at Casa Amor, and the whole room goes quiet: {a}.',
      turns: [['a', "Don't worry, I don't bite. Unless you want me to."]],
      beat: 'Somebody laughs too loudly, and then stops.' },
    { id: 'entrance.07', when: { split: true, persona: 'fuckboy' },
      stage: 'At Casa Amor, {a} walks straight to the daybeds and sits in the middle of them.',
      turns: [['a', "I'm {a}. Nobody here is single, right? That's fine. I like a challenge."]] },
    { id: 'entrance.08', when: { split: true, persona: 'hopeless-romantic' },
      stage: 'At Casa Amor, {a} arrives with a bunch of flowers.',
      turns: [['a', "I'm {a}. I brought flowers. Is that too much? It's too much."]] },
  ],
  date: [
    { id: 'date.01',
      stage: 'On the date, at a little table by the sea.',
      turns: [
        ['a', "So. Tell me the truth. Are you happy in there?"],
        { by: 'b', vary: [
          { turns: [['b', "That depends on why you're asking."], ['a', "You know why I'm asking."]] },
          { when: { taken: true, loyal: true },
            turns: [['b', 'Yes. Very. I just wanted to be polite about coming on this date.']], beat: '{a} laughs anyway.' },
          { when: { mood: 'lonely' },
            turns: [['b', "…Not really, if I'm honest."], ['a', "Then let's see what happens."]] },
        ] },
      ] },
    { id: 'date.02',
      turns: [
        ['a', "I picked you because I liked you straight away. On {~telly} and in real life."],
        ['b', "What were you watching me doing?"],
        ['a', 'Being nice to everyone. And being a terrible dancer.'],
      ] },
    { id: 'date.03', when: { bTaken: true },
      turns: [
        ['a', "I know you're coupled up. I'm not going to pretend I don't know."],
        ['b', "Then why pick me?"],
        ['a', "Because I don't think it's working. And I think you know that too."],
      ] },
    { id: 'date.04',
      stage: 'The date is on a boat, and neither of them has ever been on one.',
      turns: [
        ['b', "I think I'm going to be sick."],
        ['a', "Great first date, then."],
      ],
      beat: 'They laugh the whole way back to shore.' },
    { id: 'date.05',
      turns: [
        ['a', "What's your type? Honestly."],
        ['b', 'Kind. Funny. Someone who asks questions and listens to the answer.'],
        ['a', "I'm asking questions."],
        ['b', "You're doing alright so far."],
      ] },
    { id: 'date.06', when: { persona: 'game-player' },
      turns: [
        ['a', "Everyone at home loves you, you know. You're the one people talk about."],
        ['b', 'Is that why you picked me?'],
        ['a', "It's one reason."],
      ],
      beat: '{b} laughs, and doesn\'t ask what the others are.' },
  ],
  steal: [
    { id: 'steal.01',
      stage: 'At the fire pit, {a} has to choose who to couple up with.',
      turns: [
        ['a', "I'm really sorry to do this. But I came in here for {b}, and I'd be lying if I picked anyone else."],
      ],
      beat: "{c} stares at the ground. {b} doesn't look at {c}." },
    { id: 'steal.02',
      stage: 'At the fire pit.',
      turns: [
        ['a', "I've only been here a day. But from the moment I walked in, it's been {b}."],
      ],
      beat: '{b} gets up and walks over. {c} is left sitting alone on the bench.' },
    { id: 'steal.03', when: { persona: 'game-player' },
      stage: 'At the fire pit.',
      turns: [
        ['a', "I know this is going to cause drama. I've made my peace with that. {b}."],
      ],
      beat: '{c} laughs once, with no humour in it, and looks away.' },
    { id: 'steal.04',
      stage: 'At the fire pit.',
      turns: [
        ['a', "I don't want to ruin anyone's couple. But I have to follow my gut, and my gut says {b}."],
        ['c', "…Right."],
      ],
      beat: '{b} squeezes {c.posAdj} arm on the way past.' },
  ],
  'recouple-pick': [
    // connection
    { id: 'recouple-pick.01', when: { reason: 'connection' },
      turns: [
        ['a', "The person I want to couple up with makes me feel like myself. We can talk about anything, and I've never had to pretend."],
        ['a', "That person is {b}."],
      ],
      beat: '{b} gets up and walks straight into {a.posAdj} arms.' },
    { id: 'recouple-pick.02', when: { reason: 'connection' },
      turns: [
        ['a', "This person has been there for me on my best days and my worst ones in here. I don't need to think about it. {b}."],
      ] },
    { id: 'recouple-pick.03', when: { reason: 'connection', rung: ['exclusive', 'official'] },
      turns: [
        ['a', "I don't need to say much, because everyone knows. {b}, it's always been you."],
      ],
      beat: 'The villa cheers before {a} has finished the sentence.' },
    // attraction
    { id: 'recouple-pick.04', when: { reason: 'attraction' },
      turns: [
        ['a', "I'll be honest. The person I'm picking caught my eye the moment I saw them. I want to see where it goes."],
        ['a', "It's {b}."],
      ],
      beat: '{b} laughs, and goes a bit red.' },
    { id: 'recouple-pick.05', when: { reason: 'attraction' },
      turns: [
        ['a', "We haven't had loads of deep chats yet. But there's something there, and I'd be stupid to ignore it. {b}."],
      ] },
    { id: 'recouple-pick.06', when: { reason: 'attraction', early: true },
      turns: [
        ['a', "It's early, and I'm going on a feeling. The feeling is {b}."],
      ] },
    // safety — never a claimed spark
    { id: 'recouple-pick.07', when: { reason: 'safety' },
      turns: [
        ['a', "I'll be honest, we haven't had the spark yet. But you've been nothing but decent to me, and I'd rather build on that than chase something that isn't there."],
        ['a', "{b}."],
      ],
      beat: '{b} nods, and sits down next to {a.obj}.' },
    { id: 'recouple-pick.08', when: { reason: 'safety' },
      turns: [
        ['a', "I trust this person. In here, that counts for a lot. I'm picking {b}."],
      ] },
    { id: 'recouple-pick.09', when: { reason: 'safety', persona: 'game-player' },
      turns: [
        ['a', "This person and I understand each other. We both know what we want out of this. {b}."],
      ],
      beat: '{b} gives {a.obj} a small nod, and nobody else in the villa can read it.' },
    // loyalty — staying put
    { id: 'recouple-pick.10', when: { reason: 'loyalty' },
      turns: [
        ['a', "I don't need to think about this one. I'm staying exactly where I am. {b}."],
      ],
      beat: "{b} is already on {b.posAdj} feet." },
    { id: 'recouple-pick.11', when: { reason: 'loyalty' },
      turns: [
        ['a', "People have tried to turn my head. It hasn't worked. I'm picking {b}, again, and I'll keep picking {b}."],
      ] },
    // a steal: {b} was {c}'s, and chose {a}
    { id: 'recouple-pick.12', when: { stoleFrom: true },
      turns: [
        ['a', "I know this is going to hurt someone. I'm sorry. But I have to be honest about how I feel. {b}."],
      ],
      beat: "{b} looks at {c} first, and then walks over to {a}. {c} doesn't move." },
    { id: 'recouple-pick.13', when: { stoleFrom: true },
      turns: [
        ['a', "The person I'm choosing is already coupled up. I'm choosing them anyway. {b}."],
        ['c', 'Wow.'],
      ],
      beat: 'The fire pit goes completely silent.' },
  ],
  'dump-buildup': [
    { id: 'dump-buildup.01', when: ch('public'),
      turns: [
        ['dior', "Islanders. The public have been voting for their favourite couple."],
        ['dior', "{a}. {b}. You have received the fewest votes."],
      ],
      beat: '{b} takes {a.posAdj} hand, and neither of them looks at anyone else.' },
    { id: 'dump-buildup.02', when: ch('public'),
      turns: [
        ['dior', "The couples with the fewest public votes are at risk of being dumped from the island. The first of those couples…"],
        ['dior', "…is {a} and {b}."],
      ] },
    { id: 'dump-buildup.03', when: ch('villa'),
      turns: [
        ['dior', "{a} and {b}. The public have put you at risk. Now the islanders will decide who stays."],
      ],
      beat: '{a} looks along the bench at the people who are about to vote.' },
    { id: 'dump-buildup.04', when: ch('villa'),
      turns: [
        ['dior', "Good evening, islanders. Tonight, your fate is in each other's hands. {a}, {b}, please stand."],
      ] },
  ],
  'dump-verdict': [
    { id: 'dump-verdict.01', when: ch('public'),
      turns: [['dior', "{a}. I'm sorry. The public have voted, and you have been dumped from the island."]],
      beat: '{a} nods, and doesn\'t cry until the hugs start.' },
    { id: 'dump-verdict.02', when: ch('public'),
      turns: [['dior', "The islander leaving the villa tonight is…"], ['dior', "…{a}."]],
      beat: 'There is a long silence before anyone moves.' },
    { id: 'dump-verdict.03', when: ch('villa'),
      turns: [['dior', "The islanders have decided. {a}, you have been dumped from the island."]],
      beat: '{a} looks along the bench at the people who voted.' },
    { id: 'dump-verdict.04', when: ch('villa'),
      turns: [['dior', "With the most votes from the islanders… {a}. I'm sorry. Please say your goodbyes."]] },
    { id: 'dump-verdict.05', when: ch('recoupling'),
      stage: 'The last text of the night: whoever was not chosen is dumped from the island.',
      turns: [['a', 'That\'s me, then.']],
      beat: 'Nobody knows what to say, so everyone hugs {a.obj} at once.' },
    { id: 'dump-verdict.06', when: ch('recoupling'),
      stage: 'Everyone else is coupled up. {a} is the only one still standing.',
      turns: [['a', "It's fine. It's fine. I knew it might be me."]] },
    { id: 'dump-verdict.07', when: ch('casa'),
      stage: 'After the Casa Amor recoupling, the text arrives: the single islanders are dumped.',
      turns: [['a', "I came back for someone who didn't come back for me."]],
      beat: '{a} picks up the suitcase that was never unpacked.' },
  ],
  'ballot-reveal': [
    { id: 'ballot-reveal.01',
      turns: [['a', "This is so hard. But I'm voting to dump {b}, because I just haven't seen {b.posAdj} couple grow."]],
      beat: "{b} doesn't look at {a.obj}." },
    { id: 'ballot-reveal.02',
      turns: [['a', "I love everyone here. But I'm voting to save the couple I believe in, which means voting against {b}."]] },
    { id: 'ballot-reveal.03', when: { persona: 'game-player' },
      turns: [['a', "I've thought about who's genuine in here. I'm voting to dump {b}."]],
      beat: '{b} laughs once, and shakes {b.posAdj} head.' },
    { id: 'ballot-reveal.04',
      turns: [['a', "I'm sorry, {b}. It's not personal. I just don't think you're here for the right reasons."]],
      beat: "{b} mouths 'it's fine'." },
    { id: 'ballot-reveal.05', when: { loyal: true },
      turns: [['a', "I've got nothing against {b}. I just have to go with the couple that's been there for me. So it's {b}."]] },
    { id: 'ballot-reveal.06',
      turns: [['a', "I didn't want to do this. My vote is for {b} to leave."]],
      beat: 'The rest of the bench goes very still.' },
  ],
  'dump-reaction': [
    { id: 'dump-reaction.01',
      turns: [['a', "No. No, that's not fair."], ['b', "It's okay. It's okay. You stay and win this."]],
      beat: '{a} holds on to {b} and won\'t let go.' },
    { id: 'dump-reaction.02', when: { feels: 'strong' },
      turns: [['a', "I don't want to be in here without you."], ['b', 'You have to. Promise me you will.']] },
    { id: 'dump-reaction.03', when: { feels: 'little' },
      turns: [['a', "I'm really sorry. I'm going to miss you."], ['b', "You'll be fine."]],
      beat: 'The hug is short.' },
    { id: 'dump-reaction.04', when: { attachment: 'avoidant' },
      turns: [['a', "…Go on. Go and pack. I'll help you."]],
      beat: "{a} doesn't cry until {b} has gone." },
    { id: 'dump-reaction.05', when: { rung: ['exclusive', 'official'] },
      turns: [['a', "Wait for me. I'll see you on the outside."], ['b', "I'll be waiting."]],
      beat: 'They kiss, and the whole villa goes quiet.' },
    { id: 'dump-reaction.06',
      turns: [['a', "I can't believe it's you."], ['b', "Neither can I."]] },
  ],
  solidarity: [
    { id: 'solidarity.01',
      turns: [['a', "If you're going, I'm going."], ['b', "Don't. Don't give this up for me."], ['a', "I'm not giving anything up. You're what I came here for."]],
      beat: '{a} goes to pack, and the villa watches in silence.' },
    { id: 'solidarity.02',
      stage: '{a} stands up before the verdict is even finished.',
      turns: [['a', "I'm sorry, everyone. I'm leaving with {b}."], ['dior', "{a}, are you sure?"], ['a', "I've never been more sure."]] },
    { id: 'solidarity.03', when: { rung: 'official' },
      turns: [['a', "We came in as two people. We're leaving as a couple."]],
      beat: '{b} starts crying. Then everyone does.' },
    { id: 'solidarity.04',
      turns: [['a', "I don't want to be here without you. I'm coming with you."]],
      beat: '{b} tries to argue, and gives up halfway through.' },
  ],
  'dump-goodbye': [
    { id: 'dump-goodbye.01', when: { withB: true },
      turns: [['b', "I'm going to miss you so much."], ['a', 'Stay in touch. I mean it.']],
      beat: 'They hug for a long time.' },
    { id: 'dump-goodbye.02', when: { withB: true },
      turns: [['b', 'Win this for me.'], ['a', "It's you that has to win it now."]] },
    { id: 'dump-goodbye.03', when: { withB: true },
      turns: [['b', "This place won't be the same."], ['a', "Look after everyone for me."]] },
    { id: 'dump-goodbye.04', when: { withB: true, gender: 'f', bGender: 'f' },
      turns: [['b', "{~Girl}, I'm going to call you the second you're out."], ['a', "You'd better."]] },
    { id: 'dump-goodbye.05', when: { withB: false },
      stage: 'At the top of the steps, {a} turns round one last time.',
      turns: [['a', "Love you all. Don't do anything I wouldn't do."]],
      beat: 'The villa waves until {a} is out of sight.' },
    { id: 'dump-goodbye.06', when: { withB: false },
      stage: '{a} picks up the suitcase.',
      turns: [['a', "Thank you for everything. Honestly. It's been the best few weeks of my life."]] },
    { id: 'dump-goodbye.07', when: { withB: false, early: true },
      stage: '{a} picks up the suitcase.',
      turns: [['a', "I didn't even get to unpack properly."]],
      beat: 'Everyone laughs, and it helps a little.' },
  ],
  'dump-fallout': [
    { id: 'dump-fallout.01',
      stage: "Back at the villa, {a} is sitting on the empty side of the bed.",
      turns: [['a', "What do I do now?"]] },
    { id: 'dump-fallout.02',
      stage: 'In the kitchen, the next morning.',
      turns: [['a', "I'm single in the villa. Great. That's great."]] },
    { id: 'dump-fallout.03', when: { mood: 'heartbroken' },
      stage: '{a} is lying on the daybed with a pillow over {a.posAdj} face.',
      turns: [['a', "Don't. I know. I just need a minute."]] },
    { id: 'dump-fallout.04', when: { persona: 'game-player' },
      stage: '{a} is already looking around the garden.',
      turns: [['a', "Right. I'm single. So everyone's back on the table."]] },
  ],
  'casa-return': [
    { id: 'casa-return.01', when: { choice: 'stick', withB: true },
      stage: 'The Casa Amor recoupling. {b} is waiting at the fire pit.',
      turns: [['a', 'I came back on my own.'], ['b', '…You came back on your own.']],
      beat: '{b} runs to {a.obj}, and they nearly knock each other over.' },
    { id: 'casa-return.02', when: { choice: 'stick', withB: true },
      turns: [['b', "I didn't know if you'd come back for me."], ['a', "There was never any doubt. Not once."]] },
    { id: 'casa-return.03', when: { choice: 'stick', withB: true, mood: 'guilty' },
      turns: [['a', "I came back on my own."], ['b', "I know. Thank you."]],
      beat: "{a} holds {b} tight, and doesn't meet anyone else's eye." },
    { id: 'casa-return.04', when: { choice: 'twist', taken: true },
      stage: '{a} walks in holding hands with {b}. {pa} is waiting at the fire pit.',
      turns: [['a', "I'm sorry. I had to follow my heart."]],
      beat: '{pa} gets up and walks straight into the villa without a word.' },
    { id: 'casa-return.05', when: { choice: 'twist', taken: true },
      stage: '{a} walks in with {b}.',
      turns: [['a', "I didn't go in there looking for this. It just happened."]],
      beat: '{pa} laughs, and then starts crying.' },
    { id: 'casa-return.06', when: { choice: 'twist', taken: true, persona: 'fuckboy' },
      stage: '{a} walks in with {b}, and doesn\'t let go of {b.posAdj} hand.',
      turns: [['a', "Look, I'm not going to lie. I had a great time at Casa."]],
      beat: 'Nobody at the fire pit says anything.' },
    { id: 'casa-return.08', when: { choice: 'stick', withB: false },
      stage: '{a} walks back into the villa on {a.posAdj} own.',
      turns: [['a', "Nobody at Casa was for me. I'd rather come back single than pretend."]] },
    { id: 'casa-return.09', when: { choice: 'stick', withB: false },
      stage: 'The last of the Casa islanders comes back through the door. {a} is alone.',
      turns: [['a', "I'm back. On my own. I'm fine with that."]] },
    { id: 'casa-return.07', when: { choice: 'twist', taken: false },
      stage: '{a} walks back in with {b}.',
      turns: [['a', "I was single when I left, and I'm not single now."]],
      beat: 'The villa cheers for them.' },
  ],
  photos: [
    { id: 'photos.01',
      stage: 'At the fire pit, the photos from Casa Amor are handed round. {a} is holding one of {b}.',
      turns: [['a', "I'm going to be sick."], ['b', "It's not what it looks like."], ['a', "It's exactly what it looks like."]] },
    { id: 'photos.02',
      stage: 'A photo of {b}, on a daybed at Casa, much too close to somebody.',
      turns: [['a', 'You told me nothing happened.'], ['b', 'Nothing did happen. Not really.'], ['a', '"Not really."']],
      beat: '{a} puts the photo face down on the bench.' },
    { id: 'photos.03', when: { archetype: 'hothead' },
      stage: '{a} stares at the photo of {b}.',
      turns: [['a', "Are you serious? Are you actually serious?"]],
      beat: 'Two people have to get between them.' },
    { id: 'photos.04', when: { attachment: 'anxious' },
      stage: '{a} looks at the photo of {b} for a long time.',
      turns: [['a', "I trusted you. I sat here every night and trusted you."]],
      beat: "{a} can't finish the sentence." },
    { id: 'photos.05', when: { attachment: 'avoidant' },
      stage: '{a} glances at the photo of {b}, and hands it straight back.',
      turns: [['a', "Right. Okay. Good to know."]],
      beat: '{b} tries to talk to {a.obj} later. {a} is already asleep, or pretending to be.' },
  ],
  'heart-rate': [
    { id: 'heart-rate.01', when: { coupled: true },
      stage: "The heart-rate challenge. {a}'s monitor goes wild for one person: {b}.",
      turns: [['b', 'Obviously.'], ['a', "Don't look so smug about it."]] },
    { id: 'heart-rate.02', when: { coupled: true },
      stage: "{a}'s heart rate jumps the moment {b} starts dancing.",
      turns: [['a', "I can't help it. I'm not even embarrassed."]] },
    { id: 'heart-rate.03', when: { coupled: false, taken: true },
      stage: "{a}'s heart rate spikes for {b}, not for {pa}.",
      turns: [['a', "That doesn't mean anything. It's a machine."]],
      beat: '{pa} looks at the screen, and then at {a}.' },
    { id: 'heart-rate.04', when: { coupled: false, taken: true },
      stage: "The biggest spike of {a}'s whole afternoon is for {b}. {pa} is sitting right there.",
      turns: [['a', "…It was the dancing. It was very good dancing."]],
      beat: "{pa} doesn't laugh." },
    { id: 'heart-rate.05', when: { coupled: false, taken: false },
      stage: "{a}'s heart goes for {b}, and the whole villa turns to look.",
      turns: [['a', "Oh no. Well. Now everyone knows."]] },
    { id: 'heart-rate.06', when: { coupled: false, taken: false, persona: 'wallflower' },
      stage: "{a}'s monitor jumps for {b}, and {a} goes bright red.",
      turns: [['a', "Can we move on? Please?"]] },
  ],
  'snog-marry-pie': [
    { id: 'snog-marry-pie.01', when: { full: true },
      stage: '{a} stands up with the three cards.',
      turns: [['a', "Snog, {b}. Marry, {c}, obviously. Pie…"], ['a', 'Sorry, {d}.']],
      beat: '{d} takes a face full of cream, and takes it well.' },
    { id: 'snog-marry-pie.02', when: { full: true },
      turns: [['a', "I'd marry {c}. I'd snog {b}, just once, to see. And the pie is for {d}, who knows why."]],
      beat: '{d} asks why, through a face full of cream.' },
    { id: 'snog-marry-pie.03', when: { full: true, taken: true },
      turns: [['a', "Marry, {c}. Snog… {b}."], ['a', "And {d}, I'm really sorry."]],
      beat: '{pa} goes very quiet when the snog is called.' },
    { id: 'snog-marry-pie.04', when: { full: true, persona: 'messy' },
      turns: [['a', "Snog, {b}. Marry, {c}. And pie, {d}, because {d} knows exactly what {d} did."]],
      beat: 'The whole villa goes "ooooh".' },
    { id: 'snog-marry-pie.05',
      turns: [['a', "I'm not playing this properly. I'm just going to pie someone."]],
      beat: 'The cream goes everywhere.' },
  ],
  'movie-night': [
    { id: 'movie-night.01', when: { hasQuote: true },
      stage: 'Movie Night. The screen shows {quoteWho}, earlier in the week, saying: "{quote}"',
      turns: [['a', "Oh no. Oh, no."]],
      beat: 'The whole villa turns to look.' },
    { id: 'movie-night.02', when: { taken: true, hasQuote: true },
      stage: 'Movie Night. A clip of {a} plays. {quoteWho}: "{quote}" {pa} is sitting right next to {a.obj}.',
      turns: [['a', "I can explain."]],
      beat: '{pa} moves to the other end of the sofa.' },
    { id: 'movie-night.03', when: { taken: true },
      stage: 'Movie Night. A clip of {a} from earlier in the week plays, and {pa} is watching every second of it.',
      turns: [['a', "That was out of context. That was so out of context."]],
      beat: '{pa} gets up and goes to get a drink, and doesn\'t come back.' },
    { id: 'movie-night.04', when: { hasQuote: true },
      stage: 'Movie Night. The next clip is from a chat nobody else saw. {quoteWho}: "{quote}"',
      turns: [['a', "…Can we pause it? Can someone pause it?"]],
      beat: 'Nobody pauses it.' },
    { id: 'movie-night.05', when: { taken: true, attachment: 'avoidant' },
      stage: 'Movie Night. A clip of {a} plays, from a moment {a} thought nobody would see.',
      turns: [['a', "Yep. I said that."]],
      beat: '{pa} stares at {a}, and {a} keeps looking at the screen.' },
  ],
  notes: [
    { id: 'notes.01', when: { guessed: true },
      stage: 'An anonymous note is read out about {b}: someone in the villa thinks {b} is two-faced.',
      turns: [['b', "I know who wrote that."]],
      beat: '{b} is looking straight at {a}.' },
    { id: 'notes.02', when: { guessed: false },
      stage: 'An anonymous note about {b} is read out to the whole villa.',
      turns: [['b', "Whoever wrote that, you could have just said it to my face."]],
      beat: '{a} keeps a straight face, and says nothing.' },
    { id: 'notes.03', when: { guessed: false },
      stage: "The note says {b} is only here for the followers.",
      turns: [['b', "Wow. Okay. That's nice."]],
      beat: '{b} guesses the wrong person. {a} says nothing.' },
    { id: 'notes.04', when: { guessed: true, archetype: 'hothead' },
      stage: 'A note about {b} is read out.',
      turns: [['b', "{a}. That was you. I know it was you."], ['a', "I don't know what you're talking about."]],
      beat: "{a} doesn't meet {b.posAdj} eye." },
  ],
  families: [
    { id: 'families.01', when: { verdict: 'good' },
      stage: "A video from {a}'s family plays on the screen.",
      turns: [['a', "They love you. They actually love you."], ['b', 'Stop. They said that?']],
      beat: '{b} cries harder than {a} does.' },
    { id: 'families.02', when: { verdict: 'good' },
      stage: "{a}'s family have come to the villa. After an hour with {b}, they're all laughing together.",
      turns: [['a', "I've never brought anyone home before. I think this counts."]] },
    { id: 'families.03', when: { verdict: 'bad' },
      stage: "{a}'s family are polite to {b}. Very polite.",
      turns: [['a', "They're just protective. They'll come round."], ['b', "Will they?"]] },
    { id: 'families.04', when: { verdict: 'bad' },
      stage: "{a}'s family take {a} aside on the terrace, away from {b}.",
      turns: [['a', "They're not sure about you. They've watched everything."]],
      beat: '{b} nods, and looks down at the floor.' },
    { id: 'families.05', when: { verdict: 'unsure' },
      stage: "{a}'s family meet {b} for the first time.",
      turns: [['a', "They're still making their minds up. That's normal. Right?"], ['b', "I hope so."]] },
    { id: 'families.06', when: { verdict: 'unsure' },
      stage: "After the visit, {a} and {b} sit on the daybed together.",
      turns: [['b', "How did I do?"], ['a', "Honestly? I can't tell. They were really hard to read."]] },
  ],
  declaration: [
    { id: 'declaration.01',
      stage: 'The final. {a} stands at the fire pit and turns to {b}.',
      turns: [['a', "When I came in here, I didn't think I'd find anything real. Then I met you, and everything changed."]],
      beat: '{b} is already crying.' },
    { id: 'declaration.02',
      stage: 'The final. {a} unfolds a piece of paper, and then puts it away.',
      turns: [['a', "I wrote a speech. I'm not going to read it. I'm just going to say that I love you."]] },
    { id: 'declaration.03', when: { rung: 'official' },
      stage: 'The final.',
      turns: [['a', "You're my {b.gf}. You're my best friend. Whatever the public says tonight, I've already won."]],
      beat: 'The villa, watching from the benches, loses it.' },
    { id: 'declaration.04', when: { persona: 'villa-clown' },
      stage: 'The final.',
      turns: [['a', "I promised myself I wouldn't cry. I'm crying. {b}, you did this to me."]],
      beat: '{b} laughs, through tears.' },
    { id: 'declaration.05', when: { attachment: 'avoidant' },
      stage: 'The final.',
      turns: [['a', "I'm not good at this. I don't say things. So I'll say this once. I love you."]],
      beat: '{b} gets up and kisses {a.obj} before the speech is even finished.' },
    { id: 'declaration.06', when: { feels: 'little' },
      stage: 'The final.',
      turns: [['a', "We've been through so much in here. You've been an amazing partner, and I'll always be grateful."]],
      beat: '{b} smiles, and squeezes {a.posAdj} hand.' },
  ],
  walk: [
    { id: 'walk.01', when: { cause: 'heartbreak' },
      stage: '{a} asks to speak to everyone at the fire pit.',
      turns: [['a', "I can't stay here and watch it every day. I'm going home."]],
      beat: 'Nobody tries to talk {a.obj} out of it.' },
    { id: 'walk.02', when: { cause: 'homesick' },
      stage: '{a} gathers everyone in the kitchen.',
      turns: [['a', "I miss home. I miss my family. I've given it everything, and I've got nothing left."]] },
    { id: 'walk.03', when: { cause: 'homesick' },
      stage: '{a} has packed in the night.',
      turns: [['a', "I love you all. But I'm not happy, and I don't want to pretend for the cameras."]] },
    { id: 'walk.04', when: { cause: 'solidarity', withB: true },
      stage: '{b} is leaving, and {a} stands up.',
      turns: [['a', "I'm going with {b}. There's nothing for me here without {b.obj}."]],
      beat: 'The villa watches the two of them walk up the steps together.' },
    { id: 'walk.05', when: { cause: 'solidarity', withB: false },
      stage: '{a} has decided to leave with {a.posAdj} partner.',
      turns: [['a', "I came in for love. I'm leaving with it."]] },
    { id: 'walk.06', when: { cause: 'heartbreak', mood: 'heartbroken' },
      stage: 'The next morning, {a} is sitting on a packed suitcase by the door.',
      turns: [['a', "I'm not being dramatic. I just can't do it any more."]] },
  ],
  reveal: [
    { id: 'reveal.01', when: { hasQuote: true },
      stage: 'The reunion. The host introduces a clip the viewers never saw.',
      turns: [['dior', "Let's take a look at a moment that didn't make it to air."], ['dior', "Here's {quoteWho}: \"{quote}\""]],
      beat: 'The studio gasps.' },
    { id: 'reveal.02',
      turns: [['dior', "{a}, we have to talk about this one."], ['a', "I knew you were going to show that."]],
      beat: 'The audience gasps anyway.' },
    { id: 'reveal.03', when: { hasQuote: true },
      stage: 'The reunion. The clip plays. {quoteWho}: "{quote}"',
      turns: [['dior', "{a}. Would you like to explain?"], ['a', "Honestly? No."]],
      beat: 'The studio laughs, and {a} does too, eventually.' },
    { id: 'reveal.04', when: { withB: true },
      stage: 'The reunion. A clip nobody saw plays, and {b} is in it too.',
      turns: [['dior', "{b}, you look very surprised."], ['b', "I'm surprised they filmed it."]] },
  ],
};
