// argument — more of them. Cast: [a, b]: a starts it (a's temper is the
// short one). b is a's partner most of the time (`coupled`), otherwise the
// islander a gets on with least. A row over nothing is still a row.
export const ARGUMENT_MORE = [
  { id: 'argument.06', when: { coupled: true },
    turns: [
      ['a', "You didn't save me a seat."],
      ['b', 'There are seats everywhere.'],
      ['a', "That's not the point. You always save me a seat."],
      { by: 'b', vary: [
        { turns: [['b', "It's a seat. I'm not doing this over a seat."]], beat: '{a} sits somewhere else.' },
        { when: { attachment: 'anxious' },
          turns: [['b', "…I'm sorry. I didn't think. Sit here."]], beat: '{b} moves up, and {a} sits down, still annoyed.' },
      ] },
    ] },
  { id: 'argument.07', when: { coupled: true },
    turns: [
      ['a', 'Why were you laughing with them like that?'],
      ['b', 'Like what?'],
      ['a', 'Like you laugh with me.'],
      { by: 'b', vary: [
        { turns: [['b', "Because they said something funny. That's what laughing is."]],
          beat: '{a} goes inside and slams the door, and it swings back open.' },
        { when: { archetype: 'hothead' },
          turns: [['b', "{~Oh-my-days}. I'm not allowed to laugh now?"]], beat: 'They are both shouting by the end of it.' },
        { when: { attachment: 'secure' },
          turns: [['b', "Come here. Nobody makes me laugh like you do. You know that."]], beat: '{a} lets {b} pull {a.obj} in for a hug.' },
      ] },
    ] },
  { id: 'argument.08', when: { coupled: false },
    turns: [
      ['a', "Can you not talk over me every time I open my mouth?"],
      ['b', "I wasn't talking over you."],
      ['a', 'You just did it again.'],
    ],
    beat: 'Nobody else at the table says a word.' },
  { id: 'argument.09', when: { coupled: false },
    turns: [
      ['a', "Someone told me what you've been saying about me."],
      ['b', 'What have I been saying?'],
      ['a', "You tell me."],
      { by: 'b', vary: [
        { turns: [['b', "I really don't. So either tell me or drop it."]], beat: '{a} walks off without telling {b.obj}.' },
        { when: { archetype: ['villain', 'mastermind', 'schemer'] },
          turns: [['b', "Well, if you heard it, it must be true."]], beat: '{a} has to be walked away by two other islanders.' },
      ] },
    ] },
  { id: 'argument.10', when: { coupled: true, mood: 'jealous' },
    turns: [
      ['a', "You've been with them all afternoon."],
      ['b', "We were on the same sunbeds. There are four sunbeds."],
      ['a', "And you picked that one."],
      ['b', "Because it was in the shade!"],
    ],
    beat: '{a} goes and sits in the sun on {a.posAdj} own.' },
  { id: 'argument.11',
    turns: [
      ['a', "Why is it always me who has to apologise?"],
      ['b', "Because it's always you who starts it."],
      ['a', "That's not true."],
      ['b', "Then name one time."],
    ],
    beat: '{a} opens {a.posAdj} mouth, and closes it again.' },
  { id: 'argument.12', when: { coupled: true, gap: true },
    turns: [
      ['a', "I don't even know what we are."],
      ['b', 'Why does it matter?'],
      ['a', "Because I'm acting like we're something, and you're acting like we're not."],
      { by: 'b', vary: [
        { turns: [['b', "We're something. Just not the thing you want yet."]], beat: '{a} goes quiet.' },
        { when: { attachment: 'avoidant' },
          turns: [['b', "Can we not do this with everyone listening?"]], beat: '{b} gets up. {a} watches {b.obj} go.' },
      ] },
    ] },
  { id: 'argument.13', when: { persona: 'messy' },
    turns: [
      ['a', "Say it to my face. Go on. Say it to my face."],
      ['b', "I haven't said anything!"],
      ['a', "You've been saying it with your face all day."],
    ],
    beat: 'Somebody takes {a} by the arm and walks {a.obj} to the other end of the garden.' },
  { id: 'argument.14', when: { coupled: true },
    turns: [
      ['b', 'Why are you being like this?'],
      ['a', "Being like what?"],
      ['b', "Short with me. All day. I haven't done anything."],
      { by: 'a', vary: [
        { turns: [['a', "I don't know. I'm just in a mood."], ['b', "Then say that, instead of taking it out on me."]] },
        { when: { mood: 'guilty' },
          turns: [['a', "…I'm not. I'm fine. Leave it."]], beat: '{b} leaves it.' },
        { when: { attachment: 'avoidant' },
          turns: [['a', 'I need some space.'], ['b', "We're in a villa. Where are you going to get space?"], ['a', 'Watch me.']],
          beat: '{a} goes and lies on the roof terrace for the rest of the afternoon.' },
      ] },
    ] },
  { id: 'argument.15',
    stage: 'It starts over the last of the hair straighteners.',
    turns: [
      ['a', "I put them down for ten seconds."],
      ['b', 'You put them down and walked off.'],
      ['a', 'To get a drink! I was coming back!'],
      ['b', "How was I meant to know that?"],
    ],
    beat: 'It goes on until somebody tells them both to stop.' },
  { id: 'argument.16', when: { coupled: true, rung: ['exclusive', 'official'] },
    turns: [
      ['a', "We're meant to be exclusive, and you're still flirting with everyone."],
      ['b', "I'm not flirting. I'm being friendly."],
      ['a', "There's a difference, and you know what it is."],
      { by: 'b', vary: [
        { turns: [['b', '…Okay. I hear you.']], beat: '{b} sits with {a} for the rest of the night.' },
        { when: { persona: 'fuckboy' },
          turns: [['b', "I'm just like this. You knew that when you said yes."]], beat: '{a} gets up and goes to bed.' },
      ] },
    ] },
  { id: 'argument.17', when: { mood: 'stressed' },
    turns: [
      ['a', "Can everyone please just stop asking me if I'm okay?"],
      ['b', 'I only asked once.'],
      ['a', "You were the eighth person!"],
    ],
    beat: '{b} holds {b.posAdj} hands up and backs off. Nobody asks {a} again that day.' },
  { id: 'argument.18', when: { coupled: false },
    turns: [
      ['a', "Why do you keep getting involved in my couple?"],
      ['b', "I'm not involved. I just said what everyone's thinking."],
      ['a', "Then let everyone say it. You're not everyone."],
    ] },
  { id: 'argument.19', when: { coupled: true },
    turns: [
      ['b', "Can you at least look at me when I'm talking to you?"],
      ['a', "I am looking at you."],
      ['b', "You're looking at the pool."],
    ],
    beat: '{a} looks at {b}, finally.' },
  { id: 'argument.20',
    stage: 'It starts over a spoon left in the sink.',
    turns: [
      ['a', "You always do this. You make a joke when I'm being serious."],
      { by: 'b', vary: [
        { turns: [['b', "Because you're being serious about a spoon."], ['a', "It's not about the spoon."]],
          beat: '{a} puts the spoon down and walks off.' },
        { when: { persona: 'villa-clown' },
          turns: [['b', "I'm sorry. I'm sorry. I'll be serious."], ['a', 'Thank you.'], ['b', "…I am sorry, though."]],
          beat: '{a} throws the spoon at {b.obj}, and misses.' },
      ] },
    ] },
  { id: 'argument.21', when: { coupled: true, late: true },
    turns: [
      ['a', "I keep telling you, and you still don't get it."],
      ['b', 'Get what?'],
      ['a', 'That when I go quiet, I want you to come and find me. Not leave me to it.'],
      ['b', "Then tell me! I can't read your mind!"],
    ],
    beat: 'They sit on opposite ends of the daybed, and neither of them moves first.' },
  { id: 'argument.22', when: { persona: 'game-player' },
    turns: [
      ['a', "Everyone thinks you're lovely. I know what you're really like."],
      ['b', "And what am I really like?"],
      ['a', "Two-faced."],
    ],
    beat: '{b} laughs in {a.posAdj} face and walks off.' },
  { id: 'argument.23', when: { coupled: true },
    turns: [
      ['a', "I can't do anything right, can I?"],
      ['b', "That's not what I said."],
      ['a', "It's what you meant."],
      ['b', "Don't tell me what I meant."],
    ] },
  { id: 'argument.24',
    stage: 'The kitchen, after dinner. Nobody has done the washing up.',
    turns: [
      ['a', "I did it yesterday. And the day before."],
      ['b', "And I did it the day before that."],
      ['a', "Once! You did it once!"],
    ],
    beat: 'Nobody does the washing up.' },
  { id: 'argument.25', when: { coupled: true, attachment: 'anxious' },
    turns: [
      ['a', "Where were you? I looked everywhere."],
      ['b', 'In the gym. For half an hour.'],
      ['a', 'You could have said.'],
      ['b', "I don't need to tell you every time I go to the gym."],
    ],
    beat: "{a} doesn't say anything else, and doesn't let go of {b.posAdj} hand for the rest of the evening either." },
  { id: 'argument.26', when: { coupled: false, archetype: 'hothead' },
    turns: [
      ['a', "Do you want to say that again?"],
      ['b', "I don't need to. You heard me."],
    ],
    beat: 'Two of the others step in between them before it goes any further.' },
  { id: 'argument.27',
    turns: [
      ['a', "Stop telling me to calm down."],
      ['b', "Then calm down and I'll stop."],
    ],
    beat: '{a} slams the fridge door, and the whole kitchen jumps.' },
  { id: 'argument.28', when: { coupled: true, mood: 'jealous' },
    turns: [
      ['a', "I heard you told everyone you weren't sure about me."],
      { by: 'b', vary: [
        { turns: [['b', "I said I wasn't sure about some things. That's normal."], ['a', 'Not to me it isn\'t.']] },
        { when: { mood: 'guilty' },
          turns: [['b', "…Who told you that?"], ['a', "So you did say it."]], beat: "{b} doesn't deny it." },
      ] },
    ] },
  { id: 'argument.29', when: { coupled: true },
    turns: [
      ['b', "You're not even listening."],
      ['a', "I'm listening. I just don't agree."],
      ['b', "Then say you don't agree! Don't just sit there nodding."],
    ] },
  { id: 'argument.30', when: { phase: 'evening', rowedBefore: true },
    turns: [
      ['a', "I'm not having this argument again."],
      ['b', "Then don't start it again."],
      ['a', "I didn't start it!"],
      ['b', 'You started it last time.'],
      ['a', "That doesn't count!"],
    ],
    beat: 'They are still going when the lights go off.' },
];
