// ick, challenge-kiss, challenge-win.
//
// ick — Cast: [a, b], coupled: a goes off b. The engine does not record WHICH
// ick, so a line names a small habit and never one of the profile's icks.
// challenge-kiss — Cast: [a, b]: a kisses b, who is not a's partner, for the
// points. a's partner is watching somewhere and is never named.
// challenge-win — Cast: [a, b], coupled together, and they won.
export const ICK = [
  { id: 'ick.01',
    stage: '{b} laughs at {b.posAdj} own joke, again.',
    turns: [['a', "…Yeah. That's funny."]],
    beat: "{a} doesn't laugh." },
  { id: 'ick.02',
    turns: [
      ['b', "Babe, can you pass me the—"],
      ['a', "Please don't call me babe while you're chewing."],
      ['b', "What?"],
      ['a', 'Nothing. Here.'],
    ] },
  { id: 'ick.03',
    stage: '{b} is doing a little dance while brushing {b.posAdj} teeth.',
    turns: [['a', 'Do you do that every morning?'], ['b', 'Do what?']],
    beat: '{a} watches, and stops smiling.' },
  { id: 'ick.04',
    turns: [
      ['b', "Honestly, I think I'd win a fight against most of {~lads} in here."],
      ['a', 'Why would you ever need to know that?'],
    ],
    beat: '{a} moves along the sofa, a few inches.' },
  { id: 'ick.05',
    turns: [
      ['b', 'Watch this.'],
      ['a', "Please don't."],
    ],
    beat: '{b} tries to jump into the pool with a flip, and lands flat on {b.posAdj} back. {a} winces and looks away.' },
  { id: 'ick.06',
    turns: [
      ['a', 'Did you just clap when the food arrived?'],
      ['b', "I was excited."],
      ['a', 'Right.'],
    ] },
  { id: 'ick.07',
    stage: 'Later, in the dressing room, to nobody in particular.',
    turns: [['a', "I can't explain it. {b} ran across the lawn earlier, and I just thought, no."]] },
  { id: 'ick.08',
    turns: [
      ['b', 'Guess what my nickname was at school.'],
      ['a', "I don't want to guess."],
      ['b', 'Guess!'],
    ],
    beat: "{a} doesn't guess." },
  { id: 'ick.09',
    turns: [
      ['b', "I'm just a really loyal person, you know? Like, the most loyal person you'll ever meet."],
      ['a', "You've said that four times today."],
    ] },
  { id: 'ick.10', when: { persona: 'checklist' },
    turns: [
      ['a', "Do you always tell everyone what they're doing wrong?"],
      ['b', "I'm just trying to help."],
      ['a', 'Right.'],
    ],
    beat: '{a} goes quiet for the rest of the meal.' },
  { id: 'ick.11',
    stage: '{b} is baby-talking to a flamingo pool float.',
    turns: [['a', '…Are you okay?']] },
  { id: 'ick.12',
    turns: [
      ['b', 'I wrote you a poem.'],
      ['a', 'Oh. Great. Are you going to read it?'],
      ['b', "I'm going to sing it."],
    ],
    beat: '{a} smiles through the whole thing and looks at the floor after.' },
  { id: 'ick.13', when: { attachment: 'avoidant' },
    turns: [
      ['b', 'I missed you. You were gone for ages.'],
      ['a', 'I was at the gym for twenty minutes.'],
      ['b', 'It felt like ages.'],
    ],
    beat: '{a} goes back to the gym.' },
  { id: 'ick.14',
    turns: [
      ['b', "I don't really do feelings. I'm more of an action person, you know what I mean?"],
      ['a', "I don't, actually."],
    ] },
  { id: 'ick.15',
    stage: '{b} blows on {a.posAdj} food for {a.obj} without asking.',
    turns: [['a', "I can do that myself."], ['b', "It's hot!"], ['a', 'I know.']] },
  { id: 'ick.16',
    turns: [
      ['b', 'Wait, who even is the prime minister?'],
      ['a', "You're joking."],
      ['b', "I'm not!"],
    ],
    beat: '{a} stares at {b.obj} for a long moment.' },
];

export const CHALLENGE_KISS = [
  { id: 'challenge-kiss.01',
    stage: 'The challenge: pick the islander you most want to kiss.',
    turns: [['a', "Sorry. It's a game. It's just a game."]],
    beat: "{a} kisses {b}, and from the podium somebody's partner goes very still." },
  { id: 'challenge-kiss.02',
    turns: [
      ['a', "I'm going for points."],
      { by: 'b', vary: [
        { turns: [['b', "Go on, then."]], beat: "{a} kisses {b}, and it goes on longer than anybody needed it to." },
        { when: { taken: true, loyal: true },
          turns: [['b', 'Quick one. Cheek. I mean it.']], beat: '{a} goes for the cheek.' },
        { when: { persona: 'fuckboy' },
          turns: [['b', "About time."]], beat: '{b} kisses {a.obj} first, and the villa screams.' },
      ] },
    ] },
  { id: 'challenge-kiss.03', when: { taken: true },
    stage: "{a} looks at {a.posAdj} partner, then walks straight past.",
    turns: [['a', "It's for the challenge."]],
    beat: '{a} kisses {b}, and does not look back.' },
  { id: 'challenge-kiss.04',
    turns: [['b', 'Me? Seriously?'], ['a', "Seriously."]],
    beat: 'The kiss gets the loudest scream of the day.' },
  { id: 'challenge-kiss.05', when: { bombshell: true },
    turns: [['a', "I'm new. I don't know the rules."], ['b', "There aren't any."]],
    beat: 'Half the villa is on its feet.' },
  { id: 'challenge-kiss.06', when: { gap: true },
    turns: [['a', "Don't read into it."], ['b', "I'm not."]],
    beat: 'Neither of them looks at the other for the rest of the challenge.' },
  { id: 'challenge-kiss.07',
    stage: 'The card says: kiss the islander who has the best chat.',
    turns: [['a', "Easy."]],
    beat: '{a} walks up to {b} without breaking stride.' },
  { id: 'challenge-kiss.08', when: { persona: 'game-player' },
    turns: [['a', 'Might as well make it count.']],
    beat: '{a} takes {b.posAdj} face in both hands, for the cameras as much as anyone.' },
  { id: 'challenge-kiss.09',
    turns: [['b', 'Everyone is watching.'], ['a', "That's sort of the point."]] },
  { id: 'challenge-kiss.10', when: { taken: true, loyal: true },
    stage: '{a} hesitates at the front of the stage.',
    turns: [['a', "I'm only doing this because it's the challenge. My partner knows that."]],
    beat: "It's a peck, and {a} is back in {a.posAdj} place before anyone can cheer." },
  { id: 'challenge-kiss.11',
    stage: 'The card says: kiss the islander you would like to get to know better.',
    turns: [['a', '…Right, then.']],
    beat: '{a} crosses the stage to {b}, and the whole row holds its breath.' },
  { id: 'challenge-kiss.12', when: { persona: 'villa-clown' },
    turns: [['a', "I'm going to do a really dramatic one. Stand still."], ['b', "Oh no."]],
    beat: '{a} dips {b} like an old film. The villa is in bits.' },
  { id: 'challenge-kiss.13', when: { persona: 'wallflower' },
    turns: [['a', 'Is that… Is that okay?'], ['b', "Yeah, it's okay."]],
    beat: "It's the shyest kiss of the day." },
  { id: 'challenge-kiss.14',
    turns: [['a', "Don't get any ideas."], ['b', 'Too late.']] },
  { id: 'challenge-kiss.15',
    stage: 'Covered in foam, halfway down the slide.',
    turns: [['a', 'Quick, before the whistle.']],
    beat: '{a} kisses {b} with a mouthful of foam, and they both come up spitting.' },
  { id: 'challenge-kiss.16', when: { late: true },
    turns: [['a', "I've been wanting to know what that'd be like for weeks."], ['b', "And?"], ['a', "Ask me later."]] },
];

export const CHALLENGE_WIN = [
  { id: 'challenge-win.01',
    turns: [['a', 'We won! We actually won!'], ['b', 'Of course we won.']],
    beat: '{b} picks {a} up and spins {a.obj} round.' },
  { id: 'challenge-win.02',
    stage: 'The text says the winners get a night in the hideaway.',
    turns: [['a', 'Is that us?'], ['b', "That's us."]],
    beat: 'The whole villa whoops, and {a} goes red.' },
  { id: 'challenge-win.03',
    turns: [['b', "Told you we'd make a good team."], ['a', 'You fell over three times.'], ['b', 'And we still won.']] },
  { id: 'challenge-win.04', when: { rung: ['exclusive', 'official'] },
    turns: [['a', 'Is it bad that I care this much about a game?'], ['b', "No. It's us. I'd care too."]] },
  { id: 'challenge-win.05',
    turns: [['a', "That's the first thing we've ever won together."], ['b', "It won't be the last."]] },
  { id: 'challenge-win.06', when: { early: true },
    turns: [['b', "Well, that's one way to find out we work."], ['a', 'Are you saying we work?'], ['b', 'On a slide, at least.']] },
  { id: 'challenge-win.07', when: { persona: 'villa-clown' },
    stage: '{a} climbs up onto the podium.',
    turns: [['a', "I'd like to thank my partner, my legs, and the foam."]],
    beat: '{b} pulls {a} down, laughing.' },
  { id: 'challenge-win.08',
    turns: [['a', "You didn't let go once."], ['b', "I wasn't going to."]],
    beat: "{a} doesn't let go now, either." },
  { id: 'challenge-win.09', when: { persona: 'checklist' },
    turns: [['a', 'I had a strategy, you know.'], ['b', 'You had a strategy for a foam slide?'], ['a', 'And it worked.']] },
  { id: 'challenge-win.10',
    stage: 'Everyone else is soaked and losing.',
    turns: [['b', 'Look at them.'], ['a', "Don't gloat."], ['b', "I'm not gloating. I'm just happy."]] },
  { id: 'challenge-win.11', when: { gap: true },
    turns: [['a', 'We make a good team.'], ['b', 'In the challenges, yeah.']],
    beat: "{a} lets the 'in the challenges' go." },
  { id: 'challenge-win.12',
    turns: [['a', 'Did you see their faces?'], ['b', "I did. I'll be nice about it tomorrow."]] },
];
