// chat — a couple talking, nothing at stake. Cast: [a, b], coupled together.
// Never invent a backstory fact (a job, a sibling, a hometown): the cast
// setup owns those. The villa, the day and each other are fair game.
// Plain talk: people answer the question they were asked. A beat says what
// they do next, not a punchline.
export const CHAT = [
  { id: 'chat.01', when: { early: true },
    turns: [
      ['a', 'What did you actually think of me when I walked in?'],
      { by: 'b', vary: [
        { turns: [['b', 'Honestly? I thought you looked really nervous.'], ['a', 'I was so nervous.'], ['b', 'It was cute, though.']],
          beat: '{a} laughs.' },
        { when: { persona: 'wallflower' },
          turns: [['b', '…I thought you seemed really nice.'], ['a', 'Just nice?'], ['b', 'Really nice.']],
          beat: '{b} looks down at the pool while saying it.' },
        { when: { persona: 'villa-clown' },
          turns: [['b', "I thought, oh no, I'm going to {~fancy} that one."], ['a', 'Did you?'], ['b', 'Straight away.']],
          beat: '{a} goes red.' },
      ] },
    ] },
  { id: 'chat.02', when: { phase: ['morning', 'day'] },
    turns: [
      ['a', 'Do you ever forget there are cameras?'],
      ['b', 'All the time. Then I remember I was eating cereal out of the box this morning.'],
      ['a', 'That was you?'],
      ['b', 'That was me.'],
    ],
    beat: '{a} laughs and takes a handful.' },
  { id: 'chat.03', when: { phase: 'day' },
    turns: [
      ['a', 'I love this bit of the day.'],
      ['b', "What, when it's roasting?"],
      ['a', "No. When everyone's gone quiet and it's just us."],
      ['b', '{~Yeah}. Me too.'],
    ],
    beat: "They stay on the daybed until someone shouts that dinner's ready." },
  { id: 'chat.04', when: { rung: ['exclusive', 'official'] },
    turns: [
      ['a', 'What would a normal weekend look like? For us, outside.'],
      ['b', "Takeaway, sofa, a film. You'd pick it and I'd fall asleep."],
      ['a', "You've thought about this."],
      ['b', 'Maybe a {~little} bit.'],
    ],
    beat: '{a} pulls {b.obj} a bit closer on the daybed.' },
  { id: 'chat.05',
    turns: [
      ['a', 'Who do you think is going to last in here?'],
      ['b', 'Honestly? I hope us.'],
      ['a', 'Me too.'],
    ],
    beat: '{a} clinks {a.posAdj} glass against {b.pos}.' },
  { id: 'chat.06', when: { gap: true },
    turns: [
      ['a', "Can I ask you something, and you won't make it weird?"],
      ['b', 'Depends what it is.'],
      ['a', 'Where do you think we are? Honestly.'],
      { by: 'b', vary: [
        { turns: [['b', "We're good. We're getting there."], ['a', 'Getting where?'], ['b', "Somewhere good. Can we not put a label on it yet?"]],
          beat: '{a} says fine, and lets it go.' },
        { when: { attachment: 'avoidant' },
          turns: [['b', 'Do we have to do this now?']],
          beat: '{a} drops it. {b} goes to get a drink.' },
        { when: { attachment: 'anxious' },
          turns: [['b', '…Why? Have I done something?'], ['a', 'No! No. I just wanted to know.']],
          beat: '{b} holds on to {a.posAdj} hand for the rest of the conversation.' },
      ] },
    ] },
  { id: 'chat.07',
    turns: [
      ['a', "I've worked out how you have your tea."],
      ['b', 'Go on, then.'],
      ['a', 'Milk, two sugars, and you stir it for way longer than you need to.'],
      ['b', "That's weirdly specific."],
      ['a', 'I pay attention.'],
    ],
    beat: '{b} goes a bit pink.' },
  { id: 'chat.08', when: { mood: 'stressed' },
    turns: [
      ['a', "I'm struggling today. I don't even know why."],
      ['b', "You don't have to know why."],
      ['a', "It's everything. The heat. Everyone watching everyone."],
      ['b', "Then let's just sit here for a bit."],
    ],
    beat: "They sit with their feet in the pool and don't say anything for a while." },
  { id: 'chat.09',
    turns: [
      ['a', 'Be honest. Am I a nightmare to share a bed with?'],
      ['b', 'You steal the whole sheet and then complain that you\'re too hot.'],
      ['a', "That's fair."],
      ['b', "I'm not saying stop. I'm just saying."],
    ] },
  { id: 'chat.10', when: { persona: 'villa-clown' },
    turns: [
      ['a', 'Be honest. Am I too much sometimes?'],
      ['b', 'Sometimes.'],
      ['a', 'Like when?'],
      ['b', 'Like when you did the whole of breakfast in an accent.'],
      ['a', 'It was a good accent, though.'],
      ['b', 'It was a good accent.'],
    ],
    beat: '{b} kisses {a.obj} on the cheek.' },
  { id: 'chat.11', when: { rung: ['closed-off', 'exclusive', 'official'] },
    turns: [
      ['a', "I haven't looked at anyone else since you."],
      ['b', 'I know. I can tell.'],
      ['a', 'How?'],
      ['b', "You don't look up every time somebody new walks in any more."],
    ],
    beat: '{a} takes {b.posAdj} hand.' },
  { id: 'chat.12',
    turns: [
      ['a', 'What do you miss most? From outside.'],
      ['b', 'My own bed. Being able to shut a door. Making toast without twelve people in the kitchen.'],
      ['a', 'Not your phone?'],
      ['b', "I thought I would. I don't really."],
    ],
    beat: '{a} says the same.' },
  { id: 'chat.13', when: { bombshell: true, early: true },
    turns: [
      ['a', "It's weird, isn't it? I've only been here a couple of days and it feels like ages."],
      ['b', "Everyone says that. It doesn't stop."],
      ['a', 'Is that good or bad?'],
      ['b', 'Bit of both.'],
    ] },
  { id: 'chat.14',
    turns: [
      ['a', 'Do I look alright? Honestly.'],
      { by: 'b', vary: [
        { turns: [['b', 'You look amazing, and you know it.'], ['a', "I didn't know it. I wanted to hear it."]],
          beat: '{b} says it again.' },
        { when: { persona: 'checklist' },
          turns: [['b', 'Honestly? The other top was better.'], ['a', '…Right. Thanks.'], ['b', 'You asked.']],
          beat: '{a} goes back inside to change.' },
        { when: { persona: 'hopeless-romantic' },
          turns: [['b', 'You always look alright. You always look better than alright.']],
          beat: '{a} kisses {b.obj} on the cheek on the way past.' },
      ] },
    ] },
  { id: 'chat.15',
    turns: [
      ['a', 'I keep thinking about the next recoupling.'],
      ['b', 'Then talk to me about it. What are you worried about?'],
      ['a', "That you'd pick someone else if you had to."],
      { by: 'b', vary: [
        { turns: [['b', "I wouldn't."]],
          beat: '{a} rests {a.posAdj} head on {b.posAdj} shoulder.' },
        { when: { persona: 'game-player' },
          turns: [['b', "Nobody knows what they'd do until they're up there."]],
          beat: '{a} sits up and moves along the daybed a little.' },
        { when: { loyal: true },
          turns: [['b', "I'd pick you, whoever else was standing there. You know that."]],
          beat: '{a} rests {a.posAdj} head on {b.posAdj} shoulder.' },
      ] },
    ] },
  { id: 'chat.16', when: { early: false },
    turns: [
      ['a', "Tell me something nobody in here knows."],
      ['b', 'I cried after the first recoupling.'],
      ['a', 'Really?'],
      ['b', 'In the bathroom. Nobody saw. I thought nobody was ever going to pick me.'],
    ],
    beat: '{a} takes {b.posAdj} hand and keeps hold of it.' },
  { id: 'chat.17',
    turns: [
      ['a', "What's your favourite thing about me?"],
      ['b', "You're fishing."],
      ['a', "Obviously I'm fishing."],
      ['b', "Your laugh. It's so loud, and you don't care who hears it."],
      ['a', "That's your favourite thing?"],
      ['b', '{~Yeah}.'],
    ] },
  { id: 'chat.18', when: { rung: 'official' },
    turns: [
      ['a', 'I keep saying "we" when I talk about outside.'],
      ['b', 'I noticed.'],
      ['a', 'Is that weird?'],
      ['b', "No. I've been doing it too."],
    ] },
  { id: 'chat.19', when: { mood: 'secure' },
    turns: [
      ['a', "I'm really happy, you know."],
      ['b', '{~Yeah}?'],
      ['a', "{~Yeah}. I don't say it enough."],
      ['b', 'You say it every morning.'],
      ['a', "Well, I'm saying it again."],
    ] },
  { id: 'chat.20', when: { persona: 'wallflower' },
    turns: [
      ['a', "Sorry. I'm not very good at this bit."],
      ['b', 'What bit?'],
      ['a', "Talking, when it's just us. I go blank."],
      ['b', "You're doing fine. Tell me about your day."],
      ['a', 'You were there for all of it.'],
      ['b', 'Tell me anyway.'],
    ],
    beat: '{a} tells {b.obj}, and {b} listens to all of it.' },
  { id: 'chat.21',
    turns: [
      ['a', 'Rate today out of ten.'],
      ['b', 'Seven.'],
      ['a', 'Only seven?'],
      ['b', 'It was an eight before you ate the last yoghurt.'],
    ] },
  { id: 'chat.22', when: { mood: 'lonely' },
    turns: [
      ['a', 'I miss home today.'],
      ['b', 'Anything in particular?'],
      ['a', 'Just normal stuff. Walking to the shop. Being on my own for five minutes.'],
      ['b', 'I can go, if you want five minutes.'],
      ['a', "No. Stay. You being here helps."],
    ] },
  { id: 'chat.23', when: { persona: 'checklist' },
    turns: [
      ['a', "Okay. I've got some questions."],
      ['b', 'Oh no. Is there a list?'],
      ['a', 'Three things. Do you want kids, do you like dogs, and are you a morning person?'],
      ['b', 'Maybe, yes, and absolutely not.'],
      ['a', 'Two out of three. I can work with that.'],
    ] },
  { id: 'chat.24',
    turns: [
      ['a', 'I think everyone in here thinks we\'re boring.'],
      ['b', 'Who said that?'],
      ['a', 'Nobody. You can just tell.'],
      ['b', "I'd rather be boring than be the couple everyone's worried about."],
    ] },
  { id: 'chat.25', when: { phase: ['morning', 'day'] },
    turns: [
      ['a', "Can you do my back? I can't reach."],
      ['b', 'Suncream again? You had some an hour ago.'],
      ['a', "I know. It's more of an excuse."],
      ['b', 'I know it is.'],
    ],
    beat: '{b} does it anyway.' },
  { id: 'chat.26', when: { rung: ['exclusive', 'official'] },
    turns: [
      ['a', "When did you know you didn't want anyone else?"],
      { by: 'b', vary: [
        { turns: [['b', "It wasn't a big moment. You brought me a tea without me asking, and that was it."], ['a', 'A tea?'],
          ['b', "I know. It sounds stupid. But nobody's ever done that without being asked."]] },
        { when: { attachment: 'avoidant' },
          turns: [['b', "I don't know. It just happened."], ['a', "That's it?"], ['b', "That's all you're getting."]],
          beat: '{b} kisses {a.obj} on the forehead.' },
      ] },
    ] },
  { id: 'chat.27',
    turns: [
      ['a', 'What are you thinking about?'],
      ['b', 'Nothing.'],
      ['a', "That's never true."],
      ['b', "Fine. I was thinking I haven't been this relaxed in ages, and it's a bit scary."],
    ] },
  { id: 'chat.28', when: { early: true },
    turns: [
      ['a', "I didn't think I'd like you, you know."],
      ['b', 'Thanks.'],
      ['a', "I mean it nicely! You're not my usual type."],
      ['b', "What's your usual type?"],
      ['a', 'People who are bad for me.'],
    ],
    beat: '{b} laughs, and moves a little closer.' },
  { id: 'chat.29',
    turns: [
      ['a', 'Do you think people at home are watching this bit?'],
      ['b', 'What, us sitting here doing nothing?'],
      ['a', '{~Yeah}.'],
      ['b', "I hope so. It's my favourite bit."],
    ] },
  { id: 'chat.30', when: { persona: 'fuckboy' },
    turns: [
      ['a', "You know you're the only one I talk to like this."],
      { by: 'b', vary: [
        { turns: [['b', 'Am I?'], ['a', 'Of course you are.']],
          beat: '{b} leaves it there.' },
        { when: { persona: 'checklist' },
          turns: [['b', 'Am I, though?'], ['a', '{~Yeah}. You are.']],
          beat: '{b} raises an eyebrow and goes back to {b.posAdj} drink.' },
      ] },
    ] },
  { id: 'chat.31',
    turns: [
      ['a', "Can I be honest? I don't know what I'm doing half the time in here."],
      ['b', 'Nobody does.'],
      ['a', 'You seem like you do.'],
      ['b', "I'm just better at hiding it."],
    ] },
  { id: 'chat.32',
    turns: [
      ['a', 'We should do something tomorrow. Just us.'],
      ['b', "Like what? There's a pool and a kitchen."],
      ['a', "I'll make you breakfast, and we'll just have the day together."],
      ['b', "I'd like that."],
    ] },
  { id: 'chat.33', when: { mood: 'heartbroken' },
    turns: [
      ['a', "Sorry I've been quiet. It's still a bit raw."],
      ['b', "You don't have to apologise."],
      ['a', "I just don't want you to think it's about you."],
      ['b', "I don't. Take your time. I'm not going anywhere."],
    ] },
  { id: 'chat.34', when: { phase: ['morning', 'day'] },
    turns: [
      ['a', "You've got suncream on your nose."],
      ['b', 'Where?'],
      ['a', 'All over it.'],
      ['b', 'And you let me walk round like this for an hour?'],
      ['a', 'Sorry. It was funny.'],
    ],
    beat: '{b} wipes it off on {a.posAdj} shoulder.' },
  { id: 'chat.35', when: { late: true },
    turns: [
      ['a', "Can you believe we've been in here this long?"],
      ['b', "No. I can't remember what I used to do all day."],
      ['a', 'Me neither. Probably just looked at my phone.'],
      ['b', 'All day, every day.'],
    ] },
  { id: 'chat.36', when: { late: true, rung: ['exclusive', 'official'] },
    turns: [
      ['a', 'What happens when we leave? Actually leave.'],
      { by: 'b', vary: [
        { turns: [['b', "We go home, we sleep for two days, and then I come and find you."], ['a', 'Promise?'], ['b', 'Promise.']] },
        { when: { attachment: 'anxious' },
          turns: [['b', "I've been trying not to think about it."], ['a', 'Why?'], ['b', 'Because in here I always know where you are.']],
          beat: '{a} puts an arm round {b.obj} and keeps it there.' },
      ] },
    ] },
];
