// chat — a couple talking, nothing at stake. Cast: [a, b], coupled together.
// Never invent a backstory fact (a job, a sibling, a hometown): the cast
// setup owns those. The villa, the day and each other are fair game.
export const CHAT = [
  { id: 'chat.01', when: { early: true },
    turns: [
      ['a', 'What did you actually think of me when I walked in?'],
      { by: 'b', vary: [
        { turns: [['b', 'Honestly? I thought you looked terrified.'], ['a', 'I was terrified.'], ['b', 'It was cute.']],
          beat: '{a} laughs into {a.posAdj} drink.' },
        { when: { persona: 'wallflower' },
          turns: [['b', '…I thought you seemed nice.'], ['a', "Nice? That's it?"], ['b', 'Really nice.']],
          beat: "{b} says it to the pool rather than to {a.obj}." },
        { when: { persona: 'villa-clown' },
          turns: [['b', "I thought, that one's definitely going to snore."], ['a', 'And?'], ['b', 'And I was right.']],
          beat: '{a} throws a cushion at {b.obj}.' },
      ] },
    ] },
  { id: 'chat.02', when: { phase: ['morning', 'day'] },
    turns: [
      ['a', 'Do you ever forget there are cameras?'],
      ['b', "All the time. Then I remember I'm eating cereal out of the box with my hands."],
      ['a', 'That was you?'],
      ['b', 'That was me.'],
    ],
    beat: '{a} shakes {a.posAdj} head and takes a handful anyway.' },
  { id: 'chat.03', when: { phase: 'day' },
    turns: [
      ['a', 'I love this bit of the day.'],
      ['b', 'What, sweating?'],
      ['a', "No. When everyone's gone quiet and it's just us out here."],
      ['b', '…Yeah. Me too.'],
    ],
    beat: 'They stay on the daybed until somebody shouts that dinner is ready.' },
  { id: 'chat.04', when: { rung: ['exclusive', 'official'] },
    turns: [
      ['a', 'What would we do on a normal Tuesday? Outside, I mean.'],
      ['b', "Takeaway. Sofa. You'd pick the film and I'd fall asleep in the first ten minutes."],
      ['a', "You've thought about this."],
      ['b', 'Maybe a little bit.'],
    ],
    beat: '{a} pulls {b.obj} a bit closer on the daybed.' },
  { id: 'chat.05',
    turns: [
      ['a', 'Who do you think is actually going to last in here?'],
      ['b', "Us. After that, I've got no idea."],
      ['a', 'Good answer.'],
      ['b', 'It was the only answer.'],
    ],
    beat: '{a} clinks {a.posAdj} glass against {b.pos}.' },
  { id: 'chat.06', when: { gap: true },
    turns: [
      ['a', "Can I ask you something, and you won't make it weird?"],
      ['b', 'That depends on the question.'],
      ['a', 'Where do you think we are? Honestly.'],
      { by: 'b', vary: [
        { turns: [['b', "We're good. We're getting there."], ['a', 'Getting where?'], ['b', 'Somewhere. Can we not label it today?']],
          beat: '{a} says fine, and lets it go.' },
        { when: { attachment: 'avoidant' },
          turns: [['b', 'Do we have to do this now?']],
          beat: '{a} drops it. {b} goes to get a drink.' },
        { when: { attachment: 'anxious' },
          turns: [['b', '…Why? Have I done something?'], ['a', 'No! No. I just wanted to know.']],
          beat: "{b} holds on to {a.posAdj} hand for the rest of the conversation." },
      ] },
    ] },
  { id: 'chat.07',
    turns: [
      ['a', "I've worked out your tea order."],
      ['b', 'Go on, then.'],
      ['a', 'Milk, two sugars, and you stir it for about a minute longer than anyone needs to.'],
      ['b', "That's weirdly specific."],
      ['a', 'I pay attention.'],
    ],
    beat: '{b} goes a bit pink.' },
  { id: 'chat.08', when: { mood: 'stressed' },
    turns: [
      ['a', "I'm struggling today. I don't even know why."],
      ['b', "You don't have to know why."],
      ['a', "It's everything. The heat. Everyone watching everyone."],
      ['b', "Then let's sit here and not talk for a bit."],
    ],
    beat: "They sit with their feet in the pool and don't say anything for a while." },
  { id: 'chat.09',
    turns: [
      ['a', 'Be honest. Am I a nightmare to share a bed with?'],
      ['b', 'You steal the whole sheet and then you complain that you\'re hot.'],
      ['a', "That's fair, actually."],
      ['b', "I'm not saying stop. I'm just saying."],
    ] },
  { id: 'chat.10', when: { persona: 'villa-clown' },
    turns: [
      ['a', 'If this was a nature documentary, what animal would everyone be?'],
      ['b', 'Oh no.'],
      ['a', "I'm serious. I'm a golden retriever. You're a cat. You like me, but you'd never say it in front of anyone."],
      ['b', "I'd say it in front of people."],
      ['a', 'Say it, then.'],
    ],
    beat: '{b} pushes {a.obj} off the daybed.' },
  { id: 'chat.11', when: { rung: ['closed-off', 'exclusive', 'official'] },
    turns: [
      ['a', "I haven't looked at anyone else since you."],
      ['b', 'I know. I can tell.'],
      ['a', 'How?'],
      ['b', "You stopped checking who's walking in every time the door goes."],
    ],
    beat: '{a} looks toward the door out of habit, and they both laugh.' },
  { id: 'chat.12',
    turns: [
      ['a', 'What do you miss most? From outside.'],
      ['b', 'My own bed. A door I can shut. Toast that isn\'t being made by twelve people at once.'],
      ['a', 'Not your phone?'],
      ['b', "I thought I would. I haven't really."],
    ],
    beat: '{a} says the same.' },
  { id: 'chat.13', when: { bombshell: true, early: true },
    turns: [
      ['a', "It's strange, isn't it? I've only been here a couple of days and it feels like weeks."],
      ['b', 'Everyone says that. It gets worse.'],
      ['a', 'Worse?'],
      ['b', 'Better. Worse. Both.'],
    ] },
  { id: 'chat.14',
    turns: [
      ['a', 'Do I look alright? Honestly.'],
      { by: 'b', vary: [
        { turns: [['b', 'You look better than alright, and you know it.'], ['a', "I didn't know it. I wanted to hear it."]],
          beat: '{b} says it again, slower.' },
        { when: { persona: 'checklist' },
          turns: [['b', 'Honestly? The other top was better.'], ['a', '…Right. Thanks.'], ['b', 'You asked.']],
          beat: '{a} goes back inside to change.' },
        { when: { persona: 'hopeless-romantic' },
          turns: [['b', "You always look alright. That's the annoying thing about you."]],
          beat: '{a} kisses {b.obj} on the cheek on the way past.' },
      ] },
    ] },
  { id: 'chat.15',
    turns: [
      ['a', 'I keep thinking about the next recoupling.'],
      ['b', 'Then think about it with me. What are you worried about?'],
      ['a', "That you'd pick someone else if you had to."],
      { by: 'b', vary: [
        { turns: [['b', "I wouldn't."]],
          beat: '{a} rests {a.posAdj} head on {b.posAdj} shoulder.' },
        { when: { persona: 'game-player' },
          turns: [['b', 'Nobody knows what they\'d do until they\'re stood there.']],
          beat: '{a} sits up and moves along the daybed a little.' },
        { when: { loyal: true },
          turns: [['b', "I'd pick you if every single person in here stood up. You know that."]],
          beat: '{a} rests {a.posAdj} head on {b.posAdj} shoulder.' },
      ] },
    ] },
  { id: 'chat.16', when: { early: false },
    turns: [
      ['a', 'Tell me something nobody in here knows.'],
      ['b', 'I cried after the first recoupling.'],
      ['a', 'Really?'],
      ['b', 'In the bathroom. Nobody saw. I thought nobody would ever pick me.'],
    ],
    beat: '{a} takes {b.posAdj} hand and keeps hold of it.' },
  { id: 'chat.17',
    turns: [
      ['a', "What's your favourite thing about me?"],
      ['b', "You're fishing."],
      ['a', "Obviously I'm fishing."],
      ['b', 'Your laugh. It\'s ridiculous. You sound like a car that won\'t start.'],
      ['a', "That's your favourite thing?"],
      ['b', 'Yeah.'],
    ] },
  { id: 'chat.18', when: { rung: 'official' },
    turns: [
      ['a', 'I keep saying "we" when I talk about outside.'],
      ['b', 'I noticed.'],
      ['a', 'Is that weird?'],
      ['b', "No. I've been doing it too."],
    ] },
  { id: 'chat.19', when: { mood: 'secure' },
    turns: [
      ['a', "I'm really happy, you know."],
      ['b', 'Yeah?'],
      ['a', "Yeah. I don't say it enough."],
      ['b', 'You say it every morning.'],
      ['a', "Then I'm saying it again."],
    ] },
  { id: 'chat.20', when: { persona: 'wallflower' },
    turns: [
      ['a', "Sorry. I'm not very good at this bit."],
      ['b', 'What bit?'],
      ['a', "Talking, when it's just us. I go blank."],
      ['b', "You're doing fine. Tell me about your day."],
      ['a', 'You were there for all of it.'],
      ['b', 'Tell me anyway.'],
    ],
    beat: '{a} does. It takes ten minutes, and {b} listens to all of it.' },
  { id: 'chat.21',
    turns: [
      ['a', 'Rate today out of ten.'],
      ['b', 'Seven.'],
      ['a', 'Only seven?'],
      ['b', 'It was eight until you ate the last yoghurt.'],
    ] },
  { id: 'chat.22', when: { mood: 'lonely' },
    turns: [
      ['a', 'I miss home today.'],
      ['b', 'Anything in particular?'],
      ['a', 'Just normal stuff. Walking to the shop. Being on my own for five minutes.'],
      ['b', 'I can go, if you want five minutes.'],
      ['a', "No. Stay. That's the bit that helps."],
    ] },
  { id: 'chat.23', when: { persona: 'checklist' },
    turns: [
      ['a', "Okay. I've got questions."],
      ['b', 'Oh no. Is there a list?'],
      ['a', 'Three things. Do you want kids, do you like dogs, and do you put the milk in before the cereal?'],
      ['b', 'Maybe, yes, and never.'],
      ['a', 'Two out of three. I can work with that.'],
    ] },
  { id: 'chat.24',
    turns: [
      ['a', 'Everyone in here thinks we\'re boring.'],
      ['b', 'Who said that?'],
      ['a', 'Nobody. You can just tell.'],
      ['b', "Good. Boring means nobody's worried about us."],
    ] },
  { id: 'chat.25', when: { phase: ['morning', 'day'] },
    turns: [
      ['a', "Can you do my back? I can't reach."],
      ['b', 'Suncream again? You had some an hour ago.'],
      ['a', "I know. It's more of an excuse."],
      ['b', 'I know it is.'],
    ],
    beat: '{b} does it anyway, very slowly.' },
  { id: 'chat.26', when: { rung: ['exclusive', 'official'] },
    turns: [
      ['a', "When did you know you didn't want anyone else?"],
      { by: 'b', vary: [
        { turns: [['b', "It wasn't a big moment. You brought me a tea without asking, and that was it."], ['a', 'A tea?'],
          ['b', 'It was a really good tea.']] },
        { when: { attachment: 'avoidant' },
          turns: [['b', "I don't know. It just happened."], ['a', "That's it?"], ['b', "That's all you're getting."]],
          beat: '{b} kisses {a.obj} on the forehead.' },
      ] },
    ] },
  { id: 'chat.27',
    turns: [
      ['a', 'What are you thinking about?'],
      ['b', 'Nothing.'],
      ['a', "That's never true."],
      ['b', "Fine. I was thinking I've never been this relaxed, and it's starting to scare me."],
    ] },
  { id: 'chat.28', when: { early: true },
    turns: [
      ['a', "I didn't think I'd like you, you know."],
      ['b', 'Thanks.'],
      ['a', "I mean it nicely! You're not my usual type."],
      ['b', "What's your usual type?"],
      ['a', 'Bad for me.'],
    ],
    beat: '{b} laughs, and moves a little closer.' },
  { id: 'chat.29',
    turns: [
      ['a', 'Do you think people at home are watching this bit?'],
      ['b', 'What, us sitting here doing nothing?'],
      ['a', 'Yeah.'],
      ['b', 'I hope so. This is the best bit.'],
    ] },
  { id: 'chat.30', when: { persona: 'fuckboy' },
    turns: [
      ['a', "You know you're the only one I talk to like this."],
      { by: 'b', vary: [
        { turns: [['b', 'Am I?'], ['a', 'Course you are.']],
          beat: '{b} leaves it there.' },
        { when: { persona: 'checklist' },
          turns: [['b', 'Do you, though?'], ['a', 'I do now.']],
          beat: '{b} raises an eyebrow and goes back to {b.posAdj} drink.' },
      ] },
    ] },
  { id: 'chat.31',
    turns: [
      ['a', "Can I be honest? I don't know what I'm doing half the time in here."],
      ['b', 'Nobody does.'],
      ['a', 'You seem like you do.'],
      ['b', "That's just my face."],
    ] },
  { id: 'chat.32',
    turns: [
      ['a', 'We should do something tomorrow. Just us.'],
      ['b', "Like what? There's a pool and a kitchen."],
      ['a', "I'll make you breakfast, then we'll sit by the pool, then I'll make you lunch."],
      ['b', 'So, a normal day.'],
      ['a', 'A normal day, but on purpose.'],
    ] },
  { id: 'chat.33', when: { mood: 'heartbroken' },
    turns: [
      ['a', "Sorry I've been quiet. It's still a bit raw."],
      ['b', "You don't have to apologise."],
      ['a', "I just don't want you to think it's about you."],
      ['b', "I don't. Take your time. I'm not going anywhere."],
    ] },
  { id: 'chat.34', when: { phase: ['morning', 'day'] },
    turns: [
      ['a', "You've got suncream on your nose."],
      ['b', 'Where?'],
      ['a', 'All of it. Your whole nose.'],
      ['b', 'And you let me walk round like this for an hour?'],
      ['a', 'It was a really good hour.'],
    ],
    beat: '{b} wipes it off on {a.posAdj} shoulder.' },
  { id: 'chat.35', when: { late: true },
    turns: [
      ['a', "Can you believe we've been in here this long?"],
      ['b', "No. I can't remember what I did with my days before."],
      ['a', 'You probably had a phone.'],
      ['b', 'Oh, yeah. That was it.'],
    ] },
  { id: 'chat.36', when: { late: true, rung: ['exclusive', 'official'] },
    turns: [
      ['a', "What happens when we leave? Actually leave."],
      { by: 'b', vary: [
        { turns: [['b', "We go home, we sleep for two days, and then I come and find you."], ['a', "Promise?"], ['b', 'Promise.']] },
        { when: { attachment: 'anxious' },
          turns: [['b', "I've been trying not to think about it."], ['a', 'Why?'], ['b', "Because in here I know where you are."]],
          beat: '{a} puts an arm round {b.obj} and keeps it there.' },
      ] },
    ] },
];
