// pm/lines/day/close-more.js — more endings (see close.js). Data only.
//
// Read in a 26-islander season (seed 31): an episode plays about 18
// friendships, 16 pulls, 9 arguments, 6 chats and 4 turn-downs, and the
// ending pools held 5 to 9 each — "This was nice. We should do this every
// day." ended 37 scenes. Every pool here is sized past what one episode
// uses, and about half are an action with no line at all: most real
// conversations end with somebody getting up, not with a closing line.
// A beat-only ending never follows an opener that already ended on its own
// beat (pm/script.js closed).
import { KISS_CLOSE } from './kiss-close.js';
import { ICK_CLOSE } from './ick-close.js';
const A = (id, beat, when = {}) => ({ id, when, turns: [], beat });

export const CLOSE_MORE = {
  ...KISS_CLOSE,
  ...ICK_CLOSE,
  'friendship-close': [
    { id: 'fc.11', turns: [['a', "Right. I need a drink. Do you want one?"], ['b', "Always."]] },
    { id: 'fc.12', turns: [['b', "We should get ready soon."], ['a', "Ten more minutes."], ['b', "Ten. Then we go."]] },
    { id: 'fc.13', turns: [['a', "Thanks for listening."], ['b', "That's what I'm here for."]] },
    { id: 'fc.14', turns: [['b', "Come on. Everyone's in the pool."], ['a', "I'll be in in a minute."]] },
    { id: 'fc.15', turns: [['a', "I'm going to go and shower before the queue starts."], ['b', "Good luck with that."]] },
    { id: 'fc.16', turns: [['b', "Right, I'm starving. Kitchen?"], ['a', "Kitchen."]] },
    { id: 'fc.17', turns: [['a', "You're a good friend, you know."], ['b', "So are you. Now stop, or I'll cry."]] },
    { id: 'fc.18', turns: [['b', "Same sunbed later?"], ['a', "Obviously."]] },
    { id: 'fc.19', turns: [['a', "I feel a lot better for that."], ['b', "Good. That's the idea."]] },
    { id: 'fc.20', turns: [['b', "Let's not tell anyone we spent the whole afternoon gossiping."], ['a', "Our secret."]] },
    { id: 'fc.21', turns: [['a', "Right. Back to it."], ['b', "Back to it."]] },
    { id: 'fc.22', turns: [['b', "I'm glad we talked."], ['a', "Me too. Properly glad."]] },
    { id: 'fc.23', turns: [['a', "Don't let me forget to put sun cream on."], ['b', "I won't. I'll nag you."]] },
    { id: 'fc.24', turns: [['b', "Hug?"], ['a', "Go on, then."]] },
    { id: 'fc.25', turns: [['a', "I owe you one."], ['b', "You owe me about six."]] },
    { id: 'fc.26', turns: [['b', "Right. I'm going to go and find my partner."], ['a', "Go on. Say hi from me."]], when: { bTaken: true } },
    { id: 'fc.27', turns: [['a', "I'd better go and find {pa} before {pa} sends out a search party."], ['b', "Go."]], when: { taken: true } },
    { id: 'fc.28', turns: [['b', "Same time tomorrow, then."], ['a', "Same time tomorrow."]] },
    A('fc.b01', 'They head back to the others together.'),
    A('fc.b02', '{b} throws a towel at {a}, and they go back to the pool.'),
    A('fc.b03', 'Somebody calls them both in for dinner, and they go.'),
    A('fc.b04', 'They sit there a while longer, not saying much, and it is fine.'),
    A('fc.b05', '{a} gets up to refill the drinks, and {b} follows.'),
    A('fc.b06', 'The conversation drifts on to the others, and nobody is in a hurry to move.'),
    A('fc.b07', '{b} laughs, and nudges {a} with a shoulder.'),
    A('fc.b08', 'They go and join the group by the pool.'),
    A('fc.b09', '{a} lies back on the sunbed, and {b} does the same.'),
    A('fc.b10', 'They are still talking an hour later.'),
    A('fc.b11', '{b} gives {a} a quick hug on the way past.'),
    A('fc.b12', 'Someone shouts for them from the kitchen, and the chat is over.'),
    A('fc.b13', 'They walk back inside, arm in arm.'),
    A('fc.b14', '{a} goes to get ready, and {b} stays out in the sun.'),
    A('fc.b15', 'The two of them end up laughing about something else entirely.'),
    A('fc.b16', '{b} stretches, yawns, and says it is time for a nap.'),
  ],

  'pull-close': [
    { id: 'pc.f.08', when: { of: 'flirt' }, turns: [['a', "I've enjoyed this."], ['b', "So have I."]] },
    { id: 'pc.f.09', when: { of: 'flirt' }, turns: [['b', "People are looking."], ['a', "Let them look."]] },
    { id: 'pc.f.10', when: { of: 'flirt' }, turns: [['a', "Same time tomorrow?"], ['b', "We'll see."]] },
    { id: 'pc.f.11', when: { of: 'flirt' }, turns: [['b', "You're trouble, you know that?"], ['a', "The good kind."]] },
    { id: 'pc.f.12', when: { of: 'flirt' }, turns: [['a', "I'll let you get back."], ['b', "Thanks for the chat."]] },
    { id: 'pc.f.13', when: { of: 'flirt' }, turns: [['b', "I didn't expect to like talking to you this much."], ['a', "Is that a bad thing?"], ['b', "I'll tell you later."]] },
    { id: 'pc.f.14', when: { of: 'flirt', taken: true }, turns: [['b', "Go on. Your partner will be looking for you."], ['a', "I know."]] },
    { id: 'pc.f.15', when: { of: 'flirt', bTaken: true }, turns: [['b', "I should go back."], ['a', "Probably."]], beat: "{b} doesn't go back straight away." },
    { id: 'pc.f.16', when: { of: 'flirt' }, turns: [['a', "Think about it."], ['b', "Think about what?"], ['a', "Me."]] },
    { id: 'pc.f.17', when: { of: 'flirt' }, turns: [['b', "That was nice."], ['a', "Just nice?"], ['b', "Don't push your luck."]] },
    A('pc.fb.01', 'They walk back to the others, a little closer together than they walked out.', { of: 'flirt' }),
    A('pc.fb.02', 'Somebody from the kitchen shouts for {b}, and the moment is gone.', { of: 'flirt' }),
    A('pc.fb.03', '{b} laughs, and does not move away.', { of: 'flirt' }),
    A('pc.fb.04', 'They talk until the sun goes behind the terrace.', { of: 'flirt' }),
    A('pc.fb.05', '{a} goes back to the group, grinning, and tries very hard not to look back.', { of: 'flirt' }),
    A('pc.fb.06', 'By the time they come back, half the villa has noticed how long they were gone.', { of: 'flirt' }),
    A('pc.fb.07', '{b} goes to get a drink, and glances back at {a} on the way.', { of: 'flirt' }),
    A('pc.fb.08', 'They are interrupted by the text alarm, and neither of them is pleased about it.', { of: 'flirt' }),
    { id: 'pc.t.06', when: { of: 'turned-down' }, turns: [['a', "I'll leave you to it, then."], ['b', "Sorry."]] },
    { id: 'pc.t.07', when: { of: 'turned-down' }, turns: [['a', "Worth a try."], ['b', "It was. Honestly."]] },
    { id: 'pc.t.08', when: { of: 'turned-down' }, turns: [['b', "No hard feelings?"], ['a', "None. I'll get over it."]] },
    { id: 'pc.t.09', when: { of: 'turned-down' }, turns: [['a', "Right. That's clear, then."], ['b', "I hope you're okay."], ['a', "I'm fine."]] },
    A('pc.tb.01', '{a} nods, and goes back to the others as if nothing happened.', { of: 'turned-down' }),
    A('pc.tb.02', '{a} walks off a little faster than {a} walked over.', { of: 'turned-down' }),
    A('pc.tb.03', '{b} watches {a} go, and feels a bit bad about it.', { of: 'turned-down' }),
    A('pc.tb.04', '{a} laughs it off, and heads straight for the pool.', { of: 'turned-down' }),
    A('pc.tb.05', 'It is an awkward walk back, and they take different routes.', { of: 'turned-down' }),
    A('pc.tb.06', '{a} goes to find a friend, and does not mention it.', { of: 'turned-down' }),
    A('pc.kb.01', 'They come back separately, a few minutes apart, and neither of them looks at the other.', { of: 'kissed' }),
    A('pc.kb.02', 'Somebody sees them come back from round the side.', { of: 'kissed' }),
    A('pc.pb.01', 'They go back to the others as if nothing was said.', { of: 'promised' }),
  ],

  'chat-close': [
    { id: 'cc.w.09', when: { of: 'warm' }, turns: [['a', "I love you being here."], ['b', "Where else would I be?"]] },
    { id: 'cc.w.10', when: { of: 'warm' }, turns: [['b', "Come on. Dinner."], ['a', "Only if I'm sitting next to you."]] },
    { id: 'cc.w.11', when: { of: 'warm' }, turns: [['a', "This is the best bit of my day."], ['b', "Mine too."]] },
    { id: 'cc.w.12', when: { of: 'warm' }, turns: [['b', "Do you know what? I'm really happy."], ['a', "Good. So am I."]] },
    A('cc.wb.01', '{b} rests {b.posAdj} head on {a.posAdj} shoulder, and they stay like that.', { of: 'warm' }),
    A('cc.wb.02', 'They kiss, and then get up to join the others.', { of: 'warm' }),
    A('cc.wb.03', '{a} takes {b.posAdj} hand, and they walk back in together.', { of: 'warm' }),
    A('cc.wb.04', 'They are still smiling when they sit down for dinner.', { of: 'warm' }),
    A('cc.wb.05', '{a} kisses {b} on the forehead, and goes to get them both a drink.', { of: 'warm' }),
    A('cc.wb.06', 'Neither of them notices the others calling them in.', { of: 'warm' }),
    { id: 'cc.e.08', when: { of: 'easy' }, turns: [['b', "Right. I'm going to get changed."], ['a', "See you out there."]] },
    { id: 'cc.e.09', when: { of: 'easy' }, turns: [['a', "Shall we go and join the others?"], ['b', "Go on, then."]] },
    { id: 'cc.e.10', when: { of: 'easy' }, turns: [['b', "I like talking to you."], ['a', "Good. I like it too."]] },
    A('cc.eb.01', 'They head back to the group together.', { of: 'easy' }),
    A('cc.eb.02', '{b} goes to get ready, and {a} stays in the sun a while longer.', { of: 'easy' }),
    A('cc.eb.03', 'The chat drifts on to everyone else in the villa.', { of: 'easy' }),
    A('cc.eb.04', '{a} goes to make them both a tea.', { of: 'easy' }),
    A('cc.eb.05', 'Somebody shouts that dinner is ready, and that is the end of it.', { of: 'easy' }),
    A('cc.fb.01', '{b} goes inside, and {a} stays out there on {a.posAdj} own.', { of: 'flat' }),
    A('cc.fb.02', 'The conversation runs out, and neither of them tries very hard to start it again.', { of: 'flat' }),
    A('cc.fb.03', 'They sit side by side, both looking at the pool.', { of: 'flat' }),
  ],

  'argument-close': [
    { id: 'acl.m.07', when: { of: 'make-up' }, turns: [['a', "Friends?"], ['b', "Friends."]] },
    { id: 'acl.m.08', when: { of: 'make-up' }, turns: [['b', "Let's not do that again."], ['a', "Deal."]] },
    A('acl.mb.01', 'They hug, and it is over as quickly as it started.', { of: 'make-up' }),
    A('acl.mb.02', 'A few minutes later they are laughing about it.', { of: 'make-up' }),
    A('acl.mb.03', '{a} holds out a hand, and {b} takes it.', { of: 'make-up' }),
    { id: 'acl.w.06', when: { of: 'walk-off' }, turns: [['a', "I'm done talking."]], beat: '{a} walks off before {b} can answer.' },
    A('acl.wb.01', '{b} walks off, and {a} does not follow.', { of: 'walk-off' }),
    A('acl.wb.02', '{a} storms into the villa and does not come out for an hour.', { of: 'walk-off' }),
    A('acl.wb.03', 'They leave in opposite directions.', { of: 'walk-off' }),
    { id: 'acl.s.06', when: { of: 'simmer' }, turns: [['b', "Forget it."], ['a', "Already forgotten."]], beat: '{b} is still annoyed.' },
    A('acl.sb.01', 'They sit in silence, both of them still annoyed.', { of: 'simmer' }),
    A('acl.sb.02', 'Somebody changes the subject, loudly, and it works for now.', { of: 'simmer' }),
    A('acl.sb.03', 'Neither of them says sorry, and neither of them leaves.', { of: 'simmer' }),
    A('acl.sb.04', 'It goes quiet, but it is not finished.', { of: 'simmer' }),
  ],

  'loyalty-close': [
    { id: 'lc.07', turns: [['b', "Okay. Message received."], ['a', "Thanks."]] },
    { id: 'lc.08', turns: [['b', "Can't blame me for trying."], ['a', "I don't."]] },
    A('lc.b01', '{b} nods, and goes back to the others.'),
    A('lc.b02', '{a} goes straight back to {a.posAdj} partner.'),
    A('lc.b03', '{b} shrugs, and goes to try somebody else.'),
    A('lc.b04', 'It is a little awkward for a few minutes, and then it is not.'),
    A('lc.b05', '{a} mentions it to {a.posAdj} partner later, and they both laugh about it.'),
  ],

  'deep-chat-close': [
    A('dc.ob.01', 'They sit there for a long time afterwards, holding hands.', { of: 'open' }),
    A('dc.ob.02', '{b} kisses {a}, and neither of them says anything else for a while.', { of: 'open' }),
    A('dc.ob.03', "It's the most either of them has said in days.", { of: 'open' }),
    A('dc.gb.01', '{b} changes the subject, and {a} lets it go.', { of: 'guarded' }),
    A('dc.gb.02', '{a} squeezes {b.posAdj} hand, and does not push.', { of: 'guarded' }),
  ],
};
