// comedy — somebody makes the villa laugh. Cast: [a, b]: {a} is the one being
// funny, {b} whoever is nearest, who answers. The rest of the room can react
// in the staging and the beat, never by name.
//
// A whole little conversation, not a one-liner: the situation, {b} joining
// in, a line or two back and forth (user: "make sure we have actual
// conversations too" — every comedy scene aired as a single line). The joke is
// the SITUATION, said plainly — a jar that won't open, a song in the shower —
// never a line built to be clever. The beat says what happened next; it is not
// a second punchline.
export const COMEDY = [
  { id: 'comedy.01',
    stage: '{a} has been trying to open a jar for about five minutes.',
    turns: [['a', "Nobody help me. I've got this."], ['b', "You've been at it since breakfast."],
      ['a', "It's loosening. I can feel it loosening."], ['b', "Give it here."], ['a', "No! …Fine."]],
    beat: '{b} opens it first go.' },
  { id: 'comedy.02', when: { phase: 'morning' },
    stage: '{a} is singing in the shower, loud enough for the whole villa to hear.',
    turns: [['b', "We can all hear you!"], ['a', "I know! I'm not stopping!"],
      ['b', "At least do one we know."], ['a', "Requests are open!"]],
    beat: 'A few of them start singing along from the kitchen.' },
  { id: 'comedy.03',
    stage: '{a} comes out into the garden, hopping.',
    turns: [['a', "Has anyone seen my other flip-flop?"], ['b', "Why are you hopping? Just take the other one off."],
      ['a', "Then I'd have no flip-flops. This way I've got one."], ['b', "That's not how it works."]],
    beat: 'Somebody finds it on the roof later.' },
  { id: 'comedy.04',
    stage: '{a} does an impression of the text alarm.',
    turns: [['a', "Beep beep! Islanders, somebody has eaten the last yoghurt!"], ['b', "Don't do that! I nearly dropped my drink."],
      ['a', "It worked, though. Everyone came running."], ['b', "Who did eat the last yoghurt?"], ['a', "…Me."]],
    beat: 'Half the villa jumps before they realise it was {a}.' },
  { id: 'comedy.05',
    stage: '{a} is carrying a tray of drinks along the edge of the pool.',
    turns: [['b', "Want a hand?"], ['a', "No, I'm fine. Don't watch me."], ['b', "I'm watching you."], ['a', "Don't watch me. Don't watch me. Don't—"]],
    beat: '{a} and the drinks end up in the pool.' },
  { id: 'comedy.06',
    stage: '{b} asks {a} what {a.posAdj} type is.',
    turns: [['b', "Go on then. What's your type?"], ['a', "Honestly? Anyone who makes me a cup of tea without me having to ask."],
      ['b', "That's it? That's the bar?"], ['a', "You'd be surprised how few people get over it."]] },
  { id: 'comedy.07', when: { phase: ['day', 'evening'] },
    stage: '{a} and {b} are at the stove with two other islanders.',
    turns: [['a', "Why does it take four of us to make one pot of pasta?"], ['b', "Because you keep stirring it."],
      ['a', "You're stirring it too!"], ['b', "I'm supervising."]],
    beat: 'Three people are stirring it at once.' },
  { id: 'comedy.08',
    stage: 'The text alarm goes off, and everyone jumps.',
    turns: [['a', "I'm never getting used to that."], ['b', "You screamed."],
      ['a', "I did not scream."], ['b', "You screamed and grabbed my arm."], ['a', "Every single time, I nearly have a heart attack."]] },
  { id: 'comedy.09',
    stage: '{a} has put on three pairs of sunglasses at once.',
    turns: [['a', "Can anyone see me? Because I can't see anything."], ['b', "Why have you got three on?"],
      ['a', "It's really bright today."], ['b', "Mind the—"]],
    beat: '{a} walks into a sunbed.' },
  { id: 'comedy.10',
    stage: '{a} is doing impressions of the islanders, one at a time.',
    turns: [['a', 'Who\'s this? "Can I pull you for a chat?"'], ['b', "Everyone says that."],
      ['a', 'Okay, okay. "Can I pull you for a chat? Just a quick one?"'], ['b', "Oh, that's so good."]],
    beat: 'Everyone shouts the same name at once.' },
  { id: 'comedy.11', when: { phase: ['day', 'evening'] },
    stage: '{a} has been put in charge of the barbecue.',
    turns: [['b', "Is that meant to be black?"], ['a', "It's not burnt. It's just a bit well done."],
      ['b', "It's on fire."], ['a', "That's the flavour."]],
    beat: 'The burgers are black on both sides.' },
  { id: 'comedy.12', when: { late: true },
    stage: '{a} and {b} are lying on sunbeds, half asleep.',
    turns: [['a', "I've been in here so long I've forgotten what it's like to wear shoes."], ['b', "You wore heels last night."],
      ['a', "Those aren't shoes. Those are a punishment."], ['b', "You said you loved them."], ['a', "I lied to you."]] },
  { id: 'comedy.13', when: { phase: 'morning' },
    stage: 'At breakfast, {a} leans across the table to {b}.',
    turns: [['a', "Does anyone else feel like this is the longest job interview of their life?"], ['b', "What's the job?"],
      ['a', "Being loved. And I'm not sure I'm getting it."], ['b', "You're getting it. You've got my vote."]],
    beat: 'The whole kitchen laughs.' },
  { id: 'comedy.14', when: { early: true },
    stage: 'Round the fire pit, {a} is telling {b}.',
    turns: [['a', "I've been asked my star sign about eleven times already."], ['b', "What did you say?"],
      ['a', "A different one every time."], ['b', "So what are you really?"], ['a', "I'm not telling you now."]] },
  { id: 'comedy.15',
    stage: '{a} is trying to drink through three straws at once.',
    turns: [['b', "Why?"], ['a', "Somebody said I couldn't."], ['b', "Nobody said that."],
      ['a', "Well, I've started now, so I'm finishing."]] },
  { id: 'comedy.16',
    stage: '{a} is blowing up a giant inflatable swan by mouth.',
    turns: [['b', "There's a pump in the cupboard."], ['a', "Now you tell me."],
      ['b', "How long have you been doing that?"], ['a', "I can't feel my face."]],
    beat: 'The swan is about a quarter full.' },
  { id: 'comedy.17',
    stage: '{a} has made a sign for the bathroom door out of a cereal box.',
    turns: [['b', "What does it say?"], ['a', '"Occupied" on this side.'], ['b', "And the other side?"],
      ['a', '"Do not disturb, crying."'], ['b', "That's going to get used a lot."]],
    beat: 'It stays on the door for the rest of the week.' },
  { id: 'comedy.18', when: { persona: 'villa-clown' },
    stage: '{a} whispers the plan to {b} in the kitchen.',
    turns: [['a', "If nobody gets a text today, I'm going to shout \"I've got a text!\" and see who comes running."], ['b', "Don't. They'll kill you."],
      ['a', "Watch this."], ['b', "I'm not having anything to do with it."]],
    beat: '{a} does it, and four people run in from the garden.' },
  { id: 'comedy.19', when: { phase: 'event' },
    stage: 'During the challenge, {a} slips on the foam and goes down slowly.',
    turns: [['b', "Are you okay?"], ['a', "I'm fine! I meant to do that!"],
      ['b', "You're still on the floor."], ['a', "I'm resting. Leave me."]] },
  { id: 'comedy.20',
    stage: 'At lunch, {a} stands up to make an announcement.',
    turns: [['a', "I made the tea this morning, and I have to be honest, it was terrible. I'm sorry, everyone."], ['b', "I drank all of mine!"],
      ['a', "Why would you do that?"], ['b', "I didn't want to be rude!"]],
    beat: 'Somebody pours theirs into a plant pot.' },
  { id: 'comedy.21',
    stage: '{a} is teaching {b} a dance nobody asked to learn.',
    turns: [['a', "Five, six, seven, eight. No, the other way."], ['b', "This is the other way."],
      ['a', "Your other left!"], ['b', "I've only got one left!"]],
    beat: 'By the end, most of the villa is doing it, badly.' },
  { id: 'comedy.22', when: { mood: 'stressed' },
    stage: '{a} is at the kitchen counter, staring at the toaster.',
    turns: [['a', "I've been waiting for this toaster for ages and nothing's happening."], ['b', "How long?"],
      ['a', "Ten minutes. Maybe more."], ['b', "Is it plugged in?"], ['a', "…Don't."]],
    beat: '{b} reaches over and plugs it in.' },
  { id: 'comedy.23',
    stage: '{a} holds an empty milk bottle up to {b}.',
    turns: [['a', "Who keeps putting the empty milk back in the fridge? That's the third time today!"], ['b', "It wasn't me."],
      ['a', "You're the only one who has milk in their tea."], ['b', "…It might have been me."]] },
  { id: 'comedy.24',
    stage: '{a} is making up a song about everyone in the villa.',
    turns: [['a', "And then there's the one who's always in the gym…"], ['b', "Do me next."],
      ['a', "I'm getting to you."], ['b', "Is it nice?"], ['a', "It rhymes. That's all I'm promising."]],
    beat: 'Everyone waits to hear their own verse.' },
];
