// comedy — somebody makes the villa laugh. Cast: [a] ALONE: no {b}, no {c}.
// The room answers in the staging and the beat, never by name.
//
// The joke is the SITUATION, said plainly — a jar that won't open, a song in
// the shower — never a line built to be clever. The beat says what happened
// next; it is not a second punchline.
export const COMEDY = [
  { id: 'comedy.01',
    stage: '{a} has been trying to open a jar for about five minutes.',
    turns: [['a', "Nobody help me. I've got this."], ['a', '…Can someone help me?']],
    beat: 'Somebody takes the jar and opens it first go.' },
  { id: 'comedy.02', when: { phase: 'morning' },
    stage: '{a} is singing in the shower, loud enough for the whole villa to hear.',
    turns: [['a', "I know you can all hear me! I'm not stopping!"]],
    beat: 'A few of them start singing along from the kitchen.' },
  { id: 'comedy.03',
    stage: '{a} comes out into the garden, hopping.',
    turns: [['a', "Has anyone seen my other flip-flop? I've been walking round in one all morning."]],
    beat: 'It turns up on the roof of the hideaway, and nobody will say how.' },
  { id: 'comedy.04',
    stage: '{a} does an impression of the text alarm.',
    turns: [['a', 'Beep beep! Islanders, somebody has eaten the last yoghurt!']],
    beat: 'Half the villa jumps before they realise it was {a}.' },
  { id: 'comedy.05',
    stage: '{a} is carrying a tray of drinks along the edge of the pool.',
    turns: [['a', "Don't watch me. Don't watch me. Don't—"]],
    beat: '{a} and the drinks end up in the pool.' },
  { id: 'comedy.06',
    stage: 'Somebody asks {a} what {a.posAdj} type is.',
    turns: [['a', 'Honestly? Anyone who makes me a cup of tea without me having to ask.']] },
  { id: 'comedy.07', when: { phase: ['day', 'evening'] },
    stage: '{a} is at the stove with three other islanders.',
    turns: [['a', 'Why does it take four of us to make one pot of pasta?']],
    beat: 'Three people are stirring it at once.' },
  { id: 'comedy.08',
    stage: 'The text alarm goes off, and everyone jumps.',
    turns: [['a', "I'm never getting used to that. Every single time, I nearly have a heart attack."]] },
  { id: 'comedy.09',
    stage: '{a} has put on three pairs of sunglasses at once.',
    turns: [['a', "Can anyone see me? Because I can't see anything."]],
    beat: '{a} walks into a sunbed.' },
  { id: 'comedy.10',
    stage: '{a} is doing impressions of the islanders, one at a time.',
    turns: [['a', 'Who\'s this? "Can I pull you for a chat?"']],
    beat: 'Everyone shouts the same name at once.' },
  { id: 'comedy.11', when: { phase: ['day', 'evening'] },
    stage: '{a} has been put in charge of the barbecue.',
    turns: [['a', "It's not burnt. It's just a bit well done."]],
    beat: 'The burgers are black on both sides.' },
  { id: 'comedy.12', when: { late: true },
    stage: '{a} is lying on a sunbed, talking to whoever is nearest.',
    turns: [['a', "I've been in here so long I've forgotten what it's like to wear shoes."]] },
  { id: 'comedy.13',
    stage: 'At breakfast, {a} says it to the whole table.',
    turns: [['a', 'Does anyone else feel like this is the longest job interview of their life?']],
    beat: 'The whole kitchen agrees.' },
  { id: 'comedy.14', when: { early: true },
    stage: 'Round the fire pit, {a} is telling the others.',
    turns: [['a', "I've been asked what my star sign is about eleven times already. I've given a different one every time."]] },
  { id: 'comedy.15',
    stage: '{a} is trying to drink through three straws at once.',
    turns: [['a', "I've started now, so I'm finishing."]] },
  { id: 'comedy.16',
    stage: '{a} is blowing up a giant inflatable swan by mouth.',
    turns: [['a', "I can't feel my face."]],
    beat: 'The swan is about a quarter full.' },
  { id: 'comedy.17',
    stage: '{a} has made a sign for the bathroom door out of a cereal box.',
    turns: [['a', 'It says "occupied" on one side and "do not disturb, crying" on the other.']],
    beat: 'It stays on the door for the rest of the week.' },
  { id: 'comedy.18', when: { persona: 'villa-clown' },
    stage: '{a} announces it to everyone in the kitchen.',
    turns: [['a', 'If nobody gets a text today, I\'m going to shout "I\'ve got a text!" and see who comes running.']],
    beat: '{a} does it, and four people run in from the garden.' },
  { id: 'comedy.19', when: { phase: 'event' },
    stage: 'During the challenge, {a} slips on the foam and goes down slowly.',
    turns: [['a', "I'm fine! I meant to do that!"]] },
  { id: 'comedy.20',
    stage: 'At lunch, {a} stands up to make an announcement.',
    turns: [['a', "I made the tea this morning, and I have to be honest, it was terrible. I'm sorry, everyone."]],
    beat: 'Somebody pours theirs into a plant pot.' },
  { id: 'comedy.21',
    stage: '{a} is teaching a dance nobody asked to learn.',
    turns: [['a', 'Five, six, seven, eight. No, the other way. Your other left!']],
    beat: 'By the end, most of them are doing it, badly.' },
  { id: 'comedy.22', when: { mood: 'stressed' },
    stage: '{a} is at the kitchen counter, staring at the toaster.',
    turns: [['a', "I've been waiting for this toaster for ages and nothing's happening."]],
    beat: 'Somebody reaches over and plugs it in.' },
  { id: 'comedy.23',
    stage: '{a} holds an empty milk bottle up to the whole kitchen.',
    turns: [['a', 'Who keeps putting the empty milk back in the fridge? That\'s the third time today!']],
    beat: 'Nobody owns up.' },
  { id: 'comedy.24',
    stage: '{a} is making up a song about everyone in the villa.',
    turns: [['a', "And then there's the one who's always in the gym…"]],
    beat: 'Everyone waits to hear their own verse.' },
];
