// comedy — somebody makes the villa laugh. Cast: [a] ALONE: no {b}, no {c}.
// The room answers in the staging and the beat, never by name.
export const COMEDY = [
  { id: 'comedy.01',
    turns: [['a', "Quick announcement. Whoever keeps putting the empty milk back in the fridge: I know it's you, and so does God."]],
    beat: 'Three people look at the floor.' },
  { id: 'comedy.02', when: { phase: 'morning' },
    stage: '{a} walks out to breakfast wearing every pair of sunglasses in the dressing room.',
    turns: [['a', "Don't talk to me. I'm in my mysterious era."]],
    beat: 'It lasts until {a} walks into the kitchen door.' },
  { id: 'comedy.03',
    turns: [
      ['a', "Right, I've worked it out. If you put the lads in order of how long they take to get ready, it's the exact opposite of how long they spend in the gym."],
      ['a', "Nobody check. I'm right."],
    ] },
  { id: 'comedy.04',
    stage: '{a} is narrating the workout on the lawn in a whisper.',
    turns: [['a', 'And here we see the male, attempting a press-up. He believes he is being watched. He is correct.']],
    beat: 'The whole lawn is laughing, including the man doing the press-up.' },
  { id: 'comedy.05',
    turns: [['a', "I'd like to thank the villa for the award of Best Snorer. I didn't do it alone. Bed four, this is yours too."]],
    beat: 'Somebody throws a pillow from bed four.' },
  { id: 'comedy.06',
    stage: 'Somebody asks {a} what {a.posAdj} type is.',
    turns: [['a', "Honestly? Anyone who can open a jar. The bar is on the floor."]] },
  { id: 'comedy.07',
    turns: [
      ['a', "Can we talk about the fact that there are forty cushions on this sofa and none of them are for sitting on?"],
      ['a', "They're decorative. We live with decorative cushions. This is how it ends."],
    ] },
  { id: 'comedy.08',
    stage: 'The text alarm goes off, and everyone jumps.',
    turns: [['a', "Every time. Every single time. I'm going to go home with a heart condition."]] },
  { id: 'comedy.09',
    turns: [['a', "I've been doing the maths. There are more flamingos in this villa than there are people with a plan."]],
    beat: 'Nobody can argue with it.' },
  { id: 'comedy.10',
    stage: "{a} is doing an impression of the villa's morning routine, one islander at a time.",
    turns: [['a', "And then someone says \"I'm not even going to get involved\", and then gets involved for two hours."]],
    beat: 'Everyone laughs, and everyone looks at the same person.' },
  { id: 'comedy.11',
    turns: [['a', "The pool is not a personality. I'm saying it for some of you."]],
    beat: 'Someone in the pool splashes {a.obj}.' },
  { id: 'comedy.12', when: { phase: ['day', 'evening'] },
    stage: '{a} has been put in charge of the barbecue.',
    turns: [['a', "It's not burnt. It's well done. There's a difference and I will die on this hill."]],
    beat: 'The sausages are burnt.' },
  { id: 'comedy.13', when: { late: true },
    turns: [['a', "I've been in this villa so long I've started talking to the fridge. And the worst bit is it's the best chat I've had all week."]] },
  { id: 'comedy.14',
    turns: [['a', "Does anyone else feel like they're in a very hot, very long job interview where the job is kissing?"]],
    beat: 'The whole kitchen agrees.' },
  { id: 'comedy.15', when: { early: true },
    turns: [['a', "I've been here two days and I've already been asked what my star sign is eleven times. I've given eleven different answers."]] },
  { id: 'comedy.16',
    stage: '{a} is trying to take a sip of a drink through three straws at once.',
    turns: [['a', 'This was a mistake, and I am seeing it through.']] },
  { id: 'comedy.17',
    turns: [['a', "Every time someone says \"can I pull you for a chat\", someone in the villa loses a year off their life. Please think of the elderly. Me. I'm the elderly."]] },
  { id: 'comedy.18',
    stage: "{a} has made a sign for the bathroom door out of a cereal box.",
    turns: [['a', "It says \"occupied\" on one side and \"crying\" on the other. You're welcome."]],
    beat: 'It stays up for the rest of the series.' },
  { id: 'comedy.19', when: { persona: 'villa-clown' },
    turns: [['a', "If I don't get a text today, I'm going to text myself. I'll just shout \"I've got a text!\" and see what happens."]],
    beat: '{a} does, and four people run in from the garden.' },
  { id: 'comedy.20',
    turns: [['a', "Can we agree, as a villa, that nobody is allowed to say \"it is what it is\" today? I think we've worn it out."]],
    beat: 'Somebody says it within the hour.' },
  { id: 'comedy.21', when: { phase: 'event' },
    stage: 'During the challenge, {a} slips on the foam and goes down in slow motion.',
    turns: [['a', "I meant that. That was choreography."]] },
  { id: 'comedy.22',
    turns: [['a', "I'd like to apologise to the person who made the tea this morning. I said it was lovely. It was not lovely. It was brown water."]] },
  { id: 'comedy.23',
    stage: '{a} is teaching the villa a dance nobody asked to learn.',
    turns: [['a', "Five, six, seven, eight — no, the other left. Your other left. You've got two lefts."]],
    beat: 'By the end, everyone is doing it, badly.' },
  { id: 'comedy.24', when: { mood: 'stressed' },
    turns: [['a', "I'm fine. I'm totally fine. I've just been staring at this toaster for four minutes and it hasn't done anything."]],
    beat: 'Somebody unplugs it and plugs it back in, and it works.' },
];
