// deep-chat — a couple opening up. Cast: [a, b], coupled together.
// The past stays vague ("the last time", "my last relationship") so a line
// never contradicts the cast setup's history.
export const DEEP_CHAT = [
  { id: 'deep-chat.01',
    turns: [
      ['a', "Can I tell you something I haven't told anyone in here?"],
      ['b', 'Of course.'],
      ['a', 'The last time I let someone in, it went really badly. So if I go quiet sometimes, that\'s why.'],
      { by: 'b', vary: [
        { turns: [['b', "Thank you for telling me. I'm not going to rush you."]],
          beat: '{a} lets out a breath, and leans against {b.obj}.' },
        { when: { attachment: 'anxious' },
          turns: [['b', "Okay. Just tell me when it's that, so I don't think it's me."], ['a', 'Deal.']] },
        { when: { persona: 'villa-clown' },
          turns: [['b', "I'm not going to make a joke about that."], ['a', "You can if you want."], ['b', "No. Not this one."]],
          beat: '{b} takes {a.posAdj} hand.' },
      ] },
    ] },
  { id: 'deep-chat.02', when: { intent: ['love', 'settle-down'] },
    turns: [
      ['a', "I didn't come in here for a laugh. I know some people did."],
      ['b', 'What did you come in for?'],
      ['a', "Someone to go home with. Someone I'm still with in a year."],
      ['b', "That's a lot to say out loud."],
      ['a', "I know. I'm saying it anyway."],
    ] },
  { id: 'deep-chat.03',
    turns: [
      ['a', 'This feels different. I know everyone says that.'],
      ['b', 'Everyone does say that.'],
      ['a', "I've never said it before, though."],
    ],
    beat: '{b} looks at {a.obj} properly for a long moment.' },
  { id: 'deep-chat.04', when: { attachment: 'avoidant' },
    turns: [
      ['a', "I'm not very good at this. The feelings bit."],
      ['b', 'You seem alright at it.'],
      ['a', "That's because I'm trying really hard right now."],
      ['b', "Then keep trying. I'll tell you if you get it wrong."],
    ] },
  { id: 'deep-chat.05', when: { attachment: 'anxious' },
    turns: [
      ['a', "Can you tell me if something changes? Before it changes. Not after."],
      { by: 'b', vary: [
        { turns: [['b', "{~Yeah}. I'll tell you. I promise."], ['a', 'Even if it\'s bad?'], ['b', "Especially if it's bad."]] },
        { when: { attachment: 'avoidant' },
          turns: [['b', "I'll try. I'm not great at knowing myself till it's happened."]],
          beat: "{a} nods, and doesn't say anything for a while." },
      ] },
    ] },
  { id: 'deep-chat.06', when: { intent: 'first-love' },
    turns: [
      ['a', "I've never actually been in love. Is that weird?"],
      ['b', "It's not weird."],
      ['a', "Everyone in here talks about their exes like they're war stories. I haven't got any."],
      ['b', "Then you get to find out what it's like without anyone ruining it first."],
    ] },
  { id: 'deep-chat.07', when: { intent: 'fresh-start' },
    turns: [
      ['a', "I came in here to start again. I was a different person before."],
      ['b', 'Different how?'],
      ['a', "Harder. I didn't let anyone see anything."],
      ['b', "Well, I can see you now. For what it's worth."],
    ] },
  { id: 'deep-chat.08',
    turns: [
      ['a', 'What scares you? In here, I mean.'],
      ['b', 'That I like you more than you like me.'],
      ['a', 'You don\'t.'],
      ['b', 'You don\'t know that.'],
      ['a', 'I do. Trust me.'],
    ] },
  { id: 'deep-chat.09',
    turns: [
      ['a', "Do you ever think about what people will say when they watch this back?"],
      ['b', 'Sometimes. Mostly I try not to.'],
      ['a', "I just hope I come across like me."],
      ['b', 'You do. That\'s the thing I like.'],
    ] },
  { id: 'deep-chat.10', when: { rung: ['exclusive', 'official'] },
    turns: [
      ['a', "I want you to meet my family."],
      ['b', "{~Yeah}?"],
      ['a', "I've never said that to anyone this early."],
      ['b', "I'd like that. I'll be terrified, but I'd like that."],
    ] },
  { id: 'deep-chat.11', when: { gap: true },
    turns: [
      ['a', "I need to know if I'm on my own with this."],
      { by: 'b', vary: [
        { turns: [['b', "You're not on your own."], ['a', 'Then why does it feel like it sometimes?'],
          ['b', "Because I'm slower than you. That's all. I'm getting there."]] },
        { when: { attachment: 'avoidant' },
          turns: [['b', "I don't know what you want me to say."], ['a', 'The truth.'], ['b', "The truth is I don't know yet."]],
          beat: '{a} nods, and goes inside first.' },
        { when: { faking: true },
          turns: [['b', "You're not on your own. Honestly."]],
          beat: "{b} holds {a.posAdj} hand, and looks over {a.posAdj} shoulder at the villa." },
      ] },
    ] },
  { id: 'deep-chat.12',
    turns: [
      ['a', "I'm not good at being looked after. I'm the one who looks after people."],
      ['b', 'Then let me do it for once.'],
      ['a', "I don't know how."],
      ['b', 'You sit there, and I bring you a tea. It\'s not hard.'],
    ] },
  { id: 'deep-chat.13', when: { mood: 'guilty' },
    turns: [
      ['a', "Do you think people can change? Like, actually change?"],
      ['b', 'Why?'],
      ['a', "No reason. I just want to be better. For you."],
      ['b', "You're already fine for me."],
    ],
    beat: "{a} looks away first." },
  { id: 'deep-chat.14',
    turns: [
      ['a', "What does a good relationship look like to you?"],
      ['b', 'Boring, honestly. Nobody has to guess.'],
      ['a', 'Boring?'],
      ['b', 'I mean safe. Knowing where I stand, every day.'],
    ] },
  { id: 'deep-chat.15', when: { persona: 'hopeless-romantic' },
    turns: [
      ['a', 'I always fall too fast. Everyone at home says it.'],
      ['b', 'Are you falling now?'],
      ['a', "I'm trying really hard not to."],
      { by: 'b', vary: [
        { turns: [['b', "Don't try too hard, then."]], beat: '{a} laughs, and it sounds relieved.' },
        { when: { attachment: 'avoidant' },
          turns: [['b', "Maybe keep trying a bit longer. For both of us."]],
          beat: "{a} smiles, but lets go of {b.posAdj} hand." },
      ] },
    ] },
  { id: 'deep-chat.16', when: { persona: 'game-player' },
    turns: [
      ['a', "I know people in here think I'm playing a game."],
      ['b', 'Are you?'],
      ['a', 'With everyone else, maybe. Not with you.'],
      { by: 'b', vary: [
        { turns: [['b', "I'd like to believe that."], ['a', 'Then believe it.']] },
        { when: { persona: 'checklist' },
          turns: [['b', "That's exactly what someone playing a game would say."], ['a', "I know. I'm saying it anyway."]] },
      ] },
    ] },
  { id: 'deep-chat.17',
    turns: [
      ['a', "I watched you with everyone at dinner. You look after all of them."],
      ['b', 'Do I?'],
      ['a', "You do. Who looks after you?"],
    ],
    beat: "{b} doesn't have an answer, and {a} moves closer." },
  { id: 'deep-chat.18', when: { mood: 'heartbroken' },
    turns: [
      ['a', "I'm scared to do this again. I've only just stopped hurting."],
      ['b', "We can go slow."],
      ['a', "What if slow's not enough?"],
      ['b', "Then we go slower."],
    ] },
  { id: 'deep-chat.19',
    turns: [
      ['a', "Can I be honest about something small?"],
      ['b', 'Always.'],
      ['a', "When you go off with the others, even for an hour, I miss you."],
      ['b', "That's not small."],
    ] },
  { id: 'deep-chat.20', when: { rung: 'official' },
    turns: [
      ['a', "I don't want this to end when we leave."],
      ['b', "It won't."],
      ['a', "People always say that in here."],
      ['b', "I'm not people. I'm me, and I'm saying it."],
    ] },
  { id: 'deep-chat.21',
    turns: [
      ['a', "I don't think I've ever been this honest with anyone."],
      ['b', "Why now?"],
      ['a', "There's nothing to hide behind in here. No phone, nothing. Just us."],
    ] },
  { id: 'deep-chat.22', when: { persona: 'checklist' },
    turns: [
      ['a', "I came in with a list, you know. What I wanted."],
      ['b', 'How am I doing?'],
      ['a', "You're not on it. Hardly any of it."],
      ['b', "…Okay."],
      ['a', "And I don't care. That's the scary bit."],
    ] },
  { id: 'deep-chat.23', when: { intent: ['fun', 'fame', 'win', 'money', 'stir'] },
    turns: [
      ['a', "I'll be honest. I didn't come in here looking for anything serious."],
      { by: 'b', vary: [
        { turns: [['b', 'And now?'], ['a', 'Now I keep ending up on this daybed with you.']] },
        { when: { attachment: 'anxious' },
          turns: [['b', "…Why are you telling me that?"], ['a', "Because it's not true anymore, and I wanted you to know the difference."]] },
      ] },
    ] },
  { id: 'deep-chat.24', when: { phase: 'evening' },
    turns: [
      ['a', "What's the kindest thing anyone's ever done for you?"],
      ['b', "That's a big question."],
      ['a', 'Take your time.'],
    ],
    beat: 'They talk until the lights go off.' },
  { id: 'deep-chat.25', when: { attachment: 'secure' },
    turns: [
      ['a', "I'm not going to play games with you. I just want you to know that."],
      ['b', "I didn't think you would."],
      ['a', "Good. If I'm upset, I'll say. If I'm happy, I'll say."],
      ['b', "And right now?"],
      ['a', 'Right now I\'m happy.'],
    ] },
  { id: 'deep-chat.26', when: { late: true },
    turns: [
      ['a', "I've learned more about myself in here than in the last few years."],
      ['b', 'Like what?'],
      ['a', "That I'm allowed to want things. And say them."],
    ] },
  { id: 'deep-chat.27',
    turns: [
      ['a', "I get jealous. I'd rather tell you now than have you find out."],
      { by: 'b', vary: [
        { turns: [['b', "Thanks for telling me. Just talk to me when it happens."], ['a', 'I will.']] },
        { when: { attachment: 'avoidant' },
          turns: [['b', "I need space sometimes. That's not the same as going off with someone."], ['a', "I know. I'm going to have to learn that."]] },
      ] },
    ] },
  { id: 'deep-chat.28', when: { bombshell: true },
    turns: [
      ['a', "I know I walked in and turned everything upside down."],
      ['b', 'You did a bit.'],
      ['a', "Do you regret it?"],
      ['b', 'No. That\'s the problem.'],
    ] },
  { id: 'deep-chat.29',
    turns: [
      ['a', "Tell me about home. Not the facts. What it feels like."],
      ['b', "Loud. Busy. Everyone in everyone's business."],
      ['a', 'So, a bit like the villa.'],
      ['b', 'A bit. But at home I can go to my room and shut the door.'],
    ] },
  { id: 'deep-chat.30', when: { mood: 'lonely' },
    turns: [
      ['a', "Sometimes I'm in a room full of people in here and I still feel on my own."],
      ['b', 'Even with me?'],
      ['a', "Not with you. That's why I keep finding you."],
    ] },
];
