// friendship — two islanders who are not a couple. Cast: [a, b], any genders.
// "The girls" / "the lads" only behind a gender condition from the roster.
export const FRIENDSHIP = [
  { id: 'friendship.01', when: { phase: ['morning', 'day'] },
    turns: [
      ['a', "You've been quiet all morning."],
      ['b', "I'm fine."],
      ['a', 'You said "I\'m fine" to the toaster. I heard you.'],
      ['b', "…It's the recoupling. I don't know where I stand."],
      ['a', "Then we'll work it out. Sit down, I'm doing your eggs."],
    ],
    beat: '{b} sits down and eats.' },
  { id: 'friendship.02', when: { phase: 'morning' },
    stage: '{a} and {b} are the only two up.',
    turns: [
      ['a', 'Why are you awake?'],
      ['b', 'Somebody in our room snores like a boiler. Why are you awake?'],
      ['a', "Same somebody."],
    ],
    beat: 'They make a pot of tea and drink all of it before anyone else gets up.' },
  { id: 'friendship.03', when: { gender: 'f', bGender: 'f' },
    turns: [
      ['a', 'Sit still. I\'m nearly done.'],
      ['b', "You said that ten minutes ago."],
      ['a', "Do you want good plaits or fast plaits?"],
      ['b', 'Good plaits.'],
      ['a', 'Then sit still.'],
    ] },
  { id: 'friendship.04', when: { gender: 'm', bGender: 'm' },
    stage: '{a} and {b} are at the weights.',
    turns: [
      ['a', "Go on. Two more."],
      ['b', "I can't do two more."],
      ['a', "You can. Everyone's watching."],
      ['b', "Nobody's watching."],
      ['a', "I'm watching. Two more."],
    ],
    beat: '{b} does one, and {a} counts it as two.' },
  { id: 'friendship.05',
    turns: [
      ['a', 'Can I say something? As your mate?'],
      ['b', 'That always ends well.'],
      ['a', "You're allowed to want more than you're getting. That's all."],
      { by: 'b', vary: [
        { turns: [['b', "…Yeah. I know."]], beat: '{a} leaves it there, and puts the kettle on.' },
        { when: { attachment: 'avoidant' },
          turns: [['b', "I'm fine with what I'm getting."], ['a', 'Okay.'], ['b', "I am."]],
          beat: '{a} nods, and puts the kettle on.' },
        { when: { persona: 'hopeless-romantic' },
          turns: [['b', "I know. I just keep hoping it's about to turn into more."]],
          beat: '{a} gives {b.obj} a hug that lasts longer than either of them planned.' },
      ] },
    ] },
  { id: 'friendship.06',
    turns: [
      ['a', "Right. I'm cooking tonight."],
      ['b', 'Last time you cooked, the smoke alarm went off.'],
      ['a', "That was a learning experience."],
      ['b', "I'll help. I'm doing the knife bit, though."],
    ],
    beat: 'The smoke alarm stays quiet, just about.' },
  { id: 'friendship.07', when: { persona: 'villa-clown' },
    turns: [
      ['a', "I've made a decision. Today I'm going to be mysterious."],
      ['b', 'You?'],
      ['a', "Me. Short answers. Long looks. Nobody knows what I'm thinking."],
      ['b', 'Everyone always knows what you\'re thinking. You say it out loud.'],
      ['a', 'Not today.'],
    ],
    beat: '{a} lasts about four minutes.' },
  { id: 'friendship.08',
    turns: [
      ['a', "You're my favourite person in here that I'm not kissing."],
      ['b', "That's the nicest weird thing anyone's ever said to me."],
      ['a', 'I mean it.'],
      ['b', 'I know you do. Same.'],
    ] },
  { id: 'friendship.09', when: { mood: 'heartbroken' },
    turns: [
      ['a', "I don't want to talk about it."],
      ['b', "Then we won't."],
      ['a', '…Can you just sit here, though?'],
      ['b', "I'm not going anywhere."],
    ],
    beat: '{b} stays until {a} falls asleep on the daybed.' },
  { id: 'friendship.10',
    turns: [
      ['a', 'Who in here would you trust with a secret? Really trust.'],
      ['b', 'You. Maybe one other person.'],
      ['a', 'Who?'],
      ['b', "That's the secret."],
    ] },
  { id: 'friendship.11',
    turns: [
      ['a', "What's the worst thing you've ever done on a first date?"],
      ['b', "Fell asleep in the cinema. Snored. They moved seats."],
      ['a', 'They moved seats?'],
      ['b', "One row forward. We didn't have a second date."],
    ],
    beat: '{a} laughs so hard that someone comes out to see what happened.' },
  { id: 'friendship.12',
    turns: [
      ['a', "I'm glad you're here. I don't know if I've said that."],
      ['b', "You haven't. Say it again, I didn't hear you."],
      ['a', "I'm not saying it again."],
    ],
    beat: '{b} makes {a.obj} say it again anyway.' },
  { id: 'friendship.13', when: { mood: 'jealous' },
    turns: [
      ['a', 'Am I being mad? Tell me if I\'m being mad.'],
      { by: 'b', vary: [
        { turns: [['b', "You're not mad. You're allowed to feel it. Just don't do anything tonight."], ['a', 'Why not tonight?'],
          ['b', 'Because tonight you\'ll shout. Tomorrow you\'ll talk.']],
          beat: '{a} goes to bed instead of going to find anyone.' },
        { when: { persona: 'messy' },
          turns: [['b', "Mad? No. If it was me I'd have gone over there already."]],
          beat: '{a} looks over at the fire pit and stands up.' },
        { when: { loyal: true },
          turns: [['b', "You're not mad. But ask before you decide what happened."]],
          beat: '{a} nods and sits back down.' },
      ] },
    ] },
  { id: 'friendship.14', when: { phase: ['morning', 'day'] },
    turns: [
      ['a', 'Pass me the suncream.'],
      ['b', "You're already red."],
      ['a', "That's why I want the suncream."],
      ['b', "That's not how it works."],
    ],
    beat: '{b} passes it over anyway.' },
  { id: 'friendship.15', when: { early: true, phase: 'morning' },
    turns: [
      ['a', "I'm so glad it's you in the next bed."],
      ['b', 'Why?'],
      ['a', "Because you don't talk in the morning. I don't talk in the morning."],
      ['b', '…'],
      ['a', 'Exactly.'],
    ] },
  { id: 'friendship.16', when: { persona: 'girls-girl' },
    turns: [
      ['a', 'If anyone in here upsets you, you tell me first.'],
      ['b', 'And then what?'],
      ['a', "And then I deal with it, and you don't have to."],
      ['b', "You'd do that?"],
      ['a', "I'd do it before breakfast."],
    ] },
  { id: 'friendship.17',
    turns: [
      ['a', 'Truth or dare?'],
      ['b', "We're not twelve."],
      ['a', 'Truth or dare?'],
      ['b', '…Truth.'],
      ['a', "Who's the best kisser in here?"],
      ['b', "I'm taking the dare."],
    ],
    beat: '{a} makes {b.obj} jump in the pool fully dressed.' },
  { id: 'friendship.18', when: { mood: 'stressed', early: false },
    turns: [
      ['a', "I can't do another recoupling. I actually can't."],
      ['b', "You can. You've done it before."],
      ['a', 'That was different. I knew where I stood.'],
      ['b', "Then let's work out where you stand now. Start from the top."],
    ],
    beat: 'They go through every couple in the villa, one by one, on the back of a magazine.' },
  { id: 'friendship.19',
    turns: [
      ['a', "Why are you smiling?"],
      ['b', "I'm not."],
      ['a', 'You are. You\'ve been smiling since breakfast.'],
      ['b', '…Okay, something happened last night. I\'m not telling you here.'],
    ],
    beat: '{a} drags {b.obj} to the dressing room to hear the rest.' },
  { id: 'friendship.20',
    turns: [
      ['a', "What do you think people at home think of me?"],
      { by: 'b', vary: [
        { turns: [['b', "They think you're funny, and they think you need to stop eating everyone's crisps."]],
          beat: '{a} puts the crisps down.' },
        { when: { persona: 'checklist' },
          turns: [['b', "Honestly? I think they're still making their minds up. Give them something."]],
          beat: '{a} thinks about that for the rest of the afternoon.' },
      ] },
    ] },
  { id: 'friendship.21', when: { persona: 'wallflower' },
    turns: [
      ['a', "Is it alright if I sit here? Everyone else is being loud."],
      ['b', 'Course it is.'],
      ['a', 'You don\'t have to talk to me.'],
      ['b', "I wasn't going to."],
    ],
    beat: "They read the same magazine and don't say a word for an hour." },
  { id: 'friendship.22',
    turns: [
      ['a', 'Dance with me.'],
      ['b', "There's no music."],
      ['a', "There's always music if you're brave enough."],
      ['b', "That doesn't mean anything."],
    ],
    beat: '{a} dances anyway, and after a while {b} joins in.' },
  { id: 'friendship.23', when: { taken: true },
    turns: [
      ['a', 'Can I ask you something about my couple?'],
      ['b', 'Go on.'],
      ['a', "Do we look happy? From the outside?"],
      { by: 'b', vary: [
        { turns: [['b', 'Yeah. You look happy.'], ['a', 'Really?'], ['b', "I wouldn't say it if I didn't think it."]] },
        { when: { persona: 'girls-girl' },
          turns: [['b', 'You look happy. Whether you actually are is a different question, and you should ask yourself that one.']],
          beat: "{a} doesn't answer straight away." },
      ] },
    ] },
  { id: 'friendship.24',
    turns: [
      ['a', "Tell me something good. I've had a rubbish day."],
      ['b', 'There are two pizzas coming tonight. I heard the producers.'],
      ['a', 'Two?'],
      ['b', "Two. I'm not saying I'll share mine."],
    ] },
  { id: 'friendship.25', when: { late: true },
    turns: [
      ['a', "You'll still talk to me outside, won't you?"],
      ['b', "I'll be sick of you by the first week."],
      ['a', 'Is that a yes?'],
      ['b', "Obviously it's a yes."],
    ] },
  { id: 'friendship.26',
    turns: [
      ['a', 'Can I borrow your top?'],
      ['b', 'Which one?'],
      ['a', 'The one you were saving.'],
      ['b', "…Fine. But if anyone kisses you in it, I'm having it back."],
    ] },
  { id: 'friendship.27', when: { bombshell: true, early: true },
    turns: [
      ['a', 'Is everyone always this friendly, or is it because I\'m new?'],
      { by: 'b', vary: [
        { turns: [['b', "It's because you're new. Enjoy it while it lasts."]] },
        { when: { persona: 'girls-girl' },
          turns: [['b', 'Everyone\'s friendly till they work out who you\'re here for. So, who are you here for?']],
          beat: '{a} laughs and changes the subject.' },
      ] },
    ] },
  { id: 'friendship.28',
    turns: [
      ['a', "You know you're allowed to be sad in front of me."],
      ['b', "I know."],
      ['a', 'Do you?'],
      ['b', '…Give me a minute.'],
    ],
    beat: '{a} gives {b.obj} a minute, and then a hug.' },
  { id: 'friendship.29',
    turns: [
      ['a', 'I just won the argument about the washing up.'],
      ['b', 'Who with?'],
      ['a', "Nobody. I just did it myself. That's how you win."],
    ] },
  { id: 'friendship.30',
    turns: [
      ['a', "Who's the worst at hiding it when they fancy someone?"],
      ['b', 'You.'],
      ['a', "I'm not hiding anything."],
      ['b', 'Exactly.'],
    ] },
  { id: 'friendship.31', when: { gender: 'm', bGender: 'm' },
    turns: [
      ['a', 'Be honest, lad. Am I overdoing it?'],
      ['b', 'With what?'],
      ['a', 'All of it. The compliments, the tea, the bringing breakfast to bed.'],
      ['b', "Mate, you brought someone a croissant with a flower in it."],
      ['a', 'Was that too much?'],
      ['b', "It was a bit much. It worked, though."],
    ] },
  { id: 'friendship.32',
    turns: [
      ['a', "I've got a rule. No crying before lunch."],
      ['b', 'What happens after lunch?'],
      ['a', "After lunch, you can cry wherever you like. I'll bring the tissues."],
    ],
    beat: '{b} writes it on the fridge in eyeliner.' },
  { id: 'friendship.33', when: { mood: 'lonely' },
    turns: [
      ['a', 'Do you ever feel like everyone else has a person except you?'],
      ['b', 'All the time.'],
      ['a', "What do you do?"],
      ['b', 'Find someone else who hasn\'t got one, and sit with them.'],
    ],
    beat: '{b} shuffles along the bench to make room.' },
  { id: 'friendship.34', when: { phase: 'morning' },
    turns: [
      ['a', "I'm going to miss this. The mornings."],
      ['b', 'What, the queue for the mirror?'],
      ['a', 'Yeah. Even that.'],
    ] },
  { id: 'friendship.35', when: { persona: 'messy' },
    turns: [
      ['a', "Don't look now, but something is definitely going on over there."],
      ['b', "Where? I'm looking."],
      ['a', "I said don't look!"],
      ['b', "You can't say that and expect me not to look."],
    ],
    beat: 'They both look.' },
  { id: 'friendship.36',
    turns: [
      ['a', 'Thanks for yesterday.'],
      ['b', "What did I do?"],
      ['a', 'You sat with me. You didn\'t try to fix it.'],
      ['b', "Yeah, well. It didn't need fixing. You just needed someone there."],
    ] },
];
