// friendship, part two — the talk friends actually have in a villa: the
// debrief on each other's couples, getting ready, the lads' chat at the fire
// pit, the girls' chat on the terrace, rating the new arrival, the nerves
// before a recoupling, a party night. Cast: [a, b], not a couple.
// {pa} is a's partner and {pb} is b's; each only behind `taken` / `bTaken`.
export const FRIEND_TALK = [
  { id: 'friendship.37', when: { taken: true },
    stage: 'The daybeds, after lunch.',
    turns: [
      ['b', 'So. You and {pa}. Tell me everything.'],
      { by: 'a', vary: [
        { turns: [['a', "There's not much to tell. It's nice. It's easy."], ['b', 'Nice and easy is good.'],
          ['a', "Is it, though? I keep waiting for the sparks."]] },
        { when: { myRung: 'official' },
          turns: [['a', 'Honestly? I think {pa} might be it.'], ['b', 'Stop.'], ['a', "I'm serious."]],
          beat: '{b} screams into a cushion.' },
        { when: { attachment: 'anxious' },
          turns: [['a', "I think I like {pa} more than {pa} likes me."], ['b', "Why would you think that?"], ['a', "Because I always do."]] },
      ] },
    ] },
  { id: 'friendship.38', when: { bTaken: true },
    turns: [
      ['a', 'Has {pb} said anything yet? About being exclusive?'],
      { by: 'b', vary: [
        { turns: [['b', "Not yet. I'm not going to push it."], ['a', "You're allowed to push it a little bit."]] },
        { when: { myRung: 'official' },
          turns: [['b', "We're official. Where have you been?"], ['a', 'Since when?'], ['b', 'Since yesterday!']],
          beat: '{a} hits {b.obj} with a pillow for not saying.' },
        { when: { attachment: 'anxious' },
          turns: [['b', "No. And every day it doesn't come up, I get a bit more worried."]],
          beat: '{a} puts an arm round {b.obj}.' },
      ] },
    ] },
  { id: 'friendship.39', when: { gender: 'f', bGender: 'f', phase: 'evening' },
    stage: 'The dressing room, twenty minutes before the fire pit.',
    turns: [
      ['a', 'Zip me up?'],
      ['b', 'Who are you getting this dressed up for?'],
      ['a', 'Myself.'],
      ['b', 'And?'],
      ['a', 'And whoever happens to be looking.'],
    ] },
  { id: 'friendship.40', when: { gender: 'm', bGender: 'm' },
    stage: 'Round the fire pit, just the boys.',
    turns: [
      ['a', 'Have you made a move on anyone yet?'],
      { by: 'b', vary: [
        { turns: [['b', 'Not yet. Waiting for the right one to walk through that door.'], ['a', 'You said that last week.'],
          ['b', "And I meant it last week."]] },
        { when: { taken: true },
          turns: [['b', "{~Mate}, I'm with {pb}. I'm not making a move on anyone."], ['a', 'Just checking.']] },
        { when: { taken: true, persona: 'fuckboy' },
          turns: [['b', 'Define "a move".'], ['a', 'You know what I mean.'], ['b', "Then no. Mostly."]] },
      ] },
    ] },
  { id: 'friendship.41', when: { newArrival: true },
    stage: 'The new arrival has just walked in.',
    turns: [
      ['a', 'Well.'],
      ['b', 'Well.'],
      ['a', "I'm not saying anything."],
      ['b', "You don't have to. Your face is saying it."],
    ] },
  { id: 'friendship.42', when: { early: false },
    turns: [
      ['a', 'Who are you picking tonight?'],
      { by: 'b', vary: [
        { turns: [['b', "I've changed my mind three times since breakfast."], ['a', "And now?"], ['b', 'Four times.']] },
        { when: { taken: true, loyal: true },
          turns: [['b', '{pb}. Obviously. Why, who are you picking?']] },
        { when: { persona: 'game-player' },
          turns: [['b', 'Whoever keeps me in here.'], ['a', "That's not romantic."], ['b', "It's not meant to be."]] },
      ] },
    ] },
  { id: 'friendship.43', when: { phase: 'evening' },
    stage: "The music's on, and it's the first night nobody's being careful.",
    turns: [
      ['a', 'Come on. One dance.'],
      ['b', "I don't dance."],
      ['a', 'Everyone dances after the second drink.'],
      ['b', "I've had one."],
      ['a', 'Then half a dance.'],
    ],
    beat: '{b} ends up dancing for the rest of the song.' },
  { id: 'friendship.44', when: { taken: true },
    turns: [
      ['a', "Can I ask your opinion on something? It's about {pa}."],
      ['b', 'Go on.'],
      ['a', 'Do you think {pa} is actually into me? Be honest.'],
      { by: 'b', vary: [
        { turns: [['b', "Yeah, I do. I think you'd see it if you stopped overthinking."]], beat: '{a} laughs, and looks a bit lighter.' },
        { when: { persona: 'checklist' },
          turns: [['b', "Honestly? I think {pa} is into being in a couple. I'm not sure it's you yet."]],
          beat: "{a} doesn't say anything for a minute." },
        { when: { persona: 'girls-girl' },
          turns: [['b', "If {pa} isn't, {pa} is an idiot, and I'll be telling {pa} that myself."]] },
      ] },
    ] },
  { id: 'friendship.45',
    turns: [
      ['a', "What's the first thing you're eating when you get out?"],
      ['b', 'A roast dinner. The full thing.'],
      ['a', 'In the middle of summer?'],
      ['b', 'In the middle of summer. With gravy.'],
    ] },
  { id: 'friendship.46',
    turns: [
      ['a', 'Which couple do you think is actually going to last?'],
      ['b', 'Not the ones who kiss the most.'],
      ['a', "That's… a lot of the couples in here."],
      ['b', 'I know.'],
    ] },
  { id: 'friendship.47', when: { gender: 'f', bGender: 'f', phase: 'evening' },
    stage: "The terrace. The girls' chat, a blanket each.",
    turns: [
      ['a', 'Okay. Everyone has to say one thing they\'re worried about.'],
      ['b', 'You first.'],
      ['a', "That I've got to the point where I actually care."],
    ],
    beat: 'Nobody laughs. {b} reaches over and holds {a.posAdj} hand.' },
  { id: 'friendship.48', when: { gender: 'm', bGender: 'm', taken: true },
    stage: 'Late, by the fire pit, just the boys.',
    turns: [
      ['a', "Can I say something and you won't laugh?"],
      ['b', 'No promises.'],
      ['a', "I think I'm really falling for {pa}."],
      { by: 'b', vary: [
        { turns: [['b', "I'm not laughing. I'm {~buzzing} for you."]], beat: '{b} pulls {a} in for a hug.' },
        { when: { persona: 'villa-clown' },
          turns: [['b', "I'm laughing a bit. But I'm {~buzzing} for you."]], beat: '{b} pulls {a} in for a hug anyway.' },
      ] },
    ] },
  { id: 'friendship.49', when: { bTaken: true, phase: 'morning' },
    turns: [
      ['a', 'You and {pb} were loud last night.'],
      ['b', 'We were talking!'],
      ['a', "Is that what we're calling it?"],
    ],
    beat: '{b} throws a pillow at {a.obj}.' },
  { id: 'friendship.50', when: { taken: false },
    turns: [
      ['a', "Everyone's coupled up with someone they {~fancy}, and I'm on my own."],
      ['b', 'Not for long.'],
      ['a', 'You have to say that.'],
      ['b', "I don't have to say anything. I mean it."],
    ],
    beat: '{b} gives {a.obj} a cuddle instead.' },
  { id: 'friendship.51',
    stage: 'At the weights.',
    turns: [
      ['a', 'Spot me?'],
      ['b', "If you drop that on your face, I'm not helping."],
      ['a', "That's literally what spotting is."],
    ] },
  { id: 'friendship.52', when: { phase: 'evening' },
    turns: [
      ['a', 'You look amazing tonight.'],
      ['b', "You're only saying that because I lent you my shoes."],
      ['a', "I'm saying it because it's true. Also, the shoes."],
    ] },
  { id: 'friendship.53', when: { early: true },
    turns: [
      ['a', "I didn't think I'd make a real friend in here."],
      ['b', 'Same. I thought it would all be about the couples.'],
      ['a', "It is all about the couples. You're a bonus."],
    ] },
  { id: 'friendship.54', when: { taken: true, mood: 'jealous' },
    turns: [
      ['a', 'Did you see {pa} talking to the new one?'],
      { by: 'b', vary: [
        { turns: [['b', "It was a chat. You'd do the same."], ['a', 'I would not.'], ['b', 'You would. You do.']] },
        { when: { persona: 'girls-girl' },
          turns: [['b', "I saw. Do you want me to go and stand next to them?"]], beat: '{a} laughs for the first time all day.' },
        { when: { persona: 'messy' },
          turns: [['b', 'I saw. It went on for ages, as well.']], beat: '{a} stands up.' },
      ] },
    ] },
  { id: 'friendship.55', when: { mood: 'stressed' },
    turns: [
      ['b', 'Right. Face masks, sofa, and nobody is allowed to mention the recoupling.'],
      ['a', 'Deal.'],
    ],
    beat: 'Somebody mentions the recoupling within five minutes. {b} throws a cushion at them.' },
  { id: 'friendship.56',
    turns: [
      ['a', 'Do your impression of the text alarm.'],
      ['b', 'No.'],
      ['a', "Please. It's the only thing getting me through today."],
    ],
    beat: '{b} does it, and the whole kitchen jumps.' },
  { id: 'friendship.57', when: { late: true },
    turns: [
      ['a', "What are you going to miss most?"],
      ['b', 'You. Obviously. Then the pool.'],
      ['a', 'In that order?'],
      ['b', "Some days, yeah."],
    ] },
  { id: 'friendship.58', when: { taken: true, bTaken: true },
    turns: [
      ['a', 'Double date when we get out? Us, {pa} and {pb}.'],
      ['b', '{pb} would love that. {pb} loves you.'],
      ['a', 'Everyone loves me.'],
      ['b', 'They do, to be fair.'],
    ] },
  { id: 'friendship.59', when: { phase: ['morning', 'day'] },
    turns: [
      ['a', 'What are we making?'],
      ['b', "Whatever's left."],
      ['a', "There's three eggs and some ketchup."],
      ['b', "Then it's a ketchup omelette."],
    ] },
  { id: 'friendship.60', when: { taken: false, early: false },
    turns: [
      ['a', "If nobody picks me tonight, I'm going home."],
      ['b', 'Somebody\'s going to pick you.'],
      ['a', "You don't know that."],
      ['b', "No. But I would, if it was up to me."],
    ] },
  { id: 'friendship.61', when: { persona: 'messy' },
    turns: [
      ['a', "Have you heard what's going on with the new couple?"],
      ['b', "No, and I don't want to."],
      ['a', 'You do, though.'],
      ['b', '…I do.'],
    ] },
  { id: 'friendship.62', when: { bTaken: true },
    turns: [
      ['a', 'Is {pb} being nice to you? Really nice?'],
      { by: 'b', vary: [
        { turns: [['b', 'Yeah. Really nice.'], ['a', 'Good. Because I was ready to have a word.']] },
        { when: { attachment: 'anxious' },
          turns: [['b', 'Most of the time. I just wish {pb} said it more.'], ['a', 'Then tell {pb} that.']] },
      ] },
    ] },
  { id: 'friendship.63', when: { gender: 'f', bGender: 'f' },
    turns: [
      ['a', "If I ever start acting like I'm fine when I'm not, you tell me."],
      ['b', "You're acting like you're fine right now."],
      ['a', "…Okay, that's fair."],
    ] },
  { id: 'friendship.64', when: { gender: 'm', bGender: 'm' },
    turns: [
      ['a', "Honestly, you're the only {~lad} in here I'd actually go for {~pint} with."],
      ['b', "That's the nicest thing you've ever said to me."],
      ['a', "Don't make it weird."],
    ] },
  { id: 'friendship.65',
    turns: [
      ['a', 'Promise me something. Whatever happens in here, we stay friends.'],
      ['b', 'Obviously.'],
      ['a', 'Even if we end up fancying the same person.'],
      ['b', "…That one I'd have to think about."],
    ] },
];
