// gossip — a witness tells a partner what they saw. Cast: [a, b, c]: a saw
// it, b is c's partner, c did it. Every entry requires `knows`, so the teller
// is somebody who actually saw it (pm/script.js, knowsAbout). What a saw is
// kept to what a witness could see: c with someone else, a chat that
// wasn't just a chat. Never a detail the engine didn't record.
const K = { knows: true };
export const GOSSIP = [
  { id: 'gossip.01', when: K,
    stage: '{a} waits until the terrace is empty.',
    turns: [
      ['a', "I wasn't going to say anything, but I'd want to know if it was me."],
      ['b', 'Say what?'],
      ['a', "Earlier, on the daybeds. {c} was all over someone else, and it wasn't a chat."],
      { by: 'b', vary: [
        { turns: [['b', '{c}? You saw that?'], ['a', 'I was sat right there.']],
          beat: '{b} looks over at the pool, where {c} is laughing at something.' },
        { when: { archetype: 'hothead' },
          turns: [['b', "Where's {c}?"]], beat: '{b} is already walking.' },
        { when: { attachment: 'avoidant' },
          turns: [['b', 'Right.'], ['a', 'Are you okay?'], ['b', "Fine. Thanks for telling me."]],
          beat: "{b} goes to bed early and doesn't speak to {c} all evening." },
      ] },
    ] },
  { id: 'gossip.02', when: K,
    turns: [
      ['a', 'Can I have a word? Not here.'],
      ['b', "That's never good."],
      ['a', "It's about {c}. I saw something, and you need to hear it from me before you hear it from anyone else."],
      { by: 'b', vary: [
        { turns: [['b', '…Go on.']], beat: '{a} tells {b.obj} everything. It takes about a minute.' },
        { when: { attachment: 'anxious' },
          turns: [['b', 'I knew it. I knew something was off.'], ['a', "I'm sorry."]],
          beat: '{b} sits down on the edge of the bed and puts {b.posAdj} head in {b.posAdj} hands.' },
      ] },
    ] },
  { id: 'gossip.03', when: { ...K, persona: 'girls-girl' },
    turns: [
      ['a', "I'm telling you this because I love you, not because I want drama."],
      ['b', "What's happened?"],
      ['a', "{c} was cracking on with someone else while you were in the shower. I watched it."],
      ['b', 'How long for?'],
      ['a', 'Long enough.'],
    ],
    beat: '{a} holds {b.posAdj} hand while {b} takes it in.' },
  { id: 'gossip.04', when: { ...K, persona: 'game-player' },
    turns: [
      ['a', "I don't know if I should even say this."],
      ['b', "Then why have you brought me out here?"],
      ['a', "Because you deserve better than {c}. And after what I saw, I think you know it too."],
      { by: 'b', vary: [
        { turns: [['b', 'What did you see?']], beat: '{a} tells {b.obj}, and makes it sound slightly worse than it was.' },
        { when: { persona: 'checklist' },
          turns: [['b', "Why do you care what I deserve?"], ['a', "I just do."], ['b', 'Hm.']],
          beat: "{b} listens to all of it, and watches {a} the whole time." },
      ] },
    ] },
  { id: 'gossip.05', when: K,
    turns: [
      ['a', "Have you and {c} been alright?"],
      ['b', 'Yeah. Why?'],
      ['a', "No reason."],
      ['b', "That's not no reason. That's a reason face."],
      ['a', "…Okay. I saw something."],
    ],
    beat: '{b} sits down to hear it.' },
  { id: 'gossip.06', when: { ...K, persona: 'messy' },
    stage: 'In front of half the villa, by the kitchen.',
    turns: [
      ['a', "Are we just not going to mention what {c} was doing earlier?"],
      ['b', 'What was {c} doing?'],
      ['a', 'Oh. You don\'t know.'],
    ],
    beat: 'Everyone in the kitchen goes very quiet.' },
  { id: 'gossip.07', when: K,
    turns: [
      ['a', "I've been going back and forth about telling you."],
      ['b', "Just say it."],
      ['a', "{c} isn't being straight with you. I saw it with my own eyes."],
      { by: 'b', vary: [
        { turns: [['b', "Right. Thank you. I mean it."]], beat: '{b} gets up and goes to find {c}.' },
        { when: { loyal: true },
          turns: [['b', "No. {c} wouldn't. You've got it wrong."], ['a', "I wish I had."]],
          beat: '{b} walks off, and {a} lets {b.obj} go.' },
        { when: { mood: 'secure' },
          turns: [['b', "…Are you sure? Because I'd have bet my life on us."], ['a', "I'm sure."]],
          beat: "{b} doesn't say anything else for a long time." },
      ] },
    ] },
  { id: 'gossip.08', when: K,
    turns: [
      ['a', "You're my mate. So I'm not going to watch you get mugged off and say nothing."],
      ['b', "Who's mugging me off?"],
      ['a', '{c}.'],
    ],
    beat: "{b} laughs, and then sees {a.posAdj} face, and stops." },
  { id: 'gossip.09', when: { ...K, persona: 'wallflower' },
    turns: [
      ['a', 'Can I tell you something? I don\'t really like doing this.'],
      ['b', "You're shaking. What's wrong?"],
      ['a', "I saw {c} with someone else. I'm so sorry. I didn't know what to do."],
      ['b', "You did the right thing."],
    ] },
  { id: 'gossip.10', when: K,
    turns: [
      ['b', "Why does everyone keep looking at me like that?"],
      ['a', "Because everyone knows, and nobody wants to be the one who tells you."],
      ['b', 'Tells me what?'],
      ['a', "Then I'll be the one. It's about {c}."],
    ] },
  { id: 'gossip.11', when: { ...K, mood: 'guilty' },
    turns: [
      ['a', "I should have told you this sooner. I'm sorry I didn't."],
      ['b', 'Told me what?'],
      ['a', "{c}. With someone else. I saw it, and I sat on it, and I shouldn't have."],
      { by: 'b', vary: [
        { turns: [['b', "You let me sit next to {c.obj} all this time?"]],
          beat: "{a} doesn't have an answer." },
        { when: { attachment: 'secure' },
          turns: [['b', "Okay. You're telling me now. That's what counts."]],
          beat: '{b} squeezes {a.posAdj} arm, and goes to find {c}.' },
      ] },
    ] },
  { id: 'gossip.12', when: K,
    turns: [
      ['a', "Promise you won't shout."],
      ['b', "I can't promise that."],
      ['a', 'Then promise you won\'t shout at me.'],
      ['b', '…Fine.'],
      ['a', "{c} was kissing someone else by the pool."],
    ],
    beat: "{b} doesn't shout at {a.obj}. {b} goes looking for {c} instead." },
  { id: 'gossip.13', when: { ...K, persona: 'villa-clown' },
    turns: [
      ['a', "I'm not usually the serious one, so you know this is serious."],
      ['b', "You're scaring me."],
      ['a', "It's {c}. I saw something. No jokes this time."],
    ] },
  { id: 'gossip.14', when: K,
    turns: [
      ['b', 'Just tell me. Did {c} do something?'],
      ['a', 'Yes.'],
      ['b', 'With who?'],
      ['a', "I'm not going to drag anyone else into it. But yes."],
    ] },
  { id: 'gossip.15', when: { ...K, late: true },
    turns: [
      ['a', "We've been in here a long time, and I've never grassed on anyone. So listen to me."],
      ['b', "I'm listening."],
      ['a', "{c} isn't who you think. Not after what I saw."],
    ] },
  { id: 'gossip.16', when: K,
    turns: [
      ['a', "I've been sick about this all morning."],
      ['b', 'About what?'],
      ['a', 'About what I saw {c} doing. I think you need to talk to {c.obj}.'],
      { by: 'b', vary: [
        { turns: [['b', 'What did you see?']], beat: '{a} tells {b.obj}, quietly, in the dressing room.' },
        { when: { attachment: 'avoidant' },
          turns: [['b', "I don't want the details."], ['a', 'Okay.'], ['b', "Just tell me if it's bad."], ['a', "It's bad."]] },
      ] },
    ] },
  { id: 'gossip.17', when: { ...K, gender: 'f', bGender: 'f' },
    turns: [
      ['a', "Girl, come here. Now. Dressing room."],
      ['b', 'What? What is it?'],
      ['a', "Shut the door first."],
    ],
    beat: 'Two minutes later, {b} walks out, and goes straight to {c}.' },
  { id: 'gossip.18', when: { ...K, gender: 'm', bGender: 'm' },
    turns: [
      ['a', "Bro, I've got to tell you something, and I need you to stay calm."],
      ['b', 'Why would I not be calm?'],
      ['a', "Because it's about {c}."],
    ],
    beat: '{b} is up off the bench before {a} has finished.' },
  { id: 'gossip.19', when: K,
    turns: [
      ['a', "I don't want to be the one who ruins your couple."],
      ['b', "Then don't."],
      ['a', "I'm not. {c} already did that. I'm just the one telling you."],
    ] },
  { id: 'gossip.20', when: K,
    turns: [
      ['b', "You've been weird with me all day."],
      ['a', "Because I've been trying to work out how to tell you something about {c}."],
      ['b', "Have you worked it out?"],
      ['a', 'No. So I\'m just going to say it.'],
    ] },
  { id: 'gossip.21', when: { ...K, persona: 'hopeless-romantic' },
    turns: [
      ['a', "I really wanted you two to work. You know I did."],
      ['b', 'Why are you talking like it\'s over?'],
      ['a', "Because of what I saw {c} do."],
    ],
    beat: '{a} starts crying before {b} does.' },
  { id: 'gossip.22', when: K,
    turns: [
      ['a', 'Where were you earlier? When the lights went off?'],
      ['b', 'Asleep. Why?'],
      ['a', "Because {c} wasn't."],
    ] },
  { id: 'gossip.23', when: K,
    turns: [
      ['a', "I'd rather you hate me for telling you than find out on the telly."],
      ['b', 'Find out what?'],
      ['a', "What {c}'s been doing when you're not looking."],
    ] },
  { id: 'gossip.24', when: { ...K, persona: 'checklist' },
    turns: [
      ['a', "I'm going to give you facts, not opinions. You decide what to do."],
      ['b', 'Okay.'],
      ['a', "Earlier. The daybeds. {c}, and someone who isn't you. For about twenty minutes."],
      ['b', '…Thanks for being straight with me.'],
    ] },
];
