// kiss — a couple kiss. Cast: [a, b], coupled together. Short scenes: the
// kiss is the event, the words are what is said either side of it.
export const KISS = [
  { id: 'kiss.01', when: { early: true, rung: 'coupled', phase: 'evening' },
    stage: 'The terrace, after everyone else has gone in.',
    turns: [
      ['a', "Can I kiss you? I've wanted to all day."],
      { by: 'b', vary: [
        { turns: [['b', "You've been asking me with your eyes since lunch. Yes."]], beat: '{a} does.' },
        { when: { persona: 'wallflower' },
          turns: [['b', '…Yeah.']], beat: '{a} does, and {b} is smiling before it is over.' },
        { when: { persona: 'villa-clown' },
          turns: [['b', 'Took you long enough.']], beat: '{b} kisses {a.obj} first.' },
      ] },
    ] },
  { id: 'kiss.02',
    turns: [
      ['a', 'Come here.'],
      ['b', "I'm right here."],
      ['a', 'Closer.'],
    ],
    beat: '{b} leans in, and {a} kisses {b.obj}.' },
  { id: 'kiss.03', when: { phase: 'evening' },
    stage: 'Under the fairy lights by the fire pit.',
    turns: [
      ['b', 'Everyone can see us.'],
      ['a', 'Let them.'],
    ],
    beat: 'Somebody on the daybeds wolf-whistles, and neither of them stops.' },
  { id: 'kiss.04', when: { rung: ['exclusive', 'official'], phase: 'morning' },
    turns: [
      ['a', 'Morning.'],
      ['b', "Don't. I haven't brushed my teeth."],
      ['a', "Don't care."],
    ],
    beat: '{a} kisses {b.obj} anyway, and {b} pulls the sheet over both their heads.' },
  { id: 'kiss.05',
    stage: '{a} comes back from the kitchen with two drinks.',
    turns: [
      ['b', "What's that for?"],
      ['a', "It's a drink. It's for drinking."],
      ['b', 'No, the face. Why are you looking at me like that?'],
      ['a', 'No reason.'],
    ],
    beat: '{a} puts the drinks down, and kisses {b.obj}.' },
  { id: 'kiss.06', when: { gap: true },
    turns: [
      ['a', "You know I really like you, don't you?"],
      { by: 'b', vary: [
        { turns: [['b', "Stop talking."]], beat: '{b} kisses {a.obj} before {a} can ask anything else.' },
        { when: { attachment: 'avoidant' },
          turns: [['b', 'I know.']], beat: '{b} kisses {a.obj} quickly, and then goes to get changed.' },
      ] },
    ] },
  { id: 'kiss.07', when: { persona: 'fuckboy' },
    turns: [
      ['a', "Nobody's around."],
      ['b', 'Is that your chat-up line now?'],
      ['a', "It's not a line. It's a fact."],
    ],
    beat: '{b} rolls {b.posAdj} eyes, and kisses {a.obj} anyway.' },
  { id: 'kiss.08', when: { phase: 'evening' },
    stage: 'The pool, late.',
    turns: [
      ['b', "It's freezing."],
      ['a', 'Then come here.'],
    ],
    beat: '{b} swims over, and they kiss in the shallow end until their teeth are chattering.' },
  { id: 'kiss.09', when: { persona: 'hopeless-romantic' },
    turns: [
      ['a', "I want to remember this one."],
      ['b', 'This one?'],
      ['a', 'This exact one. Hold still.'],
    ],
    beat: '{a} kisses {b.obj} very slowly.' },
  { id: 'kiss.10',
    turns: [
      ['b', 'You taste like pineapple.'],
      ['a', "Is that good or bad?"],
      ['b', "I'm not sure yet. Again."],
    ] },
  { id: 'kiss.11', when: { mood: 'jealous' },
    stage: '{a} walks straight past the others to where {b} is sitting.',
    turns: [
      ['b', 'Hello to you too.'],
      ['a', 'Hi.'],
    ],
    beat: '{a} kisses {b.obj} in front of everyone, and holds it a second longer than usual.' },
  { id: 'kiss.12', when: { rung: 'official' },
    turns: [
      ['a', "I'm never going to get bored of this."],
      ['b', "You say that now. Wait till I've got a cold."],
      ['a', "Even then."],
    ] },
  { id: 'kiss.13', when: { phase: 'evening' },
    turns: [
      ['a', 'Goodnight.'],
      ['b', "That's the third goodnight."],
      ['a', "I'm doing it properly this time."],
    ],
    beat: '{b} kisses {a.obj} goodnight, and rolls over.' },
  { id: 'kiss.14', when: { early: true },
    turns: [
      ['b', "Was that alright?"],
      { by: 'a', vary: [
        { turns: [['a', 'That was more than alright.']], beat: '{b} grins and hides {b.posAdj} face in {a.posAdj} neck.' },
        { when: { persona: 'checklist' },
          turns: [['a', "It was good. I'll give it an eight."], ['b', 'An eight?'], ['a', "There's room to improve."]],
          beat: '{b} improves on it straight away.' },
      ] },
    ] },
  { id: 'kiss.15',
    stage: 'The dressing room, when nobody else is in there.',
    turns: [
      ['a', "We've got about thirty seconds before someone comes in."],
      ['b', "Then stop talking."],
    ],
    beat: 'Someone walks in, and they jump apart.' },
  { id: 'kiss.16', when: { mood: 'secure' },
    turns: [
      ['a', 'What was that for?'],
      ['b', 'Nothing. I just wanted to.'],
    ] },
  { id: 'kiss.17', when: { bombshell: true },
    turns: [
      ['a', 'I came in here thinking I\'d have to work for this.'],
      ['b', "Who says you're not working for it?"],
    ],
    beat: '{b} kisses {a.obj}, and then walks off before {a} can say anything.' },
  { id: 'kiss.18',
    stage: 'On the swing seat.',
    turns: [
      ['b', "If this swing breaks, I'm blaming you."],
      ['a', "It's not going to break."],
    ],
    beat: 'They kiss, and the swing creaks, and they both freeze, and then carry on.' },
  { id: 'kiss.19', when: { mood: 'stressed' },
    turns: [
      ['a', "Sorry. It's been a long day."],
      ['b', "I know. Come here."],
    ],
    beat: '{b} kisses {a.obj} on the forehead, and {a} leans into {b.obj}.' },
  { id: 'kiss.20',
    turns: [
      ['a', "You've got something on your lip."],
      ['b', 'Where?'],
      ['a', "I'll get it."],
    ],
    beat: '{a} kisses {b.obj}.' },
  { id: 'kiss.21', when: { rung: ['closed-off', 'exclusive', 'official'] },
    turns: [
      ['a', 'Do you know what I like about kissing you?'],
      ['b', 'Go on.'],
      ['a', "I don't think about anything else while I'm doing it."],
    ] },
  { id: 'kiss.22', when: { phase: 'evening' },
    turns: [
      ['b', 'The lights are going off in a minute.'],
      ['a', 'Good.'],
    ] },
  { id: 'kiss.23', when: { persona: 'villa-clown' },
    turns: [
      ['a', "On a scale of one to ten, how good was that?"],
      ['b', 'Why does everything have to have a score with you?'],
      ['a', "Because I'm winning."],
    ],
    beat: '{b} kisses {a.obj} again just to shut {a.obj} up.' },
  { id: 'kiss.24', when: { late: true },
    turns: [
      ['a', 'Do you remember our first kiss?'],
      ['b', 'You bumped my nose.'],
      ['a', "I didn't bump your nose."],
      ['b', 'You really did. This is much better.'],
    ] },
];
