// loyalty — a coupled islander turns down a pull. Cast: [a, b]: a is the
// one saying no, b is the one who asked. a's partner is not in the scene,
// so a line names them as "my partner" or "the person I'm with", never guesses.
export const LOYALTY = [
  { id: 'loyalty.01',
    turns: [
      ['b', 'Can I grab you for a chat?'],
      ['a', "If it's that kind of chat, I'll save you the walk. I'm happy where I am."],
      { by: 'b', vary: [
        { turns: [['b', 'Fair enough. Had to ask.']], beat: '{b} goes back to the daybeds.' },
        { when: { persona: 'fuckboy' },
          turns: [['b', 'For now.'], ['a', 'For good.']], beat: '{b} laughs, and walks off anyway.' },
        { when: { bombshell: true },
          turns: [['b', "I've only just got here. You haven't even given me a chance."], ['a', "I know. That's not your fault. It's still a no."]] },
      ] },
    ] },
  { id: 'loyalty.02', when: { myRung: ['closed-off', 'exclusive'] },
    turns: [
      ['b', "I think we'd be good together."],
      ['a', "Maybe in a different villa. In this one, I'm taken."],
      ['b', "You're not official."],
      ['a', "I don't need a word for it. I know what I've got."],
    ],
    beat: '{a} gets up and goes to find {a.posAdj} partner.' },
  { id: 'loyalty.03', when: { myRung: 'official' },
    turns: [
      ['b', "Can I be honest with you?"],
      ['a', "You can, but I'm going to stop you before you say it."],
      ['b', 'Why?'],
      ['a', "Because I'm official, and I'd want someone to stop them if it was the other way round."],
    ] },
  { id: 'loyalty.04',
    turns: [
      ['b', "You keep looking at me."],
      ['a', "I'm looking at the pool. You're standing in front of it."],
      ['b', 'Right.'],
      ['a', 'Right.'],
    ],
    beat: '{b} moves out of the way.' },
  { id: 'loyalty.05', when: { persona: 'hopeless-romantic' },
    turns: [
      ['b', "You're wasting yourself on them, you know."],
      ['a', "I don't think so. And if I am, it's mine to waste."],
    ],
    beat: "{a} doesn't wait for an answer." },
  { id: 'loyalty.06', when: { persona: 'girls-girl' },
    turns: [
      ['b', 'Just a chat. Five minutes.'],
      ['a', "No. And I'll be telling everyone you asked, so don't go and try it on with the others."],
    ],
    beat: '{b} holds {b.posAdj} hands up and backs off.' },
  { id: 'loyalty.07',
    turns: [
      ['b', "Can I say something without you getting weird?"],
      ['a', "Go on."],
      ['b', 'If you were single, I\'d be all over this.'],
      ['a', "Well, I'm not. So that's that."],
      ['b', "That's that."],
    ] },
  { id: 'loyalty.08', when: { loyal: true },
    turns: [
      ['b', "Nobody would know."],
      ['a', "I'd know. That's the whole point."],
    ],
    beat: '{a} walks back inside and leaves {b} on the terrace.' },
  { id: 'loyalty.09',
    turns: [
      ['b', "Everyone says your couple's on its last legs."],
      { by: 'a', vary: [
        { turns: [['a', "Everyone can mind their own business."]], beat: '{a} goes back to sunbathing.' },
        { when: { archetype: 'hothead' },
          turns: [['a', "Who's everyone? Say their names and I'll go and ask them."]],
          beat: "{b} doesn't say any names." },
        { when: { attachment: 'anxious' },
          turns: [['a', "…Who said that?"], ['b', 'Just people.'], ['a', "Then people are wrong."]],
          beat: '{a} goes to find {a.posAdj} partner straight away.' },
      ] },
    ] },
  { id: 'loyalty.10', when: { persona: 'villa-clown' },
    turns: [
      ['b', 'Fancy a chat?'],
      ['a', "I'd love to, but I'm spoken for. I'm like a parking space."],
      ['b', 'A parking space?'],
      ['a', 'Reserved. Try round the back.'],
    ] },
  { id: 'loyalty.11',
    turns: [
      ['b', "I'm not going to lie. I came in here for you."],
      ['a', "That's really flattering. Honestly. But I'm not going anywhere."],
      ['b', 'Not even a chat?'],
      ['a', "A chat's fine. As long as you know that's all it is."],
    ] },
  { id: 'loyalty.12', when: { mood: 'secure' },
    turns: [
      ['b', "Are you sure you're happy?"],
      ['a', "I've never been more sure of anything in here."],
    ],
    beat: "{a} says it without looking up from {a.posAdj} book." },
  { id: 'loyalty.13',
    turns: [
      ['b', 'Can I steal you?'],
      ['a', "I'm not a pen."],
      ['b', 'For a chat, I mean.'],
      ['a', "I know what you mean. Still no."],
    ] },
  { id: 'loyalty.14', when: { myRung: ['exclusive', 'official'] },
    turns: [
      ['b', "One kiss. That's all I'm asking."],
      ['a', "And that's all it takes to lose everything I've got. No."],
    ],
    beat: '{a} tells {a.posAdj} partner about it ten minutes later.' },
  { id: 'loyalty.15', when: { persona: 'checklist' },
    turns: [
      ['b', 'I think I tick all your boxes.'],
      ['a', "You tick most of them."],
      ['b', 'So?'],
      ['a', "So there's one you don't, and it's the one that says 'isn't trying to break up my couple'."],
    ] },
  { id: 'loyalty.16',
    turns: [
      ['b', "Just so you know, if you change your mind…"],
      ['a', "I won't."],
      ['b', 'But if you do.'],
      ['a', "I won't. Go and find someone who's looking."],
    ] },
  { id: 'loyalty.17', when: { attachment: 'avoidant' },
    turns: [
      ['b', "You seem like you need a bit of space from them."],
      ['a', "I do. From everyone. Including you."],
    ],
    beat: '{a} takes {a.posAdj} drink to the far end of the lawn.' },
  { id: 'loyalty.18',
    turns: [
      ['b', "Can we talk? It's important."],
      ['a', "Is it about us?"],
      ['b', 'Sort of.'],
      ['a', "Then there's no us. That's the whole conversation."],
    ] },
  { id: 'loyalty.19', when: { early: true },
    turns: [
      ['b', "It's early days. Nobody's settled yet."],
      ['a', "I am. I knew on the first night."],
      ['b', 'You can\'t know on the first night.'],
      ['a', 'I did, though.'],
    ] },
  { id: 'loyalty.20', when: { mood: 'guilty' },
    turns: [
      ['b', "Come for a chat. You look like you need one."],
      ['a', "I don't. Honestly. I need to go and talk to the person I'm with."],
    ],
    beat: '{a} walks off before {b} can say anything else.' },
];
