// more-a — the everyday scenes the villa has most of, a second pool each
// (user: "add a lot more variants … for all the type of event"). Measured
// before this file: friendship played 210 times a season from 77 scenes, a
// pull 177 from 40, a challenge kiss 119 from 22 — the same line three or
// four times a season. Casts follow each kind's own file (friendship.js,
// pull-more.js, chat.js, challenge.js, argument-more.js), and the friction
// is in here too: a row between friends, a pull that goes nowhere, a chat
// where something is off (user: "negative events are also part of the game").
//
// Never invent a backstory fact; plain talk; a beat says what they do next.

export const MORE_A = {
  // friendship [a, b]: two islanders who are not a couple.
  friendship: [
    { id: 'fr2.01', turns: [['a', "Do you want me to do your hair for tonight?"], ['b', "Please. I've given up on it."]], beat: '{a} gets the straighteners.' },
    { id: 'fr2.02', turns: [['a', "You were quiet at dinner."], ['b', "Just tired."], ['a', "Tired, or thinking?"], ['b', "Both."]] },
    { id: 'fr2.03', turns: [['a', "If I start getting jealous, will you tell me?"], ['b', "I'll tell you before you've even noticed."]] },
    { id: 'fr2.04', turns: [['a', "Sit with me for a bit?"], ['b', "Always."]], beat: 'They share a sunbed and say nothing for ten minutes.' },
    { id: 'fr2.05', turns: [['a', "Who's the best kisser in here, do you think?"], ['b', "I'm not answering that. There are microphones."]], beat: 'They both laugh.' },
    { id: 'fr2.06', turns: [['a', "I brought you a coffee."], ['b', "You're my favourite person in this villa."], ['a', "I know."]] },
    { id: 'fr2.07', turns: [['a', "Be honest. Am I being too much?"], ['b', "A little bit. But in a good way."]] },
    { id: 'fr2.08', turns: [['a', "Do you ever miss home?"], ['b', "Every night, around this time."], ['a', "Me too."]], beat: '{a} puts an arm round {b}.' },
    { id: 'fr2.09', turns: [['a', "Teach me that dance you did last night."], ['b', "You'll embarrass yourself."], ['a', "That's the plan."]] },
    { id: 'fr2.10', turns: [['a', "I've got your back at the next recoupling. Whatever happens."], ['b', "I know you have."]] },
    { id: 'fr2.11', turns: [['a', "What do you think of the new one?"], ['b', "Too early to say. What do you think?"], ['a', "Trouble."]] },
    { id: 'fr2.12', when: { phase: 'morning' }, turns: [['a', "I'm so glad I met you in here."], ['b', "Stop, you'll make me cry before breakfast."]] },
    { id: 'fr2.13', turns: [['a', "Can we do a workout together? I need motivating."], ['b', "I'm not motivating anyone. I'm lying down."]], beat: 'They lie down together instead.' },
    { id: 'fr2.14', turns: [['a', "You're really good at talking to people."], ['b', "I'm really good at talking. The people are a bonus."]] },
    { id: 'fr2.15', turns: [['a', "Rate the fire pit outfits from last night."], ['b', "Yours was a nine."], ['a', "Only a nine?"], ['b', "Nobody gets a ten on a Tuesday."]] },
    { id: 'fr2.16', turns: [['a', "When we get out, we're going on holiday together."], ['b', "We're literally on holiday."], ['a', "A real one. With no cameras."]] },
    { id: 'fr2.17', turns: [['a', "Are you okay? You've been off with me today."], ['b', "I'm fine. Honestly. It's not you."]], beat: '{a} is not completely convinced.' },
    { id: 'fr2.18', turns: [['a', "You told everyone what I said about my couple."], ['b', "I didn't mean anything by it."], ['a', "I told you that in private."]], beat: 'Things are cooler between them for the rest of the day.' },
    { id: 'fr2.19', turns: [['a', "Why didn't you back me up earlier?"], ['b', "Because you were wrong. I'm not going to lie for you."]] },
    { id: 'fr2.20', turns: [['a', "You've been spending a lot of time with them."], ['b', "Is that a problem?"], ['a', "No. I just miss our chats."]] },
    { id: 'fr2.21', turns: [['a', "I don't think you'd tell me if something was wrong."], ['b', "I would. I just haven't worked out what's wrong yet."]] },
    { id: 'fr2.22', turns: [['a', "You were the first one to laugh when I fell in the pool."], ['b', "I was also the first one to get you a towel."]] },
    { id: 'fr2.23', turns: [['a', "Truth or dare?"], ['b', "Truth. I'm too tired for a dare."], ['a', "Who would you pick if you could pick anyone?"], ['b', "Dare. I'll take the dare."]] },
    { id: 'fr2.24', turns: [['a', "I know you don't like them. Can you just be civil for tonight?"], ['b', "I'm always civil."], ['a', "You rolled your eyes at breakfast."]] },
    { id: 'fr2.25', turns: [['a', "Can I tell you something and you won't say anything?"], ['b', "Of course."], ['a', "I think I'm starting to really like them."]], beat: '{b} squeals and then covers {b.posAdj} own mouth.' },
    { id: 'fr2.26', turns: [['a', "You know you're allowed to be sad in here, right?"], ['b', "I know. I just don't want to be sad on camera."]] },
    { id: 'fr2.27', when: { phase: 'morning' }, turns: [['a', "I'm making everyone breakfast. Do you want anything?"], ['b', "Everything. I want everything."]] },
    { id: 'fr2.28', turns: [['a', "You've changed since you got here."], ['b', "Good changed or bad changed?"], ['a', "Good. You're happier."]] },
    { id: 'fr2.29', turns: [['a', "I'm not being funny, but you could have warned me."], ['b', "I didn't know how to say it."], ['a', "You just say it."]], beat: 'They sit apart at lunch.' },
    { id: 'fr2.30', turns: [['a', "Will you still talk to me when we're out?"], ['b', "I'll be at your door the day we land."]] },
    { id: 'fr2.31', when: { phase: 'morning' }, turns: [['a', "Did you sleep?"], ['b', "Somebody was snoring all night."], ['a', "That was you."]] },
    { id: 'fr2.32', when: { phase: 'evening' }, turns: [['a', "Last drink before the fire pit?"], ['b', "Go on, then. For courage."]] },
    { id: 'fr2.33', when: { late: true }, turns: [['a', "I can't believe how long we've been in here."], ['b', "It feels like a year and a week at the same time."]] },
    { id: 'fr2.34', when: { late: true }, turns: [['a', "Whatever happens in the final, I've got a friend for life out of this."], ['b', "Stop it. So have I."]] },
    { id: 'fr2.35', when: { mood: 'heartbroken' }, turns: [['b', "Come here. You don't have to talk."], ['a', "I don't want to talk."], ['b', "Then we won't."]], beat: '{b} holds on until {a} stops shaking.' },
    { id: 'fr2.36', when: { mood: 'stressed' }, turns: [['a', "I can't switch my brain off."], ['b', "Right. Pool. Now. No talking about couples for an hour."]] },
    { id: 'fr2.37', when: { mood: 'jealous' }, turns: [['a', "Am I being mad, or is something going on with my partner?"], ['b', "You're not mad. But I haven't seen anything either."]] },
    { id: 'fr2.38', when: { mood: 'lonely' }, turns: [['a', "Everyone's in a couple but me."], ['b', "You've got me. That's better than half of those couples."]] },
    { id: 'fr2.39', when: { gender: 'f', bGender: 'f' }, turns: [['a', "{~Girl}, what are we wearing tonight?"], ['b', "Something that makes the whole fire pit go quiet."]] },
    { id: 'fr2.40', when: { gender: 'm', bGender: 'm' }, turns: [['a', "Do you think I'm overthinking it?"], ['b', "Yes. Every single day. It's your best quality."]] },
  ],
  // pull [a, b]: a pulls b. Either may be coupled elsewhere; never to each other.
  pull: [
    { id: 'pl2.01', turns: [['a', "Can I steal you for five minutes?"], ['b', "Five minutes. I'm timing you."]] },
    { id: 'pl2.02', turns: [['a', "I've wanted to talk to you properly for days."], ['b', "Well, here I am."], ['a', "Here you are."]] },
    { id: 'pl2.03', turns: [['a', "Can I ask you something straight? Are you happy?"], ['b', "Why are you asking?"], ['a', "Because I'd like to know if there's a chance."]] },
    { id: 'pl2.04', turns: [['a', "I just want to get to know you. No pressure."], ['b', "There's always pressure in here."]] },
    { id: 'pl2.05', when: { bTaken: true }, turns: [['a', "You've been on my mind since the last recoupling."], ['b', "That's a lot to say to someone in a couple."], ['a', "I know. I'm saying it anyway."]] },
    { id: 'pl2.06', turns: [['a', "Walk with me?"], ['b', "Where to? It's a villa."], ['a', "To the other end of it."]], beat: 'They walk slowly, and nobody interrupts them.' },
    { id: 'pl2.07', turns: [['a', "I think we'd be good together."], ['b', "You don't know that."], ['a', "No. I'd like to find out."]] },
    { id: 'pl2.08', turns: [['a', "Can we talk on the terrace?"], ['b', "People will see."], ['a', "Let them."]] },
    { id: 'pl2.09', turns: [['a', "What would you say if I asked you on a date?"], ['b', "I'd say there's nowhere to go."], ['a', "The daybeds, then."]] },
    { id: 'pl2.10', turns: [['a', "I noticed you laughing at my jokes earlier."], ['b', "They were funny. It's not a big deal."], ['a', "It is to me."]] },
    { id: 'pl2.11', when: { bTaken: true }, turns: [['a', "I know you're with someone. I'm not trying to cause trouble."], ['b', "You sort of are, though."]], beat: '{pb} is watching from the kitchen.' },
    { id: 'pl2.12', when: { bTaken: true }, turns: [['a', "Does your partner make you laugh like that?"], ['b', "That's not fair."], ['a', "It's just a question."]] },
    { id: 'pl2.13', when: { taken: true }, turns: [['a', "I shouldn't be pulling you. I know I shouldn't."], ['b', "Then why are you?"], ['a', "I can't help it."]] },
    { id: 'pl2.14', turns: [['a', "Can I be honest? I'm a bit nervous right now."], ['b', "You? Nervous?"], ['a', "Only around you."]] },
    { id: 'pl2.15', turns: [['a', "I wanted to check. Is there anything there?"], ['b', "I don't know yet. Maybe."], ['a', "Maybe is good."]] },
    { id: 'pl2.16', turns: [['a', "I know this looks like grafting."], ['b', "It is grafting."], ['a', "Fair."]] },
    { id: 'pl2.17', turns: [['a', "Do you want to go to the hideaway and just talk? Only talk."], ['b', "Nobody goes to the hideaway to just talk."]] },
    { id: 'pl2.18', turns: [['a', "You look really nice tonight."], ['b', "Thank you. You're not so bad yourself."]], beat: 'They stand a little too close for a little too long.' },
    { id: 'pl2.19', turns: [['a', "Can I buy you a drink?"], ['b', "They're free."], ['a', "Can I pour you a free drink?"]], beat: '{b} laughs and takes the glass.' },
    { id: 'pl2.20', turns: [['a', "What's your biggest ick? Just so I know what not to do."], ['b', "Someone who asks what my biggest ick is."]] },
    { id: 'pl2.21', when: { rebuffed: true }, turns: [['a', "I'd really like a chat."], ['b', "Sorry. I'm not interested. I'm happy where I am."]], beat: '{a} nods, and walks away a bit faster than normal.' },
    { id: 'pl2.22', when: { rebuffed: true }, turns: [['a', "Can I pull you?"], ['b', "Now's not a good time."], ['a', "Later?"], ['b', "Maybe."]], beat: 'Later never comes.' },
    { id: 'pl2.23', when: { rebuffed: true }, turns: [['a', "I think there's something between us."], ['b', "I think you're reading too much into a conversation."]] },
    { id: 'pl2.24', turns: [['a', "I've been thinking about what you said yesterday."], ['b', "I didn't say much."], ['a', "It was enough."]] },
    { id: 'pl2.25', turns: [['a', "You're the only one in here I actually want to talk to."], ['b', "That's a lot of pressure."], ['a', "Sorry. It's true."]] },
    { id: 'pl2.26', turns: [['a', "Do you want to sit by the fire pit for a bit?"], ['b', "Alright. Just for a bit."]], beat: 'They are still there an hour later.' },
    { id: 'pl2.27', turns: [['a', "I'm going to be honest with you. I'd pick you at the recoupling."], ['b', "Don't tell me that."], ['a', "Why not?"], ['b', "Because now I'll think about it."]] },
    { id: 'pl2.28', turns: [['a', "Can I have your attention for a minute?"], ['b', "You've had it all day."]] },
    { id: 'pl2.29', turns: [['a', "Are you avoiding me?"], ['b', "A little bit."], ['a', "Why?"], ['b', "Because I like talking to you too much."]] },
    { id: 'pl2.30', when: { bTaken: true }, turns: [['a', "I don't usually do this."], ['b', "Do what?"], ['a', "Go after someone who's taken."]] },
    { id: 'pl2.31', when: { late: true }, turns: [['a', "We haven't got long left in here. I didn't want to leave without saying it."], ['b', "Saying what?"], ['a', "That I like you. That's all."]] },
    { id: 'pl2.32', when: { phase: 'evening' }, turns: [['a', "Everyone's getting ready. It's the only quiet five minutes all day."], ['b', "And you wanted to spend it with me."], ['a', "Obviously."]] },
    { id: 'pl2.33', when: { phase: 'day' }, turns: [['a', "Come in the pool with me."], ['b', "I've just done my hair."], ['a', "Come and sit on the edge, then."]] },
    { id: 'pl2.34', when: { rebuffed: true }, turns: [['a', "I feel like we'd get on better if you gave me a chance."], ['b', "I have given you a chance. It's just not there for me."]], beat: 'It stings, and {a} tries not to show it.' },
    { id: 'pl2.35', turns: [['a', "People are going to talk if we keep doing this."], ['b', "Then let's stop."], ['a', "Tomorrow."]] },
    { id: 'pl2.36', turns: [['a', "Honestly, you're my type on paper."], ['b', "What about off paper?"], ['a', "I'm working on it."]] },
    { id: 'pl2.37', turns: [['a', "I wanted to say sorry if I came on too strong yesterday."], ['b', "You did a bit."], ['a', "Can we start again?"]] },
    { id: 'pl2.38', turns: [['a', "What would it take for you to turn your head?"], ['b', "More than a chat by the pool."]] },
    { id: 'pl2.39', turns: [['a', "I can't stop looking at you."], ['b', "I'd noticed."]], beat: '{b} does not look away either.' },
    { id: 'pl2.40', turns: [['a', "One chat. That's all I'm asking."], ['b', "It's never one chat with you."]] },
  ],
  // chat [a, b]: a couple talking, nothing at stake.
  chat: [
    { id: 'ch2.01', turns: [['a', "What's the first thing you'll eat when we're out?"], ['b', "A roast dinner."], ['a', "In the middle of summer?"], ['b', "Especially in summer."]] },
    { id: 'ch2.02', turns: [['a', "You've got sun cream on your nose."], ['b', "Where?"], ['a', "Everywhere, basically."]], beat: '{a} rubs it in for {b.obj}.' },
    { id: 'ch2.03', turns: [['a', "Do you snore? Be honest."], ['b', "Never."], ['a', "You did last night."], ['b', "That was a very deep breath."]] },
    { id: 'ch2.04', turns: [['a', "If we had a dog, what would we call it?"], ['b', "Something ridiculous. Like Kevin."], ['a', "Kevin the dog. I love it."]] },
    { id: 'ch2.05', turns: [['a', "I like the way you laugh."], ['b', "I snort when I laugh."], ['a', "I know. That's what I like."]] },
    { id: 'ch2.06', turns: [['a', "Are you coming in the pool?"], ['b', "It's freezing."], ['a', "It's thirty degrees."], ['b', "The pool is freezing."]] },
    { id: 'ch2.07', turns: [['a', "What's your favourite film?"], ['b', "You'll judge me."], ['a', "I definitely will. Tell me."]] },
    { id: 'ch2.08', turns: [['a', "Can I have the last ice lolly?"], ['b', "We can share it."], ['a', "That's the most romantic thing anyone's ever said to me."]] },
    { id: 'ch2.09', turns: [['a', "I didn't think I'd like you this much."], ['b', "What did you think?"], ['a', "That you'd be a bit full of yourself."], ['b', "I am, a bit."]] },
    { id: 'ch2.10', turns: [['a', "Do you want to do a face mask with me?"], ['b', "Only if nobody sees."], ['a', "Everyone's going to see."]], beat: 'Everyone sees.' },
    { id: 'ch2.11', turns: [['a', "What's your family going to think of me?"], ['b', "They'll love you. They'll ask a lot of questions first."]] },
    { id: 'ch2.12', when: { phase: 'morning' }, turns: [['a', "Morning."], ['b', "Morning. You look nice."], ['a', "I've literally just woken up."], ['b', "I know."]] },
    { id: 'ch2.13', turns: [['a', "What song reminds you of me?"], ['b', "I'll tell you when I think of one that's not embarrassing."]] },
    { id: 'ch2.14', turns: [['a', "I'm going to make you a cup of tea."], ['b', "Milk first?"], ['a', "Never."]], beat: '{b} pretends to be outraged.' },
    { id: 'ch2.15', turns: [['a', "Do you think we'd work outside?"], ['b', "I think so. Do you?"], ['a', "I'm starting to."]] },
    { id: 'ch2.16', turns: [['a', "You're being quiet."], ['b', "I'm just happy. I'm quiet when I'm happy."]] },
    { id: 'ch2.17', turns: [['a', "Rate today out of ten."], ['b', "Seven."], ['a', "Why seven?"], ['b', "Because you took forty minutes in the shower."]] },
    { id: 'ch2.18', turns: [['a', "Can I tell you something embarrassing?"], ['b', "Please."], ['a', "I practised what I'd say to you before the fire pit."]] },
    { id: 'ch2.19', turns: [['a', "Who's your favourite in here? Apart from me."], ['b', "Apart from you? Nobody. They're all fine."]] },
    { id: 'ch2.20', turns: [['a', "I'll do your back if you do mine."], ['b', "Deal."]], beat: 'They argue about sun cream for five minutes.' },
    { id: 'ch2.21', turns: [['a', "You were talking to them for ages earlier."], ['b', "We were only talking."], ['a', "I know. I'm just saying."]], beat: 'Something small sits between them for the rest of the afternoon.' },
    { id: 'ch2.22', turns: [['a', "You didn't save me a seat at dinner."], ['b', "I didn't know I had to."], ['a', "You don't have to. It would have been nice."]] },
    { id: 'ch2.23', turns: [['a', "Are we okay?"], ['b', "Why wouldn't we be?"], ['a', "You've been a bit distant today."], ['b', "I'm just tired."]] },
    { id: 'ch2.24', turns: [['a', "Do you actually like me, or am I just the safe option?"], ['b', "Where's that come from?"], ['a', "I don't know. Just a feeling."]] },
    { id: 'ch2.25', turns: [['a', "Talk to me."], ['b', "About what?"], ['a', "Anything. You've not said a word all morning."]] },
    { id: 'ch2.26', when: { phase: 'morning' }, turns: [['a', "Do you want breakfast in bed?"], ['b', "In a room with ten other people?"], ['a', "Breakfast on the daybed, then."]] },
    { id: 'ch2.27', when: { phase: 'evening' }, turns: [['a', "You look amazing tonight."], ['b', "You're only saying that."], ['a', "I'm only saying it because it's true."]] },
    { id: 'ch2.28', when: { late: true }, turns: [['a', "Remember the first thing you said to me?"], ['b', "Don't. It was terrible."], ['a', "It was the best terrible thing anyone's said to me."]] },
    { id: 'ch2.29', when: { late: true }, turns: [['a', "I'm going to miss this. The daybeds, the sun, you."], ['b', "You're not going to miss me. I'm coming with you."]] },
    { id: 'ch2.30', when: { rung: ['exclusive', 'official'] }, turns: [['a', "What's our first real date going to be?"], ['b', "Somewhere with no cameras."], ['a', "And no fire pit."]] },
    { id: 'ch2.31', when: { mood: 'stressed' }, turns: [['a', "Everything okay?"], ['b', "I just need five minutes with you where nobody asks me about the recoupling."], ['a', "Done."]] },
    { id: 'ch2.32', when: { mood: 'jealous' }, turns: [['a', "Who were you laughing with earlier?"], ['b', "Just the group."], ['a', "It looked like more than the group."]], beat: '{b} sighs and takes {a.posAdj} hand.' },
    { id: 'ch2.33', when: { feels: 'little' }, turns: [['a', "Do you want to sit together tonight?"], ['b', "If you want."]], beat: "It's not the answer {a} was hoping for." },
    { id: 'ch2.34', when: { feels: 'little' }, turns: [['a', "What are you thinking about?"], ['b', "Nothing much."], ['a', "You always say that."]] },
    { id: 'ch2.35', turns: [['a', "If we get dumped tomorrow, I'm glad it was with you."], ['b', "We're not getting dumped tomorrow."], ['a', "But if we do."]] },
  ],
  // challenge-kiss [a, b]: a kisses b (not a's partner) for the game.
  'challenge-kiss': [
    { id: 'ck2.01', turns: [['a', "It's for the points!"], ['b', "Sure it is."]], beat: 'The whole villa cheers.' },
    { id: 'ck2.02', turns: [['a', "Sorry. The card said the best kisser."], ['b', "And you picked me."], ['a', "I didn't have much time."]] },
    { id: 'ch2k.03', turns: [['a', "Nobody say anything."], ['b', "I'm not saying anything."]], beat: 'Everyone else says something.' },
    { id: 'ck2.04', turns: [['a', "That doesn't count. It's a game."], ['b', "It counted a bit."]] },
    { id: 'ck2.05', turns: [['a', "I had to pick someone."], ['b', "You didn't have to pick me."]], beat: 'Somewhere behind them, a partner is not clapping.' },
    { id: 'ck2.06', turns: [['a', "Well, that's going to cause problems."], ['b', "For you. Not for me."]] },
    { id: 'ck2.07', turns: [['a', "I've been waiting all week for that challenge."], ['b', "I could tell."]] },
    { id: 'ck2.08', turns: [['a', "Was that too much?"], ['b', "For a game? Yes. For me? No."]] },
    { id: 'ck2.09', turns: [['a', "The rules said a kiss. I followed the rules."], ['b', "Very closely."]] },
    { id: 'ck2.10', turns: [['a', "Oops."], ['b', "Oops is right."]], beat: 'They both burst out laughing.' },
    { id: 'ck2.11', turns: [['a', "I'm sorry. It was the only way to win."], ['b', "We didn't win."], ['a', "No. But we tried."]] },
    { id: 'ck2.12', turns: [['a', "I didn't think you'd kiss me back."], ['b', "Neither did I."]] },
    { id: 'ck2.13', turns: [['a', "Please tell me my partner didn't see that."], ['b', "Everyone saw that."]] },
    { id: 'ck2.14', turns: [['a', "That was just for the game."], ['b', "Then why are you blushing?"]] },
    { id: 'ck2.15', turns: [['a', "Right. Back to the game."], ['b', "What game?"]] },
    { id: 'ck2.16', turns: [['a', "I'm going to get told off for that later."], ['b', "It'll be worth it."]] },
    { id: 'ck2.17', turns: [['a', "I didn't expect that to be so awkward."], ['b', "Thanks."], ['a', "I didn't mean it like that."]] },
    { id: 'ck2.18', turns: [['a', "Can we pretend that didn't happen?"], ['b', "Absolutely not."]] },
    { id: 'ck2.19', turns: [['a', "That was a bit of a surprise."], ['b', "A good one?"], ['a', "Let's not talk about it right now."]] },
    { id: 'ck2.20', turns: [['a', "The things I do for a challenge."], ['b', "You looked like you were enjoying it."]] },
    { id: 'ck2.21', when: { taken: true }, turns: [['a', "My partner is going to kill me."], ['b', "Only if you tell them it was good."]] },
    { id: 'ck2.22', when: { bTaken: true }, turns: [['a', "Sorry. I know you're with someone."], ['b', "It's a game. They'll understand."], ['a', "Will they?"]], beat: '{pb} does not look like somebody who understands.' },
    { id: 'ck2.23', turns: [['a', "You kiss like you mean it."], ['b', "I always mean it."]] },
    { id: 'ck2.24', turns: [['a', "I'll never hear the end of this."], ['b', "Nope."]] },
    { id: 'ck2.25', turns: [['a', "That was a dare, not a declaration."], ['b', "I didn't say anything."], ['a', "Your face did."]] },
    { id: 'ck2.26', turns: [['a', "One kiss. For the team."], ['b', "For the team."]], beat: 'It lasts longer than the team needed.' },
    { id: 'ck2.27', turns: [['a', "I think I just lost us the challenge."], ['b', "You lost us something."]] },
    { id: 'ck2.28', turns: [['a', "Let's never talk about that again."], ['b', "Agreed."]], beat: 'They both laugh about it at dinner anyway.' },
    { id: 'ck2.29', turns: [['a', "Sorry, I panicked."], ['b', "You panic very well."]] },
    { id: 'ck2.30', turns: [['a', "I only picked you because you were closest."], ['b', "I was on the other side of the lawn."]] },
  ],
  // argument [a, b]: a starts it; b is usually a's partner.
  argument: [
    { id: 'ar2.01', turns: [['a', "Why do you always do this?"], ['b', "Do what?"], ['a', "Disappear the minute someone new walks in."]] },
    { id: 'ar2.02', turns: [['a', "You made me look stupid in front of everyone."], ['b', "It was a joke."], ['a', "It wasn't funny."]], beat: '{a} walks off before {b} can answer.' },
    { id: 'ar2.03', turns: [['a', "I asked you one thing."], ['b', "And I told you. I forgot."], ['a', "You always forget."]] },
    { id: 'ar2.04', turns: [['a', "Don't talk to me like that."], ['b', "Like what?"], ['a', "Like I'm being dramatic."], ['b', "You are being dramatic."]] },
    { id: 'ar2.05', turns: [['a', "You were flirting with them."], ['b', "I was being friendly."], ['a', "There's friendly, and there's that."]] },
    { id: 'ar2.06', turns: [['a', "I'm sick of being the only one who puts effort in."], ['b', "That's not fair."], ['a', "Isn't it?"]] },
    { id: 'ar2.07', turns: [['a', "Why are you shouting?"], ['b', "I'm not shouting!"]], beat: 'The whole kitchen goes quiet.' },
    { id: 'ar2.08', turns: [['a', "You told me one thing and did another."], ['b', "I changed my mind. That's allowed."]] },
    { id: 'ar2.09', turns: [['a', "Can you not roll your eyes at me?"], ['b', "Can you not give me a reason to?"]] },
    { id: 'ar2.10', turns: [['a', "You didn't even ask how I was after the fire pit."], ['b', "I was upset too."], ['a', "That's not an answer."]] },
    { id: 'ar2.11', turns: [['a', "Everyone knows what you said about me."], ['b', "Everyone knows what you think I said."]] },
    { id: 'ar2.12', turns: [['a', "I can't do this right now."], ['b', "You never can."]], beat: '{a} goes inside and shuts the door.' },
    { id: 'ar2.13', turns: [['a', "You're not listening to me."], ['b', "I'm listening. I just don't agree."]] },
    { id: 'ar2.14', turns: [['a', "Why is it always about you?"], ['b', "It's not always about me."], ['a', "It's always about you."]] },
    { id: 'ar2.15', turns: [['a', "You could have backed me up."], ['b', "You were wrong."], ['a', "You still could have backed me up."]] },
    { id: 'ar2.16', turns: [['a', "Don't walk away from me."], ['b', "I need a minute."], ['a', "You've had a minute."]] },
    { id: 'ar2.17', turns: [['a', "That was really disrespectful."], ['b', "It was a conversation."], ['a', "In front of me."]] },
    { id: 'ar2.18', turns: [['a', "I'm not going to apologise for having feelings."], ['b', "I'm not asking you to. I'm asking you to calm down."]] },
    { id: 'ar2.19', turns: [['a', "Every time something goes wrong, it's my fault."], ['b', "I never said that."], ['a', "You didn't have to."]] },
    { id: 'ar2.20', turns: [['a', "You've been off with me all day."], ['b', "Because of last night."], ['a', "What about last night?"], ['b', "You know what."]] },
    { id: 'ar2.21', turns: [['a', "Stop telling people our business."], ['b', "I talked to one person."], ['a', "One person is the whole villa in here."]] },
    { id: 'ar2.22', turns: [['a', "Can we please not do this at the fire pit?"], ['b', "Then when? You never want to talk."]] },
    { id: 'ar2.23', turns: [['a', "I saw the way you looked at them."], ['b', "I didn't look at anyone."], ['a', "I'm not blind."]] },
    { id: 'ar2.24', turns: [['a', "You said you'd closed off."], ['b', "I have."], ['a', "Then why does it not feel like it?"]] },
    { id: 'ar2.25', turns: [['a', "Honestly, I don't even know why we're arguing."], ['b', "Neither do I."]], beat: 'They are still annoyed with each other anyway.' },
    { id: 'ar2.26', when: { rowedBefore: true }, turns: [['a', "Here we go again."], ['b', "Don't. Don't start with that."]] },
    { id: 'ar2.27', when: { late: true }, turns: [['a', "We're so close to the end and you're doing this now?"], ['b', "I'm not doing anything."]] },
    { id: 'ar2.28', when: { phase: 'morning' }, turns: [['a', "It's nine in the morning. Why are we arguing?"], ['b', "You started it."], ['a', "You started it last night."]] },
    { id: 'ar2.29', when: { mood: 'jealous' }, turns: [['a', "Just tell me the truth. Do you like them?"], ['b', "I like you."], ['a', "That's not what I asked."]] },
    { id: 'ar2.30', when: { mood: 'stressed' }, turns: [['a', "I can't cope with this today."], ['b', "With what? I haven't said anything."], ['a', "That's the problem."]] },
  ],
};
