// more-b — a second pool for the rest of the scenes that repeat (see more-a).
// Casts follow each kind's own file. Negative scenes are written alongside the
// warm ones, never as an afterthought.

export const MORE_B = {
  // comedy [a] ALONE.
  comedy: [
    { id: 'co2.01', stage: '{a} tries to do a handstand in the pool and swallows half of it.', turns: [['a', "I'm fine. I meant to do that."]] },
    { id: 'co2.02', stage: '{a} spends twenty minutes trying to get the perfect photo of the sunset, then realises there are no phones.', turns: [['a', "Oh. Right. Yeah."]] },
    { id: 'co2.03', stage: '{a} sings in the shower, loudly, and the whole garden joins in the chorus.', turns: [['a', "I didn't know you could all hear that."]] },
    { id: 'co2.04', stage: '{a} tries to cook pasta and sets off the smoke alarm.', turns: [['a', "It's fine! It's fine. Everybody stay calm."]] },
    { id: 'co2.05', stage: '{a} falls asleep on a sunbed and wakes up with a very clear tan line.', turns: [['a', "Why did nobody wake me up?"]] },
    { id: 'co2.06', when: { phase: 'morning' }, stage: '{a} does an impression of the host at breakfast. It is not a good impression.', turns: [['a', "Okay, that one needs work."]] },
    { id: 'co2.07', stage: '{a} tries to open a coconut with a spoon.', turns: [['a', "I've seen it done. On the internet."]] },
    { id: 'co2.08', stage: '{a} walks straight into the glass door. Again.', turns: [['a', "Who keeps cleaning it? Stop cleaning it."]] },
    { id: 'co2.09', stage: '{a} explains the rules of a card game nobody has ever heard of.', turns: [['a', "No, you're not listening. The joker is worth nine."]] },
    { id: 'co2.10', stage: '{a} gets stuck in an inflatable flamingo.', turns: [['a', "Can somebody help? Anyone? Please?"]] },
    { id: 'co2.11', stage: '{a} tries to do a yoga pose from memory and falls over.', turns: [['a', "That's the pose. That's what it's meant to look like."]] },
    { id: 'co2.12', stage: '{a} makes everyone a cocktail. Nobody can drink it.', turns: [['a', "It's an acquired taste."]] },
    { id: 'co2.13', stage: '{a} tries to whisper a secret and says it at full volume.', turns: [['a', "Did everyone hear that? Everyone heard that."]] },
    { id: 'co2.14', stage: '{a} spends the morning looking for sunglasses that are on {a.posAdj} head.', turns: [['a', "Has anyone seen my… oh. Never mind."]] },
    { id: 'co2.15', stage: '{a} trips carrying six drinks and saves every one of them.', turns: [['a', "Nobody move. I'm a professional."]] },
    { id: 'co2.16', stage: '{a} challenges everyone to a push-up competition and gives up after four.', turns: [['a', "Four is a good number. It's a solid number."]] },
    { id: 'co2.17', stage: '{a} gives a speech at dinner that nobody asked for.', turns: [['a', "I just want to say, I love every single one of you. Mostly."]] },
    { id: 'co2.18', stage: '{a} tries to learn a dance routine off one of the others and gets it completely wrong.', turns: [['a', "I've got my own version. It's better."]] },
    { id: 'co2.19', stage: '{a} mistakes the salt for sugar in everyone\'s tea.', turns: [['a', "Is it bad? It's bad, isn't it."]] },
    { id: 'co2.20', stage: '{a} tries to sunbathe on the lilo and drifts slowly into the corner of the pool.', turns: [['a', "I'm stuck. I'm stuck in the corner. Nobody is helping."]] },
    { id: 'co2.21', when: { phase: 'morning' }, stage: '{a} comes out for breakfast with the pillow still printed on {a.posAdj} face.', turns: [['a', "What? What are you all looking at?"]] },
    { id: 'co2.22', when: { phase: 'evening' }, stage: '{a} spends so long getting ready that the fire pit has started.', turns: [['a', "Did I miss it? Please say I didn't miss it."]] },
  ],
  // deep-chat [a, b]: a couple opening up.
  'deep-chat': [
    { id: 'dc2.01', turns: [['a', "I've never told anyone this, but I'm scared of being left."], ['b', "I'm not going anywhere."]] },
    { id: 'dc2.02', turns: [['a', "What do you actually want, when all this is over?"], ['b', "Something normal. Someone to come home to."], ['a', "Me too."]] },
    { id: 'dc2.03', turns: [['a', "Do you think you'd have noticed me outside?"], ['b', "Honestly? Probably not. And I'd have missed out."]] },
    { id: 'dc2.04', turns: [['a', "My last relationship made me stop trusting people."], ['b', "Do you trust me?"], ['a', "I'm getting there."]] },
    { id: 'dc2.05', turns: [['a', "When did you know you liked me?"], ['b', "When you laughed at my joke that wasn't funny."]] },
    { id: 'dc2.06', turns: [['a', "I'm not very good at saying how I feel."], ['b', "You're better than you think."]] },
    { id: 'dc2.07', turns: [['a', "What would you do if I got dumped tomorrow?"], ['b', "Walk out with you."], ['a', "You wouldn't."], ['b', "Try me."]] },
    { id: 'dc2.08', turns: [['a', "I worry that you're more sure than I am."], ['b', "That's okay. We don't have to be at the same place at the same time."]] },
    { id: 'dc2.09', turns: [['a', "Do you ever think about the future? With me, I mean."], ['b', "More than I should, this early."]] },
    { id: 'dc2.10', turns: [['a', "I used to think I didn't want a relationship."], ['b', "And now?"], ['a', "Now I'm not sure I want to go back to not having one."]] },
    { id: 'dc2.11', turns: [['a', "What's the worst thing someone's done to you?"], ['b', "Made me feel like I wasn't enough."], ['a', "You're enough."]] },
    { id: 'dc2.12', turns: [['a', "You're the first person in here I've actually been honest with."], ['b', "That means a lot."]] },
    { id: 'dc2.13', turns: [['a', "I need to know you're not going to change your mind the second someone new walks in."], ['b', "I can't promise you anything in here. But I'm not looking."]] },
    { id: 'dc2.14', turns: [['a', "Do you ever feel like you're playing a part in here?"], ['b', "Sometimes. Not with you, though."]] },
    { id: 'dc2.15', turns: [['a', "I don't think I've ever felt this settled with someone."], ['b', "In a villa full of bombshells?"], ['a', "Even then."]] },
    { id: 'dc2.16', turns: [['a', "Can I be honest? I'm not sure where this is going."], ['b', "Okay. Thank you for telling me."]], beat: 'It is a quiet evening after that.' },
    { id: 'dc2.17', turns: [['a', "I feel like you're holding back."], ['b', "I'm not."], ['a', "You are. And I get it. I just want to know why."]] },
    { id: 'dc2.18', turns: [['a', "Sometimes I think you're here for the experience, not for me."], ['b', "That's not fair."], ['a', "Then show me it's not true."]] },
    { id: 'dc2.19', turns: [['a', "What if it doesn't work outside?"], ['b', "Then at least we tried."], ['a', "That's not very romantic."], ['b', "It's honest."]] },
    { id: 'dc2.20', turns: [['a', "I don't want to get hurt again."], ['b', "I don't want to be the one who does it."]] },
    { id: 'dc2.21', when: { late: true }, turns: [['a', "Do you remember how nervous we were at the start?"], ['b', "I'm still nervous. Just about different things."]] },
    { id: 'dc2.22', when: { late: true }, turns: [['a', "Whatever the public decide, I've got what I came for."], ['b', "What's that?"], ['a', "You."]] },
    { id: 'dc2.23', when: { mood: 'secure' }, turns: [['a', "I don't worry about us any more."], ['b', "Good. Neither do I."]] },
    { id: 'dc2.24', when: { feels: 'little' }, turns: [['a', "Do you see this going anywhere?"], ['b', "I don't know yet."], ['a', "That's alright. I just needed to ask."]] },
    { id: 'dc2.25', when: { rung: ['exclusive', 'official'] }, turns: [['a', "I've told my family about you. In my head, anyway."], ['b', "What did they say?"], ['a', "That it's about time."]] },
  ],
  // kiss [a, b]: a couple kiss.
  kiss: [
    { id: 'ks2.01', turns: [['a', "Come here."], ['b', "Everyone's watching."], ['a', "Good."]] },
    { id: 'ks2.02', stage: '{a} kisses {b} in the middle of a sentence.', turns: [['b', "I was talking."], ['a', "I know."]] },
    { id: 'ks2.03', stage: 'A kiss by the pool as the lights come on.', turns: [['b', "That was nice."], ['a', "Just nice?"], ['b', "Very nice."]] },
    { id: 'ks2.04', when: { phase: 'morning' }, turns: [['a', "Morning kiss?"], ['b', "I haven't brushed my teeth."], ['a', "I don't care."]] },
    { id: 'ks2.05', stage: 'They kiss in the kitchen while the kettle boils.', turns: [['b', "The kettle's done."], ['a', "Let it wait."]] },
    { id: 'ks2.06', stage: '{a} kisses {b} on the forehead on the way past.', turns: [['b', "What was that for?"], ['a', "Nothing. Just because."]] },
    { id: 'ks2.07', turns: [['a', "I've been wanting to do that all day."], ['b', "Then why did you wait?"]] },
    { id: 'ks2.08', when: { phase: 'evening' }, stage: 'A quick kiss before the fire pit.', turns: [['a', "For luck."], ['b', "We don't need luck."]] },
    { id: 'ks2.09', stage: '{a} goes in for a kiss and {b} pulls away slightly.', turns: [['a', "Everything okay?"], ['b', "Yeah. Just not in front of everyone."]], beat: '{a} nods, and does not believe it.' },
    { id: 'ks2.10', stage: 'The kiss is short, and neither of them says anything after it.', turns: [['a', "Are we good?"], ['b', "We're fine."]] },
    { id: 'ks2.11', stage: '{a} kisses {b}, who is still looking over at someone else.', turns: [['a', "Hello? I'm here."], ['b', "Sorry. Sorry."]] },
    { id: 'ks2.12', turns: [['a', "You taste like sun cream."], ['b', "That's the most romantic thing you've ever said."]] },
    { id: 'ks2.13', stage: 'They kiss on the daybed until someone throws a pillow at them.', turns: [['b', "Rude."], ['a', "Ignore them."]] },
    { id: 'ks2.14', stage: 'A long kiss by the fire pit after everyone else has gone to bed.', turns: [['a', "I don't want tonight to end."], ['b', "It doesn't have to yet."]] },
    { id: 'ks2.15', when: { late: true }, turns: [['a', "Do you know how many times we've done that now?"], ['b', "Not enough."]] },
    { id: 'ks2.16', when: { phase: 'evening', feels: 'little' }, stage: 'A kiss that feels more like a habit than anything else.', turns: [['b', "Night, then."], ['a', "Night."]] },
    { id: 'ks2.17', when: { phase: 'evening' }, stage: 'They kiss on the terrace with the whole villa below them.', turns: [['b', "Best view in here."], ['a', "The villa's not bad either."]] },
    { id: 'ks2.18', stage: '{a} kisses {b} after a row that was about nothing.', turns: [['b', "We're still arguing, by the way."], ['a', "I know."]] },
  ],
  // gossip [a, b, c]: a saw it, b is c's partner, c did it. Always `knows`.
  gossip: [
    { id: 'gs2.01', when: { knows: true }, turns: [['a', "I'm only telling you because I'd want to know."], ['b', "What happened?"], ['a', "{c} was by the pool with someone for a long time."]] },
    { id: 'gs2.02', when: { knows: true }, turns: [['a', "I don't want to cause drama. But I saw {c} in the hideaway."], ['b', "With who?"]], beat: '{a} does not answer straight away.' },
    { id: 'gs2.03', when: { knows: true }, turns: [['a', "Can I have a word? It's about {c}."], ['b', "Just tell me."], ['a', "It wasn't just a chat last night."]] },
    { id: 'gs2.04', when: { knows: true }, turns: [['a', "You're one of my best friends in here. So I have to say it."], ['b', "Say what?"], ['a', "{c} kissed someone."]] },
    { id: 'gs2.05', when: { knows: true }, turns: [['a', "I've been going back and forth about telling you."], ['b', "Is this about {c}?"], ['a', "Yeah."]] },
    { id: 'gs2.06', when: { knows: true }, turns: [['a', "I saw something I wasn't meant to see."], ['b', "Please don't say it's {c}."]], beat: '{a} says nothing, which says enough.' },
    { id: 'gs2.07', when: { knows: true }, turns: [['a', "{c} isn't being honest with you."], ['b', "How do you know?"], ['a', "Because I was there."]] },
    { id: 'gs2.08', when: { knows: true }, turns: [['a', "I think you deserve better than someone who does that behind your back."], ['b', "Does what?"]] },
    { id: 'gs2.09', when: { knows: true }, turns: [['a', "I'm sorry. I thought you already knew."], ['b', "Knew what?"], ['a', "About {c} and the late-night chat."]] },
    { id: 'gs2.10', when: { knows: true }, turns: [['a', "If it was me, I'd want to hear it from a friend."], ['b', "Then tell me."]] },
    { id: 'gs2.11', when: { knows: true }, turns: [['a', "You're going to find out anyway, so it might as well be from me."], ['b', "Just say it."], ['a', "{c} has been flirting with someone else."]] },
    { id: 'gs2.12', when: { knows: true }, turns: [['a', "Don't be angry with me. Be angry with {c}."], ['b', "I'm not angry yet. I will be. Go on."]] },
    { id: 'gs2.13', when: { knows: true }, turns: [['a', "I'm not trying to split you up. I just saw what I saw."], ['b', "And what was that?"]] },
    { id: 'gs2.14', when: { knows: true }, turns: [['a', "{c} told me not to say anything. I'm saying it anyway."], ['b', "Thank you. I think."]] },
    { id: 'gs2.15', when: { knows: true, late: true }, turns: [['a', "We're weeks into this. You need to know who you're with."], ['b', "What's {c} done?"]] },
  ],
  // loyalty [a, b]: a turns down b's pull.
  loyalty: [
    { id: 'lo2.01', turns: [['b', "Can we chat?"], ['a', "I'd rather not. It wouldn't be fair on the person I'm with."]] },
    { id: 'lo2.02', turns: [['b', "Just five minutes."], ['a', "I know where five minutes leads. No, thank you."]] },
    { id: 'lo2.03', turns: [['b', "Are you really happy in your couple?"], ['a', "Yes. Really."], ['b', "You could do better."], ['a', "I don't want better. I want what I've got."]] },
    { id: 'lo2.04', turns: [['b', "I think we'd be good together."], ['a', "Maybe, in another life. Not in this villa."]] },
    { id: 'lo2.05', turns: [['b', "Come on. It's just a chat."], ['a', "It's never just a chat. You know that."]] },
    { id: 'lo2.06', turns: [['b', "I'd pick you if I could."], ['a', "That's nice of you to say. I'd still pick my partner."]] },
    { id: 'lo2.07', turns: [['b', "You looked bored with them earlier."], ['a', "I was tired. That's not the same thing."]] },
    { id: 'lo2.08', turns: [['b', "Can I take you to the terrace?"], ['a', "I'm going to say no, and I'm going to say it nicely."]] },
    { id: 'lo2.09', turns: [['b', "I just want to get to know you."], ['a', "You can get to know me at dinner, with everyone else."]] },
    { id: 'lo2.10', turns: [['b', "Nobody would have to know."], ['a', "I would know."]] },
    { id: 'lo2.11', turns: [['b', "One drink?"], ['a', "One drink with the whole group. That's the offer."]] },
    { id: 'lo2.12', when: { late: true }, turns: [['b', "It's not too late to change your mind."], ['a', "It's far too late. I made my mind up weeks ago."]] },
    { id: 'lo2.13', when: { rung: ['exclusive', 'official'] }, turns: [['b', "Are you sure you're closed off?"], ['a', "Completely. Sorry."]] },
  ],
  // challenge-win [a, b]: a couple who won.
  'challenge-win': [
    { id: 'cw2.01', turns: [['a', "We actually won!"], ['b', "I told you we would."]] },
    { id: 'cw2.02', turns: [['a', "Best team in the villa."], ['b', "Best couple in the villa."]] },
    { id: 'cw2.03', turns: [['a', "Did you see their faces?"], ['b', "I saw them. They're not happy."]], beat: 'They both laugh.' },
    { id: 'cw2.04', turns: [['a', "That's twice now."], ['b', "Three times, but who's counting?"], ['a', "You are."]] },
    { id: 'cw2.05', turns: [['a', "I didn't know you were that fast."], ['b', "I didn't know you were that loud."]] },
    { id: 'cw2.06', turns: [['a', "We make a really good team."], ['b', "We make a really good everything."]] },
    { id: 'cw2.07', turns: [['a', "I'm not going to let them forget this."], ['b', "Please don't be smug at dinner."], ['a', "I'm going to be very smug at dinner."]] },
    { id: 'cw2.08', turns: [['a', "You were amazing out there."], ['b', "You weren't bad yourself."]], beat: '{b} lifts {a} right off the ground.' },
    { id: 'cw2.09', turns: [['a', "That was all you."], ['b', "It was all us."]] },
    { id: 'cw2.10', turns: [['a', "Winners get the good sunbeds."], ['b', "That's not a rule."], ['a', "It is now."]] },
    { id: 'cw2.11', turns: [['a', "We won, but you nearly knocked me over twice."], ['b', "We won, didn't we?"]] },
    { id: 'cw2.12', turns: [['a', "Everyone thinks we're the favourites now."], ['b', "Good. Let them think it."]] },
  ],
  // ick [a, b]: a goes off b (a small habit, never the profile's icks).
  ick: [
    { id: 'ik2.01', stage: '{b} laughs at {b.posAdj} own joke before finishing it.', turns: [['a', "…Yeah. Funny."]], beat: '{a} goes a bit quiet.' },
    { id: 'ik2.02', stage: '{b} calls the pool "the big bath".', turns: [['a', "The what?"], ['b', "The bath. The big bath."]] },
    { id: 'ik2.03', stage: '{b} blows on {a.posAdj} food without asking.', turns: [['a', "I can do that myself."]] },
    { id: 'ik2.04', stage: '{b} does a little run across the lawn.', turns: [['a', "Oh no. The run. I didn't need to see the run."]] },
    { id: 'ik2.05', stage: '{b} talks in a baby voice to {a}.', turns: [['a', "Please don't do that."], ['b', "Do what?"], ['a', "The voice."]] },
    { id: 'ik2.06', stage: '{b} checks {b.posAdj} own reflection in {a.posAdj} sunglasses mid-conversation.', turns: [['a', "Are you listening to me or looking at yourself?"]] },
    { id: 'ik2.07', stage: '{b} claps when the food arrives.', turns: [['a', "Did you just clap for a sandwich?"]] },
    { id: 'ik2.08', stage: '{b} gets very competitive over a game of cards.', turns: [['a', "It's just cards."], ['b', "It is NOT just cards."]], beat: '{a} leans back and watches, not very impressed.' },
    { id: 'ik2.09', stage: '{b} says "babe" at the end of every sentence.', turns: [['a', "Can you stop saying babe for five minutes?"], ['b', "Why, babe?"]] },
    { id: 'ik2.10', stage: '{b} sulks after losing a game of volleyball.', turns: [['a', "It's volleyball. We lost. It's fine."]] },
    { id: 'ik2.11', stage: '{b} drinks straight out of the milk carton.', turns: [['a', "There are cups. There are loads of cups."]] },
    { id: 'ik2.12', stage: '{b} sneezes and does not cover it.', turns: [['a', "Right. I'm going for a swim."]] },
  ],
};

// ── the moments that repeat (lines/moments.js pools) ────────────────────
export const MORE_MOMENTS = {

  // save-tie [a, b(, c)]: a is saved on the public's votes; b (and c) tied with a.
  'save-tie': [
    { id: 'st.01', turns: [['dior', "We have a tie. {a} and {b} have the same number of saves."], ['dior', "So the public's votes decide. And the islander the public saved is… {a}."]], beat: '{b} nods slowly, and does not look at anyone.' },
    { id: 'st.02', turns: [['dior', "It's level. Nobody in the villa can split {a} and {b}."], ['dior', "The public can. Of the two, they voted for {a}."]] },
    { id: 'st.03', turns: [['dior', "Islanders, the saves are tied between {a} and {b}."], ['dior', "The tie goes to whoever the public voted for the most, and that's {a}."]], beat: '{a} breathes out. {b} gets a hug from the islanders either side.' },
    { id: 'st.04', turns: [['dior', "{a}, {b}: a tie."], ['dior', "Which means it comes down to the public. {a}, you are safe."]], beat: '{b} manages a smile, just.' },
  ],

  // final-result [a, b]: the couple, by placing (`of`), read out bottom first.
  'final-result': [
    { id: 'fr.4.01', when: { of: 'fourth' }, turns: [['dior', "In fourth place, it's {a} and {b}."]], beat: 'They hug each other, and then everybody else.' },
    { id: 'fr.4.02', when: { of: 'fourth' }, turns: [['dior', "The couple in fourth place… {a} and {b}."], ['a', "Honestly, just being in the final is enough."]] },
    { id: 'fr.4.03', when: { of: 'fourth' }, turns: [['dior', "{a} and {b}, you're in fourth place."], ['b', "We'll take it. We're going home together."]] },
    { id: 'fr.4.04', when: { of: 'fourth' }, turns: [['dior', "In fourth place… {a} and {b}."]], beat: '{a} looks disappointed for about a second, then kisses {b}.' },
    { id: 'fr.3.01', when: { of: 'third' }, turns: [['dior', "In third place, it's {a} and {b}."], ['a', "Third! That's not bad at all."]] },
    { id: 'fr.3.02', when: { of: 'third' }, turns: [['dior', "The couple in third place is… {a} and {b}."]], beat: '{b} squeezes {a.posAdj} hand, and they both smile.' },
    { id: 'fr.3.03', when: { of: 'third' }, turns: [['dior', "{a} and {b}. You're in third place."], ['b', "Thank you to everyone who voted for us."]] },
    { id: 'fr.3.04', when: { of: 'third' }, turns: [['dior', "In third place… {a} and {b}."], ['a', "I'm disappointed and I'm happy at the same time."]] },
    { id: 'fr.2.01', when: { of: 'second' }, turns: [['dior', "Which means our runners-up are… {a} and {b}."]], beat: 'The other couple is already screaming.' },
    { id: 'fr.2.02', when: { of: 'second' }, turns: [['dior', "It's the final two. And in second place… {a} and {b}."], ['a', "That's okay. That's okay. Well done, you two."]] },
    { id: 'fr.2.03', when: { of: 'second' }, turns: [['dior', "Our runners-up… {a} and {b}."], ['b', "We came so close."], ['a', "We did. And I've still got you."]] },
    { id: 'fr.2.04', when: { of: 'second' }, turns: [['dior', "{a} and {b}, you're our runners-up."]], beat: '{a} hugs the winners first, before anyone else can.' },
    { id: 'fr.1.01', when: { of: 'first' }, turns: [['dior', "The winners of Perfect Match are… {a} and {b}!"]], beat: 'The fire pit erupts. {a} lifts {b} right off the ground.' },
    { id: 'fr.1.02', when: { of: 'first' }, turns: [['dior', "The couple the public voted to win is… {a} and {b}!"], ['a', "No. No way. Are you serious?"], ['b', "We won! We actually won!"]] },
    { id: 'fr.1.03', when: { of: 'first' }, turns: [['dior', "{a}, {b}. You're the winners."]], beat: '{b} bursts into tears. {a} is laughing and crying at the same time.' },
    { id: 'fr.1.04', when: { of: 'first' }, turns: [['dior', "And the winners are… {a} and {b}!"], ['b', "I can't believe it. I can't believe it's us."], ['a', "Believe it."]] },
    { id: 'fr.1.05', when: { of: 'first', late: true }, turns: [['dior', "After everything, the winners of Perfect Match are {a} and {b}!"], ['a', "I came in here for this. For you."]], beat: 'Fireworks go off over the villa.' },
  ],
  // envelope [a, b]: winner a holds the envelope; b is a's partner (`choice`).
  envelope: [
    { id: 'env.s.01', when: { choice: 'split' }, stage: '{a} holds the envelope, and the whole villa goes silent.', turns: [['a', "There was never any question."], ['a', "I'm splitting it."]], beat: '{b} is crying before {a} has finished the sentence.' },
    { id: 'env.s.02', when: { choice: 'split' }, stage: 'The host hands {a} the envelope.', turns: [['dior', "{a}, split or steal?"], ['a', "Split. Obviously. I'd have split it with {b} on day one."]] },
    { id: 'env.s.03', when: { choice: 'split' }, stage: '{a} opens the envelope slowly, drawing it out.', turns: [['b', "Stop it. Stop it, I can't breathe."], ['a', "Split."]], beat: '{b} hits {a.obj} on the arm, then kisses {a.obj}.' },
    { id: 'env.s.04', when: { choice: 'split' }, stage: '{a} takes the envelope and looks straight at {b}.', turns: [['a', "We did this together. We're sharing it together."]] },
    { id: 'env.t.01', when: { choice: 'steal' }, stage: '{a} holds the envelope for a long time.', turns: [['a', "I'm sorry. I'm stealing."]], beat: '{b} stares at {a}, and does not say a word. The fire pit goes completely silent.' },
    { id: 'env.t.02', when: { choice: 'steal' }, stage: 'The host hands {a} the envelope.', turns: [['dior', "{a}, split or steal?"], ['a', "…Steal."], ['b', "You're joking. Tell me you're joking."]] },
    { id: 'env.t.03', when: { choice: 'steal' }, stage: '{a} opens the envelope, and cannot look at {b}.', turns: [['a', "I need this money. I'm sorry."], ['b', "After everything?"]], beat: 'The whole villa turns to look at {a}.' },
  ],
  // step-forward [a, b]: boy a walks in; b is the girl he couples with (`of`).
  'step-forward': [
    { id: 'sf2.01', when: { of: 'one' }, stage: '{a} reaches the fire pit. {b} is the only one to step forward.', turns: [['a', "Just you?"], ['b', "Just me. Is that a problem?"], ['a', "Not at all."]] },
    { id: 'sf2.02', when: { of: 'one' }, stage: '{b} steps forward the second {a} comes into view.', turns: [['b', "Sorry. I didn't even wait. I just went."], ['a', "I'm glad you did."]] },
    { id: 'sf2.03', when: { of: 'one' }, stage: '{a} walks in, and {b} takes one step forward, a little nervously.', turns: [['a', "Hi. I'm {a}."], ['b', "I know. We all heard. Hi."]], beat: 'They both laugh, and it breaks the ice.' },
    { id: 'sf2.04', when: { of: 'one' }, stage: 'Only {b} steps forward for {a}.', turns: [['a', "Right. Well. Nice to meet you, {b}."], ['b', "You don't sound very excited."], ['a', "I'm excited. I'm just nervous."]], beat: '{b} is not completely sure.' },
    { id: 'sf2.05', when: { of: 'one' }, stage: '{a} comes down the steps, and {b} steps forward straight away.', turns: [['b', "You're exactly my type. I'm not going to pretend."], ['a', "Well, now I'm blushing."]] },
    { id: 'sf2.06', when: { of: 'one' }, stage: '{b} steps forward for {a}. Nobody else moves.', turns: [['a', "Looks like we're a couple, then."], ['b', "Looks like it. Come and stand with me."]] },
    { id: 'sf2.07', when: { of: 'one' }, stage: '{a} arrives, and after a long pause {b} steps forward.', turns: [['a', "That was a long wait."], ['b', "I was thinking about it."], ['a', "And?"], ['b', "And here I am."]] },
    { id: 'sf2.08', when: { of: 'one' }, stage: '{b} steps forward for {a} and grins at the others.', turns: [['b', "I'll take this one, thanks."], ['a', "Do I get a say?"], ['b', "You can say yes."], ['a', "Yes."]] },
    { id: 'sf2.09', when: { of: 'several' }, stage: 'Three {side} step forward for {a} at once.', turns: [['a', "Oh no. Oh no, this is hard."], ['a', "{b}. Sorry, everyone."]], beat: 'The {side} who stepped forward go back into line, not all of them smiling.' },
    { id: 'sf2.10', when: { of: 'several' }, stage: '{a} walks in, and more than one {sideOne} steps forward.', turns: [['a', "I didn't think anyone would step forward, and now I've got to choose."], ['a', "I'm going with my gut. {b}."]] },
    { id: 'sf2.11', when: { of: 'several' }, stage: 'Several {side} step forward for {a}, and the fire pit goes quiet.', turns: [['a', "I've had my eye on one person since I walked in. {b}."], ['b', "I was hoping you'd say that."]] },
    { id: 'sf2.12', when: { of: 'several' }, stage: 'More than one {sideOne} steps forward, and {a} takes a long time to decide.', turns: [['a', "Can I have a minute?"], ['a', "Okay. {b}."]], beat: 'One of the {side} left in the line rolls her eyes.' },
    { id: 'sf2.13', when: { of: 'several' }, stage: '{a} looks along the line of {side} who stepped forward.', turns: [['a', "This is the best and worst moment of my life."], ['a', "{b}, would you be my partner?"], ['b', "Go on, then."]] },
    { id: 'sf2.14', when: { of: 'several' }, stage: 'The {side} step forward for {a}, and {a} goes straight to {b}.', turns: [['a', "Sorry. There was never really a choice."], ['b', "Good answer."]] },
    { id: 'sf2.15', when: { of: 'several' }, stage: 'Several {side} step forward, and {a} laughs nervously.', turns: [['a', "I feel like I'm going to make enemies whatever I do."], ['a', "{b}."]], beat: '{a} is right about the enemies, for tonight at least.' },
    { id: 'sf2.16', when: { of: 'several' }, stage: '{a} walks along the {side} who stepped forward, and stops at {b}.', turns: [['a', "You. If that's okay."], ['b', "It's more than okay."]] },
    { id: 'sf2.17', when: { of: 'nobody' }, stage: '{a} walks in, waits, and nobody steps forward.', turns: [['a', "Not even one? Wow."]], beat: '{a} laughs, but goes a bit red.' },
    { id: 'sf2.18', when: { of: 'nobody' }, stage: 'Not one {sideOne} steps forward for {a}.', turns: [['a', "That's fine. I'm a grower, not a shower."]], beat: 'That gets a laugh, at least.' },
    { id: 'sf2.19', when: { of: 'nobody' }, stage: '{a} comes down the steps. Nobody moves.', turns: [['a', "Was it the shirt? It's the shirt, isn't it."]] },
    { id: 'sf2.20', when: { of: 'nobody' }, stage: '{a} waits at the fire pit, and the line of {side} stays exactly where it is.', turns: [['a', "Right. I'll just wait over there, then."]], beat: '{a} goes and stands at the side, trying hard to look relaxed.' },
    { id: 'sf2.21', when: { of: 'nobody' }, stage: 'Nobody steps forward for {a}, and the silence goes on a bit too long.', turns: [['a', "This is fine. This is character building."]] },
    { id: 'sf2.22', when: { of: 'nobody' }, stage: '{a} walks in with a big smile, and nobody steps forward.', turns: [['a', "Okay. Well. You'll all be sorry when you get to know me."]], beat: 'A couple of the {side} look like they might be.' },
    { id: 'sf2.23', when: { of: 'nobody' }, stage: 'The {side} look at {a}, and at each other, and nobody moves.', turns: [['a', "Honestly, that's the most nervous I've ever been, for nothing."]] },
    { id: 'sf2.24', when: { of: 'nobody' }, stage: 'Nobody steps forward for {a}.', turns: [['a', "No? Nobody? Okay."]], beat: 'The host gives {a} a sympathetic little smile.' },
  ],
  // step-last [a, b]: girl a and boy b, put together at the end.
  'step-last': [
    { id: 'sl2.01', stage: 'That leaves {a} and {b}, and nobody else to choose from.', turns: [['b', "So. It's us."], ['a', "It's us. Don't look so worried."]] },
    { id: 'sl2.02', stage: '{a} and {b} are the last two standing, and they couple up.', turns: [['a', "I'll be honest, I'm not sure about this."], ['b', "Neither am I. Let's see."]], beat: 'They stand together, not quite touching.' },
    { id: 'sl2.03', stage: '{b} walks over to {a}, the only {sideOne} left.', turns: [['b', "I would have picked you anyway."], ['a', "You're only saying that."], ['b', "Maybe. Let's find out."]] },
    { id: 'sl2.04', stage: 'The last couple of the night is {a} and {b}.', turns: [['a', "At least we'll have a lot to talk about."], ['b', "Like how nobody wanted us?"], ['a', "Like that."]] },
    { id: 'sl2.05', stage: '{a} and {b} end up together, by default.', turns: [['b', "Well, this wasn't the plan."], ['a', "Plans are overrated."]] },
    { id: 'sl2.06', stage: '{b} and {a} are the last two at the fire pit.', turns: [['a', "Hi. I think we're stuck with each other."], ['b', "There are worse people to be stuck with."]] },
  ],
  // dump-goodbye [a, b] / [a]: b hugs a (who is leaving) goodbye / a to everyone.
  'dump-goodbye': [
    { id: 'dg2.01', when: { withB: true }, turns: [['a', "Don't let them forget me."], ['b', "Nobody could forget you."]], beat: 'They hold on to each other for a long time.' },
    { id: 'dg2.02', when: { withB: true }, turns: [['b', "I'll call you the minute I'm out."], ['a', "You'd better. Every day."]] },
    { id: 'dg2.03', when: { withB: true }, turns: [['a', "I only got to know you properly this week. That's the worst part."], ['b', "We've got all the time in the world outside."]] },
    { id: 'dg2.04', when: { withB: true }, turns: [['b', "This place won't be the same without you."], ['a', "Good. Make it worse."]], beat: 'They both laugh through the tears.' },
    { id: 'dg2.05', when: { withB: true }, turns: [['b', "You were the best person in here."], ['a', "Stop it, or I'll never leave."]] },
    { id: 'dg2.06', when: { withB: true }, turns: [['a', "Don't let anyone mess you about once I'm gone."], ['b', "I won't. I'll have you on the phone to tell me off."]] },
    { id: 'dg2.07', when: { withB: true }, turns: [['b', "I'm so sorry."], ['a', "Don't be. You didn't do anything."]] },
    { id: 'dg2.08', when: { withB: true }, turns: [['a', "Don't cry. You'll set me off."], ['b', "Too late."]] },
    { id: 'dg2.09', when: { withB: true }, turns: [['b', "I don't know what I'm going to do without you in the mornings."], ['a', "Sleep in, probably."]] },
    { id: 'dg2.10', when: { withB: true }, turns: [['a', "Tell them I said goodbye properly. I haven't got time to do everyone."], ['b', "I'll tell them."]] },
    { id: 'dg2.11', when: { withB: false }, stage: '{a} hugs everyone at the fire pit, one at a time.', turns: [['a', "I've had the best time. I mean it. Thank you, all of you."]] },
    { id: 'dg2.12', when: { withB: false }, stage: '{a} picks up the suitcase and turns round at the steps.', turns: [['a', "Don't do anything I wouldn't do. That leaves you quite a lot."]] },
    { id: 'dg2.13', when: { withB: false }, stage: '{a} waves from the top of the steps.', turns: [['a', "Go and get your person, all of you. I'll be watching."]] },
    { id: 'dg2.14', when: { withB: false }, stage: 'The villa gathers round as {a} leaves.', turns: [['a', "No tears. I said no tears. Okay, a few tears."]] },
  ],
  // date [a, b]: new arrival a on a date with b.
  date: [
    { id: 'dt2.01', stage: 'The date is on a boat.', turns: [['a', "So why did you say yes to this date?"], ['b', "Honestly? Curiosity."], ['a', "I can work with curiosity."]] },
    { id: 'dt2.02', stage: 'A picnic on a hill above the villa.', turns: [['a', "Tell me about the villa. Who should I watch out for?"], ['b', "Me, probably."]] },
    { id: 'dt2.03', stage: 'The date is at a rooftop bar.', turns: [['a', "I've been watching you on the show for weeks."], ['b', "That's not creepy at all."], ['a', "It's a little bit creepy."]] },
    { id: 'dt2.04', stage: 'A cooking class, and neither of them can cook.', turns: [['b', "Is it meant to be on fire?"], ['a', "Probably not."]], beat: 'They laugh the whole way through.' },
    { id: 'dt2.05', stage: 'On the date, at a beach bar.', turns: [['a', "Are you open to meeting someone new?"], ['b', "I'm in a couple."], ['a', "That's not what I asked."]] },
    { id: 'dt2.06', stage: 'A quiet table in a little restaurant by the harbour.', turns: [['a', "I picked you because you looked like you'd be honest with me."], ['b', "I'll try. Ask me anything."]] },
    { id: 'dt2.07', stage: 'The date is a go-karting track.', turns: [['b', "You cheated!"], ['a', "I won. That's different."]] },
    { id: 'dt2.08', stage: 'The date is by a pool with a view of the sea.', turns: [['a', "I didn't think you'd be this easy to talk to."], ['b', "Is that a compliment?"], ['a', "It's a warning."]] },
    { id: 'dt2.09', stage: 'At a wine tasting that neither of them takes seriously.', turns: [['a', "I think this one tastes of… wine."], ['b', "You're a natural."]] },
    { id: 'dt2.10', stage: 'On the date, the conversation keeps drying up.', turns: [['a', "So… do you like it in there?"], ['b', "Yeah. It's good."]], beat: 'They both reach for their drinks at the same time.' },
    { id: 'dt2.11', stage: 'The date is on a clifftop at sunset.', turns: [['b', "This is a lot for a first date."], ['a', "Too much?"], ['b', "Just enough."]] },
    { id: 'dt2.12', stage: 'A date at an ice cream stall on the seafront.', turns: [['a', "What flavour are you?"], ['b', "What does that even mean?"], ['a', "I'm not sure. I panicked."]] },
  ],
  // notes [a, b]: a wrote an anonymous note about b; `guessed`.
  notes: [
    { id: 'nt2.01', when: { guessed: true }, stage: 'The note about {b} says they are playing a game.', turns: [['b', "I know exactly who wrote that."]], beat: '{b} stares straight at {a}.' },
    { id: 'nt2.02', when: { guessed: false }, stage: 'A note is read out: someone thinks {b} is fake.', turns: [['b', "Fake? I've been nothing but myself."]], beat: '{a} keeps very still.' },
    { id: 'nt2.03', when: { guessed: false }, stage: "The note says {b} is only nice to the people who can help them.", turns: [['b', "That's not true. That's really not true."]] },
    { id: 'nt2.04', when: { guessed: true }, stage: 'A note says {b} talks behind people\'s backs.', turns: [['b', "Funny, coming from you."], ['a', "What makes you think it was me?"]] },
    { id: 'nt2.05', when: { guessed: false }, stage: 'The note about {b} is read out, and the fire pit goes quiet.', turns: [['b', "Right. Well. I'll be thinking about that all night now."]], beat: 'Nobody meets {b.posAdj} eye, including {a}.' },
    { id: 'nt2.06', when: { guessed: false }, stage: 'A note says {b} has been flirting with someone behind closed doors.', turns: [['b', "That's a lie. That's a complete lie."]], beat: 'Several people look at {b} anyway.' },
  ],
  // heart-rate [a, b]: b set a's heart going most (`coupled` or not).
  'heart-rate': [
    { id: 'hr2.01', when: { coupled: true }, stage: "{a}'s heart rate climbs the second {b} walks over.", turns: [['a', "That's normal. That's completely normal."]] },
    { id: 'hr2.02', when: { coupled: true }, stage: "The monitor spikes for {b}, and {a} looks relieved.", turns: [['a', "Thank God. Imagine if it had been someone else."]] },
    { id: 'hr2.03', when: { coupled: false, taken: true }, stage: "{a}'s monitor goes wild for {b}. {pa} goes very quiet.", turns: [['a', "It's the dancing. Anyone would react to that dancing."]] },
    { id: 'hr2.04', when: { coupled: false, taken: true }, stage: "{a}'s heart rate is highest for {b}, and everyone sees the number.", turns: [['a', "Machines can be wrong. That machine is wrong."]] },
    { id: 'hr2.05', when: { coupled: false, taken: false }, stage: "{a}'s monitor spikes for {b}.", turns: [['a', "Okay. Well. Now I have to say something, don't I?"]] },
    { id: 'hr2.06', when: { coupled: false, taken: false }, stage: "{b} dances for {a}, and the number goes off the scale.", turns: [['a', "Stop. Please stop. I can't breathe."]] },
  ],
  // recouple-pick [a, b, (c)]: a picks b, for the `reason` that carried it.
  'recouple-pick': [
    { id: 'rp2.01', when: { reason: 'connection' }, turns: [['a', "The person I'm choosing tonight is the first person I want to talk to every morning. {b}."]] },
    { id: 'rp2.02', when: { reason: 'connection' }, turns: [['a', "We've had our ups and downs, but I've never doubted how I feel. It's {b}."]] },
    { id: 'rp2.03', when: { reason: 'connection' }, turns: [['a', "This person gets me without me having to explain. {b}."]], beat: '{b} is already smiling.' },
    { id: 'rp2.04', when: { reason: 'attraction' }, turns: [['a', "From the second I saw this person, I couldn't stop looking. {b}."]] },
    { id: 'rp2.05', when: { reason: 'attraction' }, turns: [['a', "I'm going with my gut, and my gut says {b}."]] },
    { id: 'rp2.06', when: { reason: 'attraction' }, turns: [['a', "There's a spark there I can't ignore. I want to see where it goes. {b}."]] },
    { id: 'rp2.07', when: { reason: 'safety' }, turns: [['a', "This person has been a really good friend to me in here, and I trust them. {b}."]], beat: '{b} gives a small, polite smile.' },
    { id: 'rp2.08', when: { reason: 'safety' }, turns: [['a', "I don't know where this will go, but I know I'll be looked after. {b}."]] },
    { id: 'rp2.09', when: { reason: 'safety' }, turns: [['a', "We get on really well, and I think we could be something. {b}."]] },
    { id: 'rp2.10', when: { reason: 'loyalty' }, turns: [['a', "I said I'd stick by this person, and I meant it. {b}."]] },
    { id: 'rp2.11', when: { reason: 'loyalty' }, turns: [['a', "People have tried to turn my head. It hasn't worked. {b}, it's you."]] },
    { id: 'rp2.12', when: { reason: 'loyalty' }, turns: [['a', "Nothing's changed for me. I'm choosing {b}, again."]] },
  ],
  // snog-marry-pie [a, b, c, d]: a snogs b, marries c, pies d (`full`).
  'snog-marry-pie': [
    { id: 'smp2.01', when: { full: true }, turns: [['a', "Pie first, because I've been waiting all day. {d}."], ['a', "Snog, {b}. Marry, {c}."]], beat: '{d} did not see it coming, and wipes the cream off slowly.' },
    { id: 'smp2.02', when: { full: true }, turns: [['a', "This is so hard. Okay. Marry {c}, because {c} makes me laugh."], ['a', "Snog {b}. And {d}, come here."]], beat: '{d} gets up, knowing exactly what is coming.' },
    { id: 'smp2.03', when: { full: true, taken: true }, turns: [['a', "I'm marrying {c}. The snog is {b}, and that's all I'll say about that."], ['a', "Pie, {d}."]], beat: '{pa} does not laugh along.' },
    { id: 'smp2.04', when: { full: true }, turns: [['a', "{d}, you know why. Pie."]], beat: '{d} does know why, and the cream goes everywhere.' },
  ],
};

// ── feelings.js and ladder.js pools ─────────────────────────────────────
export const MORE_FEELINGS = {
  // advice [a, b, c]: a tells friend b what a thinks of b's partner c.
  advice: [
    { id: 'ad2.01', when: { verdict: 'good' }, turns: [['a', "You're different since you coupled up with {c}. In a good way."], ['b', "Am I?"], ['a', "You smile more. You don't notice it, but everyone else does."]] },
    { id: 'ad2.02', when: { verdict: 'good' }, turns: [['b', "Am I mad for being this into {c} already?"], ['a', "No. I'd be more worried if you weren't."]] },
    { id: 'ad2.03', when: { verdict: 'good' }, turns: [['a', "I was wrong about {c}, by the way."], ['b', "What did you think?"], ['a', "That {c} was playing a game. I don't think that any more."]] },
    { id: 'ad2.04', when: { verdict: 'good' }, turns: [['b', "Should I tell {c} how I feel?"], ['a', "Tonight. Don't wait for a better moment. There isn't one."]] },
    { id: 'ad2.05', when: { verdict: 'good' }, turns: [['a', "{c} asked me what you're like when you're sad."], ['b', "What did you say?"], ['a', "The truth. And {c} listened to every word."]] },
    { id: 'ad2.06', when: { verdict: 'bad' }, turns: [['a', "I've watched {c} when you're not around."], ['b', "And?"], ['a', "It's a different person. That's all I'll say."]], beat: '{b} does not ask for more, and thinks about it all day.' },
    { id: 'ad2.07', when: { verdict: 'bad' }, turns: [['b', "You don't like {c}, do you?"], ['a', "I don't like how {c} treats you. That's different."]] },
    { id: 'ad2.08', when: { verdict: 'bad' }, turns: [['a', "Do you actually feel happy with {c}? Or just safe?"], ['b', "Why can't it be both?"], ['a', "It can. I just don't think it is."]] },
    { id: 'ad2.09', when: { verdict: 'bad' }, turns: [['a', "You keep making excuses for {c}."], ['b', "I don't."], ['a', "You just did one. Before I'd even finished."]] },
    { id: 'ad2.10', when: { verdict: 'bad' }, turns: [['b', "Just tell me what you think."], ['a', "I think you'd be happier on your own than with {c}."]], beat: '{b} does not speak to {a} for the rest of the afternoon.' },
    { id: 'ad2.11', when: { verdict: 'unsure' }, turns: [['b', "I can't read {c} at all."], ['a', "Neither can I. Which is probably worth talking about."]] },
    { id: 'ad2.12', when: { verdict: 'unsure' }, turns: [['a', "Can I ask you something? Do you like {c}, or do you like having someone?"], ['b', "…I don't know."], ['a', "That's alright. Just work it out before the next recoupling."]] },
    { id: 'ad2.13', when: { verdict: 'unsure' }, turns: [['b', "Everyone keeps saying {c} is great."], ['a', "What do you say?"], ['b', "I say {c} is great. I just don't feel it yet."]] },
    { id: 'ad2.14', when: { verdict: 'unsure' }, turns: [['a', "Give it a few more days with {c}. If nothing changes, you'll know."], ['b', "And if something does?"], ['a', "Then you'll know that too."]] },
  ],
};

export const MORE_LADDER = {
  // keeping-open [a, b]: a tells partner b the door is still open.
  'keeping-open': [
    { id: 'ko2.01', turns: [['a', "I'm not saying no. I'm saying not yet."], ['b', "How long is not yet?"], ['a', "I don't know. That's the honest answer."]], beat: '{b} goes to bed early.' },
    { id: 'ko2.02', turns: [['a', "If someone new walks in, I want to be able to talk to them."], ['b', "Talk. Right."], ['a', "Just talk."]] },
    { id: 'ko2.03', turns: [['a', "I've been hurt before by rushing. I'm not doing it again."], ['b', "I get that. I just wish it wasn't me paying for it."]] },
    { id: 'ko2.04', turns: [['a', "You're the one I'm most interested in. I'm just not closed off."], ['b', "Most interested. Okay."]], beat: '{b} repeats it to a friend later, twice.' },
    { id: 'ko2.05', turns: [['b', "Are you keeping your options open?"], ['a', "A little bit. Is that bad?"], ['b', "It's not bad. It's just not what I wanted to hear."]] },
    { id: 'ko2.06', when: { feels: 'little' }, turns: [['a', "I don't think I'm ready to close off."], ['b', "Honestly, me neither."]], beat: 'They shake on it, which is not very romantic.' },
    { id: 'ko2.07', when: { attachment: 'anxious' }, turns: [['a', "I just want to see what else is out there."], ['b', "So I'm not enough."], ['a', "That's not what I said."]], beat: '{b} does not believe it all evening.' },
    { id: 'ko2.08', when: { late: true }, turns: [['b', "We're this far in and you're still open?"], ['a', "I know how it sounds."], ['b', "I don't think you do."]] },
  ],
};
