// more-c — a third pool for the two scenes the villa has most of (user: "add
// more to pull and friendship"). After more-a, friendship still played 210
// times a season from 117 scenes and a pull 177 from 80. Casts as more-a:
// friendship [a, b] two islanders who are not a couple; pull [a, b] a pulls b.
// Spread over mood, persona, phase and who is taken, so no one context
// carries the whole pool; the friction is written in with the warmth.

export const MORE_C = {
  friendship: [
    { id: 'fr3.01', turns: [['a', "Do you want the last of the sun cream?"], ['b', "You have it. You're already going pink."]] },
    { id: 'fr3.02', turns: [['a', "I've worked out your laugh. You have a real one and a polite one."], ['b', "Which one do you get?"], ['a', "The real one. I checked."]] },
    { id: 'fr3.03', turns: [['a', "What did you want to be when you were little?"], ['b', "A vet. Then I found out about the blood."]] },
    { id: 'fr3.04', turns: [['a', "Can you hold my drink? I'm going in the pool."], ['b', "You're going in the pool with your hair like that?"], ['a', "…Hold my drink and talk me out of it."]] },
    { id: 'fr3.05', turns: [['a', "What's the first thing you'll eat when you get out?"], ['b', "A takeaway, in bed, on my own."], ['a', "That's beautiful."]] },
    { id: 'fr3.06', turns: [['a', "Thank you for yesterday."], ['b', "What did I do?"], ['a', "You sat with me when nobody else noticed."]], beat: '{b} squeezes {a.posAdj} hand.' },
    { id: 'fr3.07', turns: [['a', "I think the others think we're a couple."], ['b', "We'd be a terrible couple."], ['a', "The worst. We'd argue about the dishes."]] },
    { id: 'fr3.08', turns: [['a', "Play me at cards."], ['b', "You'll lose."], ['a', "I always lose. I like the chat."]], beat: '{a} loses, three times in a row.' },
    { id: 'fr3.09', turns: [['a', "Can you plait my hair?"], ['b', "I can do one plait. It'll be a wonky one."], ['a', "Perfect."]] },
    { id: 'fr3.10', turns: [['a', "Do you think we'd have been friends outside?"], ['b', "No. And that's a shame, because we're great."]] },
    { id: 'fr3.11', turns: [['a', "What's the worst date you've ever been on?"], ['b', "They brought their ex."], ['a', "No."], ['b', "To the date. As a friend."]] },
    { id: 'fr3.12', turns: [['a', "Can I ask you for advice about my couple?"], ['b', "Only if you're going to take it this time."]] },
    { id: 'fr3.13', turns: [['a', "You're the only one who doesn't laugh at my singing."], ['b', "I'm laughing on the inside."]] },
    { id: 'fr3.14', turns: [['a', "Let's make breakfast for everyone."], ['b', "For everyone? That's twenty eggs."], ['a', "Then we'd better start."]], beat: 'They burn about half of them, and nobody minds.' },
    { id: 'fr3.15', turns: [['a', "I'm so glad you're here."], ['b', "In the villa, or right now?"], ['a', "Both."]] },
    { id: 'fr3.16', turns: [['a', "Is it bad that I don't miss my phone at all?"], ['b', "Give it a week."]] },
    { id: 'fr3.17', turns: [['a', "Swap tops with me tonight."], ['b', "Mine won't fit you."], ['a', "It'll fit if I believe in it."]] },
    { id: 'fr3.18', turns: [['a', "I need a pep talk."], ['b', "You're great. You look great. Go and get what you want."], ['a', "Thank you. That was very short."], ['b', "It's a short day."]] },
    { id: 'fr3.19', turns: [['a', "Who do you think goes home next?"], ['b', "I'm not doing this."], ['a', "Just a guess."], ['b', "I'm really not doing this."]] },
    { id: 'fr3.20', turns: [['a', "You did my make-up so well last night."], ['b', "I'll do it again tonight. Sit down."]] },
    { id: 'fr3.21', turns: [['a', "Why does it feel like we've known each other for years?"], ['b', "Because a day in here is about a month outside."]] },
    { id: 'fr3.22', turns: [['a', "I'll be honest. I thought you were a bit stuck-up at first."], ['b', "And now?"], ['a', "Now I know you're just shy."]] },
    { id: 'fr3.23', turns: [['a', "Can we have a lie-in tomorrow? Just us, no couples."], ['b', "The host will have something planned. There's always something planned."]] },
    { id: 'fr3.24', turns: [['a', "Tell me something nobody in here knows about you."], ['b', "I can't swim very well."], ['a', "You've been in the pool every day!"], ['b', "In the shallow end."]] },
    // the friction between friends
    { id: 'fr3.25', turns: [['a', "You didn't stick up for me at the fire pit."], ['b', "I didn't think you needed me to."], ['a', "I did."]], beat: '{b} opens {b.posAdj} mouth, and does not find anything to say.' },
    { id: 'fr3.26', turns: [['a', "I heard what you said about me in the kitchen."], ['b', "It wasn't like that."], ['a', "Then what was it like?"]], beat: 'They do not sit together at dinner.' },
    { id: 'fr3.27', turns: [['a', "You always make everything about you."], ['b', "That's not true."], ['a', "You're doing it right now."]] },
    { id: 'fr3.28', turns: [['a', "Why am I always the last to know things in here?"], ['b', "I was going to tell you."], ['a', "When?"]] },
    { id: 'fr3.29', turns: [['a', "Can I be honest? You've been a bit much today."], ['b', "Wow. Okay. Thanks."]], beat: '{b} goes and sits on the other side of the pool.' },
    { id: 'fr3.30', turns: [['a', "You gave my advice to someone else and took the credit."], ['b', "It was good advice."], ['a', "It was my advice."]] },
    { id: 'fr3.31', turns: [['a', "I feel like I'm the one who always comes to you."], ['b', "You're right. I'm sorry. I'll do better."]], beat: 'They hug, and it helps a little.' },
    { id: 'fr3.32', turns: [['a', "Are we okay?"], ['b', "Why wouldn't we be?"], ['a', "Because you've barely said a word to me since yesterday."]] },
    { id: 'fr3.33', turns: [['a', "Did you borrow my top?"], ['b', "I was going to give it back."], ['a', "You wore it on a date."]] },
    { id: 'fr3.34', turns: [['a', "You laughed when they were having a go at me."], ['b', "I laughed at the joke, not at you."], ['a', "It felt like at me."]], beat: '{b} says sorry, and {a} says it is fine, and it is not quite.' },
    { id: 'fr3.35', turns: [['a', "I don't want to fall out over a sunbed."], ['b', "Then give me the sunbed."]], beat: 'Neither of them moves, and the afternoon is spent in silence.' },
    // gated
    { id: 'fr3.36', when: { phase: 'morning' }, turns: [['a', "Why are you up so early?"], ['b', "Couldn't sleep. Want a tea?"], ['a', "Only if you make it."]] },
    { id: 'fr3.37', when: { phase: 'morning' }, turns: [['a', "Morning. Did you hear the row last night?"], ['b', "The whole villa heard the row last night."]] },
    { id: 'fr3.38', when: { phase: 'day' }, turns: [['a', "It's too hot to move."], ['b', "Then don't. I'll bring the water."]] },
    { id: 'fr3.39', when: { phase: 'evening' }, turns: [['a', "Zip me up?"], ['b', "Breathe in."], ['a', "I am breathing in."]] },
    { id: 'fr3.40', when: { phase: 'evening' }, turns: [['a', "Whatever happens tonight, come and find me after."], ['b', "I'll be right there."]] },
    { id: 'fr3.41', when: { early: true }, turns: [['a', "I don't know anyone yet. Can I stick with you for a bit?"], ['b', "Please do. I don't know anyone either."]] },
    { id: 'fr3.42', when: { early: true }, turns: [['a', "Who have you got your eye on?"], ['b', "Too early. Ask me in a week."]] },
    { id: 'fr3.43', when: { late: true }, turns: [['a', "Remember when we didn't even like each other?"], ['b', "I always liked you. I just didn't say so."]] },
    { id: 'fr3.44', when: { late: true }, turns: [['a', "It's going to be so strange waking up without you."], ['b', "I'll call you every morning. You'll be sick of me."]] },
    { id: 'fr3.45', when: { mood: 'heartbroken' }, turns: [['b', "Do you want to talk about it, or do you want me to take your mind off it?"], ['a', "The second one. Please."]], beat: '{b} tells {a} a very long story about a holiday, and it works.' },
    { id: 'fr3.46', when: { mood: 'heartbroken' }, turns: [['a', "I feel so stupid."], ['b', "You're not stupid. You liked someone. That's allowed."]] },
    { id: 'fr3.47', when: { mood: 'lonely' }, turns: [['a', "I feel like I'm on the outside of everything."], ['b', "Then come inside it. Sit here."]] },
    { id: 'fr3.48', when: { mood: 'jealous' }, turns: [['a', "They were laughing together for ages."], ['b', "People laugh. It doesn't mean anything yet."], ['a', "Yet."]] },
    { id: 'fr3.49', when: { mood: 'stressed' }, turns: [['a', "I don't know if I'm safe tonight."], ['b', "Nobody knows. Let's not spend the whole day guessing."]] },
    { id: 'fr3.50', when: { mood: 'secure' }, turns: [['a', "I'm actually really happy in here."], ['b', "I can tell. You're annoying about it."]] },
    { id: 'fr3.51', when: { taken: true }, turns: [['a', "Is it bad that I sometimes want a break from my couple?"], ['b', "No. That's what I'm for."]] },
    { id: 'fr3.52', when: { taken: true }, turns: [['a', "Do you think {pa} is as into it as I am?"], ['b', "I think {pa} lights up when you walk in."]] },
    { id: 'fr3.53', when: { bTaken: true }, turns: [['a', "How's it going with {pb}?"], ['b', "Good. Really good. I'm scared of how good."]] },
    { id: 'fr3.54', when: { bTaken: true }, turns: [['a', "I've not seen you all day. Is {pb} keeping you busy?"], ['b', "Sorry. I'll make it up to you."], ['a', "You'd better."]] },
    { id: 'fr3.55', when: { gender: 'f', bGender: 'f' }, turns: [['a', "If I get dumped, you're keeping my shoes."], ['b', "You're not getting dumped. But yes, I'm keeping the shoes."]] },
    { id: 'fr3.56', when: { gender: 'm', bGender: 'm' }, turns: [['a', "Do you want to do a workout?"], ['b', "Honestly, I want to sit here and talk about my feelings."], ['a', "…Yeah. Me too."]] },
    { id: 'fr3.57', when: { gender: 'm', bGender: 'm' }, turns: [['a', "You alright? You've gone quiet."], ['b', "Just missing home a bit."], ['a', "Come here."]], beat: 'They sit on the steps for a while, not saying much.' },
    { id: 'fr3.58', when: { persona: 'messy' }, turns: [['a', "Okay, don't be angry, but I might have said something."], ['b', "What did you say?"], ['a', "Something. To someone."]] },
    { id: 'fr3.59', when: { persona: 'wallflower' }, turns: [['b', "You don't have to talk. We can just sit."], ['a', "Thank you. I like just sitting."]] },
    { id: 'fr3.60', when: { persona: 'girls-girl' }, turns: [['a', "If anyone in here upsets you, you tell me first."], ['b', "And what will you do?"], ['a', "Talk to them. Very calmly. Very close to their face."]] },
  ],
  pull: [
    { id: 'pl3.01', turns: [['a', "I brought you a drink."], ['b', "I've already got one."], ['a', "Now you've got two."]] },
    { id: 'pl3.02', turns: [['a', "Can I ask what you're looking for in here?"], ['b', "Someone honest."], ['a', "Then I'll be honest. I like you."]] },
    { id: 'pl3.03', turns: [['a', "You keep catching me looking at you."], ['b', "You keep looking at me."]] },
    { id: 'pl3.04', turns: [['a', "I don't want to play games. I'd just like to get to know you."], ['b', "Okay. Ask me something."], ['a', "What makes you laugh?"]] },
    { id: 'pl3.05', turns: [['a', "Can I sit here?"], ['b', "There are other sunbeds."], ['a', "They don't have you on them."]], beat: '{b} rolls {b.posAdj} eyes, and moves over.' },
    { id: 'pl3.06', turns: [['a', "What's your perfect first date?"], ['b', "Somewhere quiet. Good food. No phones."], ['a', "Well, we've got the no phones."]] },
    { id: 'pl3.07', turns: [['a', "I'm not very good at this."], ['b', "At what?"], ['a', "Telling someone I like them."], ['b', "You just did."]] },
    { id: 'pl3.08', turns: [['a', "I was going to wait for the right moment."], ['b', "And this is it?"], ['a', "It's the only moment nobody else is here."]] },
    { id: 'pl3.09', turns: [['a', "I'd like to take you for a chat. Just us."], ['b', "Go on, then. Where?"], ['a', "The swing seat."]], beat: 'They swing slowly, and talk until dinner.' },
    { id: 'pl3.10', turns: [['a', "Is there anyone in here you'd turn your head for?"], ['b', "Maybe."], ['a', "Is it me?"], ['b', "Maybe."]] },
    { id: 'pl3.11', turns: [['a', "Can I show you something?"], ['b', "What?"], ['a', "The view from the terrace. Nobody ever goes up there."]] },
    { id: 'pl3.12', turns: [['a', "I've got a question, and you have to be honest."], ['b', "Okay."], ['a', "Have you thought about me at all?"], ['b', "Once or twice."]] },
    { id: 'pl3.13', turns: [['a', "You're really easy to talk to."], ['b', "So are you."], ['a', "That's a start."]] },
    { id: 'pl3.14', turns: [['a', "Would you ever go on a date with someone like me?"], ['b', "What's someone like you?"], ['a', "Nervous, apparently."]] },
    { id: 'pl3.15', turns: [['a', "Can we get to know each other properly?"], ['b', "We can get to know each other a little bit. Let's see."]] },
    { id: 'pl3.16', turns: [['a', "I like how you are with everyone."], ['b', "How am I?"], ['a', "Kind. Even when nobody's looking."]] },
    { id: 'pl3.17', turns: [['a', "Do you want to help me make dinner?"], ['b', "Is this a pull?"], ['a', "It's a pull with pasta."]] },
    { id: 'pl3.18', turns: [['a', "I'll be straight with you. You're the reason I came over tonight."], ['b', "I thought you came over for the crisps."], ['a', "The crisps were a cover."]] },
    { id: 'pl3.19', turns: [['a', "Tell me three things about you."], ['b', "I hate mornings. I love dogs. I'm a terrible dancer."], ['a', "Two out of three isn't bad."]] },
    { id: 'pl3.20', turns: [['a', "Can I ask for a kiss on the cheek?"], ['b', "That's very forward."]], beat: '{b} gives {a.obj} one anyway.' },
    // the pulls that go badly
    { id: 'pl3.21', turns: [['a', "Can I grab you for a chat?"], ['b', "I'd rather not, if that's okay."]], beat: '{a} laughs it off in front of everyone, and goes quiet after.' },
    { id: 'pl3.22', turns: [['a', "I think we've got a connection."], ['b', "We've spoken twice."], ['a', "Two good times."], ['b', "Two short times."]] },
    { id: 'pl3.23', turns: [['a', "Do you want— sorry. Can I grab you for a chat?"], ['b', "Not right now. Sorry."]], beat: '{a} walks back to the kitchen as if nothing happened.' },
    { id: 'pl3.24', turns: [['a', "I don't get why you're not interested."], ['b', "I don't have to have a reason."], ['a', "I'd just like to know."]], beat: '{b} gets up and leaves.' },
    { id: 'pl3.25', turns: [['a', "Everyone thinks we'd be good together."], ['b', "Everyone isn't me."]] },
    { id: 'pl3.26', turns: [['a', "Can we chat later?"], ['b', "Maybe. I'll see how I feel."]], beat: '{b} spends the rest of the evening with someone else.' },
    { id: 'pl3.27', turns: [['a', "You could at least give me a chance."], ['b', "I did. At lunch. It didn't go well."]] },
    { id: 'pl3.28', turns: [['a', "Why do you keep avoiding me?"], ['b', "Because you keep coming over."]], beat: 'The chat is over before it starts.' },
    { id: 'pl3.29', turns: [['a', "Sorry. I thought you were flirting with me earlier."], ['b', "I was being friendly."], ['a', "Right. Yeah. That makes sense."]], beat: '{a} goes very red.' },
    { id: 'pl3.30', turns: [['a', "I think I'm your type."], ['b', "You're really not."]], beat: 'The garden hears it, and {a} hears the garden hearing it.' },
    { id: 'pl3.31', turns: [['a', "Five minutes?"], ['b', "Two."], ['a', "Two, then."]], beat: 'It lasts two minutes exactly, and neither of them enjoys it.' },
    { id: 'pl3.32', turns: [['a', "What would you say if I told you I liked you?"], ['b', "I'd say thank you."], ['a', "That's it?"], ['b', "That's it."]] },
    // gated
    { id: 'pl3.33', when: { phase: 'morning' }, turns: [['a', "Morning. Coffee?"], ['b', "Is this a pull at eight in the morning?"], ['a', "It's a pull with coffee."]] },
    { id: 'pl3.34', when: { phase: 'day' }, turns: [['a', "Let me put sun cream on your back."], ['b', "Smooth."], ['a', "You'll burn otherwise. It's for your health."]] },
    { id: 'pl3.35', when: { phase: 'evening' }, turns: [['a', "You look gorgeous tonight."], ['b', "You're only saying that because I've made an effort."], ['a', "I'm saying it because it's true."]] },
    { id: 'pl3.36', when: { phase: 'evening' }, turns: [['a', "Can I walk you to the fire pit?"], ['b', "It's ten steps away."], ['a', "The slowest ten steps you've ever taken."]] },
    { id: 'pl3.37', when: { early: true }, turns: [['a', "I know we've only just met, but I wanted to get in first."], ['b', "Before who?"], ['a', "Before anyone else did."]] },
    { id: 'pl3.38', when: { early: true }, turns: [['a', "I didn't get to talk to you last night. I've been thinking about it."], ['b', "We're talking now."]] },
    { id: 'pl3.39', when: { late: true }, turns: [['a', "It's late in the game to be saying this."], ['b', "Then why are you?"], ['a', "Because I'd regret it if I didn't."]] },
    { id: 'pl3.40', when: { late: true }, turns: [['a', "I should have pulled you weeks ago."], ['b', "Why didn't you?"], ['a', "I was scared you'd say no."], ['b', "I might have."]] },
    { id: 'pl3.41', when: { taken: true }, turns: [['a', "I'm in a couple. I know. I just can't stop thinking about you."], ['b', "Then you need to sort out your couple first."]] },
    { id: 'pl3.42', when: { taken: true }, turns: [['a', "{pa} is great. But it's not like this."], ['b', "Like what?"], ['a', "Like I can breathe."]], beat: '{b} does not know what to do with that.' },
    { id: 'pl3.43', when: { taken: true }, turns: [['a', "Don't tell anyone I pulled you."], ['b', "Everyone can see us."], ['a', "Right. Yeah."]] },
    { id: 'pl3.44', when: { bTaken: true }, turns: [['a', "Is {pb} actually making you happy?"], ['b', "That's not your business."], ['a', "I'd like it to be."]] },
    { id: 'pl3.45', when: { bTaken: true }, turns: [['a', "I'm not trying to split you and {pb} up."], ['b', "Then what are you trying to do?"], ['a', "See if there's a door open."]], beat: '{pb} walks past, very slowly.' },
    { id: 'pl3.46', when: { bTaken: true }, turns: [['a', "Can I steal you from {pb} for a bit?"], ['b', "You can borrow me. Nobody's stealing anything."]] },
    { id: 'pl3.47', when: { bTaken: true }, turns: [['a', "I'll wait, if I have to."], ['b', "Please don't wait for me. I'm happy with {pb}."]], beat: '{a} goes and gets a drink, and does not come back to the daybeds.' },
    { id: 'pl3.48', when: { mood: 'lonely' }, turns: [['a', "I've not had a real chat with anyone in days."], ['b', "Then let's have one."]] },
    { id: 'pl3.49', when: { mood: 'lonely' }, turns: [['a', "Can I talk to you? I'm the only one in here without a couple."], ['b', "You're not the only one. Sit down."]] },
    { id: 'pl3.50', when: { mood: 'jealous' }, turns: [['a', "Did you see my partner with them earlier?"], ['b', "Is that why you've pulled me? To make a point?"], ['a', "…Maybe a little bit."]], beat: '{b} leaves {a} on the daybed.' },
    { id: 'pl3.51', when: { mood: 'heartbroken' }, turns: [['a', "I know it's soon. I just want to talk to someone new."], ['b', "That's okay. We can just talk."]] },
    { id: 'pl3.52', when: { mood: 'secure' }, turns: [['a', "I'm happy in my couple. I just wanted to say you're great."], ['b', "Is this a pull or a compliment?"], ['a', "A compliment. Honestly."]] },
    { id: 'pl3.53', when: { persona: 'hopeless-romantic' }, turns: [['a', "I think I knew the second you walked in."], ['b', "Knew what?"], ['a', "That I'd end up saying something stupid to you."]] },
    { id: 'pl3.54', when: { persona: 'fuckboy' }, turns: [['a', "You and me. Hideaway. Tonight."], ['b', "Wow. Hello to you too."], ['a', "Hello. Hideaway?"]], beat: '{b} laughs, and says no.' },
    { id: 'pl3.55', when: { persona: 'fuckboy' }, turns: [['a', "You're the best-looking person in here."], ['b', "You said that to someone else yesterday."], ['a', "…I was wrong yesterday."]] },
    { id: 'pl3.56', when: { persona: 'wallflower' }, turns: [['a', "I've been trying to come over for about an hour."], ['b', "I saw. You kept walking past."]], beat: '{a} laughs, and relaxes a little.' },
    { id: 'pl3.57', when: { persona: 'checklist' }, turns: [['a', "Can I ask you some questions? I've got a list."], ['b', "You've got a list?"], ['a', "In my head. It's a short list."]] },
    { id: 'pl3.58', when: { persona: 'messy' }, turns: [['a', "I shouldn't be over here, and we both know it."], ['b', "So go back."], ['a', "In a minute."]] },
    { id: 'pl3.59', when: { gender: 'f', bGender: 'm' }, turns: [['a', "You're not going to come over, so I've come to you."], ['b', "I was going to."], ['a', "When?"], ['b', "…At some point."]] },
    { id: 'pl3.60', when: { gender: 'm', bGender: 'f' }, turns: [['a', "I've been told I'm not allowed to be shy, so here I am."], ['b', "Who told you that?"], ['a', "Everyone in the kitchen."]] },
  ],
};
