// More versions of the moments that come back most (measured 2026-09-30:
// tests/ci-repetition.test.js). Data only. Each list joins the pool of the
// same key (lines/index.js merges them), with that pool's slots and facts:
// ratings are said aloud by a about b; a status is a's post; circle.more is
// a, b and c in Circle Chat; the host speaks over a (and b); hangout lines
// are two Influencers about c. American English, the show's own words.
const M = (key, list) => ({ [key]: list.map((x, i) => ({ id: `${key}.m${String(i + 1).padStart(2, '0')}`, ...(typeof x === 'string' ? { turns: [{ by: 'a', say: x }] } : x) })) });
const R = text => ({ turns: [{ by: 'a', react: text }] });
const H = text => ({ turns: [{ by: 'host', say: text }] });

export const MORE_LINES = {
  // ── the ratings, said aloud ──────────────────────────────────────────
  ...M('rate.affection.top', [
    "{b}, first. You've been my safe place in here.",
    "Top spot is {b}. I don't even have to think.",
    "First position, {b}. Every good day in here had {b} in it.",
    "{b} goes first. {b.Sub} made me laugh when I needed it most.",
    "Circle, {b} in first. Loyalty goes both ways.",
    "Number one. {b}. I'd trust {b.obj} with anything.",
    "First is {b}. If I have to go home, I want {b.obj} to know I meant it.",
    "{b} is my first. We clicked on day one and never unclicked.",
    "Top of my list: {b}. Real recognizes real.",
    "{b} in first place. I want {b.obj} to see it and smile.",
    "First is {b}, because {b.sub} checks on me without being asked.",
    "My number one is {b}. No strategy. Just love.",
    "{b}, you're first. You've earned it every single day.",
    "I'm putting {b} first. Friends first, game second.",
    "First place to {b}. That one wasn't even close.",
    "Circle, first position: {b}. Heart over head this time.",
    "{b} tops my list. Talking to {b.obj} is the best part of my day.",
    "{b}. First. I hope {b.sub} knows how much {b.sub} means to me.",
    "Number one is {b}, and I'll say it to anybody who asks.",
    "{b} gets first. Some people just feel like home.",
    "First is {b}. We've had each other's backs since the start.",
    "Top spot, {b}. I'm not changing my mind on that one.",
    "{b} in first. Easiest click of the night.",
    "Circle, please put {b} in first place. I'm team {b} all the way.",
    "{b} goes first. {b.Sub} never once made me feel small in here.",
  ]),
  ...M('rate.affection.bottom', [
    "Last is {b}. We never really talked. That's on both of us.",
    "{b} at the bottom. I don't know {b.obj}, so I can't defend {b.obj}.",
    "Bottom spot: {b}. It's not personal. It's just the least I know.",
    "{b}, last. One chat. One. That's all we ever had.",
    "Circle, {b} in last place. I wish it was somebody else, honestly.",
    "Last goes to {b}. We just never found our thing.",
    "{b} is at the bottom tonight. Maybe we fix that tomorrow.",
    "I'm putting {b} last. Something about {b.obj} feels far away.",
    "Last place, {b}. I barely know what {b.sub} sounds like.",
    "{b} goes last. I tried once. It didn't land.",
    "Circle, last position: {b}. No bad feelings. Just no feelings yet.",
    "{b}. Last. We haven't connected, and I'm out of time to fix it.",
    "Bottom is {b}. I'm sorry. Somebody has to be.",
    "{b} in last. I hope that changes, I really do.",
    "Last place is {b}. We're just different people.",
  ]),
  ...M('rate.threat.bottom', [
    "{b} is playing too well. Last place. I have to.",
    "{b} has too many friends in here. Bottom.",
    "Last is {b}. If {b.sub} gets power, I'm in trouble.",
    "I like {b}. That's exactly why {b.sub} scares me. Last.",
    { turns: [{ by: 'a', say: "{b}, last. You're winning, and I can't let you." }], when: { early: false } },
  ]),
  ...M('rate.middle', [
    "{b} in the middle. {b.Sub} could go either way.",
    "Middle spot for {b}. Ask me again in two days.",
    "{b} lands right in the middle. Fair and square.",
    "Circle, middle for {b}. We're getting there.",
  ]),
  // ── Circle Chat ──────────────────────────────────────────────────────
  ...M('circle.react', [
    R("Oh, {b} is feeling brave."),
    R("{b} with the energy. I see you."),
    R("That's the most {b} message ever typed."),
    R("Wait. Is {b} being serious right now?"),
    R("Okay, {b}. Tell us how you really feel."),
    R("{b} always knows what to say in here. Always."),
    R("Hm. {b} is trying a little too hard."),
    R("{b}, I love you, but read the room."),
    R("Somebody screenshot what {b} just said. Oh wait, we can't."),
    R("I'm laughing. {b} got me with that one."),
  ]),
  ...M('circle.more', [
    { when: { time: 'evening' }, turns: [{ by: 'a', send: "Movie night in every apartment. What are we watching?" }, { by: 'b', send: "Something scary. I want to scream at something that isn't this game" }, { by: 'c', send: "Rom com or nothing {e:hearteyes}" }] },
    { turns: [{ by: 'a', send: "Confession: I've talked to my TV more than to any of you" }, { by: 'b', send: "The TV is a great listener honestly" }, { by: 'c', send: "My fridge knows all my secrets {e:laugh}" }] },
    { turns: [{ by: 'a', send: "Who's the early bird in here? Be honest" }, { by: 'b', send: "Up at 5am doing yoga. Don't hate me" }, { by: 'c', send: "I hate you a little {e:laugh}" }] },
    { turns: [{ by: 'a', send: "Weirdest thing you've eaten in here so far. Go" }, { by: 'b', send: "Peanut butter on a pickle. It was a dare. From myself" }, { by: 'c', send: "That's a crime {e:shock}" }] },
    { turns: [{ by: 'a', send: "If we all met at a party right now, who's on the dance floor first?" }, { by: 'b', send: "Me. Obviously. Already there" }, { by: 'c', send: "I'm by the snacks. Always by the snacks {e:laugh}" }] },
    { turns: [{ by: 'a', send: "Rate your day out of ten. I'm a solid six" }, { by: 'b', send: "Eight! Took a nap. Changed my life" }, { by: 'c', send: "Four. Burned toast. Twice {e:sad}" }] },
    { turns: [{ by: 'a', send: "Okay who else sings to the Circle when nobody's listening" }, { by: 'b', send: "Every single day. Power ballads only" }, { by: 'c', send: "My neighbors can probably hear me {e:grimace}" }] },
    { turns: [{ by: 'a', send: "Unpopular opinion time. Mine: breakfast for dinner is the best dinner" }, { by: 'b', send: "That's not unpopular that's correct" }, { by: 'c', send: "Pancakes at 9pm is a lifestyle {e:clap}" }] },
    { turns: [{ by: 'a', send: "What's everybody wearing right now? I'm in pajamas at 4pm" }, { by: 'b', send: "Full outfit. Nowhere to go. No regrets" }, { by: 'c', send: "Pajama gang rise up {e:laugh}" }] },
    { turns: [{ by: 'a', send: "Shout out to whoever keeps the vibes good in here. You know who you are" }, { by: 'b', send: "Group hug {e:hug}" }, { by: 'c', send: "Circle fam fr {e:heart}" }] },
  ]),
  ...M('circle.leave', [
    R("And I'm out. Circle, close the chat."),
    R("Okay, I've said enough. Maybe too much."),
    R("Circle, exit. I need to think about what just happened."),
    R("That was a lot of people being nice at the same time. Suspicious."),
    R("Leaving the chat. Going to lie on the floor for a bit."),
    R("Okay, I'm done. Circle, take me home."),
  ]),
  // ── statuses ─────────────────────────────────────────────────────────
  ...M('status.low', [
    { turns: [{ by: 'a', post: "Some days are harder than others in here. Still grateful {e:pray}" }] },
    { turns: [{ by: 'a', say: "Be honest, but not too honest.", post: "Quiet day. Missing home a little today {e:sad}" }] },
    { turns: [{ by: 'a', post: "Not every day is a good day and that's okay {e:heart}" }] },
    { turns: [{ by: 'a', post: "Rough night. Coffee is my best friend this morning" }] },
    { turns: [{ by: 'a', say: "Post something real. Just once.", post: "Feeling a little lost today. Anyone else? {e:think}" }] },
    { turns: [{ by: 'a', post: "Didn't sleep. Thinking too much. Classic me {e:sweat}" }] },
    { turns: [{ by: 'a', post: "Taking it slow today. Tomorrow's a new day {e:sun}" }] },
    { turns: [{ by: 'a', post: "Sometimes you just need a long shower and a good cry. Anyway how's everybody's day" }] },
    { turns: [{ by: 'a', say: "Don't look weak. Just look human.", post: "Hard day but still standing {e:muscle}" }] },
    { turns: [{ by: 'a', post: "Missing my people back home so much today {e:heart}" }] },
  ]),
  ...M('status.high', [
    { turns: [{ by: 'a', post: "Good morning to everyone except my alarm clock {e:laugh} {t:GoodMorning}" }] },
    { turns: [{ by: 'a', say: "They put me up top. Stay humble. Mostly.", post: "Grateful for every single one of you {e:heart} {t:Blessed}" }] },
    { turns: [{ by: 'a', post: "Danced in the kitchen this morning. Highly recommend {e:party}" }] },
    { turns: [{ by: 'a', post: "Energy is HIGH today. Who's with me {e:fire}" }] },
  ]),
  ...M('status.steady', [
    { turns: [{ by: 'a', post: "Just a normal day in the Circle. Which means nothing is normal {e:laugh}" }] },
    { turns: [{ by: 'a', post: "Workout done, coffee made, ready for whatever today brings {e:muscle}" }] },
    { turns: [{ by: 'a', say: "Nothing big. Just be there.", post: "Hope everybody's having a good one {e:smile} {t:CircleFam}" }] },
  ]),
  ...M('status.react', [
    R("Aw, {b}. I needed that today."),
    R("{b} always posts at the perfect time."),
    R("That's a very {b} status. I love it."),
    R("Is {b} okay? That felt like a lot."),
    R("Circle, like {b}'s status. Obviously."),
  ]),
  ...M('likes.most', [
    R("People like me. People actually like me."),
    { turns: [{ by: 'a', react: "The most likes? Me? Okay, I'm framing this." }], beat: '{a} takes a picture of the TV with nothing.' },
    R("Top of the Newsfeed. I could get used to this."),
    "Popular is good. Popular is also a target. Enjoy it for five minutes.",
    R("The most likes! Somebody tell my mom!"),
  ]),
  // ── games ────────────────────────────────────────────────────────────
  ...M('game.first', [
    R("A game! Finally, something to do besides refresh the Circle."),
    R("Okay, game time. Nobody panic. Especially me."),
    "Games show who people really are. Watch everybody.",
    R("I love a game. I hate losing a game. Here we go."),
    "Play it cool. Play it fun. Don't give anything away.",
    R("What kind of game? Please be easy. Please be easy."),
    R("Game on! Let's see what everybody's hiding."),
    "This is where people slip. Eyes open.",
    R("A game in the Circle is never just a game."),
    R("Okay, I'm nervous and I don't even know what it is yet."),
  ]),
  ...M('game.make.plan', [
    "I'm going to make it sweet. Sweet wins hearts.",
    "Okay. Art. I can do art. I did finger painting once.",
    "Make it funny. People forgive bad art if it's funny.",
    "I know exactly who I'm doing and exactly how.",
    "Big swing. If it misses, at least it missed big.",
    "Pour my heart into it. Somebody's going to feel something.",
  ]),
  ...M('game.make.comment', [
    R("{b} made that? I didn't know {b} had that in {b.obj}."),
    R("That one's got heart. That one's {b}'s, isn't it?"),
    R("Okay, {b}'s is chaos. Beautiful chaos."),
    R("I would hang {b}'s on my wall. A small wall. In a hallway."),
    R("{b} went for it. I respect somebody who goes for it."),
  ]),
  // ── the party ────────────────────────────────────────────────────────
  ...M('party.nhie', [
    { turns: [{ by: 'a', send: "{q} {e:eyes}" }, { by: 'b', react: "Oh no. Oh, I have.", send: "Okay fine. Yes. Next question {e:grimace}" }] },
    { turns: [{ by: 'a', send: "Here's a spicy one. {q}" }, { by: 'b', send: "Not me! Never! Okay, once" }] },
    { turns: [{ by: 'a', send: "{q} {e:devil}" }, { by: 'b', react: "Do I lie? I'm not going to lie.", send: "Guilty {e:laugh}" }] },
    { turns: [{ by: 'a', send: "Everybody be honest. {q}" }, { by: 'b', send: "Honest answer: absolutely yes {e:shock}" }] },
    { turns: [{ by: 'a', send: "Last one I promise. {q}" }, { by: 'b', send: "Lol you'll never know" }, { by: 'b', react: "They'll never know. They'll never, ever know." }] },
    { turns: [{ by: 'a', send: "Okay this one's for the brave. {q}" }, { by: 'b', send: "Brave? I'm reckless. Yes {e:fire}" }] },
  ]),
  ...M('party.photo', [
    { turns: [{ by: 'a', post: "Theme? Nailed it. Dance moves? Questionable {e:laugh}" }, { by: 'b', react: "{a} is having the best night. Circle, like." }] },
    { turns: [{ by: 'a', say: "One good picture. Just one.", post: "Party mode: ON {e:party}" }, { by: 'b', react: "Look at {a}! Okay!" }] },
    { turns: [{ by: 'a', post: "Me pretending I can dance {e:sweat} {t:CircleParty}" }, { by: 'b', react: "Pretending? That's real talent, {a}." }] },
    { turns: [{ by: 'a', post: "Dressed for the theme and I have regrets {e:laugh}" }, { by: 'b', react: "No regrets, {a}! It's perfect!" }] },
    { turns: [{ by: 'a', post: "This party is better than any party I've been to in real life lol" }, { by: 'b', react: "Same, {a}. Weirdly same." }] },
    { turns: [{ by: 'a', post: "Found my angle {e:sparkle}" }, { by: 'b', react: "{a} found the angle! Circle, like it!" }] },
  ]),
  ...M('party.dance', [
    { turns: [{ by: 'a', say: "Nobody's watching. Everybody's watching. I don't care." }], beat: '{a} spins until {a.sub} nearly falls over.' },
    { turns: [{ by: 'a', react: "The music's up! Clear the living room!" }] },
    { turns: [{ by: 'a', say: "This is my cardio for the day." }], beat: '{a} dances with a throw pillow.' },
    { turns: [{ by: 'a', react: "I'm a terrible dancer. I'm a very enthusiastic terrible dancer." }] },
    { turns: [{ by: 'a', say: "If the Circle could see me now. Oh wait." }], beat: '{a} does a move that is mostly shoulders.' },
  ]),
  // ── the blocking ─────────────────────────────────────────────────────
  ...M('block.wait', [
    R("Just say the name. Just say it."),
    R("My heart is going to come out of my chest."),
    R("Whoever it is, I'm going to cry. Even if it's not me."),
    R("I can't look. Circle, tell me when it's over. You can't. Okay."),
    R("The dots. The dots are the worst part."),
    R("Breathe. You've done everything you can. Breathe."),
    R("If it's me, I'm going out with my head up. Mostly up."),
    R("This is the longest typing in the history of typing."),
  ]),
  ...M('block.react.relief', [
    R("Still here. Still here. Okay."),
    R("That was the worst minute of my life and I'm still standing."),
    { turns: [{ by: 'a', react: "I'm safe. Oh, I'm so sorry, {b}." }], beat: '{a} puts a hand over {a.posAdj} heart.' },
    R("I'm okay. {b} isn't. I don't know how to feel."),
    R("Not me. Tonight, not me."),
  ]),
  ...M('visit.wait', [
    R("If there's a knock, I'm hiding in the shower."),
    R("Please walk past my door. Please keep walking."),
    { turns: [{ by: 'a', react: "Somebody's in the hallway. I can hear them. Or I'm imagining it." }], beat: '{a} presses an ear to the door.' },
    R("I've been nothing but nice to {b}. That's either very good or very bad right now."),
    R("Okay. If it's me, I'm offering {b} a snack. Everybody likes a snack."),
  ]),
  // ── goodbyes ─────────────────────────────────────────────────────────
  ...M('goodbye.guess', [
    { turns: [{ by: 'a', react: "Here it is. {b}'s goodbye. I'm not ready." }], beat: '{a} pulls a blanket up to {a.posAdj} chin.' },
    { turns: [{ by: 'a', react: "Okay, {b}. No surprises. Please, no surprises." }], beat: '{a} sits on the very edge of the couch.' },
    { turns: [{ by: 'a', react: "I really hope {b} was real. I really do." }], beat: '{a} holds a pillow like a shield.' },
    { turns: [{ by: 'a', react: "Whatever {b} says, I'm going to hear it for days." }], beat: '{a} turns the volume down, then back up.' },
    { turns: [{ by: 'a', react: "Moment of truth. Who was {b} really?" }], beat: '{a} leans in close to the screen.' },
    { turns: [{ by: 'a', react: "Play it. No, wait. Okay, play it." }], beat: '{a} takes a deep breath and nods at the TV.' },
    { turns: [{ by: 'a', react: "I talked to {b} every single day. I think I'm going to cry." }], beat: '{a} is already holding a tissue.' },
    { turns: [{ by: 'a', react: "If {b} calls me out in this video, I'm unplugging the TV." }], beat: '{a} eyes the power cord.' },
    { turns: [{ by: 'a', react: "Let's find out if I was right about {b}." }], beat: '{a} crosses {a.posAdj} arms and waits.' },
    { turns: [{ by: 'a', react: "Circle, play {b}'s message. Rip the band-aid off." }], beat: '{a} covers {a.posAdj} eyes, then peeks.' },
  ]),
  ...M('goodbye.react.surprised', [
    { turns: [{ by: 'a', react: "Wow. Okay. I did not have that on my bingo card." }], beat: '{a} stares at the black screen for a long moment.' },
    { turns: [{ by: 'a', react: "{b}, you really got me with that one." }], beat: '{a} wipes {a.posAdj} eyes and laughs at {a.ref}.' },
    { turns: [{ by: 'a', react: "I'm going to miss {b}. I didn't know how much until now." }], beat: '{a} scrolls back through their old chats.' },
    { turns: [{ by: 'a', react: "That's one less voice in Circle Chat. It's going to feel quiet." }], beat: '{a} looks at the empty spot on the Circle.' },
    { turns: [{ by: 'a', react: "{b} was the real deal. What a goodbye." }], beat: '{a} claps at the TV, alone, for a while.' },
  ]),
  // ── the Hangout ──────────────────────────────────────────────────────
  ...M('hangout.view.noBond.keep', [
    { turns: [{ by: 'a', send: "Honestly, {c} hasn't done anything to either of us" }, { by: 'b', send: "True. {c} stays" }] },
    { turns: [{ by: 'a', send: "{c}? I don't see it. Do you?" }, { by: 'b', send: "No. Keep {c}" }, { by: 'a', react: "Good. I didn't want to fight about {c}." }] },
    { turns: [{ by: 'a', send: "Let's not waste a block on {c}" }, { by: 'b', send: "Agreed. Not tonight" }] },
    { turns: [{ by: 'a', send: "What's your read on {c}?" }, { by: 'b', send: "Harmless. Sweet. Not a threat" }, { by: 'a', send: "Same read. Moving on" }] },
    { turns: [{ by: 'a', send: "I actually like {c}. Can we keep {c.obj} out of this?" }, { by: 'b', send: "Yes. {c} is fine" }] },
  ]),
  ...M('hangout.solo.view.noBond.keep', [
    "{c} hasn't given me a single reason. {c} stays.",
    "Not {c}. {c} has been nothing but kind.",
    "{c}? No. That would be about fear, not the game.",
    "I'm leaving {c} alone. {c.Sub} deserves another day.",
    "{c} is safe. I don't even have to think about it.",
  ]),
  // ── the host ─────────────────────────────────────────────────────────
  ...M('host.chat', [
    H("Meanwhile, {a} has opened a private chat with {b}, and a bag of chips with it."),
    H("Next door, {a} is about to slide into {b}'s messages. Carefully."),
    H("{a} has been staring at a blank message to {b} for four minutes. Something's coming."),
    H("Across the hall, {a} needs a word with {b}. Just one. Maybe ten."),
    H("And over here, {a} is typing to {b} in full sentences. That's how you know it's serious."),
    H("{a} is lying on the floor, dictating a message to {b}. Comfort first."),
    H("Meanwhile, {a} decides it's time to check in on {b}."),
    H("Down the hall, {a} has a plan, a message, and {b}'s name at the top of it."),
  ]),
  ...M('host.status', [
    H("Status update time! {a} has three drafts and zero confidence."),
    H("{a} is about to share a status with the whole Circle. No pressure."),
    H("Time for {a}'s status. Every word has been very carefully chosen. By committee. Of one."),
    H("Up next, {a} tells the Circle how the day is going. The Circle is about to find out."),
    H("{a} is posting a status, which means picking a selfie, which means this could take a while."),
    H("Status time for {a}, who is using a very serious face for a very cheerful post."),
    H("{a} wants the Circle to know exactly how {a} is feeling. Mostly."),
    H("Morning status from {a}. Coffee in one hand, remote in the other."),
  ]),
  ...M('host.life', [
    H("With no chats open, {a} has started talking to the plants."),
    H("Meanwhile, {a} is attempting a recipe {a} saw once, a long time ago."),
    H("{a} has a whole afternoon and no idea what to do with it."),
    H("Over in the next apartment, {a} is doing yoga. Some of it is yoga."),
    H("Nobody's messaging {a} right now, so {a} is reorganizing the fridge. Again."),
  ]),
  ...M('host.circle', [
    H("Circle Chat is open! Everybody's about to be very, very friendly."),
    H("The group chat is live, and {a} already has something to say."),
    H("Circle Chat time. Somewhere in this building, somebody is rehearsing a joke."),
    H("It's Circle Chat, which means everybody's typing and nobody's breathing."),
  ]),
  ...M('host.cold.blocking', [
    H("The morning after a blocking. Coffee's strong, smiles are stronger, and nobody trusts anybody."),
    H("Good morning, Circle. The building is one apartment quieter, and everybody noticed."),
    H("A new day in the Circle, and somebody is pacing. Actually, everybody is pacing."),
    H("Rise and shine. Last night's blocking is still on everybody's mind, and in everybody's messages."),
    H("It's the morning after, and {a} is up early, re-reading every chat from yesterday."),
  ]),
  // ── what a says to the empty apartment (lines/asides.js) ─────────────
  ...M('aside.sweet.warm', [
    "I think {b} and I are going to be friends after this. Real friends.",
    "Every chat with {b} makes this place feel smaller in a good way.",
    "That's my person. I'm calling it.",
    "I needed that chat more than {b} knows.",
  ]),
  ...M('aside.sweet.neutral', [
    "It's okay if not every chat is amazing. That one was fine. Fine is good.",
    "{b} is sweet. I just can't read {b.obj} yet.",
    "I'll send {b} something nice tomorrow. No reason.",
    "Not a bad chat. Not a great one. A real one.",
  ]),
  ...M('aside.sweet.cold', [
    "I'm not going to take it personally. I'm going to try not to take it personally.",
    "I just want everybody in here to be okay. Even {b}.",
    "Kill them with kindness. That's all I've got.",
    "Tomorrow I'll try again. That's who I am.",
  ]),
  ...M('aside.wild.warm', [
    "I don't know what I'm doing and it's working. Don't question it.",
    "{b} is my kind of weird. Love that.",
    "Good vibes only! Well. Mostly good vibes.",
    "That was so fun I forgot I'm in a game.",
  ]),
  ...M('aside.wild.neutral', [
    "Okay. What now? I need a snack or a scandal.",
    "Fine chat. I'm going to do something unhinged later to balance it out.",
    "I wanted fireworks and I got a sparkler.",
    "{b} is nice. Nice is boring. I said it.",
  ]),
  ...M('aside.wild.cold', [
    "I'm not mad. I'm just going to rearrange all my furniture.",
    "{b} can keep that energy. I've got more of it.",
    "Deep breath. Deep breath. Okay, one more deep breath.",
    "Whatever. I'll be fine. I'm always fine.",
  ]),
  ...M('aside.schemer.warm', [
    "{b} trusts me now. That took less work than I thought.",
    "Every friend is a vote. I just gained one.",
    "{b} is going to put me first tonight. I can feel it.",
    "Sweet, easy, done. On to the next one.",
  ]),
  ...M('aside.schemer.neutral', [
    "{b} is harder to read than {b.sub} looks. Interesting.",
    "No harm done. I'll come back when {b} needs me.",
    "Patience. {b} will come around. They always do.",
    "Keep it light. Keep them guessing.",
  ]),
  ...M('aside.schemer.cold', [
    "Somebody has to go home. {b} just volunteered.",
    "That's fine. I didn't need {b}. I needed to know where {b} stands.",
    "Cold is information. I'll use it.",
    "{b} made a choice. So will I.",
  ]),
  ...M('aside.romantic.warm', [
    "I'm blushing at a TV. This is where I am in life.",
    "{b}. Just {b}. Okay, I'm done. I'm not done.",
    "If this is how it feels over messages, imagine in person.",
    "I'm going to marry that profile picture. Kidding. Mostly.",
  ]),
  ...M('aside.romantic.neutral', [
    "I'm a hopeless romantic in a building with no hope. Great.",
    "{b} is fun. I don't know if {b.sub} is my fun.",
    "Chemistry takes a few tries. That was try one.",
    "Maybe I'm looking for love in all the wrong apartments.",
  ]),
  ...M('aside.romantic.cold', [
    "Heart, you can stop now. It's not happening.",
    "I'll survive. I'll be dramatic about it, but I'll survive.",
    "{b} isn't interested. I'm interested in moving on.",
    "Rejected by a screen. A new low.",
  ]),
  ...M('aside.watcher.warm', [
    "{b} likes me. People tell you things when they like you. Useful.",
    "Warm chat. Warm chats are where people forget to be careful.",
    "I'm keeping {b} close. Close enough to hear everything.",
    "Good chat. I talked less than {b}. That's the trick.",
  ]),
  ...M('aside.watcher.neutral', [
    "{b} changes the subject every time I get close to something.",
    "Nothing wrong. Nothing right. Just watching.",
    "I'll let that chat sit. It'll make sense tomorrow.",
    "Everyone in here has a tell. Still looking for {b}'s.",
  ]),
  ...M('aside.watcher.cold', [
    "{b} doesn't want me looking too close. Now I'm looking closer.",
    "Short. Guarded. {b} is protecting something.",
    "I don't need {b} to be my friend. I just need {b} to slip.",
    "Noted. Filed. Moving on.",
  ]),
  ...M('chat.topic.single', [
    { turns: [{ by: 'a', send: "So single in the Circle. Any crushes yet? You can tell me {e:eyes}" }, { by: 'b', send: "Maybe one. Maybe two lol. I'll never tell" }, { by: 'a', send: "That means yes {e:wink}" }] },
    { turns: [{ by: 'a', send: "What's your biggest dating dealbreaker?" }, { by: 'b', send: "Being rude to waiters. Instant no" }, { by: 'a', send: "Correct answer honestly" }] },
    { turns: [{ by: 'a', send: "Would you ever date someone you met in here?" }, { by: 'b', send: "Honestly? If they're real, maybe {e:smile}" }, { by: 'a', react: "If they're real. That's the whole game, isn't it?" }] },
  ]),
};
