// Slips about a persona's own life (ci/persona-data.js TOPICS). Data only.
// a = the persona who slipped, b = the one reading. The real show's pattern:
// US 4's "golfer" who didn't know what an eagle is. A fake gets a plain fact
// about their own job or life wrong; `noticed` ends with b suspicious,
// `missed` with b none the wiser and a relieved. The fact the fake misses is
// one anybody near that life would know.
const N = (topic, n, turns, beat) => ({ id: `slip.topic.${topic}.noticed.0${n}`, turns, beat });
const M = (topic, n, turns, beat) => ({ id: `slip.topic.${topic}.missed.0${n}`, turns, beat });
const A = (send, say) => ({ by: 'a', ...(say ? { say } : {}), send });
const B = (react, send) => ({ by: 'b', react, ...(send ? { send } : {}) });
const Bs = send => ({ by: 'b', send });
const Asay = say => ({ by: 'a', say });

const RAW = {
  'slip.topic.hospital.noticed': [
    N('hospital', 1, [Bs('What floor do you work on?'), A('Oh the top one lol, best view in the hospital'),
      B("A floor isn't a view. It's a unit. Peds, ICU, ER. Every nurse knows that.")], '{b} sits up.'),
    N('hospital', 2, [A("Twelve-hour shifts are nothing, I usually get a lunch hour and a nap"),
      B('A nap? On a twelve? No nurse on earth gets a nap.')], '{b} laughs, but it is not a friendly laugh.'),
    N('hospital', 3, [Bs('Scrubs or your own clothes at work?'), A('Honestly whatever I feel like that day lol'),
      B("Whatever {a.sub} feels like. In a hospital. Right.")], '{b} opens the profile again.'),
  ],
  'slip.topic.hospital.missed': [
    M('hospital', 1, [Bs('Do you ever get used to the hospital smell?'), A('Lol you stop noticing it after a while', 'What would a real nurse say? That sounded right. I think.')],
      '{a} lets out a breath.'),
    M('hospital', 2, [A("Work has been crazy, so many patients lately"), Bs('Bless you honestly. I could never')],
      '{a} nods, relieved that was all it took.'),
    M('hospital', 3, [Bs("What's the hardest part of your job?"), A('The hours, for sure', 'Keep it short. Short is safe.')],
      '{b} sends a heart and moves on.'),
  ],
  'slip.topic.night-shifts.noticed': [
    N('night-shifts', 1, [A("Night shifts are the best, I'm always in bed by eleven lol"),
      B('In bed by eleven. On night shifts. Think about that for a second.')], '{b} reads it twice.'),
    N('night-shifts', 2, [Bs('How do you sleep after a night shift?'), A('Same as always, lights off at 10pm!'),
      B("10pm? {a.Sub}'d be at work at 10pm.")], '{b} writes it down.'),
    N('night-shifts', 3, [A("I love nights, the sun's always up when I get to work"),
      B("The sun is not up when you start a night shift. That's the whole point of it.")], '{b} shakes {b.posAdj} head.'),
  ],
  'slip.topic.night-shifts.missed': [
    M('night-shifts', 1, [Bs('How do you do nights?? I would die'), A('Coffee and blackout curtains lol', "That's what people say, right? Blackout curtains?")],
      '{a} holds still until the next message comes.'),
    M('night-shifts', 2, [A("My sleep schedule is a mess honestly"), Bs("Same and I don't even have an excuse")],
      '{a} smiles at the screen.'),
    M('night-shifts', 3, [Bs('Morning or night person?'), A("Night, it's my job lol", 'Good. That one I can answer.')],
      '{a} relaxes back into the couch.'),
  ],
  'slip.topic.childcare.noticed': [
    N('childcare', 1, [A('Babies are easy, they sleep like twenty hours a day'),
      B("Twenty hours? Has {a.sub} ever met a baby?")], '{b} laughs out loud, alone in the apartment.'),
    N('childcare', 2, [Bs("What's your go-to for a toddler meltdown?"), A('I just give them a coffee and they calm right down'),
      B('Coffee. For a toddler.')], '{b} stares at the screen for a long time.'),
    N('childcare', 3, [A("Kids love when you let them stay up late, then they're so happy the next day"),
      B('No. Nobody who looks after kids thinks that.')], '{b} crosses {b.posAdj} arms.'),
  ],
  'slip.topic.childcare.missed': [
    M('childcare', 1, [Bs('Are the kids you look after cute?'), A('The cutest!! I love them so much', 'I hope nobody asks their names.')],
      '{a} breathes out.'),
    M('childcare', 2, [A("Kids say the funniest things lol"), Bs('They really do')],
      '{a} nods, glad that one was safe.'),
    M('childcare', 3, [Bs('Do you want kids of your own one day?'), A('One day for sure! I get plenty of practice', 'Practice. Sure.')],
      '{b} has already moved on.'),
  ],
  'slip.topic.gym.noticed': [
    N('gym', 1, [Bs("What's your split?"), A('Like my hair? Down the middle lol'),
      B("{a.Sub}'s a trainer and doesn't know what a split is?")], '{b} sits straight up.'),
    N('gym', 2, [A('Leg day is my favorite, I do it like twice a year'),
      B('Twice a year. And {a.sub} trains people for a living.')], '{b} writes something down.'),
    N('gym', 3, [Bs('How much protein do you get in a day?'), A('Oh I avoid protein, it makes you bulky'),
      B('A trainer who avoids protein. Okay.')], '{b} raises an eyebrow at the screen.'),
  ],
  'slip.topic.gym.missed': [
    M('gym', 1, [Bs('Gym later?? Virtual spot me'), A("Always!! Let's get it", 'I hope that is what gym people say.')],
      '{a} does one push-up, then stops.'),
    M('gym', 2, [A('Sore from yesterday lol'), Bs('Same, I felt it walking up the stairs')],
      '{a} smiles at the screen.'),
    M('gym', 3, [Bs('Pre-workout: yes or no?'), A('Depends on the day', 'What even is pre-workout?')],
      '{b} sends a flexing emoji and moves on.'),
  ],
  'slip.topic.bar.noticed': [
    N('bar', 1, [Bs("What's your go-to drink to make?"), A('A mojito! Gin, lime, lots of mint'),
      B('Gin? A mojito is rum. Every bartender alive knows that.')], '{b} sits up on the couch.'),
    N('bar', 2, [A('Best part of bartending is getting off at like 9pm'),
      B("9pm? That's when a bar gets busy.")], '{b} reads it again.'),
    N('bar', 3, [Bs('Ever had to cut someone off?'), A('Cut them off what? Lol'),
      B("{a.Sub} doesn't know what cutting someone off means.")], '{b} writes it down.'),
  ],
  'slip.topic.bar.missed': [
    M('bar', 1, [Bs('Make me a drink when this is over'), A("Deal, I'll make you my special", "I don't have a special.")],
      '{a} laughs a little too hard.'),
    M('bar', 2, [A('The tips are the best part lol'), Bs('I bet you get SO many')],
      '{a} smiles, relieved.'),
    M('bar', 3, [Bs('Craziest thing you saw at work?'), A("Too many to pick, honestly", 'Vague. Stay vague.')],
      '{b} laughs and moves on.'),
  ],
  'slip.topic.music.noticed': [
    N('music', 1, [Bs('What guitar do you play?'), A('A red one lol'),
      B("A red one. Not a brand, not a model. A red one.")], '{b} laughs, but writes it down.'),
    N('music', 2, [A('I can read music a little, like the letters on the lines'),
      B("{a.Sub} plays every weekend and can't read music?")], '{b} frowns at the screen.'),
    N('music', 3, [Bs("What's your favorite key to write in?"), A('The front door key lol'),
      B("That was a real question. Anyone who writes songs would know.")], '{b} opens the profile.'),
  ],
  'slip.topic.music.missed': [
    M('music', 1, [Bs('Play us a song when this is over!'), A("For sure, I'll write one about you", 'I hope nobody holds me to that.')],
      '{a} stares at the ceiling.'),
    M('music', 2, [A('Music is my whole life honestly'), Bs('I love that for you')],
      '{a} nods, relieved.'),
    M('music', 3, [Bs('Who are your influences?'), A('Too many to name!', 'Please do not ask me to name one.')],
      '{b} sends a music note and moves on.'),
  ],
  'slip.topic.school.noticed': [
    N('school', 1, [Bs('What grades do you teach?'), A('Mostly A and B lol, some C'),
      B('Grades like levels. Tenth grade. {a.Sub} gave a report card.')], '{b} writes it down.'),
    N('school', 2, [A('Summers off, winters off, spring off, teaching is basically a vacation'),
      B('A teacher would never say that. Ever.')], '{b} crosses {b.posAdj} arms.'),
    N('school', 3, [Bs('How many kids in a class?'), A('Like five? Maybe six'),
      B('Five kids in a high school class. Where is this school?')], '{b} raises an eyebrow.'),
  ],
  'slip.topic.school.missed': [
    M('school', 1, [Bs('Do your students know you are on here?'), A('They are going to lose it lol', 'Please nobody ask what I teach.')],
      '{a} looks at the door, then back at the screen.'),
    M('school', 2, [A('Grading is the worst part of the job'), Bs('My teachers always said that too')],
      '{a} smiles at the screen.'),
    M('school', 3, [Bs('Favorite subject?'), A('History, always', 'Please nobody ask me a date.')],
      '{b} sends a book emoji and moves on.'),
  ],
  'slip.topic.law.noticed': [
    N('law', 1, [Bs('What kind of law?'), A('The legal kind lol'),
      B("The legal kind. {a.Sub}'s a lawyer and that's the answer?")], '{b} sits forward.'),
    N('law', 2, [A('I never had to take the bar, I was just really good at school'),
      B('Every lawyer takes the bar exam. That is not optional.')], '{b} writes it down, underlined.'),
    N('law', 3, [Bs('Ever lost a case?'), A('What case? Like a phone case?'),
      B("{a.Sub} doesn't know what a case is.")], '{b} laughs at the screen.'),
  ],
  'slip.topic.law.missed': [
    M('law', 1, [Bs('Should I be scared to argue with you?'), A('Very scared lol', 'Lawyers are confident. Be confident.')],
      '{a} grins at the screen, then stops.'),
    M('law', 2, [A('Long week at the office'), Bs('Lawyers work so hard honestly')],
      '{a} nods, relieved.'),
    M('law', 3, [Bs('Why law?'), A('I like being right lol', 'Good. That one is true.')],
      '{b} laughs and moves on.'),
  ],
  'slip.topic.firehouse.noticed': [
    N('firehouse', 1, [Bs('How many days on at the station?'), A('I go home every night at five'),
      B('Firefighters do long shifts at the station. Every single one of them.')], '{b} writes it down.'),
    N('firehouse', 2, [A('Best part of the job is riding in the back of the police car'),
      B('The police car. {a.Sub} said police car.')], '{b} stares at the screen.'),
    N('firehouse', 3, [Bs('Who cooks at your station?'), A('We order in every night lol, nobody cooks'),
      B('Every firehouse cooks. That is the whole thing.')], '{b} opens the profile.'),
  ],
  'slip.topic.firehouse.missed': [
    M('firehouse', 1, [Bs('Were you ever scared on a call?'), A('Every time, honestly', 'I hope nobody asks what a call is actually like.')],
      '{a} breathes out slowly.'),
    M('firehouse', 2, [A('My crew is my family'), Bs("That's beautiful honestly")],
      '{a} smiles at the screen.'),
    M('firehouse', 3, [Bs('Do you have a station dog?'), A('We should get one lol', 'Is that a thing?')],
      '{b} sends a dog emoji and moves on.'),
  ],
  'slip.topic.real-estate.noticed': [
    N('real-estate', 1, [Bs('How does commission work for you?'), A("I just get paid by the hour lol"),
      B('A realtor paid by the hour. No. They live on commission.')], '{b} writes it down.'),
    N('real-estate', 2, [A('Open houses are on weekdays mostly, weekends are dead'),
      B('Open houses are on weekends. Everybody knows that.')], '{b} frowns at the screen.'),
    N('real-estate', 3, [Bs('Ever had a deal fall through at closing?'), A('What is closing?'),
      B('{a.Sub} sells houses and asked what closing is.')], '{b} reads it out loud to the empty room.'),
  ],
  'slip.topic.real-estate.missed': [
    M('real-estate', 1, [Bs('What should I look for in my first home?'), A('Location, location, location lol', 'Thank you, television.')],
      '{a} nods at {a.ref} in the mirror.'),
    M('real-estate', 2, [A('The market is crazy right now'), Bs("Don't even tell me, I'm scared")],
      '{a} smiles, relieved.'),
    M('real-estate', 3, [Bs('Dream home?'), A('Anything with a pool!', 'Safe. Everybody wants a pool.')],
      '{b} sends a home emoji and moves on.'),
  ],
  'slip.topic.garage.noticed': [
    N('garage', 1, [Bs('How often should I change my oil?'), A('Oh like once, when you buy the car'),
      B("Once. A mechanic said once.")], '{b} sits straight up.'),
    N('garage', 2, [A('I mostly work on the steering wheels'),
      B('Nobody works on "the steering wheels." What does {a.sub} actually fix?')], '{b} writes it down.'),
    N('garage', 3, [Bs('Manual or automatic?'), A('Manual like the book that comes with it?'),
      B("{a.Sub} doesn't know what a manual is.")], '{b} laughs, then stops laughing.'),
  ],
  'slip.topic.garage.missed': [
    M('garage', 1, [Bs('My check engine light is on, should I be worried?'), A('Get it looked at for sure', 'That is what everyone says, right?')],
      '{a} holds still.'),
    M('garage', 2, [A('Hands are always dirty lol'), Bs('That is honestly attractive')],
      '{a} grins at the screen.'),
    M('garage', 3, [Bs('Dream car?'), A('Something old and loud', 'Nice. Nobody can check that.')],
      '{b} sends a car emoji and moves on.'),
  ],
  'slip.topic.campus.noticed': [
    N('campus', 1, [Bs('What are you majoring in?'), A('Oh I have not picked a school yet'),
      B('{a.Sub} is a senior and has not picked a school?')], '{b} opens the profile.'),
    N('campus', 2, [A('Finals are easy, you just show up and they give you the grade'),
      B('No college student has ever said that.')], '{b} writes it down.'),
    N('campus', 3, [Bs('Dorm or apartment?'), A("What's the difference lol"),
      B("{a.Sub}'s a senior in college and doesn't know what a dorm is?")], '{b} reads it three times.'),
  ],
  'slip.topic.campus.missed': [
    M('campus', 1, [Bs('Miss school yet?'), A('Weirdly yes lol', 'Keep it short. Short is safe.')],
      '{a} laughs quietly.'),
    M('campus', 2, [A('Running on no sleep and iced coffee'), Bs('The college experience')],
      '{a} smiles at the screen.'),
    M('campus', 3, [Bs('Best party on campus?'), A('Too many to count', 'Please do not ask for a name.')],
      '{b} sends a party emoji and moves on.'),
  ],
  'slip.topic.modeling.noticed': [
    N('modeling', 1, [Bs("Who's your agency?"), A("I don't need one, I just show up to shoots"),
      B('Every working model has an agency.')], '{b} sits up.'),
    N('modeling', 2, [A('Shoots are so quick, like ten minutes and done'),
      B('Ten minutes. A shoot takes all day.')], '{b} frowns at the screen.'),
    N('modeling', 3, [Bs('What was your last job?'), A('A job? Like a real job?'),
      B("{a.Sub} doesn't call a booking a job?")], '{b} writes it down.'),
  ],
  'slip.topic.modeling.missed': [
    M('modeling', 1, [Bs('Teach me how to pose!'), A('Chin down, eyes up lol', 'I learned that from a video.')],
      '{a} tries the pose in the mirror.'),
    M('modeling', 2, [A('Camera ready most days'), Bs('Obviously, look at you')],
      '{a} smiles, relieved.'),
    M('modeling', 3, [Bs('Hardest part of modeling?'), A('The waiting around', 'That is true of everything.')],
      '{b} sends a camera emoji and moves on.'),
  ],
  'slip.topic.kids.noticed': [
    N('kids', 1, [Bs('How old are your kids?'), A('Um, one is like seven and one is maybe eight or six'),
      B('Maybe eight or six. A parent knows how old their kids are.')], '{b} stares at the screen.'),
    N('kids', 2, [A('My kids sleep through the night since they were born, so easy'),
      B("No parent has ever said that. Not one.")], '{b} laughs out loud.'),
    N('kids', 3, [Bs("What's your kid's name?"), A('Oh I call them "the kid" lol'),
      B("{a.Sub} doesn't want to say the name of {a.posAdj} own kid?")], '{b} writes it down.'),
  ],
  'slip.topic.kids.missed': [
    M('kids', 1, [Bs('Do you miss your kids?'), A('Every single day', 'What would a real parent say here? Just keep it simple.')],
      '{a} looks down at {a.posAdj} hands.'),
    M('kids', 2, [A('Parenting is the hardest job there is'), Bs("I believe you, my mom says the same")],
      '{a} nods, relieved.'),
    M('kids', 3, [Bs('Are they proud of you?'), A('They better be lol', 'Please change the subject.')],
      '{b} sends a heart and moves on.'),
  ],
  'slip.topic.dog.noticed': [
    N('dog', 1, [Bs("What's your dog's name?"), A('Dog. Just Dog'),
      B("{a.Sub} named the dog Dog. Or {a.sub} doesn't have one.")], '{b} writes it down.'),
    N('dog', 2, [Bs('What breed?'), A('A golden poodle doodle retriever? Something like that'),
      B('Something like that. It lives with {a.obj}.')], '{b} laughs at the screen.'),
    N('dog', 3, [A('My dog loves chocolate, I give him some every night'),
      B('Chocolate is poison for dogs. Everybody with a dog knows that.')], '{b} sits up, alarmed.'),
  ],
  'slip.topic.dog.missed': [
    M('dog', 1, [Bs('Does your dog miss you?'), A('So much, I miss him too', 'I hope nobody asks what breed.')],
      '{a} stares at the wall.'),
    M('dog', 2, [A('Dogs are better than people'), Bs('Facts honestly')],
      '{a} grins at the screen.'),
    M('dog', 3, [Bs('Send a dog pic!!'), A("I didn't bring any lol", 'Good excuse. Keep it.')],
      '{b} sends a sad face and moves on.'),
  ],
  'slip.topic.church.noticed': [
    N('church', 1, [Bs('What church do you go to?'), A('The one with the tall roof lol'),
      B("{a.Sub} goes every Sunday and doesn't know the name?")], '{b} opens the profile.'),
    N('church', 2, [A('Christmas is my favorite, it is in spring right?'),
      B('Christmas. In spring.')], '{b} stares at the screen.'),
    N('church', 3, [Bs('Favorite Bible verse?'), A('The one about the whale probably'),
      B('That is a story, not a verse. Anyone at church would know one by heart.')], '{b} writes it down.'),
  ],
  'slip.topic.church.missed': [
    M('church', 1, [Bs('Will you pray for me?'), A('Always', 'Say it like you mean it.')],
      '{a} goes quiet for a moment.'),
    M('church', 2, [A('Sundays are for family and church'), Bs('I love that for you')],
      '{a} smiles at the screen.'),
    M('church', 3, [Bs('Do you sing in the choir?'), A('Only when nobody is listening lol', 'Please never ask me to sing.')],
      '{b} sends a laughing emoji and moves on.'),
  ],
  'slip.topic.college-sports.noticed': [
    N('college-sports', 1, [Bs('What position did you play?'), A('The running one'),
      B('The running one. That is not a position.')], '{b} sits up.'),
    N('college-sports', 2, [A('We had practice like once a month, super chill'),
      B('College teams practice every day. Every day.')], '{b} writes it down.'),
    N('college-sports', 3, [Bs('What conference were you in?'), A('Like a meeting?'),
      B("{a.Sub} played college sports and doesn't know what a conference is.")], '{b} laughs at the screen.'),
  ],
  'slip.topic.college-sports.missed': [
    M('college-sports', 1, [Bs('Miss playing?'), A('Every game day', 'Please do not ask what position I played.')],
      '{a} breathes out.'),
    M('college-sports', 2, [A('Game days were the best'), Bs("I bet you were a legend")],
      '{a} grins at the screen.'),
    M('college-sports', 3, [Bs('Biggest win?'), A('Beating our rivals, easy', 'Everybody has rivals. Safe.')],
      '{b} sends a trophy and moves on.'),
  ],
  'slip.topic.gaming.noticed': [
    N('gaming', 1, [Bs('PC or console?'), A('Phone mostly! Candy games'),
      B("{a.Sub} streams every night and plays on {a.posAdj} phone?")], '{b} opens the profile.'),
    N('gaming', 2, [A('I do not really talk while I stream, I just play'),
      B('Talking is the whole job of a streamer.')], '{b} writes it down.'),
    N('gaming', 3, [Bs("What's your rank?"), A('Rank of what?'),
      B('"Rank of what." Okay.')], '{b} stares at the screen.'),
  ],
  'slip.topic.gaming.missed': [
    M('gaming', 1, [Bs('We should play together sometime'), A('Bet, I will carry you lol', 'I will need a lot of practice first.')],
      '{a} laughs nervously.'),
    M('gaming', 2, [A('Up way too late last night gaming'), Bs('The gamer life')],
      '{a} smiles, relieved.'),
    M('gaming', 3, [Bs('Favorite game of all time?'), A('Too hard to pick!', 'Do not ask me to name one.')],
      '{b} sends a controller emoji and moves on.'),
  ],
};

// A thought about a message comes AFTER it (the renderer puts a turn's `say`
// before its `send`), so a turn with both is split: send, then think.
const sendThenThink = e => ({ ...e, turns: e.turns.flatMap(t => (t.say && t.send
  ? [{ by: t.by, send: t.send }, { by: t.by, say: t.say }] : [t])) });
export const SLIP_TOPICS = Object.fromEntries(Object.entries(RAW).map(([k, v]) => [k, v.map(sendThenThink)]));
