// GENERATED by tools/bb-house/port-style.py from mockup/mockup-bb-house-v2.html. Do not edit by hand.
export const BBX_FONTS = "@import url('https://fonts.googleapis.com/css2?family=Archivo:wdth,wght@62..125,300..900&family=Chakra+Petch:wght@500;600;700&display=swap');";
export const BBX_CSS = `.bbx .stage{position:relative;aspect-ratio:16/9;container-type:inline-size;overflow:hidden;border-radius:14px;background:#03050a;cursor:pointer;user-select:none;isolation:isolate;
  box-shadow:0 0 0 1px rgba(34,225,255,.18),0 30px 70px -20px rgba(0,20,60,.55)}
.bbx .cam{position:absolute;inset:0;transition:transform 1s cubic-bezier(.2,.75,.15,1)}
.bbx .lens{position:absolute;inset:0}
.bbx .lens.cut{animation:bbx-cut .32s steps(4,end)}
@keyframes bbx-cut{0%{transform:translateX(1.4cqw);filter:hue-rotate(40deg) saturate(2)}50%{transform:translateX(-.8cqw)}100%{transform:none;filter:none}}
.bbx .stage.bbspeaks .cam{filter:brightness(.25) saturate(.4) blur(.25cqw);transition:filter .6s}
.bbx .set{position:absolute;inset:0;overflow:hidden}
.bbx .set::before,.bbx .set::after{content:"";position:absolute;inset:0;pointer-events:none}
.bbx .floor{position:absolute;left:0;right:0;bottom:0;height:34%;z-index:0;
  background:linear-gradient(180deg,rgba(255,255,255,.07),rgba(255,255,255,0) 30%),linear-gradient(180deg,var(--fl1,#0b1120),var(--fl2,#03050a));
  border-top:.1cqw solid rgba(255,255,255,.18)}
.bbx .floor::after{content:"";position:absolute;inset:0;background:repeating-linear-gradient(90deg,rgba(255,255,255,.035) 0 .1cqw,transparent .1cqw 6cqw);
  -webkit-mask:linear-gradient(180deg,#000,transparent 80%);mask:linear-gradient(180deg,#000,transparent 80%);transform:perspective(20cqw) rotateX(40deg);transform-origin:top}
.bbx .set-kitchen{--fl1:#2a1a10;--fl2:#0b0705;background:
  radial-gradient(16cqw 22cqw at 26% 10%,rgba(255,180,90,.42),transparent 70%),radial-gradient(16cqw 22cqw at 50% 10%,rgba(255,180,90,.5),transparent 70%),
  radial-gradient(16cqw 22cqw at 74% 10%,rgba(255,180,90,.42),transparent 70%),
  linear-gradient(100deg,rgba(120,190,255,.22),transparent 34%),linear-gradient(180deg,#22160f 0%,#160e09 70%)}
.bbx .set-kitchen::before{background:linear-gradient(90deg,transparent 25.9%,rgba(255,210,150,.5) 26%,transparent 26.1%,transparent 49.9%,rgba(255,210,150,.5) 50%,transparent 50.1%,transparent 73.9%,rgba(255,210,150,.5) 74%,transparent 74.1%);
  -webkit-mask:linear-gradient(180deg,#000 0,#000 9%,transparent 9.2%);mask:linear-gradient(180deg,#000 0,#000 9%,transparent 9.2%)}
.bbx .set-kitchen::after{background:radial-gradient(1.1cqw 1.1cqw at 26% 10%,#ffe2b0,transparent),radial-gradient(1.1cqw 1.1cqw at 50% 10%,#ffe2b0,transparent),radial-gradient(1.1cqw 1.1cqw at 74% 10%,#ffe2b0,transparent),
  linear-gradient(180deg,transparent 60%,rgba(255,200,140,.18) 63%,transparent 69.5%)}
.bbx .set-bedroom{--fl1:#0d1426;--fl2:#04060c;background:radial-gradient(40cqw 30cqw at 82% 6%,rgba(110,140,230,.38),transparent 70%),linear-gradient(180deg,#0f1424,#070a12)}
.bbx .set-bedroom::before{background:repeating-linear-gradient(-26deg,rgba(170,195,255,.11) 0 1.4cqw,transparent 1.4cqw 3.6cqw);
  -webkit-mask:radial-gradient(50cqw 30cqw at 72% 26%,#000,transparent 75%);mask:radial-gradient(50cqw 30cqw at 72% 26%,#000,transparent 75%)}
.bbx .set-hoh{--fl1:color-mix(in srgb,var(--hoh) 30%,#0b0710);--fl2:#05030a;background:radial-gradient(50cqw 34cqw at 60% 14%,color-mix(in srgb,var(--hoh) 50%,transparent),transparent 70%),
  radial-gradient(18cqw 14cqw at 90% 34%,rgba(255,225,190,.35),transparent 70%),linear-gradient(180deg,color-mix(in srgb,var(--hoh) 18%,#120a18),#08050c)}
.bbx .set-hoh::before{background:linear-gradient(180deg,transparent 7.8%,color-mix(in srgb,var(--hoh) 80%,#fff) 8%,transparent 8.4%);opacity:.6}
.bbx .set-dr{--fl1:#0a0820;--fl2:#020108;background:radial-gradient(40cqw 36cqw at 50% 40%,rgba(90,60,255,.35),transparent 70%),linear-gradient(180deg,#0b0820,#03020a)}
.bbx .set-ceremony{--fl1:#06142a;--fl2:#02050c;background:radial-gradient(70cqw 26cqw at 50% -6%,rgba(30,140,255,.45),transparent 70%),linear-gradient(180deg,#07142a,#030812)}
.bbx .set-ceremony::before{background:repeating-linear-gradient(90deg,transparent 0 9.9cqw,rgba(40,170,255,.16) 9.9cqw 10cqw);-webkit-mask:linear-gradient(180deg,#000,transparent 70%);mask:linear-gradient(180deg,#000,transparent 70%)}
.bbx .set-ceremony::after{background:linear-gradient(90deg,transparent,rgba(34,225,255,.09),transparent);animation:bbx-sweep 6s ease-in-out infinite alternate}
@keyframes bbx-sweep{from{transform:translateX(-35%)}to{transform:translateX(35%)}}
.bbx .set-yard{--fl1:#1683b0;--fl2:#0a3d5c;background:radial-gradient(30cqw 26cqw at 86% 4%,rgba(255,250,225,.95),transparent 70%),linear-gradient(180deg,#5bb2e8 0%,#a9dcf2 50%,#e3d7bd 69%)}
.bbx .set-yard .floor{background:repeating-radial-gradient(circle at 30% 40%,rgba(255,255,255,.3) 0 .35cqw,transparent .45cqw 2.2cqw),linear-gradient(180deg,#36b2d9,#0d6d98);
  background-size:8cqw 4.5cqw,100% 100%;animation:bbx-caustic 6s linear infinite}
@keyframes bbx-caustic{to{background-position:8cqw 4.5cqw,0 0}}
.bbx .set-yard::after{background:radial-gradient(20cqw 12cqw at 6% 14%,rgba(20,60,30,.3),transparent 70%)}
.bbx .stage.nv .lens{filter:grayscale(1) sepia(1) hue-rotate(62deg) saturate(2.4) brightness(1.08) contrast(1.08)}
.bbx .stage.nv .grain{opacity:.22}
.bbx .grain{position:absolute;inset:0;z-index:7;pointer-events:none;opacity:.05;mix-blend-mode:screen;
  background-image:url("data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='140' height='140'%3E%3Cfilter id='n'%3E%3CfeTurbulence baseFrequency='.85' numOctaves='2'/%3E%3C/filter%3E%3Crect width='140' height='140' filter='url(%23n)'/%3E%3C/svg%3E");animation:bbx-grain .5s steps(3) infinite}
@keyframes bbx-grain{33%{transform:translate(-2%,1%)}66%{transform:translate(1%,-2%)}}
.bbx .gt{position:absolute;bottom:18.6cqw;width:11.4cqw;transform:translateX(-50%);z-index:3;transition:filter .45s}
.bbx .gt .tile{position:relative;aspect-ratio:4/5;border-radius:1.3cqw;overflow:hidden;background:linear-gradient(160deg,color-mix(in srgb,var(--c) 85%,#fff),color-mix(in srgb,var(--c) 45%,#000));
  box-shadow:inset 0 0 0 .14cqw rgba(255,255,255,.35),0 1.6cqw 3cqw rgba(0,0,0,.45);transform:perspective(50cqw) rotateY(var(--ry,0deg));transition:transform .5s cubic-bezier(.2,.8,.2,1),box-shadow .4s;
  -webkit-box-reflect:below .5cqw linear-gradient(transparent 58%,rgba(255,255,255,.22))}
.bbx .gt .tile img{position:absolute;inset:0;width:100%;height:100%;object-fit:cover;object-position:50% 14%}
.bbx .gt .tile .i{position:absolute;inset:0;display:grid;place-items:center;font:900 5cqw Archivo;color:rgba(255,255,255,.9)}
.bbx .gt .tile::after{content:"";position:absolute;inset:0;background:linear-gradient(125deg,rgba(255,255,255,.28) 0%,transparent 34%,transparent 70%,rgba(255,255,255,.08));pointer-events:none}
.bbx .gt .plate{position:absolute;left:50%;top:calc(100% + 1.3cqw);transform:translateX(-50%);display:flex;gap:.5cqw;align-items:center;white-space:nowrap;z-index:2}
.bbx .gt .plate b{font:800 1.25cqw Archivo;font-stretch:78%;letter-spacing:.14cqw;color:#fff;text-transform:uppercase;text-shadow:0 .2cqw .6cqw rgba(0,0,0,.8)}
.bbx .chipx{font:700 .82cqw 'Chakra Petch';letter-spacing:.1cqw;padding:.18cqw .5cqw;border-radius:.3cqw;text-transform:uppercase}
.bbx .chipx.hoh{background:#f5c542;color:#2a1d00}
.bbx .chipx.nom{background:#ff3355;color:#fff}
.bbx .chipx.veto{border:.1cqw solid #f5c542;color:#f5c542}
.bbx .chipx.out{background:#333;color:#aaa}
.bbx .gt{filter:brightness(.62) saturate(.75)}
.bbx .gt.speak{filter:none;z-index:4}
.bbx .gt.speak .tile{transform:perspective(50cqw) rotateY(0) scale(1.1) translateY(-.6cqw);box-shadow:inset 0 0 0 .16cqw color-mix(in srgb,var(--c) 70%,#fff),0 0 3cqw color-mix(in srgb,var(--c) 55%,transparent),0 2cqw 4cqw rgba(0,0,0,.5)}
.bbx .gt.out{filter:brightness(.4) saturate(.5) blur(.25cqw)}
.bbx .gt.in .tile{animation:bbx-tin .7s cubic-bezier(.2,.8,.2,1) both}
@keyframes bbx-tin{from{opacity:0;transform:perspective(50cqw) rotateY(var(--ry,0deg)) translateY(3cqw) scale(.94)}}
.bbx .gt.gone .tile img{filter:grayscale(1) brightness(.6)}
/* House Life: the rest of the room, out of focus at the back */
.bbx .gt.bgp{bottom:21.5cqw;width:6.8cqw;filter:brightness(.4) saturate(.55) blur(.12cqw);z-index:1}
.bbx .gt.bgp .tile{-webkit-box-reflect:none;box-shadow:0 .8cqw 1.6cqw rgba(0,0,0,.4)}
.bbx .gt.bgp .plate{display:none}
/* somebody joining the conversation comes forward */
.bbx .gt.step .tile{animation:bbx-step .55s cubic-bezier(.2,.8,.2,1) both}
@keyframes bbx-step{from{opacity:.4;transform:perspective(50cqw) rotateY(var(--ry,0deg)) translateY(-7cqw) scale(.58)}}
.bbx .trk{position:absolute;inset:-1.1cqw -1.1cqw;pointer-events:none;opacity:0;z-index:3}
.bbx .gt.speak .trk{opacity:1}
.bbx .trk i{position:absolute;width:2cqw;height:2cqw;border:.2cqw solid #22e1ff;filter:drop-shadow(0 0 .5cqw #22e1ff)}
.bbx .trk i:nth-child(1){left:0;top:0;border-right:0;border-bottom:0}
.bbx .trk i:nth-child(2){right:0;top:0;border-left:0;border-bottom:0}
.bbx .trk i:nth-child(3){left:0;bottom:0;border-right:0;border-top:0}
.bbx .trk i:nth-child(4){right:0;bottom:0;border-left:0;border-top:0}
.bbx .trk .id{position:absolute;left:0;top:-2.3cqw;font:700 .9cqw 'Chakra Petch';letter-spacing:.12cqw;color:#001018;background:#22e1ff;padding:.2cqw .6cqw;border-radius:.2cqw;white-space:nowrap}
.bbx .trk .id s{text-decoration:none;opacity:.6;margin-left:.6cqw}
.bbx .trk.lock i{animation:bbx-lock .5s cubic-bezier(.2,.8,.2,1) both}
.bbx .trk.lock i:nth-child(1){--lx:-2cqw;--ly:-2cqw}
.bbx .trk.lock i:nth-child(2){--lx:2cqw;--ly:-2cqw}
.bbx .trk.lock i:nth-child(3){--lx:-2cqw;--ly:2cqw}
.bbx .trk.lock i:nth-child(4){--lx:2cqw;--ly:2cqw}
@keyframes bbx-lock{from{transform:translate(var(--lx),var(--ly));opacity:0}}
.bbx .trk.lock .id{animation:bbx-idin .5s .2s both}
@keyframes bbx-idin{from{clip-path:inset(0 100% 0 0)}to{clip-path:inset(0 0 0 0)}}
.bbx .scan{position:absolute;left:0;right:0;height:18%;top:-20%;background:linear-gradient(180deg,transparent,rgba(34,225,255,.55),transparent);z-index:2;animation:bbx-scan .9s ease-out .1s both;mix-blend-mode:screen}
@keyframes bbx-scan{to{top:105%}}
.bbx .hud{position:absolute;inset:0;z-index:8;pointer-events:none}
.bbx .bug{position:absolute;left:2.6cqw;top:2.4cqw;display:flex;align-items:center;gap:1cqw}
.bbx .bug .eye{width:4.6cqw;height:auto}
.bbx .bug .wm{font:900 1.2cqw Archivo;font-stretch:125%;letter-spacing:.2cqw;color:#fff;line-height:1.05}
.bbx .bug .wm span{display:block;font:600 .85cqw 'Chakra Petch';letter-spacing:.24cqw;color:#22e1ff;font-stretch:100%}
.bbx .live{display:inline-flex;align-items:center;gap:.5cqw;font:700 1cqw 'Chakra Petch';letter-spacing:.16cqw;color:#fff;background:#ff2e4d;padding:.3cqw .8cqw;border-radius:.3cqw;margin-left:1cqw}
.bbx .live::before{content:"";width:.7cqw;height:.7cqw;border-radius:50%;background:#fff;animation:bbx-blink 1.2s steps(2) infinite}
@keyframes bbx-blink{50%{opacity:.2}}
.bbx .camlab{font:600 1.05cqw 'Chakra Petch';letter-spacing:.18cqw;color:#fff;padding:.3cqw .8cqw;border:.1cqw solid rgba(255,255,255,.35);border-radius:.3cqw;background:rgba(0,0,0,.35);backdrop-filter:blur(.6cqw)}
.bbx .camlab b{color:#22e1ff;font-weight:700;margin-right:.7cqw}
.bbx .camlab.sw{animation:bbx-camsw .4s}
@keyframes bbx-camsw{0%{background:#22e1ff;color:#001018}}
.bbx .clockw{position:absolute;right:2.6cqw;top:2.6cqw;text-align:right;font:600 1.05cqw 'Chakra Petch';letter-spacing:.18cqw;color:#fff}
.bbx .clockw .big{font:700 1.7cqw 'Chakra Petch';letter-spacing:.12cqw;color:#fff}
.bbx .sig{display:inline-flex;gap:.2cqw;align-items:flex-end;margin-left:.8cqw;vertical-align:-.1cqw}
.bbx .sig i{width:.35cqw;background:#22e1ff;border-radius:.1cqw}
.bbx .sig i:nth-child(1){height:.6cqw}
.bbx .sig i:nth-child(2){height:.9cqw}
.bbx .sig i:nth-child(3){height:1.2cqw}
.bbx .sig i:nth-child(4){height:1.5cqw;opacity:.35}
.bbx .feeds{position:absolute;right:2.6cqw;top:7.4cqw;display:flex;flex-direction:column;gap:.5cqw}
.bbx .ft{width:9cqw;aspect-ratio:16/9;border-radius:.4cqw;position:relative;overflow:hidden;box-shadow:0 0 0 .1cqw rgba(255,255,255,.25);opacity:.55;transition:opacity .3s,box-shadow .3s}
.bbx .ft .set{position:absolute;inset:0}
.bbx .ft .set .floor{height:30%}
.bbx .ft span{position:absolute;left:.4cqw;bottom:.25cqw;font:700 .65cqw 'Chakra Petch';letter-spacing:.08cqw;color:#fff;text-shadow:0 0 .4cqw #000;z-index:2}
.bbx .ft.on{opacity:1;box-shadow:0 0 0 .16cqw #22e1ff,0 0 1.2cqw rgba(34,225,255,.5)}
.bbx .zoom{position:absolute;left:50%;top:44%;transform:translate(-50%,-50%);width:10cqw;height:10cqw;z-index:8;pointer-events:none;animation:bbx-zoomr 1s ease-out forwards}
.bbx .zoom::before,.bbx .zoom::after{content:"";position:absolute;background:#22e1ff}
.bbx .zoom::before{left:50%;top:0;bottom:0;width:.12cqw}
.bbx .zoom::after{top:50%;left:0;right:0;height:.12cqw}
.bbx .zoom b{position:absolute;left:calc(100% + .6cqw);top:0;font:700 .9cqw 'Chakra Petch';color:#22e1ff;white-space:nowrap;letter-spacing:.1cqw}
@keyframes bbx-zoomr{0%{opacity:0;transform:translate(-50%,-50%) scale(1.6)}25%{opacity:.9;transform:translate(-50%,-50%) scale(1)}100%{opacity:0}}
.bbx .vign{position:absolute;inset:0;z-index:6;pointer-events:none;background:radial-gradient(ellipse at center,transparent 60%,rgba(0,0,0,.5)),repeating-linear-gradient(0deg,rgba(255,255,255,.018) 0 1px,transparent 1px 3px)}
.bbx .l3{position:absolute;left:3.4cqw;right:3.4cqw;bottom:2.6cqw;z-index:9}
.bbx .l3 .tagr{display:flex;align-items:stretch;height:3.2cqw;margin-left:.6cqw}
.bbx .l3 .tagr .nm{position:relative;display:flex;align-items:center;gap:1cqw;padding:0 2.2cqw 0 1.6cqw;background:linear-gradient(90deg,var(--c),color-mix(in srgb,var(--c) 55%,#0a0f1e));
  clip-path:polygon(0 0,100% 0,calc(100% - 1.4cqw) 100%,0 100%);font:900 1.75cqw Archivo;font-stretch:72%;letter-spacing:.2cqw;color:#fff;text-transform:uppercase;text-shadow:0 .1cqw .3cqw rgba(0,0,0,.35)}
.bbx .l3 .tagr .role{display:flex;align-items:center;padding:0 1.6cqw 0 1.8cqw;margin-left:-1.2cqw;background:rgba(5,9,18,.92);clip-path:polygon(1.4cqw 0,100% 0,calc(100% - 1.4cqw) 100%,0 100%);
  font:700 .95cqw 'Chakra Petch';letter-spacing:.2cqw;color:#cfe9ff;text-transform:uppercase}
.bbx .l3 .body{position:relative;background:linear-gradient(180deg,rgba(6,10,20,.9),rgba(3,6,12,.95));border-radius:0 .9cqw .9cqw .9cqw;padding:1.6cqw 2.2cqw 1.7cqw;min-height:7.8cqw;
  box-shadow:inset 0 .15cqw 0 color-mix(in srgb,var(--c) 80%,#fff),0 1.4cqw 3cqw rgba(0,0,0,.5);backdrop-filter:blur(1cqw);overflow:hidden}
.bbx .l3 .body::before{content:"";position:absolute;left:0;top:0;bottom:0;width:.35cqw;background:var(--c)}
.bbx .l3 .tx{font:500 2.05cqw/1.42 Archivo;color:#f3f6ff;letter-spacing:.01cqw}
.bbx .l3.fresh .tagr .nm{animation:bbx-wipe .45s cubic-bezier(.2,.8,.2,1) both}
.bbx .l3.fresh .tagr .role{animation:bbx-wipe .45s .12s cubic-bezier(.2,.8,.2,1) both}
.bbx .l3.fresh .body{animation:bbx-rise .35s ease-out both}
.bbx .l3.fresh .body::after{content:"";position:absolute;inset:0;background:linear-gradient(100deg,transparent 30%,rgba(255,255,255,.12) 50%,transparent 70%);animation:bbx-shine .9s .1s ease-out both}
@keyframes bbx-wipe{from{clip-path:polygon(0 0,0 0,0 100%,0 100%)}}
@keyframes bbx-rise{from{opacity:0;transform:translateY(1cqw)}}
@keyframes bbx-shine{from{transform:translateX(-100%)}to{transform:translateX(100%)}}
.bbx .l3.dr{--c:#f5c542}
.bbx .l3.dr .tx{font-style:italic}
.bbx .l3.dr .tx::before{content:"\\201C"}
.bbx .l3.dr .tx::after{content:"\\201D"}
.bbx .l3.host{--c:#ff2e4d}
.bbx .cc{position:absolute;left:50%;bottom:3.6cqw;transform:translateX(-50%);z-index:9;max-width:78cqw;text-align:center}
.bbx .cc span{font:600 1.7cqw/1.75 'Chakra Petch';letter-spacing:.04cqw;color:#fff;background:#000;padding:.25cqw .8cqw;box-decoration-break:clone;-webkit-box-decoration-break:clone}
.bbx .cc .ccl{display:table;margin-left:auto;margin-right:auto;font:700 .8cqw 'Chakra Petch';letter-spacing:.3cqw;color:rgba(255,255,255,.55);margin-bottom:.6cqw}
.bbx .bbv{position:absolute;inset:0;z-index:10;display:flex;flex-direction:column;align-items:center;justify-content:center;text-align:center;padding:0 10cqw}
.bbx .bbv .eye{width:15cqw;filter:drop-shadow(0 0 3cqw rgba(34,225,255,.55))}
.bbx .bbv .who{margin-top:1.6cqw;font:700 1.05cqw 'Chakra Petch';letter-spacing:.6cqw;color:#22e1ff}
.bbx .bbv .tx{margin-top:1.2cqw;font:800 3.1cqw/1.18 Archivo;font-stretch:115%;color:#fff;letter-spacing:.04cqw;text-shadow:0 0 2.2cqw rgba(34,225,255,.4)}
.bbx .wave{display:flex;gap:.35cqw;align-items:center;height:3cqw;margin-top:1.4cqw}
.bbx .wave i{width:.35cqw;border-radius:.2cqw;background:#22e1ff;height:20%;animation:bbx-wv .9s ease-in-out infinite alternate;opacity:.85}
@keyframes bbx-wv{to{height:100%}}
.bbx .bbv.fresh .eye{animation:bbx-eyeopen .8s cubic-bezier(.2,.8,.2,1) both}
.bbx .bbv.fresh .tx{animation:bbx-rise .6s .25s both}
@keyframes bbx-eyeopen{from{transform:scale(.6);opacity:0;filter:blur(1cqw)}}
.bbx .eye .ring{transform-origin:0 0;animation:bbx-spin 14s linear infinite}
.bbx .eye .ring2{transform-origin:0 0;animation:bbx-spin 22s linear infinite reverse}
@keyframes bbx-spin{to{transform:rotate(360deg)}}
.bbx .eye .pup{transform-origin:0 0;animation:bbx-breathe 4s ease-in-out infinite}
@keyframes bbx-breathe{50%{transform:scale(.82)}}
.bbx .obj{position:absolute;z-index:2}
.bbx .spy{left:3.6cqw;top:9cqw;width:27cqw;border-radius:.8cqw;overflow:hidden;background:#04070d;box-shadow:0 0 0 .2cqw #1c2638,0 0 3cqw rgba(34,225,255,.2);display:grid;grid-template-columns:1fr 1fr;gap:.25cqw;padding:.25cqw}
.bbx .spy .q{position:relative;aspect-ratio:16/9;overflow:hidden;border-radius:.2cqw}
.bbx .spy .q .set{position:absolute;inset:0}
.bbx .spy .q span{position:absolute;left:.4cqw;top:.3cqw;font:700 .7cqw 'Chakra Petch';color:#fff;letter-spacing:.08cqw;z-index:3;text-shadow:0 0 .3cqw #000}
.bbx .spy .q.hot{box-shadow:inset 0 0 0 .18cqw #22e1ff}
.bbx .spy .q.hot span::after{content:" ● LIVE";color:#ff2e4d;animation:bbx-blink 1s steps(2) infinite}
.bbx .spy .q .fig{position:absolute;bottom:8%;width:14%;aspect-ratio:3/4;border-radius:40% 40% .3cqw .3cqw;background:rgba(150,255,170,.6)}
.bbx .spy .q.nvq .set{filter:grayscale(1) sepia(1) hue-rotate(62deg) saturate(2.4)}
.bbx .ledtv{left:8%;top:8.6cqw;width:20cqw;margin-left:0;aspect-ratio:16/9;border-radius:.6cqw;overflow:hidden;background:#05070d;box-shadow:0 0 0 .3cqw #101624,0 0 4cqw rgba(255,46,77,.18);transition:box-shadow .4s,transform .5s}
.bbx .ledtv.on{box-shadow:0 0 0 .3cqw #ff2e4d,0 0 5cqw rgba(255,46,77,.45);transform:scale(1.03)}
.bbx .ledtv.dim img{filter:brightness(.62)}
.bbx .ledtv img{position:absolute;inset:0;width:100%;height:100%;object-fit:cover;object-position:50% 22%;filter:brightness(1.12) contrast(1.06) saturate(1.1)}
.bbx .ledtv::after{content:"";position:absolute;inset:0;background:repeating-linear-gradient(0deg,rgba(0,0,0,.06) 0 .1cqw,transparent .1cqw .3cqw),linear-gradient(0deg,rgba(0,0,0,.7),transparent 28%)}
.bbx .ledtv .lb{position:absolute;left:.6cqw;bottom:.6cqw;z-index:2;padding:.35cqw .8cqw;border-radius:.35cqw;background:rgba(4,6,12,.78);font:900 1.4cqw Archivo;font-stretch:72%;letter-spacing:.2cqw;color:#fff}
.bbx .ledtv .lb span{display:block;font:700 .75cqw 'Chakra Petch';letter-spacing:.2cqw;color:#ff2e4d}
.bbx .votes{position:absolute;left:16.5%;top:23%;transform:translate(-50%,-50%);z-index:9;display:flex;gap:2cqw;align-items:center}
.bbx .votes .v{text-align:center}
.bbx .votes .n{font:700 5cqw/1 'Chakra Petch';color:#fff;text-shadow:0 0 3cqw rgba(255,46,77,.6);min-width:7cqw}
.bbx .votes .k{font:800 .85cqw Archivo;font-stretch:78%;letter-spacing:.3cqw;color:#ff9db0;text-transform:uppercase}
.bbx .votes .sep{width:.2cqw;height:5cqw;background:linear-gradient(180deg,transparent,#ff2e4d,transparent)}
.bbx .votes.fresh .n{animation:bbx-roll .9s steps(8) both}
@keyframes bbx-roll{0%{opacity:.2;filter:blur(.4cqw)}}
.bbx .kbox{left:58%;bottom:20cqw;width:11cqw;transform:translateX(-50%)}
.bbx .kbox svg{width:100%;display:block;filter:drop-shadow(0 0 2cqw rgba(34,225,255,.35))}
.bbx .flykey{position:absolute;z-index:9;width:5cqw;left:58%;bottom:25cqw;animation:bbx-fly 1.1s cubic-bezier(.3,.7,.2,1) both}
@keyframes bbx-fly{0%{transform:translate(-50%,0) rotate(-30deg) scale(.6);opacity:0}25%{opacity:1;transform:translate(-50%,-3cqw) rotate(0) scale(1.1)}100%{transform:translate(calc(-50% + var(--dx)),var(--dy)) scale(.4);opacity:0}}
.bbx .medal{width:6.4cqw;z-index:5;transform:translateX(-50%);bottom:33cqw}
.bbx .medal svg{width:100%;display:block;filter:drop-shadow(0 0 1.4cqw rgba(245,197,66,.7))}
.bbx .medal.fresh{animation:bbx-drop 1.1s cubic-bezier(.2,.9,.3,1.25) both}
@keyframes bbx-drop{from{transform:translateX(-50%) translateY(-10cqw) rotate(-30deg);opacity:0}}
.bbx .medal.glint svg{animation:bbx-glint 1.1s ease-out}
@keyframes bbx-glint{35%{filter:drop-shadow(0 0 5cqw #ffe9a8) brightness(1.7)}}
.bbx .wall{position:absolute;left:0;right:0;top:7.4cqw;z-index:5;display:flex;justify-content:center;gap:.7cqw;perspective:60cqw}
.bbx .mw{position:relative;width:5.9cqw;aspect-ratio:4/5;border-radius:.6cqw;overflow:hidden;background:var(--c);transform:rotateY(var(--ry)) translateZ(var(--tz));
  box-shadow:inset 0 0 0 .12cqw rgba(255,255,255,.3),0 .8cqw 1.6cqw rgba(0,0,0,.5);filter:brightness(.6) saturate(.7);transition:filter .5s,box-shadow .4s,transform .5s}
.bbx .mw img{position:absolute;inset:0;width:100%;height:100%;object-fit:cover;object-position:50% 14%}
.bbx .mw .i{position:absolute;inset:0;display:grid;place-items:center;font:900 2cqw Archivo;color:#fff}
.bbx .mw .lb{position:absolute;left:0;right:0;bottom:0;z-index:2;font:700 .7cqw 'Chakra Petch';letter-spacing:.06cqw;text-align:center;padding:.2cqw 0;background:rgba(0,0,0,.7);color:#fff;text-transform:uppercase}
.bbx .mw.hoh{filter:none;box-shadow:inset 0 0 0 .16cqw #f5c542,0 0 1.6cqw rgba(245,197,66,.5)}
.bbx .mw.hoh .lb{background:#f5c542;color:#2a1d00}
.bbx .mw.safe{filter:none}
.bbx .mw.safe .key{position:absolute;right:.25cqw;top:.25cqw;z-index:2;width:2cqw;filter:drop-shadow(0 0 .4cqw rgba(0,0,0,.8))}
.bbx .mw.nom{filter:none;box-shadow:inset 0 0 0 .18cqw #ff3355,0 0 2cqw rgba(255,51,85,.7);transform:rotateY(var(--ry)) translateZ(var(--tz)) translateY(.7cqw)}
.bbx .mw.nom .lb{background:#ff3355}
.bbx .mw.veto{box-shadow:inset 0 0 0 .16cqw #f5c542}
.bbx .mw.out{filter:grayscale(1) brightness(.35)}
.bbx .mw.out::after{content:"EVICTED";position:absolute;left:-20%;right:-20%;top:40%;z-index:3;transform:rotate(-24deg);text-align:center;font:900 .9cqw Archivo;font-stretch:80%;letter-spacing:.2cqw;background:#ff3355;color:#fff;padding:.15cqw 0}
.bbx .mw.fresh{animation:bbx-mwpop .7s ease-out}
@keyframes bbx-mwpop{35%{transform:rotateY(var(--ry)) translateZ(calc(var(--tz) + 3cqw)) scale(1.12)}}
.bbx .drring{position:absolute;left:50%;top:40%;width:36cqw;aspect-ratio:1;transform:translate(-50%,-50%);z-index:1}
.bbx .drring svg{width:100%;display:block}
.bbx .drring .r1{transform-origin:50% 50%;animation:bbx-spin 30s linear infinite}
.bbx .pop{position:absolute;z-index:9;transform:translateX(-50%);bottom:42cqw;display:flex;align-items:center;gap:.6cqw;white-space:nowrap;
  background:rgba(5,9,18,.88);border:.1cqw solid rgba(255,255,255,.15);border-radius:.6cqw;padding:.5cqw .9cqw .5cqw .5cqw;animation:bbx-pop 2.4s cubic-bezier(.2,.8,.2,1) forwards;backdrop-filter:blur(.6cqw)}
.bbx .pop .d{font:700 .85cqw 'Chakra Petch';letter-spacing:.12cqw;padding:.25cqw .5cqw;border-radius:.25cqw;text-transform:uppercase}
.bbx .pop .d.up{background:#12b76a;color:#fff}
.bbx .pop .d.down{background:#ff3355;color:#fff}
.bbx .pop .d.deal{background:#f5c542;color:#2a1d00}
.bbx .pop .d.love{background:#ff4fb0;color:#fff}
.bbx .pop b{font:800 1.15cqw Archivo;font-stretch:80%;letter-spacing:.06cqw;color:#fff;text-transform:uppercase}
.bbx .pop .bar{width:5cqw;height:.4cqw;border-radius:.2cqw;background:rgba(255,255,255,.15);overflow:hidden}
.bbx .pop .bar i{display:block;height:100%;width:var(--w);background:var(--bc);animation:bbx-bar 1s .2s cubic-bezier(.2,.8,.2,1) both}
@keyframes bbx-bar{from{width:var(--w0)}}
@keyframes bbx-pop{0%{opacity:0;transform:translate(-50%,1.2cqw)}10%{opacity:1;transform:translate(-50%,0)}82%{opacity:1}100%{opacity:0;transform:translate(-50%,-1.5cqw)}}
.bbx .toast{position:absolute;left:0;right:0;top:50%;z-index:11;transform:translateY(-50%);height:10cqw;display:grid;place-items:center;pointer-events:none;overflow:hidden;
  background:linear-gradient(90deg,transparent,color-mix(in srgb,var(--tc) 85%,#000) 18%,var(--tc) 50%,color-mix(in srgb,var(--tc) 85%,#000) 82%,transparent);animation:bbx-band 2s cubic-bezier(.2,.9,.2,1) forwards}
.bbx .toast b{font:900 6cqw Archivo;font-stretch:125%;letter-spacing:.8cqw;color:#fff;text-shadow:0 .3cqw 0 rgba(0,0,0,.25)}
.bbx .toast::after{content:"";position:absolute;inset:0;background:linear-gradient(100deg,transparent 35%,rgba(255,255,255,.45) 50%,transparent 65%);animation:bbx-shine 1s .15s both}
@keyframes bbx-band{0%{clip-path:inset(50% 0 50% 0)}12%{clip-path:inset(0 0 0 0)}80%{clip-path:inset(0 0 0 0);opacity:1}100%{clip-path:inset(0 0 0 0);opacity:0}}
.bbx .stage.shake .cam{animation:bbx-shake .45s}
@keyframes bbx-shake{20%{transform:translateX(-.9cqw)}40%{transform:translateX(.9cqw)}60%{transform:translateX(-.4cqw)}}
.bbx .flash{position:absolute;inset:0;z-index:12;background:#fff;animation:bbx-flash .3s ease-out forwards;pointer-events:none}
@keyframes bbx-flash{from{opacity:.75}to{opacity:0}}
.bbx .rest{position:absolute;inset:0;z-index:9;display:flex;flex-direction:column;align-items:center;justify-content:center;text-align:center;background:radial-gradient(ellipse at center,rgba(0,0,0,.25),rgba(0,0,0,.72))}
.bbx .rest .eye{width:9cqw;filter:drop-shadow(0 0 2cqw rgba(34,225,255,.5))}
.bbx .rest .k{margin-top:1.4cqw;font:700 1.15cqw 'Chakra Petch';letter-spacing:.5cqw;color:#22e1ff;text-transform:uppercase}
.bbx .rest .t{font:900 5.4cqw/1 Archivo;font-stretch:120%;color:#fff;margin:1cqw 0 .8cqw;letter-spacing:.1cqw;text-transform:uppercase}
.bbx .rest .s{font:500 1.6cqw Archivo;color:rgba(255,255,255,.75)}
.bbx .rest .go{margin-top:2.4cqw;font:700 1cqw 'Chakra Petch';letter-spacing:.4cqw;color:#001018;background:#22e1ff;padding:.6cqw 1.6cqw;border-radius:.3cqw}
.bbx .set.photo{background-size:cover!important;background-position:center!important}
.bbx .set.photo::before,.bbx .set.photo::after,.bbx .set.photo .floor{display:none}
.bbx .front{position:absolute;inset:0;width:100%;height:100%;pointer-events:none}
.bbx .nomscreen{position:absolute;z-index:1;display:flex;flex-direction:column;align-items:center;justify-content:center;gap:4%;
  background:radial-gradient(ellipse at 50% 20%,#ff5fb4,#d02c7a 55%,#7a1048);box-shadow:inset 0 0 0 .2cqw rgba(255,255,255,.25);overflow:hidden}
.bbx .nomscreen::before{content:"";position:absolute;inset:0;background:repeating-linear-gradient(115deg,rgba(255,255,255,.07) 0 1cqw,transparent 1cqw 3cqw)}
.bbx .nhead{position:relative;font:900 1.7cqw Archivo;font-stretch:75%;letter-spacing:.12cqw;color:#fff;padding:.25cqw 1.2cqw;
  background:linear-gradient(180deg,#9b2d8f,#5e1660);box-shadow:0 0 0 .18cqw #f1c6e6;text-shadow:0 .15cqw 0 #3a0a3a}
.bbx .nslots{position:relative;display:flex;gap:6%;width:84%;justify-content:center}
.bbx .nslot{position:relative;width:34%;aspect-ratio:1;background:linear-gradient(180deg,#2b3ea8,#16226a);border:.3cqw solid #d8deea;box-shadow:0 .3cqw .8cqw rgba(0,0,0,.35),inset 0 0 1.2cqw rgba(0,0,0,.5);box-sizing:border-box;
  display:grid;place-items:center;overflow:hidden}
.bbx .nslot i{font:900 5cqw/1 Archivo;font-style:normal;color:#fff;text-shadow:0 .25cqw 0 rgba(0,0,0,.35)}
.bbx .nslot img{position:absolute;inset:0;width:100%;height:82%;object-fit:cover;object-position:50% 18%}
.bbx .nslot.on{background:#fff}
.bbx .nslot b{position:absolute;left:0;right:0;bottom:0;height:18%;display:grid;place-items:center;font:800 1cqw Archivo;font-stretch:80%;letter-spacing:.1cqw;color:#fff;background:linear-gradient(180deg,#9b2d8f,#5e1660);text-transform:uppercase}
.bbx .nslot.flip{animation:bbx-nflip .7s cubic-bezier(.3,.7,.2,1) both}
@keyframes bbx-nflip{0%{transform:rotateY(90deg);filter:brightness(3)}100%{transform:none}}
.bbx .nkeys{position:absolute;transform:translateX(-50%);display:flex;justify-content:center;gap:12%}
.bbx .nkey{width:30%;aspect-ratio:1;clip-path:polygon(30% 0,70% 0,100% 30%,100% 70%,70% 100%,30% 100%,0 70%,0 30%);
  background:radial-gradient(circle at 40% 35%,#ffd36b,#e0731f 60%,#a8430c);display:grid;place-items:center;transition:transform .5s}
.bbx .nkey b{font:900 .8cqw Archivo;color:#5a1d00}
.bbx .nkey.turned{transform:rotate(90deg)}
.bbx .nkey.now{animation:bbx-nturn .6s cubic-bezier(.3,.8,.3,1.2) both}
@keyframes bbx-nturn{from{transform:rotate(0)}to{transform:rotate(90deg)}}
.bbx .chipx.key{background:#f5c542;color:#2a1d00}
.bbx .vchip{position:absolute;left:50%;top:40%;z-index:60;width:11cqw;aspect-ratio:1;transform:translate(-50%,-50%);border-radius:50%;
  background:radial-gradient(circle at 35% 30%,#fff8d8,#f5c542 55%,#a87a10);box-shadow:0 0 0 .3cqw #fff3c4,0 1.2cqw 3cqw rgba(0,0,0,.5);
  display:grid;place-items:center;overflow:hidden;animation:bbx-chipin .9s cubic-bezier(.2,.9,.3,1.3) both}
.bbx .vchip img{width:78%;height:78%;object-fit:cover;object-position:50% 14%;border-radius:50%;box-shadow:0 0 0 .2cqw #a87a10}
.bbx .vchip b{font:900 1.3cqw/1.05 Archivo;font-stretch:80%;letter-spacing:.06cqw;color:#3d2a00;text-align:center;text-transform:uppercase}
.bbx .vchip i{position:absolute;bottom:-3.2cqw;left:50%;transform:translateX(-50%);white-space:nowrap;font:700 .9cqw 'Chakra Petch';letter-spacing:.14cqw;color:#fff;text-transform:uppercase;font-style:normal}
@keyframes bbx-chipin{from{transform:translate(-50%,40%) scale(.3) rotate(-120deg);opacity:0}}
.bbx .wall.onwall{inset:0;left:0;right:0;top:0;display:block;perspective:none;z-index:1}
.bbx .wall.onwall .mw{position:absolute;transform:none;border-radius:.15cqw;width:auto}
.bbx .mf{position:absolute;padding:.32cqw;background:linear-gradient(135deg,#fbe7a6,#c9952f 35%,#f6d77e 55%,#8a6010);box-shadow:0 .35cqw .7cqw rgba(0,0,0,.45);transition:filter .6s,box-shadow .5s}
.bbx .mf.dark{background:linear-gradient(135deg,#4a4a52,#141418 45%,#3a3a42 70%,#0b0b0e)}
.bbx .mf .mfin{position:relative;width:100%;height:100%;overflow:hidden;background:var(--c);box-shadow:inset 0 0 0 .14cqw rgba(0,0,0,.55)}
.bbx .mf .mfin img{position:absolute;inset:0;width:100%;height:100%;object-fit:cover;object-position:50% 16%}
.bbx .mf.out .mfin img{filter:grayscale(1) contrast(1.1)}
.bbx .mf.out .mfin{background:#777}
.bbx .mf.nom{box-shadow:0 0 0 .18cqw #ff3355,0 0 1.6cqw rgba(255,51,85,.85)}
.bbx .mf.fresh{animation:bbx-mfpop .8s ease-out}
@keyframes bbx-mfpop{40%{transform:scale(1.18);filter:brightness(1.6)}}
.bbx .mft{position:absolute;left:50%;bottom:-.9cqw;transform:translateX(-50%);font:800 .55cqw Archivo;letter-spacing:.06cqw;background:#f5c542;color:#2a1d00;padding:.05cqw .35cqw;border-radius:.15cqw}
.bbx .wall.onwall .mw .lb{font-size:.5cqw}
.bbx .wall.onwall .mw.safe .key{width:1.1cqw}
.bbx .set-dr.photo~.drring{display:none}
.bbx .bgp{position:absolute;bottom:25.5cqw;width:7.6cqw;transform:translateX(-50%);z-index:2;transition:filter .5s,opacity .5s}
.bbx .bgp .tile{position:relative;aspect-ratio:4/5;border-radius:.8cqw;overflow:hidden;background:var(--c);
  box-shadow:inset 0 0 0 .1cqw rgba(255,255,255,.3),0 .8cqw 1.6cqw rgba(0,0,0,.35);
  -webkit-mask:linear-gradient(180deg,#000 62%,transparent 96%);mask:linear-gradient(180deg,#000 62%,transparent 96%)}
.bbx .bgp .tile img{position:absolute;inset:0;width:100%;height:100%;object-fit:cover;object-position:50% 14%}
.bbx .bgp{filter:blur(.12cqw) brightness(.78) saturate(.85)}
.bbx .bgp .doing{position:absolute;left:50%;top:-1.9cqw;transform:translateX(-50%);white-space:nowrap;font:600 .78cqw 'Chakra Petch';letter-spacing:.08cqw;color:#fff;
  background:rgba(5,9,18,.72);padding:.15cqw .55cqw;border-radius:.25cqw;text-transform:uppercase}
.bbx .bgp.react{filter:none}
.bbx .bgp.react .tile{box-shadow:inset 0 0 0 .14cqw #fff,0 0 1.6cqw rgba(255,255,255,.35)}
.bbx .bgp.in{animation:bbx-bgin .7s ease-out both}
@keyframes bbx-bgin{from{opacity:0;transform:translateX(-30%)}}
.bbx .rx{position:absolute;z-index:9;bottom:39.5cqw;transform:translateX(-50%);white-space:nowrap;font:italic 600 1.05cqw Archivo;color:#fff;
  background:rgba(5,9,18,.85);border:.1cqw solid rgba(255,255,255,.2);padding:.35cqw .8cqw;border-radius:.5cqw;animation:bbx-pop 2.6s cubic-bezier(.2,.8,.2,1) forwards}
.bbx .rx::before{content:"";display:inline-block;width:.6cqw;height:.6cqw;border-radius:50%;background:#22e1ff;margin-right:.5cqw;vertical-align:.08cqw}
.bbx .ap{position:absolute;inset:0;z-index:30;pointer-events:none;width:100%;height:100%}
.bbx .quad{position:absolute;inset:0;display:grid;grid-template-columns:1fr 1fr;grid-template-rows:1fr 1fr;gap:.35cqw;background:#000;padding:.35cqw}
.bbx .qf{position:relative;overflow:hidden;border-radius:.5cqw;filter:brightness(.45) saturate(.6);transition:filter .5s,box-shadow .3s}
.bbx .qf.on{filter:none;box-shadow:inset 0 0 0 .2cqw #22e1ff}
.bbx .qf .set{position:absolute;inset:0}
.bbx .qf .gt{width:7.4cqw;bottom:8.6cqw}
.bbx .qf .gt .plate{display:none}
.bbx .qf .lab{position:absolute;left:1.2cqw;bottom:.9cqw;z-index:5;font:700 .95cqw 'Chakra Petch';letter-spacing:.14cqw;color:#fff;text-shadow:0 0 .5cqw #000}
.bbx .qf .lab::before{content:"● ";color:#ff2e4d}
.bbx .qf.nvq .lens2{filter:grayscale(1) sepia(1) hue-rotate(62deg) saturate(2.4) brightness(1.08)}
.bbx .qf .lens2{position:absolute;inset:0}
.bbx .qf .cc{bottom:3.2cqw;max-width:40cqw}
.bbx .qf .cc span{font-size:1.25cqw}
/* ── the line: names and the words of the game light up; a short line lands with a punch ── */
.bbx .l3 .tx b.kn{font-weight:800;color:#fff}
.bbx .l3 .tx b.kw{font-weight:800;color:#7fe9ff}
.bbx .l3.dr .tx b.kw{color:#ffe08a}
.bbx .l3.host .tx b.kw{color:#ff9db0}
.bbx .l3 .tx.lit b{animation:bbx-lit .7s ease-out both}
@keyframes bbx-lit{from{text-shadow:0 0 1.2cqw currentColor}}
.bbx .l3.snap .body{animation:bbx-snap .34s cubic-bezier(.2,1.6,.4,1) both}
.bbx .l3.snap .tx{font-size:2.45cqw;font-weight:700}
@keyframes bbx-snap{from{transform:scale(.9);opacity:.15}}
/* ── the Diary Room is a pull quote: the houseguest on the left, the words large on the right ── */
.bbx .l3.dr{left:53cqw;right:3.4cqw;bottom:auto;top:52%;transform:translateY(-50%)}
.bbx .l3.dr .body{padding:2.4cqw 2.8cqw 2.5cqw 5.4cqw;min-height:0;background:linear-gradient(160deg,rgba(30,24,6,.88),rgba(6,6,10,.95))}
.bbx .l3.dr .body::before{width:.5cqw}
.bbx .l3.dr .tx{font:500 italic 2.3cqw/1.38 Archivo;color:#fffaf0}
.bbx .l3.dr .tx::after{content:none}
.bbx .l3.dr .tx::before{content:"\\201C";position:absolute;left:1.3cqw;top:.6cqw;font:900 normal 7.4cqw/1 Georgia,serif;color:#f5c542;opacity:.9}
.bbx .l3.dr.snap .tx{font-size:3cqw}
.bbx .drring{left:40%}
/* ── the room around a conversation breathes, and reacts to a loud moment ── */
.bbx .gt.bgp .tile{animation:bbx-idle 4.2s ease-in-out infinite;animation-delay:var(--d,0s)}
@keyframes bbx-idle{50%{translate:0 -.3cqw}}
.bbx .gt.bgp.react{filter:brightness(.88) saturate(.9);z-index:2}
.bbx .gt.bgp.react .tile{animation:bbx-jump .55s cubic-bezier(.2,1.6,.4,1) both}
.bbx .gt.bgp.react.laugh .tile{animation:bbx-shake .8s ease-in-out both}
@keyframes bbx-jump{40%{translate:0 -1.5cqw;scale:1.06}}
@keyframes bbx-shake{20%,60%{rotate:-5deg}40%,80%{rotate:5deg}}
.bbx .gt .rb{position:absolute;top:.3cqw;right:.3cqw;width:2.6cqw;height:2.6cqw;z-index:3;animation:bbx-pop .5s .1s cubic-bezier(.2,1.8,.4,1) both}
.bbx .gt .rb svg{width:100%;height:100%;display:block;filter:drop-shadow(0 .2cqw .4cqw rgba(0,0,0,.5))}
@keyframes bbx-pop{from{transform:scale(0)}}
/* ── a card at every cut: the day, the time, the room ── */
.bbx .slate{position:absolute;left:3.4cqw;top:9.4cqw;z-index:10;pointer-events:none;animation:bbx-slate 3.2s ease-out both}
.bbx .slate span{display:block;font:700 1.15cqw 'Chakra Petch';letter-spacing:.35cqw;color:#7fe9ff;text-shadow:0 .2cqw .8cqw rgba(0,0,0,.8)}
.bbx .slate b{display:block;font:900 4.4cqw/1 Archivo;font-stretch:72%;letter-spacing:.15cqw;text-transform:uppercase;color:#fff;text-shadow:0 .4cqw 1.6cqw rgba(0,0,0,.75)}
@keyframes bbx-slate{0%{opacity:0;transform:translateX(-3cqw)}12%{opacity:1;transform:none}72%{opacity:1}100%{opacity:0}}
/* ── the live eviction ── */
.bbx .ballots.fin{right:auto;left:50%;top:6.2cqw;transform:translateX(-50%);min-width:0;text-align:center}
.bbx .ballots{position:absolute;right:3.4cqw;top:12cqw;z-index:9;padding:1.2cqw 1.6cqw;min-width:16cqw;background:rgba(5,9,18,.9);border:.12cqw solid rgba(34,225,255,.35);border-radius:.8cqw;backdrop-filter:blur(1cqw)}
.bbx .ballots .k{font:800 .9cqw Archivo;font-stretch:78%;letter-spacing:.3cqw;text-transform:uppercase;color:#7fe9ff}
.bbx .ballots .n{font:700 3.6cqw/1.1 'Chakra Petch';color:#fff}
.bbx .ballots .n span{font-size:1.6cqw;color:rgba(255,255,255,.5);margin-left:.5cqw}
.bbx .ballots .pips{display:flex;flex-wrap:wrap;gap:.4cqw;margin-top:.6cqw;max-width:16cqw}
.bbx .ballots .pips i{width:1.1cqw;height:1.5cqw;border-radius:.2cqw;background:rgba(255,255,255,.12)}
.bbx .ballots .pips i.on{background:linear-gradient(180deg,#7fe9ff,#22a9ff)}
.bbx .ballots .pips i.new{animation:bbx-pip .6s cubic-bezier(.2,1.6,.4,1) both}
@keyframes bbx-pip{from{transform:translateY(-1.5cqw) scale(1.6);background:#fff}}
.bbx .ballots.locked{border-color:#ff2e4d}
.bbx .ballots.locked .k{color:#ff9db0}
.bbx .bigrev{position:absolute;left:50%;top:27%;transform:translate(-50%,-50%);z-index:200;text-align:center;pointer-events:none}
.bbx .bigrev::before{content:"";position:absolute;inset:-4cqw -10cqw;background:radial-gradient(closest-side,rgba(0,0,0,.88),rgba(0,0,0,.55) 60%,transparent);z-index:-1}
.bbx .bigrev i{display:block;font:700 normal 1.6cqw 'Chakra Petch';letter-spacing:.6cqw;text-transform:uppercase;color:rgba(255,255,255,.78)}
.bbx .bigrev b{display:block;font:900 9cqw/1 Archivo;font-stretch:72%;letter-spacing:.2cqw;white-space:nowrap;color:#fff;text-shadow:0 0 4cqw rgba(255,46,77,.65),0 .5cqw 2cqw rgba(0,0,0,.8)}
.bbx .bigrev.fresh i{animation:bbx-fadeup .8s ease-out both}
.bbx .bigrev.fresh b{animation:bbx-slam 1.6s .55s cubic-bezier(.2,.9,.2,1) both}
@keyframes bbx-slam{0%{opacity:0;transform:scale(1.8);filter:blur(1.4cqw)}60%{opacity:1;transform:scale(.98);filter:none}100%{transform:scale(1)}}
@keyframes bbx-fadeup{from{opacity:0;transform:translateY(1cqw)}}
.bbx .bigrev.name b{font-size:7.5cqw}
.bbx .bigrev.name i{display:inline-block;margin-top:.9cqw;padding:.5cqw 1.6cqw;font:900 2.2cqw Archivo;font-stretch:78%;letter-spacing:.8cqw;color:#fff;background:#ff2e4d;transform:rotate(-3deg)}
.bbx .bigrev.name.safe b{text-shadow:0 0 4cqw rgba(34,225,255,.7),0 .5cqw 2cqw rgba(0,0,0,.8)}
.bbx .bigrev.name.safe i{background:#1f9fff}
.bbx .bigrev.name.fresh b{animation:bbx-slam 1.2s .15s cubic-bezier(.2,.9,.2,1) both}
.bbx .bigrev.name.fresh i{animation:bbx-stamp .5s 1.1s cubic-bezier(.2,1.8,.4,1) both}
@keyframes bbx-stamp{from{opacity:0;transform:rotate(-3deg) scale(2.4)}}
.bbx .gt.tense{z-index:4;filter:none}
.bbx .gt.tense .tile{animation:bbx-tense 1.7s ease-in-out infinite;box-shadow:inset 0 0 0 .16cqw #ff2e4d,0 0 3.5cqw rgba(255,46,77,.55)}
@keyframes bbx-tense{50%{scale:1.06}}
.bbx .doorflood{position:absolute;inset:0;z-index:7;pointer-events:none;mix-blend-mode:screen;background:radial-gradient(ellipse 30% 62% at 50% 55%,rgba(255,250,232,.96),rgba(255,214,140,.5) 42%,transparent 76%);animation:bbx-flood 2.8s ease-out both}
@keyframes bbx-flood{0%{opacity:0;transform:scaleX(.08)}25%{opacity:1;transform:scaleX(1.15)}100%{opacity:0;transform:scaleX(1.7)}}
.bbx .gt.host{z-index:3}
.bbx .gt.host .tile{box-shadow:inset 0 0 0 .16cqw #ff2e4d,0 1.4cqw 3cqw rgba(0,0,0,.5)}
.bbx .gt.host .hostlab{font:800 .75cqw 'Chakra Petch';letter-spacing:.2cqw;color:#fff;background:#ff2e4d;padding:.1cqw .5cqw;border-radius:.3cqw}
/* ── what people do, animated (stage.js actionOf) ── */
.bbx .gt .fx{position:absolute;left:50%;top:-2.6cqw;transform:translateX(-50%);z-index:5;pointer-events:none}
.bbx .gt.act-shout .tile{animation:bbx-shout .5s cubic-bezier(.3,1.8,.5,1) both}
@keyframes bbx-shout{0%{scale:1}30%{scale:1.12;rotate:-2deg}55%{rotate:2deg}100%{scale:1.08;rotate:0deg}}
.bbx .fx-shout{width:12cqw;height:12cqw;top:1cqw}
.bbx .fx-shout i{position:absolute;inset:0;border:.4cqw solid #fff;border-radius:50%;opacity:0;box-shadow:0 0 1.2cqw var(--c,#fff),inset 0 0 1.2cqw var(--c,#fff);animation:bbx-ring 1.1s ease-out both}
.bbx .fx-shout i:nth-child(2){animation-delay:.15s}.bbx .fx-shout i:nth-child(3){animation-delay:.3s}
@keyframes bbx-ring{0%{opacity:.9;transform:scale(.4)}100%{opacity:0;transform:scale(1.6)}}
.bbx .gt.act-hug.toR .tile,.bbx .gt.act-kiss.toR .tile{animation:bbx-lean-r .7s ease-out both}
.bbx .gt.act-hug.toL .tile,.bbx .gt.act-kiss.toL .tile{animation:bbx-lean-l .7s ease-out both}
@keyframes bbx-lean-r{to{translate:3.2cqw 0;rotate:4deg}}
@keyframes bbx-lean-l{to{translate:-3.2cqw 0;rotate:-4deg}}
.bbx .gt.act-kiss.toR .tile{animation-name:bbx-kiss-r}.bbx .gt.act-kiss.toL .tile{animation-name:bbx-kiss-l}
@keyframes bbx-kiss-r{to{translate:5cqw 0;rotate:7deg}}
@keyframes bbx-kiss-l{to{translate:-5cqw 0;rotate:-7deg}}
.bbx .fx-heart{width:4cqw;left:auto;right:-4.4cqw;top:2cqw;transform:none;animation:bbx-heart 1.4s .45s cubic-bezier(.2,1.8,.4,1) both}
.bbx .fx-heart svg{width:100%;display:block;filter:drop-shadow(0 0 1cqw #ff4d7d)}
@keyframes bbx-heart{0%{opacity:0;transform:scale(0)}40%{opacity:1;transform:scale(1.25)}60%{transform:scale(1)}100%{opacity:1;transform:translateY(-2cqw)}}
.bbx .gt.act-storm .tile{animation:bbx-storm-l .9s ease-in both}
.bbx .gt.act-storm[style*="left:6"] .tile,.bbx .gt.act-storm[style*="left:7"] .tile,.bbx .gt.act-storm[style*="left:8"] .tile,.bbx .gt.act-storm[style*="left:9"] .tile{animation-name:bbx-storm-r}
@keyframes bbx-storm-l{30%{translate:1cqw 0}100%{translate:-30cqw 0;opacity:0}}
@keyframes bbx-storm-r{30%{translate:-1cqw 0}100%{translate:30cqw 0;opacity:0}}
.bbx .gt.act-cry .tile{animation:bbx-cry 1.2s ease-out both}
@keyframes bbx-cry{to{translate:0 .8cqw;filter:saturate(.6) brightness(.85)}}
.bbx .fx-tears{width:2.4cqw;top:3cqw;animation:bbx-tears 1.6s ease-in infinite}
.bbx .fx-tears svg{width:100%;display:block}
@keyframes bbx-tears{0%{opacity:0;translate:0 0}20%{opacity:1}100%{opacity:0;translate:0 4cqw}}
.bbx .gt.act-laugh .tile{animation:bbx-laugh .9s ease-in-out both}
@keyframes bbx-laugh{20%,60%{translate:0 -.9cqw;rotate:-3deg}40%,80%{translate:0 0;rotate:3deg}}
.bbx .gt.act-whisper.toR .tile{animation:bbx-whis-r .6s ease-out both}.bbx .gt.act-whisper.toL .tile{animation:bbx-whis-l .6s ease-out both}
@keyframes bbx-whis-r{to{translate:2cqw .4cqw;rotate:6deg}}
@keyframes bbx-whis-l{to{translate:-2cqw .4cqw;rotate:-6deg}}
.bbx .fx-hush{width:3cqw;top:.5cqw;left:auto;right:-3cqw;transform:none;opacity:.85;animation:bbx-pop .4s .3s both}
.bbx .fx-hush svg{width:100%;display:block}
.bbx .gt.act-sit .tile{animation:bbx-sit .5s cubic-bezier(.3,1.4,.5,1) both}
@keyframes bbx-sit{to{translate:0 1.6cqw;scale:.95}}
.bbx .gt.act-cheer .tile{animation:bbx-cheer .8s cubic-bezier(.3,1.6,.5,1) both}
@keyframes bbx-cheer{25%{translate:0 -1.8cqw}50%{translate:0 0}75%{translate:0 -1.1cqw}100%{translate:0 0}}
.bbx .fx-spark{width:3cqw;animation:bbx-spark 1s ease-out both}
.bbx .fx-spark svg{width:100%;display:block}
@keyframes bbx-spark{0%{opacity:0;transform:translateX(-50%) scale(0) rotate(0)}50%{opacity:1;transform:translateX(-50%) scale(1.3) rotate(90deg)}100%{opacity:0;transform:translateX(-50%) translateY(-2cqw) scale(1) rotate(180deg)}}
.bbx .fx-impact{position:absolute;inset:0;z-index:7;pointer-events:none;background:radial-gradient(circle at 50% 60%,rgba(255,255,255,.35),transparent 45%);animation:bbx-impact .45s ease-out both}
@keyframes bbx-impact{from{opacity:1;transform:scale(.6)}to{opacity:0;transform:scale(1.4)}}
/* ── the jury house: the same building's warmth, lamplit, slow ── */
.bbx .stage.lodge .set{filter:sepia(.55) saturate(1.25) brightness(.72) hue-rotate(-8deg)}
.bbx .stage.lodge .vign{background:radial-gradient(ellipse at 50% 40%,transparent 35%,rgba(30,16,4,.75))}
/* ── finale night: the key board, confetti, sweeping spotlights ── */
.bbx .gt.walk{animation:gtwalk 1s cubic-bezier(.45,0,.3,1) both}
@keyframes gtwalk{0%{transform:translateX(-50%) translate(var(--wx),var(--wy))}30%{transform:translateX(-50%) translate(calc(var(--wx) * .75),calc(var(--wy) * .75 - .6cqw))}60%{transform:translateX(-50%) translate(calc(var(--wx) * .3),calc(var(--wy) * .3 - .6cqw))}100%{transform:translateX(-50%)}}
.bbx .obj.keydrop{position:absolute;transform:translateX(-50%);z-index:30;animation:keydrop 1.1s cubic-bezier(.5,0,.8,.4) both;filter:drop-shadow(0 0 .8cqw #f5c542)}
@keyframes keydrop{0%{transform:translateX(-50%) translateY(-9cqw) rotate(-40deg);opacity:0}25%{opacity:1}70%{transform:translateX(-50%) translateY(0) rotate(90deg);opacity:1}100%{transform:translateX(-50%) translateY(1.2cqw) rotate(90deg) scale(.4);opacity:0}}
.bbx .obj.boxglow{position:absolute;transform:translateX(-50%);aspect-ratio:1.4;z-index:29;border-radius:50%;background:radial-gradient(closest-side,rgba(127,214,255,.85),rgba(127,214,255,0));opacity:0;animation:boxglow 1.4s .75s ease-out both}
@keyframes boxglow{0%{opacity:0;transform:translateX(-50%) scale(.6)}30%{opacity:1}100%{opacity:0;transform:translateX(-50%) scale(1.6)}}
.bbx .suspense{position:absolute;inset:0;z-index:8;pointer-events:none;background:radial-gradient(ellipse at 50% 45%,rgba(0,0,0,0) 35%,rgba(0,0,0,.62) 100%)}
.bbx .suspense.fresh{animation:suspense 1.6s ease-in-out infinite}
@keyframes suspense{0%,100%{opacity:.75}50%{opacity:1}}
.bbx .keyboard.fin{top:6.2cqw;padding:.5cqw 1.6cqw;z-index:190}
.bbx .keyboard.fin .kh{display:none}
.bbx .keyboard.fin .kr{gap:1.4cqw}
.bbx .keyboard.fin .kcol{flex-direction:row;gap:.8cqw;min-width:0}
.bbx .keyboard.fin .kcol:first-child{flex-direction:row-reverse}
.bbx .keyboard.fin .kf{width:2.6cqw}
.bbx .keyboard.fin b{font-size:1.2cqw}
.bbx .keyboard.fin .kn{font-size:2.6cqw}
.bbx .keyboard.fin .kp{min-height:0;min-width:2cqw}
.bbx .keyboard.fin .kp i{width:1.3cqw;height:1.3cqw}
.bbx .keyboard{position:absolute;left:50%;top:9cqw;transform:translateX(-50%);z-index:10;padding:1.2cqw 2cqw;background:rgba(10,8,2,.88);border:.15cqw solid #e8c98a;border-radius:1cqw;text-align:center;box-shadow:0 0 4cqw rgba(232,201,138,.25)}
.bbx .keyboard .kh{display:block;font:700 .95cqw 'Chakra Petch';letter-spacing:.4cqw;color:#e8c98a;margin-bottom:.8cqw}
.bbx .keyboard .kr{display:flex;align-items:center;gap:2.4cqw}
.bbx .keyboard .kcol{display:flex;flex-direction:column;align-items:center;gap:.4cqw;min-width:16cqw}
.bbx .keyboard .kf{width:5.4cqw;aspect-ratio:4/5;border-radius:.8cqw;overflow:hidden;background:var(--c);box-shadow:0 0 0 .2cqw rgba(255,255,255,.3)}
.bbx .keyboard .kf img{width:100%;height:100%;object-fit:cover;object-position:50% 14%}
.bbx .keyboard b{font:900 1.6cqw Archivo;font-stretch:78%;letter-spacing:.15cqw;color:#fff;text-transform:uppercase}
.bbx .keyboard .kn{font:700 4.4cqw/1 'Chakra Petch';color:#fff;text-shadow:0 0 2cqw rgba(232,201,138,.7)}
.bbx .keyboard .kn.bump{animation:bbx-bump .6s cubic-bezier(.2,1.8,.4,1) both}
@keyframes bbx-bump{0%{transform:scale(1.8);color:#f5c542}100%{transform:scale(1)}}
.bbx .keyboard .kp{display:flex;gap:.3cqw;min-height:2cqw}
.bbx .keyboard .kp i{width:2cqw;height:2cqw}.bbx .keyboard .kp i svg{width:100%;height:100%;display:block}
.bbx .keyboard .kp i.new{animation:bbx-keyin .7s cubic-bezier(.2,1.6,.4,1) both}
@keyframes bbx-keyin{from{transform:translateY(-3cqw) rotate(-90deg) scale(1.8);opacity:0}}
.bbx .keyboard .kvs{font:900 1.4cqw Archivo;color:#8e8371}
.bbx .keyboard .kcol.won .kf{box-shadow:0 0 0 .3cqw #f5c542,0 0 3cqw #f5c542}
.bbx .confetti{position:absolute;inset:0;z-index:13;pointer-events:none;overflow:hidden}
.bbx .confetti i{position:absolute;top:-4%;width:.9cqw;height:1.5cqw;border-radius:.15cqw;animation:bbx-confetti 3.2s var(--d) cubic-bezier(.3,.6,.5,1) both}
@keyframes bbx-confetti{0%{transform:translate(0,0) rotate(0);opacity:1}100%{transform:translate(var(--x),62cqw) rotate(var(--r));opacity:.9}}
.bbx .beams{position:absolute;inset:0;z-index:2;pointer-events:none;mix-blend-mode:screen}
.bbx .beams i{position:absolute;top:-10%;left:50%;width:12cqw;height:80cqw;transform-origin:50% 0;background:linear-gradient(180deg,rgba(255,236,190,.28),transparent 70%);filter:blur(1cqw);animation:bbx-beam 7s ease-in-out infinite}
.bbx .beams i:nth-child(1){left:20%;animation-delay:-2s}.bbx .beams i:nth-child(3){left:80%;animation-delay:-4.5s}
@keyframes bbx-beam{0%,100%{transform:rotate(-22deg)}50%{transform:rotate(22deg)}}
/* ── the final HOH parts: a board that moves as they play; the crowning's gold flash ── */
.bbx .fboard{position:absolute;right:3cqw;top:9cqw;z-index:10;min-width:24cqw;padding:1cqw 1.4cqw;background:rgba(5,9,18,.9);border:.12cqw solid rgba(245,197,66,.5);border-radius:.9cqw}
.bbx .fboard .fh{display:block;font:700 .9cqw 'Chakra Petch';letter-spacing:.35cqw;color:#f5c542;margin-bottom:.6cqw}
.bbx .fboard .fbr{display:flex;align-items:center;gap:.8cqw;padding:.35cqw 0;transition:opacity .4s}
.bbx .fboard .fbr.out{opacity:.45;filter:grayscale(.8)}
.bbx .fboard .ff{width:2.6cqw;aspect-ratio:4/5;border-radius:.4cqw;overflow:hidden;background:var(--c);flex:none}
.bbx .fboard .ff img{width:100%;height:100%;object-fit:cover;object-position:50% 14%}
.bbx .fboard b{font:800 1.1cqw Archivo;font-stretch:80%;color:#fff;text-transform:uppercase;min-width:8cqw}
.bbx .fboard .fbar{flex:1;height:.9cqw;border-radius:.45cqw;background:rgba(255,255,255,.1);overflow:hidden;min-width:9cqw}
.bbx .fboard .fbar i{display:block;height:100%;background:linear-gradient(90deg,#22e1ff,#f5c542);transition:width .7s cubic-bezier(.2,.8,.2,1)}
.bbx .fboard .ft{font:700 .95cqw 'Chakra Petch';letter-spacing:.15cqw;color:#c7d0e4;margin-left:auto}
.bbx .goldflash{position:absolute;inset:0;z-index:12;pointer-events:none;background:radial-gradient(circle at 50% 45%,rgba(255,226,140,.85),rgba(255,200,80,.25) 40%,transparent 70%);mix-blend-mode:screen;animation:bbx-goldflash 1.6s ease-out both}
@keyframes bbx-goldflash{0%{opacity:0;transform:scale(.4)}15%{opacity:1}100%{opacity:0;transform:scale(1.5)}}
/* ── an alliance is born: its title ── */
.bbx .alcard{position:absolute;left:50%;top:38%;z-index:12;transform:translate(-50%,-50%);text-align:center;pointer-events:none;animation:bbx-alcard 3.6s ease-out both}
.bbx .alcard::before{content:"";position:absolute;inset:-3cqw -9cqw;z-index:-1;background:radial-gradient(closest-side,rgba(10,8,2,.92),rgba(10,8,2,.6) 60%,transparent)}
.bbx .alcard i{display:block;font:700 normal 1.3cqw 'Chakra Petch';letter-spacing:.6cqw;color:#f5c542}
.bbx .alcard b{display:block;font:900 6.4cqw/1.05 Archivo;font-stretch:72%;letter-spacing:.15cqw;color:#fff;text-transform:uppercase;white-space:nowrap;text-shadow:0 0 3cqw rgba(245,197,66,.6),0 .4cqw 1.6cqw rgba(0,0,0,.8)}
.bbx .alcard .alfs{display:flex;justify-content:center;gap:.8cqw;margin-top:1.2cqw}
.bbx .alcard .alf{width:5cqw;aspect-ratio:4/5;border-radius:.8cqw;overflow:hidden;background:var(--c);box-shadow:0 0 0 .2cqw #f5c542;animation:bbx-alf .5s calc(.6s + var(--i) * .12s) cubic-bezier(.2,1.6,.4,1) both}
.bbx .alcard .alf img{width:100%;height:100%;object-fit:cover;object-position:50% 14%}
@keyframes bbx-alcard{0%{opacity:0;transform:translate(-50%,-50%) scale(1.6);filter:blur(1cqw)}12%{opacity:1;transform:translate(-50%,-50%) scale(.98);filter:none}18%{transform:translate(-50%,-50%) scale(1)}82%{opacity:1}100%{opacity:0}}
@keyframes bbx-alf{from{opacity:0;transform:translateY(1.5cqw) scale(.6)}}
.bbx .alcard.joined i{color:#7fe9ff}.bbx .alcard.joined .alf{box-shadow:0 0 0 .2cqw #22e1ff}
.bbx .alcard.out i{color:#ff9db0}.bbx .alcard.out b{text-decoration:line-through;text-decoration-color:#ff2e4d;text-decoration-thickness:.4cqw}
.bbx .alcard.out .alf{box-shadow:0 0 0 .2cqw #ff2e4d;filter:grayscale(.6)}
.bbx .alcard.meeting i{color:#fff}
.bbx .alcard.deal i{color:#ffd76a}.bbx .alcard.deal .alf{box-shadow:0 0 0 .2cqw #ffd76a}
@media (prefers-reduced-motion:reduce){.bbx .gt[class*="act-"] .tile,.bbx .gt .fx,.bbx .beams i,.bbx .confetti i{animation:none}}
@media (prefers-reduced-motion:reduce){.bbx .gt.bgp .tile,.bbx .gt.tense .tile{animation:none}}`;
