// GENERATED by tools/bb-intro/render.py: the cast each rendered title sequence shows.
// The viewer plays a season's rendered titles only when this is the cast in the game; any other
// season gets the live titles built from its own houseguests (titles.js). Do not edit by hand.
export const TITLE_CASTS = {"bb-1":["Aaron","Amberly","Dylon","Felipe","Gyselle","Harriett","Hasan","Ireland","Jane","Joel","Jules","Misha","Natasha","Nico","Stella","Tobias","Zella"]};
