"""Where every Total Drama plate has water, as a coarse grid the viewer can stand people by.

    python tools/td-camp/wetgrid.py

Reads each plate's water mask (assets/sets/td/<venue>/<spot>-<tod>-water.webp, written by camp.py
from clean.py's motion map: the water's own pixels) and writes js/vp-td-ep/wet.js: for each plate
key (the same keys as marks.js), 36 rows of 64 cells, each row a hex string, a set bit = water.
The user, 2026-10-10: "dont put people in the water if they're not swimming ... respect the venues".
Re-run after clean.py + camp.py change a plate's water.
"""
import glob, os
from PIL import Image

REPO = os.path.abspath(os.path.join(os.path.dirname(__file__), '..', '..'))
COLS, ROWS = 64, 36
out = {}
for f in sorted(glob.glob(os.path.join(REPO, 'assets', 'sets', 'td', '*', '*-water.webp'))):
    venue = os.path.basename(os.path.dirname(f))
    spot = os.path.basename(f)[:-len('-water.webp')]
    if spot.endswith('-hd') or '~' in spot:
        continue
    a = Image.open(f).getchannel('A').resize((COLS, ROWS), Image.BOX)
    px = a.load()
    rows = []
    for y in range(ROWS):
        bits = 0
        for x in range(COLS):
            if px[x, y] > 128:
                bits |= 1 << x
        rows.append(format(bits, '016x'))
    if any(int(r, 16) for r in rows):
        out[f'{venue}/{spot}'] = rows

body = ',\n'.join(f'  {k!r}: [{", ".join(repr(r) for r in v)}]' for k, v in out.items())
js = (
    '// GENERATED by tools/td-camp/wetgrid.py from each plate\'s water mask - do not edit by hand.\n'
    '// Where the water is on every Total Drama plate: 36 rows of 64 cells, each row a hex string (bit x = column x),\n'
    '// a set bit is water. steps.js keeps anybody not on an authored mark out of it.\n'
    f'export const WET_COLS = {COLS}, WET_ROWS = {ROWS};\n'
    'export const TD_WET = {\n' + body + '\n};\n'
)
open(os.path.join(REPO, 'js', 'vp-td-ep', 'wet.js'), 'w', encoding='utf-8', newline='\n').write(js)
print('plates with water:', len(out))
