// ══════════════════════════════════════════════════════════════════════
// td/script/lines/isle-group.js — three people on one island
// ══════════════════════════════════════════════════════════════════════
//
// isle.trio.<kind> — a pair moment (lines/isle.js) that a third resident, {c}, walks into:
//   they take a side, break it up, make it worse, or join in.
// isle.group.<kind> — a whole-island moment (rescue-island.js _islandGroupMoment):
//   'breakfast' (food and the jabs that come with it), 'storm' (everyone saving the
//   shelter), 'fire' (stories after dark), 'chores' ({a} and {b} fight about who does
//   what; {c} gets dragged in), 'comeback' (who deserves to go back: {a} and {b} both
//   say themselves).
// Modelled on the Disventure Camp "Rescue Island" episode: chores under every scene,
// short lines that answer each other, a jab that gets a jab back, and a fight that
// turns into somebody's story about home.
// {isle} and intent as in lines/isle.js. Ids: 'ig.'.
const DUEL = { intent: 'duel' }, BACK = { intent: 'return' };

// ── a third walks in ──────────────────────────────────────────────────
const T_GRUDGE = [
  { id: 'ig.g1', when: { wrote: true }, turns: [
    { by: 'a', say: "You know exactly what you did." },
    { by: 'b', say: "And you'd have done the same thing!" },
    { by: 'c', say: "Can you two do this somewhere I'm not eating?" },
    { by: 'a', say: "Stay out of it." },
    { by: 'c', say: "Happily. Move the fight down the beach." },
    { by: 'c', conf: "Every day it's the same argument. I could do both their lines by now." },
  ] },
  { id: 'ig.g2', turns: [
    { by: 'a', say: "Tell {c} what you told me at the last vote. Go on." },
    { by: 'b', say: "I don't owe anybody an explanation." },
    { by: 'c', say: "Actually, I'd love to hear it." },
    { by: 'b', say: "Oh, great. Now there's two of you." },
    { by: 'a', conf: "I don't need {c} on my side. But it doesn't hurt." },
  ] },
  { id: 'ig.g3', turns: [
    { beat: '{a} and {b} are squaring up by the water. {c} steps right between them.' },
    { by: 'c', say: "Okay! Okay. Nobody's throwing anything." },
    { by: 'a', say: "Nobody was going to throw anything." },
    { by: 'c', say: "You're holding a coconut." },
    { by: 'a', say: "...It's my coconut." },
    { by: 'c', conf: "Somebody has to be the adult out here. Apparently it's me. That's terrifying." },
  ] },
  { id: 'ig.g4', when: { register: 'fiery' }, turns: [
    { by: 'a', say: "You've got some nerve even looking at me!" },
    { by: 'b', say: "It's a small island! Where am I supposed to look?" },
    { by: 'c', say: "At the ocean? It's huge. It's everywhere." },
    { by: 'a', say: "Not helping!" },
    { by: 'b', conf: "{a} hasn't forgiven me. {c} thinks it's a comedy show. I'm the only normal one here." },
  ] },
  { id: 'ig.g5', when: { wrote: true }, turns: [
    { by: 'b', say: "{c}, back me up. It was a game move. That's all." },
    { by: 'c', say: "I'm not getting in the middle of this." },
    { by: 'a', say: "You're already in the middle of it. You're standing right there." },
    { by: 'c', say: "Then I'm leaving the middle." },
    { beat: '{c} walks away. {a} and {b} glare at each other.' },
    { by: 'c', conf: "If I pick a side, I lose a friend. If I don't, I lose two. Great choices." },
  ] },
  { id: 'ig.g6', when: { register: 'schemer' }, turns: [
    { by: 'a', say: "Funny. {c} was just telling me what you said about {c.obj} in the game." },
    { by: 'c', say: "I was?" },
    { by: 'b', say: "I never said anything about {c}!" },
    { by: 'a', say: "Then why are you so nervous?" },
    { by: 'a', conf: "If {b} is busy defending {b.ref} to {c}, {b} isn't coming after me." },
  ] },
  { id: 'ig.g7', turns: [
    { beat: '{a} and {b} are glaring at each other across the fire. {c} sits down right in the middle.' },
    { by: 'c', say: "So. Lovely evening." },
    { by: 'a', say: "Don't." },
    { by: 'b', say: "Seriously, {c}. Not now." },
    { by: 'c', say: "I'm just sitting. Sitting is allowed." },
    { by: 'c', conf: "Somebody has to stand between those two. Today I sat between them. It worked." },
  ] },
];
const T_BLOWUP = [
  { id: 'ig.b1', turns: [
    { by: 'b', say: "You let the fire go out AGAIN!" },
    { by: 'a', say: "It's not my job to babysit the fire!" },
    { by: 'b', say: "It was literally your job! We made a chart!" },
    { by: 'c', say: "Guys! Guys. The chart was a drawing in the sand. The tide took it." },
    { by: 'a', say: "SEE?" },
    { by: 'c', conf: "Two grown people screaming about a sand chart. This is my life now." },
  ] },
  { id: 'ig.b2', turns: [
    { by: 'a', say: "You've been lying to everybody since you got here!" },
    { by: 'b', say: "Name one lie!" },
    { by: 'a', say: "You said you were 'just here to have fun'!" },
    { by: 'c', say: "Okay, everybody says that." },
    { by: 'b', say: "Thank you!" },
    { by: 'c', say: "I didn't say it was true." },
    { by: 'b', conf: "I came out here for some peace and quiet. I have got neither." },
  ] },
  { id: 'ig.b3', turns: [
    { beat: "{a} and {b} are yelling over each other. {c} sticks two fingers in {c.posAdj} mouth and whistles, loud." },
    { by: 'c', say: "ENOUGH!" },
    { beat: 'Silence. Even the birds stop.' },
    { by: 'c', say: "Thank you. Now somebody go get water. Separately." },
    { by: 'c', conf: "I didn't know I could do that. I'm doing it again tomorrow." },
  ] },
  { id: 'ig.b4', when: { register: 'fiery' }, turns: [
    { by: 'a', say: "I'm sick of you! I've been sick of you since day one!" },
    { by: 'b', say: "Then go live on the other side of the island!" },
    { by: 'a', say: "Maybe I will!" },
    { by: 'c', say: "Please do. Both of you. Different sides." },
    { by: 'a', conf: "Even {c} took {b}'s side. Whatever. I don't need either of them." },
  ] },
  { id: 'ig.b5', turns: [
    { by: 'b', say: "You took my blanket last night!" },
    { by: 'a', say: "You took MY blanket two nights ago!" },
    { by: 'b', say: "That was a different blanket!" },
    { by: 'c', say: "We only have one blanket." },
    { beat: 'Everyone stops and looks at the one blanket.' },
    { by: 'c', conf: "We're fighting over one blanket on an island. If anyone back home is watching, I'm so sorry." },
  ] },
  { id: 'ig.b6', turns: [
    { by: 'a', say: "Don't you walk away from me!" },
    { by: 'b', say: "Watch me!" },
    { by: 'c', say: "Can I just say, this is the most exciting thing that's happened here all week." },
    { by: 'a', say: "{c}!" },
    { by: 'c', say: "Sorry! Sorry. Carry on." },
    { by: 'c', conf: "I'm not proud of it. But I was really enjoying that." },
  ] },
];
const T_COMEDY = [
  { id: 'ig.c1', turns: [
    { beat: '{a} is trying to crack a coconut with a rock. {b} and {c} are watching.' },
    { by: 'b', say: "Five bucks says the coconut wins." },
    { by: 'c', say: "Ten says {a} hurts {a.ref}." },
    { beat: 'The rock slips. {a} hops around holding {a.posAdj} thumb.' },
    { by: 'c', say: "Pay up." },
    { by: 'a', conf: "I didn't get the coconut open. I did make two people very happy." },
  ] },
  { id: 'ig.c2', turns: [
    { by: 'a', say: "I've invented a new dish. Fish, rice, and a secret ingredient." },
    { by: 'b', say: "Is the secret ingredient sand?" },
    { by: 'a', say: "...Partly sand." },
    { by: 'c', say: "I'll try it." },
    { beat: '{c} tries it. {c} keeps a straight face for three whole seconds.' },
    { by: 'b', conf: "{c} said it was 'interesting'. That's island for 'please never cook again'." },
  ] },
  { id: 'ig.c3', turns: [
    { beat: "A crab marches straight through camp with {a}'s sock in its claw." },
    { by: 'a', say: "Somebody stop it!" },
    { by: 'b', say: "I'm not fighting a crab for your sock." },
    { by: 'c', say: "I'll fight it. Fifty-fifty I win." },
    { beat: "{c} lunges. The crab wins." },
    { by: 'a', conf: "We lost to a crab. As a group. That's where we're at." },
  ] },
  { id: 'ig.c4', turns: [
    { by: 'b', say: "Okay, rank us. Who's the worst at surviving out here?" },
    { by: 'c', say: "{a}." },
    { by: 'a', say: "Excuse me?" },
    { by: 'c', say: "You tried to start a fire with a wet stick for an hour." },
    { by: 'a', say: "It was damp! Not wet!" },
    { by: 'b', conf: "We have nothing to do out here. So we roast each other. It's honestly the best part." },
  ] },
  { id: 'ig.c5', turns: [
    { beat: '{a} has built a "shower" out of a coconut shell with holes in it. {b} and {c} watch {a} test it.' },
    { by: 'a', say: "Behold. Luxury." },
    { beat: 'It drips three drops and falls on {a}\'s head.' },
    { by: 'b', say: "Luxury." },
    { by: 'c', say: "Five stars." },
    { by: 'a', conf: "They laughed, but I saw {b} sneak a turn later. I saw." },
  ] },
  { id: 'ig.c6', turns: [
    { by: 'a', say: "If you could have one thing from home right now, what would it be?" },
    { by: 'b', say: "My bed." },
    { by: 'c', say: "A burger." },
    { by: 'a', say: "Toilet paper." },
    { beat: '{b} and {c} look at each other.' },
    { by: 'b', say: "...Okay, yeah. Toilet paper." },
    { by: 'c', conf: "{a} won that round. Nobody even argued." },
  ] },
];
const T_LATE = [
  { id: 'ig.l1', turns: [
    { beat: "It's late. {a} and {b} are talking by the fire. {c} sits up in the shelter, awake too." },
    { by: 'c', say: "Mind if I join? I can't sleep either." },
    { by: 'a', say: "Pull up a log." },
    { by: 'b', say: "We were just saying what we miss most." },
    { by: 'c', say: "My friends back home. They'd love it out here. For about a day." },
    { by: 'b', conf: "Three people who got voted out, sitting by a fire. Somehow it's the best night I've had." },
  ] },
  { id: 'ig.l2', turns: [
    { by: 'a', say: "Do you guys ever think about just going home?" },
    { by: 'b', say: "Every night." },
    { by: 'c', say: "Every morning, actually. Nights are fine. Mornings are rice." },
    { beat: 'They all laugh quietly so they don\'t wake anybody.' },
    { by: 'a', conf: "Out here at night, nobody's playing. We're just people." },
  ] },
  { id: 'ig.l3', turns: [
    { by: 'b', say: "What's the worst thing anyone said to you in the game?" },
    { by: 'a', say: "That I was 'easy to beat at the end.'" },
    { by: 'c', say: "Ouch." },
    { by: 'a', say: "Yeah. I think about it every time I train." },
    { by: 'c', conf: "I came over to warm my hands. I left knowing more about {a} than in the whole game." },
  ] },
  { id: 'ig.l4', turns: [
    { beat: '{a}, {b} and {c} lie on their backs by the fire, pointing at the stars.' },
    { by: 'c', say: "That one looks like a pan." },
    { by: 'b', say: "Everything looks like food to you." },
    { by: 'c', say: "Everything IS food to me. I'm starving." },
    { by: 'a', conf: "Weird thing to say, but I'll miss nights like this when I'm back in the game." },
  ] },
  { id: 'ig.l5', turns: [
    { by: 'a', say: "Can I tell you two something? I'm scared I won't make it back." },
    { by: 'b', say: "Same." },
    { by: 'c', say: "Same. Literally everyone here. Same." },
    { by: 'a', say: "Okay. That's weirdly comforting." },
    { by: 'b', conf: "Only one of us gets out of here. For one night, that didn't matter." },
  ] },
  { id: 'ig.l6', when: { register: 'schemer' }, turns: [
    { beat: '{a} and {b} are whispering late at night. {c} sits down right between them.' },
    { by: 'c', say: "What are we whispering about?" },
    { by: 'a', say: "Nothing. Home stuff." },
    { by: 'c', say: "You were saying my name." },
    { by: 'a', say: "Home stuff about you. Go to sleep." },
    { by: 'a', conf: "{c} has ears like a bat. I'm going to have to whisper quieter." },
  ] },
];
const T_CLOSE = [
  { id: 'ig.cl1', turns: [
    { by: 'a', say: "We're splitting the last coconut. You want in, {c}?" },
    { by: 'c', say: "Three ways? That's like two bites." },
    { by: 'b', say: "Two bites with friends." },
    { by: 'c', say: "Okay, that was cheesy. I'm in." },
    { by: 'b', conf: "Out here, half a coconut and some company is a good day." },
  ] },
  { id: 'ig.cl2', turns: [
    { by: 'c', say: "You two are joined at the hip. It's actually sweet." },
    { by: 'a', say: "Jealous?" },
    { by: 'c', say: "A little. Scoot over." },
    { beat: 'They make room. {c} squeezes in between them.' },
    { by: 'c', conf: "I came out here thinking everybody would be a rival. {a} and {b} kind of adopted me." },
  ] },
  { id: 'ig.cl3', turns: [
    { by: 'b', say: "Whatever happens, I'm glad it's you two out here with me." },
    { by: 'a', say: "Don't make me cry. I'm dehydrated enough." },
    { by: 'c', say: "Too late. I'm crying." },
    { by: 'a', conf: "We've got each other. It doesn't sound like much. Out here it's everything." },
  ] },
  { id: 'ig.cl4', turns: [
    { beat: '{a} wakes up shivering. {b} and {c} pile their spare clothes on top of {a.obj} without saying anything.' },
    { by: 'a', say: "You guys didn't have to." },
    { by: 'c', say: "We did. Go back to sleep." },
    { by: 'a', conf: "Nobody asked them. They just did it. I'm not going to forget that." },
  ] },
  { id: 'ig.cl5', turns: [
    { by: 'c', say: "Group hug. Come on." },
    { by: 'a', say: "Absolutely not." },
    { by: 'b', say: "Come on, {a}." },
    { beat: '{a} sighs and steps in. {c} squeezes way too hard.' },
    { by: 'a', say: "Okay. Okay! I need my ribs!" },
    { by: 'b', conf: "{a} says hugs are gross. {a} was smiling the whole time." },
  ] },
  { id: 'ig.cl6', turns: [
    { by: 'a', say: "If one of us gets back in, we don't forget the other two. Deal?" },
    { by: 'b', say: "Deal." },
    { by: 'c', say: "Deal. Even if it's {b} and {b} gets weird about it." },
    { by: 'b', say: "I won't get weird!" },
    { by: 'c', conf: "Friends on an island. It's not strategy. It's just nice." },
  ] },
];
const T_PETTY = [
  { id: 'ig.p1', turns: [
    { by: 'a', say: "{c}, settle this. Who hogged the tarp last night?" },
    { by: 'c', say: "Both of you. And {b} snores." },
    { by: 'b', say: "I do not snore!" },
    { by: 'c', say: "You snore like a boat engine." },
    { by: 'a', say: "Ha!" },
    { by: 'c', conf: "Being the judge out here means everybody's mad at you. At least it's something to do." },
  ] },
  { id: 'ig.p2', turns: [
    { by: 'b', say: "Who ate the last of the rice?" },
    { by: 'a', say: "Not me." },
    { by: 'c', say: "Not me." },
    { beat: '{a} and {c} both have rice on their faces.' },
    { by: 'b', say: "Unbelievable. Both of you?" },
    { by: 'b', conf: "Two thieves and one victim. I'm the victim. Write that down." },
  ] },
  { id: 'ig.p3', turns: [
    { by: 'a', say: "That's my side of the shelter." },
    { by: 'b', say: "There are no sides!" },
    { by: 'c', say: "There's a line in the sand. Somebody drew a line." },
    { by: 'a', say: "I drew a line." },
    { by: 'c', conf: "Somebody drew a border in the shelter. We're three people. We have borders now." },
  ] },
  { id: 'ig.p4', turns: [
    { by: 'b', say: "You took the big piece of fish again." },
    { by: 'a', say: "{c} gave it to me!" },
    { by: 'c', say: "I did not!" },
    { by: 'a', say: "You looked at me like you were giving it to me." },
    { by: 'c', conf: "Apparently I can give people fish with my eyes now. Good to know." },
  ] },
  { id: 'ig.p5', when: { register: 'fiery' }, turns: [
    { by: 'a', say: "Who keeps moving my shoes?!" },
    { by: 'b', say: "Nobody wants your shoes!" },
    { by: 'c', say: "A crab might want your shoes." },
    { by: 'a', say: "This isn't funny!" },
    { by: 'c', say: "It's a little funny." },
    { by: 'b', conf: "{a} has accused everyone and every animal of stealing those shoes." },
  ] },
  { id: 'ig.p6', turns: [
    { by: 'a', say: "Can somebody else get water for once?" },
    { by: 'b', say: "I got it yesterday." },
    { by: 'c', say: "I got it the day before." },
    { by: 'a', say: "And I got it the day before that! So it's somebody's turn!" },
    { beat: 'Nobody moves.' },
    { by: 'c', conf: "Three people, one bucket. We're going to die of thirst out of pride." },
  ] },
];
const T_PACT = [
  { id: 'ig.pa1', turns: [
    { by: 'a', say: "If one of us gets back in, we pull the others in after. Deal?" },
    { by: 'b', say: "Deal." },
    { by: 'c', say: "Wait, what deal? I'm in. Whatever it is." },
    { by: 'a', say: "You weren't even listening." },
    { by: 'c', say: "I don't need to listen. I need to be in it." },
    { by: 'a', conf: "Two was a pact. Three is an alliance. Nobody in the game sees this coming." },
  ] },
  { id: 'ig.pa2', turns: [
    { beat: '{a} and {b} are shaking on something. {c} walks up holding firewood.' },
    { by: 'c', say: "What did I miss?" },
    { by: 'b', say: "A plan. For when one of us gets back." },
    { by: 'c', say: "Is there room in the plan?" },
    { by: 'a', say: "There could be." },
    { by: 'c', conf: "I almost missed an alliance because I was getting firewood. Never getting firewood again." },
  ] },
  { id: 'ig.pa3', turns: [
    { by: 'a', say: "We stick together. Whoever goes back, the other two have a friend inside." },
    { by: 'c', say: "And whoever goes back owes the other two." },
    { by: 'b', say: "Owes them what?" },
    { by: 'c', say: "Loyalty. And maybe a burger at the end." },
    { by: 'b', conf: "Three people with nothing. Now three people with a plan." },
  ] },
  { id: 'ig.pa4', turns: [
    { by: 'b', say: "You two are making a deal, aren't you?" },
    { by: 'a', say: "Maybe." },
    { by: 'b', say: "Make it three." },
    { by: 'c', say: "Why should we?" },
    { by: 'b', say: "Because I'm the one who catches the fish." },
    { by: 'c', conf: "Fair point. We took the deal. We also took the fish." },
  ] },
  { id: 'ig.pa5', when: { register: 'schemer' }, turns: [
    { by: 'a', say: "Here's the deal. Whoever gets back in brings the others' names to nobody. Ever." },
    { by: 'b', say: "And goes after the people who sent us here." },
    { by: 'c', say: "Together." },
    { by: 'a', say: "Together." },
    { by: 'a', conf: "Three friends who owe each other. That's worth more than an idol." },
  ] },
  { id: 'ig.pa6', turns: [
    { beat: '{a}, {b} and {c} stack their hands on top of each other, a little embarrassed about it.' },
    { by: 'c', say: "Are we really doing a hand thing?" },
    { by: 'a', say: "We're doing a hand thing." },
    { by: 'b', say: "Three, two, one, back in the game!" },
    { by: 'c', conf: "Cheesy. Very cheesy. I'd do it again." },
  ] },
];
const T_NOTES = [
  { id: 'ig.n1', turns: [
    { by: 'a', say: "Okay, everybody say who voted for them. We'll find the pattern." },
    { by: 'b', say: "That's going to take a while." },
    { by: 'c', say: "We've got nothing but time." },
    { beat: 'They draw the old camp in the sand. Names. Arrows. More arrows.' },
    { by: 'b', conf: "Three people's worth of notes. We know more about the game than the people still in it." },
  ] },
  { id: 'ig.n2', turns: [
    { by: 'c', say: "The quiet ones. It's always the quiet ones." },
    { by: 'a', say: "No, it's the loud ones. They hide behind the noise." },
    { by: 'b', say: "It's both. Quiet ones plan, loud ones take the heat." },
    { by: 'c', say: "Okay, {b} wins." },
    { by: 'a', conf: "We figured out more in an afternoon out here than I did in weeks in the game." },
  ] },
  { id: 'ig.n3', turns: [
    { by: 'a', say: "Who do you think is running it now?" },
    { by: 'b', say: "Not who everyone thinks." },
    { by: 'c', say: "Agreed. Whoever looks in charge is the shield." },
    { by: 'a', say: "Then who's behind the shield?" },
    { beat: 'All three of them think of the same name at the same time.' },
    { by: 'c', conf: "When three people out here agree on something, it's probably true." },
  ] },
  { id: 'ig.n4', turns: [
    { by: 'b', say: "{c}, you were on the other tribe. What were they saying about us?" },
    { by: 'c', say: "Honestly? That you two were a pair. Easy to split." },
    { by: 'a', say: "We weren't even a pair back then!" },
    { by: 'c', say: "Didn't matter. That's what they thought." },
    { by: 'a', conf: "{c} just explained why I got voted out. Wish somebody had told me a week ago." },
  ] },
  { id: 'ig.n5', when: { register: 'cool' }, turns: [
    { by: 'a', say: "Go through it with me. Every vote, in order." },
    { by: 'c', say: "Why in order?" },
    { by: 'a', say: "Because the order tells you who was scared of who." },
    { by: 'b', say: "That's actually smart." },
    { by: 'b', conf: "{a} remembers every single vote. With dates. I'm a little scared." },
  ] },
  { id: 'ig.n6', turns: [
    { by: 'c', say: "If you go back first, who do you talk to first?" },
    { by: 'a', say: "Whoever's on the bottom." },
    { by: 'b', say: "Whoever's on the bottom is scared and will say yes to anything." },
    { by: 'c', say: "So we all agree. Find the bottom." },
    { by: 'b', conf: "We're not even in the game and we're running it better than the people inside." },
  ] },
  { id: 'ig.n7', turns: [
    { beat: '{b} scratches three columns into a flat rock with a shell: SAFE, MAYBE, DONE.' },
    { by: 'b', say: "Everyone still in the game goes in one of these. Go." },
    { by: 'a', say: "Put the loudest one under DONE. Nobody keeps a loudmouth past the merge." },
    { by: 'c', say: "Funny. That's exactly what they said about you." },
    { by: 'a', say: "And look where I am. So I was right." },
    { by: 'b', say: "That's... not the win you think it is." },
    { by: 'c', conf: "Out here the scoreboard is a rock. Somehow it's still more honest than the game." },
  ] },
  { id: 'ig.n8', turns: [
    { by: 'c', say: "Be honest. What was the moment you knew you were going home?" },
    { by: 'a', say: "When they stopped arguing with me. Nobody fights with a dead person." },
    { by: 'b', say: "Mine was breakfast. Everybody was suddenly really nice to me." },
    { by: 'c', say: "Ugh. The breakfast. They did the breakfast to me too." },
    { beat: 'All three of them go quiet, remembering a very friendly breakfast.' },
    { by: 'b', conf: "If anybody back there is ever nice to me at breakfast again, I'm playing an idol." },
  ] },
  { id: 'ig.n9', turns: [
    { by: 'a', say: "Okay. If one of us gets back in, what's the first move?" },
    { by: 'b', say: "Apologise to nobody. Act like you never left." },
    { by: 'c', say: "No, apologise to everybody. Then they think you're harmless." },
    { by: 'a', say: "So we disagree on step one. Great plan." },
    { by: 'b', say: "We agree on step two. Never get sent here again." },
    { by: 'a', conf: "We've spent two days on a plan with one step we agree on. That's still more than my old alliance had." },
  ] },
  { id: 'ig.n10', when: { register: 'sweet' }, turns: [
    { by: 'a', say: "Can I say something? I don't think any of us played badly." },
    { by: 'c', say: "I got voted out holding a fish." },
    { by: 'a', say: "Okay, one of us played badly." },
    { by: 'b', say: "It was a really good fish, though." },
    { by: 'c', say: "Thank you. Nobody in there ever said that." },
    { by: 'c', conf: "Everybody here got voted out by people who were scared of them. That's sort of a compliment." },
  ] },
];
const T_NEWFRIENDS = [
  { id: 'ig.nf1', turns: [
    { by: 'a', say: "Wait, you like that show too?" },
    { by: 'b', say: "Like it? I've watched it four times." },
    { by: 'c', say: "Oh no. Not you two as well. I can't escape this show." },
    { by: 'a', say: "Join us. You know you want to." },
    { by: 'c', conf: "I came out here to get away from people. Now I'm in a fan club." },
  ] },
  { id: 'ig.nf2', turns: [
    { by: 'b', say: "We never talked once in the game. Not once." },
    { by: 'a', say: "You were always with your little group." },
    { by: 'c', say: "Were you two really never friends? You act like old friends." },
    { by: 'a', say: "Island friends. Different thing." },
    { by: 'b', conf: "It took getting voted out to find out {a} is actually fun." },
  ] },
  { id: 'ig.nf3', turns: [
    { beat: '{a} teaches {b} a card game played with shells. {c} keeps leaning over to cheat.' },
    { by: 'b', say: "{c}, I can see you." },
    { by: 'c', say: "You can't prove anything." },
    { by: 'a', say: "You're literally holding my shells." },
    { by: 'a', conf: "Three strangers and a pile of shells. Best afternoon I've had out here." },
  ] },
  { id: 'ig.nf4', turns: [
    { by: 'c', say: "Okay, fun facts. Go." },
    { by: 'a', say: "I can whistle with my fingers." },
    { by: 'b', say: "I've never seen snow." },
    { by: 'c', say: "Never? Not once?" },
    { by: 'b', say: "Not once." },
    { by: 'c', conf: "Out here there's no game, so you actually get to know people. Wild concept." },
  ] },
  { id: 'ig.nf5', turns: [
    { by: 'a', say: "I used to think you were stuck up, {b}." },
    { by: 'b', say: "I used to think you were loud." },
    { by: 'c', say: "You are both of those things." },
    { by: 'a', say: "Thanks, {c}." },
    { by: 'b', conf: "We were never friends in the game. Out here, we're kind of a little family." },
  ] },
  { id: 'ig.nf6', turns: [
    { by: 'b', say: "Where are you from, anyway?" },
    { by: 'a', say: "You really don't know?" },
    { by: 'c', say: "Nobody knows anything about anybody. We were too busy plotting." },
    { by: 'b', say: "Well, we've got time now." },
    { by: 'c', conf: "First real conversation I've had since the game started. And it's on an island with two people who got voted out." },
  ] },
];
const T_SIZE = [
  { id: 'ig.s1', turns: [
    { beat: "{b} walks onto the beach with {b.posAdj} torch. {a} and {c} look up from the fire." },
    { by: 'c', say: "Welcome to paradise." },
    { by: 'a', say: "Don't listen to {c}. It's not paradise." },
    { by: 'b', say: "I figured, from the smell." },
    { by: 'a', conf: "Another person between me and getting back in. I already know {b}'s weak spot." },
  ] },
  { id: 'ig.s2', turns: [
    { by: 'c', say: "So, who got you?" },
    { by: 'b', say: "Everyone, apparently." },
    { by: 'a', say: "Welcome to the club. We meet every day. By the fire. Because there's nowhere else." },
    { by: 'b', conf: "Two of them, staring at me like I'm the new kid at school. Because I am." },
  ] },
  { id: 'ig.s3', turns: [
    { by: 'a', say: "Look who it is." },
    { by: 'b', say: "Don't sound so happy about it." },
    { by: 'c', say: "We're not happy. We're competitive. It's different." },
    { by: 'b', say: "Noted." },
    { by: 'c', conf: "{b} looks strong. That's bad news for whoever's still out here when the time comes." },
  ] },
  { id: 'ig.s4', when: { register: 'sweet' }, turns: [
    { by: 'a', say: "Hi! Are you okay? Do you need water? Food? A hug?" },
    { by: 'b', say: "Maybe all three." },
    { by: 'c', say: "Don't let {a} fool you. {a} is nice, but {a} trains at five in the morning." },
    { by: 'a', say: "That's not a secret, that's a tip!" },
    { by: 'b', conf: "Everyone's nice to me. That's what worries me." },
  ] },
  { id: 'ig.s5', turns: [
    { beat: '{b} drops {b.posAdj} bag. {a} and {c} exchange a look.' },
    { by: 'c', say: "Shelter's over there. You're on the windy side." },
    { by: 'b', say: "Why am I on the windy side?" },
    { by: 'a', say: "Because you're new. Those are the rules." },
    { by: 'b', say: "Who made the rules?" },
    { by: 'a', say: "We did. Just now." },
    { by: 'b', conf: "Ten seconds on this island and I'm already at the bottom. Feels familiar." },
  ] },
  { id: 'ig.s6', turns: [
    { by: 'b', say: "So what's the deal out here?" },
    { by: 'a', say: "You train, you eat rice, you sleep, you think about the vote." },
    { by: 'c', say: "Then you do it all again." },
    { by: 'b', say: "Sounds great." },
    { by: 'c', say: "It's not." },
    { by: 'a', conf: "{b} is going to be trouble. I can tell. I can always tell." },
  ] },
];

// ── the whole island ──────────────────────────────────────────────────
const G_BREAKFAST = [
  { id: 'ig.br1', turns: [
    { beat: 'Breakfast around the fire. {a} is cooking. {b} and {c} are hungry and impatient.' },
    { by: 'b', say: "Rice again?" },
    { by: 'a', say: "Rice with fish." },
    { by: 'c', say: "Where's the fish?" },
    { by: 'a', say: "It's implied." },
    { by: 'b', say: "Thanks for cooking, I guess." },
    { by: 'a', say: "You're welcome, I guess." },
    { by: 'c', conf: "Every morning we complain about the food. Every morning we eat all of it." },
  ] },
  { id: 'ig.br2', turns: [
    { by: 'a', say: "Good fish today, {b}." },
    { by: 'c', say: "It's the same fish as yesterday. It's always the same fish." },
    { by: 'b', say: "Then catch a different one. I'll wait." },
    { by: 'c', say: "I would, but I'm on resting duty." },
    { by: 'b', say: "That's not a duty! You made that up!" },
    { by: 'a', conf: "Breakfast out here comes with a side of arguing. Free of charge." },
  ] },
  { id: 'ig.br3', turns: [
    { beat: 'Everyone sits around the fire with coconut-shell bowls.' },
    { by: 'c', say: "Who's on dishes?" },
    { by: 'a', say: "The dishes are coconuts. You throw them in the ocean." },
    { by: 'b', say: "That's littering." },
    { by: 'a', say: "That's nature. Nature made the coconut." },
    { by: 'b', conf: "We have the same argument about the dishes every morning. The dishes are coconuts." },
  ] },
  { id: 'ig.br4', turns: [
    { by: 'a', say: "Wakey wakey! Breakfast is served! It's rice." },
    { by: 'b', say: "It's always rice." },
    { by: 'c', say: "Some mornings it's rice with a surprise." },
    { by: 'b', say: "The surprise is sand." },
    { by: 'c', say: "The surprise is sand." },
    { by: 'a', conf: "I make breakfast for everybody. That's not being nice. That's being remembered." },
  ] },
  { id: 'ig.br5', turns: [
    { by: 'b', say: "Who used the last of the salt?" },
    { by: 'c', say: "We had salt?" },
    { by: 'a', say: "We had salt. It was the ocean. You can't use up the ocean, {b}." },
    { by: 'b', say: "There was a little bag of salt!" },
    { beat: 'Everyone suddenly gets very interested in their rice.' },
    { by: 'b', conf: "Somebody ate the salt. I'm going to find out who. I've got nothing but time." },
  ] },
  { id: 'ig.br6', turns: [
    { by: 'c', say: "I dreamed about pancakes." },
    { by: 'a', say: "Don't." },
    { by: 'c', say: "With syrup. And butter." },
    { by: 'b', say: "{c}, I swear, I will put you in the ocean." },
    { by: 'c', say: "And bacon." },
    { by: 'a', conf: "Talking about real food out here should be against the rules. {c} breaks that rule every morning." },
  ] },
  { id: 'ig.br7', when: { register: 'schemer' }, turns: [
    { by: 'a', say: "So, breakfast question. Who here thinks they're getting back in?" },
    { by: 'b', say: "Me." },
    { by: 'c', say: "Me." },
    { by: 'a', say: "Interesting. Very interesting." },
    { by: 'b', say: "Just eat your rice." },
    { by: 'a', conf: "Everybody out here thinks it's them. That's useful. Confident people make mistakes." },
  ] },
];
const G_STORM = [
  { id: 'ig.st1', turns: [
    { beat: 'The sky goes black. Rain comes down sideways. The shelter roof starts to lift.' },
    { by: 'a', say: "Grab the roof! Grab it!" },
    { by: 'b', say: "I'm grabbing! It's grabbing back!" },
    { by: 'c', say: "Somebody save the rice!" },
    { beat: 'They hold the roof down together until the wind dies.' },
    { by: 'c', conf: "We fight about everything out here. For ten minutes in that storm, we were a team. Then we fought about who saved the rice." },
  ] },
  { id: 'ig.st2', turns: [
    { beat: 'Thunder. The fire goes out with a hiss.' },
    { by: 'b', say: "The fire! No, no, no!" },
    { by: 'a', say: "Get the dry wood under the shelter! Move!" },
    { by: 'c', say: "Which wood is dry? It's all wet! Everything is wet!" },
    { by: 'a', conf: "Lost the fire, lost half the shelter, kept each other. I'll take it." },
  ] },
  { id: 'ig.st3', turns: [
    { beat: 'The storm hits in the middle of the night. Everyone wakes up soaked.' },
    { by: 'c', say: "Is everybody okay? Count off!" },
    { by: 'a', say: "Here!" },
    { by: 'b', say: "Here! And wet!" },
    { by: 'c', say: "We're all wet! Help me with this wall!" },
    { by: 'b', conf: "At three in the morning, in the rain, nobody cares who voted for who." },
  ] },
  { id: 'ig.st4', turns: [
    { by: 'a', say: "The roof's leaking right over my bed!" },
    { by: 'b', say: "It's leaking over everybody's bed!" },
    { by: 'a', say: "Then everybody grab a leaf! Go!" },
    { beat: 'The three of them jam palm fronds into the holes while the rain pours in.' },
    { by: 'c', conf: "Crisis averted. Mostly. My half of the shelter is a pond now." },
  ] },
  { id: 'ig.st5', turns: [
    { beat: "A wave crashes up the beach and soaks the supplies." },
    { by: 'b', say: "Our food!" },
    { by: 'c', say: "Get it up the hill! Everything up the hill!" },
    { by: 'a', say: "I've got the pot! Somebody get the rice!" },
    { beat: 'They make a chain and pass everything up the beach.' },
    { by: 'a', conf: "I didn't know we could work together that fast. Maybe we should've done that in the game." },
  ] },
  { id: 'ig.st6', when: { register: 'fiery' }, turns: [
    { by: 'a', say: "Why is it ALWAYS us?! Why does the storm always hit US?" },
    { by: 'b', say: "It's an island! Storms hit islands!" },
    { by: 'c', say: "Less yelling, more holding! Hold the pole!" },
    { by: 'a', say: "I'M HOLDING THE POLE!" },
    { by: 'b', conf: "{a} screamed at the sky for an hour. The sky screamed back. It was a tie." },
  ] },
];
const G_FIRE = [
  { id: 'ig.f1', turns: [
    { beat: "It's dark. {a}, {b} and {c} sit close to the fire, telling stories." },
    { by: 'b', say: "Worst date you've ever been on. Go." },
    { by: 'a', say: "My date brought their mom." },
    { by: 'c', say: "To the date?" },
    { by: 'a', say: "To the date. The mom ordered for both of us." },
    { by: 'c', conf: "Best part of being out here: the stories. Nobody's watching what they say anymore." },
  ] },
  { id: 'ig.f2', turns: [
    { by: 'c', say: "When I was a kid I got lost at a fair. For six hours." },
    { by: 'a', say: "Six hours? Where were you?" },
    { by: 'c', say: "Riding the carousel. Over and over. I spent all my tickets." },
    { by: 'b', say: "Were you scared?" },
    { by: 'c', say: "Not until somebody finally found me." },
    { by: 'b', conf: "I didn't expect {c} to open up like that. It's easier to like someone when you know where they come from." },
  ] },
  { id: 'ig.f3', turns: [
    { by: 'a', say: "Okay, scariest moment in the whole game. Everybody." },
    { by: 'b', say: "The vote that got me. Obviously." },
    { by: 'c', say: "The first challenge. I thought I was going to drown." },
    { by: 'a', say: "Coming out here alone the first night. Nobody to talk to." },
    { beat: 'Nobody says anything for a second.' },
    { by: 'a', conf: "I'm not alone anymore. That counts for something." },
  ] },
  { id: 'ig.f4', turns: [
    { beat: '{c} is humming by the fire. {a} and {b} start humming along, badly.' },
    { by: 'b', say: "We sound terrible." },
    { by: 'a', say: "We sound great. The crabs love us." },
    { by: 'c', say: "The crabs are leaving." },
    { by: 'b', conf: "Three voted-out people, singing off-key to some crabs. I've never felt so normal." },
  ] },
  { id: 'ig.f5', turns: [
    { by: 'b', say: "What's the first thing you're doing when you get home?" },
    { by: 'a', say: "Shower. Two showers." },
    { by: 'c', say: "Calling home. Then the shower." },
    { by: 'a', say: "Aw. Okay, calling home too. Then the shower." },
    { by: 'c', conf: "Out here, home feels really far away. Saying it out loud makes it closer." },
  ] },
  { id: 'ig.f6', when: { register: 'sweet' }, turns: [
    { by: 'a', say: "Can I say something sappy?" },
    { by: 'b', say: "No." },
    { by: 'c', say: "Yes." },
    { by: 'a', say: "When this is over, I want a reunion. Real food. Real chairs. Us." },
    { by: 'b', say: "Real chairs. Okay, I'm in." },
    { by: 'b', conf: "I hate sappy stuff. I'm going to that reunion though." },
  ] },
];
const G_CHORES = [
  { id: 'ig.ch1', turns: [
    { by: 'a', say: "I've fetched the water three days in a row." },
    { by: 'b', say: "And I've kept the fire going three nights in a row!" },
    { by: 'a', say: "The fire went out twice!" },
    { by: 'b', say: "Because of the RAIN!" },
    { by: 'c', say: "Can I suggest a chart?" },
    { by: 'a', say: "No!" },
    { by: 'b', say: "No!" },
    { by: 'c', conf: "They agreed on one thing all day: hating my chart." },
  ] },
  { id: 'ig.ch2', turns: [
    { by: 'b', say: "Who's on dishes?" },
    { by: 'a', say: "Not me. I cooked." },
    { by: 'b', say: "You boiled rice. That's not cooking." },
    { by: 'a', say: "{c}, tell {b} that boiling rice is cooking." },
    { by: 'c', say: "It's... technically cooking." },
    { by: 'b', say: "Traitor." },
    { by: 'c', conf: "I was dragged into a war about rice. I picked a side. I'm already regretting it." },
  ] },
  { id: 'ig.ch3', turns: [
    { by: 'a', say: "Pass the dishes, {b}." },
    { by: 'b', say: "Oh, now you talk to me." },
    { by: 'a', say: "I'm asking for the dishes, not a conversation." },
    { by: 'c', say: "I'll do the dishes. Just stop." },
    { by: 'a', say: "No! It's {b}'s turn!" },
    { by: 'c', conf: "I tried to help and got yelled at. Lesson learned. Never help." },
  ] },
  { id: 'ig.ch4', when: { register: 'fiery' }, turns: [
    { by: 'a', say: "Am I the only person on this island who knows how to carry wood?!" },
    { by: 'b', say: "You're the only one who makes a show of it!" },
    { by: 'a', say: "Because nobody else does it!" },
    { by: 'c', say: "I did it this morning." },
    { by: 'a', say: "Fine! Two people! Out of three!" },
    { by: 'b', conf: "{a} keeps score of every chore. Out loud. All day." },
  ] },
  { id: 'ig.ch5', turns: [
    { by: 'b', say: "You've been napping since lunch." },
    { by: 'a', say: "Resting. For the return." },
    { by: 'b', say: "Resting while I fix the shelter you sleep in." },
    { by: 'c', say: "{a} did fix the roof yesterday." },
    { by: 'b', say: "Whose side are you on?" },
    { by: 'c', say: "The roof's side." },
    { by: 'a', conf: "{c} stuck up for me. I'm not going to forget that." },
  ] },
  { id: 'ig.ch6', turns: [
    { by: 'a', say: "Somebody keeps leaving fish bones in the shelter." },
    { by: 'b', say: "Don't look at me." },
    { by: 'a', say: "They're next to your bed." },
    { by: 'b', say: "They're next to {c}'s bed too!" },
    { by: 'c', say: "Leave me out of this. I'm a vegetarian." },
    { by: 'a', say: "Since when?" },
    { by: 'c', say: "Since right now." },
    { by: 'b', conf: "Somebody's lying about fish bones. It's {c}. It's obviously {c}." },
  ] },
];
const G_COMEBACK = [
  { id: 'ig.cb1', turns: [
    { by: 'a', say: "Let's be honest. Who deserves to go back in?" },
    { by: 'b', say: "Me." },
    { by: 'a', say: "Obviously me." },
    { by: 'c', say: "Wow. I can tell this is going to be a calm conversation." },
    { by: 'b', say: "You think it should be you?" },
    { by: 'c', say: "I didn't say that. I'm thinking it." },
    { by: 'a', conf: "Everyone out here is my friend until the return. Then it's every person for themselves." },
  ] },
  { id: 'ig.cb2', turns: [
    { by: 'b', say: "Face it. You got voted out first. Your chance was gone a long time ago." },
    { by: 'a', say: "And when I win my way back in?" },
    { by: 'b', say: "Keep dreaming." },
    { by: 'c', say: "{b}, that's a bit much." },
    { by: 'b', say: "I'm not going to lie to make {a} feel better." },
    { by: 'a', conf: "{b} wants me to give up. That's the best reason I've ever had not to." },
  ] },
  { id: 'ig.cb3', when: DUEL, turns: [
    { by: 'a', say: "Only one of us leaves this island. You both know that, right?" },
    { by: 'b', say: "We know." },
    { by: 'c', say: "Do we have to talk about it at breakfast?" },
    { by: 'a', say: "When else? Duels don't schedule themselves." },
    { by: 'c', conf: "I like {a}. I'd still beat {a} in a duel without blinking." },
  ] },
  { id: 'ig.cb4', when: BACK, turns: [
    { by: 'a', say: "When the return challenge comes, no hard feelings. Whoever wins, wins." },
    { by: 'b', say: "Easy for you to say. You've been training since day one." },
    { by: 'c', say: "We've ALL been training since day one." },
    { by: 'b', say: "Not like {a}. {a} is obsessed." },
    { by: 'a', conf: "I'm not obsessed. I'm prepared. They'll see the difference at the return." },
  ] },
  { id: 'ig.cb5', turns: [
    { by: 'c', say: "If you went back in, what would you do first?" },
    { by: 'a', say: "Find whoever's on the bottom and make a deal." },
    { by: 'b', say: "Find whoever voted me out and make them sweat." },
    { by: 'c', say: "That's why it should be {a}. You'd just make enemies, {b}." },
    { by: 'b', say: "Excuse me?" },
    { by: 'b', conf: "{c} just picked a favourite. Out loud. In front of me." },
  ] },
  { id: 'ig.cb6', turns: [
    { by: 'b', say: "Real talk. Who's the biggest threat on this island?" },
    { beat: '{b} and {c} both look at {a}.' },
    { by: 'a', say: "Me? Why me?" },
    { by: 'c', say: "Because you never stop training." },
    { by: 'b', say: "And you never complain. It's creepy." },
    { by: 'a', conf: "They think I'm the threat. Good. They should." },
  ] },
];

export default {
  'isle.trio.grudge': T_GRUDGE, 'isle.trio.blowup': T_BLOWUP, 'isle.trio.comedy': T_COMEDY, 'isle.trio.late': T_LATE,
  'isle.trio.close': T_CLOSE, 'isle.trio.petty': T_PETTY, 'isle.trio.pact': T_PACT, 'isle.trio.notes': T_NOTES,
  'isle.trio.newfriends': T_NEWFRIENDS, 'isle.trio.size': T_SIZE,
  'isle.group.breakfast': G_BREAKFAST, 'isle.group.storm': G_STORM, 'isle.group.fire': G_FIRE,
  'isle.group.chores': G_CHORES, 'isle.group.comeback': G_COMEBACK,
};
