// ══════════════════════════════════════════════════════════════════════
// td/story/lines/alliance.js — alliances, as whole scenes
// ══════════════════════════════════════════════════════════════════════
//
// Long versions of the engine's own alliance moments (js/td/script/lines/
// alliance.js, recruit.js, quit.js, ends.js headers say what each kind and ending
// MEANS; these keep that meaning, the same parts and the same slots), written as
// the shows write them (docs/td-dialogue-style.md): something going on, the real
// reason from the game, pushback, a turn, a confessional.
//
// Record facts (director.js recordSlots): lastBoot / {lastBoot} (a was at the last
// vote), voted 'boot' | 'other' | 'none' (a's own ballot), myVote / {myVote} (who a
// wrote, when it was not {lastBoot}), blindside, gotVotes, and after a team challenge
// lost / won, sank / {sank}, carried / {carried}, sankA, carriedA, streak.
// Story facts: prev (the storyline's last aired step), chapter (1–3), tribal.
//
// alliance.form.*: {group} is the new alliance's name; the scene ends on it (the
// viewer shows its title card). third: {c} is a founder too; never "you and me" then.

export default {
  'long.alliance.form.pitch': [
    { id: 'la.p1', place: 'water', when: { third: false, lost: true, sank: true }, turns: [
      { beat: "After the challenge. {a} finds {b} {here}, rinsing out {b.posAdj} shoes." },
      { by: 'a', say: "Can I talk to you for a second? Before everyone starts talking to everyone." },
      { by: 'b', say: "About tonight?" },
      { by: 'a', say: "About tonight. People are going to say {sank}, because {sank} was the worst out there today." },
      { by: 'b', say: "Yeah. That's kind of what I figured too." },
      { by: 'a', say: "And that's fine. But if {sank} hears it coming, {sank} goes looking for another name, and I don't want that name to be yours. Or mine." },
      { by: 'b', say: "So what are you saying?" },
      { by: 'a', say: "I'm saying we stop figuring this out alone. You and me. We vote together tonight, and every night." },
      { by: 'b', say: "Every night is a big promise." },
      { by: 'a', say: "Tonight, then. Start with tonight, see how it feels." },
      { by: 'b', say: "...Okay. Tonight. And if it works, every night." },
      { by: 'a', say: "Deal. We should call it something. {group}." },
      { by: 'b', say: "{group}. Sure, why not." },
      { by: 'b', conf: "I'm not dumb. {a} needs a vote. But I need one too, so this works out for both of us." },
    ] },
    { id: 'la.p2', place: 'eat', when: { third: false, voted: 'other', myVote: true, lastBoot: true }, turns: [
      { beat: "Morning {here}. {a} and {b} are on breakfast duty, which means stirring a pot of something grey." },
      { by: 'a', say: "Can I ask you something weird? Who did you vote for?" },
      { by: 'b', say: "That's not weird. That's just nosy." },
      { by: 'a', say: "I wrote {myVote}. And everyone else wrote {lastBoot}. I found out at the same time {lastBoot} did." },
      { by: 'b', say: "Ouch." },
      { by: 'a', say: "Yeah. So I'm done being the last one to know things. I want one person I can count on to tell me." },
      { by: 'b', say: "And you picked me." },
      { by: 'a', say: "You don't talk behind people's backs. I've been watching. I know that's rare out here." },
      { by: 'b', say: "That's a weird compliment, but okay. What do I get?" },
      { by: 'a', say: "Same thing. Somebody who tells you. Before the vote, not after." },
      { by: 'b', say: "...Fine. But if you lie to me even once, it's over." },
      { by: 'a', say: "Fair. So we're a thing. {group}." },
      { by: 'b', say: "We're a thing. Now stir. It's burning." },
      { by: 'a', conf: "Last time I was on the outside of the vote. This time I've got somebody on the inside with me." },
    ] },
    { id: 'la.p3', place: 'fire', when: { third: false, register: 'schemer' }, turns: [
      { beat: "{a} sits down next to {b} {here}. {b} is trying to get a fire going with wet wood." },
      { by: 'a', say: "Here, let me. You're smothering it." },
      { by: 'b', say: "Wow, thanks." },
      { by: 'a', say: "Can I be honest with you? You're the only person on this team I actually respect." },
      { by: 'b', say: "That's a lot of honesty for nine in the morning." },
      { by: 'a', say: "I mean it. Everybody else is either loud or useless. You actually think about stuff." },
      { by: 'b', say: "And?" },
      { by: 'a', say: "And people who think about stuff should stick together. Before the loud ones decide everything." },
      { by: 'b', say: "You want an alliance." },
      { by: 'a', say: "I want a partner. Alliance sounds so dramatic." },
      { by: 'b', say: "You literally just called everyone useless." },
      { by: 'a', say: "Okay, fine. An alliance. {group}. Yes or no?" },
      { beat: "The fire catches. {b} watches it for a second." },
      { by: 'b', say: "Yes. But I'm watching you." },
      { by: 'a', say: "I'd be disappointed if you weren't." },
      { by: 'a', conf: "Flattery, a little honesty, and help with a fire. People will join anything if they feel smart doing it." },
      { by: 'b', conf: "{a} is using me. That's fine. I'm using {a} right back." },
    ] },
    { id: 'la.p4', place: 'aside', when: { third: false, register: ['sweet', 'shy'], aOther: false }, turns: [
      { beat: "{a} has been working up to this all morning. {b} is reading {here}." },
      { by: 'a', say: "Um. Hi. Can I sit?" },
      { by: 'b', say: "It's a log. Go for it." },
      { by: 'a', say: "So, I've never done this before, so if it's stupid you can tell me." },
      { by: 'b', say: "Done what?" },
      { by: 'a', say: "Asked somebody to be in an alliance with me." },
      { by: 'b', say: "Oh. Okay. Why me?" },
      { by: 'a', say: "Because you're nice to me, and not in the fake way. Everybody else is nice in the fake way." },
      { by: 'b', say: "That's... honestly a really good reason." },
      { by: 'a', say: "So is that a yes?" },
      { by: 'b', say: "What would we even call it?" },
      { by: 'a', say: "I already thought of a name. Is that weird? It's {group}." },
      { by: 'b', say: "It's a little weird. But yeah. {group}. I'm in." },
      { by: 'a', conf: "I did it! I have an alliance! I didn't throw up or anything!" },
      { by: 'b', conf: "{a} is sweet. People are going to underestimate {a.obj}. Good. They can underestimate both of us." },
    ] },
    { id: 'la.p5', place: 'public', when: { third: false, register: 'fiery' }, turns: [
      { by: 'a', say: "Hey. You. Come here." },
      { by: 'b', say: "Wow. Hi to you too." },
      { by: 'a', say: "I'm sick of the whispering. Everybody out here is whispering. So I'm just gonna say it. You and me. Alliance. Yes or no." },
      { by: 'b', say: "That's the least sneaky alliance pitch I've ever heard." },
      { by: 'a', say: "Good. Sneaky people are the problem." },
      { by: 'b', say: "And why would I want to be in an alliance with the loudest person on the island?" },
      { by: 'a', say: "Because I'll never lie to you. If I'm mad at you, you'll know. Can you say that about anyone else here?" },
      { by: 'b', say: "...No. I really can't." },
      { by: 'a', say: "So?" },
      { by: 'b', say: "So fine. But we're not calling it anything stupid." },
      { by: 'a', say: "{group}." },
      { by: 'b', say: "That's stupid." },
      { by: 'a', say: "Too late. It's done." },
      { by: 'b', conf: "{a} has no filter, which is terrifying. But it also means I'll always know where I stand. That's worth something out here." },
    ] },
    { id: 'la.p6', place: 'secret', when: { third: false, register: ['cool', 'competitor', 'plain'] }, turns: [
      { beat: "{a} and {b} are {here}, a little way out from everybody else." },
      { by: 'a', say: "So I've been counting." },
      { by: 'b', say: "Counting what?" },
      { by: 'a', say: "People. Who sits with who, who goes off together. There are already pairs out here." },
      { by: 'b', say: "And you want to be one." },
      { by: 'a', say: "I want to not be the one left over when everybody's paired up." },
      { by: 'b', say: "That's not a very romantic pitch." },
      { by: 'a', say: "It's not a romantic thing. It's math." },
      { by: 'b', say: "Okay. Math. What do I get out of it?" },
      { by: 'a', say: "My vote, whenever you need it. And you tell me what you hear." },
      { by: 'b', say: "And if I hear something about you?" },
      { by: 'a', say: "Then especially then." },
      { by: 'b', say: "...Fine. Deal. Do we need a name?" },
      { by: 'a', say: "Everyone else has one. {group}." },
      { by: 'b', say: "{group}. Okay. Come on, they'll wonder where we went." },
      { by: 'a', conf: "It's early. But early is when you get to choose. Later, people choose for you." },
    ] },
    { id: 'la.p7', place: 'aside', when: { third: false, merged: true }, turns: [
      { by: 'a', say: "Everyone's acting like the old teams still matter. They don't." },
      { by: 'b', say: "Says somebody who doesn't have one anymore." },
      { by: 'a', say: "Says somebody who can count. There are a lot more of them than there are of my old team. Or yours." },
      { by: 'b', say: "So you want to cross over." },
      { by: 'a', say: "I want to be the two people nobody saw coming. Everybody's watching the big groups. Nobody's watching us." },
      { by: 'b', say: "Until they do." },
      { by: 'a', say: "By then it's too late for them." },
      { by: 'b', say: "And if my old team finds out?" },
      { by: 'a', say: "Then you tell them we're just friends. People believe that about me. Trust me." },
      { by: 'b', say: "...Okay. What's it called?" },
      { by: 'a', say: "{group}." },
      { by: 'b', conf: "My old team thinks I'm theirs. That's useful. {a} thinks I'm {a.posAdj}. That's useful too." },
    ] },
    { id: 'la.p8', place: 'secret', when: { third: true, members: 3 }, turns: [
      { beat: "{a} rounds up {b}, then {c}, and leads them out to {place}, where nobody can see." },
      { by: 'c', say: "If this is a prank, I'm leaving." },
      { by: 'a', say: "It's not a prank. Sit down, both of you." },
      { by: 'b', say: "Okay, this is weird. Why us?" },
      { by: 'a', say: "Because you two are the only ones I haven't caught talking about me." },
      { by: 'c', say: "That you know of." },
      { by: 'a', say: "That I know of. Which is the best anyone gets out here." },
      { by: 'b', say: "So what's the pitch?" },
      { by: 'a', say: "Three votes. Same name every time. Nobody outside us knows it until it's read." },
      { by: 'c', say: "And who decides the name?" },
      { by: 'a', say: "We do. Together. Majority wins." },
      { by: 'c', say: "Majority of three. So two of us can always vote out the third." },
      { by: 'a', say: "Then don't be the third." },
      { by: 'b', say: "Wow. Inspiring." },
      { by: 'c', say: "...Fine. I'm in. But I want that on record." },
      { by: 'a', say: "On record. {group}." },
      { by: 'b', say: "{group}. Okay." },
      { by: 'c', conf: "Three people. Somebody's going to be the odd one out eventually. I just have to make sure it's not me." },
    ] },
    { id: 'la.p9', place: 'public', when: { third: true, members: 3, lost: true }, turns: [
      { beat: "The losing team scatters back at camp. {a} grabs {b} and {c} before they can scatter with them." },
      { by: 'a', say: "Don't go anywhere. We need to talk before tonight." },
      { by: 'b', say: "About who's going home?" },
      { by: 'a', say: "About who's NOT going home. Us three." },
      { by: 'c', say: "We don't even get along that well." },
      { by: 'a', say: "We don't have to. We just have to write the same name down." },
      { by: 'c', say: "And whose name is that?" },
      { by: 'a', say: "We decide that together. But first we decide it's us three, every time." },
      { by: 'b', say: "And after tonight?" },
      { by: 'a', say: "After tonight, we're still three. And everybody else is one at a time." },
      { by: 'b', say: "...Okay. That's actually smart." },
      { by: 'c', say: "Fine. What do we call it?" },
      { by: 'a', say: "{group}." },
      { by: 'c', say: "Sure." },
      { by: 'b', conf: "We lost the challenge and somehow I walked away with two allies. Best bad day I've had out here." },
    ] },
    { id: 'la.p10', place: 'wash', when: { third: true, members: 3, register: ['sweet', 'shy', 'plain'] }, turns: [
      { beat: "{a}, {b} and {c} are washing up {here}. {a} keeps glancing at the other two." },
      { by: 'b', say: "What? You keep looking at us." },
      { by: 'a', say: "Can I say something? You guys are the only ones I actually like here." },
      { by: 'c', say: "Aw. That's sweet." },
      { by: 'a', say: "No, I mean it. And I keep thinking, what happens when they start voting people like us out?" },
      { by: 'b', say: "People like us?" },
      { by: 'a', say: "Nice people. The ones who don't plot." },
      { by: 'c', say: "So you're saying we should... plot?" },
      { by: 'a', say: "A little? Just together? Nicely?" },
      { by: 'b', say: "A nice alliance." },
      { by: 'a', say: "A nice alliance! We look out for each other and we vote together. That's all." },
      { by: 'c', say: "I mean... yeah. I'd rather be in a nice one than a mean one." },
      { by: 'a', say: "It's called {group}. I've been thinking about it all day." },
      { by: 'b', conf: "We are the three least threatening people on this island, and now we're an alliance. Honestly? That might be the plan." },
    ] },
  ],

  'long.alliance.form.couple': [
    { id: 'la.c1', place: 'aside', when: { third: false }, turns: [
      { beat: "Late. {a} and {b} are sitting up after everyone else has gone to bed, like most nights." },
      { by: 'b', say: "You know everybody thinks we're working together, right?" },
      { by: 'a', say: "We've been glued together since day one. Of course they do." },
      { by: 'b', say: "So, should we be? Actually?" },
      { by: 'a', say: "You mean make it official." },
      { by: 'b', say: "If they're going to vote us out for it anyway, we might as well get the benefits." },
      { by: 'a', say: "That's either really smart or really lazy." },
      { by: 'b', say: "Why can't it be both?" },
      { by: 'a', say: "Fine. Both. But then we do it properly. Everything we hear, we tell each other. Even the stuff that's about us." },
      { by: 'b', say: "Especially that stuff." },
      { by: 'a', say: "{group}." },
      { by: 'b', say: "That's the worst name I've ever heard. I love it." },
      { by: 'a', conf: "I didn't plan on having a partner this early. I also didn't plan on liking {b} this much." },
    ] },
    { id: 'la.c2', place: 'aside', when: { third: false, early: false }, turns: [
      { by: 'a', say: "Can I say something without you making it weird?" },
      { by: 'b', say: "No promises." },
      { by: 'a', say: "Every vote so far, I've thought about how to keep you safe before I thought about myself." },
      { by: 'b', say: "...Okay, that's a little weird." },
      { by: 'a', say: "See? This is why I don't say things." },
      { by: 'b', say: "No, it's good weird. I do the same thing. I just didn't want to say it first." },
      { by: 'a', say: "So let's stop pretending it's an accident. We're a team inside the team." },
      { by: 'b', say: "{group}." },
      { by: 'a', say: "You had a name ready?" },
      { by: 'b', say: "I've had it for days. I was waiting for you." },
      { by: 'b', conf: "Everyone out here needs one person they'd go to the wall for. {a}'s mine. It's nice to finally say it out loud." },
    ] },
    { id: 'la.c3', place: 'aside', when: { third: true, members: 3 }, turns: [
      { beat: "{a}, {b} and {c} are lying around {here} after chores, the way they do every afternoon." },
      { by: 'c', say: "Real question. If one of us went home tonight, what would the other two do?" },
      { by: 'a', say: "Cry. Then get revenge." },
      { by: 'b', say: "In that order?" },
      { by: 'a', say: "Depends who did it." },
      { by: 'c', say: "I'm serious. We spend all our time together. Everybody knows that." },
      { by: 'b', say: "So we're already a target. As a group." },
      { by: 'c', say: "So maybe we should be a group. Like, on purpose. Votes and everything." },
      { by: 'a', say: "Are you asking us to be in an alliance? Right now? Lying here?" },
      { by: 'c', say: "I'm asking you to be in an alliance right now, lying here, yes." },
      { by: 'a', say: "Okay. {group}. That's what we're called." },
      { by: 'b', say: "Fine by me." },
      { by: 'c', conf: "I trust {a} and {b} more than anyone here. Which is exactly why we need to make it official before somebody splits us up." },
    ] },
  ],

  'long.alliance.form.enemy': [
    { id: 'la.e1', place: 'eat', when: { third: false }, turns: [
      { beat: "{a} and {b} are scrubbing pots {here}, not very hard. Somewhere behind them, {target} is laughing too loud at something." },
      { by: 'a', say: "Listen to that." },
      { by: 'b', say: "I've been listening to it all week." },
      { by: 'a', say: "I can't stand {target}. I'm just going to say it." },
      { by: 'b', say: "Oh, thank god. I thought it was just me." },
      { by: 'a', say: "It's not just you. It's you and me, and probably more people who are too scared to say it." },
      { by: 'b', say: "So what do we do, stand here and hate {target.obj} quietly?" },
      { by: 'a', say: "We stop hating {target.obj} quietly and start voting {target.obj} out loudly." },
      { by: 'b', say: "Two votes isn't enough." },
      { by: 'a', say: "Two votes is a start. Two votes that always go the same way? People notice that. People join that." },
      { by: 'b', say: "...Okay. I'm in." },
      { by: 'a', say: "{group}. And {target} is the first thing on the list." },
      { by: 'b', conf: "Do I want to be in an alliance with {a}? I don't know. Do I want {target} gone? Yes. That's enough for now." },
    ] },
    { id: 'la.e2', place: 'aside', when: { third: false, register: ['schemer', 'cool'] }, turns: [
      { by: 'a', say: "You and {target} don't get along." },
      { by: 'b', say: "Is it that obvious?" },
      { by: 'a', say: "You leave every time {target} sits down. Yeah. It's obvious." },
      { by: 'b', say: "And you care because...?" },
      { by: 'a', say: "Because {target}'s been working on me too. And I'd rather {target} not get comfortable." },
      { by: 'b', say: "So you want to take {target} out." },
      { by: 'a', say: "Eventually. Not tonight, not loudly. But eventually, and together." },
      { by: 'b', say: "Why not tonight?" },
      { by: 'a', say: "Because if we go too early, {target} finds out and comes after us first. Patience." },
      { by: 'b', say: "I don't really do patience." },
      { by: 'a', say: "Then let me do it for both of us. {group}. Deal?" },
      { by: 'b', say: "Deal." },
      { by: 'a', conf: "{b} hates {target}. I need {target} gone. I don't need {b} to like me. I just need {b} to vote." },
    ] },
    { id: 'la.e3', place: 'fire', when: { third: true, members: 3 }, turns: [
      { beat: "{a}, {b} and {c} end up at the fire together after {target} storms off to bed." },
      { by: 'c', say: "Is it just me, or did it get really peaceful in here?" },
      { by: 'b', say: "It's not just you." },
      { by: 'a', say: "Can we stop pretending for one second? None of us like {target}." },
      { by: 'b', say: "I didn't say that." },
      { by: 'a', say: "You didn't have to. You rolled your eyes so hard I heard it." },
      { by: 'c', say: "Okay, fine. {target} is a lot." },
      { by: 'a', say: "So let's do something about it. Three votes. {target} goes the first night we're at a vote and the numbers are there." },
      { by: 'b', say: "And after that?" },
      { by: 'a', say: "After that, we're three people who already know they can work together." },
      { by: 'c', say: "I'm in. Honestly I've been waiting for somebody to say it." },
      { by: 'a', say: "{group}." },
      { by: 'b', conf: "Three people who hate the same person. That's not an alliance, that's a club. But clubs vote, so." },
    ] },
  ],

  'long.alliance.form.survival': [
    { id: 'la.s1', place: 'aside', when: { third: false }, turns: [
      { beat: "Everyone else is together. {a} and {b} are sitting {here}, a long way from them." },
      { by: 'a', say: "Have you noticed nobody tells us anything?" },
      { by: 'b', say: "I noticed. I thought it was just me." },
      { by: 'a', say: "It's both of us. They go quiet when we walk up. Every time." },
      { by: 'b', say: "So we're next." },
      { by: 'a', say: "One of us is. Unless we stop being alone about it." },
      { by: 'b', say: "Two people on the bottom is still two people on the bottom." },
      { by: 'a', say: "Two people is a swing vote. They need us to break a tie, they come to us. One person on the bottom is just a name." },
      { by: 'b', say: "...Okay. That's actually a good point." },
      { by: 'a', say: "So we stick together. We listen. And we wait for them to need us." },
      { by: 'b', say: "And then?" },
      { by: 'a', say: "And then we make them pay for it. {group}. You and me." },
      { by: 'b', conf: "I came in here thinking I'd be running things. Instead I'm in an alliance called {group} with the only other person nobody talks to. Okay. It's a start." },
    ] },
    { id: 'la.s2', place: 'aside', when: { third: false, gotVotes: true }, turns: [
      { by: 'b', say: "My name came up last night." },
      { by: 'a', say: "I know. Mine did too." },
      { by: 'b', say: "Seriously? I didn't know that." },
      { by: 'a', say: "Nobody told you because nobody tells us anything. That's the whole problem." },
      { by: 'b', say: "So what now? Wait for them to finish the job?" },
      { by: 'a', say: "No. Now we find out who wrote it, and we make sure they need us before they try again." },
      { by: 'b', say: "How?" },
      { by: 'a', say: "We stop being two separate easy votes and start being one swing vote. Two votes, always together." },
      { by: 'b', say: "Okay. I'm in. I don't really have a choice, do I?" },
      { by: 'a', say: "Nope. Neither do I. {group}." },
      { by: 'a', conf: "When your name gets written down, you get two options. Panic, or get organised. I'm getting organised." },
    ] },
    { id: 'la.s3', place: 'aside', when: { third: true, members: 3 }, turns: [
      { beat: "{a} finds {b} and {c} {here}, about as far from the others as it's possible to get." },
      { by: 'a', say: "Let me guess. You two ended up out here because nobody wanted you around for the strategy talk." },
      { by: 'c', say: "Rude. But yeah." },
      { by: 'a', say: "Me too. They're all in a circle back there, and none of us are in it." },
      { by: 'b', say: "So we start our own circle?" },
      { by: 'a', say: "Three people is a circle. Three people at the bottom is enough to flip a vote." },
      { by: 'c', say: "If they're split." },
      { by: 'a', say: "They're always split. Everybody's paranoid. We just have to be there when they crack." },
      { by: 'b', say: "I like it. What's it called?" },
      { by: 'a', say: "{group}." },
      { by: 'c', say: "The bottom-of-the-barrel alliance." },
      { by: 'a', say: "Call it what you want. Just vote with it." },
      { by: 'c', conf: "Everybody counts us as three easy votes. Now we're three votes that come as a set. Good luck with that." },
    ] },
  ],

  'long.alliance.form.struggle': [
    { id: 'la.t1', place: 'aside', when: { third: false }, turns: [
      { by: 'a', say: "Last night was way too close." },
      { by: 'b', say: "For you too?" },
      { by: 'a', say: "My name came up. I don't know how many times. Enough." },
      { by: 'b', say: "Mine too. I thought I was going home. I had my bag packed in my head." },
      { by: 'a', say: "So we're the two people they almost got." },
      { by: 'b', say: "Which means we're the two people they try again on." },
      { by: 'a', say: "Unless we make it harder. Two votes nobody can count on except each other." },
      { by: 'b', say: "That only works if we never flip on each other." },
      { by: 'a', say: "I'm not going to flip on the only other person who knows how last night felt." },
      { by: 'b', say: "...Okay. Me neither." },
      { by: 'a', say: "{group}. Survivors' club." },
      { by: 'b', conf: "{a} and I both almost went home. That's not friendship. But it's close enough to trust, for now." },
    ] },
  ],

  'long.recruit.join.any': [
    { id: 'lr.j1', place: 'aside', turns: [
      { beat: "{a} catches {b} alone {here}." },
      { by: 'a', say: "Got a minute?" },
      { by: 'b', say: "Depends who's asking. You or your alliance?" },
      { by: 'a', say: "Both, honestly. {group} wants you in." },
      { by: 'b', say: "Why? So I can be the extra vote you throw away when you need to?" },
      { by: 'a', say: "So you can be the vote that decides things. We're close. With you, we're not close, we're there." },
      { by: 'b', say: "And who's going home first?" },
      { by: 'a', say: "Not you. That's the point of joining." },
      { by: 'b', say: "That's not an answer." },
      { by: 'a', say: "It's the only one I can give you until you're in." },
      { by: 'b', say: "...Fine. I'm in. But if I find out you were going to vote me out before this, I'm telling everyone." },
      { by: 'a', say: "Fair. Welcome to {group}." },
      { by: 'b', conf: "Everybody wants the swing vote until the swing vote's the only one left. I'm going to enjoy this while it lasts." },
    ] },
    { id: 'lr.j2', place: 'aside', when: { lastBoot: true }, turns: [
      { by: 'a', say: "You saw what happened to {lastBoot}." },
      { by: 'b', say: "Everybody saw what happened to {lastBoot}." },
      { by: 'a', say: "{lastBoot} was on {lastBoot.posAdj} own. That's what happens to people on their own out here." },
      { by: 'b', say: "Is that a threat?" },
      { by: 'a', say: "It's an offer. {group} could use you. And you could use some people." },
      { by: 'b', say: "And if I say no?" },
      { by: 'a', say: "Then you're on your own. And you saw what happened to {lastBoot}." },
      { by: 'b', say: "So it's a threat that's dressed up like an offer." },
      { by: 'a', say: "It's both. Take it or don't." },
      { by: 'b', say: "...I'll take it." },
      { by: 'b', conf: "I don't like being pushed into things. But I also don't want to be the next {lastBoot}." },
    ] },
    { id: 'lr.j3', place: 'aside', when: { register: ['sweet', 'shy'], bOther: false }, turns: [
      { by: 'a', say: "Hey. So, me and some people have a group. A voting group. And we really like you." },
      { by: 'b', say: "Oh! Me?" },
      { by: 'a', say: "You! You're always helping with the chores and you never complain. That matters." },
      { by: 'b', say: "That's really nice. Who else is in it?" },
      { by: 'a', say: "I can tell you once you're in. That's sort of the rule." },
      { by: 'b', say: "That's kind of scary." },
      { by: 'a', say: "It's less scary than being outside of it, I promise." },
      { by: 'b', say: "Okay. Okay, yes. I want to be in it." },
      { by: 'a', say: "Yay! Welcome to {group}." },
      { by: 'b', conf: "I've never been asked to be in anything before. Even if it's a strategy thing, it still feels nice." },
    ] },
    { id: 'lr.j4', place: 'aside', when: { register: 'schemer' }, turns: [
      { beat: "{a} hands {b} the good half of a coconut and keeps the bad half." },
      { by: 'b', say: "What's this for?" },
      { by: 'a', say: "Good faith. I'm about to ask you for something." },
      { by: 'b', say: "I knew there was a catch." },
      { by: 'a', say: "There's always a catch. At least I'm telling you up front. {group}. We want a fourth." },
      { by: 'b', say: "Why me and not somebody else?" },
      { by: 'a', say: "Because you don't owe anybody here anything yet. That makes you the most valuable person in camp." },
      { by: 'b', say: "That's flattering." },
      { by: 'a', say: "It's true. And it stops being true the second you pick a side. So pick the right one." },
      { by: 'b', say: "...Fine. Yours." },
      { by: 'a', conf: "One coconut. That's what a vote costs out here." },
    ] },
  ],

  'long.recruit.refuse.any': [
    { id: 'lr.r1', place: 'aside', turns: [
      { by: 'a', say: "So. {group} has a spot open. For you." },
      { by: 'b', say: "That's really nice, but no." },
      { by: 'a', say: "You didn't even think about it." },
      { by: 'b', say: "I thought about it while you were walking over. You've been looking at me all morning." },
      { by: 'a', say: "Okay, but think about it now. You're on your own out here." },
      { by: 'b', say: "I'd rather be on my own than be somebody's spare vote." },
      { by: 'a', say: "Nobody said spare." },
      { by: 'b', say: "Nobody ever says it. That's how you know." },
      { by: 'a', say: "Fine. Your loss." },
      { by: 'a', conf: "{b} said no. That's fine. People who say no to you make really easy names to write down." },
      { by: 'b', conf: "Joining {group} means voting how they tell me. I didn't come here to take orders." },
    ] },
    { id: 'lr.r2', place: 'public', when: { band: ['enemies', 'cold'] }, turns: [
      { by: 'a', say: "Look, I know we're not exactly friends, but—" },
      { by: 'b', say: "We're not friends at all." },
      { by: 'a', say: "Okay. But {group} needs another vote, and you need people. So." },
      { by: 'b', say: "So you want me to join an alliance with you. You." },
      { by: 'a', say: "It's not about me." },
      { by: 'b', say: "It's always about you. That's literally your whole thing." },
      { by: 'a', say: "Wow. Okay, forget it." },
      { by: 'b', say: "Already forgotten." },
      { by: 'b', conf: "{a} asking me to join {a.posAdj} alliance is like a shark asking a fish to swim with it." },
    ] },
  ],

  'long.alliance.crack.any': [
    { id: 'lc.1', place: 'water', turns: [
      { beat: "{a} and {b} are supposed to be fishing {here}. The line's been in the water for ten minutes and neither of them has looked at it." },
      { by: 'a', say: "Where were you last night? After dinner?" },
      { by: 'b', say: "Walking. Why?" },
      { by: 'a', say: "Walking. With who?" },
      { by: 'b', say: "Is this an interrogation?" },
      { by: 'a', say: "It's a question. We're supposed to be {group}. That means I'm allowed to ask questions." },
      { by: 'b', say: "And it means you're supposed to trust me." },
      { by: 'a', say: "I do. I just want to keep doing it." },
      { by: 'b', say: "Then stop following me around camp." },
      { beat: "The line twitches. Neither of them moves." },
      { by: 'a', conf: "{b} didn't answer the question. People who have nothing to hide answer the question." },
      { by: 'b', conf: "Every alliance gets one paranoid person. Great. Ours is {a}." },
    ] },
    { id: 'lc.2', place: 'secret', when: { lastBoot: true, votedB: 'boot' }, turns: [
      { by: 'a', say: "Can I ask you something about the vote?" },
      { by: 'b', say: "Go ahead." },
      { by: 'a', say: "Did you write {lastBoot}?" },
      { by: 'b', say: "What kind of question is that? Yes. We all did." },
      { by: 'a', say: "Okay. Because somebody in {group} has been talking to the other side, and I'm trying to work out who." },
      { by: 'b', say: "And you thought it was me." },
      { by: 'a', say: "I thought I'd ask everyone. You're just first." },
      { by: 'b', say: "That's great. Really great for team morale." },
      { by: 'a', say: "Morale doesn't vote. People do." },
      { by: 'b', conf: "We're in an alliance and {a} is checking my homework. That's not an alliance. That's a probation." },
      { by: 'a', conf: "Maybe it's not {b}. But somebody is, and I'm not going to wait for the votes to tell me who." },
    ] },
    { id: 'lc.3', place: 'public', when: { register: 'fiery' }, turns: [
      { by: 'a', say: "I saw you. With them. At the water." },
      { by: 'b', say: "So? I'm allowed to talk to people." },
      { by: 'a', say: "You were whispering. People don't whisper about the weather." },
      { by: 'b', say: "Maybe I was whispering about you, if you keep acting like this." },
      { by: 'a', say: "Oh, real nice. Real loyal." },
      { by: 'b', say: "You don't get to talk to me about loyal when you're spying on me!" },
      { by: 'a', say: "It's not spying if you do it in the middle of camp!" },
      { beat: "A few people look over. {b} lowers {b.posAdj} voice." },
      { by: 'b', say: "Keep it down. You want the whole camp to know {group} is falling apart?" },
      { by: 'a', say: "Is it?" },
      { by: 'b', say: "It is now." },
      { by: 'a', conf: "I don't do quiet suspicions. If I think you're playing me, you'll hear about it. Probably everyone will." },
    ] },
    { id: 'lc.4', place: 'aside', when: { register: ['sweet', 'shy'] }, turns: [
      { by: 'a', say: "Can I ask you something? You can say no." },
      { by: 'b', say: "Sure. What's up?" },
      { by: 'a', say: "Are we still okay? You and me and {group}?" },
      { by: 'b', say: "Of course. Why wouldn't we be?" },
      { by: 'a', say: "You've been different with me. Quieter. Like you stopped telling me stuff." },
      { by: 'b', say: "I've just been busy." },
      { by: 'a', say: "Busy with who?" },
      { by: 'b', say: "...With the game. Everyone's busy with the game." },
      { by: 'a', say: "Okay. Sorry. I'm probably being silly." },
      { by: 'a', conf: "I said I was being silly because I didn't want to fight. I don't think I'm being silly." },
      { by: 'b', conf: "{a} is noticing things. I need to either fix this or get ahead of it." },
    ] },
    { id: 'lc.5', place: 'secret', when: { third: true }, turns: [
      { beat: "{group} is supposed to be having a meeting. {c} is late." },
      { by: 'a', say: "Where's {c}?" },
      { by: 'b', say: "{c.Sub} said {c.sub}'d be here." },
      { by: 'a', say: "{c.Sub} said that an hour ago." },
      { beat: "{c} walks up, out of breath." },
      { by: 'c', say: "Sorry, sorry. Got held up." },
      { by: 'a', say: "By who?" },
      { by: 'c', say: "Does it matter?" },
      { by: 'a', say: "It does when we're supposed to be voting together tonight." },
      { by: 'c', say: "I'm here now, aren't I? What's the plan?" },
      { by: 'a', say: "...You know what, let's do it later." },
      { by: 'a', conf: "I'm not telling {c} the plan until I know who {c} was with. I'm not that stupid." },
      { by: 'c', conf: "{a} looked at me like I was already gone. Okay. Message received." },
    ] },
  ],

  'long.alliance.quit.betrayed': [
    { id: 'lq.b1', place: 'confessional', turns: [
      { beat: "{a}, alone." },
      { by: 'a', conf: "Somebody in {group} wrote my name down. My own alliance." },
      { by: 'a', conf: "So I'm out. I'm not going to be the last person to find out again. If they want to vote me out, they can do it without me helping them." },
    ] },
    { id: 'lq.b2', place: 'confessional', when: { register: 'fiery' }, turns: [
      { by: 'a', conf: "You know what? Forget {group}. Forget all of them. They wanted my name on a piece of paper? I'll give them a whole lot more than a name to worry about." },
      { by: 'a', conf: "I'm done being nice. Nice got me a knife in the back." },
    ] },
    { id: 'lq.b3', place: 'confessional', when: { register: ['schemer', 'cool'] }, turns: [
      { by: 'a', conf: "{group} voted against me. Not all of them, but enough. They think I don't know. That's their first mistake." },
      { by: 'a', conf: "I'm not quitting out loud. I'm just not in it anymore. They'll find out when it's too late to do anything about it." },
    ] },
  ],
  'long.alliance.quit.pivot': [
    { id: 'lq.p1', place: 'confessional', turns: [
      { by: 'a', conf: "{group} was good for me. Was. The numbers moved and they didn't notice. I noticed." },
      { by: 'a', conf: "I'm not going down with a ship because I liked the people on it. I'm getting off while there's still a boat to get onto." },
    ] },
    { id: 'lq.p2', place: 'confessional', when: { register: ['sweet', 'shy'] }, turns: [
      { by: 'a', conf: "I feel really bad about this. I do. But {group} is on the wrong side now, and I don't want to go home just to be loyal to a group that can't save me." },
      { by: 'a', conf: "I hope they understand. I don't think they will." },
    ] },
  ],
  'long.alliance.quit.solo': [
    { id: 'lq.s1', place: 'confessional', turns: [
      { by: 'a', conf: "I've been carrying {group} around like a backpack full of rocks. Today I'm putting it down." },
      { by: 'a', conf: "From now on it's just me. No meetings, no promises I can't keep. Just me and whoever's useful that day." },
    ] },
  ],
  'long.alliance.quit.breakdown': [
    { id: 'lq.d1', place: 'confessional', turns: [
      { by: 'a', conf: "We can't be in the same room without fighting. {group} isn't an alliance anymore. It's a group of people who used to like each other." },
      { by: 'a', conf: "I'd rather vote with somebody I'm not friends with than keep pretending with people I can't stand." },
    ] },
  ],
};
