// ══════════════════════════════════════════════════════════════════════
// td/story/lines/chal2.js — more of the camp after a team challenge
// ══════════════════════════════════════════════════════════════════════
//
// Same parts as chal.js. won: a = {carried}, b = a's closest teammate,
// c = {sank} when not a or b. lost: a goes after b = {sank}; c = b's closest.

export default {
  'story.chal.won': [
    { id: 'ch2.w1', place: 'public', turns: [
      { beat: "The {tribe} come back {here}, still buzzing." },
      { by: 'b', say: "Okay, I need everyone to know that {a} was unreal out there." },
      { by: 'a', say: "Stop." },
      { by: 'b', say: "No! You were unreal! I was watching you and I forgot I was supposed to be doing stuff." },
      { by: 'a', say: "Yeah, I noticed that part." },
      { by: 'b', say: "Hey! We won!" },
      { by: 'a', say: "We won. Go have a nap. You earned it. Kind of." },
      { by: 'a', conf: "It's nice when people say nice things. It's also a little scary. Today they're grateful. One day they'll remember I'm the one who keeps winning." },
    ] },
    { id: 'ch2.w2', place: 'public', when: { register: 'fiery' }, turns: [
      { by: 'a', say: "Did you see that? DID YOU SEE THAT?" },
      { by: 'b', say: "Everybody saw it. You were screaming the whole time." },
      { by: 'a', say: "Because I was winning the whole time!" },
      { by: 'b', say: "Fair." },
      { by: 'a', say: "Tell the other team I said hi. Actually, don't. I'll tell them myself." },
      { by: 'b', say: "Please don't." },
      { by: 'a', conf: "I don't do humble. I won. I'm going to enjoy it, loudly, for as long as I want." },
    ] },
    { id: 'ch2.w3', place: 'aside', when: { register: ['sweet', 'shy'] }, turns: [
      { by: 'b', say: "Why are you hiding over here? You won us the whole thing." },
      { by: 'a', say: "Everyone keeps clapping me on the back. My back hurts." },
      { by: 'b', say: "That's what happens when you're the hero." },
      { by: 'a', say: "I don't want to be the hero. I just didn't want us to lose." },
      { by: 'b', say: "That's literally what being the hero is." },
      { by: 'a', say: "Oh. Huh." },
      { by: 'a', conf: "I've never won anything in my life. Like, nothing. I'm going to be thinking about today for a really long time." },
    ] },
    { id: 'ch2.w4', place: 'public', when: { register: ['schemer', 'cool'] }, turns: [
      { by: 'b', say: "That was a big win. You okay? You look like you're thinking about something." },
      { by: 'a', say: "I'm thinking about the other team." },
      { by: 'b', say: "Feeling sorry for them?" },
      { by: 'a', say: "No. I'm thinking about who they're about to vote out, and whether it helps us or hurts us." },
      { by: 'b', say: "We just won and you're already doing their strategy for them." },
      { by: 'a', say: "Somebody has to." },
      { by: 'a', conf: "Immunity tonight is nice. What's nicer is the other team losing a strong player. Fingers crossed they're stupid about it." },
    ] },
    { id: 'ch2.w5', place: 'public', when: { register: ['competitor', 'plain'] }, turns: [
      { beat: "The {tribe} get back {here}. {a} goes straight to the water bucket." },
      { by: 'b', say: "Hey. Good work out there." },
      { by: 'a', say: "Thanks. You too." },
      { by: 'b', say: "I didn't do much." },
      { by: 'a', say: "You didn't mess it up. Some days that's the same thing." },
      { by: 'b', say: "That's the nicest backhanded compliment I've ever had." },
      { by: 'a', conf: "I like winning. I don't like what it does. Every win makes me a bigger target the day the teams are gone." },
    ] },
    { id: 'ch2.w6', place: 'public', when: { third: true }, turns: [
      { by: 'b', say: "Okay, honest question. Who was the worst one out there today?" },
      { by: 'a', say: "Don't." },
      { by: 'b', say: "I'm just saying, if we'd lost..." },
      { by: 'c', say: "I'm right here, you know." },
      { by: 'b', say: "I know! I'm not saying anything bad. I'm saying we won. Which is good. For everybody." },
      { by: 'a', say: "Let it go. Nobody's going home." },
      { by: 'c', conf: "Everybody's celebrating. And I'm sitting here knowing that if we'd lost, it would have been me. That's not a great feeling to win with." },
    ] },
    { id: 'ch2.w7', place: 'fire', turns: [
      { beat: "That night {here}, the {tribe} are in a much better mood than the other team." },
      { by: 'b', say: "You know what's the best part of winning?" },
      { by: 'a', say: "Not having to vote?" },
      { by: 'b', say: "Not having to vote. And nobody whispering in the bushes all afternoon." },
      { by: 'a', say: "Give it a day. They'll be whispering again tomorrow." },
      { by: 'b', say: "Can you let me have one night?" },
      { by: 'a', say: "One night." },
      { by: 'b', conf: "{a} is the reason we're safe tonight. I'm going to remember that. I just hope {a} remembers who was cheering." },
    ] },
    { id: 'ch2.w8', place: 'public', when: { merged: false, early: true }, turns: [
      { by: 'b', say: "First win! Do you think we're the good team?" },
      { by: 'a', say: "One win doesn't make us the good team. It makes us the team that won once." },
      { by: 'b', say: "You're no fun." },
      { by: 'a', say: "I'm loads of fun. I'm just not dumb about it." },
      { by: 'b', say: "Fine. We're the team that won once. The team that won once is having a party." },
      { by: 'a', say: "...Okay. I can party." },
      { by: 'a', conf: "It's early. Everybody's still nice to each other. The moment we lose, that's going to change, so I'm enjoying it." },
    ] },
    { id: 'ch2.w9', place: 'aside', when: { gap: 'older' }, turns: [
      { by: 'b', say: "How are you not tired? I'm tired, and I'm younger than you." },
      { by: 'a', say: "Wow. Rude." },
      { by: 'b', say: "I mean it as a compliment!" },
      { by: 'a', say: "Uh-huh. Look, I've been working for a long time. I know how to keep going when it hurts." },
      { by: 'b', say: "Can you teach me?" },
      { by: 'a', say: "You stop thinking about how much it hurts. That's it." },
      { by: 'b', say: "That's terrible advice." },
      { by: 'a', say: "It's great advice. We won, didn't we?" },
      { by: 'a', conf: "Everybody thought the older one would slow them down. I just carried them. Remember that, kids." },
    ] },
  ],
  'story.chal.lost': [
    { id: 'ch2.l1', place: 'public', when: { registerB: 'fiery', register: 'fiery' }, turns: [
      { beat: "The {tribe} walk back {here}. {a} and {b} are already arguing." },
      { by: 'a', say: "You were last! LAST!" },
      { by: 'b', say: "And you were yelling at me the whole time! How was I supposed to concentrate?" },
      { by: 'a', say: "Maybe by concentrating!" },
      { by: 'b', say: "Maybe by shutting up!" },
      { by: 'c', say: "Guys! Everyone can hear you!" },
      { by: 'a', say: "Good! Let them hear it!" },
      { by: 'b', say: "Yeah, let them hear who started it!" },
      { by: 'c', conf: "We lost the challenge and now they're losing their minds. I just hope the team remembers this tonight. Both of them did this." },
    ] },
    { id: 'ch2.l2', place: 'aside', when: { registerB: ['sweet', 'shy'], register: ['sweet', 'shy', 'plain'] }, turns: [
      { by: 'a', say: "Hey. I'm not mad, okay? I just want to talk about it." },
      { by: 'b', say: "About how I lost it for us." },
      { by: 'a', say: "About what happened. You froze." },
      { by: 'b', say: "I know. I got in my head. Everyone was watching and I just... stopped." },
      { by: 'a', say: "Everyone gets in their head." },
      { by: 'b', say: "Not everyone loses the challenge for the whole team." },
      { by: 'a', say: "Look, I'm not going to tell you what people are going to do tonight. I don't know. But I'm not going to pretend it wasn't you, either." },
      { by: 'b', say: "That's fair. Thanks for not yelling." },
      { by: 'a', conf: "I like {b}. I really do. I just don't know if I like {b} enough to go home in {b.posAdj} place." },
    ] },
    { id: 'ch2.l3', place: 'public', when: { carriedA: true }, turns: [
      { by: 'a', say: "I'm just going to say it. I did everything I could out there." },
      { by: 'b', say: "We know. You keep reminding us." },
      { by: 'a', say: "Because some of us weren't even close. You were the slowest one by a mile." },
      { by: 'b', say: "Oh, so now you're the captain?" },
      { by: 'a', say: "I'm the one who almost won it on my own. That counts for something." },
      { by: 'b', say: "It counts for you being a threat. Did you think about that?" },
      { by: 'a', say: "...What's that supposed to mean?" },
      { by: 'b', say: "It means everybody saw how good you were today. Including the people voting tonight." },
      { by: 'b', conf: "{a} wants to make this about me. Fine. I'll make it about {a}. A strong player on a losing team is the easiest name to sell." },
    ] },
    { id: 'ch2.l4', place: 'fire', when: { register: ['schemer', 'cool'] }, turns: [
      { beat: "{a} sits down next to {b} {here}, all sympathy." },
      { by: 'a', say: "Hey. Don't be too hard on yourself." },
      { by: 'b', say: "I wasn't, until you said that." },
      { by: 'a', say: "I just mean, everybody knows you tried. People will understand." },
      { by: 'b', say: "Understand what?" },
      { by: 'a', say: "That today wasn't your day. That's all." },
      { by: 'b', say: "That sounds a lot like you've already decided how you're voting." },
      { by: 'a', say: "I haven't decided anything." },
      { by: 'b', say: "Right." },
      { by: 'a', conf: "If {b} thinks I'm on {b.posAdj} side, {b} won't come after me tonight. If {b} goes home, that's not my fault. That's the challenge's fault." },
      { by: 'b', conf: "{a} was being nice. {a} is never nice. That's how I know I'm in trouble." },
    ] },
    { id: 'ch2.l5', place: 'public', when: { streak: 'one', early: true }, turns: [
      { by: 'c', say: "Okay. First loss. It's fine. Teams lose." },
      { by: 'a', say: "Teams lose because of people." },
      { by: 'c', say: "Can we not do the blame thing on day one?" },
      { by: 'a', say: "It's not day one, and somebody has to go home tonight. So yeah, we're going to do the blame thing." },
      { by: 'b', say: "And I'm guessing you've already picked who." },
      { by: 'a', say: "I'm guessing you already know." },
      { by: 'b', say: "Wow. Okay." },
      { by: 'b', conf: "First vote, and I'm already the name. I need to talk to every single person on this team before tonight." },
    ] },
  ],
};
