// ══════════════════════════════════════════════════════════════════════
// td/story/lines/more.js — the pools a season wears down fastest, grown
// ══════════════════════════════════════════════════════════════════════
//
// Same keys and meanings as strategy.js, rivalry.js, showmance.js and morning*.js
// (index.js adds them up). Grown from the wear report of five played seasons
// (tests/zz-td-story-measure.test.js, 2026-10-08).

export default {
  'long.talk.approach.outside': [
    { id: 'mr.o1', place: 'work', turns: [
      { beat: "{a} offers to help {b} with a chore {here}. {b} knows it isn't about the chore." },
      { by: 'b', say: "Okay. What do you want?" },
      { by: 'a', say: "Can't I just help?" },
      { by: 'b', say: "Nobody just helps. Not out here." },
      { by: 'a', say: "Fine. I want to know if you'd ever work with somebody who isn't in your group." },
      { by: 'b', say: "I don't have a group." },
      { by: 'a', say: "Exactly. Neither do I, really. Mine just hasn't figured out that I've noticed." },
      { by: 'b', say: "Noticed what?" },
      { by: 'a', say: "That I'm the next one they'd cut. So I'm making friends before they do it." },
      { by: 'b', say: "And I'm the friend." },
      { by: 'a', say: "If you want to be." },
      { by: 'b', conf: "{a} is planning to jump ship. Good to know. Whether I'm the lifeboat or not is up to me." },
    ] },
    { id: 'mr.o2', place: 'secret', when: { register: ['schemer', 'cool'] }, turns: [
      { by: 'a', say: "I'll make this quick. My group is going to run out of people to vote for, and when they do, it's me or you." },
      { by: 'b', say: "That's a cheerful way to start a conversation." },
      { by: 'a', say: "It's an honest one. So I'd like it to be neither of us." },
      { by: 'b', say: "How?" },
      { by: 'a', say: "We find each other now, quietly. Nobody needs to know until it matters." },
      { by: 'b', say: "And when does it matter?" },
      { by: 'a', say: "The vote they don't see coming. That's when." },
      { by: 'b', say: "...You've thought about this." },
      { by: 'a', say: "I think about everything." },
      { by: 'a', conf: "My group thinks I'm loyal. I am. To me." },
    ] },
    { id: 'mr.o3', place: 'aside', when: { register: ['sweet', 'shy'] }, turns: [
      { by: 'a', say: "Can I tell you something kind of embarrassing?" },
      { by: 'b', say: "Sure." },
      { by: 'a', say: "My group doesn't really tell me stuff. I find out about the plan when everyone else does." },
      { by: 'b', say: "That's rough." },
      { by: 'a', say: "And you always seem to know what's going on, so I thought... maybe we could look out for each other?" },
      { by: 'b', say: "Look out how?" },
      { by: 'a', say: "Just tell each other things. That's it. I'm really good at listening." },
      { by: 'b', say: "...Okay. Yeah. I'd like that." },
      { by: 'b', conf: "{a} just told me {a.posAdj} alliance keeps {a.obj} in the dark. That's useful. That's really, really useful." },
    ] },
    { id: 'mr.o4', place: 'water', when: { merged: true }, turns: [
      { beat: "{a} and {b} are {here}, from different old teams, saying more than they should." },
      { by: 'a', say: "Do you ever think about how your old team would vote you out in a heartbeat?" },
      { by: 'b', say: "Every day. Thanks for bringing it up." },
      { by: 'a', say: "Mine too. So why are we still pretending we owe them anything?" },
      { by: 'b', say: "Because the second we stop pretending, they notice." },
      { by: 'a', say: "So we keep pretending. In public. And in private we're two people with nothing to lose." },
      { by: 'b', say: "Two people with nothing to lose is a pretty dangerous pair." },
      { by: 'a', say: "That's the idea." },
      { by: 'b', conf: "Teams are over. Everyone's still acting like they're not. {a} just said it out loud, to me. That means something." },
    ] },
  ],
  'long.talk.plan.any': [
    { id: 'mr.p1', place: 'aside', when: { tribal: true }, turns: [
      { by: 'b', say: "Okay, so tonight. Are we sure?" },
      { by: 'a', say: "We're sure." },
      { by: 'b', say: "Because last time we were sure, too." },
      { by: 'a', say: "Last time we didn't count. This time I counted twice." },
      { by: 'b', say: "And?" },
      { by: 'a', say: "And we're fine if nobody flips." },
      { by: 'b', say: "That's a big if." },
      { by: 'a', say: "That's always the if. That's the whole game." },
      { by: 'b', conf: "{a} keeps saying we're fine. I keep wanting to believe it. Tonight I'll find out which one of us is right." },
    ] },
    { id: 'mr.p2', place: 'secret', when: { register: ['schemer', 'cool'] }, turns: [
      { beat: "{a} keeps {a.posAdj} voice low {here}." },
      { by: 'a', say: "Here's what's going to happen. Everybody's going to come to you today. Let them." },
      { by: 'b', say: "Why?" },
      { by: 'a', say: "Because everyone who comes to you tells you who they're scared of. That's free information." },
      { by: 'b', say: "And then what?" },
      { by: 'a', say: "And then you tell me, and I tell you, and between us we know more than anyone else." },
      { by: 'b', say: "That's kind of brilliant." },
      { by: 'a', say: "It's kind of obvious. Nobody else does it, though." },
      { by: 'a', conf: "Two people listening beats ten people talking. Every single time." },
    ] },
    { id: 'mr.p3', place: 'fire', when: { register: ['fiery', 'competitor'] }, turns: [
      { by: 'a', say: "I'm done playing nice. Next vote, we go big." },
      { by: 'b', say: "Big how?" },
      { by: 'a', say: "Big like the biggest player out here. Nobody wants to say it, but everybody's thinking it." },
      { by: 'b', say: "If we miss, we're next." },
      { by: 'a', say: "If we don't try, we're next anyway, just slower." },
      { by: 'b', say: "...You really think we can pull it off?" },
      { by: 'a', say: "I think nobody will see it coming. That's half of it." },
      { by: 'b', conf: "{a} wants a big move. I want to get to the end. I'm not sure those are the same thing." },
    ] },
  ],
  'long.talk.lie.about': [
    { id: 'mr.l1', place: 'aside', when: { register: 'schemer' }, turns: [
      { by: 'a', say: "You're close with {target}, right?" },
      { by: 'b', say: "Pretty close. Why?" },
      { by: 'a', say: "No reason. Forget I asked." },
      { by: 'b', say: "No, what? You can't do that." },
      { by: 'a', say: "It's just... {target} was asking me how loyal you are. Like, a lot. It seemed weird." },
      { by: 'b', say: "{target} asked that?" },
      { by: 'a', say: "Maybe I'm reading into it. You know {target} better than me." },
      { by: 'b', say: "...Yeah. I thought I did." },
      { by: 'a', conf: "I didn't even have to say anything bad about {target}. I just let {b} fill in the blanks. People always fill them in worse." },
    ] },
    { id: 'mr.l2', place: 'secret', turns: [
      { beat: "{a} waits until {target} is well out of earshot." },
      { by: 'a', say: "I don't want to stir anything up, but you should know something." },
      { by: 'b', say: "That's what people say right before they stir something up." },
      { by: 'a', say: "Ha. Fair. {target} wants you gone. Next time we're at a vote." },
      { by: 'b', say: "How do you know?" },
      { by: 'a', say: "{target} told me. Asked if I'd go along with it." },
      { by: 'b', say: "And what did you say?" },
      { by: 'a', say: "I said I'd think about it. Then I came straight to you." },
      { by: 'b', say: "...Thank you. Seriously." },
      { by: 'a', conf: "{target} never said a word to me about {b}. But {b} believes me now, and {b} owes me. Two birds." },
    ] },
  ],
  'long.drama.fight.snap': [
    { id: 'mr.fs1', place: 'eat', turns: [
      { by: 'b', say: "Are you going to finish that, or just stare at it?" },
      { by: 'a', say: "Why, you want it?" },
      { by: 'b', say: "I'm just saying, some of us are still hungry." },
      { by: 'a', say: "Then go get more!" },
      { by: 'b', say: "There isn't any more!" },
      { by: 'a', say: "Then that's not my problem!" },
      { by: 'c', say: "Oh my god. It's food. Share it or eat it." },
      { by: 'a', say: "Fine! Here!" },
      { beat: "{a} shoves the plate across. {b} takes it without saying thanks." },
      { by: 'c', conf: "Everybody's hungry, everybody's tired, and everybody's one bad comment away from a fight. Today it was {a}." },
    ] },
    { id: 'mr.fs2', place: 'sleep', turns: [
      { beat: "Late, in the {quarters}. Somebody keeps shifting around." },
      { by: 'a', say: "Can you stop moving? Some of us are trying to sleep." },
      { by: 'b', say: "Some of us can't sleep, because some of us snore." },
      { by: 'a', say: "I don't snore!" },
      { by: 'b', say: "You absolutely snore!" },
      { by: 'c', say: "You BOTH snore. Go to sleep." },
      { beat: "Nobody says anything for a while." },
      { by: 'a', say: "I don't snore." },
      { by: 'b', conf: "I'm going to write {a}'s name down just so I can sleep through the night." },
    ] },
  ],
  'long.romance.moment.crush': [
    { id: 'mr.cr1', place: 'public', turns: [
      { beat: "{b} walks past {here}. {a} stops mid-sentence." },
      { by: 'c', say: "And then? You were saying?" },
      { by: 'a', say: "Huh? Oh. Yeah. I forgot." },
      { by: 'c', say: "You forgot. Mid-sentence. When {b} walked past." },
      { by: 'a', say: "That's a coincidence." },
      { by: 'c', say: "That's the fourth coincidence today." },
      { by: 'a', say: "Can you keep it down?" },
      { by: 'c', conf: "{a} has a crush on {b}. The whole camp can see it. Except {b}. Somehow." },
      { by: 'a', conf: "I don't have a crush. I just think {b} is really, really... I'm going to stop talking now." },
    ] },
    { id: 'mr.cr2', place: 'work', turns: [
      { by: 'a', say: "Do you need help with that?" },
      { by: 'b', say: "No, I've got it." },
      { by: 'a', say: "Are you sure? It looks heavy." },
      { by: 'b', say: "It's a bag of leaves." },
      { by: 'a', say: "Heavy leaves." },
      { by: 'b', say: "...Fine. You can help." },
      { beat: "{a} takes one side of the bag. It is not heavy. Neither of them says so." },
      { by: 'b', conf: "{a} keeps finding reasons to be near me. I'm starting to think I don't mind." },
    ] },
  ],
  'long.drama.sorry.any': [
    { id: 'mr.so1', place: 'water', turns: [
      { by: 'a', say: "Hey. Can I sit?" },
      { by: 'b', say: "If you're here to start round two, no." },
      { by: 'a', say: "I'm not. I'm here to say sorry." },
      { by: 'b', say: "...Okay. I'm listening." },
      { by: 'a', say: "I took it out on you. It wasn't even about you. It was about the game, and you were there." },
      { by: 'b', say: "That's a really bad reason to yell at someone." },
      { by: 'a', say: "I know. That's why I'm sorry." },
      { by: 'b', say: "Fine. We're good. Mostly." },
      { by: 'a', say: "Mostly's good." },
      { by: 'b', conf: "I'm going to forgive {a}. I'm also going to remember. Both of those things can be true." },
    ] },
    { id: 'mr.so2', place: 'aside', when: { register: ['sweet', 'shy'] }, turns: [
      { by: 'a', say: "I'm so sorry. I've been feeling sick about it all day." },
      { by: 'b', say: "About what?" },
      { by: 'a', say: "About how I acted. That wasn't me. Or it was me, but a really bad version of me." },
      { by: 'b', say: "Everyone has a bad version." },
      { by: 'a', say: "Yeah, but mine came out in front of everybody." },
      { by: 'b', say: "It's okay. Honestly. Thanks for saying it." },
      { by: 'a', say: "Really? You're not mad?" },
      { by: 'b', say: "I was. I'm less mad now." },
      { by: 'a', conf: "I've been holding that in all day. I feel so much lighter. I might actually be able to eat dinner." },
    ] },
  ],
  'long.drama.thaw.any': [
    { id: 'mr.th1', place: 'work', turns: [
      { beat: "{a} and {b} get stuck doing the same chore {here}. Nobody else volunteered." },
      { by: 'a', say: "This is your fault, you know." },
      { by: 'b', say: "How is this my fault?" },
      { by: 'a', say: "You put your hand up for this, and I put mine up because I didn't want you to look better than me." },
      { by: 'b', say: "...That's the dumbest thing I've ever heard." },
      { by: 'a', say: "Yeah. I'm aware." },
      { beat: "{b} laughs before {b.sub} can stop {b.ref}." },
      { by: 'b', say: "Okay, that's actually funny." },
      { by: 'a', say: "Don't tell anyone." },
      { by: 'b', conf: "I can't stand {a}. I just found out I can't stand {a} a little less than I thought." },
    ] },
    { id: 'mr.th2', place: 'fire', when: { merged: true }, turns: [
      { by: 'a', say: "We don't have to like each other, but we're running out of people." },
      { by: 'b', say: "Meaning?" },
      { by: 'a', say: "Meaning one day soon, I might need your vote, and you might need mine. So maybe we stop wasting energy." },
      { by: 'b', say: "That's the least romantic peace offer I've ever heard." },
      { by: 'a', say: "It's not romantic. It's maths." },
      { by: 'b', say: "...Okay. Truce. For now." },
      { by: 'a', say: "For now." },
      { by: 'a', conf: "I didn't make a friend. I made one less enemy. This late in the game, that's basically the same thing." },
    ] },
  ],
  'long.drama.fight.tense': [
    { id: 'mr.ft1', place: 'secret', turns: [
      { by: 'b', say: "Is there a reason you keep telling people I'm not trustworthy?" },
      { by: 'a', say: "Is there a reason you keep giving me reasons to?" },
      { by: 'b', say: "Give me one example. One." },
      { by: 'a', say: "I don't need to give you examples. I just need to give them to other people." },
      { by: 'b', say: "You're doing this on purpose." },
      { by: 'a', say: "Everything I do out here is on purpose." },
      { beat: "They stare at each other. Neither of them raises their voice. That's the scary part." },
      { by: 'b', conf: "{a} is coming after me. Quietly. I'd honestly prefer the yelling." },
    ] },
  ],
  'story.morning.blindside': [
    { id: 'mr.mb1', place: 'public', when: { register: ['competitor', 'fiery'] }, turns: [
      { beat: "{a} is {here}, doing push-ups. Hard ones." },
      { by: 'c', say: "How many is that?" },
      { by: 'a', say: "I stopped counting." },
      { by: 'c', say: "Is this about {lastBoot}?" },
      { by: 'a', say: "This is about me not seeing it. I'm supposed to see it." },
      { by: 'c', say: "Nobody saw it." },
      { by: 'a', say: "Somebody did. Somebody planned it." },
      { by: 'b', say: "Morning. Wow. Intense." },
      { by: 'a', say: "Yeah. Get used to it." },
      { by: 'a', conf: "I'm not crying about {lastBoot}. I'm getting stronger, so the next time somebody tries this on me, I win immunity and watch it fall apart." },
    ] },
    { id: 'mr.mb2', place: 'eat', when: { register: ['sweet', 'shy'] }, turns: [
      { beat: "Breakfast {here}. {a} has made two portions out of habit." },
      { by: 'c', say: "Who's the second one for?" },
      { by: 'a', say: "...Nobody. I forgot." },
      { by: 'c', say: "Oh. {lastBoot}." },
      { by: 'a', say: "I always made {lastBoot} breakfast. It's dumb." },
      { by: 'b', say: "I'll take it, if no one else is going to." },
      { beat: "{a} looks at {b} for a long second, then pushes the bowl across." },
      { by: 'a', say: "Sure. Enjoy." },
      { by: 'a', conf: "I don't know who voted for {lastBoot}. But I watched {b} eat {lastBoot}'s breakfast like nothing happened, and that told me something." },
    ] },
    { id: 'mr.mb3', place: 'aside', when: { merged: true, count: true }, turns: [
      { by: 'a', say: "{bootVotes} votes. That's not a stray. That's a plan." },
      { by: 'b', say: "Plans happen." },
      { by: 'a', say: "Plans I'm in happen. This one happened without me. That's new." },
      { by: 'b', say: "Welcome to the merge." },
      { by: 'a', say: "Were you in it?" },
      { by: 'b', say: "Does it matter now?" },
      { by: 'a', say: "It matters to me." },
      { by: 'b', say: "Then you're going to have to figure it out on your own." },
      { by: 'a', conf: "That's the first time {b} didn't answer a question I asked. That's all the answer I need." },
    ] },
  ],
};
