// ══════════════════════════════════════════════════════════════════════
// td/story/lines/morning2.js — more mornings after a vote
// ══════════════════════════════════════════════════════════════════════
//
// Same parts and outcomes as morning.js. Knowledge rules: nobody knows anyone
// else's ballot; b's own vote is spoken only when bVoted says it ('boot');
// the count ({bootVotes}) only where votes are read out (count: true).

export default {
  'story.morning.blindside': [
    { id: 'mo2.b1', place: 'eat', when: { register: ['competitor', 'plain'] }, turns: [
      { beat: "Breakfast {here}. {a} sits down across from {b} and doesn't touch {a.posAdj} food." },
      { by: 'b', say: "Something wrong with it? I mean, besides the usual." },
      { by: 'a', say: "{lastBoot} was supposed to be safe last night." },
      { by: 'b', say: "Says who?" },
      { by: 'a', say: "Says everybody I talked to. Which tells me I talked to the wrong people." },
      { by: 'b', say: "Or the right people lied to you. Happens." },
      { by: 'a', say: "Yeah? Did it happen with you?" },
      { by: 'b', say: "I'm eating my breakfast, {a}." },
      { by: 'a', say: "That's not a no." },
      { by: 'b', say: "It's not a yes either. Eat something. You'll think better." },
      { by: 'a', conf: "I'm not going to cry over it. I'm going to find out who flipped, and then I'm going to make it really expensive." },
    ] },
    { id: 'mo2.b2', place: 'sleep', when: { third: true }, turns: [
      { beat: "The {quarters}. {a} is sitting on the edge of {lastBoot}'s empty {bed} when {c} wakes up." },
      { by: 'c', say: "Have you been up all night?" },
      { by: 'a', say: "Most of it." },
      { by: 'c', say: "Do you want to talk about it?" },
      { by: 'a', say: "Talk about what? {lastBoot}'s gone, and I didn't see it coming. There's nothing to talk about. There's just stuff to do." },
      { by: 'c', say: "Like what?" },
      { by: 'a', say: "Like figuring out who I can still trust in here. Starting with you." },
      { by: 'c', say: "Me? I didn't do anything!" },
      { by: 'a', say: "Then you won't mind me asking." },
      { beat: "{b} comes in, sees them, and goes straight back out." },
      { by: 'c', say: "...Okay, that was weird." },
      { by: 'a', say: "That was very weird." },
      { by: 'a', conf: "{b} couldn't get out of that room fast enough. Innocent people don't do that." },
    ] },
    { id: 'mo2.b3', place: 'aside', when: { register: 'fiery', bVoted: 'boot' }, turns: [
      { by: 'a', say: "Tell me you didn't." },
      { by: 'b', say: "Didn't what?" },
      { by: 'a', say: "Write {lastBoot}. Tell me you didn't, and I'll believe you." },
      { by: 'b', say: "...I'm not going to lie to you." },
      { by: 'a', say: "Unbelievable." },
      { by: 'b', say: "{lastBoot} was going after people. I wasn't going to be one of them." },
      { by: 'a', say: "{lastBoot} was going after nobody! {lastBoot} was my friend!" },
      { by: 'b', say: "Your friend. Not mine." },
      { by: 'a', say: "You know what? Good. Now I know." },
      { by: 'b', conf: "At least I told {a} the truth. Most people out here wouldn't have." },
      { by: 'a', conf: "{b} wants credit for being honest about stabbing me in the back. No. No credit." },
    ] },
    { id: 'mo2.b4', place: 'aside', when: { register: ['sweet', 'shy'], bVoted: 'boot' }, turns: [
      { by: 'a', say: "Can I ask you something? Did you vote for {lastBoot}?" },
      { by: 'b', say: "...Yeah. I did." },
      { by: 'a', say: "Oh." },
      { by: 'b', say: "I'm sorry. I know you two were close." },
      { by: 'a', say: "We were. Are. I don't know what you call it when someone's gone." },
      { by: 'b', say: "It wasn't about you. I promise." },
      { by: 'a', say: "Everyone keeps saying that. It still feels like it was about me." },
      { by: 'b', say: "I get that." },
      { beat: "{a} nods, and goes off to do the dishes on {a.posAdj} own." },
      { by: 'b', conf: "I could have lied. Maybe I should have. {a} looked at me like I'd kicked a puppy." },
      { by: 'a', conf: "At least {b} told me. That's something. It's not enough, but it's something." },
    ] },
    { id: 'mo2.b5', place: 'public', when: { merged: false }, turns: [
      { beat: "Chores {here}. Everyone is very busy, and very quiet." },
      { by: 'c', say: "Okay, is nobody going to say it?" },
      { by: 'b', say: "Say what?" },
      { by: 'c', say: "That this team just voted out {lastBoot} and {a} had no idea." },
      { by: 'a', say: "Thanks, {c}. Really. That helps." },
      { by: 'c', say: "Sorry! I just mean, it's weird. Everyone's acting like it's normal." },
      { by: 'b', say: "It is normal. Somebody goes home every time we lose. That's the whole show." },
      { by: 'a', say: "And it's normal that nobody told me?" },
      { by: 'b', say: "Maybe nobody told you because you'd have told {lastBoot}." },
      { by: 'a', say: "...Yeah. I would have." },
      { by: 'b', say: "So there you go." },
      { by: 'a', conf: "{b} is right, which is the worst part. They kept me out of it because they knew which side I'd pick. So now I know which side I'm on." },
    ] },
    { id: 'mo2.b6', place: 'water', when: { register: ['schemer', 'cool'], count: true }, turns: [
      { beat: "{a} is {here}, scratching numbers into the ground with a stick." },
      { by: 'c', say: "What's that?" },
      { by: 'a', say: "Last night. {bootVotes} votes for {lastBoot}. I knew about two." },
      { by: 'c', say: "So who are the others?" },
      { by: 'a', say: "That's what the stick is for." },
      { by: 'c', say: "Are you okay?" },
      { by: 'a', say: "I'm not sad, if that's what you mean. I'm annoyed. Somebody out-planned me, and I hate being out-planned." },
      { beat: "{a} scuffs the numbers out with {a.posAdj} foot as {b} walks past." },
      { by: 'b', say: "Morning." },
      { by: 'a', say: "Morning." },
      { by: 'a', conf: "{b} said good morning like {b.sub} meant it. That's either a clear conscience, or a very good liar. I'll find out which." },
    ] },
    { id: 'mo2.b7', place: 'sleep', when: { age: ['thirties', 'older'], ageB: ['teen', 'twenties'] }, turns: [
      { beat: "{a} is up first, sitting on {a.posAdj} {bed} in the {quarters} with a towel round {a.posAdj} neck." },
      { by: 'c', say: "You okay? You're up early." },
      { by: 'a', say: "I'm always up early. I'm just usually happier about it." },
      { by: 'c', say: "Because of {lastBoot}?" },
      { by: 'a', say: "Because I've been around long enough to know when I've been played. And I didn't see this one coming. That doesn't happen to me." },
      { by: 'c', say: "It happens to everybody out here." },
      { by: 'a', say: "Sure. Once." },
      { by: 'b', say: "You two are up early." },
      { by: 'a', say: "Some of us didn't sleep so well." },
      { by: 'b', say: "I slept great." },
      { by: 'a', say: "I bet you did." },
      { by: 'a', conf: "These kids think the older player is the easy vote. Fine. Let them. It's going to make it so much better when I win." },
    ] },
    { id: 'mo2.b8', place: 'eat', when: { age: 'teen' }, turns: [
      { beat: "Breakfast {here}. {a} is pushing food around {a.posAdj} plate." },
      { by: 'c', say: "You're not eating." },
      { by: 'a', say: "I'm not hungry. Is that allowed?" },
      { by: 'c', say: "Is this about {lastBoot}?" },
      { by: 'a', say: "Everybody said they had my back. Everybody. And then it's {lastBoot} who goes home, and I'm the only one who didn't know." },
      { by: 'b', say: "Welcome to the game." },
      { by: 'a', say: "Wow. Thanks. That's super helpful." },
      { by: 'b', say: "I'm serious. Everyone gets blindsided once. The trick is it only happens once." },
      { by: 'a', say: "Is that a threat or advice?" },
      { by: 'b', say: "Yes." },
      { by: 'a', conf: "Okay. Lesson learned. Nobody here is my friend. Some of them are just better at pretending." },
    ] },
    { id: 'mo2.b9', place: 'aside', when: { merged: true, register: ['schemer', 'cool', 'competitor'] }, turns: [
      { by: 'a', say: "So. You want to tell me who was in on it?" },
      { by: 'b', say: "In on what?" },
      { by: 'a', say: "Don't. {lastBoot} was with me. Everybody knew that. Somebody built the votes to take {lastBoot.obj} out from under me." },
      { by: 'b', say: "Maybe nobody built anything. Maybe people just didn't want {lastBoot} in the end." },
      { by: 'a', say: "People don't just not want somebody all at the same time. Somebody tells them to." },
      { by: 'b', say: "And you think that was me." },
      { by: 'a', say: "I think you know who it was." },
      { by: 'b', say: "And if I did, why would I tell you?" },
      { by: 'a', say: "Because I'm going to find out anyway, and I'm going to remember who helped." },
      { by: 'b', conf: "{a} is fishing. If I give {a.obj} a name, {a} owes me. If I don't, {a} hates me. This game is so fun." },
    ] },
    { id: 'mo2.b10', place: 'work', when: { register: ['sweet', 'shy', 'plain'], third: true }, turns: [
      { beat: "Chores {here}. {c} is helping {a} carry things, mostly so {a} isn't on {a.posAdj} own." },
      { by: 'c', say: "Can I say something without you getting mad?" },
      { by: 'a', say: "Probably not, but go." },
      { by: 'c', say: "I don't think {lastBoot} would want you moping all day." },
      { by: 'a', say: "{lastBoot} would want me to win. I don't know how to do that without {lastBoot.obj}." },
      { by: 'c', say: "You do it with the people who are still here." },
      { by: 'a', say: "And which of the people who are still here wrote {lastBoot.posAdj} name?" },
      { by: 'c', say: "...Not me." },
      { by: 'a', say: "Okay. Then you're who I do it with." },
      { by: 'c', conf: "I didn't vote for {lastBoot}. Thank god. I don't think {a} would ever have forgiven me." },
    ] },
    { id: 'mo2.b11', place: 'public', when: { register: 'fiery', merged: true }, turns: [
      { beat: "{a} stands in the middle of camp as people come out for breakfast." },
      { by: 'a', say: "Good morning, everybody! Did everybody sleep well?" },
      { by: 'c', say: "Oh no." },
      { by: 'a', say: "Because {lastBoot} didn't sleep here last night, and I'd love to know who's responsible." },
      { by: 'b', say: "Can you not do this in front of everyone?" },
      { by: 'a', say: "Why not? Everyone did it in front of me." },
      { by: 'b', say: "You're making yourself the next target." },
      { by: 'a', say: "I was the next target the second {lastBoot} went home. At least now I'm a loud one." },
      { by: 'c', conf: "{a} just stood in the middle of camp and declared war on everybody. It's honestly kind of impressive." },
    ] },
    { id: 'mo2.b12', place: 'secret', when: { register: ['schemer', 'cool'] }, turns: [
      { beat: "{a} takes {c} out to {place} before breakfast." },
      { by: 'c', say: "Why are we out here?" },
      { by: 'a', say: "Because I need to know if you knew. About {lastBoot}." },
      { by: 'c', say: "No! I swear. I found out when everyone else did." },
      { by: 'a', say: "Okay." },
      { by: 'c', say: "That's it? Okay?" },
      { by: 'a', say: "If you'd known, you'd have said too much just now. You didn't. So, okay." },
      { by: 'c', say: "That's a really creepy way to trust somebody." },
      { by: 'a', say: "It's the only way I've got. Now. Who do you think did it?" },
      { by: 'c', say: "Honestly? {b}'s been acting weird all morning." },
      { by: 'a', say: "Yeah. I noticed." },
      { by: 'a', conf: "I lost my closest ally last night. This morning I picked up a new one. That's how you survive a blindside. You don't mourn. You replace." },
    ] },
    { id: 'mo2.b13', place: 'fire', when: { register: ['competitor', 'plain', 'sweet'] }, turns: [
      { beat: "{a} is relighting the fire {here}. {b} comes over to help." },
      { by: 'b', say: "Need a hand?" },
      { by: 'a', say: "No." },
      { by: 'b', say: "Okay." },
      { beat: "{b} helps anyway. Neither of them says anything for a while." },
      { by: 'b', say: "I know you're mad." },
      { by: 'a', say: "I'm not mad. I'm embarrassed. {lastBoot} trusted me to know what was going on, and I didn't." },
      { by: 'b', say: "That's not your fault." },
      { by: 'a', say: "Then whose is it?" },
      { by: 'b', say: "...The people who didn't tell you." },
      { by: 'a', say: "Right. And I'm going to figure out who that is." },
      { by: 'b', conf: "{a} is going to figure it out eventually. I just have to make sure that when {a} does, I'm already on {a.posAdj} side." },
    ] },
  ],

  'story.morning.agreed': [
    { id: 'mo2.a1', place: 'sleep', when: { register: ['sweet', 'shy'] }, turns: [
      { beat: "The {quarters}. {a} is looking at {lastBoot}'s empty {bed}." },
      { by: 'c', say: "You okay?" },
      { by: 'a', say: "I wrote {lastBoot}'s name. I keep thinking about it." },
      { by: 'c', say: "You had to. The whole team was going that way." },
      { by: 'a', say: "That's what I told myself. It doesn't feel like a reason this morning. It feels like an excuse." },
      { by: 'c', say: "Would it feel better if it was you who'd gone?" },
      { by: 'a', say: "...No." },
      { by: 'c', say: "Then it was the right call." },
      { by: 'a', conf: "{c} keeps saying it was the right call. I keep waiting to feel like it was." },
    ] },
    { id: 'mo2.a2', place: 'aside', when: { register: ['schemer', 'cool', 'competitor'] }, turns: [
      { by: 'b', say: "You good? You and {lastBoot} were close." },
      { by: 'a', say: "Close enough that {lastBoot} would've beaten me at the end." },
      { by: 'b', say: "That's cold." },
      { by: 'a', say: "That's the game. The people closest to you are the ones who know how to beat you." },
      { by: 'b', say: "So what does that make me?" },
      { by: 'a', say: "Somebody I'm not that close to yet." },
      { by: 'b', say: "...I'm going to choose to take that as a compliment." },
      { by: 'a', conf: "I'll miss {lastBoot}. I will. I'll miss {lastBoot} from a lot closer to the end than I'd have got with {lastBoot.obj} here." },
    ] },
    { id: 'mo2.a3', place: 'eat', when: { register: 'fiery' }, turns: [
      { beat: "Breakfast {here}. {a} is stabbing at {a.posAdj} food." },
      { by: 'c', say: "What did that food ever do to you?" },
      { by: 'a', say: "It's not the food. It's me." },
      { by: 'c', say: "Is this about the vote?" },
      { by: 'a', say: "I voted out {lastBoot}. My friend. Because I was scared." },
      { by: 'c', say: "Scared of what?" },
      { by: 'a', say: "Of being the one who didn't go along with it. And now I'm mad at myself, and mad at everyone else, and I can't decide who to yell at first." },
      { by: 'c', say: "Maybe don't yell at anyone?" },
      { by: 'a', say: "Yeah, that's not happening." },
      { by: 'a', conf: "I hate that I did it. I'd hate it more if I'd gone home instead. That's the worst part of this game. Both of those are true." },
    ] },
    { id: 'mo2.a4', place: 'aside', when: { merged: true }, turns: [
      { by: 'a', say: "Last night was the first vote where I actually hated what I wrote." },
      { by: 'b', say: "{lastBoot}?" },
      { by: 'a', say: "{lastBoot}. {lastBoot} and me were tight." },
      { by: 'b', say: "You know why it had to happen." },
      { by: 'a', say: "I know. If {lastBoot} stayed, everybody was going to look at the two of us as a pair. A pair doesn't last after the merge." },
      { by: 'b', say: "So now you're one person again." },
      { by: 'a', say: "One person nobody's scared of. Yeah. Lucky me." },
      { by: 'a', conf: "I cut my own partner loose so I'd look less dangerous. If that works, it's the best move I've made. If it doesn't, it's the worst." },
    ] },
  ],

  'story.morning.nobody': [
    { id: 'mo2.n1', place: 'public', when: { merged: false }, turns: [
      { beat: "The team gets on with the day {here}. {lastBoot}'s stuff is already gone." },
      { by: 'b', say: "Okay. We're down one. We need to stop losing." },
      { by: 'a', say: "Big if true." },
      { by: 'b', say: "I'm serious. Every time we lose, we lose a person. Every time we lose a person, we're weaker. That's how a team dies." },
      { by: 'c', say: "So what do we do?" },
      { by: 'b', say: "We win the next one. And if we can't win it, we make sure whoever goes next is the one who's dragging us down." },
      { by: 'a', say: "That sounds like you already have a name." },
      { by: 'b', say: "I've got a few." },
      { by: 'a', conf: "{lastBoot} was gone for one night before {b} started picking the next one. I want to be on whatever side of that {b} is on." },
    ] },
    { id: 'mo2.n2', place: 'aside', when: { register: ['sweet', 'shy'] }, turns: [
      { by: 'a', say: "Is it bad that I don't really miss {lastBoot}?" },
      { by: 'c', say: "Did you know {lastBoot.obj} that well?" },
      { by: 'a', say: "Not really. We talked like, twice." },
      { by: 'c', say: "Then no. It's not bad. You can't miss somebody you didn't know." },
      { by: 'a', say: "It feels mean." },
      { by: 'c', say: "It'd be mean if you were happy about it." },
      { by: 'a', say: "I'm not happy. I'm just... okay." },
      { by: 'a', conf: "I keep telling myself I should feel worse. Then I remember it wasn't me, and I feel fine. I think that makes me a little bit of a bad person." },
    ] },
    { id: 'mo2.n3', place: 'work', when: { register: ['fiery', 'competitor'] }, turns: [
      { by: 'a', say: "Can we not do the sad morning thing? I hate the sad morning thing." },
      { by: 'b', say: "Nobody's doing a sad morning thing." },
      { by: 'a', say: "{c} is literally looking at {lastBoot}'s empty spot." },
      { by: 'c', say: "I'm looking at the {quarters}! It's where I live!" },
      { by: 'a', say: "Whatever. We've got a challenge to win. Let's go." },
      { by: 'b', conf: "{a} doesn't do feelings. {a} does winning. Honestly? Today that's fine with me." },
    ] },
    { id: 'mo2.n4', place: 'eat', when: { register: ['schemer', 'cool'] }, turns: [
      { beat: "Breakfast {here}. {a} is watching who sits with who." },
      { by: 'b', say: "What are you staring at?" },
      { by: 'a', say: "The tables. Last night changed them. Look." },
      { by: 'b', say: "It's people eating breakfast." },
      { by: 'a', say: "It's people eating breakfast with somebody new. When {lastBoot} went, a few people lost their seat. Now they're looking for one." },
      { by: 'b', say: "That's either really smart or really creepy." },
      { by: 'a', say: "It's useful. Whoever's looking for a seat is looking for an alliance. I'd like it to be ours." },
      { by: 'a', conf: "Every vote leaves people on their own for about a day. That's the best time to recruit them. They're lonely, and they're scared." },
    ] },
  ],

  'story.morning.relief': [
    { id: 'mo2.r1', place: 'aside', when: { register: ['schemer', 'fiery'] }, turns: [
      { by: 'a', say: "I'm not going to pretend I'm sad." },
      { by: 'c', say: "Nobody asked you to." },
      { by: 'a', say: "Good. Because {lastBoot} spent the whole time making my life harder, and now {lastBoot}'s gone." },
      { by: 'c', say: "You could at least act a little bit sad." },
      { by: 'a', say: "Why? So people think I'm nice? I'm not nice. I'm still here." },
      { by: 'b', say: "Remind me never to get on your bad side." },
      { by: 'a', say: "Too late for {lastBoot}." },
      { by: 'b', conf: "{a} is loving this a little too much. People notice that kind of thing." },
    ] },
  ],
};
