// ══════════════════════════════════════════════════════════════════════
// td/story/lines/n-camp.js — camp life: group scenes, cross-team, friendship, cover
// ══════════════════════════════════════════════════════════════════════
//
// Long versions of the engine's camp moments (td/script/lines headers: crowd.js, cross.js,
// friend.js, life.js), plus the cover confessional (director.js coverScene).
//   crowd.meal / crowd.dinner  a, b and c over the food      crowd.chores  a leads, b and c pitch in
//   crowd.nerves  the team going to the vote tonight          crowd.huddle  {group} closes ranks
//   crowd.immune  after the merge a won immunity; b glad, c not
//   crowd.clash   a and b go at it in front of everyone; c steps in
//   cross.rival / cross.friend  a (team {mine}) and b (team {theirs}) at a shared camp
//   cross.spy.<leak|shut>  a fishes b about {theirs}'s plans; b lets slip / sees it coming
//   friend.*      bond, goof, comfort, open, rideordie, drift, laugh, joke, sunrise, thanks,
//                 struggle, lift, rally, solidarity, mentor, teach
//   life.surprise a, nobody rated, is good at something      hosted.raid.fun  a night run (cabins)
//   story.cover.<votes|allied|thread|quiet>  a, unheard so far this episode, to camera
// Ids: 'ny.' (camp) and 'nq.' (cover).

const Q = (id, when, lines, v) => ({ id, ...(when ? { when } : {}), turns: lines.map((conf, i) => ({ by: 'a', conf, ...(i === 0 && v ? { v } : {}) })) });

export default {
  'long.crowd.meal.any': [
    { id: 'ny.m1', place: 'eat', turns: [
      { beat: "Breakfast {here}. {a}, {b} and {c} end up at the same end of the table." },
      { by: 'b', say: "Is this the same thing as yesterday?", v: { dry: "Is this yesterday's food, or just its cousin?", loud: "Is this the SAME thing as yesterday?!", food: "Please tell me this isn't the same thing as yesterday, because I really need some variety in my life right now.", teen: "Wait, is this literally the same as yesterday?" } },
      { by: 'a', say: "I think it's the same thing as every day." },
      { by: 'c', say: "I'm going to pretend it's pancakes." },
      { by: 'a', say: "How's that going?" },
      { by: 'c', say: "Badly." },
      { by: 'b', say: "What's everybody doing today?" },
      { by: 'a', say: "Surviving. Same as you." },
      { by: 'c', conf: "Breakfast is the only time nobody talks strategy. For about ten minutes, we're just people who hate the food together.", v: { warm: "Breakfast is honestly my favourite part of the day, because nobody's plotting and we're just us.", schemer: "Everybody relaxes at breakfast. That's when you learn the most.", grown: "Ten minutes of peace over bad food. At my age, I'll take it." } },
    ] },
    { id: 'ny.m2', place: 'eat', when: { lastBoot: true }, turns: [
      { beat: "Breakfast {here}. There's an empty spot where {lastBoot} used to sit." },
      { by: 'b', say: "Is anybody going to sit there?", v: { anxious: "Is it okay to sit there? It feels weird to sit there.", blunt: "Somebody just sit there. It's a seat.", emotional: "I can't sit there. I just can't." } },
      { by: 'c', say: "It feels weird." },
      { by: 'a', say: "It's a seat. {lastBoot} isn't coming back for it." },
      { by: 'b', say: "That's cold." },
      { by: 'a', say: "It's true, though." },
      { beat: "Nobody sits there." },
      { by: 'c', conf: "Every time someone goes, there's a gap at the table. You notice it every meal for about two days. Then you stop noticing. That's the worst part.", v: { dry: "Empty seat at breakfast. By Thursday, nobody will remember it was ever full.", competitive: "One less person at the table. One less person between me and the end." } },
    ] },
    { id: 'ny.m3', place: 'eat', when: { voice: ['goofy', 'food', 'chaotic', 'loud'] }, turns: [
      { by: 'a', say: "Okay, we're ranking the food here, worst to least worst. Go." },
      { by: 'b', say: "We are not doing this." },
      { by: 'c', say: "Today's is the worst. Easily." },
      { by: 'a', say: "Wrong, day two was the worst, because day two moved." },
      { by: 'b', say: "It did not move." },
      { by: 'a', say: "It moved! I saw it!" },
      { by: 'b', conf: "{a} makes every meal into a whole thing. It's annoying. It's also the only reason anyone laughs before noon." },
    ] },
    { id: 'ny.m4', place: 'eat', when: { voice: ['schemer', 'calm', 'dry', 'competitive'] }, turns: [
      { beat: "{a} eats slowly {here}, listening to {b} and {c} talk." },
      { by: 'b', say: "...and then I said, if you want the fire bigger, get the wood yourself." },
      { by: 'c', say: "Who was that, again?" },
      { by: 'b', say: "Doesn't matter." },
      { by: 'a', say: "Sounds like it matters a little." },
      { by: 'b', say: "It doesn't." },
      { by: 'a', conf: "{b} didn't want to say the name. That means it's someone {b} is working with. Breakfast is the best time to find things out.", v: { calm: "People talk too much when they're eating. I just listen." } },
    ] },
  ],
  'long.crowd.dinner.any': [
    { id: 'ny.d1', place: 'eat', turns: [
      { beat: "Dinner {here}. Everyone is too tired to talk much." },
      { by: 'a', say: "What a day.", v: { dry: "Well, that was a day. Technically.", loud: "WHAT a day!", anxious: "That was... a lot. Today was just a lot.", grown: "Long day. My bones are telling me about it." } },
      { by: 'b', say: "What a terrible day." },
      { by: 'c', say: "Is it over? Please tell me it's over." },
      { by: 'a', say: "It's over. We just have to eat this." },
      { by: 'c', say: "Then it's not over." },
      { by: 'b', conf: "Nights like this, I almost like these people. Then breakfast comes and we're back to plotting.", v: { warm: "I actually love these people. Please don't tell them.", cruel: "They're tolerable when they're too tired to talk." } },
    ] },
    { id: 'ny.d2', place: 'eat', when: { lost: true }, turns: [
      { by: 'b', say: "So nobody's going to say it?", v: { blunt: "Are we really not going to talk about tonight?", anxious: "Is anybody else freaking out? Just me?", loud: "Is NOBODY going to say it?!" } },
      { by: 'a', say: "Say what?" },
      { by: 'b', say: "That somebody here is going home tonight, and we're all just eating like it's fine." },
      { by: 'c', say: "What do you want us to do? Not eat?" },
      { by: 'b', say: "I want somebody to say something." },
      { by: 'a', say: "Fine, this food is terrible and one of us is going home tonight. Better?" },
      { by: 'b', say: "...A little." },
      { by: 'c', conf: "Dinner before a vote is the worst meal of the day, because everybody's smiling and nobody means it.", v: { schemer: "I love dinner before a vote, because everybody's acting and you can see exactly who's bad at it.", quiet: "Nobody ate much tonight." } },
    ] },
    { id: 'ny.d3', place: 'eat', when: { voice: ['warm', 'earnest', 'emotional'] }, turns: [
      { by: 'a', say: "Can we go around and say one good thing that happened today?" },
      { by: 'b', say: "Seriously?" },
      { by: 'a', say: "Seriously, I'll go first. {c} found the good spot by the fire." },
      { by: 'c', say: "That's my good thing too, actually." },
      { by: 'b', say: "Fine. Mine is that this day is almost over." },
      { by: 'a', say: "That counts!" },
      { by: 'b', conf: "{a} made us do a sharing circle and I hated it, but I'm totally doing it again tomorrow." },
    ] },
  ],
  'long.crowd.chores.any': [
    { id: 'ny.c1', place: 'work', turns: [
      { beat: "Morning chores {here}. {a} has made a list." },
      { by: 'a', say: "Okay, {b}, you're on water, and {c}, you're with me.", v: { bossy: "Listen up. {b}, you're on water, {c}, you're with me, let's go.", warm: "Okay! {b}, would you mind doing water? And {c}, do you want to come with me?", loud: "Okay, team! {b}, you're on water, {c}, you're with me, let's go!" } },
      { by: 'c', move: 'pushback.lead' },
      { by: 'a', say: "Somebody has to be. Nobody else made a list." },
      { by: 'b', say: "That's fair, actually." },
      { by: 'c', say: "Fine. But I'm making tomorrow's list." },
      { by: 'c', conf: "Being in charge of chores is how people end up in charge of other things. I'm keeping an eye on {a}.", v: { schemer: "First it's the chores, then it's the votes. {a} knows exactly what {a} is doing.", dry: "{a} made a list. Next {a} will make a government." } },
      { by: 'a', conf: "I don't want to run the camp. I want the camp to have water. Those are different things." },
    ] },
    { id: 'ny.c2', place: 'work', turns: [
      { beat: "{a}, {b} and {c} are cleaning up {here}. It's going slowly." },
      { by: 'b', say: "Why are we always the ones doing this?", v: { dry: "Funny how it's always us. Must be our natural charm.", loud: "Why is it ALWAYS us?!", tough: "Whatever. Somebody's got to do it." } },
      { by: 'a', say: "Because we're the ones who notice it needs doing." },
      { by: 'c', say: "I'd love to stop noticing." },
      { by: 'a', say: "Then who'd do it?" },
      { by: 'c', say: "Somebody who isn't me." },
      { by: 'b', conf: "I do the chores because I'm scared of what people say about the ones who don't. I'm not proud of it, but my name stays out of their mouths.", v: { competitive: "Chores don't win. But lazy people go home first.", earnest: "I like doing my part. It's the right thing to do." } },
    ] },
    { id: 'ny.c3', place: 'work', when: { merged: true }, turns: [
      { by: 'b', say: "It's funny, everybody used to work so hard, but since the merge nobody wants to do anything.", v: { dry: "Remember when people used to help? Good times.", blunt: "Nobody works anymore. It's pathetic." } },
      { by: 'a', say: "Everybody's too busy plotting." },
      { by: 'c', say: "Some of us can plot and carry things at the same time." },
      { by: 'a', say: "Some of us are just plotting about who's carrying things." },
      { by: 'b', conf: "Doing chores at the merge is actually good strategy, because people remember who did the work, and so does the jury." },
    ] },
    { id: 'ny.c4', place: 'work', when: { voice: ['bossy', 'competitive', 'tough'] }, turns: [
      { by: 'a', say: "Faster, people. We're not on vacation." },
      { by: 'b', say: "We kind of are, though." },
      { by: 'a', say: "This is not a vacation. Vacations have beds." },
      { by: 'c', say: "Can you at least say please?" },
      { by: 'a', say: "Please go faster." },
      { by: 'c', conf: "{a} would run the whole camp like a boot camp if we let {a.obj}. We're not letting {a.obj}." },
    ] },
  ],
  'long.crowd.nerves.any': [
    { id: 'ny.n1', place: 'fire', turns: [
      { beat: "The team sits {here}, waiting to go to the vote. Nobody says much." },
      { by: 'b', say: "I hate this part.", v: { anxious: "I hate this part. I really, really hate this part.", dry: "Ah, the waiting. My favourite.", tough: "Let's just get it over with." } },
      { by: 'a', say: "The waiting?" },
      { by: 'b', say: "The waiting, and the not knowing, and the pretending we're all fine." },
      { by: 'c', say: "I'm fine." },
      { by: 'b', say: "You've been tapping your foot for ten minutes." },
      { by: 'c', say: "I'm fine with tapping." },
      { by: 'a', conf: "One of the people sitting at this fire is going home tonight. Everybody's looking at the fire so nobody has to look at each other.", v: { schemer: "Everybody's staring at the fire. I'm watching their hands.", emotional: "I just keep thinking, what if it's me? What if it's me?" } },
    ] },
    { id: 'ny.n2', place: 'aside', when: { voice: ['anxious', 'emotional', 'warm'] }, turns: [
      { by: 'a', say: "Does anyone else feel sick?" },
      { by: 'b', say: "Every time." },
      { by: 'a', say: "Like, actually sick. I think I'm going to throw up." },
      { by: 'c', say: "You're going to be okay." },
      { by: 'a', say: "You don't know that." },
      { by: 'c', say: "No. But I'm saying it anyway." },
      { by: 'a', conf: "Every single vote I think it's going to be me, and one of these times I'm going to be right." },
    ] },
    { id: 'ny.n3', place: 'fire', when: { voice: ['schemer', 'calm', 'dry', 'proud'] }, turns: [
      { by: 'b', say: "You look really relaxed for someone about to vote." },
      { by: 'a', say: "Should I look nervous?" },
      { by: 'c', say: "Everyone else does." },
      { by: 'a', say: "Then somebody has to look calm. Might as well be me." },
      { by: 'c', conf: "{a} looking that calm right before a vote either means {a} is safe, or {a} is about to do something. I don't like either one." },
    ] },
  ],
  'long.crowd.huddle.any': [
    { id: 'ny.h1', place: 'secret', turns: [
      { beat: "{group} meets one last time at {place} before the vote." },
      { by: 'a', say: "Okay, last check, is everybody good?", v: { bossy: "Last check, and nobody goes rogue tonight. Clear?", anxious: "Okay, last check, is everybody still good? Please just say yes.", calm: "Quick check before tonight. We good?" } },
      { by: 'b', say: "Good." },
      { by: 'c', say: "Good." },
      { by: 'a', say: "Same name, nobody goes off on their own, and nobody gets clever." },
      { by: 'c', say: "Why are you looking at me?" },
      { by: 'a', say: "I'm looking at everybody." },
      { by: 'b', say: "You're looking at {c} a little more." },
      { by: 'c', conf: "{group} thinks I might flip, and I wasn't going to, but now I'm actually thinking about it.", v: { loud: "They think I'd flip?! Wow. Now I kind of want to.", warm: "It really hurt that they doubted me. I'm staying loyal... I think." } },
    ] },
    { id: 'ny.h2', place: 'secret', when: { voice: ['warm', 'earnest', 'emotional'] }, turns: [
      { beat: "{group} sits in a circle at {place}." },
      { by: 'a', say: "Whatever happens tonight, we're still us. Okay?" },
      { by: 'b', say: "Okay." },
      { by: 'c', say: "Are we doing a hand thing?" },
      { by: 'a', say: "We're doing a hand thing." },
      { beat: "They stack their hands. Somebody laughs." },
      { by: 'b', conf: "{group} is the only part of this game that feels real. I really hope we all make it through tonight." },
    ] },
  ],
  'long.crowd.immune.any': [
    { id: 'ny.i1', place: 'public', turns: [
      { beat: "{a} walks back into camp wearing the immunity necklace." },
      { by: 'b', say: "Look at you!", v: { warm: "Oh my gosh, look at you! I'm so happy!", dry: "Well, well. Look who's untouchable.", teen: "Okay, look at you! That's so sick!" } },
      { by: 'a', say: "Look at me." },
      { by: 'c', say: "Don't get used to it." },
      { by: 'a', say: "I'm going to get extremely used to it." },
      { by: 'b', say: "Safe tonight. That must feel amazing." },
      { by: 'a', say: "It feels like I'm finally going to sleep tonight." },
      { by: 'c', conf: "So {a} won, fine, but that just means the rest of us have to work out which one of us goes instead, and that includes me.", v: { competitive: "{a} won again. I need to start winning or I need to start worrying.", anxious: "{a} is safe, which leaves the rest of us, which leaves me." } },
    ] },
    { id: 'ny.i2', place: 'public', when: { voice: ['loud', 'proud', 'competitive', 'theatrical'] }, turns: [
      { by: 'a', say: "Who's safe tonight? Me, that's who!" },
      { by: 'c', say: "We know. We were there." },
      { by: 'a', say: "I just want to make sure everybody heard." },
      { by: 'b', say: "Congratulations. Really." },
      { by: 'c', say: "Enjoy it. Next week you're the biggest target here." },
      { by: 'a', say: "Next week I'll win it again." },
      { by: 'c', conf: "{a} keeps winning and keeps rubbing it in. That's two good reasons to vote {a} out the second that necklace comes off." },
    ] },
  ],
  'long.crowd.clash.any': [
    { id: 'ny.x1', place: 'public', turns: [
      { beat: "It starts as an argument {here}. Then everybody is watching." },
      { by: 'a', say: "Go on, say it louder, everyone wants to hear it.", v: { cruel: "Go on, say it louder, let everybody hear what a coward you are.", loud: "SAY IT! Say it to my face!" } },
      { by: 'b', say: "Fine! You push people around, and everybody's too scared to tell you!" },
      { by: 'a', say: "I push people around? You've been talking about me all week!" },
      { by: 'c', say: "Okay, okay, stop it, both of you!" },
      { by: 'b', say: "Stay out of it, {c}." },
      { by: 'c', say: "I'd love to stay out of it! You're doing it in the middle of camp!" },
      { by: 'c', conf: "I didn't come here to be a referee. But if nobody steps in, one of them is going to end up in the water.", v: { tough: "Somebody had to stop it. I stopped it.", dry: "I'm a referee now, apparently. The pay is terrible." } },
    ] },
    { id: 'ny.x2', place: 'public', when: { voiceC: ['tough', 'bossy', 'loud'] }, turns: [
      { by: 'a', say: "You've been lying to everybody!", v: { cruel: "You're a liar and everybody knows it!", blunt: "You lie constantly, to everyone." } },
      { by: 'b', say: "Prove it!" },
      { by: 'a', say: "I don't need to prove it! Everyone knows!" },
      { by: 'c', say: "ENOUGH." },
      { beat: "Everyone goes quiet." },
      { by: 'c', say: "You two can hate each other all you want. Do it somewhere I can't hear it." },
      { by: 'c', conf: "Somebody had to shut it down, and everyone else just stood there, so I wasn't going to just stand there." },
    ] },
  ],
  'long.cross.rival.any': [
    { id: 'ny.r1', place: 'public', turns: [
      { beat: "The {mine} and the {theirs} end up {here} at the same time. {a} spots {b}." },
      { by: 'a', say: "Oh, look. The {theirs} are awake.", v: { cruel: "Oh, look. The losers are up.", dry: "The {theirs} are awake. Somebody alert the media.", loud: "HEY! The {theirs} finally woke up!" } },
      { by: 'b', say: "We've been awake for hours. We're just quieter about it than you." },
      { by: 'a', say: "Quieter. That's one word for losing." },
      { by: 'b', say: "We won the last one." },
      { by: 'a', say: "And you'll never let anybody forget it." },
      { by: 'b', conf: "{a} talks so much. Every time I see {a}, I want to beat the {mine} even more.", v: { competitive: "I'm going to beat {a} in every challenge. Every single one.", calm: "{a} can talk. We'll see what happens at the challenge." } },
    ] },
    { id: 'ny.r2', place: 'public', when: { voice: ['loud', 'tough', 'competitive'] }, turns: [
      { by: 'a', say: "Hey, {b}! Enjoy your last few days." },
      { by: 'b', say: "Excuse me?" },
      { by: 'a', say: "The {theirs} are falling apart. Everybody can see it." },
      { by: 'b', say: "Worry about the {mine}." },
      { by: 'a', say: "The {mine} are fine." },
      { by: 'b', say: "That's what everybody says right before they lose." },
      { by: 'a', conf: "I don't hate {b}, I just really, really want to beat {b}, every single time." },
    ] },
  ],
  'long.cross.friend.any': [
    { id: 'ny.f1', place: 'public', turns: [
      { beat: "{a} and {b} sit together {here}. Their teams are both watching." },
      { by: 'b', say: "My team thinks I'm spying on you.", v: { anxious: "My team keeps asking if I'm spying on you, and I'm not... am I?", dry: "Apparently I'm a spy now. Nobody told me." } },
      { by: 'a', say: "Mine thinks I'm spying on you." },
      { by: 'b', say: "Are you?" },
      { by: 'a', say: "Not even a little. You?" },
      { by: 'b', say: "No. I just like talking to you." },
      { by: 'a', say: "Same." },
      { by: 'a', conf: "{b} is on the {theirs}. I don't care. When the teams are gone, I want {b} next to me.", v: { schemer: "{b} on the other team is useful. {b} at the merge is even more useful.", warm: "{b} is my friend. Teams don't change that." } },
    ] },
    { id: 'ny.f2', place: 'aside', when: { voice: ['warm', 'earnest', 'ditzy', 'goofy'] }, turns: [
      { by: 'a', say: "I saved you some of our food. Don't tell my team." },
      { by: 'b', say: "Are you serious? Our food is so bad right now." },
      { by: 'a', say: "Ours is also bad. Just a different bad." },
      { by: 'b', say: "I'll take a different bad." },
      { by: 'b', conf: "{a} keeps being nice to me even though we're on different teams. I really hope we don't end up voting against each other." },
    ] },
  ],
  'long.cross.spy.leak': [
    { id: 'ny.s1', place: 'public', turns: [
      { by: 'a', say: "So who's in trouble on your side? You can tell me. I can't vote for anyone on your team.", v: { schemer: "So, just curious, who's on the outs over there? I can't vote for any of them.", warm: "Is everybody okay on your side? Like, is anybody in trouble?" } },
      { by: 'b', say: "Ha. Nice try." },
      { by: 'a', say: "Come on. I'm just curious." },
      { by: 'b', say: "Fine. Let's just say some of the {theirs} aren't as close as they look." },
      { by: 'a', say: "Interesting." },
      { by: 'b', say: "Don't tell anybody I said that." },
      { by: 'a', say: "Who would I tell?" },
      { by: 'a', conf: "{b} just told me the {theirs} are cracking. That's going to be very useful at the merge." },
    ] },
  ],
  'long.cross.spy.shut': [
    { id: 'ny.s2', place: 'public', turns: [
      { by: 'a', say: "So, how are things on your side? Everyone getting along?", v: { dry: "So, how's the happy family on your side?", competitive: "So how's your team holding up? Not well, I hope." } },
      { by: 'b', say: "We're great, we're all best friends. Why do you ask?" },
      { by: 'a', say: "No reason." },
      { by: 'b', say: "Mm-hm. Tell the {mine} I said nice try." },
      { by: 'a', say: "Tell them yourself." },
      { by: 'b', conf: "{a} came over here looking for gossip. I'm not giving the {mine} anything." },
    ] },
  ],

  'long.friend.bond.any': [
    { id: 'ny.b1', place: 'water', turns: [
      { beat: "{a} and {b} are supposed to be fishing {here}. Neither of them has caught anything." },
      { by: 'b', say: "We're really bad at this.", v: { dry: "We are spectacularly bad at this.", goofy: "I think the fish are laughing at us.", teen: "We're so bad at this, oh my god." } },
      { by: 'a', say: "We're amazing at this. The fish are just bad at being caught." },
      { by: 'b', say: "That's not how fishing works." },
      { by: 'a', say: "Have you ever been fishing before?" },
      { by: 'b', say: "...No." },
      { by: 'a', say: "Me neither." },
      { by: 'b', conf: "We caught nothing. I spent two hours with {a}, and it was the best two hours I've had here.", v: { tough: "No fish, but good company, so that's a fair trade.", emotional: "I didn't expect to have that much fun. I'm going to remember it." } },
    ] },
    { id: 'ny.b2', place: 'work', turns: [
      { beat: "{a} and {b} are carrying firewood {here}." },
      { by: 'a', say: "So what do you do back home?", v: { warm: "Tell me about home! What do you do?", nerdy: "So what's your actual job? Back in the real world?", teen: "So what do you do back home? Like, school or...?" } },
      { by: 'b', say: "Not this." },
      { by: 'a', say: "Same. Definitely not this." },
      { by: 'b', say: "What made you sign up?" },
      { by: 'a', say: "Honestly? I just wanted to see if I could. What about you?" },
      { by: 'b', say: "Same, kind of. And the money." },
      { by: 'a', say: "Obviously the money." },
      { by: 'a', conf: "{b} is really easy to be around, which is rare here, so I'm going to try to keep {b} close.", v: { schemer: "{b} trusts me already. That's very useful.", grown: "{b} reminds me of people I used to work with. The good ones." } },
    ] },
    { id: 'ny.b3', place: 'fire', when: { voice: ['tough', 'blunt', 'competitive', 'loud'] }, turns: [
      { by: 'b', say: "You were really good today." },
      { by: 'a', say: "Thanks. You weren't bad either." },
      { by: 'b', say: "Wow. From you, that's basically a hug." },
      { by: 'a', say: "Don't push it." },
      { by: 'b', say: "Too late. We're friends now." },
      { by: 'a', say: "...Fine. We're friends now." },
      { by: 'b', conf: "{a} acts tough with everyone. Once you get past that, {a} is actually really loyal." },
    ] },
    { id: 'ny.b4', place: 'aside', when: { voice: ['nerdy', 'anxious', 'earnest'] }, turns: [
      { by: 'a', say: "Can I tell you something embarrassing? I don't really know how to make friends." },
      { by: 'b', say: "You're doing it right now." },
      { by: 'a', say: "Am I?" },
      { by: 'b', say: "Well, you talked to me and I talked back, so that's pretty much how it works." },
      { by: 'a', say: "Huh. That's a lot simpler than I thought." },
      { by: 'a', conf: "I think I have a friend here. An actual friend. I want to write it down so I don't forget." },
    ] },
  ],
  'long.friend.goof.any': [
    { id: 'ny.g1', place: 'public', turns: [
      { beat: "{a} has decided to teach {b} a dance {here}. {b} keeps stepping on {a}'s feet." },
      { by: 'a', say: "No, left foot... your other left.", v: { loud: "LEFT! Your OTHER left!", bossy: "No, left foot. Watch me, and do it again." } },
      { by: 'b', say: "I don't have another left!" },
      { by: 'a', say: "Everyone has two lefts. One of them is your right." },
      { by: 'b', say: "That doesn't make any sense!" },
      { beat: "{b} falls over. {a} falls over laughing." },
      { by: 'b', conf: "I can't dance and {a} can't teach, but we did it for an hour, and I'd do it again tomorrow.", v: { dry: "Neither of us can dance, but we committed anyway, and that's friendship.", teen: "We did that for an hour and we're both so bad at it, but that was the best hour ever." } },
    ] },
    { id: 'ny.g2', place: 'sleep', turns: [
      { beat: "Late in the {quarters}. {a} can't stop laughing at something." },
      { by: 'b', say: "What? What is it?", v: { anxious: "What? Is something wrong? What is it?", goofy: "What? What's so funny? Tell me, I want to laugh too!" } },
      { by: 'a', say: "I just remembered your face in the challenge, when that thing fell on you." },
      { by: 'b', say: "That wasn't funny!" },
      { by: 'a', say: "It was really funny." },
      { by: 'b', say: "...Okay. It was a little funny." },
      { beat: "Somebody in the dark tells them both to shut up." },
      { by: 'a', conf: "We got told off for laughing at two in the morning. Best night yet." },
    ] },
  ],
  'long.friend.comfort.any': [
    { id: 'ny.co1', place: 'aside', turns: [
      { beat: "{b} is sitting alone {here}. {a} sits down next to {b.obj}." },
      { by: 'a', say: "Hey. You okay?", v: { warm: "Hey, hey, come here. Are you okay?", blunt: "You okay? You don't look okay.", quiet: "...You okay?" } },
      { by: 'b', say: "I'm fine." },
      { by: 'a', say: "You've been sitting here for an hour." },
      { by: 'b', say: "...I just miss home, that's all. It's stupid." },
      { by: 'a', say: "It's not stupid. I miss home too, every single day." },
      { by: 'b', say: "You do?" },
      { by: 'a', say: "Every single day. We just don't say it." },
      { by: 'b', conf: "I didn't want anyone to see me like that. I'm glad it was {a}.", v: { proud: "Nobody sees me cry. Except {a}, apparently.", emotional: "I needed that so much. {a} is a good person." } },
    ] },
    { id: 'ny.co2', place: 'sleep', when: { voice: ['tough', 'blunt', 'competitive'] }, turns: [
      { by: 'a', say: "Stop crying. Not because crying is bad, just because you'll get dehydrated." },
      { by: 'b', say: "That's the worst comfort I've ever heard." },
      { by: 'a', say: "I'm not good at this stuff. Here, have some water." },
      { by: 'b', say: "...Thanks." },
      { by: 'a', say: "You're going to be fine. You're tougher than half the people here." },
      { by: 'b', conf: "{a} is terrible at being nice, but {a} tried anyway, and that counts." },
    ] },
  ],
  'long.friend.open.any': [
    { id: 'ny.o1', place: 'water', turns: [
      { beat: "{a} and {b} are sitting {here} with their feet in the water." },
      { by: 'a', say: "Can I tell you something I haven't told anybody?" },
      { by: 'b', say: "Sure." },
      { by: 'a', say: "I almost didn't come. I was so scared people wouldn't like me." },
      { by: 'b', say: "People like you." },
      { by: 'a', say: "Some people." },
      { by: 'b', say: "I like you. That's one." },
      { by: 'a', conf: "I don't know why I told {b} that. I just felt like I could. That doesn't happen to me much.", v: { quiet: "I don't usually talk. I talked to {b}.", tough: "I don't open up to people, and I just opened up, so don't make it a thing." } },
    ] },
  ],
  'long.friend.rideordie.any': [
    { id: 'ny.rd1', place: 'secret', turns: [
      { by: 'a', say: "Promise me something.", v: { warm: "Can you promise me something? A big something?", blunt: "I need you to promise me something." } },
      { by: 'b', say: "Depends what it is." },
      { by: 'a', say: "If it ever comes down to you or me, we tell each other first. Before anybody else." },
      { by: 'b', say: "And then what?" },
      { by: 'a', say: "And then we figure it out together, like we've done everything else." },
      { by: 'b', say: "...Okay. I promise." },
      { by: 'b', conf: "Everybody here has a deal with somebody. {a} and I don't need a deal.", v: { schemer: "Everybody has deals. Ours is the only one I actually believe in.", teen: "Everybody has these fake deals. We're just actually friends." } },
    ] },
    { id: 'ny.rd2', place: 'aside', when: { merged: true }, turns: [
      { by: 'b', say: "We've made it this far.", v: { emotional: "We actually made it this far. Together.", competitive: "This far. Now we go all the way." } },
      { by: 'a', say: "Together. Every vote." },
      { by: 'b', say: "People are going to start coming for us now." },
      { by: 'a', say: "Let them. They have to get through both of us." },
      { by: 'b', say: "And if they split us?" },
      { by: 'a', say: "Then whoever's left wins it for both of us." },
      { by: 'a', conf: "{b} is the only person here I'd trust with my vote without asking. That's either really smart or really dumb." },
    ] },
    { id: 'ny.rd3', place: 'fire', when: { voice: ['loud', 'tough', 'blunt'] }, turns: [
      { by: 'a', say: "Anybody comes for you, they come through me." },
      { by: 'b', say: "That's very dramatic." },
      { by: 'a', say: "I mean it." },
      { by: 'b', say: "I know you do. Same goes for you." },
      { by: 'b', conf: "I'm pretty sure {a} would fight a bear for me, but I'd really prefer it didn't come to that." },
    ] },
  ],
  'long.friend.drift.any': [
    { id: 'ny.dr1', place: 'aside', turns: [
      { by: 'b', say: "Hey. Haven't seen you much lately.", v: { warm: "Hey, you. I miss you, where have you been?", dry: "Oh, hi. I almost forgot what you look like." } },
      { by: 'a', say: "Yeah. Been busy." },
      { by: 'b', say: "With who?" },
      { by: 'a', say: "Just... around." },
      { by: 'b', say: "Okay." },
      { beat: "{a} leaves. {b} watches {a.obj} go." },
      { by: 'b', conf: "{a} and I used to talk every day. Now I get 'been busy'. I know what busy means here.", v: { emotional: "{a} is pulling away from me, I can feel it, and it really hurts.", schemer: "'Been busy.' Busy with who? I'll find out." } },
    ] },
    { id: 'ny.dr2', place: 'public', when: { voice: ['schemer', 'calm', 'competitive', 'dry'] }, turns: [
      { by: 'b', say: "Want to sit with me?" },
      { by: 'a', say: "Maybe later." },
      { by: 'b', conf: "Maybe later. That's the third maybe later today." },
      { by: 'a', conf: "{b} is a good friend. {b} is also on the wrong side right now. I need a little distance." },
    ] },
  ],
  'long.friend.laugh.any': [
    { id: 'ny.l1', place: 'fire', turns: [
      { beat: "{a} is doing impressions {here}. It's going very well." },
      { by: 'a', say: "Okay, who's this? \"Campers! Today's challenge is EXTREMELY dangerous!\"" },
      { by: 'b', say: "Oh my god. That's {host}." },
      { by: 'c', say: "Do it again. Do the hair thing." },
      { by: 'a', say: "I'm not doing the hair thing." },
      { by: 'c', say: "Do the hair thing!" },
      { beat: "{a} does the hair thing. Everyone loses it." },
      { by: 'c', conf: "I laughed so hard tonight my stomach hurt. I forgot I was in a game for about ten whole minutes, and that's all {a}.", v: { warm: "That was the best night. Everybody laughing together.", schemer: "Being funny makes people like you, and {a} knows that. It's smart." } },
    ] },
    { id: 'ny.l2', place: 'eat', turns: [
      { beat: "{a} is telling a story at dinner. It starts normal. It does not end normal." },
      { by: 'b', say: "Wait, wait. And then what?", v: { loud: "WAIT. And THEN what?!", teen: "No way. Wait, then what happened?" } },
      { by: 'a', say: "And then it all went in the lake, with me still holding it." },
      { by: 'c', say: "Stop. I can't breathe." },
      { by: 'a', say: "I'm not even done!" },
      { by: 'b', conf: "{a} could make anything funny. I needed that today." },
    ] },
  ],
  'long.friend.joke.any': [
    { id: 'ny.j1', place: 'public', turns: [
      { by: 'a', say: "Good morning, your majesty." },
      { by: 'b', say: "Good morning, peasant." },
      { by: 'a', say: "How did your majesty sleep?" },
      { by: 'b', say: "On a rock. As usual." },
      { by: 'c', say: "Are you two ever going to explain this?" },
      { by: 'a', say: "No." },
      { by: 'b', say: "Never." },
      { by: 'a', conf: "It started on day two and I don't even remember why, but now we can't stop." },
    ] },
  ],
  'long.friend.sunrise.any': [
    { id: 'ny.su1', place: 'water', turns: [
      { beat: "Early. Everyone else is asleep. {a} and {b} are the only ones up, sitting {here}." },
      { by: 'b', say: "You're up early.", v: { dry: "You're up early. Or late, it's hard to tell.", warm: "Morning! Couldn't sleep either?", quiet: "Early." } },
      { by: 'a', say: "Couldn't sleep. You?" },
      { by: 'b', say: "Same. Too much in my head." },
      { by: 'a', say: "About the game?" },
      { by: 'b', say: "About everything." },
      { beat: "They watch the light come up for a while." },
      { by: 'a', conf: "That's the only quiet half hour I get here. Spending it with {b} feels right.", v: { grown: "Early mornings are when I think best. {b} gets that.", teen: "Sunrise with {b} is honestly the best part of being here." } },
    ] },
  ],
  'long.friend.thanks.any': [
    { id: 'ny.t1', place: 'aside', turns: [
      { by: 'a', say: "Hey. I never said thank you.", v: { warm: "Hey, I just wanted to say thank you. Really.", proud: "I don't say this often. Thank you.", quiet: "Hey... thanks. For before." } },
      { by: 'b', say: "For what?" },
      { by: 'a', say: "For yesterday. You didn't have to help me, and you did." },
      { by: 'b', say: "It was nothing." },
      { by: 'a', say: "It wasn't nothing to me." },
      { by: 'b', conf: "I barely remember doing it, but {a} remembers, and people here always remember who helped them." },
    ] },
  ],
  'long.friend.struggle.any': [
    { id: 'ny.st1', place: 'work', turns: [
      { beat: "{a} and {b} are the last two still working {here}. Both are exhausted." },
      { by: 'b', say: "I can't feel my arms.", v: { dry: "My arms have filed a complaint.", loud: "I can't feel my ARMS!", grown: "These arms are not what they used to be." } },
      { by: 'a', say: "I can't feel anything." },
      { by: 'b', say: "Why are we still doing this?" },
      { by: 'a', say: "Because if we stop, it doesn't get done." },
      { by: 'b', say: "Okay, five more minutes and then we collapse." },
      { by: 'a', move: 'agree' },
      { by: 'a', conf: "{b} and I don't really get along, but nobody else stayed to finish, and that counts for something.", v: { blunt: "I don't like {b}, but {b} stayed, so respect." } },
    ] },
    { id: 'ny.st2', place: 'aside', when: { band: ['cold', 'enemies'] }, turns: [
      { by: 'a', say: "Of all the people to get stuck with.", v: { cruel: "Great. Of course it's you.", dry: "Ah. The universe has a sense of humour." } },
      { by: 'b', say: "Trust me, I feel the same." },
      { by: 'a', say: "Let's just get it done. No talking." },
      { by: 'b', say: "Fine. No talking." },
      { beat: "Twenty minutes later, they're both talking. And laughing, a little." },
      { by: 'b', conf: "I still don't like {a}. I just hate {a} a little bit less now." },
    ] },
  ],
  'long.friend.lift.any': [
    { id: 'ny.lf1', place: 'public', turns: [
      { beat: "The mood {here} is terrible. {a} decides that's not acceptable." },
      { by: 'a', say: "Okay, everybody up. We're doing something fun.", v: { loud: "Everybody up! It's fun time, right now!", goofy: "Attention, everybody! Mandatory fun, report to the middle of camp!", warm: "Hey, everybody, come on. Let's do something fun together." } },
      { by: 'b', say: "There's nothing fun here." },
      { by: 'a', say: "Then we'll make something fun. Contest, best impression of {host}, go." },
      { by: 'c', say: "...Fine. But I'm going first." },
      { beat: "Ten minutes later, the whole camp is laughing." },
      { by: 'b', conf: "One minute we're all miserable. Then {a} opens {a.posAdj} mouth and everyone's okay again." },
    ] },
  ],
  'long.friend.rally.any': [
    { id: 'ny.ra1', place: 'fire', turns: [
      { by: 'a', say: "Can I say something? Everyone's walking around like we've already lost.", v: { competitive: "Stop moping, we're not done, not even close.", warm: "Hey, I know it's hard, but I really believe in us." } },
      { by: 'b', say: "We kind of have been losing." },
      { by: 'a', say: "One bad day. I've watched every person here do something amazing." },
      { by: 'c', say: "Even me?" },
      { by: 'a', say: "Even you, yesterday. Don't make me list it." },
      { by: 'b', say: "...Okay, fine. One bad day." },
      { by: 'c', conf: "That speech was so cheesy, but it worked, and I hate it when cheesy works." },
    ] },
  ],
  'long.friend.solidarity.any': [
    { id: 'ny.so1', place: 'public', turns: [
      { beat: "People are talking about {b} {here}. {a} walks over and sits right next to {b}." },
      { by: 'b', say: "You don't have to sit here." },
      { by: 'a', say: "I know." },
      { by: 'b', say: "People are going to think you're with me." },
      { by: 'a', say: "Let them." },
      { by: 'b', conf: "When {a} sat down next to me, I almost cried. {a} didn't say a word, and I didn't need {a.obj} to.", v: {"tough":"{a} sat with me. That's all. It meant more than I'm going to admit on camera."} },
    ] },
  ],
  'long.friend.mentor.any': [
    { id: 'ny.mt1', place: 'aside', turns: [
      { by: 'b', say: "I'm going home. I know I'm going home.", v: { emotional: "It's me, I just know it's me, I'm going home.", dry: "Well, somebody pack my bags, because I'm done." } },
      { by: 'a', say: "Hey, hey, breathe. Look at me." },
      { by: 'b', say: "I can't..." },
      { by: 'a', say: "Yes, you can. Breathe in... and out... and again." },
      { by: 'a', say: "Now tell me who you've actually talked to today. Not who you're scared of. Who you've talked to." },
      { by: 'b', say: "...Four people." },
      { by: 'a', say: "Four is a lot more than nobody. Go talk to two more before dinner." },
      { by: 'b', conf: "I was ready to give up, but {a} talked me down, and now I have a plan. It's a small one, but it's a plan.", v: { teen: "{a} totally saved me. I was freaking out so bad.", grown: "I don't panic easily, but I panicked, and {a} brought me back." } },
    ] },
  ],
  'long.friend.teach.any': [
    { id: 'ny.te1', place: 'work', turns: [
      { beat: "{a} is showing {b} how to tie a knot {here}." },
      { by: 'a', say: "Over, under, through. Pull.", v: { bossy: "Over, under, through, and pull. Now again.", warm: "Okay, it's easy. Over, under, through, and pull. You've got it." } },
      { by: 'b', say: "That's what I did." },
      { by: 'a', say: "You did over, over, through, and then you gave up." },
      { by: 'b', say: "I didn't give up! I took a break!" },
      { by: 'a', say: "Again. Slower." },
      { beat: "This time it holds." },
      { by: 'b', conf: "I learned a knot. In a challenge, that knot could save my life. Or at least save me from a vote." },
    ] },
  ],
  'long.life.surprise.any': [
    { id: 'ny.ls1', place: 'work', turns: [
      { beat: "{a} has just done something {here} that nobody thought {a} could do." },
      { by: 'b', say: "Wait. Since when can you do that?", v: { loud: "WAIT. You can do THAT?!", dry: "Oh, so you've been hiding talents. Good to know.", teen: "Wait, since when can you do that?!" } },
      { by: 'a', say: "Since always? Nobody asked." },
      { by: 'b', say: "You could have said something! We've been struggling for days!" },
      { by: 'a', say: "You didn't ask me anything for days." },
      { by: 'b', conf: "I had {a} down as dead weight, so I'm going to have to rethink that, and so is everybody else.", v: { schemer: "{a} just got a lot more dangerous. And a lot more useful.", warm: "I'm so happy for {a}, because everybody underestimated {a}, me included." } },
    ] },
  ],
  'long.hosted.raid.fun': [
    { id: 'ny.hr1', place: 'sleep', when: { venue: 'hosted-camp' }, turns: [
      { beat: "After lights-out. {a} shakes {b} awake in the {quarters}." },
      { by: 'a', say: "Psst. Kitchen run, right now.", v: { chaotic: "Psst, wake up, we're doing a crime! A small one!", goofy: "Psst. I'm going on a snack mission, are you in?" } },
      { by: 'b', say: "Are you crazy? Chef will kill us." },
      { by: 'a', say: "Chef's asleep, I checked. Come on." },
      { beat: "Ten minutes later they're back, out of breath, holding a jar of something." },
      { by: 'b', say: "What even is this?" },
      { by: 'a', say: "No idea. But it's ours." },
      { by: 'b', conf: "We stole a jar of mystery food from Chef in the middle of the night. Best night here so far." },
    ] },
  ],

  'story.cover.votes': [
    Q('nq.v1', null, ["My name came up at the last vote. Not enough to send me home. But somebody wrote it.", "If they thought about it once, they'll think about it again. I need to give them another name first."]),
    Q('nq.v2', { voice: ['loud', 'tough', 'blunt'] }, ["People wrote my name down. Cool, great. I'd love to know who, so I can thank them to their face."]),
    Q('nq.v3', { voice: ['warm', 'anxious', 'emotional', 'earnest'] }, ["I keep trying to work out who voted for me, but everybody's being so nice, which is almost worse."]),
    Q('nq.v4', { voice: ['schemer', 'calm', 'dry'] }, ["I got votes last time, which is fine, because now I know who's scared of me."]),
    Q('nq.v5', { voice: ['competitive', 'proud'] }, ["There were votes for me last time. I'm not going to cry about it. I'm going to win something so they can't do it again."]),
    Q('nq.v6', { tribal: true, phase: 'post' }, ["I had votes last time, and we lost again today. If I don't find a new name for people to write tonight, it's going to be mine."]),
    Q('nq.v7', { lastBoot: true }, ["{lastBoot} went home and I didn't. By a couple of votes.", "I don't feel lucky. I feel like the next person in line."]),
  ],
  'story.cover.allied': [
    Q('nq.a1', null, ["I've got people. I think. You never really know until the votes come out."]),
    Q('nq.a2', { voice: ['schemer', 'calm', 'cruel'] }, ["My alliance thinks I'm the loyal one, and I am... for now."]),
    Q('nq.a3', { voice: ['warm', 'anxious', 'earnest'] }, ["Being in an alliance is nice. I just hope I'm as important to them as they are to me."]),
    Q('nq.a4', { voice: ['loud', 'tough', 'blunt'] }, ["If anybody in my alliance even thinks about flipping, they're going to hear about it. Loudly."]),
    Q('nq.a5', { voice: ['competitive', 'proud', 'bossy'] }, ["We've got the numbers right now, but just right now, so I don't want anybody getting comfortable."]),
    Q('nq.a6', { merged: true }, ["The merge changes everything. My alliance looked strong on our old team. Here it's just one group out of a lot of groups."]),
    Q('nq.a7', { tribal: true, phase: 'post' }, ["My people say I'm safe tonight. I believe them. I'm still going to talk to everybody else, just in case."]),
  ],
  'story.cover.thread': [
    Q('nq.t1', null, ["There's a lot going on here. I'm in the middle of some of it and I'm trying to stay out of the rest."]),
    Q('nq.t2', { voice: ['loud', 'chaotic', 'theatrical'] }, ["Everybody here thinks I'm the problem. Fine, at least I'm interesting."]),
    Q('nq.t3', { voice: ['warm', 'emotional', 'earnest'] }, ["I didn't think I'd care this much. About the people, I mean. I thought it'd just be a game."]),
    Q('nq.t4', { voice: ['schemer', 'calm', 'dry'] }, ["Everybody's so busy with their own drama, they've stopped watching me. That's exactly how I like it."]),
    Q('nq.t5', { voice: ['competitive', 'tough', 'blunt'] }, ["I didn't come here to make friends or enemies. Somehow I've got both."]),
    Q('nq.t6', { voice: ['goofy', 'ditzy', 'food'] }, ["I don't totally know what's going on with everybody. I know what's going on with me. I'm hungry."]),
  ],
  'story.cover.quiet': [
    Q('nq.q1', null, ["Nobody's really said my name yet, which I think is good? I'm going to go with good."]),
    Q('nq.q2', { voice: ['schemer', 'calm', 'dry'] }, ["I haven't been in one single fight, and people think that means I'm not playing, but I'm playing."]),
    Q('nq.q3', { voice: ['warm', 'anxious', 'earnest'] }, ["I don't know if people forget I'm here or if they're just being nice. Either way, I'm still here."]),
    Q('nq.q4', { voice: ['loud', 'chaotic', 'tough'] }, ["I've been really calm so far, like really calm, so don't get used to it."]),
    Q('nq.q5', { voice: ['competitive', 'blunt', 'proud'] }, ["I keep my head down, I do the chores, I show up for the challenges. I don't need to be the main character every day."]),
    Q('nq.q6', { phase: 'post', tribal: true }, ["Tonight's going to be bad for somebody. I'm trying to make sure it isn't me without making it obvious that's what I'm doing."]),
    Q('nq.q7', { phase: 'post', tribal: false }, ["No vote for us tonight, so I'm going to sleep so well. On a rock, but well."]),
    Q('nq.q8', { early: true }, ["It's still early. I'm figuring out who talks too much and who doesn't talk enough. I'll move when I know."]),
    Q('nq.q9', { merged: true }, ["Everybody's talking about the big players. Nobody's talking about me. Let's keep it that way a little longer."]),
    Q('nq.q10', { voice: ['goofy', 'ditzy', 'food'] }, ["I've mostly been eating and napping, and people think I'm not trying, but I'm trying really hard to nap."]),
  ],
};
