// ══════════════════════════════════════════════════════════════════════
// td/story/lines/n-chal.js — back at camp after a team challenge
// ══════════════════════════════════════════════════════════════════════
//
// director.js afterChallenge(). lost: a goes after b = {sank} (the team's lowest score);
// c = b's closest teammate. {carried} only with the 'carried' fact; {streak} = losses in a row
// ('streak': one | two | many). won: a = {carried}; b = a's closest; c = {sank} when not a or b.
// Nobody says what the challenge was: the challenge screen showed it.

export default {
  'story.chal.lost': [
    { id: 'nc.l1', place: 'public', turns: [
      { beat: "The {tribe} get back {here}. {a} throws {a.posAdj} stuff down." },
      { by: 'a', say: "Well, that was embarrassing.", v: { loud: "That was a JOKE. We got destroyed!", dry: "Great job, everybody, really, that was inspiring stuff." } },
      { by: 'b', say: "Don't look at me." },
      { by: 'a', say: "Who else am I supposed to look at? You were the slowest one out there by a mile.",
        v: { cruel: "I'm looking at you because you were the problem. You know you were the problem.", warm: "I'm not trying to blame you. But you did kind of fall apart out there." } },
      { by: 'b', say: "Oh, so it's all my fault. Nobody else messed up.", v: { anxious: "I know, I know, okay? I'm sorry.", tough: "Say that again. I dare you." } },
      { by: 'a', say: "Nobody else messed up like that." },
      { by: 'c', say: "Okay, stop, we lost, all of us." },
      { by: 'a', conf: "I'm not going to pretend we lost as a team. We lost because of {b}, and everybody saw it." },
      { by: 'b', conf: "If {a} wants me gone, {a} is going to have to work for it. I'm not going quietly." },
    ] },
    { id: 'nc.l2', place: 'aside', when: { voiceB: ['anxious', 'warm', 'emotional', 'earnest'] }, turns: [
      { beat: "Back at camp. {b} is sitting {here} away from the rest of the {tribe}." },
      { by: 'c', say: "Hey. You okay?" },
      { by: 'b', say: "I'm the reason we lost, you can say it, everybody's thinking it." },
      { by: 'c', say: "That's not true." },
      { by: 'a', say: "It's a little true." },
      { by: 'c', say: "{a}!" },
      { by: 'a', say: "What? I'm not trying to be mean, {b} froze, and we all saw it.", v: { cruel: "What? Somebody has to say it, so it might as well be me." } },
      { by: 'b', say: "I know, I'm sorry, I really tried." },
      { beat: "{b} gets up and walks off. {c} glares at {a}." },
      { by: 'c', say: "Nice. Really nice." },
      { by: 'a', conf: "Do I feel bad? A little. But I'm not going home because I was too nice to say what happened." },
      { by: 'b', conf: "I wanted to show everyone I could do this. Today I showed them I can't." },
    ] },
    { id: 'nc.l3', place: 'public', when: { voiceB: ['dry', 'schemer', 'calm', 'cruel'] }, turns: [
      { by: 'a', say: "So are we going to talk about it, or are we just going to pretend it didn't happen?" },
      { by: 'b', say: "Talk about what?" },
      { by: 'a', say: "About you. Dead last on our team." },
      { by: 'b', say: "I wasn't the one screaming at everyone the whole time. That really helped.", v: { dry: "Sure, and let's also talk about your screaming, because that was really helpful." } },
      { by: 'a', say: "Somebody had to give directions." },
      { by: 'b', say: "Oh, is that what that was?" },
      { by: 'c', say: "Can we figure out who's going home without doing this?" },
      { by: 'b', say: "We are figuring it out. {a}'s just doing it out loud." },
      { by: 'b', conf: "Okay, I had a bad challenge. But I'm not the one who made half the team hate them on the walk back. Let's see who people actually want gone." },
    ] },
    { id: 'nc.l4', place: 'public', when: { voiceB: ['competitive', 'blunt', 'tough', 'bossy'] }, turns: [
      { beat: "The {tribe} drag themselves back to camp. {b} is the last one in." },
      { by: 'b', say: "Go ahead. Say it." },
      { by: 'a', say: "I didn't say anything." },
      { by: 'b', say: "You're thinking it so loud I can hear it." },
      { by: 'a', say: "Fine. You cost us that one." },
      { by: 'b', say: "Yeah, I know, I've been beating myself up the whole walk back, so get in line." },
      { by: 'a', say: "Feeling bad doesn't win us the next one." },
      { by: 'b', say: "So what do you want, an apology? Sorry, I'll be better tomorrow." },
      { by: 'a', conf: "I'll give {b} this, {b} owned it. I still don't know if I want {b} on my team for the next one." },
    ] },
    { id: 'nc.l5', place: 'public', when: { carried: true }, turns: [
      { by: 'a', say: "Can I say what everyone's thinking? We lost that because of {b}." },
      { by: 'b', say: "Wow. Thanks." },
      { by: 'a', say: "{carried} basically carried us and we still lost. That tells you something." },
      { by: 'c', say: "It tells me we've got one {carried} and a lot of everybody else. That's not all on {b}." },
      { by: 'a', say: "It's mostly on {b}." },
      { by: 'b', say: "Then write my name down and stop talking about it." },
      { by: 'a', say: "Maybe I will." },
      { by: 'c', conf: "{a} needs somebody to blame so nobody looks at {a}. It's so obvious." },
      { by: 'b', conf: "Everyone's acting like {carried} won it alone and I lost it alone. That's not how a team works. I don't think they care." },
    ] },
    { id: 'nc.l6', place: 'public', when: { streak: 'two' }, turns: [
      { beat: "Camp. Nobody says anything for a while." },
      { by: 'a', say: "Two in a row. Two." },
      { by: 'c', say: "We know, {a}." },
      { by: 'a', say: "Do we? Because I don't think everybody's taking this seriously." },
      { by: 'b', say: "Is that about me?" },
      { by: 'a', say: "You were last today. You tell me." },
      { by: 'b', say: "Last time it was somebody else, and they're gone now. Did that fix anything?" },
      { by: 'a', say: "It's a start." },
      { by: 'b', conf: "Two losses and everyone's looking for someone to vote out. I just need to make sure it isn't me." },
    ] },
    { id: 'nc.l7', place: 'public', when: { streak: 'many' }, turns: [
      { by: 'c', say: "That's {streak} in a row. {streak}." },
      { by: 'a', say: "Thanks, we can count." },
      { by: 'c', say: "I'm just saying something has to change." },
      { by: 'a', say: "Yeah. We need to stop dragging people along." },
      { by: 'b', say: "Here we go." },
      { by: 'a', say: "I'm not wrong, {b}. You were behind every single one of us again." },
      { by: 'b', say: "Everybody was behind somebody! That's what losing is!" },
      { by: 'c', conf: "The other team keeps winning, and we keep voting each other out. Great plan." },
      { by: 'b', conf: "We've lost {streak} in a row and somehow I'm the one everybody's blaming." },
    ] },
    { id: 'nc.l8', place: 'aside', when: { voice: ['schemer', 'calm'] }, turns: [
      { beat: "{a} waits until the others go off to clean up, then sits down next to {c}." },
      { by: 'a', say: "Rough one today." },
      { by: 'c', say: "Yeah." },
      { by: 'a', say: "I'm not going to say anything mean about {b}. {b} tried." },
      { by: 'c', say: "Thanks. I don't think {b} deserves to go home over one bad challenge." },
      { by: 'a', say: "Totally, it's just that we can't really afford many more of those, you know?" },
      { by: 'c', say: "...Yeah. I guess." },
      { by: 'a', say: "Just think about it." },
      { by: 'a', conf: "You don't tell people who to vote for. You just give them a reason and let them get there themselves." },
      { by: 'c', conf: "{a} said {a} wasn't going to say anything mean, and then spent five minutes saying it. I'm not stupid." },
    ] },
    { id: 'nc.l9', place: 'public', when: { voice: ['loud', 'tough', 'blunt'] }, turns: [
      { by: 'a', say: "That was the worst thing I've ever seen. Ever." },
      { by: 'c', say: "Not now." },
      { by: 'a', say: "Then when? After {b} costs us another one?" },
      { by: 'b', say: "I can hear you." },
      { by: 'a', say: "Good! That's the point!" },
      { by: 'b', say: "You weren't exactly great out there either. You just yell louder about it." },
      { by: 'a', say: "Excuse me?" },
      { by: 'b', say: "You heard me." },
      { by: 'c', say: "Okay! Everybody go to a different part of camp, now." },
      { by: 'a', conf: "{b} wants to fight me? Fine, {b} couldn't even get through the challenge." },
      { by: 'b', conf: "I'm done letting {a} talk to me like that. Done." },
    ] },
    { id: 'nc.l10', place: 'public', when: { voice: ['warm', 'earnest', 'anxious'] }, turns: [
      { by: 'a', say: "Hey, {b}? Can I talk to you for a second?" },
      { by: 'b', say: "If it's about today, I know. I'm sorry." },
      { by: 'a', say: "I'm not mad. I just think you should go talk to people before tonight." },
      { by: 'b', say: "Why? Am I going home?" },
      { by: 'a', say: "I don't know. That's kind of why I'm telling you." },
      { by: 'b', say: "...Okay. Thanks." },
      { by: 'a', conf: "I don't want {b} to go home. But I'm not going to lie to {b} either. People are talking." },
    ] },
    { id: 'nc.l11', place: 'public', when: { voice: ['goofy', 'food', 'ditzy', 'chaotic'] }, turns: [
      { by: 'a', say: "Okay, so that went badly." },
      { by: 'c', say: "Understatement." },
      { by: 'a', say: "On the bright side, nobody got hurt. Much." },
      { by: 'b', say: "I kind of got hurt." },
      { by: 'a', say: "Yeah, but you also kind of lost it for us." },
      { by: 'b', say: "Thanks, {a}." },
      { by: 'a', say: "I'm just being honest! Honest is good!" },
      { by: 'b', conf: "{a} didn't mean it in a mean way. I think. It still means people are going to write my name." },
    ] },
  ],

  'story.chal.won': [
    { id: 'nc.w1', place: 'public', turns: [
      { beat: "The {tribe} come back {here} cheering." },
      { by: 'b', say: "{a}! That was insane, you did that!", v: { dry: "Okay, that was actually impressive, and I'm only saying it once." } },
      { by: 'a', say: "We did that.", v: { proud: "Yeah, I did that. You're welcome.", competitive: "We needed that. We really needed that." } },
      { by: 'b', say: "No, you did that. I mostly tried not to fall over." },
      { by: 'a', say: "Hey, you didn't fall over. That counts." },
      { by: 'a', conf: "I'm so relieved I could sleep for a week. And I'll admit it, part of me is enjoying watching the other team panic.", v: {"cruel":"Honestly, watching them panic is the best part of winning.","warm":"I'm just so glad it's not us tonight. I feel a little bad for them, actually."} },
    ] },
    { id: 'nc.w2', place: 'public', when: { third: true }, turns: [
      { by: 'b', say: "No vote tonight! No vote tonight!" },
      { by: 'c', say: "Yeah, okay. Calm down." },
      { by: 'b', say: "I'm not rubbing it in. I'm celebrating." },
      { by: 'a', say: "Honestly, {c}, if we'd lost, you'd have been in trouble.", v: { warm: "We all did good, even you, {c}. Mostly." } },
      { by: 'c', say: "Thanks, {a}. Great pep talk." },
      { by: 'a', say: "I'm just being honest. Next time, pull your weight." },
      { by: 'c', conf: "{a} carried us once and now {a} thinks {a} runs the team, so okay, I'll remember that." },
    ] },
    { id: 'nc.w3', place: 'public', turns: [
      { beat: "Back {here}. {a} is lying flat on the ground." },
      { by: 'b', say: "Are you alive?" },
      { by: 'a', say: "No." },
      { by: 'b', say: "Do you want food?" },
      { by: 'a', say: "...Yes.", v: { food: "YES, yes, bring all of it!" } },
      { by: 'b', say: "You were amazing out there. I don't think we win without you." },
      { by: 'b', conf: "{a} won us that challenge. The bad part is, everyone on both teams just watched {a} do it." },
    ] },
    { id: 'nc.w4', place: 'aside', when: { voice: ['schemer', 'calm', 'dry'] }, turns: [
      { by: 'b', say: "Look at you. Hero of the day." },
      { by: 'a', say: "I just didn't want to go to a vote tonight." },
      { by: 'b', say: "That's the least excited anyone's ever been about winning." },
      { by: 'a', say: "Winning makes people notice you. I don't love being noticed." },
      { by: 'a', conf: "Winning challenges makes you a target later and losing them makes you a target now, so I'll take later." },
    ] },
    { id: 'nc.w5', place: 'aside', when: { voice: ['warm', 'anxious', 'earnest', 'emotional'] }, turns: [
      { by: 'b', say: "Did you see their faces? The other team?" },
      { by: 'a', say: "I kind of feel bad for them." },
      { by: 'b', say: "Don't. They'd be celebrating if it was us." },
      { by: 'a', say: "I know. I still feel a little bad." },
      { by: 'b', say: "You won it for us and you feel bad. You're so weird." },
      { by: 'a', conf: "I've never been the one who won anything, like ever, so I'm going to remember today." },
    ] },
    { id: 'nc.w6', place: 'public', when: { voice: ['loud', 'proud', 'competitive', 'theatrical'] }, turns: [
      { by: 'a', say: "Did you see that? Did you SEE that?" },
      { by: 'b', say: "Everybody saw it. You were screaming the whole time." },
      { by: 'a', say: "Because I was winning the whole time!" },
      { by: 'b', say: "Fair." },
      { by: 'a', say: "Somebody go tell the other team I said hi. Actually, no, I'll do it myself." },
      { by: 'b', say: "Please don't." },
      { by: 'a', conf: "I'm not going to act humble. I won. I'm going to enjoy it, loudly, for as long as I want." },
    ] },
    { id: 'nc.w7', place: 'fire', turns: [
      { beat: "That night {here}. The {tribe} are in a much better mood than the other team." },
      { by: 'b', say: "Best part of winning?" },
      { by: 'a', say: "Not having to vote?" },
      { by: 'b', say: "Not having to vote. And nobody whispering in the bushes all afternoon." },
      { by: 'a', say: "Give it a day. They'll be back to whispering tomorrow." },
      { by: 'b', say: "Can you let me have one night?" },
      { by: 'a', say: "One night." },
      { by: 'b', conf: "{a} is the reason we're safe tonight. I'm going to remember that. I hope {a} remembers who was cheering for {a.obj}." },
    ] },
    { id: 'nc.w8', place: 'public', when: { early: true }, turns: [
      { by: 'b', say: "First win! Does this mean we're the good team?" },
      { by: 'a', say: "It means we won once." },
      { by: 'b', say: "You're no fun." },
      { by: 'a', say: "I'm fun. I'm just not getting excited about one win." },
      { by: 'b', say: "Fine, we won once, but we're still having a party." },
      { by: 'a', say: "...Okay. I can do a party." },
      { by: 'a', conf: "It's still early and everybody's nice to each other, but the first time we lose, that's going to change." },
    ] },
    { id: 'nc.w9', place: 'aside', when: { gap: 'older' }, turns: [
      { by: 'b', say: "How are you not tired? I'm wrecked, and I'm way younger than you." },
      { by: 'a', say: "Wow. Rude." },
      { by: 'b', say: "It's a compliment!" },
      { by: 'a', say: "Mm-hm. I've worked a lot of long days, you just keep going." },
      { by: 'b', say: "Can you teach me how?" },
      { by: 'a', say: "Stop thinking about how much it hurts. That's it." },
      { by: 'b', say: "That's terrible advice." },
      { by: 'a', say: "We won, didn't we?" },
      { by: 'a', conf: "Everybody assumed the old one would slow them down. I didn't slow anybody down today." },
    ] },
  ],
};
