// ══════════════════════════════════════════════════════════════════════
// td/story/lines/n-drama.js — camp drama, as whole scenes
// ══════════════════════════════════════════════════════════════════════
//
// Long versions of the engine's drama moments (td/script/lines/drama.js, drama2.js headers
// say what each kind and ending means; these keep the meaning, the parts and the slots):
//   drama.bomb.<hothead|arrogant>  a says the thing nobody should say, in front of b
//   drama.fight.<erupt|snap|tense|rare>  a and b fight; the ending is a's temper
//   drama.dispute.*   a and b disagree about the game      drama.clash.*  both try to run camp
//   drama.explode.*   a unloads on b                         drama.meltdown.*  a falls apart
//   drama.intimidate.*  a unnerves b                         drama.prank.<well|badly>  a pranks b
//   drama.dig.*       a takes a shot at b in front of people drama.nemesis.*  the camp knows
//   drama.sorry.<fight|meltdown|bomb|other>  a apologises to b
//   drama.thaw.<talk|blowup|small> / drama.truce.*  rivals a and b soften
//   drama.stir.*      a sets b and c against each other
//   drama.paranoia.bold  a turns on b, a's closest ally, for nothing
//   drama.paranoia.quiet a tells b that {target} (not here) is playing both sides
// Ids: 'nd.'.

export default {
  'long.drama.bomb.hothead': [
    { id: 'nd.bh1', place: 'public', turns: [
      { beat: "Everyone is {here}. {a} has been in a bad mood since breakfast." },
      { by: 'b', say: "Can somebody pass the water?" },
      { by: 'a', say: "Get it yourself. You've got legs.", v: { cruel: "Get it yourself. Or is walking too hard for you too?" } },
      { by: 'b', say: "What is your problem today?" },
      { by: 'a', say: "My problem is I'm doing all the work around here and everybody else is sitting around!" },
      { by: 'b', say: "Nobody's sitting around." },
      { by: 'a', say: "You're sitting right now!" },
      { by: 'b', say: "I'm sitting because I just carried firewood for an hour. You'd know if you'd looked up." },
      { beat: "Nobody says anything. Somebody suddenly gets very interested in the fire." },
      { by: 'a', conf: "Okay. Maybe the firewood thing was true. I'm still not apologising.", v: { loud: "Did I yell? Yes. Was I wrong? ...Partly. Don't put that in.", emotional: "I don't even know why I said that. I'm so tired. Everything makes me want to scream." } },
      { by: 'b', conf: "{a} just yelled at me in front of everybody for helping. Okay. I'll remember that at the vote." },
    ] },
    { id: 'nd.bh2', place: 'work', when: { lost: true }, turns: [
      { beat: "After the challenge, {here}. Nobody is talking about the loss, which is worse than talking about it." },
      { by: 'b', say: "Should we split up the chores before it gets dark?" },
      { by: 'a', say: "Oh, NOW you want to work hard? Where was that this afternoon?" },
      { by: 'b', say: "Wow. Are we really doing this?" },
      { by: 'a', say: "Somebody has to. We lost, and everybody's acting like it just happened to us." },
      { by: 'b', say: "It did just happen to us. All of us. Including you." },
      { by: 'a', say: "I didn't come in last!" },
      { by: 'b', say: "No, you came in loud. Every single time." },
      { by: 'a', conf: "I'm angry because we lost. I'm allowed to be angry when we lose. Somebody needs to care." },
      { by: 'b', conf: "We lose, and {a} blows up at whoever's closest. Tonight that was me. Tomorrow it'll be somebody else." },
    ] },
    { id: 'nd.bh3', place: 'eat', when: { voiceB: ['warm', 'anxious', 'earnest', 'emotional', 'ditzy'] }, turns: [
      { beat: "Dinner {here}. {b} is telling a story about home. {a} cuts in." },
      { by: 'a', say: "Can you stop? Nobody cares about your grandma's dog." },
      { by: 'b', say: "Oh. Sorry. I didn't..." },
      { by: 'a', say: "You talk all the time. All the time! It's like being stuck in a room with a radio." },
      { beat: "{b}'s face drops. {b} puts down {b.posAdj} bowl and walks off." },
      { by: 'a', say: "What? I'm just being honest." },
      { by: 'b', conf: "I was just trying to make everybody feel better. I didn't know I was that annoying." },
      { by: 'a', conf: "Okay, that one was too far. I'll say sorry. Later. When I'm less hungry." },
    ] },
    { id: 'nd.bh4', place: 'fire', when: { prev: ['friction', 'blowup'] }, turns: [
      { beat: "{a} and {b} have been circling each other all day. At the fire {here}, it finally goes." },
      { by: 'b', say: "Are you going to keep staring at me or are you going to say it?" },
      { by: 'a', say: "Fine. You've been talking about me. Behind my back. Again." },
      { by: 'b', say: "I've been talking about you to your face. You just don't listen." },
      { by: 'a', say: "I listen fine! I just don't like what you say!" },
      { by: 'b', say: "That's not the same thing!" },
      { beat: "Both of them are standing now. Everyone else leans back from the fire." },
      { by: 'a', say: "You know what? I'm done. I'm done with you." },
      { by: 'b', say: "You were done with me on day one." },
      { by: 'a', conf: "{b} knows exactly how to get to me. And {b} does it every single day." },
    ] },
  ],
  'long.drama.bomb.arrogant': [
    { id: 'nd.ba1', place: 'public', turns: [
      { beat: "The team is hanging around {here}. {a} is stretched out like {a} owns the place." },
      { by: 'a', say: "Let's be honest. Without me, this team would have lost every challenge." },
      { by: 'b', say: "Are you serious right now?" },
      { by: 'a', say: "Am I wrong? Who won it for us last time?" },
      { by: 'b', say: "We all did. That's how teams work." },
      { by: 'a', say: "Sure. Some of us just did more of the team part." },
      { by: 'b', say: "You know people can hear you, right?" },
      { by: 'a', say: "Good. Maybe they'll try harder.", v: { schemer: "I know. I'm saying it so they do.", proud: "That's kind of the point." } },
      { by: 'b', conf: "{a} just told the whole team they're useless. To their faces. I didn't even have to do anything." },
    ] },
    { id: 'nd.ba2', place: 'eat', when: { carriedA: true }, turns: [
      { beat: "{a} carried today's challenge, and {a} wants everyone {here} to know it." },
      { by: 'a', say: "You're welcome, by the way." },
      { by: 'b', say: "For what?" },
      { by: 'a', say: "For today. You'd all be voting somebody out tonight if it wasn't for me." },
      { by: 'b', say: "We said thank you. Like, four times." },
      { by: 'a', say: "Five would be nice." },
      { by: 'b', say: "You know what would be nice? If you let somebody else talk for once." },
      { by: 'a', conf: "I won us the challenge. I'm allowed to be a little bit proud of that." },
      { by: 'b', conf: "{a} was great today. {a} also made sure every single one of us felt terrible about it." },
    ] },
    { id: 'nd.ba3', place: 'aside', when: { merged: true }, turns: [
      { by: 'a', say: "Can I be real with you? Most of the people left don't deserve to be here." },
      { by: 'b', say: "That's a lot of people." },
      { by: 'a', say: "Half of them are only here because somebody bigger kept them around." },
      { by: 'b', say: "And you're one of the big ones." },
      { by: 'a', say: "I'm the biggest one. Everybody knows it." },
      { by: 'b', say: "You know that's exactly what people say right before they get voted out." },
      { by: 'a', say: "Not me." },
      { by: 'b', conf: "{a} just told me {a} is the biggest threat here. I agree. I'm going to tell everybody else too." },
    ] },
  ],
  'long.drama.fight.erupt': [
    { id: 'nd.fe1', place: 'public', turns: [
      { beat: "It starts over nothing. {b} sits in {a}'s spot {here}." },
      { by: 'a', say: "Move." },
      { by: 'b', say: "There's a whole log. Sit somewhere else." },
      { by: 'a', say: "I said MOVE!" },
      { by: 'b', say: "Don't yell at me!" },
      { by: 'a', say: "Then stop making me yell!" },
      { beat: "{a} kicks the log. It doesn't move. {a} grabs {a.posAdj} foot." },
      { by: 'b', say: "Are you okay?" },
      { by: 'a', say: "DON'T talk to me!" },
      { by: 'a', conf: "Was it about the log? No. It was about everything. The log just happened to be there." },
      { by: 'b', conf: "{a} has a temper like a firework. You don't know when it's going off, but you know it's going off." },
    ] },
    { id: 'nd.fe2', place: 'work', turns: [
      { beat: "{a} and {b} are supposed to be fixing the {quarters} together {here}." },
      { by: 'b', say: "You're holding it wrong." },
      { by: 'a', say: "I'm holding it fine." },
      { by: 'b', say: "It's falling down. While you hold it." },
      { by: 'a', say: "Then YOU hold it!" },
      { beat: "{a} lets go. The whole side comes down on {b}." },
      { by: 'b', say: "Are you KIDDING me?!" },
      { by: 'a', say: "You said you wanted to hold it!" },
      { by: 'b', conf: "I'm going to be picking splinters out of my hair for a week. And {a} thinks it was my fault." },
      { by: 'a', conf: "I lost my temper. And the roof. Mostly the temper." },
    ] },
  ],
  'long.drama.fight.snap': [
    { id: 'nd.fs1', place: 'eat', turns: [
      { beat: "{b} has been tapping {b.posAdj} spoon on the table for ten minutes {here}." },
      { by: 'a', say: "Can you stop that?" },
      { by: 'b', say: "Stop what?" },
      { by: 'a', say: "The tapping. The tapping! You've been doing it all morning!" },
      { by: 'b', say: "Okay, wow, it's just a spoon." },
      { by: 'a', say: "It's not just a spoon. It's the spoon and the humming and the way you chew." },
      { by: 'b', say: "The way I CHEW?" },
      { by: 'a', conf: "I was fine. I was totally fine. And then the spoon happened." },
      { by: 'b', conf: "I've been here for days, and today is the day my chewing became a problem. Okay." },
    ] },
    { id: 'nd.fs2', place: 'sleep', turns: [
      { beat: "Late in the {quarters}. Somebody's snoring. {a} sits up." },
      { by: 'a', say: "{b}. {b}. You're snoring." },
      { by: 'b', say: "...I'm asleep." },
      { by: 'a', say: "You WERE asleep. Now nobody's asleep. Roll over." },
      { by: 'b', say: "Don't tell me how to sleep." },
      { by: 'a', say: "Somebody has to! I haven't slept since we got here!" },
      { beat: "Someone else in the {quarters} throws a pillow at both of them." },
      { by: 'a', conf: "It's not about the snoring. Okay, it's a little bit about the snoring." },
    ] },
    { id: 'nd.fs3', place: 'work', when: { lost: true }, turns: [
      { by: 'b', say: "We're not going to talk about what happened today?" },
      { by: 'a', say: "What is there to talk about? We lost." },
      { by: 'b', say: "You could start with why you didn't pass me the rope." },
      { by: 'a', say: "You weren't ready!" },
      { by: 'b', say: "I was screaming your name!" },
      { by: 'a', say: "Everybody was screaming! It's a challenge! That's what people do!" },
      { by: 'b', say: "Forget it. You never listen anyway." },
      { by: 'a', conf: "Now it's my fault? Great. Love being the bad guy." },
    ] },
  ],
  'long.drama.fight.tense': [
    { id: 'nd.ft1', place: 'aside', turns: [
      { beat: "{a} finds {b} away from everybody. {a} keeps {a.posAdj} voice very low." },
      { by: 'a', say: "I need you to stop talking about me." },
      { by: 'b', say: "I don't know what you mean." },
      { by: 'a', say: "Yes, you do. You said I can't be trusted. Somebody told me word for word." },
      { by: 'b', say: "Then they got it wrong." },
      { by: 'a', say: "I'm being very calm right now. I'd like you to notice that." },
      { by: 'b', say: "I noticed." },
      { by: 'a', say: "Good. Because I won't be calm next time." },
      { by: 'b', conf: "{a} didn't raise {a.posAdj} voice once. That was so much scarier than yelling." },
    ] },
    { id: 'nd.ft2', place: 'secret', when: { voice: ['calm', 'dry', 'schemer', 'proud'] }, turns: [
      { by: 'a', say: "I don't like you. I'm not going to pretend I do." },
      { by: 'b', say: "Okay. That's fine." },
      { by: 'a', say: "But I'm not going to fight you in front of everyone, because that's what you want." },
      { by: 'b', say: "What I want is for you to stop acting like you're in charge." },
      { by: 'a', say: "I'm not in charge. I'm just better at this than you." },
      { by: 'b', say: "Wow." },
      { by: 'a', conf: "Losing your temper in this game is like handing people a reason. I'm not giving {b} one." },
    ] },
  ],
  'long.drama.fight.rare': [
    { id: 'nd.fr1', place: 'public', turns: [
      { beat: "{a} is the calmest person in camp. Until {here}, this afternoon." },
      { by: 'b', say: "Come on, it was a joke." },
      { by: 'a', say: "It wasn't funny. It hasn't been funny for days." },
      { by: 'b', say: "Whoa. Okay." },
      { by: 'a', say: "No. Don't 'okay' me. I've let it go every time. I'm not letting it go today." },
      { beat: "Everybody stops what they're doing. Nobody has ever heard {a} like this." },
      { by: 'b', say: "I'm sorry. I didn't know it bothered you." },
      { by: 'a', say: "That's because I never said. I'm saying it now." },
      { by: 'a', conf: "I don't yell. I really don't. But everyone's got a limit, and I found mine.", v: { warm: "I hate fighting. I really do. I just couldn't smile through it anymore." } },
      { by: 'b', conf: "{a} snapped at me. {a}. I didn't know that was possible. I guess I earned it." },
    ] },
  ],
  'long.drama.fight.any': [
    { id: 'nd.fa1', place: 'public', turns: [
      { by: 'a', say: "Why do you always do that?" },
      { by: 'b', say: "Do what?" },
      { by: 'a', say: "Act like I'm not here. I'm talking and you just keep going." },
      { by: 'b', say: "Maybe if you said something worth stopping for..." },
      { by: 'a', say: "Oh, great. Really nice." },
      { by: 'b', say: "You started it." },
      { by: 'a', say: "I asked a question!" },
      { beat: "They glare at each other until somebody calls them both to help with dinner." },
      { by: 'a', conf: "{b} and I can't be in the same place for five minutes. Everybody's noticed. Everybody's tired of it. So am I." },
    ] },
  ],

  'long.drama.dispute.any': [
    { id: 'nd.dp1', place: 'aside', turns: [
      { by: 'a', say: "Can I say something about the way you're playing?" },
      { by: 'b', say: "Can I stop you?" },
      { by: 'a', say: "You're telling everybody different things. People talk. They compare." },
      { by: 'b', say: "I'm keeping my options open." },
      { by: 'a', say: "You're keeping everyone confused. Including the people on your side." },
      { by: 'b', say: "If they're confused, they're not voting for me." },
      { by: 'a', say: "Or they're voting for you because they don't know where you are." },
      { by: 'b', conf: "{a} thinks there's one right way to play this. There isn't. There's my way and there's {a}'s way." },
      { by: 'a', conf: "{b} is going to get both of us voted out. I need to decide how close I want to be standing when it happens." },
    ] },
    { id: 'nd.dp2', place: 'secret', when: { lost: true, sank: true }, turns: [
      { by: 'a', say: "We have to talk about tonight. It has to be {sank}." },
      { by: 'b', say: "No. {sank} had one bad day." },
      { by: 'a', say: "{sank} had the worst day. That's how this works before the merge." },
      { by: 'b', say: "{sank} is loyal to us. You'd throw that away for one challenge?" },
      { by: 'a', say: "I'd throw it away to win the next challenge." },
      { by: 'b', say: "And when it's you having the bad day?" },
      { by: 'a', say: "Then I hope I've been useful the rest of the time." },
      { by: 'b', conf: "{a} wants to keep the strong ones. I want to keep the ones who'll actually vote with us. We can't both be right." },
    ] },
    { id: 'nd.dp3', place: 'aside', when: { voice: ['loud', 'blunt', 'tough'] }, turns: [
      { by: 'a', say: "Your plan is bad." },
      { by: 'b', say: "Good morning to you too." },
      { by: 'a', say: "I'm serious. You want to go after the strongest person here. We need them for challenges." },
      { by: 'b', say: "We need them gone before they win immunity every week." },
      { by: 'a', say: "We need to make it to the merge first!" },
      { by: 'b', say: "Fine. Do it your way. When it goes wrong, I'm going to say I told you." },
      { by: 'a', say: "And when it goes right, I'm going to say it louder." },
      { by: 'b', conf: "{a} and I want the same thing. We just completely disagree about how to get it." },
    ] },
  ],
  'long.drama.clash.any': [
    { id: 'nd.cl1', place: 'work', turns: [
      { beat: "Morning chores {here}. {a} has a plan. So does {b}." },
      { by: 'a', say: "Okay. Two people on water, two on wood, and I'll do food." },
      { by: 'b', say: "Actually, I already told everybody: wood first, then water." },
      { by: 'a', say: "Why would you do wood first?" },
      { by: 'b', say: "Because it takes longer and it's cooler in the morning." },
      { by: 'a', say: "That makes no sense." },
      { by: 'b', say: "It makes perfect sense. You just didn't think of it." },
      { beat: "The rest of the team stands there holding buckets, waiting." },
      { by: 'a', conf: "Nobody voted {b} in charge. Nobody voted me in charge either. But at least I'm good at it.", v: { bossy: "Somebody has to run this place. It should be the person who's actually organised. Me." } },
      { by: 'b', conf: "{a} wants to be the leader so badly. The team doesn't need a leader. It needs people to stop arguing about buckets." },
    ] },
    { id: 'nd.cl2', place: 'public', when: { lost: true }, turns: [
      { by: 'a', say: "Okay, everybody. That can't happen again. Next time we listen to one person." },
      { by: 'b', say: "And let me guess. That person is you." },
      { by: 'a', say: "Do you have a better idea?" },
      { by: 'b', say: "I had a better idea during the challenge. Nobody could hear it over you." },
      { by: 'a', say: "Because I was trying to get us organised!" },
      { by: 'b', say: "You were trying to be in charge. There's a difference." },
      { by: 'a', conf: "If I don't lead, nobody does. And then we lose." },
      { by: 'b', conf: "We lost with {a} leading. I'm just pointing that out." },
    ] },
  ],
  'long.drama.explode.any': [
    { id: 'nd.ex1', place: 'public', turns: [
      { beat: "{b} makes one more comment {here}. That's the one that does it." },
      { by: 'a', say: "Do you ever stop? Seriously, do you ever stop?" },
      { by: 'b', say: "What did I even say?" },
      { by: 'a', say: "It's not what you said! It's everything you say! You correct everybody! You complain about everything! You think you're the only one who's tired!" },
      { by: 'b', say: "Okay, I didn't..." },
      { by: 'a', say: "And you never, EVER help with dinner!" },
      { beat: "{a} walks off. A long silence." },
      { by: 'b', say: "...I helped with dinner yesterday." },
      { by: 'a', conf: "I've been holding that in since we got here. It felt amazing. Now I feel kind of sick." },
      { by: 'b', conf: "I didn't know {a} hated me that much. Now everybody knows. Great." },
    ] },
    { id: 'nd.ex2', place: 'aside', when: { voiceB: ['tough', 'loud', 'blunt', 'cruel'] }, turns: [
      { by: 'a', say: "I'm going to say this once." },
      { by: 'b', say: "Here we go." },
      { by: 'a', say: "You've been pushing people around since we got here. Me. Everybody. And nobody says anything because they're scared of you." },
      { by: 'b', say: "And you're not scared?" },
      { by: 'a', say: "I'm terrified! I'm saying it anyway!" },
      { by: 'b', say: "...Huh." },
      { by: 'b', conf: "Nobody's ever talked to me like that out here. I'm annoyed. I'm also kind of impressed." },
    ] },
  ],
  'long.drama.meltdown.any': [
    { id: 'nd.md1', place: 'public', turns: [
      { beat: "{a} has been quiet all day. Then, {here}, {a} drops the bucket and doesn't pick it up." },
      { by: 'c', say: "Hey. You okay?" },
      { by: 'a', say: "No. No, I'm not okay. I'm hungry and I haven't slept and everything here is wet!" },
      { by: 'a', say: "I just want one thing to go right. One thing!" },
      { beat: "{a} sits down in the dirt. Nobody knows what to do." },
      { by: 'b', say: "Do you want some water?" },
      { by: 'a', say: "I don't want water. I want to go home. No. I don't want to go home. I don't know what I want." },
      { by: 'a', conf: "I lost it. In front of everybody. I'm going to be embarrassed about this for the rest of my life.", v: { tough: "I don't cry. I didn't cry. My eyes got wet because of the smoke." } },
    ] },
    { id: 'nd.md2', place: 'public', when: { third: false }, turns: [
      { beat: "{a} has been trying to start the fire for an hour {here}. It keeps going out." },
      { by: 'a', say: "Come ON. Come on, come on, come on." },
      { by: 'b', say: "Do you want me to try?" },
      { by: 'a', say: "No! I can do it! I can do ONE thing!" },
      { beat: "It goes out again. {a} throws the stick into the bushes and screams." },
      { by: 'b', say: "Okay. Okay. I'm just going to sit here." },
      { by: 'a', conf: "It wasn't the fire. It was the fire and the challenge and the vote and the food. The fire was just the last thing." },
    ] },
  ],
  'long.drama.intimidate.any': [
    { id: 'nd.in1', place: 'aside', turns: [
      { beat: "{a} sits down right next to {b} {here}. Too close." },
      { by: 'b', say: "Can I help you?" },
      { by: 'a', say: "Just saying hi." },
      { by: 'b', say: "You've never said hi to me." },
      { by: 'a', say: "I'm saying it now. I'm also saying I know you were talking about me last night." },
      { by: 'b', say: "I wasn't..." },
      { by: 'a', say: "Sure. Have a nice day." },
      { beat: "{a} gets up and walks off. {b} doesn't move for a while." },
      { by: 'b', conf: "{a} didn't threaten me. Not exactly. But I'm not going to sleep tonight." },
      { by: 'a', conf: "I didn't say anything mean. I just wanted {b} to know I'm paying attention." },
    ] },
    { id: 'nd.in2', place: 'work', when: { voice: ['tough', 'competitive', 'loud'] }, turns: [
      { beat: "{a} is chopping wood {here}. {b} is stacking it." },
      { by: 'a', say: "You know you were the slowest today, right?" },
      { by: 'b', say: "I know." },
      { by: 'a', say: "Just making sure." },
      { beat: "{a} brings the axe down. Hard. The log splits in two." },
      { by: 'b', say: "Was that for me?" },
      { by: 'a', say: "That was for the log." },
      { by: 'b', conf: "{a} wanted me to feel small. It worked. For about five minutes. Then I got mad." },
    ] },
  ],
  'long.drama.prank.well': [
    { id: 'nd.pw1', place: 'sleep', turns: [
      { beat: "Early morning in the {quarters}. {b} reaches for {b.posAdj} shoes." },
      { by: 'b', say: "Why are my shoes full of sand?" },
      { by: 'a', say: "I have no idea what you're talking about." },
      { by: 'b', say: "You're laughing." },
      { by: 'a', say: "I'm laughing about something else." },
      { by: 'b', say: "...Okay, that's actually pretty good. Where's the rest of my stuff?" },
      { by: 'a', say: "Check the roof." },
      { by: 'b', conf: "I'm going to get {a} back. Not today. But I'm going to get {a} back." },
      { by: 'a', conf: "Everybody laughed. Even {b}. That's a good prank. Nobody got hurt and the camp needed something funny." },
    ] },
    { id: 'nd.pw2', place: 'public', when: { voice: ['goofy', 'chaotic', 'theatrical'] }, turns: [
      { beat: "{a} has been planning this for two days. {b} sits down {here}." },
      { beat: "The log tips. {b} goes straight backwards into a pile of leaves." },
      { by: 'b', say: "WHO DID THAT?" },
      { by: 'a', say: "The log did it. The log's been weird all week." },
      { by: 'b', say: "You're the only one who's been sawing things!" },
      { by: 'a', say: "That's... a fair point. Okay, it was me." },
      { by: 'b', say: "...I'm going to laugh, but I'm still mad." },
      { by: 'a', conf: "Two days of work. Worth it. I'd do it again. I will do it again." },
    ] },
  ],
  'long.drama.prank.badly': [
    { id: 'nd.pb1', place: 'public', turns: [
      { beat: "{a} hid a frog in {b}'s bag. {b} did not think it was funny." },
      { by: 'b', say: "WHAT IS WRONG WITH YOU?" },
      { by: 'a', say: "It was a joke! It's a frog!" },
      { by: 'b', say: "I told you on the first day I'm scared of frogs!" },
      { by: 'a', say: "...Did you?" },
      { by: 'b', say: "Yes! In front of everybody!" },
      { beat: "The rest of the team looks at {a}. Nobody is laughing." },
      { by: 'a', conf: "I really didn't remember the frog thing. I'm an idiot. I'm a big idiot." },
      { by: 'b', conf: "Either {a} forgot, or {a} remembered and did it anyway. I don't know which one's worse." },
    ] },
  ],
  'long.drama.dig.any': [
    { id: 'nd.dg1', place: 'eat', turns: [
      { beat: "Everyone {here}. {b} is telling the table how hard {b} worked today." },
      { by: 'a', say: "Wow. You must be so tired." },
      { by: 'b', say: "I am, actually." },
      { by: 'a', say: "From all that standing around. It really takes it out of you." },
      { by: 'b', say: "Excuse me?" },
      { by: 'a', say: "What? I said you must be tired." },
      { by: 'b', conf: "{a} won't ever say it straight. It's always a little joke with a knife in it." },
      { by: 'a', conf: "I didn't say anything mean. Everyone just knew what I meant. That's different.", v: { dry: "I said one sentence. {b} heard the whole speech. That's {b}'s problem." } },
    ] },
    { id: 'nd.dg2', place: 'public', when: { voice: ['cruel', 'schemer', 'proud', 'dry'] }, turns: [
      { by: 'b', say: "Does anybody want some of this? I found berries." },
      { by: 'a', say: "Are you sure they're berries? You were sure about the challenge too." },
      { beat: "A couple of people laugh. {b} doesn't." },
      { by: 'b', say: "Okay. I'll just eat them myself, then." },
      { by: 'a', say: "Brave." },
      { by: 'b', conf: "I try to do one nice thing and {a} turns it into a joke about me. Every time." },
    ] },
    { id: 'nd.dg3', place: 'public', when: { lost: true }, turns: [
      { by: 'b', say: "We'll get them next time." },
      { by: 'a', say: "We will. Especially if some of us figure out which way the finish line is." },
      { by: 'b', say: "That was one time." },
      { by: 'a', say: "I didn't say who." },
      { by: 'b', say: "You didn't have to." },
      { by: 'b', conf: "{a} wants everybody to blame me for today. And {a} wants it to look like a joke." },
    ] },
  ],
  'long.drama.nemesis.any': [
    { id: 'nd.nm1', place: 'public', turns: [
      { beat: "{a} and {b} end up at the same spot {here}. Again." },
      { by: 'a', say: "Oh, great." },
      { by: 'b', say: "I was here first." },
      { by: 'a', say: "You're always here first. You do it on purpose." },
      { by: 'b', say: "Yes. I wake up every morning and think, how can I ruin your day." },
      { by: 'a', say: "I knew it!" },
      { by: 'c', say: "Can you two please not do this today?" },
      { by: 'a', say: "Tell {b}!" },
      { by: 'b', say: "Tell {a}!" },
      { by: 'c', conf: "{a} and {b} have been at war since the first day. I don't even think they remember why. I just want to eat in peace." },
    ] },
    { id: 'nd.nm2', place: 'public', when: { third: false }, turns: [
      { by: 'a', say: "I just want you to know, the day you go home is going to be the best day of my life." },
      { by: 'b', say: "That's so funny. I was going to say the same thing to you." },
      { by: 'a', say: "Great. Something we agree on." },
      { by: 'b', say: "The only thing." },
      { by: 'a', conf: "Everyone here knows I can't stand {b}. I don't hide it. Hiding it would be fake." },
      { by: 'b', conf: "{a} isn't my rival. A rival is someone you respect. {a} is just loud." },
    ] },
  ],

  'long.drama.sorry.fight': [
    { id: 'nd.sf1', place: 'aside', turns: [
      { beat: "{a} finds {b} alone {here}. {a} doesn't sit down." },
      { by: 'a', say: "Hey. About yesterday." },
      { by: 'b', say: "What about it?" },
      { by: 'a', say: "I shouldn't have said what I said. I was angry, and you were there." },
      { by: 'b', say: "That's not really an apology." },
      { by: 'a', say: "...I'm sorry. That's the apology. I'm sorry." },
      { by: 'b', say: "Okay. Thank you." },
      { by: 'a', say: "Are we okay?" },
      { by: 'b', say: "We're getting there." },
      { by: 'a', conf: "Saying sorry is the worst. I'd rather do another challenge.", v: { proud: "I don't apologise. I just did. Nobody make a big deal about it.", warm: "I felt sick about it all night. I'm so glad I said something." } },
      { by: 'b', conf: "{a} said sorry. I believe it. I'm also not going to forget it happened." },
    ] },
    { id: 'nd.sf2', place: 'water', when: { voice: ['loud', 'tough', 'blunt', 'competitive'] }, turns: [
      { beat: "{a} sits down next to {b} {here} and doesn't say anything for a while." },
      { by: 'b', say: "If you're here to yell, I'm leaving." },
      { by: 'a', say: "I'm not here to yell. I'm here to say I was out of line." },
      { by: 'b', say: "You were really out of line." },
      { by: 'a', say: "I know. I get loud. It's a thing. I'm working on it." },
      { by: 'b', say: "Work faster." },
      { by: 'a', say: "...Fair." },
      { by: 'b', conf: "{a} said sorry, which I didn't think {a} knew how to do. I'll take it." },
    ] },
  ],
  'long.drama.sorry.meltdown': [
    { id: 'nd.sm1', place: 'aside', turns: [
      { by: 'a', say: "So. You saw all that yesterday." },
      { by: 'b', say: "Everybody saw all that yesterday." },
      { by: 'a', say: "Yeah. I'm sorry. I wasn't okay, and I took it out on everybody." },
      { by: 'b', say: "You don't have to apologise for having a bad day." },
      { by: 'a', say: "I kind of do. I threw a bucket." },
      { by: 'b', say: "You did throw a bucket." },
      { by: 'a', conf: "I'm embarrassed. But {b} was nice about it. Nicer than I would have been." },
    ] },
  ],
  'long.drama.sorry.bomb': [
    { id: 'nd.sb1', place: 'aside', turns: [
      { by: 'a', say: "Can I talk to you? I said some things yesterday." },
      { by: 'b', say: "You did." },
      { by: 'a', say: "I didn't mean them. Well, I meant some of them. But not like that. Not in front of everyone." },
      { by: 'b', say: "That's a strange apology." },
      { by: 'a', say: "I'm bad at this." },
      { by: 'b', say: "I can tell. But thanks for trying." },
      { by: 'b', conf: "{a} came to say sorry. That's more than most people here would do. I'm still watching {a}, though." },
    ] },
  ],
  'long.drama.sorry.any': [
    { id: 'nd.sa1', place: 'water', turns: [
      { beat: "{a} walks down to {b} {here}." },
      { by: 'a', say: "Do you have a minute?" },
      { by: 'b', say: "I've got nothing but minutes." },
      { by: 'a', say: "Things have been weird between us. I think it's partly my fault." },
      { by: 'b', say: "Partly?" },
      { by: 'a', say: "Mostly. I'm sorry. I want to fix it." },
      { by: 'b', say: "Okay. Me too." },
      { by: 'a', conf: "I don't need {b} to be my best friend. I just don't want {b} as an enemy." },
    ] },
    { id: 'nd.sa2', place: 'aside', when: { voice: ['warm', 'anxious', 'earnest', 'emotional'] }, turns: [
      { by: 'a', say: "I made you something." },
      { by: 'b', say: "...Is that a bracelet made of grass?" },
      { by: 'a', say: "It's an apology bracelet. I'm sorry about everything. I hate it when people are mad at me." },
      { by: 'b', say: "I wasn't that mad." },
      { by: 'a', say: "You weren't?" },
      { by: 'b', say: "I was a little mad. I'm less mad now. It's a good bracelet." },
      { by: 'a', conf: "I can't sleep when people are upset with me. Now I can sleep. Yay." },
    ] },
    { id: 'nd.sa3', place: 'aside', when: { voice: ['schemer', 'calm', 'dry', 'cruel'] }, turns: [
      { by: 'a', say: "Look, I think we got off on the wrong foot." },
      { by: 'b', say: "We got off on both wrong feet." },
      { by: 'a', say: "Fine. Both feet. I'm sorry. I'd rather work with you than against you." },
      { by: 'b', say: "Is this a real sorry or a game sorry?" },
      { by: 'a', say: "Does it matter, if it works out for both of us?" },
      { by: 'b', conf: "That was a game sorry. I know a game sorry. I'll still take it, because I need allies too." },
      { by: 'a', conf: "Saying sorry costs me nothing. Having {b} against me could cost me the game." },
    ] },
  ],
  'long.drama.thaw.any': [
    { id: 'nd.th1', place: 'work', turns: [
      { beat: "{a} and {b} get stuck on water duty together {here}. Neither of them chose it." },
      { by: 'a', say: "I'll carry this one." },
      { by: 'b', say: "I can carry it." },
      { by: 'a', say: "I know you can. I'm just offering." },
      { by: 'b', say: "...Thanks." },
      { beat: "They walk for a bit." },
      { by: 'b', say: "You're less annoying when you're not talking." },
      { by: 'a', say: "You're less annoying when you're carrying the other bucket." },
      { by: 'b', conf: "{a} and I aren't friends. But I don't want to throw something at {a} every time I see {a.obj} anymore. That's progress." },
    ] },
    { id: 'nd.th2', place: 'fire', when: { lastBoot: true }, turns: [
      { by: 'b', say: "Weird with {lastBoot} gone." },
      { by: 'a', say: "Yeah. It's quiet." },
      { by: 'b', say: "You know, {lastBoot} was the one who kept saying we hated each other." },
      { by: 'a', say: "Did we, though?" },
      { by: 'b', say: "I don't know. I did a bit." },
      { by: 'a', say: "Same. Less now." },
      { by: 'b', say: "Less now." },
      { by: 'a', conf: "{lastBoot} going home changed a lot. Turns out a lot of my problem with {b} was coming from {lastBoot}." },
    ] },
    { id: 'nd.th3', place: 'fire', when: { merged: true }, turns: [
      { by: 'a', say: "Can I say something without you getting mad?" },
      { by: 'b', say: "Probably not, but go ahead." },
      { by: 'a', say: "We're the last two from our side who still fight. Everybody else gave up. Maybe we should too." },
      { by: 'b', say: "...You want a truce?" },
      { by: 'a', say: "A truce until the end of the week. Then we can go back to hating each other." },
      { by: 'b', say: "Deal." },
      { by: 'b', conf: "{a} and I have been fighting so long, I forgot what it's like to just sit by the fire. It's nice. Don't tell {a}." },
    ] },
  ],
  'long.drama.truce.any': [
    { id: 'nd.tr1', place: 'aside', turns: [
      { by: 'a', say: "Can we stop this?" },
      { by: 'b', say: "Stop what?" },
      { by: 'a', say: "Whatever this is between us. It's not getting either of us anywhere." },
      { by: 'b', say: "You started it." },
      { by: 'a', say: "Maybe. And I'm ending it. I'm sorry. Truce?" },
      { by: 'b', say: "...Truce." },
      { by: 'a', conf: "I don't have to like {b}. But fighting with {b} every day was making me look bad. And tired." },
    ] },
  ],
  'long.drama.stir.any': [
    { id: 'nd.st1', place: 'public', when: { third: true }, turns: [
      { beat: "{a} sits down between {b} and {c} {here}." },
      { by: 'a', say: "{b}, didn't you say {c} barely did anything today?" },
      { by: 'b', say: "I... what? I said it was a hard day." },
      { by: 'c', say: "You said WHAT?" },
      { by: 'b', say: "I didn't say that!" },
      { by: 'a', say: "Oh. Maybe I heard it wrong." },
      { beat: "{b} and {c} are both looking at each other now, not at {a}." },
      { by: 'a', conf: "I didn't make anything up. I just repeated it a little louder. Now they're watching each other instead of me.", v: { chaotic: "Was that mean? Yes. Was it fun? Also yes." } },
    ] },
    { id: 'nd.st2', place: 'aside', when: { third: true, lost: true }, turns: [
      { by: 'a', say: "Can I tell you something? {c} has been saying the loss was your fault." },
      { by: 'b', say: "Seriously?" },
      { by: 'a', say: "I heard it twice." },
      { by: 'b', say: "{c} lost us that challenge!" },
      { beat: "{b} storms off to find {c}." },
      { by: 'a', conf: "{c} never said it. But {b} was already thinking it. I just helped." },
    ] },
  ],
  'long.drama.paranoia.bold': [
    { id: 'nd.pa1', place: 'aside', turns: [
      { by: 'a', say: "Are you working with somebody else?" },
      { by: 'b', say: "What? No. Where's this coming from?" },
      { by: 'a', say: "You were gone for an hour this morning." },
      { by: 'b', say: "I was getting water! You saw me get water!" },
      { by: 'a', say: "For an hour?" },
      { by: 'b', say: "The well is far! I can't believe you're doing this." },
      { by: 'a', say: "I just need to know where you are." },
      { by: 'b', conf: "I've done nothing. Nothing! And now {a} thinks I'm a traitor. This is how alliances end." },
      { by: 'a', conf: "{b} sounded honest. That's what worries me. Liars always sound honest." },
    ] },
  ],
  'long.drama.paranoia.quiet': [
    { id: 'nd.pq1', place: 'secret', turns: [
      { by: 'a', say: "Can I tell you something and you don't freak out?" },
      { by: 'b', say: "That's a terrible way to start." },
      { by: 'a', say: "I think {target} is playing both sides." },
      { by: 'b', say: "{target}? Based on what?" },
      { by: 'a', say: "Little things. {target} talks to everyone. {target} is nice to everyone. Nobody's that nice." },
      { by: 'b', say: "Some people are just nice." },
      { by: 'a', say: "Not in this game." },
      { by: 'b', conf: "{a} has no proof. None. But now I'm going to look at {target} differently, and I hate that." },
    ] },
  ],
};
