// ══════════════════════════════════════════════════════════════════════
// td/story/lines/n-group.js — strategy talks as group conversations
// ══════════════════════════════════════════════════════════════════════
//
// When the person who starts a strategy talk works in groups (director.js shapeFor), the friends
// a and b share join it as c (and d). Same keys as n-talk.js: talk.plan (map / plain / quiet),
// talk.game, talk.checkin, talk.scramble. Everyone here is on the same side, so nobody hears
// anything they shouldn't. Ids: 'ng.'.

export default {
  'long.talk.plan.any': [
    { id: 'ng.p1', place: 'secret', when: { third: true }, turns: [
      { beat: "{a}, {b} and {c} meet at {place}, the way they've started doing every afternoon." },
      { by: 'a', say: "Okay. What's everybody heard?", v: { loud: "Okay, okay, what's everybody got? Somebody tell me something!", dry: "Okay, so who's heard what? Go ahead, I know you've all got something.", anxious: "Okay, um, has anybody heard anything? Anything bad?", teen: "Okay, spill. What's everyone heard?" } },
      { by: 'b', say: "People are nervous. Nobody's saying a name yet." },
      { by: 'c', say: "I've heard one name twice now, but I'm not saying it until I hear it a third time." },
      { by: 'a', say: "That's fair. Whose name?" },
      { by: 'c', say: "Third time." },
      { by: 'b', say: "So we wait?" },
      { by: 'a', say: "We wait, we listen, and we don't say anything first. Whoever says a name first becomes the next name." },
      { by: 'c', conf: "The three of us tell each other everything. It's the only reason I sleep at night.", v: { dry: "We tell each other everything. It's either very healthy or very paranoid.", warm: "I trust these two with everything. That feels so rare here.", quiet: "We tell each other everything. That's enough.", grown: "At my age you learn who to trust fast. These two, I trust." } },
    ] },
    { id: 'ng.p2', place: 'sleep', when: { fourth: true }, turns: [
      { beat: "{a}, {b}, {c} and {d} are in the {quarters}, keeping their voices down." },
      { by: 'd', say: "Should we really be doing this in here?", v: { anxious: "Should we really be doing this in here? What if somebody walks in?", loud: "Is this a secret meeting? It feels like a secret meeting!", dry: "Ah yes, a top-secret meeting. In the room everybody sleeps in." } },
      { by: 'a', say: "Everybody else is out. We've got a few minutes." },
      { by: 'b', say: "So what's the plan? Like, if we keep winning nobody goes home, but if we lose..." },
      { by: 'c', say: "We lose, and it's not one of us four. That's the plan." },
      { by: 'a', say: "Right. And we don't fight about who goes next until we have to." },
      { by: 'd', say: "And if somebody comes to one of us with a deal?" },
      { by: 'a', say: "Then you bring it back here, to all of us, and nobody makes side deals." },
      { by: 'b', say: "No side deals." },
      { by: 'd', conf: "Four of us, sitting on {bed}s, promising no side deals. Somebody in this room is going to make one. I just hope it's not about me.", v: { schemer: "Four of us promised no side deals, and I've already got two, so... that's fine.", warm: "I believe them. I really want to believe them.", teen: "We literally pinky-promised no side deals, so somebody's lying, and I just really hope it's not about me." } },
    ] },
    { id: 'ng.p3', place: 'fire', when: { third: true, voice: ['warm', 'earnest', 'emotional'] }, turns: [
      { by: 'a', say: "Can we just check in for a second? Like as people, I mean, not as votes." },
      { by: 'b', say: "That's very you." },
      { by: 'a', say: "I know. But this place is making me crazy, and you two are the only ones I can talk to." },
      { by: 'c', say: "Same. I've said 'I'm fine' about forty times today." },
      { by: 'b', say: "Okay, but also as votes, since we're here anyway. We're still together, right?" },
      { by: 'a', say: "We're together." },
      { by: 'c', say: "Together." },
      { by: 'a', conf: "I don't care if it's corny. Knowing two people have my back is the only thing keeping me going here.", v: { emotional: "I cried a little after that, but it was happy crying, because I really needed it.", grown: "Sure, it's corny, but at my age you learn that corny usually means it's real." } },
    ] },
    { id: 'ng.p4', place: 'work', when: { third: true, tribal: true }, turns: [
      { beat: "{a}, {b} and {c} are pretending to gather wood {here}. They aren't gathering much." },
      { by: 'b', say: "We need a name for tonight.", v: { blunt: "We need a name. Now.", anxious: "So, um, about tonight... we need a name, right?", bossy: "Okay, tonight we pick a name before anybody else picks one for us." } },
      { by: 'a', say: "We need a name that isn't one of us. That's the only rule." },
      { by: 'c', say: "Everybody else is saying a name. We just don't know whose." },
      { by: 'a', say: "Then we split up, each of us talks to one person, and we meet back here before dinner." },
      { by: 'b', say: "And if we hear our own names?" },
      { by: 'a', say: "Then you run straight back here, as fast as you can." },
      { by: 'c', conf: "We have a system now. Three of us, three conversations, one name by dinner. That's the most organised I've felt since I got here.", v: { nerdy: "Three people, three conversations, one name by dinner. It's basically an algorithm.", dry: "We have a whole system now, and I've never been part of a system before, so honestly it's kind of terrifying.", competitive: "Three of us, one name by dinner. That's how you win a vote." } },
    ] },
  ],
  'long.talk.plan.map': [
    { id: 'ng.m1', place: 'secret', when: { fourth: true }, turns: [
      { beat: "{a} draws in the dirt with a stick. {b}, {c} and {d} crouch around it." },
      { by: 'a', say: "Okay, so these are us, these are them, and these are the ones nobody's got yet.", v: { nerdy: "Okay, so group A is us, group B is them, and group C is everybody who hasn't picked yet. Follow me?", bossy: "Listen up, it's us, it's them, and it's the people we're about to take from them.", dry: "So this rock is us, that rock is them, and that sad little leaf is everybody else." } },
      { by: 'c', say: "That's a lot of 'nobody's got yet'." },
      { by: 'a', say: "That's where we win. We get two of them, and we have the numbers every vote until the merge." },
      { by: 'd', say: "Which two?" },
      { by: 'a', say: "Whoever likes us most. {b}, you're good with people, so you take one, and {c}, you take the other." },
      { by: 'b', say: "And what do you do?" },
      { by: 'a', say: "I keep everybody from noticing we're doing it." },
      { by: 'd', say: "And me?" },
      { by: 'a', say: "You keep winning challenges. Nobody votes out the person they need." },
      { by: 'd', conf: "{a} had the whole game drawn in the dirt in two minutes. I'm glad I'm in the circle and not one of the scribbles.", v: { anxious: "{a} drew the whole game in the dirt. I checked twice that I wasn't one of the scribbles.", goofy: "{a} drew a whole map, and I was a stick figure on it, but I was a safe stick figure, so I'll take it." } },
    ] },
    { id: 'ng.m2', place: 'aside', when: { third: true }, turns: [
      { by: 'a', say: "Here's how I see the next three votes.", v: { schemer: "I've already planned the next three votes. Want to hear them?", calm: "Let me walk you through the next three votes.", competitive: "Next three votes. Here's how we win all of them." } },
      { by: 'b', say: "Three? I can barely see tonight." },
      { by: 'a', say: "Tonight's easy, but after that the big ones start getting scared, and that's when we pick them off." },
      { by: 'c', say: "And after that?" },
      { by: 'a', say: "After that, it's us. And we'll talk about it then." },
      { by: 'c', say: "That's ominous." },
      { by: 'a', say: "That's honest." },
      { by: 'b', conf: "{a} has the next three votes planned. At some point, one of the names on that plan is going to be mine or {c}'s. I'm trying not to think about it.", v: { dry: "{a} planned three votes ahead. My name is probably on vote four.", warm: "I trust {a}. I just hope {a} trusts us back when the plan runs out." } },
    ] },
  ],
  'long.talk.game.any': [
    { id: 'ng.g1', place: 'aside', when: { third: true }, turns: [
      { beat: "{a}, {b} and {c} are sitting {here}, comparing notes." },
      { by: 'a', say: "Okay. Who's running this place?", v: { loud: "Okay, real question! Who's running this place?!", nerdy: "Let's be analytical. Who actually holds the power here?", teen: "Okay but who's actually running things here?" } },
      { by: 'b', say: "Honestly? Nobody, but everybody thinks they are." },
      { by: 'c', say: "I think it's whoever's quietest. The quiet ones always know the most." },
      { by: 'a', say: "So who's quiet?" },
      { by: 'c', say: "Not us. We've been talking for ten minutes." },
      { by: 'b', say: "Then let's stop talking and start watching." },
      { by: 'c', conf: "We spent the whole afternoon working out who's in charge. We didn't get an answer. We did all agree it isn't any of us, which is the right answer to give.", v: { schemer: "We all agreed it isn't any of us. Which is exactly what someone in charge would say.", goofy: "We talked for hours and figured out that nobody knows anything, so... great meeting, I guess." } },
    ] },
    { id: 'ng.g2', place: 'secret', when: { third: true, threat: true }, turns: [
      { by: 'a', say: "Has anybody else noticed {threat} hasn't lost a thing?", v: { competitive: "Is it just me, or does {threat} win literally everything?", anxious: "Has anyone else noticed {threat} never loses? Because I've noticed, like, a lot.", blunt: "{threat} wins everything. We need to talk about it." } },
      { by: 'b', say: "Everybody's noticed." },
      { by: 'c', say: "We need {threat} for the challenges, though." },
      { by: 'a', say: "Until the merge. After that, {threat} wins immunity every week and the rest of us fight over who goes." },
      { by: 'b', say: "So we do it right before the merge." },
      { by: 'c', say: "And if we do it too early, we lose every challenge and one of us goes." },
      { by: 'a', say: "Then we do it at exactly the right time, all together, and nobody goes off on their own." },
      { by: 'b', conf: "Three of us, all thinking about {threat}. That's three votes {threat} doesn't know about yet.", v: { cruel: "{threat} has no idea three of us want {threat} gone. Good.", warm: "I like {threat}. I just like staying here more." } },
    ] },
    { id: 'ng.g3', place: 'fire', when: { fourth: true }, turns: [
      { by: 'b', say: "Okay, here's a question. If the teams merged tomorrow, who's in trouble?", v: { nerdy: "Hypothetical: the teams merge tomorrow. Who's most at risk?", loud: "Okay, okay! If we merged tomorrow, who's toast?" } },
      { by: 'a', say: "Whoever's loudest." },
      { by: 'c', say: "Whoever has a showmance." },
      { by: 'd', say: "Whoever's won the most." },
      { by: 'b', say: "So, not us." },
      { by: 'a', say: "Not us, as long as we stay boring." },
      { by: 'd', say: "I can be boring. I'm great at boring." },
      { by: 'c', conf: "Our whole strategy is to be the most boring group in the game. It might actually work.", v: { dry: "Our strategy is to be boring. Finally, something I'm good at.", competitive: "I hate it, but boring wins games, so I'm going to be boring." } },
    ] },
  ],
  'long.talk.checkin.any': [
    { id: 'ng.c1', place: 'secret', when: { third: true }, turns: [
      { by: 'a', say: "Quick check. We're all still good?", v: { anxious: "Sorry, I just need to check, we're all still good, right?", bossy: "Quick check-in, is everybody still with us? I want to hear you say it.", calm: "Just checking in. All good?" } },
      { by: 'b', say: "Good." },
      { by: 'c', say: "Good. Somebody came to me this morning asking questions, though." },
      { by: 'a', say: "Who?" },
      { by: 'c', say: "It doesn't matter, I didn't tell them anything, I just wanted you to know people are asking." },
      { by: 'b', say: "That means somebody's counting votes." },
      { by: 'a', say: "Then we count ours first." },
      { by: 'c', conf: "We check in every day. It sounds paranoid. It's the only reason we still know where everybody stands.", v: { dry: "We do check-ins every day now, which is very paranoid, but hey, we're all still here.", warm: "Checking in every day feels like having a family here." } },
    ] },
    { id: 'ng.c2', place: 'water', when: { fourth: true }, turns: [
      { beat: "{a}, {b}, {c} and {d} wade into the water {here}, where nobody can hear them." },
      { by: 'd', say: "This is the weirdest meeting place yet.", v: { loud: "Why are we meeting IN the water?!", dry: "Ah, the wet meeting. My favourite.", goofy: "Is this a meeting or a swim lesson?" } },
      { by: 'a', say: "Nobody follows you into the water. Everybody good?" },
      { by: 'b', say: "Good." },
      { by: 'c', say: "Good." },
      { by: 'd', say: "Good, but I'm getting cold." },
      { by: 'a', say: "Then I'll be quick. Same plan as yesterday, and if anybody hears anything, we come straight back here." },
      { by: 'd', conf: "Our alliance meets in the water now. That's where we are in this game.", v: { anxious: "We meet in the water so nobody can hear. What happens when someone learns to swim over?", teen: "We have alliance meetings in the water now, which is so weird, but honestly I kind of love it." } },
    ] },
  ],
  'long.talk.scramble.any': [
    { id: 'ng.s1', place: 'aside', when: { third: true }, turns: [
      { beat: "{a} finds {b} and {c} together {here} and doesn't waste a second." },
      { by: 'a', say: "Both of you. Please. Two minutes.", v: { loud: "Both of you! Please! Two minutes, that's all!", anxious: "Can I, um, can I talk to you both? Please? Just for a second?", schemer: "Hey, you two, can I talk to you for a minute? You're going to want to hear this." } },
      { by: 'b', say: "What's going on?" },
      { by: 'a', say: "My name's out there, I can feel it, and I just need two votes to make it close." },
      { by: 'c', say: "Close doesn't save you." },
      { by: 'a', say: "Close makes people nervous. Nervous people change their minds." },
      { by: 'b', say: "And what do we get?" },
      { by: 'a', say: "Me, on your side, for the rest of the game." },
      { by: 'c', say: "We'll think about it." },
      { by: 'b', conf: "{a} pitched both of us at once, which is either really desperate or really smart. Maybe both, honestly.", v: { dry: "{a} pitched us both at once. Points for efficiency.", warm: "I felt bad for {a}. I also didn't promise anything." } },
      { by: 'a', conf: "If I talk to them together, they can't tell each other different stories about what I said. Smart. Hopefully." },
    ] },
  ],
};
