// ══════════════════════════════════════════════════════════════════════
// td/story/lines/n-group4.js — the big group scenes, for three to six people
// ══════════════════════════════════════════════════════════════════════
//
// camp-events.js _crowdScenes invites more people to its group moments (data.with: the lead's
// closest, the rest of an alliance), up to six. These scenes play with any of them: the lines for
// d, e and f are optional (opt: true) and drop out cleanly when that person isn't there, so the
// conversation reads whole at every size. Required parts follow the engine's cast (a, b, c; for
// crowd.project and crowd.banter a to d).
//   crowd.meal    breakfast, a the most sociable          crowd.dinner  the evening meal
//   crowd.chores  a leads the work                        crowd.project a takes charge, b pushes back
//   crowd.banter  safe tonight, unwinding                 crowd.won     back from a win, a scored most
//   crowd.lost    back from a loss: a blames b (lowest score), c stands up for b
//   crowd.huddle  {group} closes ranks before the vote   crowd.nerves  the team waiting to vote
// Ids: 'nl.'.

const O = (by, say) => ({ by, say, opt: true });

export default {
  'long.crowd.meal.any': [
    { id: 'nl.m1', place: 'eat', turns: [
      { beat: "Breakfast {here}. The team squeezes in around the table." },
      { by: 'a', say: "Morning, everybody! How did we sleep?" },
      { by: 'b', say: "I didn't." },
      { by: 'c', say: "Something was crawling on me all night." },
      O('d', "That was me. Sorry. The floor is lumpy."),
      { by: 'a', say: "Okay. So, terrible. Great. Same as every morning." },
      O('e', "Is anybody going to eat that?"),
      { by: 'b', say: "Take it. I've lost my appetite." },
      O('f', "What do we think today's challenge is?"),
      { by: 'c', say: "Something with mud. It's always something with mud." },
      { by: 'a', conf: "Breakfast is the one time we're all just people. Then the challenge starts and we're not." },
    ] },
    { id: 'nl.m2', place: 'eat', when: { lastBoot: true }, turns: [
      { beat: "Breakfast {here}. Nobody sits in the spot where {lastBoot} used to." },
      { by: 'b', say: "It's weird without {lastBoot}." },
      { by: 'a', say: "It's quieter." },
      O('d', "Too quiet."),
      { by: 'c', say: "Are we going to talk about it?" },
      O('e', "Talk about what? It's a game. People leave."),
      { by: 'a', say: "We don't have to talk about it. We just have to make sure it doesn't happen again for a while." },
      O('f', "Then we'd better win today."),
      { by: 'c', conf: "Everybody's acting normal. Nobody's acting normal. One of the people at this table wrote {lastBoot}'s name." },
    ] },
    { id: 'nl.m3', place: 'eat', when: { voice: ['goofy', 'food', 'chaotic', 'loud', 'theatrical'] }, turns: [
      { by: 'a', say: "Okay! Ranking the food. Worst to least worst. Everybody gets one vote." },
      { by: 'b', say: "We are not doing this." },
      { by: 'c', say: "Today's. Today's is the worst." },
      O('d', "Day two. Day two moved."),
      { by: 'a', say: "Thank you! Day two moved!" },
      O('e', "It didn't move." ),
      O('f', "It moved. I saw it."),
      { by: 'b', say: "Fine. Day two. Can I eat now?" },
      { by: 'b', conf: "{a} turns every meal into a show. I complain about it every time. Breakfast would be so boring without it." },
    ] },
  ],
  'long.crowd.dinner.any': [
    { id: 'nl.d1', place: 'eat', turns: [
      { beat: "Dinner {here}. Everyone is too tired to talk much." },
      { by: 'a', say: "What a day." },
      { by: 'b', say: "What a terrible day." },
      O('d', "I can't feel my legs."),
      { by: 'c', say: "Is it over? Please tell me it's over." },
      { by: 'a', say: "It's over. We just have to eat this." },
      O('e', "Then it's not over."),
      O('f', "Hey, at least it's warm. Ish."),
      { by: 'b', conf: "Nights like this, I actually like these people. Then breakfast comes and we're back to plotting." },
    ] },
    { id: 'nl.d2', place: 'eat', when: { tribal: true }, turns: [
      { by: 'b', say: "So nobody's going to say it?" },
      { by: 'a', say: "Say what?" },
      { by: 'b', say: "That one of us is going home tonight, and we're all just eating like it's fine." },
      O('d', "What do you want us to do? Not eat?"),
      { by: 'c', say: "I want to eat. I'm going to eat." },
      O('e', "I can't. I'm too nervous."),
      { by: 'a', say: "Fine. This food is terrible and one of us is leaving. Better?" },
      O('f', "...A little, honestly."),
      { by: 'c', conf: "Dinner before a vote is the worst meal of the day. Everybody's smiling at everybody. Nobody means it." },
    ] },
  ],
  'long.crowd.chores.any': [
    { id: 'nl.c1', place: 'work', turns: [
      { beat: "Morning chores {here}. {a} hands out the jobs." },
      { by: 'a', say: "{b}, water. {c}, firewood." },
      O('d', "What about me?"),
      O('d', "Don't say latrine. Please don't say latrine."),
      { by: 'a', say: "Everybody else, help where it's needed." },
      O('e', "I'll do water with {b}. It's the easy one."),
      { by: 'b', say: "It's not the easy one. It's heavy." },
      O('f', "I'll take firewood, then."),
      { by: 'c', conf: "Nobody voted {a} in charge of chores. Nobody argued either. That's how it starts." },
    ] },
  ],
  'long.crowd.project.any': [
    { id: 'nl.p1', place: 'work', turns: [
      { beat: "The {quarters} needs fixing, and {a} has decided to be in charge of fixing it." },
      { by: 'a', say: "Okay, listen up. {c}, {d}, branches. {b}, you hold the frame." },
      { by: 'b', say: "Who died and made you leader?" },
      { by: 'a', say: "Nobody. But if nobody says something, we sleep in the rain again." },
      O('e', "I'm not sleeping in the rain again. I'll do whatever {a} says."),
      { by: 'c', say: "Branches are fine. I like branches." },
      { by: 'd', say: "Me too." },
      O('f', "And I'll stay out of the way. That's my job."),
      { by: 'b', say: "Fine. But I'm holding it my way." },
      { beat: "Two hours later, it's standing. Mostly." },
      { by: 'b', conf: "{a} bosses everybody around and it drives me crazy. The worst part? It worked." },
    ] },
    { id: 'nl.p2', place: 'work', when: { voice: ['bossy', 'loud', 'competitive', 'tough'] }, turns: [
      { by: 'a', say: "Team meeting! Right now! Everybody!" },
      { by: 'd', say: "It's seven in the morning." },
      { by: 'a', say: "Exactly. The other team is still asleep. That's how we beat them." },
      { by: 'b', say: "We're not beating anybody by fixing a fire pit." },
      O('e', "We might be. Their fire pit is terrible."),
      { by: 'a', say: "Thank you! You're on rocks, {b}." },
      { by: 'b', say: "I'm not taking orders from you." },
      { by: 'c', say: "I'll do rocks. Can we just get it done?" },
      O('f', "Can we get it done after breakfast?"),
      { by: 'a', say: "After. See? That's teamwork." },
      { by: 'c', conf: "Every morning it's {a} giving orders and {b} saying no. The rest of us just pick up rocks." },
    ] },
  ],
  'long.crowd.banter.any': [
    { id: 'nl.b1', place: 'fire', turns: [
      { beat: "No vote tonight. The team sits around the fire with nothing to plot." },
      { by: 'a', say: "Okay. One thing you miss from home. Go." },
      { by: 'b', say: "My bed. My actual bed." },
      { by: 'c', say: "Food that doesn't move." },
      { by: 'd', say: "My dog. My dog would hate it here." },
      O('e', "My dog would love it here. He'd eat the food."),
      { by: 'a', say: "That's disgusting." },
      O('e', "He's a very brave dog."),
      O('f', "I miss being clean. Just, generally."),
      { beat: "Everybody laughs. Nobody wants to go to bed." },
      { by: 'c', conf: "I didn't come here for friends. I've got a whole fire full of them now. That's going to make voting really hard." },
    ] },
    { id: 'nl.b2', place: 'fire', turns: [
      { by: 'c', say: "Real question. If {host} had to do one of our challenges, which one?" },
      { by: 'a', say: "The worst one. Obviously." },
      { by: 'd', say: "And we get to watch." },
      { by: 'b', say: "And make fun of the hair." },
      O('e', "Nobody touches the hair."),
      O('f', "Somebody has to touch the hair eventually."),
      { beat: "Everybody laughs." },
      { by: 'd', conf: "We spent twenty minutes planning revenge on {host}. It's never going to happen. Best twenty minutes of my week." },
    ] },
  ],
  'long.crowd.won.any': [
    { id: 'nl.w1', place: 'public', turns: [
      { beat: "The team comes back {here} cheering. {a} is the one everybody wants to high-five." },
      { by: 'b', say: "Did you see {a} out there?" },
      { by: 'c', say: "Everybody saw {a} out there!" },
      O('d', "MVP! MVP!"),
      { by: 'a', say: "Stop. It was all of us." },
      O('e', "It was mostly you." ),
      { by: 'b', say: "No vote tonight! Nobody goes home!" },
      O('f', "I'm going to sleep for twelve hours."),
      { by: 'a', conf: "Winning feels amazing. Being the reason we won is better. It's also exactly how you become a target later." },
    ] },
    { id: 'nl.w2', place: 'public', when: { voice: ['loud', 'proud', 'competitive', 'theatrical'] }, turns: [
      { by: 'a', say: "Who won it? WE won it!" },
      { by: 'b', say: "We heard you the first five times." },
      { by: 'c', say: "Let {a} have it. {a} earned it." },
      O('d', "Can I have it a little bit too? I carried the rope."),
      { by: 'a', say: "Everybody can have it! Tonight we're all winners!" },
      O('e', "That's so corny."),
      O('f', "Corny and safe. I'll take it."),
      { by: 'b', conf: "{a} is going to be unbearable tonight. I don't care. We're not voting anybody out." },
    ] },
    { id: 'nl.w3', place: 'fire', turns: [
      { by: 'c', say: "So. That's two in a row. Or one. Whatever. It felt like two." },
      { by: 'a', say: "Don't jinx it." },
      { by: 'b', say: "It's not a jinx. We're just good." },
      O('d', "We're not that good. We got lucky on the last part."),
      O('e', "Lucky still counts."),
      { by: 'a', say: "Lucky absolutely counts." },
      O('f', "Can we just be happy for one night?"),
      { by: 'c', conf: "The other team is picking someone to send home right now. We're sitting by the fire. That feeling never gets old." },
    ] },
  ],
  'long.crowd.lost.any': [
    { id: 'nl.l1', place: 'public', turns: [
      { beat: "The team drags itself back {here}. Nobody looks at anybody." },
      { by: 'a', say: "Well, I'm just going to say it. We lost that because of {b}." },
      { by: 'b', say: "Wow. Okay." },
      { by: 'c', say: "Hey. Back off. We all lost it." },
      O('d', "{b} did come last, though."),
      { by: 'c', say: "And who was yelling the whole time instead of helping?" },
      O('e', "Can we not do this right now?"),
      { by: 'a', say: "When should we do it? After the vote?" },
      O('f', "Maybe. Yeah. After the vote sounds good."),
      { by: 'b', conf: "{a} needed somebody to blame and I was right there. At least {c} stood up for me." },
      { by: 'c', conf: "{b} had a bad day. {a} had a bad attitude. I know which one I'd rather keep." },
    ] },
    { id: 'nl.l2', place: 'public', when: { voice: ['loud', 'tough', 'blunt', 'cruel'] }, turns: [
      { by: 'a', say: "Are we going to pretend that didn't happen? {b}, you froze." },
      { by: 'b', say: "I didn't freeze. I slipped." },
      { by: 'a', say: "For a whole minute?" },
      O('d', "It was kind of a long slip."),
      { by: 'c', say: "Seriously? You're ganging up on {b} now?" },
      O('e', "Nobody's ganging up. We're just upset."),
      { by: 'c', say: "Then be upset at the challenge. Not at a person." },
      O('f', "I'm upset at everything. Is that allowed?"),
      { by: 'a', conf: "Somebody has to say it, or we keep losing. Fine. I'll be the bad guy." },
    ] },
    { id: 'nl.l3', place: 'aside', turns: [
      { by: 'c', say: "Okay. Everybody take a breath." },
      { by: 'a', say: "I'm breathing. I'm also annoyed." },
      { by: 'b', say: "I know it was me. You don't have to say it." },
      O('d', "It wasn't only you."),
      { by: 'c', say: "It was all of us. And whoever goes tonight, it's going to be because of a vote, not one mistake." },
      O('e', "That's very wise. I hate it."),
      O('f', "Can we talk about it later? I just want to sit down."),
      { by: 'b', conf: "Everyone knows I lost it for us. {c} is the only one making it feel survivable." },
    ] },
  ],
  'long.crowd.huddle.any': [
    { id: 'nl.h1', place: 'secret', turns: [
      { beat: "{group} meets at {place}. Everybody who's in it shows up." },
      { by: 'a', say: "Okay. Is everybody here?" },
      { by: 'b', say: "Everybody's here." },
      O('d', "Where's... oh. Sorry. You're there."),
      { by: 'a', say: "Same name tonight. Nobody goes off on their own." },
      { by: 'c', say: "And if somebody comes to one of us with a different name?" },
      { by: 'a', say: "Then you bring it here. To all of us." },
      O('e', "No side deals."),
      O('f', "No side deals. Agreed."),
      { by: 'c', conf: "Being in a group this big feels safe. It also means there are a lot of people who could break it." },
    ] },
    { id: 'nl.h2', place: 'secret', when: { voice: ['warm', 'earnest', 'emotional'] }, turns: [
      { beat: "{group} sits in a circle at {place}." },
      { by: 'a', say: "Whatever happens tonight, we're still us. Okay?" },
      { by: 'b', say: "Okay." },
      O('d', "Are we doing a hand thing?"),
      { by: 'a', say: "We're doing a hand thing." },
      { beat: "They stack their hands. Somebody laughs." },
      O('e', "This is so corny."),
      O('f', "You put your hand in, though."),
      { by: 'c', conf: "{group} is the only part of this game that feels real. I really hope we all get through tonight." },
    ] },
    { id: 'nl.h3', place: 'secret', when: { voice: ['bossy', 'schemer', 'calm', 'competitive'] }, turns: [
      { by: 'a', say: "Let's go around. Everybody tells me what they've heard today." },
      { by: 'b', say: "People are nervous. Nobody's said a name to me." },
      { by: 'c', say: "I heard one name. Twice." },
      O('d', "Same one?"),
      { by: 'c', say: "Same one." },
      O('e', "Then that's the name we watch."),
      O('f', "Or the name we use."),
      { by: 'a', say: "We'll decide together. Not here. Later, one at a time." },
      { by: 'b', conf: "{a} runs these meetings like a general. It's a little scary. It also keeps us alive." },
    ] },
  ],
  'long.crowd.nerves.any': [
    { id: 'nl.n1', place: 'fire', turns: [
      { beat: "The team waits by the fire to go to the vote. Nobody says much." },
      { by: 'b', say: "I hate this part." },
      { by: 'a', say: "The waiting?" },
      { by: 'b', say: "The waiting, and the pretending we're all fine." },
      { by: 'c', say: "I'm fine." },
      O('d', "You've been tapping your foot for ten minutes."),
      O('e', "We're all tapping something."),
      { by: 'c', say: "I'm fine with tapping." },
      { by: 'a', conf: "One of the people at this fire is going home tonight. Everybody's looking at the fire so nobody has to look at each other." },
    ] },
  ],
};
