// ══════════════════════════════════════════════════════════════════════
// td/story/lines/n-group.js — strategy talks as group conversations
// ══════════════════════════════════════════════════════════════════════
//
// When the person who starts a strategy talk works in groups (director.js shapeFor), the friends
// a and b share join it as c (and d). Same keys as n-talk.js: talk.plan (map / plain / quiet),
// talk.game, talk.checkin, talk.scramble. Everyone here is on the same side, so nobody hears
// anything they shouldn't. Ids: 'ng.'.

export default {
  'long.talk.plan.any': [
    { id: 'ng.p1', place: 'secret', when: { third: true }, turns: [
      { beat: "{a}, {b} and {c} meet at {place}, the way they've started doing every afternoon." },
      { by: 'a', say: "Okay. What's everybody heard?" },
      { by: 'b', say: "People are nervous. Nobody's saying a name yet." },
      { by: 'c', say: "I heard one name. Twice. I'm not saying it until I hear it a third time." },
      { by: 'a', say: "That's fair. Whose name?" },
      { by: 'c', say: "Third time." },
      { by: 'b', say: "So we wait?" },
      { by: 'a', say: "We wait, we listen, and we don't say anything first. Whoever says a name first becomes the next name." },
      { by: 'c', conf: "The three of us tell each other everything. It's the only reason I sleep at night." },
    ] },
    { id: 'ng.p2', place: 'sleep', when: { fourth: true }, turns: [
      { beat: "{a}, {b}, {c} and {d} are in the {quarters}, keeping their voices down." },
      { by: 'd', say: "Should we really be doing this in here?" },
      { by: 'a', say: "Everybody else is out. We've got a few minutes." },
      { by: 'b', say: "So what's the plan? We keep winning, nobody goes home. We lose..." },
      { by: 'c', say: "We lose, and it's not one of us four. That's the plan." },
      { by: 'a', say: "Right. And we don't fight about who goes next until we have to." },
      { by: 'd', say: "And if somebody comes to one of us with a deal?" },
      { by: 'a', say: "Then you bring it here. To all of us. No side deals." },
      { by: 'b', say: "No side deals." },
      { by: 'd', conf: "Four of us, sitting on {bed}s, promising no side deals. Somebody in this room is going to make one. I just hope it's not about me." },
    ] },
    { id: 'ng.p3', place: 'fire', when: { third: true, voice: ['warm', 'earnest', 'emotional'] }, turns: [
      { by: 'a', say: "Can we just check in? As people, I mean. Not as votes." },
      { by: 'b', say: "That's very you." },
      { by: 'a', say: "I know. But this place is making me crazy, and you two are the only ones I can talk to." },
      { by: 'c', say: "Same. I've said 'I'm fine' about forty times today." },
      { by: 'b', say: "Okay. Then also as votes, since we're here. We're together, right?" },
      { by: 'a', say: "We're together." },
      { by: 'c', say: "Together." },
      { by: 'a', conf: "I don't care if it's corny. Knowing two people have my back is the only thing keeping me going here." },
    ] },
    { id: 'ng.p4', place: 'work', when: { third: true, tribal: true }, turns: [
      { beat: "{a}, {b} and {c} are pretending to gather wood {here}. They aren't gathering much." },
      { by: 'b', say: "We need a name for tonight." },
      { by: 'a', say: "We need a name that isn't one of us. That's the only rule." },
      { by: 'c', say: "Everybody else is saying a name. We just don't know whose." },
      { by: 'a', say: "Then we split up. Each of us talks to one person. We meet back here before dinner." },
      { by: 'b', say: "And if we hear our own names?" },
      { by: 'a', say: "Then we run. Back here. Fast." },
      { by: 'c', conf: "We have a system now. Three of us, three conversations, one name by dinner. That's the most organised I've felt since I got here." },
    ] },
  ],
  'long.talk.plan.map': [
    { id: 'ng.m1', place: 'secret', when: { fourth: true }, turns: [
      { beat: "{a} draws in the dirt with a stick. {b}, {c} and {d} crouch around it." },
      { by: 'a', say: "These are us. These are them. These are the ones nobody's got yet." },
      { by: 'c', say: "That's a lot of 'nobody's got yet'." },
      { by: 'a', say: "That's where we win. We get two of them, and we have the numbers every vote until the merge." },
      { by: 'd', say: "Which two?" },
      { by: 'a', say: "Whoever likes us most. {b}, you're good with people. You take one. {c}, you take the other." },
      { by: 'b', say: "And what do you do?" },
      { by: 'a', say: "I keep everybody from noticing we're doing it." },
      { by: 'd', say: "And me?" },
      { by: 'a', say: "You keep winning challenges. Nobody votes out the person they need." },
      { by: 'd', conf: "{a} had the whole game drawn in the dirt in two minutes. I'm glad I'm in the circle and not one of the scribbles." },
    ] },
    { id: 'ng.m2', place: 'aside', when: { third: true }, turns: [
      { by: 'a', say: "Here's how I see the next three votes." },
      { by: 'b', say: "Three? I can barely see tonight." },
      { by: 'a', say: "Tonight's easy. After that, the big ones start getting scared. That's when we pick them off." },
      { by: 'c', say: "And after that?" },
      { by: 'a', say: "After that, it's us. And we'll talk about it then." },
      { by: 'c', say: "That's ominous." },
      { by: 'a', say: "That's honest." },
      { by: 'b', conf: "{a} has the next three votes planned. At some point, one of the names on that plan is going to be mine or {c}'s. I'm trying not to think about it." },
    ] },
  ],
  'long.talk.game.any': [
    { id: 'ng.g1', place: 'aside', when: { third: true }, turns: [
      { beat: "{a}, {b} and {c} are sitting {here}, comparing notes." },
      { by: 'a', say: "Okay. Who's running this place?" },
      { by: 'b', say: "Honestly? Nobody. Everybody thinks they are." },
      { by: 'c', say: "I think it's whoever's quietest. The quiet ones always know the most." },
      { by: 'a', say: "So who's quiet?" },
      { by: 'c', say: "Not us. We've been talking for ten minutes." },
      { by: 'b', say: "Then let's stop talking and start watching." },
      { by: 'c', conf: "We spent the whole afternoon working out who's in charge. We didn't get an answer. We did all agree it isn't any of us, which is the right answer to give." },
    ] },
    { id: 'ng.g2', place: 'secret', when: { third: true, threat: true }, turns: [
      { by: 'a', say: "Has anybody else noticed {threat} hasn't lost a thing?" },
      { by: 'b', say: "Everybody's noticed." },
      { by: 'c', say: "We need {threat} for the challenges, though." },
      { by: 'a', say: "Until the merge. After that, {threat} wins immunity every week and the rest of us fight over who goes." },
      { by: 'b', say: "So we do it right before the merge." },
      { by: 'c', say: "And if we do it too early, we lose every challenge and one of us goes." },
      { by: 'a', say: "Then we do it at exactly the right time. Together. Nobody moves alone." },
      { by: 'b', conf: "Three of us, all thinking about {threat}. That's three votes {threat} doesn't know about yet." },
    ] },
    { id: 'ng.g3', place: 'fire', when: { fourth: true }, turns: [
      { by: 'b', say: "Okay, here's a question. If the teams merged tomorrow, who's in trouble?" },
      { by: 'a', say: "Whoever's loudest." },
      { by: 'c', say: "Whoever has a showmance." },
      { by: 'd', say: "Whoever's won the most." },
      { by: 'b', say: "So, not us." },
      { by: 'a', say: "Not us, as long as we stay boring." },
      { by: 'd', say: "I can be boring. I'm great at boring." },
      { by: 'c', conf: "Our whole strategy is to be the most boring group in the game. It might actually work." },
    ] },
  ],
  'long.talk.checkin.any': [
    { id: 'ng.c1', place: 'secret', when: { third: true }, turns: [
      { by: 'a', say: "Quick check. We're all still good?" },
      { by: 'b', say: "Good." },
      { by: 'c', say: "Good. Somebody came to me this morning asking questions, though." },
      { by: 'a', say: "Who?" },
      { by: 'c', say: "Doesn't matter. I didn't tell them anything. I just wanted you to know they're asking." },
      { by: 'b', say: "That means somebody's counting votes." },
      { by: 'a', say: "Then we count ours first." },
      { by: 'c', conf: "We check in every day. It sounds paranoid. It's the only reason we still know where everybody stands." },
    ] },
    { id: 'ng.c2', place: 'water', when: { fourth: true }, turns: [
      { beat: "{a}, {b}, {c} and {d} wade into the water {here}, where nobody can hear them." },
      { by: 'd', say: "This is the weirdest meeting place yet." },
      { by: 'a', say: "Nobody follows you into the water. Everybody good?" },
      { by: 'b', say: "Good." },
      { by: 'c', say: "Good." },
      { by: 'd', say: "Good, but I'm getting cold." },
      { by: 'a', say: "Then I'll be quick. Same plan as yesterday. If anybody hears anything, we come back here." },
      { by: 'd', conf: "Our alliance meets in the water now. That's where we are in this game." },
    ] },
  ],
  'long.talk.scramble.any': [
    { id: 'ng.s1', place: 'aside', when: { third: true }, turns: [
      { beat: "{a} finds {b} and {c} together {here} and doesn't waste a second." },
      { by: 'a', say: "Both of you. Please. Two minutes." },
      { by: 'b', say: "What's going on?" },
      { by: 'a', say: "My name's out there. I can feel it. I need two votes to make it close." },
      { by: 'c', say: "Close doesn't save you." },
      { by: 'a', say: "Close makes people nervous. Nervous people change their minds." },
      { by: 'b', say: "And what do we get?" },
      { by: 'a', say: "Me. On your side. For the rest of the game." },
      { by: 'c', say: "We'll think about it." },
      { by: 'b', conf: "{a} pitched both of us at once. That's either really desperate or really smart. Maybe both." },
      { by: 'a', conf: "If I talk to them together, they can't tell each other different stories about what I said. Smart. Hopefully." },
    ] },
  ],
};
