// ══════════════════════════════════════════════════════════════════════
// td/story/lines/n-group2.js — camp moments that grow past two people
// ══════════════════════════════════════════════════════════════════════
//
// director.js PULL: a friendship moment started by someone who works in groups takes in the
// friends a and b share (c, and d); a fight in front of camp takes in c, b's closest friend, who
// is on b's side; an alliance wobbling takes in c, an ally of both. Same meaning as the pair
// versions (n-drama.js, n-camp.js). Ids: 'nh.'.

export default {
  'long.friend.bond.any': [
    { id: 'nh.b1', place: 'water', when: { third: true }, turns: [
      { beat: "{a}, {b} and {c} are supposed to be fishing {here}. Nobody has caught anything." },
      { by: 'c', say: "I think the fish are avoiding us specifically.", v: { dry: "The fish have clearly been warned about us.", goofy: "I think the fish formed an alliance against us.", nerdy: "Statistically, we should have caught something by now. The fish are cheating." } },
      { by: 'a', say: "They heard about {b}'s singing." },
      { by: 'b', say: "My singing is great." },
      { by: 'c', say: "Your singing is why there are no fish." },
      { by: 'b', say: "Fine, no singing. We'll just sit here in total silence and keep catching nothing." },
      { by: 'a', say: "Honestly? Best afternoon I've had here." },
      { by: 'c', say: "Same." },
      { by: 'b', conf: "We didn't catch a single fish. I've got two friends I'd go to the end with. Fair trade.", v: { emotional: "We didn't catch any fish, but I've got two best friends now, and I'm going to cry about that, not the fish.", tough: "No fish, but good company, so I'll take it." } },
    ] },
    { id: 'nh.b2', place: 'fire', when: { fourth: true }, turns: [
      { beat: "Late, {here}. {a}, {b}, {c} and {d} are the last ones still up." },
      { by: 'd', say: "Okay, everybody has to say one thing they miss from home. Go.", v: { warm: "Okay, what's one thing you miss from home? I'll go first if you want.", loud: "Okay, okay, what do you miss most from home? GO!", teen: "Okay, what do you miss most? Besides your phone." } },
      { by: 'a', say: "My bed. My actual bed." },
      { by: 'b', say: "Food that doesn't move." },
      { by: 'c', say: "My dog. My dog would hate it here." },
      { by: 'd', say: "My dog would love it here. He'd eat the food." },
      { by: 'a', say: "That's disgusting." },
      { by: 'd', say: "He's a very brave dog." },
      { beat: "Everybody laughs. Nobody wants to go to bed." },
      { by: 'c', conf: "I didn't come here to make friends, and now I've got three, which is going to make voting really hard.", v: { schemer: "I've got three friends now, which means three people I'm going to have to vote out eventually. Great.", warm: "I have three friends here, three, and I don't ever want to vote any of them out." } },
    ] },
    { id: 'nh.b3', place: 'work', when: { third: true }, turns: [
      { beat: "{a}, {b} and {c} are doing the chores nobody else wanted {here}." },
      { by: 'a', say: "How did we end up on this again?", v: { dry: "How do we keep getting the worst jobs? Is it a talent?", tough: "Why is it always us? Whatever, let's just do it." } },
      { by: 'b', say: "We're the only ones who didn't run when we saw the bucket." },
      { by: 'c', say: "I didn't run because I didn't see the bucket." },
      { by: 'a', say: "So you're here by accident." },
      { by: 'c', say: "I'm always here by accident. That's my whole game." },
      { by: 'b', conf: "Every time there's a bad job, it's the three of us. I'm starting to think that's not a coincidence. I'm starting to think we just like each other.", v: { anxious: "We always end up together, so... is that a friendship? I think that's a friendship.", grown: "The ones who do the dirty work together tend to stick together. Always been true." } },
    ] },
  ],
  'long.friend.goof.any': [
    { id: 'nh.g1', place: 'public', when: { third: true }, turns: [
      { beat: "{a} has found a stick {here} and declared it a microphone." },
      { by: 'a', say: "Welcome back to the show! I'm here with two of our contestants, so tell me, how are you feeling?", v: { theatrical: "Live from the most glamorous place on Earth! How are our stars feeling today?", goofy: "Ladies and gentlemen, today's guests are two very smelly people! How are we doing?" } },
      { by: 'b', say: "Hungry, tired, smelly." },
      { by: 'c', say: "Mostly smelly." },
      { by: 'a', say: "Incredible answers. And who do you think is going home next?" },
      { by: 'b', say: "The microphone." },
      { by: 'c', say: "Definitely the microphone." },
      { by: 'a', conf: "We do a fake talk show every afternoon now. It's the stupidest thing ever. It's my favourite part of the day.", v: { dry: "Our fake talk show has terrible ratings, like one viewer, and it's me.", teen: "We do a fake talk show every day now and it's so dumb, but I love it so much." } },
    ] },
    { id: 'nh.g2', place: 'sleep', when: { fourth: true }, turns: [
      { beat: "Lights out in the {quarters}. Somebody giggles. Then all four of them are giggling." },
      { by: 'a', say: "Stop, stop, people are trying to sleep." },
      { by: 'b', say: "You started it!" },
      { by: 'c', say: "Who made that noise?" },
      { by: 'd', say: "...That was me. Sorry, it was my stomach." },
      { beat: "It gets much worse." },
      { by: 'b', conf: "We got told to shut up by the entire {quarters}. Worth it.", v: { anxious: "Everybody yelled at us and I feel bad, but I'm still laughing.", grown: "I'm far too old to be shushed. I loved it." } },
    ] },
  ],
  'long.friend.joke.any': [
    { id: 'nh.j1', place: 'public', when: { third: true }, turns: [
      { by: 'a', say: "Good morning, your majesty.", v: { dry: "Good morning, your highness. Your throne is a log again.", theatrical: "All rise! Her majesty has awoken!", goofy: "Good morning, your majesty! Your royal breakfast is... well, it's slop again." } },
      { by: 'b', say: "Good morning, peasant." },
      { by: 'c', say: "Can I be a duke yet?" },
      { by: 'b', say: "You have to earn duke." },
      { by: 'c', say: "I carried the water for three days!" },
      { by: 'a', say: "Fine. Duke of water." },
      { by: 'c', say: "I'll take it." },
      { by: 'c', conf: "I don't remember how this started. Now we have a whole royal family. I'm the Duke of Water. It's the best title I've ever had." },
    ] },
  ],
  'long.friend.sunrise.any': [
    { id: 'nh.s1', place: 'water', when: { third: true }, turns: [
      { beat: "Early. {a}, {b} and {c} are the only ones awake, sitting {here}." },
      { by: 'c', say: "Did either of you sleep?", v: { anxious: "Did anyone sleep? Because I didn't sleep at all.", dry: "So. Who got the full zero hours?", calm: "Sleep okay?" } },
      { by: 'a', say: "Not really." },
      { by: 'b', say: "Something was crawling on me all night." },
      { by: 'c', say: "That was me, sorry, the ground is really lumpy." },
      { beat: "They watch the light come up. Nobody says anything for a while." },
      { by: 'a', conf: "Twenty minutes every morning where nobody's playing the game. I'm going to miss that more than anything.", v: { warm: "These mornings are my favourite part of this whole thing.", quiet: "Mornings like this are good. Quiet." } },
    ] },
  ],
  'long.friend.struggle.any': [
    { id: 'nh.t1', place: 'work', when: { third: true }, turns: [
      { beat: "{a}, {b} and {c} are the last three still working {here}. All of them are exhausted." },
      { by: 'b', say: "I can't feel my arms.", v: { loud: "I CAN'T FEEL MY ARMS!", dry: "I think my arms quit. I don't blame them.", grown: "My arms are not what they used to be." } },
      { by: 'c', say: "I can't feel anything below my neck." },
      { by: 'a', say: "Five more minutes." },
      { by: 'b', say: "You said that twenty minutes ago." },
      { by: 'a', say: "And it worked, didn't it?" },
      { by: 'c', say: "Okay, five more minutes, and then we're lying down in the dirt." },
      { by: 'c', conf: "Nobody else stayed to finish, just the three of us, and people remember who stays.", v: { competitive: "We outworked everyone. That's going to matter.", warm: "I'm sore and I'm tired, but I really love these two." } },
    ] },
  ],
  'long.alliance.crack.any': [
    { id: 'nh.k1', place: 'secret', when: { third: true }, turns: [
      { beat: "{a} has asked {b} and {c} to meet at {place}. {a} gets straight to it." },
      { by: 'a', say: "Somebody in {group} has been talking to the other side.", v: { blunt: "Someone in {group} is a snake. Let's figure out who.", anxious: "I think... I think someone in {group} is talking to the other side. And it's freaking me out.", schemer: "Somebody in {group} has been chatting with the enemy. I'd like to know who." } },
      { by: 'b', say: "That's a big thing to say." },
      { by: 'a', say: "It's a big thing to do." },
      { by: 'c', say: "Who?" },
      { by: 'a', say: "I don't know yet. That's why I'm asking you two first." },
      { by: 'b', say: "Wait. You think it's one of us?" },
      { by: 'a', say: "I think it's somebody. I'm starting with the people I trust most and working down." },
      { by: 'c', say: "That's a horrible way to say it." },
      { by: 'c', conf: "{a} just told us we're the most trusted people in {group}, and also suspects. I don't know how to feel about that.", v: { dry: "Most trusted and suspects at the same time. Nice to have range.", emotional: "I'd never betray {group}. I can't believe {a} even thought it." } },
    ] },
  ],

  'long.drama.fight.any': [
    { id: 'nh.f1', place: 'public', when: { third: true }, turns: [
      { beat: "It starts small {here}. It doesn't stay small." },
      { by: 'a', say: "Why do you always do that?", v: { loud: "Why do you ALWAYS do that?!", dry: "Do you practise this, or does it come naturally?", cruel: "Why do you always have to be like this?" } },
      { by: 'b', say: "Do what?" },
      { by: 'a', say: "Act like you're better than everybody. You did it all morning." },
      { by: 'c', say: "Whoa. Where is this coming from?" },
      { by: 'a', say: "Stay out of it, {c}." },
      { by: 'c', say: "No, you're yelling at my friend in front of everybody, so I'm in it now." },
      { by: 'b', say: "It's fine, {c}." },
      { by: 'c', say: "It's not fine." },
      { by: 'a', conf: "Great, now it's two against one, but I'm still right." },
      { by: 'c', conf: "{b} wasn't going to say anything back, so I did, because that's what friends are for.", v: { tough: "Nobody talks to my friends like that.", warm: "{b} is too nice to fight back. So I did it for {b}." } },
    ] },
    { id: 'nh.f2', place: 'public', when: { third: true, voice: ['loud', 'tough', 'blunt', 'cruel'] }, turns: [
      { by: 'a', say: "You've been slacking all day and everybody knows it!" },
      { by: 'b', say: "I've been working as hard as anybody!" },
      { by: 'a', say: "Then why does it look like you're on vacation?" },
      { by: 'c', move: 'defend' },
      { by: 'a', say: "Or what?" },
      { by: 'c', say: "Or you can do {b}'s chores AND yours tomorrow. Since you're so worried about it." },
      { beat: "A couple of people laugh. {a} doesn't." },
      { by: 'b', conf: "{c} had my back without even thinking about it. I'm not going to forget that." },
      { by: 'a', conf: "{b} just hides behind {c}, so fine, now I've got two names to remember." },
    ] },
    { id: 'nh.f3', place: 'eat', when: { third: true }, turns: [
      { beat: "Dinner {here}. {a} and {b} have been snapping at each other since they sat down." },
      { by: 'b', say: "Can you pass the water? Or is that too much to ask?", v: { dry: "Could you pass the water? Or is that above your pay grade?", loud: "Pass the water! Is that SO hard?" } },
      { by: 'a', say: "Everything's too much to ask with you." },
      { by: 'b', say: "Wow." },
      { by: 'c', say: "Can you two not, while we're eating?" },
      { by: 'a', say: "Tell {b}. {b} started it." },
      { by: 'c', say: "I'm telling both of you. I'm telling you more, though." },
      { by: 'c', conf: "I'm on {b}'s side, everybody knows that, and I'm not going to pretend I'm not.", v: { blunt: "I'm on {b}'s side. End of story.", calm: "I'll always back {b}. That's just how it is." } },
    ] },
  ],
  'long.drama.bomb.any': [
    { id: 'nh.m1', place: 'public', when: { third: true }, turns: [
      { beat: "Everyone is {here} when {a} says it." },
      { by: 'a', say: "Let's be honest. Half the people here are only here because somebody's carrying them.", v: { cruel: "Let's be real. Half of you are dead weight and the rest of us are carrying you.", proud: "Some of us are carrying this team, and I won't name names, but it's me." } },
      { by: 'b', say: "Are you talking about me?" },
      { by: 'a', say: "If it fits." },
      { by: 'c', say: "Are you kidding? {b} won us the last challenge." },
      { by: 'a', say: "Once." },
      { by: 'c', say: "Once is more than you." },
      { beat: "Somebody actually goes 'oooh'." },
      { by: 'b', conf: "I didn't even have to answer, because {c} did it for me, and honestly better than I would have." },
      { by: 'a', conf: "I said what everybody was thinking, and nobody else was brave enough to say it. Or dumb enough, one of those.", v: { loud: "Somebody had to say it! I said it!", dry: "I said it out loud. Apparently that's illegal here." } },
    ] },
  ],
  'long.drama.dig.any': [
    { id: 'nh.d1', place: 'eat', when: { third: true }, turns: [
      { by: 'b', say: "I'll do the dishes tonight.", v: { warm: "I'll do the dishes tonight. Everybody relax.", anxious: "I can do the dishes, if that's okay? I'll do the dishes." } },
      { by: 'a', say: "Wow, big day for you. Is that your first chore this week?" },
      { by: 'c', say: "That's not true. {b} did breakfast." },
      { by: 'a', say: "Did {b}? I must have missed it." },
      { by: 'c', say: "You were asleep." },
      { by: 'a', conf: "I make one little comment and {c} comes running, so I guess {b} and {c} are a lot closer than I thought." },
      { by: 'b', conf: "{a} takes shots at me every single day, and today somebody finally shot back, and it felt amazing.", v: { emotional: "I almost cried when {c} defended me. Good tears.", tough: "{a} talks a lot. Today {a} got answered." } },
    ] },
  ],
  'long.drama.clash.any': [
    { id: 'nh.c1', place: 'work', when: { third: true }, turns: [
      { beat: "Chores {here}. {a} and {b} both have a plan." },
      { by: 'a', say: "Okay, everybody. Water first, then wood.", v: { bossy: "Listen up, it's water first and then wood, so let's move.", loud: "Okay, people, water first and then wood! Go, go, go!" } },
      { by: 'b', say: "Actually, I already told people wood first." },
      { by: 'a', say: "Why would you do wood first?" },
      { by: 'b', say: "Because it takes longer and it's cooler in the morning." },
      { by: 'c', say: "{b}'s right. I'm doing wood." },
      { by: 'a', say: "Great, fine, do whatever you want." },
      { by: 'a', conf: "{c} always sides with {b}, every single time, so now I've got two people to deal with instead of one.", v: { cruel: "Oh, {b} has a little sidekick now. Cute. I'll deal with both of them.", schemer: "{c} always backs {b} up, which is good to know. Very good to know." } },
      { by: 'c', conf: "It's not about sides, wood first just makes more sense. Okay, fine, it's a little about sides." },
    ] },
  ],
  'long.drama.explode.any': [
    { id: 'nh.e1', place: 'public', when: { third: true }, turns: [
      { by: 'a', say: "Do you ever stop? Seriously, do you ever stop?", v: { loud: "Do you EVER stop?!", dry: "Is there an off switch? I've been looking for days." } },
      { by: 'b', say: "What did I even say?" },
      { by: 'a', say: "It's not what you said, it's everything! The correcting, the complaining, all of it!" },
      { by: 'c', say: "Okay, that's enough." },
      { by: 'a', say: "Oh, here we go. {b}'s bodyguard." },
      { by: 'c', say: "Somebody has to be. You just screamed at {b} for asking where the rope was." },
      { beat: "{a} storms off. {c} puts a hand on {b}'s shoulder." },
      { by: 'b', conf: "{a} has been waiting to explode at somebody for days. I just happened to be standing there. Thank god {c} was too.", v: { anxious: "I thought {a} was going to hit me. I'm still shaking.", calm: "{a} needed to explode at somebody and I was in the way, but {c} got me out of it." } },
    ] },
  ],
};
