// ══════════════════════════════════════════════════════════════════════
// td/story/lines/n-long4.js — whole conversations where the season only had sketches
// ══════════════════════════════════════════════════════════════════════
// The user, 2026-10-08: "I'm tired of 4/5 line events that tell nothing". Measured over three
// played seasons, these kinds aired at five spoken lines or fewer most of the time; each version
// here is a conversation of eight or more, with a start, a turn and somewhere it ends up. Same
// keys and roles as their headers:
//   vt2.sure            a is sure it's {wrote} tonight and has no idea it's a (director.js voteTalk);
//                       b, a's friend, isn't writing a's name and doesn't know either. bWrote: b is
//                       writing {wrote} too; other: b is writing {other}. Nothing may say how it ends.
//   chm.*               n-chm.js (two: between a and b; else a's own moment, b saw it)
//   psy.<need>          n-psy.js (b is the one person a trusts most, when pair)
//   long.friend.drift.any  a quietly pulls away from b, a close friend
//   long.conf.bigmove.any  a wants to make a move (b, when there, is who a tells)
//   arc.ally.formed     a, b (c, d) form {group}
// Ids: 'nl4.'.

export default {
  'vt2.sure': [
    { id: 'nl4.u1', turns: [
      { beat: "{a} and {b} are the last two at the fire before everybody heads out." },
      { by: 'a', say: "Tonight's going to be easy. It's {wrote}, everybody knows it's {wrote}." },
      { by: 'b', say: "Everybody keeps saying that." },
      { by: 'a', say: "Because it's true. Did anybody say a different name to you?" },
      { by: 'b', say: "No. Nobody's said anything to me all afternoon, which is kind of weird, now that you mention it." },
      { by: 'a', say: "That's not weird. That's just people being quiet on a vote day." },
      { by: 'b', say: "I'm writing {wrote} with you.", when: { bWrote: true } },
      { by: 'b', say: "For what it's worth, I'm writing {other}. I just think it's the smarter vote.", when: { other: true } },
      { by: 'a', say: "Okay, then we're fine. We're both fine." },
      { by: 'b', conf: "{a} is completely sure about tonight. I wish I was that sure about anything in this game." },
    ] },
    { id: 'nl4.u2', when: { voice: ['loud', 'tough', 'competitive', 'proud'] }, turns: [
      { by: 'a', say: "{wrote} is going home, and honestly, I can't wait to watch it happen." },
      { by: 'b', say: "You're really confident." },
      { by: 'a', say: "I'm confident because I counted. {wrote} has nobody." },
      { by: 'b', say: "Who did you count with?" },
      { by: 'a', say: "Everybody. I talked to everybody." },
      { by: 'b', say: "And they all said {wrote}?" },
      { by: 'a', say: "They all nodded when I said {wrote}. Same thing." },
      { by: 'b', say: "...Is it, though?" },
      { by: 'a', say: "Don't do that. Don't make me nervous right before the vote." },
    ] },
    { id: 'nl4.u3', when: { voice: ['anxious', 'warm', 'earnest', 'emotional'] }, turns: [
      { by: 'a', say: "Can I tell you something? I feel good about tonight, like actually good." },
      { by: 'b', say: "That's new for you." },
      { by: 'a', say: "I know! Usually I'm a mess before a vote. But it's {wrote}, and I'm with the numbers for once." },
      { by: 'b', say: "I'm really glad. You deserve a calm night." },
      { by: 'a', say: "After tonight, I think I can finally relax a little." },
      { by: 'b', say: "Don't relax too much. It's still this game." },
      { by: 'a', say: "Let me have this one. Please." },
      { by: 'b', conf: "{a} finally feels safe. I really, really hope {a} is right." },
    ] },
    { id: 'nl4.u4', when: { voice: ['calm', 'dry', 'schemer'] }, turns: [
      { by: 'a', say: "Walk me through it one more time. Who's on {wrote}?" },
      { by: 'b', say: "You've already walked me through it three times." },
      { by: 'a', say: "Then a fourth won't hurt." },
      { by: 'b', say: "Okay. You, me, and everybody you talked to after lunch." },
      { by: 'a', say: "And nobody's mentioned anyone else to you?" },
      { by: 'b', say: "Not to me. But I'm not exactly who people come to with plans." },
      { by: 'a', say: "That's what I like about you. You're honest about what you don't know." },
      { by: 'a', conf: "I've done the math. It's {wrote}. The only thing I can't count is who's lying to me, and I don't think anybody is." },
    ] },
  ],

  'chm.clash.any': [
    { id: 'nl4.c1', when: { two: true }, turns: [
      { beat: "{a} and {b} come back from {chal} still arguing, and the rest of the team gives them a wide berth." },
      { by: 'b', say: "I told you to wait. I said wait, and you went anyway." },
      { by: 'a', say: "Because if I'd waited, we'd still be out there." },
      { by: 'b', say: "We'd still be out there and still in it! Instead we lost!" },
      { by: 'a', say: "We lost because you froze, not because I moved." },
      { by: 'b', say: "I didn't freeze, I was thinking. You should try it sometime." },
      { by: 'a', say: "Oh, that's great, really great. Go say that to the team." },
      { by: 'b', say: "Maybe I will." },
      { by: 'a', conf: "{b} wants everybody to think {chal} was my fault, so fine, let {b} try. I know exactly what happened out there." },
    ] },
    { id: 'nl4.c2', when: { two: true, bLikesA: true }, turns: [
      { beat: "{b} finds {a} sitting alone behind the {quarters} after {chal}." },
      { by: 'b', say: "Hey. Can we talk about what happened out there?" },
      { by: 'a', say: "You mean you screaming at me in front of everybody?" },
      { by: 'b', say: "I didn't scream." },
      { by: 'a', say: "You screamed. The other team heard it." },
      { by: 'b', say: "...Okay, I screamed. I was scared we were going to lose, and I took it out on you. I'm sorry." },
      { by: 'a', say: "I know you were scared, and so was I. That's why it hurt." },
      { by: 'b', say: "Are we okay?" },
      { by: 'a', say: "We're okay. Just don't do it again, because next time I'm screaming back." },
      { by: 'b', conf: "I nearly lost one of the only people here I actually like over a stupid challenge. I need to be better than that." },
    ] },
    { id: 'nl4.c3', when: { two: true, bHatesA: true }, turns: [
      { by: 'b', say: "You did that on purpose." },
      { by: 'a', say: "Did what?" },
      { by: 'b', say: "At {chal}. You got in my way every single time." },
      { by: 'a', say: "Maybe you were in my way." },
      { by: 'b', say: "There was a whole course! We didn't need to be in the same spot!" },
      { by: 'a', say: "And yet you kept ending up right where I was going. Funny, that." },
      { by: 'c', say: "Can you two not, for one night?", opt: true },
      { by: 'b', say: "Tell {a.obj} that." },
      { by: 'a', conf: "{b} and I can't even do a challenge without it turning into a war. Honestly? That's fine. I'm better at wars than {b} is." },
    ] },
    { id: 'nl4.c4', when: { two: false }, turns: [
      { beat: "The team is sitting around after {chal}, nobody saying much. {b} finally breaks it." },
      { by: 'b', say: "Can I say what everybody's thinking?" },
      { by: 'a', say: "Here we go." },
      { by: 'b', say: "You were really hard on people today. Like, really hard." },
      { by: 'a', say: "Somebody had to keep us moving." },
      { by: 'b', say: "Keeping us moving and yelling at us are two different things." },
      { by: 'a', say: "If we'd won, you'd be calling it leadership." },
      { by: 'b', say: "If we'd won, maybe. We didn't." },
      { by: 'b', conf: "{a} thinks being loud is the same as being in charge. Half the team is going to remember today a lot longer than {a} thinks." },
    ] },
  ],
  'chm.saved.any': [
    { id: 'nl4.s1', when: { two: true }, turns: [
      { beat: "{b} limps over to where {a} is sitting and drops down beside {a.obj}." },
      { by: 'b', say: "I didn't say it out there, so I'm saying it now. Thank you." },
      { by: 'a', say: "You don't have to." },
      { by: 'b', say: "I do. At {chal}, I was done and ready to quit, and you came back." },
      { by: 'a', say: "You'd have done the same for me." },
      { by: 'b', say: "I honestly don't know if I would have. That's what's bothering me." },
      { by: 'a', say: "Then next time, you'll know. That's all that matters." },
      { by: 'b', say: "Next time I'm coming back for you. I promise." },
      { by: 'b', conf: "Everybody's going to remember who won {chal}. I'm going to remember who came back for me." },
    ] },
    { id: 'nl4.s2', when: { two: true, bHatesA: true }, turns: [
      { by: 'b', say: "So. About today." },
      { by: 'a', say: "You're welcome." },
      { by: 'b', say: "I wasn't going to say thank you." },
      { by: 'a', say: "I know. I'm saying it for you, so you don't have to." },
      { by: 'b', say: "Why did you even do it? You don't like me." },
      { by: 'a', say: "I don't. But I like losing even less, and we needed you to finish." },
      { by: 'b', say: "That's the least romantic rescue in history." },
      { by: 'a', say: "Good. Let's keep it that way." },
      { by: 'b', conf: "The one person here I can't stand pulled me through {chal}. Now I owe {a.obj}, and I hate owing {a.obj} anything." },
    ] },
    { id: 'nl4.s3', when: { two: false }, turns: [
      { beat: "The whole team is crowded around {a} by the fire, replaying {chal} move by move." },
      { by: 'b', say: "And then you just went back for the last one like it was nothing!" },
      { by: 'a', say: "It wasn't nothing. My legs are still shaking." },
      { by: 'b', say: "Nobody could tell! You looked like you'd done it a hundred times." },
      { by: 'a', say: "I've never done anything like it in my life." },
      { by: 'b', say: "Well, now you have. And everybody saw." },
      { by: 'a', say: "Yeah. Everybody saw." },
      { by: 'a', conf: "It's nice being the hero for a day. But I've watched this game long enough to know heroes make great targets." },
    ] },
  ],
  'chm.sabotage.any': [
    { id: 'nl4.b1', when: { two: true }, turns: [
      { beat: "{b} marches straight past the fire and stops in front of {a}." },
      { by: 'b', say: "I saw what you did out there." },
      { by: 'a', say: "I don't know what you're talking about.", v: { schemer: "You'll have to be more specific. I did a lot of things.", cruel: "And? It worked, didn't it?" } },
      { by: 'b', say: "At {chal}, you messed with my stuff on purpose." },
      { by: 'a', say: "Prove it." },
      { by: 'b', say: "I don't have to prove it. I watched you." },
      { by: 'a', say: "Then tell everybody. See who believes you over me." },
      { by: 'c', say: "I believe {b.obj}.", opt: true },
      { by: 'b', conf: "{a} cheated, and {a} doesn't even care that I know. Fine. Now I know exactly what kind of player I'm dealing with." },
    ] },
    { id: 'nl4.b2', when: { two: false }, turns: [
      { by: 'b', say: "Can I ask you something, just between us?" },
      { by: 'a', say: "Sure." },
      { by: 'b', say: "At {chal}, with the other team's stuff. Was that you?" },
      { by: 'a', say: "Why would you think that?" },
      { by: 'b', say: "Because I was right behind you." },
      { beat: "{a} doesn't say anything for a moment." },
      { by: 'a', say: "We won, didn't we?" },
      { by: 'b', say: "We did. I'm just not sure I'm happy about how." },
      { by: 'b', conf: "{a} won us {chal} by cheating. I'm grateful, and I'm also never turning my back on {a} again." },
    ] },
  ],

  'psy.belong': [
    { id: 'nl4.p1', when: { pair: true, moment: 'lost', lastBoot: true }, turns: [
      { beat: "{a} hasn't touched breakfast. {b} slides along the log to sit next to {a.obj}." },
      { by: 'b', say: "You okay?" },
      { by: 'a', say: "I keep turning round to tell {lastBoot} things, and {lastBoot} isn't there." },
      { by: 'b', say: "Yeah. I noticed you doing that." },
      { by: 'a', say: "Is that stupid? It's been one night." },
      { by: 'b', say: "It's not stupid. You two were close." },
      { by: 'a', say: "I don't really know who I am here without {lastBoot}. I don't know who I sit with." },
      { by: 'b', say: "You sit with me. That's who." },
      { by: 'a', conf: "I came here to win. I didn't come here to need people. Turns out I do, and it's the scariest thing about this whole game." },
    ] },
    { id: 'nl4.p2', when: { pair: true, moment: 'votes' }, turns: [
      { by: 'a', say: "Can I ask you something weird? Do people here like me?" },
      { by: 'b', say: "What? Of course they do." },
      { by: 'a', say: "Then why did my name come up last night?" },
      { by: 'b', say: "That's not about liking you. That's about numbers." },
      { by: 'a', say: "Numbers don't write names. People do." },
      { by: 'b', say: "Okay, fair. But I didn't write it, and I'd tell you if I knew who did." },
      { by: 'a', say: "You promise?" },
      { by: 'b', say: "I promise." },
      { by: 'a', conf: "Getting votes is one thing. Not knowing who's being nice to me and who's lying, that's what I can't sleep through." },
    ] },
    { id: 'nl4.p3', when: { pair: true, moment: 'bottom' }, turns: [
      { beat: "Everybody's laughing at something by the fire. {a} laughs too, a second late, and then gets up and walks off. {b} follows." },
      { by: 'b', say: "Hey. Where are you going?" },
      { by: 'a', say: "Nowhere. Just needed a minute." },
      { by: 'b', say: "Was it something somebody said?" },
      { by: 'a', say: "No, that's the thing, nobody said anything. I'm just not really in any of the jokes." },
      { by: 'b', say: "You're in mine." },
      { by: 'a', say: "You're nice. You're also the only one." },
      { by: 'b', say: "Then let's make it two. Come back and sit with me." },
      { by: 'a', conf: "I get along with everybody here, and I'm close to nobody. I didn't know those were different things until this week." },
    ] },
  ],
  'psy.control': [
    { id: 'nl4.k1', when: { pair: true }, turns: [
      { by: 'b', say: "You've been watching everybody all morning." },
      { by: 'a', say: "Somebody has to." },
      { by: 'b', say: "Why does it have to be you?" },
      { by: 'a', say: "Because if I don't know where everybody is, I start imagining where they are. And what I imagine is always worse." },
      { by: 'b', say: "That sounds exhausting." },
      { by: 'a', say: "It is. But it's less exhausting than being blindsided." },
      { by: 'b', say: "You know you can't control all of it, right?" },
      { by: 'a', say: "I know. I just don't believe it." },
      { by: 'b', conf: "{a} has the whole camp mapped out in {a.posAdj} head. I just hope {a} leaves a little room in there to breathe." },
    ] },
  ],
  'psy.temper': [
    { id: 'nl4.t1', when: { pair: true }, turns: [
      { by: 'a', say: "I almost lost it at somebody this morning." },
      { by: 'b', say: "I saw. You walked off right before." },
      { by: 'a', say: "I had to. If I'd stayed, I'd have said something I couldn't take back." },
      { by: 'b', say: "That's good, though. Walking off." },
      { by: 'a', say: "It doesn't feel good. It feels like I'm holding a pot that's about to boil over." },
      { by: 'b', say: "So when it boils, come find me. Yell at me instead." },
      { by: 'a', say: "You'd let me yell at you?" },
      { by: 'b', say: "Better me than somebody with a vote." },
      { by: 'a', conf: "Everybody here knows I've got a temper. The game is going to be whether I can keep it in until it doesn't matter anymore." },
    ] },
  ],
  'psy.prove': [
    { id: 'nl4.v1', when: { pair: true }, turns: [
      { by: 'a', say: "Do you think people here take me seriously?" },
      { by: 'b', say: "Why are you asking?" },
      { by: 'a', say: "Because every time there's a plan, I find out about it last. Like they don't think I'd matter." },
      { by: 'b', say: "Maybe they just don't think you're a threat." },
      { by: 'a', say: "That's exactly the problem. I want to be a threat, and I want them to worry about me." },
      { by: 'b', say: "Careful what you wish for." },
      { by: 'a', say: "I'm being careful. I just want one vote where I'm the reason it went the way it did." },
      { by: 'a', conf: "Everybody back home thinks I'm the nice one. I want to go home as the one who made a move." },
    ] },
  ],

  'long.friend.drift.any': [
    { id: 'nl4.d1', turns: [
      { beat: "{b} saves {a} a spot at the fire, like always. {a} sits down on the other side." },
      { by: 'b', say: "Hey. I saved you a spot." },
      { by: 'a', say: "Oh. Sorry, I didn't see." },
      { by: 'b', say: "You walked right past it." },
      { by: 'a', say: "I just wanted to sit over here tonight. It's not a big deal." },
      { by: 'b', say: "It's the third time today something wasn't a big deal." },
      { by: 'a', say: "Can we not do this in front of everybody?" },
      { by: 'b', say: "Sure. Whenever you've got time for me again." },
      { by: 'a', conf: "{b} is a good friend. {b} is also on the wrong side of this camp right now, and I can't be seen glued to {b.obj}." },
    ] },
    { id: 'nl4.d2', turns: [
      { by: 'b', say: "Do you want to go get water with me?" },
      { by: 'a', say: "Maybe later." },
      { by: 'b', say: "That's what you said this morning." },
      { by: 'a', say: "Then I meant it this morning too." },
      { by: 'b', say: "Did I do something?" },
      { by: 'a', say: "No, you didn't do anything. That's not what this is." },
      { by: 'b', say: "Then what is it?" },
      { by: 'a', say: "It's just the game. I'm sorry." },
      { by: 'b', conf: "'It's just the game.' That's what people say right before they stop being your friend." },
    ] },
  ],
  'long.conf.bigmove.any': [
    { id: 'nl4.m1', when: { pair: true }, turns: [
      { by: 'a', say: "Can I tell you something you can't repeat?" },
      { by: 'b', say: "Depends what it is." },
      { by: 'a', say: "I'm tired of riding the majority. Everybody's comfortable, and comfortable people stop paying attention." },
      { by: 'b', say: "You want to make a move." },
      { by: 'a', say: "I want to make a move that everybody remembers." },
      { by: 'b', say: "That's how people go home, you know." },
      { by: 'a', say: "It's also how people win. I'd rather go home swinging than sit here until it's my turn." },
      { by: 'b', say: "Okay. When you've got a name, tell me first." },
      { by: 'a', conf: "{b} didn't say no. In this game, not saying no is basically a yes." },
    ] },
  ],
  'arc.ally.formed': [
    { id: 'nl4.a1', turns: [
      { beat: "{a} and {b} end up on firewood duty, far enough out that nobody can hear them." },
      { by: 'a', say: "Can I ask you something honest? Who do you actually trust here?" },
      { by: 'b', say: "Honestly? Maybe you, and maybe only you." },
      { by: 'a', say: "Same. I've been watching who talks to who, and nobody's looking out for either of us." },
      { by: 'b', say: "So let's look out for each other." },
      { by: 'a', say: "Officially?" },
      { by: 'b', say: "Officially. And if we're doing it, it needs a name, so let's call it {group}." },
      { by: 'a', say: "{group}, I like that. You and me, and nobody else unless we both say yes." },
      { by: 'b', conf: "We just made {group} in the middle of a pile of firewood. Nobody knows. That's exactly how I want it." },
    ] },
    { id: 'nl4.a2', when: { third: true }, turns: [
      { beat: "{a} gets {b} and {c} away from camp on the excuse of looking for coconuts." },
      { by: 'c', say: "There aren't any coconuts over here." },
      { by: 'a', say: "I know. I needed you both alone." },
      { by: 'b', say: "Okay, now I'm interested." },
      { by: 'a', say: "Everybody else here already has a group. We don't. If we don't make one now, we're the ones who get picked off." },
      { by: 'c', say: "So what, the three of us?" },
      { by: 'a', say: "The three of us, and we call it {group}. We tell each other everything first, before anybody else hears it." },
      { by: 'b', say: "I'm in." },
      { by: 'c', say: "...Okay. I'm in too. But if either of you lies to me, I'm out, and I'm taking everything I know with me." },
      { by: 'a', conf: "{group} started with a fake coconut hunt. Every great alliance needs a terrible origin story." },
    ] },
  ],
};
