// ══════════════════════════════════════════════════════════════════════
// td/story/lines/n-morning.js — the morning after a vote
// ══════════════════════════════════════════════════════════════════════
//
// director.js morningAfter(). Parts: a = the camper closest to {lastBoot}; b = somebody who
// voted {lastBoot} out (bVoted 'boot'), or another camper; c = a third, sometimes absent.
//   blindside  a did not vote {lastBoot} and didn't see it coming
//   agreed     a voted {lastBoot} out too, and was close to them
//   relief     a couldn't stand {lastBoot}
//   nobody     nobody was close to {lastBoot}; the camp moves on
// {bootVotes} only where votes are read out (count). Nobody knows anybody else's ballot; b's own
// vote is said only when bVoted says it. `v` = what the line becomes in a speaker's voice.

export default {
  'story.morning.blindside': [
    { id: 'nm.b1', place: 'eat', when: { bVoted: 'boot' }, turns: [
      { beat: "Breakfast {here}. {lastBoot}'s spot is empty. {a} hasn't eaten anything." },
      { by: 'b', say: "You going to eat that?", v: { food: "Are you gonna eat that? Because I'll eat that.", cruel: "Don't let it go to waste. Somebody here's still in the game." } },
      { by: 'a', say: "Are you serious right now?" },
      { by: 'b', say: "What? It's breakfast." },
      { by: 'a', say: "{lastBoot} was here yesterday. Now {lastBoot} isn't, and you want to talk about breakfast.",
        v: { loud: "{lastBoot} got voted out last night and you're asking about my BREAKFAST?", dry: "Sure. Let's talk about breakfast. That's definitely what's on my mind." } },
      { by: 'b', say: "I'm sorry about {lastBoot}. I am." },
      { by: 'a', say: "Are you? Because you don't look sorry." },
      { by: 'b', say: "What do you want me to say?" },
      { by: 'a', say: "Who it was. That's all I want." },
      { by: 'b', conf: "I voted for {lastBoot}. I'm not going to tell {a} that over breakfast.", v: { schemer: "I wrote {lastBoot}'s name. {a} will figure that out eventually. I'd rather it was later." } },
      { by: 'a', conf: "{lastBoot} was the one person here I trusted. Somebody at that table voted {lastBoot.obj} out, and they're all acting normal.",
        v: { emotional: "I cried for like an hour last night. I'm not crying in front of them. I'm not giving them that." } },
    ] },
    { id: 'nm.b2', place: 'sleep', turns: [
      { beat: "Early, in the {quarters}. {a} is sitting on {lastBoot}'s empty {bed}." },
      { by: 'c', say: "Hey. Did you sleep at all?" },
      { by: 'a', say: "Not really." },
      { by: 'c', say: "I'm sorry. I didn't know it was going to be {lastBoot}. I swear." },
      { by: 'a', say: "I know. That's the scary part. Nobody told me, and nobody told you either.",
        v: { anxious: "That's what scares me. If nobody told you, and nobody told me, then who knew?" } },
      { by: 'c', say: "So what do we do?" },
      { by: 'a', say: "We find out who did it. Then we stop trusting them.", v: { tough: "We find out who did it. Then they're next.", warm: "We stick together. Me and you. That's what we do." } },
      { by: 'c', conf: "{a} looks wrecked. {lastBoot} was {a.posAdj} person. I don't want to be the next person {a} loses." },
    ] },
    { id: 'nm.b3', place: 'work', when: { voice: ['loud', 'tough', 'blunt'] }, turns: [
      { beat: "{a} comes out of the {quarters} and kicks over the water bucket. Everybody stops." },
      { by: 'a', say: "Okay. Who was it?" },
      { by: 'b', say: "Who was what?" },
      { by: 'a', say: "Don't. Somebody here voted out {lastBoot}, and I want to know who." },
      { by: 'c', say: "{a}, can you calm down for one second?" },
      { by: 'a', say: "No! I can't! My friend got voted out and you're all walking around like nothing happened!" },
      { by: 'b', say: "Yelling at everybody isn't going to bring {lastBoot.obj} back." },
      { by: 'a', say: "No, but it's going to make me feel a whole lot better." },
      { by: 'c', conf: "{a} just kicked a bucket at seven in the morning. If I'd voted for {lastBoot}, I'd be hiding right now." },
      { by: 'a', conf: "I'm not crazy. I'm mad. Whoever did this is going to find out what that means." },
    ] },
    { id: 'nm.b4', place: 'fire', when: { voice: ['warm', 'anxious', 'earnest', 'emotional'] }, turns: [
      { beat: "{a} is sitting by the cold fire {here} with {a.posAdj} knees pulled up." },
      { by: 'c', say: "Hey. You okay?" },
      { by: 'a', say: "I keep turning around to say something to {lastBoot}. And then I remember." },
      { by: 'c', say: "Yeah. It's weird without {lastBoot.obj}." },
      { by: 'a', say: "{lastBoot.Sub} didn't see it coming. You could see it on {lastBoot.posAdj} face." },
      { by: 'c', say: "None of us did." },
      { by: 'a', say: "Somebody did." },
      { beat: "{a} looks over at {b}, who is suddenly very busy with the water." },
      { by: 'a', conf: "I thought everyone here was nice. I'm learning that nice and honest aren't the same thing." },
      { by: 'b', conf: "I feel bad. I do. But {lastBoot} wasn't going to the end with me, and {a} is going to have to get over it." },
    ] },
    { id: 'nm.b5', place: 'water', when: { voice: ['schemer', 'calm', 'dry'] }, turns: [
      { beat: "{a} is {here}, skipping stones. {b} comes down with a fishing rod." },
      { by: 'b', say: "Mind if I fish here?" },
      { by: 'a', say: "Go ahead." },
      { by: 'b', say: "You're taking it pretty well. {lastBoot}, I mean." },
      { by: 'a', say: "Am I? I was about to say the same thing about you.", v: { dry: "Am I? You look like you slept great." } },
      { by: 'b', say: "What's that supposed to mean?" },
      { by: 'a', say: "Nothing. Just that you look pretty relaxed for somebody whose team just lost a person." },
      { by: 'b', say: "I don't know what you want me to say." },
      { by: 'a', say: "Nothing. You've said plenty." },
      { by: 'a', conf: "I'm not going to yell about {lastBoot}. I'm going to work out who did it, and they're going to find out the hard way." },
      { by: 'b', conf: "{a} is way too calm about this. That makes me nervous." },
    ] },
    { id: 'nm.b6', place: 'sleep', when: { count: true }, turns: [
      { beat: "The {quarters}, before anyone's really awake. {a} is going over it out loud." },
      { by: 'a', say: "{bootVotes} votes. {bootVotes} people wrote {lastBoot}'s name, and I didn't hear about any of it." },
      { by: 'c', say: "Maybe nobody wanted you to find out." },
      { by: 'a', say: "Yeah. That's the problem." },
      { by: 'b', say: "Can you two do this outside? Some of us are trying to sleep." },
      { by: 'a', say: "Some of us lost a friend last night." },
      { by: 'b', say: "Some of us didn't get voted out at all. Count your blessings." },
      { by: 'c', say: "Wow." },
      { by: 'a', conf: "You don't make jokes like that unless the vote went exactly how you wanted it to." },
    ] },
    { id: 'nm.b7', place: 'eat', when: { merged: true }, turns: [
      { beat: "Breakfast {here}. People are eating in little groups. Nobody's sitting with {a}." },
      { by: 'a', say: "Wow. Okay. So that's how it is now." },
      { by: 'c', say: "It's not like anything. Sit down." },
      { by: 'a', say: "{lastBoot} was in every plan I had. Every single one. And nobody gave me a heads-up." },
      { by: 'c', say: "Nobody gave anybody a heads-up. That's why it worked." },
      { by: 'b', say: "If it helps, it wasn't about you." },
      { by: 'a', say: "How would you know who it was about?" },
      { by: 'b', say: "I'm just saying." },
      { by: 'a', say: "You're saying a lot for somebody who wasn't involved." },
      { by: 'a', conf: "This late in the game, a vote like that doesn't just happen. Somebody organised it. And {b} knows more than {b} is saying." },
    ] },
    { id: 'nm.b8', place: 'aside', when: { bVoted: 'boot', voice: ['loud', 'blunt', 'tough', 'competitive'] }, turns: [
      { by: 'a', say: "Just tell me. Did you write {lastBoot}?" },
      { by: 'b', say: "...Yeah. I did." },
      { by: 'a', say: "Unbelievable." },
      { by: 'b', say: "{lastBoot} was coming after people. I wasn't going to be one of them." },
      { by: 'a', say: "{lastBoot} wasn't coming after anybody! {lastBoot} was my friend!" },
      { by: 'b', say: "Your friend. Not mine." },
      { by: 'a', say: "Fine. Good. At least now I know." },
      { by: 'b', conf: "I could have lied. I didn't. I think that should count for something." },
      { by: 'a', conf: "{b} wants credit for being honest about it. No. That's not how this works." },
    ] },
    { id: 'nm.b9', place: 'aside', when: { bVoted: 'boot', voice: ['warm', 'anxious', 'earnest', 'ditzy'] }, turns: [
      { by: 'a', say: "Can I ask you something? Did you vote for {lastBoot}?" },
      { by: 'b', say: "...I did. I'm sorry." },
      { by: 'a', say: "Oh." },
      { by: 'b', say: "I know you two were close." },
      { by: 'a', say: "We were. I don't know what you call it now." },
      { by: 'b', say: "It wasn't about you. I promise." },
      { by: 'a', say: "Everybody keeps saying that. It still feels like it was." },
      { beat: "{a} goes off to do the dishes alone." },
      { by: 'b', conf: "I could have lied to {a}. Maybe I should have. The way {a} looked at me was worse than a fight." },
    ] },
    { id: 'nm.b10', place: 'public', when: { merged: false, third: true }, turns: [
      { beat: "Chores {here}. Everybody's very busy and very quiet." },
      { by: 'c', say: "Okay, is nobody going to say it?" },
      { by: 'b', say: "Say what?" },
      { by: 'c', say: "That we voted out {lastBoot} and {a} had no idea." },
      { by: 'a', say: "Thanks, {c}. Really helpful." },
      { by: 'c', say: "Sorry! It's just weird. Everybody's acting like it's normal." },
      { by: 'b', say: "It is normal. We lost, somebody went home. That's the show." },
      { by: 'a', say: "And it's normal that nobody told me?" },
      { by: 'b', say: "Maybe nobody told you because you'd have told {lastBoot}." },
      { by: 'a', say: "...Yeah. I would have." },
      { by: 'a', conf: "{b} is right, and that's the worst part. They left me out because they knew which side I'd pick. So now I know which side I'm on." },
    ] },
    { id: 'nm.b11', place: 'public', when: { merged: true, voice: ['loud', 'theatrical', 'chaotic'] }, turns: [
      { beat: "{a} is standing in the middle of camp as everyone comes out." },
      { by: 'a', say: "Good morning, everybody! Did everybody sleep well?" },
      { by: 'c', say: "Oh no." },
      { by: 'a', say: "Because {lastBoot} didn't sleep here last night, and I'd love to know who to thank for that." },
      { by: 'b', say: "Can you not do this in front of everyone?" },
      { by: 'a', say: "Why not? You all did it in front of me." },
      { by: 'b', say: "You're making yourself the next target." },
      { by: 'a', say: "I was the next target the second {lastBoot} left. At least now I'm a loud one." },
      { by: 'c', conf: "{a} just declared war on the whole camp before breakfast. It's honestly kind of impressive." },
    ] },
    { id: 'nm.b12', place: 'secret', when: { voice: ['schemer', 'calm', 'nerdy'] }, turns: [
      { beat: "{a} takes {c} out to {place} before breakfast." },
      { by: 'c', say: "Why are we out here?" },
      { by: 'a', say: "Because I need to know if you knew about {lastBoot}." },
      { by: 'c', say: "No! I swear. I found out when everybody else did." },
      { by: 'a', say: "Okay." },
      { by: 'c', say: "That's it? Okay?" },
      { by: 'a', say: "If you'd known, you'd have said way more just now. You didn't. So, okay." },
      { by: 'c', say: "Who do you think did it?" },
      { by: 'a', say: "I've got a guess. I want to be sure first." },
      { by: 'a', conf: "I lost my closest ally last night. I'm not going to sit around feeling sorry for myself. I need a new one by tonight." },
    ] },
    { id: 'nm.b13', place: 'sleep', when: { voice: ['ditzy', 'goofy', 'food'] }, turns: [
      { beat: "{a} wakes up and looks over at {lastBoot}'s {bed}. It's empty." },
      { by: 'a', say: "Has anybody seen {lastBoot}?" },
      { by: 'c', say: "{a}. {lastBoot} went home last night." },
      { by: 'a', say: "Oh. Right. Right, I knew that." },
      { by: 'c', say: "Are you okay?" },
      { by: 'a', say: "No. I just forgot for, like, a second. It was a really nice second." },
      { by: 'a', conf: "I really liked {lastBoot}. And I don't even know who voted for {lastBoot.obj}. Is it bad that I don't want to know?" },
    ] },
  ],

  'story.morning.agreed': [
    { id: 'nm.a1', place: 'eat', turns: [
      { beat: "After breakfast {here}. {a} is washing up, scrubbing the same plate over and over." },
      { by: 'b', say: "That one's clean." },
      { by: 'a', say: "I know it's clean." },
      { by: 'b', say: "You did the right thing last night." },
      { by: 'a', say: "Did I? Because it doesn't feel like it. It feels like I voted out the one person who'd have had my back." },
      { by: 'b', say: "{lastBoot} would've beaten you at the end. You know that." },
      { by: 'a', say: "Maybe. I still didn't want to be the one who did it.", v: { schemer: "I know. That's why I did it. I just didn't expect to feel this bad about it." } },
      { by: 'a', conf: "I wrote {lastBoot}'s name. I keep thinking about it. I hope it was worth it." },
    ] },
    { id: 'nm.a2', place: 'aside', when: { voice: ['warm', 'anxious', 'earnest', 'emotional'] }, turns: [
      { beat: "{a} is {here}, twisting a piece of string into a bracelet." },
      { by: 'c', say: "Who's that for?" },
      { by: 'a', say: "It was going to be for {lastBoot}." },
      { by: 'c', say: "You could still give it to {lastBoot.obj}. After the show." },
      { by: 'a', say: "I don't think {lastBoot.sub}'d want it from me." },
      { by: 'c', say: "Why not?" },
      { by: 'a', say: "Because I voted for {lastBoot.obj}. Everyone said it had to be {lastBoot}, so I went along with it." },
      { by: 'c', say: "Oh." },
      { by: 'a', conf: "I'm going to finish it anyway. I'll give it to {lastBoot} at the end and say sorry. If {lastBoot} even talks to me." },
    ] },
    { id: 'nm.a3', place: 'aside', when: { voice: ['schemer', 'calm', 'dry', 'cruel'] }, turns: [
      { by: 'b', say: "You're quiet this morning." },
      { by: 'a', say: "I'm always quiet in the morning." },
      { by: 'b', say: "Not like this. Is it {lastBoot}?" },
      { by: 'a', say: "{lastBoot} was useful. Now {lastBoot} isn't here. That's it.", v: { cruel: "{lastBoot} is gone. I'm not going to cry about it." } },
      { by: 'b', say: "That's cold. You two were close." },
      { by: 'a', say: "Which is why it had to be me who did it. If I'd hesitated, you'd all be looking at me right now." },
      { by: 'a', conf: "Did I like {lastBoot}? Yeah. Did I want to sit next to {lastBoot} at the end? No way." },
    ] },
    { id: 'nm.a4', place: 'public', when: { voice: ['loud', 'blunt', 'tough'] }, turns: [
      { by: 'b', say: "Morning." },
      { by: 'a', say: "Don't." },
      { by: 'b', say: "Don't what? Say morning?" },
      { by: 'a', say: "Don't act like everything's great. We just voted out {lastBoot}." },
      { by: 'b', say: "And you voted for {lastBoot} too." },
      { by: 'a', say: "Yeah, because everyone was saying if I didn't, I was next! Don't stand there and act surprised!" },
      { by: 'c', say: "Guys. Keep it down." },
      { by: 'a', conf: "I'm not proud of it. And if I have to feel bad about it, so does everyone who talked me into it." },
    ] },
    { id: 'nm.a5', place: 'aside', when: { merged: true }, turns: [
      { by: 'a', say: "Last night was the first vote I actually hated." },
      { by: 'b', say: "Because of {lastBoot}?" },
      { by: 'a', say: "{lastBoot} and I were close. Everybody knew it." },
      { by: 'b', say: "That's why it had to happen." },
      { by: 'a', say: "I know. People were looking at us like a pair. A pair never makes it." },
      { by: 'b', say: "So now you're on your own." },
      { by: 'a', say: "On my own, and nobody's scared of me. Great." },
      { by: 'a', conf: "I cut my closest ally loose so I'd look less dangerous. If it works, it's the best move I've made. If it doesn't, it's the worst." },
    ] },
  ],

  'story.morning.relief': [
    { id: 'nm.r1', place: 'sleep', turns: [
      { beat: "{a} wakes up, stretches and looks at {lastBoot}'s empty {bed}." },
      { by: 'a', say: "Huh. It's so quiet." },
      { by: 'c', say: "Because {lastBoot}'s gone?" },
      { by: 'a', say: "Because nobody's telling me I'm doing everything wrong. It's nice." },
      { by: 'c', say: "That's a little harsh." },
      { by: 'a', say: "{lastBoot} was on me from day one. I'm allowed to enjoy one quiet morning." },
      { by: 'b', say: "Just maybe don't enjoy it in front of {lastBoot}'s friends." },
      { by: 'a', conf: "Am I sad {lastBoot} is gone? No. I'm not going to pretend I am." },
    ] },
    { id: 'nm.r2', place: 'eat', when: { voice: ['cruel', 'schemer', 'loud', 'proud'] }, turns: [
      { beat: "Breakfast {here}. {a} is in a very good mood." },
      { by: 'a', say: "Is it me, or does the food taste better today?" },
      { by: 'b', say: "It's the same as yesterday." },
      { by: 'a', say: "It's the same without {lastBoot} complaining about it. That's a big improvement." },
      { by: 'c', say: "You know {lastBoot} can't hear you, right?" },
      { by: 'a', say: "That's what makes it so nice." },
      { by: 'b', say: "You're making people wonder if you're next, you know." },
      { by: 'a', say: "Please. Who would come after me?" },
      { by: 'b', conf: "{a} is gloating at breakfast. I don't even have to make a case against {a}. {a} is making it for me." },
    ] },
    { id: 'nm.r3', place: 'aside', when: { voice: ['warm', 'anxious', 'earnest', 'calm'] }, turns: [
      { by: 'c', say: "You okay? You've been smiling all morning." },
      { by: 'a', say: "Have I? Sorry." },
      { by: 'c', say: "Don't be sorry. I'm just wondering why." },
      { by: 'a', say: "I know I'm supposed to feel bad. But {lastBoot} picked on me since we got here." },
      { by: 'c', say: "Yeah. I noticed that." },
      { by: 'a', say: "So today I can do the chores without somebody telling me I'm doing them wrong. Is that so bad?" },
      { by: 'c', say: "No. Honestly, it's kind of nice." },
      { by: 'a', conf: "I didn't even vote for {lastBoot}. Somebody else got rid of my problem for me. I'll take it." },
    ] },
    { id: 'nm.r4', place: 'aside', when: { merged: true }, turns: [
      { by: 'a', say: "So that's one less person who wants me gone." },
      { by: 'b', say: "That you know of." },
      { by: 'a', say: "Thanks for that." },
      { by: 'b', say: "I'm serious. {lastBoot} talked about you a lot. That doesn't mean {lastBoot} was the only one thinking it." },
      { by: 'a', say: "Can I have an hour to enjoy this before you ruin it?" },
      { by: 'b', say: "You get ten minutes. Then we talk about who's next." },
      { by: 'a', conf: "{lastBoot} going home is the best thing that's happened to me all game. That tells you how the game's been going." },
    ] },
  ],

  'story.morning.nobody': [
    { id: 'nm.n1', place: 'work', when: { count: true }, turns: [
      { beat: "Morning chores {here}. Nobody mentions {lastBoot}." },
      { by: 'b', say: "So. That's done." },
      { by: 'a', say: "Yep." },
      { by: 'b', say: "{bootVotes} votes. Nice and clean." },
      { by: 'a', say: "Clean for you. You were on the right side of it." },
      { by: 'b', say: "So were you." },
      { by: 'a', say: "This time. I found out an hour before. I don't love that." },
      { by: 'b', say: "That's an hour more than {lastBoot} got." },
      { by: 'a', conf: "Nobody's sad about {lastBoot} this morning. I get it. But I'm watching how fast everybody moved on." },
    ] },
    { id: 'nm.n2', place: 'public', when: { third: true }, turns: [
      { by: 'c', say: "Is it weird that nobody's said {lastBoot}'s name all morning?" },
      { by: 'a', say: "Not really." },
      { by: 'b', say: "What do you want, a moment of silence?" },
      { by: 'c', say: "I don't know. Maybe?" },
      { by: 'b', say: "Fine." },
      { beat: "There's about two seconds of silence." },
      { by: 'b', say: "Okay. Who's on firewood?" },
      { by: 'c', say: "You're the worst." },
      { by: 'a', conf: "{lastBoot} was nice. {lastBoot} just never picked a side. And if you don't pick a side, you end up on the losing one." },
    ] },
    { id: 'nm.n3', place: 'secret', when: { voice: ['schemer', 'competitive', 'calm', 'dry'] }, turns: [
      { beat: "{a} and {b} have gone off to {place}, away from everyone else." },
      { by: 'a', say: "So who's next?" },
      { by: 'b', say: "{lastBoot}'s been gone, what, ten hours?" },
      { by: 'a', say: "And in a couple of days somebody's going to be asking about one of us. I'd rather ask first." },
      { by: 'b', say: "Fair. I've got a name." },
      { by: 'a', say: "Me too. You say yours first." },
      { by: 'b', say: "No way. You first." },
      { by: 'a', say: "On three?" },
      { by: 'b', say: "On three." },
      { beat: "Neither of them says anything on three." },
      { by: 'b', conf: "If {a} won't tell me a name, it's either because the name is mine, or because {a} thinks I'll leak it. I don't like either." },
    ] },
    { id: 'nm.n4', place: 'public', when: { merged: false }, turns: [
      { beat: "The team gets on with the day {here}. {lastBoot}'s stuff is already gone." },
      { by: 'b', say: "Okay. We're down one. We need to stop losing." },
      { by: 'a', say: "Yeah, no kidding." },
      { by: 'b', say: "I'm serious. Every time we lose, we lose a person. And every person we lose makes it harder to win the next one." },
      { by: 'c', say: "So what do we do?" },
      { by: 'b', say: "We win the next one. And if we lose, we make sure the right person goes." },
      { by: 'a', say: "Sounds like you already have somebody in mind." },
      { by: 'b', say: "I've got a few." },
      { by: 'a', conf: "{lastBoot} has been gone one night and {b} is already picking the next one. I want to be on whatever side {b} is on." },
    ] },
    { id: 'nm.n5', place: 'sleep', when: { voice: ['goofy', 'food', 'ditzy', 'chaotic'] }, turns: [
      { by: 'a', say: "Did {lastBoot} take the good pillow?" },
      { by: 'c', say: "What good pillow?" },
      { by: 'a', say: "Exactly. There's no good pillow anymore." },
      { by: 'b', say: "That's what you're worried about? Not the vote?" },
      { by: 'a', say: "The vote's over. The pillow thing is still happening." },
      { by: 'a', conf: "I liked {lastBoot}. We just weren't close. I'm not going to fake cry. I'm going to find a better pillow." },
    ] },
  ],
};
