// ══════════════════════════════════════════════════════════════════════
// td/story/lines/n-run.js — the running gags (td/story/runners.js has the header)
// ══════════════════════════════════════════════════════════════════════
// run.<kind>.<1|2|3>: 1 sets it up, 2 calls it back, 3 pays it off. a owns the bit; b has to put up
// with it; c (may be missing) is there. Before the challenge.
// The user, 2026-10-08: "the crab named Gerald is not well written and has no continuation". So a
// bit builds the way a sitcom runner does. The callbacks air in order (call 1, 2, 3+), each the next
// step: the bit gets bigger, other people get dragged into it, and by the third it touches the game.
// The payoff turns it round. Jokes that land on the first read, in plain words. Ids: 'nrn.'.

export default {
  // ── hides snacks everywhere ──
  'run.food.1': [
    { id: 'nrn.f1', turns: [
      { beat: "{b} picks up {a}'s sleeping bag to shake it out, and three crackers fall onto the floor." },
      { by: 'b', say: "Why are there crackers in your sleeping bag?" },
      { by: 'a', say: "Those are emergency crackers." },
      { by: 'b', say: "What's the emergency?" },
      { by: 'a', say: "Being hungry at night. It happens every night, so it's a very regular emergency." },
      { by: 'b', say: "Are there more?" },
      { by: 'a', say: "Define 'more'." },
      { by: 'b', say: "{a}." },
      { by: 'a', say: "There might be some in the tool box. And under the big rock. And in my left shoe." },
      { by: 'a', conf: "I'm not sorry about the snacks. Every group trip I've ever been on, if I didn't hide my food, I didn't eat my food." },
    ] },
    { id: 'nrn.f1b', when: { third: true }, turns: [
      { beat: "{c} reaches into the rice sack and pulls out a granola bar that definitely didn't come with the rice." },
      { by: 'c', say: "Okay, whose is this?" },
      { by: 'a', say: "Never seen it before in my life." },
      { by: 'b', say: "It's got your name written on it." },
      { by: 'a', say: "...Then it's mine, and I'd like it back." },
      { by: 'c', say: "Where did you even get it?" },
      { by: 'a', say: "I brought it. I bring snacks everywhere. I'll probably be buried with a granola bar." },
      { by: 'b', conf: "We're on an island with no food, and {a} is somehow the only person here who isn't hungry. I want to know how, and I'm a little scared to find out." },
    ] },
  ],
  'run.food.2': [
    { id: 'nrn.f2', when: { call: 1 }, turns: [
      { by: 'b', say: "Why is there a banana in the tool box?" },
      { by: 'a', say: "Because nobody ever looks in the tool box." },
      { by: 'b', say: "I just looked in the tool box." },
      { by: 'a', say: "Well, now I need a new spot. Thanks a lot." },
      { by: 'b', say: "How many spots do you have?" },
      { by: 'a', say: "Seven. Six, now." },
      { by: 'b', say: "We've been here for a week." },
      { by: 'a', say: "And I've been busy." },
      { by: 'a', conf: "Every time somebody finds one of my hiding places, a little part of me dies. And then I find a new hiding place." },
    ] },
    { id: 'nrn.f3', when: { call: 2 }, turns: [
      { beat: "It's late. {b} sits up in the {quarters} to the sound of somebody crunching in the dark." },
      { by: 'b', say: "{a}, are you eating?" },
      { by: 'a', say: "No." },
      { by: 'b', say: "I can hear you chewing." },
      { by: 'a', say: "That's the wind." },
      { by: 'c', say: "The wind doesn't chew, {a}.", opt: true },
      { by: 'a', say: "Fine. Does anybody want half a cracker? I'm offering half a cracker to the whole {quarters}." },
      { by: 'b', say: "...Yes, actually." },
      { by: 'b', conf: "I went to bed annoyed at {a} and fell asleep holding half a cracker. That's how {a} wins people over. Snacks, at midnight." },
    ] },
    { id: 'nrn.f3b', when: { call: 3 }, turns: [
      { by: 'b', say: "I have a weird question. Are you using the snacks to get votes?" },
      { by: 'a', say: "I would never." },
      { by: 'b', say: "Three people have told me you gave them crackers this week." },
      { by: 'a', say: "Those are gifts. Gifts between friends." },
      { by: 'b', say: "And who are your friends right now?" },
      { by: 'a', say: "Whoever's hungry." },
      { by: 'b', say: "That's everybody." },
      { by: 'a', say: "Exactly." },
      { by: 'b', conf: "I'm honestly impressed, and a little worried, because I've eaten {a}'s crackers twice this week and now I feel like I owe {a} my vote." },
    ] },
  ],
  'run.food.3': [
    { id: 'nrn.f4', turns: [
      { beat: "Everybody's starving after a terrible day. {a} disappears behind the {quarters} and comes back with both arms full." },
      { by: 'a', say: "Okay. Nobody ask me where these came from." },
      { by: 'b', say: "Are those the crackers? From the first week?" },
      { by: 'a', say: "Emergency crackers. This is the emergency." },
      { by: 'c', say: "I take back everything I ever said about you.", opt: true },
      { by: 'b', say: "How many hiding places did you actually have?" },
      { by: 'a', say: "I'm taking that to my grave." },
      { by: 'b', conf: "We made fun of {a}'s snack stash for weeks, and tonight it fed the entire camp. I'm never laughing at a squirrel again." },
    ] },
    { id: 'nrn.f4b', turns: [
      { by: 'b', say: "I found your last spot." },
      { by: 'a', say: "You did not." },
      { by: 'b', say: "Inside the hollow log by the fire. Two biscuits and a whole bag of raisins." },
      { by: 'a', say: "Okay. Okay. I respect that. What do you want?" },
      { by: 'b', say: "Half the raisins and your vote tonight." },
      { by: 'a', say: "You can have all the raisins. The vote is a separate negotiation." },
      { by: 'a', conf: "{b} found my last stash, and I'm genuinely impressed. Out of everybody here, {b} is the one I'd trust to keep a secret. Or a biscuit." },
    ] },
  ],

  // ── gives everybody nicknames ──
  'run.nickname.1': [
    { id: 'nrn.n1', turns: [
      { by: 'a', say: "Morning, Captain Sunburn." },
      { by: 'b', say: "Who's Captain Sunburn?" },
      { by: 'a', say: "You. Look at your shoulders." },
      { by: 'b', say: "That's not a nickname, that's a medical condition." },
      { by: 'a', say: "It can be both." },
      { by: 'b', say: "What's your nickname, then?" },
      { by: 'a', say: "I don't need one. I'm the one who gives them out." },
      { by: 'b', say: "That's not how it works." },
      { by: 'a', conf: "Everybody here gets a nickname. It's how I remember people. Also, it's how I make sure they remember me." },
    ] },
  ],
  'run.nickname.2': [
    { id: 'nrn.n2', when: { call: 1 }, turns: [
      { by: 'a', say: "Hey, Sleepy. Hey, The Professor. Hey, Bandana." },
      { by: 'b', say: "Do you know anybody's actual name?" },
      { by: 'a', say: "I know all of them. I just like mine better." },
      { by: 'c', say: "I've been Bandana for three days and I don't own a bandana.", opt: true },
      { by: 'a', say: "You will." },
      { by: 'b', say: "And what am I today?" },
      { by: 'a', say: "Still Captain Sunburn. You've earned it, look at you." },
      { by: 'b', conf: "{a} has nicknamed every single person in this camp. The scary part is that half of them are starting to stick." },
    ] },
    { id: 'nrn.n3', when: { call: 2 }, turns: [
      { beat: "{b} walks into camp to hear somebody else call {c} 'Bandana'." },
      { by: 'b', say: "Wait. You're doing it too now?" },
      { by: 'c', say: "Doing what?", opt: true },
      { by: 'b', say: "The nicknames! It's spreading!" },
      { by: 'a', say: "It's not spreading. It's catching on. There's a difference." },
      { by: 'b', say: "What's the difference?" },
      { by: 'a', say: "One of them sounds like a disease, and the other one sounds like I'm a genius." },
      { by: 'b', conf: "Two weeks ago, {a} was the only one doing it. Now I heard somebody call me Captain Sunburn in a strategy meeting. I'm losing the war." },
    ] },
    { id: 'nrn.n3b', when: { call: 3 }, turns: [
      { by: 'b', say: "Can I ask you something serious about the nicknames?" },
      { by: 'a', say: "Anything, Captain." },
      { by: 'b', say: "Do you have one for the vote tonight? Like, a code name?" },
      { by: 'a', say: "...You want me to make up code names for the people we're voting out?" },
      { by: 'b', say: "If anybody overhears us, they won't know who we mean." },
      { by: 'a', say: "Oh, this is the best day of my life." },
      { by: 'a', conf: "My nicknames are now officially a strategic tool. I'd like everybody who rolled their eyes at me to come and apologise, one at a time." },
    ] },
  ],
  'run.nickname.3': [
    { id: 'nrn.n4', turns: [
      { beat: "{a} comes back from the water to find a piece of bark leaning against the {quarters}, with something written on it in charcoal." },
      { by: 'a', say: "'Nickname Machine'?" },
      { by: 'b', say: "We all voted. It was unanimous." },
      { by: 'a', say: "That's the best thing anybody's ever done for me." },
      { by: 'c', say: "You're welcome, Nickname Machine.", opt: true },
      { by: 'a', say: "I don't know what to say." },
      { by: 'b', say: "That's a first." },
      { by: 'a', conf: "They gave me a nickname. The whole camp, together. I'm not crying. Captain Sunburn's crying." },
    ] },
  ],

  // ── can't keep a secret ──
  'run.secret.1': [
    { id: 'nrn.s1', turns: [
      { by: 'b', say: "Okay, I'm going to tell you something, and you can't tell anybody." },
      { by: 'a', say: "I would never." },
      { by: 'b', say: "I think there's a frog living in my shoe." },
      { by: 'a', say: "Oh my gosh." },
      { by: 'b', say: "Promise you won't say anything." },
      { by: 'a', say: "I promise. Hand on heart." },
      { beat: "Two minutes later, {a} is telling everyone at the fire about the frog in {b}'s shoe." },
      { by: 'b', conf: "Nobody tell {a} anything. Not about frogs, not about votes, not about anything. I learned that the easy way, thank goodness." },
    ] },
  ],
  'run.secret.2': [
    { id: 'nrn.s2', when: { call: 1 }, turns: [
      { by: 'a', say: "I'm not supposed to say, but..." },
      { by: 'b', say: "Then don't say." },
      { by: 'a', say: "But it's so good!" },
      { by: 'b', say: "That's what you said about the frog." },
      { by: 'a', say: "The frog was good! Everybody loved the frog!" },
      { by: 'b', say: "I didn't love the frog. It was my shoe." },
      { by: 'a', conf: "I can keep a secret. I just can't keep it for very long. Like, an hour. A good, strong hour." },
    ] },
    { id: 'nrn.s2b', when: { call: 2 }, turns: [
      { beat: "{b} finds {a} sitting alone by the water with {a.posAdj} hand over {a.posAdj} own mouth." },
      { by: 'b', say: "Are you okay?" },
      { by: 'a', say: "Somebody told me something an hour ago, and I've been sitting here so I don't tell anybody." },
      { by: 'b', say: "That's actually really mature." },
      { by: 'a', say: "It's so hard. It's about a vote. It's a really good one." },
      { by: 'b', say: "Don't tell me." },
      { by: 'a', say: "I'm not going to tell you." },
      { by: 'a', say: "...It's about tonight." },
      { by: 'b', conf: "{a} lasted fifty-eight minutes. I timed it. Honestly, that's a personal best." },
    ] },
    { id: 'nrn.s2c', when: { call: 3 }, turns: [
      { by: 'b', say: "I've been thinking. What if everybody stops telling you real secrets?" },
      { by: 'a', say: "That would be awful." },
      { by: 'b', say: "And what if we told you fake ones instead?" },
      { by: 'a', say: "...Wait." },
      { by: 'b', say: "Somebody says something to you, you spread it, and the whole camp hears the wrong thing." },
      { by: 'a', say: "Are you saying I could be a weapon?" },
      { by: 'b', say: "I'm saying you're already a megaphone. We might as well point you somewhere useful." },
      { by: 'b', conf: "Everybody here treats {a}'s big mouth as a problem. I think it's the most useful thing in this camp." },
    ] },
  ],
  'run.secret.3': [
    { id: 'nrn.s3', turns: [
      { by: 'b', say: "Wait. You knew about it this whole time, and you didn't tell anybody?" },
      { by: 'a', say: "Nobody." },
      { by: 'b', say: "You. You kept a secret." },
      { by: 'a', say: "I know! I've been dying! I've been biting my tongue so hard it hurts!" },
      { by: 'b', say: "How long?" },
      { by: 'a', say: "Two whole days. I nearly told a tree yesterday." },
      { by: 'b', conf: "{a} kept a secret for two whole days. I don't know whether to be proud of {a.obj} or scared of what else {a} is capable of." },
    ] },
  ],

  // ── adopts an animal ──
  'run.pet.1': [
    { id: 'nrn.p1', turns: [
      { beat: "{a} walks into camp holding a crab in both hands, very carefully, like it's a baby bird." },
      { by: 'a', say: "Everybody, I'd like you to meet Gerald." },
      { by: 'b', say: "That's a crab." },
      { by: 'a', say: "That's Gerald. He's a crab, and his name is Gerald. Both things can be true." },
      { by: 'b', say: "Where did you even find him?" },
      { by: 'a', say: "He found me. He was sitting on my towel this morning, and he just looked at me." },
      { by: 'b', say: "Crabs don't look at people." },
      { by: 'a', say: "Gerald does. Gerald is very emotionally available." },
      { by: 'b', conf: "We don't have enough food, we don't have enough sleep, and now we have Gerald." },
      { by: 'a', conf: "Everybody in this game is going to lie to me sooner or later. Gerald isn't. Gerald is the only one here I can trust." },
    ] },
  ],
  'run.pet.2': [
    { id: 'nrn.p2', when: { call: 1 }, turns: [
      { beat: "{b} wakes up to find a ring of shells built carefully around {a}'s sleeping spot." },
      { by: 'b', say: "What is that?" },
      { by: 'a', say: "Gerald's house." },
      { by: 'b', say: "Gerald has a house now?" },
      { by: 'a', say: "Everybody needs a home, {b}. Even crabs. Especially crabs, they've had a hard week." },
      { by: 'b', say: "Gerald isn't in it." },
      { by: 'a', say: "He's at work." },
      { by: 'b', say: "At work. Doing what?" },
      { by: 'a', say: "I don't ask him about his job. It's rude." },
      { by: 'b', conf: "{a} built a crab a house. I can't even build us a decent fire, and {a} built a crab a house." },
    ] },
    { id: 'nrn.p3', when: { call: 2 }, turns: [
      { by: 'c', say: "Why is there a crab sitting on my breakfast?", opt: true },
      { by: 'a', say: "Gerald likes you! That's a huge compliment. He doesn't sit on just anybody's breakfast." },
      { by: 'b', say: "That's not Gerald." },
      { by: 'a', say: "What do you mean, that's not Gerald?" },
      { by: 'b', say: "Gerald has a chip in his left claw. This one doesn't." },
      { by: 'a', say: "...How do you know what Gerald's claw looks like?" },
      { by: 'b', say: "Because you've shown me Gerald's claw nine times!" },
      { by: 'a', say: "Then this is Gerald's brother. Gerald Two." },
      { by: 'b', conf: "I came here to play a game for a million dollars. I now know a crab well enough to pick him out of a lineup." },
    ] },
    { id: 'nrn.p3b', when: { call: 3 }, turns: [
      { beat: "{a} is crouched by the shell house, talking quietly. {b} sits down next to {a.obj}." },
      { by: 'b', say: "Are you telling the crab about the vote?" },
      { by: 'a', say: "Gerald's a good listener. And he can't tell anybody." },
      { by: 'b', say: "So what does Gerald think?" },
      { by: 'a', say: "Gerald thinks we should stick together tonight. You and me." },
      { by: 'b', say: "Gerald said that?" },
      { by: 'a', say: "Gerald nodded. Well, he moved his eye stalk. It's basically a nod." },
      { by: 'b', say: "...Okay. If Gerald's in, I'm in." },
      { by: 'b', conf: "I just made an alliance through a crab. I'm not proud of it. I'm also not going back on it, because Gerald's watching." },
    ] },
  ],
  'run.pet.3': [
    { id: 'nrn.p4', turns: [
      { beat: "Early morning. {a} carries Gerald down to the edge of the water, with {b} a few steps behind." },
      { by: 'a', say: "I've been thinking. Gerald doesn't belong in a shell house. He belongs out there." },
      { by: 'b', say: "Are you okay?" },
      { by: 'a', say: "I'm fine. This game isn't a place for a crab. It's barely a place for people." },
      { beat: "{a} sets Gerald down. Gerald stays perfectly still for a moment, then scuttles sideways into the water." },
      { by: 'a', say: "Bye, buddy. Thanks for listening." },
      { by: 'b', say: "He was a good crab." },
      { by: 'a', say: "He was the best crab." },
      { by: 'b', conf: "We had a goodbye ceremony for a crab who isn't dead, and I cried. A little. Do not put that on television." },
    ] },
    { id: 'nrn.p4b', turns: [
      { beat: "{a} comes back from the water pump with a very serious face." },
      { by: 'a', say: "I have news. Gerald has a family." },
      { by: 'b', say: "A what?" },
      { by: 'a', say: "There are four little crabs living under the shell house. Gerald's been a dad this whole time." },
      { by: 'b', say: "So that's where he's been going." },
      { by: 'a', say: "To work. I told you. He was at work. Being a dad is work." },
      { by: 'b', conf: "I didn't expect a crab to make me emotional this season. And yet, here I am, emotional about a crab." },
    ] },
  ],

  // ── a workout club nobody joined ──
  'run.fitness.1': [
    { id: 'nrn.w1', turns: [
      { beat: "Sunrise. {a} is doing push-ups in the middle of camp, counting very loudly." },
      { by: 'a', say: "Forty-one! Forty-two! Who's joining me?" },
      { by: 'b', say: "Nobody. It's six in the morning." },
      { by: 'a', say: "The best time! Forty-three!" },
      { by: 'b', say: "Can you at least count in your head?" },
      { by: 'a', say: "Counting out loud is how you know you mean it! Forty-four!" },
      { by: 'a', conf: "I'm starting a workout club. It's going to get the whole team in shape, and we are never losing another challenge. Membership is free. Membership is currently one." },
    ] },
  ],
  'run.fitness.2': [
    { id: 'nrn.w2', when: { call: 1 }, turns: [
      { by: 'a', say: "Workout club in five minutes! Bring water!" },
      { by: 'b', say: "How many people came yesterday?" },
      { by: 'a', say: "One. But it was a great one." },
      { by: 'b', say: "Was it you?" },
      { by: 'a', say: "It was me, and I was amazing. I did a personal best." },
      { by: 'b', say: "At what?" },
      { by: 'a', say: "At showing up. You should try it." },
      { by: 'b', conf: "Every morning, {a} runs a workout club for exactly one person. The commitment is honestly a little inspiring. I'm still not going." },
    ] },
    { id: 'nrn.w2b', when: { call: 2 }, turns: [
      { beat: "{a} has drawn a poster in charcoal on a flat rock: WORKOUT CLUB. ALL WELCOME. SNACKS AFTER." },
      { by: 'b', say: "Snacks after? We don't have snacks." },
      { by: 'a', say: "That's a problem for after." },
      { by: 'c', say: "Is it a lie if it brings people in?", opt: true },
      { by: 'a', say: "It's marketing." },
      { by: 'b', say: "How many people did the poster get you?" },
      { by: 'a', say: "Two. Both of them left when they found out about the snacks." },
      { by: 'b', conf: "{a} lied on a poster to get people to exercise. I didn't know that was a thing you could do. I'm learning a lot about {a} this week." },
    ] },
    { id: 'nrn.w2c', when: { call: 3 }, turns: [
      { by: 'b', say: "You know people are starting to say you're the strongest one here, right?" },
      { by: 'a', say: "That's the workout club!" },
      { by: 'b', say: "That's not a good thing. Strong people go home at the merge." },
      { by: 'a', say: "...Oh. Oh no." },
      { by: 'b', say: "So maybe stop doing push-ups in the middle of camp where everybody can see." },
      { by: 'a', say: "But that's the best spot! The light is perfect!" },
      { by: 'a', conf: "I've spent weeks trying to get people to notice my workout club. Turns out they noticed. Now I need them to stop noticing, immediately." },
    ] },
  ],
  'run.fitness.3': [
    { id: 'nrn.w3', turns: [
      { beat: "Sunrise. {a} walks out of the {quarters}, and {b} is already there, stretching." },
      { by: 'a', say: "What are you doing?" },
      { by: 'b', say: "Don't make it a big deal." },
      { by: 'a', say: "Workout club! It's happening! Everybody, workout club is HAPPENING!" },
      { by: 'b', say: "I said don't make it a big deal!" },
      { by: 'a', say: "This is the biggest deal of my life! I'm going to make you a membership card!" },
      { by: 'b', conf: "{a} asked me every morning for weeks. I finally said yes, mostly so {a} would stop asking. Don't tell {a} I actually liked it." },
    ] },
  ],

  // ── narrates their own life ──
  'run.drama.1': [
    { id: 'nrn.d1', turns: [
      { by: 'a', say: "And so, our hero wakes, alone, in a strange and terrible land." },
      { by: 'b', say: "You're narrating again." },
      { by: 'a', say: "Our hero's tribe-mate is very rude before breakfast." },
      { by: 'b', say: "Our hero's tribe-mate hasn't had breakfast, because our hero burnt it." },
      { by: 'a', say: "A cruel blow. Our hero carries on." },
      { by: 'a', conf: "Everybody here thinks they're the main character. I'm just the only one honest enough to say it out loud." },
    ] },
  ],
  'run.drama.2': [
    { id: 'nrn.d2', when: { call: 1 }, turns: [
      { by: 'a', say: "Little did they know, the rice was undercooked." },
      { by: 'b', say: "We all know the rice is undercooked. You cooked it." },
      { by: 'a', say: "A shocking twist!" },
      { by: 'b', say: "It's not a twist if you made it happen." },
      { by: 'a', say: "Those are the best twists." },
      { by: 'b', conf: "Living with {a} is like being stuck inside a nature documentary about one very dramatic animal." },
    ] },
    { id: 'nrn.d2b', when: { call: 2 }, turns: [
      { beat: "{a} is narrating quietly while {b} and {c} whisper by the water." },
      { by: 'a', say: "And there, by the water, two players plot in secret, unaware they are being watched..." },
      { by: 'b', say: "We can hear you!" },
      { by: 'a', say: "...unaware they are being watched by a very talented narrator." },
      { by: 'c', say: "Can you narrate somewhere else?", opt: true },
      { by: 'a', say: "The narrator goes where the story is." },
      { by: 'b', conf: "{a} narrating us is annoying. {a} narrating our strategy meeting, out loud, by the water, is a security problem." },
    ] },
    { id: 'nrn.d2c', when: { call: 3 }, turns: [
      { by: 'b', say: "Okay, I need your help." },
      { by: 'a', say: "Our hero is needed!" },
      { by: 'b', say: "Yes. I want you to narrate tonight's vote. Loudly, around the camp, before we go." },
      { by: 'a', say: "Why?" },
      { by: 'b', say: "Because if you say the wrong name dramatically enough, everybody will think it's the real one." },
      { by: 'a', say: "You want me to narrate a lie." },
      { by: 'b', say: "I want you to narrate a twist." },
      { by: 'a', conf: "I've been training for this my entire life. I just didn't know it would be with a fake vote on an island." },
    ] },
  ],
  'run.drama.3': [
    { id: 'nrn.d3', turns: [
      { by: 'b', say: "And so, against all the odds, our hero made it further than anybody thought." },
      { by: 'a', say: "Wait. Are you narrating me?" },
      { by: 'b', say: "Somebody had to. You've been doing it for everybody else for weeks." },
      { by: 'a', say: "Keep going. Please. Keep going." },
      { by: 'b', say: "Our hero's narration was annoying, but our hero was loved." },
      { by: 'a', conf: "{b} narrated me. Me. I've never been the subject of a narration before. I'm so moved I could do a whole monologue about it, and I might." },
    ] },
  ],

  // ── can't stop talking about their job ──
  'run.job.1': [
    { id: 'nrn.j1', when: { job: true }, turns: [
      { by: 'b', say: "How do you know how to do that?" },
      { by: 'a', say: "Oh, back home I'm a {job}. You pick things up." },
      { by: 'b', say: "A {job} taught you to do that?" },
      { by: 'a', say: "Being a {job} teaches you everything, if you pay attention." },
      { by: 'b', say: "Name one thing it taught you that's useful out here." },
      { by: 'a', say: "Patience. And how to tie a really good knot." },
      { by: 'b', conf: "I've learned more about being a {job} in three days than I ever wanted to know in my whole life." },
    ] },
  ],
  'run.job.2': [
    { id: 'nrn.j2', when: { job: true, call: 1 }, turns: [
      { by: 'a', say: "You know, this reminds me of something that happened at work once." },
      { by: 'b', say: "Everything reminds you of work." },
      { by: 'a', say: "Because being a {job} is basically this, but with better snacks and fewer bugs." },
      { by: 'b', say: "Please don't tell the story about your boss again." },
      { by: 'a', say: "It's a different story." },
      { by: 'b', say: "Is your boss in it?" },
      { by: 'a', say: "...My boss is in all of them." },
      { by: 'b', conf: "I know {a}'s boss's name, birthday, and favourite sandwich. I have never met this person." },
    ] },
    { id: 'nrn.j2b', when: { job: true, call: 2 }, turns: [
      { by: 'b', say: "Okay, I've been keeping count. That's eleven work stories today." },
      { by: 'a', say: "Eleven? It's not even lunch." },
      { by: 'b', say: "I know. That's why I'm worried." },
      { by: 'a', say: "Being a {job} is a big part of who I am." },
      { by: 'b', say: "We know. Everybody here could do your job by now." },
      { by: 'a', say: "Then you're welcome, because that's free training." },
      { by: 'a', conf: "People laugh at the work stories, but every single one of them has a lesson. Mostly about trusting nobody. That's useful here." },
    ] },
    { id: 'nrn.j2c', when: { job: true, call: 3 }, turns: [
      { by: 'b', say: "Can I ask you something about being a {job}? For real this time?" },
      { by: 'a', say: "You want a work story? Voluntarily?" },
      { by: 'b', say: "How do you deal with people at work who say one thing and do another?" },
      { by: 'a', say: "Oh. You write everything down, and you never let them know you're writing it down." },
      { by: 'b', say: "That's actually really good advice for out here." },
      { by: 'a', say: "Everything about being a {job} is really good advice for out here. I've been telling you for weeks." },
      { by: 'b', conf: "I spent a month rolling my eyes at {a}'s job, and it turns out it was the best strategy class in the game." },
    ] },
  ],
  'run.job.3': [
    { id: 'nrn.j3', when: { job: true }, turns: [
      { beat: "Something breaks at camp, and everybody, without saying a word, turns to look at {a}." },
      { by: 'a', say: "What?" },
      { by: 'b', say: "You're the {job}. Fix it." },
      { by: 'a', say: "I've been waiting my whole life for this moment." },
      { by: 'c', say: "Just fix it, please.", opt: true },
      { by: 'a', say: "Stand back. This is what I trained for." },
      { by: 'b', conf: "We teased {a} about being a {job} for weeks, and then the one time it mattered, it really did matter. I'm never going to hear the end of it." },
    ] },
  ],
};
