// ══════════════════════════════════════════════════════════════════════
// td/story/lines/n-vote2.js — more of the vote, talked through (n-vote.js has the header)
// ══════════════════════════════════════════════════════════════════════
//
// Every camp that votes gets these scenes every vote, so each pool needs a season's worth of
// different conversations. Ids: 'nw.'.

const C = (id, when, conf, v) => ({ id, ...(when ? { when } : {}), turns: [{ by: 'a', conf, ...(v ? { v } : {}) }] });

export default {
  'story.vote.plan.plan': [
    { id: 'nw.p1', place: 'wash', turns: [
      { beat: "{a} and {b} are washing up {here}, side by side." },
      { by: 'a', say: "So. Tonight." },
      { by: 'b', say: "Tonight. Who've you got?" },
      { by: 'a', say: "{target}. That's what I keep hearing." },
      { by: 'b', say: "From who?" },
      { by: 'a', say: "Enough people. {votes}, if everybody does what they said." },
      { by: 'b', say: "That's a big if." },
      { by: 'a', say: "It's always a big if. But {target} is the name nobody argues with." },
      { by: 'b', say: "Okay. {target}." },
      { by: 'b', conf: "Nobody here hates {target}. Nobody's going to fight for {target} either. That's how you end up being the name." },
    ] },
    { id: 'nw.p2', place: 'sleep', turns: [
      { beat: "{a} sits on the end of {b}'s {bed} in the {quarters}." },
      { by: 'b', say: "You're doing the face." },
      { by: 'a', say: "What face?" },
      { by: 'b', say: "The I've-got-a-plan face." },
      { by: 'a', say: "Fine, {target}, tonight." },
      { by: 'b', say: "Why {target}?" },
      { by: 'a', say: "Because I can get {votes} people to write it. I can't get that many on anyone else." },
      { by: 'b', say: "You've done the maths." },
      { by: 'a', say: "Twice." },
      { by: 'a', conf: "I'd love to tell you {target} is some huge threat. Honestly, {target} is just the name that adds up." },
    ] },
    { id: 'nw.p3', place: 'work', turns: [
      { beat: "{a} and {b} are hauling water {here}. {a} waits until they're out of earshot." },
      { by: 'a', say: "Are you okay with {target}?" },
      { by: 'b', say: "For tonight?" },
      { by: 'a', say: "For tonight." },
      { by: 'b', say: "I don't love it. {target} has been nice to me." },
      { by: 'a', say: "{target} has been nice to everybody. That's not a reason to keep {target}." },
      { by: 'b', say: "It's kind of a reason." },
      { by: 'a', say: "It's {votes} votes or it's a mess. I'd rather have the votes." },
      { by: 'b', say: "...Fine. {target}." },
      { by: 'b', conf: "I keep voting for people I like. I wish this game had more people I didn't." },
    ] },
    { id: 'nw.p4', place: 'secret', when: { merged: true }, turns: [
      { by: 'b', say: "Okay, it's the merge, so everyone's going to be scrambling. What's our name?" },
      { by: 'a', say: "{target}." },
      { by: 'b', say: "Not one of the big names?" },
      { by: 'a', say: "Big names have friends and {target} doesn't, so tonight we take the vote that actually works." },
      { by: 'b', say: "And next time?" },
      { by: 'a', say: "Next time we go big. You need numbers before you go big." },
      { by: 'a', conf: "{votes} people writing {target}. It's not exciting, but exciting is how you go home." },
    ] },
    { id: 'nw.p5', place: 'water', turns: [
      { beat: "{a} and {b} sit {here} with their feet in the water." },
      { by: 'b', say: "I've heard three different names today." },
      { by: 'a', say: "Forget the other two. It's {target}." },
      { by: 'b', say: "How do you know?" },
      { by: 'a', say: "Because I'm the one who's been saying {target}, and people have been saying it back." },
      { by: 'b', say: "So you started it." },
      { by: 'a', say: "Somebody had to." },
      { by: 'b', conf: "Every vote, somebody picks the name, and tonight it was {a}, and I'm just glad it wasn't my name." },
    ] },
    { id: 'nw.p6', place: 'aside', when: { voice: ['loud', 'tough', 'blunt'] }, turns: [
      { by: 'a', say: "It's {target}, done, don't overthink it." },
      { by: 'b', say: "That's it? That's the whole plan?" },
      { by: 'a', say: "That's the whole plan: {votes} of us write {target} and then we go to bed." },
      { by: 'b', say: "What if something changes?" },
      { by: 'a', say: "Then come find me and I'll fix it." },
      { by: 'b', conf: "{a} plans votes the way {a} does everything, loud and fast and really sure, and I just hope sure means right." },
    ] },
    { id: 'nw.p7', place: 'aside', when: { voice: ['ditzy', 'goofy', 'food', 'chaotic'] }, turns: [
      { by: 'a', say: "Okay, I've been doing strategy. Are you ready?" },
      { by: 'b', say: "Oh no." },
      { by: 'a', say: "It's {target}! Everybody says {target}, I asked like everyone." },
      { by: 'b', say: "You asked everyone? Including {target}?" },
      { by: 'a', say: "...No. I'm not THAT bad at this." },
      { by: 'b', say: "Okay, {target}. Good work." },
      { by: 'a', conf: "I did strategy today! I'm basically a mastermind now. Well, a small one." },
    ] },
    { id: 'nw.p8', place: 'aside', when: { third: true }, turns: [
      { by: 'a', say: "Okay, let's make this quick before people notice." },
      { by: 'c', say: "Notice what? Three people standing behind a tree?" },
      { by: 'a', say: "It's {target} tonight. That's the name." },
      { by: 'b', say: "Fine by me." },
      { by: 'c', say: "Why {target}?" },
      { by: 'a', say: "Because everyone else has somebody looking out for them. {target} doesn't. {votes} of us, and nobody fights it." },
      { by: 'c', say: "...Okay. {target}." },
      { by: 'a', conf: "That's the boring way to win a vote, but boring is good, because boring means it actually happens." },
    ] },
    { id: 'nw.p9', place: 'fire', turns: [
      { beat: "{a} pokes the fire. {b} sits next to {a.obj}." },
      { by: 'b', say: "So are we good for tonight?" },
      { by: 'a', say: "{target}." },
      { by: 'b', say: "Still?" },
      { by: 'a', say: "Still. Nothing's changed, and if anything, more people are on it now." },
      { by: 'b', say: "Then why do you look worried?" },
      { by: 'a', say: "Because nothing's changed. That's when somebody's about to change it." },
      { by: 'b', conf: "{a} is paranoid. But {a} is paranoid and still here, so maybe that's the trick." },
    ] },
  ],
  'story.vote.plan.weak': [
    { id: 'nw.w1', place: 'public', when: { sank: true }, turns: [
      { by: 'b', say: "So. We all saw today." },
      { by: 'a', say: "We all saw today." },
      { by: 'b', say: "{target} just stopped. Right in the middle." },
      { by: 'a', say: "And that's the third time something like that's happened, so it's {target} tonight, and I've got {votes} on it." },
      { by: 'b', say: "I feel bad." },
      { by: 'a', say: "Feel bad after we win the next one." },
      { by: 'a', conf: "I'm not voting for {target} because I'm mean. I'm voting for {target} because I want to win a challenge before the merge." },
    ] },
    { id: 'nw.w2', place: 'aside', when: { voice: ['warm', 'anxious', 'earnest'] }, turns: [
      { by: 'a', say: "I think it has to be {target}." },
      { by: 'b', say: "Because of the challenges?" },
      { by: 'a', say: "Because of the challenges. I hate saying it, because {target} tries so hard." },
      { by: 'b', say: "Trying doesn't win anything, though." },
      { by: 'a', say: "I know. That's why I hate saying it." },
      { by: 'a', conf: "{target} is a sweetheart. But sweet doesn't carry anything across the finish line." },
    ] },
    { id: 'nw.w3', place: 'work', turns: [
      { beat: "{a} and {b} are fixing the {quarters} {here}." },
      { by: 'a', say: "Hold that end. No, the other end." },
      { by: 'b', say: "You're in a mood." },
      { by: 'a', say: "I'm in a we-keep-losing mood. It's {target} tonight." },
      { by: 'b', say: "Because {target} isn't strong enough." },
      { by: 'a', say: "Because we need people who can pull their weight, and {target} can't, and {votes} of us agree." },
      { by: 'b', conf: "{a} is right. It's still a horrible thing to say about somebody while holding up their roof." },
    ] },
    { id: 'nw.w4', place: 'aside', when: { third: true }, turns: [
      { by: 'a', say: "Quick vote count. Who's the weakest one we've got?" },
      { by: 'b', say: "That's harsh." },
      { by: 'c', say: "It's {target}. We all know it's {target}." },
      { by: 'a', say: "So that's {votes}. Unless anybody has a better idea." },
      { by: 'b', say: "I don't." },
      { by: 'c', conf: "This is the part of the game I don't like, because nobody did anything wrong, somebody's just the slowest." },
    ] },
  ],
  'story.vote.plan.threat': [
    { id: 'nw.t1', place: 'secret', turns: [
      { beat: "{a} has been waiting for {b} {here}." },
      { by: 'b', say: "This had better be good. I was eating." },
      { by: 'a', say: "{target} has won more than anybody here. And talked to more people than anybody here." },
      { by: 'b', say: "So?" },
      { by: 'a', say: "So if we don't do it tonight, {target} wins immunity next time, and the time after that, and then {target} wins the whole thing." },
      { by: 'b', say: "And you've got the votes?" },
      { by: 'a', say: "{votes}. If you're in." },
      { by: 'b', move: 'agree.reluctant' },
      { by: 'b', conf: "{target} is the best player here. That's a compliment {target} is going to hear tonight." },
    ] },
    { id: 'nw.t2', place: 'aside', when: { voice: ['schemer', 'calm', 'dry', 'cruel'] }, turns: [
      { by: 'a', say: "Can I tell you who's actually running this place?" },
      { by: 'b', say: "I thought you were." },
      { by: 'a', say: "Ha, no, {target} is. Watch who everybody goes to after a challenge, it's always {target}." },
      { by: 'b', say: "Huh. You're right." },
      { by: 'a', say: "So we cut it off tonight. {target}, {votes} votes." },
      { by: 'a', conf: "The person everybody talks to is the person who decides the votes. I'd like that to be me." },
    ] },
    { id: 'nw.t3', place: 'aside', when: { voice: ['warm', 'anxious', 'earnest', 'emotional'] }, turns: [
      { by: 'b', say: "Are you sure about {target}? You two are close." },
      { by: 'a', say: "That's why I'm sure. I know how good {target} is at this." },
      { by: 'b', say: "That's kind of cold." },
      { by: 'a', say: "I know, and I don't feel cold, I feel sick, but if I wait, {target} beats all of us." },
      { by: 'a', conf: "I'm going to write {target}'s name, and then I'm going to feel bad about it for a long time." },
    ] },
    { id: 'nw.t4', place: 'aside', when: { late: true }, turns: [
      { by: 'a', say: "Look how few of us are left." },
      { by: 'b', say: "I know." },
      { by: 'a', say: "So think about the jury. Who are they voting for if {target} gets to the end?" },
      { by: 'b', say: "{target}." },
      { by: 'a', say: "{target}, every single time, so {target} doesn't get to the end." },
      { by: 'b', conf: "This late in the game it's not about who you like, it's about who beats you, and {target} beats me." },
    ] },
  ],
  'story.vote.plan.grudge': [
    { id: 'nw.g1', place: 'aside', turns: [
      { by: 'a', say: "I can't do another day with {target}. I'm serious." },
      { by: 'b', say: "What did {target} do now?" },
      { by: 'a', say: "Everything, all of it, all the time." },
      { by: 'b', say: "Okay, but is there a game reason?" },
      { by: 'a', say: "The game reason is I'll be playing better without {target} in my head. And {votes} people feel the same." },
      { by: 'b', conf: "This isn't strategy, it's {a} needing {target} gone, and lucky for {a}, half the camp does too." },
    ] },
    { id: 'nw.g2', place: 'eat', turns: [
      { beat: "Dinner {here}. {target} is at the other end. {a} doesn't look up." },
      { by: 'b', say: "You haven't said a word to {target} all day." },
      { by: 'a', say: "I'll say one tonight. On a piece of paper." },
      { by: 'b', say: "That's dark." },
      { by: 'a', say: "Everyone's on it, {votes} of us, because {target} made a lot of people angry this week." },
      { by: 'a', conf: "Some people play this game, and {target} just annoys everybody in it, so tonight it stops." },
    ] },
    { id: 'nw.g3', place: 'aside', when: { voice: ['warm', 'anxious', 'earnest'] }, turns: [
      { by: 'a', say: "Is it bad that I want {target} gone because of how {target} talked to me?" },
      { by: 'b', say: "No. {target} was really mean to you." },
      { by: 'a', say: "I thought I'd be the bigger person." },
      { by: 'b', say: "You can be the bigger person who votes {target} out. A lot of us are." },
      { by: 'a', conf: "I'm not proud of it, but {target} made me feel tiny, and tonight I feel a little bigger." },
    ] },
  ],
  'story.vote.plan.strike': [
    { id: 'nw.s1', place: 'secret', turns: [
      { by: 'b', say: "Where's the fire?" },
      { by: 'a', say: "{target}. {target} is trying to vote you out tonight." },
      { by: 'b', say: "What? Who said that?" },
      { by: 'a', say: "{target} said it, to somebody who told me. So we're voting {target}. {votes} of us, if you're in." },
      { by: 'b', say: "I'm in. I'm very in." },
      { by: 'b', conf: "Ten minutes ago, I had nothing against {target}. Now {target} is the only name I want to write." },
    ] },
    { id: 'nw.s2', place: 'aside', when: { voice: ['loud', 'tough', 'blunt'] }, turns: [
      { by: 'a', say: "Guess whose name {target} has been throwing around?" },
      { by: 'b', say: "Yours?" },
      { by: 'a', say: "Mine, so it's {target} tonight, and I don't care who else {target} likes." },
      { by: 'b', say: "Do we have the numbers?" },
      { by: 'a', say: "{votes}. {target} picked the wrong person." },
      { by: 'a', conf: "You want to come after me? Fine, just be ready for me to come after you first." },
    ] },
  ],
  'story.vote.plan.shield': [
    { id: 'nw.h1', place: 'secret', turns: [
      { by: 'a', say: "People wanted to vote you out tonight." },
      { by: 'b', say: "...Oh." },
      { by: 'a', say: "I've been moving people all afternoon, and now it's {target}, {votes} people." },
      { by: 'b', say: "You did that for me?" },
      { by: 'a', say: "You'd have done it for me. Just act normal tonight." },
      { by: 'b', conf: "I didn't even know I was in trouble. I'd be going home without {a}." },
    ] },
    { id: 'nw.h2', place: 'aside', when: { voice: ['schemer', 'calm', 'proud'] }, turns: [
      { by: 'a', say: "You owe me." },
      { by: 'b', say: "For what?" },
      { by: 'a', say: "Your name was the plan an hour ago. Now the plan is {target}." },
      { by: 'b', say: "How?" },
      { by: 'a', say: "I talked to people, and it's {votes} now. You're welcome." },
      { by: 'a', conf: "I saved {b} tonight. And the best thing about saving people is they remember it at the end." },
    ] },
  ],

  'story.vote.other.boot': [
    { id: 'nw.o1', place: 'aside', turns: [
      { by: 'a', say: "We're writing {target}, right?" },
      { by: 'b', say: "That's what you said." },
      { by: 'a', say: "Good, because I'm sick of {target}, and everybody I've talked to is sick of {target}." },
      { by: 'b', say: "Everybody?" },
      { by: 'a', say: "Everybody. Tonight's going to be easy." },
      { by: 'a', conf: "{target} should start packing. I'd help, but I'm busy feeling good about tonight." },
    ] },
    { id: 'nw.o2', place: 'water', turns: [
      { beat: "{a} and {b} are skipping stones {here}." },
      { by: 'b', say: "You're in a good mood." },
      { by: 'a', say: "Because I know how tonight goes. {target}." },
      { by: 'b', say: "You've checked with people?" },
      { by: 'a', say: "Checked, double-checked. Everyone's nodding." },
      { by: 'b', say: "Nodding isn't voting." },
      { by: 'a', say: "Don't ruin my good mood." },
      { by: 'b', conf: "{a} is really sure about tonight. People are only that sure in this game right before it goes wrong." },
    ] },
    { id: 'nw.o3', place: 'sleep', when: { voice: ['warm', 'anxious', 'earnest', 'ditzy'] }, turns: [
      { by: 'a', say: "Can I tell you something? I think tonight is going to be okay." },
      { by: 'b', say: "Yeah?" },
      { by: 'a', say: "It's going to be {target}, everyone said so, I asked like five people." },
      { by: 'b', say: "Did any of them look weird when you asked?" },
      { by: 'a', say: "...No? I don't think so? Why?" },
      { by: 'b', say: "No reason." },
      { by: 'a', conf: "I'm actually relaxed tonight, which never happens, because I'm sure it's {target}." },
    ] },
    { id: 'nw.o4', place: 'aside', when: { voice: ['schemer', 'calm', 'dry', 'competitive', 'proud'] }, turns: [
      { by: 'a', say: "{target} has been running around all afternoon." },
      { by: 'b', say: "Scrambling?" },
      { by: 'a', say: "Yeah, scrambling, which pretty much tells you {target} is going home." },
      { by: 'b', say: "What if {target} is scrambling against somebody else?" },
      { by: 'a', say: "Then that somebody else should be worried. Not me." },
      { by: 'a', conf: "Everybody's on {target}. I'm going to sleep great tonight." },
    ] },
    { id: 'nw.o5', place: 'fire', when: { third: false }, turns: [
      { by: 'b', say: "Who are you writing?" },
      { by: 'a', say: "{target}. You?" },
      { by: 'b', say: "{target}." },
      { by: 'a', say: "See? Easy, everyone's saying {target}." },
      { by: 'b', say: "Who's everyone?" },
      { by: 'a', say: "You know. Everyone." },
      { by: 'b', conf: "{a} didn't name a single person. I'm writing {target}, but I'm not as relaxed as {a} is." },
    ] },
  ],
  'story.vote.other.losing': [
    { id: 'nw.l1', place: 'aside', turns: [
      { by: 'a', say: "Is anyone else on {target} or is it just us?" },
      { by: 'b', say: "I think it's just us." },
      { by: 'a', say: "Great. So we're throwing our votes away." },
      { by: 'b', say: "We're making a point." },
      { by: 'a', say: "The point being we don't have any friends." },
      { by: 'b', conf: "We're going to write {target}, lose the vote, and then everyone's going to know exactly where we stand. Excellent." },
    ] },
    { id: 'nw.l2', place: 'secret', when: { voice: ['warm', 'anxious', 'earnest', 'emotional'] }, turns: [
      { by: 'a', say: "I tried. I really tried to get people on {target}." },
      { by: 'b', say: "And?" },
      { by: 'a', say: "And everyone said maybe. Which means no." },
      { by: 'b', say: "So what do we do?" },
      { by: 'a', say: "We write {target} anyway and hope the maybes meant yes." },
      { by: 'a', conf: "I don't think the maybes meant yes." },
    ] },
  ],

  'story.vote.swing.yes': [
    { id: 'nw.y1', place: 'aside', when: { swing: 'numbers' }, turns: [
      { by: 'b', say: "You've been talking to everyone today. What's going on?" },
      { by: 'a', say: "{target}. Tonight." },
      { by: 'b', say: "How many?" },
      { by: 'a', say: "With you, {votes}." },
      { by: 'b', say: "And without me?" },
      { by: 'a', say: "Still enough. But I'd rather you were on the right side of it." },
      { by: 'b', say: "...Okay. I'm on the right side of it." },
      { by: 'b', conf: "{a} didn't need me. That's exactly why I said yes. You don't want to be the one vote that wasn't there." },
    ] },
    { id: 'nw.y2', place: 'work', when: { swing: 'trust' }, turns: [
      { beat: "{a} picks up the other end of the log {b} is dragging." },
      { by: 'b', say: "Thanks. What do you want?" },
      { by: 'a', say: "Why does everybody think I want something?" },
      { by: 'b', say: "Because you always do." },
      { by: 'a', say: "Fine. {target}, tonight. Will you do it?" },
      { by: 'b', say: "If you're asking, yeah. You haven't lied to me yet." },
      { by: 'a', conf: "{b} says yes because {b} trusts me. That's worth more than the vote. I need to keep it that way." },
    ] },
    { id: 'nw.y3', place: 'aside', when: { swing: 'self' }, turns: [
      { by: 'a', say: "I'll be honest. The other name going around tonight was yours." },
      { by: 'b', say: "What?!" },
      { by: 'a', say: "Relax, I moved it, it's {target} now, but I need you to write it." },
      { by: 'b', say: "Obviously I'm writing it. I'd write anything that isn't me." },
      { by: 'b', conf: "{a} could be lying about my name being out there. I'm still not taking the chance." },
    ] },
    { id: 'nw.y4', place: 'fire', turns: [
      { by: 'a', say: "Can I count on you tonight?" },
      { by: 'b', say: "Depends who for." },
      { by: 'a', say: "{target}." },
      { by: 'b', say: "{target}, huh. I was wondering when somebody would say it." },
      { by: 'a', say: "So that's a yes." },
      { by: 'b', say: "That's a yes." },
      { by: 'b', conf: "I've been waiting for somebody to bring me {target}'s name. I just didn't want to be the one who said it first." },
    ] },
    { id: 'nw.y5', place: 'work', turns: [
      { beat: "{a} finds {b} {here}, alone with a pile of chores." },
      { by: 'a', say: "Want help?" },
      { by: 'b', say: "Always. What's the catch?" },
      { by: 'a', say: "No catch. Well, a small catch: {target}, tonight." },
      { by: 'b', say: "{target}? Why?" },
      { by: 'a', say: "Because it's that, or it's one of us. And I'd really like it not to be one of us." },
      { by: 'b', say: "...Okay. Grab that end." },
      { by: 'b', conf: "{a} wanted my vote and carried half my chores to get it. That's a fair price." },
    ] },
    { id: 'nw.y6', place: 'aside', turns: [
      { by: 'b', say: "You've got that look. Who is it?" },
      { by: 'a', say: "{target}." },
      { by: 'b', say: "Huh. I thought it'd be somebody else." },
      { by: 'a', say: "So does {target}. That's why it works." },
      { by: 'b', say: "And you need me." },
      { by: 'a', say: "I'd like you. It's better when it isn't close." },
      { by: 'b', say: "Fine. I'm in." },
      { by: 'a', conf: "That's {votes}, and I'm not celebrating until the votes are read, but that's {votes}." },
    ] },
    { id: 'nw.y7', place: 'water', turns: [
      { beat: "{a} sits down next to {b} {here}." },
      { by: 'a', say: "I'm going to be honest with you, because you'd figure it out anyway. It's {target} tonight." },
      { by: 'b', say: "Is that a question?" },
      { by: 'a', say: "It's an invitation." },
      { by: 'b', say: "You're very polite about votes." },
      { by: 'a', say: "Is that a yes?" },
      { by: 'b', say: "It's a yes." },
      { by: 'b', conf: "I like that {a} told me straight. Half the people here would have told me it was somebody else." },
    ] },
    { id: 'nw.y8', place: 'aside', when: { voiceB: ['loud', 'tough', 'blunt', 'competitive'] }, turns: [
      { by: 'a', say: "{target}. You in?" },
      { by: 'b', say: "Finally. Somebody with a plan." },
      { by: 'a', say: "So that's a yes." },
      { by: 'b', say: "That's a yes. I've been waiting all day for somebody to say a name I could live with." },
      { by: 'b', conf: "I don't need a big speech. Give me a name that makes sense and I'll write it." },
    ] },
    { id: 'nw.y9', place: 'fire', when: { voiceB: ['anxious', 'emotional', 'earnest'] }, turns: [
      { by: 'a', say: "Hey, it's going to be {target} tonight, and I wanted you to hear it from me." },
      { by: 'b', say: "Oh... okay. Thank you for telling me." },
      { by: 'a', say: "Are you okay with it?" },
      { by: 'b', say: "I'm not okay with any of it. But I'm okay with it being {target} and not me." },
      { by: 'b', conf: "I said yes. I always say yes. I just hope somebody tells me first like that, the night it's me." },
    ] },
    { id: 'nw.y10', place: 'aside', when: { merged: true }, turns: [
      { by: 'a', say: "You've been floating between groups all week." },
      { by: 'b', say: "I've been listening to groups all week." },
      { by: 'a', say: "Then listen to this one. It's {target}, and we have the numbers with you." },
      { by: 'b', say: "And without me?" },
      { by: 'a', say: "Then we're less sure, and you're the person nobody trusts after tonight." },
      { by: 'b', say: "...Fine. {target}." },
      { by: 'b', conf: "Being the swing vote is great until you swing the wrong way. I'm not swinging the wrong way tonight." },
    ] },
    { id: 'nw.y11', place: 'eat', turns: [
      { beat: "{a} slides in next to {b} {here} and keeps {a.posAdj} voice low." },
      { by: 'a', say: "Don't look up. {target}, tonight." },
      { by: 'b', say: "Why can't I look up?" },
      { by: 'a', say: "Because {target} is sitting right over there." },
      { by: 'b', say: "...Oh. Okay, yes." },
      { by: 'b', conf: "{a} pitched me a vote at dinner with the target ten feet away. That's either brave or stupid. I said yes, so I hope it's brave." },
    ] },
    { id: 'nw.y12', place: 'aside', when: { voiceB: ['schemer', 'calm', 'dry', 'proud'] }, turns: [
      { by: 'a', say: "{target}. I need you." },
      { by: 'b', say: "You need me, or you need a vote?" },
      { by: 'a', say: "Today, a vote. Tomorrow, maybe you." },
      { by: 'b', say: "That's honest. I'll do it." },
      { by: 'b', conf: "Everybody's going to remember who was on the right side tonight. I want to be one of them." },
    ] },
  ],
  'story.vote.swing.no': [
    { id: 'nw.n1', place: 'aside', turns: [
      { by: 'a', say: "It's {target} tonight, and I need you." },
      { by: 'b', move: 'refuse' },
      { by: 'a', say: "You didn't even let me finish." },
      { by: 'b', say: "I don't need you to finish. I'm not voting {target}." },
      { by: 'a', say: "Then who are you voting?" },
      { by: 'b', say: "That's my business." },
      { by: 'a', conf: "{b} won't tell me. That means {b} is with somebody else. I need to find out who before tonight." },
    ] },
    { id: 'nw.n2', place: 'aside', when: { swing: 'protect' }, turns: [
      { by: 'a', say: "I need your vote on {target}." },
      { by: 'b', say: "{target} has had my back since day one." },
      { by: 'a', say: "And?" },
      { by: 'b', say: "And I don't stab people who've had my back. Ask somebody else." },
      { by: 'b', conf: "If {target} goes tonight, it's not going to be with my vote. I'm not that kind of player." },
    ] },
    { id: 'nw.n3', place: 'aside', when: { voiceB: ['schemer', 'calm', 'dry', 'competitive'] }, turns: [
      { by: 'a', say: "{target}, tonight. You in?" },
      { by: 'b', say: "What's in it for me?" },
      { by: 'a', say: "{target} goes home." },
      { by: 'b', say: "That's in it for you. I said what's in it for me." },
      { by: 'a', say: "...I'll owe you." },
      { by: 'b', say: "Everyone's going to owe me eventually. Not tonight." },
      { by: 'a', conf: "{b} is shopping for a better deal. Tonight I don't have one to give." },
    ] },
    { id: 'nw.n4', place: 'aside', turns: [
      { by: 'a', say: "Are you with us on {target}?" },
      { by: 'b', say: "No. Sorry." },
      { by: 'a', say: "Can I ask why?" },
      { by: 'b', say: "Because {target} isn't the one I'm worried about. I'm not wasting my vote." },
      { by: 'a', say: "Then who are you worried about?" },
      { by: 'b', say: "That's my business tonight." },
      { by: 'a', conf: "{b} has a different name. If enough people have a different name, tonight gets messy." },
    ] },
    { id: 'nw.n5', place: 'water', when: { voiceB: ['warm', 'anxious', 'earnest', 'emotional'] }, turns: [
      { by: 'a', say: "We're doing {target} tonight. Will you vote with us?" },
      { by: 'b', say: "I can't, I'm sorry, {target} has been so nice to me." },
      { by: 'a', say: "Nice doesn't keep you here." },
      { by: 'b', say: "Maybe not. But I have to be able to look at myself tomorrow." },
      { by: 'b', conf: "I said no and I'm terrified, but I'd feel worse if I'd said yes." },
    ] },
  ],

  'story.vote.target.scramble': [
    { id: 'nw.c1', place: 'secret', turns: [
      { by: 'a', say: "Please tell me you're not writing my name." },
      { by: 'b', say: "Where'd you hear that?" },
      { by: 'a', say: "Everywhere. I just need to know you're with me, so it's {wrote}, okay? Not me, {wrote}." },
      { by: 'b', say: "Okay. {wrote}." },
      { by: 'a', say: "Promise?" },
      { by: 'b', say: "Promise." },
      { by: 'a', conf: "I've talked to everybody I could. If it's not enough, it's not enough. But I'm not going home without trying." },
    ] },
    { id: 'nw.c2', place: 'aside', when: { voice: ['schemer', 'calm', 'proud', 'competitive'] }, turns: [
      { by: 'a', say: "Let's be smart for a second." },
      { by: 'b', say: "Okay..." },
      { by: 'a', say: "Whoever is pushing my name tonight wants a strong player gone, and who's next after me? You." },
      { by: 'b', say: "That's a stretch." },
      { by: 'a', say: "Is it? Write {wrote} with me and we're both safe for another week." },
      { by: 'a', conf: "I'm not begging, because begging doesn't work, I'm just showing {b} who's next after me." },
    ] },
    { id: 'nw.c3', place: 'work', turns: [
      { beat: "{a} drops what {a} is doing and goes straight to {b} {here}." },
      { by: 'a', say: "I'm hearing my name. Is it real?" },
      { by: 'b', say: "I don't know. Maybe." },
      { by: 'a', say: "Maybe means yes. Help me, because if enough of us go {wrote}, it flips." },
      { by: 'b', say: "I'll see what I can do." },
      { by: 'a', conf: "I spent all day thinking tonight was easy, and it's not, I might actually be going home." },
    ] },
  ],
  'story.vote.target.safe': [
    C('nw.a1', null, "I'm not worried about tonight, it's {wrote}, everybody I've talked to says {wrote}.", { loud: "Tonight's an easy one, it's {wrote}, done!", warm: "I think it's going to be {wrote} tonight, and I'm sad about it, but I'm not worried." }),
    C('nw.a2', null, "{wrote} has been acting weird all day. Running around talking to people. That's how you know {wrote} is the one going.", { dry: "{wrote} has been running from person to person all afternoon, which is totally normal, relaxed behaviour." }),
    C('nw.a3', null, "My name hasn't come up once, not once, so it's {wrote} tonight.", { anxious: "My name hasn't come up once, and that's good, right? That's good. It's {wrote}." }),
    C('nw.a4', null, "I've got my people, and my people say {wrote}, so I'm writing {wrote} and going to bed.", { tough: "My people are solid, it's {wrote}, and nobody's coming for me." }),
    C('nw.a5', { why: 'grudge' }, "I've been waiting all week to write {wrote}'s name. Tonight I finally get to."),
    C('nw.a6', { why: 'threat' }, "If we don't get {wrote} out now, we'll never get {wrote} out, and I've told everybody, and they agree."),
    C('nw.a7', { why: 'weak' }, "We lost because of {wrote}, everybody knows it, so this is the easiest vote I'll ever make."),
    C('nw.a8', { why: 'strike' }, "{wrote} has been coming after me. Tonight I get there first."),
    C('nw.a9', null, "Everyone keeps telling me to relax, so I'm relaxing. It's {wrote}.", { goofy: "Everyone told me to relax, so I took a nap, because it's {wrote}, and napping is a strategy." }),
    C('nw.a10', { merged: true }, "Now that the teams are gone, everybody's scrambling, but not me, because I know where my votes are. It's {wrote}."),
    C('nw.a11', null, "I'm not even nervous, because everybody knows it's {wrote}, even {wrote} probably knows.", { anxious: "I'm a little nervous, only a little, because it's {wrote}. It has to be {wrote}." }),
    C('nw.a12', null, "I've counted, and I've got enough people, so {wrote} goes tonight.", { nerdy: "I've counted this vote four times. Every time, it comes out {wrote}." }),
    C('nw.a13', null, "Everyone was really nice to me today, which is a good sign, I think, so it's {wrote} tonight.", { dry: "Everyone was extremely friendly to me today. I'm choosing to take that as a good thing. It's {wrote}." }),
    C('nw.a14', null, "I told everyone I'm writing {wrote}, and nobody argued, so that's the whole plan.", { loud: "I told EVERYONE it's {wrote}, and nobody said a word back, so it's a done deal." }),
  ],
};
