// ══════════════════════════════════════════════════════════════════════
// td/story/lines/rivalry.js — rivalries, as whole scenes
// ══════════════════════════════════════════════════════════════════════
//
// Long versions of the engine's drama moments (td/script/lines/drama.js and
// drama2.js headers):
//   drama.bomb.<arrogant|hothead>  {a} says the thing nobody should say out loud, in
//                                  front of {b} (the most offended, who reacts).
//   drama.fight.<erupt|snap|tense|rare>  {a} and {b} fight; the band is {a}'s temper.
//   drama.dispute.<callout|press|precise|plain>  {a} and {b} disagree about the game.
//   drama.clash.any                {a} and {b} both try to run camp.
//   drama.sorry.<fight|meltdown|bomb|other>  {a} apologises to {b}.
//   drama.thaw.<talk|blowup|small> rivals {a} and {b} soften.
//   drama.nemesis.any              {a} and {b} hate each other; the camp knows.
//   drama.dig.any                  {a} takes a passive-aggressive shot at {b} in public.
// Story facts: prev (the rivalry's last aired step), chapter, lost/sank... after a
// team challenge (director.js recordSlots).

export default {
  'long.drama.bomb.hothead': [
    { id: 'rv.bh1', place: 'public', turns: [
      { beat: "Everyone is {here}. {a} has been in a mood since breakfast." },
      { by: 'b', say: "Can you pass the water?" },
      { by: 'a', say: "Get it yourself. You've got legs. Not that you used them today." },
      { by: 'b', say: "Excuse me?" },
      { by: 'a', say: "You heard me. Everyone heard me. I'm just the only one who says it." },
      { by: 'b', say: "Wow. Okay. What is your problem?" },
      { by: 'a', say: "My problem is I'm stuck on a team with people who'd lose a race to a log!" },
      { beat: "It goes very quiet." },
      { by: 'b', say: "You need to calm down." },
      { by: 'a', say: "Don't tell me to calm down!" },
      { by: 'b', say: "Fine. Then stay mad. On your own." },
      { beat: "{b} gets up and leaves. A couple of people follow {b.obj}." },
      { by: 'a', conf: "Did I go too far? Maybe. Was I wrong? No. Somebody had to say it." },
      { by: 'b', conf: "{a} just showed the whole camp exactly who {a} is. I'm not even mad. I'm grateful." },
    ] },
    { id: 'rv.bh2', place: 'work', when: { lost: true }, turns: [
      { beat: "After the challenge {here}. Nobody is talking about it, which is worse than talking about it." },
      { by: 'b', say: "Can we at least split up the chores before—" },
      { by: 'a', say: "Oh, NOW you want to work? Where was this an hour ago?" },
      { by: 'b', say: "Are you serious right now?" },
      { by: 'a', say: "I'm serious every day! I'm the only one who is!" },
      { by: 'c', say: "Hey. Hey. Not like this." },
      { by: 'a', say: "Then like what? We keep losing and everybody just shrugs!" },
      { by: 'b', say: "We keep losing, and you keep screaming. Funny how the screaming never helps." },
      { by: 'a', say: "Say that again." },
      { by: 'b', say: "I said it once. You heard it." },
      { by: 'c', conf: "If we go to a vote tonight, {a} just made it very easy for a lot of people." },
      { by: 'a', conf: "Everybody here wants to lose politely. I'd rather win rude." },
    ] },
    { id: 'rv.bh3', place: 'eat', when: { registerB: ['sweet', 'shy'] }, turns: [
      { beat: "Dinner {here}. {b} is telling a story nobody asked for, and everyone's being nice about it." },
      { by: 'b', say: "...and then the raccoon just took it right out of my hand. Like it was his." },
      { by: 'a', say: "Can you not? Seriously. Nobody cares." },
      { by: 'b', say: "Oh. Sorry. I was just—" },
      { by: 'a', say: "Talking. You're always just talking." },
      { by: 'c', say: "Dude. That's not cool." },
      { by: 'a', say: "What? I'm the only one honest enough to say it." },
      { beat: "{b} puts {b.posAdj} spoon down and doesn't pick it back up." },
      { by: 'b', say: "I'm gonna go." },
      { by: 'c', say: "You don't have to—" },
      { by: 'b', say: "No, it's fine. I'm gonna go." },
      { by: 'c', conf: "{b} has never said a mean word to anybody out here. {a} picked the one person who'd never fight back." },
      { by: 'b', conf: "I know I talk a lot. I just didn't know everybody hated it." },
    ] },
    { id: 'rv.bh4', place: 'fire', when: { registerB: 'fiery' }, turns: [
      { by: 'a', say: "Oh, look who finally decided to show up." },
      { by: 'b', say: "Oh, look who finally decided to open their mouth. Wait. You never close it." },
      { by: 'a', say: "Real mature." },
      { by: 'b', say: "You started it!" },
      { by: 'a', say: "And I'll finish it. You're the most useless person on this team and everyone knows it." },
      { by: 'b', say: "Everyone knows you're a walking temper tantrum!" },
      { beat: "People start edging away {here}." },
      { by: 'a', say: "At least I do something!" },
      { by: 'b', say: "Yelling isn't something!" },
      { by: 'a', conf: "{b} wants to go? Let's go. I'm not scared of {b}." },
      { by: 'b', conf: "{a} thinks {a.sub} can steamroll me. Clearly {a} has never met me." },
    ] },
    { id: 'rv.bh5', place: 'public', when: { prev: ['friction', 'blowup'] }, turns: [
      { beat: "{a} and {b} have managed a whole morning without speaking. It ends {here}." },
      { by: 'b', say: "You're standing in my way." },
      { by: 'a', say: "Walk around." },
      { by: 'b', say: "Or you could move." },
      { by: 'a', say: "Or you could stop acting like you own the place. Again." },
      { by: 'b', say: "This again? Seriously?" },
      { by: 'a', say: "Yeah. This again. Because you never actually said sorry." },
      { by: 'b', say: "Because I've got nothing to be sorry for!" },
      { by: 'a', say: "That's exactly what a person who should be sorry says!" },
      { by: 'c', conf: "These two have been at each other for days. Someone needs to go home just so the rest of us can eat in peace." },
    ] },
  ],
  'long.drama.bomb.arrogant': [
    { id: 'rv.ba1', place: 'public', turns: [
      { beat: "{a} is holding court {here}. Nobody asked for court." },
      { by: 'a', say: "Let's be honest. If I wasn't on this team, you'd all be gone already." },
      { by: 'b', say: "Wow." },
      { by: 'a', say: "What? It's a compliment. To me. But still." },
      { by: 'b', say: "You think you're carrying us?" },
      { by: 'a', say: "I don't think. I know. I've seen you all compete." },
      { by: 'b', say: "And we've seen you talk. Constantly." },
      { by: 'a', say: "Talking is free. Winning isn't. Which one of us has won something?" },
      { beat: "Nobody answers that." },
      { by: 'b', conf: "{a} is so sure everybody needs {a.obj}. I can't wait to show {a.obj} how wrong that is." },
      { by: 'a', conf: "Do they like me? No. Do they need me? Yes. I'll take needed over liked any day." },
    ] },
    { id: 'rv.ba2', place: 'eat', when: { carriedA: true }, turns: [
      { by: 'a', say: "You're welcome, by the way." },
      { by: 'b', say: "For what?" },
      { by: 'a', say: "For today. I had the best score on this whole team. Again. Somebody should say thank you." },
      { by: 'b', say: "We lost." },
      { by: 'a', say: "We lost because I'm one person. Imagine if I had help." },
      { by: 'c', say: "Okay, that's a little much." },
      { by: 'a', say: "Is it, though? Name one thing you did today that helped." },
      { by: 'b', say: "I didn't make everyone hate me. That's something." },
      { by: 'a', conf: "They can hate me as much as they like. They still can't win without me, and they know it." },
      { by: 'b', conf: "Being good at challenges doesn't stop people writing your name. {a} is about to learn that." },
    ] },
    { id: 'rv.ba3', place: 'aside', when: { register: 'schemer' }, turns: [
      { by: 'a', say: "Can I give you some advice? As a friend?" },
      { by: 'b', say: "We're not friends." },
      { by: 'a', say: "As a person who's smarter than you, then." },
      { by: 'b', say: "Oh, this'll be good." },
      { by: 'a', say: "Stop trying so hard. Everybody can see it. It's embarrassing." },
      { by: 'b', say: "Trying so hard at what?" },
      { by: 'a', say: "At being somebody people want to keep around. You're not. You're somebody people feel sorry for." },
      { beat: "{b} just stares at {a}." },
      { by: 'a', say: "See? That face. That's what I'm talking about." },
      { by: 'a', conf: "If {b} is busy feeling small, {b} isn't busy making plans. That's not mean. That's efficient." },
      { by: 'b', conf: "{a} wants me to think I'm nothing. That's how I know {a} is scared I'm something." },
    ] },
    { id: 'rv.ba4', place: 'public', when: { merged: true }, turns: [
      { by: 'a', say: "I just want everyone to know, I'm not worried. About any of you." },
      { by: 'b', say: "Nobody asked." },
      { by: 'a', say: "Well, now you know. You can relax." },
      { by: 'b', say: "That's not relaxing. That's a threat with a smile on it." },
      { by: 'a', say: "It's confidence. You should try it sometime." },
      { by: 'b', say: "I'm confident about one thing. You're going home before me." },
      { by: 'a', say: "Cute." },
      { by: 'b', conf: "The merge is when you're supposed to make friends. {a} decided to make a list of enemies instead. I'm happy to be at the top of it." },
    ] },
  ],

  'long.drama.fight.any': [
    { id: 'rv.f1', place: 'public', turns: [
      { beat: "It starts over nothing {here}, and gets bigger very fast." },
      { by: 'a', say: "You do this every time!" },
      { by: 'b', say: "Do what?!" },
      { by: 'a', say: "Act like everything's fine and then talk about me the second I walk away!" },
      { by: 'b', say: "Maybe if you didn't give people so much to talk about!" },
      { by: 'a', say: "Oh, that's real nice. Real mature." },
      { by: 'b', say: "You want mature? Grow up and stop yelling at people!" },
      { by: 'c', say: "Okay! Okay. Both of you. Breathe." },
      { by: 'a', say: "I'm breathing! I'm breathing really hard!" },
      { beat: "{b} storms off. {a} kicks a rock and immediately regrets it." },
      { by: 'c', conf: "Every single day. Every day, these two. I'm going to start charging admission." },
      { by: 'a', conf: "I wasn't going to start a fight. Then {b} opened {b.posAdj} mouth." },
    ] },
  ],
  'long.drama.fight.erupt': [
    { id: 'rv.fe1', place: 'public', turns: [
      { by: 'b', say: "Can you not leave your stuff everywhere? It's been in the way all day." },
      { by: 'a', say: "Are you KIDDING me right now?!" },
      { by: 'b', say: "It's a simple question!" },
      { by: 'a', say: "It's a stupid question, from a stupid person, and I'm SICK of it!" },
      { by: 'b', say: "Whoa. Whoa. Where is this coming from?" },
      { by: 'a', say: "From days of you acting like you're better than me! That's where!" },
      { beat: "{a} throws {a.posAdj} towel on the ground. Everyone {here} stops what they're doing." },
      { by: 'b', say: "Okay. You need to walk away." },
      { by: 'a', say: "YOU walk away!" },
      { by: 'b', say: "Fine!" },
      { by: 'a', conf: "I know, I know. I lost it. But {b} has been pushing me for days, and today I pushed back." },
      { by: 'b', conf: "I asked {a} to move a bag. That's all I did. That's all it takes." },
    ] },
  ],
  'long.drama.fight.tense': [
    { id: 'rv.ft1', place: 'aside', turns: [
      { by: 'a', say: "I'm going to say this once, calmly. Stay out of my business." },
      { by: 'b', say: "I don't know what you're talking about." },
      { by: 'a', say: "You do. You've been asking people about me. Who I talk to. What I said." },
      { by: 'b', say: "People talk. I listen. That's not a crime." },
      { by: 'a', say: "It is when you're the one starting it." },
      { by: 'b', say: "Are you threatening me?" },
      { by: 'a', say: "I'm telling you. There's a difference. You'll know when I'm threatening you." },
      { beat: "{a} walks away slowly. {b} lets out a breath." },
      { by: 'b', conf: "{a} didn't raise {a.posAdj} voice once. That was so much scarier than yelling." },
      { by: 'a', conf: "I don't yell. Yelling's for people who don't have a plan." },
    ] },
  ],
  'long.drama.fight.rare': [
    { id: 'rv.fr1', place: 'public', turns: [
      { beat: "Nobody has ever seen {a} lose it. That changes {here}." },
      { by: 'b', say: "Come on, it was a joke." },
      { by: 'a', say: "It's always a joke with you! It's always a joke, and I'm always the punchline!" },
      { by: 'b', say: "...Whoa." },
      { by: 'a', say: "I've been nice. I've been so nice. And every time I'm nice, you take a little bit more." },
      { by: 'b', say: "I didn't know you felt like that." },
      { by: 'a', say: "Because you never asked!" },
      { beat: "{a} walks off. Nobody follows. Nobody knows what to do." },
      { by: 'b', conf: "I've never seen {a} like that. Ever. I think I might've really messed up." },
      { by: 'a', conf: "I don't do that. I'm not that person. But I'm also not going to be everyone's doormat for another week." },
    ] },
  ],
  'long.drama.fight.snap': [
    { id: 'rv.fs1', place: 'work', turns: [
      { beat: "{a} and {b} are supposed to be doing chores together {here}. It is not going well." },
      { by: 'b', say: "You're doing it wrong." },
      { by: 'a', say: "There's no wrong way to do this." },
      { by: 'b', say: "There's literally a wrong way, and you're doing it." },
      { by: 'a', say: "Then do it yourself!" },
      { by: 'b', say: "I would, if you'd get out of the way!" },
      { by: 'a', say: "Gladly!" },
      { beat: "{a} drops everything and walks off. {b} looks at the mess." },
      { by: 'b', say: "...Great. Perfect." },
      { by: 'a', conf: "I lasted ten minutes with {b}. Ten. That's a personal record." },
    ] },
  ],

  'long.drama.dispute.any': [
    { id: 'rv.d1', place: 'aside', turns: [
      { by: 'a', say: "I'm not voting with you on this one." },
      { by: 'b', say: "Since when?" },
      { by: 'a', say: "Since you stopped telling me why. You just give me a name and expect me to write it." },
      { by: 'b', say: "That's how it works." },
      { by: 'a', say: "That's how it works for you. I want reasons." },
      { by: 'b', say: "The reason is it keeps us both safe. Is that good enough?" },
      { by: 'a', say: "It would be, if I believed it." },
      { by: 'b', say: "Wow. Okay." },
      { by: 'b', conf: "{a} wants to argue about every single vote. That's fine. People who argue about every vote don't last." },
      { by: 'a', conf: "I'm not a vote you get to spend. I'm a person who decides." },
    ] },
    { id: 'rv.d2', place: 'secret', when: { lost: true, sank: true }, turns: [
      { beat: "Away from the others, {here}. The vote is tonight." },
      { by: 'a', say: "It has to be {sank}. {sank} lost us that challenge." },
      { by: 'b', say: "{sank} had one bad day. You want to vote out the weakest person or the most dangerous one?" },
      { by: 'a', say: "Right now? The one who'll make us lose again." },
      { by: 'b', say: "And next week, when the strong one we kept turns on us?" },
      { by: 'a', say: "Then that's next week's problem." },
      { by: 'b', say: "That's how people go home in week nine. They keep the dangerous ones because the challenges are easier." },
      { by: 'a', say: "And that's how teams lose every challenge until there's nobody left." },
      { beat: "Neither of them backs down." },
      { by: 'a', conf: "{b} is thinking about the merge. I'm thinking about tonight. You can't get to the merge if you don't survive tonight." },
      { by: 'b', conf: "Everybody votes out the weak link. Nobody ever thinks about what happens when the weak links are all gone." },
    ] },
  ],

  'long.drama.clash.any': [
    { id: 'rv.c1', place: 'work', when: { venue: ['hosted-camp', 'survival-island', 'carnival'] }, turns: [
      { beat: "{a} has a plan for the day {here}. So does {b}. They're not the same plan." },
      { by: 'a', say: "Okay, everyone. Wood first, then water, then we fix the roof." },
      { by: 'b', say: "Actually, we should do the roof first. It's going to rain." },
      { by: 'a', say: "It's not going to rain." },
      { by: 'b', say: "Look at the sky!" },
      { by: 'a', say: "I'm looking at the sky. The sky is fine." },
      { by: 'c', say: "Should we... vote on it?" },
      { by: 'a', say: "No." },
      { by: 'b', say: "No." },
      { by: 'c', say: "Cool. Cool cool cool." },
      { by: 'c', conf: "Two people who both think they're in charge, and one roof. This is going to end badly. Probably for the roof." },
      { by: 'b', conf: "Somebody has to make the decisions out here. It's just a coincidence that it's me." },
    ] },
    { id: 'rv.c2', place: 'public', when: { lost: true }, turns: [
      { by: 'a', say: "Okay. Next challenge, I'm calling it. We do it my way." },
      { by: 'b', say: "Your way? Your way is how we lost today." },
      { by: 'a', say: "We lost today because nobody listened to me!" },
      { by: 'b', say: "We lost today because you were shouting so much nobody could hear anything!" },
      { by: 'a', say: "So who's the captain, then? You?" },
      { by: 'b', say: "Maybe! At least people would listen to me without covering their ears!" },
      { by: 'c', say: "We don't need a captain. We need to stop losing." },
      { by: 'a', say: "Same thing!" },
      { by: 'b', say: "It really isn't." },
      { by: 'c', conf: "Whoever wins this argument, the rest of us lose. That's how it always goes." },
    ] },
  ],

  'long.drama.sorry.any': [
    { id: 'rv.s1', place: 'aside', turns: [
      { beat: "{a} finds {b} {here}. {a} has clearly been rehearsing." },
      { by: 'a', say: "Hey. Can I say something? You don't have to say anything back." },
      { by: 'b', say: "...Okay." },
      { by: 'a', say: "I was out of line. Before. I said stuff I didn't mean, and I said it loud." },
      { by: 'b', say: "You meant some of it." },
      { by: 'a', say: "Maybe some of it. But not like that. Not in front of everyone." },
      { by: 'b', say: "Why now?" },
      { by: 'a', say: "Because I keep thinking about it. And I'd rather you hate me for something real." },
      { by: 'b', say: "...I don't hate you. I just don't trust you." },
      { by: 'a', say: "That's fair. I'll take that." },
      { by: 'b', conf: "Was that real? I think it was real. I'm still not going to forget it." },
      { by: 'a', conf: "Apologising is the worst. It's still better than going home with somebody hating me for no reason." },
    ] },
    { id: 'rv.s2', place: 'water', when: { register: 'fiery' }, turns: [
      { by: 'a', say: "Okay. I'm bad at this, so just let me get through it." },
      { by: 'b', say: "Get through what?" },
      { by: 'a', say: "I'm sorry. Okay? I'm sorry. I lose my temper and then I can't find it again." },
      { by: 'b', say: "That's... the most honest thing you've ever said to me." },
      { by: 'a', say: "Don't make it weird." },
      { by: 'b', say: "I'm not making it weird. Thank you." },
      { by: 'a', say: "Okay. Good. We're good?" },
      { by: 'b', say: "We're better." },
      { by: 'a', conf: "That was harder than any challenge. I'd rather do today's challenge again. Twice." },
    ] },
    { id: 'rv.s3', place: 'aside', when: { register: ['schemer', 'cool'] }, turns: [
      { by: 'a', say: "I owe you an apology." },
      { by: 'b', say: "Do you mean it, or do you need my vote?" },
      { by: 'a', say: "Can't it be both?" },
      { by: 'b', say: "At least you're honest." },
      { by: 'a', say: "I'm always honest. Just not always nice. I'm trying to work on the nice part." },
      { by: 'b', say: "It needs a lot of work." },
      { by: 'a', say: "Then let me work on it. Starting with you." },
      { by: 'b', say: "...Fine. Apology accepted. Provisionally." },
      { by: 'a', conf: "I don't do apologies for fun. I do them because a grudge is a vote you can't count on." },
      { by: 'b', conf: "I accepted. I'm not stupid. I just know which battles I can afford right now." },
    ] },
  ],
  'long.drama.thaw.any': [
    { id: 'rv.t1', place: 'aside', turns: [
      { beat: "{a} and {b} end up {here} on their own. Neither of them leaves." },
      { by: 'b', say: "This is weird." },
      { by: 'a', say: "What is?" },
      { by: 'b', say: "Us. Sitting here. Not yelling." },
      { by: 'a', say: "Give it a minute." },
      { by: 'b', say: "Ha." },
      { by: 'a', say: "Can I be honest? I don't actually hate you. I just hate that you're good at this." },
      { by: 'b', say: "...Same, honestly." },
      { by: 'a', say: "So what, we just stop?" },
      { by: 'b', say: "We stop for today. Let's not get crazy." },
      { by: 'a', conf: "I don't trust {b}. But I understand {b} a little better now. That's going to be either really useful or really dangerous." },
    ] },
    { id: 'rv.t2', place: 'fire', when: { lastBoot: true }, turns: [
      { by: 'a', say: "Weird how {lastBoot} going home made us the two people left on opposite sides." },
      { by: 'b', say: "I noticed that too." },
      { by: 'a', say: "And we're both still here. So maybe we stop wasting energy on each other." },
      { by: 'b', say: "Is that a peace treaty?" },
      { by: 'a', say: "It's a ceasefire. Peace treaties are for people who like each other." },
      { by: 'b', say: "Fine. Ceasefire." },
      { by: 'b', conf: "{a} and I are never going to be friends. But we might be two people who stop each other from going home. That's almost better." },
    ] },
  ],
  'long.drama.nemesis.any': [
    { id: 'rv.n1', place: 'public', turns: [
      { beat: "{a} walks in. {b} walks out. Everyone {here} watches it happen." },
      { by: 'c', say: "Do you two ever get tired?" },
      { by: 'a', say: "Of what?" },
      { by: 'c', say: "Hating each other. It looks exhausting." },
      { by: 'a', say: "It's not hate. It's a hobby." },
      { by: 'c', say: "That's so much worse." },
      { by: 'a', say: "{b} started it. I'm just very committed to finishing it." },
      { by: 'c', conf: "Everybody knows {a} and {b} can't stand each other. The question is which one of them takes the other one down first." },
      { by: 'b', conf: "One of us is going home because of the other one. I've accepted that. I've just decided it's going to be {a}." },
    ] },
  ],
  'long.drama.dig.any': [
    { id: 'rv.g1', place: 'eat', turns: [
      { beat: "Mealtime {here}. Everyone's tired." },
      { by: 'a', say: "Oh, {b}, you're eating? Good for you. I thought you'd be too busy." },
      { by: 'b', say: "Busy with what?" },
      { by: 'a', say: "Oh, you know. Whatever it is you do all day. Nobody's really sure." },
      { by: 'c', say: "Wow." },
      { by: 'b', say: "Is there something you want to say to me, {a}?" },
      { by: 'a', say: "I just said it. Weren't you listening? That's kind of my point." },
      { beat: "{b} smiles. It's not a nice smile." },
      { by: 'b', say: "Okay. I'll remember that." },
      { by: 'a', conf: "Was that mean? Maybe. Was it funny? Definitely." },
      { by: 'b', conf: "{a} wants to do this in front of everyone. Fine. Everyone's going to be there when I get my turn." },
    ] },
  ],
};
