// ══════════════════════════════════════════════════════════════════════
// td/story/lines/showmance.js — showmances, as whole scenes
// ══════════════════════════════════════════════════════════════════════
//
// Long versions of the engine's romance moments (td/script/lines/romance.js and
// romance2.js headers). Every pair passed romanticCompat before the engine fired.
//   romance.flirt.any          {a} and {b} flirt; not a couple yet. No kiss.
//   romance.spark.any          {a} and {b} are officially a thing now.
//   romance.moment.<couple|crush>  'couple': established (kisses allowed);
//                              'crush': a crush getting obvious. No kiss.
//   romance.honeymoon.any      the glow of a new couple.
//   romance.night.kiss         after-dark game; the bottle lands on {a} and {b}; they kiss.
//   romance.jealous.any        {a} used to be {b}'s person; now it's {c}.
//   romance.fade.<amicable|soured>  the showmance quietly ends.
//   romance.noticed.any        {a} watches the couple {b} and {c} and starts counting votes.
//   romance.target.any         {a} decides the couple {b} and {c} has to be split.
//   romance.rideordie.any      {a} and {b} are going to the end together.
//   romance.tri.tension        {a} watches {b} (the one {a} is with) drift toward {c}.
//   romance.tri.confront       {a} confronts {b} about {c}.

export default {
  'long.romance.flirt.any': [
    { id: 'sm.f1', place: 'water', turns: [
      { beat: "{a} and {b} are {here}, supposedly doing chores. Mostly they're talking." },
      { by: 'b', say: "You're doing that thing again." },
      { by: 'a', say: "What thing?" },
      { by: 'b', say: "Where you pretend you're not looking at me." },
      { by: 'a', say: "I'm not pretending. I'm just bad at it." },
      { by: 'b', say: "You really are." },
      { by: 'a', say: "Is that a problem?" },
      { by: 'b', say: "...No. Not really." },
      { beat: "Neither of them says anything for a second. {b} looks away first." },
      { by: 'b', say: "We should probably actually do the chores." },
      { by: 'a', say: "Probably." },
      { beat: "Neither of them moves." },
      { by: 'b', conf: "I'm not here for romance. I said that on day one. Day one me was very confident." },
      { by: 'a', conf: "I've got a game to play. I know that. I just also have eyes." },
    ] },
    { id: 'sm.f2', place: 'fire', when: { register: ['sweet', 'shy'] }, turns: [
      { beat: "{a} sits down next to {b} {here}, a little closer than there's any need to." },
      { by: 'a', say: "Is this seat taken?" },
      { by: 'b', say: "It's a log. There's like ten feet of it." },
      { by: 'a', say: "I know. I picked this part." },
      { by: 'b', say: "Oh." },
      { by: 'a', say: "Is that weird? That's weird. I can move." },
      { by: 'b', say: "No! No. Stay. It's a good part of the log." },
      { by: 'a', say: "It is a good part of the log." },
      { beat: "They both laugh, then both stop at the same time, then both laugh again." },
      { by: 'a', conf: "I have never been smooth in my life. I don't know why I thought I'd start out here." },
      { by: 'b', conf: "{a} is so awkward. It's honestly kind of the best thing about {a.obj}." },
    ] },
    { id: 'sm.f3', place: 'aside', when: { register: ['schemer', 'cool'] }, turns: [
      { by: 'a', say: "You know you're the only interesting person here, right?" },
      { by: 'b', say: "Is that a line?" },
      { by: 'a', say: "It's an observation. Lines are for people who need them." },
      { by: 'b', say: "And you don't need them." },
      { by: 'a', say: "Do I look like I need them?" },
      { by: 'b', say: "You look like you think you don't." },
      { by: 'a', say: "Ha. See? Interesting." },
      { by: 'b', say: "Careful. People will start talking." },
      { by: 'a', say: "Let them. They talk anyway." },
      { by: 'a', conf: "Is {b} useful? Yes. Is {b} also really, really good-looking? Also yes. Nobody said I can't have both." },
      { by: 'b', conf: "{a} is playing a game with me. I know that. I'm just not sure I mind." },
    ] },
    { id: 'sm.f4', place: 'public', when: { register: 'fiery' }, turns: [
      { by: 'b', say: "Do you ever say anything nicely?" },
      { by: 'a', say: "Nope." },
      { by: 'b', say: "Not even to me?" },
      { by: 'a', say: "Especially not to you. You'd get a big head." },
      { by: 'b', say: "So you think I'm worth being nice to." },
      { by: 'a', say: "I didn't say that." },
      { by: 'b', say: "You kind of did." },
      { by: 'a', say: "...Shut up." },
      { by: 'b', say: "You're blushing." },
      { by: 'a', say: "It's HOT out here!" },
      { by: 'b', conf: "{a} yells at everyone. {a} yells at me a little differently. I've noticed." },
    ] },
    { id: 'sm.f5', place: 'work', when: { merged: false }, turns: [
      { beat: "{a} keeps finding reasons to work next to {b} {here}." },
      { by: 'c', say: "You know you could just say you like {b}." },
      { by: 'a', say: "What? I don't— I'm helping." },
      { by: 'c', say: "You've carried the same thing back and forth three times." },
      { by: 'a', say: "It's heavy!" },
      { by: 'c', say: "It's a bucket. It's empty." },
      { by: 'b', say: "What are you two whispering about?" },
      { by: 'a', say: "Nothing! Buckets!" },
      { by: 'c', conf: "Everybody on this team can see it except the two people it's happening to." },
    ] },
  ],

  'long.romance.spark.any': [
    { id: 'sm.s1', place: 'secret', turns: [
      { beat: "{a} and {b} have slipped off to {place}. Nobody followed. They checked." },
      { by: 'a', say: "So. What are we doing?" },
      { by: 'b', say: "Sitting. Talking." },
      { by: 'a', say: "You know what I mean." },
      { by: 'b', say: "...Yeah. I know what you mean." },
      { by: 'a', say: "Because I like you. Like, actually like you. Not game like you." },
      { by: 'b', say: "I like you too. That's the problem." },
      { by: 'a', say: "Why's that a problem?" },
      { by: 'b', say: "Because the second everybody knows, they'll split us up. Couples don't last out here." },
      { by: 'a', say: "So we don't tell anybody." },
      { by: 'b', say: "We don't tell anybody." },
      { beat: "{b} kisses {a}. It's quick, and then it isn't." },
      { by: 'a', conf: "I came out here to win a million dollars. Nobody told me I was going to like somebody this much. That wasn't in the brochure." },
      { by: 'b', conf: "Is this a terrible idea? Yes. Am I doing it anyway? Obviously." },
    ] },
    { id: 'sm.s2', place: 'water', turns: [
      { by: 'b', say: "Can I ask you something weird?" },
      { by: 'a', say: "Always." },
      { by: 'b', say: "Are we a thing? Like, a thing thing?" },
      { by: 'a', say: "I thought we already were." },
      { by: 'b', say: "You did?" },
      { by: 'a', say: "Since about three days ago. I was waiting for you to catch up." },
      { by: 'b', say: "Wow. Okay. Rude. Romantic, but rude." },
      { by: 'a', say: "So that's a yes?" },
      { by: 'b', say: "That's a yes." },
      { beat: "They kiss {here}. Somewhere behind them, somebody whistles." },
      { by: 'b', say: "Oh my god." },
      { by: 'a', say: "Well. That's not a secret anymore." },
      { by: 'b', conf: "Everyone knows now. Great. We're officially the couple everyone wants to split up." },
    ] },
    { id: 'sm.s3', place: 'sleep', when: { merged: true }, turns: [
      { beat: "Late, in the {quarters}. Everyone else is asleep. {a} and {b} are whispering." },
      { by: 'a', say: "Can I tell you something? I think about you way too much." },
      { by: 'b', say: "That's a weird thing to tell somebody at the merge." },
      { by: 'a', say: "Why?" },
      { by: 'b', say: "Because now you're my biggest weakness, and I'm yours." },
      { by: 'a', say: "Is that a bad thing?" },
      { by: 'b', say: "It's the worst thing. Strategically." },
      { by: 'a', say: "And not strategically?" },
      { beat: "{b} doesn't answer. {b} just leans in." },
      { by: 'b', conf: "Everybody's going to come for us now. I knew that before I kissed {a}. I did it anyway." },
    ] },
  ],

  'long.romance.moment.couple': [
    { id: 'sm.mc1', place: 'water', turns: [
      { beat: "{a} and {b} are {here}, {b}'s head on {a}'s shoulder." },
      { by: 'b', say: "I could stay here forever." },
      { by: 'a', say: "Forever's a long time to go without a shower." },
      { by: 'b', say: "You're ruining it." },
      { by: 'a', say: "I'm making it memorable." },
      { by: 'b', say: "Do you think we'd still like each other on the outside? Without all this?" },
      { by: 'a', say: "Without the bugs, the food and the voting? I think we'd like each other a lot more." },
      { by: 'b', say: "Good answer." },
      { beat: "{b} kisses {a}. They don't hear {c} coming until {c} clears {c.posAdj} throat." },
      { by: 'c', say: "Sorry. Some of us have to use this spot too." },
      { by: 'c', conf: "They're cute. They're also the biggest pair on this island, and they're not even trying to hide it." },
    ] },
    { id: 'sm.mc2', place: 'eat', turns: [
      { beat: "Mealtime {here}. {a} saves {b} the better portion without saying anything about it." },
      { by: 'b', say: "You did it again." },
      { by: 'a', say: "Did what?" },
      { by: 'b', say: "Gave me yours." },
      { by: 'a', say: "Mine was bigger. You were hungrier. Basic maths." },
      { by: 'b', say: "That's not maths, that's you being nice." },
      { by: 'a', say: "Don't tell anyone. I've got a reputation." },
      { by: 'b', say: "Your reputation is being nice to me." },
      { by: 'a', say: "Exactly. So don't ruin it." },
      { by: 'b', conf: "Everybody out here is in it for themselves. Then there's {a}, giving me half {a.posAdj} food. I don't know how to compete with that." },
    ] },
  ],
  'long.romance.moment.crush': [
    { id: 'sm.mr1', place: 'aside', turns: [
      { beat: "{b} is telling a story {here}. {a} is listening like it's the best story ever told." },
      { by: 'b', say: "...and that's how I ended up stuck on the roof." },
      { by: 'a', say: "That's amazing." },
      { by: 'b', say: "It's really not. It's kind of stupid." },
      { by: 'a', say: "It's amazing to me." },
      { by: 'b', say: "You're weird, you know that?" },
      { by: 'a', say: "Good weird?" },
      { by: 'b', say: "...Yeah. Good weird." },
      { by: 'a', conf: "I don't think {b} has any idea. Which is good. I'd die. I would actually die." },
      { by: 'b', conf: "{a} has a crush on me. It's very obvious. I'm still deciding what I think about it." },
    ] },
  ],
  'long.romance.honeymoon.any': [
    { id: 'sm.h1', place: 'public', turns: [
      { beat: "{a} and {b} are being a couple {here}, in front of everyone." },
      { by: 'c', say: "Can you two not? Some of us are trying to eat." },
      { by: 'a', say: "We're not doing anything!" },
      { by: 'c', say: "You're doing it with your eyes." },
      { by: 'b', say: "Jealous?" },
      { by: 'c', say: "Of what? Being the first couple on everybody's hit list?" },
      { beat: "That lands. {a} and {b} look at each other." },
      { by: 'b', say: "Nobody's coming for us." },
      { by: 'c', say: "Sure. Keep telling yourselves that." },
      { by: 'c', conf: "I'm not even trying to be mean. I'm just the only one saying out loud what everyone's thinking." },
      { by: 'a', conf: "{c} has a point. I hate it when {c} has a point." },
    ] },
    { id: 'sm.h2', place: 'aside', turns: [
      { by: 'a', say: "Can I tell you what I like most about you?" },
      { by: 'b', say: "Is this going to be embarrassing?" },
      { by: 'a', say: "Probably." },
      { by: 'b', say: "Go on, then." },
      { by: 'a', say: "Everyone out here's always working an angle. You're the only person I don't have to figure out." },
      { by: 'b', say: "That's either really sweet or you think I'm simple." },
      { by: 'a', say: "Sweet! Definitely sweet." },
      { by: 'b', say: "Good answer." },
      { by: 'b', conf: "Do I think about the game? Yes. Do I think about {a} more? Embarrassingly, yes." },
    ] },
  ],
  'long.romance.night.kiss': [
    { id: 'sm.n1', place: 'fire', turns: [
      { beat: "Late. Somebody's found a bottle, and half the camp is sitting in a circle {here}." },
      { by: 'c', say: "Okay, okay. Spin it." },
      { beat: "{a} spins. The bottle wobbles, slows, and stops on {b}." },
      { by: 'c', say: "Ohhhh." },
      { by: 'b', say: "You don't have to—" },
      { by: 'a', say: "Rules are rules." },
      { beat: "{a} leans across the circle. It's meant to be a quick one. It is not a quick one." },
      { by: 'c', say: "Okay! Okay, that's enough, you're making the rest of us uncomfortable!" },
      { by: 'b', say: "...Who's next?" },
      { by: 'b', conf: "It was a game. It was a dumb game. I can't stop thinking about it." },
      { by: 'a', conf: "I didn't plan that. I'm really, really glad it happened." },
    ] },
  ],
  'long.romance.jealous.any': [
    { id: 'sm.j1', place: 'aside', turns: [
      { by: 'a', say: "So you and {c} are a thing now." },
      { by: 'b', say: "We're not a thing. We just talk." },
      { by: 'a', say: "You used to just talk to me." },
      { by: 'b', say: "I still talk to you." },
      { by: 'a', say: "Not like before. Before, you'd come find me first thing. Now you go find {c}." },
      { by: 'b', say: "Are you jealous?" },
      { by: 'a', say: "I'm not jealous. I'm observant." },
      { by: 'b', say: "Those sound really similar right now." },
      { by: 'a', conf: "It's fine. It's totally fine. I'm going to go stand somewhere far away from {c} and be totally fine." },
      { by: 'b', conf: "I didn't know {a} felt like that. I really didn't. And now I don't know what to do with it." },
    ] },
    { id: 'sm.j2', place: 'public', when: { register: 'fiery' }, turns: [
      { beat: "{b} and {c} are laughing about something {here}. {a} comes straight over." },
      { by: 'a', say: "Must be a great joke." },
      { by: 'c', say: "It was, actually." },
      { by: 'a', say: "Tell it, then. I could use a laugh." },
      { by: 'b', say: "{a}, come on." },
      { by: 'a', say: "What? I'm just being friendly. Like {c}. Super friendly." },
      { by: 'c', say: "Is there a problem?" },
      { by: 'a', say: "Nope. No problem. Have fun." },
      { by: 'c', conf: "{a} is jealous of me. Of me. I'm not even trying. That's honestly kind of flattering." },
    ] },
  ],
  'long.romance.fade.any': [
    { id: 'sm.fd1', place: 'aside', turns: [
      { by: 'b', say: "We haven't really talked in a few days." },
      { by: 'a', say: "Yeah. I noticed." },
      { by: 'b', say: "Is it something I did?" },
      { by: 'a', say: "No. It's not you. It's... out here. Everybody's watching us, and every vote, I'm thinking about you instead of the game." },
      { by: 'b', say: "And that's bad?" },
      { by: 'a', say: "It's bad for the game." },
      { by: 'b', say: "So that's it? The game wins?" },
      { by: 'a', say: "I don't know. Maybe for now." },
      { beat: "{b} nods, and doesn't say anything else." },
      { by: 'b', conf: "Nobody broke up with anybody. We just stopped. I think that's worse." },
      { by: 'a', conf: "I still like {b}. I just like being here more. I hope that doesn't make me a monster." },
    ] },
  ],
  'long.romance.fade.soured': [
    { id: 'sm.fd2', place: 'public', turns: [
      { by: 'b', say: "Oh, so now you're not even sitting with me?" },
      { by: 'a', say: "I can sit where I want." },
      { by: 'b', say: "You've been doing this for days. Just say it." },
      { by: 'a', say: "Say what?" },
      { by: 'b', say: "That we're done!" },
      { by: 'a', say: "...Fine. We're done." },
      { by: 'b', say: "Wow. You didn't even think about it." },
      { by: 'a', say: "I've thought about it for days. You just weren't listening." },
      { by: 'c', conf: "Everybody watched that. Everybody. That's the end of the island's favourite couple, live, at breakfast." },
      { by: 'b', conf: "Fine. Good. One less thing to worry about. Now I can actually play this game." },
    ] },
  ],
  'long.romance.noticed.any': [
    { id: 'sm.no1', place: 'aside', turns: [
      { beat: "{a} watches {b} and {c} share a look across camp." },
      { by: 'a', conf: "Those two think nobody's noticed. Everybody's noticed. A couple out here isn't two votes. It's one vote that moves twice." },
      { by: 'a', conf: "And if one of them goes, the other one's going to be heartbroken, and heartbroken people vote with their feelings. I can work with that." },
    ] },
  ],
  'long.romance.target.any': [
    { id: 'sm.t1', place: 'aside', turns: [
      { beat: "{a} is {here}, watching {b} and {c}." },
      { by: 'a', conf: "{b} and {c} are a pair. They vote together, they sleep next to each other, and they'll take each other to the end." },
      { by: 'a', conf: "So one of them has to go. Soon. Before the rest of the camp starts thinking about it. Then I get to look like the one who saw it first." },
    ] },
  ],
  'long.romance.rideordie.any': [
    { id: 'sm.r1', place: 'secret', turns: [
      { by: 'a', say: "If they come for you, they come for me. You know that, right?" },
      { by: 'b', say: "That's not how this game works." },
      { by: 'a', say: "It's how we work." },
      { by: 'b', say: "And if it comes down to us? Final two, and only one of us gets the money?" },
      { by: 'a', say: "Then we get there first and fight about it later." },
      { by: 'b', say: "That's the least romantic thing anyone's ever said to me." },
      { by: 'a', say: "And yet you're smiling." },
      { by: 'b', say: "...And yet I'm smiling." },
      { by: 'b', conf: "Everyone says couples don't make it to the end. Watch us." },
    ] },
  ],
  'long.romance.tri.tension': [
    { id: 'sm.tt1', place: 'aside', turns: [
      { beat: "{a} watches {b} help {c} with something {here}, for the third time today." },
      { by: 'a', say: "You two are getting close." },
      { by: 'b', say: "We're friends." },
      { by: 'a', say: "We were friends once. Look how that went." },
      { by: 'b', say: "That's not fair." },
      { by: 'a', say: "Isn't it? I'm just saying what I see." },
      { by: 'b', say: "You're seeing things." },
      { by: 'a', conf: "I'm not crazy. I'm not. {b} looks at {c} the way {b} used to look at me." },
    ] },
  ],
  'long.romance.tri.confront': [
    { id: 'sm.tc1', place: 'secret', turns: [
      { by: 'a', say: "I need you to be honest with me. Is something going on with {c}?" },
      { by: 'b', say: "What? No!" },
      { by: 'a', say: "Then why do you go quiet every time {c} walks in?" },
      { by: 'b', say: "I don't go quiet!" },
      { by: 'a', say: "You're quiet right now." },
      { by: 'b', say: "Because you're interrogating me!" },
      { by: 'a', say: "Because you're not answering!" },
      { beat: "{b} looks away. That's an answer too." },
      { by: 'a', say: "Wow. Okay." },
      { by: 'b', say: "It's not what you think." },
      { by: 'a', say: "Then tell me what it is." },
      { by: 'b', conf: "I don't know what it is. That's the whole problem." },
    ] },
  ],
};
