# tools/bb-house/port-anchors.py — Blender's measurements of the rooms, for the viewer.
#
# house.py anchors() writes assets/bb/house/default/<room>.json: where each seat, the nominations
# screen, the key box and the memory-wall panels land on screen. Every season's house is the
# same models redressed, so one set of anchors serves all of them. Output: js/vp-bb-ep/anchors.js.
#   python tools/bb-house/port-anchors.py
import json, os
ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
d = os.path.join(ROOT, 'assets', 'bb', 'house', 'default')
din = json.load(open(os.path.join(d, 'dining.json')))
liv = json.load(open(os.path.join(d, 'living.json')))
stu = json.load(open(os.path.join(d, 'studio.json')))
fin = json.load(open(os.path.join(d, 'finale.json')))
anch = {
    'dining': {k: din[k] for k in ('seats', 'head', 'box', 'screen')},
    'ceremony': {'seats': liv['seats'], 'panels': liv['panels']},
    'studio': {'seats': stu['seats']},
    'finale': {'seats': fin['seats'], 'slot': fin['slot']},
}
js = ('// GENERATED by tools/bb-house/port-anchors.py from Blender\'s anchors(). Do not edit by hand.\n'
      '// [x % from left, y % from bottom, depth] per seat; rectangles in % of the frame.\n'
      f'export const ANCH = {json.dumps(anch, separators=(",", ":"))};\n')
open(os.path.join(ROOT, 'js', 'vp-bb-ep', 'anchors.js'), 'w', encoding='utf-8').write(js)
print('ok')
