// ══════════════════════════════════════════════════════════════════════
// td/story/lines/voices/batch17.js — the voice overhaul, depth pass 6 (a fourth set of casts)
// ══════════════════════════════════════════════════════════════════════
// Gaps from seeds 3131, 4141, 5252, 6363, 7474, 8585 (57.3% before). Same meaning per line.

export default {
  'npl.sc4': { 0: { ditzy: "{target} and {partner} are, like, a pair, and pairs get to the end, so I'm splitting them up tonight. I think that's how it works." } },
  'nl4.u3': { 7: { cruel: "{a} finally feels safe, how sweet. I hope {a} is right, for {a}'s sake." } },
  'nl4.u1': {
    1: { ditzy: "Tonight's going to be easy! It's {wrote}, everybody says {wrote}." },
    2: { tough: "Everybody keeps saying that." },
    3: { ditzy: "Because it's true! Did anybody say a different name to you?" },
    4: { tough: "No. Nobody's said a word to me all afternoon, which is weird, now you mention it." },
    6: { tough: "I'm writing {wrote} with you." },
    8: { ditzy: "Okay, then we're fine! We're both fine!" },
  },
  'nvt.f2': {
    0: { blunt: "I think I'm going to make the merge.", ditzy: "Can I tell you something? I think I'm going to make the merge, like, actually!", schemer: "Can I tell you something? I think I'm going to make the merge.", dry: "Can I tell you something? I think I'm going to make the merge, against all odds." },
    2: { ditzy: "Yeah! Tonight's {wrote}, and then nobody's got a reason to come for me.", dry: "Yes. Tonight's {wrote}, and after that, I'm nobody's problem." },
    4: { dry: "It's the best feeling. Thanks, by the way, for having my back, and I don't say that often.", blunt: "It's the best feeling. Thanks for having my back.", ditzy: "It's the best feeling! Thank you for having my back.", competitive: "It's the best feeling. Thanks for having my back." },
  },
  'nv4.p5': {
    0: { cruel: "Let me show you something." },
    1: { dry: "Is it another drawing in the sand? Your favourite medium." },
    2: { cruel: "It's another drawing in the sand. Every line from {partner} goes to {target} and back, which is pathetic, really." },
    3: { dry: "So they talk to each other a lot. Riveting." },
    4: { cruel: "They talk to each other and nobody else. That's not a friendship, it's an alliance pretending to be sweet." },
    5: { dry: "And you want to break it." },
    6: { cruel: "Tonight it's {target}, and then we watch {partner} come crawling to somebody." },
    7: { dry: "Watching that scared me a little. I'm on the other half of that drawing, and I'd like to stay there." },
  },
  'nl4.p1': {
    1: { dry: "You okay?", emotional: "Hey. Are you okay?" },
    3: { dry: "Yeah. I noticed you doing that.", emotional: "Yeah. I noticed you doing that, and it broke my heart a bit." },
    5: { dry: "It's not stupid. You two were close.", emotional: "It's not stupid at all. You two were so close." },
    7: { quiet: "You sit with me.", dry: "You sit with me, that's who. You're stuck with me now.", emotional: "You sit with me. Always." },
  },
  'nth.g2': {
    1: { cruel: "Are you going to pretend last night didn't happen?" },
    3: { cruel: "Your vote was on me. I can count, {b}." },
    6: { cruel: "That's not the point, and you know it." },
  },
  'nl4.k1': { 0: { ditzy: "You've been watching everybody all morning. Like, everybody." } },
  'nl4.a1': {
    1: { emotional: "Can I ask you something honest? Who do you actually trust here, because I'm struggling.", dry: "Honest question: who do you actually trust here? It's a short list, I assume." },
    3: { emotional: "Same. I've been watching who talks to who, and nobody's looking out for either of us, and it scares me.", dry: "Same. I've watched who talks to who, and nobody's looking out for either of us." },
    5: { emotional: "Officially?", dry: "Officially?" },
    7: { emotional: "{group}, I love it. You and me, and nobody else unless we both say yes.", dry: "{group}, fine. You and me, and nobody else unless we both agree." },
  },
  'nvu.p1': {
    3: { emotional: "It's two votes holding hands. Every time one of them is in trouble, the other one saves them, and it's lovely, and it's a problem." },
    5: { emotional: "So if we don't split them now, we never will. It has to be {target} tonight, and I hate it." },
    7: { emotional: "{partner} is going to be heartbroken, and heartbroken people need friends. We'll be there for {partner}." },
  },
  'ns.f4': {
    1: { cruel: "You didn't have to do that.", emotional: "Aw, you didn't have to do that.", competitive: "You didn't have to do that." },
    3: { cruel: "It's a little weird. It's also a little sweet.", emotional: "It's a little weird. It's also really sweet.", competitive: "It's a little weird. It's also sweet." },
    5: { cruel: "You can stay.", emotional: "You can stay. I'd like you to.", competitive: "You can stay." },
  },
  'nl6.y1': {
    1: { ditzy: "Your team's going to wonder where you are!" },
    3: { ditzy: "When this is all over, we're hanging out, for real!" },
    5: { ditzy: "Why wouldn't we?" },
    7: { ditzy: "...Then let's make sure we're on the same side by then?" },
  },
  'nl.l2': {
    1: { calm: "I didn't freeze. I slipped.", dry: "I didn't freeze, I slipped, gracefully." },
    3: { dry: "It was kind of a long slip.", ditzy: "It was, like, a really long slip." },
  },
  'nv.y6': {
    1: { calm: "That's not a quick question." },
    3: { calm: "...Yes." },
    5: { dry: "That's {votes}, and I can breathe now. It's {target} tonight." },
  },
  'nl5.f3': {
    0: { loud: "HEY! That's three fish, and there are EIGHT of us!", dry: "Three fish, and there are eight of us. Interesting maths.", quiet: "That's three fish. There are eight of us.", blunt: "That's three fish. There are eight of us." },
    1: { warm: "I caught them, though." },
    2: { loud: "You caught them for the TEAM! That's how it works!", dry: "You caught them for the team. That's how teams work, apparently.", quiet: "You caught them for the team.", blunt: "You caught them for the team." },
    3: { warm: "Then the team can go catch some. Sorry, I'm just tired." },
    6: { warm: "...Fine, take one, take two. I'm sorry." },
    7: { loud: "Three fish, in front of EVERYBODY! I didn't have to say another word after that!" },
  },
  'nl.w2': {
    1: { ditzy: "We heard you the first five times!" },
    5: { calm: "That's so corny." },
    7: { ditzy: "{a} is going to be so loud tonight, but I don't care, because nobody's going home!" },
  },
  'nl.w3': {
    4: { competitive: "Lucky still counts.", dry: "Lucky still counts. It's in the rules." },
    6: { cruel: "Can we just be happy for one night? Is that too much to ask from you people?", ditzy: "Can we just be happy for one night?" },
  },
  'nk.ao1': { 8: { ditzy: "{a} wants out of {a.posAdj} group and came to me? That's either a big chance or a trap. I'm not sure which." } },
  'nar.l1': { 4: { earnest: "I'm in, honestly. Do we get a name?" } },
  'ns.cf1': {
    1: { anxious: "Shouldn't you be with your team?" },
    3: { anxious: "I'm being a spy. A nervous spy." },
    5: { anxious: "So are you." },
    6: { anxious: "The {mine} are the enemy and {a} is on the {mine}. My brain knows that. The rest of me is in trouble." },
  },
  'nl.w1': {
    2: { ditzy: "Everybody saw {a} out there!" },
    6: { loud: "No vote tonight! NOBODY goes home!" },
    8: { dry: "Winning feels amazing. Being the reason we won is better. It's also how you become a target, which is less fun.", nerdy: "Winning feels amazing, and being the reason we won is better. It also makes me a target later, statistically." },
  },
  'nlx.l1': { 1: { ditzy: "That's just what you do for your people, right? You don't do it so they owe you. You do it because it's right.", calm: "That's what you do for your people, not so they owe you, but because it's right." } },
  'ny.r2': {
    1: { blunt: "Excuse me?", warm: "Excuse me?" },
    3: { blunt: "Worry about the {mine}.", warm: "Worry about the {mine}, okay?" },
    5: { blunt: "Everybody says that right before they lose.", warm: "That's what everybody says right before they lose." },
  },
  'nc.w3': {
    2: { earnest: "No.", cruel: "No." },
    3: { loud: "Do you want FOOD?" },
    4: { earnest: "...Yes.", cruel: "...Yes." },
    5: { cruel: "Fine, you were good out there. I don't think we win without you.", loud: "You were AMAZING out there! I don't think we win without you!", dry: "You were amazing out there. I don't think we win without you, sadly." },
  },
  'nbl.r1': {
    1: { tough: "Go on. Say it." },
    2: { dry: "Not this time." },
    3: { tough: "Really?" },
    6: { dry: "Don't get used to it." },
  },
  'nvu.d1': {
    2: { dry: "I'm trying to work out how many votes I've got. I keep getting the same disappointing number." },
    4: { dry: "Not enough." },
    6: { dry: "{wrote}. It has to be {wrote}." },
    8: { dry: "If I'm wrong, I've wasted an afternoon panicking, and if I'm right, I'm going home. I'd prefer wrong." },
  },
  'nps.b4': {
    0: { dry: "Back home I organise everything. The parties, the group chats. Here, nobody needs me to, which is humbling.", ditzy: "Back home I'm the one who organises everything, like parties and group chats, and here nobody needs me to." },
    1: { ditzy: "So I've been helping with chores. Not because I like chores! People just talk to you when you help." },
  },
  'ny.s1': {
    1: { anxious: "Ha. Nice try." },
    3: { tough: "Fine. Some of the {theirs} aren't as close as they look." },
    5: { tough: "Don't tell anybody I said that." },
  },
  'nth.d1': {
    1: { ditzy: "You'd have done the same!" },
    3: { ditzy: "Well, now you owe me one!" },
    5: { ditzy: "{a} owes me one now. I didn't warn {a} to get a favour, but I'll take it, I guess." },
  },
  'nvu.d7': {
    0: { earnest: "Why do you look like you've seen a ghost?" },
    2: { loud: "Maybe they were talking about something EMBARRASSING!", earnest: "Maybe they were talking about something embarrassing." },
    4: { loud: "So what do we DO?", earnest: "So what do we do?" },
    6: { loud: "I'm with you! Let's go!", earnest: "I'm with you. Let's go." },
    7: { loud: "Maybe {a} is wrong! I'd still rather be paranoid with {a} than get blindsided!", earnest: "Maybe {a} is wrong. I'd honestly rather be paranoid with {a} than get blindsided." },
  },
  'nm.b12': {
    1: { loud: "Why are we all the way OUT here?" },
    3: { loud: "NO! I swear, I found out when everybody else did!" },
    5: { loud: "That's IT? Okay?" },
    7: { loud: "So who do you think DID it?" },
  },
  'nvu.d4': {
    1: { earnest: "You're going to kill that fire." },
    2: { ditzy: "Good. Something should go out tonight that isn't me!" },
    3: { warm: "Wow, okay. Hey, what happened?" },
    4: { ditzy: "Nothing happened! That's the problem. Nobody's talked to me all day, and last time that happened, that person went home." },
    5: { earnest: "So what are you thinking?" },
    6: { ditzy: "{wrote}! If {wrote} goes, the people coming for me lose their loudest voice." },
    7: { warm: "{a} is convinced it's {a} tonight, and I want to help {a}. The numbers say {a} might not be wrong." },
  },
  'nm.b3': {
    2: { ditzy: "Who was what?" },
    4: { anxious: "{a}, can you please calm down for one second?" },
    6: { ditzy: "Yelling at everybody isn't going to bring {lastBoot.obj} back!" },
    8: { anxious: "{a} just kicked a bucket at seven in the morning. If I'd voted for {lastBoot}, I'd be hiding, and honestly, I'm hiding anyway." },
  },
  'nw.y10': {
    0: { cruel: "You've been floating between groups all week.", dry: "You've been floating between groups all week. Very relaxing for you.", warm: "You've been floating between groups all week.", loud: "You've been floating between groups ALL WEEK!", blunt: "You've been floating between groups all week." },
    1: { loud: "I've been LISTENING to groups all week!", ditzy: "I've been listening to groups all week.", earnest: "I've been listening to groups all week.", theatrical: "I've been listening to every group all week, darling.", warm: "I've been listening to everybody all week." },
    2: { cruel: "Then listen to this one. It's {target}, and we have the numbers with you.", dry: "Then listen to this one. It's {target}, and with you we have the numbers.", warm: "Then listen to this one. It's {target}, and we have the numbers with you.", loud: "Then LISTEN to this one! It's {target}, and with you, we have the numbers!", blunt: "It's {target}. With you, we have the numbers." },
    3: { loud: "And WITHOUT me?", ditzy: "And without me?", earnest: "And without me?", theatrical: "And without me?", warm: "And without me?" },
    4: { cruel: "Then we're less sure, and you're the person nobody trusts after tonight.", dry: "Then we're less sure, and you become the person nobody trusts. Your choice.", warm: "Then we're less sure, and I'm worried nobody trusts you after tonight.", loud: "Then we're less sure, and NOBODY trusts you after tonight!", blunt: "Then we're less sure, and nobody trusts you." },
    5: { loud: "...FINE. {target}.", ditzy: "...Okay. {target}.", earnest: "...Fine. {target}.", theatrical: "...Fine. {target}.", warm: "...Okay. {target}." },
    6: { loud: "Being the swing vote is GREAT until you swing the wrong way! I'm not swinging the wrong way tonight!", ditzy: "Being the swing vote is fun until you swing the wrong way. I'm not doing that tonight.", theatrical: "Being the swing vote is glorious until you swing the wrong way, and I refuse to tonight.", warm: "Being the swing vote is great until you pick wrong, and I don't want anybody hurt by my mistake." },
  },
  'nvu.d3': {
    1: { cruel: "That depends on the something." },
    3: { cruel: "That's a question-shaped request." },
    6: { cruel: "I can't promise you {wrote}. I can promise it won't be my vote that sends you home." },
  },
  'nth.g1': {
    1: { dry: "Can I ask you something? Why did you write my name?", emotional: "Can I ask you something? Why did you write my name?" },
    2: { anxious: "What makes you think I did?", loud: "What makes you think I DID?", cruel: "What makes you think I did?", warm: "What makes you think I did?" },
    3: { dry: "There were hardly any votes on me. The maths wasn't hard.", emotional: "There were hardly any votes on me, and it wasn't hard to work out where they came from, and it hurt." },
    4: { loud: "It wasn't about YOU! It was a numbers thing!", cruel: "It wasn't about you. It was a numbers thing." },
    5: { dry: "I had your back. From the first day.", emotional: "I had your back from the very first day." },
    6: { anxious: "I know you did.", loud: "I KNOW you did.", cruel: "I know you did." },
  },
  'nvt.d3': {
    0: { dry: "If it's me tonight, I want you to know I'm not mad at you. Mildly annoyed, maybe." },
    1: { ditzy: "Why would it be you?", emotional: "Why would it be you? Don't say that." },
    3: { ditzy: "Then let's make it somebody else!", emotional: "Then let's make it somebody else. I'm not losing you." },
    5: { ditzy: "{wrote}! I'll start asking around.", emotional: "{wrote}. I'll start asking around, right now." },
    6: { loud: "I've got one friend, one name and three hours! That's not a lot, but it's more than NOTHING!" },
  },
  'nl5.p2': {
    2: { schemer: "We just get each other." },
    3: { competitive: "That's really sweet." },
  },
  'ncx.d1': {
    1: { ditzy: "I think it's me. I really think it's me tonight." },
    2: { calm: "Who told you that?", loud: "Who TOLD you that?" },
    3: { ditzy: "Nobody told me anything! Everybody just stopped talking to me around lunchtime." },
    4: { loud: "So what do you want to DO?" },
    5: { ditzy: "{wrote}! If I can get enough people onto {wrote}, I'm fine." },
    6: { ditzy: "When people go quiet around you, it's never good. I'm not waiting to find out what it means." },
  },
  'nm.b5': {
    1: { ditzy: "Mind if I fish here?", dry: "Mind if I fish here? I won't catch anything." },
    2: { blunt: "Go ahead." },
    3: { ditzy: "You're taking it pretty well? {lastBoot}, I mean.", dry: "You're taking it pretty well. {lastBoot}, I mean." },
    4: { blunt: "Am I? I was about to say the same about you." },
    5: { ditzy: "What's that supposed to mean?", dry: "What's that supposed to mean?" },
    6: { blunt: "You look relaxed for somebody whose team just lost a person." },
    7: { ditzy: "I don't know what you want me to say!", dry: "I don't know what you want me to say." },
    8: { blunt: "Nothing. You've said plenty." },
    9: { blunt: "I won't yell about {lastBoot}. I'll find out who did it, and they'll find out what that means." },
    10: { ditzy: "{a} is way too calm about this, and it's making me nervous.", dry: "{a} is far too calm about this. I'd like to be somewhere else." },
  },
  'nw.n3': {
    0: { calm: "{target}, tonight. Are you in?", warm: "{target}, tonight. Will you be in?", schemer: "{target}, tonight. You in?", theatrical: "{target}, tonight. Are you with me?", blunt: "{target}, tonight. In?" },
    1: { nerdy: "What's in it for me?" },
    2: { calm: "{target} goes home.", warm: "{target} goes home.", schemer: "{target} goes home.", theatrical: "{target} goes home!", blunt: "{target} goes home." },
    3: { nerdy: "That's in it for you. I asked what's in it for me." },
    4: { calm: "...I'll owe you.", warm: "...I'll owe you, I promise.", schemer: "...I'll owe you.", theatrical: "...I'll owe you.", blunt: "I'll owe you." },
    5: { nerdy: "Everyone will owe me eventually. Not tonight." },
    6: { calm: "{b} is shopping for a better deal, and tonight I don't have one to give.", warm: "{b} wants a better deal, and I don't have one. I hope {b} doesn't end up hurt for it.", schemer: "{b} is shopping for a better deal. I'll remember the price.", blunt: "{b} wants a better deal. I don't have one." },
  },
  'nvu.d5': {
    0: { calm: "I'll be honest with you. I'm scared.", warm: "I'm going to be honest with you, I'm really scared.", dry: "I'm going to be honest. I'm scared, which is new.", competitive: "Honestly? I'm scared." },
    1: { earnest: "Of what?", emotional: "Of what? Talk to me.", calm: "Of what?", theatrical: "Of what?", dry: "Of what?", blunt: "Of what?" },
    2: { calm: "Of tonight. Everybody goes for walks in twos and threes, and I'm never one of the two.", warm: "Of tonight. Everybody keeps going for walks in twos and threes, and I'm never one of the two.", dry: "Of tonight. People keep going for walks in pairs, and I'm never half of a pair.", competitive: "Of tonight. Everybody's pairing off, and I'm never picked." },
    3: { earnest: "You're one of my two. I mean that." },
    4: { calm: "Thanks. That's one vote.", warm: "Thank you, that's nice. That's one vote.", dry: "Thanks, that's nice. That's one vote.", competitive: "Thanks. That's one vote." },
    5: { earnest: "Then let's get you more. Who do you want?", emotional: "Then let's get you more. Who do you want?", calm: "Then let's get you more. Who?", theatrical: "Then let's find you more. Who do you want?", dry: "Then let's get you more. Who do you want?", blunt: "Let's get more. Who?" },
    6: { calm: "{wrote}.", warm: "{wrote}.", dry: "{wrote}.", competitive: "{wrote}." },
    7: { earnest: "Okay. Let's go find some people who don't like {wrote}.", emotional: "Okay. Let's go find everybody who doesn't like {wrote}.", calm: "Okay. Let's find people who don't like {wrote}.", theatrical: "Let's go find everyone who can't stand {wrote}.", dry: "Okay, let's go find people who don't like {wrote}. It won't take long.", blunt: "Okay. Let's find people who don't like {wrote}." },
    8: { warm: "Maybe it's not me. Maybe I'm just tired and paranoid. If it is me, I'm going to fight for it.", dry: "Maybe it's not me, and I'm just tired, hungry and paranoid. If it is me, I'm not going quietly." },
  },
  'nvq.p1': {
    1: { cruel: "Have you ever seen one of them without the other?", bossy: "Have you ever seen those two apart?" },
    3: { cruel: "Then you know what happens at the merge. Two votes that never split.", bossy: "Then you know what happens at the merge. Two votes that never split." },
    5: { cruel: "It's cute, and it's going to beat us, so tonight we split them up.", bossy: "It's cute, and it's going to beat us, so tonight we split them up." },
    7: { cruel: "{target}. {partner} without {target} is just a lost puppy.", bossy: "{target}. {partner} won't know what to do without {target}." },
    9: { cruel: "{partner} will be devastated and alone, and alone people need friends. Guess who'll be right there.", bossy: "{partner} will be devastated and on their own, and we'll be there. That's the plan." },
  },
  'fp.c1': { 2: { cruel: "The money, obviously. And to prove I could." } },
  'fp.x2': {
    1: { earnest: "That's mine.", competitive: "That's mine." },
    2: { dry: "Is your name on it?" },
    3: { earnest: "Is yours?", competitive: "Is yours?" },
    5: { earnest: "Fine. Enjoy it.", competitive: "Fine. Enjoy it." },
  },
  'nvq.t2': {
    1: { competitive: "{target}.", schemer: "{target}.", dry: "{target}.", quiet: "{target}.", loud: "{target}!" },
    3: { competitive: "{target} hasn't had to. Everybody likes {target}, and {target} wins challenges. That's who beats us at the end.", schemer: "{target} hasn't had to. Everybody likes {target}, and that's the danger.", dry: "{target} hasn't had to, because everyone likes {target}. That's the whole problem.", quiet: "{target} hasn't had to. Everybody likes {target}.", loud: "{target} hasn't HAD to! Everybody already likes {target}!" },
    4: { bossy: "So you want to get rid of someone for being too good." },
    5: { competitive: "I want them gone before it's too late. Give it a week and nobody will dare write the name.", schemer: "Before it's too late. A week from now, nobody will dare write that name.", dry: "Before it's too late. In a week, nobody will be brave enough to write it.", quiet: "Before it's too late.", loud: "Before it's too LATE! A week from now, nobody will dare!" },
    6: { loud: "And if it blows up on us?", dry: "And if it blows up on us?", bossy: "And if it blows up on us?", warm: "And if it blows up on us?", theatrical: "And if it blows up in our faces?" },
    7: { competitive: "Then it blows up and at least we tried. If we don't, it definitely blows up at the end.", schemer: "Then it blows up, and we tried. If we don't do it, it blows up at the end for sure.", dry: "Then it blows up. If we don't do it, it blows up later, with a jury watching.", quiet: "Then we tried.", loud: "Then it blows up, and at least we TRIED!" },
    8: { loud: "Okay. How many have we got?", dry: "Okay. How many have we got?", bossy: "How many have we got?", warm: "Okay. How many have we got?", theatrical: "Very well. How many do we have?" },
    9: { competitive: "It's tight. Everybody else is on {other}, so we need one more before tonight.", dry: "It's tight. Everybody else is on {other}, so we need one more person, ideally a brave one." },
    10: { competitive: "I don't want to vote out the strong player. I just know I lose to them at the end.", schemer: "I don't want to vote out the strong player either. I just know I'd be sitting next to them at the end, losing.", dry: "I don't want to vote out the strong player. I'd just rather not lose to them.", quiet: "I don't want to. I'd just lose to them at the end." },
  },
  'fp.c2': {
    0: { ditzy: "Oh! Do you want help with that?" },
    1: { dry: "I've got it... actually, no, help me." },
    3: { dry: "Thanks, I'm {b}, by the way. I wasn't listening during names, and nobody was." },
    4: { ditzy: "{a}! I wasn't listening either." },
    5: { dry: "Good. Then we're even." },
    6: { ditzy: "{b} is so easy to be around! I didn't think I'd find somebody like that on day one." },
  },
  'nv4.n3': {
    1: { quiet: "Nobody does." },
    7: { quiet: "You can feel awful and still do it." },
  },
  'nv4.n2': {
    0: { calm: "Who are we doing tonight?", dry: "So, who's the lucky winner tonight?", warm: "Who are we doing tonight?", theatrical: "So, who's the unlucky one tonight?", earnest: "Who are we voting for tonight?" },
    1: { schemer: "{target}.", nerdy: "{target}." },
    3: { schemer: "Just like that. I asked around, and {target} is the name everybody agreed to before I'd finished asking.", nerdy: "Just like that. I asked around, and {target} is the name everybody agreed to." },
    4: { calm: "You don't have a problem with {target}, though.", dry: "You don't even have a problem with {target}.", warm: "You don't have a problem with {target}, though.", theatrical: "You don't even dislike {target}!", earnest: "You don't actually have a problem with {target}." },
    5: { schemer: "I don't need a problem with {target}. I need numbers, and I have them.", nerdy: "I don't need a problem with {target}. I need numbers, and I have them." },
    6: { calm: "And if somebody switches?", dry: "And if somebody switches?", warm: "And if somebody switches?", theatrical: "And if somebody switches?", earnest: "And if somebody switches?" },
    7: { schemer: "Then I find out who, and they're next.", nerdy: "Then I find out who, and they're next." },
  },
  'nw.y6': { 0: { warm: "You've got that look. Who is it?" } },
};
