// ══════════════════════════════════════════════════════════════════════
// td/story/lines/voices/batch20.js — the voice overhaul, pooled pass 3
// ══════════════════════════════════════════════════════════════════════
// Ranked across twelve more fresh seasons (seeds 1919..3737, 71.9% before). One or two connected
// sentences per line, so nothing here reads as a string of fragments.

export default {
  'npm.o1': { 2: { warm: "We are getting water, and while we're getting it, we're going to have a little talk about tonight.", proud: "We are getting water, and while we do, we're discussing tonight.", dry: "We are getting water, technically, and while we're at it, we're talking about tonight." } },
  'nd.nm2': {
    1: { warm: "That's so funny, because I was going to say the same thing to you.", earnest: "That's funny, because honestly, I was going to say the same to you.", calm: "That's funny. I was going to say the same thing to you.", anxious: "That's so funny, I was going to say the same thing to you.", competitive: "That's funny, I was about to say the same to you.", cruel: "How funny, I was going to say the same thing to you.", tough: "Funny, I was going to say the same to you." },
    2: { warm: "Great, something we agree on.", loud: "GREAT! Something we agree on!", earnest: "Great, something we actually agree on.", competitive: "Great, something we agree on.", dry: "Great, something we agree on. Mark the calendar.", tough: "Good, something we agree on.", theatrical: "Marvellous, something we finally agree on." },
    3: { warm: "The only thing.", earnest: "The only thing.", calm: "The only thing.", anxious: "The only thing.", competitive: "The only thing.", cruel: "The only thing, ever.", tough: "The only thing." },
    4: { warm: "Everybody knows I can't stand {b}, and I'm not going to pretend otherwise, because that would be fake.", dry: "Everyone knows I can't stand {b}, and I don't hide it, because faking it would be exhausting." },
  },
  'nl.m1': {
    1: { warm: "Morning, everybody! How did we all sleep?", calm: "Morning, everybody. How did we sleep?", flirty: "Morning, everybody. How did we sleep?" },
    2: { dry: "I didn't, in case anyone was wondering.", warm: "I didn't, honestly.", earnest: "I didn't sleep at all.", proud: "I didn't, but I'm fine.", tough: "I didn't." },
    3: { warm: "Something was crawling on me all night, and I was too tired to move it.", schemer: "Something was crawling on me all night.", quiet: "Something crawled on me all night.", anxious: "Something was crawling on me all night, and I'm still scared to check what.", chaotic: "Something was crawling on me all night, and honestly, I think we're friends now.", calm: "Something was crawling on me all night.", proud: "Something was crawling on me all night, which I did not appreciate." },
    5: { warm: "Okay, so terrible, same as every morning, but we're all still here.", nerdy: "Okay, so terrible, which is consistent with every other morning.", competitive: "Okay, so terrible, same as every morning.", calm: "Okay, terrible, same as every morning.", flirty: "Okay, so terrible, same as every morning." },
    6: { warm: "Is anybody going to eat that?", calm: "Is anybody going to eat that?", ditzy: "Is anybody going to eat that?" },
    7: { dry: "Take it, I've lost my appetite looking at it.", warm: "Take it, I've lost my appetite.", earnest: "Take it, I've lost my appetite.", proud: "Take it, I've lost my appetite.", tough: "Take it." },
    8: { calm: "What do we think today's challenge is?", cruel: "What do we think today's humiliation is?", warm: "What do we think today's challenge is going to be?" },
    9: { warm: "Something with mud, it's always something with mud.", schemer: "Something with mud, it's always something with mud.", quiet: "Mud. It's always mud.", anxious: "Something with mud, I bet, it's always something with mud.", chaotic: "Something with mud, and I'm ready for it!", calm: "Something with mud, it's always mud.", proud: "Something with mud, which is beneath us, frankly." },
  },
  'nd.sb1': {
    0: { warm: "Can I talk to you? I said some things yesterday, and I feel bad.", nerdy: "Can I talk to you? I said some things yesterday that I regret.", competitive: "Can I talk to you? I said some things yesterday.", quiet: "Can we talk? About yesterday." },
    2: { warm: "I didn't mean them, or I meant some of them, but not like that, and not in front of everyone.", proud: "I didn't mean all of it. Some of it, yes, but not like that, and not in public.", nerdy: "I didn't mean them. Well, some of them, but not phrased like that, and not in front of everyone.", competitive: "I didn't mean most of it, and I shouldn't have said any of it in front of everyone.", schemer: "I didn't mean them, not like that, and not in front of everyone." },
    3: { competitive: "That's a strange apology.", anxious: "That's a strange apology.", loud: "That's a STRANGE apology.", tough: "Strange apology." },
    4: { warm: "I'm bad at this, I'm sorry.", proud: "I'm not good at this.", nerdy: "I'm bad at this.", competitive: "I'm bad at this.", schemer: "I'm bad at this.", quiet: "I'm bad at this." },
    5: { loud: "I can TELL! But thanks for trying.", competitive: "I can tell, but thanks for trying.", nerdy: "I can tell, but thank you for trying.", anxious: "I can tell, but thanks for trying.", warm: "I can tell, but thank you for trying, really.", tough: "I can tell. Thanks for trying.", calm: "I can tell, but thanks for trying.", quiet: "Thanks for trying." },
  },
  'no.j2': {
    2: { warm: "Rules first, and the big one is that we vote together, every single time.", earnest: "Rules first: we vote together, every single time.", competitive: "Rule one: we vote together, every time.", quiet: "We vote together. Always.", ditzy: "Rules first! We vote together, like, every time.", loud: "RULES FIRST! We vote together, every single time!", nerdy: "First rule: we vote together, every single time.", theatrical: "Rules first, darling: we vote as one, every single time." },
    3: { earnest: "And nobody talks about this meeting to anyone.", competitive: "And nobody talks about this meeting.", emotional: "And nobody talks about this meeting, to anyone.", calm: "And nobody talks about this meeting.", dry: "And nobody talks about this meeting, obviously.", proud: "And nobody discusses this meeting, with anyone.", nerdy: "And nobody discusses this meeting, with anyone.", anxious: "And nobody talks about this meeting, please, to anyone." },
    4: { schemer: "Not even to your showmance, if you get one.", anxious: "Not even to your showmance, if you get one.", warm: "Not even to your showmance, if you get one!", flirty: "Not even to your showmance, if you get one.", earnest: "Not even to a showmance, if you get one.", loud: "Not even to your SHOWMANCE!", tough: "Not even to a showmance." },
    7: { calm: "{group} has real rules, and I've never been in anything this organised. It's a little scary, but mostly a relief.", anxious: "{group} has real rules, and that scares me a little, but mostly I feel so relieved to belong somewhere.", competitive: "{group} has real rules, and that's how we win. I've never been in anything this organised." },
  },
  'nl6.g2': { 0: { warm: "Hey, are you crying?", anxious: "Hey, are you crying? Are you okay?", loud: "Hey, are you CRYING?", quiet: "Are you crying?", schemer: "Hey, are you crying?" } },
  'nar.l4': {
    0: { warm: "I'm not going to make a big speech. I just think you and I see this game the same way.", calm: "I won't make a speech. I think you and I see this game the same way.", competitive: "No big speech. You and I see this game the same way.", anxious: "I'm not good at speeches, but I think you and I see this game the same way.", loud: "I'm not going to make a big SPEECH! I just think we see this game the same way!" },
    2: { warm: "I'm asking if you'll write the same name as me until it's just us left, and we can call it {group}.", calm: "I'm asking if you'll write the same name as me until it's just us, and we'll call it {group}.", competitive: "Same name as me, every vote, until it's just us, and we call it {group}.", anxious: "I'm asking if you'll write the same name as me until it's just us left, as {group}, if that's okay.", loud: "I'm asking if you'll write the SAME NAME as me until it's just us left! {group}!" },
  },
  'ndp.w5': { 0: { competitive: "Another win, another silence, and I'm getting used to the sound of nobody clapping.", earnest: "That's another win, and another silence, and honestly it's starting to hurt less, which worries me.", warm: "Another win, and another silence. I just wish somebody was happy for me.", blunt: "Another win, and nobody clapped again." } },
  'nlx.c1': {
    1: { warm: "We are celebrating, because we're alive, we're here, and nobody has to cook tonight!", loud: "We are CELEBRATING! We're alive, we're here, and nobody has to cook tonight!", food: "We are celebrating, and nobody has to cook tonight, so I'm eating everything!", calm: "We're celebrating, because we're alive, and nobody has to cook tonight.", theatrical: "We are celebrating, darlings! We're alive, we're here, and nobody cooks tonight!" },
    2: { warm: "Somebody does have to cook tonight, though.", anxious: "Somebody does have to cook tonight, though.", proud: "Somebody does have to cook tonight.", bossy: "Somebody does have to cook tonight, and it isn't going to do itself." },
    3: { warm: "Not with that attitude! Come and dance with me!", loud: "Not with THAT attitude! Dance with me!", food: "Not with that attitude! Dance with me, and then we'll eat!", calm: "Not with that attitude. Dance with me.", theatrical: "Not with that attitude, darling! Dance with me!" },
    4: { quiet: "Fine. One song.", warm: "Fine, one song!", nerdy: "Fine, one song.", anxious: "Fine, one song, but I'm bad at dancing." },
    6: { warm: "For one whole night, nobody talked about the vote, and I didn't know how much I needed that.", dry: "For one night, nobody mentioned the vote, which I'd forgotten was possible.", anxious: "For one night, nobody talked about the vote, and I could finally breathe.", proud: "For one night, nobody talked about the vote, and it was good." },
  },
  'nly.u2': {
    1: { earnest: "Somebody had to, honestly. It was a mess.", calm: "Somebody had to, it was a mess.", warm: "Somebody had to, it was such a mess.", competitive: "Somebody had to. It was a mess." },
    3: { earnest: "Nobody asks me to do anything, so I just do it.", calm: "Nobody asks me to do anything, so I just do it.", warm: "Nobody asks me to do anything, so I just do it.", competitive: "Nobody asks me to do anything. I just do it." },
  },
  'nly.u1': {
    0: { warm: "You're up early.", calm: "You're up early.", schemer: "You're up early.", anxious: "You're up early. Is everything okay?" },
    1: { anxious: "I'm practising the rope climb, because I was the slowest one up it yesterday.", nerdy: "I'm practising the rope climb. I was the slowest yesterday, and I'd like to improve that.", ditzy: "I'm practising the rope climb, because I was so slow yesterday.", calm: "I'm practising the rope climb. I was slowest yesterday.", dry: "I'm practising the rope climb, since I was the slowest one up it yesterday." },
    2: { warm: "You were also the only one who didn't quit.", calm: "You were also the only one who didn't quit.", schemer: "You were also the only one who didn't quit.", anxious: "You were the only one who didn't quit, though." },
    3: { anxious: "Not quitting doesn't win challenges.", nerdy: "Not quitting doesn't win challenges.", ditzy: "Not quitting doesn't win, though.", calm: "Not quitting doesn't win challenges.", dry: "Not quitting doesn't win challenges, sadly." },
    4: { warm: "It does eventually.", calm: "It does eventually.", schemer: "It does, eventually.", anxious: "It does eventually." },
    5: { warm: "{a} has the worst luck in this game and the most stubborn heart, and I know which one I'd bet on.", calm: "{a} has the worst luck and the most stubborn heart here. I know which I'd bet on.", schemer: "{a} has terrible luck and a stubborn heart, and stubborn lasts longer. I'm keeping {a} close.", anxious: "{a} has the worst luck and the most stubborn heart, and I really hope the heart wins." },
  },
  'ny.c2': {
    1: { calm: "Why are we always the ones doing this?", ditzy: "Why is it always us doing this?", schemer: "Why are we always the ones doing this?", quiet: "Why is it always us?", warm: "Why are we always the ones doing this?" },
    6: { calm: "I do the chores because I'm scared of what people say about the ones who don't. I'm not proud of it, but it keeps my name out of their mouths.", quiet: "I do the chores so nobody talks about me." },
  },
  'nk.ro1': {
    0: { warm: "Can you do me a favour? Just mention to the others that you're worried about how close things are.", earnest: "Can you do me a favour, and tell the others you're worried about how close things are?", calm: "Can you do me a favour? Mention to the others that you're worried about how close things are.", anxious: "Could you do me a favour? Just mention to the others you're worried about how close things are." },
    1: { warm: "Worried about who?", calm: "Worried about who?" },
    2: { warm: "Nobody in particular, just say it out loud and see what they say back.", earnest: "Nobody in particular, just say it and see what they say.", calm: "Nobody in particular. Say it and see what comes back.", anxious: "Nobody in particular, just say it and see what they say back." },
    4: { warm: "I just want to know where everyone's head is.", earnest: "I just want to know where everyone's head is, honestly.", calm: "I just want to know where everyone's head is.", anxious: "I just want to know where everyone's head is." },
    5: { calm: "Okay, sure.", anxious: "Okay, sure.", loud: "Okay! Sure!", dry: "Okay, sure.", warm: "Okay, sure!", nerdy: "Okay, sure.", quiet: "Sure." },
  },
  'ny.rd2': {
    0: { calm: "We've made it this far.", warm: "We've made it this far, together.", dry: "We've made it this far, somehow." },
    3: { anxious: "Let them, because they have to get through both of us.", dry: "Let them, they have to get through both of us.", warm: "Let them, they have to get through both of us." },
  },
  'ns.f5': {
    0: { competitive: "We were on different teams for so long, and I never really talked to you.", schemer: "We were on different teams for so long, and I never really talked to you.", dry: "We were on different teams for so long, and I never really talked to you.", calm: "We were on different teams so long, I never really talked to you." },
    1: { quiet: "You were busy trying to beat me.", calm: "You were busy trying to beat me.", warm: "You were busy trying to beat me.", food: "You were busy trying to beat me, and eating my team's snacks.", anxious: "You were busy trying to beat me." },
    2: { competitive: "And you were busy being annoyingly good at challenges.", schemer: "And you were busy being annoyingly good at challenges.", dry: "And you were busy being annoyingly good at challenges.", calm: "And you were busy being annoyingly good at challenges.", warm: "And you were busy being annoyingly good at challenges." },
    3: { quiet: "Was that a compliment?", calm: "Was that a compliment?", warm: "Was that a compliment?", food: "Was that a compliment?", anxious: "Was that a compliment?" },
    4: { competitive: "Don't let it go to your head.", schemer: "Don't let it go to your head.", dry: "Don't let it go to your head.", warm: "Don't let it go to your head." },
    5: { quiet: "Too late.", calm: "Too late.", food: "Too late.", anxious: "Too late.", warm: "Too late." },
    6: { competitive: "I spent weeks thinking {a} was my enemy, and it turns out {a} is just really fun to talk to, which is a problem.", dry: "I spent weeks assuming {a} was my enemy, and it turns out {a} is just fun to talk to. That's inconvenient.", warm: "I spent weeks thinking {a} was my enemy, and it turns out {a} is wonderful to talk to." },
  },
  'nd.ex1': {
    1: { earnest: "Do you ever stop? Seriously, do you ever stop?", calm: "Do you ever stop? Seriously.", cruel: "Do you ever stop? Seriously, ever?", warm: "Do you ever stop? Seriously, do you?", flirty: "Do you ever stop? Seriously?", anxious: "Do you ever stop? Seriously, do you ever stop?" },
    3: { earnest: "It's not what you said, it's everything you say, the correcting and the complaining and all of it.", cruel: "It's not what you said, it's everything you say, and I'm done pretending it isn't.", calm: "It's not what you said, it's everything you say, the correcting and the complaining.", warm: "It's not what you said, it's everything, and I'm sorry, but I can't take it anymore." },
  },
  'nh.e1': { 0: { anxious: "Do you ever stop? Seriously, do you ever stop?", calm: "Do you ever stop? Seriously.", earnest: "Do you ever stop? Seriously, do you?" } },
  'fd.c3': {
    1: { warm: "What is this?", earnest: "What is this?", chaotic: "What is this? Can I touch it?" },
    2: { loud: "I think it's supposed to be STEW.", cruel: "I think it's supposed to be stew. Supposedly.", bossy: "I think it's supposed to be stew." },
    3: { warm: "It's looking at me.", theatrical: "It's looking at me, darling.", anxious: "It's looking at me, I swear.", flirty: "It's looking at me." },
    7: { warm: "Day one, and I'd already trade my whole bag for a sandwich.", competitive: "Day one, and I'd already trade my whole bag for a sandwich.", anxious: "Day one, and I'd already trade my whole bag for one sandwich." },
  },
  'nl.c1': {
    3: { calm: "Don't say latrine, please don't say latrine.", warm: "Please don't say latrine.", anxious: "Please, please don't say latrine." },
    5: { warm: "I'll do water with {b}, it's the easy one.", dry: "I'll do water with {b}, the easy one, obviously.", quiet: "I'll do water with {b}.", loud: "I'll do water with {b}! It's the easy one!" },
  },
  'nh.c1': {
    1: { earnest: "Okay, everybody, water first, then wood.", blunt: "Water first, then wood.", calm: "Okay, everybody, water first, then wood.", food: "Okay, everybody, water first, then wood, then food.", anxious: "Okay, everybody, water first, then wood?" },
    3: { earnest: "Why would you do wood first?", warm: "Why would you do wood first?", blunt: "Why wood first?", calm: "Why would you do wood first?", food: "Why would you do wood first?", anxious: "Why would you do wood first?", tough: "Why wood first?" },
    4: { quiet: "It takes longer, and it's cooler in the morning.", anxious: "Because it takes longer, and it's cooler in the morning.", calm: "Because it takes longer, and it's cooler in the morning.", nerdy: "Because wood takes longer, and the morning is cooler.", theatrical: "Because it takes longer, and the morning is cool!" },
    8: { competitive: "It's not about sides, wood first just makes more sense, okay, fine, it's a little about sides.", calm: "It's not about sides, wood first makes more sense, though fine, it's a little about sides.", ditzy: "It's not about sides, wood first just makes sense, but okay, it's a little about sides.", schemer: "It's not about sides. Wood first makes sense, and yes, it's also a little about sides.", warm: "It's not about sides, wood first just makes more sense, though I do like {b}." },
  },
  'ny.x1': { 1: { warm: "Go on, say it louder, everyone wants to hear it.", dry: "Go on, say it louder, the people at the back can't hear.", anxious: "Go on, say it louder, everyone wants to hear it.", calm: "Go on. Say it louder.", flirty: "Go on, say it louder, everyone wants to hear it." } },
  'nlx.k5': { 0: { competitive: "Nothing to say? Really?", calm: "Nothing to say?", earnest: "Nothing to say? Really?", warm: "Nothing to say? Really?" } },
  'nm.b1': {
    1: { anxious: "You going to eat that?", calm: "You going to eat that?", blunt: "You eating that?", theatrical: "Are you going to eat that?", flirty: "You going to eat that?" },
    3: { food: "What? It's breakfast, and I'm starving.", anxious: "What? It's breakfast.", calm: "What? It's breakfast.", blunt: "It's breakfast.", theatrical: "What? It's breakfast!", flirty: "What? It's breakfast." },
    4: { calm: "{lastBoot} was here yesterday, and now {lastBoot} isn't, and you want to talk about breakfast.", quiet: "{lastBoot} is gone, and you want to talk about breakfast.", warm: "{lastBoot} was here yesterday, and now {lastBoot} isn't, and you want to talk about breakfast?" },
    6: { calm: "Are you? Because you don't look sorry.", anxious: "Are you? Because you don't look sorry.", dry: "Are you? You don't look sorry.", quiet: "You don't look sorry.", warm: "Are you? Because you don't look sorry." },
    8: { calm: "Who it was, that's all I want.", anxious: "Who it was, that's all I want.", dry: "Who it was, that's all I want.", quiet: "Who it was.", warm: "Just who it was, that's all I want." },
    9: { food: "I voted for {lastBoot}, and I'm not going to tell {a} that over breakfast.", anxious: "I voted for {lastBoot}, and I can't tell {a} that over breakfast, I just can't.", blunt: "I voted for {lastBoot}. I'm not saying that at breakfast.", theatrical: "I voted for {lastBoot}, and I will not confess that over breakfast." },
    10: { calm: "{lastBoot} was the one person here I trusted, and somebody at that table voted {lastBoot.obj} out while they all act normal.", anxious: "{lastBoot} was the one person I trusted, and somebody at that table voted {lastBoot.obj} out, and I'm scared to know who." },
  },
  'nvq.r1': {
    1: { warm: "Look at them, they're doing it again.", schemer: "Look at them. They're doing it again.", food: "Look at them, they're doing it again.", quiet: "They're doing it again.", calm: "Look at them, they're doing it again." },
    3: { warm: "Planning. {theirs} has been planning since we got here, and every time we walk past, they go quiet.", schemer: "Planning. {theirs} has been planning since the second we got here, and they go quiet when we pass.", food: "Planning. {theirs} has been planning since we got here, and they go quiet every time we walk past.", quiet: "Planning. They go quiet when we pass.", calm: "Planning. {theirs} has been planning since we arrived, and they go quiet when we walk past." },
    4: { earnest: "So you want to go after {target}.", competitive: "So you want {target}.", anxious: "So you want to go after {target}?", warm: "So you want to go after {target}.", calm: "So you want to go after {target}." },
    5: { warm: "{target} is the glue, and the others listen to {target}, so take {target} out and they're arguing by tomorrow.", schemer: "{target} is the glue. Take {target} out, and they're arguing with each other by tomorrow.", food: "{target} is the glue, and the others listen to {target}, so take {target} out and they start arguing.", quiet: "{target} is the glue. Take {target}, and they fall apart.", calm: "{target} is the glue. Take {target} out, and they start arguing by tomorrow." },
    7: { warm: "I've had a lot of time, because nobody from {theirs} talks to me.", schemer: "I've had a lot of time. Nobody from {theirs} talks to me.", food: "I've had a lot of time, because nobody from {theirs} talks to me.", quiet: "I've had time. Nobody talks to me.", calm: "I've had plenty of time. Nobody from {theirs} talks to me." },
    11: { earnest: "Do we have enough?", competitive: "Do we have enough?", anxious: "Do we have enough?", warm: "Do we have enough?", calm: "Do we have enough?" },
    13: { warm: "It's close, they've got {them} on me, and we've got {votes} on {target}.", food: "It's close, they've got {them} on me, and we've got {votes} on {target}.", quiet: "Close. {them} on me, {votes} on {target}.", calm: "It's close. {them} on me, {votes} on {target}." },
  },
  'nk.tc1': {
    1: { food: "Did you?", competitive: "Did you?", schemer: "Did you?", calm: "Did you?", tough: "Did you?" },
    2: { earnest: "Yeah, I just thought you should know.", ditzy: "Yeah! I just thought you should know.", anxious: "Yeah, I just thought you should know.", loud: "YEAH! I just thought you should know!", food: "Yeah, I just thought you should know.", theatrical: "Yes, I simply thought you should know." },
    3: { food: "Who said it?", competitive: "Who said it?", schemer: "Who said it?", calm: "Who said it?", tough: "Who?" },
    4: { earnest: "I can't say.", ditzy: "I can't say!", anxious: "I can't say, I'm sorry.", loud: "I CAN'T say!", food: "I can't say.", theatrical: "I simply can't say." },
    5: { food: "Of course you can't.", competitive: "Of course you can't.", schemer: "Of course you can't.", calm: "Of course you can't.", tough: "Of course." },
    6: { food: "{b} wanted to see if I'd run around camp panicking. I'm not telling anybody, I'm eating my lunch, and that was a test I just passed.", competitive: "{b} wanted to see if I'd panic and tell everybody. I'm telling nobody, and that test was mine." },
  },
  'nlx.f1': {
    1: { anxious: "Getting firewood.", warm: "Getting firewood.", competitive: "Getting firewood.", emotional: "Getting firewood." },
    3: { anxious: "We always need firewood when something happens.", warm: "We always need firewood when something happens.", competitive: "We always need firewood when something happens.", emotional: "We always need firewood when something happens." },
  },
  'nd.ft1': {
    1: { warm: "I need you to stop talking about me.", competitive: "I need you to stop talking about me." },
    3: { warm: "Yes, you do. You said I can't be trusted, and somebody told me word for word.", competitive: "Yes, you do. You said I can't be trusted, word for word.", nerdy: "Yes, you do. You said I can't be trusted, and I have it word for word." },
  },
  'npl.sc3': { 0: { quiet: "{target} has an idol, I'm fairly sure, and I want it to go home unplayed.", earnest: "I honestly think {target} has an idol, and I'd love it to go home unplayed in {target}'s pocket.", dry: "I'm fairly sure {target} is sitting on an idol, and I'd love it to go home unused, as a souvenir." } },
  'nvr.p1': {
    0: { warm: "Did anyone else notice {target} and {partner} sharing a bowl again?", emotional: "Did anyone else see {target} and {partner} sharing a bowl again?", earnest: "Did anyone else notice {target} and {partner} sharing a bowl again?", ditzy: "Did anybody else see {target} and {partner} sharing a bowl again?", blunt: "{target} and {partner} shared a bowl again.", calm: "Did anyone else notice {target} and {partner} sharing a bowl again?" },
    2: { competitive: "It's sweet until the merge, and then it's two votes that never split.", calm: "It's sweet until the merge, and then it's two votes that never split.", flirty: "It's sweet until the merge, and then it's two votes that never split.", warm: "It's sweet, until the merge, when it's two votes that will never split.", nerdy: "It's sweet until the merge, when it becomes two votes that never split." },
    3: { warm: "So which one?", emotional: "So which one?", earnest: "So which one?", ditzy: "So which one?", blunt: "Which one?", calm: "So which one?" },
    4: { competitive: "{target}, because {partner} without {target} is just somebody looking for a new best friend.", calm: "{target}. Without {target}, {partner} is just looking for a new best friend.", flirty: "{target}. {partner} without {target} is just somebody looking for a new best friend.", warm: "{target}, and {partner} will be looking for a new best friend.", nerdy: "{target}. {partner} without {target} is somebody looking for a new best friend." },
    5: { calm: "And who's that going to be?", earnest: "And who's that going to be?", nerdy: "And who's that going to be?", warm: "And who's that going to be?" },
    6: { competitive: "Whoever's nicest to {partner} tomorrow morning, so all three of us, be really nice.", calm: "Whoever's nicest to {partner} tomorrow, so all of us, be nice.", flirty: "Whoever's nicest to {partner} tomorrow morning, so be very nice.", warm: "Whoever's nicest to {partner} tomorrow, so let's all be really kind.", nerdy: "Whoever's nicest to {partner} tomorrow morning, so let's all be very nice." },
  },
  'ndp.w6': {
    0: { earnest: "I keep winning, and they keep looking at me like I've done something wrong, and I honestly don't know what.", competitive: "I keep winning, and they keep looking at me like it's a crime.", tough: "I keep winning, and they keep glaring at me.", anxious: "I keep winning, and they keep looking at me like I've done something wrong, and it scares me.", warm: "I keep winning, and they look at me like I did something wrong, and it hurts." },
    1: { earnest: "Maybe being good at this is the thing you're not supposed to be here. It's too late to stop now.", competitive: "Maybe being good at this is the one thing you can't be here, but I'm not stopping now." },
  },
  'nv.n3': {
    0: { dry: "So, what are you doing tonight?", competitive: "What are you doing tonight?", schemer: "What are you doing tonight?", flirty: "What are you doing tonight?", anxious: "What are you doing tonight?" },
    1: { competitive: "I've got a plan.", schemer: "I've got a plan.", loud: "I've got a PLAN.", calm: "I've got a plan.", tough: "I've got a plan.", quiet: "I have a plan." },
    2: { dry: "Make it {target}.", competitive: "Make it {target}.", schemer: "Make it {target}.", flirty: "Make it {target}.", anxious: "Make it {target}? Please?" },
    3: { competitive: "My plan isn't {target}.", schemer: "My plan isn't {target}.", loud: "My plan ISN'T {target}.", calm: "My plan isn't {target}.", tough: "My plan isn't {target}.", quiet: "It isn't {target}." },
    4: { dry: "Then change it.", competitive: "Then change it.", schemer: "Then change it.", flirty: "Then change it, for me.", anxious: "Then change it?" },
  },
  'ny.o1': {
    1: { calm: "Can I tell you something I haven't told anybody?", flirty: "Can I tell you something I haven't told anybody else?", warm: "Can I tell you something I haven't told anybody?", loud: "Can I tell you something I haven't told ANYBODY?" },
    3: { calm: "I almost didn't come, because I was scared people wouldn't like me.", flirty: "I almost didn't come, because I was scared people wouldn't like me.", warm: "I almost didn't come, because I was so scared people wouldn't like me.", loud: "I almost didn't come! I was so scared people wouldn't like me!" },
    5: { calm: "Some people.", flirty: "Some people.", warm: "Some people.", loud: "SOME people." },
    7: { calm: "I don't know why I told {b} that. I just felt like I could, and that doesn't happen to me much.", flirty: "I don't know why I told {b} that. I just felt like I could, and I liked that feeling.", loud: "I don't know WHY I told {b} that! I just felt like I could!" },
  },
  'nly.r2': {
    0: { warm: "Can everybody look up from their feet for one second?", calm: "Can everybody stop looking at their feet for a second?", ditzy: "Can everybody stop looking at their feet, just for one second?", competitive: "Everybody, eyes up for one second." },
    2: { warm: "I know, I'm tired too, but if we go to bed like this, we wake up like this, and we lose again.", calm: "I'm tired too, but if we go to bed like this, we wake up like this and lose again.", ditzy: "I know, I'm tired too, but if we go to bed sad, we wake up sad, and we lose again.", competitive: "I'm tired too, but if we sleep on this, we lose again." },
    4: { warm: "A pep talk, and then everybody gets the last of the hot water.", calm: "A pep talk, and then everybody gets the last of the hot water.", ditzy: "A pep talk, and then everybody gets the last of the hot water!", competitive: "A pep talk, and then the last of the hot water." },
  },
  'nl.n1': { 4: { competitive: "I'm fine.", calm: "I'm fine.", loud: "I'm FINE.", chaotic: "I'm fine! Totally fine!", anxious: "I'm fine. I think.", theatrical: "I am perfectly fine." } },
  'nlx.k1': {
    0: { warm: "We need to talk about what you did.", loud: "We need to TALK about what you did.", competitive: "We need to talk about what you did.", anxious: "We need to talk about what you did." },
    3: { competitive: "I don't have a good reason. I panicked and made a bad call, and you got hurt.", dry: "I don't have a good reason. I panicked, made a bad call, and you paid for it.", loud: "I don't have a good reason! I panicked, I made a bad call, and you got hurt!", calm: "I don't have a good reason. I panicked, I made a bad call, and you got hurt by it.", bossy: "There's no good reason. I panicked, made a bad call, and you got hurt." },
  },
  'nh.j1': {
    2: { warm: "Can I be a duke yet?", calm: "Can I be a duke yet?", emotional: "Can I please be a duke yet?", ditzy: "Can I be a duke now?" },
    4: { warm: "I carried the water for three days!", calm: "I carried the water for three days.", emotional: "I carried the water for three whole days!", ditzy: "I carried the water for three days!" },
    5: { warm: "Fine, Duke of Water.", dry: "Fine. Duke of Water.", schemer: "Fine, Duke of Water.", tough: "Fine. Duke of Water.", calm: "Fine. Duke of Water." },
    6: { warm: "I'll take it!", calm: "I'll take it.", emotional: "I'll take it! I'm so happy!", ditzy: "I'll take it!" },
  },
  'nd.sa3': {
    1: { earnest: "We got off on both wrong feet.", dry: "We got off on both wrong feet, impressively.", flirty: "We got off on both wrong feet.", warm: "We got off on both wrong feet, didn't we?" },
    3: { earnest: "Is this a real sorry, or a game sorry?", dry: "Is this a real sorry, or a game sorry?", flirty: "Is this a real sorry, or a game sorry?", warm: "Is this a real sorry, or a game sorry?" },
    5: { earnest: "That was a game sorry, and I know a game sorry when I hear one. I'll still take it, because I need allies too.", dry: "That was a game sorry. I know one when I hear it, and I'll still take it, because allies are allies.", warm: "That was a game sorry, I think, but I'll take it, because I need friends too." },
  },
  'ny.co1': {
    6: { quiet: "You do?", calm: "You do?", warm: "You do?" },
    8: { quiet: "I didn't want anyone to see me like that. I'm glad it was {a}.", calm: "I didn't want anyone to see me like that, and I'm glad it was {a}.", tough: "I didn't want anyone to see me like that. If somebody had to, I'm glad it was {a}.", warm: "I didn't want anyone to see me like that, and I'm so glad it was {a}." },
  },
  'nps.r2': {
    0: { earnest: "You've been coughing all night. Here, take my blanket.", anxious: "You've been coughing all night, here, take my blanket, please.", emotional: "You've been coughing all night. Here, take my blanket.", warm: "You've been coughing all night, sweetie. Here, take my blanket." },
    2: { earnest: "I've been cold before. Take it.", anxious: "I've been cold before, it's fine, take it.", emotional: "I've been cold before. Please take it.", warm: "I've been cold before, it's fine. Take it." },
    4: { earnest: "Because somebody has to, and I'd rather it was me.", anxious: "Because somebody has to, and I'd rather it was me.", emotional: "Because somebody has to, and I'd rather it was me.", warm: "Because somebody has to, and I'd rather it was me." },
  },
  'nvt.f2': { 2: { earnest: "Yeah. Tonight's {wrote}, honestly, and after that nobody's got a reason to come for me.", food: "Yeah. Tonight's {wrote}, and after that nobody's got a reason to come for me.", warm: "Yeah. Tonight's {wrote}, and after that, nobody has a reason to come for me.", chaotic: "Yeah! Tonight's {wrote}, and after that, nobody's got a reason to come for me!" } },
  'ns.f1': {
    6: { warm: "You're smiling, though.", calm: "You're smiling, though.", food: "You're smiling, though.", quiet: "You're smiling." },
    9: { warm: "{b} laughed at all my jokes today, even the bad ones, especially the bad ones.", calm: "{b} laughed at all my jokes today, even the bad ones.", food: "{b} laughed at all my jokes today, even the bad ones, and shared a snack with me.", quiet: "{b} laughed at all my jokes. Even the bad ones." },
  },
  'nl5.i1': { 4: { warm: "Nobody saw and nobody knows, and that's the most important part.", proud: "Nobody saw, and nobody knows. That's what matters.", schemer: "Nobody saw and nobody knows, which is the whole point.", calm: "Nobody saw and nobody knows. That's the important part." } },
  'nl.h3': { 1: { calm: "People are nervous, and nobody's said a name to me.", competitive: "People are nervous. Nobody's said a name to me.", dry: "People are nervous, and nobody's said a name to me, which is suspicious.", ditzy: "People are nervous, and nobody's told me a name." } },
  'nl.l1': {
    5: { earnest: "{b} did come last, though.", warm: "{b} did come last, though. Sorry.", dry: "{b} did come last, though." },
    6: { competitive: "And who was yelling the whole time instead of helping?", earnest: "And who was yelling the whole time instead of helping?", calm: "And who was yelling instead of helping?", warm: "And who was yelling the whole time instead of helping?" },
    8: { proud: "When should we do it, then? After the vote?", nerdy: "When should we do it? After the vote?", chaotic: "When should we do it? After the vote?", theatrical: "When should we do it, then? After the vote?" },
  },
  'nc.w1': {
    2: { earnest: "We did that.", anxious: "We did that, all of us.", loud: "WE did that!", dry: "We did that." },
    4: { earnest: "Hey, you didn't fall over, and that counts.", anxious: "Hey, you didn't fall over, that counts.", warm: "Hey, you didn't fall over. That counts.", loud: "Hey, you didn't fall over! That COUNTS!", dry: "You didn't fall over, which counts." },
  },
  'ne.b1': {
    0: { earnest: "We're all good for tonight, yeah? {target}?", proud: "We're all good for tonight? {target}?", warm: "We're all good for tonight, yeah? {target}?", calm: "We're all good for tonight? {target}?", dry: "We're all good for tonight, yeah? {target}?" },
    2: { earnest: "You don't sound very sure.", proud: "You don't sound sure.", warm: "You don't sound very sure.", calm: "You don't sound very sure.", dry: "You don't sound very sure." },
    4: { earnest: "Everybody hates this part.", proud: "Everybody hates this part.", warm: "Everybody hates this part.", calm: "Everybody hates this part.", dry: "Everybody hates this part." },
  },
  'nar.r1': { 2: { loud: "You're not! We were just talking about lunch!", competitive: "You're not. We were talking about lunch.", anxious: "You're not, we were just talking about lunch.", dry: "You're not. We were just talking about lunch." } },
  'ns.f2': {
    2: { competitive: "I'm fine.", calm: "I'm fine.", ditzy: "I'm fine!", warm: "I'm fine." },
    3: { warm: "Here, take my jacket.", schemer: "Here, take my jacket.", anxious: "Here, take my jacket.", dry: "Here, take my jacket." },
    4: { competitive: "Then you'll be cold.", calm: "Then you'll be cold.", ditzy: "Then you'll be cold!", warm: "Then you'll be cold." },
    6: { competitive: "...It's okay.", calm: "...It's okay.", ditzy: "...It's okay.", warm: "...It's okay." },
    8: { calm: "Nothing happened, we just sat there, and it was the best night I've had since I got here.", ditzy: "Nothing happened, we just sat there, and it was the best night I've had here.", warm: "Nothing happened, we just sat there, and it was the best night since I got here.", competitive: "Nothing happened, and it was the best night I've had here. I'm in trouble." },
  },
  'ny.d3': { 6: { earnest: "{a} made us do a sharing circle, and I hated it, and honestly I'm doing it again tomorrow.", calm: "{a} made us do a sharing circle, and I'll do it again tomorrow.", quiet: "{a} made us share. I'll do it again.", ditzy: "{a} made us do a sharing circle, and I hated it, and I'm doing it again tomorrow!" } },
  'ny.n2': { 5: { warm: "No, but I'm saying it anyway.", proud: "No, but I'm saying it anyway.", calm: "No, but I'm saying it anyway.", nerdy: "No, but I'm saying it anyway." } },
  'nw.y7': { 4: { calm: "You're very polite about votes.", competitive: "You're very polite about votes." } },
  'nar.l5': {
    0: { warm: "Everybody else already has a group, and if we don't make one, we're the leftovers.", food: "Everybody else has a group, and if we don't make one, we're the leftovers.", anxious: "Everybody else already has a group, and if we don't make one, we're the leftovers.", calm: "Everybody else has a group. If we don't make one, we're the leftovers." },
    1: { warm: "So we make one.", competitive: "So we make one.", calm: "So we make one.", theatrical: "Then we make one." },
    3: { warm: "We know we're the ones nobody asked, and that's enough to start with, as {group}.", food: "We know we're the ones nobody asked, and that's enough to start, as {group}.", anxious: "We're the ones nobody asked, and that's enough to start with, as {group}.", calm: "We're the ones nobody asked, and that's enough to start with, as {group}." },
  },
  'nm.n2': {
    0: { competitive: "Is it weird that nobody's said {lastBoot}'s name all morning?", schemer: "Has anybody noticed nobody's said {lastBoot}'s name all morning?", calm: "Is it weird that nobody's said {lastBoot}'s name all morning?", anxious: "Is it weird nobody's said {lastBoot}'s name all morning?" },
    8: { dry: "I liked {lastBoot}, I really did, but watching {lastBoot} try to befriend everybody scared me into picking a side.", schemer: "I liked {lastBoot}. Watching {lastBoot} try to please everyone taught me to pick a side, and fast." },
  },
  'nk.tn2': { 0: { schemer: "Now that it's every person for themselves, everyone's going to look at {b}, and I'd like to be looking first.", dry: "Now it's every person for themselves, everybody will look at {b}.", nerdy: "With the teams gone, everybody will start looking at {b}.", anxious: "Now that it's every person for themselves, everybody is going to look at {b}, and I'm next to {b}.", flirty: "Now that it's every person for themselves, everyone's going to look at {b}." } },
  'nl5.s1': { 6: { dry: "I was nice to {b} just now, and I meant it. I'll also be thinking about that challenge when we vote, because I'm practical.", nerdy: "I was nice to {b} just now, and I meant it, but I'll still be weighing that challenge at the vote.", anxious: "I was kind to {b}, and I meant it, but I'm scared I'll still be thinking about that challenge at the vote." } },
  'nvu.g2': { 2: { calm: "Oh, we know. The whole camp heard you two this morning.", earnest: "Oh, we know. The whole camp heard you two this morning.", warm: "Oh, we know. The whole camp heard you two this morning.", food: "Oh, we know. The whole camp heard you two this morning, over breakfast.", anxious: "Oh, we know. The whole camp heard you two this morning." } },
  'ns.k1': {
    2: { warm: "Rules are rules.", earnest: "Rules are rules.", tough: "Rules are rules.", anxious: "Rules are rules." },
    3: { competitive: "There are no rules! We made this up ten minutes ago!", nerdy: "There are no rules. We invented this game ten minutes ago.", bossy: "There are no rules, we made this up ten minutes ago!", warm: "There are no rules! We made this up ten minutes ago!" },
    6: { competitive: "...Okay. Spin it again.", nerdy: "...Okay. Spin it again.", bossy: "...Fine. Spin it again.", warm: "...Okay. Spin it again." },
  },
  'ncx.b1': {
    1: { calm: "{lastBoot} left this, and I can't bring myself to throw it out. It's just a shirt, except it isn't.", warm: "{lastBoot} left this, and I can't bring myself to throw it out, because it's not just a shirt." },
    2: { calm: "Everybody else woke up today and got on with it, and I woke up without anybody to get on with.", warm: "Everybody else woke up and got on with it, and I woke up with nobody to get on with, and it hurt." },
  },
  'nl.m2': {
    5: { warm: "Talk about what? It's a game, people leave.", earnest: "Talk about what? It's a game, and people leave.", calm: "Talk about what? It's a game, and people leave.", dry: "Talk about what? It's a game, people leave, and that's the format." },
    8: { quiet: "I keep looking around the table, wondering who wrote {lastBoot}'s name.", dry: "I keep looking around the table wondering who wrote {lastBoot}'s name, and nobody's giving it away.", calm: "I keep looking around the table wondering who wrote {lastBoot}'s name, and it makes me a little sick.", warm: "I keep looking around the table wondering who wrote {lastBoot}'s name, and it makes me feel sick." },
  },
  'nar.t1': { 3: { competitive: "Everybody loves {b}, and {b} wins challenges and never gets tired. That's great for the team now and a disaster for me later.", anxious: "Everybody here loves {b}. {b} wins, helps everyone, never gets tired, and that terrifies me for later." } },
  'nl6.i1': {
    2: { warm: "Nope.", calm: "Nope.", dry: "Nope.", quiet: "No.", food: "Nope." },
    3: { warm: "Then why are you staring at me?", earnest: "Then why are you staring at me?", ditzy: "Then why are you staring at me?", nerdy: "Then why are you staring at me?" },
    4: { warm: "Just interested in what you're going to do next.", calm: "Just interested in what you'll do next.", dry: "Just interested in what you're going to do next.", quiet: "Just watching.", food: "Just interested in what you're going to do next." },
    5: { warm: "I'm going to get water.", earnest: "I'm going to get water.", ditzy: "I'm going to get water?", nerdy: "I'm going to get water." },
    6: { warm: "Interesting.", calm: "Interesting.", dry: "Interesting.", quiet: "Interesting.", food: "Interesting." },
    8: { warm: "It is when you do it.", calm: "It is when you do it.", dry: "It is when you do it.", quiet: "It is when you do it.", food: "It is when you do it." },
  },
  'nm.b2': {
    2: { ditzy: "Not really.", calm: "Not really.", nerdy: "Not really.", earnest: "Not really.", warm: "Not really." },
    3: { competitive: "I'm sorry, I didn't know it was going to be {lastBoot}, I swear.", loud: "I'm sorry! I didn't KNOW it was going to be {lastBoot}!", blunt: "I didn't know it was {lastBoot}. I swear.", quiet: "I didn't know. I swear.", anxious: "I'm so sorry, I didn't know it was going to be {lastBoot}, I swear." },
  },
  'nly.l1': {
    1: { calm: "What are you doing?", ditzy: "What are you doing?", earnest: "What are you doing?", loud: "What are you DOING?" },
    2: { warm: "Singing! Join in, it's the only song I know all the words to.", competitive: "Singing. Join in, it's the only song I know all the words to.", theatrical: "Singing, darling! Join in, it's the only song I know every word of.", dry: "Singing. Join in, it's the only song I know all the words to.", flirty: "Singing. Join in, it's the only song I know all the words to." },
    3: { anxious: "That's a commercial jingle.", cruel: "That's a commercial jingle.", quiet: "That's a jingle.", theatrical: "That's a commercial jingle!", warm: "That's a commercial jingle!" },
    4: { warm: "And it slaps.", competitive: "And it slaps.", theatrical: "And it slaps.", dry: "And it slaps.", flirty: "And it slaps." },
    6: { calm: "We were soaking wet and starving, and {a} had us singing about breakfast cereal.", ditzy: "We were soaking wet and starving, and somehow {a} had us all singing about cereal!", earnest: "We were wet and starving, and {a} had us singing about breakfast cereal. I loved it.", loud: "We were SOAKING wet and STARVING, and {a} had us singing about breakfast cereal!" },
  },
  'nar.e1': { 0: { calm: "I've got an Extra Vote, and tonight I'm using it, because I want {target} gone and I'm not leaving that to anybody else.", quiet: "I've got an Extra Vote. Tonight it goes on {target}." } },
  'nl6.m2': { 3: { calm: "Nobody here is not hungry.", anxious: "Nobody here is not hungry.", chaotic: "Nobody here is not hungry!", loud: "NOBODY here is not hungry!" } },
  'nm.n3': { 2: { dry: "{lastBoot}'s been gone, what, ten hours? Respect for the dead.", emotional: "{lastBoot}'s been gone, what, ten hours?", calm: "{lastBoot}'s been gone, what, ten hours?" } },
  'nl.l3': {
    1: { loud: "I'm breathing! I'm also annoyed!", proud: "I'm breathing, and I'm also annoyed.", warm: "I'm breathing, and I'm also a bit annoyed." },
    2: { quiet: "I know it was me.", anxious: "I know it was me, you don't have to say it.", cruel: "I know it was me. You don't have to say it.", proud: "I know it was me. You don't need to say it." },
    3: { calm: "It wasn't only you.", earnest: "It honestly wasn't only you.", dry: "It wasn't only you.", nerdy: "It wasn't only you." },
    4: { warm: "It was all of us, and whoever goes tonight goes because of a vote, not one mistake.", food: "It was all of us, and whoever goes tonight goes because of a vote, not one mistake.", calm: "It was all of us. Whoever goes tonight goes because of a vote, not one mistake." },
    5: { earnest: "That's very wise, and I hate it.", warm: "That's very wise, and I hate it.", chaotic: "That's very wise, and I hate it!", blunt: "Wise. I hate it." },
  },
  'nk.cs1': { 6: { earnest: "That was my move, mine, and {a} is just standing there telling everyone it was {a.posAdj}.", competitive: "That was my move, and {a} is telling everyone it was {a.posAdj}. I won't let that stand.", calm: "That was my move, and {a} is just standing there telling everyone it was {a.posAdj}.", nerdy: "That was my move, and {a} is claiming it as {a.posAdj} in front of everyone." } },
  'nps.b3': {
    0: { dry: "Can I ask you something weird? Do people here like me?", quiet: "Do people here like me?", warm: "Can I ask you something weird? Do people here like me?" },
    2: { dry: "Then why did my name come up last night?", quiet: "Then why did my name come up?", warm: "Then why did my name come up last night?" },
    3: { competitive: "That's not about liking you, that's about the game.", warm: "That's not about liking you, I promise, that's about the game.", calm: "That's not about liking you. That's the game.", anxious: "That's not about liking you, it's about the game." },
    4: { dry: "It doesn't feel like the game. It feels like the cafeteria in eighth grade, but with worse food.", quiet: "It feels like the cafeteria in eighth grade.", warm: "It doesn't feel like the game, it feels like the cafeteria in eighth grade." },
  },
  'nk.ta1': { 0: { calm: "Want to know something? Just between us.", competitive: "Want to know something? Just between us.", warm: "Want to know something? Just between us.", earnest: "Want to know something, just between us?" } },
  'nv.y5': {
    1: { warm: "I'm always the vote somebody needs. What's the name?", loud: "I'm ALWAYS the vote somebody needs! What's the name?", food: "I'm always the vote somebody needs. What's the name?" },
    3: { warm: "Interesting. And when you need me again?", loud: "Interesting! And when you need me AGAIN?", food: "Interesting. And when you need me again?" },
    5: { warm: "Good, because I won't either. {target}.", loud: "Good, because I won't EITHER! {target}!", food: "Good, because I won't either. {target}." },
    6: { warm: "{a} owes me now, and that's worth a lot more than one vote.", loud: "{a} owes me NOW, and that's worth more than one vote!", food: "{a} owes me now, and that's worth a lot more than one vote." },
  },
  'nly.k2': { 3: { calm: "I'm not looking at you like anything.", quiet: "I'm not looking at you.", theatrical: "I am not looking at you like anything, darling.", anxious: "I'm not looking at you like anything!" } },
  'nl.h3': { 8: { calm: "{a} runs these meetings like a general, which is a little scary, but it keeps us alive.", dry: "{a} runs these meetings like a general, which is a little scary, but also why we're alive.", ditzy: "{a} runs these meetings like a general! It's scary, but it keeps us alive." } },
  'nps.e4': { 1: { nerdy: "I can't save everybody, and I'm finally accepting that. I just have to make sure I'm still standing.", anxious: "I can't save everybody, I'm learning that, and it scares me. I just have to stay standing.", quiet: "I can't save everyone. I just have to keep standing." } },
  'ny.st1': {
    3: { competitive: "Why are we still doing this?", chaotic: "Why are we still doing this?", theatrical: "Why are we still doing this?" },
    5: { competitive: "Okay, five more minutes, and then we collapse.", chaotic: "Five more minutes, then we collapse!", theatrical: "Five more minutes, and then we collapse dramatically." },
  },
  'ny.rd1': {
    0: { dry: "Promise me something.", calm: "Promise me something.", loud: "PROMISE me something." },
    1: { anxious: "Depends what it is.", ditzy: "Depends what it is!", dry: "Depends what it is.", flirty: "Depends what it is." },
  },
  'ns.s3': {
    3: { calm: "So should we stop?", nerdy: "So should we stop?", warm: "So should we stop?" },
    4: { schemer: "Do you want to?", emotional: "Do you want to?", food: "Do you want to?" },
    5: { calm: "No.", nerdy: "No.", warm: "No." },
    7: { calm: "Being in a couple at the merge is stupid, and every strategy book would say so, and I'm doing it anyway.", nerdy: "Being in a couple at the merge is strategically terrible, and I'm doing it anyway.", warm: "Being in a couple at the merge is stupid, and I don't care, because I'm happy." },
  },
  'ns.s2': {
    3: { warm: "Is this a thing, you and me? Because I want it to be a thing.", calm: "Is this a thing, you and me? I'd like it to be.", theatrical: "Is this a thing, you and me? Because I want it to be a thing." },
    5: { warm: "Then why didn't you say?", calm: "Then why didn't you say?", theatrical: "Then why didn't you say?" },
    7: { warm: "I'm smiling so much my face hurts, and it's not official official, but it's official to me.", calm: "It's not official official, but it's official to me, and I'm very happy.", theatrical: "My face hurts from smiling. It's not official official, but it's official to me." },
  },
  'nv4.n4': {
    0: { quiet: "Roll call. Who's everybody writing?", proud: "Okay, roll call. Who's everybody writing?", warm: "Okay, roll call. Who's everybody writing?" },
    1: { warm: "{target}.", calm: "{target}.", earnest: "{target}." },
    2: { earnest: "{target}.", warm: "{target}.", proud: "{target}.", dry: "{target}." },
    3: { quiet: "{target}. Easy.", proud: "{target}. Okay, that was easy.", warm: "{target}. Okay, that was easy." },
    4: { earnest: "Easy is good, because easy means nobody does something stupid.", warm: "Easy is good. Easy means nobody does anything stupid.", proud: "Easy is good. Nobody does anything stupid.", dry: "Easy is good. Easy means nobody goes rogue." },
  },
  'nvr.g1': {
    1: { nerdy: "I'm writing {target} tonight, and I'm telling you now so nobody acts surprised.", competitive: "I'm writing {target} tonight, so nobody act surprised.", loud: "I'm writing {target} TONIGHT, so nobody act surprised!", proud: "I'm writing {target} tonight. Consider yourselves informed." },
    2: { warm: "Because of the thing at lunch?", quiet: "The thing at lunch?", loud: "Because of the thing at LUNCH?" },
    3: { nerdy: "Because of lunch, and yesterday, and every single day before that.", competitive: "Because of lunch, yesterday, and every day before that.", loud: "Because of the thing at lunch, AND yesterday, AND every day before that!", proud: "Because of lunch, and yesterday, and every day before." },
    4: { calm: "We can't vote somebody out just because you hate them.", warm: "We can't vote somebody out just because you don't like them.", blunt: "We can't vote someone out because you hate them." },
    5: { nerdy: "I don't hate {target}, okay, I do, but {target} hates me too, which means {target} writes my name the second it's easy.", competitive: "Fine, I hate {target}, but {target} hates me too, and writes my name the moment it's easy.", loud: "I don't HATE {target}! Okay, I do! But {target} hates me too, and writes my name the second it's easy!", proud: "I don't hate {target}, fine, I do, and {target} would write my name the moment it's easy." },
    6: { warm: "That's fair, actually.", quiet: "Fair.", loud: "That's FAIR, actually." },
    9: { calm: "...Fine.", warm: "...Fine.", blunt: "Fine." },
    10: { warm: "{a} is running a whole vote on pure rage, and I'm kind of impressed, and I'm also staying out of {a}'s way.", quiet: "{a} is voting on rage. I'm staying out of the way.", loud: "{a} is running a WHOLE vote on pure rage! I'm staying out of {a}'s way!" },
  },
  'nw.n1': { 6: { calm: "{b} won't tell me, so {b} is with somebody else, and I need to find out who before tonight.", dry: "{b} won't tell me, so {b} is with somebody else, wonderful, and I need to know who.", loud: "{b} won't tell me! That means {b} is with somebody else, and I need to know who!" } },
  'nd.cl1': {
    5: { warm: "That makes no sense to me.", anxious: "That makes no sense.", tough: "That makes no sense." },
    8: { warm: "Nobody voted {b} in charge, or me either, but at least I'm good at it.", anxious: "Nobody voted {b} in charge, or me, but I'm trying my best, and I think I'm good at it.", tough: "Nobody voted {b} in charge. Nobody voted me either, but I'm good at it." },
  },
  'nd.dp1': { 1: { warm: "Can I stop you?", anxious: "Can I stop you?" } },
  'nl6.s2': { 0: { competitive: "Did everybody see that catch at the challenge? I'm happy to do it again, slower, for anyone who missed it.", proud: "Did everybody see that catch? I'll gladly do it again, slower, for anyone who missed it.", ditzy: "Did everybody see that catch? I can do it again, slower, if anybody missed it!" } },
  'nd.sm1': {
    1: { calm: "Everybody saw all that yesterday.", loud: "EVERYBODY saw all that yesterday.", dry: "Everybody saw all that yesterday. In detail.", theatrical: "Everybody witnessed all of that yesterday." },
    2: { warm: "Yeah, I'm sorry. I wasn't okay, and I took it out on everybody.", anxious: "Yeah, I'm so sorry. I wasn't okay, and I took it out on everybody.", cruel: "Yeah. I wasn't okay, and I took it out on everybody.", nerdy: "Yeah, I'm sorry. I wasn't okay, and I took it out on everyone." },
    3: { calm: "You don't have to apologise for having a bad day.", loud: "You don't have to apologise for a bad day!", dry: "You don't have to apologise for having a bad day.", theatrical: "You needn't apologise for a bad day." },
    4: { warm: "I kind of do, I threw a bucket.", anxious: "I kind of do, because I threw a bucket.", cruel: "I kind of do. I threw a bucket.", nerdy: "I kind of do, since I threw a bucket." },
    5: { calm: "You did throw a bucket.", loud: "You DID throw a bucket.", dry: "You did throw a bucket. A big one.", theatrical: "You did throw a bucket." },
    6: { warm: "I'm embarrassed, but {b} was so nice about it, nicer than I'd have been.", anxious: "I'm so embarrassed, and {b} was really nice about it, nicer than I'd have been.", cruel: "I'm embarrassed. {b} was nicer about it than I would have been.", nerdy: "I'm embarrassed, but {b} was kinder about it than I'd have been." },
  },
  'nd.ex2': { 0: { calm: "I'm going to say this once.", competitive: "I'm going to say this once.", earnest: "I'm going to say this once, honestly.", food: "I'm going to say this once." } },
  'nar.w4': { 3: { warm: "And did you think about it?", loud: "And did you THINK about it?", tough: "And did you think about it?" } },
  'nly.a2': {
    0: { competitive: "Can I ask you something about the group, just between us?", proud: "Can I ask you something about the group, between us?", bossy: "I want to ask you something about the group, just between us.", loud: "Can I ask you something about the group? Just between US?" },
    2: { competitive: "Do you feel like everybody in it is still on the same page?", proud: "Do you feel everyone's still on the same page?", bossy: "Is everybody in it still on the same page?", loud: "Do you feel like EVERYBODY is still on the same page?" },
    4: { competitive: "I don't know, that's why I'm asking you first.", proud: "I don't know, which is why I'm asking you first.", bossy: "I don't know. That's why I'm asking you first.", loud: "I don't KNOW! That's why I'm asking you first!" },
  },
  'na.k4': {
    3: { competitive: "Of course. Why wouldn't we be?", dry: "Of course. Why wouldn't we be?", bossy: "Of course we are. Why wouldn't we be?", warm: "Of course! Why wouldn't we be?" },
    7: { competitive: "...With the game. Everybody's busy with the game.", dry: "...With the game. Everybody's busy with the game.", bossy: "...With the game. Everyone's busy with the game.", warm: "...With the game. Everybody's busy with the game, sorry." },
  },
  'nh.s1': {
    2: { competitive: "Not really.", calm: "Not really.", nerdy: "Not really.", food: "Not really." },
    3: { earnest: "Something was crawling on me all night.", anxious: "Something was crawling on me all night, and I'm scared to look.", loud: "Something was CRAWLING on me all night!", warm: "Something was crawling on me all night." },
    4: { warm: "That was me, sorry, the ground is really lumpy.", schemer: "That was me, sorry, the ground is really lumpy." },
  },
  'nl.d2': {
    0: { emotional: "So nobody's going to say it?", warm: "So nobody's going to say it?", proud: "So nobody is going to say it?", calm: "So nobody's going to say it?" },
    8: { quiet: "I hate dinner before a vote. Everybody smiles, and I can't tell who's lying.", theatrical: "I despise dinner before a vote. Everybody smiles at everybody, and I can't tell who's lying." },
  },
  'ny.m1': {
    1: { quiet: "Same thing as yesterday?", calm: "Is this the same thing as yesterday?", chaotic: "Is this the same thing as yesterday?", warm: "Is this the same thing as yesterday?" },
    2: { competitive: "I think it's the same thing as every day.", proud: "It's the same as every day.", warm: "I think it's the same thing as every day." },
    3: { warm: "I'm going to pretend it's pancakes.", calm: "I'm going to pretend it's pancakes.", anxious: "I'm going to pretend it's pancakes." },
    4: { competitive: "How's that going?", proud: "How's that going?", warm: "How's that going?" },
    5: { warm: "Badly.", calm: "Badly.", anxious: "Badly." },
    6: { quiet: "What's everybody doing today?", calm: "What's everybody doing today?", chaotic: "What's everybody doing today?", warm: "What's everybody doing today?" },
    7: { competitive: "Surviving, same as you.", proud: "Surviving, as usual.", warm: "Surviving, same as you." },
  },
  'nw.n5': { 0: { warm: "We're doing {target} tonight. Will you vote with us?", schemer: "We're doing {target} tonight. Will you vote with us?", blunt: "{target} tonight. With us?", anxious: "We're doing {target} tonight. Will you vote with us, please?" } },
  'nl6.g1': {
    1: { warm: "Remind me why we signed up for this.", ditzy: "Remind me why we signed up for this?", calm: "Remind me why we signed up for this.", dry: "Remind me why we signed up for this." },
    3: { warm: "Right, the money.", ditzy: "Right! The money.", calm: "Right. The money.", dry: "Right, the money." },
    4: { competitive: "And the adventure.", schemer: "And the adventure.", anxious: "And the adventure.", ditzy: "And the adventure!" },
    8: { warm: "We're going to be fine, tired and hungry and gross, but fine.", ditzy: "We're going to be fine! Tired, hungry, gross, and fine.", calm: "We're going to be fine, tired and hungry and gross, but fine.", dry: "We're going to be fine, in the tired, hungry, gross sense of fine." },
  },
};
