// ══════════════════════════════════════════════════════════════════════
// td/story/lines/voices/batch16.js — the voice overhaul, depth pass 5 (held-out casts)
// ══════════════════════════════════════════════════════════════════════
// Gaps taken from seeds 5150, 6060, 7272, 8383, 9494, 1010 (53.8% before). Same meaning per line.

export default {
  'nl4.u4': { 1: { schemer: "You've already walked me through it three times. I'm keeping count." } },
  'nl4.u3': {
    0: { blunt: "I feel good about tonight. Actually good." },
    1: { loud: "That's NEW for you!" },
    2: { blunt: "I know. Usually I'm a mess before a vote, but it's {wrote}, and I'm with the numbers." },
    4: { blunt: "After tonight, I can finally relax." },
    5: { loud: "Don't relax TOO much! It's still this game!" },
    6: { blunt: "Let me have this one." },
  },
  'nl4.u2': {
    0: { calm: "{wrote} is going home tonight, and I'm looking forward to watching it." },
    1: { blunt: "You're really confident." },
    2: { calm: "I'm confident because I counted. {wrote} has nobody." },
    3: { blunt: "Who did you count with?", schemer: "Who exactly did you count with?" },
    4: { calm: "Everybody. I talked to everybody." },
    5: { blunt: "And they all said {wrote}?", schemer: "And they all said {wrote}? In those words?" },
    6: { calm: "They all nodded when I said {wrote}. That's the same thing." },
    7: { blunt: "Is it, though?" },
    8: { calm: "Don't do that. Not right before the vote." },
  },
  'ndp.w4': {
    0: { warm: "Nobody congratulated me, and that hurt more than I expected. I'm the name they all wanted, and now they need a new one.", cruel: "Nobody congratulated me. Good. I'm the name they all wanted, and they'll have to settle for somebody else." },
    1: { warm: "Which means somebody else is in danger tonight because of me. I should find out who, and make sure they're okay." },
  },
  'nl4.a1': {
    1: { schemer: "Honest question. Who do you actually trust here?", tough: "Who do you actually trust here?", loud: "Can I ask you something? Who do you ACTUALLY trust here?" },
    2: { blunt: "You. Maybe only you.", goofy: "Honestly? You, and maybe that crab." },
    3: { loud: "Same! I've watched who talks to who, and NOBODY's looking out for either of us!" },
    4: { blunt: "So let's look out for each other.", goofy: "So let's look out for each other. Like two raccoons." },
    5: { loud: "Officially?!" },
    6: { blunt: "Officially, and it needs a name, so {group}.", goofy: "Officially! And every great team needs a name, so let's call it {group}." },
    7: { loud: "{group}, I love it! You and me, and nobody else unless we both say yes!" },
  },
  'nl4.u1': { 7: { cruel: "For what it's worth, I'm writing {other}. It's the smarter vote, and I'm not here to be loyal to bad ideas." } },
  'nar.l1': {
    2: { competitive: "Like an alliance?" },
    4: { cruel: "I'm in. I assume there's a name." },
    6: { competitive: "So now I'm in {group}. It sounds great, and it's three votes, and I'm going to hold {a} to every word." },
  },
  'nv4.p2': {
    0: { calm: "I'll just say it. {target} and {partner} are running this camp as a two-person team." },
    2: { calm: "Is it? Name one vote they split on." },
    4: { calm: "Exactly. Two votes, one brain. If we don't break it up now, we're all just waiting to be next." },
    6: { calm: "{target}. {target} does the talking." },
    8: { calm: "Then {partner} screams. Screaming isn't a vote." },
  },
  'nv4.p3': {
    1: { blunt: "I've been thinking about {target} and {partner}." },
    3: { blunt: "They are, and that's what makes this awful. One of them has to go tonight." },
    5: { blunt: "Because if they both reach the merge, they're two votes nobody splits, and one of us goes home every time they vote." },
    7: { blunt: "{target} is the one I'd lose to. I hate saying it." },
    9: { blunt: "I'm going to look {partner} in the eye tomorrow and feel sick. I'm doing it anyway." },
  },
  'fp.c2': {
    1: { warm: "I've got it... actually, no, I'd love some help.", calm: "I've got it... actually, no, help.", flirty: "I've got it... actually, no, help me." },
    3: { warm: "Thank you, I'm {b}, by the way! I know we did names, but I wasn't listening.", calm: "Thanks, I'm {b}. I wasn't listening during names.", flirty: "Thanks, I'm {b}, by the way. I wasn't listening during names, but I'm listening now." },
    5: { warm: "Good, then we're even.", calm: "Good. We're even.", flirty: "Good. Then we're even." },
  },
  'nj.p5': {
    1: { cruel: "Are you going to help, or just point?", competitive: "Are you going to help, or just point?", blunt: "Help or stop pointing.", earnest: "Are you going to help, or just point?", schemer: "Are you going to help, or just point?" },
    3: { anxious: "The big picture is that log. It's really heavy.", schemer: "The big picture is that log, and it's heavy.", earnest: "Honestly, the big picture is that log. It's heavy.", food: "The big picture is that log. It's heavy, and I haven't eaten." },
    5: { dry: "Just grab an end, {a}. It won't bite." },
    7: { competitive: "{a} wants to look like the leader without doing the work. I made sure everybody saw that.", blunt: "{a} pointed while we lifted, and everybody saw.", earnest: "{a} wants to look like the leader without doing any of the work, and I made sure everybody saw.", schemer: "{a} wants to look like a leader without lifting anything. I made sure everybody noticed, quietly." },
  },
  'nl.l2': {
    1: { chaotic: "I didn't freeze, I slipped! Possibly on purpose, but mostly a slip!" },
    3: { anxious: "It was kind of a long slip, though." },
  },
  'ndp.s4': {
    0: { warm: "Being the swing vote isn't about tonight. It's about who I hurt, and who I can keep safe." },
    1: { warm: "Whatever I write, somebody leaves tonight feeling saved by me, and somebody feels betrayed, and I hate that part." },
  },
  'nl.w1': { 7: { flirty: "I'm going to sleep for twelve hours. Don't miss me too much." } },
  'fp.x1': {
    1: { flirty: "I was about to, yeah. Were you watching me?", tough: "I was about to.", bossy: "I was about to. I had a system." },
    2: { theatrical: "You've been 'about to' for ten whole minutes!", loud: "You've been about to for TEN MINUTES!" },
    3: { flirty: "And you've been watching me for ten minutes. So." },
    5: { flirty: "I've known {a} for one day. That's plenty.", tough: "One day with {a}. That's enough.", bossy: "I've known {a} one day, and {a} already thinks {a} is in charge. No." },
    6: { loud: "{b} rubbed me the wrong way the SECOND we got here! I'm not saying anything yet, but I noticed!" },
  },
  'nl.w2': {
    2: { earnest: "Let {a} have it. {a} really earned it." },
    6: { cruel: "Corny and safe. I'll take it.", competitive: "Corny and safe. I'll take it." },
  },
  'nv.y6': {
    0: { schemer: "Quick question: {target}, tonight, yes or no?" },
    2: { schemer: "It's a quick answer if it's yes." },
  },
  'nvu.d7': {
    1: { blunt: "Because I walked up to the group by the water and everybody stopped talking.", cruel: "Because I walked up to the group by the water and they all went silent. Subtle." },
    2: { schemer: "Maybe they were talking about something embarrassing.", cruel: "Maybe they were talking about something embarrassing. Like you." },
    3: { blunt: "They were talking about me.", cruel: "They were talking about me. How brave of them." },
    4: { cruel: "So what do we do?" },
    5: { blunt: "We make it {wrote}. I'll talk to every person here if I have to.", cruel: "We make it {wrote}. I'll talk to every single one of them, and I'll enjoy it." },
    6: { schemer: "I'm with you. Let's go.", cruel: "I'm with you. Let's go ruin someone's night." },
    7: { cruel: "Maybe {a} is wrong. I'd still rather be paranoid with {a} than let those people win." },
  },
  'nl4.k1': {
    0: { competitive: "You've been watching everybody all morning." },
    1: { theatrical: "Somebody has to!", calm: "Somebody has to.", blunt: "Somebody has to.", cruel: "Somebody has to.", schemer: "Somebody has to.", warm: "Somebody has to keep an eye on everybody." },
    2: { warm: "Why does it have to be you?", tough: "Why you?", competitive: "Why does it have to be you?", calm: "Why does it have to be you?", nerdy: "Why does it have to be you?" },
    3: { theatrical: "Because if I don't know where everybody is, I imagine where they are, and what I imagine is always a disaster.", calm: "Because if I don't know where everybody is, I start imagining it, and what I imagine is worse.", blunt: "If I don't know where people are, I imagine it. And I imagine the worst.", cruel: "Because if I don't know where everybody is, I assume the worst. I'm usually right.", schemer: "Because if I don't know where everybody is, I start guessing, and my guesses are always worse.", warm: "Because if I don't know where everybody is, I start worrying, and I worry about the worst." },
    4: { tough: "That sounds exhausting." },
    5: { theatrical: "It is! But it's less exhausting than being blindsided.", calm: "It is. It's less exhausting than being blindsided.", blunt: "It is. Blindsides are worse.", cruel: "It is. Being blindsided is worse.", schemer: "It is. But less exhausting than a blindside.", warm: "It is. But it's less exhausting than being blindsided." },
    6: { warm: "You know you can't control all of it, right?", tough: "You can't control all of it.", competitive: "You can't control all of it.", calm: "You know you can't control all of it.", nerdy: "You know you can't control every variable, right?" },
    7: { theatrical: "I know. I simply refuse to believe it.", calm: "I know. I just don't believe it.", blunt: "I know. I don't believe it.", cruel: "I know. I don't believe it.", schemer: "I know. I just don't believe it.", warm: "I know. I just don't believe it." },
    8: { tough: "{a} has the whole camp mapped out. I hope {a} gives {a.ref} a break before {a} snaps." },
  },
  'nl4.v1': {
    2: { loud: "Because every time there's a plan, I find out LAST! Like I don't matter!" },
    4: { loud: "That's EXACTLY the problem! I want to be a threat, and I want them to worry about me!" },
    6: { loud: "I'm being careful! I just want one vote where I'm the reason it went that way!" },
  },
  'nv4.n3': {
    3: { loud: "And that's {target}?" },
    5: { loud: "{target} might cry tomorrow!" },
  },
  'nbl.c5': {
    1: { warm: "Do we have to?", nerdy: "Do we, though?" },
    3: { flirty: "Wow. You could just say my name, you know." },
  },
  'nvt.d3': {
    3: { dry: "Then let's make it somebody else." },
    6: { schemer: "I've got one friend, one name and three hours. That's a start, and starts are what I'm good at." },
  },
  'nc.w3': {
    1: { earnest: "Are you alive?" },
    6: { earnest: "{a} won us that challenge, and I'm so grateful. The bad part is, both teams watched {a} do it." },
  },
  'ny.s1': {
    2: { cruel: "Come on. I'm just curious.", anxious: "Come on, I'm just curious.", calm: "I'm just curious.", proud: "Come on. I'm just curious.", warm: "Come on, I'm just curious!" },
    3: { warm: "Fine. Let's just say some of the {theirs} aren't as close as they look.", theatrical: "Fine. Let's just say the {theirs} are not the happy family they pretend to be.", ditzy: "Fine. Some of the {theirs} aren't, like, as close as they look.", calm: "Fine. Some of the {theirs} aren't as close as they look.", anxious: "Fine, but some of the {theirs} aren't as close as they look." },
    5: { warm: "Don't tell anybody I said that.", theatrical: "Don't tell a soul I said that.", ditzy: "Don't tell anybody I said that, okay?", calm: "Don't tell anybody I said that.", anxious: "Please don't tell anybody I said that." },
    6: { cruel: "Who would I tell?", anxious: "Who would I tell?", calm: "Who would I tell?", proud: "Who would I tell?", warm: "Who would I tell?" },
    7: { cruel: "{b} just told me the {theirs} are cracking. I'll be using that at the merge, and {b} won't like how." },
  },
  'nbl.r2': { 6: { theatrical: "I came back braced to be yelled at, and instead we made a plan. Who are these people? I love them.", nerdy: "I came back expecting blame, and instead we made a plan. That's a much better outcome." } },
  'nv4.n1': {
    1: { nerdy: "So that's five people who'd write {target}." },
    2: { schemer: "And nobody who'd fight hard enough for {target} to cause trouble.", calm: "And nobody who'd fight for {target} hard enough to cause trouble.", dry: "And nobody who'd fight for {target} hard enough to cause trouble. Tragic, but useful.", competitive: "And nobody who'd fight for {target} enough to matter.", flirty: "And nobody who'd fight for {target} hard enough to cause trouble.", theatrical: "And not a single soul who'd fight for {target}." },
    4: { schemer: "Sometimes a shrug is the safest vote you'll ever cast. Nobody's angry, nobody wants revenge, and we're still here tomorrow.", calm: "A shrug can be the safest vote you'll cast. Nobody's angry, nobody's out for revenge, and we're still here.", dry: "A shrug is sometimes the safest vote there is. Nobody's angry, nobody wants revenge, and we all survive.", competitive: "A shrug vote is a safe vote. Nobody's angry, nobody comes after us, and we're still in it.", flirty: "Sometimes a shrug is the safest vote you'll ever cast. Nobody's angry, and we're both still here tomorrow.", theatrical: "Sometimes a shrug is the safest vote of all. No anger, no revenge, and we live to see tomorrow." },
    5: { warm: "I'd rather vote out somebody I'm actually worried about." },
    6: { warm: "I'd rather vote out {alt}, honestly. {alt} worries me.", theatrical: "I'd rather vote out {alt}. {alt} is the real danger.", calm: "I'd rather vote out {alt}. {alt} worries me.", nerdy: "I'd rather vote out {alt}. {alt} is the bigger risk." },
    7: { schemer: "So would I. But the people we're worried about have friends, and tonight's not the night for a war.", calm: "So would I. But the dangerous ones have friends, and tonight isn't the night for a war.", dry: "So would I. But the scary ones have friends, and I'd rather not start a war tonight.", competitive: "So would I, but the dangerous ones have friends. Not tonight.", flirty: "So would I. But they have friends, and I'd rather not start a war tonight.", theatrical: "So would I! But the dangerous ones have friends, and tonight is not the night to start a war." },
    9: { nerdy: "I'm voting for {target} because it's the easy option. I don't love that it's easy. I'm doing it anyway." },
  },
  'nvt.d2': {
    2: { warm: "Good, because I'm nervous. Somebody's getting votes together, and every conversation I walk into stops.", earnest: "Good, because I'm nervous, honestly. Somebody's getting votes together, and every conversation stops when I walk in.", calm: "Good, because I'm nervous. Somebody's getting votes, and conversations stop when I walk in." },
    4: { warm: "It could be, but it isn't. It's me.", earnest: "It could be, but honestly, it isn't. It's me.", calm: "It could be, but it isn't. It's me." },
    6: { warm: "{wrote}. If {wrote} goes, whoever's coming for me loses their best vote.", calm: "{wrote}. If {wrote} goes, whoever's coming for me loses their best vote." },
    7: { earnest: "{wrote}. I just need enough people to see what I see." },
  },
  'nc.w7': {
    1: { warm: "Best part of winning?", anxious: "Best part of winning?", competitive: "Best part of winning?", earnest: "What's the best part of winning?" },
    2: { calm: "Not having to vote?", competitive: "Winning?", anxious: "Not having to vote?", flirty: "Not having to vote? Getting to sit here with you?" },
    3: { warm: "Not having to vote, and nobody whispering in the bushes all afternoon.", anxious: "Not having to vote. And nobody whispering in the bushes all afternoon.", competitive: "Not voting, and no whispering in the bushes.", earnest: "Not having to vote. And nobody whispering in the bushes all afternoon." },
    4: { calm: "Give it a day. They'll be back to whispering tomorrow.", competitive: "Give it a day. They'll be whispering again tomorrow.", anxious: "Give it a day. They'll be whispering again tomorrow.", flirty: "Give it a day. They'll be back to whispering tomorrow." },
    5: { warm: "Can you let me have one night, please?", anxious: "Can I just have one night?", competitive: "Can I have one night?", earnest: "Can you let me have one night?" },
    6: { calm: "One night.", competitive: "One night.", anxious: "One night.", flirty: "One night. It's yours." },
    7: { anxious: "{a} is the reason we're safe tonight. I hope {a} remembers I was cheering, because I'll need that later.", competitive: "{a} won it for us, and I'll remember that. I hope {a} remembers who was cheering loudest." },
  },
  'nm.b4': { 9: { competitive: "I feel bad, I do. But {lastBoot} wasn't going to the end with me, and {a} will have to get over it.", loud: "I feel bad! I DO! But {lastBoot} wasn't going to the end with me, and {a} has to get over it!" } },
  'nth.g1': {
    1: { warm: "Can I ask you something? Why did you write my name?", competitive: "Why did you write my name?", cruel: "So, why did you write my name?", anxious: "Can I ask you something? Why did you write my name?", bossy: "I want to know why you wrote my name." },
    2: { nerdy: "What makes you think I did?" },
    3: { warm: "Because there were hardly any votes on me, and it wasn't hard to work out where they came from.", competitive: "There were barely any votes on me. It wasn't hard to work out.", cruel: "Because there were hardly any votes on me, and I can count.", anxious: "Because there were hardly any votes on me, and I worked it out, and it made me feel sick.", bossy: "There were hardly any votes on me. I worked it out." },
    4: { competitive: "It wasn't about you. It was a numbers thing." },
    5: { warm: "I had your back. From the first day, I had your back.", competitive: "I had your back from day one.", cruel: "I had your back. From the first day.", anxious: "I had your back, from the very first day.", bossy: "I had your back from the first day." },
    7: { competitive: "{b} knew I had {b.posAdj} back and wrote my name anyway. I won't scream about it. I'll beat {b} instead." },
  },
  'nl4.p1': {
    1: { blunt: "You okay?", bossy: "Are you okay? Eat something." },
    3: { blunt: "Yeah. I noticed.", bossy: "Yeah. I noticed you doing that." },
    5: { blunt: "It's not stupid. You two were close.", bossy: "It's not stupid. You were close." },
    7: { blunt: "You sit with me.", bossy: "You sit with me. That's decided." },
    8: { nerdy: "I came here to win, and I didn't think I'd need people. Turns out I do, and that's the scariest thing I've learned here." },
  },
  'nps.c3': {
    1: { flirty: "I'm relaxing right now.", schemer: "I'm relaxing.", anxious: "I am relaxing. Right now.", calm: "I'm relaxing right now.", blunt: "I'm relaxing." },
    2: { anxious: "You're counting people." },
    3: { flirty: "I can relax and count at the same time.", schemer: "I can relax and count at the same time.", anxious: "I can relax and count at the same time! Kind of.", calm: "I can do both.", blunt: "I can do both." },
    5: { flirty: "{b} is the only one who sees how hard I'm working. I like that {b} notices.", schemer: "{b} is the only person who sees how hard I'm working. That makes {b} either my best ally or my biggest risk.", anxious: "{b} is the only one who sees how hard I'm working, and that makes me nervous and grateful at the same time.", calm: "{b} sees how hard I'm working. I'm still deciding what to do with that.", blunt: "{b} sees how hard I work, which is useful or dangerous. I'm not sure yet." },
  },
  'nk.ev1': {
    0: { earnest: "An extra vote. One that nobody is counting on but me, and I want to use it well." },
    1: { tough: "At the right vote, one name decides everything, and I get to write it twice.", earnest: "At the right vote, one name decides everything, and I'm going to make sure I write it for the right reason.", nerdy: "At the right vote, one name changes the outcome, and I'll write it twice." },
  },
  'nv4.p5': { 7: { warm: "Watching that scared me. I'm on the other half of that drawing, and I'd really like to stay there with {a}." } },
  'nm.b5': {
    1: { calm: "Mind if I fish here?", competitive: "Mind if I fish here?" },
    3: { calm: "You're taking it pretty well. {lastBoot}, I mean.", competitive: "You're taking it well. {lastBoot}, I mean." },
    5: { calm: "What's that supposed to mean?", earnest: "What's that supposed to mean?", emotional: "What's that supposed to mean?", competitive: "What's that supposed to mean?" },
    7: { calm: "I don't know what you want me to say.", earnest: "I honestly don't know what you want me to say.", emotional: "I don't know what you want me to say!", competitive: "I don't know what you want me to say." },
    10: { calm: "{a} is far too calm about this, and that makes me nervous.", competitive: "{a} is too calm about this. I need to watch {a}." },
  },
  'nv4.g2': {
    0: { blunt: "You've been very calm about {target} lately." },
    2: { bossy: "Suspiciously calm. After everything." },
    4: { bossy: "So tonight's the night." },
    6: { bossy: "{a} has been smiling at {target} for days, and it wasn't forgiveness, it was patience. I'd like to be told these things." },
  },
  'nvt.f3': {
    0: { theatrical: "Okay, so after tonight, we should start planning who's next.", competitive: "After tonight, we start on who's next.", flirty: "So after tonight, you and I should plan who's next.", emotional: "After tonight, can we plan who's next together? I want to." },
    1: { warm: "Let's just get through tonight first, okay?", schemer: "Let's just get through tonight first.", calm: "Let's get through tonight first.", blunt: "Tonight first.", nerdy: "Let's just get through tonight first." },
    2: { blunt: "Tonight's easy. It's {wrote}.", competitive: "Tonight's easy. It's {wrote}.", flirty: "Tonight's easy. It's {wrote}.", cruel: "Tonight's easy. It's {wrote}.", emotional: "Tonight's easy, it's {wrote}." },
    3: { warm: "Nothing's easy out here.", schemer: "Nothing's easy out here.", calm: "Nothing's easy out here.", blunt: "Nothing's easy.", nerdy: "Nothing's easy out here." },
    4: { theatrical: "Wow, optimistic! Who are you, and what have you done with my friend?", blunt: "Wow. What's wrong with you?", competitive: "Wow. Optimistic.", flirty: "Wow, optimistic. Who are you, and where's my friend?", cruel: "Wow. Optimistic.", emotional: "Wow, are you okay? That's not like you." },
    5: { warm: "Sorry. I'm just tired.", schemer: "Sorry. I'm just tired.", calm: "Sorry. I'm just tired.", blunt: "Sorry. I'm tired.", nerdy: "Sorry. I'm just tired." },
  },
  'nm.b9': {
    1: { calm: "...I did. I'm sorry.", anxious: "...I did. I'm so sorry.", dry: "...I did. I'm sorry.", schemer: "...I did. I'm sorry.", warm: "...I did. I'm really sorry.", earnest: "...I did, and I'm sorry. I won't lie to you." },
    3: { calm: "I know you two were close.", anxious: "I know you two were close.", dry: "I know you two were close.", schemer: "I know you two were close.", warm: "I know you two were so close.", earnest: "I know you two were close." },
    5: { calm: "It wasn't about you. I promise.", anxious: "It wasn't about you, I promise.", dry: "It wasn't about you. I promise.", schemer: "It wasn't about you.", warm: "It wasn't about you, I promise.", earnest: "It honestly wasn't about you." },
    8: { calm: "I could have lied to {a}, and maybe I should have. The way {a} looked at me was worse than a fight.", anxious: "I could have lied to {a}. The way {a} looked at me made me feel sick.", dry: "I could have lied. The look on {a}'s face was worse than a fight.", schemer: "I could have lied to {a}. I chose honesty, and that look on {a}'s face was the price.", warm: "I could have lied to {a}, but I couldn't do that. The way {a} looked at me broke my heart.", earnest: "I could have lied to {a}, and I didn't. The way {a} looked at me was worse than any fight." },
  },
  'nw.n4': {
    0: { calm: "Are you with us on {target}?", blunt: "You with us on {target}?" },
    1: { flirty: "No. Sorry." },
    2: { calm: "Can I ask why?", blunt: "Why?" },
    3: { flirty: "Because {target} isn't the one I'm worried about. I'm not wasting my vote." },
    4: { calm: "Then who are you worried about?", blunt: "Then who?" },
    5: { flirty: "That's my business tonight." },
    6: { calm: "{b} wouldn't give me the name. If a few more people do that, tonight falls apart.", blunt: "{b} said no. A few more of those and tonight falls apart." },
  },
  'nm.b7': {
    1: { warm: "Wow, okay. So that's how it is now.", earnest: "Wow, okay. So that's how it is now.", anxious: "Wow, okay, so that's how it is now.", competitive: "So that's how it is now." },
    2: { dry: "It's not like anything. Sit down.", anxious: "It's not like anything, I promise. Sit down.", earnest: "It's not like anything. Sit down.", cruel: "It's not like anything. Sit down." },
    3: { warm: "{lastBoot} was in every plan I had, and nobody even gave me a heads-up.", earnest: "{lastBoot} was in every plan I had, every single one, and nobody gave me a heads-up.", anxious: "{lastBoot} was in every plan I had, and nobody warned me.", competitive: "{lastBoot} was in every plan I had, and nobody warned me." },
    4: { dry: "Nobody gave anybody a heads-up. That's why it worked.", anxious: "Nobody gave anybody a heads-up. That's why it worked.", earnest: "Nobody warned anybody. That's why it worked.", cruel: "Nobody warned anybody. That's why it worked.", warm: "Nobody warned anybody, that's why it worked. I'm sorry.", flirty: "Nobody warned anybody. That's why it worked." },
    5: { warm: "If it helps, it wasn't about you.", emotional: "If it helps, it wasn't about you.", dry: "If it helps, it wasn't about you.", schemer: "If it helps, it wasn't about you.", goofy: "If it helps, it wasn't about you.", bossy: "It wasn't about you." },
    6: { warm: "How would you know who it was about?", earnest: "How would you know who it was about?", anxious: "How would you know who it was about?", competitive: "How would you know?" },
    7: { warm: "I'm just saying.", emotional: "I'm just saying.", dry: "I'm just saying.", schemer: "I'm just saying.", goofy: "I'm just saying.", bossy: "I'm just saying." },
    8: { warm: "You're saying a lot for somebody who wasn't involved.", earnest: "You're saying a lot for somebody who wasn't involved.", anxious: "You're saying a lot for somebody who wasn't involved.", competitive: "You're saying a lot for somebody who wasn't involved." },
    9: { warm: "I don't believe last night just happened. Somebody organised it, and I hate that I keep looking at {b}.", earnest: "I don't believe last night just happened. Somebody organised it, and every time I look at {b}, I wonder.", anxious: "Last night didn't just happen. Somebody organised it, and every time I look at {b}, my stomach drops.", competitive: "Somebody organised last night, and I think {b} knows who. I'm going to find out." },
  },
  'nth.g2': {
    0: { emotional: "Morning! Do you want some of this?", ditzy: "Morning! Want some?", warm: "Morning! Do you want some of this?", goofy: "Morning! It's terrible, want some?", bossy: "Morning. Have some of this." },
    1: { warm: "Are you going to pretend last night didn't happen?", anxious: "Are you just going to pretend last night didn't happen?", earnest: "Are you going to pretend last night didn't happen?", calm: "Are you going to pretend last night didn't happen?", nerdy: "Are you going to pretend last night didn't happen?" },
    2: { emotional: "What about last night?", ditzy: "What about last night?", warm: "What about last night?", goofy: "What about last night?", bossy: "What about it?" },
    3: { warm: "Your vote was on me. I can count, {b}.", anxious: "Your vote was on me. I can count, {b}.", earnest: "Your vote was on me, {b}. I can count.", calm: "Your vote was on me. I can count.", nerdy: "Your vote was on me. The numbers only work one way, {b}." },
    5: { emotional: "I didn't think it would matter! You were never going home!", ditzy: "I didn't think it mattered? You were never going home.", warm: "I didn't think it would matter. You were never going home, I promise.", goofy: "I didn't think it would matter. You were never going home.", bossy: "It didn't matter. You were never going home." },
    6: { warm: "That's not the point, and you know it's not the point.", anxious: "That's not the point.", earnest: "That's not the point, and you know it.", calm: "That's not the point.", nerdy: "That's not the point, and you know it." },
    7: { emotional: "I wrote {a}'s name to stay with the group, and I thought {a} would never find out, and now I feel awful.", ditzy: "I wrote {a}'s name because everybody did, and I didn't think {a} would notice. {a} noticed.", warm: "I wrote {a}'s name to stay with the group, and I never wanted {a} to find out. I feel terrible.", goofy: "I wrote {a}'s name to stay with the group, and I thought {a} would never find out. Turns out {a} can count.", bossy: "I wrote {a}'s name to stay with the group, and {a} found out. I'll deal with it." },
  },
  'nvt.f1': {
    1: { schemer: "Isn't this nice? For once, I'm not worried about anything." },
    2: { dry: "That's great.", blunt: "Great." },
    3: { loud: "It's {wrote} tonight, everybody said so! You're on {wrote}, right?", schemer: "It's {wrote} tonight. You're on {wrote}, right?" },
  },
  'nps.r3': {
    0: { emotional: "Somebody I've been looking after wrote my name last night, and it broke my heart a little." },
    1: { anxious: "I'm not going to stop helping people. I'm just going to watch who helps back, because I'm scared now." },
  },
  'nvq.p1': {
    4: { schemer: "It's kind of cute, though." },
    8: { schemer: "{partner} is going to be devastated." },
  },
  'ndp.w1': { 0: { blunt: "I won. When I turned around, nobody was clapping." } },
  'fd.c2': {
    2: { warm: "We did our names on the dock!", chaotic: "We said our names on the dock! I said mine twice!", loud: "We said our names on the DOCK!", theatrical: "We said our names on the dock, darling." },
    3: { tough: "Nobody was listening. I'm {a}.", loud: "And NOBODY was listening! I'm {a}!", competitive: "Nobody was listening. I'm {a}.", cruel: "And nobody was listening. I'm {a}.", warm: "Yeah, and nobody was listening! I'm {a}." },
    4: { chaotic: "{c}! Hi, hello!" },
    5: { warm: "{d}. Hi, everybody!", schemer: "{d}." },
    6: { cruel: "{b}. And for the record, I'm not here to make friends.", loud: "{b}! And for the RECORD, I'm not here to make friends!", competitive: "{b}. I'm not here to make friends, I'm here to win." },
    7: { loud: "First impressions? {d} is going to be funny, and {b} is going to be a PROBLEM.", competitive: "First impressions? {d} is going to be funny, and {b} is going to be competition." },
  },
  'fp.x2': {
    2: { tough: "Is your name on it?" },
    7: { warm: "Day one and {a} already took my {bed}. I'm trying not to take it personally.", food: "Day one and {a} took my {bed}. I'm going to remember that, right after I find something to eat." },
  },
  'ncx.d1': { 2: { goofy: "Who told you that? Was it the crab?" } },
  'nly.x2': {
    0: { earnest: "How's your team doing? Oh, wait, I already know.", warm: "How's your team doing? Oh, I already know, sorry.", calm: "How's your team doing? Oh, wait, I already know." },
    1: { cruel: "Funny. Is that what you practised in the mirror this morning?", warm: "Funny. Did you practise that this morning?", competitive: "Funny. Practised that in the mirror?", nerdy: "Funny. Did you rehearse that?" },
    2: { earnest: "I don't need to practise. I just tell the truth.", warm: "I don't need to practise. I just tell the truth.", calm: "I don't need to practise. I tell the truth.", food: "I don't need to practise. I just tell the truth, over breakfast." },
    3: { cruel: "The truth is we're going to beat you today, and you'll have to walk past me after.", warm: "The truth is we're going to beat you today. No hard feelings.", competitive: "The truth is we beat you today, and you walk past me after.", nerdy: "The truth is we're going to beat you today, and you'll have to walk past me afterwards." },
    4: { earnest: "{a} talks a big game. One day {a} has to back it up, and I'll be right there to see it.", warm: "{a} talks a big game, and I kind of like it. I'll still enjoy beating {a}.", calm: "{a} talks a big game, and one day {a} has to back it up. I'll be watching." },
  },
  'nk.ao1': {
    2: { schemer: "Depends what it is.", ditzy: "Depends what it is?", dry: "Depends what it is." },
    3: { chaotic: "Are you happy with where you are, with your people? Because I'm not, anyway!" },
    4: { schemer: "Why?", ditzy: "Why?", dry: "Why?" },
    5: { chaotic: "Because I'm not happy with mine! They treat me like the spare, and I don't think you're anybody's first pick either." },
    6: { schemer: "Wow. Thanks.", ditzy: "Oh. Thanks?", dry: "Wow. Thanks." },
    7: { chaotic: "I'm not being mean! We're in the same spot! Two people in the same spot can do a lot!" },
    9: { chaotic: "I'm not jumping yet. I'm just leaning over the edge to see how far down it is.", proud: "I'm not jumping yet. I'm choosing where to land.", bossy: "I'm not jumping yet. I'm making a plan for when I do." },
  },
  'nps.b4': { 0: { calm: "Back home I organise everything. Here nobody needs me to, and I'm still working out what to do with that." } },
  'nv4.s1': {
    1: { schemer: "Don't say it. I know you're thinking it.", calm: "Don't say it. I know you're thinking it.", proud: "Don't say it. I know you're thinking it.", nerdy: "Don't say it. I know what you're thinking.", theatrical: "Don't say it! I know you're thinking it." },
    3: { schemer: "That if {target} hadn't fallen apart, we'd be eating tonight instead of voting.", calm: "That if {target} hadn't fallen apart out there, we'd be eating instead of voting.", proud: "That if {target} hadn't fallen apart, we'd be eating tonight.", nerdy: "That if {target} hadn't fallen apart, we'd be eating tonight instead of voting.", theatrical: "That if {target} hadn't fallen apart, we'd be feasting instead of voting!" },
    5: { schemer: "Everybody's thinking it. {target} is lovely, and {target} is also why we keep losing.", calm: "Everybody's thinking it. {target} is lovely, and also the reason we keep losing.", proud: "Everybody's thinking it. {target} is nice, and {target} is why we lose.", nerdy: "Everybody's thinking it. {target} is a lovely person, and the reason we keep losing.", theatrical: "Everybody's thinking it! {target} is lovely, and {target} is the reason we keep losing." },
    6: { theatrical: "So that's the vote.", warm: "So that's the vote.", calm: "So that's the vote." },
    7: { schemer: "That's the vote. We need to start winning, and this is how.", calm: "That's the vote. We start winning, and this is how.", proud: "That's the vote. We start winning now.", nerdy: "That's the vote. This is how we start winning.", theatrical: "That's the vote! This is how we start winning!" },
  },
  'ny.m4': {
    1: { earnest: "...and then I said, if you want the fire bigger, get the wood yourself.", competitive: "...so I said, if you want the fire bigger, get the wood yourself.", dry: "...and then I said, if you want the fire bigger, get the wood yourself. Revolutionary." },
    2: { anxious: "Who was that, again?" },
    3: { earnest: "Doesn't matter.", competitive: "Doesn't matter.", dry: "Doesn't matter." },
    5: { earnest: "It doesn't.", competitive: "It doesn't.", dry: "It doesn't." },
  },
  'ns.f3': {
    1: { competitive: "Are you going to help or just stand there?", flirty: "Are you going to help, or just stand there looking at me?" },
    3: { warm: "You're staring.", competitive: "You're staring.", flirty: "You're staring. Not that I mind." },
    5: { warm: "Oh my gosh. Pick up an axe.", flirty: "Oh my gosh. Pick up an axe, charmer." },
    7: { flirty: "{a} is being so obvious, and it's working. I'm not even pretending it isn't." },
  },
  'nj.p3': {
    1: { schemer: "Sounds good. What do you need?", warm: "Sounds good! What do you need?", blunt: "Fine. What do you need?", theatrical: "Sounds marvellous. What do you need?", loud: "Sounds GOOD! What do you need?" },
    3: { calm: "Why do you get to decide?", blunt: "Why do you decide?" },
    5: { cruel: "...Fine. Fire's fine.", calm: "...Fine. Fire's fine.", blunt: "Fine. Fire.", theatrical: "...Fine. I'll take the fire.", bossy: "...Fine, fire, but my way." },
    6: { theatrical: "Water it is!", blunt: "Water.", anxious: "Water it is, I guess.", calm: "Water it is.", competitive: "Water it is." },
    8: { calm: "{a} is so nice about it that nobody notices {a} is running the camp. I notice.", theatrical: "{a} runs the entire camp so sweetly that nobody notices. I notice everything." },
  },
  'nbl.r1': {
    1: { cruel: "Go on, say it. I know you want to." },
    2: { calm: "Not this time." },
    3: { cruel: "Really?" },
    4: { calm: "Last time we blamed somebody, we lost again anyway. So maybe it's all of us." },
    6: { calm: "Don't get used to it." },
  },
  'nw.y5': {
    1: { dry: "Want help? I'm offering, which is rare.", competitive: "Want help?", tough: "Want help?", loud: "Want some help?!" },
    2: { earnest: "Always. What's the catch?" },
    3: { dry: "No catch. Well, a small catch: {target}, tonight.", competitive: "Small catch: {target}, tonight.", tough: "One catch. {target}, tonight.", loud: "No catch! Well, a small catch, {target}, tonight!" },
    4: { earnest: "{target}? Why?", theatrical: "{target}? Why?", calm: "{target}? Why?", proud: "{target}? Why?" },
    5: { dry: "Because it's that or one of us, and I'd rather it wasn't one of us.", competitive: "Because it's that or one of us.", tough: "Because it's {target} or it's one of us.", loud: "Because it's that or one of US! And I'd like it NOT to be one of us!" },
  },
};
