// ══════════════════════════════════════════════════════════════════════
// td/story/lines/voices/batch19.js — the voice overhaul, pooled pass 2
// ══════════════════════════════════════════════════════════════════════
// Ranked across twelve more fresh seasons (seeds 1111..3636, 65.8% before): the lines that lost
// the most speakers' voices, filled with the voices most often missing on each.

export default {
  'npl.o3': {
    0: { nerdy: "You've been staring at me for about ten minutes. Just say it.", theatrical: "You've been staring at me for ten whole minutes, darling. Just say it.", warm: "You've been staring at me for ten minutes. You can just say it, you know.", dry: "You've been staring at me for ten minutes, and it's getting awkward, so just say it." },
    1: { calm: "Fine, but not here. Over there.", blunt: "Not here. Over there.", theatrical: "Fine, but not here. Somewhere more private.", dry: "Fine, but not here. Over there, where the trees can't hear.", nerdy: "Fine, but not here. Over there.", warm: "Okay, but not here. Over there." },
  },
  'nd.dp1': {
    2: { loud: "You're telling everybody different things, and people talk! They compare notes!", ditzy: "You're telling everybody different stuff, and people talk, you know? They compare notes.", warm: "You're telling everybody different things, and people talk. I'm worried for you.", earnest: "You're telling everybody different things, honestly, and people compare notes.", schemer: "You're telling everybody different things. People compare notes.", anxious: "You're telling everybody different things, and people talk, and it scares me.", competitive: "You're telling everybody different things. People compare notes." },
    4: { ditzy: "You're keeping everyone confused, even the people on your side.", earnest: "You're keeping everybody confused, honestly. Even your own side.", schemer: "You're confusing everyone, even your own side.", anxious: "You're keeping everyone confused, including the people on your side.", warm: "You're confusing everyone, even the people who like you.", theatrical: "You're confusing everybody, even your own allies!", calm: "You're keeping everyone confused, including your own side.", bossy: "You're confusing everyone, including your own side. Stop.", cruel: "You're keeping everyone confused, including the idiots on your side." },
    5: { warm: "If they're confused, they're not voting for me.", loud: "If they're CONFUSED, they're not voting for me!", quiet: "Confused people don't vote for me.", calm: "If they're confused, they're not voting for me." },
    6: { ditzy: "Or they're voting for you because they don't know where you are?", earnest: "Or they're voting for you because they don't know where you are.", schemer: "Or they vote for you because they can't place you.", anxious: "Or they're voting for you because they don't know where you are.", bossy: "Or they vote for you because nobody knows where you stand." },
  },
  'nth.g5': {
    0: { warm: "Hey. About that vote.", calm: "Hey. About that vote.", ditzy: "Hey, so, about that vote.", earnest: "Hey. I wanted to talk about that vote.", loud: "Hey! About that vote.", flirty: "Hey, you. About that vote.", food: "Hey, about that vote. Do you want half my rice?" },
    1: { calm: "I'm sorry. I've said it before, but I really am.", loud: "I'm SORRY. I've said it before, but I really am!", earnest: "I'm sorry. I've said it before, and I'll keep saying it.", flirty: "I'm sorry. I've said it before, but I really mean it.", warm: "I'm so sorry. I've said it before, but I really am.", competitive: "I'm sorry. I've said it before, and I mean it.", schemer: "I'm sorry. I've said it before, but I mean it.", ditzy: "I'm sorry! I know I said it before, but I really am.", anxious: "I'm so sorry. I've said it before, but I really, really am." },
    2: { warm: "I know, and I get it now. I've had to write names I didn't want to write too.", calm: "I know, and I get it now. I've written names I didn't want to write.", ditzy: "I know. I get it now, because I've had to write names I didn't want to.", earnest: "I know, and I understand now. I've had to write names I didn't want to write too.", loud: "I know, and I get it now! I've had to write names I didn't want to write either!", flirty: "I know, and I get it now. I've had to write names I didn't want to.", food: "I know, and I get it now. I've had to write names I didn't want to write too." },
    3: { calm: "So we're okay?", loud: "So we're OKAY?", earnest: "So we're okay?", flirty: "So we're okay?", warm: "So we're okay?", competitive: "We're okay?", schemer: "So we're okay?", ditzy: "So we're okay?", anxious: "So we're okay? Really?" },
    4: { warm: "We're okay. Just don't do it again.", calm: "We're okay. Just don't do it again.", ditzy: "We're okay! Just don't do it again.", earnest: "We're okay. Just please don't do it again.", loud: "We're OKAY. Just don't do it again!", flirty: "We're okay. Just don't do it again.", food: "We're okay. Just don't do it again." },
    5: { calm: "Deal.", loud: "Deal!", earnest: "Deal.", warm: "Deal.", competitive: "Deal.", schemer: "Deal.", ditzy: "Deal!", anxious: "Deal." },
    6: { warm: "I was angry at {b} for a whole week. Then I had to write the name of somebody I liked, and suddenly I understood.", calm: "I spent a week angry at {b}. Then I wrote the name of somebody I liked, and it wasn't simple anymore.", ditzy: "I was mad at {b} for a whole week, and then I had to vote for somebody I liked, and it got complicated.", earnest: "I was angry at {b} for a week. Then I had to write a name I didn't want to, and now I get it.", loud: "I was ANGRY at {b} for a whole week! Then I had to write somebody's name I liked, and it wasn't so simple!" },
  },
  'nly.x1': {
    3: { loud: "ENJOY it. It won't last!", theatrical: "Enjoy it, darling. It won't last.", bossy: "Enjoy it. It won't last.", blunt: "Enjoy it. Won't last.", nerdy: "Enjoy it. It won't last.", schemer: "Enjoy it. It won't last.", cruel: "Enjoy it. It won't last." },
    4: { warm: "That's what you said last time.", earnest: "That's what you said last time.", theatrical: "That's what you said last time.", blunt: "You said that last time.", food: "That's what you said last time.", dry: "That's what you said last time." },
  },
  'ne.h4': {
    1: { schemer: "Why didn't you?", food: "Why didn't you?", anxious: "Why didn't you?", loud: "Why DIDN'T you?", warm: "Why didn't you?", nerdy: "Why didn't you?", theatrical: "Why didn't you?", calm: "Why didn't you?" },
    3: { food: "You're not the problem.", schemer: "You're not the problem.", anxious: "You're not the problem.", nerdy: "You're not the problem.", theatrical: "You're not the problem, darling.", calm: "You're not the problem." },
  },
  'nm.n2': {
    1: { warm: "Not really.", nerdy: "Not really.", theatrical: "Not particularly.", proud: "Not really.", loud: "Not REALLY.", anxious: "Not really." },
    3: { competitive: "I don't know. Maybe?", warm: "I don't know. Maybe?", schemer: "I don't know. Maybe.", blunt: "Maybe.", flirty: "I don't know. Maybe?", quiet: "Maybe.", ditzy: "I don't know. Maybe?" },
    4: { theatrical: "Fine.", food: "Fine.", warm: "Fine.", anxious: "Fine.", ditzy: "Fine!", earnest: "Fine." },
    6: { theatrical: "Okay. Who's on firewood?", food: "Okay, who's on firewood, and who's on breakfast?", warm: "Okay. Who's on firewood?", anxious: "Okay. Who's on firewood?", ditzy: "Okay! Who's on firewood?", earnest: "Okay. Who's on firewood?" },
  },
  'nd.ft2': {
    1: { warm: "Okay. That's fine.", earnest: "Okay. That's fine.", calm: "Okay. That's fine.", competitive: "Fine.", nerdy: "Okay. That's fine.", ditzy: "Okay! That's fine.", dry: "Okay. That's fine.", loud: "Okay! That's FINE." },
    2: { food: "But I'm not going to fight you in front of everyone, because that's what you want.", earnest: "But I'm not going to fight you in front of everyone, because that's what you want.", competitive: "I won't fight you in front of everyone. That's what you want.", nerdy: "But I won't fight you in public, because that's exactly what you want.", warm: "But I'm not going to fight you in front of everyone." },
    3: { warm: "What I want is for you to stop acting like you're in charge.", earnest: "What I want is for you to stop acting like you're in charge.", calm: "What I want is for you to stop acting like you're in charge.", competitive: "I want you to stop acting like you're in charge.", nerdy: "What I want is for you to stop acting as if you're in charge.", ditzy: "What I want is for you to stop acting like you're the boss.", dry: "What I want is for you to stop acting like you're in charge.", loud: "What I WANT is for you to stop acting like you're in charge!" },
    4: { food: "I'm not in charge. I'm just better at this than you.", loud: "I'm not IN CHARGE. I'm just better at this than you!", nerdy: "I'm not in charge. I'm just better at this than you." },
    5: { earnest: "Wow.", competitive: "Wow.", nerdy: "Wow.", dry: "Wow.", warm: "Wow." },
  },
  'ny.ls1': {
    1: { calm: "Wait. Since when can you do that?", theatrical: "Wait, since when can you do THAT?", quiet: "Since when can you do that?", earnest: "Wait, since when can you do that?" },
    4: { warm: "You didn't ask me anything for days.", ditzy: "You didn't ask me anything for days!", food: "You didn't ask me anything for days.", competitive: "You didn't ask me anything for days.", quiet: "Nobody asked me anything for days.", cruel: "You didn't ask me anything for days.", calm: "You didn't ask me anything for days." },
  },
  'nk.sc4': {
    1: { quiet: "What is it?", anxious: "What is it?", loud: "What IS it?", flirty: "What is it?", earnest: "What is it?", warm: "What is it?", theatrical: "What is it?" },
    3: { quiet: "Who said I was going to vote for you?", anxious: "Who said I was going to vote for you?", loud: "Who SAID I was going to vote for you?", flirty: "Who said I was going to vote for you?", earnest: "Who said I was going to vote for you?", warm: "Who said I was going to vote for you?", theatrical: "Who said I was going to vote for you?" },
  },
  'nk.cc1': {
    1: { theatrical: "Here we go.", competitive: "Here we go.", earnest: "Here we go.", bossy: "Here we go.", loud: "Here we GO.", warm: "Here we go.", proud: "Here we go." },
    5: { warm: "Maybe that was a silly thing to say out loud. Now everyone knows I run votes. I just couldn't let {b} have it.", blunt: "Maybe that was dumb to say out loud. Now everyone knows I run votes. I'm not letting {b} have it.", theatrical: "Perhaps that was foolish to declare. Now everyone knows I run votes. But {b} doesn't get my moment.", calm: "Maybe that was a dumb thing to say out loud. Now everyone knows I run votes. I still wasn't letting {b} have it." },
  },
  'no.b1': {
    1: { warm: "Okay, nobody move. This is perfect.", calm: "Okay, nobody move. This is perfect.", schemer: "Okay, nobody move. This is perfect.", emotional: "Okay, nobody move. This is perfect.", tough: "Nobody move. This is perfect.", blunt: "Nobody move." },
    3: { loud: "That's what makes it PERFECT!", warm: "That's what makes it perfect.", earnest: "That's what makes it perfect.", bossy: "That's what makes it perfect.", theatrical: "That's what makes it perfect!" },
    4: { loud: "Can somebody pass the water? WITHOUT moving?", dry: "Can somebody pass the water? Without moving?", quiet: "Water? Without moving?", emotional: "Can somebody pass the water? Without moving?", warm: "Can somebody pass the water? Without moving?" },
    6: { loud: "Then I'll die of thirst! Happily!", dry: "Then I'll die of thirst, happily.", quiet: "Then I'll die happy.", emotional: "Then I'll die of thirst. Happily.", warm: "Then I'll die of thirst, happily." },
    7: { theatrical: "I could stay like this all day.", quiet: "I could stay like this.", earnest: "I could stay like this all day.", emotional: "I could stay like this all day.", competitive: "I could stay like this all day.", ditzy: "I could stay like this all day!" },
  },
  'ny.m3': {
    1: { emotional: "We are not doing this.", loud: "We are NOT doing this.", cruel: "We are not doing this.", competitive: "We're not doing this.", theatrical: "We are not doing this.", schemer: "We're not doing this." },
    2: { loud: "Today's is the WORST! Easily!", warm: "Today's is the worst. Easily.", ditzy: "Today's is the worst!", bossy: "Today's is the worst. Easily.", dry: "Today's is the worst. Easily." },
    4: { emotional: "It did not move.", loud: "It did NOT move!", cruel: "It did not move.", competitive: "It did not move.", dry: "It did not move.", theatrical: "It most certainly did not move.", schemer: "It did not move.", anxious: "It did not move. Did it?" },
  },
  'nvr.s2': {
    2: { anxious: "Rough is one word for it.", food: "Rough is one word for it.", schemer: "Rough is one word for it.", theatrical: "Rough is one word for it. Catastrophic is another.", warm: "Rough is one word for it.", competitive: "Rough is one word for it." },
    3: { loud: "You're thinking about {target}.", food: "You're thinking about {target}.", warm: "You're thinking about {target}.", theatrical: "You're thinking about {target}.", dry: "You're thinking about {target}.", earnest: "You're thinking about {target}.", proud: "You're thinking about {target}.", ditzy: "You're thinking about {target}?" },
    4: { anxious: "Everybody is thinking about {target}. I'm just the only one saying it out loud.", food: "Everybody's thinking about {target}. I'm just the one saying it.", schemer: "Everybody is thinking about {target}. I'm just the only one saying it.", theatrical: "Everybody is thinking about {target}! I'm merely the one brave enough to say it.", warm: "Everybody's thinking about {target}. I'm just the only one saying it, and I hate it.", competitive: "Everyone's thinking about {target}. I'm just saying it." },
    6: { anxious: "We don't have one more chance to give. If we lose again, it's one of us.", food: "We don't have another chance to give. If we lose again, it's one of us.", schemer: "We don't have another chance. If we lose again, it's one of us.", theatrical: "We don't have one more chance to give! Lose again, and it's one of us.", warm: "We don't have another chance to give. If we lose again, it's one of us, and I can't let that happen.", competitive: "No more chances. If we lose again, it's one of us." },
    7: { loud: "Yeah. I KNOW.", food: "Yeah. I know.", warm: "Yeah. I know.", theatrical: "Yes. I know.", dry: "Yeah. I know.", earnest: "Yeah. I know.", proud: "I know.", ditzy: "Yeah, I know." },
  },
  'nk.bd2': {
    0: { warm: "I'm making a list of who I think voted for me.", loud: "I'm making a LIST of who I think voted for me!", anxious: "I'm making a list of who I think voted for me.", dry: "I'm making a list of who I think voted for me, and it's mostly everyone.", calm: "I'm making a list of who I think voted for me." },
    2: { warm: "Want to help? You know these people better than me.", earnest: "Will you help? You know these people better than me.", loud: "Want to HELP? You know these people better!", anxious: "Will you help? You know these people better than I do.", dry: "Want to help? You know these people better than me, unfortunately.", calm: "Want to help? You know these people better than me." },
    3: { quiet: "Sure. Who's on it?", warm: "Sure. Who's on it?", calm: "Sure. Who's on it?", loud: "Sure! Who's on it?", earnest: "Of course. Who's on it?", anxious: "Sure. Who's on it?" },
  },
  'ndp.s1': { 1: { earnest: "The other part of me keeps asking what happens when the people I said no to find out it was me.", loud: "The other part of me keeps asking what happens when they work out it was ME!", dry: "The other part of me keeps asking what happens when the people I turned down work it out. Nothing good, probably.", nerdy: "The other part of me keeps calculating what happens when the people I said no to work it out.", ditzy: "The other part of me keeps worrying about when the people I said no to find out.", proud: "The other part of me knows the people I turned down will work it out. Let them." } },
  'nd.dp2': {
    2: { loud: "{sank} had the WORST day! That's how this works before the merge!", warm: "{sank} had the worst day, and I'm sorry, but that's how this works before the merge.", competitive: "{sank} had the worst day. That's how it works before the merge.", anxious: "{sank} had the worst day. That's how this works before the merge.", flirty: "{sank} had the worst day. That's how this works before the merge.", food: "{sank} had the worst day. That's how this works before the merge.", schemer: "{sank} had the worst day. That's how this works before the merge." },
    4: { loud: "I'd throw it away to win the NEXT challenge!", warm: "I'd throw it away to win the next challenge, and I hate saying it.", theatrical: "I'd throw it away to win the next challenge, yes.", proud: "I'd throw it away to win the next challenge.", nerdy: "I'd throw it away to win the next challenge.", food: "I'd throw it away to win the next challenge.", ditzy: "I'd throw it away to win the next one!" },
  },
  'nly.m1': {
    1: { theatrical: "Okay. Walk me through it.", quiet: "Tell me.", earnest: "Okay. Walk me through it.", calm: "Okay. Walk me through it.", loud: "Okay! Walk me through it!" },
    2: { calm: "I said too much to the wrong person, and now everybody knows I'm worried.", competitive: "I said too much to the wrong person. Now everybody knows I'm worried.", warm: "I said too much to the wrong person, and now everybody knows I'm worried.", blunt: "I said too much to the wrong person. Everyone knows I'm worried.", bossy: "I said too much to the wrong person, and now everybody knows I'm worried.", loud: "I said too much to the WRONG person, and now everybody knows I'm worried!" },
    4: { calm: "Not everybody shows it.", competitive: "Not everybody shows it.", warm: "Not everybody shows it.", blunt: "Not everyone shows it.", bossy: "Not everybody shows it.", loud: "Not everybody SHOWS it!" },
    5: { theatrical: "Then tomorrow you show up calm, help with the water, and let them wonder.", quiet: "Tomorrow, be calm, help with the water, and let them wonder.", earnest: "Then tomorrow you show up calm, help with the water, and let them wonder.", calm: "Then tomorrow you show up calm, you help with the water, and you let them wonder.", loud: "Then TOMORROW you show up calm, help with the water, and let them wonder!" },
  },
  'nbl.c6': {
    1: { earnest: "Don't.", warm: "Please don't.", cruel: "Don't.", anxious: "Don't.", theatrical: "Don't you dare." },
    3: { earnest: "You said 'interesting'.", warm: "You said 'interesting'.", cruel: "You said 'interesting'.", anxious: "You said 'interesting'.", theatrical: "You said 'interesting'." },
  },
  'ny.d3': { 6: { anxious: "{a} made us do a sharing circle. I hated every second, and I'm doing it again tomorrow.", warm: "{a} made us do a sharing circle, and I pretended to hate it, and I'm doing it again tomorrow.", loud: "{a} made us do a SHARING CIRCLE! I hated it! I'm doing it again tomorrow!", competitive: "{a} made us do a sharing circle, and I'm doing it again tomorrow. Don't tell anyone.", calm: "{a} made us do a sharing circle, and I'm going to do it again tomorrow.", earnest: "{a} made us do a sharing circle, and honestly, I'm doing it again tomorrow." } },
  'nk.ao2': {
    1: { calm: "Okay. What do you want?", anxious: "Okay. What do you want?", food: "Okay. What do you want?", warm: "Okay. What do you want?" },
    2: { warm: "My name came up last time, and some of those votes came from my own people.", loud: "My name came up last time! Some of those votes came from my OWN people!", schemer: "My name came up last time. Some of those votes came from my own people.", food: "My name came up last time. Some of those votes came from my own people.", earnest: "My name came up last time, and some of those votes came from my own people." },
    3: { calm: "That's rough.", anxious: "That's rough.", food: "That's rough.", warm: "That's really rough. I'm sorry.", blunt: "Rough." },
    4: { warm: "So I'm looking for new people, and you've never written my name. I checked.", loud: "So I'm looking for new people, and you've NEVER written my name! I checked!", schemer: "So I'm looking for new people, and you've never written my name. I checked.", food: "So I'm looking for new people, and you've never written my name. I checked.", earnest: "So I'm looking for new people, and you've never written my name. I checked." },
    5: { calm: "You checked?", anxious: "You checked?", food: "You checked?", warm: "You checked?", blunt: "You checked?" },
    6: { warm: "I've been doing a lot of checking.", loud: "I've been doing a LOT of checking.", schemer: "I've been doing a lot of checking.", food: "I've been doing a lot of checking.", earnest: "I've been doing a lot of checking." },
    7: { calm: "{a} is about to jump ship, and whether I'm the lifeboat is up to me.", anxious: "{a} is about to jump ship, and I'm terrified of being the lifeboat or not.", food: "{a} is about to jump ship. Whether I'm the lifeboat is up to me.", warm: "{a} is about to jump ship, and I want to help, but I need to be careful.", blunt: "{a} is jumping ship. I decide if I'm the lifeboat." },
  },
  'nar.t3': { 0: { loud: "{other} isn't voting with us tonight! I've got a Vote Steal, so {other} doesn't get a vote, and WE get another one!", warm: "{other} isn't voting with us tonight. I've got a Vote Steal, and I hate using it, but {other} doesn't get a vote.", schemer: "{other} isn't voting with us tonight. I've got a Vote Steal, so {other} doesn't vote, and we get an extra one." } },
  'nvr.r1': {
    0: { theatrical: "Why do you keep saying 'them' like it's a team?", schemer: "Why do you keep saying 'them' like it's a team?", calm: "Why do you keep saying 'them' like it's a team?", warm: "Why do you keep saying 'them' like it's a team?", ditzy: "Why do you keep saying 'them' like they're a team?" },
    1: { warm: "Because it is a team, {theirs}, and they eat together, sleep near each other, and vote together.", emotional: "Because it is a team, {theirs}, and they eat together, sleep together and vote together.", schemer: "Because it is a team, {theirs}, and they eat, sleep and vote together.", competitive: "Because it's a team, {theirs}, and they eat together and vote together.", blunt: "It's a team, {theirs}, and they do everything together.", calm: "Because it is a team, {theirs}, and they eat, sleep and vote together." },
    2: { theatrical: "And {target} is in it.", schemer: "And {target} is in it.", calm: "And {target} is in it.", warm: "And {target} is in it?", ditzy: "And {target} is in it?" },
    3: { warm: "{target} holds it together. The others don't make a move without asking {target} first.", emotional: "{target} holds it together. The others don't move without asking {target}.", schemer: "{target} holds it together. Nobody moves without asking {target} first.", competitive: "{target} holds it together. Nobody moves without {target}.", blunt: "{target} holds them together.", calm: "{target} is the one who holds it together." },
    4: { theatrical: "So if {target} goes...", schemer: "So if {target} goes...", calm: "So if {target} goes...", warm: "So if {target} goes...", ditzy: "So if {target} goes...?" },
    5: { warm: "...they have to work out who's in charge, and while they argue, they're not coming for us.", emotional: "...they have to work out who's in charge, and while they argue, they're not coming for us.", schemer: "...they argue about who leads, and while they argue, they're not coming for us.", competitive: "...they fight over who's in charge, and they're not coming for us.", blunt: "...they fight over who's in charge. Not us.", calm: "...they have to work out who leads, and while they do, they're not coming for us." },
    6: { theatrical: "That's actually smart.", schemer: "That's actually smart.", calm: "That's actually smart.", warm: "That's actually smart.", ditzy: "Oh, that's actually smart!" },
    7: { warm: "Don't sound so surprised.", emotional: "Don't sound so surprised.", schemer: "Don't sound so surprised.", competitive: "Don't sound so surprised.", blunt: "Don't sound surprised.", calm: "Don't sound so surprised." },
    8: { theatrical: "I always thought {a} was just loud. Turns out {a} has been watching all of us this whole time.", schemer: "I thought {a} was just loud. {a} has been watching everyone, and now I'm watching {a}.", calm: "I always thought {a} was just loud. {a} has been watching everybody this whole time.", warm: "I always thought {a} was just loud, and I'm a little impressed, honestly.", ditzy: "I always thought {a} was just loud! Turns out {a} has been watching everybody." },
  },
  'nl.m1': {
    2: { earnest: "I didn't.", anxious: "I didn't.", tough: "I didn't.", theatrical: "I did not.", dry: "I didn't.", ditzy: "I didn't!" },
    3: { blunt: "Something was crawling on me all night.", competitive: "Something was crawling on me all night.", loud: "Something was CRAWLING on me all night!", ditzy: "Something was crawling on me all night!", warm: "Something was crawling on me all night.", quiet: "Something crawled on me." },
    5: { calm: "Okay, so terrible. Same as every morning.", nerdy: "Okay, so terrible, consistent with every morning.", warm: "Okay, so terrible. Same as every morning, then.", anxious: "Okay, so terrible. Same as every morning.", flirty: "Okay, so terrible. Same as every morning.", dry: "Okay, terrible. Great. Same as every morning." },
    7: { earnest: "Take it. I've lost my appetite.", anxious: "Take it. I've lost my appetite.", tough: "Take it.", theatrical: "Take it. I've quite lost my appetite.", dry: "Take it. I've lost my appetite.", ditzy: "Take it! I've lost my appetite." },
    9: { blunt: "Something with mud. Always mud.", competitive: "Something with mud. It's always mud.", loud: "Something with MUD! It's ALWAYS mud!", ditzy: "Something with mud. It's always mud!", warm: "Something with mud. It's always something with mud.", quiet: "Mud. Always mud." },
  },
  'nar.t7': {
    0: { warm: "I know {other} isn't voting my way tonight, so I'm taking {other}'s vote, and I don't feel great about it.", dry: "I know which way {other} is voting tonight, and it isn't mine. So, I'm borrowing {other}'s vote.", nerdy: "I know which way {other} is voting, and it's against me, so I'm taking {other}'s vote.", schemer: "{other} isn't voting my way tonight. So {other} doesn't vote at all.", calm: "I know {other} isn't voting my way tonight. So I'm taking {other}'s vote." },
    1: { warm: "{other} is going to be furious, and I'll make it right tomorrow. Tonight it might be the vote that saves me.", dry: "{other} will be furious, and that's tomorrow's problem. Tonight, it might save me.", nerdy: "{other} will be furious. I'll handle that tomorrow, because tonight it might be the deciding vote.", schemer: "{other} will be furious tomorrow. Tonight, it might save me.", calm: "{other} will be furious, and I'll deal with that tomorrow. Tonight it might save me." },
  },
  'nth.d4': {
    0: { earnest: "Hey, I'm with you. Whatever happens, you've got my vote.", calm: "I'm with you. Whatever happens, you've got my vote.", warm: "Hey, I'm with you, whatever happens. You've got my vote.", loud: "Hey, I'm WITH you! You've got my vote!", anxious: "Hey, I'm with you, whatever happens, okay? You've got my vote.", quiet: "I'm with you. My vote's yours." },
    2: { earnest: "You saved me. I'm never going to forget it.", calm: "You saved me. I won't forget it.", warm: "You saved me, and I'm never going to forget it.", loud: "You SAVED me! I'm not forgetting that!", anxious: "You saved me. I'm never going to forget it.", quiet: "You saved me. I won't forget." },
  },
  'nl.p2': { 7: { warm: "I'll do rocks. Can we just get it done?", schemer: "I'll do rocks. Let's get it done.", blunt: "I'll do rocks.", dry: "I'll do rocks. Can we get it done before I age?", earnest: "I'll do rocks. Let's just get it done." } },
  'ny.j1': {
    1: { emotional: "Good morning, peasant.", earnest: "Good morning, peasant.", warm: "Good morning, my dear peasant.", calm: "Good morning, peasant.", food: "Good morning, peasant. Fetch me breakfast.", bossy: "Good morning, peasant. Stand up straight." },
    2: { warm: "How did your majesty sleep?", blunt: "How'd your majesty sleep?", nerdy: "How did your majesty sleep?", loud: "How did your MAJESTY sleep?" },
    3: { emotional: "On a rock. As usual.", earnest: "On a rock, as usual.", warm: "On a rock, as usual.", food: "On a rock, with no breakfast in bed.", bossy: "On a rock, as usual. Unacceptable." },
    4: { loud: "Are you two EVER going to explain this?", earnest: "Are you two ever going to explain this?", calm: "Are you two ever going to explain this?", food: "Are you two ever going to explain this?", warm: "Are you two ever going to explain this?" },
    5: { warm: "No.", blunt: "No.", nerdy: "No.", loud: "NO." },
    6: { emotional: "Never.", earnest: "Never.", warm: "Never.", calm: "Never.", food: "Never.", bossy: "Never." },
  },
  'no.b2': {
    0: { earnest: "Okay, everybody, what's the most embarrassing thing that's happened to you here? Go.", loud: "OKAY, everybody! What's the most embarrassing thing that's happened to you here? Go!", flirty: "Okay, everybody, what's your most embarrassing moment here? Go.", warm: "Okay, everybody, what's the most embarrassing thing that's happened to you here?", dry: "Okay, everybody, most embarrassing moment so far. I need material.", calm: "Okay, everybody, most embarrassing thing so far?" },
    1: { warm: "I fell in the water. Twice.", ditzy: "I fell in the water! Twice!", emotional: "I fell in the water twice, and I nearly cried.", loud: "I fell in the WATER! TWICE!" },
    3: { loud: "I called {host} 'MOM'.", theatrical: "I called {host} 'Mom'. To their face.", emotional: "I called {host} 'Mom'.", warm: "I called {host} 'Mom'." },
    5: { loud: "It was EARLY! I was TIRED!", theatrical: "It was early! I was exhausted!", emotional: "It was early! I was tired!", warm: "It was early! I was tired!" },
    6: { earnest: "That's the best one. That's the winner.", loud: "That's the BEST one! That's the winner!", flirty: "That's the best one. That's the winner.", warm: "That's the best one. That's the winner.", dry: "That's the best one, that's the winner. Nobody beats that.", calm: "That's the winner." },
  },
  'nl5.s1': { 2: { competitive: "No. I know I lost it for us.", ditzy: "No. I know I lost it for us.", warm: "No, I know I lost it for us. I'm so sorry.", cruel: "No. I know I lost it for us.", chaotic: "No! I know I lost it for us!" } },
  'ny.d3': { 1: { anxious: "Seriously?", warm: "Seriously?", competitive: "Seriously?", calm: "Seriously?", earnest: "Seriously?" } },
  'no.f1': {
    1: { warm: "You've been slacking all day, and everybody knows it.", quiet: "You've been slacking all day.", anxious: "You've been slacking all day, and everybody knows it.", dry: "You've been slacking all day. Everybody's noticed." },
    2: { theatrical: "I have been working as hard as ANYBODY!", loud: "I've been working as HARD as anybody!", blunt: "I've worked as hard as anyone.", tough: "I've been working as hard as anybody.", warm: "I've been working as hard as anybody!" },
    3: { warm: "Whoa. What's going on?", schemer: "Whoa. What is your problem?", calm: "Whoa. What's your problem?", cruel: "Whoa. What is your problem?", loud: "WHOA. What is your problem?" },
    5: { warm: "Great. Now it's a whole fan club.", quiet: "Great. A fan club.", anxious: "Great. Now it's a whole fan club.", dry: "Great. Now there's a fan club." },
    6: { warm: "It's not a fan club. It's people who saw what happened.", schemer: "It's not a fan club. It's witnesses.", calm: "It's not a fan club. It's people who saw what happened.", cruel: "It's not a fan club. It's people who saw you.", loud: "It's not a FAN CLUB! It's people who SAW what happened!" },
    8: { theatrical: "It's fine. Let it go.", loud: "It's FINE. Let it go.", blunt: "It's fine.", tough: "It's fine. Leave it.", warm: "It's fine. Let it go." },
    9: { warm: "I said one thing to {b}, and suddenly I'm fighting three people. Noted.", quiet: "One thing to {b}, and I'm fighting three people. Noted.", anxious: "I said one thing to {b}, and suddenly three people are against me, and it scared me.", dry: "One comment to {b}, and suddenly I'm fighting three people. Lovely, and all noted." },
    10: { theatrical: "I didn't even have to defend myself. That's how you know who your real friends are.", loud: "I didn't even have to DEFEND myself! That's how you know who your friends are!", blunt: "I didn't have to defend myself. That shows who my friends are.", tough: "I didn't have to defend myself. Good to know who's got my back.", warm: "I didn't even have to defend myself. I felt so loved." },
  },
  'nk.la1': {
    1: { warm: "Know what?", nerdy: "Know what?", anxious: "Know what?", dry: "Know what?" },
    2: { loud: "{target} said your name last night! As the next vote!", theatrical: "{target} said your name last night, as the next vote.", nerdy: "{target} mentioned your name last night as the next vote.", warm: "{target} said your name last night, as the next vote. I'm sorry.", ditzy: "{target} said your name last night? Like, as the next vote?" },
    3: { warm: "{target}? Are you sure?", nerdy: "{target}? Are you sure?", anxious: "{target}? Are you sure?", dry: "{target}? You're sure?" },
    4: { loud: "I HEARD it, and I'm sorry! I just thought you'd want to know!", theatrical: "I heard it, and I'm so sorry. I thought you deserved to know.", nerdy: "I heard it, and I'm sorry. I assumed you'd want to know.", warm: "I heard it, and I'm so sorry. I just thought you'd want to know.", ditzy: "I heard it! Sorry, I just thought you'd want to know." },
    5: { warm: "...Yeah. Thanks.", nerdy: "...Yeah. Thanks.", anxious: "...Yeah. Thank you.", dry: "...Yeah. Thanks." },
    6: { loud: "{target} NEVER said that! But now {b} won't trust {target}, and {b} trusts me more. Two for one!", theatrical: "{target} never said a word of it. Now {b} distrusts {target}, and trusts me a little more.", nerdy: "{target} never said that, but {b}'s trust in {target} drops and in me rises, which is efficient.", warm: "{target} never said that, and I feel awful. But now {b} trusts me more." },
    7: { warm: "I thought {target} was on my side. I guess I was wrong, and it really hurts.", nerdy: "I thought {target} was on my side. Apparently I miscalculated.", anxious: "I thought {target} was on my side. Now I don't know who is.", dry: "I thought {target} was on my side. I guess I thought wrong." },
  },
  'nd.dp3': {
    1: { warm: "Good morning to you too.", loud: "Good MORNING to you too!", earnest: "Good morning to you too.", tough: "Morning to you too." },
    3: { loud: "We need them gone before they win immunity EVERY week!", warm: "We need them gone before they win immunity every week.", tough: "They need to go before they win immunity every week." },
  },
  'nl.c1': { 8: { bossy: "I didn't say anything when {a} started giving out jobs, and I should have. I'd have done it better.", earnest: "I didn't say anything when {a} started giving out jobs, and honestly, I'm annoyed at myself.", calm: "I didn't say anything when {a} took charge of the jobs. I'm a little annoyed at myself.", dry: "I said nothing when {a} started giving out jobs, and now I'm on water. Great.", cruel: "I let {a} start giving out jobs. I won't let it happen twice." } },
  'nl6.c1': { 1: { earnest: "With what? We've got water.", blunt: "With what? Water?", calm: "With what? We've got water.", anxious: "With what? We've only got water." } },
  'ny.i2': { 4: { schemer: "Enjoy it. Next week you're the biggest target here.", warm: "Enjoy it. Next week you're the biggest target here, though.", emotional: "Enjoy it. Next week you're the biggest target here.", earnest: "Enjoy it. Next week, you're the biggest target here.", loud: "ENJOY it! Next week you're the biggest target here!" } },
  'nvq.g1': {
    2: { bossy: "The log's fine. It's {target}.", theatrical: "The log is fine. It's {target}.", earnest: "The log's fine. It's {target}.", competitive: "It's {target}.", schemer: "The log's fine. It's {target}.", nerdy: "The log's fine. It's {target}." },
    3: { emotional: "What happened now?", warm: "Oh no. What happened now?", dry: "What happened now?", loud: "What happened NOW?", calm: "What happened?", ditzy: "What happened now?" },
    6: { bossy: "I want {target} gone because {target} can't stand me either. One of us goes eventually. It's going to be tonight.", theatrical: "I want {target} gone, because {target} loathes me too. One of us goes eventually, and tonight's the night.", earnest: "I want {target} gone because {target} can't stand me either. One of us goes eventually, and I'd rather it was tonight.", competitive: "{target} can't stand me either, so one of us goes, tonight.", schemer: "{target} can't stand me either, so one of us goes eventually. I'd rather choose when.", nerdy: "{target} dislikes me too, so one of us will go eventually. Tonight is the best timing." },
    8: { bossy: "Are you in?", theatrical: "Are you in?", earnest: "Are you in?", competitive: "You in?", schemer: "Are you in?", nerdy: "Are you in?" },
    9: { emotional: "I'd rather vote {alt}, if I'm honest.", warm: "I'd rather vote {alt}, honestly.", dry: "I'd rather vote {alt}, if I'm honest.", loud: "I'd rather vote {alt}!", calm: "I'd rather vote {alt}." },
    10: { bossy: "{alt} can wait. I can't spend another day biting my tongue.", theatrical: "{alt} can wait! I cannot bite my tongue one more day.", earnest: "{alt} can wait. I can't keep biting my tongue.", competitive: "{alt} can wait. I can't.", schemer: "{alt} can wait. I can't spend another day biting my tongue." },
    12: { emotional: "Fine. I'm in.", warm: "Okay. I'm in.", dry: "Fine. I'm in.", loud: "FINE. I'm in.", calm: "Fine. I'm in.", ditzy: "Okay! I'm in." },
    13: { emotional: "This isn't strategy, it's {a} being sick of {target}. {a} has the votes, though, and I'm not getting in the way.", warm: "This isn't strategy, it's {a} being fed up with {target}. I'm going along, but I feel a bit bad.", dry: "This isn't strategy. This is {a} being sick of {target}. But {a} has the votes, and I value my life.", loud: "This isn't STRATEGY, this is {a} being sick of {target}! But {a} has the votes, so fine!", calm: "This isn't strategy. It's {a} being sick of {target}. {a} has the votes, so I'm staying out of the way.", ditzy: "This isn't really strategy, it's just {a} being sick of {target}. But {a} has the votes, so okay." },
  },
  'nps.b1': { 1: { loud: "I'm FINE, I'm going to be fine! I just don't know who I eat breakfast with now!", calm: "I'm fine, I'm going to be fine. I just don't know who I eat breakfast with now.", warm: "I'm okay. I'm going to be okay. I just don't really know who I eat breakfast with now.", dry: "I'm fine. I'm going to be fine. I just have to find a new breakfast buddy, which is a whole thing.", theatrical: "I'm fine, and I'll be fine. I simply don't know who I break my fast with now.", earnest: "I'm fine, honestly. I just don't know who I eat breakfast with now." } },
  'nm.b8': {
    1: { earnest: "...Yeah. I did.", warm: "...Yeah, I did. I'm sorry.", loud: "...YEAH. I did.", calm: "...Yes. I did." },
    3: { earnest: "{lastBoot} was coming after people, honestly. I wasn't going to be one of them.", warm: "{lastBoot} was coming after people, and I wasn't going to be one of them. I'm sorry.", loud: "{lastBoot} was coming after PEOPLE! I wasn't going to be one of them!", calm: "{lastBoot} was coming after people. I wasn't going to be one of them." },
  },
  'nl.m1': {
    4: { earnest: "That was me, sorry. The floor is really lumpy.", anxious: "That was me, sorry, the floor is really lumpy.", warm: "That was me, sorry! The floor is really lumpy.", competitive: "That was me. The floor's lumpy.", ditzy: "That was me! Sorry, the floor is really lumpy.", theatrical: "That was me, I'm afraid. The floor is dreadfully lumpy." },
    6: { nerdy: "Is anybody going to eat that?", theatrical: "Is anybody going to eat that?", loud: "Is ANYBODY going to eat that?" },
  },
  'nmx.d1': {
    1: { quiet: "Somebody wrote my name last night. I've narrowed it down.", warm: "So somebody wrote my name last night, and I've narrowed it down.", ditzy: "Okay, so somebody wrote my name last night, and I've, like, narrowed it down.", loud: "Okay! Somebody wrote my name last night, and I've NARROWED it down!", earnest: "Okay, so somebody wrote my name last night, and I've narrowed it down.", theatrical: "Someone wrote my name last night, and I've narrowed the suspects down." },
    2: { loud: "Oh yeah? WHO?", warm: "Oh yeah? Who?", theatrical: "Oh? Who?", blunt: "Who?" },
    3: { quiet: "Not you. That's one down.", warm: "Not you, obviously. So that's one down, and everybody else to go.", ditzy: "Not you, obviously! So that's one down, and everybody else to go.", loud: "Not YOU, obviously! So that's one down, everybody else to go!", earnest: "Not you, obviously. So that's one down, and everybody else to go.", theatrical: "Not you, obviously. One down, everybody else to go." },
    4: { loud: "That's... a GOOD start.", blunt: "That's a start.", warm: "That's... a good start.", theatrical: "That's... a fine start." },
    5: { quiet: "You'll help me, right?", warm: "You'll help me figure it out, right?", ditzy: "You'll help me figure it out, right?", loud: "You'll HELP me figure it out, right?", earnest: "You'll help me figure it out, right?", theatrical: "You'll help me solve this, won't you?" },
    6: { loud: "Of COURSE.", blunt: "Sure.", warm: "Of course.", theatrical: "Of course." },
    7: { loud: "{a} wants my help finding who voted against {a.obj}, and it was ME! I need a poker face!", blunt: "{a} wants my help finding who voted against {a.obj}, and it was me. Poker face.", warm: "{a} wants my help finding out who voted against {a.obj}, and it was me. I feel sick.", theatrical: "{a} wants my help unmasking the culprit, and the culprit is me. I'll need my finest poker face." },
  },
  'ns.mr1': {
    2: { theatrical: "What? No, your face is fine, your face is lovely, I mean...", earnest: "What? No, no, your face is fine, it's great, I mean...", calm: "What? No, your face is fine, great, even.", quiet: "No. Your face is fine.", anxious: "What? No, your face is fine, your face is great, oh no, I mean..." },
    4: { theatrical: "I'm going to go and stand in the lake now. Forever.", earnest: "I'm going to go stand in the lake now.", calm: "I'm going to go stand in the lake now.", quiet: "I'm going to the lake.", anxious: "I'm going to go stand in the lake now. Bye." },
  },
  'ny.m4': {
    1: { loud: "...and then I said, if you want the fire bigger, get the wood YOURSELF!", ditzy: "...and then I said, if you want the fire bigger, get the wood yourself!", anxious: "...and then I said, if you want the fire bigger, get the wood yourself.", warm: "...and then I said, if you want the fire bigger, get the wood yourself." },
    3: { loud: "Doesn't MATTER.", ditzy: "Doesn't matter!", anxious: "Doesn't matter.", warm: "Doesn't matter." },
    5: { loud: "It DOESN'T.", ditzy: "It doesn't!", anxious: "It doesn't.", warm: "It doesn't." },
  },
  'nps.t3': {
    0: { loud: "{lastBoot} used to grab my arm when I was about to say something stupid! Now NOBODY'S going to grab my arm!", proud: "{lastBoot} used to stop me before I said something stupid. Now nobody will." },
    1: { loud: "So I have to grab my OWN arm! That's going to be so much harder than it sounds!", proud: "So I have to stop myself now. I can do that." },
  },
  'na.s1': {
    1: { warm: "Have you noticed nobody tells us anything?", quiet: "Nobody tells us anything.", schemer: "Have you noticed nobody tells us anything?", theatrical: "Have you noticed? Nobody tells us anything.", blunt: "Nobody tells us anything." },
    2: { loud: "I noticed! I thought it was just me!", theatrical: "I noticed. I assumed it was just me.", dry: "I noticed. I thought it was just me being unpopular.", blunt: "I noticed.", food: "I noticed. I thought it was just me.", tough: "I noticed." },
    3: { warm: "It's both of us. They stop talking every time we walk over.", quiet: "Both of us. They go quiet when we walk up.", schemer: "It's both of us. They stop talking every time we walk over.", theatrical: "It's both of us. Conversation dies every time we arrive.", blunt: "Both of us. They stop talking when we walk over." },
    4: { loud: "So we're NEXT.", theatrical: "So we're next.", dry: "So we're next. Wonderful.", blunt: "So we're next.", food: "So we're next.", tough: "So we're next." },
    5: { warm: "One of us is, unless we stop being alone.", quiet: "One of us is. Unless we team up.", schemer: "One of us is. Unless we stop being alone.", theatrical: "One of us is, unless we stop being alone.", blunt: "One of us. Unless we team up." },
    6: { loud: "Two people at the bottom is still two people at the BOTTOM!", theatrical: "Two people at the bottom is still two people at the bottom.", dry: "Two people at the bottom is still two people at the bottom.", blunt: "Two at the bottom is still the bottom.", food: "Two people at the bottom is still two people at the bottom.", tough: "Two at the bottom is still the bottom." },
    7: { warm: "Two people is a swing vote. If they ever need to break a tie, they need us.", quiet: "Two people is a swing vote.", schemer: "Two people is a swing vote. If they need a tie broken, they need us.", theatrical: "Two people is a swing vote! If they need a tie broken, they need us.", blunt: "Two is a swing vote. They'll need us." },
    8: { loud: "...Okay! That's actually a good point!", theatrical: "...Okay, that's actually a good point.", dry: "...Okay, that's actually a good point, annoyingly.", blunt: "Good point.", food: "...Okay, that's actually a good point.", tough: "...Fine. Good point." },
    9: { warm: "So we stick together, we listen, and we wait for them to need us. {group}.", quiet: "We stick together and we wait, as {group}.", schemer: "So we stick together, listen, and wait for them to need us. {group}.", theatrical: "So we stick together, listen, and wait. {group}.", blunt: "We stick together and wait. {group}." },
    10: { loud: "I didn't come here to be on the bottom! But at least I'm not down here ALONE!", theatrical: "I didn't come here to be at the bottom, but at least I'm not down here alone.", dry: "I didn't come here to be at the bottom. At least it's less lonely now.", blunt: "I didn't come to be at the bottom. At least I'm not alone.", food: "I didn't come here to be on the bottom. At least I've got company down here." },
  },
  'nly.i1': {
    0: { quiet: "I'll tell you something. I want something back.", anxious: "I'm going to tell you something, and I want something back.", loud: "I'm going to tell you something, and I want something BACK!", dry: "I'll tell you something, and I want something in return. It's called trade.", warm: "I'm going to tell you something, and I'd like something back.", proud: "I'll tell you something. I'll want something back." },
    2: { quiet: "There's a group of three you don't know about. They meet behind the {quarters}.", anxious: "There's a group of three you don't know about. They meet behind the {quarters} when everybody's at the water.", loud: "There's a GROUP of three you don't know about! They meet behind the {quarters}!", dry: "There's a group of three you don't know about. They meet behind the {quarters}, very subtly.", warm: "There's a group of three you don't know about. They meet behind the {quarters} when everybody's at the water.", proud: "There's a group of three you don't know about. They meet behind the {quarters} when everyone's at the water." },
    3: { dry: "And what do you want?", loud: "And what do you WANT?", warm: "And what do you want?", theatrical: "And what is it you want?", anxious: "And what do you want?" },
    4: { quiet: "Your word that you won't help them when they come for me.", anxious: "Your word that when they come for me, you won't help them.", loud: "Your WORD that you won't help them when they come for me!", dry: "Your word that you won't help them when they come for me. Small price.", warm: "Your word that when they come for me, you won't help them.", proud: "Your word you won't help them when they come for me." },
  },
  'nl.n1': { 1: { warm: "I hate this part.", loud: "I HATE this part.", theatrical: "I despise this part.", flirty: "I hate this part.", blunt: "I hate this." } },
  'ndp.w5': { 1: { theatrical: "Every time I win, the camp grows quieter around me. One night I'll lose, and they'll all be waiting.", calm: "Every time I win, the camp gets quieter around me. One night I'll lose, and they'll be ready." } },
  'nl4.p2': {
    0: { anxious: "Can I ask you something weird? Do people here like me?", warm: "Can I ask you something weird? Do people here like me?", theatrical: "Can I ask you something strange? Do people here like me?", calm: "Can I ask you something? Do people here like me?", dry: "Weird question. Do people here like me?" },
    2: { anxious: "Then why did my name come up last night?", warm: "Then why did my name come up last night?", theatrical: "Then why did my name come up last night?", calm: "Then why did my name come up last night?", dry: "Then why did my name come up last night?" },
    3: { calm: "That's not about liking you. That's about numbers.", loud: "That's not about LIKING you! That's numbers!", warm: "That's not about liking you, I promise. That's about numbers.", flirty: "That's not about liking you. That's about numbers.", earnest: "Honestly, that's not about liking you. That's about numbers.", proud: "That's not about liking you. That's numbers." },
    4: { anxious: "Numbers don't write names. People do.", warm: "Numbers don't write names. People do.", theatrical: "Numbers don't write names. People do.", calm: "Numbers don't write names. People do.", dry: "Numbers don't write names. People do." },
    6: { anxious: "You promise?", warm: "You promise?", theatrical: "Do you promise?", calm: "You promise?", dry: "You promise?" },
    7: { calm: "I promise.", loud: "I PROMISE.", warm: "I promise.", flirty: "I promise.", earnest: "I promise.", proud: "I promise." },
  },
  'nvq.s1': { 8: { calm: "I thought about {alt}, but {alt} actually helped today.", loud: "I thought about {alt}, but {alt} actually HELPED today!", competitive: "I thought about {alt}, but {alt} helped today.", quiet: "{alt} helped today.", cruel: "I thought about {alt}, but annoyingly, {alt} helped today." } },
  'nl6.s1': { 0: { anxious: "Not to brag, but I think I've got this whole game figured out. Maybe.", warm: "Not to brag, but I think I've basically got this game figured out.", calm: "Not to brag, but I've basically got this game figured out." } },
  'nv4.n5': {
    0: { schemer: "There are two names going round camp tonight. {target} and {other}.", calm: "There are two names going around tonight. {target} and {other}.", dry: "Two names are going round camp tonight. {target} and {other}.", warm: "There are two names going round camp tonight, {target} and {other}.", cruel: "Two names tonight. {target} and {other}.", earnest: "There are two names going round camp tonight, {target} and {other}." },
    1: { warm: "Which one's got more?", dry: "Which one's winning?", competitive: "Which has more?", food: "Which one's got more?", loud: "Which one's got MORE?", ditzy: "Which one has more?" },
    2: { schemer: "{target}, by a little. That's why I'm putting everything on {target}.", calm: "{target}, by a little. So I'm putting everything on {target}.", dry: "{target}, narrowly. Hence everything on {target}.", warm: "{target}, by a little. That's why I'm putting everything on {target}.", cruel: "{target}, by a little. Everything goes on {target}.", earnest: "{target}, by a little. That's why I'm putting everything on {target}." },
    3: { warm: "And if the {other} people get louder?", dry: "And if the {other} people get louder?", competitive: "And if the {other} side gets louder?", food: "And if the {other} people get louder?", loud: "And if the {other} people get LOUDER?", ditzy: "And if the {other} people get louder?" },
    4: { schemer: "Then we've got the night to make sure they don't. Who haven't you talked to yet?", calm: "Then we have the night to make sure they don't. Who haven't you talked to?", dry: "Then we have tonight to stop that. Who haven't you talked to?", warm: "Then we've got tonight to make sure they don't. Who haven't you talked to yet?", cruel: "Then we make sure they don't. Who haven't you talked to?", earnest: "Then we've got tonight to make sure they don't. Who haven't you talked to yet?" },
    5: { warm: "Pretty much everybody on the far end of the beach.", dry: "Pretty much everybody on the far end of the beach. The quiet ones.", competitive: "Everybody on the far end of the beach.", food: "Pretty much everybody on the far end of the beach.", loud: "Pretty much EVERYBODY on the far end of the beach!", ditzy: "Um, pretty much everybody at the far end of the beach?" },
    6: { schemer: "Then go talk to them, nice and casual, and make sure they hear {target} before they hear {other}.", calm: "Then go talk to them, casually. Make sure they hear {target} first.", dry: "Then go chat, very casually, and make sure {target} is the first name they hear.", warm: "Then go and talk to them, nice and casual. Just make sure they hear {target} before {other}.", cruel: "Go talk to them. Make sure they hear {target} first.", earnest: "Then go talk to them, nice and casual, and make sure they hear {target} before {other}." },
    7: { warm: "I don't even care who deserves it anymore. I just don't want my name to be the one they hear first.", dry: "I've stopped caring who deserves it. I just need my name not to be the first one they hear.", competitive: "Deserving doesn't matter now. My name just can't be first.", food: "I don't care who deserves it anymore. I just need my name to stay out of it.", loud: "I don't even CARE who deserves it anymore! My name just can't be the first one they hear!", ditzy: "I don't even care who deserves it. I just don't want my name to be first." },
  },
  'nv.n4': {
    0: { warm: "Hey, it's {target} tonight. Are you with us?", dry: "It's {target} tonight. Are you with us?", schemer: "It's {target} tonight. Are you with us?" },
    2: { warm: "People who want {target} gone.", dry: "People who want {target} gone. A growing club.", schemer: "People who want {target} gone." },
    4: { warm: "So that's a no.", dry: "So that's a no.", schemer: "So that's a no." },
  },
  'nlx.v3': { 0: { dry: "Let's be honest, everybody here does what I say. They just pretend it was their idea.", nerdy: "Let's be honest, everybody here does what I say. They just believe they came up with it.", blunt: "Everybody here does what I say. They pretend otherwise.", cruel: "Everybody here does what I say. They just aren't smart enough to notice." } },
  'nj.p5': { 3: { warm: "The big picture is that log, and it's heavy.", ditzy: "The big picture is that log! It's really heavy.", quiet: "The log's heavy." } },
  'nd.bh3': {
    1: { earnest: "Can you stop? Nobody cares about your grandma's dog.", warm: "Can you please stop? Nobody really cares about your grandma's dog.", calm: "Can you stop? Nobody cares about your grandma's dog.", schemer: "Can you stop? Nobody cares about your grandma's dog.", blunt: "Stop. Nobody cares about the dog." },
    2: { quiet: "Oh. Sorry.", calm: "Oh, sorry, I didn't...", bossy: "Oh, sorry, I didn't...", cruel: "Oh, sorry, I didn't..." },
    5: { loud: "What? I'm just being HONEST!", earnest: "What? I'm just being honest.", calm: "What? I'm just being honest.", blunt: "I'm being honest." },
  },
  'nl6.m2': { 0: { blunt: "Want mine?", earnest: "Do you want the rest of mine?", ditzy: "Want the rest of mine?", cruel: "Want the rest of mine?", theatrical: "Would you like the rest of mine?" } },
  'nrl.i2': { 2: { loud: "Then WHY?", anxious: "Then why?", warm: "Then why?" } },
  'nw.y5': {
    1: { earnest: "Want help?", theatrical: "Need a hand?", food: "Want help? I'll work for snacks.", calm: "Want help?", anxious: "Do you want help?" },
    3: { earnest: "No catch. Well, a small one: {target}, tonight.", theatrical: "No catch! Well, a tiny one: {target}, tonight.", food: "No catch. Well, a small catch, {target}, tonight.", calm: "No catch. Well, a small one: {target}, tonight.", anxious: "No catch. Well, a small catch: {target}, tonight." },
    5: { earnest: "Because it's that or one of us, and I'd really rather it wasn't one of us.", theatrical: "Because it's {target} or one of us, and I'd rather it wasn't us.", food: "Because it's that or one of us, and I'd rather it wasn't one of us.", calm: "Because it's that or one of us. I'd rather it wasn't us.", anxious: "Because it's that or one of us, and I'd really like it not to be one of us." },
  },
  'ny.s2': {
    2: { bossy: "No reason.", anxious: "No reason.", schemer: "No reason." },
    4: { bossy: "Tell them yourself.", anxious: "Tell them yourself.", schemer: "Tell them yourself." },
  },
  'nlx.j1': {
    2: { schemer: "Yeah, amazing, again.", loud: "Yeah, AMAZING, again!", ditzy: "Yeah, amazing, again.", dry: "Yeah, amazing, again, as always.", food: "Yeah, amazing, again." },
    4: { schemer: "Nothing. It's just funny how it's always you.", loud: "NOTHING! It's just funny how it's ALWAYS you!", ditzy: "Nothing! It's just funny how it's always you.", dry: "Nothing. It's just funny how it's always you, every time.", food: "Nothing. It's just funny how it's always you." },
  },
  'nth.g1': { 4: { quiet: "It wasn't about you. It was numbers.", schemer: "It wasn't about you. It was a numbers thing.", ditzy: "It wasn't about you! It was a numbers thing.", nerdy: "It wasn't about you. It was purely numbers.", anxious: "It wasn't about you, I promise. It was a numbers thing." } },
  'ncx.b2': {
    0: { calm: "Can I sit with you at breakfast? I used to sit with {lastBoot}.", warm: "Can I sit with you at breakfast? I used to sit with {lastBoot}.", loud: "Can I sit with you at breakfast? I used to sit with {lastBoot}!" },
    2: { calm: "I know, I'm asking anyway. It makes me feel less like I'm just showing up.", warm: "I know. I'm asking anyway, because it makes me feel less like I'm just showing up.", loud: "I know, I'm asking anyway! It makes me feel less like I'm just showing up!" },
  },
  'na.d4': { 7: { warm: "...Fine. Final two.", anxious: "...Okay. Final two.", proud: "...Fine. Final two.", nerdy: "...Fine. Final two.", earnest: "...Okay. Final two." } },
  'ns.s1': {
    2: { warm: "Let them wonder.", anxious: "Let them wonder." },
    3: { calm: "So what is this? You and me?", loud: "So what IS this? You and me?", earnest: "So what is this, you and me?", dry: "So what is this? You and me?" },
    4: { warm: "I don't know. I just know I want to be wherever you are.", anxious: "I don't know. I just know I want to be wherever you are." },
    5: { calm: "That's a lot.", loud: "That's a LOT.", earnest: "That's a lot.", dry: "That's a lot." },
    6: { warm: "Too much?", anxious: "Is it too much?" },
    7: { calm: "No. Not too much.", loud: "No! Not too much!", earnest: "No. Not too much.", dry: "No. Not too much." },
    10: { calm: "Everybody's going to say a showmance is a target, and they're right, and I don't care right now.", loud: "Everybody's going to say a showmance is a TARGET, and they're right, and I don't CARE!", earnest: "Everybody will say a showmance is a target, and they're right, but I honestly don't care right now.", dry: "Everybody will say a showmance is a target, and they're right, but I'm choosing not to care." },
  },
  'na.c1': { 1: { food: "You know everybody thinks we're working together, right?", warm: "You know everybody thinks we're working together, right?", emotional: "You know everybody thinks we're working together, right?", quiet: "Everybody thinks we're working together.", bossy: "Everybody thinks we're working together. You know that?" } },
  'nk.rp1': { 6: { earnest: "I just paid attention to people, and they opened up to me like nobody had listened in weeks. I feel a little bad about how well it works.", loud: "I just paid ATTENTION to people, and they opened right up! I feel a little bad about how well that works!", theatrical: "I simply listened, and they opened up like flowers. I feel a touch guilty about how well it works." } },
  'nv4.p4': {
    2: { loud: "{target}!", calm: "{target}.", competitive: "{target}.", theatrical: "{target}." },
    3: { schemer: "Not {partner}?", anxious: "Not {partner}?", earnest: "Not {partner}?", nerdy: "Not {partner}?", dry: "Not {partner}?" },
    4: { loud: "If we take {partner}, {target} gets ANGRY and smart! If we take {target}, {partner} gets sad and lonely!", calm: "If we take {partner}, {target} gets angry and smart. If we take {target}, {partner} just gets lonely.", competitive: "Take {partner}, and {target} gets angry and smart. Take {target}, and {partner} just gets lonely, so it's an easy choice.", theatrical: "Take {partner}, and {target} becomes vengeful and clever. Take {target}, and {partner} becomes lonely. I know which I prefer." },
    6: { loud: "That's the GAME! Are you in?", calm: "That's the game. Are you in?", competitive: "That's the game. In?", theatrical: "That's the game. Are you in?" },
    7: { warm: "...I'm in.", emotional: "...I'm in.", calm: "...I'm in.", earnest: "...I'm in." },
    8: { schemer: "I'm in. I'm also never letting you plan anything against me.", anxious: "I'm in. Please never plan anything against me.", earnest: "I'm in, and I'm never letting you plan against me.", nerdy: "I'm in. I'm also never letting you plan anything against me.", dry: "I'm in. Also, please never plan anything against me." },
  },
  'ny.i1': {
    2: { blunt: "Look at me.", warm: "Look at me!", dry: "Look at me. Immune.", calm: "Look at me." },
    3: { loud: "Don't get USED to it!", bossy: "Don't get used to it.", calm: "Don't get used to it.", theatrical: "Don't grow accustomed to it." },
    4: { blunt: "I'm going to get extremely used to it.", warm: "I'm going to get very used to it!", dry: "I'm going to get extremely used to it.", calm: "I'm going to get used to it." },
    5: { schemer: "Safe tonight. That must feel amazing.", earnest: "Safe tonight. That must feel amazing.", warm: "Safe tonight. That must feel amazing!", theatrical: "Safe tonight. How glorious that must feel.", nerdy: "Safe tonight. That must feel good." },
    6: { blunt: "It feels like I'll finally sleep tonight.", warm: "It feels like I'm finally going to sleep tonight.", dry: "It feels like I'm finally going to sleep tonight. Which would be novel.", calm: "It feels like I'll finally sleep tonight." },
  },
  'nvu.g1': {
    1: { schemer: "I'm angry about every morning. {target} has been on me since the first day, and today was just the loudest.", theatrical: "I'm still furious about every morning! {target} has been on me since the very first day.", nerdy: "I'm angry about every morning. {target} has been at me since day one, and today was the peak.", loud: "I'm still ANGRY about every morning! {target} has been on me since the first day!", anxious: "I'm still angry about every morning. {target} has been on me since the first day, and today was the worst." },
    2: { warm: "So what do you want?", dry: "So what do you want?", theatrical: "So what do you want?", food: "So what do you want?", calm: "So what do you want?" },
    3: { schemer: "I want to write {target}'s name, and I want you to write it with me.", theatrical: "I want to write {target}'s name, and I want you beside me when I do.", nerdy: "I want to write {target}'s name, and I'd like you to write it with me.", loud: "I want to write {target}'s NAME, and I want you to write it with me!", anxious: "I want to write {target}'s name, and I really want you to write it with me." },
    5: { schemer: "Both. {target} would write my name in a heartbeat, so I'm getting there first.", theatrical: "Both! {target} would write mine in a heartbeat, and I'm simply faster.", nerdy: "Both. {target} would write my name instantly, so I'm just getting there first.", loud: "BOTH! {target} would write my name in a heartbeat!", anxious: "Both. {target} would write my name in a heartbeat, and I'm scared of that." },
    7: { schemer: "I know how it looks, petty and personal. One of us was always going to send the other home, and I'd rather it was me doing it.", theatrical: "I know how it looks. Petty. Personal. But one of us was always sending the other home, and I'd rather be the one doing it." },
  },
  'fd.c3': {
    1: { nerdy: "What is this?", loud: "What IS this?", theatrical: "What on earth is this?", schemer: "What is this?", bossy: "What is this?" },
    4: { nerdy: "Just eat it. We'll need the calories for whatever Chris has planned.", tough: "Just eat it. We need the energy.", food: "Just eat it. We need our energy for whatever Chris has planned.", cruel: "Just eat it. We need our energy for whatever Chris has planned." },
    7: { loud: "Day one, and I'd already trade my WHOLE bag for a sandwich!", nerdy: "Day one, and I'd already trade everything I packed for one sandwich.", flirty: "Day one, and I'd already trade my whole bag for a sandwich.", blunt: "Day one. I'd trade my whole bag for a sandwich." },
  },
  'nvr.r2': {
    1: { nerdy: "Why does every secret meeting happen behind this shed?", warm: "Why does every secret meeting happen behind this shed?", competitive: "Why is every secret meeting behind this shed?", theatrical: "Why does every secret meeting happen behind this one shed?", calm: "Why does every secret meeting happen behind this shed?" },
    2: { competitive: "Because it's the only place {theirs} can't see us.", warm: "Because it's the only place {theirs} can't see us.", emotional: "Because it's the only place {theirs} can't see us.", earnest: "Because it's the only place {theirs} can't see us.", bossy: "Because it's the only place {theirs} can't see us." },
    3: { nerdy: "Okay, so, {theirs}. What are we doing about them?", anxious: "Okay, so {theirs}. What are we doing about them?", warm: "Okay, so, {theirs}. What are we doing about them?", competitive: "So, {theirs}. What's the plan?", loud: "Okay! So, {theirs}, what are we doing about them?" },
    4: { competitive: "We take {target}. Not the loudest one, the one who decides things.", warm: "We take {target}. Not the loudest one, the one who actually decides things.", emotional: "We take {target}. Not the loudest, the one who decides.", earnest: "We take {target}. Not the loudest one, the one who actually decides things.", bossy: "We take {target}. The one who decides things." },
    5: { nerdy: "{target} decides things?", warm: "{target} decides things?", competitive: "{target} decides things?", theatrical: "{target} decides things?", calm: "{target} decides things?" },
    6: { competitive: "Watch them at dinner. Everybody looks at {target} before they say anything.", warm: "Watch them at dinner. Everybody looks at {target} before they speak.", emotional: "Watch them at dinner. They all look at {target} before they say anything.", earnest: "Watch them at dinner. Everybody looks at {target} first.", bossy: "Watch them at dinner. They all look at {target} first." },
    7: { nerdy: "How many have we got?", anxious: "How many have we got?", warm: "How many have we got?", competitive: "Numbers?", loud: "How many have we GOT?" },
    10: { nerdy: "I've walked past {theirs} a hundred times and never noticed they check {target} first. Now I can't unsee it.", warm: "I've walked past {theirs} a hundred times and never noticed they all look at {target}. Now I can't stop seeing it.", competitive: "I've walked past {theirs} a hundred times. Now I see they all look at {target}, and I know where to aim.", theatrical: "A hundred times I walked past {theirs}, and never saw them glance at {target}. Now I see nothing else.", calm: "I've walked past {theirs} a hundred times and never noticed they look at {target} first." },
  },
  'fp.c4': {
    1: { cruel: "I was going to.", loud: "I was GOING to!", warm: "I was going to.", ditzy: "I was going to!" },
    3: { cruel: "...No, it's terrible. Take it.", loud: "...No, it's TERRIBLE, take it!", warm: "...No, it's terrible. Please, take it.", ditzy: "...No, it's terrible, take it!" },
    5: { cruel: "We met this morning.", loud: "We met THIS MORNING!", warm: "We met this morning!", ditzy: "We met this morning?" },
    7: { cruel: "{a} is ridiculous. I'm going to keep {a} around.", loud: "{a} is RIDICULOUS! I kind of love it!", warm: "{a} is ridiculous, and I kind of love it already.", ditzy: "{a} is so ridiculous! I kind of love it." },
  },
  'nm.a4': { 0: { anxious: "Morning.", blunt: "Morning.", cruel: "Morning.", loud: "MORNING." } },
  'nlx.k5': { 3: { earnest: "{a} didn't even try, no apology, no excuse, nothing, and that told me everything.", ditzy: "{a} didn't even try, no sorry, no excuse, nothing! That tells me everything.", flirty: "{a} didn't even try. Not an apology, not an excuse. That told me all I need to know.", blunt: "{a} didn't try or apologise, and that says everything.", dry: "{a} didn't even try, with no apology and no excuse, which was very informative." } },
  'nvr.s1': {
    0: { earnest: "So we're all thinking the same thing, right?", warm: "So we're all thinking the same thing, right?", ditzy: "So we're all thinking the same thing, right?", loud: "So we're ALL thinking the same thing, right?" },
    2: { earnest: "I'm going to say it. We lost because of {target}.", warm: "I'm going to say it, and I'm sorry. We lost because of {target}.", ditzy: "I'm going to say it! We lost because of {target}.", loud: "I'm going to SAY it! We lost because of {target}!" },
    3: { dry: "It's not just today, though, it's every challenge. {target} tries, and trying isn't working.", nerdy: "It's not just today, it's every challenge. {target} tries, but trying isn't working.", warm: "It's not just today, it's every challenge. {target} tries so hard, but it isn't working.", tough: "It's not just today, it's every challenge, and trying isn't working." },
    5: { dry: "We all feel awful. We'll feel worse if we keep losing and it's one of us.", nerdy: "We all feel awful. We'll still feel awful if we lose again, and then it's one of us.", warm: "We all feel awful. We'll still feel awful if we keep losing, and then it's one of us.", tough: "We all feel awful. We'll feel worse if it's one of us." },
    6: { earnest: "Okay. {target}.", emotional: "Okay, {target}. I hate this.", calm: "Okay. {target}.", loud: "OKAY. {target}.", anxious: "Okay. {target}." },
  },
  'nly.t1': {
    1: { calm: "I never said thank you for the other day.", warm: "I never said thank you for the other day.", dry: "I never said thank you for the other day.", anxious: "I never said thank you for the other day, and I've felt bad about it.", ditzy: "I never said thank you for the other day!" },
    3: { calm: "For not letting me fall apart. You didn't have to stay up with me.", warm: "For not letting me fall apart. You didn't have to stay up with me, and you did.", dry: "For not letting me fall apart. You didn't have to stay up with me.", anxious: "For not letting me fall apart. You didn't have to stay up with me.", ditzy: "For not letting me fall apart! You didn't have to stay up with me." },
    5: { calm: "Not out here. Most people here would have let me.", warm: "Not out here. Most people out here would've let me.", dry: "Not out here. Out here most people would have sold tickets.", anxious: "Not out here. Out here most people would've let me fall apart.", ditzy: "Not out here! Out here most people would've let me." },
  },
  'nl.m2': {
    2: { nerdy: "It's quieter.", warm: "It's quieter.", anxious: "It's quieter.", calm: "It's quieter.", dry: "It's quieter." },
    3: { blunt: "Too quiet.", theatrical: "Far too quiet.", loud: "TOO quiet.", calm: "Too quiet.", competitive: "Too quiet." },
    4: { earnest: "Are we going to talk about it?", competitive: "Are we going to talk about it?", anxious: "Are we going to talk about it?", blunt: "Are we talking about it?" },
    6: { nerdy: "We don't have to talk about it. We just have to make sure it doesn't happen again for a while.", warm: "We don't have to talk about it. We just have to make sure it doesn't happen again soon.", anxious: "We don't have to talk about it. We just have to make sure it doesn't happen again.", calm: "We don't have to talk about it. We just make sure it doesn't happen again soon.", dry: "We don't have to talk about it. We just have to avoid a repeat for a while." },
  },
  'nrl.p1': {
    0: { warm: "Did you hear what {target} said? That {target} would never write {protects}'s name, no matter what?", quiet: "{target} said {target} would never write {protects}'s name.", dry: "Did you hear {target} announce that {protects} is untouchable?", nerdy: "Did you hear {target} say {target} would never write {protects}'s name?" },
    2: { warm: "Then {target} just told us exactly who stands between us and {protects}.", quiet: "Then {target} just told us who's in the way.", dry: "Then {target} just told us exactly who's in the way. Helpful.", nerdy: "Then {target} just identified who stands between us and {protects}." },
    3: { loud: "So we go through {target}!", earnest: "So we go through {target}.", schemer: "So we go through {target}.", theatrical: "So we go through {target}." },
    4: { warm: "We go through {target} first. Then {protects} doesn't have a shield anymore.", quiet: "{target} first. Then {protects} has no shield.", dry: "{target} first, and then {protects} has no shield. Simple.", nerdy: "{target} first. Then {protects} has no shield." },
  },
  'nps.e2': {
    0: { competitive: "My name came up last night, and for a second I was back there, last time, watching the votes come out.", nerdy: "My name came up last night, and for a moment I was back in my last season, watching the votes.", schemer: "My name came up last night, and for a second I was right back watching the votes last time.", calm: "My name came up last night, and for a moment I was right back there, last time." },
    1: { competitive: "But I'm still here, which is already better than last time. I'm counting it as a win.", nerdy: "But I'm still here, which already beats last time. I'll keep measuring it like that.", schemer: "I'm still here. That already beats last time.", calm: "But I'm still here. That's already better than last time." },
  },
  'ny.n2': {
    1: { schemer: "Every time.", earnest: "Every time.", loud: "EVERY time.", nerdy: "Every time." },
    3: { warm: "You're going to be okay.", food: "You're going to be okay. Have some of this.", loud: "You're going to be OKAY!", calm: "You're going to be okay." },
  },
};
