// ══════════════════════════════════════════════════════════════════════
// td/story/lines/voices/batch21.js — the voice overhaul, pooled pass 4
// ══════════════════════════════════════════════════════════════════════
// Ranked across twelve more fresh seasons (seeds 1616..3003, 76.9% before). Connected sentences.

export default {
  'nd.dg1': {
    1: { warm: "Wow, you must be so tired.", loud: "WOW, you must be SO tired.", tough: "You must be tired.", nerdy: "Wow, you must be exhausted.", dry: "Wow, you must be so tired." },
    3: { dry: "From all that standing around, which really takes it out of you.", blunt: "From all that standing around.", warm: "From all that standing around, I mean." },
    5: { loud: "What? I said you must be TIRED!", warm: "What? I only said you must be tired.", nerdy: "What? I said you must be tired." },
    7: { loud: "I didn't say anything MEAN! Everyone just knew what I meant, and that's different!", warm: "I didn't say anything mean, honestly, everyone just knew what I meant.", nerdy: "Technically I said nothing mean. Everyone just inferred it, and that's different." },
  },
  'fd.c1': {
    1: { loud: "I'm taking the bottom bunk by the WINDOW!", proud: "I'm taking the bottom bunk by the window.", theatrical: "I'm claiming the bottom bunk by the window, darling." },
    2: { loud: "Did we ALL agree on that?", cruel: "Did we all agree on that?", proud: "Did we all agree on that?", competitive: "Did we agree on that?", nerdy: "Did we all agree on that?", tough: "Did we agree on that?" },
    3: { loud: "I'm agreeing on it NOW!", warm: "I'm agreeing on it now, if that's okay?", cruel: "I'm agreeing on it now.", proud: "I'm agreeing on it now.", theatrical: "I am agreeing on it now." },
    4: { warm: "Can I at least have the one that isn't next to the door?", loud: "Can I at least have the one that ISN'T next to the door?", dry: "Can I at least have the one that isn't next to the door, where the draft lives?", goofy: "Can I at least have the one not next to the door? The door looks haunted." },
    5: { theatrical: "Sure, whatever, I'll take the one nobody wants, as always.", quiet: "I'll take the one nobody wants.", anxious: "Sure, I'll take the one nobody wants, that's fine.", nerdy: "Sure, I'll take the one nobody wants.", proud: "Fine, I'll take the one nobody wants.", dry: "Sure, whatever, I'll take the one nobody wants." },
  },
  'nar.w1': {
    1: { warm: "I need to tell you something, and you can't tell anybody I told you.", competitive: "I need to tell you something, and you didn't hear it from me.", emotional: "I need to tell you something, and please don't tell anybody I told you.", anxious: "I need to tell you something, and you can't tell anybody it was me.", loud: "I need to tell you something, and you CAN'T tell anybody I told you!", schemer: "I need to tell you something. You didn't hear it from me." },
    3: { warm: "{pitcher} is going around saying your name for tonight, and I'm sorry.", competitive: "{pitcher} is going round saying your name for tonight.", emotional: "{pitcher} is going around saying your name, for tonight.", anxious: "{pitcher} is going around saying your name, for tonight.", loud: "{pitcher} is going around saying YOUR name! For tonight!", schemer: "{pitcher} is going around saying your name, for tonight." },
    4: { nerdy: "{pitcher}? Are you sure?", proud: "{pitcher}? Are you sure?", cruel: "{pitcher}? Are you sure?", warm: "{pitcher}? Are you sure?", earnest: "{pitcher}? Are you sure?", calm: "{pitcher}? Are you sure?" },
    5: { warm: "I heard it myself, and I'm so sorry.", competitive: "I heard it myself. I'm sorry.", emotional: "I heard it myself, and I'm so sorry.", anxious: "I heard it myself, I'm sorry.", loud: "I heard it MYSELF! I'm sorry!", schemer: "I heard it myself. Sorry." },
  },
  'nlx.v2': {
    1: { nerdy: "Enjoy your water.", schemer: "Enjoy your water.", food: "Enjoy your water, and your lunch.", warm: "Enjoy your water.", cruel: "Enjoy your water.", proud: "Enjoy your water." },
    2: { warm: "What's that supposed to mean?", earnest: "What's that supposed to mean?", schemer: "What's that supposed to mean?" },
    3: { nerdy: "Only that I'd enjoy everything, if I were you, while it lasts.", schemer: "Just that I'd enjoy everything, if I were you, while it lasts.", food: "Just that I'd enjoy every meal, if I were you, while it lasts.", warm: "Just that I'd enjoy everything, if I were you, while it lasts.", cruel: "Just that I'd enjoy everything while it lasts.", proud: "Just that I'd enjoy everything while it lasts." },
    4: { warm: "I smiled back, but my heart was pounding, because {a} just threatened me so politely.", earnest: "I smiled back, but my heart was pounding. {a} just threatened me politely, and I won't sleep tonight." },
  },
  'na.p11': {
    2: { warm: "Everybody who matters to me.", loud: "Everybody who MATTERS.", cruel: "Everybody who matters.", proud: "Everybody who matters.", schemer: "Everybody who matters." },
    4: { warm: "Look around, because if we all vote together, nobody here goes home until everybody else has.", loud: "Look around! If we ALL vote together, nobody here goes home until everybody else has!", cruel: "Look around. If we vote together, nobody here goes home until everyone else has.", proud: "Look around. Vote together, and nobody here goes home until everybody else has.", schemer: "Look around. If we vote as one, nobody here goes home until everyone else has." },
    5: { anxious: "We'd have to agree on a name every single time.", earnest: "We'd have to all agree on a name every time.", warm: "We'd have to agree on a name every time.", theatrical: "We'd have to agree on a name every single time.", loud: "We'd have to agree on a name EVERY time!" },
    6: { warm: "Then we agree on a name every time.", loud: "Then we AGREE on a name every time!", cruel: "Then we agree every time.", proud: "Then we agree every time.", schemer: "Then we agree on a name every time." },
    7: { earnest: "And who decides when we can't?", anxious: "And who decides when we can't?", nerdy: "And who decides when we disagree?", blunt: "Who decides when we can't?", warm: "And who decides when we can't?", schemer: "And who decides when we can't?" },
    8: { warm: "...We'll figure that out.", loud: "...We'll figure that OUT.", cruel: "...We'll figure that out.", proud: "...We'll figure that out.", schemer: "...We'll figure that out." },
    9: { anxious: "We should probably figure that out, though.", earnest: "We should probably figure that out.", warm: "We should probably figure that out.", theatrical: "We should probably figure that out.", loud: "We should PROBABLY figure that out!" },
    10: { warm: "{group}. Agreed?", loud: "{group}! Agreed?", cruel: "{group}. Agreed?", proud: "{group}. Agreed?", schemer: "{group}. Agreed?" },
    12: { earnest: "{a} didn't answer my question, and I think that's because {a} already knows who's deciding. It's {a}.", nerdy: "{a} didn't answer my question, which tells me {a} plans to be the one deciding.", blunt: "{a} dodged my question. {a} will be deciding.", schemer: "{a} didn't answer, so {a} intends to decide. Noted." },
  },
  'nv4.g1': {
    0: { dry: "I'm not going to pretend this is strategy, because it isn't.", warm: "I'm not going to pretend this is strategy, okay?", competitive: "This isn't strategy, and I'm not pretending it is.", goofy: "I'm not even going to pretend this is strategy.", loud: "I'm NOT going to pretend this is strategy!" },
    1: { warm: "Okay, that's a strong start." },
    2: { dry: "{target} has been in my face since the first day, at every chore, every meal and every challenge.", warm: "{target} has been in my face since day one, every chore, every meal, every challenge.", competitive: "{target} has been in my face since day one. Every chore, every challenge.", goofy: "{target} has been in my face since day one, every chore, every meal, every challenge, every breath.", loud: "{target} has been in my FACE since the first day! Every chore, every meal, every challenge!" },
    3: { earnest: "And tonight you want to end it.", calm: "And tonight you want to end it.", warm: "And tonight you want to end it.", emotional: "And tonight you want it to end.", theatrical: "And tonight, you want to end it." },
    4: { dry: "Tonight I want to sleep without hearing {target}'s voice, which seems reasonable.", warm: "Tonight I just want to sleep without hearing {target}'s voice.", competitive: "Tonight I want to sleep without {target}'s voice in my ear.", goofy: "Tonight I want to sleep without {target}'s voice narrating my dreams.", loud: "Tonight I want to SLEEP without hearing {target}'s voice!" },
    6: { dry: "It's a great reason to vote somebody out, just not a smart one, and I'm fine with that.", warm: "It's a great reason, just not a smart one, and I'm okay with that.", competitive: "It's a great reason, not a smart one. I don't care.", goofy: "It's a great reason, just not a smart one, and I've made my peace with that.", loud: "It's a GREAT reason, just not a smart one, and I'm fine with that!" },
    7: { earnest: "...Okay. Honestly, {target} gets on my nerves too.", calm: "...Okay. {target} gets on my nerves too.", warm: "...Okay. Honestly, {target} gets on my nerves too.", emotional: "...Okay. {target} gets on my nerves too, honestly.", theatrical: "...Fine. {target} grates on me too." },
  },
  'nrn.f1': {
    1: { warm: "Why are there crackers in your sleeping bag?", dry: "Why are there crackers in your sleeping bag?", calm: "Why are there crackers in your sleeping bag?", competitive: "Why are there crackers in your sleeping bag?", quiet: "There are crackers in your sleeping bag." },
    3: { warm: "What's the emergency?", dry: "And what's the emergency?", calm: "What's the emergency?", competitive: "What's the emergency?", quiet: "What emergency?" },
    4: { loud: "Being HUNGRY at night! It happens every night, so it's a very regular emergency!", proud: "Being hungry at night, which happens nightly, so it's a planned emergency.", warm: "Being hungry at night, and it happens every night, so it's a very regular emergency." },
    5: { warm: "Are there more?", dry: "Are there more?", calm: "Are there more?", competitive: "Are there more?", quiet: "More?" },
    6: { loud: "Define 'MORE'.", proud: "Define 'more'.", warm: "Define 'more'." },
    7: { warm: "{a}.", dry: "{a}.", calm: "{a}.", competitive: "{a}.", quiet: "{a}." },
    8: { loud: "There MIGHT be some in the tool box, and under the big rock, and in my left shoe!", proud: "There might be some in the tool box, under the big rock, and in my left shoe.", warm: "There might be some in the tool box, and under the big rock, and in my left shoe." },
  },
  'nrn.f2': {
    0: { warm: "Why is there a banana in the tool box?", anxious: "Why is there a banana in the tool box?", calm: "Why is there a banana in the tool box?", competitive: "Why is there a banana in the tool box?", flirty: "Why is there a banana in the tool box?" },
    1: { loud: "Because NOBODY ever looks in the tool box!" },
    2: { warm: "I just looked in the tool box.", anxious: "I just looked in the tool box.", calm: "I just looked in the tool box.", competitive: "I just looked in the tool box.", flirty: "I just looked in the tool box." },
    3: { loud: "Well, now I need a NEW spot! Thanks a lot!", proud: "Well, now I need a new spot. Thank you.", warm: "Well, now I need a new spot. Thanks a lot." },
    4: { warm: "How many spots do you have?", anxious: "How many spots do you have?", calm: "How many spots do you have?", competitive: "How many spots do you have?", flirty: "How many spots do you have?" },
    5: { loud: "Seven! Six, now!", proud: "Seven. Six now.", warm: "Seven, six now." },
    6: { warm: "We've been here for a week.", anxious: "We've only been here a week.", calm: "We've been here for a week.", competitive: "We've been here a week.", flirty: "We've been here for a week." },
    7: { loud: "And I've been BUSY!", proud: "And I've been busy.", warm: "And I've been busy." },
  },
  'nvq.s1': { 2: { anxious: "I know.", schemer: "I know.", earnest: "I know.", warm: "I know.", proud: "I know." } },
  'ns.f1': {
    1: { warm: "You're splashing me on purpose.", schemer: "You're splashing me on purpose." },
    8: { warm: "I'm not here to fall for anybody, I'm here to win, and I need {a} to stop being cute for one day.", schemer: "I came here to win, not to fall for somebody, so I need {a} to stop being cute for a day.", loud: "I am NOT here to fall for somebody! I'm here to win! I need {a} to stop being cute for ONE day!" },
  },
  'nlx.v1': {
    0: { nerdy: "Listen to me. Whatever happens with the rest of them, you're safe with me.", schemer: "Listen. Whatever happens with the rest, you're safe with me.", food: "Listen to me. Whatever happens with the rest of them, you're safe with me." },
    2: { nerdy: "Because you're the only one here I actually like, and please don't spread it around.", schemer: "You're the only one here I actually like. Don't spread it around.", food: "Because you're the only one here I actually like, so don't spread it around." },
    4: { nerdy: "I'm not sweet. I'm loyal to the right people.", schemer: "I'm not sweet. I'm loyal to the right people.", food: "I'm not sweet. I'm just loyal to the right people." },
  },
  'nvt.f3': { 0: { loud: "Okay, so after tonight, we start thinking about who's NEXT!", calm: "After tonight, we should start thinking about who's next.", warm: "So after tonight, we should start thinking about who's next, together.", proud: "After tonight, we plan who's next.", earnest: "After tonight, we should honestly start thinking about who's next.", ditzy: "Okay, so after tonight, we should think about who's next?" } },
  'nps.t2': {
    1: { proud: "I'm trying not to say anything I'll regret.", tough: "I'm trying not to say anything I'll regret.", loud: "I'm TRYING not to say anything I'll regret!", dry: "I'm trying not to say anything I'll regret, which is hard for me.", goofy: "I'm trying not to say anything I'll regret, so I'm just chewing my lip." },
    2: { anxious: "About last night?", loud: "About last NIGHT?", quiet: "Last night?", goofy: "About last night?", warm: "About last night?" },
    3: { proud: "About the people who wrote my name and then said good morning to me like nothing happened.", tough: "About the people who wrote my name and then said good morning like nothing happened.", loud: "About the people who WROTE my name and then said good morning like nothing happened!", dry: "About the people who wrote my name and then cheerfully said good morning.", goofy: "About the people who wrote my name, then said good morning like it was a regular Tuesday." },
    5: { proud: "The old me would have flipped the breakfast table. The new me is going to smile and wait, and that's much scarier.", tough: "The old me would've flipped the table. The new me waits, and that's scarier.", loud: "The old me would have FLIPPED the breakfast table! The new me is going to smile and wait!", dry: "The old me would have flipped the breakfast table. The new me is going to smile, which is far more terrifying." },
  },
  'nvr.n1': {
    0: { warm: "Okay, I've talked to everybody, and every name splits the tribe except one.", loud: "Okay! I've talked to EVERYBODY, and every name splits the tribe except one!", dry: "I've talked to everybody, and every name splits the tribe except one." },
    1: { warm: "Let me guess, {target}.", blunt: "{target}.", anxious: "Let me guess, {target}?" },
    2: { warm: "{target}, because nobody loves it and nobody hates it.", loud: "{target}! Nobody loves it, nobody hates it!", dry: "{target}, the name nobody loves and nobody hates." },
    4: { warm: "It's the reason nobody gets blindsided and nobody starts a war, and tomorrow we're all still friends.", loud: "It's the reason nobody gets blindsided and nobody starts a WAR! Tomorrow we're all still friends!", dry: "It's the reason nobody gets blindsided and nobody starts a war, so tomorrow we're all still friends." },
    5: { dry: "Except {target}.", loud: "Except {target}!", ditzy: "Except {target}?", anxious: "Except {target}.", warm: "Except {target}." },
    6: { warm: "Except {target}.", loud: "Except {target}.", dry: "Except {target}, yes." },
  },
  'nlx.r1': {
    0: { warm: "Hey, can we talk?", nerdy: "Hey, can we talk?", loud: "Hey! Can we talk?", calm: "Hey. Can we talk?" },
    1: { competitive: "We haven't really talked in days.", earnest: "We haven't really talked in days.", blunt: "We haven't talked in days." },
    2: { warm: "I know, and that's kind of the point. I miss it.", nerdy: "I know, that's the point. I miss it.", loud: "I KNOW, that's the point! I miss it!", calm: "I know, that's the point. I miss it." },
    3: { competitive: "I miss it too, honestly.", earnest: "I miss it too, honestly.", dry: "I miss it too, honestly.", warm: "I miss it too, so much.", blunt: "I miss it too." },
    4: { warm: "Whatever happened, I don't even remember why we stopped.", nerdy: "Whatever happened, I can't remember why we stopped.", loud: "Whatever happened, I don't even REMEMBER why we stopped!", calm: "Whatever happened, I don't remember why we stopped." },
    5: { competitive: "Me neither. Sit down.", earnest: "Me neither, honestly. Sit down.", dry: "Me neither. Sit down.", warm: "Me neither. Come, sit down.", blunt: "Me neither. Sit." },
  },
  'nl6.s3': {
    0: { dry: "Let's be honest, if I wasn't on this team, you'd all have lost every challenge by now.", nerdy: "Statistically, without me, this team loses every challenge.", schemer: "Let's be honest, without me, you'd all have lost every challenge by now." },
    1: { schemer: "We won the one you sat out.", cruel: "We won the one you sat out.", blunt: "We won the one you missed.", competitive: "We won the one you sat out." },
    3: { blunt: "It was the hardest one yet.", schemer: "It was the hardest one yet.", cruel: "It was the hardest one yet.", quiet: "It was the hardest.", competitive: "It was the hardest one yet." },
    5: { schemer: "I'm going to walk away now, before I say something I can't take back.", cruel: "I'm walking away before I say something I mean.", blunt: "I'm walking away.", competitive: "I'm walking away before I say something I regret." },
  },
  'nl6.g2': {
    2: { dry: "It's a lot every day.", warm: "It's a lot every day, I know.", cruel: "It's a lot every day.", schemer: "It's a lot every day." },
    4: { dry: "You're still here, which is better at this than most people.", warm: "You're still here, and that's better than most people manage.", cruel: "You're still here. That's more than most.", schemer: "You're still here. That's better than most." },
    6: { dry: "Barely surviving counts. Come and sit with me for a bit.", warm: "Barely surviving counts, okay? Come and sit with me for a bit.", cruel: "Barely surviving counts. Sit with me.", schemer: "Barely surviving counts. Sit with me for a bit." },
  },
  'nd.ex2': {
    2: { dry: "You've been pushing people around since we got here, me, everybody, and nobody says anything because they're scared of you.", warm: "You've been pushing people around since we got here, and nobody says anything because they're scared of you, and I'm saying it." },
    4: { warm: "I'm terrified, and I'm saying it anyway!", earnest: "I'm terrified, honestly, and I'm saying it anyway.", dry: "I'm terrified, and I'm saying it anyway, apparently." },
  },
  'fd.g1': {
    3: { proud: "It's called getting to know each other.", loud: "It's called GETTING TO KNOW EACH OTHER!", warm: "It's called getting to know each other!" },
    6: { proud: "See? That wasn't so bad.", loud: "SEE? That wasn't so bad!", warm: "See? That wasn't so bad!" },
  },
  'nk.bm1': { 1: { blunt: "I want to do something that makes them all stop and look at me. Soon.", cruel: "I want to do something that makes them all stop and stare, and I want it soon.", warm: "I want to do something that makes them all notice me, soon.", loud: "I want to do something that makes them ALL stop and look at me!", schemer: "I want a move that makes them all stop and look at me, soon." } },
  'nk.lb1': {
    2: { warm: "{target} has been telling people you're the next to go, and I'm so sorry.", anxious: "{target} has been telling people you're the next to go.", schemer: "{target} has been telling people you're the next to go.", nerdy: "{target} has been telling people you're the next to go." },
    4: { warm: "That's what {target} tells everybody.", anxious: "That's what {target} tells everybody.", schemer: "That's what {target} tells everybody.", nerdy: "That's what {target} tells everybody." },
    6: { warm: "{target} never said anything about {b}, and I feel a bit bad. {b} believed me so fast that the doubts were already there.", anxious: "{target} never said anything about {b}, and {b} believed me straight away, which scares me a little.", schemer: "{target} never mentioned {b} at all, and {b} believed me instantly, so the doubts were already there.", nerdy: "{target} never mentioned {b}. {b} believed me immediately, which means {b} already doubted {target}." },
  },
  'nps.h3': {
    1: { food: "Just thinking about home. It's a birthday back there today, and they'll be having cake.", blunt: "Thinking about home. There's a birthday today.", dry: "Just thinking about home. It's a birthday back there today, and I'm missing the cake.", loud: "Just thinking about HOME! It's a birthday today!", warm: "Just thinking about home. It's a birthday today, back there." },
    3: { food: "Somebody who's going to be very upset I missed it, and the cake.", blunt: "Somebody who'll be upset I missed it.", dry: "Somebody who will be very upset I missed it.", loud: "Somebody who's going to be VERY upset I missed it!", warm: "Somebody who's going to be really upset I missed it." },
  },
  'nm.b8': { 7: { blunt: "I could have lied and I didn't. That should count.", loud: "I could have LIED and I didn't! That should count for something!", proud: "I could have lied, and I didn't. That should count for something.", competitive: "I told the truth when I could have lied. That should count.", earnest: "I could have lied, and I didn't, and honestly, that should count for something." } },
  'ny.b1': {
    2: { tough: "We're good at this. The fish are just bad at being caught.", calm: "We're amazing at this. The fish are just bad at being caught.", warm: "We're amazing at this, the fish are just bad at being caught.", earnest: "We're amazing at this, honestly. The fish are just bad at being caught.", nerdy: "We're excellent at this. The fish are simply bad at being caught." },
    3: { warm: "That's not how fishing works.", ditzy: "That's not how fishing works, is it?", competitive: "That's not how fishing works.", goofy: "That's not how fishing works, I'm pretty sure." },
    4: { tough: "Have you ever been fishing?", calm: "Have you ever been fishing before?", warm: "Have you ever been fishing before?", earnest: "Have you ever actually been fishing before?", nerdy: "Have you ever been fishing before?" },
    5: { warm: "...No.", ditzy: "...No?", competitive: "...No.", goofy: "...No. Have you?" },
    6: { tough: "Me neither.", calm: "Me neither.", warm: "Me neither.", earnest: "Me neither, honestly.", nerdy: "Me neither." },
    7: { warm: "We caught nothing, and I spent two hours with {a}, and it was the best two hours I've had here.", ditzy: "We didn't catch anything, but I spent two hours with {a}, and it was the best!", competitive: "We caught nothing. Two hours with {a}, and it was the best time I've had here.", goofy: "We caught nothing. Two hours with {a}, and it was the best two hours I've had here. The fish lost." },
  },
  'ny.ra1': { 1: { warm: "We kind of have been losing, though.", theatrical: "We have, in fairness, been losing.", proud: "We have been losing.", loud: "We HAVE been losing!" } },
  'nk.mf1': {
    0: { competitive: "It's all set. Everyone's voting {target} tonight.", anxious: "It's all set, I think. Everyone's voting {target} tonight.", schemer: "It's all set. Everyone's voting {target} tonight.", goofy: "It's all set! Everyone's voting {target} tonight!" },
    2: { competitive: "I counted. You're the last one I needed.", anxious: "I counted, and you're the last one I needed.", schemer: "I counted. You're the last one I needed.", goofy: "I counted, and you're the last piece of the puzzle!" },
    4: { competitive: "Everyone is not on it. But now {b} is, and {b} will tell the next person everyone's on it, and that's how a majority gets built.", schemer: "Not everyone is on it, but {b} is now, and {b} will tell the next person it's everyone. That's how majorities are made." },
  },
  'nar.w5': {
    0: { anxious: "Don't freak out, but {pitcher} is trying to get people on {target}.", warm: "Don't freak out, but {pitcher} is trying to get people on {target}.", dry: "Don't freak out, but {pitcher} is trying to get people on {target}." },
    2: { anxious: "Not yet. I came to you first.", warm: "Not yet, I came to you first.", dry: "Not yet. I came to you first." },
  },
  'nar.g2': {
    0: { loud: "You're doing it WRONG, by the way.", warm: "You're doing it wrong, by the way.", earnest: "You're doing it wrong, by the way.", competitive: "You're doing it wrong.", calm: "You're doing it wrong, by the way." },
    2: { loud: "Maybe I WILL.", warm: "Maybe I will.", earnest: "Maybe I will.", competitive: "Maybe I will.", calm: "Maybe I will." },
  },
  'nm.n4': {
    1: { warm: "Okay, we're down one, and we need to stop losing.", anxious: "Okay, we're down one, and we have to stop losing.", nerdy: "We're down one, and we need to stop losing." },
    2: { quiet: "Yeah, no kidding.", dry: "Yeah, no kidding.", warm: "Yeah, no kidding.", anxious: "Yeah, no kidding.", earnest: "Yeah, no kidding." },
    3: { warm: "I'm serious. Every time we lose, we lose a person, and every person we lose makes the next one harder.", anxious: "I'm serious. Every loss costs a person, and that makes the next one harder.", nerdy: "Every loss costs a person, and each person lost makes the next challenge harder." },
    4: { warm: "So what do we do?", earnest: "So what do we do?", competitive: "So what do we do?", dry: "So what do we do?" },
    5: { warm: "We win the next one, and if we lose, we make sure the right person goes.", anxious: "We win the next one, and if we lose, we make sure the right person goes.", nerdy: "We win the next one, and if we lose, we choose the right person." },
    6: { quiet: "You already have somebody in mind.", dry: "Sounds like you already have somebody in mind.", warm: "Sounds like you already have somebody in mind.", anxious: "You already have somebody in mind?", earnest: "Sounds like you already have somebody in mind." },
    7: { warm: "I've got a few.", anxious: "I've got a few.", nerdy: "I have a few." },
    8: { quiet: "{lastBoot} has been gone one night, and {b} is already picking the next. I want to be on {b}'s side.", dry: "{lastBoot} has been gone one night, and {b} is already picking the next. I'd like to be on {b}'s side of that.", warm: "{lastBoot} has been gone one night, and {b} is already planning the next. I'd feel safer on {b}'s side.", anxious: "{lastBoot} has only been gone one night, and {b} is already picking the next. I want to be on {b}'s side.", earnest: "{lastBoot} has been gone one night, and {b} is already picking the next one. I want to be on {b}'s side." },
  },
  'nl.h3': { 3: { loud: "Same one?", emotional: "Same one?", proud: "Same one?", goofy: "Same one?" } },
  'nl5.f2': {
    2: { earnest: "Mm-hmm?", competitive: "Mm-hmm?", warm: "Mm-hmm?", proud: "Mm-hmm?" },
    3: { warm: "Those were the emergency crackers.", competitive: "Those were the emergency crackers.", dry: "Those were the emergency crackers.", blunt: "Those were the emergency crackers." },
    4: { earnest: "This is an emergency. I'm starving.", competitive: "This is an emergency. I'm starving.", warm: "This is an emergency, I'm starving.", proud: "This is an emergency. I'm starving." },
    6: { earnest: "Okay, you can't tell anybody.", competitive: "You can't tell anybody.", warm: "Okay, please don't tell anybody.", proud: "You can't tell anybody." },
  },
  'ndp.b1': { 1: { emotional: "But if I hold back tonight, I'm only hurting myself, and everybody else is playing to win, so why shouldn't I? I hope I'm right.", warm: "But if I hold back, I'm only hurting myself, and everybody else is playing to win. I just wish it didn't have to be {friend}." } },
  'nvq.g1': { 4: { competitive: "Nothing new, that's the problem. It's every day, the comments, the eye rolls, the way {target} talks to me like I'm stupid." } },
  'ns.n1': {
    1: { ditzy: "Never have I ever had a crush on someone in this camp!", anxious: "Never have I ever had a crush on someone in this camp.", proud: "Never have I ever had a crush on someone in this camp.", earnest: "Never have I ever had a crush on someone in this camp." },
    4: { ditzy: "Who is it?", anxious: "Who is it?", proud: "Who is it?", earnest: "Who is it?" },
    5: { anxious: "It's not a question game, it's never have I ever! Next!", competitive: "It's not a question game. Next!", warm: "It's not a question game, it's never have I ever! Next!" },
  },
  'nv4.r1': {
    0: { emotional: "You're staring at {theirs} again.", competitive: "You're staring at {theirs} again.", nerdy: "You're staring at {theirs} again.", blunt: "You're staring at {theirs}.", flirty: "You're staring at {theirs} again." },
    1: { loud: "Because they're doing it AGAIN! Every time somebody new walks over, they stop talking!", dry: "Because they're doing it again. Every time somebody new walks over, they stop talking.", flirty: "Because they're doing it again. Every time somebody walks over, they stop talking.", warm: "Because they're doing it again. Every time somebody new walks over, they stop talking." },
    2: { emotional: "Maybe they just like their privacy.", competitive: "Maybe they just like their privacy.", nerdy: "Maybe they just value privacy.", blunt: "Maybe they like privacy.", flirty: "Maybe they just like their privacy." },
    3: { loud: "Nobody likes privacy that much out here! They're planning, and one of us is in that plan!", dry: "Nobody likes privacy that much out here. They're planning, and I'd bet one of us is in it.", flirty: "Nobody likes privacy that much. They're planning, and one of us is in that plan.", warm: "Nobody likes privacy that much here. They're planning, and I'm worried one of us is in it." },
    4: { emotional: "So we go first.", competitive: "So we go first.", nerdy: "So we go first.", blunt: "We go first.", flirty: "So we go first." },
    5: { loud: "We go FIRST, and it's {target}, because {target} holds {theirs} together!", dry: "We go first, and it's {target}, because {target} holds {theirs} together.", flirty: "We go first, and it's {target}, because {target} holds {theirs} together.", warm: "We go first, and it's {target}, because {target} is the one holding {theirs} together." },
    6: { emotional: "And then?", competitive: "And then?", nerdy: "And then?", blunt: "Then?", flirty: "And then?" },
    7: { loud: "And then we watch them fall apart trying to decide who's in charge!", dry: "Then we watch them fall apart deciding who's in charge.", flirty: "Then we watch them fall apart trying to decide who's in charge.", warm: "Then we watch them fall apart deciding who's in charge." },
    8: { emotional: "{a} wants to pull one brick out of {theirs} and watch the wall come down, and I really hope {a} chose the right brick.", competitive: "{a} wants to pull one brick and bring down {theirs}. I hope it's the right brick.", nerdy: "{a} wants to remove the one brick holding {theirs} up. I hope {a} has identified the right one.", blunt: "{a} is pulling one brick to drop {theirs}. Hope it's the right one.", flirty: "{a} wants to pull one brick and watch {theirs} fall. I hope {a} picked the right brick." },
  },
  'nd.dp3': {
    0: { warm: "Your plan is bad, I'm sorry.", dry: "Your plan is bad.", competitive: "Your plan is bad.", flirty: "Your plan is bad.", nerdy: "Your plan is flawed." },
    1: { warm: "Good morning to you too.", loud: "Good MORNING to you too!" },
    2: { warm: "I'm serious, you want to go after the strongest person here, and we need them for challenges.", theatrical: "I'm serious, you want to go after our strongest player, and we need them!", dry: "I'm serious. You want to go after the strongest person here, whom we need for challenges.", flirty: "I'm serious, you want to go after the strongest person here, and we need them." },
    5: { dry: "Fine, do it your way, and when it goes wrong, I'll say I told you so.", theatrical: "Fine, do it your way! And when it goes wrong, I shall say I told you so!" },
    7: { dry: "{a} and I want the same thing, and completely disagree about how to get it.", theatrical: "{a} and I want the very same thing, and disagree utterly on how to get there." },
  },
  'ns.s1': { 9: { calm: "I didn't come here to fall for anybody, and that plan lasted about a week.", warm: "I didn't come here to fall for anybody, and that plan lasted about a week. I'm glad.", quiet: "I didn't plan on falling for anyone. That lasted a week.", loud: "I did NOT come here to fall for anybody! That plan lasted about a week!", schemer: "I didn't come here to fall for anybody, and that plan lasted about a week." } },
  'nps.p2': {
    0: { warm: "You've been up since before sunrise.", earnest: "You've been up since before sunrise.", loud: "You've been up since BEFORE sunrise!", flirty: "You've been up since before sunrise." },
    1: { warm: "I've been practising knots, for the challenges.", competitive: "I've been practising knots for the challenges.", anxious: "I've been practising knots, for the challenges.", quiet: "Practising knots." },
    3: { warm: "Nobody else got picked last in the first challenge, either.", competitive: "Nobody else got picked last in the first challenge.", anxious: "Nobody else got picked last in the first challenge, either.", quiet: "Nobody else got picked last." },
    5: { warm: "I know, and I still remember everybody's face.", competitive: "I know. I still remember everybody's face.", anxious: "I know. I still remember everybody's face.", quiet: "I remember their faces." },
  },
  'nj.p3': { 8: { ditzy: "{a} is so nice about it that nobody notices {a} is running the whole camp, but I noticed!", loud: "{a} is SO nice about it, nobody notices {a} is running the whole camp! I notice!", proud: "{a} runs the camp so nicely that nobody notices. I notice.", tough: "{a} runs the camp, nice as anything. I see it." } },
  'nl.w2': { 2: { blunt: "Let {a} have it. {a} earned it.", loud: "Let {a} HAVE it! {a} earned it!", dry: "Let {a} have it. {a} earned it.", calm: "Let {a} have it. {a} earned it." } },
  'nl.d2': {
    5: { schemer: "I can't, I'm too nervous.", nerdy: "I can't, I'm too nervous.", warm: "I can't, I'm too nervous.", tough: "I can't eat. I'm too wound up." },
    8: { dry: "I hate dinner before a vote, because everybody smiles at everybody and I can't tell who's lying.", warm: "I hate dinner before a vote. Everybody smiles at everybody, and I can't tell who's lying, and it makes me sad." },
  },
  'ny.co1': {
    3: { ditzy: "You've been sitting here for an hour.", cruel: "You've been sitting here for an hour.", loud: "You've been sitting here for an HOUR.", dry: "You've been sitting here for an hour." },
    7: { ditzy: "Every single day, we just don't say it.", cruel: "Every single day. We just don't say it.", loud: "EVERY single day! We just don't say it!", dry: "Every single day. We just don't say it." },
  },
  'npl.sc9': { 0: { ditzy: "I've been listening all day, and {target} is the name, so I'm just going to go with it.", earnest: "I've listened to everybody all day, and honestly, {target} is the name, so I'm going with it." } },
  'ny.mt1': {
    1: { warm: "Hey, hey, breathe, look at me.", theatrical: "Hey, hey, breathe. Look at me, darling.", goofy: "Hey, hey, breathe, look at me. Look at my face." },
    2: { dry: "I can't...", loud: "I CAN'T...", proud: "I can't..." },
    3: { warm: "Yes, you can. Breathe in, and out, and again.", theatrical: "Yes, you can. Breathe in, and out, and again.", goofy: "Yes, you can. Breathe in, and out, and again, like a sleepy dog." },
    4: { warm: "Now tell me who you've actually talked to today, not who you're scared of.", theatrical: "Now, tell me who you've actually spoken to today, not who frightens you.", goofy: "Now tell me who you've actually talked to today, not who you're scared of." },
    5: { dry: "...Four people.", loud: "...FOUR people.", proud: "...Four people." },
    6: { warm: "Four is so much more than nobody. Go talk to two more before dinner.", theatrical: "Four is far more than nobody! Go and talk to two more before dinner.", goofy: "Four is way more than nobody. Go talk to two more before dinner, and smile." },
    7: { dry: "I was ready to give up, and {a} talked me down, so now I have a plan, a small one.", loud: "I was READY to give up, and {a} talked me down! Now I have a plan!", proud: "I was close to giving up, and {a} talked me down. Now I have a plan." },
  },
  'ny.su1': { 7: { anxious: "That's the only quiet half hour I get here, and spending it with {b} makes me feel safe.", blunt: "That's my only quiet half hour. Spending it with {b} feels right.", schemer: "That's the only quiet half hour I get, and spending it with {b} feels right.", tough: "Only quiet half hour I get. Good to spend it with {b}." } },
  'nl.m3': { 1: { anxious: "We are not doing this.", earnest: "We are not doing this." } },
  'nvq.s1': { 10: { schemer: "Nobody wants to be the one who says it out loud, and {a} just doesn't mind. That's useful to me." } },
  'nl5.p1': { 3: { cruel: "Both of you? Together?", earnest: "Both of you, together?", proud: "Both of you? Together?", loud: "Both of you? TOGETHER?" } },
  'nj.p5': { 5: { blunt: "Grab an end, {a}.", goofy: "Just grab an end, {a}. It doesn't bite.", competitive: "Just grab an end, {a}.", anxious: "Just grab an end, {a}, please." } },
  'nd.st1': { 7: { ditzy: "I didn't make anything up! I just repeated it louder, and now they're watching each other instead of me.", anxious: "I didn't make anything up. I repeated it louder, and now they're watching each other, not me.", competitive: "I didn't make anything up. I repeated it louder, and now they watch each other, not me." } },
  'nk.ci2': {
    1: { loud: "We're OKAY! We were okay yesterday too!", ditzy: "We're okay! We were okay yesterday too.", anxious: "We're okay, we were okay yesterday too.", schemer: "We're okay. We were okay yesterday." },
    3: { loud: "Quiet is GOOD! Quiet means nobody's coming for us!", ditzy: "Quiet is good, it means nobody's coming for us!", anxious: "Quiet is good, quiet means nobody's coming for us.", schemer: "Quiet is good. Quiet means nobody's coming for us." },
  },
  'nrn.f3': {
    2: { loud: "NO.", proud: "No.", warm: "No." },
    3: { warm: "I can hear you chewing.", anxious: "I can hear you chewing.", calm: "I can hear you chewing.", competitive: "I can hear you chewing." },
    4: { loud: "That's the WIND.", proud: "That's the wind.", warm: "That's the wind." },
    5: { anxious: "The wind doesn't chew, {a}.", warm: "The wind doesn't chew, {a}.", dry: "The wind doesn't chew, {a}." },
    6: { loud: "FINE! Does anybody want half a cracker, because I'm offering it to the whole {quarters}!", proud: "Fine, does anybody want half a cracker? I'm offering it to the whole {quarters}.", warm: "Fine, does anybody want half a cracker? I'm sharing with the whole {quarters}." },
    7: { warm: "...Yes, actually.", anxious: "...Yes, actually.", calm: "...Yes, actually.", competitive: "...Yes, actually." },
  },
  'nd.dp1': { 3: { anxious: "I'm keeping my options open.", competitive: "I'm keeping my options open.", loud: "I'm keeping my OPTIONS open!" } },
  'nf.b1': { 1: { schemer: "Yeah. Of course.", proud: "Yes, of course.", cruel: "Yeah. Of course." } },
  'nh.b3': {
    3: { earnest: "I didn't run because I didn't see the bucket.", anxious: "I didn't run because I didn't see the bucket.", warm: "I didn't run, because I didn't see the bucket." },
    4: { loud: "So you're here by ACCIDENT!", dry: "So you're here by accident." },
  },
  'nl6.q1': {
    0: { loud: "I'll tell you what I know if you tell me what YOU know!", earnest: "I'll tell you what I know if you tell me what you know.", warm: "I'll tell you what I know, if you tell me what you know.", dry: "I'll tell you what I know if you tell me what you know. Fair trade." },
    2: { loud: "Why ME first?", earnest: "Why me first?", warm: "Why me first?", dry: "Why me first?" },
    3: { blunt: "You came to me.", quiet: "You came to me.", dry: "Because you came to me.", emotional: "Because you came to me." },
    4: { loud: "Fine! People are a LOT more nervous than they look! Two of them asked me if they're safe!", earnest: "Fine. People are more nervous than they look, and two of them asked me if they're safe.", warm: "Fine. People are more nervous than they look, and two of them asked me today if they're safe.", dry: "Fine. People are more nervous than they look, and two asked me if they're safe." },
    5: { blunt: "Who?", quiet: "Who?", dry: "Who?", emotional: "Who?" },
    6: { loud: "Your TURN.", earnest: "Your turn.", warm: "Your turn.", dry: "Your turn." },
    7: { blunt: "I heard a name this morning. Not yours.", quiet: "I heard a name. Not yours.", dry: "...Okay. I heard a name this morning, and it wasn't yours.", emotional: "...Okay. I heard a name this morning, and it wasn't yours." },
    8: { loud: "That's a START!", earnest: "That's a start.", warm: "That's a start.", dry: "That's a start." },
  },
  'nc.w4': {
    1: { nerdy: "I just didn't want to go to a vote tonight.", warm: "I just didn't want anyone going home tonight.", competitive: "I just didn't want a vote tonight." },
    3: { nerdy: "Winning makes people notice you, and I don't love being noticed.", warm: "Winning makes people notice you, and I don't really like being noticed.", competitive: "Winning makes people notice you. I don't love that." },
    4: { nerdy: "Winning makes you a target later, and losing makes you one now, so I'll take later.", warm: "Winning makes you a target later, and losing makes you one now, so I'd rather later.", competitive: "Winning makes you a target later, losing makes you one now. I'll take later." },
  },
  'nh.c1': { 7: { blunt: "{c} always sides with {b}, so now I've got two of them to deal with.", warm: "{c} always sides with {b}, every time, and now I've got two people to deal with, which hurts a bit.", theatrical: "{c} always sides with {b}, every time, and now I face two opponents instead of one!", earnest: "{c} always sides with {b}, every single time, so now I have two people to deal with." } },
  'nd.ba1': {
    1: { schemer: "Let's be honest, without me, this team would have lost every challenge.", loud: "Let's be HONEST! Without me, this team would have lost every challenge!", theatrical: "Let's be honest, darlings. Without me, this team would have lost everything.", nerdy: "Let's be honest, without me this team would have lost every challenge." },
    3: { schemer: "Am I wrong? Who won it for us last time?", loud: "Am I WRONG? Who won it for us last time?", theatrical: "Am I wrong? Who won it for us last time?", nerdy: "Am I wrong? Who won it for us last time?" },
  },
  'nar.l5': { 2: { warm: "Out of us? We barely know each other.", dry: "Out of us? We barely know each other.", earnest: "Out of us? We barely know each other." } },
  'nl.c1': { 1: { schemer: "{b}, water, and {c}, firewood.", loud: "{b}, WATER! {c}, FIREWOOD!", blunt: "{b}, water. {c}, wood." } },
  'na.x2': {
    1: { proud: "Tell me what?", competitive: "Tell me what?" },
    3: { proud: "They? Or you?", competitive: "They, or you?" },
    5: { proud: "At least you're honest.", competitive: "At least you're honest." },
  },
  'ny.d3': { 4: { blunt: "Fine. Mine is that this day is almost over.", emotional: "Fine, mine is that this day is almost over.", anxious: "Fine, mine is that this day is almost over.", loud: "FINE! Mine is that this day is almost over!" } },
  'na.d5': {
    1: { blunt: "Go on.", loud: "Go ON.", dry: "Go on.", earnest: "Go on." },
    3: { blunt: "That's a lot.", loud: "That's a LOT.", dry: "That's a lot.", earnest: "That's a lot." },
    5: { blunt: "Yes. Obviously.", loud: "YES! Obviously yes!", dry: "Yes. Obviously yes.", earnest: "Yes, obviously yes." },
    6: { blunt: "{a} would fight anybody for {a.posAdj} people. I want to be one of them.", loud: "{a} would fight ANYBODY for {a.posAdj} people! I want to be one of them!", dry: "{a} would fight anybody for {a.posAdj} people, and I'd much rather be one of them.", earnest: "{a} would fight anybody for {a.posAdj} people, and honestly, I want to be one of them." },
  },
  'nl5.f3': {
    0: { competitive: "Hey! That's three fish, and there are eight of us.", calm: "That's three fish, and there are eight of us.", warm: "Hey, that's three fish, and there are eight of us." },
    2: { competitive: "You caught them for the team. That's how it works.", calm: "You caught them for the team. That's how it works.", warm: "You caught them for the team, that's how it works." },
  },
  'nps.h2': { 0: { warm: "My name came up last night, and all I could think about was having to explain it to everyone at home.", blunt: "My name came up. All I could think was how I'd explain it at home." } },
  'npl.sc4': { 0: { loud: "{target} and {partner} are a PAIR, and pairs get to the end, so I'm splitting them up tonight!", dry: "{target} and {partner} are a pair, and pairs get to the end, so tonight I'm being the bad guy." } },
  'na.x1': {
    1: { loud: "We need to TALK.", competitive: "We need to talk.", warm: "We need to talk." },
    2: { warm: "If this is about the vote...", earnest: "If this is about the vote...", dry: "If this is about the vote..." },
    3: { loud: "It's about the VOTE.", competitive: "It's about the vote.", warm: "It's about the vote." },
    4: { warm: "I had my reasons.", earnest: "I had my reasons, honestly.", dry: "I had my reasons." },
    5: { loud: "I'm SURE you did! They just weren't {group}'s reasons!", competitive: "I'm sure you did. They weren't {group}'s.", warm: "I'm sure you did. They just weren't {group}'s reasons." },
    6: { warm: "So that's it? One vote, and I'm out?", earnest: "So that's it? One vote and I'm out?", dry: "So that's it? One vote and I'm out?" },
    7: { loud: "One vote against one of US, yeah!", competitive: "One vote against one of us. Yeah.", warm: "One vote against one of us, yeah." },
    8: { warm: "You'd have done the same thing.", earnest: "You'd have done the same thing.", dry: "You'd have done the same thing." },
    9: { loud: "MAYBE! But I'd have told you first!", competitive: "Maybe. But I'd have told you first.", warm: "Maybe, but I'd have told you first." },
  },
  'na.j6': {
    5: { earnest: "Like an alliance?", proud: "Like an alliance?", warm: "Like an alliance?", blunt: "An alliance?" },
    7: { earnest: "Okay, yes.", proud: "Yes.", warm: "Okay, yes!", blunt: "Yes." },
  },
  'nd.cl1': { 9: { food: "I'm so tired of it. {a} wants to be in charge, and all I want is for people to stop fighting about buckets so I can eat.", loud: "I'm SO tired of it! {a} wants to be in charge, and I just want everybody to stop fighting about BUCKETS!" } },
  'nd.fs2': { 4: { competitive: "Don't tell me how to sleep.", proud: "Don't tell me how to sleep.", calm: "Don't tell me how to sleep.", theatrical: "Do not tell me how to sleep." } },
  'ndp.b1': { 0: { emotional: "I don't want to hurt {friend}, I really don't, because {friend} is one of the only people I look forward to seeing every morning." } },
  'nmx.n1': { 1: { proud: "{fallen} forgot this, and I'm going to keep it, which is a little silly of me.", warm: "{fallen} forgot this, and I think I'm going to keep it. Is that silly?", dry: "{fallen} forgot this, and I think I'm keeping it, which is stupid, isn't it?", earnest: "{fallen} forgot this, and I think I'm going to keep it, honestly." } },
  'ndp.w5': { 1: { emotional: "Every time I win, the camp gets a little quieter around me, and one night I'm going to lose, and they'll be waiting." } },
  'nd.th2': {
    0: { warm: "It's weird with {lastBoot} gone.", quiet: "Weird without {lastBoot}.", emotional: "It's so weird with {lastBoot} gone." },
    1: { loud: "Yeah. It's QUIET.", emotional: "Yeah, it's quiet.", cruel: "Yeah. It's quiet.", quiet: "Quiet." },
    2: { warm: "You know, {lastBoot} was the one who kept saying we hated each other.", quiet: "{lastBoot} kept saying we hated each other.", emotional: "You know, {lastBoot} was always the one saying we hated each other." },
    3: { loud: "Did we, though?", emotional: "Did we, though?", cruel: "Did we, though?", quiet: "Did we?" },
    4: { warm: "I don't know. I did, a bit.", quiet: "I did a bit.", emotional: "I don't know, I did a bit." },
    5: { loud: "Same! Less now.", emotional: "Same, but less now.", cruel: "Same. Less now.", quiet: "Same. Less now." },
    6: { warm: "Less now.", quiet: "Less now.", emotional: "Less now." },
    7: { loud: "{lastBoot} going home changed a LOT! Turns out half my problem with {b} was coming from {lastBoot}!", emotional: "{lastBoot} going home changed so much, and a lot of my problem with {b} was coming from {lastBoot}.", cruel: "With {lastBoot} gone, I can see a lot of my problem with {b} was {lastBoot}'s doing.", quiet: "Turns out my problem with {b} came from {lastBoot}." },
  },
  'nk.tc1': { 6: { earnest: "{b} wanted to see if I'd run around camp panicking and telling everybody. I'm not telling anybody, and that test was mine to pass." } },
  'nl.p1': {
    1: { schemer: "Okay, listen up. {c} and {d} on branches, and {b}, you hold the frame.", nerdy: "Okay, listen up: {c} and {d} on branches, {b} holds the frame." },
    3: { schemer: "Somebody has to, or we sleep in the rain again.", nerdy: "Somebody has to, or we sleep in the rain again." },
    5: { theatrical: "Branches are fine. I adore branches.", dry: "Branches are fine. I like branches.", earnest: "Branches are fine, I like branches." },
    6: { dry: "Me too.", anxious: "Me too.", warm: "Me too!", blunt: "Same." },
  },
  'nly.o1': {
    1: { food: "I thought it was the money.", theatrical: "I thought it was the money.", competitive: "I thought it was the money.", anxious: "I thought it was the money." },
    2: { warm: "The money's nice, but I've spent my whole life being the quiet one in the room, and I wanted to see if I could be something else.", dry: "The money's nice, but I've been the quiet one my whole life, and I wanted to see if I could be something else.", blunt: "The money's nice. I've always been the quiet one. I wanted to see if I could be more." },
    3: { food: "And?", theatrical: "And?", competitive: "And?", anxious: "And?" },
  },
  'na.f2': {
    1: { nerdy: "Did you sleep? I didn't sleep at all.", dry: "Did you sleep? I didn't.", goofy: "Did you sleep? I didn't, I counted sheep and they all left.", warm: "Did you sleep? I didn't sleep at all." },
    3: { nerdy: "Every time it comes down to the last {item}, I'm convinced it's going to be me.", dry: "Every time it comes down to the last {item}, I'm sure it's me.", goofy: "Every time it comes down to the last {item}, I'm sure it's going to be me.", warm: "Every time it comes down to the last {item}, I'm sure it's going to be me." },
    5: { nerdy: "Because I've got people. I've got you.", dry: "Because I've got people. I've got you.", goofy: "Because I've got people. I've got you!", warm: "Because I've got people, and I've got you." },
    6: { anxious: "...Yeah. You've got me.", emotional: "...Yeah. You've got me.", proud: "...Yeah. You've got me.", competitive: "...Yeah. You've got me." },
  },
  'nd.fr1': { 2: { warm: "It wasn't funny, and it hasn't been funny for days.", anxious: "It wasn't funny. It hasn't been funny for days.", earnest: "It honestly wasn't funny, and it hasn't been for days.", blunt: "It wasn't funny. For days." } },
  'nrn.d1': {
    0: { loud: "AND SO, our hero wakes, alone, in a strange and terrible land!", theatrical: "And so, our hero awakens, alone, in a strange and terrible land." },
    2: { loud: "Our hero's tribe-mate is VERY rude before breakfast!", theatrical: "Our hero's tribe-mate is dreadfully rude before breakfast." },
    4: { loud: "A CRUEL blow! Our hero carries on!", theatrical: "A cruel blow. Yet our hero carries on." },
    5: { loud: "Everybody here thinks they're the main character! I'm just honest enough to say it OUT LOUD!", theatrical: "Everybody here believes they're the main character. I simply have the courage to narrate it." },
  },
  'ng.s1': {
    2: { competitive: "What's going on?", warm: "What's going on?", proud: "What's going on?" },
    3: { competitive: "My name's out there, I can feel it, and I need two votes to make it close.", dry: "My name's out there, I can feel it, and I need two votes to make it close.", proud: "My name is out there, and I need two votes to make it close.", warm: "My name's out there, I can feel it, and I just need two votes to make it close." },
    4: { dry: "Close doesn't save you.", quiet: "Close doesn't save you.", blunt: "Close won't save you.", loud: "Close doesn't SAVE you!" },
    5: { competitive: "Close makes people nervous, and nervous people change their minds.", dry: "Close makes people nervous, and nervous people change their minds.", proud: "Close makes people nervous, and nervous people change their minds.", warm: "Close makes people nervous, and nervous people change their minds." },
    6: { competitive: "And what do we get?", warm: "And what do we get?", proud: "And what do we get?" },
    7: { competitive: "Me, on your side, for the rest of the game.", dry: "Me, on your side, for the rest of the game. Lucky you.", proud: "Me, on your side, for the rest of the game.", warm: "Me, on your side, for the rest of the game." },
    8: { dry: "We'll think about it.", quiet: "We'll think about it.", blunt: "We'll think about it.", loud: "We'll THINK about it." },
    10: { competitive: "If I talk to them together, they can't tell each other different stories about what I said, which is smart, I hope.", dry: "If I talk to them together, they can't compare different stories. Smart, hopefully." },
  },
  'nv.y5': { 4: { competitive: "You'll get something back. I won't forget.", proud: "You'll get something back. I don't forget.", schemer: "You'll get something back. I won't forget." } },
  'na.n3': {
    1: { loud: "Wow. Good MORNING to you too.", calm: "Wow. Good morning to you too.", warm: "Wow, good morning to you too.", blunt: "Good morning to you too." },
    3: { loud: "We could TRY to fix it!", calm: "We could try to fix it.", warm: "We could try to fix it, you know.", blunt: "We could fix it." },
    5: { loud: "FINE! Don't come to me when you need a vote!", calm: "Fine. Don't come to me when you need a vote.", warm: "Fine, but don't come to me when you need a vote.", blunt: "Fine. Don't come to me for votes." },
    7: { loud: "{a} just blew up the only group keeping {a.obj} safe! I'm not stopping {a.obj}!", calm: "{a} just blew up the only group keeping {a.obj} safe, and I'm not going to stop {a.obj}.", warm: "{a} just blew up the only group that was keeping {a.obj} safe, and I'm too tired to stop {a.obj}.", blunt: "{a} blew up the group keeping {a.obj} safe. I'm not stopping {a.obj}." },
  },
  'nvr.o1': {
    0: { warm: "So, who? I really don't want it to be anybody I like.", loud: "So WHO? I really don't want it to be anybody I like!" },
    1: { quiet: "Then it's {target}. Have you talked to {target} this week?", dry: "Then it's {target}. Have you had one real conversation with {target} this week?", nerdy: "Then it's {target}. Have you had a meaningful conversation with {target} this week?", loud: "Then it's {target}! Have you had a REAL conversation with {target} this week?" },
    3: { calm: "Me neither. {target} goes off alone every chance there is.", warm: "Me neither. {target} goes off alone every chance there is.", dry: "Me neither. {target} goes off alone at every opportunity.", earnest: "Me neither, honestly. {target} goes off alone every chance there is." },
    4: { quiet: "So if {target} goes, nobody cries and nobody comes after us.", dry: "So if {target} goes, nobody's crying, nobody's angry, and nobody's coming after us.", nerdy: "So if {target} leaves, nobody's upset, and nobody retaliates.", loud: "Right! So if {target} goes, nobody's crying, nobody's ANGRY, nobody's coming after us!" },
    6: { quiet: "It's the least mean option. Any other name hurts someone.", dry: "It's the least mean option we have. Every other name, somebody gets hurt.", nerdy: "It's the least harmful option available. Every other name hurts someone.", loud: "It's the LEAST mean option! Every other name, somebody gets hurt!" },
  },
  'nk.dd1': {
    0: { theatrical: "So I'm not the only one, am I?", tough: "So I'm not the only one.", earnest: "So I'm not the only one, am I?", nerdy: "So I'm not the only one, am I?" },
    2: { theatrical: "The only person you promised the end to.", tough: "The only one you promised the end to.", earnest: "The only person you promised the end to.", nerdy: "The only person you promised the end to." },
    4: { theatrical: "Does it matter? You're not saying no.", tough: "Does it matter? You're not saying no.", earnest: "Does it matter? You're not saying no.", nerdy: "Does it matter? You haven't said no." },
  },
  'nd.dg3': {
    1: { dry: "We will, especially if some of us work out which way the finish line is.", theatrical: "We will! Especially if certain people can find the finish line.", competitive: "We will, if some of us figure out which way the finish line is.", ditzy: "We will! Especially if some of us figure out where the finish line is." },
    2: { proud: "That was one time.", earnest: "That was one time." },
    3: { dry: "I didn't say who.", theatrical: "I didn't say who, darling.", competitive: "I didn't say who.", earnest: "I didn't say who." },
  },
  'fd.g2': {
    2: { blunt: "We've been here eight hours.", competitive: "We've been here like eight hours.", schemer: "We've been here like eight hours." },
    4: { loud: "My plan is to NOT go home first!", theatrical: "My plan is simply not to go home first." },
  },
  'nj.p3': { 1: { earnest: "Sounds good, what do you need?" } },
  'fp.x1': {
    1: { loud: "I was ABOUT to, yeah!", theatrical: "I was about to, yes." },
    5: { loud: "I've known {a} for ONE day, and that's more than enough!", theatrical: "I've known {a} for one day, and that is more than enough." },
  },
  'ny.m3': {
    0: { proud: "Okay, we're ranking the food, worst to least worst. Go.", calm: "Okay, we're ranking the food, worst to least worst." },
    3: { proud: "Wrong, day two was the worst, because day two moved.", calm: "Wrong, day two was the worst, because day two moved." },
    4: { quiet: "It didn't move.", warm: "It did not move!" },
    5: { proud: "It moved! I saw it!", calm: "It moved. I saw it." },
  },
  'nl.p2': {
    3: { loud: "We're not beating ANYBODY by fixing a fire pit!", schemer: "We're not beating anybody by fixing a fire pit." },
    4: { anxious: "We might be. Their fire pit is terrible.", calm: "We might be. Their fire pit is terrible.", earnest: "We might be, honestly, their fire pit is terrible." },
  },
  'nl.n1': { 3: { schemer: "The waiting, and the pretending we're all fine.", food: "The waiting, and the pretending we're all fine.", earnest: "The waiting, and the pretending we're all fine." } },
  'nly.l1': {
    2: { ditzy: "Singing! Join in, it's the only song I know all the words to!", schemer: "Singing. Join in, it's the only song I know all the words to.", proud: "Singing. Join in, it's the only song I know all the words to." },
    4: { ditzy: "And it slaps!", schemer: "And it slaps.", proud: "And it slaps." },
  },
  'nv4.n4': {
    6: { proud: "I'm keeping an eye on {shaky}, who has been quiet all day.", loud: "I'm keeping an EYE on {shaky}! {shaky} has been quiet all day!", calm: "I'm keeping an eye on {shaky}, who's been quiet all day." },
    7: { warm: "Not if we stop talking about it and go eat.", loud: "Not if we stop TALKING about it and go eat!" },
  },
  'nm.n2': { 3: { earnest: "I don't know, maybe?", dry: "I don't know. Maybe?" } },
};
