// Turn the bios already written into voice profiles into UPDATE statements.
//
//   node worker/build_bio_backfill.mjs > worker/roster_bio_backfill.sql
//   npx wrangler d1 execute dc-franchise --remote --file roster_bio_backfill.sql
//
// Twenty-five characters have had an age, an origin and an orientation since the
// day they were created — sitting at the front of their voice profile as a
// sentence, because that is the one field the episode writer reads. This reads
// them back out with the same parser the Studio now uses and writes them into
// the columns, so nobody retypes anything.
//
// Safe to re-run: every statement is an UPDATE keyed on slug, and the parser is
// deterministic. It writes only characters whose profile actually has a lead-in,
// so it can never blank a field that was filled in by hand afterwards.
import { readFileSync } from 'node:fs';
import { parseBio } from '../js/bio.js';

const profiles = JSON.parse(readFileSync(new URL('../voice-profiles.json', import.meta.url), 'utf8')).profiles;
const roster = JSON.parse(readFileSync(new URL('../franchise_roster.json', import.meta.url), 'utf8'));
const list = Array.isArray(roster) ? roster : (roster.players || roster.roster || []);
const slugOf = new Map(list.map(p => [p.name, p.slug]));

const q = v => (v === null || v === undefined || v === '') ? 'NULL' : `'${String(v).replace(/'/g, "''")}'`;

const lines = [
  '-- Generated by worker/build_bio_backfill.mjs — do not edit by hand.',
  '-- Reads the bio lead-in out of each voice profile and fills the columns.',
  '',
];
let n = 0;

for (const [name, text] of Object.entries(profiles)) {
  const bio = parseBio(text);
  if (bio.age == null && !bio.ethnicity && !bio.nationality) continue;
  const slug = slugOf.get(name);
  if (!slug) {
    // A character with a profile and no roster row cannot be updated. Say so in
    // the output rather than silently writing 24 of 25 rows.
    lines.push(`-- SKIPPED ${name}: no roster row with that name`);
    continue;
  }
  lines.push(
    `UPDATE roster SET age = ${bio.age ?? 'NULL'}, ethnicity = ${q(bio.ethnicity)}, `
    + `nationality = ${q(bio.nationality)}, descriptor = ${q(bio.descriptor)} `
    + `WHERE slug = ${q(slug)};`);
  n++;
}

lines.push('', `-- ${n} characters carried a bio.`);
console.log(lines.join('\n'));
