#!/usr/bin/env python3
"""Seed the D1 `roster` table from the existing franchise_roster.json.

Reads franchise_roster.json (+ voice-profiles.json for the voice text) and writes
roster_seed.sql. Never modifies either input.

Run:   python worker/build_roster_seed.py
Then:  cd worker && npx wrangler d1 execute dc-franchise --remote --file roster_seed.sql
"""

import json
import os

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)

STATS = ['physical', 'endurance', 'mental', 'social', 'strategic',
         'loyalty', 'boldness', 'intuition', 'temperament']


def sql(v):
    if v is None or v == '':
        return 'NULL'
    if isinstance(v, bool):
        return '1' if v else '0'
    if isinstance(v, (int, float)):
        return str(v)
    return "'" + str(v).replace("'", "''") + "'"


with open(os.path.join(ROOT, 'franchise_roster.json'), encoding='utf-8') as f:
    players = json.load(f).get('players', [])

voices = {}
vpath = os.path.join(ROOT, 'voice-profiles.json')
if os.path.exists(vpath):
    with open(vpath, encoding='utf-8') as f:
        voices = json.load(f).get('profiles', {})
# voice-profiles.json is keyed by display NAME, the roster by slug
voices_lc = {str(k).strip().lower(): v for k, v in voices.items()}

lines = [
    '-- GENERATED by worker/build_roster_seed.py. Do not hand-edit; regenerate instead.',
    '-- Wipes and refills the roster table from franchise_roster.json. Re-runnable.',
    '',
    'DELETE FROM roster;',
    '',
]

seen = set()
skipped = []
with_voice = 0

for p in players:
    slug = str(p.get('slug') or '').strip().lower()
    name = str(p.get('name') or '').strip()
    if not slug or not name:
        skipped.append(p.get('name') or p.get('slug'))
        continue
    if slug in seen:
        skipped.append(f'{slug} (duplicate)')
        continue
    seen.add(slug)

    st = p.get('stats') or {}
    voice = voices_lc.get(name.lower())
    if voice:
        with_voice += 1

    cols = [sql(slug), sql(name), sql(p.get('gender')), sql(p.get('sexuality')),
            sql(p.get('archetype'))]
    cols += [sql(st.get(s)) for s in STATS]
    cols += [sql(voice), '1' if p.get('isReturnee') else '0', '0', "datetime('now')"]

    lines.append(
        'INSERT INTO roster (slug,name,gender,sexuality,archetype,'
        + ','.join(STATS)
        + ',voice,is_returnee,retired,updated_at) VALUES ('
        + ','.join(cols) + ');'
    )

lines.append('')
out = os.path.join(HERE, 'roster_seed.sql')
with open(out, 'w', encoding='utf-8') as f:
    f.write('\n'.join(lines))

print(f'wrote {out}')
print(f'  characters : {len(seen)}')
print(f'  with voice : {with_voice}')
if skipped:
    print(f'  ! skipped {len(skipped)}: {skipped[:10]}')
