-- Rankings table (step 2 of moving the derived databases into D1).
-- Apply with:  npx wrangler d1 execute dc-franchise --remote --file rankings_schema.sql
-- Safe to re-run.
--
-- Mirrors rankings_database.json, which is DERIVED — regenerated by the export
-- after each season and refreshed into D1 by POST /api/sync-seasons. Never edit
-- this table by hand; the next sync overwrites it.

CREATE TABLE IF NOT EXISTS rankings (
  player_id  TEXT PRIMARY KEY,     -- -> players.id / roster.slug
  name       TEXT,
  rank       INTEGER,              -- 1 = top of the franchise
  tier       TEXT,                 -- "S+", "A", ...
  score      REAL,
  title      TEXT,                 -- "The Snake Charmer"
  emoji      TEXT,                 -- AI-assigned, used by devotees.html
  status     TEXT,

  avg_placement  REAL,
  win_rate       REAL,
  wins           INTEGER,
  seasons_played INTEGER,
  challenge_wins INTEGER,
  votes_against  INTEGER,
  jury_votes     INTEGER,
  idols_found    INTEGER,

  placement_percentile REAL,
  win_percentile       REAL,
  challenge_percentile REAL,
  social_percentile    REAL,
  strategic_percentile REAL,

  -- Prose and lists are stored as-is: they're for display, not for querying.
  reasoning  TEXT,
  strengths  TEXT,                 -- JSON array
  weaknesses TEXT                  -- JSON array
);

-- Leaderboard-style reads walk this in rank order.
CREATE INDEX IF NOT EXISTS idx_rankings_rank ON rankings (rank);
CREATE INDEX IF NOT EXISTS idx_rankings_tier ON rankings (tier, rank);
