-- Generated by worker/build_bio_backfill.mjs — do not edit by hand.
-- Reads the bio lead-in out of each voice profile and fills the columns.

UPDATE roster SET age = 22, ethnicity = NULL, nationality = NULL, descriptor = NULL WHERE slug = 'stanley';
UPDATE roster SET age = 23, ethnicity = 'Latino', nationality = NULL, descriptor = NULL WHERE slug = 'zachary';
UPDATE roster SET age = 25, ethnicity = NULL, nationality = 'Nigerian', descriptor = NULL WHERE slug = 'obi';
UPDATE roster SET age = 19, ethnicity = NULL, nationality = NULL, descriptor = NULL WHERE slug = 'arlo';
UPDATE roster SET age = 21, ethnicity = NULL, nationality = NULL, descriptor = 'Scouse' WHERE slug = 'doug';
UPDATE roster SET age = 32, ethnicity = NULL, nationality = NULL, descriptor = NULL WHERE slug = 'jeremiah';
UPDATE roster SET age = 22, ethnicity = NULL, nationality = NULL, descriptor = NULL WHERE slug = 'avani';
UPDATE roster SET age = 65, ethnicity = NULL, nationality = NULL, descriptor = NULL WHERE slug = 'dameira';
UPDATE roster SET age = 27, ethnicity = NULL, nationality = NULL, descriptor = NULL WHERE slug = 'nessa';
UPDATE roster SET age = 20, ethnicity = NULL, nationality = NULL, descriptor = NULL WHERE slug = 'drea';
UPDATE roster SET age = 16, ethnicity = NULL, nationality = 'Japanese', descriptor = NULL WHERE slug = 'hina';
UPDATE roster SET age = 23, ethnicity = NULL, nationality = NULL, descriptor = NULL WHERE slug = 'natasha';
UPDATE roster SET age = 24, ethnicity = NULL, nationality = 'Canadian', descriptor = NULL WHERE slug = 'aaron';
UPDATE roster SET age = 18, ethnicity = NULL, nationality = 'American', descriptor = NULL WHERE slug = 'amberly';
UPDATE roster SET age = 27, ethnicity = NULL, nationality = 'British', descriptor = NULL WHERE slug = 'dylon';
UPDATE roster SET age = 35, ethnicity = NULL, nationality = 'Brazilian', descriptor = NULL WHERE slug = 'felipe';
UPDATE roster SET age = 24, ethnicity = NULL, nationality = NULL, descriptor = NULL WHERE slug = 'gyselle';
UPDATE roster SET age = 21, ethnicity = 'Asian', nationality = 'Canadian', descriptor = NULL WHERE slug = 'harriett';
UPDATE roster SET age = 21, ethnicity = 'Asian', nationality = 'Canadian', descriptor = NULL WHERE slug = 'jane';
UPDATE roster SET age = 25, ethnicity = 'Arab', nationality = NULL, descriptor = NULL WHERE slug = 'hasan';
UPDATE roster SET age = 26, ethnicity = NULL, nationality = NULL, descriptor = NULL WHERE slug = 'ireland';
UPDATE roster SET age = 26, ethnicity = NULL, nationality = 'American', descriptor = NULL WHERE slug = 'joel';
UPDATE roster SET age = 29, ethnicity = NULL, nationality = 'Puerto Rican', descriptor = NULL WHERE slug = 'jules';
UPDATE roster SET age = 23, ethnicity = NULL, nationality = 'American', descriptor = NULL WHERE slug = 'misha';
UPDATE roster SET age = 34, ethnicity = NULL, nationality = 'American', descriptor = 'Italian' WHERE slug = 'nico';
UPDATE roster SET age = 29, ethnicity = NULL, nationality = 'American', descriptor = NULL WHERE slug = 'stella';
UPDATE roster SET age = 19, ethnicity = NULL, nationality = NULL, descriptor = NULL WHERE slug = 'tobias';
UPDATE roster SET age = 20, ethnicity = 'Mixed', nationality = 'Canadian', descriptor = 'Mexican' WHERE slug = 'zella';

-- 28 characters carried a bio.
