// td/story/kits/kits-deep.js — two more parts for every kit, for the scenes whose heat depends on the pair
//   defend  a, when somebody who doesn't like them sneers at their thing (Dunia, when Nura called her
//           witchcraft a brand: "This isn't some aesthetic. It's my religion.")
//   deep    a, to somebody they trust: the true thing under the bit
// Merged into the kits by kits/index.js.

export default {
  Alejandro: { defend: ["You can mock my manners all you like. They're the reason everybody here still listens to me."], deep: ["My brother José used to call me Al to make me feel small. I've spent my whole life making sure nobody can."] },
  Bowie: { defend: ["I'm loud because I'm good at this. You don't get to make that sound like a flaw."], deep: ["Sometimes I'm not sure people like me or just like watching me. I think that's why I perform so hard."] },
  DJ: { defend: ["Being kind isn't weak, man. My mama raised me this way, and I'm not changing it for a game."], deep: ["I get scared a lot more than people think. I just don't want anybody else to be scared too."] },
  Gwen: { defend: ["I don't need you to get it. I just need you to leave it alone."], deep: ["I act like I don't care what people think. I care. I just got tired of losing myself trying to fit in."] },
  Julia: { defend: ["Laugh all you want. I built a brand from nothing, and that's more than you've ever done."], deep: ["The influencer thing is a costume. I'm not sure anymore what's under it. That scares me more than losing."] },
  Mike: { defend: ["I've been laughed at for a lot worse than being nervous. It doesn't work on me anymore."], deep: ["I hid parts of myself for years because I thought nobody could handle them. Some days I still feel like I'm hiding."] },
  Millie: { defend: ["Taking notes isn't the same as judging. Okay, it's a little the same. But it's also how I understand things."], deep: ["I write about people because I never knew how to be with them. I'd really like to learn. Out here, maybe."] },
  Thom: { defend: ["Keeping people safe isn't a joke to me. It never will be."], deep: ["Something happened on the job I still can't talk about. Out here, nobody needs me to be okay all the time. That's new."] },
  Miriam: { defend: ["I've earned every one of these years, dear. Don't you dare make them sound like a weakness."], deep: ["My husband and my son died the same night. A drunk driver. I don't talk about it. I don't know why I'm telling you."] },
  Grett: { defend: ["My body is my job. I'm not going to apologise for being good at it."], deep: ["I've spent so long making people see me a certain way. I'm not sure anybody's ever actually seen me."] },
  Gabby: { defend: ["They're not just pets. They're my family. Say it again and see what happens."], deep: ["There's a voice in my head that says the meanest thing it can. I don't always know which one of us is talking."] },
  James: { defend: ["Half a million people chose to watch me. You can sneer, but they chose."], deep: ["For years the only person who talked to me was my sister. The followers were just proof I existed."] },
  Lake: { defend: ["Precision isn't coldness. It's caring enough to do something properly."], deep: ["My parents controlled everything. My clothes, my hair, my future. Out here, every choice is mine, and it terrifies me."] },
  Yul: { defend: ["You're just upset someone finally said it out loud."], deep: ["When I went viral, everybody loved me. When they stopped, I didn't know who I was without it."] },
  Natalia: { defend: ["Babes, gossip is how I survived. I'm not about to be ashamed of it for you."], deep: ["When I came out, I was terrified nobody would stay. My family did. I don't take people staying for granted."] },
  Natasha: { defend: ["I feel things a lot. That's not something you get to make me feel stupid about."], deep: ["I fall for people so fast because I'm scared that if I wait, they'll leave first."] },
  Aaron: { defend: ["I don't owe anyone my life story."], deep: ["The scar's from a job. A tree came down wrong. It was my call. Somebody else got hurt worse. That's all I'll say."] },
  Amberly: { defend: ["Y'all can laugh at the crowns. I earned every single one of 'em, and I'll earn this too."], deep: ["Back home everybody knows my family. Out here nobody does, and I don't know who I am without 'em."] },
  Dylon: { defend: ["Mock the money all you want, mate. It's paid for everything I've ever needed."], deep: ["My parents still bring up the degree. Every Christmas. Doesn't matter what I earn."] },
  Felipe: { defend: ["Laugh at my art, amor, and you laugh at the only thing that never left me."], deep: ["My family barely speaks to me since I came out. My brother calls in secret. I love him for it, and I hate that it's a secret."] },
  Gyselle: { defend: ["Modelling's a real job. Do you know how hard it is to look this calm on a nine-hour shoot?"], deep: ["I agree with whoever's strongest because I'm scared of being the one people don't like. I know. I'm working on it."] },
  Harriett: { defend: ["Somebody has to run things. You don't get to complain about it and also not do it."], deep: ["I talk for Jane because I'm scared she'll get hurt if I don't. I know she doesn't need me to. I just don't know how to stop."] },
  Jane: { defend: ["...Being quiet doesn't mean I have nothing to say. It means I'm choosing."], deep: ["I write love stories because I don't know how to say any of it out loud. Maybe one day I will."] },
  Hasan: { defend: ["Speaking carefully is not arrogance. It is respect for the truth."], deep: ["My father died when I was young. I became the man of the house at eleven. I do not know how to stop being responsible for everyone."] },
  Ireland: { defend: ["You call it cold. I call it surviving."], deep: ["I left home at sixteen. Nobody came looking. I've been playing alone ever since."] },
  Joel: { defend: ["Call me a meathead one more time, bro. I dare you. In any of my three languages."], deep: ["My whole family only ever talked about my football. I wanted somebody to ask me what I actually think about things."] },
  Jules: { defend: ["Caring about people isn't a trick, mi vida. Even if I care about a few too many."], deep: ["I raised my brothers and sisters because nobody else would. Sometimes I don't know how to be anybody's but theirs."] },
  Misha: { defend: ["I say what I say to your face. You don't get to call that rude just because it hurt."], deep: ["When my Nana gets sick, I'm going to be lost. I think about it every time I'm far away from her."] },
  Nico: { defend: ["Fixing things isn't small. Ask anybody whose bike I've saved."], deep: ["Shared custody's hard. Every other week I come home to a quiet house. That's the part nobody tells you."] },
  Stella: { defend: ["Now that's just not nice. Being a mother is the hardest job I've ever done."], deep: ["I love my babies more than anything. But sometimes I forget who I was before them, and that scares me."] },
  Tobias: { defend: ["Streaming's a real job. I pay rent with it. Do you?"], deep: ["My dad still thinks I'm wasting my life. I came here to show him. I don't know if it'll be enough."] },
  Zella: { defend: ["Laugh at my band all you want. We're going to be huge. And then you'll pretend you knew."], deep: ["I yell because if I talk normally, I'll cry. I hate crying. So I yell."] },
  Aubrey: { defend: ["It's not a joke to me, okay? It's how I make sense of people. You're not better than me for not believing."], deep: ["I was so shy as a kid. Astrology gave me a way to talk to people. It still kind of does."] },
  Ara: { defend: ["Ambition isn't a character flaw. It's the only thing that's ever worked for me."], deep: ["My parents gave up everything for love. I watched what it cost them. I'm never doing that."] },
  Bruno: { defend: ["I know I talk about it a lot. But being useful is the only time I feel like I'm actually good at something."], deep: ["I applied to this show four times. Four. I always felt like I wasn't the kind of person they'd pick."] },
  Dunia: { defend: ["This isn't some aesthetic or a cute hobby. It's my religion. My belief. Not something I do to feel special."], deep: ["People laughed at me for years. So now I laugh first, so nobody can see that it still gets to me."] },
  Ernesto: { defend: ["Experience is not something to mock, young one. One day you will have some, if you are lucky."], deep: ["My children are grown. They do not call as much as they used to. Out here, at least, people need me."] },
  Evie: { defend: ["Well, I think I'm very interesting, actually. Money doesn't make you boring, darling. It just makes you rested."], deep: ["Everybody thinks I've had an easy life. I have. And I've never once been sure anybody liked me for me."] },
  Finn: { defend: ["Theatre saved my life, darling. Mock it and you're mocking the only thing I'm good at."], deep: ["Everyone at drama school is better than me. I just say I'm the best first, so nobody else gets to say I'm not."] },
  Manu: { defend: ["Hey. You can laugh at me, but you don't laugh at my friends."], deep: ["I wasn't a great example when I was young. Then Aleki was born, and I realised somebody was watching me. I changed for him."] },
  Nura: { defend: ["Being negative isn't a personality. It's just accurate."], deep: ["I'm stuck. Same job, same flat, same everything. I came here because I was scared I'd stay stuck forever."] },
  Oliwia: { defend: ["It's not creepy. It's love. I keep things so they don't disappear."], deep: ["I didn't have any friends growing up. The animals were the only ones who stayed. I don't want to be alone again."] },
  Ren: { defend: ["I'm weird. You're boring. Only one of those is a problem, and it's not mine."], deep: ["Some places weren't kind to me. I learned to make people laugh before they could decide what I was."] },
  Sami: { defend: ["Numbers don't lie. People do. I'd rather trust the numbers."], deep: ["I was married once. I read every risk except that one. I'm still not sure what I missed."] },
  'Anita Crown Davenport': { defend: ["Thank you so much for that, but pageants taught me more than you'd think. Like how to smile through this."], deep: ["First alternate eleven times. Sometimes I wonder if I'm just good enough to almost win."] },
  Autumnatic: { defend: ["My looks are art, baby. Ugly art is still art."], deep: ["I make everybody laugh so nobody notices I'm not sure my work is any good."] },
  'Cheryl Hole': { defend: ["I know I'm a mess. I'm a happy mess. That's more than you can say."], deep: ["I laugh at myself first because when I was a kid, everybody else got there first."] },
  Cupcakke: { defend: ["Funny doesn't mean silly, sweetie. It takes more skill to make you laugh than to make you cry."], deep: ["Local queens never took me seriously. I want somebody to, just once."] },
  'Gigi Cherie': { defend: ["Silence is not emptiness. It is a choice. A very elegant one."], deep: ["I started miming because I was too shy to speak on stage. Now I'm not sure I know how to stop."] },
  'Ginger Hollywood': { defend: ["Twenty years at the top isn't luck, darling. It's work. You'd know if you'd done any."], deep: ["I'm forty-two. In my world, that's ancient. This might be my last big stage, and I know it."] },
  'Marge Stache': { defend: ["Caring about everybody's business is caring about everybody. That's not a flaw."], deep: ["I collect everybody's secrets so nobody looks too hard at mine."] },
  'Minnie Skurr': { defend: ["Laugh all you want, babe. I'll be dancing on the finale stage."], deep: ["I'm the youngest here, and some days I feel like everybody can see I'm making it up as I go."] },
  'Paige Turner': { defend: ["Young lady, I have been reading people for twenty years. Do not attempt to read me."], deep: ["Twenty years of making people laugh. Sometimes I wonder if anyone would stay if I stopped."] },
  Quin: { defend: ["My work has meaning. You just haven't done the reading."], deep: ["People see a model and stop looking. I'm trying to make them look longer."] },
  Riot: { defend: ["If my activism makes you uncomfortable, you're exactly who it's for."], deep: ["I've buried too many friends who didn't make it. Every vote, every fight, I'm doing it for them."] },
  'Sharon Needles': { defend: ["Darling, I'm the villain because villains get remembered. You'll be forgotten by Thursday."], deep: ["Controversy keeps my name out there. Without it, I'm not sure anybody would remember me at all."] },
  Taystee: { defend: ["Being beautiful is a talent. Not everyone has it. Clearly."], deep: ["Every agency said no. I'm still not sure I believe I'm beautiful. I just say it until it sounds true."] },
  'Velvet Vixen': { defend: ["I'm not doing too much. I'm doing exactly enough, and you can't keep up."], deep: ["Every audition treated me like I was interchangeable. Velvet is the first time I've been the one they look at."] },
};
