// td/story/kits/kits1.js — character kits, batch 1 (written from each roster profile: voice, occupation,
// descriptor, backstory, personality, casting interview). bit[i] / tease[i] / reply[i] are one exchange.
// {a} is the kit's owner; in tease, the one speaking is somebody else, talking to {a}.

export default {
  Alejandro: {
    thing: 'how charming he is',
    bit: [
      "You've been carrying water all morning. Here, let me take that, a beautiful person shouldn't have to do the heavy lifting.",
      "My family always said a gentleman is judged by how he treats people when nobody is watching. Lucky for you, someone always is.",
      "I don't need to win every challenge. I just need everybody to want me on their side when it matters.",
    ],
    tease: [
      "Does that line actually work on people, Al?",
      "Is everything you say rehearsed, or just the compliments?",
      "That's the creepiest thing anybody's said to me this week.",
    ],
    reply: [
      "Never call me Al. And yes, it works. You're still holding the bucket, aren't you?",
      "Everything worth saying is rehearsed. The trick is making it sound like it isn't.",
      "Creepy is a strong word. I'd say prepared.",
    ],
    home: ["My parents, my uncle, and two older brothers who will be watching to see me lose. I'm not going to give them the satisfaction.",
      "A family that measures everything. Grades, trophies, money. Winning this is the only thing José won't have done first."],
    want: ["To win, obviously. And to never have to hear José's voice say I came second.", "Respect. Money comes with it. Respect doesn't, you have to take it."],
    conf: ["Everyone here thinks they're watching me. I'm the one doing the watching.",
      "A kind word costs nothing and buys almost everything. People are so cheap to purchase."],
    askHome: ["Tell me, who's waiting for you back home? I'm genuinely curious.", "Do you have someone at home? You must, a person like you."],
    askWant: ["And what is it you really want from all this? Be honest, I'll know if you're not.", "Everyone wants something here. What's yours?"],
  },
  Bowie: {
    thing: 'being a theatre kid',
    bit: [
      "Okay, nobody panic, but I've been rehearsing my reaction for when we win, and it involves a split.",
      "I was prom king AND prom queen, so I think I can handle a team captain election, thank you.",
      "If we lose today, I want everyone to know I'm going to cry, and it's going to be beautiful.",
    ],
    tease: [
      "Please don't do the split. Your knees are on our team.",
      "Is there anything you haven't been crowned?",
      "Can you cry quieter than last time, at least?",
    ],
    reply: [
      "My knees are trained professionals. They'll be fine.",
      "Not yet. That's what this show is for.",
      "Absolutely not. If I'm crying, I'm giving it everything.",
    ],
    home: ["My mom, who has watched every musical I've ever been in, including the ones where I was a tree.",
      "My friends from the theatre. They made me promise to win and also to name an alliance after a Broadway show."],
    want: ["Another crown. I don't care what it's made of.", "To be the one everybody remembers, and to win. In that order, honestly."],
    conf: ["I love these people. I'm also going to beat them. Both of those things are true.",
      "People think drama is a distraction. It's information. Who cries, who yells, who goes quiet. I'm taking notes."],
    askHome: ["Okay, tell me everything. Who's at home? Partner? Pets? A secret twin?", "Who are you doing this for back home?"],
    askWant: ["What's the dream, though? Like the real one, not the one you'd say in the audition tape.", "If you win, what's the first thing you do?"],
  },
  DJ: {
    thing: 'how soft he is',
    bit: [
      "I saved everybody some of the fish. I cooked it like my mama does, with the lemon, except we don't have a lemon.",
      "There's a bird nest by the shelter. Can we please not build anything near it? She's got babies.",
      "I'm fine with the dark. I'm fine with it. Is anybody else maybe a little not fine with it?",
    ],
    tease: [
      "You know we're supposed to be competing, right, not running a restaurant?",
      "Are you going to ask the bird for permission to sleep, too?",
      "You're the biggest guy here, man. The dark should be scared of you.",
    ],
    reply: [
      "Nobody competes good hungry. Eat your fish.",
      "If she says no, we move the shelter. That's just manners.",
      "That's what everybody says. The dark doesn't care how big you are.",
    ],
    home: ["My mama. She taught me to cook and to say thank you, and she's going to be so mad if I forget either.",
      "My mom and a whole lot of animals. I volunteer at a shelter back home. Those dogs are probably wondering where I went."],
    want: ["Enough money to buy my mama a house with a real kitchen.", "I want to get through this without being mean to anybody. And, you know, win."],
    conf: ["People see how big I am and think I'm scary. I'm not. I cried at a commercial last week.",
      "I don't like voting people out. I never will. I'm just trying to make sure the good ones stay."],
    askHome: ["You got family back home? They must miss you.", "Who's taking care of things for you while you're here?"],
    askWant: ["What would you do with the money? For real.", "What made you want to come out here?"],
  },
  Gwen: {
    thing: 'being goth',
    bit: [
      "Great. Sunshine. My favourite.",
      "If anyone has a black marker, I'll trade you half my rice. I'm running out of eyeliner.",
      "You know there's a meteor shower this week? It's the only thing out here I'm actually looking forward to.",
    ],
    tease: [
      "You could just, I don't know, smile for once?",
      "You're trading food for makeup. Out here.",
      "Do you have a single interest that isn't in the dark?",
    ],
    reply: [
      "I could. I'm choosing not to.",
      "Priorities. You'll understand when you're older.",
      "Horror movies. Also in the dark. So, no.",
    ],
    home: ["My mom, my brother, and my nana, who dyes her hair purple to match mine. She's cooler than all of you.",
      "My sketchbook, my drum kit, and a bed that isn't made of sticks. Not necessarily in that order."],
    want: ["To get through this without pretending to be somebody I'm not.", "The money. I'm not going to lie and say it's about the experience."],
    conf: ["Everybody here is so desperate to be liked. I'll take being trusted by two people over being liked by everyone.",
      "I don't do fake. If that makes me a target, fine. At least I'll go home as me."],
    askHome: ["So who's waiting for you back home? Or is that too personal?", "You have people at home? Real ones, I mean."],
    askWant: ["Why are you actually here? And don't say 'the experience'.", "What do you want out of this? The honest answer."],
  },
  Julia: {
    thing: 'being an influencer',
    bit: [
      "Okay, this light is actually gorgeous. If we had a phone, this would get so much engagement.",
      "I'm a citizen of Mother Earth, so honestly, sleeping outside is kind of my brand.",
      "Babe, your posture. I'm not being mean, I'm being honest. People respect honesty.",
    ],
    tease: [
      "We don't have phones. Nobody's watching except the cameras.",
      "Didn't you complain about a bug for twenty minutes yesterday?",
      "That was definitely mean.",
    ],
    reply: [
      "The cameras are the phones now. Smile.",
      "Mother Earth and I are working through some things.",
      "It was honest. Being honest just sounds mean when you're not used to it.",
    ],
    home: ["My parents run a bake shop. I used to work there. Now I have, like, a platform.",
      "My followers, mostly. And my sister, Megan, who is going to hate how good I look on TV."],
    want: ["To win, and to be the most talked-about person on this show. Both is ideal.", "A bigger platform. Money's nice. Attention lasts longer."],
    conf: ["The trick is, you smile while you say it. Then they don't even notice they've been cut.",
      "They all think I'm a ditzy influencer. Good. Ditzy influencers don't get voted out first."],
    askHome: ["Who's your support system back home? I love that for you, whoever it is.", "So who are you going home to? Be honest."],
    askWant: ["What's your brand here, though? Like, what do you want people to say about you?", "What are you actually after? Everybody's after something."],
  },
  Mike: {
    thing: 'how nervous he gets',
    bit: [
      "Sorry, is this anybody's spot? I can move. I'll move. I'm moving.",
      "I'm not freaking out about the challenge. I'm just checking where all the exits are. Normal stuff.",
      "I did some improv back home, so if anyone needs a distraction during the vote, I've got a whole bit about a talking raccoon.",
    ],
    tease: [
      "You've apologised to a log twice today.",
      "There are no exits, Mike. It's an island.",
      "Please don't do the raccoon at the vote.",
    ],
    reply: [
      "The log was there first!",
      "Then I'll check the trees. Trees are basically exits.",
      "It's a really good raccoon, though.",
    ],
    home: ["Zoey. We've been through a lot, and she's the reason I'm brave enough to be here.",
      "My family and my friends, who know everything about me now. That took a while. I'm proud of it."],
    want: ["To play my own game, as me. All of me, for once.", "I want to win without hurting anybody. I know, I know. I'm going to try anyway."],
    conf: ["I spent a long time hiding parts of myself. I'm not doing that out here. Mostly.",
      "When somebody I care about is in trouble, I stop being nervous. It's weird. I should probably care about more people."],
    askHome: ["Do you have someone back home? Sorry, is that weird to ask? You don't have to answer.", "Who's back home rooting for you?"],
    askWant: ["What's the dream? If you win, I mean. Sorry, that's a big question.", "Why did you sign up? Honestly I'm still not sure why I did."],
  },
  Millie: {
    thing: 'her notebook',
    bit: [
      "Fun fact: forty percent of plastic in the ocean is fishing nets. So when we fish, we should really think about that.",
      "I'm keeping notes on everyone. For journalism. It's not a strategy thing. It's mostly not a strategy thing.",
      "We're doing the shelter wrong. I read about this. I can't do it myself, but I know we're doing it wrong.",
    ],
    tease: [
      "Millie, we're starving. Let us fish.",
      "What did you write about me?",
      "So you'll supervise.",
    ],
    reply: [
      "Fine. But I'm writing down that I said it.",
      "Nothing bad. Mostly nothing bad. It's descriptive.",
      "I'll consult. Consulting is a real job.",
    ],
    home: ["My mom, who wanted me to do something normal for once. This is not normal. I'm aware.",
      "My editor at the school paper, who thinks this will be a great series. I hope she's right. I hope I survive it."],
    want: ["To prove I can do more than watch people. I want to actually be in it.", "To win, and to write about it after. I have notes already."],
    conf: ["I came here to observe my generation's failures. Turns out I'm one of them. I'm adding that to the notes.",
      "It's easier to judge people than to talk to them. I'm working on it. It's slow."],
    askHome: ["Can I ask about your life back home? It's for context. And because I'm curious.", "What's your family like? You don't have to answer. I'll still take notes."],
    askWant: ["What are you hoping to get out of this, honestly? I'm trying to understand people better.", "Why are you really here? Off the record."],
  },
  Thom: {
    thing: 'being a cop',
    bit: [
      "Nobody leaves camp alone after dark. I'm serious. Buddy system, everybody.",
      "I'm just going to walk the perimeter real quick. Old habit.",
      "When I was a kid I read every comic I could find. I always wanted to be the guy who shows up when it goes wrong.",
    ],
    tease: [
      "Okay, Officer. Should we sign in and out, too?",
      "There's no perimeter. It's a beach.",
      "So you're the hero now?",
    ],
    reply: [
      "If it keeps everybody safe, yes.",
      "Then I'm walking the beach. Same thing.",
      "I'm just the guy who shows up. That's all I've ever wanted to be.",
    ],
    home: ["My mom, Jackie, who taught me to skate, and my little brother Tony, who is definitely eating all my food right now.",
      "My mom and my brother. They've been there for the worst of it. I'd like to give them something good."],
    want: ["I want to do this right. Win or lose, I want to be able to look myself in the mirror.", "To prove I can trust people again. And to win, if I can."],
    conf: ["I don't like lying. I'm good at it, which is worse. I'm trying not to need it out here.",
      "People think I'm guarded. I am. You'd be too. But I'll go to war for the ones who earn it."],
    askHome: ["Who's waiting for you at home? Somebody's got your back out there, I hope.", "You got family back home? They okay with you being out here?"],
    askWant: ["What are you really here for? I'd rather know now.", "What happens if you win? Where does it go?"],
  },
  Miriam: {
    thing: 'being old enough to be everyone\'s grandmother',
    bit: [
      "I've been awake since five. Somebody here snores like a leaf blower, and I will find out who.",
      "In my day, we didn't complain about the food. We ate it, and then we complained.",
      "I rowed, I played water polo, I threw knives competitively. This challenge does not frighten me.",
    ],
    tease: [
      "You're up at five every day? Why?",
      "Miriam, you've complained about the food at every meal.",
      "You threw knives?",
    ],
    reply: [
      "Because I'm seventy-three, dear, and the sleep is over.",
      "After eating it. Pay attention.",
      "Competitively. Ask nicely and I'll show you. Ask rudely and I'll also show you.",
    ],
    home: ["My cat, Biscuit, and my neighbour Joey, who's watching him. Joey had better not be feeding him the cheap food.",
      "An empty house and a very spoiled cat. That's all I need to say about it."],
    want: ["To win, and then to watch every one of you realise you underestimated the old lady.", "Enough money to keep Biscuit in the good food until he outlives us all."],
    conf: ["They think the old woman is an easy vote. Let them think it. I've buried better people than this lot.",
      "I don't do sweet. I do useful. Sweet gets you a nice funeral, useful gets you to the end."],
    askHome: ["And who's waiting for you at home? Somebody, I hope. You look like you need somebody.", "Do your parents know you're out here doing this? Heavens."],
    askWant: ["What on earth do you want out of this? Fame? You'll find it disappointing.", "Why are you here, young one? And don't give me the speech."],
  },
  Grett: {
    thing: 'being a fitness influencer',
    bit: [
      "If anyone wants to actually be useful today, I'm doing a circuit at the beach. You're welcome.",
      "This is why we keep losing. Nobody here has done a real squat in their life.",
      "My followers would be horrified by this diet. I'm horrified by this diet.",
    ],
    tease: [
      "Nobody asked for a workout, Grett.",
      "Was that a pep talk? Because it felt like an insult.",
      "Your followers aren't here.",
    ],
    reply: [
      "Nobody asked to lose the last challenge either, and here we are.",
      "It was both. You're welcome for both.",
      "They'll see the episode. I'm doing this for the episode.",
    ],
    home: ["My audience, my brand, and a flat that's far too nice to be away from this long.",
      "Nobody I'd call when I'm upset. I'm working on that. Don't make it a thing."],
    want: ["To win. And for everybody who said I was just a pretty face to watch me do it.", "Control. Of my own game, for once, and nobody else's."],
    conf: ["People think I'm mean. I'm honest, and honest just sounds mean to people who aren't used to it.",
      "I don't need them to like me. I need them to be scared of what happens if they cross me."],
    askHome: ["So who's waiting for you? Boyfriend? Girlfriend? Nobody? Come on.", "Who's watching you back home? Be honest."],
    askWant: ["What do you actually want out of this? You can't just be here for fun.", "What's your plan here, really?"],
  },
  Gabby: {
    thing: 'how many pets she has',
    bit: [
      "Look, I made a friend! He's a crab, and his name is Pavel, and he's very shy, so please be quiet.",
      "Did anybody eat the eggs? Because those were somebody's babies, and I need to know who.",
      "At home I have three cats, two dogs, a ferret, a lizard, and a goat. The goat is my favourite. Don't tell the cats.",
    ],
    tease: [
      "Gabby, please don't name the dinner.",
      "We're starving. The eggs were dinner.",
      "Who is watching all those animals right now?",
    ],
    reply: [
      "He isn't dinner. He's Pavel.",
      "Then I'll eat the rice and I'll be sad about it.",
      "Ellie. She's going to be so tired when I get home.",
    ],
    home: ["Ellie. My girlfriend. We've been together five years and this is the longest we've ever been apart, and I hate it.",
      "Ellie and a house full of animals. I miss all of them so much I can't think about it for too long."],
    want: ["To win and use the money for an animal sanctuary. A big one, with a pond.", "To make it far enough that Ellie is proud. And then win, if I can."],
    conf: ["Sometimes there's a voice in my head that says the mean thing first. I don't have to listen to it. Today I didn't.",
      "If you're kind to me, I'll do anything for you. If you hurt somebody I love, I won't forget it. Ever."],
    askHome: ["Who's waiting for you at home? Do you have pets? Please say you have pets.", "Do you have a girlfriend or a boyfriend back home? Do they miss you?"],
    askWant: ["What would you do with the money? I want to hear everybody's answer!", "What do you want most out of this? Like, in your heart?"],
  },
  James: {
    thing: 'being an influencer',
    bit: [
      "I counted. Four people at breakfast, three at lunch. Somebody's skipping meals to have conversations.",
      "Back home, I had half a million people watching every move I made. Out here it's eight. It's almost relaxing.",
      "Plans change. I don't. That's the whole secret.",
    ],
    tease: [
      "You counted people at breakfast?",
      "Eight people and a camera crew.",
      "That's a very nice sentence. What does it mean?",
    ],
    reply: [
      "I count everything. It's free information.",
      "The camera crew doesn't vote.",
      "It means I'll still be here when your plan doesn't work.",
    ],
    home: ["My sister. She was my only friend for a long time. She's the one I'm doing this for, if I'm honest.",
      "A lot of followers, and one person who would notice if I disappeared. That's my sister."],
    want: ["To win, cleanly, and in a way that looks good on camera. Both matter.", "To find out if I can win without performing. I'm not sure I can."],
    conf: ["Everybody wants to be part of a story. I just make sure I'm the one telling it.",
      "I don't raise my voice. If you raise your voice, you've already lost the room."],
    askHome: ["Tell me about home. Who matters there?", "Who's watching for you back home?"],
    askWant: ["What do you want from this? People always have an answer they say and an answer they mean.", "What's your end goal here?"],
  },
  Lake: {
    thing: 'chess',
    bit: [
      "If anyone wants to play, I've drawn a chessboard in the sand. The pieces are shells. The white king is a slightly larger shell.",
      "I've started writing a story about a girl stranded on an island. It's fiction. Mostly.",
      "There's a precise way to split the firewood so it lasts all night. I can show you, if you'd like to do it properly.",
    ],
    tease: [
      "You're playing chess with shells. On a beach. In a survival game.",
      "Is the girl in the story going to vote anyone out?",
      "Is there a precise way to do everything?",
    ],
    reply: [
      "Chess is a survival game. It just has better manners.",
      "Not yet. She's still deciding who she trusts.",
      "Yes. Most people simply don't bother.",
    ],
    home: ["My friends, who helped me stop living the way my parents wanted me to. I chose this. That still feels strange to say.",
      "My notebooks and my chessboard. My parents, technically, though they don't know I'm here."],
    want: ["To make my own choices for as long as I can. Winning would just be the last one.", "To win, without becoming someone I'd have to forgive."],
    conf: ["I've spent my life being told what to do. Out here, every move is mine. It's terrifying. I love it.",
      "People confuse being loud with being strong. I'd rather be strong."],
    askHome: ["May I ask who's waiting for you at home?", "What's your life like at home? I'd like to know, if you're willing."],
    askWant: ["What would winning mean for you? Not the money. The other thing.", "What brought you here? I mean the real reason."],
  },
  Yul: {
    thing: 'being a former dancer',
    bit: [
      "Bold choice, wearing that today. Bold.",
      "I went viral at fifteen. Some of you are going to go viral after this, too. For crying.",
      "Nothing personal, but whoever built this shelter should never build anything again.",
    ],
    tease: [
      "Wow. Do you ever say anything nice?",
      "At least people will remember us.",
      "You didn't help build it.",
    ],
    reply: [
      "That was nice. You'd know if I was being mean.",
      "That's the dream, isn't it? Being remembered for the worst thing you did.",
      "I don't build. I critique. Someone has to.",
    ],
    home: ["A podcast that does better than your entire family's careers combined.", "A lot of people who want to be me. Nobody I'd call."],
    want: ["The money and the attention, and I'll take the attention first.", "To remind everybody who I am."],
    conf: ["Nice is a performance. I just stopped performing it.",
      "Nothing personal. That's what I always say. It's always personal."],
    askHome: ["Who's at home, then? Let me guess. Nobody important.", "Do you even have anyone back home?"],
    askWant: ["What do you want? Fame? You don't have the face for it.", "Why are you here? Genuinely asking. I can't work it out."],
  },
  Natalia: {
    thing: 'being a publicist',
    bit: [
      "Okay, I'm not saying there's a story here, but somebody went to the well three times this morning and came back with no water.",
      "Babes, as a professional publicist, I'm telling you, your image on this team is in crisis. I can fix it. I charge.",
      "I've already got the chisme on everybody. Who's crying at night, who's whispering, who's lying about where they went.",
    ],
    tease: [
      "Do you ever just mind your own business?",
      "You're going to charge me? Out here?",
      "That sounds like a full-time job.",
    ],
    reply: [
      "Minding other people's business IS my business, babes.",
      "First consult's free. After that we talk about rice.",
      "It is, and I'm the best employee I've ever had.",
    ],
    home: ["My family, who always backed me, even when I came out. Especially then. I'm doing this for them.",
      "My clients, my friends, and a group chat that has definitely been on fire since I left."],
    want: ["To win, and to control my own story for once instead of fixing everybody else's.", "Discipline. Real bonds, fewer messy flips. And then the money, obviously."],
    conf: ["Everybody thinks gossip is useless. Gossip is just information that hasn't been fact-checked yet.",
      "I bond fast. It's my superpower and it's going to get me in trouble. It always does."],
    askHome: ["Okay, spill. Who's waiting for you at home? Are they cute?", "Babes, who's back home? Give me names."],
    askWant: ["What do you actually want out of this, though? I won't tell anyone. I'll tell some people.", "What's your story here? Like, how do you want this to end?"],
  },
  Natasha: {
    thing: 'falling for people too fast',
    bit: [
      "Okay, I just met everyone yesterday and I already have, like, three best friends. That's normal, right?",
      "I'm studying to be a public defender, so honestly, if anyone gets voted out unfairly, I'm going to make a speech.",
      "Sorry, I'm oversharing. I do that. I just told someone my entire dating history at the well.",
    ],
    tease: [
      "Three best friends in one day? That's a lot.",
      "There are no appeals here, Natasha.",
      "Your entire dating history? At the well?",
    ],
    reply: [
      "I have a lot of love to give! It's a problem! I'm working on it!",
      "There should be. I'm going to write to someone.",
      "It's a short history. It's just very emotional.",
    ],
    home: ["My parents and my law school friends, who said I'd get attached to everyone in the first week. They were right.",
      "My mom, who's Filipina and is going to call everyone in the family the second I'm on screen."],
    want: ["To make real connections, and to win without lying to the people I care about. Is that possible? It should be.", "I want to win, and I want to still like myself after."],
    conf: ["I fall for people so fast. Not just romantically. I mean, also romantically.",
      "Every so often I hear myself and think, Natasha, please develop boundaries. Then I don't."],
    askHome: ["Okay, who's at home? Tell me everything. Partner? Family? Best friend?", "Do you have someone you're missing? I already miss everyone."],
    askWant: ["What do you want out of this? Like, emotionally?", "What's the dream? I want to know everyone's dream."],
  },
  Aaron: {
    thing: 'never talking about himself',
    bit: [
      "The shelter's leaning. I'll fix it before it rains.",
      "I worked logging camps in the interior for six years. This is a vacation with worse food.",
      "Somebody's been going into the woods every morning. Same direction. I'm not going to say who.",
    ],
    tease: [
      "Do you ever say more than ten words at once?",
      "Six years in the woods. That explains a lot.",
      "You noticed that? You don't even talk to anyone.",
    ],
    reply: [
      "When it's worth it.",
      "It explains enough.",
      "I don't need to talk to notice.",
    ],
    home: ["Winnipeg. My father thinks I should come home and work for him. I'd rather not.",
      "It's old. Doesn't matter."],
    want: ["The money. And to do it without making promises I can't keep.", "To be left alone, eventually. With enough money to make that possible."],
    conf: ["People get nervous when they realise how much I notice. So I let them think I don't.",
      "I'm not good at lying. If I have to start, I'm already in trouble."],
    askHome: ["Where's home for you?", "You have people back home?"],
    askWant: ["What are you here for?", "What happens if you win?"],
  },
  Amberly: {
    thing: 'pageants',
    bit: [
      "Y'all, I have walked a runway in four-inch heels on a cattle trailer. This challenge ain't nothin'.",
      "If somebody's bein' fake on this team, my face is gonna tell you before my mouth does, hon.",
      "Back home I've got six older brothers. Six. So if anybody here thinks they can push me around, bless your heart.",
    ],
    tease: [
      "On a cattle trailer?",
      "Your face is doing something right now, Amberly.",
      "Bless your heart is a threat, isn't it?",
    ],
    reply: [
      "County fair, sugar. You make do.",
      "That's 'cause somebody here is bein' fake. Ain't sayin' who.",
      "Only if you deserve it.",
    ],
    home: ["My mama, six brothers, and a whole lotta cows. My mama's gonna be screamin' at the TV.",
      "Our farm, and my pageant crowns, which my mama dusts every Sunday."],
    want: ["To be famous! Like, real famous, not county famous.", "To win, and to show everybody back home I'm more than a pretty sash."],
    conf: ["I don't need a big nerd plan. I just need to figure out who's fake. Takes me about four minutes.",
      "If y'all leave me out of somethin', I'm gonna act real normal. And then I'm not."],
    askHome: ["Hon, who's waitin' on you back home?", "You got a sweetheart back home, sugar?"],
    askWant: ["What're you gonna do with the money, boo?", "What's your dream, hon? Everybody's got one."],
  },
  Dylon: {
    thing: 'crypto',
    bit: [
      "Look at it this way, mate. The fish is a bad trade. Two hours of fishing for one fish. I'm out.",
      "I read this team like a portfolio. Couple of blue chips, couple of penny stocks, and one complete liability.",
      "I left the LSE because my crypto was making more than the lecturers. Best decision I ever made.",
    ],
    tease: [
      "You haven't fished once.",
      "Who's the liability?",
      "Didn't your parents hate that?",
    ],
    reply: [
      "Exactly. Smart money doesn't fish.",
      "I'd tell you, mate, but you'd take it personally.",
      "They still mention the degree. They also mention the house I bought them.",
    ],
    home: ["A flat in London I paid for myself, and two parents who still ask when I'm finishing my degree.",
      "My clients, who are definitely panicking without me."],
    want: ["The money's a rounding error. I want the win on my record.", "To beat everyone here without my name ever being on a single move."],
    conf: ["Everyone's a number. Some people just haven't worked out what theirs is yet.",
      "I keep my hands clean and let someone else hold the knife. That's not cowardice. That's risk management."],
    askHome: ["So what's your life back home, mate? What's the position?", "Who's backing you at home?"],
    askWant: ["What's your exit strategy here? What are you actually in it for?", "What would you do with the money, mate? Bet it's a bad trade."],
  },
  Felipe: {
    thing: 'being an artist',
    bit: [
      "Meu Deus, your posture today. You're standing like you borrowed your spine from someone shorter.",
      "I'm sketching everyone. Don't look. How I draw you is what I think of you, so maybe don't look at all.",
      "I didn't come for the money, amor. I came for the art. The money is just the frame.",
    ],
    tease: [
      "Was that a compliment?",
      "Can I see mine?",
      "Then you won't mind if I win it.",
    ],
    reply: [
      "It was attention. From me, that's better than a compliment.",
      "Not yet, querido. You're not finished.",
      "Ha! Over my beautiful dead body.",
    ],
    home: ["My little brother. He calls when the rest of the family isn't listening. That's my whole family, really.",
      "My studio in São Paulo, which smells like paint and bad decisions. I miss it terribly."],
    want: ["To make something beautiful out of this. And yes, fine, the money.", "To be seen again. I used to be someone people talked about."],
    conf: ["I see everything. A fake laugh, a nervous hand. My problem is my mouth doesn't wait for permission.",
      "Everyone here is a painting. Some of them are badly framed. I'm only telling the truth."],
    askHome: ["Tell me, querido, who's waiting for you at home?", "Who do you miss? Your face says somebody."],
    askWant: ["What do you want, amor? I mean, deep in the soul.", "Why are you here? And don't say the money, it's so beige."],
  },
  Gyselle: {
    thing: 'modelling',
    bit: [
      "Honestly, I'm obsessed with how everyone looks today. Like, no literally, the island is doing wonders for your skin.",
      "I've done shoots in way worse conditions than this. Okay, maybe not worse. But colder.",
      "I'm having a makeup night at the shelter later, everybody's invited, it's going to be so cute.",
    ],
    tease: [
      "We look terrible. We haven't showered in a week.",
      "Name one shoot that was worse than this.",
      "We have no makeup.",
    ],
    reply: [
      "Honestly? Dewy. It's a look.",
      "Swimwear. In Zürich. In March.",
      "We have charcoal and berries. You'd be amazed."],
    home: ["My parents. They moved our whole family to LA for my career. I owe them everything, literally.",
      "My agency, my followers, and my mom, who's going to text me every single episode."],
    want: ["Honestly? To get far and be someone everyone liked. Winning would be amazing too.", "To be more than a pretty face. Is that cliché? It's cliché."],
    conf: ["I don't need to be the one making the moves. I just need to be standing next to whoever is.",
      "In here I'm all smiles. In here, I mean the confessional, I can say it: some of these people are not it."],
    askHome: ["Okay, who's waiting for you back home? I'm obsessed already.", "Do you have someone back home? You totally do."],
    askWant: ["What do you want out of this? Honestly?", "What's the dream? Like, after this?"],
  },
};
