// td/story/kits/kits2.js — character kits, batch 2 (see kits1.js for the shape)

export default {
  Harriett: {
    thing: 'being in charge of everything',
    bit: [
      "No but listen, if we do the water run now, we can do firewood after, and then nobody has an excuse.",
      "I'm a dental assistant. I keep an entire office on schedule. This camp is nothing.",
      "Jane doesn't want to do the challenge. Jane, tell them. See? She agrees with me.",
    ],
    tease: [
      "Who made you the boss?",
      "Does the office like you, though?",
      "Jane didn't say anything.",
    ],
    reply: [
      "Nobody. That's the point. Somebody had to.",
      "They like that things get done. Liking me is a bonus.",
      "She agreed with her face. I know her face.",
    ],
    home: ["My grandparents, my parents, and the dental office, which is probably on fire without me.",
      "Jane's here, so honestly, home is mostly here. Plus our grandparents, who are watching with a magnifying glass."],
    want: ["To win. Not second. Not 'did well'. Win.", "To prove I'm not just loud. I'm loud and right."],
    conf: ["Everybody thinks I'm messy. Good. Messy people get underestimated.", "Nobody talks down to Jane. Nobody. I don't care if she wants to handle it herself."],
    askHome: ["Okay, who's at home? Quick version.", "No but listen, who's waiting for you?"],
    askWant: ["What's your plan? You have to have a plan.", "What do you actually want? Don't say fun."],
  },
  Jane: {
    thing: 'how quiet she is',
    bit: [
      "...Sorry. I was going to say something, but you're already on a different thing.",
      "I write romance novels online. Under a fake name. Please don't tell anyone. Except... you just heard. Sorry.",
      "The shelter's going to flood. The roof slopes the wrong way. I didn't say anything. Sorry.",
    ],
    tease: [
      "Jane, you can just talk, you know.",
      "Wait, romance? You?",
      "Jane, why didn't you say anything?",
    ],
    reply: [
      "I know. By the time I'm ready, it's over.",
      "Mostly dragons. Kissing dragons. It's fine.",
      "Harriett was talking. Harriett's always talking.",
    ],
    home: ["My grandparents. And my readers, I guess. About four hundred people who don't know who I am.",
      "Harriett's here. So mostly my grandparents, and a lot of unfinished chapters."],
    want: ["To not be the first one out. And maybe to say one sentence out loud that I've only ever written.", "I want to win. I didn't want to say that out loud. It's out now."],
    conf: ["I notice everything. Who's lying, who's scared. I just never say it in time.", "Harriett speaks for me. I let her. I'm not sure I should."],
    askHome: ["Um. Who's at home for you? Sorry. You don't have to answer.", "Do you miss someone? You seem like you miss someone."],
    askWant: ["What do you want out of this? Sorry. That's a lot.", "Why did you come? I'm still not sure why I did."],
  },
  Hasan: {
    thing: 'being a law student',
    bit: [
      "If I may summarise your point: you would like to vote out the person you dislike, and you are calling that strategy.",
      "I am not above drama. I simply do not participate in it. There is a distinction.",
      "I keep every agreement I make. That is not naivety. It is the only reputation worth having.",
    ],
    tease: [
      "Do you talk like that to everyone?",
      "You're literally in the drama right now.",
      "That's going to get you voted out.",
    ],
    reply: [
      "Only to people whose arguments deserve better structure.",
      "Observing it is not the same as taking part.",
      "Perhaps. But nobody will ever say I lied to them.",
    ],
    home: ["My mother, who raised four children alone. I am the oldest. I owe her more than I can say.",
      "Three younger siblings who think I am far too serious. They are correct, occasionally."],
    want: ["To become a defence attorney and repay my mother. The money would help with both.", "To win honestly. I would like to prove that is still possible."],
    conf: ["People mistake my silence for scheming. I am simply thinking before I speak, which seems to be rare here.", "Emotional players are not strategic. I will keep telling myself that until it stops being true."],
    askHome: ["May I ask who is waiting for you at home?", "Who are you doing this for? Most people have a someone."],
    askWant: ["What exactly do you hope to achieve here? I would like to understand your reasoning.", "What will you do with the money, should you win?"],
  },
  Ireland: {
    thing: 'poker',
    bit: [
      "You want to know what I'm thinking? Sure. What are you thinking first?",
      "I played cards in Vegas for five years. Everybody has a tell. Yours is your left eyebrow.",
      "I'm not worried about tonight. I'm never worried. That's the trick, you never let them see it.",
    ],
    tease: [
      "Do you ever just answer a question?",
      "My eyebrow does not do anything.",
      "You look a little worried, actually.",
    ],
    reply: [
      "Did you?",
      "It just did.",
      "Then you're reading the bluff. Good for you.",
    ],
    home: ["Vegas. A one-bedroom, a deck of cards, and nobody I'm related to.", "It's... not really a home thing. I left when I was sixteen. I made my own."],
    want: ["The money. All of it. I've never had a safety net, and I'd like one.", "To win a hand where nobody else even knew we were playing."],
    conf: ["Everybody thinks I'm calm. I'm counting votes in my head every second I'm awake.", "I make a slightly different deal with everybody. I mean all of them. That's the problem."],
    askHome: ["Who's back home for you? Or is that a bad question?", "You got people at home?"],
    askWant: ["What would you do with the money? Really.", "What are you playing for?"],
  },
  Joel: {
    thing: 'his dog Lola',
    bit: [
      "LET'S GO! Big day, big day. Who's ready to win? Bro, you look ready. You look so ready.",
      "Fun fact, I speak three languages. People see the muscles and assume I can't read. I read, baby.",
      "I miss Lola so bad. She's a French bulldog. She snores like a chainsaw and I love her more than people.",
    ],
    tease: [
      "Do you have any volume other than loud?",
      "Okay, which three?",
      "You've mentioned Lola nine times today.",
    ],
    reply: [
      "This is my inside voice. You should hear me at the gym.",
      "English, Spanish, and gym. Gym's a language, trust me.",
      "And I'll mention her nine more. She deserves it.",
    ],
    home: ["Lola, obviously. And my family in Florida, who are loud. Like, louder than me.", "My clients in LA and my dog. My dog's more important. Don't tell my clients."],
    want: ["To win, and to show everybody I'm not just some dumb jock.", "To lead the strongest team here. And then win. Winning's part of leading."],
    conf: ["People see a gym guy and think I'm stupid. I'm not stupid. I'm just loud about everything.", "I've got a line. Don't cross it. Everybody gets one warning, and then it gets loud."],
    askHome: ["Who you got at home, bro? Kids? Dogs? Tell me about the dog.", "Who's watching for you back home?"],
    askWant: ["What's the dream, champ? Big picture.", "What do you want out of this, for real?"],
  },
  Jules: {
    thing: 'falling in love with everyone',
    bit: [
      "Oye, your shoulders are up by your ears. Come here, sit. Two minutes, and you'll feel like a new person.",
      "I'll be honest, mi vida, I came for two things. Love and money. Not necessarily in that order.",
      "I'm a bartender back home. I make strangers feel like cousins in five minutes. Out here, it's harder without the rum.",
    ],
    tease: [
      "Do you give everybody a massage?",
      "Love and money. That's very honest.",
      "You're making me feel like a cousin right now and I don't like it.",
    ],
    reply: [
      "Only the people who need one. That's everybody, it turns out.",
      "I don't lie about the important things, bendito.",
      "Give it five more minutes. You'll love it.",
    ],
    home: ["My little brothers and sisters. I raised them, mostly. My mom tried. I love her anyway.", "San Juan, then New York, now California. Home is wherever the people I love are this week."],
    want: ["I need the money. I'm not ashamed. My family needs it more than I do.", "Love, maybe. I always fall too fast. Then the money, if love doesn't work out."],
    conf: ["Two people ask me for opposite things, and I say 'dale, mi vida' to both. That's my whole problem.", "I fall in love every three weeks. Every time, I mean it. That's the dangerous part."],
    askHome: ["Mi vida, who's waiting for you back home?", "Tell me about home. Who do you miss?"],
    askWant: ["Dale, tell me. What do you really want out of this?", "If you win, what's the first thing you buy?"],
  },
  Misha: {
    thing: 'surfing',
    bit: [
      "I said what I said. Somebody left the pot dirty again and I'm not about to pretend I didn't notice.",
      "This water's nothing. I've surfed Cocoa Beach in a storm with my daddy yelling at me from the shore.",
      "Y'all ate? Come here. Nobody's going to a challenge hungry on my watch.",
    ],
    tease: [
      "It's one pot, Misha.",
      "Your dad yelled at you while you surfed?",
      "You're not our mom.",
    ],
    reply: [
      "It's one pot today. It's the principle forever.",
      "He was coaching. Loudly. With love.",
      "No, but I'm the one who fed you, so act right.",
    ],
    home: ["My Nana. She raised me as much as anybody. When I'm upset, she's the one I call.", "My daddy, who taught me to surf, and my Nana, who taught me everything else."],
    want: ["To win, and to go home and tell my Nana I did it right. No lying, no sneaking.", "The money for a better board and a trip to the big waves. And to make my family proud."],
    conf: ["I don't lie and I don't sneak. If I've got something to say, I'm saying it to your face.", "When I get real quiet, that's when you should worry. Loud is fine. Quiet is not."],
    askHome: ["Who's waiting on you back home, hon?", "You got family? Tell me about them."],
    askWant: ["What do you want out of this, for real?", "What are you gonna do with the money?"],
  },
  Nico: {
    thing: 'being everybody\'s dad',
    bit: [
      "I fixed the pot handle. Don't thank me. Just don't break it again.",
      "Can everybody stop talking about the vote before the coffee's done? It's not done.",
      "My daughter told me to be nice on TV. I'm being nice. This is nice.",
    ],
    tease: [
      "Okay, Dad.",
      "We don't have coffee, Nico.",
      "This is you being nice?",
    ],
    reply: [
      "Don't call me that.",
      "Then nobody's talking about the vote.",
      "You should see me when I'm not.",
    ],
    home: ["My daughter, Canzada. She's twelve. She started the application. She thinks I'm funnier than I am.", "My shop in Queens and a big loud family that's going to argue about every episode."],
    want: ["Money for my kid's school. Then a quiet life. Mostly the quiet life.", "Keep my word, don't be a headache, get home to my daughter. Win if I can."],
    conf: ["Everybody keeps calling me Dad. I already have a kid. I don't need nine more.", "I don't do feelings talks. I fix things. If you need a feelings talk, find somebody else."],
    askHome: ["Got people at home?", "Who's waiting on you?"],
    askWant: ["What's the money for?", "What are you doing here, really?"],
  },
  Stella: {
    thing: 'her kids',
    bit: [
      "Oh honey, my littlest would love this beach. He'd eat the sand, but he'd love it.",
      "I made everybody's beds this morning. I know nobody asked. I just can't help myself.",
      "Now, I don't mean anything by it, but your breath, sweetie. Bless you. It's the island, it's not you.",
    ],
    tease: [
      "Do you ever not talk about your kids?",
      "Stella, you don't have to mother us.",
      "Stella, you can't just say that to people.",
    ],
    reply: [
      "Oh, I couldn't if I tried. They're my whole heart.",
      "I know, honey. I just can't stop.",
      "Oh dear, I said that out loud, didn't I?",
    ],
    home: ["My husband and our two babies, both under five. My husband's doing bedtime. Bless him.", "My church group, my neighbours, and two little ones who I hope are brushing their teeth right."],
    want: ["To be kind to everybody and still make it to the end. Is that silly? It's not silly.", "To show my kids their mama can do something hard. And win a little money for their college."],
    conf: ["Everybody underestimates me. Sometimes that's fair. Sometimes, honey, it is not fair at all.", "I told somebody something I maybe shouldn't have. I just can't keep a secret. I never could."],
    askHome: ["Oh, tell me about your family, honey! Who's at home?", "Do you have little ones? Or a sweetheart?"],
    askWant: ["What are you hoping for out here, sweetie?", "What would you do with the money? Something nice, I hope."],
  },
  Tobias: {
    thing: 'streaming',
    bit: [
      "Hey chat. Oh, right, there's no chat. Hey... camera guy.",
      "Okay, so in game theory terms, we're in a prisoner's dilemma, and nobody here is a prisoner, which is the dilemma.",
      "If we lose this challenge, that's an L. That's a massive L. That's an L for the history books.",
    ],
    tease: [
      "Are you talking to the camera again?",
      "That made no sense.",
      "Please stop saying L.",
    ],
    reply: [
      "The camera's basically chat. Chat is always watching.",
      "It made sense in my head. And on my stream. To like four people.",
      "Okay, then that's a big W. Everything's a W now.",
    ],
    home: ["My parents. My mom gets the stream thing. My dad's still asking when I'm going to college.", "My stream, my card binder, and my followers, who are definitely spamming that I'm getting robbed."],
    want: ["To win, and to show my dad streaming can pay. Literally.", "To make it to the end with the strongest players and be the one they never saw coming."],
    conf: ["I know the theory. Like, all of it. I just never know who's actually doing the theory.", "Chat would be screaming right now. Chat would be so mad at me."],
    askHome: ["Yo, who's back home for you?", "Who's watching the show for you, like your mom or whatever?"],
    askWant: ["What's your win condition here? Like, endgame?", "What would you even do with the money?"],
  },
  Zella: {
    thing: 'her band',
    bit: [
      "And? You got a problem with how I'm doing it? Do it yourself, then.",
      "My band played a sold-out show last month. Okay, it was a bar. It was a sold-out bar.",
      "If anybody touches the fire one more time while it's going, I'm going to scream. I mean it. With love.",
    ],
    tease: [
      "Wow, okay, attitude.",
      "How many people fit in the bar?",
      "With love?",
    ],
    reply: [
      "It's not attitude. It's honesty with volume.",
      "Forty. It was a great forty.",
      "Always with love. Loud love.",
    ],
    home: ["My band and the record store. And my parents, who come to every show, even the bad ones.", "Montreal, my guitar, and a girlfriend I broke up with two weeks before this. Great timing."],
    want: ["The money for a real record. Like, a real one, in a studio.", "To win. And to stop crying when I'm angry. One of those is more likely."],
    conf: ["I snap. Then it's over. I don't hold grudges, I just hold volume.", "Somebody thanked me today and I didn't know where to look. Don't thank me. Just be cool."],
    askHome: ["Who's back home for you? Tell me, I'm bored.", "You got somebody at home?"],
    askWant: ["What do you want out of this, though? Really?", "What's the money for?"],
  },
  Aubrey: {
    thing: 'astrology',
    bit: [
      "Okay, I don't want to alarm anyone, but we have three Scorpios on this team, and that's a problem.",
      "What time were you born? I'm asking for a reason. It matters. Trust me.",
      "I'm a psych student, and I'm into astrology, and both of them are telling me the same thing about you.",
    ],
    tease: [
      "You think three people are a problem because of their birthdays?",
      "Why does that matter?",
      "What are they telling you?",
    ],
    reply: [
      "I don't think it. I know it. Water signs are all secrets.",
      "Your rising sign tells me who you are when nobody's watching.",
      "That you're hiding something. Earth sign energy. Very suspicious.",
    ],
    home: ["My parents and my cat, Ziggy. He's a Siamese and a Leo, which explains everything.", "My psych classes, my cross-stitch, and a cat who definitely thinks I abandoned him."],
    want: ["To win, and to prove I was right about everyone. I usually am.", "To read everybody before they read me."],
    conf: ["People think astrology is a joke. It's a framework. Like psychology, but prettier.", "I made my mind up about everybody on day one. I don't change it. Why would I? I was right."],
    askHome: ["Okay, who's waiting for you at home? Also, what's your sign?", "Do you have a partner? What sign are they?"],
    askWant: ["What do you want out of this? Your chart says ambition, but I want to hear it.", "What's your dream? Like, your Midheaven dream?"],
  },
  Ara: {
    thing: 'being class president',
    bit: [
      "If we're doing this, we're doing it properly. I was class president. I know how to run a room full of idiots.",
      "I'm a business student. Everything here is a negotiation. Including breakfast.",
      "Some of you are being very loud for people with no plan.",
    ],
    tease: [
      "Wow. Love that you called us idiots.",
      "You're negotiating breakfast?",
      "Do you have a plan?",
    ],
    reply: [
      "I said a room full. Not this room. Mostly.",
      "Everything's a negotiation if you're doing it right.",
      "Obviously. You'll see it when it's too late.",
    ],
    home: ["My parents, who left Korea for love. I'm never doing that. Love's not a plan.", "A family that thinks I'm the golden child. I'd like to keep it that way."],
    want: ["To win. I don't do second place. I don't do 'great effort'.", "To prove ambition isn't something you have to apologise for."],
    conf: ["I build trust fast and spend it faster. That's not cruel. It's efficient.", "Everybody wants to be liked. I want to be the one deciding who goes home."],
    askHome: ["So who's at home? I'm asking to be polite.", "What's your family like? Supportive? Embarrassing?"],
    askWant: ["What's your plan? Please tell me you have one.", "What do you actually want? Specifics."],
  },
  Bruno: {
    thing: 'his job as a personal assistant',
    bit: [
      "As a personal assistant, I can tell you, this schedule is a mess. I could fix it. I fix Valerie's every day.",
      "Fun fact: the last time they did this challenge, the team that went for the flag first won. I've watched it eleven times.",
      "My mom made me this hoodie for good luck. Don't laugh. It's worked so far.",
    ],
    tease: [
      "Bruno, you've told us you're a personal assistant like twelve times.",
      "Eleven times?",
      "It's been one day, Bruno.",
    ],
    reply: [
      "Because it's relevant! It's always relevant!",
      "Twelve. I watched it again on the flight.",
      "And I'm still here. It's working.",
    ],
    home: ["My parents, Teresa and Alvaro, and my boss Valerie, who has definitely called me forty times already.", "My mom, my grandma, who's also Teresa, and a very lonely to-do list."],
    want: ["To be a real Favourite. Not just a fan. Somebody people remember.", "To prove a superfan can actually win this. I've studied for years."],
    conf: ["I know everything about this game. Doing it is really, really different from knowing it.", "Valerie always says, 'Bruno, can you handle this?' And I always can. I just need somebody to ask."],
    askHome: ["Okay, who's at home for you? I'm asking because I genuinely want to know!", "Who's your support system? Mine's my mom and a hoodie."],
    askWant: ["What's your strategy? Sorry. Also, what do you want? Both.", "What would winning mean for you? Like, emotionally?"],
  },
  Dunia: {
    thing: 'being a witch',
    bit: [
      "I pulled a card for the team this morning. The Tower. I'm not going to tell you what it means. You don't want to know.",
      "Don't touch my altar. It's a pile of shells and a candle stub, and it's sacred, thank you.",
      "Your energy is very grey today. Not bad grey. Just grey. Drink some water.",
    ],
    tease: [
      "Is the Tower bad?",
      "It's a pile of shells.",
      "What does grey mean?",
    ],
    reply: [
      "It's change. Sometimes change is a building on fire.",
      "It's a sacred pile of shells. Respect the shells.",
      "It means you need water and a hug, and I've only got water.",
    ],
    home: ["My tarot clients in Montreal and three cats, a toad and a rabbit. Don't ask how they all get along.", "My coven. Okay, my friends. But we call it a coven."],
    want: ["To win, and to show people my practice isn't a gimmick. It's who I am.", "To read every person here before they've read a single card of mine."],
    conf: ["People think it's an aesthetic. It's my religion. I'm not going to apologise for it.", "I charm first and listen hardest. By the time anybody notices, I've read the whole deck."],
    askHome: ["Tell me, who's waiting for you back home? Your energy says someone.", "Who's in your life back home? I'm getting a feeling."],
    askWant: ["What do you want, really? I'll know if you're lying. Witch thing.", "What's your heart after out here?"],
  },
  Ernesto: {
    thing: 'giving advice',
    bit: [
      "If I may offer some guidance: we should build the shelter first and decorate never.",
      "In my career, I trained hundreds of people. Not one of them listened as little as this team.",
      "When I was a boy, I made gazpacho with my mother. You learn patience from a tomato.",
    ],
    tease: [
      "Nobody asked for guidance, Ernesto.",
      "Maybe they were just bored.",
      "You learn what from a tomato?",
    ],
    reply: [
      "And that, my young friend, is exactly the problem.",
      "Boredom is also a choice. A poor one.",
      "Patience. Peel it slowly or it bleeds everywhere. Like this team.",
    ],
    home: ["My children and my grandchildren. And my wood carvings, which are much better behaved.", "A small town in Spain, a workshop full of wood shavings, and a family I am very proud of."],
    want: ["To be useful, and to be respected for it. Winning would be a pleasant bonus.", "To show these young peacocks that experience still counts for something."],
    conf: ["I am not bossy. I simply have more experience than everyone around me. It looks the same from outside.", "When people listen to me, I would walk through fire for them. When they do not, I sulk. I am aware."],
    askHome: ["Tell me about your family. Who is waiting for you?", "Do you have people at home who worry about you?"],
    askWant: ["And what is it you hope to gain here? Besides blisters.", "What brought you here, young one?"],
  },
  Evie: {
    thing: 'being rich',
    bit: [
      "Is there a spa on this island? There must be a spa. Somewhere. Behind a rock.",
      "I'm not lazy, darling. I'm conserving my charisma for when it's needed.",
      "My mother gave me this ascot. It's been to Monaco. It has never been to a place like this.",
    ],
    tease: [
      "Evie, there's no spa.",
      "When is it needed?",
      "You brought an ascot? Here?",
    ],
    reply: [
      "Then what's the point of the island?",
      "Brunch, mostly. And emergencies.",
      "Of course. You never know when you'll need to look elegant during a crisis.",
    ],
    home: ["A lovely little estate, my horses, and a very attentive masseuse named Raoul.", "My father's stables, my scarf collection, and my brunch friends, who are all very worried."],
    want: ["To be charming on television. And the money, I suppose, though I've got rather a lot already.", "To find a man. Is that allowed? I'm putting it out there."],
    conf: ["Everyone thinks I'm silly. I'm not silly. I'm just very, very relaxed.", "I've never done anything hard in my entire life. This is my first time. It's awful."],
    askHome: ["And who's waiting for you at home, darling? A husband? Two?", "Do you have a big house? Tell me about the house."],
    askWant: ["What on earth are you doing here, darling? Is it the money? It's always the money.", "What do you want? I want a massage."],
  },
  Finn: {
    thing: 'being a theatre kid',
    bit: [
      "I don't mean to brag, but I was the understudy who saved opening night. Ride the Cyclone. Look it up.",
      "Darling, if you're going to cry, at least find your light. You're crying in the shade.",
      "Everyone here is under-rehearsed. It's honestly painful to watch.",
    ],
    tease: [
      "You've mentioned that show three times today.",
      "Are you directing my crying now?",
      "You haven't rehearsed anything either.",
    ],
    reply: [
      "Because it's the best thing I've ever done, and I'm twenty.",
      "Someone has to. You're clearly not.",
      "I'm a natural. There's a difference, darling."],
    home: ["My drama school in Sydney, where everyone is jealous of me, rightly.", "My mum, who has every one of my programmes framed. Every one."],
    want: ["Fame. Real fame. This is the audition for everything else.", "To win, and to be the most talked-about person in every single episode."],
    conf: ["Some people walk into a room and everyone looks under-rehearsed. I'm one of them.", "I'm not mean. I'm honest with a better delivery."],
    askHome: ["So who's waiting for you at home? Do they know how lucky they are?", "Who's your audience back home?"],
    askWant: ["What's your motivation, darling? In the scene, I mean. In life.", "What do you want out of this? Be dramatic, I'll allow it."],
  },
  Manu: {
    thing: 'being everybody\'s big brother',
    bit: [
      "Hey, hey, no frowns! What's wrong? Come here, tell big Manu.",
      "I sell refrigerators back home. You know how hard it is to make someone excited about a fridge? Very hard. I'm very good.",
      "I used to party a lot. Then my little brother was born, and I thought, he needs somebody to look up to.",
    ],
    tease: [
      "Manu, I'm fine, I'm just thinking.",
      "Are you going to sell us a fridge?",
      "That's actually really sweet.",
    ],
    reply: [
      "You were thinking with a frown. Think with a smile.",
      "If I find one on this island, you're getting the deal of a lifetime.",
      "Don't tell Aleki. He thinks I'm cool.",
    ],
    home: ["My little brother, Aleki, and my dad and Leilani. They're having a watch party every week.", "Hawaii. My family, my friends, and my store, where I'm the top seller three years running."],
    want: ["To make my family proud. And maybe buy my dad a new boat.", "To protect the people I like out here. And win, if they let me."],
    conf: ["I'm not a mastermind. I know that. I've just got heart, and I work hard.", "When somebody I care about gets laughed at, I'm not so friendly anymore."],
    askHome: ["Hey, tell me about your family! Who's at home?", "You got brothers? Sisters? Tell me everything."],
    askWant: ["What are you gonna do with the money, huh? Something good?", "What do you want out of this, bro?"],
  },
  Nura: {
    thing: 'being a pessimist',
    bit: [
      "Great. Another beautiful day in paradise. Can't wait to die of sunburn.",
      "I work retail. People yell at me about coupons for a living. This is a vacation.",
      "I used to write poetry. Then a girl laughed at it. Now I write tragic comedies. Mostly tragic.",
    ],
    tease: [
      "Do you ever say anything positive?",
      "That's genuinely the saddest thing I've heard today.",
      "Can I read one?",
    ],
    reply: [
      "I'm positive this is going to go badly.",
      "It's early. Give me an hour.",
      "No. Maybe later. Probably not.",
    ],
    home: ["A roommate named Chelsea and a cash register that misses me. That's it.", "San Francisco, a job I hate, and a bass guitar I haven't touched since I was sixteen."],
    want: ["Something different. Anything. I'll know it when it's not a cash register.", "To win, so I never have to scan another coupon."],
    conf: ["Everybody here is so excited. It's exhausting. I'm trying to be excited. It's not working.", "I don't hate people. I just don't know how to talk to them without making a joke about death."],
    askHome: ["Who's at home for you? Or do you live alone with your regrets, like a normal person?", "Got anyone back home?"],
    askWant: ["What do you want out of this? And don't say it's 'a journey'.", "Why are you even here?"],
  },
  Oliwia: {
    thing: 'taxidermy',
    bit: [
      "That bird by the shelter passed away. It's very peaceful. I could preserve it, if anyone wanted.",
      "I knit little sweaters for my specimens back home. My first cat, Lena, has six.",
      "Can I sit with you? I'll be quiet. I'm very good at being quiet. I promise.",
    ],
    tease: [
      "Please don't preserve the bird.",
      "Your dead cat has six sweaters?",
      "You can just sit, Oliwia. You don't have to ask.",
    ],
    reply: [
      "Okay. But it would've been beautiful.",
      "She gets cold. Well, she used to. Now it's for her dignity.",
      "Oh. Okay. Thank you. That's very nice."],
    home: ["My animals in Alaska. Some living, some preserved. I love all of them the same.", "A workshop, a lot of glass eyes, and Lena, who watches over everything."],
    want: ["To make a friend. A real one, who stays.", "To be useful. If I'm useful, people keep me."],
    conf: ["People think death is scary. I think it's the only thing that lasts.", "I'll do anything to be on the right side of the vote. Anything. I know that's not good."],
    askHome: ["Who's waiting for you at home? Sorry. Is that okay to ask?", "Do you have pets? Living ones?"],
    askWant: ["What do you want out of this? I'd like to know. If that's okay.", "What would make you happy out here?"],
  },
  Ren: {
    thing: 'being a circus acrobat',
    bit: [
      "If anybody needs something from the top of the tree, I've got you. Also, I'm already up here.",
      "I used to do aerial silks. Then I did graphic design. Then I did both, at once. It went badly.",
      "Ladies, gentlemen, everyone in between, please stay seated for the greatest show on this beach.",
    ],
    tease: [
      "Why are you up a tree, Ren?",
      "How do you do both at once?",
      "There's no show, Ren.",
    ],
    reply: [
      "Why is anyone anywhere? It's the view.",
      "Very carefully, upside down, with a laptop.",
      "There's always a show. You're just not watching."],
    home: ["Nowhere and everywhere. I've lived out of a backpack for years, and people have been lovely almost everywhere.", "A studio in Vegas, my silks, and a lot of friends who think I'm the weird one. They're right."],
    want: ["To make people smile. And to win. Smiling first, though.", "To play my own game, my own way, and still be me at the end."],
    conf: ["People think I'm weird. I am weird. It's my favourite thing about me.", "I'll joke about everything. Then somebody gets bullied, and I'm not joking anymore."],
    askHome: ["Who's at home for you? Spill. I'm nosy.", "Got anybody special back home?"],
    askWant: ["What do you want from all this? Dream big. I mean big.", "What's your act? Everybody has an act."],
  },
  Sami: {
    thing: 'calculating the odds',
    bit: [
      "I'm a risk analyst. So when I say this plan has maybe a thirty percent chance, that's me being generous.",
      "Relax. Nobody's coming for you tonight. Probably. I'd put it at eighty-twenty.",
      "Mango sticky rice. That's what I'd kill for right now. Metaphorically. Mostly.",
    ],
    tease: [
      "Do you calculate everything?",
      "Eighty-twenty isn't relaxing.",
      "You'd kill for rice?",
    ],
    reply: [
      "It's free, and it's usually right.",
      "It is if you're the eighty.",
      "Mango sticky rice. Get it right."],
    home: ["A good job, a gym membership, and a lot of horror movies. And an ex-wife who's definitely watching.", "Bangkok, where my family thinks I'm on holiday. In a way, I am."],
    want: ["The money, the win, and to never be the one holding the knife when it happens.", "To stay close to power without anybody noticing I'm there."],
    conf: ["Out there I deny everything. In here I can admit it: I'm usually the one who started it.", "Everybody's a risk. Some people are just priced wrong."],
    askHome: ["So who's waiting for you back home?", "Got people at home? Partner?"],
    askWant: ["What's your upside here? What are you really after?", "What would you do with the money?"],
  },
};
