// td/story/kits/kits3.js — character kits, batch 3: the drag queens, at camp (see kits1.js for the shape)

export default {
  'Anita Crown Davenport': {
    thing: 'pageants',
    bit: [
      "Thank you so much for that question! I think the most important thing on this island is kindness. And hydration.",
      "I've been first alternate eleven times. Eleven! This time I'm going to be the winner. Thank you so much!",
      "Posture, everyone! Even when you're starving, you can starve with your shoulders back.",
    ],
    tease: [
      "Nobody asked you a question, Anita.",
      "Eleven times? That's a lot of almost.",
      "I'm not starving with my shoulders back.",
    ],
    reply: [
      "Somebody always does, eventually. I like to be ready.",
      "It's a lot of practice! Thank you so much!",
      "Then you'll starve with bad posture, and that's worse."],
    home: ["My drag mothers, the Davenports. I want to make the whole house proud.", "Texas, my crowns, and a closet full of sashes that say 'first alternate'."],
    want: ["To finally win something. Anything. Thank you so much.", "To make everyone like me. And to win. In that order, honestly."],
    conf: ["I miss shade sometimes. People tell me later. I just smile and say thank you.", "Everything is an interview question if you smile hard enough."],
    askHome: ["Thank you so much for being here! Who's waiting for you at home?", "Who are your people back home?"],
    askWant: ["What's your platform? Like, what do you stand for out here?", "What would winning mean to you?"],
  },
  Autumnatic: {
    thing: 'her outfits',
    bit: [
      "Ooh, she's pressed like a panini today! Look at her face. Ha!",
      "I made a new look out of the tarp and some vines. It's high-concept. It's about survival. And also sequins.",
      "Back in Brooklyn I emcee the club every Saturday. A crowd of drunk people is way scarier than this.",
    ],
    tease: [
      "Who's pressed like a panini?",
      "The tarp was our roof.",
      "Scarier than a jungle?",
    ],
    reply: [
      "Don't make me say it. You know who. Ha!",
      "It's a roof AND a moment.",
      "The jungle doesn't throw drinks at you."],
    home: ["The New York club scene. My sisters, my regulars, and a sewing machine held together with tape.", "Brooklyn. A tiny apartment and a giant wig wall."],
    want: ["To win, and to make the whole camp laugh while I do it.", "For someone to finally say my looks are high fashion. And mean it."],
    conf: ["I stir the pot. Gently. With love. And then I stand back and watch.", "My concepts are genius. My execution is a work in progress."],
    askHome: ["Okay, baby, who's at home? Spill it!", "Who's waiting on you back home?"],
    askWant: ["What are you really here for? The money? The drama? Both? Ha!", "What's the dream, baby?"],
  },
  'Cheryl Hole': {
    thing: 'being an Essex girl',
    bit: [
      "Right, I know my shelter looks like it was put together with a glue stick and a dream, but I'm having a lovely time!",
      "In Essex, we'd be at bottomless brunch by now. Here, it's bottomless rice. It's not the same, babe.",
      "I'm not saying I'm the funniest one here. I'm just saying nobody else is trying.",
    ],
    tease: [
      "It's going to fall down, Cheryl.",
      "Is that all you think about?",
      "We're trying, actually.",
    ],
    reply: [
      "Then I'll have a lovely time on the floor.",
      "No. Sometimes I think about the second brunch.",
      "Try harder, babe."],
    home: ["Essex! My mates, my nan, and every club in a ten-mile radius.", "My girls back home, who are definitely watching this at a pub."],
    want: ["To have the time of my life. And the money. Mostly the time of my life.", "To prove a party girl can go the distance."],
    conf: ["I laugh at myself first. That way nobody else gets to.", "I stir the pot a little. Not a lot. Just enough to make it bubble."],
    askHome: ["Go on then, who's at home? Tell me everything.", "You got someone back home, babe?"],
    askWant: ["What are you actually here for? Be honest, I won't tell. I will.", "What's the dream, babe?"],
  },
  Cupcakke: {
    thing: 'cabaret',
    bit: [
      "This rice is like a cupcake with no frosting. Sad, beige, and still somehow worth eating.",
      "I do brunch shows back home. I've sung show tunes over the sound of a blender. This is nothing.",
      "Oh, sweetie, if you think I'm only funny, you haven't seen me when I'm annoyed.",
    ],
    tease: [
      "Do you compare everything to cake?",
      "Over a blender?",
      "What happens when you're annoyed?",
    ],
    reply: [
      "Everything is cake, sweetie. Some of it's just bad cake.",
      "Two blenders. And a birthday party.",
      "I get very, very precise. It's like icing. Sharp edges."],
    home: ["My brunch regulars in San Antonio. They're like family, except they tip.", "A closet full of rhinestones and repurposed cake toppers."],
    want: ["To show everybody the funny one can also win.", "To be taken seriously. I'll still be funny about it."],
    conf: ["People underestimate the comedy queen. That's fine. Underestimate me all the way to the end.", "I laugh at my own jokes. Somebody has to start."],
    askHome: ["Sweetie, who's waiting at home?", "Tell me about home. I love a backstory."],
    askWant: ["What do you want out of this, sugar?", "What's the dream? Big or small?"],
  },
  'Gigi Cherie': {
    thing: 'mime',
    bit: [
      "The morning fog is like the beginning of a French film. Nothing has happened, and yet everything is sad.",
      "I spent six years doing mime. You learn that a gesture can say more than a speech. Like this.",
      "I have studied each of you. It is like watching a ballet performed by ducks.",
    ],
    tease: [
      "Okay, that's very dramatic for fog.",
      "You're just waving.",
      "Which one of us is the duck?",
    ],
    reply: [
      "All fog is dramatic. You simply do not listen.",
      "I am saying hello. Badly. On purpose.",
      "All of you. Beautifully."],
    home: ["A tiny theatre in Montréal and a very tolerant cat.", "My costume studio. Silent, white, and full of feathers."],
    want: ["To make something beautiful and strange. Winning would be the final pose.", "To be understood. Or at least, to be misunderstood interestingly."],
    conf: ["I rarely speak. When I do, I like it to count. Or to be funny. Ideally both.", "Everyone here is very loud. I am the pause between their sentences."],
    askHome: ["Tell me. Who waits for you, at home?", "Who do you miss? Your face is telling me."],
    askWant: ["What is it you want, truly?", "Why are you here? Not the money. The other reason."],
  },
  'Ginger Hollywood': {
    thing: 'being a Hollywood headliner',
    bit: [
      "Darling, star quality cannot be taught. But I'm willing to try with you. Briefly.",
      "Twenty years headlining in Los Angeles, and I've never once slept on a floor. This is a first, baby.",
      "Shoulders back, chin up. The cameras are always rolling, and they love a professional.",
    ],
    tease: [
      "Was that an insult?",
      "Welcome to the floor.",
      "Who made you the director?",
    ],
    reply: [
      "It was a review. You'll learn the difference.",
      "Thank you, darling. I'll be giving it two stars.",
      "Nobody. I simply am one."],
    home: ["My drag house. My children. Some of them are older than me, but they're still my children.", "Los Angeles, a wall of wigs, and a phone full of producers."],
    want: ["To end my career at the top. The very top.", "To prove the veteran still has the best act in town."],
    conf: ["I give advice. Some people call it controlling. I call it free mentorship.", "Every queen here thinks she's the star. I'm the one who's actually headlined."],
    askHome: ["Darling, who's waiting for you at home?", "Tell me about your family, baby."],
    askWant: ["What do you want from all this, baby? The truth.", "Where do you see yourself after this, darling?"],
  },
  'Marge Stache': {
    thing: 'knowing everybody\'s business',
    bit: [
      "Sweetheart, I'm not gossiping. I'm providing the community with important updates.",
      "I brought snacks. Sit down, have a cracker, and tell me who you're voting for. Kidding. Unless.",
      "I teach improv. The first rule is 'yes, and'. Which is also how I get people to tell me things.",
    ],
    tease: [
      "That's literally gossip.",
      "I'm not telling you who I'm voting for.",
      "You're doing it right now.",
    ],
    reply: [
      "It's journalism with snacks.",
      "Yes, and? Have another cracker.",
      "Yes, and you're still talking."],
    home: ["Chicago. My improv students and a dinner theatre that has murder mysteries every Thursday.", "A whole neighbourhood that's going to be furious I didn't take them with me."],
    want: ["To know everything that's going on. And to win, while I'm at it.", "To make everyone feel at home. Then send them home."],
    conf: ["Everybody tells the auntie everything. Everybody.", "I'm nurturing. And nosy. They're the same skill."],
    askHome: ["Who's at home, sweetheart? Tell your auntie.", "So, who's waiting for you? Spill it."],
    askWant: ["What do you really want, honey? Don't lie to auntie.", "What's your plan? I won't tell. I'll tell everyone."],
  },
  'Minnie Skurr': {
    thing: 'dancing',
    bit: [
      "Mami, if the beat drops, so do I. That's not a joke. That's my whole strategy.",
      "I learned the whole cheer routine in one try. One. Ask anybody.",
      "Babe, I'm twenty-two and I'm already better than half of you. No offence. Some offence.",
    ],
    tease: [
      "There is no beat, Minnie.",
      "Nobody here saw you learn it.",
      "That's a lot of offence.",
    ],
    reply: [
      "There's always a beat, babe. You're just not listening.",
      "That's because I'm that fast.",
      "I'm young! I'm allowed!"],
    home: ["Miami. My dance students and my mami, who's going to scream every time I'm on TV.", "My dance team. We're like sisters. Annoying, loud sisters."],
    want: ["To win, and to be the youngest one who ever did.", "To show everybody I'm more than a dancer."],
    conf: ["Choreography? Easy. Talking? Okay, sometimes I talk before I think.", "Everybody thinks the baby goes home first. The baby is not going home first."],
    askHome: ["Babe, who's at home for you?", "Who's watching for you back home, mami?"],
    askWant: ["What's your dream, babe? Tell me.", "What do you want out of this?"],
  },
  'Paige Turner': {
    thing: 'being a librarian',
    bit: [
      "Please lower your voice, young lady. Your outfit is already making enough noise.",
      "I worked twenty years in a used bookstore. You learn to judge a book by its cover. Accurately.",
      "This team is like a library book nobody returned. Overdue and slightly damp.",
    ],
    tease: [
      "Did you just call me loud?",
      "That's not what the saying means.",
      "Wow. Thanks.",
    ],
    reply: [
      "I called your outfit loud. You were collateral.",
      "It is now. I've revised it.",
      "Don't thank me. I've charged you a late fee."],
    home: ["Philadelphia. Twenty years of bars, books, and girls who learned their shade from me.", "A small apartment with far too many books and far too few chairs."],
    want: ["To win, and to finally be the one everybody quotes.", "To read everyone here. Literally and otherwise."],
    conf: ["I find the insecurity in about four minutes. Then I wait for the right moment.", "Advice from less experienced people is like a pamphlet. I'll glance at it."],
    askHome: ["Young lady, who's waiting for you at home?", "Tell me about your family. I'll try not to judge. I'll fail."],
    askWant: ["And what is it you want? The short version, please.", "What exactly brought you here?"],
  },
  Quin: {
    thing: 'being an artist',
    bit: [
      "The shelter's actually quite a strong silhouette. It represents, like, collective fragility.",
      "I did a show in London where I was the installation. People walked around me for three hours.",
      "I'm not a model. I'm an artist who happens to be photographed a lot.",
    ],
    tease: [
      "It's a pile of sticks, Quin.",
      "What did you do for three hours?",
      "Isn't that what a model is?",
    ],
    reply: [
      "That's the fragility. You get it.",
      "Existed. Loudly. Without moving.",
      "No. A model doesn't have a concept."],
    home: ["London. My studio, my club, and a group chat that thinks I'm pretentious.", "Art school friends who are going to dissect every outfit I wear on this show."],
    want: ["To be taken seriously as an artist. The money funds the art.", "To make a moment people talk about in galleries."],
    conf: ["When people ask me what my concept means, I need about twelve seconds to make one up.", "Everyone's very literal here. It's exhausting, but also inspiring."],
    askHome: ["So, what's your world like, back home?", "Who's your scene? Like, who do you run with?"],
    askWant: ["What's your concept for this? Like, as a person?", "What do you actually want from it?"],
  },
  Riot: {
    thing: 'activism',
    bit: [
      "If my opinion bothers you, good. It means you heard it.",
      "Back in Detroit I raise money for queer youth housing. A vote is just a fundraiser with worse snacks.",
      "I'm not here to make anybody comfortable. I'm here to win, and to say what nobody else will.",
    ],
    tease: [
      "Do you ever just relax?",
      "That's a very weird way to see a vote.",
      "That's a lot of pressure for breakfast.",
    ],
    reply: [
      "When everybody's safe. So, no.",
      "It's the right way. You'll see.",
      "Breakfast can handle it."],
    home: ["My community. The kids I organise for. They're the reason I'm here.", "Detroit. My tattoo shop and every protest I've ever led."],
    want: ["Money for the youth housing project. Every dollar.", "To win, loudly, and on my own terms."],
    conf: ["I turn every disagreement into a debate. I know. I'm not going to stop.", "I don't do fake. Not in my art, not in my game."],
    askHome: ["Who's your community back home?", "Who are you fighting for?"],
    askWant: ["What do you actually stand for out here?", "What's the money for, if you win?"],
  },
  'Sharon Needles': {
    thing: 'horror',
    bit: [
      "Darling, I'm not inside your head. You simply left the door unlocked.",
      "I host a horror show back home. Watching this team make dinner is scarier.",
      "She has star quality, assuming the star already burned out.",
    ],
    tease: [
      "Okay, that's creepy.",
      "Wow. That's just rude.",
      "Who are you even talking about?",
    ],
    reply: [
      "Creepy is just honest in the dark.",
      "Rude is when you mean it. I always mean it.",
      "Oh, you'll work it out. Eventually."],
    home: ["Providence. My club nights, my fans, and a coffin I sleep in. Kidding. It's a futon.", "My online audience. They love a villain, and I love being loved."],
    want: ["Fame. Screen time. If I have to be the villain to get it, hand me the cape.", "To be the one everybody talks about after."],
    conf: ["Everybody's got a weak spot. I just press on it until they flinch.", "I'll be the villain. Villains get the best lines."],
    askHome: ["And who's waiting for you at home, darling? Anyone who'll miss you?", "Tell me about home. I'm collecting weaknesses. I mean stories."],
    askWant: ["What do you want, darling? Truly? I'm dying to know.", "Why are you here? Be honest. I'll know."],
  },
  Taystee: {
    thing: 'being beautiful',
    bit: [
      "I didn't come here to be funny. I came here to be photographed.",
      "Everybody's freaking out about the challenge. I'm just going to look good doing it.",
      "Is this lighting doing anything for me? It should be. I'm doing something for it.",
    ],
    tease: [
      "There's no photographer, Taystee.",
      "That's not a strategy.",
      "The lighting is just the sun.",
    ],
    reply: [
      "There's always a camera.",
      "It's worked so far.",
      "And the sun is lucky."],
    home: ["Dallas. A mirror, a sewing machine, and a stack of agency rejections I've framed.", "Not much. I'm my own whole team."],
    want: ["To be admired. And the money. Mostly the admiring.", "To prove the agencies wrong. All of them."],
    conf: ["I don't need to be the funny one. I'm the beautiful one. That's a job.", "Criticism? I shrug. Then I check my reflection. Still good."],
    askHome: ["Who's at home for you?", "You have somebody back home?"],
    askWant: ["What do you want out of this?", "What's your thing, out here?"],
  },
  'Velvet Vixen': {
    thing: 'choreography',
    bit: [
      "Give me eight counts and a little floor space, and I'll fix this whole challenge.",
      "I wasn't doing too much. Everybody else was doing too little.",
      "I trained in jazz, hip-hop, Bollywood and bhangra. I can dance my way out of anything. Including a vote.",
    ],
    tease: [
      "It's not a dance challenge, Velvet.",
      "You were doing way too much.",
      "You can't dance out of a vote.",
    ],
    reply: [
      "Everything's a dance challenge if you're brave enough.",
      "That's called commitment.",
      "Watch me. Five, six, seven, eight."],
    home: ["Toronto. My dance students and a family that still asks when I'm getting a real job.", "A South Asian dance night that I basically run now. They're my people."],
    want: ["To win, and to never be anybody's backup dancer again.", "To show everybody what I can do when it's my spotlight."],
    conf: ["I interrupt people. I know. My brain's just already on the next count.", "I'm loyal. Ride or die. I just ride very fast."],
    askHome: ["Okay, who's at home? Quick, quick, tell me!", "Who are your people back home?"],
    askWant: ["What do you want out of this? Tell me fast before I start dancing.", "What's your dream?"],
  },
};
