// ══════════════════════════════════════════════════════════════════════
// bb/story/lines/feud.js — two people who cannot stand each other, scene by scene
// ══════════════════════════════════════════════════════════════════════
//
// Written against docs/bb-dialogue-style.md. Each entry is a WHOLE scene.
//
// Roles:
//   friction   a did it, b had it done to them (c: somebody else in the room)
//   argument   a starts it (the one with the grievance), b is on the receiving end
//   apology    a apologises, b decides
//   cold       a and b are not speaking; c may notice
// {when} is when the earlier step happened: earlier / yesterday / the other day / last week.
//
// Recaps ('recap.feud.<step>.<outcome>.<a|b>') open a scene whose cause the viewer did
// not see: the person who was there says it plainly in the Diary Room.

export default {
  // ── friction: chores, food, noise, mess ─────────────────────────────
  'story.feud.friction.chores': [
    { id: 'sf.c1', room: 'kitchen', turns: [
      { beat: 'Kitchen. {b} opens the dishwasher. It is full of clean plates nobody has put away, and the sink is full of dirty ones.' },
      { by: 'b', say: "Whose pan is this?" },
      { by: 'a', say: "Mine. I'm letting it soak." },
      { by: 'b', say: "Since this morning?" },
      { by: 'a', say: "It's a soaking pan." },
      { by: 'b', say: "That's not a thing. That's not a type of pan." },
      { by: 'a', say: "It's literally a thing. Everybody does it." },
      { by: 'b', say: "Okay, well, everybody needs the sink." },
      { beat: '{a} takes the pan out of the sink, puts it on the counter, and walks off.' },
      { by: 'b', say: "...So now it's on the counter." },
      { by: 'b', dr: "It's not about the pan. It's that {a} thinks the rest of us are the staff." },
    ] },
    { id: 'sf.c2', room: 'kitchen', turns: [
      { by: 'b', say: "Did somebody eat the rest of the chicken?" },
      { beat: 'Silence. {a} is holding a plate of chicken.' },
      { by: 'a', say: "Was it yours?" },
      { by: 'b', say: "I made it. For four people. I said I made it for four people." },
      { by: 'a', say: "I didn't hear that part." },
      { by: 'b', say: "You were standing right there." },
      { by: 'a', say: "Okay, I'm sorry, do you want it back?" },
      { by: 'b', say: "You've eaten half of it!" },
      { by: 'a', say: "So you want half?" },
      { beat: '{b} closes the fridge very hard.' },
      { by: 'a', dr: "It's chicken. In this house people will forgive you for a lie before they forgive you for chicken." },
    ] },
    { id: 'sf.c3', room: 'bedroom', turns: [
      { beat: 'Bedroom, after lights out. {a} is talking. Loudly.' },
      { by: 'b', say: "Hey. Some of us are trying to sleep." },
      { by: 'a', say: "It's like eleven." },
      { by: 'b', say: "It's one-thirty." },
      { by: 'a', say: "...Oh. Okay. Sorry." },
      { beat: 'Two minutes later {a} laughs at something. Loudly.' },
      { by: 'b', say: "Seriously?" },
      { by: 'a', say: "I said sorry!" },
      { by: 'b', say: "Then be sorry quieter!" },
      { by: 'b', dr: "I've slept about four hours since I got here, and I can tell you exactly whose fault every one of the missing ones is." },
    ] },
    { id: 'sf.c4', room: 'bathroom', turns: [
      { by: 'b', say: "Hey, so, the bathroom." },
      { by: 'a', say: "What about it?" },
      { by: 'b', say: "There's hair. Everywhere. On everything." },
      { by: 'a', say: "And you think it's mine." },
      { by: 'b', say: "It's long and it's your color." },
      { by: 'a', say: "Wow. Okay. Detective {b}." },
      { by: 'b', say: "I'm not trying to be a jerk, I just want to brush my teeth without—" },
      { by: 'a', say: "Fine. I'll clean it. Happy?" },
      { by: 'b', say: "Yes, actually." },
      { by: 'a', dr: "Was it my hair? Yes. Did I need to be called Rapunzel in front of the whole kitchen? No." },
    ] },
    { id: 'sf.c5', room: 'kitchen', turns: [
      { beat: '{b} holds up an empty coffee tin and shakes it.' },
      { by: 'b', say: "Who finished the coffee and put the empty tin back?" },
      { by: 'a', say: "I was going to tell someone." },
      { by: 'b', say: "You were going to tell someone. When?" },
      { by: 'a', say: "When they asked. Which you just did. So. It was me." },
      { by: 'b', say: "You know we don't get more until shopping." },
      { by: 'a', say: "I know. I'm sorry. I was tired." },
      { by: 'b', say: "We're all tired! That's what the coffee was for!" },
      { by: 'b', dr: "I'm not a morning person. Without coffee I'm not a person at all. {a} knows that now." },
    ] },
    { id: 'sf.c6', presumes: ['hoh'], turns: [
      { by: 'b', say: "Can I ask you something without it being a thing?" },
      { by: 'a', say: "That's how every thing starts." },
      { by: 'b', say: "You've had my towel. For three days." },
      { by: 'a', say: "That's my towel." },
      { by: 'b', say: "Mine's the blue one." },
      { by: 'a', say: "They're all blue!" },
      { by: 'b', say: "Mine's the bluer one." },
      { beat: 'They both look at the towel.' },
      { by: 'a', say: "...Okay, that is bluer." },
      { by: 'a', dr: "Living with strangers is a lot of finding out you've been using somebody's towel." },
    ] },
    { id: 'sf.c7', room: 'kitchen', when: { band: ['cold', 'enemies'] }, turns: [
      { beat: '{a} leaves a bowl on the counter, right next to the sink.' },
      { by: 'b', say: "The sink's right there." },
      { by: 'a', say: "I can see the sink." },
      { by: 'b', say: "So put it in the sink." },
      { by: 'a', say: "I'm going to wash it." },
      { by: 'b', say: "When?" },
      { by: 'a', say: "When I'm done being told to." },
      { beat: '{a} leaves the bowl exactly where it is and walks away.' },
      { by: 'b', dr: "It's one bowl. It's one bowl, and it's going to be there tomorrow, and that's the point." },
    ] },
  ],

  // ── friction: a joke that cut ───────────────────────────────────────
  'story.feud.friction.joke': [
    { id: 'sf.j1', room: 'living-room', when: { third: true }, turns: [
      { beat: 'Living room. Everyone is on the sofas. {a} stands up.' },
      { by: 'a', say: "Okay, okay, who's this?" },
      { beat: '{a} sits down very slowly, crosses both arms, and sighs at the ceiling.' },
      { by: 'c', say: "Oh my god, that's {b}!" },
      { beat: 'The room falls apart laughing. {b} smiles, a beat too late.' },
      { by: 'b', say: "Yeah. Good one." },
      { by: 'a', say: "Come on, it's a little bit you." },
      { by: 'b', say: "I said good one." },
      { by: 'b', dr: "Everybody laughed. I laughed. I wasn't laughing." },
    ] },
    { id: 'sf.j2', turns: [
      { by: 'a', say: "Oh, {b}'s doing the thinking face." },
      { by: 'b', say: "I don't have a thinking face." },
      { by: 'a', say: "You do, it's like this." },
      { beat: '{a} squints and purses up the mouth.' },
      { by: 'b', say: "Okay." },
      { by: 'a', say: "And then you go 'hmm'. Every time." },
      { by: 'b', say: "Are you done?" },
      { by: 'a', say: "Relax, I'm messing with you." },
      { by: 'b', dr: "I know what that was. That was {a} telling the whole room I'm the one always plotting. With a smile on." },
    ] },
    { id: 'sf.j3', turns: [
      { by: 'b', say: "I told you that in private." },
      { by: 'a', say: "It was a funny story!" },
      { by: 'b', say: "It was private. I told you because you asked." },
      { by: 'a', say: "Nobody cares, it's a cute story." },
      { by: 'b', say: "I care. That's the whole point. I care." },
      { by: 'a', say: "Okay. Sorry. Jeez." },
      { by: 'b', dr: "I've known {a} for like a week. I'm never telling {a} anything again." },
    ] },
    { id: 'sf.j4', room: 'kitchen', when: { third: true }, turns: [
      { beat: 'Somebody puts music on. {b} starts dancing by the counter.' },
      { by: 'a', say: "Oh no. Oh no, {b}'s doing the dance." },
      { by: 'b', say: "What dance?" },
      { by: 'a', say: "The one where your arms don't know what your legs are doing." },
      { by: 'c', say: "Stop, that's mean." },
      { by: 'c', say: "...It's a little bit true, though." },
      { beat: '{b} stops dancing.' },
      { by: 'b', say: "Wow. Okay. I'll just stand here, then." },
      { by: 'a', say: "Come on, keep going, I'm kidding!" },
      { by: 'b', dr: "I was having fun. For about a minute. Then {a} made sure I wasn't." },
    ] },
    { id: 'sf.j5', turns: [
      { by: 'a', say: "Oh no, careful, {b}'s going to cry." },
      { by: 'b', say: "I'm not going to cry." },
      { by: 'a', say: "Lip's going." },
      { by: 'b', say: "My lip is not going." },
      { by: 'a', say: "It's a little bit going." },
      { beat: '{b} gets up and goes to the bathroom.' },
      { by: 'a', say: "What? It was a joke!" },
      { by: 'b', dr: "I cried once. Once. And now that's my whole personality to {a}." },
    ] },
    { id: 'sf.j6', room: 'kitchen', turns: [
      { by: 'a', say: "Can you even cook? Like, actually?" },
      { by: 'b', say: "I've been cooking since I was twelve." },
      { by: 'a', say: "Twelve-year-old food, then." },
      { by: 'b', say: "You've had seconds." },
      { by: 'a', say: "I was being polite." },
      { by: 'b', say: "Then stop being polite and make your own." },
      { by: 'b', dr: "{a} has eaten everything I've made in here, and then made fun of it. That's a special kind of person." },
    ] },
    { id: 'sf.j7', when: { register: 'schemer', third: true }, turns: [
      { by: 'c', say: "What do you make of {b}, honestly?" },
      { by: 'a', say: "Honestly, I love {b}. {b}'s like a golden retriever." },
      { by: 'b', say: "I'm standing right here." },
      { by: 'a', say: "Loyal. Happy. Not a lot going on upstairs." },
      { by: 'b', say: "Wow." },
      { by: 'a', say: "I'm kidding! Kind of." },
      { by: 'a', dr: "If people think {b} is a puppy, nobody looks at {b} as a threat. Including {b}. You're welcome." },
      { by: 'b', dr: "I'm not stupid. I know a compliment that's really an insult when I hear one." },
    ] },
  ],

  // ── friction: somebody snaps ───────────────────────────────────────
  'story.feud.friction.snap': [
    { id: 'sf.s1', room: 'kitchen', turns: [
      { by: 'b', say: "Morning!" },
      { by: 'a', say: "Can you not? Like, five minutes. Can I have five minutes?" },
      { by: 'b', say: "I said good morning." },
      { by: 'a', say: "And I said five minutes." },
      { by: 'b', say: "Okay. Wow." },
      { beat: '{b} takes a cereal bowl to the other end of the table.' },
      { by: 'a', dr: "Was I rude? Yes. Did I sleep? No. Those two things are connected." },
      { by: 'b', dr: "I've never been told off for saying good morning before. New experience." },
    ] },
    { id: 'sf.s2', turns: [
      { by: 'b', say: "Hey, are you using the—" },
      { by: 'a', say: "Yes. I'm using it. Obviously I'm using it." },
      { by: 'b', say: "I was just asking." },
      { by: 'a', say: "You were going to ask me to hurry up." },
      { by: 'b', say: "I was going to ask if you wanted a tea." },
      { beat: 'Pause.' },
      { by: 'a', say: "...Oh." },
      { by: 'b', say: "Yeah. Oh." },
      { by: 'a', dr: "In my defense, everybody in this house asks me to hurry up. Apparently not everybody." },
    ] },
    { id: 'sf.s3', turns: [
      { by: 'b', say: "You okay? You've been quiet all day." },
      { by: 'a', say: "Why does everybody keep asking me that?" },
      { by: 'b', say: "Because you've been quiet all day." },
      { by: 'a', say: "Maybe I just don't want to talk to anybody. Is that allowed?" },
      { by: 'b', say: "It's allowed." },
      { by: 'a', say: "Great. Then let me do it." },
      { beat: '{b} holds both hands up and backs out of the room.' },
      { by: 'b', dr: "I tried. I'm not trying again." },
    ] },
    { id: 'sf.s4', when: { band: ['cold', 'enemies'] }, turns: [
      { by: 'b', say: "You left the door open again." },
      { by: 'a', say: "Oh my god, then close it!" },
      { by: 'b', say: "Don't shout at me." },
      { by: 'a', say: "I'm not shouting!" },
      { by: 'b', say: "You're literally shouting right now!" },
      { by: 'a', say: "Because you follow me around telling me about doors!" },
      { beat: '{a} slams the door. Shut.' },
      { by: 'b', say: "...Thank you." },
      { by: 'a', dr: "The door. It's always the door. {b} has a thing about the door." },
    ] },
    { id: 'sf.s5', turns: [
      { by: 'b', say: "Do you want to play cards with us?" },
      { by: 'a', say: "No." },
      { by: 'b', say: "Okay, you don't have to—" },
      { by: 'a', say: "I said no. I don't want to play cards. I don't want to play anything." },
      { by: 'b', say: "Alright. Sorry I asked." },
      { by: 'a', say: "Yeah, me too." },
      { by: 'b', dr: "That's the last time I invite {a} to anything. Cards. It was cards." },
    ] },
    { id: 'sf.s6', room: 'bedroom', when: { late: false }, turns: [
      { beat: '{b} sits down on the end of a bed.' },
      { by: 'a', say: "That's my bed." },
      { by: 'b', say: "I'm just sitting for a second." },
      { by: 'a', say: "Sit on your own bed." },
      { by: 'b', say: "Mine's right there, I'm literally one bed over." },
      { by: 'a', say: "Then it's not far, is it?" },
      { beat: '{b} gets up, very slowly.' },
      { by: 'b', say: "You're in a mood." },
      { by: 'a', say: "I'm in a house full of people and none of the doors lock. Yes. I'm in a mood." },
    ] },
  ],

  // ── the argument ────────────────────────────────────────────────────
  'story.feud.argument.any': [
    { id: 'sa.1', turns: [
      { by: 'a', say: "Can I say something? Since apparently everyone else gets to." },
      { by: 'b', say: "Here we go." },
      { by: 'a', say: "No, not 'here we go'. You don't get to 'here we go' me." },
      { by: 'b', say: "Okay. Say it." },
      { by: 'a', say: "Since {when}, you've been rolling your eyes every time I open my mouth. Every time. At dinner, in the kitchen, in front of people—" },
      { by: 'b', say: "I don't roll my eyes—" },
      { by: 'a', say: "—you're doing it right now!" },
      { by: 'b', say: "Because you're being dramatic!" },
      { by: 'a', say: "I'm being dramatic? You haven't said one nice word to me since!" },
      { by: 'b', say: "Maybe because you haven't given me a reason to!" },
      { beat: 'Nobody else in the house is talking any more.' },
      { by: 'a', say: "Wow. Okay. Good to know." },
      { by: 'b', say: "You asked." },
      { by: 'a', say: "Yeah. I did." },
      { beat: '{a} walks out.' },
      { by: 'b', dr: "Do I feel bad? A little. Was I wrong? No." },
      { by: 'a', dr: "Now I know. And knowing is better." },
    ] },
    { id: 'sa.2', room: 'kitchen', when: { third: true }, turns: [
      { by: 'a', say: "Do you have a problem with me? Like, actually? Because I'd rather just know." },
      { by: 'b', say: "I don't have a problem with you." },
      { by: 'a', say: "Then what was {when}?" },
      { by: 'b', say: "That wasn't a problem. That was a comment." },
      { by: 'a', say: "It was a comment in front of everybody." },
      { by: 'b', say: "Then don't do stuff that gets comments!" },
      { by: 'c', say: "Okay, okay. Guys." },
      { by: 'a', say: "No, {c}, I'm fine. I'm asking a question." },
      { by: 'b', say: "And I answered it." },
      { by: 'a', say: "You didn't, though. You never do. You just make a face and walk off—" },
      { by: 'b', say: "I'm not walking off—" },
      { by: 'a', say: "—and then I hear about it from three other people!" },
      { by: 'b', say: "Who? Who are you hearing it from?" },
      { by: 'a', say: "Doesn't matter who." },
      { by: 'b', say: "It matters to me!" },
      { beat: '{c} quietly picks up a plate and leaves the kitchen.' },
      { by: 'b', dr: "Somebody in this house is carrying stories to {a}. And when I find out who, that's my next conversation." },
    ] },
    { id: 'sa.3', room: 'bedroom', turns: [
      { by: 'a', say: "Hey. Can we talk? Bedroom?" },
      { by: 'b', say: "Is this about {when}?" },
      { by: 'a', say: "It's about all of it, honestly." },
      { beat: 'Bedroom. {a} shuts the door. {b} sits on a bed. {a} stays standing.' },
      { by: 'a', say: "I'm going to say this once, and I want you to actually listen." },
      { by: 'b', say: "I'm listening." },
      { by: 'a', say: "You talk down to me. Not all the time. But enough. Enough that people have noticed. And I've let it go, and let it go, and I'm done letting it go." },
      { by: 'b', say: "That's not— I don't talk down to anyone." },
      { by: 'a', say: "You just did it. Just now. 'I don't talk down to anyone.' Like I'm five." },
      { by: 'b', say: "That's my normal voice!" },
      { by: 'a', say: "Then your normal voice is the problem!" },
      { beat: 'Pause.' },
      { by: 'b', say: "...Okay. I hear you." },
      { by: 'a', say: "Do you?" },
      { by: 'b', say: "I said I hear you. What else do you want?" },
      { by: 'a', dr: "'I hear you.' That's what people say when they're waiting for you to stop talking." },
    ] },
    { id: 'sa.4', room: 'kitchen', when: { late: false, band: 'enemies' }, turns: [
      { by: 'a', say: "Oh, look who it is." },
      { by: 'b', say: "Don't start." },
      { by: 'a', say: "I'm not starting anything. I'm just standing in my own kitchen." },
      { by: 'b', say: "It's not your kitchen." },
      { by: 'a', say: "It's more my kitchen than it is yours. You've never washed a single thing in it." },
      { by: 'b', say: "Is that what this is about? Dishes? After {when}?" },
      { by: 'a', say: "It's about you! It's about you being you, all day, every day, in my face!" },
      { by: 'b', say: "Then go upstairs! Nobody's making you look at me!" },
      { by: 'a', say: "A whole house full of people and you're the one I can't get away from!" },
      { by: 'b', say: "Funny, I was going to say the exact same thing!" },
      { beat: 'They both reach for the same mug. Neither lets go.' },
      { by: 'a', say: "Seriously?" },
      { by: 'b', say: "Seriously." },
      { beat: '{a} lets go. {b} pours coffee into it, slowly, and walks out.' },
      { by: 'a', dr: "That was my mug. Everybody knows that's my mug. That was a declaration of war with a mug." },
    ] },
    { id: 'sa.5', turns: [
      { by: 'a', say: "Can I just ask — why did you do that {when}?" },
      { by: 'b', say: "Do what?" },
      { by: 'a', say: "You know what." },
      { by: 'b', say: "I genuinely don't." },
      { by: 'a', say: "Okay, so you're going to make me say it. Fine. You made me look stupid. In front of people I'm trying to work with." },
      { by: 'b', say: "That wasn't— I wasn't trying to make you look like anything." },
      { by: 'a', say: "But you did." },
      { by: 'b', say: "Then I'm sorry it came across like that." },
      { by: 'a', say: "'Came across like that.' That's not sorry. That's a sorry that blames me." },
      { by: 'b', say: "What do you want me to say?" },
      { by: 'a', say: "I want you to say you did it!" },
      { by: 'b', say: "Fine! I did it! Happy?" },
      { by: 'a', say: "...No. Actually. Not really." },
      { by: 'b', dr: "{a} wanted an apology and a confession and a fight all at once. I can only do two of those before lunch." },
    ] },
    { id: 'sa.6', when: { register: 'fiery' }, turns: [
      { by: 'a', say: "No. No, we're doing this now." },
      { by: 'b', say: "Doing what?" },
      { by: 'a', say: "This! You and me! Since {when}, I've been biting my tongue, and I'm done, I'm done biting it." },
      { by: 'b', say: "Then stop biting it, nobody asked you to." },
      { by: 'a', say: "You think you're so much better than everyone. You walk around this house like you're the HOH every week—" },
      { by: 'b', say: "Oh my god." },
      { by: 'a', say: "—and you're not! You're not anything! You're a person who eats the last of everything and says sorry like it's a favor!" },
      { by: 'b', say: "Are you finished?" },
      { by: 'a', say: "No, I'm not finished! I'll tell you when I'm finished!" },
      { by: 'b', say: "Then let me know, because I'm going to bed." },
      { beat: '{b} walks out.' },
      { by: 'a', say: "Yeah! Walk away! That's what you do!" },
      { by: 'a', dr: "Did I lose it a bit? Yeah. Do I regret it? Ask me tomorrow." },
      { by: 'b', dr: "{a} wanted an audience. I don't do audiences." },
    ] },
    { id: 'sa.7', when: { register: ['cool', 'schemer'] }, turns: [
      { by: 'a', say: "Sit down a second." },
      { by: 'b', say: "I'm good standing." },
      { by: 'a', say: "Suit yourself. I just want to understand something. What was that, {when}?" },
      { by: 'b', say: "What was what?" },
      { by: 'a', say: "See, you do this. You answer a question with a question, and then people forget what they asked." },
      { by: 'b', say: "I don't know what you want me to say." },
      { by: 'a', say: "The truth would be a nice start." },
      { by: 'b', say: "The truth is it wasn't a big deal." },
      { by: 'a', say: "It was a big deal to me. That's two people who think it's a big deal, if you count me. And you should count me." },
      { by: 'b', say: "Okay." },
      { by: 'a', say: "Okay what?" },
      { by: 'b', say: "Okay, I'll count you." },
      { by: 'a', dr: "I don't yell. I don't need to. I just ask the question again until the answer gets honest." },
    ] },
    { id: 'sa.8', turns: [
      { by: 'b', say: "Are you going to keep ignoring me, or…" },
      { by: 'a', say: "I'm not ignoring you." },
      { by: 'b', say: "You walked out of the room when I walked in. Twice." },
      { by: 'a', say: "Maybe I was leaving anyway." },
      { by: 'b', say: "Twice?" },
      { by: 'a', say: "Fine. You want to know why? Because of {when}. Because I'm still mad about it, and if I talk to you right now I'll say something I can't take back." },
      { by: 'b', say: "Then say it." },
      { by: 'a', say: "You don't want me to." },
      { by: 'b', say: "I really do. Say it." },
      { by: 'a', say: "...I thought we were friends. That's it. That's the thing. I thought we were friends, and friends don't do that." },
      { beat: '{b} opens up to answer, and nothing comes out.' },
      { by: 'b', dr: "I had a whole comeback ready. And then {a} said that, and I had nothing." },
    ] },
  ],

  // ── the apology ─────────────────────────────────────────────────────
  'story.feud.apology.accepted': [
    { id: 'sp.a1', room: 'kitchen', turns: [
      { beat: '{b} is doing the dishes. {a} comes in, stops, and picks up a towel.' },
      { by: 'a', say: "Hey." },
      { by: 'b', say: "Hey." },
      { by: 'a', say: "Can I talk to you for a sec?" },
      { by: 'b', say: "I'm kind of in the middle of something." },
      { by: 'a', say: "Two seconds." },
      { by: 'b', say: "...Okay." },
      { by: 'a', say: "{when}. That wasn't cool. I know it wasn't." },
      { by: 'b', say: "No. It wasn't." },
      { by: 'a', say: "I was trying to be funny, or— I don't know what I was trying to be. It came out wrong." },
      { by: 'b', say: "Everybody heard it, though." },
      { by: 'a', say: "I know. I know. I'm sorry." },
      { by: 'b', say: "It's fine." },
      { by: 'a', say: "Is it?" },
      { by: 'b', say: "It will be. Just don't do it again." },
      { by: 'a', say: "I won't. I swear." },
      { by: 'b', dr: "Do I believe {a}? Kind of. Do I trust {a}? Not yet." },
    ] },
    { id: 'sp.a2', turns: [
      { by: 'a', say: "Got a minute?" },
      { by: 'b', say: "Depends. Are you going to shout at me?" },
      { by: 'a', say: "No. I'm going to say sorry. Which is way harder, so be nice." },
      { by: 'b', say: "Go on, then." },
      { by: 'a', say: "I was a jerk {when}. I was tired and I was stressed and you were just there. That's not an excuse. That's just what happened." },
      { by: 'b', say: "You really hurt my feelings." },
      { by: 'a', say: "I know." },
      { by: 'b', say: "Like, I went to bed upset." },
      { by: 'a', say: "I know. I'm really sorry." },
      { beat: 'A long pause.' },
      { by: 'b', say: "...Okay. Thank you. For actually coming to say it." },
      { by: 'a', say: "Hug?" },
      { by: 'b', say: "Don't push it." },
      { beat: '{b} hugs {a} anyway.' },
      { by: 'a', dr: "That was the hardest conversation I've had in here. Harder than any comp." },
    ] },
    { id: 'sp.a3', turns: [
      { by: 'a', say: "I owe you an apology." },
      { by: 'b', say: "You do." },
      { by: 'a', say: "You're not going to make this easy, are you?" },
      { by: 'b', say: "Nope." },
      { by: 'a', say: "Fair. Okay. I'm sorry for {when}. I was out of line." },
      { by: 'b', say: "Thank you." },
      { by: 'a', say: "That's it?" },
      { by: 'b', say: "What do you want, a speech? You said sorry, I said thank you. We're good." },
      { by: 'a', say: "We're good?" },
      { by: 'b', say: "We're good. Just — think next time." },
      { by: 'a', say: "Deal." },
      { by: 'a', dr: "I came in with a whole speech prepared. Didn't need any of it. Kind of annoyed about that, honestly." },
    ] },
    { id: 'sp.a4', room: 'backyard', when: { band: ['friends', 'neutral'] }, turns: [
      { beat: 'Backyard. {b} is lying on a lounger. {a} sits down on the next one.' },
      { by: 'a', say: "So I've been thinking." },
      { by: 'b', say: "Dangerous." },
      { by: 'a', say: "Ha. Yeah. About {when}." },
      { by: 'b', say: "Oh." },
      { by: 'a', say: "I don't want this to be a thing. You're one of like three people in here I actually like. I don't want to be weird with you over something stupid I said." },
      { by: 'b', say: "It was pretty stupid." },
      { by: 'a', say: "It was really stupid. I'm sorry." },
      { by: 'b', say: "Okay." },
      { by: 'a', say: "Okay we're fine, or okay you heard me?" },
      { by: 'b', say: "Okay we're fine. Lie down, you're blocking my sun." },
      { by: 'b', dr: "I can stay mad for days. With {a} I made it about a day and a half. That's how I know I actually like {a}." },
    ] },
    { id: 'sp.a5', turns: [
      { by: 'a', say: "Hey, um. I made you a coffee." },
      { by: 'b', say: "...Why?" },
      { by: 'a', say: "Because I'm sorry about {when}, and I'm better at coffee than I am at saying sorry." },
      { by: 'b', say: "This is a peace coffee." },
      { by: 'a', say: "It's a peace coffee." },
      { by: 'b', say: "Did you put sugar in it?" },
      { by: 'a', say: "Two." },
      { by: 'b', say: "I take one." },
      { by: 'a', say: "Then it's an extra-sorry coffee." },
      { beat: '{b} laughs despite everything.' },
      { by: 'b', say: "Fine. Apology accepted. Coffee mostly accepted." },
      { by: 'b', dr: "Two sugars. Disgusting. But I drank it, because I knew what it meant." },
    ] },
    { id: 'sp.a6', room: 'kitchen', when: { third: true }, turns: [
      { beat: 'Kitchen. {c} is there too. {a} comes in and clears their throat.' },
      { by: 'a', say: "Can I say something? In front of {c}, since {c} was there." },
      { by: 'c', say: "Oh no." },
      { by: 'a', say: "No, it's good. {b}, I'm sorry about {when}. You didn't deserve that, and I said it where everyone could hear it, so I'm saying sorry where people can hear it too." },
      { by: 'b', say: "...Wow. Okay." },
      { by: 'c', say: "That was actually really nice." },
      { by: 'b', say: "Yeah. Thank you. Seriously." },
      { by: 'a', say: "Okay, I'm leaving before I cry." },
      { by: 'b', dr: "Saying it in front of {c} — that took guts. I didn't think {a} had that in there." },
    ] },
  ],
  'story.feud.apology.refused': [
    { id: 'sp.r1', turns: [
      { by: 'a', say: "Hey. Can I say something?" },
      { by: 'b', say: "If it's about {when}, I don't want to hear it." },
      { by: 'a', say: "I just want to apologise." },
      { by: 'b', say: "And I don't want to accept it. So we're stuck." },
      { by: 'a', say: "Come on. I'm trying here." },
      { by: 'b', say: "You're trying now. Where was the trying when you said it?" },
      { by: 'a', say: "That's fair. But I'm sorry. I mean it." },
      { by: 'b', say: "Okay. You said it. I heard it." },
      { by: 'a', say: "But you don't accept it." },
      { by: 'b', say: "Not today." },
      { by: 'a', dr: "I said sorry. I meant it. What happens now is on {b}." },
      { by: 'b', dr: "Sorry is a word. I want to see something different first." },
    ] },
    { id: 'sp.r2', turns: [
      { by: 'a', say: "Look. I'm sorry, okay? For {when}." },
      { by: 'b', say: "Are you sorry, or are you sorry because it's eviction week and you need votes?" },
      { by: 'a', say: "Wow." },
      { by: 'b', say: "It's a real question." },
      { by: 'a', say: "I'm sorry because I'm sorry." },
      { by: 'b', say: "Funny timing, though." },
      { by: 'a', say: "Forget it. Forget I said anything." },
      { by: 'b', say: "Already forgotten." },
      { by: 'b', dr: "Funny how people get sorry right when they need something." },
    ] },
    { id: 'sp.r3', turns: [
      { by: 'a', say: "I know you're mad at me." },
      { by: 'b', say: "Good, at least you know something." },
      { by: 'a', say: "I'm trying to say sorry." },
      { by: 'b', say: "So say it." },
      { by: 'a', say: "I'm sorry you got upset about {when}." },
      { by: 'b', say: "No. Nope. That's not it." },
      { by: 'a', say: "What?" },
      { by: 'b', say: "'Sorry you got upset.' That's you saying sorry for my feelings. Try again." },
      { by: 'a', say: "I'm not doing this." },
      { by: 'b', say: "Then don't." },
      { by: 'b', dr: "If you're going to apologise, apologise for the thing you did, not for how I took it." },
    ] },
    { id: 'sp.r4', when: { band: 'enemies' }, turns: [
      { by: 'a', say: "Can we just — call a truce? I'm sorry about {when}." },
      { by: 'b', say: "No." },
      { by: 'a', say: "No?" },
      { by: 'b', say: "No. You don't get to do the thing and then do the sorry and then everything's fine. That's not how it works with me." },
      { by: 'a', say: "Then how does it work with you?" },
      { by: 'b', say: "It works like this. You stay over there, I stay over here, and we see who's still in the house in a month." },
      { by: 'a', say: "That's really how you want to play it." },
      { by: 'b', say: "That's really how I want to play it." },
      { by: 'a', dr: "I tried. Write that down somewhere. I tried." },
    ] },
    { id: 'sp.r5', room: 'living-room', turns: [
      { beat: '{a} sits down next to {b} on the sofa. {b} moves along to the end.' },
      { by: 'a', say: "Really?" },
      { by: 'b', say: "Really." },
      { by: 'a', say: "I came to say sorry." },
      { by: 'b', say: "I know. I can tell. You've got your sorry face on." },
      { by: 'a', say: "I don't have a sorry face." },
      { by: 'b', say: "You've had it on since breakfast. I'm still not ready." },
      { by: 'a', say: "When will you be ready?" },
      { by: 'b', say: "I'll let you know." },
      { by: 'b', dr: "I'm not trying to be cruel. I'm just not there yet, and I'm not going to pretend I am." },
    ] },
    { id: 'sp.r6', turns: [
      { by: 'a', say: "So I wanted to clear the air about {when}." },
      { by: 'b', say: "The air's clear. I know exactly what you think of me." },
      { by: 'a', say: "That's not what I think of you." },
      { by: 'b', say: "Then why'd you say it?" },
      { by: 'a', say: "Because I was angry. People say stuff when they're angry." },
      { by: 'b', say: "People say what they mean when they're angry. The rest of the time they're just being polite." },
      { by: 'a', say: "...Okay. I'm still sorry." },
      { by: 'b', say: "Noted." },
      { by: 'a', dr: "'Noted.' Like I'm a memo. Fine. Noted right back." },
    ] },
  ],

  // ── the cold war ────────────────────────────────────────────────────
  'story.feud.cold.any': [
    { id: 'sc.1', room: 'kitchen', turns: [
      { beat: 'Kitchen. {a} is making toast. {b} walks in, sees {a}, and stops.' },
      { by: 'b', say: "Is the kettle on?" },
      { by: 'a', say: "Don't know." },
      { by: 'b', say: "It's right next to you." },
      { by: 'a', say: "Then you can see for yourself." },
      { beat: '{b} checks the kettle. It is on.' },
      { by: 'b', say: "Thanks for nothing." },
      { by: 'a', say: "Any time." },
      { by: 'a', dr: "We haven't had a real conversation since {when}. I'm fine with that. Honestly, it's peaceful." },
    ] },
    { id: 'sc.2', when: { third: true }, turns: [
      { by: 'c', say: "Okay, what's going on with you two?" },
      { by: 'a', say: "Nothing." },
      { by: 'b', say: "Nothing." },
      { by: 'c', say: "You both said nothing at the exact same time. That's not nothing." },
      { by: 'a', say: "Ask {b}." },
      { by: 'b', say: "Ask {a}." },
      { by: 'c', say: "Oh my god. I'm going outside." },
      { by: 'c', dr: "{a} and {b} have been doing this since {when}. It's like living with divorced parents." },
    ] },
    { id: 'sc.3', room: 'bedroom', turns: [
      { beat: '{b} walks into the bedroom. {a} picks up a pillow and walks out the other door.' },
      { by: 'b', dr: "That's the third room {a} has left because I walked into it. At this point it's a workout plan." },
      { by: 'a', dr: "I'm not being petty. I'm just choosing where I am. And where I am is wherever {b} isn't." },
    ] },
    { id: 'sc.4', room: 'kitchen', turns: [
      { by: 'b', say: "Pass the salt?" },
      { beat: '{a} slides it across the table without looking up.' },
      { by: 'b', say: "Thank you." },
      { beat: 'Nothing.' },
      { by: 'b', say: "I said thank you." },
      { by: 'a', say: "I heard." },
      { by: 'b', say: "You're welcome, then. For the thank you." },
      { by: 'a', say: "Great." },
      { by: 'b', dr: "It's been like this since {when}. I'm not going to beg." },
      { by: 'a', dr: "I'm civil. Civil is all {b} gets." },
    ] },
    { id: 'sc.5', room: 'bathroom', turns: [
      { beat: 'Bathroom. {a} and {b} are at the mirrors, side by side, brushing their teeth. Neither of them looks sideways.' },
      { by: 'a', say: "Are you done with the toothpaste?" },
      { by: 'b', say: "No." },
      { beat: '{b} puts more toothpaste on, very slowly.' },
      { by: 'b', say: "Now I am." },
      { by: 'a', dr: "That's what we are now. Two people who are petty with toothpaste." },
    ] },
    { id: 'sc.6', turns: [
      { by: 'a', say: "Is {b} coming to dinner?" },
      { by: 'b', say: "I'm right here." },
      { by: 'a', say: "I can see that. I was asking the room." },
      { by: 'b', say: "The room says yes." },
      { by: 'a', say: "Great. I'll sit at the other end." },
      { by: 'b', say: "Great. I'll sit at this one." },
      { by: 'b', dr: "Ever since {when}, {a} talks about me in the third person when I'm standing right there. I'm right there." },
    ] },
  ],

  // ── recaps: the cause, said plainly, when the viewer did not see it ──
  'recap.feud.friction.chores.b': [
    { id: 'rf.cb1', turns: [{ by: 'b', dr: "So {when}, {a} left a mess in the kitchen and I said something about it. And it did not go well." }] },
    { id: 'rf.cb2', turns: [{ by: 'b', dr: "{when}, {a} and I had words about the kitchen. Small stuff. It's always small stuff in here, until it isn't." }] },
    { id: 'rf.cb3', turns: [{ by: 'b', dr: "I asked {a} to clean up after {a.obj}self {when}. Apparently that's a crime now." }] },
  ],
  'recap.feud.friction.chores.a': [
    { id: 'rf.ca1', turns: [{ by: 'a', dr: "{when}, {b} came at me about some dishes. Some dishes. Like I'd burned the house down." }] },
    { id: 'rf.ca2', turns: [{ by: 'a', dr: "{b} and I got into it {when} over the kitchen. I'll admit I wasn't the tidiest. I won't admit {b} was right." }] },
    { id: 'rf.ca3', turns: [{ by: 'a', dr: "{when}, {b} told me off for leaving stuff out. In front of people. So that's where we are." }] },
  ],
  'recap.feud.friction.joke.b': [
    { id: 'rf.jb1', turns: [{ by: 'b', dr: "{when}, {a} made a joke about me. In front of everybody. And everybody laughed." }] },
    { id: 'rf.jb2', turns: [{ by: 'b', dr: "{a} did an impression of me {when}. The whole room thought it was hilarious. I didn't." }] },
    { id: 'rf.jb3', turns: [{ by: 'b', dr: "{when}, {a} decided I'd be the punchline. I'm not the punchline." }] },
  ],
  'recap.feud.friction.joke.a': [
    { id: 'rf.ja1', turns: [{ by: 'a', dr: "{when} I made a joke about {b}. Harmless. Everybody laughed. Except {b}, apparently." }] },
    { id: 'rf.ja2', turns: [{ by: 'a', dr: "I teased {b} a little {when}. I tease everybody. {b} just took it worse than everybody." }] },
    { id: 'rf.ja3', turns: [{ by: 'a', dr: "{when}, I did a bit about {b}. The bit landed. {b} didn't." }] },
  ],
  'recap.feud.friction.snap.b': [
    { id: 'rf.sb1', turns: [{ by: 'b', dr: "{when}, {a} snapped at me. Out of nowhere. I was just being nice." }] },
    { id: 'rf.sb2', turns: [{ by: 'b', dr: "{a} bit my head off {when}. For nothing. I'm still thinking about it." }] },
    { id: 'rf.sb3', turns: [{ by: 'b', dr: "So {when}, {a} lost it at me over basically nothing. I don't do well with being shouted at." }] },
  ],
  'recap.feud.friction.snap.a': [
    { id: 'rf.sa1', turns: [{ by: 'a', dr: "I snapped at {b} {when}. I was having a bad day. {b} was just standing in the wrong place." }] },
    { id: 'rf.sa2', turns: [{ by: 'a', dr: "{when}, I was short with {b}. Shorter than I meant to be." }] },
    { id: 'rf.sa3', turns: [{ by: 'a', dr: "{b} caught me at a bad moment {when}, and I let it show. A lot." }] },
  ],
  'recap.feud.friction.caption': [
    { id: 'rf.x1', turns: [{ beat: '{when}, {a} and {b} clashed in the kitchen. Neither of them has let it go.' }, { by: 'a', dr: "It's fine. It's whatever." }] },
    { id: 'rf.x2', turns: [{ beat: '{when}, {a} and {b} had words. It was small. It has not stayed small.' }, { by: 'b', dr: "I'm not going to pretend it didn't happen." }] },
    { id: 'rf.x3', turns: [{ beat: 'Since {when}, {a} and {b} have barely spoken.' }, { by: 'a', dr: "We just don't click." }] },
  ],
  'recap.feud.argument.a': [
    { id: 'rg.a1', turns: [{ by: 'a', dr: "{b} and I had it out {when}. Properly. It got loud." }] },
    { id: 'rg.a2', turns: [{ by: 'a', dr: "{when} I finally said everything I'd been holding in to {b}. Everything." }] },
    { id: 'rg.a3', turns: [{ by: 'a', dr: "You might've heard {b} and me {when}. The whole house heard us." }] },
  ],
  'recap.feud.argument.b': [
    { id: 'rg.b1', turns: [{ by: 'b', dr: "{a} came at me {when}. Screaming. In front of everyone." }] },
    { id: 'rg.b2', turns: [{ by: 'b', dr: "{when}, {a} decided to tell me exactly what {a.sub} thinks of me. Loudly." }] },
    { id: 'rg.b3', turns: [{ by: 'b', dr: "We had a fight {when}. A big one. I'm still not over it." }] },
  ],
  'recap.feud.argument.caption': [
    { id: 'rg.x1', turns: [{ beat: '{when}, {a} and {b} had a shouting match the whole house heard.' }, { by: 'a', dr: "Yeah. That happened." }] },
    { id: 'rg.x2', turns: [{ beat: '{when}, a fight between {a} and {b} cleared the kitchen.' }, { by: 'b', dr: "I'm not proud of it." }] },
    { id: 'rg.x3', turns: [{ beat: "{when}, {a} and {b} finally said it all to each other's faces." }, { by: 'a', dr: "It had to happen." }] },
  ],
  'recap.feud.cold.a': [
    { id: 'rc.a1', turns: [{ by: 'a', dr: "{b} and I haven't really spoken since {when}. On purpose." }] },
    { id: 'rc.a2', turns: [{ by: 'a', dr: "I've been ignoring {b} since {when}. It's going great. For me." }] },
    { id: 'rc.a3', turns: [{ by: 'a', dr: "{b} and I are in a cold war. Started {when}. Nobody's blinked yet." }] },
  ],
  'recap.feud.cold.b': [
    { id: 'rc.b1', turns: [{ by: 'b', dr: "{a} has been ignoring me since {when}. Like, full silent treatment." }] },
    { id: 'rc.b2', turns: [{ by: 'b', dr: "Ever since {when}, {a} leaves rooms when I walk in. It's very mature." }] },
    { id: 'rc.b3', turns: [{ by: 'b', dr: "{a} and I have been pretending the other one doesn't exist since {when}." }] },
  ],
};
