// ══════════════════════════════════════════════════════════════════════
// bb/story/lines/firstnight.js — the first night, many ways
// ══════════════════════════════════════════════════════════════════════
//
// Every season opens on the first night, so a handful of versions meant the same
// opening season after season (the user, 2026-10-06: "is it happening every first
// episode? … we want variants"). These are added to set.firstnight / set.firstbed, and
// write.js remembers across seasons which ones this viewer has already seen. Each is a
// different first night: a different room, a different thing going wrong, a different
// person taking charge. Nobody knows anybody yet, so nobody mentions a past.

export default {
  'set.firstnight.open': [
    { id: 'fn.1', room: 'living-room', turns: [
      { beat: 'Living room, first night. {a} has decided there should be a house meeting. Nobody else has decided this.' },
      { by: 'a', say: "Okay, everyone. Quick house meeting." },
      { by: 'b', say: "We've been here three hours." },
      { by: 'a', say: "Exactly. Rules. We need rules." },
      { by: 'c', say: "What kind of rules?" },
      { by: 'a', say: "Dishes, showers, who sleeps where." },
      { by: 'd', say: "Rule one: no house meetings." },
      { beat: 'Half the room laughs. {a} does not.' },
      { by: 'e', say: "Rule two: whoever cooks doesn't wash up." },
      { by: 'b', say: "Seconded." },
      { by: 'a', say: "...Fine. Those are good rules." },
      { by: 'd', dr: "It's the first night and somebody's already trying to run the house. That makes me nervous, and I'm going to remember who it was." },
    ] },
    { id: 'fn.2', room: 'backyard', turns: [
      { beat: 'Backyard, first night. The lights are on round the pool. Everybody is out there, nobody quite knows why.' },
      { by: 'a', say: "Is anyone else just… in shock?" },
      { by: 'b', say: "Completely. I keep touching things." },
      { by: 'c', say: "Touching things?" },
      { by: 'b', say: "To check they're real. The pool's real. I checked." },
      { by: 'd', say: "Are we allowed in the pool?" },
      { by: 'e', say: "Nobody said we're not." },
      { by: 'a', say: "Nobody said we are." },
      { beat: 'Everybody looks at the pool. Nobody gets in.' },
      { by: 'c', say: "Tomorrow. Tomorrow we'll be brave." },
      { by: 'e', dr: "We stood round a pool for half an hour, too scared to get in. Nobody wants to be the first one to do anything in here." },
    ] },
    { id: 'fn.3', room: 'kitchen', turns: [
      { beat: 'Kitchen, first night. {a} is cooking for everyone, uninvited. The house is circling the stove.' },
      { by: 'b', say: "What are you making?" },
      { by: 'a', say: "Something with everything that was in the fridge." },
      { by: 'c', say: "That's not a dish." },
      { by: 'a', say: "It's a dish now." },
      { by: 'd', say: "It smells amazing, actually." },
      { by: 'e', say: "Is there enough for everyone?" },
      { by: 'a', say: "If everyone has a small amount and doesn't ask questions." },
      { beat: 'Everybody has a small amount. Everybody asks questions.' },
      { by: 'b', dr: "The first person to feed the house is either going to be loved or targeted. Tonight: loved." },
    ] },
    { id: 'fn.4', room: 'bedroom', turns: [
      { beat: 'Bedroom, first night. Two good beds, one bad bed, and a lot of people standing in the doorway.' },
      { by: 'a', say: "Okay, so how are we doing this? Fairly?" },
      { by: 'b', say: "First come, first served." },
      { by: 'c', say: "That's not fair, that's just fast." },
      { by: 'b', say: "Fast is fair. Ask the comps." },
      { by: 'd', say: "Rock, paper, scissors for the bed by the window." },
      { beat: 'Six adults play rock, paper, scissors for a bed. It takes eleven rounds.' },
      { by: 'e', say: "Best of three!" },
      { by: 'a', say: "It's been best of eleven!" },
      { by: 'd', dr: "I lost the bed by the window to rock. Rock. I always go rock. Everyone should know that by now." },
    ] },
    { id: 'fn.5', room: 'living-room', turns: [
      { beat: 'Living room, first night. Somebody suggests saying where everyone thinks everyone else is from. It goes badly.' },
      { by: 'a', say: "Okay, {b}. Guess where I'm from." },
      { by: 'b', say: "Somewhere with a beach." },
      { by: 'a', say: "Wrong." },
      { by: 'c', say: "Somewhere cold?" },
      { by: 'a', say: "Also wrong." },
      { by: 'd', say: "Somewhere… in the middle?" },
      { by: 'a', say: "That's just geography now." },
      { by: 'e', say: "I give up. Where?" },
      { by: 'a', say: "Not telling. Mystery's good for my game." },
      { by: 'c', dr: "Night one and {a} is already keeping secrets about where {a.sub}'s from. I like that. I don't trust it, but I like it." },
    ] },
    { id: 'fn.6', room: 'kitchen', turns: [
      { beat: 'Kitchen, first night. The first bottle of anything has been opened. People are louder already.' },
      { by: 'a', say: "To the house!" },
      { by: 'b', say: "To the house!" },
      { by: 'c', say: "To whoever wins!" },
      { by: 'd', say: "...That's a weird toast." },
      { by: 'c', say: "Why?" },
      { by: 'e', say: "Because it's one of us, and it's only one of us." },
      { beat: 'Glasses hang in the air for a second too long.' },
      { by: 'a', say: "To the house. Let's just stick with the house." },
      { by: 'b', dr: "One toast. That's all it took. Everyone remembered it's a game. Thanks, {c}." },
    ] },
    { id: 'fn.7', room: 'living-room', turns: [
      { beat: 'Living room, first night. {a} is taking bets on who wins the first Head of Household.' },
      { by: 'a', say: "Odds on. Who's winning HOH tomorrow?" },
      { by: 'b', say: "We don't even know what the comp is." },
      { by: 'a', say: "That's what makes it gambling." },
      { by: 'c', say: "I'll bet on {d}. {d} looks fast." },
      { by: 'd', say: "Don't bet on me! Now I'm a target!" },
      { by: 'e', say: "Too late. You're the favourite." },
      { by: 'd', say: "I've been here six hours and I'm already the favourite?" },
      { by: 'a', say: "Favourites go home first. Sorry." },
      { by: 'd', dr: "Six hours in and somebody's already painted a target on me. As a joke. In here, there are no jokes." },
    ] },
    { id: 'fn.8', room: 'kitchen', turns: [
      { beat: 'Kitchen, first night. Somebody has found the stash of snacks, and the house has descended on it.' },
      { by: 'a', say: "Do we ration this?" },
      { by: 'b', say: "Ration it? It's the first night!" },
      { by: 'c', say: "That's exactly why we ration it." },
      { by: 'd', say: "I'm eating the chocolate. Ration the rest." },
      { by: 'e', say: "You can't just eat the chocolate!" },
      { by: 'd', say: "Watch me." },
      { beat: 'The chocolate is gone in under a minute. Several people will remember this.' },
      { by: 'c', dr: "Somebody ate all the chocolate on night one. If I'm ever HOH, I won't forget it. I'm only half joking." },
    ] },
    { id: 'fn.9', room: 'backyard', turns: [
      { beat: 'Backyard, first night. Everyone is lying on the grass, staring up at a ceiling of lights.' },
      { by: 'a', say: "You can't see the sky." },
      { by: 'b', say: "There's a roof." },
      { by: 'a', say: "I know there's a roof. I just thought you'd see the sky." },
      { by: 'c', say: "We won't see the sky for months." },
      { by: 'd', say: "Don't say months. Say weeks. Weeks sounds better." },
      { by: 'e', say: "Weeks, then." },
      { by: 'b', say: "Lots of weeks." },
      { beat: 'Nobody says anything for a while. It is surprisingly nice.' },
      { by: 'a', dr: "Ten minutes of nobody talking on the first night. Weirdly, that's when I felt like we were all in this together." },
    ] },
    { id: 'fn.10', room: 'living-room', turns: [
      { beat: 'Living room, first night. {a} is sitting on the floor. Everyone else ends up sitting on the floor too.' },
      { by: 'b', say: "Why are we all on the floor?" },
      { by: 'a', say: "I don't know. I sat down here. You all followed." },
      { by: 'c', say: "There's a perfectly good sofa." },
      { by: 'd', say: "The floor feels more honest." },
      { by: 'e', say: "What does that even mean?" },
      { by: 'd', say: "I don't know. It's been a long day." },
      { beat: 'Nobody moves to the sofa. The floor wins.' },
      { by: 'c', dr: "{a} sat on the floor and the whole house followed. That's a leader. Or a very persuasive floor." },
    ] },
    { id: 'fn.11', room: 'kitchen', turns: [
      { beat: 'Kitchen, first night. The house is trying to work out how the oven works. Nobody can.' },
      { by: 'a', say: "Which one's the oven light?" },
      { by: 'b', say: "That one's the timer." },
      { by: 'c', say: "That one's making a noise." },
      { by: 'd', say: "Why is it beeping?" },
      { by: 'e', say: "Press everything." },
      { by: 'a', say: "Don't press everything!" },
      { beat: 'Somebody presses everything. The oven turns on, the fan turns on, and a light nobody knew existed turns on.' },
      { by: 'b', say: "Well. It's on." },
      { by: 'e', dr: "Six of us, one oven, twenty minutes. If the comps are anything like this, we're in trouble." },
    ] },
    { id: 'fn.12', room: 'bedroom', turns: [
      { beat: 'Bedroom, first night. Everybody is unpacking at the same time. Clothes are everywhere.' },
      { by: 'a', say: "Is this your sock or my sock?" },
      { by: 'b', say: "It's been four hours. How are our socks already mixed up?" },
      { by: 'c', say: "Who brought eleven pairs of shoes?" },
      { by: 'd', say: "Me. You never know." },
      { by: 'c', say: "You never know what?" },
      { by: 'd', say: "What shoes a situation needs." },
      { by: 'e', say: "We live in one house. There are no situations." },
      { by: 'd', say: "There are always situations." },
      { by: 'a', dr: "Eleven pairs of shoes. In a house with no outside. I respect the confidence." },
    ] },
  ],
  'set.firstnight.close': [
    { id: 'fn.c1', turns: [{ beat: 'Somewhere around midnight, the house goes from loud to quiet without anybody noticing.' }, { by: 'b', dr: "Everyone was buzzing all day. Then it hit us. We're actually here. And only one of us leaves with the money." }] },
    { id: 'fn.c2', turns: [{ beat: 'People drift off in twos and threes. The first private conversations of the season start in corners.' }, { by: 'd', dr: "You could see it. The first little huddles. The game started tonight, whatever anybody says." }] },
    { id: 'fn.c3', turns: [{ beat: 'One person stays up last, watching the house settle, counting faces.' }, { by: 'e', dr: "I watched who went to bed with who. I'm not proud of it. But I watched." }] },
    { id: 'fn.c4', turns: [{ beat: 'The kitchen is wrecked. Nobody is going to clean it tonight.' }, { by: 'a', dr: "Day one, and we've already got a dishes problem. That's going to be a fight. I can feel it." }] },
    { id: 'fn.c5', turns: [{ beat: 'The music goes off. The lights dim. Somebody laughs in the dark at nothing.' }, { by: 'c', dr: "Best night in the house. Probably. Everybody likes everybody tonight. It won't last." }] },
  ],
  'set.firstbed.open': [
    { id: 'fb.1', turns: [
      { beat: 'Lights out, first night. Somebody’s mattress squeaks every time they breathe.' },
      { by: 'a', say: "Who's squeaking?" },
      { by: 'b', say: "My bed. I'm not moving. It just squeaks." },
      { by: 'c', say: "It squeaks when you breathe?" },
      { by: 'b', say: "Apparently." },
      { by: 'd', say: "Stop breathing, then." },
      { beat: 'Laughter. Then shushing. Then more laughter.' },
      { by: 'e', dr: "We're going to have to live with the squeaky bed for weeks. I'm already plotting to evict the bed." },
    ] },
    { id: 'fb.2', turns: [
      { beat: 'Lights out, first night. Somebody is whispering a list of everyone’s names, trying to remember them.' },
      { by: 'a', say: "{b}, {c}, {d}... who's next to {d}?" },
      { by: 'e', say: "Me. It's {e}." },
      { by: 'a', say: "{e}. Sorry, it's been a long day." },
      { by: 'b', say: "Are you doing a roll call in the dark?" },
      { by: 'a', say: "I'm memorising. Tomorrow I'm going to know everyone." },
      { by: 'c', say: "Tomorrow you're going to forget everyone again." },
      { beat: '{a} carries on whispering names until somebody throws a pillow.' },
      { by: 'a', dr: "If you don't know everyone's name by day two, you've already lost. I'm not losing over names." },
    ] },
    { id: 'fb.3', turns: [
      { beat: 'First night. The lights go off. Then the lights come back on. Then they go off again.' },
      { by: 'a', say: "Is that us or them?" },
      { by: 'b', say: "That's them." },
      { by: 'c', say: "Are they messing with us already?" },
      { by: 'd', say: "Welcome to Big Brother." },
      { beat: 'Off. On. Off. Everyone groans at once.' },
      { by: 'e', say: "I'm sleeping with my eyes closed. They can't get me with my eyes closed." },
      { by: 'c', dr: "First night, and the house is already playing with us. Good to know who's really in charge." },
    ] },
    { id: 'fb.4', turns: [
      { beat: 'Lights out, first night. Somebody starts telling a ghost story. Nobody asked for one.' },
      { by: 'a', say: "...and then the door slowly opened—" },
      { by: 'b', say: "No. No ghost stories. We live here." },
      { by: 'c', say: "Let them finish!" },
      { by: 'a', say: "—and standing in the doorway was—" },
      { beat: 'The bedroom door creaks open. It is just somebody coming back from the bathroom.' },
      { by: 'd', say: "WHY IS EVERYONE SCREAMING?" },
      { by: 'e', dr: "Worst timing in the history of the house. I nearly went home on night one. Of a heart attack." },
    ] },
    { id: 'fb.5', turns: [
      { beat: 'Lights out, first night. One person can’t sleep without saying goodnight to everyone individually.' },
      { by: 'a', say: "Night, {b}." },
      { by: 'b', say: "Night." },
      { by: 'a', say: "Night, {c}." },
      { by: 'c', say: "Goodnight." },
      { by: 'a', say: "Night, {d}." },
      { by: 'd', say: "Are you doing everyone?" },
      { by: 'a', say: "Night, {e}." },
      { by: 'e', say: "Goodnight, {a}. Go to sleep." },
      { by: 'b', dr: "{a} said goodnight to every single person by name. Sweet. Also a strategy. Definitely a strategy." },
    ] },
    { id: 'fb.6', turns: [
      { beat: 'Lights out, first night. A single whisper from the dark.' },
      { by: 'a', say: "Does anyone else feel like they're at camp?" },
      { by: 'b', say: "Camp with cameras." },
      { by: 'c', say: "And a cash prize." },
      { by: 'd', say: "And a vote every week." },
      { by: 'e', say: "...This is the worst camp." },
      { beat: 'Somebody laughs so hard the bed shakes.' },
      { by: 'c', dr: "The worst camp. Best night. I'm going to remember this when it gets ugly." },
    ] },
    { id: 'fb.7', turns: [
      { beat: 'Lights out. Somebody is already asleep. Snoring. Loudly.' },
      { by: 'b', say: "Who is that?" },
      { by: 'c', say: "I think it's {a}." },
      { by: 'd', say: "How? We turned the lights off two minutes ago." },
      { by: 'e', say: "Some people are just built different." },
      { beat: 'The snoring gets louder. Somebody puts a pillow over their head.' },
      { by: 'b', say: "This is our life now." },
      { by: 'd', dr: "First night. First snorer. We know who's sleeping on the sofa next week." },
    ] },
  ],
};
