// ══════════════════════════════════════════════════════════════════════
// bb/story/lines/gametalk.js — the game talk of the week, which changes as the season does
// ══════════════════════════════════════════════════════════════════════
//
// The user, 2026-10-06: "do we have speech that evolves, like pre-jury strategising about who
// we're bringing to jury, talking about Block Buster, strategising around that too… with bond
// events negative or positive, I want a real BB experience". Houseguests on the real show talk
// about the game they are in THIS week: early on it is numbers and trust, then who has to go
// before jury, then who is going to be bitter, then who you can beat at the end.
// The director (bb/story/director.js) chooses which of these a stretch airs from the state of
// the game (write.js writeGameTalk), and the roles below are always true when it does:
//
//   talk.bb.hoh      a = HOH, b = HOH's closest, c = the target, d = another nominee
//                    (a Block Buster week, three on the block, before the Block Buster)
//   talk.bb.nominee  a = a nominee, b = a's closest, c = the HOH (same week)
//   talk.veto.hope   a = a nominee, b = a's closest, c = the HOH (before the veto is played for)
//   talk.nexthoh     a, b close, c = the best competitor left (before the HOH is played for)
//   talk.prejury     a, b close, c = a threat both are wary of (one or two evictions from jury)
//   talk.jury.bitter a, b close, {gone} = the juror who just walked out
//   talk.jury.manage a, b close, c = whoever the house likes most (jury phase)
//   talk.endgame     a, b close, c = somebody else still in (six or fewer left)
//   talk.bond.vent   a cannot stand c and tells b, a's closest
//   talk.bond.trust  a and b, the closest pair in the house
//
// An entry may carry `phase: [...]` ('early', 'prejury', 'jury', 'endgame'): it airs only then.

export default {
  'talk.bb.hoh': [
    { id: 'gt.bh1', room: 'hoh-room', turns: [
      { beat: 'HOH room, door shut. {a} is lying across the bed. {b} is sitting on the floor.' },
      { by: 'b', say: "Okay. Three on the block. Talk me through it." },
      { by: 'a', say: "{c} is the target. The other two are there to fill seats." },
      { by: 'b', say: "And if {c} wins the Block Buster?" },
      { by: 'a', say: "Then I'm stuck sending home somebody I never wanted gone." },
      { by: 'b', say: "So you need {c} to lose." },
      { by: 'a', say: "I need {c} to lose to one of the other two. There's nothing I can do except hope." },
      { by: 'b', say: "What's the Block Buster usually? Physical?" },
      { by: 'a', say: "It's whatever it is. {c} is good at everything. That's the problem." },
      { by: 'a', dr: "Three people on the block sounds like more control. It's actually less. One of them gets off it, and I don't get a say in which." },
    ] },
    { id: 'gt.bh2', room: 'hoh-room', turns: [
      { beat: 'HOH room. {b} has come up with two drinks and closes the door with a foot.' },
      { by: 'b', say: "How are you feeling?" },
      { by: 'a', say: "Like I did my part. Now it's out of my hands until Thursday." },
      { by: 'b', say: "Do you want {d} to win the Block Buster?" },
      { by: 'a', say: "Honestly? Yes. {d} off, {c} and the other one in the chairs. I'd take that." },
      { by: 'b', say: "And if {c} comes off?" },
      { by: 'a', say: "Then we have a real conversation about who we keep. And it won't be a nice one." },
      { by: 'b', say: "We'll figure it out. We always do." },
      { by: 'b', dr: "{a} put three up and only cares about one of them. If that one wins Block Buster, the whole week is wasted." },
    ] },
    { id: 'gt.bh3', room: 'hoh-room', turns: [
      { beat: 'HOH room, late. {a} is pacing. {b} is watching from the bed.' },
      { by: 'a', say: "What if I made the wrong call?" },
      { by: 'b', say: "You didn't." },
      { by: 'a', say: "If {c} wins this thing, {c} knows exactly who did it. And I'm not HOH next week." },
      { by: 'b', say: "Then {c} has to win HOH too. That's two comps in a row." },
      { by: 'a', say: "{c} could do it." },
      { by: 'b', say: "So could you. Stop pacing. You're making me dizzy." },
      { beat: '{a} sits down, then stands straight back up.' },
      { by: 'a', dr: "If {c} wins on Thursday, I've made an enemy for nothing. That's the risk of swinging big." },
    ] },
    { id: 'gt.bh4', turns: [
      { beat: '{a} and {b}, by the pool, talking quietly with their backs to the house.' },
      { by: 'b', say: "Who do you think wins the Block Buster?" },
      { by: 'a', say: "Not {c}. Please, not {c}." },
      { by: 'b', say: "{d} wants it more than anyone. You can see it." },
      { by: 'a', say: "Then I'm rooting for {d}. Loudly. From the sidelines." },
      { by: 'b', say: "You can't root for anyone. You put them all up." },
      { by: 'a', say: "Silently, then. Very silently." },
      { by: 'a', dr: "I'm the Head of Household and I've never been more nervous. My week comes down to a game I'm not even playing." },
    ] },
    { id: 'gt.bh5', room: 'hoh-room', turns: [
      { beat: 'HOH room. {a} has the camera screen on and is watching the kitchen. {b} comes in.' },
      { by: 'b', say: "Spying?" },
      { by: 'a', say: "Watching {c} campaign. Look at that. Third person in ten minutes." },
      { by: 'b', say: "Does {c} know it's about {c}?" },
      { by: 'a', say: "{c} knows. Everyone on that block thinks they're the target." },
      { by: 'b', say: "So what's the plan if {c} wins the Block Buster?" },
      { by: 'a', say: "Same plan. Smaller. Whoever's left in the chairs, we pick the one who'd come after us." },
      { by: 'b', dr: "There's no clean week with three on the block. Somebody gets lucky, and you deal with it." },
    ] },
  ],
  'talk.bb.nominee': [
    { id: 'gt.bn1', room: 'bedroom', turns: [
      { beat: 'Bedroom. {a} is sitting on the bed in workout gear. {b} comes in and shuts the door.' },
      { by: 'b', say: "You okay?" },
      { by: 'a', say: "I'm winning that Block Buster. I'm not leaving it to a vote." },
      { by: 'b', say: "You don't know you'd lose the vote." },
      { by: 'a', say: "I know {c} didn't put me up to keep me." },
      { by: 'b', say: "Fair." },
      { by: 'a', say: "So I win. Simple. Then {c} has to deal with whoever's left." },
      { by: 'b', say: "And if you don't win?" },
      { by: 'a', say: "Then I need you counting votes for me. Every single one." },
      { by: 'a', dr: "Three people on the block, one way off it. I'm not leaving my game in other people's hands." },
    ] },
    { id: 'gt.bn2', turns: [
      { beat: 'The backyard. {a} is doing laps round the yard. {b} falls in alongside.' },
      { by: 'b', say: "Training?" },
      { by: 'a', say: "Something like that. I don't know what the Block Buster is, so I'm training for everything." },
      { by: 'b', say: "By walking in circles?" },
      { by: 'a', say: "By not sitting still. If I sit still I think about {c}." },
      { by: 'b', say: "What about {c}?" },
      { by: 'a', say: "About how {c} is going to tell me it's nothing personal." },
      { by: 'b', say: "That's what everybody says." },
      { by: 'a', say: "Then everybody's lying." },
      { by: 'b', dr: "{a} is walking laps like it's going to help. Honestly? It might. A nominee who's angry wins comps." },
    ] },
    { id: 'gt.bn3', room: 'kitchen', turns: [
      { beat: 'The kitchen, quiet. {a} is eating standing up. {b} sits on the counter.' },
      { by: 'b', say: "Are you nervous?" },
      { by: 'a', say: "About the Block Buster? Terrified. About the vote? More terrified." },
      { by: 'b', say: "Which would you rather?" },
      { by: 'a', say: "The Block Buster. At least then it's on me." },
      { by: 'b', say: "If it comes to the vote, I've got you." },
      { by: 'a', say: "I know you do. It's the others I'm worried about." },
      { by: 'a', dr: "I'd rather lose a game than lose a vote. If I lose a game, nobody lied to me." },
    ] },
    { id: 'gt.bn4', room: 'bedroom', turns: [
      { beat: 'Bedroom, lights low. {a} is lying on top of the covers. {b} lies down on the next bed.' },
      { by: 'a', say: "Can I ask you something and you tell me the truth?" },
      { by: 'b', say: "Always." },
      { by: 'a', say: "If I don't win the Block Buster, am I going home?" },
      { by: 'b', say: "...I don't know yet. That's the truth." },
      { by: 'a', say: "Okay." },
      { by: 'b', say: "I'm working on it." },
      { by: 'a', say: "Then I'll win it. Then you don't have to work so hard." },
      { by: 'b', dr: "{a} asked me straight out and I couldn't say yes or no. That told {a} everything." },
    ] },
  ],
  'talk.veto.hope': [
    { id: 'gt.vh1', room: 'bedroom', turns: [
      { beat: 'Bedroom. {a} is staring at the ceiling. {b} sits on the edge of the bed.' },
      { by: 'a', say: "The veto is my only way off this thing." },
      { by: 'b', say: "You have to get picked to play first." },
      { by: 'a', say: "Don't. I know. Houseguest's choice, pray to the chips." },
      { by: 'b', say: "If you get to pick, pick me." },
      { by: 'a', say: "Obviously I'll pick you." },
      { by: 'b', say: "Then if I win it, it's coming off you." },
      { by: 'a', say: "And {c} has to put someone else up. That's the best thing I've heard all day." },
      { by: 'a', dr: "{c} put me up. If I win that veto, I come off and {c} has to make another enemy. I like that a lot." },
    ] },
    { id: 'gt.vh2', turns: [
      { beat: 'The hammock. {a} and {b} are squeezed into it, swinging slowly.' },
      { by: 'b', say: "Do you think you're the pawn?" },
      { by: 'a', say: "Everybody up there thinks they're the pawn. Until Thursday." },
      { by: 'b', say: "So what do you do?" },
      { by: 'a', say: "Pawns go home all the time. I'm not trusting {c}'s plan. I'm winning the veto." },
      { by: 'b', say: "And if you don't?" },
      { by: 'a', say: "Then I campaign like my life depends on it. Because it does." },
      { by: 'b', dr: "Nobody on the block believes the word 'pawn'. Nobody should." },
    ] },
    { id: 'gt.vh3', room: 'kitchen', turns: [
      { beat: 'The kitchen. {a} is making a protein shake with real violence. {b} watches.' },
      { by: 'b', say: "What did that banana ever do to you?" },
      { by: 'a', say: "Nothing. I'm just annoyed with {c}." },
      { by: 'b', say: "Veto practice?" },
      { by: 'a', say: "Veto fuel. If I play, I'm winning." },
      { by: 'b', say: "And if it's a puzzle?" },
      { by: 'a', say: "Then I'll be very angry at a puzzle." },
      { by: 'a', dr: "I'm on the block. The veto's the only thing in this house that can fix that today." },
    ] },
  ],
  'talk.nexthoh': [
    { id: 'gt.nh1', turns: [
      { beat: 'The backyard. {a} and {b} are lying on loungers, eyes shut against the lights.' },
      { by: 'a', say: "HOH tomorrow." },
      { by: 'b', say: "Don't. I'm relaxing." },
      { by: 'a', say: "If {c} wins it, one of us is going up." },
      { by: 'b', say: "...I'm not relaxing anymore." },
      { by: 'a', say: "So one of us has to win it. Or we make sure {c} doesn't." },
      { by: 'b', say: "How do we make sure {c} doesn't?" },
      { by: 'a', say: "We beat {c}. That's the only way I know." },
      { by: 'b', dr: "{c} has won more than anyone. Every HOH, it's the same question: what happens if {c} wins again?" },
    ] },
    { id: 'gt.nh2', room: 'kitchen', turns: [
      { beat: 'Kitchen, late. {a} and {b} are eating cereal out of mugs.' },
      { by: 'b', say: "If you win HOH, who goes up?" },
      { by: 'a', say: "You know who." },
      { by: 'b', say: "{c}?" },
      { by: 'a', say: "Has to be. Everybody says it should happen and nobody does it." },
      { by: 'b', say: "And if {c} wins?" },
      { by: 'a', say: "Then we start being very, very nice to {c}." },
      { by: 'b', say: "That's a terrible plan." },
      { by: 'a', say: "That's the only plan." },
      { by: 'a', dr: "Every week the house has the same conversation. Somebody should take out {c}. Then nobody does." },
    ] },
    { id: 'gt.nh3', room: 'bedroom', turns: [
      { beat: 'Bedroom. {a} is stretching on the floor. {b} watches from a bed.' },
      { by: 'b', say: "Are you actually stretching for HOH?" },
      { by: 'a', say: "If it's endurance, I'm ready." },
      { by: 'b', say: "And if it's a quiz?" },
      { by: 'a', say: "Then my hamstrings will be very disappointed." },
      { by: 'b', say: "Seriously, though. {c} can't win this one." },
      { by: 'a', say: "I know. If {c} wins, {c} cleans house. Starting with us." },
      { by: 'b', dr: "There's always a week where you think: if I don't win this, I'm gone. This feels like that week." },
    ] },
  ],
  'talk.prejury': [
    { id: 'gt.pj1', phase: ['prejury'], room: 'bedroom', turns: [
      { beat: 'Bedroom, door shut. {a} and {b} are sitting cross-legged on the same bed, voices low.' },
      { by: 'a', say: "We need to talk about jury." },
      { by: 'b', say: "It's not jury yet." },
      { by: 'a', say: "That's my point. Whoever goes before jury doesn't vote for the winner." },
      { by: 'b', say: "You're thinking about {c}." },
      { by: 'a', say: "Everybody likes {c}. If {c} sits on that jury, {c} talks the whole jury into whoever {c} wants." },
      { by: 'b', say: "So {c} has to go before the jury starts." },
      { by: 'a', say: "Or we never get rid of {c} at all." },
      { by: 'a', dr: "The last few weeks before jury, you're not just evicting someone. You're choosing who gets to judge you." },
    ] },
    { id: 'gt.pj2', phase: ['prejury'], turns: [
      { beat: 'The backyard, by the wall. {a} and {b} are pretending to play pool.' },
      { by: 'b', say: "If we take a shot, it has to be soon." },
      { by: 'a', say: "Before jury." },
      { by: 'b', say: "Before jury. Because whoever we cut after that is a vote against us." },
      { by: 'a', say: "{c}?" },
      { by: 'b', say: "{c} would never vote for me. Ever. I'd rather {c} watched the finale from a sofa at home." },
      { by: 'a', say: "Wow. That's harsh." },
      { by: 'b', say: "It's harsh, but it's true." },
      { by: 'b', dr: "Pre-jury evictions are free. No bitterness, no vote. After that, every name you write down comes back to you." },
    ] },
    { id: 'gt.pj3', phase: ['prejury'], room: 'kitchen', turns: [
      { beat: 'The kitchen, washing up. {a} washes. {b} dries. Neither is looking at the other.' },
      { by: 'a', say: "Have you counted how many weeks till jury?" },
      { by: 'b', say: "I count every day." },
      { by: 'a', say: "If {c} makes it to jury, we're in trouble." },
      { by: 'b', say: "Why?" },
      { by: 'a', say: "Because {c} remembers everything. Every vote. Every lie." },
      { by: 'b', say: "We haven't lied to {c}." },
      { by: 'a', say: "Not yet." },
      { by: 'b', dr: "{a} said 'not yet' and kept washing up. That's the coldest thing I've heard in here." },
    ] },
    { id: 'gt.pj4', phase: ['prejury'], room: 'living-room', turns: [
      { beat: 'Living room, late. {a} and {b} are on the sofa under one blanket, whispering.' },
      { by: 'b', say: "Who do you want on the jury?" },
      { by: 'a', say: "People who like me." },
      { by: 'b', say: "That's not a lot of people." },
      { by: 'a', say: "That's rude. But you're not wrong." },
      { by: 'b', say: "Who don't you want?" },
      { by: 'a', say: "{c}. Not because {c} is bad. Because {c} is good. Good players sway juries." },
      { by: 'b', say: "Then we need {c} out before it starts." },
      { by: 'a', dr: "You don't only play the house. You play the jury you're going to face. And you build it now." },
    ] },
  ],
  'talk.jury.bitter': [
    { id: 'gt.jb1', phase: ['jury', 'endgame'], room: 'bedroom', turns: [
      { beat: 'The morning after. {a} and {b} are sitting on {gone}’s stripped bed.' },
      { by: 'a', say: "{gone} is in the jury house right now." },
      { by: 'b', say: "Thinking about us." },
      { by: 'a', say: "Thinking about who voted out {gone}." },
      { by: 'b', say: "Do you think {gone} knows?" },
      { by: 'a', say: "{gone} knows. And {gone} has weeks to think about it." },
      { by: 'b', say: "Great. Love that for us." },
      { by: 'b', dr: "Every person who leaves now gets a vote for the winner. You're not just sending them home. You're sending them to judge you." },
    ] },
    { id: 'gt.jb2', phase: ['jury', 'endgame'], room: 'kitchen', turns: [
      { beat: 'Kitchen. {a} is making coffee. {b} comes in yawning.' },
      { by: 'b', say: "Is {gone} going to be bitter?" },
      { by: 'a', say: "Would you be?" },
      { by: 'b', say: "...Yeah. I'd be really bitter." },
      { by: 'a', say: "Then {gone} is going to be bitter." },
      { by: 'b', say: "We can fix it. If we make it to the end, we explain." },
      { by: 'a', say: "You think a speech fixes being lied to?" },
      { by: 'b', say: "I think it has to." },
      { by: 'a', dr: "Every juror walks out with a story about who did them wrong. You'd better hope you're not the villain in it." },
    ] },
    { id: 'gt.jb3', phase: ['jury', 'endgame'], turns: [
      { beat: 'The backyard. {a} and {b} are lying on the grass, staring up.' },
      { by: 'a', say: "Do you think {gone} would vote for us?" },
      { by: 'b', say: "For you, maybe. For me? Not a chance." },
      { by: 'a', say: "Why not?" },
      { by: 'b', say: "Because I hugged {gone} that morning and wrote {gone}'s name down that night." },
      { by: 'a', say: "Oof. That's going to hurt." },
      { by: 'b', say: "It already does." },
      { by: 'b', dr: "I'll see {gone} again on finale night. I've already started writing what I'll say." },
    ] },
  ],
  'talk.jury.manage': [
    { id: 'gt.jm1', phase: ['jury'], presumes: ['jurors'], room: 'bedroom', turns: [
      { beat: 'Bedroom, door shut. {a} and {b} are counting on their fingers.' },
      { by: 'a', say: "Who's on the jury so far? Who likes us?" },
      { by: 'b', say: "Maybe half of them, if we're lucky." },
      { by: 'a', say: "And who does the whole jury like?" },
      { by: 'b', say: "{c}." },
      { by: 'a', say: "{c} hasn't burned a single person. Nobody's bitter at {c}." },
      { by: 'b', say: "So {c} wins in front of any jury." },
      { by: 'a', say: "So {c} can't be sitting next to us at the end." },
      { by: 'a', dr: "The nicest person in the house is the most dangerous one now. Nobody on the jury has a reason to vote against {c}." },
    ] },
    { id: 'gt.jm2', phase: ['jury', 'endgame'], room: 'kitchen', turns: [
      { beat: 'Kitchen, late night. {a} and {b} are sharing a bag of crisps on the floor.' },
      { by: 'b', say: "If we make the end together, who wins?" },
      { by: 'a', say: "Honestly?" },
      { by: 'b', say: "Honestly." },
      { by: 'a', say: "Depends who's on the jury. Right now? Probably you." },
      { by: 'b', say: "Why me?" },
      { by: 'a', say: "Because I've been the one doing the dirty work." },
      { by: 'b', say: "We've both done it." },
      { by: 'a', say: "The jury doesn't see it like that. They see whose name was on the block." },
      { by: 'a', dr: "I've started thinking about how the jury sees me. It's not a pretty picture." },
    ] },
    { id: 'gt.jm3', phase: ['jury'], turns: [
      { beat: 'The backyard, pacing laps. {a} and {b} talk without looking at each other.' },
      { by: 'a', say: "I keep thinking about how I'd answer the jury." },
      { by: 'b', say: "Answer what?" },
      { by: 'a', say: "Why I deserve it. What I did." },
      { by: 'b', say: "And?" },
      { by: 'a', say: "And {c} has a better answer than me. That's the problem." },
      { by: 'b', say: "Then {c} doesn't get to answer." },
      { by: 'a', say: "Exactly." },
      { by: 'b', dr: "Late in the game, you're not just playing to survive. You're playing to have a story the jury wants to reward." },
    ] },
  ],
  'talk.endgame': [
    { id: 'gt.eg1', phase: ['endgame'], room: 'bedroom', turns: [
      { beat: 'An emptier house now. {a} and {b} are lying in the dark in a bedroom that used to sleep many more.' },
      { by: 'a', say: "It's so quiet." },
      { by: 'b', say: "There's nobody left to be loud." },
      { by: 'a', say: "Final two. You and me. Still?" },
      { by: 'b', say: "Still." },
      { by: 'a', say: "Even if {c} offers you something?" },
      { by: 'b', say: "{c} has nothing I want." },
      { by: 'a', say: "Okay." },
      { beat: 'Neither of them sleeps for a while.' },
      { by: 'a', dr: "{b} said 'still'. I believe it. I think. You can't really know in here until the last night." },
    ] },
    { id: 'gt.eg2', phase: ['endgame'], room: 'kitchen', turns: [
      { beat: 'The kitchen table, which seats a lot of people. Two of them are at it.' },
      { by: 'b', say: "Do you ever think about how many chairs this table has?" },
      { by: 'a', say: "Every time we sit down. There used to be so many of us." },
      { by: 'b', say: "We're nearly there." },
      { by: 'a', say: "Nearly isn't there. {c} still needs to go." },
      { by: 'b', say: "And if {c} wins the next HOH?" },
      { by: 'a', say: "Then one of us is in trouble, and we both know which." },
      { by: 'b', say: "Don't say that." },
      { by: 'a', say: "Somebody has to say it." },
      { by: 'b', dr: "This late, every competition is a final. Lose one and it could be over." },
    ] },
    { id: 'gt.eg3', phase: ['endgame'], turns: [
      { beat: 'The backyard, late. {a} and {b} are sitting on the edge of the pool, feet in the water.' },
      { by: 'a', say: "If it came down to it. Final three. Would you take me?" },
      { by: 'b', say: "Would you take me?" },
      { by: 'a', say: "I asked first." },
      { by: 'b', say: "I'd take you. I think I'd lose to you, and I'd still take you." },
      { by: 'a', say: "That's the nicest thing anyone's said to me in here." },
      { by: 'b', say: "Don't make me regret it." },
      { by: 'a', dr: "Taking someone you'd lose to is either loyalty or a mistake. In this house it's usually both." },
    ] },
  ],
  'talk.bond.vent': [
    { id: 'gt.bv1', phase: ['early'], room: 'bedroom', turns: [
      { beat: 'Bedroom. {a} drops onto the bed next to {b} and groans into a pillow.' },
      { by: 'b', say: "{c}?" },
      { by: 'a', say: "How did you know?" },
      { by: 'b', say: "It's always {c}." },
      { by: 'a', say: "{c} has to have the last word. Every single time." },
      { by: 'b', say: "Then don't talk to {c}." },
      { by: 'a', say: "We live in a house with one kitchen!" },
      { by: 'a', dr: "{c} and I are never going to be friends. I've accepted it. I'm just waiting for the right week." },
    ] },
    { id: 'gt.bv2', room: 'kitchen', turns: [
      { beat: 'The kitchen. {a} is chopping vegetables a lot harder than vegetables need. {b} watches.' },
      { by: 'b', say: "Who's the onion?" },
      { by: 'a', say: "{c} is the onion." },
      { by: 'b', say: "What happened?" },
      { by: 'a', say: "Nothing happened. That's the point. {c} just walks in and the room gets worse." },
      { by: 'b', say: "That's not a reason to evict somebody." },
      { by: 'a', say: "It's my reason." },
      { by: 'b', dr: "You can't win this game if you let one person get under your skin. {a} has let {c} all the way in." },
    ] },
    { id: 'gt.bv3', phase: ['jury', 'endgame'], room: 'bedroom', turns: [
      { beat: 'Bedroom. {a} is sitting with {b}, both keeping their voices down.' },
      { by: 'a', say: "I can't sit next to {c} at the end." },
      { by: 'b', say: "Why?" },
      { by: 'a', say: "Because I can't stand {c}. And it'll show. The jury will see it." },
      { by: 'b', say: "So beat {c} before the end." },
      { by: 'a', say: "I'm trying. It's not that easy." },
      { by: 'b', say: "Then keep trying." },
      { by: 'a', dr: "I've had to be nice to {c} for weeks. The day I don't have to anymore is going to be a good day." },
    ] },
    { id: 'gt.bv4', phase: ['prejury', 'jury'], turns: [
      { beat: 'The backyard. {a} is throwing a ball against the wall, over and over. {b} sits nearby.' },
      { by: 'a', say: "Have you noticed {c} being extra nice to me lately?" },
      { by: 'b', say: "I've noticed." },
      { by: 'a', say: "Smiling at me. Like we're friends." },
      { by: 'b', say: "Maybe {c} thinks you are." },
      { by: 'a', say: "Then {c} hasn't been paying attention." },
      { by: 'b', say: "Careful. If {c} goes to jury mad at you, that's a vote gone." },
      { by: 'a', say: "{c} was never voting for me anyway." },
      { by: 'a', dr: "{c} and I can be polite. Polite is not the same as liking someone." },
    ] },
    { id: 'gt.bv5', room: 'living-room', turns: [
      { beat: 'The living room. {a} and {b} are on the sofa. {a} is talking very quietly and very fast.' },
      { by: 'a', say: "Did you hear what {c} said about me?" },
      { by: 'b', say: "No. What?" },
      { by: 'a', say: "I don't know exactly. But I saw the faces." },
      { by: 'b', say: "That's not proof of anything." },
      { by: 'a', say: "In this house it is." },
      { by: 'b', say: "Don't start a fight over faces." },
      { by: 'a', say: "I'm not starting anything. I'm remembering it." },
      { by: 'b', dr: "{a} doesn't need proof about {c}. {a} has decided. That's worse." },
    ] },
  ],
  'talk.bond.trust': [
    { id: 'gt.bt1', phase: ['early', 'prejury'], room: 'bedroom', turns: [
      { beat: 'Bedroom, lights out. {a} and {b} are whispering between two beds.' },
      { by: 'a', say: "Can I tell you something?" },
      { by: 'b', say: "Always." },
      { by: 'a', say: "You're the only person in here I don't have to think around." },
      { by: 'b', say: "What does that mean?" },
      { by: 'a', say: "It means with everybody else, I'm working out what to say. With you I just talk." },
      { by: 'b', say: "Me too. I didn't know I needed that until now." },
      { by: 'b', dr: "In a house where everybody's playing, finding one person you can just be normal with is everything." },
    ] },
    { id: 'gt.bt2', room: 'kitchen', turns: [
      { beat: 'The kitchen, early morning. {a} has already made two coffees. One for {b}.' },
      { by: 'b', say: "You remembered how I take it." },
      { by: 'a', say: "I've watched you make it every morning." },
      { by: 'b', say: "That's either sweet or creepy." },
      { by: 'a', say: "It's sweet. Drink your coffee." },
      { by: 'b', say: "If we're ever up against each other..." },
      { by: 'a', say: "We won't be." },
      { by: 'b', say: "But if we are." },
      { by: 'a', say: "Then I'll still make you coffee." },
      { by: 'a', dr: "{b} is the person I'd trust with my game. I hope I never have to find out if that's a mistake." },
    ] },
    { id: 'gt.bt3', phase: ['jury', 'endgame'], turns: [
      { beat: 'The backyard, night. {a} and {b} are lying on the grass. The house behind them has gone quiet.' },
      { by: 'b', say: "Do you remember the first night?" },
      { by: 'a', say: "Barely. It feels like a year ago." },
      { by: 'b', say: "I didn't think we'd be friends." },
      { by: 'a', say: "Neither did I." },
      { by: 'b', say: "And now look." },
      { by: 'a', say: "Now look. The two of us, still here." },
      { by: 'b', say: "Whatever happens. I'm glad it was you." },
      { by: 'a', dr: "If I lose to {b}, I'll be okay with it. I don't say that about anyone else in here." },
    ] },
    { id: 'gt.bt4', room: 'living-room', turns: [
      { beat: 'The living room. {b} has fallen asleep on {a}’s shoulder mid-conversation. {a} hasn’t moved.' },
      { beat: 'Somebody walks past, sees them, and quietly turns off the lamp.' },
      { by: 'b', say: "...Was I asleep?" },
      { by: 'a', say: "For twenty minutes." },
      { by: 'b', say: "You could have moved." },
      { by: 'a', say: "I didn't want to." },
      { by: 'b', dr: "There are maybe two people in here I'd fall asleep next to. {a} is one of them. That says a lot about this house." },
    ] },
    { id: 'gt.bt5', phase: ['prejury', 'jury'], room: 'bedroom', turns: [
      { beat: 'Bedroom. {a} is sitting with {b}, both talking low and fast.' },
      { by: 'a', say: "Promise me something." },
      { by: 'b', say: "Depends." },
      { by: 'a', say: "If one of us has to go, the other one doesn't lie about it. We tell each other first." },
      { by: 'b', say: "That's a big promise in here." },
      { by: 'a', say: "That's why I'm asking you and nobody else." },
      { by: 'b', say: "...Okay. I promise." },
      { beat: 'They shake on it. Then {b} pulls {a} into a hug.' },
      { by: 'b', dr: "Nobody makes that promise in here. I made it. I meant it. I hope I never have to keep it." },
    ] },
  ],
};
