// ══════════════════════════════════════════════════════════════════════
// bb/story/lines/groups.js — three, four, five people in a room
// ══════════════════════════════════════════════════════════════════════
//
// The user, 2026-10-06: "most conversation especially at the start are like 3+ person",
// "there's group alliance too". write.js routes a step here when the group version exists:
// an alliance of three or more meets with everybody in it (c, d, e are the other members);
// gossip, banter, late nights, friends and a new couple being teased pull in the speakers'
// closest people as c, d and e. A line that needs d or e only airs when they are there.
// Group talk overlaps, interrupts and has side comments (docs/bb-dialogue-style.md §3).

export default {
  // ── an alliance of three or more, all in the room ───────────────────
  'story.alliance.formed.group': [
    { id: 'gf.1', room: 'bedroom', turns: [
      { beat: 'Bedroom, door shut. {a} has brought them in one at a time: {b}, then {c}, then everyone else.' },
      { by: 'c', say: "Okay, why are we all in here? This looks really suspicious." },
      { by: 'a', say: "Because I want to say something once, to all of you, so nobody hears it second-hand." },
      { by: 'b', say: "Go on." },
      { by: 'a', say: "Everyone in this room, I trust. Everyone outside it, I don't know yet. So I want us to be a group. Properly." },
      { by: 'c', say: "How many of us?" },
      { by: 'a', say: "Look around. This many. No more." },
      { by: 'b', say: "And we vote together?" },
      { by: 'a', say: "Every time. We argue in here, we vote out there as one." },
      { by: 'c', say: "I'm in." },
      { by: 'b', say: "In." },
      { by: 'a', say: "Then we're {alliance}." },
      { by: 'c', say: "Who came up with that?" },
      { by: 'a', say: "Me. Just now. Live with it." },
      { by: 'c', dr: "Walked into a bedroom with no idea, walked out in an alliance. That's how fast it happens in here." },
    ] },
    { id: 'gf.2', turns: [
      { by: 'd', say: "Wait. Is this an alliance? Are we making an alliance right now?" },
      { by: 'a', say: "Keep your voice down." },
      { by: 'd', say: "We are! We're making an alliance!" },
      { by: 'b', say: "We're having a chat." },
      { by: 'c', say: "A chat with the door locked." },
      { by: 'a', say: "Okay, yes. It's an alliance. If everyone wants it." },
      { by: 'd', say: "I want it." },
      { by: 'b', say: "I want it." },
      { by: 'c', say: "Obviously I want it, I locked the door." },
      { by: 'a', say: "Then it needs a name." },
      { by: 'd', say: "Something cool." },
      { by: 'a', say: "{alliance}." },
      { by: 'd', say: "...Something cooler." },
      { by: 'a', say: "It's {alliance}." },
      { by: 'b', dr: "Four people, one locked door, one terrible name. Honestly, I've never felt safer." },
    ] },
    { id: 'gf.3', presumes: ['hoh'], turns: [
      { by: 'a', say: "Can I say something to all three of you?" },
      { by: 'b', say: "That sounds serious." },
      { by: 'a', say: "Have you noticed we always end up together? Every meal, every night, same faces." },
      { by: 'c', say: "Because you're the only normal people in here." },
      { by: 'a', say: "Exactly. So everyone else has already decided we're a group. They're going to treat us like one." },
      { by: 'b', say: "So we might as well be one." },
      { by: 'a', say: "So we might as well be one." },
      { by: 'c', say: "Is this you recruiting us? In the kitchen? While I'm holding a spoon?" },
      { by: 'a', say: "Yes." },
      { by: 'c', say: "...Fine. Yes. Spoon and all." },
      { by: 'a', say: "{alliance}. That's us." },
      { by: 'b', dr: "We were already a group. We just hadn't said it out loud. Now there's a name, and a name means somebody can find out." },
    ] },
    { id: 'gf.4', room: 'backyard', when: { early: true }, turns: [
      { beat: 'Backyard. {a}, {b} and {c} are lying on the grass in a row.' },
      { by: 'b', say: "We've barely been here five minutes and I already know who I'd trust with my life." },
      { by: 'c', say: "Who?" },
      { by: 'b', say: "Look left and look right." },
      { by: 'a', say: "Aw." },
      { by: 'c', say: "That's so cheesy. I love it." },
      { by: 'a', say: "So let's make it real. The three of us, at least until the numbers get small." },
      { by: 'b', say: "And then?" },
      { by: 'a', say: "Then we deal with it like adults." },
      { by: 'c', say: "We're never going to be adults about it." },
      { by: 'a', say: "Then like children. But together. We're {alliance}." },
      { by: 'c', dr: "Three people on the grass, making a pact. It felt like a film. It also felt like the start of something that's going to hurt." },
    ] },
    { id: 'gf.5', turns: [
      { by: 'a', say: "Right. Everyone in? Door shut?" },
      { by: 'e', say: "Door's shut." },
      { by: 'a', say: "Okay. Five of us. Five votes. That's enough to decide every week in this house if we stick." },
      { by: 'b', say: "If." },
      { by: 'a', say: "If. That's the only word that matters. Can everyone in this room promise not to talk to the others about us?" },
      { by: 'c', say: "Promise." },
      { by: 'd', say: "Promise." },
      { by: 'e', say: "Promise." },
      { by: 'b', say: "...Promise." },
      { by: 'a', say: "You paused." },
      { by: 'b', say: "I was swallowing!" },
      { by: 'a', say: "Then we're {alliance}. Five of us. Nobody else." },
      { by: 'd', dr: "Five's a lot. Five's a majority. Five's also five mouths. Somebody will talk. Not me. But somebody." },
    ] },
    { id: 'gf.6', room: 'storage-room', turns: [
      { beat: 'Storage room. {a}, {b} and {c} squeezed between the shelves.' },
      { by: 'c', say: "Why is it always the storage room?" },
      { by: 'a', say: "Because nobody comes in here." },
      { by: 'b', say: "Everybody comes in here. It's where the food is." },
      { by: 'a', say: "Then let's be quick. We three want the same things. We should stop pretending we don't." },
      { by: 'c', say: "What things?" },
      { by: 'a', say: "To get to jury. To not be the first ones picked off. To have people who'll fight for us when we're up." },
      { by: 'b', say: "That's… actually everything." },
      { by: 'a', say: "That's everything. So we fight for each other. {alliance}." },
      { by: 'c', say: "Okay. In. Can we leave before someone wants crisps?" },
      { by: 'a', dr: "Some alliances are about winning. This one's about not losing alone." },
    ] },
  ],
  'story.alliance.checkin.group': [
    { id: 'gk.1', turns: [
      { by: 'a', say: "Okay, everyone, quick. Numbers. Where are we?" },
      { by: 'b', say: "We're good." },
      { by: 'c', say: "We're good." },
      { by: 'a', say: "Everybody keeps saying 'good'. Give me names." },
      { by: 'b', say: "Fine. I've got one more person saying our name. Maybe two." },
      { by: 'c', say: "I've got nobody new. But nobody's turned." },
      { by: 'a', say: "So that's us, plus one. Plus maybe two." },
      { by: 'b', say: "Plus maybe two." },
      { by: 'a', say: "'Maybe' doesn't vote." },
      { by: 'c', say: "Then let's turn 'maybe' into 'yes' tonight." },
      { by: 'a', dr: "{alliance} has never lost a vote. We've also never counted properly. Tonight we count properly." },
    ] },
    { id: 'gk.2', room: 'bedroom', turns: [
      { beat: 'Bedroom. {a}, {b}, {c} and {d} on two beds, talking in whispers.' },
      { by: 'd', say: "Can I say something without everyone jumping on me?" },
      { by: 'a', say: "No promises." },
      { by: 'd', say: "I think we're too obvious. Everyone knows we're a group." },
      { by: 'b', say: "So?" },
      { by: 'd', say: "So we keep sitting together at every meal. We might as well wear matching shirts." },
      { by: 'c', say: "I'd wear a matching shirt." },
      { by: 'a', say: "Nobody's wearing a matching shirt. {d}'s right, though. We split up a bit. In public." },
      { by: 'b', say: "And in private?" },
      { by: 'a', say: "In private, nothing changes. {alliance} is {alliance}." },
      { by: 'd', dr: "Nobody likes to hear their alliance is obvious. But someone had to say it before the house said it for us." },
    ] },
    { id: 'gk.3', presumes: ['noms'], turns: [
      { by: 'a', say: "So. The block. Is everyone where they should be on Thursday?" },
      { by: 'b', say: "Yes." },
      { by: 'c', say: "Yes." },
      { by: 'a', say: "Say the name. Out loud. All of you." },
      { by: 'b', say: "Really?" },
      { by: 'a', say: "Really. I want to hear it." },
      { beat: 'Everybody says the same name at the same time. It comes out like a choir.' },
      { by: 'c', say: "That was creepy." },
      { by: 'a', say: "That was perfect." },
      { by: 'b', dr: "{a} made us say it out loud like a promise. It was weird. It also worked. Nobody's wobbling now." },
    ] },
    { id: 'gk.4', turns: [
      { by: 'c', say: "Can we talk about the fact that one of us has been in the HOH room a lot?" },
      { by: 'b', say: "Here we go." },
      { by: 'a', say: "Who?" },
      { by: 'c', say: "I'm not naming names. I'm just saying, one of us." },
      { by: 'b', say: "It's me. Obviously it's me. I was asking for information. For us." },
      { by: 'c', say: "For an hour?" },
      { by: 'b', say: "It was a lot of information!" },
      { by: 'a', say: "Okay, okay. Next time, you tell us before you go up. Deal?" },
      { by: 'b', say: "Deal. Wow. Interrogated by my own alliance." },
      { by: 'c', dr: "Trust in {alliance} is like a glass. One crack and you can't stop looking at it." },
    ] },
    { id: 'gk.5', room: 'backyard', turns: [
      { beat: 'Backyard. {a}, {b}, {c} and {d} doing laps of the pool very slowly, as a group, which is not subtle at all.' },
      { by: 'b', say: "We look like a cult." },
      { by: 'a', say: "Keep walking. Anyone hear anything today?" },
      { by: 'c', say: "Somebody asked me if we're a group." },
      { by: 'd', say: "What did you say?" },
      { by: 'c', say: "I said, 'What group?'" },
      { by: 'b', say: "Smooth." },
      { by: 'c', say: "Then I walked straight out here with all of you." },
      { by: 'a', say: "...Less smooth." },
      { by: 'd', dr: "We are the least secret secret alliance in the history of this show." },
    ] },
    { id: 'gk.6', turns: [
      { by: 'a', say: "Hands in. Quickly. Before anyone walks past." },
      { by: 'b', say: "We're doing hands in again?" },
      { by: 'a', say: "Every week. It's tradition." },
      { by: 'c', say: "It's been, like, a week." },
      { by: 'a', say: "A week is a tradition in here. Hands in." },
      { beat: 'Hands go in. Somebody whispers "{alliance}" far too loudly.' },
      { by: 'b', say: "Who said it that loud?" },
      { by: 'c', say: "Not me." },
      { by: 'a', say: "It was definitely you." },
      { by: 'c', dr: "Every week the hands go in. Every week fewer of us mean it. But the hands still go in." },
    ] },
  ],
  'story.alliance.leftout.group': [
    { id: 'gl.1', room: 'bedroom', turns: [
      { beat: '{a} walks into the bedroom. {b}, {c} and the others are mid-sentence. The sentence stops.' },
      { by: 'a', say: "Oh. Is this a meeting?" },
      { by: 'b', say: "No. Just talking." },
      { by: 'a', say: "About what?" },
      { by: 'c', say: "Nothing. The comp." },
      { by: 'a', say: "All of you. About the comp. In here. With the door shut." },
      { by: 'b', say: "Okay, it was a bit of a meeting." },
      { by: 'a', say: "Of {alliance}. Which I'm in." },
      { by: 'c', say: "You were asleep!" },
      { by: 'a', say: "Then wake me up! That's literally what alliances do!" },
      { by: 'a', dr: "Left out of my own alliance. In my own bedroom. I'm not paranoid. I'm counting." },
    ] },
    { id: 'gl.2', turns: [
      { by: 'a', say: "So when was somebody going to tell me the plan?" },
      { by: 'b', say: "Tonight. We were going to tell you tonight." },
      { by: 'c', say: "We literally decided it an hour ago." },
      { by: 'a', say: "Without me." },
      { by: 'b', say: "You were in the HOH room!" },
      { by: 'a', say: "For ten minutes!" },
      { by: 'c', say: "A lot can happen in ten minutes." },
      { by: 'a', say: "Apparently. Like being cut out of everything." },
      { by: 'b', say: "Nobody's cutting you out. Sit down. Here's the plan." },
      { by: 'b', dr: "We messed up. But if {a} keeps making it this big, {a} is going to make it true." },
    ] },
    { id: 'gl.3', room: 'bedroom', turns: [
      { by: 'c', say: "Should we wait for {a}?" },
      { by: 'b', say: "{a}'s in the shower. We'll fill {a} in." },
      { by: 'd', say: "We always say that." },
      { by: 'b', say: "And we always do." },
      { by: 'd', say: "Do we, though?" },
      { beat: 'The bathroom door opens. {a} stands there with a towel on {a.posAdj} head.' },
      { by: 'a', say: "Fill me in on what?" },
      { by: 'b', say: "...Everything. Come in. Sit down." },
      { by: 'a', dr: "Every time I take a shower, my alliance has a meeting. I'm going to start showering with the door open." },
    ] },
    { id: 'gl.4', turns: [
      { by: 'a', say: "Can I ask the whole group a question?" },
      { by: 'b', say: "Sure." },
      { by: 'a', say: "If we had to cut someone in {alliance}, who would it be?" },
      { by: 'c', say: "Why would you ask that?" },
      { by: 'a', say: "Because I think you've already talked about it. And I think it's me." },
      { beat: 'Nobody says anything for slightly too long.' },
      { by: 'b', say: "That's not— nobody's said that." },
      { by: 'a', say: "Then why did nobody say 'no' straight away?" },
      { by: 'c', dr: "There's no good answer to that question. There's only the time it takes you to answer. We took too long." },
    ] },
  ],

  // ── gossip, three or four on a bed ──────────────────────────────────
  'story.target.gossip.group': [
    { id: 'gg.1', presumes: ['hoh'], room: 'bedroom', turns: [
      { beat: 'Bedroom. {a}, {b} and {c} on one bed, heads close together.' },
      { by: 'a', say: "Okay, nobody repeat this." },
      { by: 'c', say: "We never repeat anything." },
      { by: 'b', say: "We repeat everything." },
      { by: 'a', say: "{target} was in the HOH room for an hour last night." },
      { by: 'c', say: "An hour?" },
      { by: 'b', say: "Doing what?" },
      { by: 'a', say: "Exactly. Doing what?" },
      { by: 'c', say: "I bet they were making a deal." },
      { by: 'b', say: "Or crying. People cry up there." },
      { by: 'a', say: "{target} doesn't cry. {target} plans." },
      { by: 'c', dr: "We spent an hour talking about {target} spending an hour in the HOH room. Nobody saw the irony." },
    ] },
    { id: 'gg.2', turns: [
      { by: 'b', say: "Has anyone else noticed {target} never washes up?" },
      { by: 'c', say: "Oh, thank god, I thought it was just me." },
      { by: 'a', say: "Not once. I've counted." },
      { by: 'd', say: "Why are you counting?" },
      { by: 'a', say: "Because somebody has to count." },
      { by: 'c', say: "{target} just leaves the plate. Right next to the sink. Like it's a gift." },
      { by: 'b', say: "And then says 'thank you, guys!' like we're staff." },
      { by: 'd', say: "Okay, that's actually really annoying." },
      { by: 'a', say: "Welcome. You're one of us now." },
      { by: 'd', dr: "I walked in neutral on {target}. I walked out hating {target}'s plate. That's what this house does." },
    ] },
    { id: 'gg.3', room: 'kitchen', when: { early: true }, turns: [
      { beat: 'Kitchen. {a}, {b} and {c} are pretending to make sandwiches.' },
      { by: 'a', say: "First impressions. Go. {target}." },
      { by: 'b', say: "Too nice." },
      { by: 'c', say: "Way too nice." },
      { by: 'a', say: "Nobody's that nice this early." },
      { by: 'b', say: "Unless they're just nice." },
      { by: 'c', say: "Nobody's just nice on a show like this." },
      { by: 'a', say: "Exactly. So {target} is either a saint or a genius." },
      { by: 'b', say: "And there are no saints in here." },
      { by: 'b', dr: "We've barely met {target} and we've already decided {target}'s a genius villain because of some tea. This place." },
    ] },
    { id: 'gg.4', turns: [
      { by: 'c', say: "Who's the biggest threat in this house? Go round. One name each." },
      { by: 'a', say: "{target}." },
      { by: 'b', say: "{target}." },
      { by: 'c', say: "Oh, wow. Same." },
      { by: 'd', say: "Wait, I was going to say somebody else." },
      { by: 'a', say: "Who?" },
      { by: 'd', say: "...Doesn't matter. {target}." },
      { by: 'b', say: "That was very peer-pressured." },
      { by: 'd', say: "It was a hundred percent peer-pressured." },
      { by: 'c', dr: "Four people, one name. That's how a target is born in here. Not in a ceremony. On a bed." },
    ] },
    { id: 'gg.5', turns: [
      { by: 'a', say: "Did you hear what {target} said at dinner?" },
      { by: 'b', say: "What?" },
      { by: 'c', say: "Oh, I heard." },
      { by: 'a', say: "Tell them." },
      { by: 'c', say: "{target} said 'I'm not here to make friends'. At dinner. While eating our food." },
      { by: 'b', say: "Our food?" },
      { by: 'c', say: "The food we made!" },
      { by: 'b', say: "That's so rude." },
      { by: 'a', say: "Right?" },
      { by: 'b', dr: "I wasn't at dinner. I'm furious anyway. That's how fast gossip moves in here." },
    ] },
    { id: 'gg.6', room: 'backyard', turns: [
      { beat: 'Backyard. {a}, {b}, {c} and {d} on the loungers, all facing away from the house.' },
      { by: 'b', say: "Okay, is {target} watching?" },
      { by: 'c', say: "No, {target}'s inside." },
      { by: 'b', say: "Okay. So. {target} told me something weird this morning." },
      { by: 'a', say: "What?" },
      { by: 'b', say: "That we should all be 'careful who we trust'." },
      { by: 'd', say: "That's what people say when they're the one you shouldn't trust." },
      { by: 'a', say: "Exactly what I was going to say." },
      { by: 'c', say: "That's what everyone was going to say." },
      { by: 'd', dr: "We've decided {target} is untrustworthy because {target} told us not to trust people. Big Brother logic." },
    ] },
  ],

  // ── a week-one pitch to a room ──────────────────────────────────────
  'story.target.pitch.group': [
    { id: 'gp.1', presumes: ['hoh'], turns: [
      { by: 'a', say: "Okay, can I get the room's opinion on something?" },
      { by: 'b', say: "Always." },
      { by: 'a', say: "{target}. Yes or no. Do we trust {target}?" },
      { by: 'c', say: "No." },
      { by: 'b', say: "Not really." },
      { by: 'a', say: "Why not?" },
      { by: 'c', say: "Talks to everybody. Commits to nobody." },
      { by: 'b', say: "And always asks who you're voting for. Always." },
      { by: 'a', say: "So if we had to pick a name this week—" },
      { by: 'c', say: "—that's the name." },
      { by: 'a', dr: "I didn't have to push. I just asked the room. The room did the rest." },
    ] },
    { id: 'gp.2', room: 'living-room', presumes: ['hoh'], turns: [
      { beat: '{a} has gathered {b}, {c} and {d} on the sofa like a press conference.' },
      { by: 'a', say: "I'm going to make a case and you can all shoot it down." },
      { by: 'd', say: "Love a case." },
      { by: 'a', say: "{target} is the biggest threat in this house and nobody's saying it." },
      { by: 'b', say: "I've said it. Quietly." },
      { by: 'c', say: "I've thought it loudly." },
      { by: 'a', say: "So let's say it together. If we go to the HOH as a group, it's a group decision, and nobody wears it alone." },
      { by: 'd', say: "That's actually smart." },
      { by: 'b', say: "It's sneaky." },
      { by: 'a', say: "Smart is sneaky with good manners." },
      { by: 'c', dr: "Going to the HOH as a group, so nobody gets the blame. That's {a}'s whole game. And I'm in it now." },
    ] },
    { id: 'gp.3', presumes: ['hoh'], turns: [
      { by: 'b', say: "So what's the plan? Somebody tell me the plan." },
      { by: 'a', say: "The plan is {target}." },
      { by: 'c', say: "Since when?" },
      { by: 'a', say: "Since this morning. Since {target} went straight upstairs after the comp." },
      { by: 'b', say: "To congratulate the HOH?" },
      { by: 'a', say: "To 'congratulate' the HOH. For forty minutes." },
      { by: 'c', say: "Okay, that's a long congratulations." },
      { by: 'b', say: "That's a congratulations with a deal in it." },
      { by: 'a', say: "Exactly. So we get there before {target} does it again." },
      { by: 'b', dr: "Whoever gets to the HOH first, wins the week. We're about to run up the stairs. Metaphorically. Mostly." },
    ] },
  ],

  // ── banter, three or four people ────────────────────────────────────
  'story.life.banter.group': [
    { id: 'gb.1', turns: [
      { by: 'a', say: "Okay, settle something for us. Is a hot dog a sandwich?" },
      { by: 'b', say: "Yes." },
      { by: 'c', say: "No." },
      { by: 'd', say: "Here we go." },
      { by: 'b', say: "Bread, filling. Sandwich." },
      { by: 'c', say: "A sandwich has two pieces of bread!" },
      { by: 'b', say: "A sub roll is one piece of bread!" },
      { by: 'c', say: "Is a sub a sandwich, then?" },
      { by: 'b', say: "OBVIOUSLY a sub is a sandwich!" },
      { by: 'd', say: "Is a taco a sandwich?" },
      { beat: 'The table erupts. Nobody agrees on anything for the next ten minutes.' },
      { by: 'a', dr: "This is the most anyone's argued since we got here. Not about votes. About a hot dog." },
    ] },
    { id: 'gb.2', turns: [
      { by: 'b', say: "If this house was a school, what would everyone be?" },
      { by: 'a', say: "{c}'s the teacher's pet." },
      { by: 'c', say: "Excuse me?" },
      { by: 'a', say: "You always tell Big Brother when someone's not wearing their mic." },
      { by: 'c', say: "That's a rule!" },
      { by: 'b', say: "Teacher's pet." },
      { by: 'd', say: "What am I?" },
      { by: 'b', say: "You're the kid at the back of the class who sleeps through everything and still passes." },
      { by: 'd', say: "...Accurate." },
      { by: 'c', dr: "I'm not a teacher's pet. I just like the rules. That's completely different. I'm going to tell Big Brother." },
    ] },
    { id: 'gb.3', room: 'kitchen', turns: [
      { beat: 'Kitchen. {a} is attempting pancakes. {b}, {c} and {d} are watching like it’s a sport.' },
      { by: 'b', say: "Flip it." },
      { by: 'a', say: "It's not ready." },
      { by: 'c', say: "It's been ready for a minute." },
      { by: 'd', say: "It's smoking a bit." },
      { by: 'a', say: "That's the butter." },
      { by: 'b', say: "That's the pancake." },
      { beat: '{a} flips it. It lands on the floor.' },
      { by: 'c', say: "Ten out of ten." },
      { by: 'd', say: "Points for height." },
      { by: 'a', dr: "Four people, one pancake, zero help. That's a house in a nutshell." },
    ] },
    { id: 'gb.4', presumes: ['hoh'], turns: [
      { by: 'a', say: "What's the first thing you'll eat when you get out?" },
      { by: 'b', say: "Pizza. Obviously." },
      { by: 'c', say: "A whole roast chicken. By myself. In silence." },
      { by: 'd', say: "That's dark." },
      { by: 'c', say: "That's a dream." },
      { by: 'a', say: "I just want a salad that hasn't been sitting in that fridge for a week." },
      { by: 'b', say: "Boo." },
      { by: 'd', say: "Boo! Salad!" },
      { by: 'a', say: "Fine! Chips! A bucket of chips!" },
      { by: 'b', say: "Better." },
      { by: 'd', dr: "We talk about food for an hour every day. It's the only thing in here everyone agrees on." },
    ] },
    { id: 'gb.5', turns: [
      { by: 'c', say: "Okay, impressions. Who can do the Big Brother voice?" },
      { by: 'a', say: "'{b}, please go to the Diary Room.'" },
      { by: 'b', say: "That's terrible." },
      { by: 'd', say: "Let me. 'Houseguests. This is not a drill.'" },
      { by: 'c', say: "That's not what it says!" },
      { by: 'd', say: "It's what it should say!" },
      { by: 'b', say: "'Houseguests, please stop talking about pancakes.'" },
      { beat: 'Over the speakers, a voice calls one of them to the Diary Room. Everybody screams.' },
      { by: 'a', dr: "Big Brother has perfect timing. I'm convinced it's listening. It's always listening." },
    ] },
    { id: 'gb.6', turns: [
      { by: 'a', say: "Can we all agree to never do the dishes again?" },
      { by: 'b', say: "That's how we got here." },
      { by: 'c', say: "Where's 'here'?" },
      { by: 'b', say: "A kitchen with no clean spoons." },
      { by: 'd', say: "I'll do them if someone sings." },
      { by: 'a', say: "Deal." },
      { beat: '{a} sings. Badly. {d} does the dishes. {b} and {c} join in on the chorus.' },
      { by: 'c', dr: "We sang four songs and did every dish in the house. Best hour all week. Don't tell anyone, they'll expect it again." },
    ] },
    { id: 'gb.7', presumes: ['hoh'], turns: [
      { by: 'b', say: "Does anyone know what day it is?" },
      { by: 'a', say: "No." },
      { by: 'c', say: "Thursday?" },
      { by: 'd', say: "It's definitely not Thursday." },
      { by: 'c', say: "How do you know?" },
      { by: 'd', say: "Because nobody's crying." },
      { by: 'b', say: "That's actually the best way to tell." },
      { by: 'a', say: "Tuesday. It feels like a Tuesday." },
      { by: 'c', say: "Every day feels like a Tuesday in here." },
      { by: 'b', dr: "You stop knowing what day it is. You start knowing what kind of day it is. This is a waiting day." },
    ] },
  ],
  'story.life.latenight.group': [
    { id: 'gn.1', room: 'kitchen', turns: [
      { beat: 'Kitchen, two in the morning. {a} is eating cereal. {b} and {c} wander in, one after the other.' },
      { by: 'b', say: "Oh. Hi." },
      { by: 'a', say: "Can't sleep?" },
      { by: 'b', say: "Can't sleep." },
      { by: 'c', say: "Can't sleep either. Is there more cereal?" },
      { by: 'a', say: "Half a box." },
      { by: 'c', say: "Perfect." },
      { beat: 'Three people at the counter, eating cereal in the dark.' },
      { by: 'b', say: "Do you guys ever forget we're on TV?" },
      { by: 'a', say: "Right now? Yeah." },
      { by: 'c', say: "Right now's the only time I forget." },
      { by: 'b', dr: "Two in the morning is the only time this house is honest. Everyone's too tired to lie." },
    ] },
    { id: 'gn.2', room: 'backyard', turns: [
      { beat: 'Backyard, late. {a}, {b}, {c} and {d} lying on the grass, looking up.' },
      { by: 'a', say: "What's the first thing you'll do when you get out?" },
      { by: 'b', say: "Sleep for two days." },
      { by: 'c', say: "Have a shower with nobody waiting." },
      { by: 'd', say: "Look at my phone for six hours straight." },
      { by: 'a', say: "That's so sad." },
      { by: 'd', say: "It's so honest." },
      { beat: 'Everybody laughs, quietly. Then nobody says anything for a long time.' },
      { by: 'b', say: "I'm going to miss this, weirdly." },
      { by: 'c', say: "Don't. Don't make it sad." },
      { by: 'c', dr: "Moments like that, you forget it's a game. Then you remember. Then you feel bad for forgetting." },
    ] },
    { id: 'gn.3', turns: [
      { by: 'a', say: "Is everyone awake?" },
      { by: 'b', say: "Yes." },
      { by: 'c', say: "Unfortunately." },
      { by: 'd', say: "No." },
      { by: 'a', say: "{d}, you answered." },
      { by: 'd', say: "I'm sleep-talking." },
      { by: 'b', say: "What's keeping everyone up?" },
      { by: 'c', say: "Thursday." },
      { by: 'a', say: "Thursday." },
      { by: 'd', say: "Thursday. Go to sleep." },
      { beat: 'Nobody goes to sleep.' },
      { by: 'b', dr: "Four people lying in the dark, all thinking about the same vote, none of us saying a name. That's a bedroom on eviction week." },
    ] },
    { id: 'gn.4', turns: [
      { by: 'b', say: "Can I ask everyone something weird?" },
      { by: 'a', say: "It's three in the morning. Everything's weird." },
      { by: 'b', say: "Do you think we'd all be friends? Outside?" },
      { by: 'c', say: "Some of us." },
      { by: 'a', say: "Which some?" },
      { by: 'c', say: "I'm not answering that in a room full of witnesses." },
      { by: 'd', say: "Smart." },
      { by: 'b', say: "I think we would. All of us. We'd have a group chat." },
      { by: 'a', say: "The group chat would be chaos." },
      { by: 'b', say: "The best chaos." },
      { by: 'd', dr: "It's sweet. It's also exactly what you say to people you're about to vote out." },
    ] },
  ],
  'story.life.friends.group': [
    { id: 'gw.1', turns: [
      { by: 'a', say: "I just want to say I love you guys." },
      { by: 'b', say: "Oh no, is someone going home?" },
      { by: 'a', say: "No! I'm just saying it!" },
      { by: 'c', say: "We love you too. Weirdo." },
      { by: 'd', say: "Group hug?" },
      { by: 'b', say: "Absolutely not." },
      { beat: 'Group hug. {b} is in the middle of it, complaining the whole time.' },
      { by: 'b', say: "I hate this." },
      { by: 'c', say: "You love this." },
      { by: 'b', dr: "I love this. Don't tell them." },
    ] },
    { id: 'gw.2', room: 'bedroom', turns: [
      { beat: '{a}, {b} and {c} have dragged the mattresses into one corner of the bedroom.' },
      { by: 'c', say: "Is this allowed?" },
      { by: 'a', say: "Nobody said it isn't." },
      { by: 'b', say: "We've built a nest." },
      { by: 'a', say: "It's a fort." },
      { by: 'b', say: "It's a nest. We're baby birds." },
      { by: 'c', say: "Baby birds in a nest in a game show." },
      { by: 'a', say: "Best nest in the house." },
      { by: 'c', dr: "Three adults sleeping in a nest. Everyone else thinks it's an alliance. It's just a nest. Mostly." },
    ] },
    { id: 'gw.3', room: 'bedroom', turns: [
      { by: 'a', say: "Whatever happens, we stay friends. All of us." },
      { by: 'b', say: "Even if we vote each other out?" },
      { by: 'a', say: "Especially then." },
      { by: 'c', say: "That's going to be tested." },
      { by: 'd', say: "Probably this week." },
      { by: 'a', say: "Then this week we'll find out." },
      { by: 'b', say: "Pinky promise." },
      { beat: 'Four little fingers link in the middle of the bed.' },
      { by: 'd', dr: "We made a pinky promise. In a house where promises last about four days. I really hope this one's different." },
    ] },
  ],

  // ── a new couple, and their friends ─────────────────────────────────
  'story.showmance.spark.group': [
    { id: 'gs.1', turns: [
      { by: 'c', say: "So. You two." },
      { by: 'a', say: "What about us two?" },
      { by: 'd', say: "Don't play dumb. You've been on that sofa for three hours." },
      { by: 'b', say: "It's a comfy sofa." },
      { by: 'c', say: "It's the worst sofa in the house." },
      { by: 'a', say: "We were just talking." },
      { by: 'd', say: "About what?" },
      { by: 'a', say: "...Stuff." },
      { by: 'c', say: "'Stuff'. They were talking about 'stuff'." },
      { beat: '{b} throws a cushion at {c}. {a} goes bright red.' },
      { by: 'd', dr: "Everyone can see it. Everyone. Except, apparently, the two of them." },
    ] },
    { id: 'gs.2', room: 'kitchen', turns: [
      { beat: 'Kitchen. {a} and {b} are cooking together. {c} and {d} are watching from the counter, eating crisps.' },
      { by: 'c', say: "This is better than TV." },
      { by: 'd', say: "This is TV." },
      { by: 'a', say: "Can you two go somewhere else?" },
      { by: 'c', say: "No, we're invested." },
      { by: 'b', say: "We're making pasta." },
      { by: 'd', say: "You're making eyes." },
      { by: 'a', say: "Oh my god." },
      { by: 'c', say: "Look, they're both blushing." },
      { by: 'b', dr: "Can't flirt in this house without a live audience. And a commentary team. With crisps." },
    ] },
    { id: 'gs.3', turns: [
      { by: 'c', say: "Truth or dare, everyone. {a}, you first." },
      { by: 'a', say: "Truth." },
      { by: 'c', say: "Who in this house would you kiss?" },
      { by: 'a', say: "That's not fair." },
      { by: 'd', say: "It's truth. You picked it." },
      { beat: '{a} doesn’t say anything. {a} also doesn’t look away from {b}.' },
      { by: 'd', say: "Oh, that's an answer." },
      { by: 'c', say: "That's an answer with a face." },
      { by: 'b', say: "My turn! Dare. Give me a dare. Change the subject." },
      { by: 'b', dr: "{a} didn't say a name. {a} didn't need to. Now the whole room knows. Great." },
    ] },
    { id: 'gs.4', turns: [
      { by: 'c', say: "Okay, intervention. You two need to just admit it." },
      { by: 'a', say: "Admit what?" },
      { by: 'd', say: "That you like each other." },
      { by: 'b', say: "We're friends." },
      { by: 'c', say: "Friends don't share a towel." },
      { by: 'a', say: "It was one time! Mine was wet!" },
      { by: 'd', say: "Friends don't make each other's tea with the exact right amount of sugar." },
      { by: 'b', say: "That's just being observant." },
      { by: 'c', say: "That's being in love." },
      { beat: '{a} and {b} look at each other and then very quickly away.' },
      { by: 'c', dr: "Somebody had to say it. They were never going to. I'm basically a cupid. A nosy cupid." },
    ] },
    { id: 'gs.5', room: 'living-room', turns: [
      { beat: 'Living room. {a}’s head is on {b}’s shoulder. {c} and {d} are sitting opposite, staring.' },
      { by: 'a', say: "What?" },
      { by: 'c', say: "Nothing." },
      { by: 'd', say: "Nothing at all." },
      { by: 'b', say: "You're both staring." },
      { by: 'c', say: "We're looking at the wall behind you." },
      { by: 'd', say: "It's a really interesting wall." },
      { by: 'a', say: "...I'm not moving." },
      { by: 'c', say: "We didn't ask you to." },
      { by: 'd', dr: "Nobody's moving. Nobody's saying it. Everybody knows. Day whatever-it-is of the slowest romance in history." },
    ] },
  ],
};
