// ══════════════════════════════════════════════════════════════════════
// bb/story/lines/groups3.js — campaigning, the block, the count, and the house rallying
// ══════════════════════════════════════════════════════════════════════
//
// More of the house in more of the scenes (the user, 2026-10-06: "most conversation
// especially at the start are like 3+ person"). A nominee works a room of voters, friends
// gather round somebody on the block, allies count together, the house rallies round a
// homesick friend, a prank has an audience. Roles as in groups.js; a is the nominee in
// lobby and block, {target} the other nominee.

export default {
  'story.target.lobby.group': [
    { id: 'gl3.1', room: 'bedroom', presumes: ['noms'], turns: [
      { beat: '{a} finds {b}, {c} and {d} together in the bedroom and shuts the door.' },
      { by: 'a', say: "I know. I know. Everyone's sick of being talked to." },
      { by: 'b', say: "You're the fourth person today." },
      { by: 'a', say: "Then I'll be quick. I'm not asking for a promise. I'm asking for a fair hearing." },
      { by: 'c', say: "Go on, then." },
      { by: 'a', say: "Keep me, and I'm a vote for every person in this room next week. Keep {target}, and {target} owes the people who put me up. Not you." },
      { by: 'd', say: "That's actually a good point." },
      { by: 'b', say: "It's a very good point." },
      { by: 'a', say: "That's all. Think about it." },
      { beat: '{a} leaves. The three of them look at each other.' },
      { by: 'c', say: "...Okay. That was good." },
      { by: 'c', dr: "Pitching three people at once is either very brave or very stupid. With {a}, it worked." },
    ] },
    { id: 'gl3.2', presumes: ['noms'], turns: [
      { by: 'a', say: "Can I have everyone for one minute? Just one?" },
      { by: 'b', say: "Is this a campaign speech?" },
      { by: 'a', say: "It's a campaign speech." },
      { by: 'c', say: "At dinner?" },
      { by: 'a', say: "Everyone's here. It's efficient." },
      { by: 'd', say: "Fine. One minute." },
      { by: 'a', say: "I haven't won anything. I haven't put anyone up. I've never lied to anyone in this room. That's my case." },
      { by: 'b', say: "That's it?" },
      { by: 'a', say: "That's it. I'm not good at speeches." },
      { by: 'd', say: "...That was a pretty good speech." },
      { by: 'b', dr: "{a} did the whole campaign at dinner, in one go. Short and honest. Annoyingly effective." },
    ] },
    { id: 'gl3.3', presumes: ['noms'], turns: [
      { by: 'b', say: "So who's everyone voting for?" },
      { by: 'c', say: "You can't just ask that." },
      { by: 'a', say: "Well, I'm sitting right here, so I'd love to know." },
      { by: 'd', say: "Awkward." },
      { by: 'a', say: "It's fine. Just be honest. Am I going?" },
      { by: 'b', say: "...It's close." },
      { by: 'c', say: "It's really close." },
      { by: 'a', say: "Close how?" },
      { by: 'd', say: "Close like you should go and talk to a couple more people." },
      { by: 'a', say: "Names. Give me names." },
      { by: 'd', dr: "{a} asked the room straight out. Nobody gave names. But we gave {a} enough to go on." },
    ] },
    { id: 'gl3.4', room: 'backyard', presumes: ['noms'], turns: [
      { beat: 'Backyard. {a} is lying on a lounger. {b}, {c} and {d} are on the ones around it.' },
      { by: 'a', say: "Be honest. If it was you, what would you do?" },
      { by: 'b', say: "Talk to everyone." },
      { by: 'c', say: "Talk to nobody. Let them come to you." },
      { by: 'd', say: "Win the veto." },
      { by: 'a', say: "The veto's done." },
      { by: 'd', say: "Oh. Then talk to everyone." },
      { by: 'a', say: "Great. So I've got a fifty-fifty on advice." },
      { by: 'b', say: "You've got three people right here who want you to stay. Start with us." },
      { by: 'a', dr: "Three votes on three loungers. I'm not saying I cried. I'm saying the sun was very bright." },
    ] },
    { id: 'gl3.5', presumes: ['noms'], when: { register: ['fiery', 'competitor'] }, turns: [
      { by: 'a', say: "Right, everyone in here. I'm not begging. I'm telling you facts." },
      { by: 'b', say: "Here we go." },
      { by: 'a', say: "Fact one. I win comps. If I stay, I'm a shield. People come after me, not you." },
      { by: 'c', say: "That's… actually true." },
      { by: 'a', say: "Fact two. {target} is a vote for whoever is HOH. Every week. Ask anyone." },
      { by: 'd', say: "Also true." },
      { by: 'a', say: "Fact three. I'm loud, but I'm loyal. Ask anybody I've ever voted with." },
      { by: 'b', say: "Are there more facts?" },
      { by: 'a', say: "That's all the facts. Vote smart." },
      { by: 'c', dr: "Three facts, no begging, no tears. I didn't think a campaign could be that persuasive and that loud at the same time." },
    ] },
    { id: 'gl3.6', presumes: ['noms'], turns: [
      { by: 'b', say: "Okay, we've talked about it." },
      { by: 'a', say: "Who's 'we'?" },
      { by: 'c', say: "Us three." },
      { by: 'a', say: "And?" },
      { by: 'd', say: "And we want to keep you. But we need you to promise something." },
      { by: 'a', say: "Anything." },
      { by: 'b', say: "If you win HOH next week, none of us go up. None." },
      { by: 'a', say: "Done. Easy. Done." },
      { by: 'c', say: "Say it like you mean it." },
      { by: 'a', say: "None of you go up. I swear." },
      { by: 'd', dr: "Three votes for one promise. It's a good deal for {a}. It's a better deal for us, if {a} keeps it." },
    ] },
  ],
  'story.target.block.group': [
    { id: 'gk3.1', presumes: ['noms'], room: 'bedroom', turns: [
      { beat: 'Bedroom. {a} is curled up on a bed. {b}, {c} and {d} have arrived one by one and now all sit around {a}.' },
      { by: 'b', say: "We brought snacks." },
      { by: 'c', say: "And a blanket." },
      { by: 'd', say: "And me. I'm the third thing." },
      { by: 'a', say: "You're all ridiculous." },
      { by: 'b', say: "You're on the block. You're allowed ridiculous people." },
      { by: 'a', say: "What are people saying out there?" },
      { by: 'c', say: "Not now. Snacks first. Then strategy." },
      { by: 'a', say: "...What kind of snacks?" },
      { by: 'a', dr: "Being on the block is the loneliest thing in this house. Except when it isn't. Today it wasn't." },
    ] },
    { id: 'gk3.2', presumes: ['noms'], turns: [
      { by: 'b', say: "Okay. War council." },
      { by: 'a', say: "I don't want a war council." },
      { by: 'c', say: "You're getting a war council." },
      { by: 'd', say: "Who's definitely voting {target} out?" },
      { by: 'b', say: "Us three. Obviously." },
      { by: 'c', say: "And two more who said yes but looked at the floor." },
      { by: 'a', say: "Floor-yes doesn't count." },
      { by: 'd', say: "Then we go turn the floor-yeses into eye-contact yeses. Tonight." },
      { by: 'b', say: "We'll split up. Two people each." },
      { by: 'a', dr: "I've got three people running my campaign for me. I didn't ask. I'm not going to stop them." },
    ] },
    { id: 'gk3.3', room: 'kitchen', presumes: ['noms'], turns: [
      { beat: 'Kitchen. {a} is staring into a mug of tea that has gone cold. {b}, {c} and {d} are trying to be normal around {a}.' },
      { by: 'b', say: "Want me to make you a fresh one?" },
      { by: 'a', say: "This one's fine." },
      { by: 'c', say: "It's stone cold." },
      { by: 'a', say: "I like it cold." },
      { by: 'd', say: "Nobody likes it cold." },
      { by: 'a', say: "I can't even drink tea properly. I'm on the block and I can't drink tea." },
      { by: 'b', say: "Hey. It's not over." },
      { by: 'c', say: "We've got four days. Four days is a lot in here." },
      { by: 'a', dr: "They made me a fresh tea anyway. I drank it. It helped. Stupid tea." },
    ] },
    { id: 'gk3.4', presumes: ['noms'], turns: [
      { by: 'a', say: "If I go on Thursday—" },
      { by: 'b', say: "No." },
      { by: 'c', say: "Nope." },
      { by: 'd', say: "Not doing it." },
      { by: 'a', say: "Let me finish!" },
      { by: 'b', say: "You're going to do a goodbye speech. We're not having a goodbye speech on a Monday." },
      { by: 'a', say: "It's not a goodbye speech. It's a 'thank you' speech." },
      { by: 'c', say: "Save it for Thursday. If you need it. Which you won't." },
      { by: 'a', dr: "Three people refused to let me say goodbye. That's either friendship or denial. Maybe both." },
    ] },
  ],
  'story.target.count.group': [
    { id: 'gc3.1', presumes: ['noms'], turns: [
      { by: 'a', say: "Right. Everybody. Count it with me. Out loud." },
      { by: 'b', say: "Everyone in this room." },
      { by: 'c', say: "Plus the two in the kitchen. They said {target}." },
      { by: 'd', say: "Out loud?" },
      { by: 'c', say: "Out loud. To my face." },
      { by: 'a', say: "That's enough to send {target} home." },
      { by: 'b', say: "So we've got it." },
      { by: 'a', say: "We've got it today. Nobody talks to anyone about it till Thursday." },
      { by: 'd', say: "Not even a little?" },
      { by: 'a', say: "Not even a little." },
      { by: 'b', dr: "Every vote, counted out loud in a bedroom. If this leaks, we'll know it was one of us." },
    ] },
    { id: 'gc3.2', presumes: ['noms'], turns: [
      { by: 'b', say: "Somebody's lying to us." },
      { by: 'a', say: "Why?" },
      { by: 'b', say: "Because I counted, and it doesn't add up." },
      { by: 'c', say: "Count again." },
      { by: 'b', say: "I've counted four times!" },
      { by: 'd', say: "Count with us, then." },
      { beat: 'They count together, on their fingers, name by name.' },
      { by: 'a', say: "...That's one short." },
      { by: 'c', say: "Who said yes and looked away?" },
      { by: 'd', dr: "One vote short. Four people in a room trying to remember which 'yes' sounded like a 'no'." },
    ] },
    { id: 'gc3.3', room: 'storage-room', presumes: ['noms'], turns: [
      { beat: 'Storage room. {a}, {b}, {c} and {d} squeezed between the shelves, whispering.' },
      { by: 'a', say: "Is everyone still on {target}?" },
      { by: 'b', say: "Yes." },
      { by: 'c', say: "Yes." },
      { by: 'd', say: "...Yes." },
      { by: 'a', say: "That 'yes' was late." },
      { by: 'd', say: "I was thinking!" },
      { by: 'a', say: "About what?" },
      { by: 'd', say: "About whether there's any more cereal in here. There isn't. I'm with you." },
      { by: 'a', dr: "Every vote is a room of people saying 'yes' and one person saying it slightly too slowly." },
    ] },
  ],
  'story.life.homesick.group': [
    { id: 'gh3.1', presumes: ['hoh'], turns: [
      { beat: '{a} has been quiet all day. At dinner, {b}, {c} and {d} finally say something.' },
      { by: 'b', say: "You okay? You've barely eaten." },
      { by: 'a', say: "Just missing home a bit." },
      { by: 'c', say: "Oh, we all are." },
      { by: 'd', say: "Tell us one thing you miss. Just one." },
      { by: 'a', say: "...My own bed. Not being watched." },
      { by: 'b', say: "Mine's my kitchen." },
      { by: 'c', say: "Mine's going for a walk and not coming back for hours." },
      { by: 'd', say: "Mine's silence. Actual silence." },
      { by: 'a', dr: "Everyone at the table said what they miss. It made me feel a lot less alone. And a lot more homesick. Both." },
    ] },
    { id: 'gh3.2', presumes: ['hoh'], room: 'bedroom', turns: [
      { beat: 'Bedroom. {a} is under a blanket. {b} lifts the corner of it. {c} and {d} are right behind.' },
      { by: 'b', say: "We're coming in." },
      { by: 'a', say: "It's a one-person blanket." },
      { by: 'c', say: "Not any more." },
      { beat: 'Four people under one blanket. It does not fit.' },
      { by: 'd', say: "This is so uncomfortable." },
      { by: 'a', say: "...Thank you." },
      { by: 'b', say: "We're not leaving till you smile." },
      { beat: '{a} smiles.' },
      { by: 'b', dr: "Homesickness in here comes in waves. When it gets one of us, the rest of us just pile on. Literally." },
    ] },
    { id: 'gh3.3', presumes: ['hoh'], turns: [
      { by: 'b', say: "Okay. Distraction time. Everyone tell {a} the most embarrassing thing that's happened to them in here." },
      { by: 'c', say: "I walked into the Diary Room and forgot what I went in for." },
      { by: 'd', say: "I fell off the hammock twice in one day." },
      { by: 'b', say: "I said 'thank you' to the fridge." },
      { by: 'a', say: "You did not." },
      { by: 'b', say: "Out loud. It had been a long day." },
      { beat: '{a} laughs for the first time all day.' },
      { by: 'a', dr: "Three people embarrassed themselves on purpose to cheer me up. That's love, in here." },
    ] },
  ],
  'story.life.prank.group': [
    { id: 'gx3.1', room: 'bedroom', turns: [
      { beat: '{a} has filled {b}’s pillowcase with crisps. {c} and {d} are hiding behind the bedroom door to watch.' },
      { by: 'c', say: "Shh. Here they come." },
      { beat: '{b} flops onto the bed. Crunch.' },
      { by: 'b', say: "What—" },
      { beat: '{c} and {d} burst out laughing from behind the door.' },
      { by: 'b', say: "Who did this?" },
      { by: 'd', say: "Not us. We just watched." },
      { by: 'a', say: "...It was a gift." },
      { by: 'b', dr: "There are crisps in my hair. There will be crisps in my bed for the rest of the season. Revenge is coming. For all three of them." },
    ] },
    { id: 'gx3.2', turns: [
      { by: 'a', say: "Okay. Everyone. The plan." },
      { by: 'c', say: "I love a plan." },
      { by: 'a', say: "When {b} goes for a shower, we move all the furniture in the bedroom one foot to the left." },
      { by: 'd', say: "Why?" },
      { by: 'a', say: "So it's wrong, but {b} can't work out why." },
      { by: 'c', say: "That's evil." },
      { by: 'a', say: "That's art." },
      { beat: 'Twenty minutes later, {b} stands in the doorway, frowning, for a very long time.' },
      { by: 'b', say: "Something's different." },
      { by: 'd', dr: "{b} knew something was off and could never prove it. Best prank in the house. Nobody got hurt. Except {b}'s sense of reality." },
    ] },
    { id: 'gx3.3', room: 'kitchen', turns: [
      { beat: 'Kitchen. {a} has replaced the sugar with salt. {c} and {d} know. {b} does not.' },
      { by: 'c', say: "Make us all a cup of tea, {b}?" },
      { by: 'b', say: "Sure." },
      { by: 'd', say: "Two sugars in mine." },
      { by: 'b', say: "Coming up." },
      { beat: '{b} takes a big sip of {b.posAdj} own tea first. Silence.' },
      { by: 'b', say: "...Why does this taste like the sea?" },
      { beat: '{a}, {c} and {d} completely lose it.' },
      { by: 'b', dr: "Three people, one salt pot, and my dignity. I'll get them back. I've got all season." },
    ] },
  ],
  'story.life.chores.group': [
    { id: 'gr3.1', turns: [
      { by: 'a', say: "House meeting. About the kitchen." },
      { by: 'b', say: "Oh no." },
      { by: 'c', say: "Here we go." },
      { by: 'a', say: "There are more mugs in that sink than there are people in this house." },
      { by: 'd', say: "So somebody's using two." },
      { by: 'a', say: "Somebody's using three. And I'm tired." },
      { by: 'b', say: "Fine. Rota. Let's do a rota." },
      { by: 'c', say: "We had a rota. Nobody followed it." },
      { by: 'a', say: "Then we do a new rota, and this time I'm in charge of it." },
      { by: 'd', dr: "{a} is in charge of the rota now. Power has gone to {a}'s head. Over mugs." },
    ] },
    { id: 'gr3.2', room: 'kitchen', turns: [
      { beat: '{a}, {b}, {c} and {d} are doing a "deep clean" of the kitchen, which mostly means arguing about where things go.' },
      { by: 'a', say: "The pans go in the bottom cupboard." },
      { by: 'b', say: "The pans have always gone in the top cupboard." },
      { by: 'c', say: "The pans go wherever there's space." },
      { by: 'd', say: "There's never space." },
      { by: 'a', say: "Because nobody puts the pans in the bottom cupboard!" },
      { beat: 'A pan falls out of the top cupboard. Everybody looks at it.' },
      { by: 'b', say: "...Okay. Bottom cupboard." },
      { by: 'c', dr: "We spent an hour on the kitchen. It is exactly as messy as when we started, but the pans are in a new place." },
    ] },
    { id: 'gr3.3', room: 'bathroom', turns: [
      { by: 'a', say: "Everyone grab a cloth. We're cleaning the bathroom. Together." },
      { by: 'b', say: "Together?" },
      { by: 'a', say: "If we all do it, it takes ten minutes." },
      { by: 'c', say: "If we all do it, nobody does anything and we chat for an hour." },
      { by: 'd', say: "That sounds better, honestly." },
      { beat: 'They chat for an hour. The bathroom is about a third clean.' },
      { by: 'a', say: "Well. Progress." },
      { by: 'b', dr: "A third of a clean bathroom and the best gossip of the week. I'd call that a successful afternoon." },
    ] },
  ],
};
