// ══════════════════════════════════════════════════════════════════════
// bb/story/lines/hohweek2.js — more of the Head of Household's week
// ══════════════════════════════════════════════════════════════════════
//
// The pools in hohweek.js air nearly every week (a plan, a fishing trip, a verdict), so three
// versions ran out inside a month. These widen them; the roles are the same:
// {a} the HOH, {b} who they talk to, {c} the target, {d} the other nominee.

export default {
  'talk.hohweek.plan.pawn': [
    { id: 'hw.pp4', room: 'hoh-room', turns: [
      { beat: 'HOH room. {a} has the blinds down and is talking low.' },
      { by: 'a', say: "{c} goes up. I've known that since the second I won." },
      { by: 'b', say: "Everybody knows that. Who's the other one?" },
      { by: 'a', say: "{d}. {d} gets along with everybody, so nobody votes {d} out." },
      { by: 'b', say: "Does {d} know yet?" },
      { by: 'a', say: "Not yet. I'm asking tonight." },
      { by: 'b', say: "Ask nicely. Pawns remember how they were asked." },
      { by: 'a', dr: "{c} is the one I'm afraid of. {d} is just the safest name I can put beside {c} without anybody thinking I've changed targets." },
    ] },
    { id: 'hw.pp5', room: 'hoh-room', turns: [
      { beat: 'HOH room. {b} is lying on the floor. {a} is sitting on the bed with the HOH letter on {a}\'s knees.' },
      { by: 'b', say: "Have you decided?" },
      { by: 'a', say: "{c}, and {d} as a pawn." },
      { by: 'b', say: "Why not two real targets?" },
      { by: 'a', say: "Because if {c} wins the veto, I want the person left on the block to be somebody I don't mind keeping." },
      { by: 'b', say: "And then you put up a replacement." },
      { by: 'a', say: "Exactly. The pawn gives me a second chance." },
      { by: 'a', dr: "{d} is my insurance. If {c} gets off the block, I still get to choose who goes up next, and {d} walks away safe." },
    ] },
  ],
  'talk.hohweek.plan.two': [
    { id: 'hw.p24', room: 'hoh-room', turns: [
      { beat: 'HOH room. {a} is already in pyjamas at four in the afternoon. {b} sits on the end of the bed.' },
      { by: 'b', say: "Talk me through it." },
      { by: 'a', say: "{c} and {d}. Both of them, for real." },
      { by: 'b', say: "No pawn at all?" },
      { by: 'a', say: "I don't trust anybody enough to put them in danger for me, and I don't want to lie to anybody either." },
      { by: 'b', say: "So whoever stays hates you." },
      { by: 'a', say: "Whoever stays hated me already." },
      { by: 'a', dr: "{c} and {d} both want me gone. I'd rather they find that out from the block than from me pretending to be their friend." },
    ] },
    { id: 'hw.p25', room: 'hoh-room', turns: [
      { beat: 'HOH room. {b} is eating cereal out of the box. {a} is counting on {a}\'s fingers.' },
      { by: 'b', say: "What are you counting?" },
      { by: 'a', say: "Votes. If {c} and {d} are both up, how many people would keep each of them." },
      { by: 'b', say: "And?" },
      { by: 'a', say: "Not enough, either way. That's why they're both going up." },
      { by: 'b', say: "You're not worried about the veto?" },
      { by: 'a', say: "If one of them wins it, the other one is still there." },
      { by: 'b', dr: "{a} isn't gambling on a pawn this week. Two real targets means the week works whichever one walks out the door." },
    ] },
  ],
  'talk.hohweek.plan.pair': [
    { id: 'hw.pa4', room: 'hoh-room', turns: [
      { beat: 'HOH room. {a} has pulled {b} in and shut the door with a foot.' },
      { by: 'a', say: "Have you noticed {c} and {d} never vote against each other?" },
      { by: 'b', say: "I've noticed they never leave each other's side." },
      { by: 'a', say: "Same thing. They're a two-person alliance, and nobody's saying it." },
      { by: 'b', say: "So you put them both up." },
      { by: 'a', say: "Both up. One of them goes, and the other one has nobody." },
      { by: 'b', say: "That's going to be ugly." },
      { by: 'a', dr: "A pair is twice as hard to get rid of as one person. Put them on the block together and I only need the house to agree on one of them." },
    ] },
    { id: 'hw.pa5', room: 'hoh-room', turns: [
      { beat: 'HOH room. {b} is sitting on the stairs to the bathroom. {a} is pacing.' },
      { by: 'b', say: "You keep looking at the door." },
      { by: 'a', say: "Because {c} and {d} are going to come up here together. They always do." },
      { by: 'b', say: "And you're putting them up together." },
      { by: 'a', say: "Neither of them can campaign for the other. They'll both be too busy saving themselves." },
      { by: 'b', say: "And whoever's left?" },
      { by: 'a', say: "Is on their own for the first time all game." },
      { by: 'b', dr: "{a} could have picked one of them. {a} picked both, so the one who stays has lost their only real friend. That's cold, and it's smart." },
    ] },
  ],
  'talk.hohweek.plan.quiet': [
    { id: 'hw.qu4', room: 'hoh-room', turns: [
      { beat: 'HOH room. {b} is reading out names from a list {a} wrote. {a} says no to every one of them.' },
      { by: 'b', say: "What about the big players?" },
      { by: 'a', say: "Not this week. Every one of them has friends who'd come after me." },
      { by: 'b', say: "So who's left?" },
      { by: 'a', say: "{c} and {d}. Nobody's going to start a war over them." },
      { by: 'b', say: "Isn't that a bit of a waste?" },
      { by: 'a', say: "Maybe. But it's a safe waste." },
      { by: 'a', dr: "I'd love to make a big move. I'd also love to still be here in a month. This week I'm choosing the second one." },
    ] },
  ],
  'talk.hohweek.pawn.agree': [
    { id: 'hw.wa4', room: 'hoh-room', turns: [
      { beat: 'HOH room. {a} has made two cups of tea and hands one to {b}.' },
      { by: 'b', say: "You made me tea. This is bad, isn't it?" },
      { by: 'a', say: "It's a favour. A big one. I need you on the block next to {c}." },
      { by: 'b', say: "As a pawn." },
      { by: 'a', say: "As a pawn. You'd have my vote, and I'd be getting you votes all week." },
      { by: 'b', say: "Fine. But I'm keeping the tea." },
      { by: 'a', say: "Keep the mug too." },
      { by: 'b', dr: "I said yes because saying no to the HOH is how you end up a target next week. Being a pawn for {a} at least means {a} owes me one." },
    ] },
    { id: 'hw.wa5', room: 'hoh-room', turns: [
      { beat: 'HOH room. {b} is looking at the nomination keys on the bed while {a} explains.' },
      { by: 'a', say: "{c} is the target. You'd just be sitting there so {c} has somebody next to them." },
      { by: 'b', say: "Who else did you ask?" },
      { by: 'a', say: "Nobody. You're the only person I trust to do it." },
      { by: 'b', say: "That's either sweet or a really good line." },
      { by: 'a', say: "It's true." },
      { by: 'b', say: "Okay. I'm in. Don't make me regret it." },
      { by: 'b', dr: "I'm scared. I'm also not stupid. {a} has the power this week, and helping {a} now means I'm protected the next time {a} has it." },
    ] },
  ],
  'talk.hohweek.fish.honest': [
    { id: 'hw.fh4', room: 'hoh-room', turns: [
      { beat: 'HOH room. {b} comes up the stairs slowly, like {b} already knows.' },
      { by: 'b', say: "I'm not going to waste your time. Is it me?" },
      { by: 'a', say: "It's you." },
      { by: 'b', say: "Can I ask why?" },
      { by: 'a', say: "Because you'd do the same to me. I'm just doing it first." },
      { by: 'b', say: "That's fair. I hate that it's fair." },
      { by: 'a', say: "Win the veto and prove me wrong." },
      { by: 'b', dr: "I'm not even angry with {a}. I'm angry that {a} is right, and that I didn't win that HOH myself." },
    ] },
    { id: 'hw.fh5', room: 'hoh-room', turns: [
      { beat: 'HOH room. {b} is standing in the doorway. {a} pats the bed for {b} to sit.' },
      { by: 'b', say: "I'd rather stand. Am I going up?" },
      { by: 'a', say: "Yes. I wanted you to hear it from me, not at the ceremony." },
      { by: 'b', say: "Is there anything I can do?" },
      { by: 'a', say: "Honestly? Not with me. The veto's your best shot." },
      { by: 'b', say: "Then I'll win it." },
      { by: 'a', say: "I hope for your sake you do." },
      { by: 'a', dr: "{b} deserved the truth. Lying would only make things worse when the keys come out, and I'd rather have {b} angry than betrayed." },
    ] },
    { id: 'hw.fh6', room: 'hoh-room', turns: [
      { beat: 'HOH room. {b} has brought nothing, no snacks and no speech.' },
      { by: 'b', say: "Just tell me straight." },
      { by: 'a', say: "Straight: you're my target." },
      { by: 'b', say: "Okay. Thank you." },
      { by: 'a', say: "You're taking that well." },
      { by: 'b', say: "I'm not. I'm just not going to fall apart in your room." },
      { by: 'a', say: "That's fair." },
      { by: 'b', dr: "{a} looked me in the eye and told me. I can respect that and still want {a} out of this house more than anything." },
    ] },
  ],
  'talk.hohweek.fish.deflect': [
    { id: 'hw.fd4', room: 'hoh-room', turns: [
      { beat: 'HOH room. {b} is asking questions. {a} is answering a different question every time.' },
      { by: 'b', say: "Am I safe?" },
      { by: 'a', say: "I haven't decided anything yet." },
      { by: 'b', say: "Am I in danger?" },
      { by: 'a', say: "I haven't decided anything yet." },
      { by: 'b', say: "You're just going to keep saying that." },
      { by: 'a', say: "Because it keeps being true." },
      { by: 'b', dr: "If I were safe, {a} would have said so. {a} said nothing, three times. I can count." },
    ] },
    { id: 'hw.fd5', room: 'hoh-room', turns: [
      { beat: 'HOH room. {b} is sitting on the floor. {a} is talking about the HOH letter, the snacks, anything else.' },
      { by: 'b', say: "This is a lovely tour. Am I going up?" },
      { by: 'a', say: "I'm still listening to people." },
      { by: 'b', say: "That's a yes, isn't it?" },
      { by: 'a', say: "It's a 'still listening'." },
      { by: 'b', say: "Okay. I'll take the hint." },
      { by: 'a', say: "There's no hint." },
      { by: 'b', dr: "There was definitely a hint. When the HOH gives you a tour of the room instead of an answer, you're going up." },
    ] },
    { id: 'hw.fd6', room: 'hoh-room', turns: [
      { beat: 'HOH room. {b} is pleading. {a} is listening, arms folded.' },
      { by: 'b', say: "I'll vote with you. Every week. Whatever you want." },
      { by: 'a', say: "That's a big promise." },
      { by: 'b', say: "I mean it. So am I safe?" },
      { by: 'a', say: "I'll think about it." },
      { by: 'b', say: "That isn't a yes." },
      { by: 'a', say: "It isn't a no either." },
      { by: 'a', dr: "{b} offered me everything, and I still couldn't say yes. I didn't want to lie to {b} either, so I said nothing at all." },
    ] },
  ],
  'talk.hohweek.fish.lie': [
    { id: 'hw.fl4', room: 'hoh-room', turns: [
      { beat: 'HOH room. {b} is apologising for anything {b} might have done. {a} waves it away.' },
      { by: 'b', say: "If I did something wrong, I want to fix it." },
      { by: 'a', say: "You didn't do anything wrong. You're fine." },
      { by: 'b', say: "So I'm not going up?" },
      { by: 'a', say: "You're not going up." },
      { by: 'b', say: "Thank you. I've been sick about it all day." },
      { by: 'a', say: "Go and get some sleep." },
      { by: 'a', dr: "I told {b} what {b} needed to hear so {b} would stop working the house. {b} is my target. I'll deal with how {b} feels about it at the ceremony." },
    ] },
    { id: 'hw.fl5', room: 'hoh-room', turns: [
      { beat: 'HOH room. {a} hugs {b} at the door, longer than usual.' },
      { by: 'b', say: "So we're good?" },
      { by: 'a', say: "We're great. You're the last person I'd put up." },
      { by: 'b', say: "I knew it. People are just being paranoid." },
      { by: 'a', say: "People are always paranoid in HOH week." },
      { by: 'b', say: "Okay. Night." },
      { by: 'a', say: "Night." },
      { by: 'a', dr: "{b} is going up next to somebody harmless, and {b} is going home. Telling {b} the truth tonight would only give {b} four days to stop me." },
    ] },
    { id: 'hw.fl6', room: 'hoh-room', turns: [
      { beat: 'HOH room. {b} sits down. {a} looks relaxed. Too relaxed.' },
      { by: 'b', say: "I need to know if I should be campaigning." },
      { by: 'a', say: "Campaigning? For what? You're not even on my radar." },
      { by: 'b', say: "People say I am." },
      { by: 'a', say: "People say a lot. I'm the one with the keys, and I'm telling you you're fine." },
      { by: 'b', say: "Okay. I believe you." },
      { by: 'a', say: "Good. Go and enjoy your week." },
      { by: 'a', dr: "If {b} spends the week campaigning, {b} might find the votes to stay. So {b} isn't going to spend the week campaigning." },
    ] },
  ],
  'talk.hohweek.float.any': [
    { id: 'hw.fo4', room: 'bedroom', turns: [
      { beat: 'Bedroom. {a} is reading on a bunk while people go up and down the HOH stairs outside.' },
      { by: 'b', say: "You haven't been up there once." },
      { by: 'a', say: "No. And I'm not going to." },
      { by: 'b', say: "{c} might think you're avoiding them." },
      { by: 'a', say: "{c} won't think about me at all. That's the idea." },
      { by: 'b', say: "That's either genius or lazy." },
      { by: 'a', dr: "Every person who goes up those stairs is asking {c} for something. I'm the one person in this house who isn't. That's not lazy, that's a plan." },
    ] },
    { id: 'hw.fo5', room: 'kitchen', turns: [
      { beat: 'Kitchen. {a} is cooking for the whole house while everyone else whispers in corners.' },
      { by: 'b', say: "You're making dinner? Now?" },
      { by: 'a', say: "Somebody has to. Everybody else is busy panicking." },
      { by: 'b', say: "Aren't you worried about the nominations?" },
      { by: 'a', say: "I'm worried about the pasta. The nominations aren't my problem this week." },
      { by: 'b', say: "How can you be sure?" },
      { by: 'a', dr: "Nobody nominates the person who feeds them. I'm not here to win competitions. I'm here to still be here when the big players knock each other out." },
    ] },
    { id: 'hw.fo6', room: 'backyard', turns: [
      { beat: 'Backyard. {a} is playing catch against the wall, alone, while the house argues indoors.' },
      { by: 'b', say: "You're not inside for the drama?" },
      { by: 'a', say: "The drama's not about me. I'd like to keep it that way." },
      { by: 'b', say: "Doesn't it bother you, not being in the middle of it?" },
      { by: 'a', say: "Being in the middle of it is how people get nominated." },
      { by: 'b', say: "Fair." },
      { by: 'a', dr: "I know people think I'm not playing. I am. I'm just playing the part of the game where nobody sees you coming." },
    ] },
  ],
  'talk.hohweek.verdict.done': [
    { id: 'hw.vd4', room: 'living-room', presumes: ['vote'], turns: [
      { beat: 'Living room, the morning after. {a} is stretched out on the couch with eyes closed.' },
      { by: 'b', say: "You look like you slept for the first time in a week." },
      { by: 'a', say: "I did. {c} is gone. It worked." },
      { by: 'b', say: "Not everybody's happy about it." },
      { by: 'a', say: "Not everybody had to be. Enough people were." },
      { by: 'b', say: "And now you're just a houseguest again." },
      { by: 'a', dr: "My one job as HOH was getting {c} out of this house, and I did it. Now somebody else holds the keys, and I find out what that costs me." },
    ] },
    { id: 'hw.vd5', room: 'kitchen', presumes: ['vote'], turns: [
      { beat: 'Kitchen. {a} and {b} are doing the breakfast dishes side by side.' },
      { by: 'b', say: "Can I say it?" },
      { by: 'a', say: "Say it." },
      { by: 'b', say: "That was a really good HOH." },
      { by: 'a', say: "{c} is gone, and I'm still friends with most of the house. I'll take it." },
      { by: 'b', say: "Most?" },
      { by: 'a', dr: "{c} walked out exactly the way I planned. It doesn't make me safe next week, but nobody can say my week was wasted." },
    ] },
    { id: 'hw.vd6', room: 'backyard', presumes: ['vote'], turns: [
      { beat: 'Backyard. {a} is sitting in the hot tub, alone, until {b} climbs in.' },
      { by: 'b', say: "Celebrating?" },
      { by: 'a', say: "Quietly. {c} would have put me up the second they won anything." },
      { by: 'b', say: "And now {c} can't." },
      { by: 'a', say: "And now {c} can't." },
      { by: 'b', say: "Who's next, then?" },
      { by: 'a', dr: "I removed the person most likely to come after me. That's what you do with an HOH. Whatever happens next, I used it." },
    ] },
    { id: 'hw.vd7', room: 'bedroom', presumes: ['vote'], turns: [
      { beat: 'Bedroom. {a} is moving back into a shared room, carrying an armful of clothes.' },
      { by: 'b', say: "Back to the cheap seats." },
      { by: 'a', say: "Back to the cheap seats. Worth it." },
      { by: 'b', say: "Because {c}'s gone?" },
      { by: 'a', say: "Because {c}'s gone, and it was my call." },
      { by: 'b', say: "Do you feel bad at all?" },
      { by: 'a', dr: "I don't feel bad. I made a plan, I stuck to it, and {c} is gone. Most HOHs don't get the week they wanted. I did." },
    ] },
  ],
  'talk.hohweek.verdict.missed': [
    { id: 'hw.vm4', room: 'living-room', presumes: ['vote'], turns: [
      { beat: 'Living room. {a} is sitting with a cushion over {a}\'s face.' },
      { by: 'b', say: "Are you hiding?" },
      { by: 'a', say: "From {c}. Yes." },
      { by: 'b', say: "You can't hide from {c} forever." },
      { by: 'a', say: "I know. I tried to get rid of {c}, it didn't work, and now we live together." },
      { by: 'b', say: "Awkward." },
      { by: 'a', dr: "The worst result for an HOH is putting somebody up and watching them stay. {c} knows I came for them, and {c} is still here." },
    ] },
    { id: 'hw.vm5', room: 'kitchen', presumes: ['vote'], turns: [
      { beat: 'Kitchen. {a} is making coffee and not looking at anybody.' },
      { by: 'b', say: "You haven't said a word all morning." },
      { by: 'a', say: "What is there to say? {c} is still here, and the wrong person went home." },
      { by: 'b', say: "It happens." },
      { by: 'a', say: "It happened to me. On my week." },
      { by: 'b', say: "So you go again." },
      { by: 'a', dr: "I had one target. One. And they're standing at the counter making toast. I have to win something soon, or {c} is going to make me pay for trying." },
    ] },
    { id: 'hw.vm6', room: 'bedroom', presumes: ['vote'], turns: [
      { beat: 'Bedroom. {a} is pulling on a hoodie. {b} is sitting on the next bed.' },
      { by: 'b', say: "How bad is it?" },
      { by: 'a', say: "{c} survived. {c} knows it was me. That's how bad." },
      { by: 'b', say: "Maybe {c} will let it go." },
      { by: 'a', say: "Would you?" },
      { by: 'b', say: "...No." },
      { by: 'a', dr: "I made my move and it missed. Now I've got an enemy who knows exactly what I'm willing to do, and no power to stop them." },
    ] },
  ],
};
