// ══════════════════════════════════════════════════════════════════════
// bb/story/lines/hohweek.js — the Head of Household's week, played on screen
// ══════════════════════════════════════════════════════════════════════
//
// The user, 2026-10-07: "they don't strategise enough about nominations: one-on-ones with the
// HOH are important for strategy and we barely get any... we never really feel what their plan
// is. The viewer needs to feel and see the actual strategy, bad or good, and every way of
// playing, even floating", and "did X have a good HOH or a bad one, did they get the target
// out, how do we know?"
//
// The plan is the engine's (bb/strategy.js picks the shape, bb/week.js negotiates the pawn).
// These scenes are that plan being made, sold, fished for and dodged, and then judged.
//
// Roles: {a} the HOH. {b} who they are talking to. {c} the real target. {d} the other
// nominee (the pawn, the partner, the ally). {e} the backdoor target.

export default {
  // ════ the plan, said out loud to the HOH's closest person ════
  // target and pawn: the classic week
  'talk.hohweek.plan.pawn': [
    { id: 'hw.pp1', room: 'hoh-room', turns: [
      { beat: 'HOH room, door shut. {a} is sitting on the end of the bed. {b} is leaning on the dresser.' },
      { by: 'b', say: "So. Who's going up?" },
      { by: 'a', say: "{c}. That's not even a question for me." },
      { by: 'b', say: "And next to {c}?" },
      { by: 'a', say: "{d}, as a pawn. {d} isn't the one I want gone." },
      { by: 'b', say: "Pawns go home in this game. You know that, right?" },
      { by: 'a', say: "Only if the veto goes wrong. If it goes right, {c} leaves and {d} never even packs a bag." },
      { by: 'a', dr: "I need {c} out this week. Putting {d} up next to them is a risk, but somebody has to sit in that other chair, and {d} is the one the house would never vote out." },
    ] },
    { id: 'hw.pp2', room: 'hoh-room', turns: [
      { beat: 'HOH room. {a} has the nomination keys on the bed and keeps moving them around like chess pieces.' },
      { by: 'b', say: "You're doing the thing with the keys again." },
      { by: 'a', say: "It helps me think. Okay. {c} is the target. We agree on that?" },
      { by: 'b', say: "We've agreed on that since you won." },
      { by: 'a', say: "Then I need somebody safe to sit next to {c}. Somebody the house won't vote out if it comes to it." },
      { by: 'b', say: "{d}?" },
      { by: 'a', say: "{d}. Nobody would ever pick {d} over {c}." },
      { by: 'b', dr: "I trust {a}'s plan. I just don't love that it depends on a whole house behaving the way {a} expects it to." },
    ] },
    { id: 'hw.pp3', room: 'hoh-room', turns: [
      { beat: 'HOH room, late. {b} is lying across the bed. {a} is pacing.' },
      { by: 'a', say: "I keep thinking about who I'd regret putting up." },
      { by: 'b', say: "And?" },
      { by: 'a', say: "Not {c}. I won't lose a second of sleep over {c}." },
      { by: 'b', say: "Then it's settled." },
      { by: 'a', say: "It's half settled. The other chair is the hard part. I'm going to ask {d} to sit in it." },
      { by: 'b', say: "And if {d} says no?" },
      { by: 'a', dr: "This is the part nobody tells you about winning HOH. You don't just pick an enemy. You pick a friend to put in danger too." },
    ] },
  ],
  // the backdoor: the real target is not on the block until the veto
  'talk.hohweek.plan.backdoor': [
    { id: 'hw.pb1', room: 'hoh-room', turns: [
      { beat: 'HOH room, door locked. {a} checks the hallway before saying a word.' },
      { by: 'a', say: "I'm not putting {e} up at the ceremony." },
      { by: 'b', say: "What? I thought {e} was the whole point." },
      { by: 'a', say: "{e} is the whole point. That's why {e} doesn't go up first. On the block, {e} gets to play for the veto." },
      { by: 'b', say: "So you put up two people who aren't the target..." },
      { by: 'a', say: "{c} and {d}. One of them comes down with the veto, and {e} goes up in their place. No veto left to save {e}." },
      { by: 'b', say: "That only works if somebody uses the veto." },
      { by: 'a', dr: "A backdoor is the cleanest move in this game, and the riskiest. If {e} works it out before the veto, I'm the one in trouble next." },
    ] },
    { id: 'hw.pb2', room: 'hoh-room', turns: [
      { beat: 'HOH room. {a} and {b} are whispering under the duvet so the microphones barely catch it.' },
      { by: 'b', say: "Say it again, slower." },
      { by: 'a', say: "{c} and {d} go up. Neither of them is the real target. The veto gets used, and {e} goes up as the replacement." },
      { by: 'b', say: "And {e} doesn't see it coming." },
      { by: 'a', say: "{e} can't see it coming. That's the only way it works." },
      { by: 'b', say: "What do we tell {c} and {d}?" },
      { by: 'a', say: "That they're safe. Because they are. They just can't know why." },
      { by: 'b', dr: "{a} has never looked this calm. It's either a genius move or the thing that gets us both sent home." },
    ] },
    { id: 'hw.pb3', room: 'hoh-room', turns: [
      { beat: "HOH room. {b} is eating the HOH snacks. {a} has not touched them." },
      { by: 'b', say: "You look like you've got a secret." },
      { by: 'a', say: "I do. {e} thinks I like {e}." },
      { by: 'b', say: "Don't you?" },
      { by: 'a', say: "I like {e} enough to let {e} relax until the veto meeting. Then {e} goes up, and there's nothing left to win." },
      { by: 'b', say: "That's cold." },
      { by: 'a', say: "It's the only way to get {e} out. {e} wins too much." },
      { by: 'a', dr: "If I put {e} up at the ceremony, {e} wins the veto. I've watched {e} win. So {e} waits for the replacement chair." },
    ] },
  ],
  // two real targets: no pawn, nobody lied to
  'talk.hohweek.plan.two': [
    { id: 'hw.p21', room: 'hoh-room', turns: [
      { beat: 'HOH room. {a} sits {b} down on the bed like it is a job interview.' },
      { by: 'a', say: "I'm not doing a pawn this week." },
      { by: 'b', say: "Two real targets?" },
      { by: 'a', say: "{c} and {d}. I'd be happy with either of them walking out of that door." },
      { by: 'b', say: "That's going to make you two enemies at once." },
      { by: 'a', say: "They're already my enemies. At least this way, whoever survives knows exactly where I stand." },
      { by: 'b', say: "Brave." },
      { by: 'a', dr: "Putting up a pawn means lying to a friend. I'd rather put up two people who already don't like me and sleep at night." },
    ] },
    { id: 'hw.p22', room: 'hoh-room', turns: [
      { beat: "HOH room. {b} is reading the HOH letter again. {a} takes it away." },
      { by: 'a', say: "Focus. I need to say this out loud to somebody." },
      { by: 'b', say: "Go on." },
      { by: 'a', say: "{c} and {d} are running half the votes in this house. I'm putting both of them up." },
      { by: 'b', say: "Both? Not one and a pawn?" },
      { by: 'a', say: "With a pawn, one of them is still out there next week, angry, with all their votes. With both of them up, one is gone for sure." },
      { by: 'b', say: "And the other one comes after you." },
      { by: 'b', dr: "{a} is playing this like the only week {a} will ever have power. Honestly, it might be." },
    ] },
    { id: 'hw.p23', room: 'hoh-room', turns: [
      { beat: 'HOH room. {a} is lying on the floor staring at the ceiling. {b} is sitting next to {a}.' },
      { by: 'b', say: "You've been quiet for ten minutes." },
      { by: 'a', say: "I was trying to find a pawn. There isn't one. Everybody I'd ask is somebody I need." },
      { by: 'b', say: "So?" },
      { by: 'a', say: "So {c} and {d} both go up, and they both mean it." },
      { by: 'b', say: "That's going to be a loud week." },
      { by: 'a', say: "Let it be loud. At least nobody can say I lied to them." },
      { by: 'a', dr: "I don't have a friend I'm willing to risk, so I'm not risking one. {c} and {d} both earned their spot on that block." },
    ] },
  ],
  // splitting a pair: the target beside the one person who would fight for them
  'talk.hohweek.plan.pair': [
    { id: 'hw.pa1', room: 'hoh-room', turns: [
      { beat: 'HOH room. {a} has drawn something on the back of the HOH letter: two names, a line between them.' },
      { by: 'b', say: "What's that?" },
      { by: 'a', say: "{c} and {d}. They're a pair, whatever they say in public." },
      { by: 'b', say: "And you're putting them both up." },
      { by: 'a', say: "Together. Neither one can pull the other off, and they can't campaign for each other." },
      { by: 'b', say: "One of them goes home whatever happens." },
      { by: 'a', say: "That's the point. Whoever's left is alone." },
      { by: 'a', dr: "{c} and {d} have been protecting each other all game. Put them side by side and one of them loses the only person they trust." },
    ] },
    { id: 'hw.pa2', room: 'hoh-room', turns: [
      { beat: 'HOH room, door shut. {b} is sitting cross-legged on the bed.' },
      { by: 'b', say: "Everybody thinks you're putting up {c} and a pawn." },
      { by: 'a', say: "Everybody's wrong. {c} goes up next to {d}." },
      { by: 'b', say: "{d}? I thought you didn't mind {d}." },
      { by: 'a', say: "I don't. But {d} would burn the house down to save {c}. If {d} is on the block too, {d} has to save {d} first." },
      { by: 'b', say: "That's really mean. And really smart." },
      { by: 'a', say: "Mostly smart." },
      { by: 'b', dr: "{a} isn't just picking a target. {a} is breaking up the strongest pair in the house, and they're going to hate {a} for it." },
    ] },
    { id: 'hw.pa3', room: 'hoh-room', turns: [
      { beat: 'HOH room. {a} is watching the house on the HOH camera. {c} and {d} are in the kitchen, heads together.' },
      { by: 'a', say: "Look at them. Every single day." },
      { by: 'b', say: "You think they've got a deal?" },
      { by: 'a', say: "I know they do. And I'm not going to be the person sitting next to them at the end." },
      { by: 'b', say: "So who goes up?" },
      { by: 'a', say: "Both. Let them fight it out on the block." },
      { by: 'b', say: "They'll know it was about them as a pair." },
      { by: 'a', dr: "If they get to the end together, one of them wins. I'd rather split them now, while I still have the key." },
    ] },
  ],
  // the target beside their closest ally, who is not a pawn and was promised nothing
  'talk.hohweek.plan.ally': [
    { id: 'hw.al1', room: 'hoh-room', turns: [
      { beat: 'HOH room. {a} is walking {b} through it on the bed, using two pillows as the nominees.' },
      { by: 'a', say: "This one's {c}. The target." },
      { by: 'b', say: "And the other pillow?" },
      { by: 'a', say: "{d}. {c}'s best friend in here." },
      { by: 'b', say: "{d} isn't a pawn, then. You didn't ask {d}." },
      { by: 'a', say: "No. I want {d} so busy saving {d} that nobody's out there fighting for {c}." },
      { by: 'b', say: "Brutal." },
      { by: 'a', dr: "{c}'s best weapon is {d}. Put {d} on the block too, and {c} has nobody left to campaign for them." },
    ] },
    { id: 'hw.al2', room: 'hoh-room', turns: [
      { beat: 'HOH room. {b} has just asked who the second nominee is. {a} is taking a long time to answer.' },
      { by: 'a', say: "{d}." },
      { by: 'b', say: "{d}? What did {d} do to you?" },
      { by: 'a', say: "Nothing. {d} is {c}'s closest person in this house. That's all." },
      { by: 'b', say: "So {d} is collateral." },
      { by: 'a', say: "{d} is the one who'd work hardest to keep {c} here. I'm just giving {d} something else to worry about." },
      { by: 'b', say: "{d} isn't going to see it that way." },
      { by: 'b', dr: "{a} is taking out {c} by tying up {c}'s best friend. It's smart. I wouldn't want to be on the other end of it." },
    ] },
    { id: 'hw.al3', room: 'hoh-room', turns: [
      { beat: 'HOH room. {a} is writing two names on the HOH notepad, then turning it over.' },
      { by: 'b', say: "Can I see?" },
      { by: 'a', say: "{c}, which you knew. And {d}." },
      { by: 'b', say: "Why {d}? I don't get it." },
      { by: 'a', say: "Because {d} and {c} are a team. If only {c} goes up, {d} spends the whole week getting votes for {c}." },
      { by: 'b', say: "And with both of them up..." },
      { by: 'a', say: "{d} spends the whole week getting votes for {d}." },
      { by: 'a', dr: "I'm not trying to evict {d}. I'm trying to make sure {c} has no one left in their corner." },
    ] },
  ],
  // two easy names: the quiet week, no capital spent
  'talk.hohweek.plan.quiet': [
    { id: 'hw.qu1', room: 'hoh-room', turns: [
      { beat: 'HOH room. {b} is waiting for the big plan. {a} shrugs.' },
      { by: 'a', say: "{c} and {d}." },
      { by: 'b', say: "That's it? Nobody big?" },
      { by: 'a', say: "Nobody big. The big players can fight each other. I'm not starting a war with my one week of power." },
      { by: 'b', say: "People will say you wasted it." },
      { by: 'a', say: "People will say a lot of things. They won't come after me for this." },
      { by: 'b', say: "Fair." },
      { by: 'a', dr: "I could go after a big name and have half the house on my back. Or I can nominate two people nobody will fight for, and keep my head down. I'm keeping my head down." },
    ] },
    { id: 'hw.qu2', room: 'hoh-room', turns: [
      { beat: 'HOH room. {a} is lying on the bed, very relaxed for somebody holding the keys.' },
      { by: 'b', say: "You don't look stressed." },
      { by: 'a', say: "Because I'm doing the easy thing. {c} and {d}. The whole house would nominate them if they had the keys." },
      { by: 'b', say: "Not exactly a big move." },
      { by: 'a', say: "Big moves make big enemies. I'd rather be here at the end." },
      { by: 'b', say: "And the real threats stay in the house." },
      { by: 'a', say: "They're the real threats to everybody. Somebody else can deal with them." },
      { by: 'b', dr: "{a} played it safe. Honestly, I'd have gone bigger. But nobody's going to be angry with {a} after the eviction, and that counts for a lot." },
    ] },
    { id: 'hw.qu3', room: 'hoh-room', turns: [
      { beat: 'HOH room. {a} is talking to {b} while folding the HOH robe over and over.' },
      { by: 'a', say: "I asked around. Everybody says the same two names." },
      { by: 'b', say: "{c} and {d}." },
      { by: 'a', say: "{c} and {d}. If that's what the house wants, that's who goes up." },
      { by: 'b', say: "What do you want?" },
      { by: 'a', say: "Me? I want to not be the next target. This is how." },
      { by: 'b', say: "Following the house." },
      { by: 'a', dr: "It's not exciting television. But nobody can be angry with me for doing what everyone asked, and I need that more than a big move right now." },
    ] },
  ],

  // ════ the HOH asks somebody to sit in the pawn's chair ════
  'talk.hohweek.pawn.agree': [
    { id: 'hw.wa1', room: 'hoh-room', turns: [
      { beat: 'HOH room. {a} asks {b} to come up, and closes the door.' },
      { by: 'a', say: "I need to ask you something huge, and you can say no." },
      { by: 'b', say: "You want me to go up." },
      { by: 'a', say: "Next to {c}. You're not the target. You're the safety net." },
      { by: 'b', say: "And if something goes wrong?" },
      { by: 'a', say: "Then I fight for you like it was me sitting there. I promise." },
      { by: 'b', say: "...Okay. I'll do it." },
      { by: 'b', dr: "I said yes because I trust {a}, and because if this works, {a} owes me. I just really hope I'm right to trust {a}." },
    ] },
    { id: 'hw.wa2', room: 'hoh-room', turns: [
      { beat: 'HOH room. {b} sits down before {a} even asks.' },
      { by: 'b', say: "I know what this is. You need a pawn." },
      { by: 'a', say: "I need somebody I trust up there next to {c}. Somebody the house won't vote out." },
      { by: 'b', say: "Then I'm your somebody. Just make sure {c} is the one who goes." },
      { by: 'a', say: "That's the plan." },
      { by: 'b', say: "And next time you win, I'm not going up." },
      { by: 'a', say: "Deal." },
      { by: 'b', dr: "Going up as a pawn is scary. But it means {a} owes me, and in this house that's worth a lot." },
    ] },
    { id: 'hw.wa3', room: 'hoh-room', turns: [
      { beat: 'HOH room. {a} is sitting very close to {b}, talking quietly.' },
      { by: 'a', say: "You'd be a pawn. Just a pawn. {c} is the one going home." },
      { by: 'b', say: "That's what every HOH says to every pawn." },
      { by: 'a', say: "I mean it." },
      { by: 'b', say: "I know you mean it now. I'm worried about eviction night." },
      { by: 'a', say: "So is that a no?" },
      { by: 'b', say: "It's a yes. But if I go home, I'm never forgiving you." },
      { by: 'b', dr: "I didn't really have a choice. If I'd said no, I think {a} would have put me up anyway, just without the promise." },
    ] },
  ],
  'talk.hohweek.pawn.refuse': [
    { id: 'hw.wf1', room: 'hoh-room', turns: [
      { beat: 'HOH room. {b} stands up before {a} has finished the sentence.' },
      { by: 'b', say: "No. Absolutely not." },
      { by: 'a', say: "You haven't heard the plan." },
      { by: 'b', say: "I've heard enough. Pawns go home. I'm not sitting in that chair for anybody." },
      { by: 'a', say: "Even for me?" },
      { by: 'b', say: "Especially for you. You're the one with the key." },
      { beat: '{b} leaves. {a} stares at the door for a long time.' },
      { by: 'a', dr: "{b} said no. So now I find somebody else to put up next to {c}, and I've learned exactly how much {b} trusts me." },
    ] },
    { id: 'hw.wf2', room: 'hoh-room', turns: [
      { beat: 'HOH room. {a} is asking. {b} is shaking their head the whole time.' },
      { by: 'b', say: "If you put me up, I won't think of it as a pawn. I'll think of it as you nominating me." },
      { by: 'a', say: "That's not fair." },
      { by: 'b', say: "Neither is the block." },
      { by: 'a', say: "{c} is the target. You'd be completely safe." },
      { by: 'b', say: "Then put somebody else up who's completely safe." },
      { by: 'a', say: "Okay. I heard you." },
      { by: 'a', dr: "I asked nicely, and {b} said no. I'll remember that the next time {b} needs something from me." },
    ] },
    { id: 'hw.wf3', room: 'hoh-room', turns: [
      { beat: 'HOH room. {b} laughs when {a} asks, then sees {a} is serious.' },
      { by: 'b', say: "Wait. You're actually asking me?" },
      { by: 'a', say: "You're the one person the house would never vote out over {c}." },
      { by: 'b', say: "That's very flattering, and the answer is no." },
      { by: 'a', say: "Why?" },
      { by: 'b', say: "Because pawns go home in this game, and I'm not finding out what that feels like." },
      { by: 'a', say: "Fine." },
      { by: 'b', dr: "{a} wasn't happy with me. But a pawn has to win the vote to stay, and I'm not betting my whole game on {a}'s promise." },
    ] },
  ],

  // ════ the target climbs the stairs to find out where they stand ════
  'talk.hohweek.fish.honest': [
    { id: 'hw.fh1', room: 'hoh-room', turns: [
      { beat: 'HOH room. {b} knocks, comes in, and does not sit down.' },
      { by: 'b', say: "Just tell me. Am I going up?" },
      { by: 'a', say: "...Yes. I'm not going to lie to you." },
      { by: 'b', say: "Wow. Okay. Thank you for saying it to my face, I guess." },
      { by: 'a', say: "You'd have found out at the ceremony anyway. You deserved to hear it from me." },
      { by: 'b', say: "Is there anything I can say?" },
      { by: 'a', say: "Win the veto." },
      { by: 'b', dr: "At least {a} was honest. It doesn't make it hurt less. It does make me want to win that veto more than anything." },
    ] },
    { id: 'hw.fh2', room: 'hoh-room', turns: [
      { beat: 'HOH room. {b} sits on the edge of the bed, arms folded.' },
      { by: 'b', say: "People are saying I'm your target." },
      { by: 'a', say: "People are right." },
      { by: 'b', say: "Can I at least know why?" },
      { by: 'a', say: "Because you're good at this game, and you're not playing it with me." },
      { by: 'b', say: "That doesn't feel like a compliment." },
      { by: 'a', say: "It's the only kind I've got right now." },
      { by: 'a', dr: "I'd rather {b} hate me for being honest than find out I lied and hate me more. I might be facing {b} on the jury one day." },
    ] },
    { id: 'hw.fh3', room: 'hoh-room', turns: [
      { beat: 'HOH room. {b} has come up with a speech ready. {a} stops it before it starts.' },
      { by: 'a', say: "Before you say anything: you're going up." },
      { by: 'b', say: "I haven't even made my case." },
      { by: 'a', say: "I know. I don't want you wasting it on me. Save it for the house." },
      { by: 'b', say: "That's... weirdly kind." },
      { by: 'a', say: "It's not personal. You're just the biggest threat to me right now." },
      { by: 'b', say: "Okay. Then I'll see you at the veto." },
      { by: 'b', dr: "I walked up those stairs to beg, and {a} told me the truth before I could start. I'm angry, but I respect it. Now I need the veto." },
    ] },
  ],
  'talk.hohweek.fish.deflect': [
    { id: 'hw.fd1', room: 'hoh-room', turns: [
      { beat: 'HOH room. {b} has come up "just to see the room". It has been twenty minutes.' },
      { by: 'b', say: "So... have you decided?" },
      { by: 'a', say: "I'm still thinking about it. Honestly." },
      { by: 'b', say: "Am I in the conversation?" },
      { by: 'a', say: "Everybody's in the conversation. That's what this week is." },
      { by: 'b', say: "That's not a no." },
      { by: 'a', say: "It's not a yes either." },
      { by: 'b', dr: "{a} didn't answer the question. In this house, that is the answer. I think I'm going up." },
    ] },
    { id: 'hw.fd2', room: 'hoh-room', turns: [
      { beat: 'HOH room. {b} is sitting where the last visitor sat, asking the same question.' },
      { by: 'b', say: "I just want to know where I stand." },
      { by: 'a', say: "You stand right here, in my room, eating my snacks." },
      { by: 'b', say: "I'm serious." },
      { by: 'a', say: "So am I. I haven't made up my mind, and I'm not telling anybody until I have." },
      { by: 'b', say: "Okay." },
      { by: 'b', say: "Thanks for the snacks, I guess." },
      { by: 'a', dr: "I couldn't tell {b} the truth, and I didn't want to lie. So I made a joke, and I think {b} knew exactly what that meant." },
    ] },
    { id: 'hw.fd3', room: 'hoh-room', turns: [
      { beat: 'HOH room. {b} is pitching. {a} is nodding and saying nothing.' },
      { by: 'b', say: "I'd be loyal to you. I mean it. Whatever you need." },
      { by: 'a', say: "I appreciate that." },
      { by: 'b', say: "So you won't put me up?" },
      { by: 'a', say: "I'm going to think about everything people have said to me today." },
      { by: 'b', say: "That sounds like a speech you've given five times already." },
      { by: 'a', say: "Six, actually." },
      { by: 'b', dr: "I offered {a} everything, and got nothing back. Not a promise, not a hint. That scares me more than a straight no." },
    ] },
  ],
  'talk.hohweek.fish.lie': [
    { id: 'hw.fl1', room: 'hoh-room', turns: [
      { beat: 'HOH room. {b} comes in nervous. {a} is all smiles.' },
      { by: 'b', say: "Please tell me I'm safe this week." },
      { by: 'a', say: "You're safe. Of course you're safe. Why would you even think that?" },
      { by: 'b', say: "People keep looking at me." },
      { by: 'a', say: "People look at everyone. Go and relax. Enjoy your week." },
      { by: 'b', say: "Okay. Thank you. Really." },
      { beat: '{b} leaves, lighter. {a} stops smiling the second the door closes.' },
      { by: 'a', dr: "{b} is going up. If I'd told the truth, {b} would have spent four days campaigning against me. Lying buys me those four days." },
    ] },
    { id: 'hw.fl2', room: 'hoh-room', turns: [
      { beat: 'HOH room. {b} has brought {a} a coffee.' },
      { by: 'b', say: "We're good, right? You and me?" },
      { by: 'a', say: "We're more than good. I'd never put you up." },
      { by: 'b', say: "Promise?" },
      { by: 'a', say: "Promise." },
      { by: 'b', say: "Okay. I needed to hear that." },
      { by: 'a', dr: "I just looked {b} in the eye and lied. It's the worst part of this game, and I'd do it again, because {b} is my target and {b} can't know that yet." },
    ] },
    { id: 'hw.fl3', room: 'hoh-room', turns: [
      { beat: 'HOH room. {b} is sitting on the bed. {a} is sitting next to {b}, very friendly.' },
      { by: 'b', say: "I heard my name come up." },
      { by: 'a', say: "From who? Not from me." },
      { by: 'b', say: "So I'm not a target?" },
      { by: 'a', say: "You're not even on my list. I've got bigger problems than you." },
      { by: 'b', say: "That's a relief." },
      { by: 'a', say: "Go and enjoy the hot tub. Seriously." },
      { by: 'a', dr: "{b} is exactly who I'm coming for. A target who feels safe doesn't make deals behind my back, and I need {b} calm until the keys come out." },
    ] },
  ],

  // ════ somebody playing the floating game while the house queues on the stairs ════
  'talk.hohweek.float.any': [
    { id: 'hw.fo1', room: 'kitchen', turns: [
      { beat: 'Kitchen. Everybody else is finding a reason to go upstairs. {a} is making toast.' },
      { by: 'b', say: "You're not going up to see {c}?" },
      { by: 'a', say: "Why would I? Everybody's up there begging. I'm down here being nobody's problem." },
      { by: 'b', say: "That's a strategy?" },
      { by: 'a', say: "That's my whole strategy." },
      { by: 'b', say: "And if {c} puts you up anyway?" },
      { by: 'a', dr: "The HOH remembers who came up those stairs. Every visitor is somebody asking for something. I'd rather {c} forgot I exist this week." },
    ] },
    { id: 'hw.fo2', room: 'backyard', turns: [
      { beat: 'Backyard. {a} is lying on a lounger with eyes shut, while the house queues on the HOH stairs.' },
      { by: 'b', say: "Aren't you worried?" },
      { by: 'a', say: "About what? I'm not in anybody's way. I haven't won anything. I haven't lied to anybody." },
      { by: 'b', say: "That won't keep you safe forever." },
      { by: 'a', say: "It doesn't have to be forever. It has to be this week." },
      { by: 'b', say: "And next week?" },
      { by: 'a', dr: "People call it floating like it's an insult. I call it still being here while the people who played hard pack their bags." },
    ] },
    { id: 'hw.fo3', room: 'living-room', turns: [
      { beat: 'Living room. {a} is folding laundry while the house argues about the HOH.' },
      { by: 'b', say: "What do you think {c} is going to do?" },
      { by: 'a', say: "Honestly? No idea. I'm just glad it isn't my decision." },
      { by: 'b', say: "You're not even a little curious?" },
      { by: 'a', say: "Curious, yes. Involved, no." },
      { by: 'b', say: "Must be nice." },
      { by: 'a', dr: "This week I agree with whoever is talking to me, help with the dishes, and stay off every list. It's not exciting, but it keeps me here." },
    ] },
  ],

  // ════ the morning after: did the HOH's week work? ════
  // the target walked out the door
  'talk.hohweek.verdict.done': [
    { id: 'hw.vd1', room: 'kitchen', presumes: ['vote'], turns: [
      { beat: 'Kitchen, the morning after the eviction. {a} has carried the HOH snacks downstairs.' },
      { by: 'b', say: "You did it. {c} is gone." },
      { by: 'a', say: "I keep waiting to feel bad about it." },
      { by: 'b', say: "Do you?" },
      { by: 'a', say: "No. I feel like I can breathe." },
      { by: 'b', say: "Now you've got no power, though." },
      { by: 'a', dr: "I said {c} was leaving this week, and {c} left. That was the whole plan, and it worked. Whatever happens to me next, I got that done." },
    ] },
    { id: 'hw.vd2', room: 'backyard', presumes: ['vote'], turns: [
      { beat: 'Backyard. {a} is lying on the grass, smiling at nothing.' },
      { by: 'b', say: "Somebody looks pleased with themselves." },
      { by: 'a', say: "Somebody had a perfect week." },
      { by: 'b', say: "{c} said some things on the way out." },
      { by: 'a', say: "{c} was always going to. It doesn't change anything." },
      { by: 'b', say: "It might change the jury." },
      { by: 'a', dr: "I named my target, and my target is gone. Nothing went sideways. That's what a good HOH looks like." },
    ] },
    { id: 'hw.vd3', room: 'hoh-room', presumes: ['vote'], turns: [
      { beat: 'HOH room, the last morning before the next competition. {a} is taking the photos off the wall.' },
      { by: 'b', say: "Sad to give it up?" },
      { by: 'a', say: "A bit. Not sad about the week, though." },
      { by: 'b', say: "{c} really didn't see it coming at the end." },
      { by: 'a', say: "{c} saw it. {c} just couldn't stop it." },
      { by: 'b', say: "So, good HOH?" },
      { by: 'a', dr: "I came in with one name, and that name is gone. Some HOHs spend the whole week changing their minds. I didn't, and it paid off." },
    ] },
  ],
  // the target survived: the veto, or the house voted the other way
  'talk.hohweek.verdict.missed': [
    { id: 'hw.vm1', room: 'kitchen', presumes: ['vote'], turns: [
      { beat: 'Kitchen, the morning after the eviction. {a} has not touched breakfast. Laughing carries in from the living room.' },
      { by: 'b', say: "You know whose laugh that is." },
      { by: 'a', say: "{c}'s. Yeah. I know." },
      { by: 'b', say: "{c} is still here." },
      { by: 'a', say: "{c} is still here because the week fell apart. I had the target. I just didn't get the target out." },
      { by: 'b', say: "So what now?" },
      { by: 'a', dr: "My whole HOH was about getting {c} out, and {c} is in the next room laughing. I used my week and got nothing for it, and {c} knows I tried." },
    ] },
    { id: 'hw.vm2', room: 'bedroom', presumes: ['vote'], turns: [
      { beat: 'Bedroom. {a} is lying face down on the bed. {b} sits next to {a}.' },
      { by: 'b', say: "It wasn't your fault." },
      { by: 'a', say: "It was my week. Everything that happened in it is my fault." },
      { by: 'b', say: "You couldn't control everything." },
      { by: 'a', say: "No. And now {c} is still here, and {c} knows I'm the one who tried to send {c} home." },
      { by: 'b', say: "So you need to win the next HOH." },
      { by: 'a', dr: "I had the power and I wasted it. {c} survived my week, and the next time {c} wins anything, I'm the first name on the list." },
    ] },
    { id: 'hw.vm3', room: 'backyard', presumes: ['vote'], turns: [
      { beat: 'Backyard. {a} is pacing by the pool. {b} is trying to keep up.' },
      { by: 'a', say: "I put {c} up. I did everything right." },
      { by: 'b', say: "And {c} is still here." },
      { by: 'a', say: "And {c} is still here." },
      { by: 'b', say: "You know what that makes you, right?" },
      { by: 'a', say: "A target. Yeah. I know." },
      { by: 'a', dr: "A failed HOH is the worst thing in this game. You make an enemy, you don't get rid of them, and then you have no power left. That's my week." },
    ] },
  ],
  // the pawn went home
  'talk.hohweek.verdict.pawn': [
    { id: 'hw.vp1', room: 'bedroom', presumes: ['vote'], turns: [
      { beat: "Bedroom, the morning after. One bed has been stripped. {a} is sitting on it." },
      { by: 'b', say: "You can't sit there all day." },
      { by: 'a', say: "I promised {d}. I promised {d} was safe." },
      { by: 'b', say: "You couldn't have known the house would turn." },
      { by: 'a', say: "That's what everybody says to the HOH who sends a pawn home." },
      { by: 'b', say: "And {c} is still here." },
      { by: 'a', dr: "{d} sat in that chair because I asked, and {d} went home because the house didn't follow me. {c} is still here. That's the worst way an HOH can end." },
    ] },
    { id: 'hw.vp2', room: 'kitchen', presumes: ['vote'], turns: [
      { beat: 'Kitchen. {a} is cleaning a counter that is already clean.' },
      { by: 'b', say: "Talk to me." },
      { by: 'a', say: "The pawn went home. My pawn. The person I swore was safe." },
      { by: 'b', say: "{d} knew the risk." },
      { by: 'a', say: "{d} knew the risk because I told {d} there wasn't one." },
      { by: 'b', say: "The jury's going to hear about this." },
      { by: 'a', dr: "I trusted the house to vote the way it said it would, and it didn't. {d} paid for that, not me." },
    ] },
    { id: 'hw.vp3', room: 'backyard', presumes: ['vote'], turns: [
      { beat: 'Backyard. {a} is sitting alone. {b} brings two mugs out.' },
      { by: 'b', say: "Here. You need this." },
      { by: 'a', say: "I don't need tea. I need to go back to the ceremony and start again." },
      { by: 'b', say: "What would you change?" },
      { by: 'a', say: "Everything. I'd put up somebody who could take care of themselves." },
      { by: 'b', say: "And {c}?" },
      { by: 'a', dr: "My plan was {c} out and {d} safe. I got the exact opposite. I didn't just fail as HOH, I sent home somebody who trusted me." },
    ] },
  ],
};
