// ══════════════════════════════════════════════════════════════════════
// bb/story/lines/more-groups.js — the group pools that air most, widened
// ══════════════════════════════════════════════════════════════════════
//
// Group versions are chosen three times in four in the first fortnight, so gossip circles
// and group banter air far more often than their two-person versions did (measured
// 2026-10-06: the six gossip circles repeated inside four weeks). Added to the same keys.

export default {
  'story.target.gossip.group': [
    { id: 'gg2.1', turns: [
      { beat: '{a}, {b} and {c} are folding laundry together, which nobody has ever done voluntarily.' },
      { by: 'b', say: "Okay, so this is just laundry." },
      { by: 'a', say: "Just laundry." },
      { by: 'c', say: "Totally normal laundry." },
      { by: 'a', say: "Anyway. {target}." },
      { by: 'b', say: "I knew it wasn't laundry." },
      { by: 'a', say: "{target} asked me who I'd put up if I won HOH. Straight out. At breakfast." },
      { by: 'c', say: "Who asks that at breakfast?" },
      { by: 'b', say: "Somebody making a list." },
      { by: 'a', say: "That's what I thought." },
      { by: 'c', dr: "We folded one towel in twenty minutes. Best gossip session of the week, worst laundry." },
    ] },
    { id: 'gg2.2', turns: [
      { by: 'a', say: "Can I say something mean?" },
      { by: 'b', say: "Always." },
      { by: 'c', say: "Please." },
      { by: 'a', say: "I don't think {target} is as nice as everyone thinks." },
      { by: 'b', say: "That's not mean, that's true." },
      { by: 'c', say: "Why, what happened?" },
      { by: 'a', say: "Nothing happened. That's the thing. {target} never puts a foot wrong. Nobody's that perfect in here." },
      { by: 'c', say: "So {target}'s too nice and that's suspicious?" },
      { by: 'a', say: "Yes." },
      { by: 'b', say: "Honestly? Same." },
      { by: 'c', dr: "We decided someone's a villain for being too nice. I'd like to say that's unusual in here. It isn't." },
    ] },
    { id: 'gg2.3', when: { third: true }, turns: [
      { by: 'b', say: "Shh. Is {target} coming?" },
      { by: 'c', say: "No, {target}'s in the shower." },
      { by: 'b', say: "Okay. Did anyone else see {target} with the HOH this morning?" },
      { by: 'a', say: "I did. Whispering." },
      { by: 'c', say: "Whispering about what?" },
      { by: 'a', say: "Couldn't hear. But {target} looked over here twice." },
      { by: 'b', say: "At us?" },
      { by: 'a', say: "At us." },
      { beat: 'The shower turns off. All three of them start talking about the weather.' },
      { by: 'b', dr: "Three people talking about the weather, very loudly, at the exact second a shower stops. Subtle." },
    ] },
    { id: 'gg2.4', turns: [
      { by: 'c', say: "Okay, everybody be honest. Who's {target} actually working with?" },
      { by: 'a', say: "Everyone." },
      { by: 'b', say: "Nobody." },
      { by: 'c', say: "Those can't both be true." },
      { by: 'a', say: "Everyone thinks they're working with {target}. Nobody actually is." },
      { by: 'b', say: "...Oh. That's worse." },
      { by: 'c', say: "So we're all being played?" },
      { by: 'a', say: "Not all of us. Not if we compare notes." },
      { by: 'b', say: "Okay. What has {target} told you?" },
      { by: 'a', dr: "Ten minutes later we'd worked out {target} had told each of us something different. That was a useful ten minutes." },
    ] },
    { id: 'gg2.5', presumes: ['hoh'], room: 'backyard', turns: [
      { beat: 'Backyard. {a}, {b} and {c} are in the pool, which is the only place in the house the microphones struggle.' },
      { by: 'a', say: "Can you hear me?" },
      { by: 'b', say: "Barely." },
      { by: 'c', say: "Good. Talk fast." },
      { by: 'a', say: "{target} is building something. A group. I've seen them all go up to the HOH room together." },
      { by: 'b', say: "How many?" },
      { by: 'a', say: "At least three. Maybe four." },
      { by: 'c', say: "That's a majority if they get one more." },
      { by: 'a', say: "Exactly. So they don't get one more." },
      { by: 'c', dr: "Strategy in the pool. Everything we say sounds like we're drowning. Which, to be fair, we might be." },
    ] },
    { id: 'gg2.6', presumes: ['hoh'], turns: [
      { by: 'b', say: "I need a sanity check." },
      { by: 'a', say: "Go." },
      { by: 'b', say: "Is {target} being weird with me, or am I being paranoid?" },
      { by: 'c', say: "Both." },
      { by: 'b', say: "Thanks." },
      { by: 'a', say: "No, but seriously, {target} has been a bit off. With everyone." },
      { by: 'c', say: "Ever since the HOH comp." },
      { by: 'b', say: "So it's not just me." },
      { by: 'a', say: "It's not just you. It's never just you in here." },
      { by: 'b', dr: "I went in thinking I was paranoid. Came out knowing three people are paranoid about the same person. That's not paranoia. That's a target." },
    ] },
    { id: 'gg2.7', room: 'kitchen', presumes: ['noms'], when: { third: true }, turns: [
      { beat: 'Kitchen. {a} is cooking. {b} and {c} are "helping", which means standing close and talking quietly.' },
      { by: 'b', say: "Did you hear what {target} said about the vote?" },
      { by: 'a', say: "No, what?" },
      { by: 'c', say: "That it's 'already decided'." },
      { by: 'a', say: "Decided by who?" },
      { by: 'b', say: "That's what I want to know." },
      { by: 'c', say: "Nobody decided it with me." },
      { by: 'a', say: "Nobody decided it with any of us." },
      { by: 'b', say: "So who's in the room deciding it?" },
      { by: 'a', dr: "If a vote is 'already decided', there's a room somewhere I'm not in. I need to find that room." },
    ] },
    { id: 'gg2.8', turns: [
      { by: 'a', say: "Promise me nobody repeats this." },
      { by: 'b', say: "Promise." },
      { by: 'c', say: "Promise." },
      { by: 'a', say: "I think {target} has a showmance. A secret one." },
      { by: 'b', say: "With who?!" },
      { by: 'a', say: "I don't know yet. But {target} keeps disappearing at night." },
      { by: 'c', say: "Maybe {target} can't sleep." },
      { by: 'a', say: "Nobody can't sleep that many times." },
      { by: 'b', say: "We need a stake-out." },
      { by: 'c', say: "We are not doing a stake-out." },
      { by: 'b', dr: "We're absolutely doing a stake-out." },
    ] },
  ],
};
