// ══════════════════════════════════════════════════════════════════════
// bb/story/lines/more-banter.js — two people passing the time, widened
// ══════════════════════════════════════════════════════════════════════
//
// The prose audit, 2026-10-06: a full season aired the same "what day is it" and "if you were
// home" conversations two and three times; the pool had sixteen scenes for a season that airs
// two or three a week. These are whole conversations in plain English: a joke lands on first
// read, nobody answers in one clipped word, and nobody has a family, a pet or a job the roster
// does not give them. Roles: {a} and {b}.

export default {
  'story.life.banter.any': [
    { id: 'bz.1', room: 'kitchen', turns: [
      { beat: 'Kitchen. {a} is trying to open a jar. {b} watches for a while before saying anything.' },
      { by: 'b', say: "Do you want me to try?" },
      { by: 'a', say: "No. I've loosened it for you. That's what's happening here." },
      { by: 'b', say: "So when I open it, it was you." },
      { by: 'a', say: "It was always going to be me." },
      { by: 'b', say: "Okay. Give it here, then." },
      { beat: '{b} opens it first try. {a} takes the jar back without a word.' },
      { by: 'a', say: "You're welcome." },
      { by: 'a', dr: "I loosened that jar. I want that on the record. Nobody in this house will ever believe me." },
    ] },
    { id: 'bz.2', room: 'backyard', turns: [
      { beat: 'Backyard. {a} and {b} are lying on the grass, looking up at the roof over the yard.' },
      { by: 'a', say: "If you could have one thing from outside right now, what would it be?" },
      { by: 'b', say: "My own pillow. This one feels like it's full of crisps." },
      { by: 'a', say: "Mine's definitely full of something. I hear it every time I turn over." },
      { by: 'b', say: "That's not a pillow, that's a snack." },
      { by: 'a', say: "Don't. Now I'm hungry and tired." },
      { by: 'b', say: "Welcome to Big Brother." },
      { by: 'a', dr: "We spent twenty minutes talking about pillows. It was the best conversation I've had in here." },
    ] },
    { id: 'bz.3', room: 'living-room', turns: [
      { beat: 'Living room. {a} is teaching {b} a card game. It is not going well.' },
      { by: 'a', say: "Okay, so the sevens are wild." },
      { by: 'b', say: "Since when?" },
      { by: 'a', say: "Since I just said so. I'm teaching you the house rules." },
      { by: 'b', say: "Whose house?" },
      { by: 'a', say: "This house. Big Brother rules. Everything changes on a Thursday." },
      { by: 'b', say: "Then I'm saying the eights are wild too." },
      { by: 'a', say: "You can't do that. You're not the one teaching." },
      { by: 'b', dr: "I've lost four games to {a}. I'm now fairly sure {a} is making it up as we go." },
    ] },
    { id: 'bz.4', room: 'bedroom', turns: [
      { beat: 'Bedroom. {a} is folding clothes into very neat squares. {b} is watching from the next bed.' },
      { by: 'b', say: "You know nobody's checking, right?" },
      { by: 'a', say: "I'm checking. It's the only thing in this house I can actually control." },
      { by: 'b', say: "Can you do mine?" },
      { by: 'a', say: "Absolutely not. That's how it starts. Then I'm doing everybody's." },
      { by: 'b', say: "Just one shirt." },
      { by: 'a', say: "No. Fold your own shirt." },
      { by: 'b', dr: "{a} said no, and then quietly folded one of my shirts on the way out. I saw it." },
    ] },
    { id: 'bz.5', room: 'kitchen', turns: [
      { beat: 'Kitchen, late. {a} and {b} are eating cereal straight out of the box, standing up.' },
      { by: 'a', say: "Is this dinner?" },
      { by: 'b', say: "It's a snack that went on too long." },
      { by: 'a', say: "We had dinner two hours ago." },
      { by: 'b', say: "And now we're having the dinner after dinner. It's a tradition. As of tonight." },
      { by: 'a', say: "Do traditions usually start with getting caught?" },
      { by: 'b', say: "The good ones do." },
      { by: 'a', dr: "{b} invents a new tradition every time we're caught doing something we shouldn't be." },
    ] },
    { id: 'bz.6', room: 'backyard', turns: [
      { beat: 'Backyard. {a} is trying to learn to juggle with three oranges. {b} is keeping score.' },
      { by: 'b', say: "That's two catches. A new record." },
      { by: 'a', say: "It was three. You blinked." },
      { by: 'b', say: "I watched it hit the floor." },
      { by: 'a', say: "It bounced back up. That counts as a catch in my version." },
      { by: 'b', say: "Your version has a lot of rules nobody else knows about." },
      { by: 'a', say: "That's why I'm winning." },
      { by: 'b', dr: "{a} has now dropped every orange in the house. We're going to need to ask for more oranges." },
    ] },
    { id: 'bz.7', room: 'living-room', turns: [
      { beat: 'Living room. {a} and {b} are arguing about the best seat on the sofa.' },
      { by: 'a', say: "The corner seat is the best seat. Everybody knows that." },
      { by: 'b', say: "The corner seat is where the spring is." },
      { by: 'a', say: "The spring is part of the experience." },
      { by: 'b', say: "Then enjoy it. I'm having the middle." },
      { beat: '{a} sits down in the corner and immediately shifts to one side.' },
      { by: 'b', say: "How's the experience?" },
      { by: 'a', say: "It's great. I love it. Don't look at me." },
      { by: 'b', dr: "{a} would rather sit on a spring for a month than admit the middle seat is better." },
    ] },
    { id: 'bz.8', room: 'kitchen', turns: [
      { beat: 'Kitchen. {a} has made toast for {b} without being asked.' },
      { by: 'b', say: "What's this for?" },
      { by: 'a', say: "It's toast. It isn't for anything." },
      { by: 'b', say: "In this house, toast is always for something." },
      { by: 'a', say: "Fine. It's for you not being weird about the toast." },
      { by: 'b', say: "...That's fair. Thank you." },
      { by: 'a', say: "See? That wasn't so hard." },
      { by: 'b', dr: "I keep waiting to find out what the toast was for. I think it was just toast. In this house, that's rare." },
    ] },
    { id: 'bz.9', room: 'bedroom', turns: [
      { beat: 'Bedroom. {a} is lying awake, staring at the ceiling. {b} can tell.' },
      { by: 'b', say: "You're thinking so loudly I can hear it." },
      { by: 'a', say: "I can't work out what to do with my hands in here." },
      { by: 'b', say: "Normally you'd be holding a phone." },
      { by: 'a', say: "That's depressing. That's exactly what it is." },
      { by: 'b', say: "Hold a pillow. It's the same thing, but it doesn't buzz." },
      { by: 'a', say: "...That's actually helping. Goodnight." },
      { by: 'a', dr: "No phone, no music, no clock. You end up talking to people. Apparently that's what hands were for all along." },
    ] },
    { id: 'bz.10', room: 'backyard', turns: [
      { beat: 'Backyard. {a} and {b} are on the hammock together, which keeps trying to tip them out.' },
      { by: 'a', say: "Stop moving." },
      { by: 'b', say: "I'm not moving. The hammock is moving." },
      { by: 'a', say: "The hammock is moving because you're moving." },
      { by: 'b', say: "If we both stay completely still, we'll be fine." },
      { by: 'a', say: "Okay. Nobody breathe." },
      { beat: 'The hammock tips. They both end up on the grass, laughing.' },
      { by: 'b', dr: "Every time we get on that hammock, it wins. It's the strongest player in the house." },
    ] },
    { id: 'bz.11', room: 'living-room', turns: [
      { beat: 'Living room. {a} is doing an impression of the Big Brother voice. {b} is crying with laughter.' },
      { by: 'a', say: "Houseguests. Please stop eating the good cheese." },
      { by: 'b', say: "Do the one about the pool." },
      { by: 'a', say: "Houseguests. The pool is not a bath." },
      { by: 'b', say: "Who used the pool as a bath?" },
      { by: 'a', say: "I'm not naming names. Big Brother is watching. Big Brother knows." },
      { by: 'b', say: "Stop, I can't breathe." },
      { by: 'b', dr: "{a}'s Big Brother voice is better than the real one. Don't tell Big Brother I said that." },
    ] },
    { id: 'bz.12', room: 'kitchen', turns: [
      { beat: 'Kitchen. {a} and {b} are trying to cook something from what is left in the fridge.' },
      { by: 'a', say: "We've got eggs, half a pepper, and something in a tub I don't recognise." },
      { by: 'b', say: "Don't open the tub." },
      { by: 'a', say: "What if the tub is the answer?" },
      { by: 'b', say: "The tub is never the answer." },
      { beat: 'They make an omelette. Nobody opens the tub.' },
      { by: 'a', say: "This is good. This is actually good." },
      { by: 'b', say: "It's mostly pepper." },
      { by: 'a', dr: "That omelette was mostly pepper. It was still the best thing I've eaten in here." },
    ] },
    { id: 'bz.13', room: 'bedroom', turns: [
      { beat: 'Bedroom. {a} is trying to name every bed in the room in order, eyes shut. {b} is checking.' },
      { by: 'a', say: "Door, window, the creaky one, mine, yours..." },
      { by: 'b', say: "There's no window." },
      { by: 'a', say: "The one by where a window would be." },
      { by: 'b', say: "That's just the wall." },
      { by: 'a', say: "Then it's the wall bed. I stand by it." },
      { by: 'b', say: "You've given every bed in here a name." },
      { by: 'a', say: "Somebody had to." },
      { by: 'b', dr: "{a} has a name for every bed in this room. None of them are the right names, but {a} is very confident." },
    ] },
    { id: 'bz.14', room: 'backyard', turns: [
      { beat: 'Backyard. {a} and {b} are walking laps, talking about anything except the game.' },
      { by: 'b', say: "Rule for this lap: nobody says the word vote." },
      { by: 'a', say: "Or nominate." },
      { by: 'b', say: "Or anybody's name." },
      { by: 'a', say: "Then what are we going to talk about?" },
      { beat: 'They walk the whole lap in silence, then burst out laughing.' },
      { by: 'b', say: "Okay. One more lap. You can say one name." },
      { by: 'a', say: "Deal." },
      { by: 'a', dr: "We tried one lap without talking about the game. We lasted about forty seconds. This place gets into your head." },
    ] },
  ],
};
