// ══════════════════════════════════════════════════════════════════════
// bb/story/lines/more-sets2.js — the weekly set pieces, widened for several seasons
// ══════════════════════════════════════════════════════════════════════
//
// The HOH room reveal and the house after nominations air every week; a viewer who plays
// season after season saw them come back by the second season (the user, 2026-10-06: "widen
// it more"). With write.js remembering across seasons, two dozen versions each carry two or
// three seasons without a repeat. Roles as in set.js.

export default {
  'set.hohroom.open': [
    { id: 'xh.1', room: 'hoh-room', turns: [
      { beat: 'HOH room. {a} stands at the door like a bouncer. The house queues on the stairs.' },
      { by: 'a', say: "One at a time. It's a small room." },
      { by: 'b', say: "It's the biggest room in the house." },
      { by: 'a', say: "It's a small room for all of us." },
      { by: 'c', say: "Can I go first? I cheered for you the loudest." },
      { by: 'a', say: "You cheered for yourself the loudest." },
      { by: 'c', say: "I cheered for both of us!" },
      { beat: 'Everybody squeezes in anyway. The bouncer plan lasts four seconds.' },
      { by: 'd', dr: "{a} tried to have a door policy. Power doesn't make you a bouncer. It makes you a host." },
    ] },
    { id: 'xh.2', room: 'hoh-room', turns: [
      { beat: 'HOH room. {a} is reading the letter from home in silence. Everyone waits.' },
      { by: 'b', say: "Read it out!" },
      { by: 'a', say: "No. This one's just for me." },
      { by: 'c', say: "Fair." },
      { by: 'd', say: "Very fair." },
      { by: 'e', say: "...Just the first line?" },
      { by: 'a', say: "No!" },
      { beat: '{a} folds the letter and puts it in a pocket. Nobody pushes again.' },
      { by: 'b', dr: "{a} kept the letter private. Smart. A letter tells you who someone is playing for." },
    ] },
    { id: 'xh.3', room: 'hoh-room', turns: [
      { beat: 'HOH room. The basket has been raided. {a} is trying to work out who took the crisps.' },
      { by: 'a', say: "There were two bags of crisps. Now there's one." },
      { by: 'b', say: "Maybe there was only ever one." },
      { by: 'a', say: "I counted." },
      { by: 'c', say: "You counted the crisps?" },
      { by: 'a', say: "I'm Head of Household. I count everything." },
      { by: 'd', say: "Somebody check {e}'s pockets." },
      { by: 'e', say: "Why me?!" },
      { by: 'd', say: "You've gone very quiet." },
      { by: 'e', dr: "I did not take the crisps. I ate them. In the bathroom. That's different." },
    ] },
    { id: 'xh.4', room: 'hoh-room', turns: [
      { beat: 'HOH room. {a} lies down on the big bed and immediately falls asleep. The house watches, unsure what to do.' },
      { by: 'b', say: "Is {a} asleep?" },
      { by: 'c', say: "Completely. Snoring and everything." },
      { by: 'd', say: "Do we leave?" },
      { by: 'e', say: "Do we stay and eat the chocolate?" },
      { by: 'b', say: "We leave." },
      { beat: 'Everybody leaves. One person takes one chocolate on the way out.' },
      { by: 'c', dr: "First thing {a} did with power was take a nap. Honestly, respect. That comp was brutal." },
    ] },
    { id: 'xh.5', room: 'hoh-room', turns: [
      { beat: 'HOH room. The house has piled in. {a} is trying to show everyone the view from the window, which is a wall.' },
      { by: 'a', say: "And from up here, you can see—" },
      { by: 'b', say: "A wall." },
      { by: 'a', say: "A very nice wall." },
      { by: 'c', say: "Is that the same wall we see from the kitchen?" },
      { by: 'a', say: "It's a different side of the wall." },
      { by: 'd', say: "Wow. Power really does change your perspective." },
      { beat: 'The room cracks up.' },
      { by: 'a', dr: "No view, no window, no privacy, and I've never been happier. The bed is enormous." },
    ] },
    { id: 'xh.6', room: 'hoh-room', turns: [
      { beat: 'HOH room. {a} has made everyone take their shoes off at the door. There are many, many shoes.' },
      { by: 'b', say: "Is this a temple now?" },
      { by: 'a', say: "It's a clean room. I'd like it to stay a clean room." },
      { by: 'c', say: "For how long?" },
      { by: 'a', say: "One week. That's all I ask." },
      { by: 'd', say: "Can we at least sit on the bed?" },
      { by: 'a', say: "Sit on the edge. Feet off." },
      { by: 'e', say: "This is the strictest HOH in history." },
      { by: 'e', dr: "The no-shoes rule is the first rule of {a}'s reign. I wonder what the second one is. I wonder if it's me on the block." },
    ] },
    { id: 'xh.7', room: 'hoh-room', turns: [
      { beat: 'HOH room. The house is crowded round, reading the HOH letter over {a}’s shoulder.' },
      { by: 'a', say: "Personal space. Remember it?" },
      { by: 'b', say: "We just want to see the handwriting." },
      { by: 'c', say: "It's very neat handwriting." },
      { by: 'a', say: "Can I read my own letter, please?" },
      { by: 'd', say: "Read it out loud, then." },
      { by: 'a', say: "'Stay strong. Trust your gut.'" },
      { by: 'e', say: "Ooh. 'Trust your gut.' What's your gut saying?" },
      { by: 'a', say: "My gut is saying everyone get off my bed." },
      { by: 'b', dr: "'Trust your gut.' Now everyone in that room is wondering whose name {a}'s gut is saying." },
    ] },
    { id: 'xh.8', room: 'hoh-room', turns: [
      { beat: 'HOH room. {a} is giving a tour of the HOH bathroom as if it’s a museum.' },
      { by: 'a', say: "And here we have the towels. Very fluffy, very clean, and only for me." },
      { by: 'b', say: "Wow." },
      { by: 'a', say: "And here, the shower. Nobody waiting outside it." },
      { by: 'c', say: "I'm genuinely jealous." },
      { by: 'a', say: "And here, the lock." },
      { by: 'd', say: "A LOCK?" },
      { by: 'a', say: "A working lock." },
      { beat: 'The whole house gasps. Someone tries the lock just to hear it click.' },
      { by: 'd', dr: "A lock. A door that locks. I'd win HOH just to have that lock for a week." },
    ] },
  ],
  'set.hohroom.close': [
    { id: 'xh.c1', room: 'hoh-room', turns: [{ beat: 'By the time the last person leaves, the chocolate is gone and so is the first name on {a}’s list.' }, { by: 'a', dr: "Everyone came up here to celebrate with me. A few of them came up here to campaign. I can tell which." }] },
    { id: 'xh.c2', room: 'hoh-room', turns: [{ beat: 'The house files out. One of them looks back at the camera screen on the way out.' }, { by: 'a', dr: "Everyone who walks out of this room is thinking the same thing: who's going up. So am I." }] },
    { id: 'xh.c3', room: 'hoh-room', turns: [{ beat: 'Alone at last, {a} sits on the edge of the bed and stares at nothing.' }, { by: 'a', dr: "Ten minutes ago this was the best room in the house. Now it's the room where I have to decide who gets hurt." }] },
  ],
  'set.afternoms.open': [
    { id: 'xa.1', room: 'living-room', turns: [
      { beat: 'After the ceremony. {a} hasn’t moved from the chair. Somebody brings a blanket.' },
      { by: 'd', say: "Here." },
      { by: 'a', say: "I'm not cold." },
      { by: 'd', say: "It's not for cold. It's for being sad." },
      { by: 'a', say: "...Okay. Thanks." },
      { by: 'b', say: "Can I have a sad blanket?" },
      { by: 'e', say: "You get the other half." },
      { beat: 'The two nominees end up under one blanket. It is a very small blanket.' },
      { by: 'd', dr: "Two people on the block, sharing a blanket. Nobody said the obvious thing out loud." },
    ] },
    { id: 'xa.2', room: 'kitchen', turns: [
      { beat: 'After nominations, the kitchen. {c} comes down and makes a sandwich in total silence.' },
      { by: 'c', say: "Anyone want anything?" },
      { by: 'd', say: "We're good." },
      { by: 'e', say: "Fine, thanks." },
      { by: 'c', say: "Okay." },
      { beat: '{c} takes the sandwich back upstairs. Nobody speaks until the door closes.' },
      { by: 'f', say: "That was the most awkward sandwich in history." },
      { by: 'a', say: "I hope it was a bad sandwich." },
      { by: 'b', dr: "The HOH made a sandwich and the whole kitchen froze. That's what power does in here. Even a sandwich is scary." },
    ] },
    { id: 'xa.3', room: 'living-room', turns: [
      { beat: 'Straight after nominations. {b} is laughing. Nobody knows why, including {b}.' },
      { by: 'a', say: "Why are you laughing?" },
      { by: 'b', say: "I don't know! I'm on the block! It's ridiculous!" },
      { by: 'd', say: "Is this a breakdown?" },
      { by: 'b', say: "Probably!" },
      { beat: '{a} starts laughing too. Then half the room is laughing.' },
      { by: 'e', say: "This is the weirdest nomination day ever." },
      { by: 'b', dr: "You either laugh or you cry. I chose laughing. I'll probably cry about it later." },
    ] },
    { id: 'xa.4', room: 'backyard', turns: [
      { beat: 'After nominations. The house drifts to the backyard and sits in a rough circle, saying nothing.' },
      { by: 'd', say: "Should we do something?" },
      { by: 'e', say: "Like what?" },
      { by: 'd', say: "I don't know. A game. Anything." },
      { by: 'a', say: "Can we just sit? For a bit?" },
      { by: 'f', say: "We can just sit." },
      { beat: 'They sit. For a long time. Nobody leaves the nominees on their own.' },
      { by: 'f', dr: "Sometimes the kindest thing in this house is just staying in the circle. Not saying anything. Just staying." },
    ] },
    { id: 'xa.5', room: 'kitchen', turns: [
      { beat: 'After the ceremony, dinner. {d} puts a full plate in front of {a} without being asked.' },
      { by: 'a', say: "You made me a plate?" },
      { by: 'd', say: "You weren't going to eat otherwise." },
      { by: 'a', say: "That's so nice. That's actually really nice." },
      { by: 'b', say: "Is there a plate for me?" },
      { by: 'e', say: "There's a plate for everybody." },
      { by: 'b', say: "Then I'll stop sulking. For ten minutes." },
      { by: 'a', dr: "Somebody made sure I ate on the worst day of my week. I'll remember that." },
    ] },
    { id: 'xa.6', room: 'living-room', turns: [
      { beat: 'After nominations. The house is sitting on the sofas, staring at the blank TV screen.' },
      { by: 'e', say: "This is unbearable." },
      { by: 'f', say: "Somebody say something." },
      { by: 'd', say: "...Nice weather today." },
      { by: 'a', say: "You haven't seen the sky in a month." },
      { by: 'd', say: "...I'm guessing, okay?" },
      { beat: '{b} snorts. The tension breaks a little.' },
      { by: 'e', dr: "Nomination days are the worst days. Everybody's trying not to say the obvious thing." },
    ] },
    { id: 'xa.7', room: 'bedroom', turns: [
      { beat: 'After the ceremony. {a} is packing a bag. Just in case. Everybody keeps walking past to look.' },
      { by: 'd', say: "Stop packing." },
      { by: 'a', say: "I'm being organised." },
      { by: 'e', say: "You're being dramatic." },
      { by: 'a', say: "I'd rather be ready." },
      { by: 'b', say: "Should I be packing?" },
      { by: 'd', say: "Nobody should be packing!" },
      { beat: '{d} starts unpacking {a}’s bag. {a} starts packing it again. It goes on for a while.' },
      { by: 'a', dr: "If I'm packed, I'm ready. If I'm ready, it won't hurt as much. That's the theory." },
    ] },
    { id: 'xa.8', room: 'living-room', turns: [
      { beat: 'After nominations. Somebody suggests a movie night. There are no movies.' },
      { by: 'd', say: "We could act one out." },
      { by: 'e', say: "Which one?" },
      { by: 'd', say: "Any one. Everybody knows how films go." },
      { by: 'a', say: "Can I play the person who survives?" },
      { by: 'b', say: "I want to be the person who survives." },
      { by: 'f', say: "There's only one survivor. That's the whole film." },
      { beat: 'A small, uncomfortable silence. Everybody gets the joke at once.' },
      { by: 'f', dr: "I made a joke about only one survivor on nomination day. Everyone laughed. Nobody laughed properly." },
    ] },
  ],
  'set.afternoms.close': [
    { id: 'xa.c1', turns: [{ beat: 'The house starts its usual split. This week the line runs right down the middle of the kitchen.' }, { by: 'b', dr: "Every nomination week the house picks a side. You can see it by dinner." }] },
    { id: 'xa.c2', turns: [{ beat: 'The two nominees sit apart for the first time all day. Both of them are being visited.' }, { by: 'a', dr: "It's a campaign now. Smile, talk, count. Four days of it." }] },
  ],
  'set.morningafter.open': [
    { id: 'xm.1', room: 'kitchen', turns: [
      { beat: 'Morning after. Somebody finds a note {gone} left on the fridge.' },
      { by: 'a', say: "'Don't forget to water the plant.'" },
      { by: 'b', say: "What plant?" },
      { by: 'c', say: "There's a plant?" },
      { by: 'd', say: "There's a plant in the bathroom. It's very dead." },
      { by: 'a', say: "{gone} was watering a dead plant?" },
      { by: 'e', say: "{gone} was an optimist." },
      { beat: 'Somebody waters the dead plant anyway. For {gone}.' },
      { by: 'c', dr: "We're watering a dead plant now. That's how much we miss {gone}. Or how bored we are." },
    ] },
    { id: 'xm.2', room: 'living-room', turns: [
      { beat: 'Morning after. The house is gathered on the sofas, recapping the vote like sports commentators.' },
      { by: 'a', say: "I wasn't sure until the moment the host said the name." },
      { by: 'b', say: "I knew on Tuesday." },
      { by: 'c', say: "You did not know on Tuesday." },
      { by: 'b', say: "I had a feeling on Tuesday." },
      { by: 'd', say: "Everyone has a feeling on Tuesday." },
      { by: 'e', say: "Did anyone actually go against the house?" },
      { beat: 'Everybody looks at everybody. Nobody says a word.' },
      { by: 'a', dr: "The morning after a vote, everybody's a detective. Nobody's a witness." },
    ] },
    { id: 'xm.3', room: 'kitchen', turns: [
      { beat: 'Morning after. {gone}’s spot at the table is empty. Somebody sits in it, then stands straight back up.' },
      { by: 'b', say: "That felt wrong." },
      { by: 'a', say: "It's just a chair." },
      { by: 'b', say: "It's {gone}'s chair." },
      { by: 'c', say: "It's a chair until somebody new sits in it permanently." },
      { by: 'd', say: "So, who's sitting in it permanently?" },
      { beat: 'Nobody sits in it. The chair stays empty all breakfast.' },
      { by: 'd', dr: "Nobody would sit in {gone}'s chair. By tomorrow somebody will. That's how fast it goes." },
    ] },
    { id: 'xm.4', room: 'bedroom', turns: [
      { beat: 'Morning after. Somebody has found {gone}’s hoodie under a bed.' },
      { by: 'a', say: "{gone} left this." },
      { by: 'b', say: "Should we give it to Big Brother?" },
      { by: 'c', say: "I'm keeping it." },
      { by: 'd', say: "That's stealing." },
      { by: 'c', say: "It's not stealing. It's something to remember {gone} by." },
      { by: 'e', say: "It's a very nice hoodie." },
      { beat: '{c} puts it on. It suits {c} better. Nobody says so.' },
      { by: 'c', dr: "I'll give it back on finale night. If I'm still here. If I'm not, it's evidence." },
    ] },
    { id: 'xm.5', room: 'kitchen', turns: [
      { beat: 'Morning after. The house is quiet. Somebody turns the kettle on and it is the loudest thing in the world.' },
      { by: 'a', say: "Tea, anyone?" },
      { by: 'b', say: "Please." },
      { by: 'c', say: "Yes." },
      { by: 'd', say: "Can you make {gone}'s order by mistake again?" },
      { by: 'a', say: "Why?" },
      { by: 'd', say: "So it feels normal for one more morning." },
      { beat: 'Somebody makes one extra tea. It sits on the counter, getting cold, all morning.' },
      { by: 'b', dr: "One extra cup of tea. Nobody drank it. Nobody poured it out either." },
    ] },
    { id: 'xm.6', room: 'living-room', turns: [
      { beat: 'Morning after. The house is doing a group workout, mostly so nobody has to talk about the vote.' },
      { by: 'a', say: "And squat! And up!" },
      { by: 'b', say: "Why are we doing this?" },
      { by: 'a', say: "Endorphins. We need endorphins." },
      { by: 'c', say: "I need sleep." },
      { by: 'd', say: "I need a nap." },
      { by: 'e', say: "Ten more squats for {gone}!" },
      { beat: 'Ten more squats, for {gone}. Nobody actually finishes them.' },
      { by: 'c', dr: "We grieve with squats in this house. Badly. Very badly." },
    ] },
  ],
  'set.morningafter.close': [
    { id: 'xm.c1', turns: [{ beat: 'By the afternoon, the house is talking about the HOH comp instead. {gone} is already a story people tell.' }, { by: 'a', dr: "One night. That's how long you're missed in here. Then there's another key, another chair, another Thursday." }] },
  ],
  'set.dinner.open': [
    { id: 'xd.1', room: 'kitchen', turns: [
      { beat: 'Dinner. {a} has decided everyone should share one embarrassing story. Most people refuse.' },
      { by: 'b', say: "Pass." },
      { by: 'c', say: "Pass." },
      { by: 'a', say: "You can't all pass!" },
      { by: 'd', say: "Fine. I once waved at someone who was waving at somebody behind me." },
      { by: 'e', say: "That's not embarrassing, that's everyone." },
      { by: 'd', say: "I waved back for a while." },
      { by: 'f', say: "How long?" },
      { by: 'd', say: "Way too long. They'd already gone round the corner." },
      { by: 'e', dr: "{d} won the embarrassing story game with a wave. Low bar. Great dinner." },
    ] },
    { id: 'xd.2', room: 'kitchen', turns: [
      { beat: 'Dinner. Two people have cooked two different dinners at the same time. There is a competition now.' },
      { by: 'a', say: "Mine's better." },
      { by: 'b', say: "Mine's spicier." },
      { by: 'c', say: "Spicier isn't better." },
      { by: 'b', say: "Spicier is always better." },
      { by: 'd', say: "Can we vote?" },
      { by: 'e', say: "Nobody is voting on dinner. We vote enough." },
      { by: 'f', say: "I'm eating both. Together. On one plate." },
      { beat: '{f} mixes them. Both cooks look personally betrayed.' },
      { by: 'f', dr: "I found a way to stay neutral in the dinner war. Also it was delicious. Don't tell either of them." },
    ] },
    { id: 'xd.3', room: 'kitchen', turns: [
      { beat: 'Dinner. Nobody has spoken for a minute. Everyone is just chewing.' },
      { by: 'a', say: "This is the quietest dinner we've ever had." },
      { by: 'b', say: "We're tired." },
      { by: 'c', say: "We're always tired." },
      { by: 'd', say: "We're tired and full. It's a peaceful combination." },
      { by: 'e', say: "Let's never talk again. This is nice." },
      { beat: 'They do not talk again for almost two whole minutes. A house record.' },
      { by: 'a', dr: "Two minutes of silence at a dinner table. The most relaxed I've been since I got here." },
    ] },
    { id: 'xd.4', room: 'kitchen', turns: [
      { beat: 'Dinner. Somebody has made dessert. The house is suspicious of dessert.' },
      { by: 'a', say: "Why is there dessert?" },
      { by: 'b', say: "Because I made dessert." },
      { by: 'c', say: "Nobody makes dessert unless they want something." },
      { by: 'b', say: "I want you to eat dessert." },
      { by: 'd', say: "That's exactly what someone who wants something would say." },
      { by: 'e', say: "I'll eat it. I don't care what it costs me." },
      { beat: 'Everyone eats dessert. Everyone watches {b} the whole time.' },
      { by: 'b', dr: "I made a cake because I like cake. I've never been more distrusted in my life." },
    ] },
  ],
  'set.backyard.open': [
    { id: 'xy.1', room: 'backyard', turns: [
      { beat: 'Backyard. Somebody has started a game of tag. Grown adults are running in circles round the pool.' },
      { by: 'a', say: "You're it!" },
      { by: 'b', say: "I was not touching base!" },
      { by: 'c', say: "There's no base!" },
      { by: 'b', say: "The hammock is base!" },
      { by: 'd', say: "Since when?" },
      { by: 'b', say: "Since now!" },
      { beat: 'Somebody falls in the pool. Tag is cancelled.' },
      { by: 'e', dr: "We played tag for ten minutes. It ended in the pool and an argument about base. Like every game in this house." },
    ] },
    { id: 'xy.2', room: 'backyard', turns: [
      { beat: 'Backyard. The house is lying in the sun, trying to guess what the next comp will be.' },
      { by: 'a', say: "It'll be the endurance one. I can feel it." },
      { by: 'b', say: "You can't feel a comp." },
      { by: 'a', say: "I can feel it in my legs." },
      { by: 'c', say: "Your legs are just tired from lying down." },
      { by: 'd', say: "I bet it's a quiz." },
      { by: 'e', say: "Please be a quiz. I'm good at quizzes." },
      { by: 'b', say: "That's why it won't be a quiz." },
      { by: 'c', dr: "Everyone guesses the comp. Nobody ever guesses right. That doesn't stop anyone." },
    ] },
    { id: 'xy.3', room: 'backyard', turns: [
      { beat: 'Backyard. A spontaneous talent show has started. Nobody has a talent.' },
      { by: 'a', say: "Watch this. I can touch my nose with my tongue." },
      { by: 'b', say: "That's not a talent, that's a medical condition." },
      { by: 'c', say: "I can whistle with my fingers." },
      { beat: '{c} tries. Nothing happens. {c} tries again. A tiny squeak.' },
      { by: 'd', say: "Ten out of ten." },
      { by: 'e', say: "I can do a cartwheel." },
      { by: 'f', say: "No, you can't." },
      { by: 'e', dr: "I could not do a cartwheel. I found that out in front of everyone. On camera. On the grass." },
    ] },
    { id: 'xy.4', room: 'backyard', turns: [
      { beat: 'Backyard, golden hour. Everyone is quiet for once, watching the light go.' },
      { by: 'a', say: "It's actually beautiful out here." },
      { by: 'b', say: "It's a fake sunset. There's a roof." },
      { by: 'a', say: "Let me have this." },
      { by: 'c', say: "It's a very good fake sunset." },
      { by: 'd', say: "Best fake sunset I've ever seen." },
      { beat: 'Nobody moves until the lights flip to night mode.' },
      { by: 'b', dr: "I said it was fake. It was fake. It was still the nicest ten minutes of the week." },
    ] },
  ],
  'set.gamenight.open': [
    { id: 'xg.1', room: 'living-room', turns: [
      { beat: 'Living room. {a} has made up a game: {a} reads out something a houseguest said this week, and everybody has to guess who said it.' },
      { by: 'a', say: "First one. Who said: 'I'm not here to make friends'?" },
      { by: 'b', say: "That's not fair. Everybody's said that." },
      { by: 'a', say: "Fine. Next one. Who said: 'I'll be in the storage room if anyone needs me'?" },
      { by: 'c', say: "That's {d}. Easy." },
      { by: 'd', say: "I said that once!" },
      { by: 'e', say: "You say it every single day." },
      { beat: 'The room falls apart laughing. {d} throws a cushion.' },
      { by: 'd', dr: "That game was supposed to be fun. It was. It was also the whole house telling me they notice everything I do." },
    ] },
    { id: 'xg.2', room: 'living-room', turns: [
      { beat: 'Living room. A game of "never have I ever" with fingers up. It gets risky fast.' },
      { by: 'a', say: "Never have I ever lied in this house." },
      { beat: 'Every single finger goes down at once.' },
      { by: 'b', say: "Wow." },
      { by: 'c', say: "At least we're honest about lying." },
      { by: 'd', say: "Never have I ever made a final two." },
      { beat: 'A few fingers go down. Everybody clocks exactly whose.' },
      { by: 'e', say: "I think we should stop playing this." },
      { by: 'e', dr: "We learned more in five minutes of that game than in a week of strategy talks. Then we stopped. Very fast." },
    ] },
    { id: 'xg.3', room: 'living-room', turns: [
      { beat: 'Living room. A dance-off has broken out. There is no music. Somebody is beatboxing.' },
      { by: 'a', say: "Go! Go! Go!" },
      { by: 'b', say: "I'm going!" },
      { by: 'c', say: "Is that a dance or a seizure?" },
      { by: 'b', say: "It's called freestyle!" },
      { by: 'd', say: "Next! Me next!" },
      { beat: '{d} does a move that nobody has a name for. The room screams.' },
      { by: 'e', say: "Winner. No contest." },
      { by: 'd', dr: "I won a dance-off with no music, judged by six people who can't dance. Proudest moment in the house." },
    ] },
  ],
};
