// ══════════════════════════════════════════════════════════════════════
// bb/story/lines/more-groups2.js — the rest of the group pools, widened
// ══════════════════════════════════════════════════════════════════════
//
// Sized from the twelve-week measurement (2026-10-06): an alliance member left out of a
// group meeting aired eight times on four scenes, friends in a group six on three, group
// banter seven on seven. Added to the same keys. Roles as in groups.js.

export default {
  'story.alliance.leftout.group': [
    { id: 'gl2.1', turns: [
      { by: 'a', say: "So the group decided. Without me." },
      { by: 'b', say: "It wasn't a decision, it was a conversation." },
      { by: 'c', say: "A short one." },
      { by: 'a', say: "Short enough to fit in while I was in the Diary Room?" },
      { by: 'b', say: "...Yes." },
      { by: 'a', say: "Great. So what did 'we' decide?" },
      { by: 'c', say: "Same plan as yesterday." },
      { by: 'a', say: "Then why did you need a conversation about it?" },
      { beat: 'Nobody has a good answer.' },
      { by: 'a', dr: "If the plan's the same, you don't need a meeting. You only need a meeting when the plan's changed. Without me." },
    ] },
    { id: 'gl2.2', room: 'bedroom', turns: [
      { beat: 'Bedroom. {b} and {c} are deep in conversation. {a} sits down on the next bed. They stop.' },
      { by: 'a', say: "Keep going. I'm in this too, apparently." },
      { by: 'b', say: "We were just saying—" },
      { by: 'c', say: "—about the comp." },
      { by: 'a', say: "Two people, two different answers, same sentence. Very convincing." },
      { by: 'b', say: "Okay. We were talking about the vote." },
      { by: 'a', say: "And?" },
      { by: 'c', say: "And we wanted to be sure before we told everyone." },
      { by: 'a', say: "I'm not 'everyone'. I'm in the group." },
      { by: 'b', dr: "{a} is right, and also exhausting. Both things. Every week." },
    ] },
    { id: 'gl2.3', turns: [
      { by: 'c', say: "Are we telling {a}?" },
      { by: 'b', say: "Later." },
      { by: 'd', say: "We said 'later' last time." },
      { by: 'b', say: "And we told {a} later." },
      { by: 'd', say: "After the vote." },
      { by: 'c', say: "That's not later. That's never, with extra steps." },
      { beat: '{a} walks in, holding a mug, and stops.' },
      { by: 'a', say: "Telling me what?" },
      { by: 'b', say: "...Sit down." },
      { by: 'a', dr: "I walked in on my own alliance deciding whether to tell me things. That's not an alliance. That's an alliance with me on the outside of it." },
    ] },
    { id: 'gl2.4', when: { register: ['fiery'] }, turns: [
      { by: 'a', say: "No, don't 'calm down' me. Everybody in {alliance} knew except me!" },
      { by: 'b', say: "You weren't around!" },
      { by: 'a', say: "I was in the kitchen! It's ten feet away!" },
      { by: 'c', say: "It was quick, it just happened—" },
      { by: 'a', say: "Things don't 'just happen' in this house! People make them happen! You made it happen without me!" },
      { by: 'b', say: "Okay. You're right. We should have got you." },
      { by: 'a', say: "Thank you." },
      { by: 'c', say: "Are you going to stay angry?" },
      { by: 'a', say: "For about an hour. Then I'll be fine. Leave me alone for an hour." },
      { by: 'c', dr: "{a} explodes, and then {a} is fine. You just have to wait for the hour." },
    ] },
    { id: 'gl2.5', turns: [
      { by: 'a', say: "Can I ask something and everyone answer honestly?" },
      { by: 'b', say: "Sure." },
      { by: 'a', say: "Am I still in {alliance}? Like, actually?" },
      { by: 'c', say: "Of course you are." },
      { by: 'b', say: "Yes." },
      { by: 'a', say: "Then why am I always the last to know?" },
      { by: 'c', say: "Bad luck?" },
      { by: 'a', say: "It's not luck if it keeps happening." },
      { beat: 'Nobody can argue with that.' },
      { by: 'a', dr: "I'm in an alliance that tells me things last. That's not an alliance. That's a waiting room." },
    ] },
  ],
  'story.life.friends.group': [
    { id: 'gw2.1', presumes: ['hoh'], room: 'bedroom', turns: [
      { beat: 'Bedroom. {a}, {b} and {c} are lying on one bed, talking about nothing.' },
      { by: 'a', say: "If we all get evicted, we're going on holiday together." },
      { by: 'b', say: "Where?" },
      { by: 'a', say: "Anywhere with no cameras." },
      { by: 'c', say: "Anywhere with doors that lock." },
      { by: 'b', say: "Anywhere where nobody votes on anything." },
      { by: 'a', say: "So, anywhere." },
      { by: 'c', say: "Anywhere. Deal." },
      { by: 'b', dr: "We plan a holiday every night. We're never going to go. It doesn't matter. It's the planning." },
    ] },
    { id: 'gw2.2', turns: [
      { by: 'b', say: "Can I just say, you lot are the only reason I haven't lost it in here." },
      { by: 'a', say: "Aw." },
      { by: 'c', say: "Same, honestly." },
      { by: 'd', say: "We should make it official. Like a club." },
      { by: 'a', say: "A club for people who haven't lost it?" },
      { by: 'd', say: "The Haven't Lost It Club." },
      { by: 'c', say: "Membership: four." },
      { by: 'b', say: "Membership: four, for now." },
      { by: 'd', dr: "It's not an alliance. It's a club. Very different. Clubs have snacks." },
    ] },
    { id: 'gw2.3', room: 'living-room', turns: [
      { beat: 'Living room. {a}, {b} and {c} have built a cushion fort and are refusing to come out.' },
      { by: 'a', say: "This fort is game-free." },
      { by: 'b', say: "Nobody says a name in the fort." },
      { by: 'c', say: "Nobody counts a vote in the fort." },
      { by: 'a', say: "Nobody even thinks about Thursday in the fort." },
      { by: 'b', say: "...I just thought about Thursday." },
      { by: 'c', say: "Out. Out of the fort." },
      { by: 'b', say: "I take it back!" },
      { by: 'a', dr: "The fort has rules. The fort is the only place in this house with rules that everyone actually keeps." },
    ] },
    { id: 'gw2.4', turns: [
      { by: 'a', say: "Okay, favourite thing about being in here. Go." },
      { by: 'b', say: "The pool at night when nobody's in it." },
      { by: 'c', say: "Nobody needs me to answer an email." },
      { by: 'd', say: "Honestly? This. Right here." },
      { by: 'a', say: "Mine's this too." },
      { by: 'c', say: "That's so cheesy." },
      { by: 'b', say: "It's also true, though." },
      { by: 'c', say: "...Fine. Mine's this too." },
      { by: 'c', dr: "Three people said 'this' and I rolled my eyes. Then I said it too. I'm never admitting I meant it." },
    ] },
  ],
  'story.life.banter.group': [
    { id: 'gb2.1', presumes: ['hoh'], turns: [
      { by: 'a', say: "Okay, what's everyone's worst habit? Be honest." },
      { by: 'b', say: "I talk in my sleep." },
      { by: 'c', say: "I know. You said my name last night." },
      { by: 'b', say: "What did I say?!" },
      { by: 'c', say: "Just my name. Very sadly." },
      { by: 'd', say: "That's terrifying." },
      { by: 'a', say: "What's yours, {d}?" },
      { by: 'd', say: "I don't have any bad habits." },
      { by: 'b', say: "You eat cereal standing up with the fridge open." },
      { by: 'd', say: "That's efficient, not a habit!" },
      { by: 'c', dr: "We all know each other's worst habits now. We've lived together long enough to be annoyed by each other properly." },
    ] },
    { id: 'gb2.2', turns: [
      { by: 'b', say: "What do you think they're watching at home right now?" },
      { by: 'a', say: "Us, eating crisps." },
      { by: 'c', say: "Riveting." },
      { by: 'd', say: "Hi, everyone. These crisps are very good." },
      { by: 'a', say: "Don't advertise crisps!" },
      { by: 'd', say: "I'm not advertising, I'm sharing a review." },
      { by: 'b', say: "Five stars. Would eat again on national television." },
      { by: 'c', say: "We're all going to look insane." },
      { by: 'a', dr: "Somewhere, people are watching four adults review crisps. I hope they're having as much fun as we are." },
    ] },
    { id: 'gb2.3', room: 'kitchen', turns: [
      { beat: 'Kitchen. {a}, {b}, {c} and {d} are trying to make a cake with no recipe.' },
      { by: 'a', say: "How much flour?" },
      { by: 'b', say: "Some." },
      { by: 'c', say: "A lot." },
      { by: 'd', say: "Enough." },
      { by: 'a', say: "Those are three different amounts!" },
      { by: 'b', say: "Just put it in. It'll be fine." },
      { beat: 'It is not fine. It is a brick. Everybody eats some anyway.' },
      { by: 'c', say: "It's… crunchy." },
      { by: 'd', say: "It's a crunchy cake." },
      { by: 'a', dr: "We made a cake with four opinions and no recipe. That's this house, basically. It was terrible. We ate all of it." },
    ] },
    { id: 'gb2.4', turns: [
      { by: 'a', say: "If this house was a TV show, what would it be called?" },
      { by: 'b', say: "It is a TV show." },
      { by: 'a', say: "A different one. Our one." },
      { by: 'c', say: "'Nobody Washes Up.'" },
      { by: 'd', say: "'Where's The Peanut Butter.'" },
      { by: 'b', say: "'Twelve People, One Toilet Roll.'" },
      { by: 'a', say: "Okay, these are all just complaints." },
      { by: 'c', say: "That's what our show would be. Complaints." },
      { by: 'd', dr: "We pitched about fifteen TV shows. Every single one was about the bathroom. We need to get out more." },
    ] },
    { id: 'gb2.5', turns: [
      { by: 'b', say: "Who do you think is the best liar in the house?" },
      { by: 'a', say: "That's dangerous." },
      { by: 'c', say: "Just say it." },
      { by: 'a', say: "Fine. Whoever's the best liar, we'd never know. That's the point." },
      { by: 'd', say: "Oh, that's deep." },
      { by: 'b', say: "That's a dodge." },
      { by: 'a', say: "It's both." },
      { by: 'c', say: "So it's you. You're the best liar. You just proved it." },
      { by: 'a', say: "...I'm going to get a drink." },
      { by: 'c', dr: "{a} dodged the question so well, I'm now convinced {a} is the best liar in the house. Mission accomplished, {a}." },
    ] },
  ],
  'story.life.latenight.group': [
    { id: 'gn2.1', presumes: ['hoh'], room: 'bedroom', turns: [
      { beat: 'Bedroom, long after lights out. A whisper from one bed sets off the others.' },
      { by: 'a', say: "Is anyone awake?" },
      { by: 'b', say: "No." },
      { by: 'c', say: "Yes." },
      { by: 'a', say: "Do you ever think about how weird this is? Strangers, sleeping in one room, on TV?" },
      { by: 'c', say: "Every night." },
      { by: 'b', say: "I'm thinking about it right now. Thanks." },
      { by: 'a', say: "Sorry." },
      { by: 'd', say: "Can everyone think about it quieter?" },
      { by: 'c', dr: "Every night someone asks 'is anyone awake?' Every night everyone is." },
    ] },
    { id: 'gn2.2', room: 'kitchen', turns: [
      { beat: 'Kitchen, three in the morning. Four people who couldn’t sleep, one jar of peanut butter, four spoons.' },
      { by: 'a', say: "This is our secret." },
      { by: 'b', say: "What is?" },
      { by: 'a', say: "Three a.m. peanut butter club." },
      { by: 'c', say: "Is it a club now?" },
      { by: 'a', say: "Everything's a club at three a.m." },
      { by: 'd', say: "Do we have rules?" },
      { by: 'a', say: "One rule. Nobody talks about the game." },
      { beat: 'They don’t. For an hour, nobody talks about the game.' },
      { by: 'd', dr: "Best hour I've had in here. Nobody wanted anything from anyone. Just peanut butter." },
    ] },
  ],
  'story.showmance.spark.group': [
    { id: 'gs2.1', turns: [
      { by: 'c', say: "So are we just not going to talk about it?" },
      { by: 'a', say: "About what?" },
      { by: 'd', say: "You two. Holding hands under the table." },
      { by: 'b', say: "We weren't holding hands!" },
      { by: 'c', say: "Your knees were holding hands." },
      { by: 'a', say: "That's not a thing." },
      { by: 'd', say: "Knee-holding is the most serious kind of holding." },
      { beat: '{a} and {b} move their knees apart very obviously.' },
      { by: 'c', dr: "They think nobody can see under the table. We can all see under the table." },
    ] },
    { id: 'gs2.2', room: 'living-room', turns: [
      { beat: 'Living room. {c} and {d} have arranged the sofa so that {a} and {b} have to sit together. It’s not subtle.' },
      { by: 'a', say: "Why is there only one seat left?" },
      { by: 'c', say: "Coincidence." },
      { by: 'b', say: "There were four seats a minute ago." },
      { by: 'd', say: "Furniture moves." },
      { by: 'a', say: "Furniture does not move!" },
      { by: 'c', say: "Just sit down." },
      { beat: '{a} and {b} sit down together. Neither of them complains again.' },
      { by: 'd', dr: "We're basically matchmakers now. Somebody has to be. These two are hopeless on their own." },
    ] },
    { id: 'gs2.3', turns: [
      { by: 'c', say: "{a}, quick question. Favourite person in the house?" },
      { by: 'a', say: "I don't have a favourite person." },
      { by: 'd', say: "Liar." },
      { by: 'c', say: "{b}, same question." },
      { by: 'b', say: "...Pass." },
      { by: 'd', say: "Both of them passed. At the same time." },
      { by: 'c', say: "That's the loudest pass I've ever heard." },
      { beat: '{a} and {b} both suddenly need to be in other rooms.' },
      { by: 'd', dr: "Two people refusing to answer the same question, then leaving at the same time. Case closed." },
    ] },
  ],
  'story.alliance.formed.pact': [
    { id: 'af4.1', turns: [
      { by: 'a', say: "Can I make a weird offer?" },
      { by: 'b', say: "I love a weird offer." },
      { by: 'a', say: "I protect you this week. You protect me next week. And we keep doing that until there's nobody left but us." },
      { by: 'b', say: "That's not weird. That's a final two." },
      { by: 'a', say: "It's a final two with a schedule." },
      { by: 'b', say: "I like a schedule." },
      { by: 'a', say: "So yes?" },
      { by: 'b', say: "Yes. On a schedule." },
      { by: 'b', dr: "{a} made a final two sound like a timetable. Weirdly, that's the most trustworthy pitch I've heard in here." },
    ] },
    { id: 'af4.2', turns: [
      { by: 'b', say: "I keep thinking about who I could actually trust at the end." },
      { by: 'a', say: "And?" },
      { by: 'b', say: "And it's a really short list." },
      { by: 'a', say: "How short?" },
      { by: 'b', say: "You're on it." },
      { by: 'a', say: "Who else?" },
      { by: 'b', say: "That's the whole list." },
      { by: 'a', say: "...Then let's not waste it. Final two." },
      { by: 'b', say: "Final two." },
      { by: 'a', dr: "A list with one name on it. That's the best compliment this house has given me." },
    ] },
    { id: 'af4.3', room: 'backyard', turns: [
      { beat: 'Backyard. {a} and {b} are lying on the grass, side by side, not looking at each other.' },
      { by: 'a', say: "Say it first." },
      { by: 'b', say: "Say what?" },
      { by: 'a', say: "You know what. The thing we're both thinking." },
      { by: 'b', say: "That we should go to the end together?" },
      { by: 'a', say: "That." },
      { by: 'b', say: "Why did I have to say it first?" },
      { by: 'a', say: "So if it goes wrong, it was your idea." },
      { by: 'b', say: "...That's evil. Fine. Final two." },
      { by: 'b', dr: "{a} made me say it first so it's my idea. That's the most {a} thing that's ever happened. I love it." },
    ] },
  ],
  'story.alliance.checkin.solid': [
    { id: 'ak4.1', turns: [
      { by: 'a', say: "Weekly check. Still us?" },
      { by: 'b', say: "Still us." },
      { by: 'a', say: "Nobody new in your ear?" },
      { by: 'b', say: "Two people tried. I gave them nothing." },
      { by: 'a', say: "What did they want?" },
      { by: 'b', say: "To know who I'm voting with." },
      { by: 'a', say: "And you said?" },
      { by: 'b', say: "'The house.' Same as always." },
      { by: 'a', dr: "'The house.' Our code for 'none of your business'. Nobody's cracked it yet." },
    ] },
    { id: 'ak4.2', turns: [
      { by: 'b', say: "Do you ever worry I'll flip on you?" },
      { by: 'a', say: "Every day." },
      { by: 'b', say: "Wow." },
      { by: 'a', say: "Not because of you. Because of this house. It makes everyone flip eventually." },
      { by: 'b', say: "Not me." },
      { by: 'a', say: "Then prove it by being boring. Week after week. Just boring." },
      { by: 'b', say: "I can be boring." },
      { by: 'a', say: "I know. It's your best quality." },
      { by: 'b', dr: "{a} called me boring as a compliment. In here, it is one. Boring people don't get blindsided." },
    ] },
  ],
};
