// ══════════════════════════════════════════════════════════════════════
// bb/story/lines/more-couple.js — a couple who came in together
// ══════════════════════════════════════════════════════════════════════
//
// The cast's kinship can make two houseguests a couple before the door opens
// (married, engaged, partners, dating). Move-in says so in the Diary Room; the house
// does not know. A scene between them must never call them "friends" (write.js drops
// those lines for a couple), and these give them their own: the block, and the strain
// of acting like strangers. `when: { kin: 'together' }` (facts.js).

export default {
  'story.target.block.any': [
    { id: 'kc.b1', presumes: ['noms'], when: { kin: 'together' }, room: 'storage-room', turns: [
      { beat: 'Storage room. {b} slips in after {a} and pulls the door shut.' },
      { by: 'a', say: "You can't be in here. Somebody'll notice." },
      { by: 'b', say: "I don't care. You're on the block." },
      { by: 'a', say: "I know I'm on the block. I was there." },
      { by: 'b', say: "I can't even sit next to you out there. I have to act like you're just some person." },
      { by: 'a', say: "Then keep acting. If they find out about us, it's both of us next week." },
      { by: 'b', say: "I don't care about next week." },
      { by: 'a', say: "I do. One of us has to get to the end. Promise me it's you, if it's not me." },
      { beat: '{b} doesn’t answer. {b} just holds on.' },
      { by: 'b', dr: "The whole house is watching {a} like a stranger who might go home. Nobody knows I'm watching the person I love." },
    ] },
    { id: 'kc.b2', presumes: ['noms'], when: { kin: 'together' }, turns: [
      { by: 'b', say: "Hey. You okay?" },
      { by: 'a', say: "Don't. People are looking." },
      { by: 'b', say: "People always look." },
      { by: 'a', say: "Not at you and me. That's the deal. Go sit with somebody else." },
      { by: 'b', say: "I'm going to vote to keep you." },
      { by: 'a', say: "Quietly. Vote quietly. Don't campaign for me. Don't even look worried." },
      { by: 'b', say: "I am worried." },
      { by: 'a', say: "I know. Do it inside." },
      { beat: '{b} walks away and sits down next to somebody else, laughing at nothing.' },
      { by: 'a', dr: "Watching {b} pretend not to care is the worst part of this week. Worse than the block." },
    ] },
    { id: 'kc.b3', presumes: ['noms'], when: { kin: 'together' }, room: 'bedroom', turns: [
      { beat: 'Bedroom, lights out. A whisper across the gap between two beds.' },
      { by: 'b', say: "Are you awake?" },
      { by: 'a', say: "Obviously." },
      { by: 'b', say: "What do we do if it's you on Thursday?" },
      { by: 'a', say: "Then you keep going. And you win. And you tell them about us in the speech." },
      { by: 'b', say: "That's not funny." },
      { by: 'a', say: "It's a little funny." },
      { by: 'b', say: "It's not even a little bit funny." },
      { beat: 'A hand reaches across the gap. Another one takes it.' },
      { by: 'a', dr: "We came in here together. I always knew one of us might go first. I just didn't think it would feel like this." },
    ] },
  ],
  'story.life.friends.any': [
    { id: 'kc.f1', when: { kin: 'together' }, turns: [
      { by: 'a', say: "Pass the salt?" },
      { by: 'b', say: "Here you go." },
      { beat: 'Their fingers touch for a second longer than they should. Neither of them looks up.' },
      { by: 'a', say: "Thanks." },
      { by: 'b', say: "No problem." },
      { by: 'a', dr: "That's the most we've touched all day. Over salt. That's my love life now." },
      { by: 'b', dr: "Nobody saw. I checked. I always check." },
    ] },
    { id: 'kc.f2', when: { kin: 'together' }, turns: [
      { by: 'b', say: "Somebody asked me today if I knew you before." },
      { by: 'a', say: "What did you say?" },
      { by: 'b', say: "I said no. Then I said you seem nice." },
      { by: 'a', say: "'Seem nice'?" },
      { by: 'b', say: "It was the most neutral thing I could think of!" },
      { by: 'a', say: "I'm going to be 'seems nice' for the rest of my life now." },
      { by: 'b', say: "You do seem nice." },
      { by: 'a', say: "Stop it. Someone's coming." },
      { by: 'b', dr: "Every lie I tell about {a} gets a little bit harder. The 'seems nice' one nearly killed me." },
    ] },
    { id: 'kc.f3', when: { kin: 'together' }, room: 'backyard', turns: [
      { beat: 'Backyard. {a} and {b} are on opposite ends of the pool, pretending to sunbathe.' },
      { by: 'a', say: "Can you hear me?" },
      { by: 'b', say: "Barely. Why are we talking across a pool?" },
      { by: 'a', say: "Because it's the only place nobody sits between us." },
      { by: 'b', say: "This is ridiculous." },
      { by: 'a', say: "I miss you." },
      { by: 'b', say: "I'm literally right there." },
      { by: 'a', say: "Across a pool. It counts." },
      { by: 'b', dr: "We're in the same house, and I've never missed {a} more. I didn't know that was possible." },
    ] },
  ],
  'story.showmance.spark.couple': [
    { id: 'kc.s1', room: 'kitchen', turns: [
      { beat: 'Kitchen. {a} is making tea. {b} reaches past for a mug, very close, not looking.' },
      { by: 'b', say: "Excuse me." },
      { by: 'a', say: "Sure." },
      { by: 'b', say: "...You still take two sugars?" },
      { by: 'a', say: "Don't. Somebody will hear you knowing that." },
      { by: 'b', say: "I'm just being polite." },
      { by: 'a', say: "Strangers don't know how many sugars." },
      { by: 'b', say: "Then I'm a very observant stranger." },
      { by: 'a', dr: "{b} knows exactly how I take my tea. Of course {b} does. I can't let anyone see that {b} knows." },
    ] },
    { id: 'kc.s2', turns: [
      { by: 'a', say: "You looked at me at dinner." },
      { by: 'b', say: "I look at everyone at dinner." },
      { by: 'a', say: "Not like that." },
      { by: 'b', say: "Like what?" },
      { by: 'a', say: "Like you do at home. When I say something stupid." },
      { by: 'b', say: "You did say something stupid." },
      { by: 'a', say: "Somebody's going to notice." },
      { by: 'b', say: "Then stop saying stupid things." },
      { by: 'b', dr: "It's so hard not to look at {a} the normal way. My face just does it. I've had years of practice." },
    ] },
    { id: 'kc.s3', room: 'storage-room', turns: [
      { beat: 'Storage room. {a} and {b} have both come in for cereal at exactly the same moment. Again.' },
      { by: 'b', say: "This is getting suspicious." },
      { by: 'a', say: "I genuinely wanted cereal." },
      { by: 'b', say: "Four times today?" },
      { by: 'a', say: "...I wanted to see you for four seconds." },
      { by: 'b', say: "You're going to get us caught." },
      { by: 'a', say: "Worth it." },
      { beat: '{b} kisses {a} on the cheek and leaves first, holding an empty bowl.' },
      { by: 'a', dr: "Four seconds in a cupboard. That's our whole relationship in here. I'll take it." },
    ] },
    { id: 'kc.s4', turns: [
      { by: 'a', say: "Somebody said you're cute. Today. In the kitchen." },
      { by: 'b', say: "Who?" },
      { by: 'a', say: "Doesn't matter who. I had to stand there and agree like it was news." },
      { by: 'b', say: "What did you say?" },
      { by: 'a', say: "I said 'yeah, I guess'." },
      { by: 'b', say: "'You guess'?" },
      { by: 'a', say: "What was I supposed to say? 'Yes, I know, I've been telling you for years'?" },
      { by: 'b', dr: "{a} 'guesses' I'm cute. In front of the house. I'm going to bring that up for the rest of our lives." },
    ] },
    { id: 'kc.s5', room: 'living-room', turns: [
      { beat: 'Living room. {a} and {b} are on opposite ends of the sofa. Their feet are touching under a blanket.' },
      { by: 'a', say: "Don't move." },
      { by: 'b', say: "I'm not moving." },
      { by: 'a', say: "If anyone sits in the middle, we're done for." },
      { by: 'b', say: "Then look grumpy. Nobody sits next to grumpy." },
      { beat: '{a} pulls a very grumpy face at the room.' },
      { by: 'b', say: "Perfect." },
      { by: 'b', dr: "Nobody has sat between us all afternoon. {a}'s grumpy face is honestly a weapon." },
    ] },
    { id: 'kc.s6', turns: [
      { by: 'b', say: "How are we doing?" },
      { by: 'a', say: "Out loud, or for real?" },
      { by: 'b', say: "For real." },
      { by: 'a', say: "For real, I miss you, and you're right there, and it's ridiculous." },
      { by: 'b', say: "Same. Every day." },
      { by: 'a', say: "And out loud?" },
      { by: 'b', say: "Out loud, you seem nice. We should hang out some time." },
      { beat: '{a} laughs, then catches it and turns it into a cough.' },
      { by: 'a', dr: "We have two conversations at once now. The one we're having, and the one everybody else can hear." },
    ] },
  ],
  'story.showmance.declare.couple': [
    { id: 'kc.d1', room: 'bedroom', turns: [
      { beat: 'Bedroom, lights out. A whisper across the gap between two beds.' },
      { by: 'a', say: "Can I say something sappy?" },
      { by: 'b', say: "If you're quick." },
      { by: 'a', say: "Coming in here with you was the best and worst idea we've ever had." },
      { by: 'b', say: "Best because?" },
      { by: 'a', say: "Because you're here." },
      { by: 'b', say: "And worst?" },
      { by: 'a', say: "Because I can't tell anyone you're here." },
      { by: 'b', say: "...That's annoyingly sweet." },
      { by: 'b', dr: "Whatever happens in this game, I'm going home with {a}. That's the bit nobody in this house knows." },
    ] },
    { id: 'kc.d2', turns: [
      { by: 'b', say: "If they find out about us, it's over. You know that." },
      { by: 'a', say: "I know." },
      { by: 'b', say: "So if one of us has to go, it should be you or me on purpose. Not both by accident." },
      { by: 'a', say: "Are you saying you'd vote me out?" },
      { by: 'b', say: "I'm saying I'd rather you win than we both lose." },
      { by: 'a', say: "...That's the most romantic thing anyone's ever said to me, and it's about getting evicted." },
      { by: 'b', say: "That's us." },
      { by: 'a', dr: "We came in together. If it comes to it, one of us gets the other one to the end. That's the deal. That's love, in here." },
    ] },
    { id: 'kc.d3', room: 'kitchen', turns: [
      { by: 'a', say: "Can I tell you something I haven't said since we got here?" },
      { by: 'b', say: "Go on." },
      { by: 'a', say: "I love you." },
      { by: 'b', say: "...Oh, you can't just say that in the kitchen." },
      { by: 'a', say: "There's nobody here." },
      { by: 'b', say: "There's eight cameras here." },
      { by: 'a', say: "Then eight cameras know." },
      { by: 'b', say: "I love you too. Now go away before someone comes in." },
      { by: 'b', dr: "First time either of us has said it in this house. In the kitchen. Next to the bins. Perfect." },
    ] },
  ],
};