// ══════════════════════════════════════════════════════════════════════
// bb/story/lines/more-house.js — the busiest house pools, widened
// ══════════════════════════════════════════════════════════════════════
//
// The second half of the 2026-10-05 widening (see more-alliance.js): arguments,
// flirting, lobbying, the block, gossip and everyday banter air most often in a long
// season. Entries are added to the same keys (lines/index.js). Roles as in the main
// files (feud.js, showmance.js, target.js, life.js).

export default {
  // ── feud ────────────────────────────────────────────────────────────
  'story.feud.argument.any': [
    { id: 'sa2.1', turns: [
      { by: 'a', say: "Are we going to talk about it, or are we just going to keep doing this?" },
      { by: 'b', say: "Doing what?" },
      { by: 'a', say: "This. The looks. The little comments. Since {when}." },
      { by: 'b', say: "I haven't made any comments." },
      { by: 'a', say: "'Oh, look who's up.' 'Nice of you to help.' Every morning." },
      { by: 'b', say: "That's just banter." },
      { by: 'a', say: "Banter is when both people laugh!" },
      { by: 'b', say: "Then laugh!" },
      { by: 'a', say: "I'm not going to laugh at you making fun of me!" },
      { by: 'b', say: "Then stop giving me material!" },
      { beat: 'Somebody in the next room turns the music up. Neither of them notices.' },
      { by: 'a', say: "You know what? Forget it. You're not worth the energy." },
      { by: 'b', say: "Funny, you've used a lot of it." },
      { by: 'a', dr: "I wanted to clear the air. Turns out the air was full of {b}." },
      { by: 'b', dr: "Did I enjoy that? A bit. Should I have? Probably not." },
    ] },
    { id: 'sa2.2', when: { third: true }, turns: [
      { by: 'a', say: "Oh, so now you're talking about me to {c}?" },
      { by: 'b', say: "I wasn't talking about you." },
      { by: 'c', say: "We were literally talking about lunch." },
      { by: 'a', say: "And you stopped when I walked in." },
      { by: 'b', say: "Because you walked in like you were about to start something!" },
      { by: 'a', say: "I'm not starting anything. You started it. {when}." },
      { by: 'b', say: "Oh my god, are we still on that?" },
      { by: 'a', say: "Yes! We're still on that! Because you never said sorry!" },
      { by: 'b', say: "Because I didn't do anything wrong!" },
      { by: 'c', say: "Okay, I'm going to go have lunch somewhere else." },
      { beat: '{c} leaves with a plate. Neither of them watches {c} go.' },
      { by: 'a', say: "Great. Now {c} thinks I'm crazy." },
      { by: 'b', say: "That's not on me." },
      { by: 'c', dr: "I just wanted a sandwich. I walked into a war over a sandwich." },
    ] },
    { id: 'sa2.3', turns: [
      { by: 'b', say: "If you've got something to say, say it to my face." },
      { by: 'a', say: "Fine. Here's my face." },
      { by: 'b', say: "Go on, then." },
      { by: 'a', say: "You're fake. You're nice to everyone's face and then you go and do whatever you want. {when} was the proof." },
      { by: 'b', say: "That's rich, coming from you." },
      { by: 'a', say: "What's that supposed to mean?" },
      { by: 'b', say: "It means you're the fakest person in this house and everyone knows it but you." },
      { by: 'a', say: "Name one person who thinks that." },
      { by: 'b', say: "I'm not going to throw people under the bus like you do." },
      { by: 'a', say: "Because there's nobody to throw!" },
      { by: 'b', say: "Keep telling yourself that." },
      { by: 'a', dr: "{b} said 'everyone knows it'. Everyone. I've spent all afternoon wondering who 'everyone' is." },
    ] },
    { id: 'sa2.4', when: { register: ['sweet', 'shy'] }, turns: [
      { by: 'a', say: "Can I say something? I'm not good at this, so just let me say it." },
      { by: 'b', say: "Okay." },
      { by: 'a', say: "{when} really hurt. And I've been pretending it didn't. And I'm tired of pretending." },
      { by: 'b', say: "I didn't think it was a big deal." },
      { by: 'a', say: "I know you didn't. That's kind of the problem." },
      { by: 'b', say: "What do you want me to do?" },
      { by: 'a', say: "I don't know. I just wanted you to know. I'm not a doormat. Even if I act like one sometimes." },
      { beat: '{b} looks at {a} properly for the first time in days.' },
      { by: 'b', say: "...Okay. I hear you." },
      { by: 'a', dr: "My hands were shaking the whole time. But I said it. I actually said it." },
    ] },
    { id: 'sa2.5', turns: [
      { by: 'a', say: "I'm done being nice about it." },
      { by: 'b', say: "About what?" },
      { by: 'a', say: "About you! About {when}! About all of it!" },
      { by: 'b', say: "Keep your voice down, people are sleeping." },
      { by: 'a', say: "Oh, now you care about people!" },
      { by: 'b', say: "I've always cared about people!" },
      { by: 'a', say: "Except me!" },
      { by: 'b', say: "That's not— okay, you know what, I'm not doing this at midnight." },
      { by: 'a', say: "Then when? You're never available! You're always busy being everyone's best friend!" },
      { by: 'b', say: "Tomorrow. We do this tomorrow. With coffee." },
      { by: 'a', say: "...Fine. Tomorrow. With coffee." },
      { by: 'b', dr: "We are absolutely not doing it tomorrow. Tomorrow I'm going to be very busy. All day." },
    ] },
  ],
  'story.feud.friction.joke': [
    { id: 'sf2.j1', when: { third: true }, turns: [
      { by: 'a', say: "Hey {c}, have you ever seen {b} try to do a push-up?" },
      { by: 'b', say: "Don't." },
      { by: 'a', say: "It's like watching a fish on a dock." },
      { by: 'c', say: "Stop, that's mean." },
      { by: 'c', say: "...Can you do it again, though?" },
      { beat: '{a} does a very floppy impression. {c} cries laughing.' },
      { by: 'b', say: "I've done four push-ups today. That's four more than {a}'s ever seen me do." },
      { by: 'a', say: "That's the spirit!" },
      { by: 'b', dr: "I'm laughing on the outside. On the inside, I'm doing push-ups out of spite, and {a} will never see them." },
    ] },
    { id: 'sf2.j2', turns: [
      { by: 'a', say: "Morning, sunshine." },
      { by: 'b', say: "Morning." },
      { by: 'a', say: "Wow. Rough night? You look like you slept in a hedge." },
      { by: 'b', say: "Thanks." },
      { by: 'a', say: "I mean it nicely. A nice hedge." },
      { by: 'b', say: "There's no nice way to say hedge." },
      { by: 'a', say: "A designer hedge." },
      { by: 'b', say: "Please stop talking to me until I've had coffee." },
      { by: 'b', dr: "{a} thinks {a} is the funniest person in this house. {a} is the loudest. That's not the same thing." },
    ] },
    { id: 'sf2.j3', turns: [
      { by: 'b', say: "Why did you tell everyone I snore?" },
      { by: 'a', say: "Because you do." },
      { by: 'b', say: "Maybe. But you didn't have to announce it at dinner." },
      { by: 'a', say: "It was funny!" },
      { by: 'b', say: "It was funny to you. Now nobody wants the bed next to me." },
      { by: 'a', say: "That's not my fault, that's your nose's fault." },
      { by: 'b', say: "I'm moving my bed next to yours, then." },
      { by: 'a', say: "Don't you dare." },
      { by: 'b', dr: "Revenge is a dish best served at two in the morning, very loudly, right next to {a}'s ear." },
    ] },
  ],
  'story.feud.apology.refused': [
    { id: 'sp2.r1', turns: [
      { by: 'a', say: "I just want to say I'm sorry for {when}." },
      { by: 'b', say: "Okay." },
      { by: 'a', say: "...Okay?" },
      { by: 'b', say: "Okay, I heard you." },
      { by: 'a', say: "Are we good?" },
      { by: 'b', say: "We're not bad." },
      { by: 'a', say: "That's not the same as good." },
      { by: 'b', say: "No. It isn't." },
      { by: 'a', dr: "'We're not bad.' That's where we are. Somewhere between not bad and not good, for the rest of the season." },
    ] },
    { id: 'sp2.r2', turns: [
      { by: 'a', say: "Can we please just move on?" },
      { by: 'b', say: "You can. I'm not there yet." },
      { by: 'a', say: "I said I'm sorry. I've said it three times." },
      { by: 'b', say: "And I heard you all three times." },
      { by: 'a', say: "So what more do you want?" },
      { by: 'b', say: "Time. I want time. You can't apologise someone into being okay." },
      { by: 'a', say: "...Fine. Take your time." },
      { by: 'b', dr: "{a} wants a quick fix because {a} feels bad. That's {a}'s problem. I'm not rushing for anybody." },
    ] },
    { id: 'sp2.r3', when: { register: ['fiery'] }, turns: [
      { by: 'a', say: "Look, I'm sorry, okay?" },
      { by: 'b', say: "Don't 'okay' me." },
      { by: 'a', say: "I'm trying to apologise!" },
      { by: 'b', say: "You're shouting an apology at me!" },
      { by: 'a', say: "Because you won't listen to a normal one!" },
      { by: 'b', say: "A normal one would've been days ago!" },
      { by: 'a', say: "...Fair. That's fair." },
      { by: 'b', say: "Come back when you can do it without shouting." },
      { by: 'a', dr: "Shouting an apology was a bad idea. I see that now. I saw it about halfway through." },
    ] },
  ],

  // ── showmance ───────────────────────────────────────────────────────
  'story.showmance.spark.any': [
    { id: 'sm2.1', turns: [
      { by: 'b', say: "Why are you looking at me like that?" },
      { by: 'a', say: "Like what?" },
      { by: 'b', say: "Like you're about to say something stupid." },
      { by: 'a', say: "I was going to say you look nice today." },
      { by: 'b', say: "...That's not stupid." },
      { by: 'a', say: "It felt stupid in my head." },
      { by: 'b', say: "Say it again." },
      { by: 'a', say: "No! Once was hard enough." },
      { by: 'b', dr: "{a} went bright red. I'm going to think about that for the rest of the day." },
    ] },
    { id: 'sm2.2', room: 'kitchen', turns: [
      { beat: 'Kitchen. {a} is cooking. {b} is sitting on the counter, eating the ingredients.' },
      { by: 'a', say: "That's for the recipe." },
      { by: 'b', say: "I'm taste-testing." },
      { by: 'a', say: "You've eaten half the cheese." },
      { by: 'b', say: "It needed testing." },
      { by: 'a', say: "Get off my counter." },
      { by: 'b', say: "Make me." },
      { beat: 'Neither of them moves. {a} keeps cooking with {b} still sitting there.' },
      { by: 'a', dr: "If anyone else ate my cheese, I'd lose my mind. {b} eats it and I just… let it happen." },
    ] },
    { id: 'sm2.3', turns: [
      { by: 'a', say: "Truth or dare." },
      { by: 'b', say: "We're not twelve." },
      { by: 'a', say: "Truth or dare." },
      { by: 'b', say: "...Truth." },
      { by: 'a', say: "Who in this house would you date? Outside." },
      { by: 'b', say: "That's not fair." },
      { by: 'a', say: "It's truth. You picked it." },
      { by: 'b', say: "Fine. Somebody very annoying who asks stupid questions." },
      { by: 'a', say: "Oh. Huh." },
      { by: 'b', say: "Your turn. Truth or dare." },
      { by: 'b', dr: "I picked truth so I wouldn't have to do anything embarrassing. I did something way more embarrassing." },
    ] },
    { id: 'sm2.4', room: 'backyard', turns: [
      { beat: 'Backyard. {a} is trying to teach {b} a card trick. It is not going well.' },
      { by: 'a', say: "No, you hold it like this." },
      { beat: '{a} moves {b}’s fingers into place. Then doesn’t let go.' },
      { by: 'b', say: "Like this?" },
      { by: 'a', say: "Like… yeah. Like that." },
      { by: 'b', say: "You're still holding my hand." },
      { by: 'a', say: "I'm teaching you the trick." },
      { by: 'b', say: "The trick's finished." },
      { by: 'a', say: "...It's a long trick." },
      { by: 'a', dr: "There was no trick. There was never a trick. I don't know any card tricks." },
    ] },
    { id: 'sm2.5', turns: [
      { by: 'b', say: "Can you braid hair?" },
      { by: 'a', say: "Badly." },
      { by: 'b', say: "Badly's fine." },
      { beat: '{a} sits behind {b} and starts braiding. Very slowly.' },
      { by: 'b', say: "You're taking forever." },
      { by: 'a', say: "I'm being careful." },
      { by: 'b', say: "You're being slow." },
      { by: 'a', say: "Careful and slow are the same thing." },
      { by: 'b', dr: "It took {a} twenty minutes to do one braid. I didn't complain once." },
    ] },
    { id: 'sm2.6', when: { third: true }, turns: [
      { by: 'c', say: "Are you two going to tell us, or…" },
      { by: 'a', say: "Tell you what?" },
      { by: 'c', say: "Whatever this is." },
      { by: 'b', say: "There's no 'this'." },
      { by: 'c', say: "You've been sitting on the same sofa cushion for an hour. There are four cushions." },
      { by: 'a', say: "It's the comfy one." },
      { by: 'c', say: "They're all the same cushion!" },
      { by: 'c', dr: "Everyone in this house can see it. Everyone. Except the two people sitting on one cushion." },
    ] },
  ],

  // ── target ──────────────────────────────────────────────────────────
  'story.target.lobby.lands': [
    { id: 'tl2.1', presumes: ['noms'], turns: [
      { by: 'a', say: "I'm not going to give you a big speech." },
      { by: 'b', say: "Thank god." },
      { by: 'a', say: "Just one thing. If I stay, I owe you. Not the house. You." },
      { by: 'b', say: "Owe me what?" },
      { by: 'a', say: "Whatever you need. A vote. A heads-up. A save." },
      { by: 'b', say: "That's a big promise." },
      { by: 'a', say: "That's why it's the only thing I'm saying." },
      { by: 'b', say: "...Okay. I'll keep that in mind." },
      { by: 'b', dr: "No crying, no begging, just a deal. {a} knows how to campaign." },
    ] },
    { id: 'tl2.2', presumes: ['noms'], turns: [
      { by: 'a', say: "Do you have a minute? I know everyone's been coming at you." },
      { by: 'b', say: "You're the fifth person today." },
      { by: 'a', say: "Then I'll be quick. Who would you rather live with next week? Me or {target}?" },
      { by: 'b', say: "That's not fair." },
      { by: 'a', say: "It's the only question that matters." },
      { by: 'b', say: "...You. Probably you." },
      { by: 'a', say: "Then vote like it." },
      { by: 'a', dr: "You don't ask for a vote. You ask a question where the answer is the vote." },
    ] },
    { id: 'tl2.3', room: 'backyard', presumes: ['noms'], turns: [
      { beat: '{a} sits down next to {b} on the edge of the pool.' },
      { by: 'a', say: "I'm scared." },
      { by: 'b', say: "I know." },
      { by: 'a', say: "And I hate asking, because I know you're in a weird spot." },
      { by: 'b', say: "I am in a weird spot." },
      { by: 'a', say: "But I'd do it for you. If it was you up there, I'd do it for you. You know I would." },
      { by: 'b', say: "...I know you would." },
      { by: 'a', say: "So?" },
      { by: 'b', say: "So I'm thinking about it. Seriously." },
      { by: 'b', dr: "{a} would do it for me. That's the thing. {a} really would. I keep coming back to that." },
    ] },
    { id: 'tl2.4', presumes: ['noms'], turns: [
      { by: 'a', say: "Okay, I made a list." },
      { by: 'b', say: "Of course you did." },
      { by: 'a', say: "Reasons to keep me. One: I've never put you up. Two: I'm not a comp threat. Three: I'm funny." },
      { by: 'b', say: "Are you, though?" },
      { by: 'a', say: "Four: I have a great sense of humour about not being funny." },
      { beat: '{b} laughs despite everything.' },
      { by: 'b', say: "Okay, that was funny." },
      { by: 'a', say: "Is that a vote?" },
      { by: 'b', say: "It's a maybe with a laugh in it." },
      { by: 'a', dr: "A maybe with a laugh in it. That's better than most yeses I've had this week." },
    ] },
    { id: 'tl2.5', presumes: ['noms'], when: { band: ['cold', 'neutral'] }, turns: [
      { by: 'a', say: "I know we're not close." },
      { by: 'b', say: "We're really not." },
      { by: 'a', say: "And I know you've got no reason to save me." },
      { by: 'b', say: "That's true too." },
      { by: 'a', say: "But {target} has a reason to come after you. I don't. Think about that." },
      { by: 'b', say: "Why would {target} come after me?" },
      { by: 'a', say: "Ask {target} who's on the list for next week. Watch the face." },
      { by: 'b', say: "...Okay. I'll ask." },
      { by: 'a', dr: "If I can't make {b} like me, I can make {b} scared of {target}. Scared votes count the same." },
    ] },
    { id: 'tl2.6', presumes: ['noms'], turns: [
      { by: 'a', say: "Can I tell you something nobody else knows?" },
      { by: 'b', say: "That depends." },
      { by: 'a', say: "{target} has a final two. And it's not with you." },
      { by: 'b', say: "How do you know?" },
      { by: 'a', say: "Because {target} offered me one first. I said no." },
      { by: 'b', say: "...Seriously?" },
      { by: 'a', say: "Seriously. So keep that in mind when you vote." },
      { by: 'b', dr: "I can't check if that's true. Which is exactly why it's going to work on me." },
    ] },
    { id: 'tl2.7', presumes: ['noms'], turns: [
      { by: 'a', say: "I just wanted to say thank you." },
      { by: 'b', say: "For what?" },
      { by: 'a', say: "For not avoiding me. Everybody avoids you when you're on the block. You didn't." },
      { by: 'b', say: "You're still a person." },
      { by: 'a', say: "Not in here, I'm not. In here I'm a nominee." },
      { by: 'b', say: "You're a person to me." },
      { by: 'a', say: "...Then would you vote like I'm a person?" },
      { by: 'b', say: "Ha. Okay. Smooth. Yeah. I think I will." },
      { by: 'b', dr: "{a} turned a thank-you into a vote pitch so smoothly I didn't see it coming. Respect." },
    ] },
  ],
  'story.target.block.any': [
    { id: 'tb2.1', presumes: ['noms'], room: 'bedroom', turns: [
      { beat: 'Bedroom, late. {a} is lying on top of the covers, wide awake. {b} sits on the next bed.' },
      { by: 'b', say: "You're not asleep." },
      { by: 'a', say: "Nobody on the block sleeps." },
      { by: 'b', say: "You've got to try." },
      { by: 'a', say: "Every time I close my eyes, I count votes." },
      { by: 'b', say: "What do you get?" },
      { by: 'a', say: "Depends. Sometimes four. Sometimes two." },
      { by: 'b', say: "Then it's not decided. Go to sleep on four." },
      { by: 'a', say: "...Okay. Four." },
      { by: 'a', dr: "'Go to sleep on four.' Best advice anyone's given me in here." },
    ] },
    { id: 'tb2.2', presumes: ['noms'], turns: [
      { by: 'a', say: "Did I do something wrong? Like, actually?" },
      { by: 'b', say: "No. You were just the easiest name to say." },
      { by: 'a', say: "That's worse." },
      { by: 'b', say: "I know. I'm sorry. But it means it's not personal. And not personal can be changed." },
      { by: 'a', say: "How?" },
      { by: 'b', say: "Make it harder to say your name. Talk to everyone. Be impossible to forget." },
      { by: 'a', say: "Be impossible to forget." },
      { by: 'b', say: "Starting tonight." },
      { by: 'a', dr: "{b} gave me a plan. I didn't have a plan. Now I have a plan." },
    ] },
    { id: 'tb2.3', presumes: ['noms'], turns: [
      { by: 'b', say: "You've been cleaning the same counter for twenty minutes." },
      { by: 'a', say: "It's dirty." },
      { by: 'b', say: "It's been clean for nineteen of those minutes." },
      { by: 'a', say: "...I don't know what else to do with my hands." },
      { by: 'b', say: "Come sit down." },
      { by: 'a', say: "If I sit down, I'll think." },
      { by: 'b', say: "Then think with me. Out loud. It's better than thinking at a counter." },
      { by: 'a', dr: "{b} saw I was falling apart and didn't make a big thing of it. Just told me to sit down. I sat down." },
    ] },
    { id: 'tb2.4', presumes: ['noms'], when: { band: 'friends' }, turns: [
      { by: 'b', say: "Whatever happens Thursday, I'm with you." },
      { by: 'a', say: "You don't have to say that." },
      { by: 'b', say: "I know I don't. I'm saying it anyway." },
      { by: 'a', say: "Even if it costs you?" },
      { by: 'b', say: "If keeping my friend costs me, then fine. It costs me." },
      { beat: '{a} tries to say something and can’t.' },
      { by: 'a', say: "...Thank you." },
      { by: 'b', say: "Don't cry. If you cry, I'll cry, and then we're both a mess on camera." },
      { by: 'b', dr: "Game says I should keep my distance this week. I don't care what the game says." },
    ] },
    { id: 'tb2.5', presumes: ['noms'], turns: [
      { by: 'a', say: "Can you do something for me?" },
      { by: 'b', say: "Anything." },
      { by: 'a', say: "Find out where {target}'s votes are. Quietly. I can't ask, everyone watches me now." },
      { by: 'b', say: "You want me to be your spy." },
      { by: 'a', say: "I want you to be my eyes. Spies are worse." },
      { by: 'b', say: "...Fine. Your eyes. Give me till tonight." },
      { by: 'a', dr: "When you're on the block, every room goes quiet when you walk in. You need someone who can walk in for you." },
    ] },
  ],
  'story.target.gossip.any': [
    { id: 'tg2.1', turns: [
      { by: 'a', say: "Okay, I'm not saying anything." },
      { by: 'b', say: "But you're about to." },
      { by: 'a', say: "But I'm about to. {target} and the HOH. Forty minutes. Door shut." },
      { by: 'b', say: "Forty?" },
      { by: 'a', say: "I counted. There's only so many times you can walk past a door before it gets weird." },
      { by: 'b', say: "How many times did you walk past?" },
      { by: 'a', say: "Seven." },
      { by: 'b', say: "That's weird." },
      { by: 'a', say: "It was weird. But I got the number." },
      { by: 'b', dr: "Forty minutes with the HOH. I'm not going to sleep tonight." },
    ] },
    { id: 'tg2.2', turns: [
      { by: 'b', say: "Who do you think's running this house right now?" },
      { by: 'a', say: "Honestly?" },
      { by: 'b', say: "Honestly." },
      { by: 'a', say: "{target}. Quietly. Nobody sees it." },
      { by: 'b', say: "{target}? Really?" },
      { by: 'a', say: "Every plan this week ended up exactly where {target} wanted. Every one." },
      { by: 'b', say: "...Huh. Now that you say it." },
      { by: 'a', say: "Now that I say it, you'll see it everywhere." },
      { by: 'b', dr: "I didn't think about {target} once this morning. Now I can't think about anything else." },
    ] },
    { id: 'tg2.3', turns: [
      { by: 'a', say: "Can I ask you something weird?" },
      { by: 'b', say: "Always." },
      { by: 'a', say: "Has {target} ever asked you who you trust? Like, straight out?" },
      { by: 'b', say: "...Yeah. Actually. A few days ago." },
      { by: 'a', say: "Me too. And I said a name. And now that person won't talk to me." },
      { by: 'b', say: "Oh no." },
      { by: 'a', say: "Oh yes." },
      { by: 'b', say: "Who did I say? What did I say?" },
      { by: 'b', dr: "I need to remember exactly what I told {target}. I'm going to be up all night doing it." },
    ] },
    { id: 'tg2.4', room: 'bedroom', turns: [
      { beat: '{a} and {b} are folding laundry, very slowly, in the corner of the bedroom.' },
      { by: 'a', say: "Don't look up. {target} just walked past that door for the third time." },
      { by: 'b', say: "Why?" },
      { by: 'a', say: "Because every time two people talk quietly, {target} wants to know why." },
      { by: 'b', say: "Then let's give {target} something to wonder about." },
      { by: 'a', say: "Like what?" },
      { by: 'b', say: "Laugh like I just said something amazing." },
      { beat: '{a} laughs, very loudly. Outside the door, footsteps stop. Then they move on.' },
      { by: 'b', dr: "We were talking about socks. {target} is now going to spend all night wondering what was so funny about socks." },
    ] },
  ],

  // ── life ────────────────────────────────────────────────────────────
  'story.life.banter.any': [
    { id: 'lb2.1', turns: [
      { by: 'a', say: "If this house was a hotel, how many stars?" },
      { by: 'b', say: "Two." },
      { by: 'a', say: "Two? Harsh." },
      { by: 'b', say: "One for the pool. One for the fact that the fridge works." },
      { by: 'a', say: "What about the beds?" },
      { by: 'b', say: "The beds take a star away. It's one star." },
      { by: 'a', say: "One star. Would not recommend." },
      { by: 'b', say: "Would not recommend. Staff watch you sleep." },
      { by: 'a', dr: "One star. Staff watch you sleep. Free food, though. Honestly, still one star." },
    ] },
    { id: 'lb2.2', when: { third: true }, turns: [
      { by: 'a', say: "Okay, hot take. Breakfast for dinner is better than dinner for dinner." },
      { by: 'b', say: "Wrong." },
      { by: 'c', say: "So wrong." },
      { by: 'a', say: "Pancakes at night!" },
      { by: 'b', say: "Pancakes at night is a cry for help." },
      { by: 'c', say: "It's what you eat when you've given up." },
      { by: 'a', say: "Then I've given up and I'm happier than both of you." },
      { by: 'b', say: "...Okay, that's a fair point." },
      { by: 'c', dr: "We had pancakes for dinner. It was great. I'm never admitting that to {a}." },
    ] },
    { id: 'lb2.3', presumes: ['hoh'], turns: [
      { by: 'b', say: "What's the first song you're putting on when you get out?" },
      { by: 'a', say: "Anything. Literally anything. I'd listen to a car alarm." },
      { by: 'b', say: "A car alarm?" },
      { by: 'a', say: "It's music if you've had none for weeks." },
      { by: 'b', say: "I've been humming the same song for three days." },
      { by: 'a', say: "I know. I can hear you. Everyone can hear you." },
      { by: 'b', say: "Is that why people keep leaving the room?" },
      { by: 'a', say: "That's exactly why." },
      { by: 'b', dr: "I'm humming it again right now. I can't stop. Send help." },
    ] },
    { id: 'lb2.4', when: { third: true }, turns: [
      { by: 'c', say: "Okay, I'm bored. Somebody tell me a secret." },
      { by: 'a', say: "Absolutely not." },
      { by: 'b', say: "Not in this house." },
      { by: 'c', say: "A fake secret, then." },
      { by: 'a', say: "Fine. I once beat a champion at chess." },
      { by: 'b', say: "Is that fake?" },
      { by: 'a', say: "Completely fake. I don't know how the horse moves." },
      { by: 'c', say: "That's the worst fake secret I've ever heard." },
      { by: 'b', say: "I'm a secret agent." },
      { by: 'c', say: "Better. Slightly." },
      { by: 'a', dr: "We played 'fake secrets' for an hour. In a house where everyone has real ones. It was weirdly relaxing." },
    ] },
    { id: 'lb2.5', turns: [
      { by: 'a', say: "I'm going to ask Big Brother for more toilet paper." },
      { by: 'b', say: "Again?" },
      { by: 'a', say: "Somebody in this house is eating it." },
      { by: 'b', say: "Nobody is eating it." },
      { by: 'a', say: "Then where is it going?" },
      { by: 'b', say: "There are a lot of people in here." },
      { by: 'a', say: "Not that many. Not that much." },
      { by: 'b', dr: "{a} has a theory that someone is hoarding toilet paper. {a} has been checking bags. {a} might be losing it." },
    ] },
    { id: 'lb2.6', turns: [
      { by: 'b', say: "Do you think the cameras get bored of us?" },
      { by: 'a', say: "Today? Definitely." },
      { by: 'b', say: "We've been lying on this floor for an hour." },
      { by: 'a', say: "It's a good floor." },
      { by: 'b', say: "It's a great floor. Cool. Flat." },
      { by: 'a', say: "Never lets you down." },
      { by: 'b', say: "Somewhere, someone is watching us lie on a floor." },
      { by: 'a', say: "Hi. Sorry. It's a slow day." },
      { by: 'a', dr: "Not every day in here is drama. Some days you just lie on the floor and apologise to the cameras." },
    ] },
    { id: 'lb2.7', when: { third: true }, turns: [
      { by: 'a', say: "Who's the worst at the comps? Be honest." },
      { by: 'b', say: "Me." },
      { by: 'c', say: "Definitely {b}." },
      { by: 'b', say: "You didn't have to agree so fast." },
      { by: 'c', say: "You fell off the thing." },
      { by: 'b', say: "Everybody fell off the thing!" },
      { by: 'a', say: "You fell off it before it started moving." },
      { by: 'b', say: "...That's fair. I'm the worst." },
      { by: 'b', dr: "I'm not here to win comps. I'm here to make it to the end without anyone noticing I can't win comps." },
    ] },
    { id: 'lb2.8', room: 'bathroom', turns: [
      { beat: '{a} is trying to cut a fringe in the bathroom mirror. {b} walks in.' },
      { by: 'b', say: "No. Absolutely not. Put the scissors down." },
      { by: 'a', say: "I'm bored." },
      { by: 'b', say: "Boredom is not a haircut." },
      { by: 'a', say: "It's a little bit a haircut." },
      { by: 'b', say: "Give me the scissors." },
      { beat: '{a} hands them over, very reluctantly.' },
      { by: 'b', dr: "I've saved one person's life in this house. Well, one person's hair. Same thing, on TV." },
    ] },
  ],
  'story.life.friends.any': [
    { id: 'lf2.1', turns: [
      { by: 'a', say: "If one of us goes home this week—" },
      { by: 'b', say: "Nope." },
      { by: 'a', say: "I'm just saying—" },
      { by: 'b', say: "Nope. We're not doing the goodbye speech early." },
      { by: 'a', say: "Fine. But if we do—" },
      { by: 'b', say: "If we do, I'll miss you like crazy. Done. Speech over." },
      { by: 'a', say: "...That was a good speech." },
      { by: 'b', dr: "I'm not doing goodbyes before I have to. That's how you jinx it." },
    ] },
    { id: 'lf2.2', turns: [
      { by: 'b', say: "You saved me the last yoghurt." },
      { by: 'a', say: "I did." },
      { by: 'b', say: "The strawberry one." },
      { by: 'a', say: "I know you like the strawberry one." },
      { by: 'b', say: "That's the nicest thing anyone's done for me in here." },
      { by: 'a', say: "It's a yoghurt." },
      { by: 'b', say: "It's not a yoghurt. It's a statement." },
      { by: 'b', dr: "People think alliances are made with speeches. Mine was made with a yoghurt." },
    ] },
    { id: 'lf2.3', turns: [
      { by: 'a', say: "Can I just sit here? I don't want to talk about the game." },
      { by: 'b', say: "Then we won't." },
      { by: 'a', say: "What do we talk about?" },
      { by: 'b', say: "Anything. What did you want to be when you were little?" },
      { by: 'a', say: "...An astronaut. You?" },
      { by: 'b', say: "A dinosaur." },
      { by: 'a', say: "Like a scientist who studies dinosaurs?" },
      { by: 'b', say: "No. A dinosaur." },
      { by: 'a', dr: "Half an hour about dinosaurs. Not a single word about the game. Best half hour of my week." },
    ] },
  ],
  'story.life.homesick.helped': [
    { id: 'lh2.1', turns: [
      { by: 'b', say: "What's wrong?" },
      { by: 'a', say: "Nothing. I just miss normal." },
      { by: 'b', say: "What's normal?" },
      { by: 'a', say: "Opening the fridge and it being my fridge. Going to bed when I want. Not being watched." },
      { by: 'b', say: "We've got a fridge." },
      { by: 'a', say: "It's not my fridge." },
      { by: 'b', say: "Then we'll make it your fridge. You get the whole top shelf." },
      { by: 'a', say: "...The whole top shelf?" },
      { by: 'b', say: "The whole top shelf. Don't tell anyone." },
      { by: 'a', dr: "{b} gave me a shelf. A whole shelf. I put three things on it. I've never felt more at home." },
    ] },
    { id: 'lh2.2', turns: [
      { by: 'a', say: "Do you ever forget what it's like outside?" },
      { by: 'b', say: "All the time." },
      { by: 'a', say: "I tried to remember what rain sounds like." },
      { by: 'b', say: "And?" },
      { by: 'a', say: "I couldn't." },
      { by: 'b', say: "Close your eyes." },
      { beat: '{b} drums very gently on the table with {b.posAdj} fingertips.' },
      { by: 'a', say: "...That's really bad rain." },
      { by: 'b', say: "It's the best I've got." },
      { by: 'a', dr: "It sounded nothing like rain. It was perfect." },
    ] },
    { id: 'lh2.3', turns: [
      { beat: '{a} is sitting by the memory wall, looking at nothing in particular.' },
      { by: 'b', say: "Penny for them." },
      { by: 'a', say: "Just thinking about home." },
      { by: 'b', say: "Good thoughts or bad thoughts?" },
      { by: 'a', say: "Good thoughts. That's the problem. The good ones make it worse." },
      { by: 'b', say: "Then tell me one. Out loud. It's better out loud." },
      { by: 'a', say: "...Sunday mornings. Not having to be anywhere." },
      { by: 'b', say: "That's a good one." },
      { by: 'a', dr: "Saying it out loud helped. I don't know why. It just did." },
    ] },
  ],
};
