// ══════════════════════════════════════════════════════════════════════
// bb/story/lines/scheme.js — a lie told, and the day it comes out
// ══════════════════════════════════════════════════════════════════════
//
// Written against docs/bb-dialogue-style.md. Each entry is a WHOLE scene.
//   lie      a lies to b about {target} (who is not in the room)   believed | rejected
//   caught   a confronts b, who has been lying; the lie is on record (aired or recapped)
// Only villains and qualifying neutrals scheme (bb-events/schemes.js decides who);
// the words never make a nice archetype the liar.

export default {
  'story.scheme.lie.believed': [
    { id: 'sl.b1', presumes: ['hoh'], turns: [
      { by: 'a', say: "I wasn't going to say anything." },
      { by: 'b', say: "But?" },
      { by: 'a', say: "But you'd want to know. {target} said your name. To the HOH. Yesterday." },
      { by: 'b', say: "My name? For what?" },
      { by: 'a', say: "For the block." },
      { by: 'b', say: "You're joking." },
      { by: 'a', say: "I wish I was." },
      { by: 'b', say: "{target} told me we were good. Like, this morning." },
      { by: 'a', say: "{target} tells everybody they're good." },
      { by: 'a', dr: "Did {target} say it? No idea. Does {b} believe it? Completely. That's all that matters." },
    ] },
    { id: 'sl.b2', turns: [
      { by: 'a', say: "Can I be honest with you about something?" },
      { by: 'b', say: "Of course." },
      { by: 'a', say: "Be careful with {target}." },
      { by: 'b', say: "Why? What happened?" },
      { by: 'a', say: "I just heard some stuff. About you. From {target}. I don't want to repeat it." },
      { by: 'b', say: "No, repeat it. Please." },
      { by: 'a', say: "Just… {target} doesn't think you're as smart as you think you are. That's the nice version." },
      { by: 'b', say: "Wow." },
      { by: 'a', say: "I'm sorry. I thought you should know." },
      { by: 'b', dr: "I knew it. I knew {target} was two-faced. I just didn't know about which face." },
      { by: 'a', dr: "I didn't even have to make anything up. I just had to look sad and say 'I don't want to repeat it'." },
    ] },
    { id: 'sl.b3', turns: [
      { by: 'a', say: "Did you know {target} has a final two?" },
      { by: 'b', say: "With who?" },
      { by: 'a', say: "Doesn't matter with who. It's not with you." },
      { by: 'b', say: "{target} said I was the final two." },
      { by: 'a', say: "Oh. Oh no." },
      { by: 'b', say: "What?" },
      { by: 'a', say: "Nothing. Forget I said anything." },
      { by: 'b', say: "I can't forget it now!" },
      { by: 'a', dr: "'Forget I said anything.' Nobody in the history of this show has ever forgotten. That's why you say it." },
    ] },
    { id: 'sl.b4', turns: [
      { by: 'a', say: "Hey, so, weird thing." },
      { by: 'b', say: "Okay?" },
      { by: 'a', say: "{target} asked me who you're voting for this week. Like, really pushed for it." },
      { by: 'b', say: "Why would {target} care?" },
      { by: 'a', say: "That's what I thought. Why would {target} care, unless {target}'s counting you on the other side?" },
      { by: 'b', say: "...Huh." },
      { by: 'a', say: "I didn't tell {target} anything, obviously." },
      { by: 'b', say: "Thank you." },
      { by: 'a', dr: "{target} never asked me anything. But now {b} is going to avoid {target} all week. And {b} talking to {target} was the one thing I couldn't have." },
    ] },
    { id: 'sl.b5', when: { register: ['schemer'] }, turns: [
      { by: 'a', say: "I feel like I have to tell you this, as your friend." },
      { by: 'b', say: "That sounds bad." },
      { by: 'a', say: "{target} has been doing an impression of you. Behind your back. People were laughing." },
      { by: 'b', say: "What kind of impression?" },
      { by: 'a', say: "I'd rather not." },
      { by: 'b', say: "Please. I want to know." },
      { by: 'a', say: "The way you talk when you're stressed. It was… mean. I didn't laugh, for the record." },
      { by: 'b', say: "I can't believe {target} would do that." },
      { by: 'a', say: "I couldn't either." },
      { by: 'a', dr: "There was no impression. But {b} doesn't know that. And now {b} never will, because {b} will never ask {target}." },
    ] },
    { id: 'sl.b6', presumes: ['hoh'], turns: [
      { by: 'a', say: "Don't look now, but {target} keeps watching you." },
      { by: 'b', say: "What? Where?" },
      { by: 'a', say: "I said don't look!" },
      { by: 'b', say: "Sorry! Why's {target} watching me?" },
      { by: 'a', say: "I heard {target} thinks you're the biggest threat in the house. Bigger than the HOH." },
      { by: 'b', say: "Me? I haven't even won anything!" },
      { by: 'a', say: "That's what makes you scary, apparently." },
      { by: 'b', dr: "I've been nothing but nice to {target}. And this is what I get." },
    ] },
  ],
  'story.scheme.lie.rejected': [
    { id: 'sl.r1', turns: [
      { by: 'a', say: "So I heard {target} said something about you." },
      { by: 'b', say: "Did you?" },
      { by: 'a', say: "Yeah. Something about your game. That you're—" },
      { by: 'b', say: "Who did you hear it from?" },
      { by: 'a', say: "...People." },
      { by: 'b', say: "People. Right." },
      { by: 'b', say: "I'll ask {target} myself, then." },
      { by: 'a', say: "Don't— you don't have to do that." },
      { by: 'b', say: "Why not? If it's true, {target} will say so." },
      { by: 'b', dr: "When somebody won't tell you where they heard something, it's because they heard it from themselves." },
    ] },
    { id: 'sl.r2', turns: [
      { by: 'a', say: "Be careful with {target}. That's all I'm saying." },
      { by: 'b', say: "Why?" },
      { by: 'a', say: "{target}'s not who you think." },
      { by: 'b', say: "{target} has been nothing but straight with me." },
      { by: 'a', say: "That's what {target} wants you to think." },
      { by: 'b', say: "Or that's what you want me to think." },
      { by: 'a', say: "Wow. Okay." },
      { by: 'b', dr: "{a} wants me away from {target}. Which tells me {target} is worth staying close to." },
    ] },
    { id: 'sl.r3', presumes: ['hoh'], turns: [
      { by: 'a', say: "Did you know {target} wants you out?" },
      { by: 'b', say: "No. Because {target} doesn't." },
      { by: 'a', say: "How do you know?" },
      { by: 'b', say: "Because I asked. Yesterday. Straight out. And {target} looked me in the eye." },
      { by: 'a', say: "People lie looking you in the eye." },
      { by: 'b', say: "Yeah. They do." },
      { beat: '{b} looks at {a} for a second too long.' },
      { by: 'a', dr: "{b} looked at me like I was the liar. Which, to be fair." },
    ] },
    { id: 'sl.r4', presumes: ['vote'], turns: [
      { by: 'a', say: "I don't want to be dramatic, but {target} is coming for you." },
      { by: 'b', say: "You said that about two other people last week." },
      { by: 'a', say: "And was I wrong?" },
      { by: 'b', say: "Yes! They're both still here, and neither of them came for me!" },
      { by: 'a', say: "Yet." },
      { by: 'b', say: "Go tell someone else. I'm out of the market for warnings." },
      { by: 'b', dr: "{a} has been 'warning' me about somebody every week. Funny how it's never {a}." },
    ] },
    { id: 'sl.r5', when: { band: 'cold' }, turns: [
      { by: 'a', say: "I think you should know something about {target}." },
      { by: 'b', say: "I think I'll pass." },
      { by: 'a', say: "You don't even know what it is." },
      { by: 'b', say: "I know who it's coming from." },
      { by: 'a', say: "That's not fair." },
      { by: 'b', say: "Neither are you, mostly." },
      { by: 'a', dr: "{b} doesn't trust me. Fine. That just means I need someone {b} does trust to say it for me." },
    ] },
  ],
  'story.scheme.caught.any': [
    { id: 'sx.1', turns: [
      { by: 'a', say: "So I talked to {target}." },
      { by: 'b', say: "...Okay?" },
      { by: 'a', say: "And {target} never said any of it. Not one word. Not my name, not the HOH, none of it." },
      { by: 'b', say: "That's what {target} told you." },
      { by: 'a', say: "And I believe {target}. You want to know why?" },
      { by: 'b', say: "Why?" },
      { by: 'a', say: "Because I asked three other people. And the only person who heard it was you." },
      { beat: 'Silence.' },
      { by: 'b', say: "I must have misunderstood something." },
      { by: 'a', say: "No. You understood it perfectly. You just made it up." },
      { by: 'a', dr: "I almost went after {target} because of {b}. I almost did it. That's what scares me." },
      { by: 'b', dr: "Busted. Completely. I'm not going to pretend I'm not." },
    ] },
    { id: 'sx.2', when: { third: true }, turns: [
      { by: 'a', say: "Can everyone just— can everyone come in here for a second?" },
      { by: 'c', say: "What's going on?" },
      { by: 'a', say: "{b}, tell them what you told me. About {target}." },
      { by: 'b', say: "This isn't the place—" },
      { by: 'a', say: "It's the perfect place! Say it in front of everybody, since it's true!" },
      { by: 'b', say: "I just said I'd heard something—" },
      { by: 'a', say: "From who? Say who!" },
      { beat: '{b} says nothing.' },
      { by: 'c', say: "Oh my god." },
      { by: 'a', say: "Yeah. That's what I thought." },
      { by: 'c', dr: "Watching someone get caught in a lie in front of the whole house is like watching a car crash. In slow motion. And you know the car." },
    ] },
    { id: 'sx.3', turns: [
      { by: 'a', say: "I want to tell you a story. Tell me if it sounds familiar." },
      { by: 'b', say: "Okay…" },
      { by: 'a', say: "Somebody tells me {target} is after me. So I'm scared. So I go to {target}, and {target} has no idea what I'm talking about." },
      { by: 'b', say: "Right…" },
      { by: 'a', say: "So I go back and ask who said it. And it's just one person. Every time. One person." },
      { by: 'b', say: "I don't—" },
      { by: 'a', say: "Don't. I'm not asking. I'm telling you I know." },
      { by: 'b', dr: "{a} told it like a bedtime story. That was so much worse than shouting." },
    ] },
    { id: 'sx.4', when: { register: ['fiery'] }, turns: [
      { by: 'a', say: "You LIAR!" },
      { by: 'b', say: "Whoa, whoa, what—" },
      { by: 'a', say: "Everything you told me about {target}! Every single thing! Made up!" },
      { by: 'b', say: "I didn't make it up, I heard—" },
      { by: 'a', say: "From who?! Who did you hear it from?!" },
      { by: 'b', say: "I can't remember exactly—" },
      { by: 'a', say: "You can't remember because there's nobody to remember!" },
      { beat: 'Doors open all over the house.' },
      { by: 'a', say: "Stay away from me. Seriously. Stay away." },
      { by: 'b', dr: "I've been caught before. Never this loud." },
    ] },
    { id: 'sx.5', turns: [
      { by: 'a', say: "Just so you know, I talked to {target}." },
      { by: 'b', say: "And?" },
      { by: 'a', say: "And now we're both wondering why you'd lie about us to each other." },
      { by: 'b', say: "I didn't lie, I was just passing on what—" },
      { by: 'a', say: "You passed it on to both of us. In opposite directions." },
      { beat: '{b} sits down.' },
      { by: 'b', say: "...Okay. What do you want?" },
      { by: 'a', say: "Nothing. I just wanted to see your face." },
      { by: 'a', dr: "{b} played {target} and me against each other. It worked for a week. One conversation and it's over." },
    ] },
    { id: 'sx.6', turns: [
      { by: 'a', say: "Why would you do that?" },
      { by: 'b', say: "Do what?" },
      { by: 'a', say: "You know what. {target}. Everything you said. Why?" },
      { by: 'b', say: "...Because it's a game." },
      { by: 'a', say: "It's a game. That's it? That's your reason?" },
      { by: 'b', say: "What do you want me to say? Sorry? Fine. Sorry. It's still a game." },
      { by: 'a', say: "I trusted you." },
      { by: 'b', say: "I know. That's why it worked." },
      { by: 'a', dr: "'That's why it worked.' I'll be hearing that in my sleep." },
    ] },
  ],

  'recap.scheme.lie.a': [
    { id: 'rsl.a1', turns: [{ by: 'a', dr: "{when}, I told {b} a story about {target}. Was it true? Doesn't matter. {b} believed it." }] },
    { id: 'rsl.a2', turns: [{ by: 'a', dr: "I planted something with {b} {when}. About {target}. Little seed. Watch it grow." }] },
    { id: 'rsl.a3', turns: [{ by: 'a', dr: "{when}, I told {b} that {target} was after {b}. A little white lie. Mostly white." }] },
  ],
  'recap.scheme.lie.b': [
    { id: 'rsl.b1', turns: [{ by: 'b', dr: "{when}, {a} told me {target} was coming for me. I didn't know whether to believe it." }] },
    { id: 'rsl.b2', turns: [{ by: 'b', dr: "{a} came to me {when} with stuff about {target}. Bad stuff." }] },
    { id: 'rsl.b3', turns: [{ by: 'b', dr: "{when}, {a} warned me about {target}. I've been thinking about it ever since." }] },
  ],
  'recap.scheme.lie.caption': [
    { id: 'rsl.x1', turns: [{ beat: '{when}, {a} told {b} that {target} was after {b}.' }, { by: 'a', dr: "Was it true? Who knows." }] },
    { id: 'rsl.x2', turns: [{ beat: '{when}, {a} spread a story about {target}. It reached {b}.' }, { by: 'b', dr: "I heard it." }] },
    { id: 'rsl.x3', turns: [{ beat: '{when}, {a} started a rumour about {target}.' }, { by: 'a', dr: "Let's see where it goes." }] },
  ],
};
