// ══════════════════════════════════════════════════════════════════════
// bb/story/lines/set.js — the whole house in one room
// ══════════════════════════════════════════════════════════════════════
//
// The user, 2026-10-06: "we only have 2 person conversation", "we don't feel that the house
// is full", "no one in the background", "too short", "boring". Every stretch now opens on a
// set piece: up to six people (roles a–f) talking over each other, the stretch's public
// moments played inside it, and an ensemble close. Written against docs/bb-dialogue-style.md
// (§3 "group meeting" and "banter": voices overlapping, side comments, a running joke).
//
//   set.<type>.open / .close   firstnight · firstbed · hohroom (a = HOH) · afternoms
//                              (a, b = nominees, c = HOH) · morningafter ({gone} = last
//                              evicted) · dinner · backyard · gamenight
//   set.cut.<kind>             the camera finding a moment inside the room: clash | fun | flirt
//   bg.<room>                  who else is in a shared room (x, y), one line
//   bg.react                   the room reacting to a row (x, y)

export default {
  // ── the first night ─────────────────────────────────────────────────
  'set.firstnight.open': [
    { id: 'sn.f1', room: 'kitchen', turns: [
      { beat: 'Kitchen, first night. Somebody has found the pasta. Nobody has found the colander. Everybody is in the kitchen anyway.' },
      { by: 'a', say: "Okay, roll call, because I've already forgotten everyone's name." },
      { by: 'b', say: "Same. I've been calling everyone 'babe' for an hour." },
      { by: 'c', say: "That's my strategy too." },
      { by: 'a', say: "So we're all just 'babe'." },
      { by: 'd', say: "Can one of the babes pass me a fork?" },
      { by: 'e', say: "There are no forks. I've checked every drawer." },
      { by: 'b', say: "How can there be no forks?" },
      { by: 'e', say: "There's eleven spoons and a whisk." },
      { by: 'c', say: "So we're eating pasta with a whisk." },
      { beat: 'Somebody does, in fact, eat pasta with a whisk.' },
      { by: 'd', dr: "First night, and we're already a family. A weird family with no forks. But a family." },
    ] },
    { id: 'sn.f2', room: 'kitchen', turns: [
      { beat: 'First night. Everyone is crowded round the kitchen island, still in the clothes they arrived in.' },
      { by: 'a', say: "Okay, can we do the thing where we all say one fact about ourselves?" },
      { by: 'b', say: "No." },
      { by: 'c', say: "Absolutely not." },
      { by: 'a', say: "Come on, it's an icebreaker!" },
      { by: 'd', say: "The ice is broken. We broke it. Somebody cried in the bathroom an hour ago." },
      { by: 'e', say: "That was me. I'm fine. It's just a lot." },
      { by: 'b', say: "It is a lot." },
      { by: 'a', say: "Okay, new icebreaker. Everybody say who they think is going to win." },
      { beat: 'Silence. Everybody looks at everybody.' },
      { by: 'c', say: "...Let's go back to facts." },
      { by: 'a', dr: "The second I said 'who's going to win', you could see every single person do the maths. That's when it stopped being a party." },
    ] },
    { id: 'sn.f3', room: 'bedroom', turns: [
      { beat: 'The beds. There are not enough good ones. Everybody arrives at the bedroom door at the same time.' },
      { by: 'a', say: "I'm just going to put my bag here." },
      { by: 'b', say: "That's a bed. You're claiming a bed." },
      { by: 'a', say: "I'm putting my bag on a bed. Those are different things." },
      { by: 'c', say: "Then I'm putting my bag on this bed." },
      { by: 'd', say: "Wait, are we doing beds now? I thought we were doing dinner." },
      { by: 'e', say: "We're doing beds now. Keep up." },
      { by: 'b', say: "Does anyone snore? Be honest. This is the moment to be honest." },
      { beat: 'Nobody admits to snoring. Somebody is lying.' },
      { by: 'd', dr: "I got the bed by the door. Everybody walks past it. Everybody. All night. I've made a terrible mistake." },
    ] },
    { id: 'sn.f4', room: 'living-room', turns: [
      { beat: 'Living room, first night. Everyone is on the sofas, a bit too polite, a bit too loud.' },
      { by: 'a', say: "Does it feel real yet? To anyone?" },
      { by: 'b', say: "No. I keep waiting for someone to say 'cut'." },
      { by: 'c', say: "Nobody's going to say cut. They never say cut." },
      { by: 'd', say: "There's a camera in the ceiling right above my head. I keep looking at it." },
      { by: 'e', say: "Don't look at it, that's the one rule." },
      { by: 'd', say: "I can't stop looking at it now that you've said that!" },
      { by: 'a', say: "Hi, everyone at home!" },
      { by: 'c', say: "Don't wave! We're not allowed to wave!" },
      { by: 'a', say: "Who said?" },
      { by: 'c', say: "I don't know. It feels like a rule." },
      { by: 'e', dr: "Everyone's being lovely. Everyone. That's what's terrifying. Somebody in that room is lying, and I don't know who yet." },
    ] },
  ],
  'set.firstnight.close': [
    { id: 'sn.c1', turns: [{ beat: 'By midnight the kitchen is a disaster and nobody has said a single word about the game. Yet.' }, { by: 'c', dr: "Tomorrow it starts. Tonight we're just people." }] },
    { id: 'sn.c2', turns: [{ beat: 'The pasta is gone. So is the polite stage. Somebody puts on music and two people start dancing badly.' }, { by: 'a', dr: "I like everyone. I'm going to have to stop liking everyone. Just not tonight." }] },
    { id: 'sn.c3', turns: [{ beat: 'Little groups start to form: two in the corner, three by the pool door, one person alone at the counter, watching all of it.' }, { by: 'e', dr: "You can already see who's going to be with who. It's the first night, and you can already see it." }] },
  ],
  'set.firstbed.open': [
    { id: 'sb.f1', room: 'bedroom', turns: [
      { beat: 'Lights out, the first night. A dark bedroom full of people who met this afternoon.' },
      { by: 'a', say: "Goodnight, everyone." },
      { by: 'b', say: "Goodnight." },
      { by: 'c', say: "Night." },
      { by: 'd', say: "Goodnight, cameras." },
      { by: 'e', say: "Don't talk to the cameras!" },
      { by: 'd', say: "They're lonely!" },
      { beat: 'Somebody laughs. Somebody shushes them. Somebody laughs at the shushing.' },
      { by: 'b', say: "Who just— was that a snore? Already?" },
      { by: 'a', say: "It's been four minutes." },
      { by: 'c', dr: "Day one. Nobody's slept. Nobody's going to. Everybody's lying in the dark doing maths." },
    ] },
    { id: 'sb.f2', room: 'bedroom', turns: [
      { beat: 'Lights out. The bedroom goes quiet for almost a full minute.' },
      { by: 'a', say: "Is anyone else not tired at all?" },
      { by: 'b', say: "Wide awake." },
      { by: 'c', say: "I've never been less tired in my life." },
      { by: 'd', say: "Should we just… keep talking?" },
      { by: 'e', say: "Big Brother's going to tell us off." },
      { by: 'a', say: "Then we whisper." },
      { beat: 'They whisper. It is not quiet. It goes on until three.' },
      { by: 'd', dr: "We talked until three about absolutely nothing. That was the best part of the whole day." },
    ] },
    { id: 'sb.f3', room: 'bedroom', turns: [
      { beat: 'First night. Everyone in bed. Someone is still whispering in the dark.' },
      { by: 'a', say: "Can I say something?" },
      { by: 'b', say: "If it's game, no." },
      { by: 'a', say: "It's not game. I'm just really glad I'm here." },
      { by: 'c', say: "...Same." },
      { by: 'd', say: "Me too." },
      { by: 'e', say: "Okay, that was really nice. Now everyone shut up." },
      { beat: 'Everyone laughs into their pillows.' },
      { by: 'b', dr: "Tonight everyone's glad to be here. Give it a week." },
    ] },
  ],

  // ── the HOH room reveal ─────────────────────────────────────────────
  'set.hohroom.open': [
    { id: 'sh.o1', room: 'hoh-room', turns: [
      { beat: 'The whole house troops up the stairs behind {a}. The door opens on the HOH room.' },
      { by: 'b', say: "Oh my god. There's a bed. A real bed." },
      { by: 'c', say: "There's a basket. Is that a snack basket?" },
      { by: 'a', say: "Don't touch the snack basket." },
      { by: 'd', say: "I'm just looking at the snack basket." },
      { by: 'e', say: "Open the letter! Open the letter!" },
      { beat: '{a} opens the letter from home, reads two lines, and has to stop.' },
      { by: 'b', say: "Oh no. Somebody hug {a}." },
      { beat: 'Everybody hugs {a}. It is a lot of hugs.' },
      { by: 'c', dr: "Everybody was crying with {a}. Everybody was also looking at the photos on the wall to see who {a} talks about. That's this house." },
    ] },
    { id: 'sh.o2', room: 'hoh-room', turns: [
      { beat: 'HOH room. {a} stands in the middle of it while everyone else piles onto the bed.' },
      { by: 'a', say: "Okay, everybody, this is my room, please get your shoes off my bed." },
      { by: 'b', say: "Our bed." },
      { by: 'a', say: "My bed. For one week. It's my one week." },
      { by: 'c', say: "Can we at least have a chocolate each?" },
      { by: 'a', say: "One. Each. And then I'm counting them." },
      { by: 'd', say: "You're going to count them?" },
      { by: 'a', say: "I'm going to count them every night." },
      { beat: 'Somebody takes two. {a} sees it.' },
      { by: 'e', dr: "There's a camera that shows the whole house in that room. You can watch everyone. That's the real prize. Not the chocolate." },
    ] },
    { id: 'sh.o3', room: 'hoh-room', turns: [
      { beat: 'Everybody is crammed into the HOH room, admiring {a}’s photos.' },
      { by: 'b', say: "Who's this?" },
      { by: 'a', say: "Just people from home." },
      { by: 'c', say: "Everyone looks so happy." },
      { by: 'd', say: "Can we stay up here tonight? All of us?" },
      { by: 'a', say: "Absolutely not." },
      { by: 'd', say: "Just for an hour?" },
      { by: 'a', say: "Twenty minutes. Then I need to think." },
      { by: 'e', say: "'Think.' That's code." },
      { by: 'a', say: "It's not code! It's just thinking!" },
      { by: 'b', dr: "'I need to think.' {a} means 'I need to work out who's going on the block'. Twenty minutes, and then one of us is a target." },
    ] },
    { id: 'sh.o4', room: 'hoh-room', turns: [
      { beat: 'HOH room. {a} is lying on the big bed. The whole house is somehow also on the big bed.' },
      { by: 'c', say: "This is the comfiest thing I've ever touched." },
      { by: 'a', say: "It's lovely. Please leave." },
      { by: 'b', say: "Just five more minutes." },
      { by: 'd', say: "Is that the shower? You've got your own shower?" },
      { by: 'a', say: "I've got my own shower." },
      { by: 'e', say: "Can I use your shower?" },
      { by: 'a', say: "No!" },
      { by: 'e', say: "It was worth asking." },
      { by: 'a', dr: "Everybody's my best friend this week. Every single person. I know exactly what that means." },
    ] },
    { id: 'sh.o5', room: 'hoh-room', turns: [
      { beat: 'The HOH room door opens. {a} walks in first and everybody else pours in behind.' },
      { by: 'b', say: "Congratulations! Seriously. You earned it." },
      { by: 'c', say: "You were amazing in that comp." },
      { by: 'd', say: "Honestly, you were." },
      { by: 'a', say: "Thank you. Thank you, everyone." },
      { by: 'e', say: "So… are we safe?" },
      { beat: 'The room goes quiet.' },
      { by: 'a', say: "...I haven't decided anything." },
      { by: 'e', say: "Right. Of course. Ignore me." },
      { by: 'c', dr: "One person said it out loud. Everybody else was thinking it. 'So, are we safe?' Brilliant timing." },
    ] },
    { id: 'sh.o6', room: 'hoh-room', turns: [
      { beat: 'HOH room. The letter has been read. The chocolate is half gone. Somebody is jumping on the bed.' },
      { by: 'a', say: "Can people please stop jumping on my bed?" },
      { by: 'b', say: "It's so bouncy!" },
      { by: 'c', say: "Everything up here is better. The towels are better." },
      { by: 'd', say: "The air is better." },
      { by: 'a', say: "The air is the same air." },
      { by: 'd', say: "It's HOH air. It's different." },
      { by: 'e', say: "Can we vote on who gets the bed next week?" },
      { by: 'a', say: "That's literally the whole game." },
      { by: 'b', dr: "Everyone's laughing. Everyone's also memorising who {a} is laughing with the most." },
    ] },
  ],
  'set.hohroom.close': [
    { id: 'sh.c1', room: 'hoh-room', turns: [{ beat: 'One by one, the house drifts back downstairs. The last two to leave take their time.' }, { by: 'a', dr: "I watched who left first. I watched who stayed. That's my week, decided, right there." }] },
    { id: 'sh.c2', room: 'hoh-room', turns: [{ beat: 'The door shuts. {a} sits alone on the big bed and stares at the house camera.' }, { by: 'a', dr: "It's lovely up here. It's also the loneliest room in the house. Everyone wants something from you." }] },
    { id: 'sh.c3', room: 'hoh-room', turns: [{ beat: '{a} finally gets everyone out and locks the door. Within a minute, somebody knocks.' }, { by: 'a', dr: "That's the first visitor. There will be a lot more. And every single one of them has a name they want me to say." }] },
    { id: 'sh.c4', room: 'hoh-room', turns: [{ beat: 'Everyone leaves except one, who lingers by the door, waiting for the others to go.' }, { by: 'a', dr: "Whoever stays behind wants a private word. There's always somebody who stays behind." }] },
  ],

  // ── after the nominations ────────────────────────────────────────────
  'set.afternoms.open': [
    { id: 'sa.o1', room: 'living-room', turns: [
      { beat: 'The ceremony is over. Nobody has moved from the sofas.' },
      { by: 'c', say: "That's it. Meeting's over. Sorry, guys." },
      { beat: '{c} goes upstairs. The room stays exactly where it is.' },
      { by: 'd', say: "Okay. Well." },
      { by: 'a', say: "Don't. Please don't 'okay, well' me." },
      { by: 'e', say: "Do you want a hug?" },
      { by: 'a', say: "No. Yes. I don't know." },
      { by: 'b', say: "I need some air." },
      { by: 'd', say: "Do you want company?" },
      { by: 'b', say: "...No. Actually, I'll stay. I don't want to be on my own." },
      { beat: '{b} sits back down. Somebody passes {b} a cushion without a word.' },
      { by: 'e', dr: "There's always a minute after nominations where nobody knows where to look. This was a long minute." },
    ] },
    { id: 'sa.o2', room: 'kitchen', turns: [
      { beat: 'After the ceremony. The kitchen is very busy and nobody is cooking.' },
      { by: 'd', say: "Is anyone hungry?" },
      { by: 'e', say: "No." },
      { by: 'f', say: "Starving, actually." },
      { by: 'd', say: "Read the room." },
      { by: 'f', say: "I'm reading it. I'm still hungry." },
      { by: 'a', say: "It's fine. Eat. Life goes on." },
      { by: 'b', say: "For some of us." },
      { beat: 'Everyone pretends not to hear that.' },
      { by: 'f', dr: "Nominations make everyone weird. I'm not weird. I'm just hungry. Those are different." },
    ] },
    { id: 'sa.o3', room: 'living-room', turns: [
      { beat: 'The nomination ceremony has just ended. {a} and {b} are still sitting in the chairs.' },
      { by: 'a', say: "Can we get up now?" },
      { by: 'b', say: "I don't think there's a rule." },
      { by: 'a', say: "Then why am I still sitting here?" },
      { by: 'd', say: "Come on. Both of you. Kitchen. I'm making tea." },
      { by: 'e', say: "Tea fixes nothing." },
      { by: 'd', say: "Tea fixes everything. Up." },
      { beat: 'They get up. The house follows them into the kitchen like a slow parade.' },
      { by: 'b', dr: "Everyone was really kind. Everyone. Including the people who are going to vote me out on Thursday." },
    ] },
    { id: 'sa.o4', room: 'living-room', turns: [
      { beat: 'Ceremony over. Half the house goes one way, half goes the other. Nobody goes upstairs to the HOH room.' },
      { by: 'd', say: "Well, that was awkward." },
      { by: 'e', say: "That was horrible." },
      { by: 'f', say: "It wasn't that bad." },
      { by: 'd', say: "You weren't the one sitting in the chair." },
      { by: 'a', say: "Can everyone stop talking about the chair, please?" },
      { by: 'f', say: "Sorry." },
      { by: 'a', say: "Thank you." },
      { by: 'b', say: "It was a horrible chair, though." },
      { beat: 'Despite everything, {a} laughs.' },
      { by: 'd', dr: "You could cut the air in there with a knife. Then {b} said the thing about the chair and it was fine for about four seconds." },
    ] },
    { id: 'sa.o5', room: 'kitchen', turns: [
      { beat: 'After nominations, the kitchen. {c} comes down for a glass of water. Every conversation stops.' },
      { by: 'c', say: "Don't stop on my account." },
      { by: 'd', say: "We weren't— we were just talking about dinner." },
      { by: 'c', say: "Sure." },
      { by: 'a', say: "Can I talk to you later? Upstairs?" },
      { by: 'c', say: "Of course. Any time." },
      { beat: '{c} goes back up. The kitchen waits until the door shuts.' },
      { by: 'e', say: "'Any time.' Did you hear that?" },
      { by: 'b', say: "'Any time' is what you say when it's already decided." },
      { by: 'a', dr: "{c} was nice to me. That's the worst sign. Nobody's nice to the person they want to stay." },
    ] },
    { id: 'sa.o6', room: 'backyard', turns: [
      { beat: 'The house spills out into the backyard after the ceremony, mostly to be anywhere but the living room.' },
      { by: 'd', say: "Nice day for it." },
      { by: 'e', say: "For what?" },
      { by: 'd', say: "I don't know. Being outside. Not in there." },
      { by: 'a', say: "Agreed. I'm never going in there again." },
      { by: 'f', say: "You have to go in there. The beds are in there." },
      { by: 'a', say: "I'll sleep out here." },
      { by: 'b', say: "I'll join you." },
      { beat: 'The two nominees lie down on the grass. Somebody brings them a blanket. Then two more people lie down too.' },
      { by: 'f', dr: "We all ended up on the grass. Nominees, non-nominees, everybody. For about an hour, nobody was playing." },
    ] },
  ],
  'set.afternoms.close': [
    { id: 'sa.c1', turns: [{ beat: 'By the evening, the house has split: one group in the kitchen, one in the backyard, the nominees in the middle of both.' }, { by: 'b', dr: "Four days. I've got four days to change seven minds." }] },
    { id: 'sa.c2', turns: [{ beat: 'The house starts to break into little pairs, all of them talking quietly, all of them looking at the nominees.' }, { by: 'a', dr: "Everyone's whispering. Everyone. I've never been so aware of a whisper in my life." }] },
    { id: 'sa.c3', turns: [{ beat: 'One by one, people drift off to have private conversations. The nominees end up alone together at the table.' }, { by: 'a', dr: "Sitting next to the person you're up against. Both pretending it's fine. It's not fine." }] },
    { id: 'sa.c4', turns: [{ beat: 'Somebody puts music on. Nobody dances. The music plays anyway.' }, { by: 'b', dr: "Music on, nobody talking. That's what a house sounds like the day the block goes up." }] },
  ],

  // ── the morning after an eviction ────────────────────────────────────
  'set.morningafter.open': [
    { id: 'sm.o1', room: 'bedroom', turns: [
      { beat: 'The morning after. One empty bed. Nobody has made it, and nobody wants to.' },
      { by: 'a', say: "It's so weird without {gone}." },
      { by: 'b', say: "I keep expecting {gone} to walk in asking where the coffee is." },
      { by: 'c', say: "{gone} always knew where the coffee was." },
      { by: 'd', say: "Does anyone know where the coffee is?" },
      { beat: 'Nobody knows where the coffee is.' },
      { by: 'e', say: "Okay, that's actually really sad." },
      { by: 'a', say: "To {gone}. Wherever the coffee is." },
      { by: 'c', dr: "Every time somebody leaves, the house gets a bit quieter. And a bit meaner. You can feel it straight away." },
    ] },
    { id: 'sm.o2', room: 'kitchen', turns: [
      { beat: 'Breakfast. Everybody is pretending to be fine. {gone}’s mug is still on the draining board.' },
      { by: 'b', say: "Should we move {gone}'s mug?" },
      { by: 'c', say: "Leave it." },
      { by: 'd', say: "It's just a mug." },
      { by: 'c', say: "Leave it a day." },
      { by: 'e', say: "So who's next, then?" },
      { by: 'a', say: "Seriously? At breakfast?" },
      { by: 'e', say: "Everyone's thinking it." },
      { by: 'a', say: "Everyone's thinking it. Nobody's saying it. That's how breakfast works." },
      { by: 'e', dr: "I said what everyone was thinking. Apparently that's rude. Apparently you're only meant to think it." },
    ] },
    { id: 'sm.o3', room: 'kitchen', turns: [
      { beat: 'Morning. The house is up early, which never happens. Nobody slept much.' },
      { by: 'a', say: "Did anyone sleep?" },
      { by: 'b', say: "No." },
      { by: 'c', say: "Barely." },
      { by: 'd', say: "Like a baby." },
      { by: 'a', say: "Of course you did." },
      { by: 'd', say: "My vote went the right way. I sleep fine when my vote goes the right way." },
      { beat: 'A couple of people look at each other.' },
      { by: 'e', say: "...That's a very specific thing to say." },
      { by: 'b', dr: "'My vote went the right way.' Thank you. Now I know at least one person's vote. Everybody does." },
    ] },
    { id: 'sm.o4', room: 'kitchen', turns: [
      { beat: 'Kitchen, the morning after {gone} left. Somebody has cooked far too much breakfast.' },
      { by: 'c', say: "I made {gone}'s eggs. By accident. Muscle memory." },
      { by: 'a', say: "Oh no." },
      { by: 'b', say: "I'll eat them." },
      { by: 'd', say: "That's dark." },
      { by: 'b', say: "It's not dark, it's eggs. {gone} would want them eaten." },
      { by: 'e', say: "{gone} would want them eaten by {gone}." },
      { beat: 'Everybody laughs. It sounds a bit too loud.' },
      { by: 'c', dr: "We laugh about it. We have to. Otherwise you'd just sit there knowing it's going to be one of us next." },
    ] },
    { id: 'sm.o5', room: 'living-room', turns: [
      { beat: 'Living room. The house is gathered around the memory wall. {gone}’s photo has gone grey.' },
      { by: 'a', say: "That's so creepy. They do it so fast." },
      { by: 'b', say: "Like {gone} was never here." },
      { by: 'c', say: "{gone} was definitely here. {gone} left socks everywhere." },
      { by: 'd', say: "Are those {gone}'s socks on the sofa?" },
      { by: 'c', say: "They're {gone}'s socks." },
      { by: 'e', say: "Nobody move the socks." },
      { by: 'b', say: "We're not making a shrine out of socks." },
      { by: 'e', say: "We're absolutely making a shrine out of socks." },
      { by: 'd', dr: "The socks stayed on the sofa for three days. Nobody would move them. That's how we grieve in here." },
    ] },
    { id: 'sm.o6', room: 'kitchen', turns: [
      { beat: 'Morning. Half the house is in the kitchen, the other half is pretending to sleep in.' },
      { by: 'a', say: "Is it just me, or is it really quiet without {gone}?" },
      { by: 'b', say: "{gone} was loud." },
      { by: 'c', say: "{gone} was SO loud." },
      { by: 'd', say: "I miss the loud." },
      { by: 'b', say: "Same, weirdly." },
      { by: 'e', say: "Should someone be loud? To fill the gap?" },
      { beat: 'Everybody looks at {e}.' },
      { by: 'e', say: "...I'm not volunteering. I was asking." },
      { by: 'a', dr: "Last night somebody went out of that door. This morning we're joking about it. That's how fast this place moves." },
    ] },
  ],
  'set.morningafter.close': [
    { id: 'sm.c1', turns: [{ beat: 'By lunchtime, the empty bed has been taken. Nobody admits to taking it.' }, { by: 'b', dr: "It took four hours for somebody to move into a dead person's bed. Four hours. That's this game." }] },
    { id: 'sm.c2', turns: [{ beat: 'The house starts to split back into its little groups. Everybody counts heads.' }, { by: 'd', dr: "One fewer person means every vote counts more. Everybody's doing the maths. You can see their lips move." }] },
    { id: 'sm.c3', turns: [{ beat: 'Somebody puts on music. The house gets on with it.' }, { by: 'a', dr: "That's the thing about this house. Somebody leaves, everyone's sad for a morning, and then there's a new HOH to win." }] },
  ],

  // ── an ordinary evening ─────────────────────────────────────────────
  'set.dinner.open': [
    { id: 'sd.o1', room: 'kitchen', turns: [
      { beat: 'Dinner. Everyone crammed round the table. Someone has made curry and someone else has opinions about it.' },
      { by: 'a', say: "This is amazing. Who made this?" },
      { by: 'b', say: "Me. Thank you." },
      { by: 'c', say: "It's a bit spicy." },
      { by: 'b', say: "It's mild." },
      { by: 'c', say: "My mouth is on fire." },
      { by: 'd', say: "Your mouth is on fire because you've had three bowls." },
      { by: 'c', say: "Because it's amazing! I can complain and like it!" },
      { by: 'e', say: "Pass the rice, someone." },
      { by: 'f', say: "There's no rice left." },
      { by: 'e', say: "Who ate all the rice?" },
      { beat: 'Everybody looks at {c}.' },
      { by: 'b', dr: "Feeding people in here is power. You'd be amazed how hard it is to put the person who makes dinner on the block." },
    ] },
    { id: 'sd.o2', room: 'kitchen', turns: [
      { beat: 'Dinner. Too many people, too few chairs. Two people are sitting on the counter.' },
      { by: 'a', say: "Okay, question for the table." },
      { by: 'b', say: "Oh no." },
      { by: 'a', say: "Best competition so far. Go." },
      { by: 'c', say: "The one where I won." },
      { by: 'd', say: "You haven't won one." },
      { by: 'c', say: "Then the one where I nearly won." },
      { by: 'e', say: "That's all of them." },
      { by: 'f', say: "I liked the one in the dark. Nobody could see me fall over." },
      { by: 'a', say: "We all heard you fall over." },
      { by: 'f', say: "Hearing is not seeing." },
      { by: 'd', dr: "Dinner's the only time all of us are in one room and nobody's working. Nearly nobody." },
    ] },
    { id: 'sd.o3', room: 'kitchen', turns: [
      { beat: 'Dinner. {a} is trying to make a toast. Nobody is listening.' },
      { by: 'a', say: "Everyone. Everyone. I'd like to make a toast." },
      { by: 'b', say: "With water?" },
      { by: 'a', say: "With water. To the best house ever." },
      { by: 'c', say: "That's what everyone says." },
      { by: 'a', say: "And to the best people." },
      { by: 'd', say: "Some of the people." },
      { by: 'e', say: "Most of the people." },
      { by: 'a', say: "Can I finish my toast?" },
      { by: 'f', say: "No. We're eating. Cheers." },
      { beat: 'Glasses clink. Several people look at each other over the top of them.' },
      { by: 'c', dr: "'To the best people.' Everybody drank to it. Half of us are planning to vote out the other half." },
    ] },
    { id: 'sd.o4', room: 'kitchen', turns: [
      { beat: 'Dinner. The table has split itself in two without anyone saying a word: one end loud, one end quiet.' },
      { by: 'a', say: "Why's it so quiet down that end?" },
      { by: 'b', say: "We're eating." },
      { by: 'a', say: "We're eating too. We're just eating loudly." },
      { by: 'c', say: "Come sit up this end. It's more fun." },
      { by: 'd', say: "I'm comfy." },
      { by: 'c', say: "You're plotting." },
      { by: 'd', say: "I'm eating a potato." },
      { by: 'e', say: "You can plot and eat a potato." },
      { by: 'f', say: "I do it all the time." },
      { by: 'b', dr: "Where you sit at dinner tells everyone who you're with. That's why I always sit in the middle. Nobody knows what to do with the middle." },
    ] },
    { id: 'sd.o5', room: 'kitchen', turns: [
      { beat: 'Dinner. Somebody has dropped the lasagne on the floor. The house stands round it in silence.' },
      { by: 'a', say: "Five second rule." },
      { by: 'b', say: "It's been about forty seconds." },
      { by: 'c', say: "Forty second rule." },
      { by: 'd', say: "That floor is disgusting." },
      { by: 'e', say: "Then you clean it." },
      { by: 'd', say: "Then you clean it!" },
      { by: 'f', say: "I'm eating it." },
      { beat: '{f} eats a bit of it off the floor. The house screams.' },
      { by: 'a', dr: "We had cereal for dinner in the end. Seven people eating cereal around a lasagne nobody would clean up." },
    ] },
  ],
  'set.dinner.close': [
    { id: 'sd.c1', room: 'kitchen', turns: [{ beat: 'Dinner breaks up. The washing-up does not get done. It never gets done.' }, { by: 'e', dr: "Same people always clean. Same people always don't. You learn a lot from the sink." }] },
    { id: 'sd.c2', room: 'kitchen', turns: [{ beat: 'One by one people drift away from the table. A few of them drift in exactly the same direction.' }, { by: 'c', dr: "Watch who leaves the table together. That's the real seating plan." }] },
    { id: 'sd.c3', room: 'kitchen', turns: [{ beat: 'Plates everywhere. Somebody starts singing. Somebody else, from the next room, begs them to stop.' }, { by: 'a', dr: "Some nights it's just a house full of friends. Those are the nights you have to remember it's a game." }] },
    { id: 'sd.c4', room: 'kitchen', turns: [{ beat: 'The table empties. Two people stay behind, talking low over the empty dishes.' }, { by: 'f', dr: "Everyone leaves dinner. The two who stay behind are the ones you need to watch." }] },
  ],
  'set.backyard.open': [
    { id: 'sy.o1', room: 'backyard', turns: [
      { beat: 'Backyard. A hot afternoon. Everyone is by the pool, nobody is in it.' },
      { by: 'a', say: "Somebody go in first." },
      { by: 'b', say: "You go in first." },
      { by: 'a', say: "I suggested it. Suggesting is my contribution." },
      { by: 'c', say: "It's freezing. I put a toe in." },
      { by: 'd', say: "A toe isn't a test." },
      { by: 'e', say: "Fine. I'm going in." },
      { beat: '{e} jumps in. {e} comes up screaming.' },
      { by: 'e', say: "IT'S LOVELY! IT'S LOVELY!" },
      { by: 'f', say: "You're shaking." },
      { by: 'e', say: "COME IN!" },
      { by: 'b', dr: "Nobody went in after that. We watched {e} turn blue for ten minutes and called it entertainment." },
    ] },
    { id: 'sy.o2', room: 'backyard', turns: [
      { beat: 'Backyard. Someone has invented a game with a frisbee and a set of rules nobody else understands.' },
      { by: 'a', say: "Okay, so if it hits the hammock, that's three points." },
      { by: 'b', say: "Why three?" },
      { by: 'a', say: "Because the hammock's hard to hit." },
      { by: 'c', say: "I just hit it. That's three points." },
      { by: 'a', say: "Not if you're standing on the grass." },
      { by: 'c', say: "Where else would I be standing?!" },
      { by: 'd', say: "Can we just throw it?" },
      { by: 'a', say: "That's not a game, that's just throwing." },
      { by: 'e', say: "Throwing is a great game." },
      { by: 'f', dr: "We played for an hour. Nobody understood the rules. {a} won. Obviously." },
    ] },
    { id: 'sy.o3', room: 'backyard', turns: [
      { beat: 'Backyard. Everybody is lying on loungers in a long row, like a very sad beach.' },
      { by: 'a', say: "This is a holiday." },
      { by: 'b', say: "This is a holiday where they can throw you off the beach." },
      { by: 'c', say: "Best holiday ever." },
      { by: 'd', say: "Worst holiday ever." },
      { by: 'e', say: "Can someone get me a drink?" },
      { by: 'f', say: "Get your own drink." },
      { by: 'e', say: "I'm on holiday." },
      { by: 'f', say: "We're all on holiday!" },
      { beat: 'Nobody gets anybody a drink. Everyone lies there.' },
      { by: 'c', dr: "Afternoons like this, you almost forget. Almost. Then you look down the row and think: which of these people is going home on Thursday?" },
    ] },
    { id: 'sy.o4', room: 'backyard', turns: [
      { beat: 'Backyard workout. One person is very serious about it. Everyone else is lying on the grass watching.' },
      { by: 'a', say: "Twenty more. Come on, who's joining?" },
      { by: 'b', say: "Nobody." },
      { by: 'c', say: "I'll count." },
      { by: 'a', say: "Counting isn't working out." },
      { by: 'c', say: "It's working out my brain." },
      { by: 'd', say: "One… two… is it two yet?" },
      { by: 'e', say: "It's been two for ages." },
      { by: 'a', say: "It's been four!" },
      { by: 'f', say: "Is that a comp thing? Are you training?" },
      { beat: 'Everyone stops laughing and looks at {a}.' },
      { by: 'a', dr: "The second someone says 'training', everybody's watching you. Should've done my push-ups in the shower." },
    ] },
  ],
  'set.backyard.close': [
    { id: 'sy.c1', room: 'backyard', turns: [{ beat: 'The sun goes in. The backyard empties, two and three at a time.' }, { by: 'b', dr: "Out there it's all jokes. Inside it's all whispers. You need both to survive." }] },
    { id: 'sy.c2', room: 'backyard', turns: [{ beat: 'Big Brother calls everyone inside. Nobody moves for a full minute.' }, { by: 'd', dr: "That's the only bit of the day that feels like real life. Then the voice says 'inside', and it's a game again." }] },
    { id: 'sy.c3', room: 'backyard', turns: [{ beat: 'Somebody falls asleep on a lounger. Somebody else puts sun cream on their nose in the shape of a heart.' }, { by: 'a', dr: "We are adults. We are competing for a lot of money. We drew a heart on someone's nose." }] },
  ],
  'set.gamenight.open': [
    { id: 'sg.o1', room: 'living-room', turns: [
      { beat: 'Living room. Game night. Somebody has found a pack of cards with three cards missing.' },
      { by: 'a', say: "We can still play. We'll just never get a full house." },
      { by: 'b', say: "That's the house we're in. That's thematic." },
      { by: 'c', say: "What are we playing?" },
      { by: 'a', say: "Liar's game. You say a card, you put it down, people call you a liar." },
      { by: 'd', say: "Oh, this is going to go badly." },
      { by: 'e', say: "This is going to go so badly." },
      { by: 'f', say: "Two kings." },
      { by: 'b', say: "Liar." },
      { by: 'f', say: "...How did you know?" },
      { by: 'b', say: "Because I've watched you lie all week." },
      { beat: 'The room goes "ooooh". {f} pretends to be offended. Mostly pretends.' },
      { by: 'c', dr: "We played a game about lying in a house full of liars. Nobody won. Everybody learned something." },
    ] },
    { id: 'sg.o2', room: 'living-room', turns: [
      { beat: 'Living room. Somebody has made up a quiz about the house.' },
      { by: 'a', say: "Question one. Who takes the longest showers?" },
      { by: 'b', say: "Easy." },
      { by: 'c', say: "Everyone knows that." },
      { by: 'd', say: "Don't say it." },
      { by: 'e', say: "{d}." },
      { by: 'd', say: "I said don't say it!" },
      { by: 'a', say: "Question two. Who's most likely to win HOH next?" },
      { beat: 'Silence. Nobody wants to answer that one.' },
      { by: 'f', say: "...Let's go back to showers." },
      { by: 'a', dr: "Ask a house about showers and they'll talk for an hour. Ask them who's a threat and they all suddenly need the bathroom." },
    ] },
    { id: 'sg.o3', room: 'living-room', turns: [
      { beat: 'Living room. A blanket fort has been built out of every cushion in the house.' },
      { by: 'a', say: "Password." },
      { by: 'b', say: "There's a password?" },
      { by: 'a', say: "There's always a password." },
      { by: 'c', say: "Snacks?" },
      { by: 'a', say: "Correct. Come in." },
      { by: 'd', say: "Can I come in?" },
      { by: 'a', say: "Password." },
      { by: 'd', say: "Snacks." },
      { by: 'a', say: "It's changed. It's now 'I bring snacks'." },
      { by: 'e', say: "Oh, that's an alliance. That's literally an alliance with a door." },
      { by: 'f', dr: "Six adults in a blanket fort, at night, arguing about a password. Best night in this house." },
    ] },
    { id: 'sg.o4', room: 'living-room', turns: [
      { beat: 'Living room. Charades. Somebody has been acting out the same word for two straight minutes.' },
      { by: 'a', say: "Is it a horse?" },
      { by: 'b', say: "It's not a horse." },
      { by: 'c', say: "Is it a duck?" },
      { by: 'b', say: "Why would it be a duck?!" },
      { by: 'd', say: "You're flapping." },
      { by: 'b', say: "I'm not flapping, I'm galloping!" },
      { by: 'e', say: "So it IS a horse!" },
      { by: 'b', say: "It's a CAR!" },
      { by: 'f', say: "Galloping is not driving!" },
      { by: 'b', dr: "I'm never doing charades again. These people can't tell a horse from a car. These people vote." },
    ] },
  ],
  'set.gamenight.close': [
    { id: 'sg.c1', room: 'living-room', turns: [{ beat: 'The game falls apart in an argument about the rules. Everyone goes to bed happy anyway.' }, { by: 'e', dr: "Nights like that are why I'll be sad when this is over. And also why I'll be glad." }] },
    { id: 'sg.c2', room: 'living-room', turns: [{ beat: 'Midnight. Somebody is still trying to start another round. The lights go off on them.' }, { by: 'a', dr: "Big Brother turned the lights off on our game. We kept playing in the dark. Nobody could see the cards. Didn't matter." }] },
    { id: 'sg.c3', room: 'living-room', turns: [{ beat: 'The house goes to bed in twos. One pair goes the long way round, past the storage room.' }, { by: 'c', dr: "Game night's when people relax. Relaxed people say things. I was listening." }] },
  ],

  // ── the camera finding a moment inside the room ─────────────────────
  'set.cut.clash': [
    { id: 'sc.c1', turns: [{ beat: 'At the other end, something has started between {a} and {b}.' }] },
    { id: 'sc.c2', turns: [{ beat: 'Across the room, {b} has gone very quiet. {a} has not noticed. Yet.' }] },
    { id: 'sc.c3', turns: [{ beat: 'In the middle of it all, {a} and {b} are no longer laughing.' }] },
    { id: 'sc.c4', turns: [{ beat: 'Not everyone is having a good time. {b} has been glaring at {a} for a while.' }] },
  ],
  'set.cut.fun': [
    { id: 'sc.f1', turns: [{ beat: 'Off to one side, {a} and {b} are in their own little world.' }] },
    { id: 'sc.f2', turns: [{ beat: 'Meanwhile, {a} has decided this is the moment.' }] },
    { id: 'sc.f3', turns: [{ beat: 'On the edge of it all, {a} and {b} have started something of their own.' }] },
    { id: 'sc.f4', turns: [{ beat: 'Somebody turns up the music. {a} and {b} take that as permission.' }] },
  ],
  'set.cut.flirt': [
    { id: 'sc.l1', turns: [{ beat: 'Not everyone is paying attention to the room. {a} and {b} have found each other again.' }] },
    { id: 'sc.l2', turns: [{ beat: 'In the corner, {a} has managed to end up next to {b}. Again. Somehow.' }] },
    { id: 'sc.l3', turns: [{ beat: 'The house is loud. {a} and {b} are not listening to any of it.' }] },
    { id: 'sc.l4', turns: [{ beat: 'Half the house has noticed where {a} keeps sitting. The other half is about to.' }] },
  ],

  // ── the rest of the house, in a shared room ─────────────────────────
  'bg.kitchen': [
    { id: 'bk.1', turns: [{ beat: 'Behind them, {x} is washing up very slowly and not even pretending not to listen.' }] },
    { id: 'bk.2', turns: [{ beat: '{x} and {y} are arguing about the toaster at the other end of the counter.' }] },
    { id: 'bk.3', turns: [{ beat: '{x} wanders in, takes a yoghurt, and wanders out again without a word.' }] },
    { id: 'bk.4', turns: [{ beat: '{x} is at the stove, cooking something that smells amazing and sharing none of it.' }] },
    { id: 'bk.5', turns: [{ beat: 'At the table, {x} and {y} are doing a puzzle with half the pieces missing.' }] },
    { id: 'bk.6', turns: [{ beat: '{x} opens the fridge, stares into it for a long time, and closes it again.' }] },
  ],
  'bg.living-room': [
    { id: 'bl.1', turns: [{ beat: 'On the other sofa, {x} is asleep with {y}’s feet in {x.posAdj} lap.' }] },
    { id: 'bl.2', turns: [{ beat: '{x} is lying on the floor, staring at the ceiling, and has been for an hour.' }] },
    { id: 'bl.3', turns: [{ beat: 'Across the room, {x} and {y} are playing cards and cheating at it.' }] },
    { id: 'bl.4', turns: [{ beat: '{x} is doing yoga in the middle of the room. Nobody asked {x} to.' }] },
    { id: 'bl.5', turns: [{ beat: '{x} walks through, sees who is talking, and walks straight back out.' }] },
    { id: 'bl.6', turns: [{ beat: 'By the memory wall, {x} is reading everyone’s names out loud, quietly, to {y}.' }] },
  ],
  'bg.backyard': [
    { id: 'by.1', turns: [{ beat: 'Over in the pool, {x} and {y} are having a very loud splashing contest.' }] },
    { id: 'by.2', turns: [{ beat: '{x} is doing laps of the backyard, round and round, earphones in that aren’t plugged into anything.' }] },
    { id: 'by.3', turns: [{ beat: 'On the far lounger, {x} is either asleep or very good at pretending.' }] },
    { id: 'by.4', turns: [{ beat: '{x} and {y} are on the hammock, which is only built for one.' }] },
    { id: 'by.5', turns: [{ beat: 'Somewhere behind them, {x} shoots a basketball, misses, and swears.' }] },
    { id: 'by.6', turns: [{ beat: '{x} is lying on the grass with {y}, both pointing at clouds.' }] },
  ],
  'bg.bedroom': [
    { id: 'bd.1', turns: [{ beat: 'Two beds over, {x} is asleep. Or says so.' }] },
    { id: 'bd.2', turns: [{ beat: '{x} is lying on the next bed, reading the back of a shampoo bottle for the tenth time.' }] },
    { id: 'bd.3', turns: [{ beat: 'In the corner, {x} and {y} are folding laundry and listening to every word.' }] },
    { id: 'bd.4', turns: [{ beat: '{x} is buried under a duvet. Only the feet are visible.' }] },
    { id: 'bd.5', turns: [{ beat: 'From under a pile of blankets, {x} says, "I can hear you, by the way." Nobody stops.' }] },
    { id: 'bd.6', turns: [{ beat: '{x} wanders in looking for a hairbrush, takes a very long time finding it, and leaves.' }] },
  ],
  'bg.react': [
    { id: 'br.1', turns: [{ beat: '{x} freezes halfway through whatever {x.sub} was doing. {y} mouths, "What is happening?"' }] },
    { id: 'br.2', turns: [{ by: 'x', say: "Okay, okay. Guys." }, { beat: 'Nobody listens to {x}.' }] },
    { id: 'br.3', turns: [{ beat: '{x} and {y} slowly back out of the room without a word.' }] },
    { id: 'br.4', turns: [{ by: 'y', say: "Should we… go?" }, { by: 'x', say: "No. I want to see this." }] },
    { id: 'br.5', turns: [{ beat: 'The whole room has gone quiet. {x} hasn\u2019t moved in a full minute.' }] },
    { id: 'br.6', turns: [{ by: 'x', say: "Can we not do this in the kitchen?" }, { beat: 'They do it right there anyway.' }] },
    { id: 'br.7', turns: [{ beat: '{y} catches {x}’s eye across the room. Neither of them says a word.' }] },
    { id: 'br.8', turns: [{ by: 'x', say: "Somebody turn the music up." }, { by: 'y', say: "No, leave it. Let them." }] },
  ],
};
