// ══════════════════════════════════════════════════════════════════════
// bb/story/lines/showmance.js — two people, a house full of cameras
// ══════════════════════════════════════════════════════════════════════
//
// Written against docs/bb-dialogue-style.md. Each entry is a WHOLE scene. a and b
// are the two of them. In jealous, a is the jealous one and c (when present) is
// the person a is jealous of. A love scene uses the pair's own history where it
// can: the step before it (spark → kiss → declare) is on record, or recapped.

export default {
  // ── spark: flirting ─────────────────────────────────────────────────
  'story.showmance.spark.any': [
    { id: 'sm.s1', room: 'kitchen', turns: [
      { beat: 'Kitchen. {a} is trying to open a jar and losing.' },
      { by: 'b', say: "Do you want help with that?" },
      { by: 'a', say: "No. I've got it." },
      { beat: 'The jar does not open.' },
      { by: 'a', say: "I've loosened it for you." },
      { by: 'b', say: "Oh, have you?" },
      { beat: '{b} opens it first try.' },
      { by: 'a', say: "Because I loosened it." },
      { by: 'b', say: "Sure. Thank you for your service." },
      { by: 'a', say: "You're welcome." },
      { beat: 'Neither of them moves to leave.' },
      { by: 'a', dr: "I did not loosen it. But {b} let me pretend, and that's… actually really cute?" },
    ] },
    { id: 'sm.s2', turns: [
      { by: 'a', say: "Can I ask you something random?" },
      { by: 'b', say: "Always." },
      { by: 'a', say: "Do you always laugh like that, or is it just at my jokes?" },
      { by: 'b', say: "Wow. Confident." },
      { by: 'a', say: "It's a real question!" },
      { by: 'b', say: "It's mostly at your jokes." },
      { by: 'a', say: "Mostly?" },
      { by: 'b', say: "Don't push it." },
      { beat: '{a} grins and looks at the floor.' },
      { by: 'b', dr: "I came in here to play a game. I did not come in here to giggle. And yet." },
    ] },
    { id: 'sm.s3', room: 'backyard', turns: [
      { beat: 'Backyard, late. Everyone else has gone in. {a} and {b} are still on the same lounger.' },
      { by: 'b', say: "We should go in." },
      { by: 'a', say: "We should." },
      { beat: 'Neither of them moves.' },
      { by: 'b', say: "Any minute now." },
      { by: 'a', say: "Any minute." },
      { by: 'b', say: "You're not going in." },
      { by: 'a', say: "Neither are you." },
      { by: 'b', say: "I'm waiting for you to go in first, so it doesn't look like I was waiting." },
      { by: 'a', say: "...That's the nicest thing anybody's said to me in here." },
      { by: 'a', dr: "We stayed out there for another hour. Talking about nothing. It was the best hour I've had in this house." },
    ] },
    { id: 'sm.s4', turns: [
      { by: 'a', say: "You've got something on your face." },
      { by: 'b', say: "Where?" },
      { by: 'a', say: "Here. No— here." },
      { beat: '{a} reaches over and wipes it off with a thumb. Then leaves the thumb there a second too long.' },
      { by: 'b', say: "...Got it?" },
      { by: 'a', say: "Got it." },
      { by: 'b', say: "Was there actually anything there?" },
      { by: 'a', say: "Little bit." },
      { by: 'b', say: "Little bit." },
      { by: 'b', dr: "There was nothing on my face. I checked. {a} just wanted an excuse. I'm choosing to be flattered." },
    ] },
    { id: 'sm.s5', presumes: ['hoh'], turns: [
      { by: 'b', say: "Why do you always sit next to me?" },
      { by: 'a', say: "I don't always sit next to you." },
      { by: 'b', say: "You've sat next to me at every meal." },
      { by: 'a', say: "That's a coincidence." },
      { by: 'b', say: "Every meal." },
      { by: 'a', say: "...Do you want me to stop?" },
      { by: 'b', say: "No. I just wanted you to admit it." },
      { by: 'a', say: "Fine. I sit next to you on purpose." },
      { by: 'b', say: "Good." },
      { by: 'a', dr: "I got caught sitting next to {b} on purpose, and I don't even care. I'll be sitting there again tomorrow." },
    ] },
    { id: 'sm.s6', turns: [
      { by: 'a', say: "Okay, honest question. What's your type?" },
      { by: 'b', say: "Why do you want to know?" },
      { by: 'a', say: "Research." },
      { by: 'b', say: "Research for what?" },
      { by: 'a', say: "For… a friend." },
      { by: 'b', say: "Which friend?" },
      { by: 'a', say: "You don't know them." },
      { by: 'b', say: "I know everyone in this house." },
      { by: 'a', say: "Then you know exactly which friend." },
      { beat: '{b} laughs and throws a cushion at {a}.' },
      { by: 'b', dr: "Nobody asks what your type is for a friend. I think {a} likes me, and I think I'm happy about that." },
    ] },
    { id: 'sm.s7', when: { third: true }, turns: [
      { by: 'c', say: "Are you two going to share that blanket all night, or…" },
      { by: 'a', say: "It's cold!" },
      { by: 'c', say: "It's not cold. It's the warmest night we've had." },
      { by: 'b', say: "I run cold." },
      { by: 'c', say: "You both run cold. Under one blanket. Okay." },
      { beat: '{c} leaves. {a} and {b} do not move the blanket.' },
      { by: 'c', dr: "Everybody's noticed. Everybody. Except, apparently, the two of them." },
    ] },
  ],

  // ── kiss: the first one ─────────────────────────────────────────────
  'story.showmance.kiss.first': [
    { id: 'sk.f1', room: 'bedroom', turns: [
      { beat: 'Bedroom. Lights out. {a} and {b} are on the same bed, talking in whispers.' },
      { by: 'b', say: "Can I ask you something?" },
      { by: 'a', say: "Mm-hm." },
      { by: 'b', say: "Is this a game thing? Us?" },
      { by: 'a', say: "Does it feel like a game thing?" },
      { by: 'b', say: "No." },
      { by: 'a', say: "Then it's not." },
      { beat: 'A long pause. Then {a} kisses {b}.' },
      { by: 'b', say: "...Finally." },
      { by: 'a', say: "Shut up." },
      { by: 'b', say: "You shut up." },
      { by: 'a', dr: "I've been thinking about doing that since {when}. Whatever happens now, I don't regret it." },
    ] },
    { id: 'sk.f2', turns: [
      { by: 'a', say: "Can I tell you something, and you don't freak out?" },
      { by: 'b', say: "That's a terrifying start." },
      { by: 'a', say: "I really want to kiss you right now." },
      { by: 'b', say: "...Oh." },
      { by: 'a', say: "See, that's a freak-out face." },
      { by: 'b', say: "It's not a freak-out face! It's a— I'm processing." },
      { by: 'a', say: "Process faster." },
      { beat: '{b} kisses {a}.' },
      { by: 'b', say: "Processed." },
      { by: 'b', dr: "There are cameras everywhere. Everywhere. I completely forgot about every single one of them." },
    ] },
    { id: 'sk.f3', room: 'backyard', turns: [
      { beat: 'Backyard. {a} and {b} are lying on the grass, looking up.' },
      { by: 'b', say: "Do you think about what happens when this is over?" },
      { by: 'a', say: "Sometimes. Do you?" },
      { by: 'b', say: "More since {when}." },
      { by: 'a', say: "Why since then?" },
      { by: 'b', say: "You know why." },
      { beat: '{a} turns to look at {b}. {b} is already looking.' },
      { by: 'a', say: "Yeah. I know why." },
      { beat: '{a} kisses {b}. Somebody inside switches on the patio light. Neither of them notices.' },
      { by: 'a', dr: "The whole house is going to know by breakfast. I don't care. I really, really don't care." },
    ] },
    { id: 'sk.f4', turns: [
      { by: 'a', say: "Stop looking at me like that." },
      { by: 'b', say: "Like what?" },
      { by: 'a', say: "Like you're going to do something stupid." },
      { by: 'b', say: "What if I am?" },
      { by: 'a', say: "Then do it." },
      { beat: '{b} kisses {a}. Then pulls back, looking slightly shocked.' },
      { by: 'b', say: "That was the stupid thing." },
      { by: 'a', say: "I liked the stupid thing." },
      { by: 'b', say: "Yeah?" },
      { by: 'a', say: "Do it again." },
      { by: 'b', dr: "Everyone told me a showmance is a target. They're right. I know they're right. I just don't care right now." },
    ] },
    { id: 'sk.f5', when: { register: ['shy'] }, turns: [
      { by: 'a', say: "I'm not very good at this." },
      { by: 'b', say: "At what?" },
      { by: 'a', say: "At… saying stuff. Like, the stuff you're supposed to say." },
      { by: 'b', say: "You don't have to say anything." },
      { by: 'a', say: "I kind of want to, though." },
      { by: 'b', say: "Then say it badly. I won't mind." },
      { by: 'a', say: "Okay. I like you. A lot. Since {when}, really. And I've been trying to work out how to—" },
      { beat: '{b} kisses {a}, mid-sentence.' },
      { by: 'b', say: "You were taking too long." },
      { by: 'a', dr: "I had a whole thing planned. I got about halfway. Honestly, it went better than the plan." },
    ] },
    { id: 'sk.f6', room: 'kitchen', turns: [
      { beat: 'Kitchen, three in the morning. {a} and {b} are both pretending to want toast.' },
      { by: 'b', say: "Couldn't sleep?" },
      { by: 'a', say: "Couldn't sleep. You?" },
      { by: 'b', say: "Couldn't sleep." },
      { by: 'a', say: "Weird." },
      { by: 'b', say: "So weird." },
      { beat: 'The toast pops. Nobody reaches for it.' },
      { by: 'a', say: "I wasn't really hungry." },
      { by: 'b', say: "Me neither." },
      { beat: '{a} kisses {b} next to the toaster.' },
      { by: 'b', dr: "Neither of us ate the toast. I haven't been this happy since I walked in here." },
    ] },
  ],

  // ── kiss: a couple who came in together ─────────────────────────────
  'story.showmance.kiss.couple': [
    { id: 'sk.c1', presumes: ['hoh'], room: 'bedroom', turns: [
      { beat: 'The lights are off. {a} checks the door, then slips over to {b}’s bed.' },
      { by: 'b', say: "What are you doing? Somebody's going to see." },
      { by: 'a', say: "Everyone's asleep." },
      { by: 'b', say: "That's what you said last time." },
      { by: 'a', say: "Last time was different. Last time I wasn't going crazy." },
      { by: 'b', say: "You're going crazy?" },
      { by: 'a', say: "I've had to act like I barely know you. All day. Every day. It's killing me." },
      { by: 'b', say: "I know. Me too." },
      { beat: '{a} kisses {b}. Quickly.' },
      { by: 'a', say: "Okay. Okay, I'm going." },
      { by: 'b', say: "Go. Before I stop you." },
      { by: 'a', dr: "Nobody in here knows. We came in together and nobody knows. That kiss was the only real minute I've had all week." },
    ] },
    { id: 'sk.c2', turns: [
      { by: 'b', say: "We said we'd keep it quiet in here." },
      { by: 'a', say: "We are keeping it quiet. Look. Nobody's here." },
      { by: 'b', say: "There are cameras everywhere." },
      { by: 'a', say: "The cameras already know." },
      { by: 'b', say: "That's a good point, actually." },
      { beat: '{a} kisses {b}.' },
      { by: 'b', say: "Okay. One. Then we go back to being strangers." },
      { by: 'a', say: "Strangers who've been together for ages." },
      { by: 'b', say: "Strangers. Go." },
      { by: 'b', dr: "If they find out we came in together, we're done. Both of us. So we're strangers. Strangers who sometimes kiss in the storage room." },
    ] },
    { id: 'sk.c3', presumes: ['hoh'], room: 'storage-room', turns: [
      { beat: 'Storage room. {b} is looking for cereal. {a} comes in and shuts the door.' },
      { by: 'b', say: "No. Absolutely not. Somebody's going to want cereal." },
      { by: 'a', say: "Thirty seconds." },
      { by: 'b', say: "You said thirty seconds yesterday and it was ten minutes." },
      { by: 'a', say: "I've missed you." },
      { by: 'b', say: "I'm right here. I've been right here all day." },
      { by: 'a', say: "Right here pretending you don't know me." },
      { beat: '{b} gives in and kisses {a}.' },
      { by: 'b', say: "Thirty seconds." },
      { by: 'a', dr: "Do you know how hard it is to call the person you love 'mate' in front of everybody? Very. Very hard." },
    ] },
    { id: 'sk.c4', turns: [
      { by: 'a', say: "How are we doing? Honestly." },
      { by: 'b', say: "Honestly? I hate this. I hate pretending." },
      { by: 'a', say: "Me too." },
      { by: 'b', say: "Somebody asked me today if I fancied you. I said no. Out loud. I said no." },
      { by: 'a', say: "...Did you say it convincingly?" },
      { by: 'b', say: "Very convincingly. That's the worst part." },
      { by: 'a', say: "Hey. Come here." },
      { beat: '{a} kisses {b} on the forehead.' },
      { by: 'a', say: "We just have to get far enough. Then we can stop pretending." },
      { by: 'b', dr: "Saying 'no' about {a} out loud was harder than any comp I've played." },
    ] },
    { id: 'sk.c5', room: 'bedroom', turns: [
      { beat: 'Everyone else is asleep. {b} slides over to {a}’s bed.' },
      { by: 'a', say: "We agreed." },
      { by: 'b', say: "Five minutes." },
      { by: 'a', say: "You always say five minutes." },
      { by: 'b', say: "And you always let me." },
      { beat: '{a} kisses {b}.' },
      { by: 'a', say: "Five minutes." },
      { by: 'b', dr: "Everyone thinks {a} and I just met. Pretending I'm not in love with {a} is the hardest part of this game." },
    ] },
  ],

  // ── declare: saying what this is ────────────────────────────────────
  'story.showmance.declare.any': [
    { id: 'sd.1', turns: [
      { by: 'a', say: "Can I tell you something? And you can't laugh." },
      { by: 'b', say: "I'm not going to laugh." },
      { by: 'a', say: "You're already smiling." },
      { by: 'b', say: "That's just my face." },
      { by: 'a', say: "Okay. So. I came in here with a plan. Win comps, keep my head down, don't get attached to anybody. And then {when} happened, and I've been sitting there ever since thinking… I'm in trouble." },
      { beat: 'A long pause.' },
      { by: 'b', say: "What kind of trouble?" },
      { by: 'a', say: "The kind where I don't care about the plan as much as I care about you." },
      { by: 'b', say: "That's the dumbest, sweetest thing anybody's ever said to me." },
      { by: 'a', say: "So is that a yes, or…" },
      { by: 'b', say: "Come here." },
      { by: 'b', dr: "Everybody keeps telling me a showmance is a target. I know. I just don't care right now." },
    ] },
    { id: 'sd.2', when: { late: false }, turns: [
      { by: 'b', say: "So what are we?" },
      { by: 'a', say: "What do you mean?" },
      { by: 'b', say: "You know what I mean. Are we a thing? A game thing? A thing-thing?" },
      { by: 'a', say: "What do you want us to be?" },
      { by: 'b', say: "No, no, you don't get to turn it around. You first." },
      { beat: '{a} takes a breath.' },
      { by: 'a', say: "A thing-thing. I want us to be a thing-thing." },
      { by: 'b', say: "Really?" },
      { by: 'a', say: "Really. Since {when}, honestly." },
      { by: 'b', say: "...Okay. Me too. Thing-thing." },
      { by: 'a', dr: "We just defined the relationship in a house full of microphones. Very romantic. Very public." },
    ] },
    { id: 'sd.3', room: 'bedroom', turns: [
      { beat: 'Bedroom, lights out. {a} and {b} are talking very quietly.' },
      { by: 'b', say: "Can I be really honest?" },
      { by: 'a', say: "Always." },
      { by: 'b', say: "I'm scared of this. Of us. Because if one of us goes, the other one's on their own in here, and I don't know if I can do that." },
      { by: 'a', say: "Hey." },
      { by: 'b', say: "And I know it's a game, and I know it's stupid, and everyone's going to say we're—" },
      { by: 'a', say: "Hey. Look at me." },
      { beat: '{b} looks.' },
      { by: 'a', say: "Whatever happens in here, happens. Out there, it's still us. Okay?" },
      { by: 'b', say: "...Okay." },
      { by: 'a', dr: "Out there, it's still us. I meant that. I don't say stuff like that." },
    ] },
    { id: 'sd.4', turns: [
      { by: 'a', say: "I need to say something and I need you to just let me say it." },
      { by: 'b', say: "Okay." },
      { by: 'a', say: "I like you. Like, really like you. Not 'nice person in a house' like you. Actually like you." },
      { by: 'b', say: "..." },
      { by: 'a', say: "You're not saying anything." },
      { by: 'b', say: "You told me to let you say it!" },
      { by: 'a', say: "I'm done saying it! Now you say something!" },
      { by: 'b', say: "I like you too. I really do." },
      { by: 'a', say: "Okay. Good. Great. I'm going to go lie down." },
      { by: 'b', dr: "{a} said it and then basically ran away. I've never liked anybody more." },
    ] },
    { id: 'sd.5', turns: [
      { by: 'b', say: "I need to know if this is a game thing." },
      { by: 'a', say: "Are you serious?" },
      { by: 'b', say: "I need to know." },
      { by: 'a', say: "...You think I'm playing you?" },
      { by: 'b', say: "I don't know! Everyone plays everyone in here!" },
      { by: 'a', say: "Not me. Not with you." },
      { by: 'b', say: "Promise?" },
      { by: 'a', say: "I promise. You're the one thing in here that isn't a game." },
      { beat: '{b} lets out a breath.' },
      { by: 'b', say: "Okay." },
      { by: 'b', dr: "I believe {a}. That's either the best or worst thing I've done in this house." },
    ] },
    { id: 'sd.6', when: { register: ['fiery', 'competitor'] }, turns: [
      { by: 'a', say: "Okay, I'm just going to say it, because I'm bad at not saying things." },
      { by: 'b', say: "That's very true." },
      { by: 'a', say: "I'm crazy about you. There. I said it. I'm crazy about you and it's ruining my game." },
      { by: 'b', say: "Ruining it?" },
      { by: 'a', say: "Completely! I can't focus! I'm in comps thinking about you! I lost the last one because you were in the crowd!" },
      { by: 'b', say: "That's not true." },
      { by: 'a', say: "It's a little bit true!" },
      { by: 'b', say: "...I'm a little bit crazy about you too." },
      { by: 'a', say: "Yeah?" },
      { by: 'b', say: "Yeah. Now go win something." },
      { by: 'a', dr: "Best day in the house. Worst day for my strategy. Worth it." },
    ] },
  ],

  // ── hiding: keeping it from the house ───────────────────────────────
  'story.showmance.hiding.any': [
    { id: 'sh.1', turns: [
      { by: 'a', say: "New rules." },
      { by: 'b', say: "Here we go." },
      { by: 'a', say: "Separate rooms at night. No saving seats. Thirty seconds between us leaving a room." },
      { by: 'b', say: "Thirty seconds?" },
      { by: 'a', say: "Thirty. I've timed how long people take to notice." },
      { by: 'b', say: "You timed it?" },
      { by: 'a', say: "I timed it." },
      { by: 'b', say: "That's insane." },
      { by: 'a', say: "That's how we last." },
      { by: 'b', dr: "{a} has a spreadsheet in {a.posAdj} head about how to hide me. It's romantic. In a horrible way." },
    ] },
    { id: 'sh.2', turns: [
      { by: 'b', say: "How long do we have to do this?" },
      { by: 'a', say: "Until the numbers are right." },
      { by: 'b', say: "That's not an answer." },
      { by: 'a', say: "It's the only answer I've got." },
      { by: 'b', say: "I don't like not sitting next to you." },
      { by: 'a', say: "I know. I don't like it either." },
      { by: 'b', say: "Then why are we doing it?" },
      { by: 'a', say: "Because two votes that always go together get split up. And I'd rather sit across the room from you than watch you go home." },
      { by: 'b', dr: "{a} is right. I hate that {a} is right." },
    ] },
    { id: 'sh.3', room: 'kitchen', turns: [
      { beat: '{a} walks into the kitchen. {b} is already there. They both stop.' },
      { by: 'a', say: "Oh. Hi." },
      { by: 'b', say: "Hi." },
      { by: 'a', say: "...I'll come back." },
      { by: 'b', say: "You don't have to—" },
      { by: 'a', say: "I'll come back." },
      { beat: '{a} leaves. Thirty seconds later, {a} comes back in.' },
      { by: 'b', say: "That was thirty seconds exactly." },
      { by: 'a', say: "I know. I counted." },
      { by: 'b', dr: "We're so bad at this. We're so, so bad at this." },
    ] },
    { id: 'sh.4', when: { third: true }, turns: [
      { by: 'c', say: "Are you two fighting?" },
      { by: 'a', say: "No. Why?" },
      { by: 'c', say: "You haven't sat together all day." },
      { by: 'b', say: "We don't have to sit together." },
      { by: 'c', say: "You always sit together." },
      { by: 'a', say: "Well, today we're not." },
      { by: 'c', say: "Okay. Weird. But okay." },
      { by: 'c', dr: "They're either fighting, or they're trying very hard to look like they're not together. Both mean something." },
    ] },
    { id: 'sh.5', turns: [
      { by: 'a', say: "Somebody asked me about us today." },
      { by: 'b', say: "What did you say?" },
      { by: 'a', say: "I said we're just friends." },
      { by: 'b', say: "Did they buy it?" },
      { by: 'a', say: "They said 'sure' in that voice." },
      { by: 'b', say: "The 'sure' voice is bad." },
      { by: 'a', say: "The 'sure' voice is really bad." },
      { by: 'b', say: "So we need to be more 'just friends'." },
      { by: 'a', say: "We need to be the most 'just friends' anyone's ever seen." },
      { by: 'a', dr: "We're going to have to be boring. Publicly boring. I don't know if we can do boring." },
    ] },
  ],

  // ── jealous ─────────────────────────────────────────────────────────
  'story.showmance.jealous.any': [
    { id: 'sj.1', when: { third: true }, turns: [
      { by: 'a', say: "You and {c} were up there a long time." },
      { by: 'b', say: "We were talking." },
      { by: 'a', say: "For an hour." },
      { by: 'b', say: "It was game talk." },
      { by: 'a', say: "An hour of game talk. With the door shut." },
      { by: 'b', say: "Are you actually jealous right now?" },
      { by: 'a', say: "I'm not jealous." },
      { by: 'b', say: "You're a little jealous." },
      { by: 'a', say: "I'm asking a normal question in a normal voice." },
      { by: 'b', say: "That is not your normal voice." },
      { by: 'b', dr: "{a} gets jealous when I talk to anyone for more than a minute. It's cute for about a day. We're past the day." },
    ] },
    { id: 'sj.2', turns: [
      { by: 'a', say: "Can I say something without you getting annoyed?" },
      { by: 'b', say: "Probably not, but go on." },
      { by: 'a', say: "You've been different today." },
      { by: 'b', say: "Different how?" },
      { by: 'a', say: "Busy. Talking to everyone. Not talking to me." },
      { by: 'b', say: "I'm playing a game. I have to talk to people." },
      { by: 'a', say: "I know. I just— I missed you today." },
      { by: 'b', say: "...Okay, that's not fair, you can't say it like that." },
      { by: 'a', say: "Like what?" },
      { by: 'b', say: "Like a sad puppy." },
      { by: 'a', dr: "I'm not jealous. I'm just… aware. Very, very aware of who {b} talks to." },
    ] },
    { id: 'sj.3', when: { third: true }, turns: [
      { by: 'c', say: "{b}, come help me with the dinner?" },
      { by: 'b', say: "Sure." },
      { beat: '{b} goes. {a} watches the whole way to the kitchen.' },
      { by: 'a', dr: "{c} has asked {b} for help with something every day this week. Every day. I can count." },
      { beat: 'Later. {a} catches {b} alone.' },
      { by: 'a', say: "So you and {c} are cooking buddies now." },
      { by: 'b', say: "Are you serious?" },
      { by: 'a', say: "I'm just saying." },
      { by: 'b', say: "You're saying something. I'm cutting onions. That's all that's happening." },
      { by: 'b', dr: "It was onions. I cried, because onions. That's the whole story." },
    ] },
    { id: 'sj.4', turns: [
      { by: 'b', say: "Why are you being quiet with me?" },
      { by: 'a', say: "I'm not being quiet." },
      { by: 'b', say: "You've said four words to me today." },
      { by: 'a', say: "Maybe I've got nothing to say." },
      { by: 'b', say: "You always have something to say." },
      { by: 'a', say: "Fine. I saw you laughing with somebody earlier. Really laughing. You don't laugh like that with me any more." },
      { by: 'b', say: "That's not true." },
      { by: 'a', say: "It's a little bit true." },
      { by: 'b', say: "Come here. You're being an idiot." },
      { by: 'a', say: "A jealous idiot?" },
      { by: 'b', say: "The most jealous idiot." },
      { by: 'b', dr: "I'll make {a} laugh like that tonight. On purpose. Then we're even." },
    ] },
    { id: 'sj.5', when: { register: ['fiery'] }, turns: [
      { by: 'a', say: "So that's how it is." },
      { by: 'b', say: "How what is?" },
      { by: 'a', say: "Somebody new pays you some attention and suddenly I don't exist." },
      { by: 'b', say: "That is so unfair." },
      { by: 'a', say: "Is it?" },
      { by: 'b', say: "Yes! I was being nice! People are allowed to be nice to me!" },
      { by: 'a', say: "Not that nice!" },
      { by: 'b', say: "Listen to yourself!" },
      { beat: '{b} walks off. {a} kicks a cushion across the room.' },
      { by: 'a', dr: "Was I a bit much? Maybe. Am I wrong? I don't think I'm wrong." },
    ] },
    { id: 'sj.6', turns: [
      { by: 'a', say: "Can I ask you something and you just answer?" },
      { by: 'b', say: "Sure." },
      { by: 'a', say: "Is there anyone else? In here. That you'd—" },
      { by: 'b', say: "No." },
      { by: 'a', say: "You answered really fast." },
      { by: 'b', say: "Because it's an easy question! No. There's nobody else." },
      { by: 'a', say: "Okay." },
      { by: 'b', say: "Is there anyone else for you?" },
      { by: 'a', say: "No. God, no." },
      { by: 'b', say: "Then we're two idiots asking each other stupid questions." },
      { by: 'a', dr: "I needed to hear it. I don't know why. This house makes you need to hear things." },
    ] },
  ],

  // ── fight ───────────────────────────────────────────────────────────
  'story.showmance.fight.any': [
    { id: 'sg.1', turns: [
      { by: 'b', say: "Can we not do this here?" },
      { by: 'a', say: "Where do you want to do it? The storage room? Again?" },
      { by: 'b', say: "Keep your voice down." },
      { by: 'a', say: "Why? So people don't find out we're not perfect?" },
      { by: 'b', say: "So people don't find out we're anything!" },
      { by: 'a', say: "Is that what this is? You're embarrassed of me?" },
      { by: 'b', say: "I'm not embarrassed! I'm trying to keep us both in the house!" },
      { by: 'a', say: "By pretending I don't exist!" },
      { by: 'b', say: "By being smart!" },
      { beat: '{a} walks out. {b} stands in the empty room.' },
      { by: 'b', dr: "We're on the same side. We're always on the same side. So why does it feel like a war?" },
    ] },
    { id: 'sg.2', turns: [
      { by: 'a', say: "You said you'd talk to me first. Before anything. You promised." },
      { by: 'b', say: "It happened really fast—" },
      { by: 'a', say: "You promised!" },
      { by: 'b', say: "I know I promised! I'm sorry! I didn't have time!" },
      { by: 'a', say: "You had time to talk to everyone else." },
      { by: 'b', say: "That was game. This is us." },
      { by: 'a', say: "There isn't a difference in here! Everything is game!" },
      { by: 'b', say: "Then what are we?" },
      { by: 'a', say: "...I don't know any more." },
      { by: 'a', dr: "I said that to hurt {b}. It worked. I wish it hadn't." },
    ] },
    { id: 'sg.3', room: 'bedroom', turns: [
      { beat: 'Bedroom. {b} is lying facing the wall. {a} sits on the edge of the bed.' },
      { by: 'a', say: "Are you awake?" },
      { by: 'b', say: "No." },
      { by: 'a', say: "Are you still mad?" },
      { by: 'b', say: "Yes." },
      { by: 'a', say: "Can I sit here anyway?" },
      { beat: 'A long pause.' },
      { by: 'b', say: "...Fine." },
      { by: 'a', say: "I'm sorry I shouted." },
      { by: 'b', say: "I'm sorry I made you shout." },
      { by: 'a', say: "Is that a real apology?" },
      { by: 'b', say: "It's half a real apology. Go to sleep." },
      { by: 'a', dr: "It was only half an apology. But from {b}, in this house, half an apology means a lot." },
    ] },
    { id: 'sg.4', turns: [
      { by: 'a', say: "Do you even want this anymore?" },
      { by: 'b', say: "Where's this coming from?" },
      { by: 'a', say: "You barely look at me. You go to bed before me. You sit at the other end of the table." },
      { by: 'b', say: "We agreed to do that! That was your idea!" },
      { by: 'a', say: "To hide it from them! Not from me!" },
      { by: 'b', say: "I'm not hiding anything from you!" },
      { by: 'a', say: "Then why does it feel like you are?" },
      { by: 'b', say: "Because this house is getting in your head!" },
      { by: 'a', say: "Maybe it's getting in yours." },
      { by: 'b', dr: "This is what the house does. It doesn't split you up. It just makes you split yourselves up." },
    ] },
    { id: 'sg.5', turns: [
      { by: 'b', say: "I heard you told people we're 'just friends'." },
      { by: 'a', say: "We agreed to say that." },
      { by: 'b', say: "We agreed to say it. You didn't have to say it like that." },
      { by: 'a', say: "Like what?" },
      { by: 'b', say: "Like you meant it! Like it was easy!" },
      { by: 'a', say: "It's not easy! It's never easy!" },
      { by: 'b', say: "It sounded easy." },
      { by: 'a', say: "Because I'm good at lying! That's my job in here! I lie to everyone!" },
      { by: 'b', say: "...Do you lie to me?" },
      { by: 'a', say: "No. Never you." },
      { by: 'b', dr: "{a} said 'never you' so fast. I want to believe it. I want to believe it so badly." },
    ] },
  ],

  // ── breakup ─────────────────────────────────────────────────────────
  'story.showmance.breakup.any': [
    { id: 'sb.1', turns: [
      { by: 'a', say: "Can we talk?" },
      { by: 'b', say: "Nothing good ever starts with 'can we talk'." },
      { by: 'a', say: "I know." },
      { by: 'b', say: "...Oh." },
      { by: 'a', say: "I think we need to stop. In here. I think it's hurting both of us." },
      { by: 'b', say: "Hurting us how?" },
      { by: 'a', say: "Everyone sees us as one vote. One target. And we keep fighting about stuff that doesn't matter because this place is— it's too much." },
      { by: 'b', say: "So that's it." },
      { by: 'a', say: "In here. That's it in here." },
      { by: 'b', say: "And out there?" },
      { by: 'a', say: "I don't know. I really don't know." },
      { by: 'b', dr: "'I don't know.' Of all the things to say. I'd have preferred a no." },
    ] },
    { id: 'sb.2', turns: [
      { by: 'b', say: "I'm done." },
      { by: 'a', say: "Done with what?" },
      { by: 'b', say: "This. Us. The fighting, the hiding, all of it. I'm done." },
      { by: 'a', say: "You don't mean that." },
      { by: 'b', say: "I've never meant anything more in this house." },
      { by: 'a', say: "Over one fight?" },
      { by: 'b', say: "It's not one fight. It's every fight. It's every day." },
      { beat: '{b} leaves. {a} sits down on the floor.' },
      { by: 'a', dr: "I didn't see it coming. Everybody else probably did. I didn't." },
    ] },
    { id: 'sb.3', room: 'backyard', turns: [
      { beat: 'Backyard. {a} and {b} are sitting at opposite ends of the same lounger.' },
      { by: 'a', say: "This is weird." },
      { by: 'b', say: "It's really weird." },
      { by: 'a', say: "Are we still friends?" },
      { by: 'b', say: "I don't know how to be friends with you." },
      { by: 'a', say: "We were friends before." },
      { by: 'b', say: "For like a day." },
      { by: 'a', say: "It was a good day." },
      { by: 'b', say: "...It was a good day." },
      { by: 'b', dr: "Breaking up with somebody you can't get away from is its own special kind of hell." },
    ] },
    { id: 'sb.4', turns: [
      { by: 'a', say: "I think you're playing me." },
      { by: 'b', say: "What?" },
      { by: 'a', say: "I think you've been playing me. The whole time. For the vote." },
      { by: 'b', say: "You genuinely believe that?" },
      { by: 'a', say: "I don't know what to believe any more." },
      { by: 'b', say: "Then I can't help you. If you don't know by now, I can't help you." },
      { by: 'a', say: "So that's it?" },
      { by: 'b', say: "You ended it. Just now. When you said that." },
      { by: 'b', dr: "Of everything anyone has said to me in this house, that's the one that's going to stay." },
    ] },
    { id: 'sb.5', turns: [
      { by: 'b', say: "I don't want to fight any more." },
      { by: 'a', say: "Me neither." },
      { by: 'b', say: "So maybe we just… stop. Everything. Stop." },
      { by: 'a', say: "Stop us?" },
      { by: 'b', say: "Stop us. Before we really hate each other." },
      { beat: 'A long silence.' },
      { by: 'a', say: "Okay." },
      { by: 'b', say: "Okay?" },
      { by: 'a', say: "I don't want to hate you. So okay." },
      { by: 'a', dr: "That's the saddest 'okay' I've ever said." },
    ] },
  ],

  // ── recaps ──────────────────────────────────────────────────────────
  'recap.showmance.spark.a': [
    { id: 'rms.a1', turns: [{ by: 'a', dr: "{b} and I have been flirting since {when}. Everybody's noticed. I've noticed everybody noticing." }] },
    { id: 'rms.a2', turns: [{ by: 'a', dr: "There's something with {b}. Since {when}. I don't know what it is yet." }] },
    { id: 'rms.a3', turns: [{ by: 'a', dr: "{when}, {b} and I talked for hours. About nothing. I can't stop thinking about it." }] },
  ],
  'recap.showmance.spark.b': [
    { id: 'rms.b1', turns: [{ by: 'b', dr: "{a} has been flirting with me since {when}. And I've been flirting back. Badly." }] },
    { id: 'rms.b2', turns: [{ by: 'b', dr: "Since {when}, {a} sits next to me at every meal. Every single one." }] },
    { id: 'rms.b3', turns: [{ by: 'b', dr: "{when}, {a} and I stayed up talking. I haven't stopped smiling since." }] },
  ],
  'recap.showmance.spark.caption': [
    { id: 'rms.x1', turns: [{ beat: 'Since {when}, {a} and {b} have been inseparable.' }, { by: 'a', dr: "It's nothing. It's fine." }] },
    { id: 'rms.x2', turns: [{ beat: '{when}, {a} and {b} talked late into the night.' }, { by: 'b', dr: "We just get each other." }] },
    { id: 'rms.x3', turns: [{ beat: '{a} and {b} have been flirting since {when}. The house has noticed.' }, { by: 'a', dr: "Is it obvious? It's obvious." }] },
  ],
  'recap.showmance.kiss.a': [
    { id: 'rmk.a1', turns: [{ by: 'a', dr: "{b} and I kissed {when}. So now that's a thing." }] },
    { id: 'rmk.a2', turns: [{ by: 'a', dr: "{when}, I kissed {b}. I don't regret it. Not even a little." }] },
    { id: 'rmk.a3', turns: [{ by: 'a', dr: "Ever since {b} and I kissed {when}, everything's different." }] },
  ],
  'recap.showmance.kiss.b': [
    { id: 'rmk.b1', turns: [{ by: 'b', dr: "{a} kissed me {when}. I kissed back. Obviously." }] },
    { id: 'rmk.b2', turns: [{ by: 'b', dr: "{when}, {a} and I kissed. The whole house knows by now." }] },
    { id: 'rmk.b3', turns: [{ by: 'b', dr: "{a} and I have been together since {when}. Together together." }] },
  ],
  'recap.showmance.kiss.caption': [
    { id: 'rmk.x1', turns: [{ beat: '{when}, {a} and {b} kissed.' }, { by: 'a', dr: "Yeah. That happened." }] },
    { id: 'rmk.x2', turns: [{ beat: 'Since {when}, {a} and {b} have been a couple.' }, { by: 'b', dr: "It's real. I know it's real." }] },
    { id: 'rmk.x3', turns: [{ beat: '{when}, {a} and {b} became a couple.' }, { by: 'a', dr: "Best thing in the house." }] },
  ],
  'recap.showmance.declare.a': [
    { id: 'rmd.a1', turns: [{ by: 'a', dr: "{b} and I made it official {when}. It's real now. Scary real." }] },
    { id: 'rmd.a2', turns: [{ by: 'a', dr: "{when}, I told {b} how I feel. {b} feels the same." }] },
    { id: 'rmd.a3', turns: [{ by: 'a', dr: "Since {when}, {b} and I are a proper couple." }] },
  ],
  'recap.showmance.declare.b': [
    { id: 'rmd.b1', turns: [{ by: 'b', dr: "{a} told me {when} that it's not a game thing. I believe {a}." }] },
    { id: 'rmd.b2', turns: [{ by: 'b', dr: "{when}, {a} and I decided we're together. Properly." }] },
    { id: 'rmd.b3', turns: [{ by: 'b', dr: "{a} and I are a thing. Since {when}. A real thing." }] },
  ],
  'recap.showmance.fight.a': [
    { id: 'rmf.a1', turns: [{ by: 'a', dr: "{b} and I had a fight {when}. A bad one." }] },
    { id: 'rmf.a2', turns: [{ by: 'a', dr: "{when}, {b} and I said some things. Things you can't take back." }] },
    { id: 'rmf.a3', turns: [{ by: 'a', dr: "We fought {when}. We've been off ever since." }] },
  ],
  'recap.showmance.fight.b': [
    { id: 'rmf.b1', turns: [{ by: 'b', dr: "{a} and I had it out {when}. It wasn't pretty." }] },
    { id: 'rmf.b2', turns: [{ by: 'b', dr: "Since {when}, things with {a} have been weird." }] },
    { id: 'rmf.b3', turns: [{ by: 'b', dr: "{when}, {a} and I had our first real fight. It was a big one." }] },
  ],
  'recap.showmance.jealous.a': [
    { id: 'rmj.a1', turns: [{ by: 'a', dr: "{when}, I got jealous. I'm not proud of it." }] },
    { id: 'rmj.a2', turns: [{ by: 'a', dr: "I said some jealous stuff to {b} {when}. Things have been tense since." }] },
    { id: 'rmj.a3', turns: [{ by: 'a', dr: "{b} has been spending a lot of time with other people. I said so {when}. It didn't go well." }] },
  ],
  'recap.showmance.jealous.b': [
    { id: 'rmj.b1', turns: [{ by: 'b', dr: "{a} got jealous {when}. Over nothing. Over a conversation." }] },
    { id: 'rmj.b2', turns: [{ by: 'b', dr: "{when}, {a} accused me of ignoring {a.obj}. I wasn't." }] },
    { id: 'rmj.b3', turns: [{ by: 'b', dr: "{a} has been jealous since {when}. It's exhausting." }] },
  ],
  'recap.showmance.hiding.a': [
    { id: 'rmh.a1', turns: [{ by: 'a', dr: "{b} and I agreed {when} to keep it quiet. For the game." }] },
    { id: 'rmh.a2', turns: [{ by: 'a', dr: "Since {when}, {b} and I have been pretending we're just friends." }] },
    { id: 'rmh.a3', turns: [{ by: 'a', dr: "{when}, we decided to hide it. It's harder than it sounds." }] },
  ],
  'recap.showmance.hiding.b': [
    { id: 'rmh.b1', turns: [{ by: 'b', dr: "{a} wants us to hide it. Since {when}. I'm trying." }] },
    { id: 'rmh.b2', turns: [{ by: 'b', dr: "{when}, {a} made rules. No sitting together. No leaving rooms together." }] },
    { id: 'rmh.b3', turns: [{ by: 'b', dr: "Since {when}, we've been playing strangers in public." }] },
  ],
};
