// ══════════════════════════════════════════════════════════════════════
// bb/story/lines/style.js — every houseguest plays their own game
// ══════════════════════════════════════════════════════════════════════
//
// The user, 2026-10-06: "strategising isn't just creating alliances… there are a lot of types
// of game in Big Brother to build from: from floater to challenge beast to manipulator to
// strategist… I don't see that yet." These scenes show a houseguest playing the way they
// play (bb/story/gametalk.js styleTalkFor picks who, from their archetype, rotating so the
// whole house gets seen). Roles:
//
//   a  the houseguest whose game it is      b  a's closest person in the house
//   c  who the game is about: the strongest player (beast, strategist), somebody a cannot
//      stand (manipulator, provocateur), the HOH or the house's leader (floater), a's
//      ally (loyal), the person a trusts least (perceptive)
//
// The archetype rules hold: only villains, masterminds and schemers manipulate. A provocateur
// (hothead, chaos agent, wildcard) stirs things up in the open and never lies.

export default {
  // ── the floater: no fixed side, always with the numbers ──
  'talk.style.floater': [
    { id: 'gy-sf.1', presumes: ['vote'], room: 'kitchen', turns: [
      { beat: 'The kitchen. {a} drifts over to where {c} is making lunch and starts helping without being asked.' },
      { by: 'c', say: "You're helping?" },
      { by: 'a', say: "I'm a helper. Everybody knows that." },
      { by: 'c', say: "Everybody knows you were helping somebody else yesterday." },
      { by: 'a', say: "Yesterday they needed help. Today you do." },
      { by: 'a', dr: "People call it floating. I call it being where the votes are. Nobody's ever evicted the person standing next to them." },
    ] },
    { id: 'gy-sf.2', room: 'living-room', turns: [
      { beat: 'Living room. {a} is lying on the floor, listening to two conversations at once.' },
      { by: 'b', say: "Whose side are you on this week?" },
      { by: 'a', say: "The winning one." },
      { by: 'b', say: "And which one is that?" },
      { by: 'a', say: "Ask me on Thursday." },
      { by: 'b', dr: "{a} doesn't pick a side until the side is already picked. It's annoying. It's also why {a} is still here." },
    ] },
    { id: 'gy-sf.3', presumes: ['vote'], room: 'hoh-room', turns: [
      { beat: 'HOH room. {a} is on the end of the bed, laughing at {c}’s jokes a little too hard.' },
      { by: 'c', say: "You're up here a lot this week." },
      { by: 'a', say: "Nicest room in the house." },
      { by: 'c', say: "You were up here a lot last week, too. With somebody else." },
      { by: 'a', say: "I like the room. Not the person in it." },
      { by: 'a', dr: "Whoever has the key to this room is my best friend for seven days. It's not personal. It's real estate." },
    ] },
    { id: 'gy-sf.4', turns: [
      { beat: 'The backyard. {a} and {b} are on loungers, watching two groups talk at either end of the yard.' },
      { by: 'b', say: "Which one are you going to?" },
      { by: 'a', say: "Neither. I'll wait and see which one gets bigger." },
      { by: 'b', say: "That's a strategy?" },
      { by: 'a', say: "It's my strategy. I've never been on the block. Have you?" },
      { by: 'b', say: "...Once." },
      { by: 'a', say: "Exactly." },
    ] },
    { id: 'gy-sf.5', room: 'bedroom', turns: [
      { beat: 'Bedroom. {a} is asking {b} about the vote, very casually.' },
      { by: 'a', say: "So which way is everyone going?" },
      { by: 'b', say: "Why? You haven't decided?" },
      { by: 'a', say: "I've decided. I've decided to go with everyone." },
      { by: 'b', say: "That's not deciding. That's waiting." },
      { by: 'a', dr: "I'm not a sheep. Sheep don't know which way the field is going. I always know." },
    ] },
    { id: 'gy-sf.6', room: 'kitchen', turns: [
      { beat: 'The kitchen. Somebody asks {a} straight out who {a} is working with.' },
      { by: 'b', say: "Who are you actually with, in here?" },
      { by: 'a', say: "Everyone." },
      { by: 'b', say: "That's not an answer." },
      { by: 'a', say: "It's the only true one." },
      { by: 'b', dr: "{a} has a little bit of every alliance and the whole of none of them. That's either genius or it's going to blow up." },
    ] },
  ],
  // ── the comp beast: wins, and has to live with it ──
  'talk.style.beast': [
    { id: 'gy-sb.1', turns: [
      { beat: 'The backyard, early. {a} is doing sprints up and down the yard while everyone else is still asleep.' },
      { by: 'b', say: "It's seven in the morning." },
      { by: 'a', say: "The comp doesn't care what time it is." },
      { by: 'b', say: "There isn't a comp today." },
      { by: 'a', say: "There's always a comp coming." },
      { by: 'a', dr: "My game is simple. If I win, I stay. If I keep winning, nobody can touch me. That's the plan." },
    ] },
    { id: 'gy-sb.2', room: 'bedroom', turns: [
      { beat: 'Bedroom. {b} sits down beside {a}, keeping the voice low.' },
      { by: 'b', say: "People are talking about you." },
      { by: 'a', say: "Because I keep winning?" },
      { by: 'b', say: "Because you keep winning." },
      { by: 'a', say: "So what do I do? Lose on purpose?" },
      { by: 'b', say: "Maybe. Once." },
      { by: 'a', dr: "Everyone wants a competitor on their side until the competitor is the biggest threat in the house. Then nobody wants you at all." },
    ] },
    { id: 'gy-sb.3', room: 'kitchen', turns: [
      { beat: 'The kitchen. {a} is eating a huge plate of food. {c} watches from across the counter.' },
      { by: 'c', say: "Carb-loading?" },
      { by: 'a', say: "Always." },
      { by: 'c', say: "You know you can't win everything." },
      { by: 'a', say: "I don't need to win everything. Just the next one." },
      { by: 'c', dr: "Every time {a} wins, the rest of us lose a week. Somebody has to take {a} out before it's too late." },
    ] },
    { id: 'gy-sb.4', turns: [
      { beat: 'The backyard. {a} is practising balancing on the edge of a step, eyes closed.' },
      { by: 'b', say: "What are you doing?" },
      { by: 'a', say: "Practising standing still." },
      { by: 'b', say: "For what?" },
      { by: 'a', say: "Endurance comp. Someone's going to have to stand on something for hours. I want it to be me who's still standing." },
      { by: 'b', dr: "{a} trains for comps that haven't been announced. It's either very smart or very weird." },
    ] },
    { id: 'gy-sb.5', room: 'living-room', turns: [
      { beat: 'Living room. {a} is going through every comp so far, out loud, to {b}.' },
      { by: 'a', say: "{c} is good at puzzles. I'm not. That's where I'm weak." },
      { by: 'b', say: "So you'll lose a puzzle." },
      { by: 'a', say: "I'm not losing anything. I'm going to get better at puzzles." },
      { by: 'b', say: "By when? Thursday?" },
      { by: 'a', dr: "I know exactly where I'm weak. That's why I win." },
    ] },
    { id: 'gy-sb.6', room: 'bedroom', turns: [
      { beat: 'Bedroom, late. {a} is lying awake, staring at the ceiling.' },
      { by: 'b', say: "Can't sleep?" },
      { by: 'a', say: "If I don't win the next one, I think I'm going up." },
      { by: 'b', say: "You don't know that." },
      { by: 'a', say: "Look at me. I'm the obvious name." },
      { by: 'a', dr: "Being good at comps is great right up until the week you lose one. Then you're just a big target with no shield." },
    ] },
  ],
  // ── the manipulator (villains, masterminds, schemers only): a seed, planted ──
  'talk.style.manipulator': [
    { id: 'gy-sm.1', room: 'kitchen', turns: [
      { beat: 'The kitchen. {a} is making tea and talking to {b} as if it’s nothing.' },
      { by: 'a', say: "Has {c} said anything to you about the vote?" },
      { by: 'b', say: "No. Why?" },
      { by: 'a', say: "No reason. Just... {c} was asking a lot of questions about you earlier." },
      { by: 'b', say: "What kind of questions?" },
      { by: 'a', say: "Oh, nothing. Forget I said it." },
      { by: 'a', dr: "I didn't say anything untrue. {c} did ask about the vote. {b} will do the rest." },
    ] },
    { id: 'gy-sm.2', room: 'bedroom', turns: [
      { beat: 'Bedroom. {a} sits close to {b} and lowers their voice.' },
      { by: 'a', say: "I'm only telling you because I trust you." },
      { by: 'b', say: "Okay..." },
      { by: 'a', say: "I don't think {c} is as loyal to you as you think." },
      { by: 'b', say: "Why would you say that?" },
      { by: 'a', say: "Just watch. Watch who {c} talks to when you leave the room." },
      { by: 'a', dr: "You don't tell people what to think. You tell them where to look. Then they find it themselves." },
    ] },
    { id: 'gy-sm.3', presumes: ['vote'], room: 'living-room', turns: [
      { beat: 'Living room. {a} and {b} are on the sofa, talking low.' },
      { by: 'a', say: "I'm not saying {c} is lying to you." },
      { by: 'b', say: "But?" },
      { by: 'a', say: "But ask {c} who was in the bedroom last night. See what the answer is." },
      { by: 'b', say: "...Why? What happened in the bedroom?" },
      { by: 'a', say: "I don't know. That's why you should ask." },
      { beat: '{b} walks away looking worried. {a} picks up a magazine as if nothing happened.' },
      { by: 'a', dr: "{b} came in trusting {c}. {b} is leaving with a question. A question is all I need." },
    ] },
    { id: 'gy-sm.4', turns: [
      { beat: 'The backyard. {a} and {b} are lying on the grass, {a} doing most of the talking.' },
      { by: 'a', say: "You know {c} would put you up in a heartbeat, right?" },
      { by: 'b', say: "{c} told me we were good." },
      { by: 'a', say: "{c} told me the same thing about you. Funny, that." },
      { by: 'b', say: "...What do you mean?" },
      { by: 'a', say: "I don't mean anything. I just think you should be careful." },
      { by: 'a', dr: "I'm not lying. I'm just not telling the whole truth. There's a difference, and it's going to win me this game." },
    ] },
    { id: 'gy-sm.5', room: 'kitchen', turns: [
      { beat: 'The kitchen. {a} is being very nice to {c}, laughing, hugging. {b} watches.' },
      { by: 'b', say: "I thought you couldn't stand {c}." },
      { by: 'a', say: "I can't." },
      { by: 'b', say: "Then why the hugging?" },
      { by: 'a', say: "Because the day {c} goes, {c} won't see it coming. And it won't be my name on it." },
      { by: 'b', dr: "{a} is the friendliest person in the house to the people {a} wants gone. That should scare everybody." },
    ] },
    { id: 'gy-sm.6', presumes: ['vote'], room: 'bedroom', turns: [
      { beat: 'Bedroom, door shut. {a} is talking very quietly, almost to the camera.' },
      { by: 'a', dr: "Every person in this house thinks I'm on their side. That's not an accident. That's weeks of work." },
      { by: 'a', dr: "{c} is next. {c} just doesn't know it, and {c} won't until the votes are read." },
    ] },
  ],
  // ── the strategist: the house, mapped ──
  'talk.style.strategist': [
    { id: 'gy-st.1', room: 'bedroom', turns: [
      { beat: 'Bedroom, door shut. {a} is drawing lines in the air between invisible people while {b} watches.' },
      { by: 'a', say: "These two are a pair. That's a group of three. Those four think they're one group, but they're two." },
      { by: 'b', say: "And where are we?" },
      { by: 'a', say: "In the middle. Which means nobody can count without us." },
      { by: 'b', say: "And {c}?" },
      { by: 'a', say: "{c} is the only one doing the same maths I am. That's the problem." },
      { by: 'a', dr: "This game is numbers. Everyone else is playing feelings. I'm counting." },
    ] },
    { id: 'gy-st.2', presumes: ['vote'], room: 'kitchen', turns: [
      { beat: 'The kitchen. {a} and {b} are washing up, talking in short bursts whenever the room empties.' },
      { by: 'a', say: "Three weeks from now. Who's left?" },
      { by: 'b', say: "How would I know?" },
      { by: 'a', say: "Guess." },
      { by: 'b', say: "...Us. And probably {c}." },
      { by: 'a', say: "And who beats us if {c} is still here?" },
      { by: 'b', say: "{c}." },
      { by: 'a', say: "Then that's the plan." },
      { by: 'a', dr: "You don't play this week. You play three weeks from now. This week just has to get you there." },
    ] },
    { id: 'gy-st.3', room: 'living-room', turns: [
      { beat: 'Living room. {a} is watching the house from the sofa, saying nothing, while {b} talks.' },
      { by: 'b', say: "Are you even listening?" },
      { by: 'a', say: "To you? Yes. To everyone else? Also yes." },
      { by: 'b', say: "What have you heard?" },
      { by: 'a', say: "{c} has had four private conversations today. Four. Nobody has four conversations unless they're counting." },
      { by: 'a', dr: "I watch who talks to who. It tells me more than anything anybody says to me." },
    ] },
    { id: 'gy-st.4', presumes: ['vote'], turns: [
      { beat: 'The backyard. {a} walks laps with {b}, talking strategy between the sound of the pool filter.' },
      { by: 'a', say: "We don't need to be in charge. We just need to never be the target." },
      { by: 'b', say: "How do we manage that?" },
      { by: 'a', say: "By making sure there's always a bigger one. Right now that's {c}." },
      { by: 'b', say: "And when {c} goes?" },
      { by: 'a', say: "Then we find the next one before anyone finds us." },
      { by: 'b', dr: "{a} has a plan for three weeks from now. I don't have a plan for dinner." },
    ] },
    { id: 'gy-st.5', room: 'bedroom', turns: [
      { beat: 'Bedroom. {a} is lying on the bed with both eyes shut, counting on fingers.' },
      { by: 'b', say: "What are you counting?" },
      { by: 'a', say: "Votes. If {c} goes up next week, who saves {c}?" },
      { by: 'b', say: "And?" },
      { by: 'a', say: "Not enough people. That's what I needed to know." },
      { by: 'a', dr: "You can't control who wins HOH. You can control what everybody thinks the obvious move is." },
    ] },
    { id: 'gy-st.6', room: 'kitchen', turns: [
      { beat: 'The kitchen, late. {a} and {b} are the only two up.' },
      { by: 'b', say: "Do you ever stop playing?" },
      { by: 'a', say: "Not in here." },
      { by: 'b', say: "That sounds exhausting." },
      { by: 'a', say: "It is. But the alternative is going home." },
      { by: 'a', dr: "Everybody in here is playing the game. Most of them just haven't noticed yet." },
    ] },
  ],
  // ── the social player: time with everyone ──
  'talk.style.social': [
    { id: 'gy-ss.1', room: 'living-room', turns: [
      { beat: 'Living room. {a} goes from sofa to sofa, five minutes with each person, like a host at a party.' },
      { by: 'b', say: "Do you ever sit still?" },
      { by: 'a', say: "Not when there's someone I haven't talked to today." },
      { by: 'b', say: "Who's left?" },
      { by: 'a', say: "{c}. Hold my drink." },
      { by: 'a', dr: "Nobody votes out somebody they had a nice conversation with this morning. So I have a nice conversation with everybody, every morning." },
    ] },
    { id: 'gy-ss.2', room: 'kitchen', turns: [
      { beat: 'The kitchen. {a} is making everyone’s coffee exactly how they like it. {b} watches.' },
      { by: 'b', say: "You know everybody's order?" },
      { by: 'a', say: "Everybody's order, everybody's birthday, everybody's middle name." },
      { by: 'b', say: "That's terrifying." },
      { by: 'a', say: "That's friendship." },
      { by: 'b', dr: "{a} isn't winning comps. {a} doesn't need to. Half this house would feel bad voting {a} out." },
    ] },
    { id: 'gy-ss.3', turns: [
      { beat: 'The backyard. {a} has organised a game everyone is playing, even {c}.' },
      { by: 'c', say: "I don't even like games." },
      { by: 'a', say: "You like this one. Look at you. You're smiling." },
      { by: 'c', say: "...Barely." },
      { by: 'a', dr: "Get people laughing together and they forget they're competing. For an hour. Sometimes that's all you need." },
    ] },
    { id: 'gy-ss.4', room: 'bedroom', turns: [
      { beat: 'Bedroom. {a} is sitting with {c}, who has had a rough day, and is just listening.' },
      { by: 'c', say: "Why are you being nice to me?" },
      { by: 'a', say: "Because you looked like you needed it." },
      { by: 'c', say: "Nobody else noticed." },
      { by: 'a', say: "I notice." },
      { by: 'a', dr: "It's not a strategy if you mean it. I mean it. It just happens to be a very good strategy too." },
    ] },
    { id: 'gy-ss.5', room: 'living-room', turns: [
      { beat: 'Living room. Three separate groups are sitting apart. {a} sits in the middle of the floor and gets them all talking.' },
      { by: 'a', say: "Okay, everyone. Best thing that happened to you today. Go." },
      { by: 'b', say: "Do we have to?" },
      { by: 'a', say: "You have to." },
      { by: 'b', dr: "Every group in this house thinks {a} is theirs. That's the trick, and I don't think {a} even knows it's a trick." },
    ] },
    { id: 'gy-ss.6', room: 'kitchen', turns: [
      { beat: 'The kitchen. {b} pulls {a} aside.' },
      { by: 'b', say: "You know you can't be friends with everyone forever." },
      { by: 'a', say: "Watch me." },
      { by: 'b', say: "At some point you have to vote somebody out." },
      { by: 'a', say: "And I'll be sad about it. And they'll forgive me. That's the difference." },
      { by: 'b', dr: "{a} genuinely thinks the jury will forgive anything if you're nice enough about it. {a} might be right." },
    ] },
  ],
  // ── the loyal one: keeps their word, checks on their people ──
  'talk.style.loyal': [
    { id: 'gy-sl.1', presumes: ['vote'], room: 'bedroom', turns: [
      { beat: 'Bedroom. {a} checks in on {c} for the third time today.' },
      { by: 'c', say: "I'm fine. You can stop asking." },
      { by: 'a', say: "I'll stop asking when you're safe." },
      { by: 'c', say: "You really mean that, don't you?" },
      { by: 'a', say: "I don't say things I don't mean." },
      { by: 'a', dr: "I told {c} I had {c}’s back. I'm not taking that back. I don't care what it costs me." },
    ] },
    { id: 'gy-sl.2', room: 'kitchen', turns: [
      { beat: 'The kitchen. {b} is trying to talk {a} into a move against {c}.' },
      { by: 'b', say: "It's the smart play." },
      { by: 'a', say: "It's the smart play for you." },
      { by: 'b', say: "It's the smart play for you too." },
      { by: 'a', say: "Then I'll make the dumb play and sleep at night." },
      { by: 'b', dr: "{a} is the most loyal person in this house. It's beautiful. It's also going to get {a} evicted." },
    ] },
    { id: 'gy-sl.3', turns: [
      { beat: 'The backyard. {a} and {c} are side by side on the loungers.' },
      { by: 'c', say: "If it came to it, you'd vote for me to stay. Wouldn't you?" },
      { by: 'a', say: "You don't have to ask." },
      { by: 'c', say: "I know. I just like hearing it." },
      { by: 'a', say: "Then I'll say it every day. I'm with you." },
      { by: 'a', dr: "Some people play this game with numbers. I play it with people. Mine are worth more." },
    ] },
    { id: 'gy-sl.4', room: 'living-room', turns: [
      { beat: 'Living room. Someone is talking about {c} behind {c}’s back. {a} cuts in.' },
      { by: 'a', say: "Say that to {c}, then." },
      { by: 'b', say: "I'm just saying what everyone's thinking." },
      { by: 'a', say: "Not everyone." },
      { beat: 'The conversation dies. {a} goes back to what {a} was doing.' },
      { by: 'a', dr: "I don't let people talk about my people. That's my one rule in here." },
    ] },
    { id: 'gy-sl.5', room: 'bedroom', turns: [
      { beat: 'Bedroom, late. {a} is lying awake.' },
      { by: 'b', say: "What's wrong?" },
      { by: 'a', say: "Somebody asked me to turn on {c} today." },
      { by: 'b', say: "And?" },
      { by: 'a', say: "And I said no. And now I'm wondering how long I can keep saying no." },
      { by: 'a', dr: "Loyalty is easy in week one. It gets heavier every week after that." },
    ] },
    { id: 'gy-sl.6', room: 'kitchen', turns: [
      { beat: 'The kitchen. {a} saves {c} a plate before anybody else can eat.' },
      { by: 'c', say: "You saved me food?" },
      { by: 'a', say: "Always." },
      { by: 'c', dr: "In a house where everyone's looking for the angle, {a} doesn't have one. That's rarer than winning HOH." },
    ] },
  ],
  // ── the underdog: counted out, still here ──
  'talk.style.underdog': [
    { id: 'gy-su.1', presumes: ['vote'], room: 'bedroom', turns: [
      { beat: 'Bedroom. {a} is lying on the bed, listening to people plan in the next room without {a}.' },
      { by: 'b', say: "Doesn't it bother you? They never include you." },
      { by: 'a', say: "It used to." },
      { by: 'b', say: "And now?" },
      { by: 'a', say: "Now I think it's the reason I'm still here." },
      { by: 'a', dr: "Nobody's counting me. That's fine. I'm counting all of them." },
    ] },
    { id: 'gy-su.2', presumes: ['vote'], turns: [
      { beat: 'The backyard. {a} is on their own on the steps. {b} sits down.' },
      { by: 'b', say: "You've survived more weeks than anyone expected." },
      { by: 'a', say: "Including me." },
      { by: 'b', say: "How?" },
      { by: 'a', say: "Every week somebody bigger than me is a threat. I just keep being smaller." },
      { by: 'a', dr: "I was supposed to go first. I keep not going. Eventually people are going to have to take me seriously, and I'd rather they didn't." },
    ] },
    { id: 'gy-su.3', presumes: ['vote'], room: 'kitchen', turns: [
      { beat: 'The kitchen. {c} says, half joking, that {a} is lucky to still be here.' },
      { by: 'c', say: "You know you're lucky, right?" },
      { by: 'a', say: "Am I?" },
      { by: 'c', say: "Nobody thought you'd last this long." },
      { by: 'a', say: "Nobody's evicted me either." },
      { by: 'a', dr: "Everyone thinks I'm lucky. Luck doesn't last this long. Something else does." },
    ] },
    { id: 'gy-su.4', room: 'living-room', turns: [
      { beat: 'Living room. {a} is quietly watching an argument, saying nothing.' },
      { by: 'b', say: "You're not getting involved?" },
      { by: 'a', say: "Why would I? Every fight in this house is two people who aren't me." },
      { by: 'a', dr: "Let the big players knock each other out. I'll be here when they're done." },
    ] },
    { id: 'gy-su.5', presumes: ['vote'], room: 'bedroom', turns: [
      { beat: 'Bedroom, late. {a} and {b} are whispering.' },
      { by: 'a', say: "If I win one comp, just one, everything changes." },
      { by: 'b', say: "Then win one." },
      { by: 'a', say: "I'm trying. I'm getting closer every week." },
      { by: 'b', say: "You came second last time." },
      { by: 'a', say: "Second is just first with bad luck." },
      { by: 'b', dr: "{a} has been at the bottom since day one and hasn't stopped fighting once. I'd love to see {a} win something." },
    ] },
    { id: 'gy-su.6', room: 'kitchen', turns: [
      { beat: 'The kitchen. {a} overhears somebody say {a} would be easy to beat at the end.' },
      { beat: '{a} keeps stirring the pot on the stove and says nothing.' },
      { by: 'a', dr: "They want to take me to the end because they think I can't win. Good. Take me. Let's see." },
    ] },
  ],
  // ── the provocateur (hothead, chaos agent, wildcard): stirs it up in the open ──
  'talk.style.provocateur': [
    { id: 'gy-sp.1', room: 'kitchen', turns: [
      { beat: 'The kitchen, full. {a} decides to say out loud what everyone has been whispering.' },
      { by: 'a', say: "So are we all just going to pretend {c} isn't running this house?" },
      { by: 'c', say: "Excuse me?" },
      { by: 'a', say: "You heard me. Everyone's thinking it. I'm saying it." },
      { beat: 'Nobody moves. Somebody puts a spoon down very quietly.' },
      { by: 'a', dr: "Everybody in here whispers. I don't whisper. If I think it, I say it, and let's see who flinches." },
    ] },
    { id: 'gy-sp.2', room: 'living-room', turns: [
      { beat: 'Living room. {a} is bored, which is never good news.' },
      { by: 'b', say: "What are you thinking?" },
      { by: 'a', say: "I'm thinking this house is too quiet." },
      { by: 'b', say: "Please don't." },
      { by: 'a', say: "Too late. I've had an idea." },
      { by: 'b', dr: "When {a} gets bored, somebody's week gets ruined. I just hope it's not mine." },
    ] },
    { id: 'gy-sp.3', turns: [
      { beat: 'The backyard. {a} walks straight up to {c} in front of everyone.' },
      { by: 'a', say: "Are you putting me up if you win HOH?" },
      { by: 'c', say: "...Why would you ask me that out here?" },
      { by: 'a', say: "Because I want everybody to hear the answer." },
      { by: 'c', say: "I'm not doing this right now." },
      { by: 'a', say: "That's a yes, then." },
      { by: 'a', dr: "Some people play this game in the shadows. I'd rather turn the lights on." },
    ] },
    { id: 'gy-sp.4', room: 'kitchen', turns: [
      { beat: 'The kitchen. {a} slams a cupboard. {b} winces.' },
      { by: 'b', say: "Breathe." },
      { by: 'a', say: "I'm breathing. Loudly." },
      { by: 'b', say: "You can't blow up at {c}. Not this week." },
      { by: 'a', say: "Why not?" },
      { by: 'b', say: "Because you're the one who'll look bad." },
      { by: 'a', dr: "I know. I know I should stay calm. I'm working on it. I'm not working very hard." },
    ] },
    { id: 'gy-sp.5', room: 'living-room', turns: [
      { beat: 'Living room. {a} announces a plan nobody asked for.' },
      { by: 'a', say: "New rule. Everyone says who they're voting for. Right now. Out loud." },
      { by: 'b', say: "That's not how this works." },
      { by: 'a', say: "Why not? What's everyone hiding?" },
      { beat: 'Nobody answers. {a} looks delighted.' },
      { by: 'b', dr: "{a} doesn't care about having a plan. {a} cares about making everyone else's plan fall apart." },
    ] },
    { id: 'gy-sp.6', room: 'bedroom', turns: [
      { beat: 'Bedroom. {a} is lying on the bed, grinning at the ceiling.' },
      { by: 'b', say: "What did you do?" },
      { by: 'a', say: "Nothing. Yet." },
      { by: 'a', dr: "Nobody knows what I'm going to do next. Including me. That's my best weapon." },
    ] },
  ],
  // ── the perceptive one: reads the room ──
  'talk.style.perceptive': [
    { id: 'gy-sr.1', room: 'living-room', turns: [
      { beat: 'Living room. {a} is watching {c} across the room, saying nothing.' },
      { by: 'b', say: "What are you looking at?" },
      { by: 'a', say: "{c} just looked at the door three times in a minute." },
      { by: 'b', say: "So?" },
      { by: 'a', say: "So {c} is waiting for somebody. And {c} doesn't want anyone to know who." },
      { by: 'a', dr: "People think the game happens in the conversations. It happens in the bits in between." },
    ] },
    { id: 'gy-sr.2', presumes: ['vote'], room: 'kitchen', turns: [
      { beat: 'The kitchen. {a} leans in to {b}.' },
      { by: 'a', say: "Did you notice who {c} sat next to at dinner?" },
      { by: 'b', say: "No. Should I have?" },
      { by: 'a', say: "Same person as last night. And the night before." },
      { by: 'b', say: "Maybe they're friends." },
      { by: 'a', say: "Maybe. Or maybe they're more than that, game-wise." },
      { by: 'a', dr: "Nobody announces their alliances. But everybody sits with them." },
    ] },
    { id: 'gy-sr.3', room: 'bedroom', turns: [
      { beat: 'Bedroom. {a} is explaining something to {b}, quietly.' },
      { by: 'a', say: "{c} smiled at me today. A real smile." },
      { by: 'b', say: "That's nice." },
      { by: 'a', say: "It's not nice. {c} never smiles at me. Something's changed." },
      { by: 'b', say: "Maybe {c} just likes you now." },
      { by: 'a', dr: "When somebody who doesn't like you suddenly does, they need something. I'd like to know what." },
    ] },
    { id: 'gy-sr.4', turns: [
      { beat: 'The backyard. {a} sits down beside {b}.' },
      { by: 'a', say: "The house is about to flip." },
      { by: 'b', say: "How do you know?" },
      { by: 'a', say: "Everybody stopped talking about the vote. That only happens when it's already been decided somewhere I wasn't." },
      { by: 'b', say: "So what do we do?" },
      { by: 'b', dr: "{a} reads this house like a book. I just hope I'm not on the next page." },
    ] },
    { id: 'gy-sr.5', presumes: ['vote'], room: 'living-room', turns: [
      { beat: 'Living room. {c} tells a story. {a} listens very carefully.' },
      { beat: 'Everyone laughs at the end. {a} smiles, a beat late.' },
      { by: 'a', dr: "That's the third version of that story I've heard. The details keep changing. People who are telling the truth don't need to change the details." },
    ] },
    { id: 'gy-sr.6', room: 'kitchen', turns: [
      { beat: 'The kitchen. {b} asks {a} how {a} always seems to know things first.' },
      { by: 'b', say: "How do you always know?" },
      { by: 'a', say: "I listen." },
      { by: 'b', say: "We all listen." },
      { by: 'a', say: "No. You all wait for your turn to talk." },
      { by: 'b', dr: "{a} said that like it was nothing. It was the most useful thing anyone's said to me in here." },
    ] },
  ],
  // ── the goat: carried, and maybe that's fine ──
  'talk.style.goat': [
    { id: 'gy-sg.1', room: 'kitchen', turns: [
      { beat: 'The kitchen. {a} is happily eating while a strategy meeting happens around {a}.' },
      { by: 'b', say: "Are you listening to this?" },
      { by: 'a', say: "You'll tell me who to vote for." },
      { by: 'b', say: "That's... true, actually." },
      { by: 'b', dr: "Everybody wants to sit next to {a} at the end. Which means everybody keeps {a} around. Which might be the smartest game in the house." },
    ] },
    { id: 'gy-sg.2', room: 'living-room', turns: [
      { beat: 'Living room. {a} is asked a straight question about their game.' },
      { by: 'c', say: "What's your strategy?" },
      { by: 'a', say: "Be nice. Don't win anything. See what happens." },
      { by: 'c', say: "That's not a strategy." },
      { by: 'a', say: "I'm still here, aren't I?" },
      { by: 'a', dr: "People think I don't know what they think of me. I know. I'm fine with it. They keep me." },
    ] },
    { id: 'gy-sg.3', room: 'bedroom', turns: [
      { beat: 'Bedroom. {b} tells {a} what the house says about {a}.' },
      { by: 'b', say: "People think you're the easiest person to beat at the end." },
      { by: 'a', say: "Good." },
      { by: 'b', say: "Good?" },
      { by: 'a', say: "Nobody evicts the person they want to beat." },
      { by: 'b', say: "You've actually thought about this." },
      { by: 'a', dr: "Let them think I'm easy. Easy people make it to finale night." },
    ] },
    { id: 'gy-sg.4', turns: [
      { beat: 'The backyard. {a} is sunbathing while the house argues indoors.' },
      { by: 'b', say: "There's a huge fight going on inside." },
      { by: 'a', say: "Is it about me?" },
      { by: 'b', say: "No." },
      { by: 'a', say: "Then I'll stay out here." },
      { by: 'a', dr: "I don't need to be in every fight. I need to be in the final chair." },
    ] },
    { id: 'gy-sg.5', presumes: ['vote'], room: 'kitchen', turns: [
      { beat: 'The kitchen. {c} jokes that {a} has done nothing all season.' },
      { by: 'c', say: "What have you actually done in here?" },
      { by: 'a', say: "Survived." },
      { by: 'c', say: "That's not a move." },
      { by: 'a', say: "It's the only move that matters." },
    ] },
    { id: 'gy-sg.6', room: 'bedroom', turns: [
      { beat: 'Bedroom, late. {a} lies awake.' },
      { beat: 'Somebody across the room is whispering about the vote. {a} turns over and pretends to be asleep.' },
      { by: 'a', dr: "Sometimes I wonder if I'm being carried. Then I think: who cares, as long as I'm being carried to the end." },
    ] },
  ],
};
